### ISSUE TITLE
preview enabled conditionally on display space

### ISSUE THREAD

**Issue by teto** [ibhagwan/fzf-lua#1002]
### Info

- Operating System: nixos
- Shell: zsh
- Terminal: kitty
- `nvim --version`: nightly
- `fzf --version`: 0.45

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
	local fzf_history_dir = vim.fn.expand('~/.local/share/fzf-history')
	fzf_lua.setup({
		commands = { sort_lastused = true },
		-- [...]
		fzf_opts = {
			-- [...]
			['--history'] = fzf_history_dir,
			-- to get the prompt at the top
			['--layout'] = 'reverse',
		},
		winopts = {
			preview = {
				-- default = 'builtin'
				hidden = 'hidden',
			},
			layout = 'flex'
		},
	})
fzf_lua.register_ui_select()

```
</details>

### Description 
I love the code_action preview, it's great thank you for that ! 
I often find myself with narrow windows though, in which case I would like to autoremove the preview to see just the listed coactions. Is that doable ? 

Right now I can press F4 to toggle the preview when it takes the space but I would like it to be automatic. 
Ideally I would like to do so without rebinding `gA` which is a neovim binding.

**Comment by ibhagwan** [comment]
Yes, it’s possible, take a look at #1000 and #755, if you set `previewer=false` on the dynamic options it will overwrite the preview setting from `lsp.code_actions`.

Read this to understand dynamic options for ui.select:
https://github.com/ibhagwan/fzf-lua/wiki#ui-select-auto-size
