### ISSUE TITLE
`git_stage_unstage` doesn't stage or unstage

### ISSUE THREAD

**Issue by heygarrett** [ibhagwan/fzf-lua#1004]
### Info

- Operating System: macOS 14.2.1 (23C71)
- Shell: fish, version 3.7.0
- Terminal: wezterm 20230712-072601-f4abf8fd
- `nvim --version`:  

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

- `fzf --version`: 0.45.0 (brew)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
return {
	"https://github.com/ibhagwan/fzf-lua",
	config = function()
		local fzf_lua = require("fzf-lua")
		local actions = require("fzf-lua.actions")

		vim.api.nvim_create_user_command(
			"Status",
			function() fzf_lua.git_status() end,
			{ desc = "fzf-lua picker: git status" }
		)

		fzf_lua.setup({
			fzf_opts = {
				["--cycle"] = "",
			},
			winopts = {
				preview = {
					layout = "vertical",
					vertical = "down:75%",
				},
			},
			git = {
				status = {
					cmd = "git status --short",
					actions = {
						["right"] = false,
						["left"] = false,
						["tab"] = {
							fn = actions.git_stage_unstage,
							reload = true,
						},
					},
				},
			},
		})
	end,
}
```
</details>

### Description 

I've noticed recently that using `git_stage_unstage` has stopped working. I tried changing it to a different keymap, but no luck. I also tried re-enabling `right` and `left` default keymaps and confirmed `git_stage` and `git_unstage` still work as expected.

I struggled to figure out how to customize the minimal init, so apologies for not being able to reproduce the issue that way.

**Comment by ibhagwan** [comment]
@heygarrett, correct, oversight of a recent PR, should work after https://github.com/ibhagwan/fzf-lua/commit/f021b287bf095f20cb5062fc9486dd3243ae220c.

**Comment by heygarrett** [comment]
Yep! It's work now. Thanks!
