### ISSUE TITLE
grep empty string not exactly fzf.vim rg command

### ISSUE THREAD

**Issue by RaulCote** [ibhagwan/fzf-lua#1005]
### Info

- Operating System: MacOS Ventura 13.5
- Shell: zsh
- Terminal: iTerm2
- `nvim --version`: 0.9.1
- `fzf --version`: 0.44.1

### Description 

First congrats for this wonderful plugin, it saves me day to day. By reading the wiki I decided a long ago to add the following keymap to my config as it's suppossed to be the replacement for fzf.vim Rg command.

`vim.keymap.set('n', '<leader>rg', [[:lua require('fzf-lua').grep({ search = "" })<CR>]], { noremap = true, silent = true })`

While on medium size repos it works good I'm noticing it's indexing files slower and slower as the apps grows bigger and bigger. It takes even up to 4 seconds or 5 seconds to index everything and finish the Rg search while the proper fzf.vim Rg search is almost instant. As you can notice on the videos below the fzf loading icon is showing for a while (this happens on every search) but I almost don't see it on fzf.vim. Just wanted to give a heads up as I don't think is exactly the right replacement for Rg I guess.

fzf-lua gif:

https://github.com/ibhagwan/fzf-lua/assets/42467898/068365aa-5bbb-47d5-8a19-c009a8468df0

fzf-vim gif:

https://github.com/ibhagwan/fzf-lua/assets/42467898/a70d9537-7917-43e4-a2cc-b164178dc549

**Comment by ibhagwan** [comment]
Btw, not sure if you’ve noticed you can also recreate fzf.vim’s commands with `:FzfLua setup_fzfvim_cmds`.

**Comment by RaulCote** [comment]
Excellent, the git_icons=false and file_icons=false made the trick. Somehow even if I don't have installed the web devicons dependency it seems to make some work. Without the icons performance is the same as the regular fzf Rg.

Thank you very much for your fast responses.

**Comment by ibhagwan** [comment]
> Somehow even if I don't have installed the web devicons dependency it seems to make some work

That the git_icons at work, try it on a small repo, change a file and you’ll see the letter `M` next to it - that requires processing.

> Thank you very much for your fast responses.

Your’re welcome and ty for your kind words!
