### ISSUE TITLE
diag_source option not working

### ISSUE THREAD

**Issue by santhosh-tekuri** [ibhagwan/fzf-lua#1006]
by default`fzf.diagnostics_document` shows the source file path. 

I am trying to remove source file path as below:

```lua
vim.keymap.set('n', ' d', function() fzf.diagnostics_document({diag_source=false}) end, { desc = "Open diagnostic picker" })
```

but it is still showing the source file path

**Comment by ibhagwan** [comment]
> by defaultfzf.diagnostics_document shows the source file path.

Diag source is for displaying the name of the originating LSP server not for the source file path, it’s actually off by default, you can see the difference if you run `:FzfLua diagnostics_workspace diag_source=true`.

If you wish to hide the file paths use `--delimiter` and `--with-nth` in `fzf_opts`, search the issues and man fzf to understand how it works and how to use it.

**Comment by santhosh-tekuri** [comment]
got it. thanks
