### ISSUE TITLE
After opening nvim first jump from grep ignores the line

### ISSUE THREAD

**Issue by kapral18** [ibhagwan/fzf-lua#1010]
### Info

- Operating System: 14.2.1
- Shell: fish
- Terminal: Iterm2
- `nvim --version`:
```sh
NVIM v0.10.0-dev-2124+g11e8e1462-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```
- `fzf --version`: 0.45.0 (brew)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>
<a href="https://github.com/kapral18/config.nvim/blob/5a4bd082e5f9a935555db61e6e4f9b7904ae7b43/lua/plugins/fzf.lua#L323" rel="nofollow noopener">config</a>
</details>

### Description 

When I start nvim the first live grep jump always misses the line and instead just opens at the beginning of the file. The subsequent ones work fine. I tried with mini.sh cannot reproduce there though.

**Comment by ibhagwan** [comment]
You’re probably missing `--line-number` in your custom rg_opts, make sure the command includes both `--line-number --column`, that way fzf-lua knows where to go.

**Comment by kapral18** [comment]
@ibhagwan no it's there https://github.com/kapral18/config.nvim/blob/5a4bd082e5f9a935555db61e6e4f9b7904ae7b43/lua/plugins/fzf.lua#L60

**Comment by ibhagwan** [comment]
> When I start nvim the first live grep jump always misses the line and instead just opens at the beginning of the file. The subsequent ones work fine. I tried with mini.sh cannot reproduce there though.

Now that I read this again, if this just happens the first time and not with `mini.sh` this would most likely point out to an issue specific to your config.

My bet would be either an autocmd or another plug-in (that creates an autocmd), the only way to solve this is by commenting out parts of your config until you narrow it down to the offending section.

Most likely this isn’t an fzf-lua issue.
