### ISSUE TITLE
Highlights of character matches get reset when matched twice

### ISSUE THREAD

**Issue by jbarap** [ibhagwan/fzf-lua#1012]
### Info

- Operating System: Pop!_OS 22.04 LTS
- Shell: zsh
- Terminal: kitty
- `nvim --version`: v0.10.0-dev-2133+g5a8fe0769
- `fzf --version`: 0.29 (devel)

- [x] The issue is reproducible with `mini.sh`

</details>

### Description

When typing a word twice, the characters matched in the second word will clear the matches from the first one.

To reproduce:
1. Go to the main neovim repo
2. Run `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"`
3. Enter find files with `<C-p>`
4. Type "funcs" into the prompt. The first two files will be the correctly matched files `funcs.h` and `funcs.c`, with only the "funcs' characters highlighted as matches.
![image](https://github.com/ibhagwan/fzf-lua/assets/57547764/db465595-206f-4a1f-a91d-ec3980db2830)

6. Type an additional " funcs", such that the full prompt now reads "funcs funcs". The order of the files won't change, but now all the highlights of the matched characters will disappear. 
![image](https://github.com/ibhagwan/fzf-lua/assets/57547764/4e348d22-3231-4b81-807b-2d3f8837cab2)

The behavior doesn't appear to be the same with just the fzf cli:
![image](https://github.com/ibhagwan/fzf-lua/assets/57547764/0ba645a0-8955-4f73-b941-a14eb1b01eab)

Great job with the plugin btw.

**Comment by ibhagwan** [comment]
This is an upstream bug, apparently when ansi colors are used in the entries it bugs out the second match.

As a workaround you can disable coloring until this gets solved upstream:
```lua
:FzfLua files color_icons=false
```
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/2e32ecb3-6adb-4d5f-88e6-2f9bc75683cd)

**Comment by jbarap** [comment]
Huh, interesting. Thank you for the quick response!

**Comment by ibhagwan** [comment]
> Huh, interesting. Thank you for the quick response!

Interesting bug, this only happens **to entries that contain an ansi color escape sequence**.

Run this in the shell:
```sh
echo "\x1b[0;34mblue\x1b[0m\n\x1b[0;34mblue\x1b[0m\n\x1b[0;34mblue\x1b[0m" | fzf --ansi
```
Now, input `bl bl` and the match is cleared:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/02666866-cd15-47aa-a39d-c440dfdf04ec)

Now run this (last entry isn't color coded):
```sh
echo "\x1b[0;34mblue\x1b[0m\n\x1b[0;34mblue\x1b[0m\n\x1b[0;34mblue\x1b[0m\nblue" | fzf --ansi
```

If you input `bl bl` again, the entries that have an ansi escape sequence have the bug, but the clear entry does not:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/672d97ff-8ca6-45a7-99f0-a1b3273c768a)

**Comment by ibhagwan** [comment]
Reported upstream: https://github.com/junegunn/fzf/issues/3596

**Comment by jbarap** [comment]
Thanks! I was just looking for an issue upstream that mentioned something about this.

**Comment by ibhagwan** [comment]
> Thanks! I was just looking for an issue upstream that mentioned something about this.

You're obviously onto some serious edge case here :-)

**Comment by ibhagwan** [comment]
@jbarap, fixed on upstream master via https://github.com/junegunn/fzf/commit/2a8b65e105ec1a1a9d4cecf947b7267f04453b7c, closing.
