### ISSUE TITLE
Add left padding to `vim.ui.select` index prefix

### ISSUE THREAD

**Issue by towry** [ibhagwan/fzf-lua#1013]
I have searched in the issues, no similar issue found.

### Description 

Using fzf-lua as vim.ui.select backend, when the items is greater than 9, the right content is not well aligned because the index prefix, it would be better if:

1. the index number is left padding so the index prefix are all width equal.
2. or, add option to disable the index prefix?

<img width="357" alt="截屏2024-01-24 11 11 14" src="https://github.com/ibhagwan/fzf-lua/assets/8279858/5cfd46bc-1f1f-4509-b957-e38f4791b3f5">

**Comment by ibhagwan** [comment]
> or, add option to disable the index prefix?

You can already do that with `--with-nth` and a dot `--delimiter` (in `fzf_opts`).

**Comment by towry** [comment]
Isn't those two options prevent fuzzy matching in the content instead of hiding the index prefix?

> Using fzf-lua as vim.ui.select backend, when the items is greater than 9, the right content is not well aligned because the index prefix, it would be better if:

**The issue** is right content is not well aligned, so I need to 
1. left padding index prefix, for example, if the max index is 99, the index `1..9` should be left padding one space.
2. or disable the index prefix, meaning hide it.

Does those two option can achieve this? I searched the `:help` and `man fzf`, a bit confused.

**Comment by ibhagwan** [comment]
> Isn't those two options prevent fuzzy matching in the content instead of hiding the index prefix?

`--nth` prevents fuzzy matching, `--with-nth` hides.

> The issue is right content is not well aligned, so I need to

That’s a personal preference, some want the numbers to be padded and some wouldn’t, I would prefer to avoid her another customization option nobody but a single user uses and can only be found in the issues.

> or disable the index prefix, meaning hide it.

Set delimiter to dot, and use `--with-nth=2..`, this is used to hide fields in many different pickers, take a look at  #762 for example.

**Comment by towry** [comment]
Hi, thanks for quick response, now the results is looks like this:

<img width="354" alt="截屏2024-01-24 14 00 59" src="https://github.com/ibhagwan/fzf-lua/assets/8279858/e79c84d4-70da-4a65-9f72-904813279425">

the code:

```lua
    fzflua.register_ui_select({
      winopts = {
        fullscreen = false,
        height = 0.6,
        width = 0.7,
      },
      fzf_opts = {
        ['--with-nth'] = '2..',
        ['--delimiter'] = '.',
      },
    })
```

**Comment by ibhagwan** [comment]
> Hi, thanks for the quick response, now the result is like this:

Probably due to the color coding ansi sequence, try different fields, you can try `..-1` or `3..`, you’ll figure it out.

**Comment by ibhagwan** [comment]
If this doesn’t work you can also try with space delimiter `[ ]`, play around with it, imagine the string is split by the delimiter and you’re selecting which parts of the string to display.

**Comment by towry** [comment]
<img width="221" alt="截屏2024-01-24 14 20 24" src="https://github.com/ibhagwan/fzf-lua/assets/8279858/1b68a08b-8b97-4072-bba9-c4c47da5c568">

I modified fzf-lua source code at https://github.com/ibhagwan/fzf-lua/blob/36195a230246fc44e8144ee0b454fc022ac5326b/lua/fzf-lua/providers/ui_select.lua#L85, removed `utils.ansi_codes.magenta`

with `with-nth` set to `3..`, but even if i hide the dot, the right content will still be not well aligned.

even if those options work, it will affect all `vim.ui.select` pickers. the best solution I think is left padding the index prefix.

**Comment by towry** [comment]
Ok, with with-nth options, the best i can achieve is this:

<img width="525" alt="截屏2024-01-24 14 24 52" src="https://github.com/ibhagwan/fzf-lua/assets/8279858/9d1b4dbe-9312-4c9f-b866-73fe8d838d53">

code:

```lua
    fzflua.register_ui_select({
      winopts = {
        fullscreen = false,
        height = 0.6,
        width = 0.7,
      },
      fzf_opts = {
        ['--ansi'] = '',
        ['--info'] = 'inline',
        ['--with-nth'] = '-100..',
        ['--delimiter'] = ' ',
      },
    })
```

**Comment by ibhagwan** [comment]
I was in bed when I replied to you so couldn’t test this stuff, fzf delimiter is a regex so you need to escape the dot as it’s a regex special character use it like this:
```lua
  fzf_opts={
    ["--delimiter"] = "[\\.]",
    ["--with-nth"] = "2.."
  }
```

Which will result in the index perfectly hidden:
![IMG_1836](https://github.com/ibhagwan/fzf-lua/assets/59988195/4d20097f-186a-42d2-b372-64901d4b975e)

**Comment by towry** [comment]
Thanks for your solution, it works great, much appreciated!

**Comment by ibhagwan** [comment]
> Thanks for your solution, it works great, much appreciated!

You're welcome @towry!

**Comment by towry** [comment]
Just want to add config that I think works very well, the previous config sometimes breaks the UI:

```
    fzflua.register_ui_select({
      winopts = {
        fullscreen = false,
        height = 0.6,
        width = 0.75,
      },
      fzf_opts = {
        ['--delimiter'] = '[BEGIN{FS="."}]',
        ['--with-nth'] = '2..',
      },
    })
```

![截屏2024-03-22 09 02 44](https://github.com/ibhagwan/fzf-lua/assets/8279858/e9a5db1b-fd35-4c1e-8878-fd093eded4fc)
![截屏2024-03-22 09 01 17](https://github.com/ibhagwan/fzf-lua/assets/8279858/edf84118-a090-4779-8d80-88364848b85f)

**Comment by ibhagwan** [comment]
Looks great @towry! Out of curiosity and being lazy to google or `man awk`… how is `BEGIN{FS="."}` different as a delimiter?

**Comment by towry** [comment]
My mistake, it seems make no difference 😂
