### ISSUE TITLE
`live_grep` leaves .git/index.lock file when a search in progress is canceled

### ISSUE THREAD

**Issue by mgnsk** [ibhagwan/fzf-lua#1015]
### Info

- Operating System: Arch Linux
- Shell: fish
- Terminal: foot
- `nvim --version`:
```
NVIM v0.10.0-dev-2191+g4e59422e1
Build type: RelWithDebInfo
LuaJIT 2.1.1706032906
Run "nvim -V1 -v" for more info
```
- `fzf --version`: 0.45.0 (20240101)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({})
```

This is my nvim config:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
		"ibhagwan/fzf-lua",
		config = function()
			require("fzf-lua").setup({})
		end,
})
```

Could not reproduce with mini.sh (curl method).
</details>

### Description 

I'm running the live_grep, then pressing Ctrl+C before the results load. A `.git/index.lock` file is left behind. This happens some 20-30 times a day.

I tracked down that this first started happening in https://github.com/ibhagwan/fzf-lua/commit/ada262b4235c86a4365eb49d51e4f7616c8f7da5

It looks like the SIGINT reaches the git process through vim's `system` function and then git leaves behind the index.lock? It seems strange that git doesn't remove this file itself.

EDIT: attaching terminal recording: https://asciinema.org/a/a2bRgP1uCm5dFpB0DH3edXo3q

**Comment by ibhagwan** [comment]
Will investigate, can you check if running live grep with `git_icons=false` works around the issue?

I’m trying to get a clue what in live_grep even requires a git lock, I can only think of the git status to display the git icons unless the git lock is internal to neovim or rg somehow?

**Comment by ibhagwan** [comment]
Also, the code in the commit is only with neovim nightly as 0.9 doesn’t have `vim.system`, if this doesn’t happen on 0.9.5 we can temporarily revert back to use `vim.fn.system` instead.

**Comment by mgnsk** [comment]
> Will investigate, can you check if running live grep with `git_icons=false` works around the issue?
> 
> I’m trying to get a clue what in live_grep even requires a git lock, I can only think of the git status to display the git icons unless the git lock is internal to neovim or rg somehow?

It does seem to that setting `git_icons=false` on nvim nightly fixes the issue. 

> Also, the code in the commit is only with neovim nightly as 0.9 doesn’t have `vim.system`, if this doesn’t happen on 0.9.5 we can temporarily revert back to use `vim.fn.system` instead.

It seems that nvim 0.9.5 doesn't have this issue even with `git_icons=true`.

**Comment by ibhagwan** [comment]
> It does seem to that setting git_icons=false on nvim nightly fixes the issue.

It's definitely that I was able to reproduce that by running `:FzfLua git_status` and cancelling quickly with ctrl-c.

> It seems that nvim 0.9.5 doesn't have this issue even with git_icons=true.

This is also reprorucible for me on 0.9.5, 0.9.4, 0.9.2, 0.9 and 0.8.3 (probably every verison out there...) **which brings me to strongly suspect this is most likely a git bug**.

I'm currently using `2.43.0` (apparently latest), what is your git version?

**Comment by mgnsk** [comment]
> I'm currently using `2.43.0` (apparently latest), what is your git version?

Also on `2.43.0`.

Still can't reproduce the issue myself anywhere except nvim nightly with default fzf-lua config.

**Comment by ibhagwan** [comment]
> > I'm currently using `2.43.0` (apparently latest), what is your git version?
> 
> Also on `2.43.0`.
> 
> Still can't reproduce the issue myself anywhere except nvim nightly with default fzf-lua config.

This is a weird one but I’ll get to the bottom of it.

It’s very easy for me to reproduce, I have a bare repo setup at $HOME so running `git status -su` takes a while (listing untracked files), running `FzfLua git_status` and cancelling leaves the index file.

What confuses me more is not being able to reproduce this in the shell, so this is somehow related to neovim/fzf/fzf-lua.

**Comment by mgnsk** [comment]
This might have something to do with how git is called. I've seen such issues before where something was different depending if the program run in a script or not (maybe something pty related, maybe not, I've no immediate knowledge without doing a research first). I wonder if there's any difference between vim's `system` and `jobstart`.

Could the `--no-optional-locks` option be used?
https://git-scm.com/docs/git#Documentation/git.txt---no-optional-locks

**Comment by ibhagwan** [comment]
> Could the --no-optional-locks option be used?

I'm not sure what would be the implications of this flag, the last thing I want is to cause another issue due to a potential bug that needs to be solved.

I was able to reproduce this in the shell, seems like this might be an `fzf` issue, I tried many times to run `git status -su` and interrupting with `ctrl-c` to no avail, but doing this and cancelling really quick seems to be the issue:
```sh
FZF_DEFAULT_COMMAND="git status -su" fzf
# although less, I also managed to get the index locked with
git status -su | fzf
```

Can you try and let me know if you experience the same behavior? My fzf version is `0.45.0`.

**Comment by mgnsk** [comment]
Yep, managed to reproduce with `FZF_DEFAULT_COMMAND="git status -su" fzf`. fzf version is also `0.45.0`.

**Comment by ibhagwan** [comment]
@mgnsk, I'm still unsure if this is a git or upstream issue but it does seem that `--no-optional-locks` solves this issue with no apparent downside (for `git status`), I therefore added it in the latest commit and also replaced `-s` (short format) with `--porcelain=v1` as suggested by @wookayin in #889.

**Comment by wookayin** [comment]
Oh this was the reason I was sometimes getting weird `.git/index.lock` issues!! Thanks for the fix.

**Comment by ibhagwan** [comment]
> Oh this was the reason I was sometimes getting weird `.git/index.lock` issues!! Thanks for the fix.

Thank you @mgnsk for both the issue identification and the fix :smile:

**Comment by mgnsk** [comment]
I got curious and looked at what fzf does. With the `FZF_DEFAULT_COMMAND="git status -su" fzf` case, it kills the git process with SIGKILL which indeed does not allow git to clean up its lockfile.

In the pipe case `git status -su | fzf` (which I can't reproduce myself), all processes in the pipeline should receive a SIGINT so git either observes that or an error from its stdout. It does not sound believable git can't handle that. I'm not sure how you got the index locked like that.

https://github.com/junegunn/fzf/blob/master/src/reader.go#L83-L87
Note the `defaultCommand` has nothing to do with `FZF_DEFAULT_COMMAND`.

**Comment by ibhagwan** [comment]
> I got curious and looked at what fzf does. With the `FZF_DEFAULT_COMMAND="git status -su" fzf` case, it kills the git process with SIGKILL which indeed does not allow git to clean up its lockfile.
> 
> In the pipe case `git status -su | fzf` (which I can't reproduce myself), all processes in the pipeline should receive a SIGINT so git either observes that or an error from its stdout. It does not sound believable git can't handle that. I'm not sure how you got the index locked like that.
> 
> https://github.com/junegunn/fzf/blob/master/src/reader.go#L83-L87 Note the `defaultCommand` has nothing to do with `FZF_DEFAULT_COMMAND`.

The question is, does this justify an issue upstream and would there be any other solution to what we already did, I’m not really sure what else is there to do when a process receives a SIGKILL.

**Comment by mgnsk** [comment]
> The question is, does this justify an issue upstream and would there be any other solution to what we already did, I’m not really sure what else is there to do when a process receives a SIGKILL.

Probably not, the SIGKILL must be there for a good reason and making our command play nice is the best we could do.
