### ISSUE TITLE
Question: remapping keymaps

### ISSUE THREAD

**Issue by pmzn** [ibhagwan/fzf-lua#1019]
### Info

Hello, I am trying to switch from Telescope to fzf-lua for it's increased speed on large repo / manipulating large files.
Thanks a lot for the hard work !

I am trying to recover my previous Telescope mapping, which are the followings for the **normal mode**:

```
				mappings = {
					...
					n = {
						["<esc>"] = actions.close,
						["<CR>"] = actions.select_default,
						["<C-x>"] = actions.select_horizontal,
						["<C-v>"] = actions.select_vertical,
						["<C-t>"] = actions.select_tab,

						["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
						["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
						["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
						["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,

						["j"] = actions.move_selection_next,
						["k"] = actions.move_selection_previous,
						["H"] = actions.move_to_top,
						["M"] = actions.move_to_middle,
						["L"] = actions.move_to_bottom,

						["<Down>"] = actions.move_selection_next,
						["<Up>"] = actions.move_selection_previous,
						["gg"] = actions.move_to_top,
						["G"] = actions.move_to_bottom,

						["<C-u>"] = actions.preview_scrolling_up,
						["<C-d>"] = actions.preview_scrolling_down,

						["<PageUp>"] = actions.results_scrolling_up,
						["<PageDown>"] = actions.results_scrolling_down,

						["?"] = actions.which_key,
					},
                                  ...
				},
			},

```

Is there a way to emulate a similar behaviour in fzf-lua ? For now, when I enter normal mode, I am unable to interact with the plugin.

Any input is much appreciated, thanks a ton for the help !

**Comment by ibhagwan** [comment]
> Is there a way to emulate a similar behaviour in fzf-lua ? For now, when I enter normal mode, I am unable to interact with the plugin.

Fzf-lua is a terminal buffer and runs an external process (hence the performance), you can probably emulate some of these mappings with custom functions that feedkeys to the terminal but IMHO it would be hackky and unnatural.

You’d also need to remap Esc to <C-\-n> which is how you enter normal mode on terminal buffers.

**Comment by pmzn** [comment]
Thank you, super clear ! I guess I will learn new bindings then :)
