### ISSUE TITLE
Builtin previewer stops updating after one entry is selected

### ISSUE THREAD

**Issue by fsouza** [ibhagwan/fzf-lua#102]
As I navigate, it updates fine, but as soon as I select an entry (with multiple selections enabled), the preview gets stuck with that entry.

See recording:

https://user-images.githubusercontent.com/108725/132113266-4cc3d44e-b4dc-44bc-858d-0c9f9bb9a567.mp4

Notice how after I select an item in the middle the preview gets stuck with that item.

**Comment by ibhagwan** [comment]
Good find, seems like a bug with `nvim-fzf`, opened [nvim-fzf issue #29](https://github.com/vijaymarupudi/nvim-fzf/issues/29).

Will keep this open for tracking until it's solved upstream.

**Comment by ibhagwan** [comment]
[Turns out this is an `fzf` issue](https://github.com/vijaymarupudi/nvim-fzf/issues/29#issuecomment-913154430):

```sh
seq 1 4 | fzf --preview="echo {} {+}" --multi
```

**Comment by vijaymarupudi** [comment]
I wouldn't call this an issue, necessarily, what @fsouza is asking for is achievable, just using `{}` instead of `{+}`. `{+}` is all the selected items, if there are some, otherwise the current line. `{}` is always the current line.

**Comment by ibhagwan** [comment]
> I wouldn't call this an issue, necessarily, what @fsouza is asking for is achievable, just using `{}` instead of `{+}`. `{+}` is all the selected items, if there are some, otherwise the current line. `{}` is always the current line.

I guess this ties into  #103, also reminds me of [my nvim-fzf PR #18](https://github.com/vijaymarupudi/nvim-fzf/pull/18).

Perhaps finer control over the fzf action parameters is due?

**Comment by ibhagwan** [comment]
@vijaymarupudi I have the PR ready in https://github.com/ibhagwan/nvim-fzf/commit/936d37a3248bb957f370d496351d671aa6614171 if you change your mind, this would also solve the hack code I added for #103 (replacing `{+}` with `{q}`).

**Comment by vijaymarupudi** [comment]
Now this is a situation where that PR was important, there is no other way to fix this. I've accidentally independently implemented the same PR. Well, I've pushed it anyways! Update `nvim-fzf`!

**Comment by ibhagwan** [comment]
> Now this is a situation where that PR was important, there is no other way to fix this. I've accidentally independently implemented the same PR. Well, I've pushed it anyways! Update `nvim-fzf`!

I’m just happy I was finally able to convince you to add that, ty :)

**Comment by ibhagwan** [comment]
Reopening this, I’ll fix this properly for all providers today.

**Comment by fsouza** [comment]
@ibhagwan @vijaymarupudi thank you very much for addressing this and apologies for not being more helpful here

**Comment by ibhagwan** [comment]
Should be good now.
