### ISSUE TITLE
[feat]: Fuzzy find over changed git files

### ISSUE THREAD

**Issue by Palanikannan1437** [ibhagwan/fzf-lua#1020]
### Description 

Is there any possibility to `live_grep` over git diff/only the changed files. Having this as a flag would be awesome, what are your thoughts @ibhagwan....

**Comment by ibhagwan** [comment]
> ### Description
> Is there any possibility to `live_grep` over git diff/only the changed files. Having this as a flag would be awesome, what are your thoughts @ibhagwan....

Anything is possible with some effort, I’m not sure if `rg` supports this out of the box but perhaps you can craft your own command using `git grep` (which you can set as `cmd = …` to live grep.

Quick search shows this might be possible:
https://stackoverflow.com/questions/13955390/git-grep-but-restricted-to-new-or-modified-files-in-the-index#14053984

**Comment by ibhagwan** [comment]
Alternatively if you just want to fuzzy over a specific set, you can use `grep({ raw_cmd = … })}` and for cmd craft a command  that would perform rg with an empty search on each file out of git status, something like:
```sh
git status -s | grep M | xargs … rg …
```

Play with this command in the shell until you get an output of all diff files in ripgrep format (with line/column), feed that command to fzf-lua’s grep and you’ll get what you want.

**Comment by ibhagwan** [comment]
@Palanikannan1437, I had a free moment and could craft your command easily:
```lua
:lua require("fzf-lua").grep({raw_cmd = [[git status -su | rg "^\s*M" | cut -d ' ' -f3 | xargs rg --hidden --column --line-number --no-heading --color=always  --with-filename -e '']]})
```

**Comment by ibhagwan** [comment]
Closing, the purposed command should solve your issue, feel free to reopen if you need further help.

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437, I had a free moment and could craft your command easily:
> 
> ```lua
> :lua require("fzf-lua").grep({raw_cmd = [[git status -su | rg "^\s*M" | cut -d ' ' -f3 | xargs rg --hidden --column --line-number --no-heading --color=always  --with-filename -e '']]})
> ```

This is awesome, thanks for taking the time @ibhagwan. I really gotta learn my cli tools better....

**Comment by AlejandroSanchez90** [comment]
Im getting this after running the above commands, the commands works but then i have to delete this index file to be able to stage/unstage files again
```
git reset -- /sagas.ts:

> fatal: Unable to create '/.git/index.lock': File exists.
> 
> Another git process seems to be running in this repository, e.g.
> an editor opened by 'git commit'. Please make sure all processes
> are terminated then try again. If it still fails, a git process
> may have crashed in this repository earlier:
> remove the file manually to continue.
> 
```

**Comment by ibhagwan** [comment]
> Im getting this after running the above commands, the commands works but then i have to delete this index file to be able to stage/unstage files again
> 
> ```
> git reset -- /sagas.ts:
> 
> > fatal: Unable to create '/.git/index.lock': File exists.
> > 
> > Another git process seems to be running in this repository, e.g.
> > an editor opened by 'git commit'. Please make sure all processes
> > are terminated then try again. If it still fails, a git process
> > may have crashed in this repository earlier:
> > remove the file manually to continue.
> > 
> ```

Probably a git issue, unrelated to fzf-lua, try upgrading git.
