### ISSUE TITLE
Question: Open file picker/grep with toggle_ignore already enabled

### ISSUE THREAD

**Issue by star-szr** [ibhagwan/fzf-lua#1021]
Thank you for this incredible plugin.

I've been happy to ditch my hacked-together ignore toggles for the recently added ignore toggle actions for both files and grep. Thank you very much for both of those. One thing I am missing is a way to open a picker and toggle the ignore action immediately. 

Is there/could there be a way to pass in an option to the picker to set the initial settings for these toggles? Or have the header logic check which flags were passed? Or some other simpler thing I haven't considered?

I can set the toggle via `fd_opts` or `rg_opts` but the UI does not reflect the status of the options passed in which makes things a bit inconsistent.

**Comment by ibhagwan** [comment]
> Or have the header logic check which flags were passed? Or

This should be the solution, I was planning to add this anyways.

I’ll leave this issue open until fixed.

**Comment by ibhagwan** [comment]
@star-szr, should work as expected with https://github.com/ibhagwan/fzf-lua/commit/718be95a88f6200137c17d64999e947afba07151.

**Comment by ibhagwan** [comment]
> @ibhagwan indeed, it works perfectly. Thank you so much!

Ty for the update @star-szr!
