### ISSUE TITLE
invalid value width "" is not an integer

### ISSUE THREAD

**Issue by kapral18** [ibhagwan/fzf-lua#1023]
![CleanShot 2024-02-02 at 09 38 56](https://github.com/ibhagwan/fzf-lua/assets/1625373/0f5c4b1d-8a1b-464f-b9d8-76832b561c47)

### Info

- Operating System: MacOS Sonoma 14.3
- Shell: fish
- Terminal: ITerm2
- `nvim --version`: v0.9.5
- `fzf --version`: 0.46.1

- [x] The issue is reproducible with `mini.sh`

**Comment by ibhagwan** [comment]
@kapral18, should workwith https://github.com/ibhagwan/fzf-lua/commit/fd567e008124428c281255feaa53873029326679.
