### ISSUE TITLE
.gitignore not used by `:FzfLua files` inside bare repo

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#1026]
### Info

- Operating System: Arch Linux
- Shell: fish
- Terminal: wezterm
- `nvim --version`: v0.10.0-dev-2257+g302fa5f7d
- `fzf --version`: 0.44.1 (d7d2ac3)

### Description 

I'm not sure if this is a bug or a feature request, but it seems like `:FzfLua files` doesn't use `.gitignore` when inside a bare repo (a common way to handle dotfiles). Despite being a bit of a niche case, it would be nice to have support for it :)

**Comment by ibhagwan** [comment]
Fzf-lua merely reflects the output of the underlying command (rg, fd, etc), run `:FzfLua files debug=true` and examine the command in the first line (starts with `[DEBUG]`), run that command in the shell and that’s what fzf-lua displays (with the additions of icons).

Fzf-lua itself has no awareness of `.gitignore`, the new options to respect/ignore gitignore toggles the `--no-ignore` flag but the responsibility of the filtering lies on fd or rg.

There is always the option to ignore some patters on the fzf-lua side with `file_ignore_patterns` but that’s not exactly .gitignore.


![IMG_1857](https://github.com/ibhagwan/fzf-lua/assets/59988195/852b4144-4181-4a59-98b6-1207ba8c354b)
> After pressing `ctrl-g`
![IMG_1858](https://github.com/ibhagwan/fzf-lua/assets/59988195/43cef749-6e45-4267-9d6e-cb2aec23685c)

**Comment by MariaSolOs** [comment]
@ibhagwan thank you for the careful explanation! It seems like I'm running into the `fd`'s issue described [here](https://github.com/sharkdp/fd/issues/1032).

I'll close this since it's not a problem with `fzf-lua` but with one of its dependencies (or simply my ignorance 😅)
