### ISSUE TITLE
`continue_last_filter` or `repeat_last_filter`

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#103]
Currently the option exists to `continue_last_search` or `repeat_last_search`:

https://github.com/ibhagwan/fzf-lua/blob/7a144f81da3a8d7362134355872c295de77136ab/lua/fzf-lua/providers/grep.lua#L106

It would be nice if fzf-lua could remember the last filter prompt that was entered. My workflow involves 

1. Hitting `<leader>fg` to run `live_grep`
2. Filtering down by typing text in the prompt
3. Selecting files and hitting enter to open them
4. Sometimes I realize I need to open one additional file
5. Hitting `<leader>fg` to run `live_grep` again, and filtering down by typing the same text that I did in step 2.

It would be nice if there was an option that allowed the previously entered text to be prefilled in the prompt.

**Comment by ibhagwan** [comment]
Currently it’s not possible as the command is managed internally by `fzf`, it’s a good idea and I also have the same workflow and get annoyed when I can’t continue from the last search, let me see if I can solve it.

**Comment by ibhagwan** [comment]
Try the latest commit, `live_grep()` now saves the typed query by default, you can continue either with regular grep or with live grep by supplying:
```lua
:lua require('fzf-lua').grep({ continue_last_search = true })
:lua require('fzf-lua').live_grep({ continue_last_search = true })
```

Alternatively, if you wish for live grep to not pollute your last search use:
```lua
:lua require('fzf-lua').live_grep({ do_not_save_last_search = true })
```

Let me know what you think @kdheepak?


@vijaymarupudi, I had to implement a small hack to the `raw_async_action` and replace `{+}` with `{q}` as it's geared towards preview actions and not `reload` events, seems to work very nice nonetheless but perhaps you'd like to address this in the code and documentation?

https://github.com/ibhagwan/fzf-lua/commit/62024ecf9a31faabdd61daee71f19aaa774af9c4

**Comment by ibhagwan** [comment]
FYI, added a "convenience" function `live_grep_resume()` so it's easier to find with the builtin provider (equal to running `live_grep` with `continue_last_search = true`).

**Comment by vijaymarupudi** [comment]
Sorry, I didn't notice the mention, `fzf-lua`'s prolific development kinda made this get lost in the flurry of emails. I've unwatched `fzf-lua` (weirdly so that I can follow it better), so now when you mention me, I should be able to respond promptly. I believe we've addressed the library issue in a different thread :)

**Comment by kdheepak** [comment]
@ibhagwan works great! Thanks for making these features available in such a short turn around!

**Comment by kdheepak** [comment]
The same thing doesn't work for `require"fzf-lua".files({continue_last_search = true})` btw.

**Comment by ibhagwan** [comment]
> The same thing doesn't work for `require"fzf-lua".files({continue_last_search = true})` btw.

That’s because it wasn’t implemented for `files` - that would require hooking the reload event and adding  more flags and tests and what not just to be able to save the file query, not sure if the added complexity is worth it for files?

**Comment by kdheepak** [comment]
Possibly. I think for repositories where there's a large number of files it might be worth it? 

I would certainly find it useful even on smaller repos. I end up doing the same searches quite often even on smaller repositories, since often times I'm searching for a folder and then I open a file in it. If I want to open another file in the same folder, I have to redo the search.

**Comment by ibhagwan** [comment]
I can probably add it for `fzf` but that will create an inconsistency with `skim`, the reason is skim doesn’t support change events, it’s not an issue with `live_grep` as it uses something called “skim interactive mode”. Using either `change:reload` with fzf or interactive with skim disables the fuzzy search functionality, `rg` is essentially executed with a new query for every keystroke, the fuzzy search is disabled.

Therefore implementing this for `files` (or any provider that requires the fuzzy search and isn’t “live”) is going to have inconsistent functionality between the binaries (and lots of ugly conditionals in the code).

**Comment by kdheepak** [comment]
I see. That makes sense. I can try to implement it locally for use in my config.

**Comment by ibhagwan** [comment]
> I see. That makes sense. I can try to implement it locally for use in my config.

You can actually do it quite simply, even with the existing `files` provider, just create a `raw_action` (you don’t need `raw_async_action`) from nvim-fzf (make sure to set `fzf_field_expression` to `{q}`), and send additional fzf args `—bind=change:<raw_action_string>`, this way your action function will get called every keystroke (at `args[1]`), save the query in a local variable and if it’s not empty send it to fzf with `—query`.

You can add any flags you want to fzf by supplying `fzf_cli_args`.

**Comment by ibhagwan** [comment]
Implemented it for you ~15 lines of code, `files_resume()`, it's a bit hacky and doesn't have fancy options and supported only by `fzf`.

The way it works is that you have to basically use that instead of `files()` all the time, it always saves queries and always starts from the last input (regardless of `cwd` or other options), use at your own discretion.

https://github.com/ibhagwan/fzf-lua/blob/07288898afd83339dcbd02268a98fc79329055cd/lua/fzf-lua/providers/files.lua#L53-L77

**Comment by kdheepak** [comment]
Thanks for implementing it! There's some weird flickering going on on my end when I use this though. Maybe this is because the action function is called at every keystroke and there's no way around this?

**Comment by ibhagwan** [comment]
> Thanks for implementing it! There's some weird flickering going on on my end when I use this though. Maybe this is because the action function is called at every keystroke and there's no way around this?

I’m not sure, the command is run in the background, it shouldn’t cause flickering, does the same flickering happen with live grep?

**Comment by kdheepak** [comment]
Here's a screencast of what it looks like:

https://user-images.githubusercontent.com/1813121/132252707-a0b5e9c8-26f1-4969-adcb-5fe62a3e399b.mov

No the flickering doesn't happen when using livegrep.

**Comment by ibhagwan** [comment]
Should work nicely now, had to change the fzf flag from `change:execute` to `change:execute-silent`

**Comment by kdheepak** [comment]
Nice! That resolves it for me!

**Comment by ibhagwan** [comment]
FYI, I found an issue with the live_grep with resume, I changed the default live grep back to native, if you want to continue using it while I work on the issue you need to call `live_grep_resume` directly.

**Comment by kdheepak** [comment]
Thanks for letting me know. I’m not experiencing any issue. I’m curious what the problem is.

**Comment by ibhagwan** [comment]
I'm not sure yet what causes this but it seems that when typing too fast or initializing with queries that return long result sets the async function completes before the entire result set is populated so you end up with partial results.

I wanted to change the function anyways and add a cancellation of the async function to speed things up when live grep'ing on a huge codebase and make it even more responsive, so I look at this as an opportunity.

On the bright side, I optimized the `live_grep_native` (which is currently linked by `live_grep`) and it's working really well, special chars, continuation from regular grep, etc, so it's not that bad, the only thing missing right now is the "resume" functionality which you can manually opt into by using the `_resume` version.

I'll keep this thread updated when I figure it out.

**Comment by ibhagwan** [comment]
Should be working now, had a fun race condition bug, love those :-)

Default `live_grep` restored to the resume version.

**Comment by ibhagwan** [comment]
@kdheepak since I know you’re interested, [here’s a description of what happened and the solution](https://github.com/vijaymarupudi/nvim-fzf/issues/32).
