### ISSUE TITLE
Make git change hard reset the buffer

### ISSUE THREAD

**Issue by I-Own-You** [ibhagwan/fzf-lua#1030]
### Info

- Operating System: arch
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.9.5
- `fzf --version`: 0.46.1

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
-- default with some changing for rg,fd and UI things
})
```
</details>

### Description 

When i use `:FzfLua gti_status`, and then i press `ctrl+x`, it supposes to reset the buffer, and it resets the buffer, but only if i dont have the buffer opened (not in the bakcground).

I would want it to reset the buffer while being opened as well, if thats possible.

[Screencast from 2024-02-05 21-58-17.webm](https://github.com/ibhagwan/fzf-lua/assets/91146968/147bb4ef-7310-47ad-8b74-3b08cbd4848c)

**Comment by ibhagwan** [comment]
I'm aware of this issue, it requires further digging about the correct way to reload existing buffers in neovim other than `e!` (as sometimes you'd reset more than the current buffer).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/78bd3729e18a544331f15be8e65ae52fc4390ac7

I was able to find a more elegant solution by calling `:checktime` which respects the users' `autoread` setting.
