### ISSUE TITLE
Selecting branch from git_branches sometimes gives attempt to concatenate local 'msg' (a nil value)

### ISSUE THREAD

**Issue by mikehaertl** [ibhagwan/fzf-lua#1032]
### Info

- Operating System: Linux Mint 21.3
- Shell: bash
- Terminal: GNOME Terminal 3.44.09
- `nvim --version`: NVIM v0.10.0-dev-2154+gb4da4783f
- `fzf --version`: 0.41.1 (6eb1874)
- `fzf-lua`: 36195a2

### Description

When I select a branch from `:FzfLua git_branches` I sometimes get this error:

```
[Fzf-lua] fn_selected threw an error: .../.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/utils.lua:125: attempt to concatenate local 'msg' (a nil value)
stack traceback:
^I...e/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:170: in function '__concat'
^I.../.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/utils.lua:125: in function 'fast_event_aware_notify'
^I.../.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/utils.lua:130: in function 'info'
^I...local/share/nvim/plugged/fzf-lua/lua/fzf-lua/actions.lua:581: in function 'action'
^I...local/share/nvim/plugged/fzf-lua/lua/fzf-lua/actions.lua:72: in function 'act'
^I...e/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:94: in function 'fn_selected'
^I...e/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:168: in function <...e/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:167>
^I[C]: in function 'xpcall'
^I...e/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:167: in function <...e/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:161>
```

It could be related to branches that e.g. contain dashes like `315-fix-null-values`. Branches without (`master`) seem to work.

### fzf-luca configuration for git

```
  git = {
    status = {
      preview_pager = 'delta --width=$FZF_PREVIEW_COLUMNS',
    },
    commits = {
      preview_pager = 'DELTA_FEATURES=+ delta --width=$FZF_PREVIEW_COLUMNS',
    },
    bcommits = {
      preview_pager = 'delta --width=$FZF_PREVIEW_COLUMNS',
      actions = {
        ['ctrl-x'] = actions.git_buf_split,
      }
    },
  },
```

### Notes

To save some time I did not provide a full minimal config to reproduce. Let me know if you really need this to reproduce the issue.

**Comment by ibhagwan** [comment]
> It could be related to branches that e.g. contain dashes like `315-fix-null-values` Branches without (master) seem to work.

This doesn’t seem to be the case I can switch branches with hyphens, can you provide a name of a failed branch as well as the output of how this branch appears in `git branch --all`?

**Comment by ibhagwan** [comment]
> Like I said: If I select 315-fix-null-values I get the error. Can I try anything else to help debugging the issue?

I’ll figure it out, might be related to it being the current branch (prefixed by *), it should do nothing technically, I’ll test.

**Comment by ibhagwan** [comment]
@mikehaertl, should work as expected, this was an error with nightly due to the new `vim.system`, apparently the message `Switch to branch...` is directed to `stderr`.

**Comment by mikehaertl** [comment]
Confirmed, thank you!
