### ISSUE TITLE
Is it possible to make a keymap to an uppercase letter?

### ISSUE THREAD

**Issue by sainttttt** [ibhagwan/fzf-lua#1035]
I've been trying to make a keymap using <Shift-q> or <s-q> or <Q> but I can't seem to make a keymap that will only respond to uppercase Q or shift-q. Is this possible currently? Thanks!

**Comment by ibhagwan** [comment]
That would depend on the mapping you’re after, `keymap.fzf` is for fzf binds (the inner terminal process) and `keymap.builtin` is neovim binds, obviously the latter is more flexible as fzf binds are more restrictive.

You can also use the `on_create` event to create any bind using `vim.keymap.set` and send any key combo with `feedkeys`.

If you can describe in details what you’re trying to achieve I’ll do my best to help.

**Comment by sainttttt** [comment]
I was wondering if I could bind the uppercase Q (shift-q) to closing fzf-lua, if that would be possible

**Comment by ibhagwan** [comment]
Looking at `man fzf` it doesn’t seem like shift-a is a valid bind, but what you can do is add the below to your neovim config:
```lua
  vim.api.nvim_create_autocmd("FileType",
    {
      pattern = "fzf",
      callback = function(e)
        vim.keymap.set("t", "<S-q>", "<C-c>", { buffer = e.buf, silent = true })
      end,
    })
```

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if this doesn't resolve your issue.
