### ISSUE TITLE
Question: How to scroll the preview window?

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [ibhagwan/fzf-lua#1037]
Hi, I would like to know how I can scroll inside the preview window when looking at git commits or when I look at the preview for a file. Thanks.

![image](https://github.com/ibhagwan/fzf-lua/assets/44822875/3818cc4e-27ed-4acd-a8d6-bccc2ca7825c)

I browsed the help files and wiki but there is no mention of scrolling. Perhaps it just isn't intuitive to me. Page up/down moves to the top/bottom of search results.

**Comment by ibhagwan** [comment]
Look at the default `shift-up|down` binds:
https://github.com/ibhagwan/fzf-lua/blob/5edef75e7fda195f10afb160acca07330b4cd03a/README.md?plain=1#L593-L607

**Comment by ibhagwan** [comment]
Btw, if you press `F1` you’ll get the bottom help screen with all the configured keybinds:
![IMG_1883](https://github.com/ibhagwan/fzf-lua/assets/59988195/0a910b62-c7dd-4bdb-a492-94c8480e75a4)
