### ISSUE TITLE
[Windows] Regression testing progress

### ISSUE THREAD

**Issue by ibhagwan** [ibhagwan/fzf-lua#1038]
Testing of the [windows branch](https://github.com/ibhagwan/fzf-lua/tree/windows)

- Buffers | Tabs
  + [x] cwd_only
  + [x] sort_lastused
  + [x] action: close buffer
  + [x] previewer
    * [x] builtin
    * [x] bat
- Files
  + [x] no args
  + [x] cwd
    * [x] absolute
    * [x] relative
    * [x] with ~
    * [x] with spaces
  + [x] cwd_prompt
  + [x] previewer
    * [x] builtin
    * [x] bat
  + [x] cmd
    + [x] fd
    + [x] rg (no fd installed)
    + [x] dir (no rg/fd installed)
  + [x] file_ignore_patterns
  + [x] multiprocess (true/false)
  + [x] toggle `.gitignore` action
  + [x] resume
  + [x] path_shorten
  + [x] git_icons
  + [x] file_icons
  + [x] color_icons
- Oldfiles
  + [x] cwd_only
  + [x] custom `cwd`
  + [x] `stat_file` (true|false)
  + [x] `include_current_session`
- Quickfix & Loclist
  + [x] Quickfix
  + [x] Quickfix Stack
  + [x] Loclist
  + [x] Loclist Stack
- Lines|BLines
  + [x] previewer
    * [x] builtin
    * [x] bat
- Args (arglist)
  + [x] action: argdel
  + [x] previewer
    * [x] builtin
    * [x] bat
- Live grep | grep
  + [x] no args
  + [x] no `rg` installed
  + [x] regex special chars `[(~'"\/$?*&|;[]<>)]`
  + [x] exec_empty_query
    * [x] true
    * [x] false
  + [x] rg_glob
    * [x] true
    * [x] false
  + [x] glob filtering
  + [x] actions
    * [x] toggle grep <-> live grep
    * [x] toggle `.gitignore` 
  + [x] query|search resume
  + [x] previewer
    * [x] builtin
    * [x] bat
  + [x] cwd variants
  + [x] current buffer grep|lgrep
    * [x] toggle grep <-> live grep
    * [x] query|search resume
   + [x] variants
    * [x] `grep_cword`
    * [x] `grep_cWORD`
    * [x] `grep_visual`
- BTags
  + [x] ctag_autogen
    * [x] true
    * [x] false
    * [x] false, no `rg` installed
  + [x] previewer
    * [x] builtin
    * [x] bat
- Tags grep | live grep
  + [x] no `rg` installed
  + [x] grep <-> live grep
  + [x] query|search resume
  + [x] previewer
    * [x] builtin
    * [x] bat
  + [x] variants
    * [x] `tags_grep_cword`
    * [x] `tags_grep_cWORD`
    * [x] `tags_grep_visual`
- Git
  + [x] Files
    * [x] not in a git repo
    * [x] path_shorten
    * [x] cwd
    * [x] previewer
      - [x] builtin
      - [x] bat
  + [x] Status
    * [x] cwd
    * [x] preview modified
    * [x] preview untracked
    * [x] preview deleted
    * [x] action: stage 
    * [x] action: unstage 
    * [x] action: stage-unstage
  + [x] Commits
    * [x] cwd
    * [x] action: checkout 
  + [x] BCommits
    * [x] cwd
    * [x] visual range
    * [x] action: git buf edit 
  + [x] Branches
    * [x] cwd
    * [x] action: switch
  + [x] Stash
    * [x] pop
    * [x] drop
  + [x] Tags
    * [x] action: checkout
- LSP
  + [x] locations
     * [x] `includeDeclaration`
     * [x] `ignore_current_line`
     * [x] async|sync (true|false)
  + [x] Document symbols
  + [x] Workspace symbols
    * [x] cwd_only
    * [x] ctrl-g to live_query
    * [x] ctrl-g from live_query
    * [x] query|search resume
  + [x] Diagnostics
    * [x] document
    * [x] workspace
  + [x] Code Actions
    * [x] previewer: codeaction
    * [x] previewer: codeaction_native (no delta)
    * [x] previewer: codeaction_native (+ delta)
- Misc
  + [x] Help tags
    * [x] previewer: builtin
    * [x] previewer: native
  + [x] highlights
  + [x] commands
  + [x] command history
  + [x] search history
  + [x] marks
  + [x] jumps
  + [x] changes
  + [x] registers
  + [x] tagstack
  + [x] autocmds
  + [x] keymaps
  + [x] filetypes
  + [x] spell_suggest
  + [x] packadd
- UI select
  + [x] register
  + [x] deregister
- DAP
  + [x] breakpoints
- Completion
  + [x] path (+icons)
  + [x] file (+icons)
  + [x] line
  + [x] bline

**Comment by asknet** [comment]
Great progress! 👏

**Comment by ibhagwan** [comment]
Upstream issues for tracking:
https://github.com/junegunn/fzf/issues/3626

**Comment by TheLeoP** [comment]
Hey again c:. I saw your post in reddit and got some motivation to help with the Windows integration again (sorry for disappearing).

`:FzfLua live_grep` and then entering any input is giving me the following error: `""C:/Program" is not recognized as an internal command ...`. Is it working for you? I'm guessing that it has something to do with with some scaping problems, but I don't fully understand the new code yet.

`:FzfLua live_grep_native` does work (but the preview is always empty), so that makes me think that the scaping problem may be coming from the `spawn_stdio` wrapper.

Also, I'm not sure if I'm doing something wrong because I'm having a lot of random problems. For example, `:FzfLua files` (using fd) does not work for me (I haven't tested it without fd), it always shows nothing as a result. If I executed the command that `debug=true` gaves me, it works, so fzf-lua isn't getting the results from fzf for some reason (?).

Do any of the recent changes may be affected by my system language being Spanish? I can't really think about a lot of other differences between my windows installation and your Windows VM.

**Comment by ibhagwan** [comment]
> Hey again c:. I saw your post in reddit and got some motivation to help with the Windows integration again (sorry for disappearing).
> 
> `:FzfLua live_grep` and then entering any input is giving me the following error: `""C:/Program" is not recognized as an internal command ...`. Is it working for you? I'm guessing that it has something to do with with some scaping problems, but I don't fully understand the new code yet.
> `:FzfLua live_grep_native` does work (but the preview is always empty), so that makes me think that the scaping problem may be coming from the `spawn_stdio` wrapper.

Yes @TheLeoP, everything I tested worked very well but I didn’t expect this to go that smooth, it’s still windows after all :)

My guess is also a missing call to `libuv.shellescape`, can you please post the output of `:messages` after running both:
```lua
:FzfLua live_grep debug=v
:FzfLua live_grep debug=v _base64=false
```
 
> Also, I'm not sure if I'm doing something wrong because I'm having a lot of random problems. For example, `:FzfLua files` (using fd) does not work for me (I haven't tested it without fd), it always shows nothing as a result. If I executed the command that `debug=true` gaves me, it works, so fzf-lua isn't getting the results from fzf for some reason (?).


You’re not doing anything wrong, this is clearly a bug, everything should work out of the box, same as above can you post the output of:

```lua
:FzfLua files debug=v
:FzfLua files debug=v _base64=false
```
 
> Do any of the recent changes may be affected by my system language being Spanish? I can't really think about a lot of other differences between my windows installation and your Windows VM.

The code should be agnostic to Unicode/languages, we’re probably not far from getting all this to work perfectly, with your help and some minor adjustments we’ll get there :)

**Comment by ibhagwan** [comment]
Oh @TheLeoP, one important note, have you tried with zero config? If you copied the old defaults to your `setup` and they contained `rg_opts|fd_opts` which contained single quotes `'` this could be the issue, Windows does not treat those as arguments quotes but rather as a string literal and it can cause all kinds of issues.

**Comment by TheLeoP** [comment]
> one important note, have you tried with zero config?

Yeah, I'm using zero config.

Output of `live_grep`:

```
[Fzf-lua]: FZF_DEFAULT_COMMAND: break || break
[Fzf-lua]: fzf cmd: fzf --ansi --info ^"default^" --height ^"100^%^" --header ^":: ^<^[[38;2;255;235;205mctrl-g^[[0m^> to ^[[38;2;255;64;64mFuzzy Search^[[0m^" --layout ^"reverse^" --prompt ^"*Rg^> ^" --print-query --bind ^"ctrl-a:beginning-of-line,ctrl-e:end-of-line,alt-a:toggle-all,f3:toggle-preview-wrap,f4:toggle-preview,shift-down:preview-page-down,ctrl-z:abort,ctrl-u:unix-line-discard,zero:execute-silent^(mkdir ^^\^"C:/Users/pcx/AppData/Local/Temp/nvim.0/jV60NL/0^^\^" ^&^& set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=2 , debug=true}^^^)^^\^" -- ^),ctrl-f:half-page-down,shift-up:preview-page-up,ctrl-b:half-page-up^" --expect ^"ctrl-c,ctrl-q,alt-l,esc,ctrl-s,ctrl-v,ctrl-t,alt-q,ctrl-g^" --disabled --preview-window ^"nohidden:right:0^" --border ^"none^" --query ^"^" --multi --preview ^"set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=1 , debug=true}^^^)^^\^" -- {}^" --bind=^"change:reload:set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/libuv.lua]]^^^)^^^(^^^).spawn_stdio^^^([==[e2NvbG9yX2ljb25zID0gdHJ1ZSwgZyA9IHtfZnpmX2x1YV9zZXJ2ZXIgPSAiXFxcXC5cXHBpcGVcXGZ6Zi1sdWEuMTcwNzk3NTk4MS4xMTU0OC4xIiwgX2Rldmljb25zX3BhdGggPSAiQzovVXNlcnMvcGN4L0FwcERhdGEvTG9jYWwvbnZpbS1kYXRhL2xhenkvbnZpbS13ZWItZGV2aWNvbnMvbHVhL252aW0td2ViLWRldmljb25zLmx1YSJ9LCBjbWQgPSAicmcgLS1jb2x1bW4gLS1saW5lLW51bWJlciAtLW5vLWhlYWRpbmcgLS1jb2xvcj1hbHdheXMgLS1zbWFydC1jYXNlIC0tbWF4LWNvbHVtbnM9NDA5NiAtZSB7YXJndnp9ICIsIGdpdF9pY29ucyA9IHRydWUsIGFyZ3ZfZXhwciA9IHRydWUsIGRlYnVnID0gInYiLCBmaWxlX2ljb25zID0gdHJ1ZX0=]==],[==[cmV0dXJuIHJlcXVpcmUoIm1ha2VfZW50cnkiKS5maWxl]==],[==[cmV0dXJuIHJlcXVpcmUoIm1ha2VfZW50cnkiKS5wcmVwcm9jZXNz]==]^^^)^^\^" -- {q} 2^>^&1 ^|^| break^" > ^"C:\Users\pcx\AppData\Local\Temp\nvim.0\jV60NL\2^"
[Fzf-lua]: FZF_DEFAULT_COMMAND: break || break
[Fzf-lua]: fzf cmd: fzf --ansi --info ^"default^" --height ^"100^%^" --header ^":: ^<^[[38;2;255;235;205mctrl-g^[[0m^> to ^[[38;2;255;64;64mFuzzy Search^[[0m^" --layout ^"reverse^" --prompt ^"*Rg^> ^" --print-query --bind ^"ctrl-a:beginning-of-line,ctrl-e:end-of-line,alt-a:toggle-all,f3:toggle-preview-wrap,f4:toggle-preview,shift-down:preview-page-down,ctrl-z:abort,ctrl-u:unix-line-discard,zero:execute-silent^(mkdir ^^\^"C:/Users/pcx/AppData/Local/Temp/nvim.0/jV60NL/3^^\^" ^&^& set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=4 , debug=true}^^^)^^\^" -- ^),ctrl-f:half-page-down,shift-up:preview-page-up,ctrl-b:half-page-up^" --expect ^"ctrl-c,ctrl-q,alt-l,esc,ctrl-s,ctrl-v,ctrl-t,alt-q,ctrl-g^" --disabled --preview-window ^"nohidden:right:0^" --border ^"none^" --query ^"^" --multi --preview ^"set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=3 , debug=true}^^^)^^\^" -- {}^" --bind=^"change:reload:set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/libuv.lua]]^^^)^^^(^^^).spawn_stdio^^^({color_icons = true, g = {_fzf_lua_server = ^^\\\^"\\\\.\\pipe\\fzf-lua.1707975981.11548.1^^\\\^", _devicons_path = ^^\\\^"C:/Users/pcx/AppData/Local/nvim-data/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua^^\\\^"}, cmd = ^^\\\^"rg --column --line-number --no-heading --color=always --smart-case --max-columns=4096 -e {argvz} ^^\\\^", git_icons = true, debug = ^^\\\^"v^^\\\^", argv_expr = true, _base64 = false, file_icons = true},[==[return require^^^(^^\\\^"make_entry^^\\\^"^^^).file]==],[==[return require^^^(^^\\\^"make_entry^^\\\^"^^^).preprocess]==]^^^)^^\^" -- {q} 2^>^&1 ^|^| break^" > ^"C:\Users\pcx\AppData\Local\Temp\nvim.0\jV60NL\5^"
```

Output of `files`:

```
[Fzf-lua]: FZF_DEFAULT_COMMAND: set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime& ^"C:/Program Files/Neovim/bin/nvim.exe^" -n --headless --clean --cmd ^"lua loadfile^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/libuv.lua]]^)^(^).spawn_stdio^([==[e2NvbG9yX2ljb25zID0gdHJ1ZSwgZyA9IHtfZnpmX2x1YV9zZXJ2ZXIgPSAiXFxcXC5cXHBpcGVcXGZ6Zi1sdWEuMTcwNzk3NTk4MS4xMTU0OC4xIiwgX2Rldmljb25zX3BhdGggPSAiQzovVXNlcnMvcGN4L0FwcERhdGEvTG9jYWwvbnZpbS1kYXRhL2xhenkvbnZpbS13ZWItZGV2aWNvbnMvbHVhL252aW0td2ViLWRldmljb25zLmx1YSJ9LCBjbWQgPSAiZmQgLS1jb2xvcj1uZXZlciAtLXR5cGUgZiAtLWhpZGRlbiAtLWZvbGxvdyAtLWV4Y2x1ZGUgLmdpdCIsIGdpdF9pY29ucyA9IHRydWUsIGRlYnVnID0gInYiLCBmaWxlX2ljb25zID0gdHJ1ZX0=]==],[==[cmV0dXJuIHJlcXVpcmUoIm1ha2VfZW50cnkiKS5maWxl]==],[==[cmV0dXJuIHJlcXVpcmUoIm1ha2VfZW50cnkiKS5wcmVwcm9jZXNz]==]^)^" || break
[Fzf-lua]: fzf cmd: fzf --ansi --info ^"default^" --height ^"100^%^" --layout ^"reverse^" --multi --bind ^"ctrl-a:beginning-of-line,ctrl-e:end-of-line,alt-a:toggle-all,f3:toggle-preview-wrap,f4:toggle-preview,shift-down:preview-page-down,ctrl-z:abort,ctrl-u:unix-line-discard,zero:execute-silent^(mkdir ^^\^"C:/Users/pcx/AppData/Local/Temp/nvim.0/jV60NL/6^^\^" ^&^& set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=6 , debug=true}^^^)^^\^" -- ^),ctrl-f:half-page-down,shift-up:preview-page-up,ctrl-b:half-page-up^" --expect ^"ctrl-c,ctrl-q,alt-l,esc,ctrl-s,ctrl-v,ctrl-t,alt-q,ctrl-g^" --header ^":: ^<^[[38;2;255;235;205mctrl-g^[[0m^> to ^[[38;2;255;64;64mDisable .gitignore^[[0m^" --preview-window ^"nohidden:right:0^" --border ^"none^" --prompt ^"~\AppData\Local\nvim\\^" --print-query --preview ^"set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=5 , debug=true}^^^)^^\^" -- {}^" > ^"C:\Users\pcx\AppData\Local\Temp\nvim.0\jV60NL\8^"
[Fzf-lua]: FZF_DEFAULT_COMMAND: set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime& ^"C:/Program Files/Neovim/bin/nvim.exe^" -n --headless --clean --cmd ^"lua loadfile^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/libuv.lua]]^)^(^).spawn_stdio^({color_icons = true, g = {_fzf_lua_server = \^"\\\\.\\pipe\\fzf-lua.1707975981.11548.1\^", _devicons_path = \^"C:/Users/pcx/AppData/Local/nvim-data/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua\^"}, cmd = \^"fd --color=never --type f --hidden --follow --exclude .git\^", git_icons = true, debug = \^"v\^", _base64 = false, file_icons = true},[==[return require^(\^"make_entry\^"^).file]==],[==[return require^(\^"make_entry\^"^).preprocess]==]^)^" || break
[Fzf-lua]: fzf cmd: fzf --ansi --info ^"default^" --height ^"100^%^" --layout ^"reverse^" --multi --bind ^"ctrl-a:beginning-of-line,ctrl-e:end-of-line,alt-a:toggle-all,f3:toggle-preview-wrap,f4:toggle-preview,shift-down:preview-page-down,ctrl-z:abort,ctrl-u:unix-line-discard,zero:execute-silent^(mkdir ^^\^"C:/Users/pcx/AppData/Local/Temp/nvim.0/jV60NL/9^^\^" ^&^& set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=8 , debug=true}^^^)^^\^" -- ^),ctrl-f:half-page-down,shift-up:preview-page-up,ctrl-b:half-page-up^" --expect ^"ctrl-c,ctrl-q,alt-l,esc,ctrl-s,ctrl-v,ctrl-t,alt-q,ctrl-g^" --header ^":: ^<^[[38;2;255;235;205mctrl-g^[[0m^> to ^[[38;2;255;64;64mDisable .gitignore^[[0m^" --preview-window ^"nohidden:right:0^" --border ^"none^" --prompt ^"~\AppData\Local\nvim\\^" --print-query --preview ^"set VIMRUNTIME=C:/Program Files/Neovim/share/nvim/runtime^& ^^\^"C:/Program Files/Neovim/bin/nvim.exe^^\^" -n --headless --clean --cmd ^^\^"lua loadfile^^^([[C:/Users/pcx/AppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]]^^^)^^^(^^^).rpc_nvim_exec_lua^^^({fzf_lua_server=[[\\.\pipe\fzf-lua.1707975981.11548.1]], fnc_id=7 , debug=true}^^^)^^\^" -- {}^" > ^"C:\Users\pcx\AppData\Local\Temp\nvim.0\jV60NL\11^"
```

**Comment by ibhagwan** [comment]
Ty @TheLeoP, I was able to reproduce the issue,  my neovim was installed by scoop in a path that contained no spaces, once I installed neovim in `C:\Program Files\Neovim` I have the exact same, I'm still confused why as the escape sequence looks perfect, probably somehing silly which I'll solve easily tomorrow.

**Comment by ibhagwan** [comment]
@TheLeoP, the fix was indeed easy, turns out I also needed to escape spaces with carets in my custom cmd.exe shellescape, can you try https://github.com/ibhagwan/fzf-lua/commit/1c696d9dcd2c351a693054846b55b1d4f7a8d013 and lmk if that fixes your issue?

**Comment by TheLeoP** [comment]
Thanks. The commit is working as expected :D. Most things seems to be working.

Back to an old problem, are you able to reproduce not being able to move between entries of `:FzfLua buffers` using `<c-n>` and `<c-p>`?

**Comment by ibhagwan** [comment]
> Thanks. The commit is working as expected :D. Most things seems to be working.
> 
> Back to an old problem, are you able to reproduce not being able to move between entries of `:FzfLua buffers` using `<c-n>` and `<c-p>`?

I did not forget about that and tested it but was not able to reproduce, I think this is something related to your env, my ctrl-n/p work as expected.

**Comment by TheLeoP** [comment]
> I think this is something related to your env, my ctrl-n/p work as expected.

Even on `:FzfLua buffers`? ctrl-n/p worked fine for all the other commands I tested, but not `buffers`. I'll try to come up with a minimal repro.

**Comment by ibhagwan** [comment]
> Even on `:FzfLua buffers`? ctrl-n/p worked fine for all the other commands I tested, but not `buffers`. I'll try to come up with a minimal repro.

![Peek 2024-02-15 02-18](https://github.com/ibhagwan/fzf-lua/assets/59988195/885420ae-c3c1-4204-929e-821b5c4be4d8)

**Comment by ibhagwan** [comment]
Windows branch was merged, closing.
