### ISSUE TITLE
Any way to remove the action keybind header above/below prompt

### ISSUE THREAD

**Issue by SwayKh** [ibhagwan/fzf-lua#1039]
![1707738635_grim](https://github.com/ibhagwan/fzf-lua/assets/59339401/fe20c396-6bf2-4bd8-8d7b-741b7e4dcbe7)

Is there a way to remove header showing the actions keybind? Sorry I don't exactly know what's that called and it's hard to find any info about it. I did go through the documentations and tried some toggles that looked related but Didn't work.

Under `fzf_opts` setting the `[--header]` flag to any string seems to work for some prompts like keymaps, colorschemes. but not for find-files, git-files, buffers. Also setting it to empty string shows `--header-line=1` and setting it to just `" "` creates a empty line above the prompt. 
Is there a way to disable this altogether.

PS: This is unrelated but how can I achieve the layout like `FzfLua commands` has, built the preview inside a window, without highlighting? I wasn't able to find the layout options in the default options file.
![1707740040_grim](https://github.com/ibhagwan/fzf-lua/assets/59339401/62fb01bc-6ca1-4f95-a2ce-9c384f22e403)

**Comment by ibhagwan** [comment]
> Is there a way to remove header showing the actions keybind? Sorry I don't exactly know what's that called and it's hard to find any info about it. I did go through the documentations and tried some toggles that looked related but Didn't work.

Search for `no_header`, `no_header_i`, similar question last week in  #1031.

> This is unrelated but how can I achieve the layout like FzfLua commands has, built the preview inside a window, without highlighting? I wasn't able to find the layout options in the default options file.

In-term previewed are called native, try the profile `fzf-native` from `:FzfLua profiles` (which uses the `bat` previewerr), if you wish to remove highlighting completely use the `cat` or `head` previewer, for example `:FzfLua files previewer=cat`.

To learn how to set these options permanently (via `setup`) explore the profiles config files under:
https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/profiles/README.md

**Comment by SwayKh** [comment]
That all worked!

I *did* find the `no_header` and `no_header_i` toggles in the documentation but I set them in the grep opts table and that didn't seem to work(my bad, I was testing it with `:FzfLua files`, so of course it didn't work), But using in keybinds when calling `FzfLua files` seem to work.

And `fzf-native` profile is exactly what I wanted it to look. And highlights look fine so that's no problem.

Thanks for all the quick help, And Thanks for this amazing plugin!
Have a nice day

**Comment by ibhagwan** [comment]
Thank you for you kind words.
