### ISSUE TITLE
[Windows] `:FzfLua buffers` fails - Refers to mkfifo

### ISSUE THREAD

**Issue by ColinKennedy** [ibhagwan/fzf-lua#1041]
### Info

- Operating System: Windows 10
- Shell: cmd
- Terminal: Command Prompt
- `nvim --version`: 0.9.1
- `fzf --version`: 0.27.2

<details>
<summary>fzf-lua configuration</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
	"ibhagwan/fzf-lua",
	-- optional for icon support
	dependencies = { "nvim-tree/nvim-web-devicons" },
	config = function()
	  -- calling `setup` is optional for customization
	  require("fzf-lua").setup({})
	end
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```
</details>

### Description 
- `nvim -u minimal_init.lua`
- Call `:FzfLua buffers`
- 
You get this error

```
E5108: Error executing lua ....repro/plugins/fzf-lua/lua/fzf-lua/providers/buffers.lua:211: Vim:E475:
Invalid value for argument cmd: 'mkfifo' is not executable
stack traceback:
        [C]: in function 'fzf_exec'
        ....repro/plugins/fzf-lua/lua/fzf-lua/providers/buffers.lua:211: in function <....repro/plugin
s/fzf-lua/lua/fzf-lua/providers/buffers.lua:171>
        ...orinkite/temp/.repro/plugins/fzf-lua/lua/fzf-lua/cmd.lua:78: in function 'run_command'
        ...orinkite/temp/.repro/plugins/fzf-lua/lua/fzf-lua/cmd.lua:100: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

**Comment by ColinKennedy** [comment]
Seems to happen for other commands as well, like `:FzfLua marks`

**Comment by ibhagwan** [comment]
If seems you’re using the main branch, Windows is still in beta, requires the use of [windows branch](https://github.com/ibhagwan/fzf-lua/tree/windows)

**Comment by ColinKennedy** [comment]
Oh whoops, I'll try again the next time I'm at a windows machine.

**Comment by ColinKennedy** [comment]
Confirmed working. It's a bit slow on my end but I suspect it's related to my fzf install / Windows and not the plugin. Thanks!

**Comment by ibhagwan** [comment]
> Confirmed working. It's a bit slow on my end but I suspect it's related to my fzf install / Windows and not the plugin. Thanks!

I also find a bit slow but that’s probably partly because I’m on a really slow VPS, aside from that, having to spawn everything via `cmd.exe` impacts the startup of every operation (even preview triggers), I did try fzf.vim and experienced the same thing (as it also has to spawn a term command via cmd.exe) so I’m not sure what I can do about it, even `cmd /c echo…` is slow.

The interesting thing is that running WSL (void Linux) runs extremely well, after the initial slow startup of the WSL all commands are almost instantaneous as they are on Linux/Mac.

**Comment by ColinKennedy** [comment]
Yep, one of the reasons I'm pushing for fzf-lua is that fzf.vim is unusably slow in Windows and I saw the recent post online calling for Windows testers. fzf-lua has been an overall been much more fluid and responsive and I'm loving it so far! I'll have to look into WSL, lots of people have recommended it to me.
