### ISSUE TITLE
Display filename only during live_grep

### ISSUE THREAD

**Issue by sainttttt** [ibhagwan/fzf-lua#1043]
I'd like to only display the filename in the search results for live_grep, and exclude the matched text in the list of files. I'm able to do this with this code:

`vim.keymap.set("n", "gF", function() fzf_lua.live_grep({ cmd = "rg2() { export LANG=en_US.UTF-8; rg  --column --no-ignore --line-number --no-heading --color=always --smart-case --max-columns=4096 -e  \"$@\" | cut -d':' -f1-2; }; rg2" }) end)`

But the issue is in the preview, the cursor doesn't move to the matched word, just the matched line. Is there a way to restore the default functionality of getting the cursor to move to the matched position, but only display the filenames without all the matched text? Thanks!

**Comment by sainttttt** [comment]
I fixed it with this

`vim.keymap.set("n", "gF", function() fzf_lua.live_grep({ cmd = "rg2() { export LANG=en_US.UTF-8; rg  --column --no-ignore --line-number --no-heading --color=always --smart-case --max-columns=4096 -e  \"$@\" | cut -d':' -f1-3; }; rg2" }) end)`

**Comment by ibhagwan** [comment]
IMHO, this is better solved with `--with-nth` (search the issues to see how to use), you can hide whichever part of the string you want without extra commands and without potentially  affecting anything else.
