### ISSUE TITLE
Is there a way to specify a default selected option?

### ISSUE THREAD

**Issue by Einenlum** [ibhagwan/fzf-lua#1045]
I was trying to make a PR to change the way `FzfLua colorschemes` works: I think it would be nice to set the current colorscheme as selected when it opens.

Right now, given that I use the `forestbones` colorscheme:

![1](https://github.com/ibhagwan/fzf-lua/assets/5675200/16b8bcca-88af-4c37-928b-0b8189c0f1e1)

If I launch `FzfLua colorschemes` it starts with `alduin` (because it's the first item in my list):

![2](https://github.com/ibhagwan/fzf-lua/assets/5675200/cb4c99d5-699b-4095-9256-2f81270c25bb)

I thought it would be quite simple to change this behavior, but I couldn't find an easy way to this in the code/issues/wiki. Is it something I should do directly in the colorschemes provider with custom logic? Is there a more "global" option to set a default selected value from the outside?

Thanks!

**Comment by ibhagwan** [comment]
No such option currently but very easy to implements, just need to insert the current scheme as first entry in the colors table and delete it from the other index:
https://github.com/ibhagwan/fzf-lua/blob/91ec17b4fd0d810599f054eef08db967a0457fbf/lua/fzf-lua/providers/colorschemes.lua#L22-L25

I leave it up to upi if you wish to become a contributor or let me handle it.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d8643f1e75cee43ae95a5a748bdcc6c3e9b38145

@Einenlum, should do what you want in regards to `colorschemes` within the limitations of our discussion.

**Comment by Einenlum** [comment]
Awesome, thank you very much @ibhagwan <3
