### ISSUE TITLE
Be able to use `Home` and `End` keys

### ISSUE THREAD

**Issue by Einenlum** [ibhagwan/fzf-lua#1046]
I use very often `Home` and `End` keys from my keyboard as "start" and "end" ways to navigate, whether it's in my terminal or my browser.

These keys don't seem to be doing anything in Fzf Lua and it would be quite cool if it was supported to go back to the start of the list or go to the end.

**Comment by ibhagwan** [comment]
Read `man fzf`, you can already do that, add new bindings into `keymap.fzf`, `home='first', end='last'` and you’ll get what you want.

**Comment by Einenlum** [comment]
Perfect, thanks!
