### ISSUE TITLE
Suggestion for beating latency / typing feedback - Debounced syntax highlighting

### ISSUE THREAD

**Issue by ColinKennedy** [ibhagwan/fzf-lua#1047]
While using `:FzfLua files`, I'm unable to type in the prompt area if a large file ends up in the preview. I tracked it down and the slowness comes from the previewer. So I added `require("fzf-lua").setup({ files = {previewer = "cat"}})` and now it is smooth.

This got me thinking whether fzf-lua's previewer could benefit from how https://github.com/kevinhwang91/nvim-bqf approaches previews. In nvim-bqf there's no delay while scrolling or typing. But if you rest on any file for > `delay_syntax` (default: 50 ms) then the previewer renders syntax highlighting for the view. It doesn't seem that fzf-lua has that and thought it'd be a great addition. What do you think?

**Comment by ibhagwan** [comment]
A denouncing mechanism already exists, the default preview denounce delay matches that of fzf which js 100ms, if you wish to change that set `winopts.preview.delay` to something larger, try running `:FzfLua files winopts.preview.delay=1000` and notice the difference.

**Comment by ColinKennedy** [comment]
I missed that option, thanks. Still it doesn't explain why continuous typing is interrupted in that case. I'll check out that option once I'm back at my main machine and see how much it improves

**Comment by ibhagwan** [comment]
> Still it doesn't explain why continuous typing is interrupted in that case. I'll check out that option once I'm back at my main machine and see how much it improves

It all would depend how fast you type as 100ms is a small timeout, try it out and lmk.

**Comment by ColinKennedy** [comment]
I had a look at `require("fzf-lua").setup({ winopts = {preview = {delay = 250}}})`. It does improve typing responsiveness but at the expense of being able to view files. `winopts.preview.delay` differs from the original suggestion. In the suggestion above, users can still see the file's contents immediately (because opening a buffer is very quick in Vim). The slow part, parsing and syntax highlighting, is what gets debounced so you can still briefly view files without paying the full cost. `winopts.preview.delay` in contrast doesn't let you view the file in a preview without syntax highlighting. Would you be up for a "syntax highlight debounce"?

**Comment by ibhagwan** [comment]
Then take a look at `previewers.bulltin.syntax_delay`
https://github.com/ibhagwan/fzf-lua/blob/91ec17b4fd0d810599f054eef08db967a0457fbf/lua/fzf-lua/defaults.lua#L171

**Comment by ColinKennedy** [comment]
Beautiful, works great. Thank you!

**Comment by ibhagwan** [comment]
> Beautiful, works great. Thank you!

Actually it’s not working as I wanted it, it can queue too many syntax commands for the wrong buffers, I have to make sure to syntax only the current loaded buffer.

**Comment by ibhagwan** [comment]
Can you try out https://github.com/ibhagwan/fzf-lua/commit/07f603473b4aed6c238b2331fe0e09964c5d0af1 under the windows branch? I don't want to add more commits to main and I'm planning on merging the windows branch today or tomorrow?

**Comment by ColinKennedy** [comment]
It seems to be working fine for me. One thing that I did notice in both the `windows` and `main` branch is that if you type something, pause, and then attempt to backspace or type again, the syntax trigger will block typing. So you get periodic start-and-stop while typing things. Unless the syntax delay is high, it can be difficult to predict when the slowdown will happen since typing speed tends to vary.

You can see it in the video below. I type "asdf" repeatedly and then immediately backspace and there's no pause in typing. Then I type "asdf", pause, then try to backspace. It gets one character in, creating "asd", then I have to wait for the full syntax highlight. I'm trying to still type but the inprogress highlighting prevents it.

https://github.com/ibhagwan/fzf-lua/assets/10103049/cd5912a7-ae0a-48ea-9389-6f6df828a809

Not sure if this is the sort of feedback you're looking for. Just something I noticed. If you want me to check out anything specific, I'm happy to test.

**Comment by ibhagwan** [comment]
> One thing that I did notice in both the windows and main branch is that if you type something, pause, and then attempt to backspace or type again, the syntax trigger will block typing.

I’m not sure how I can overcome that, the preview runs on the main thread as the syntax trigger, when it gets triggered on a big file it will cause a delay, I can’t control that as that’s neovim, I can only control the trigger delay and making sure only one gets triggered for the currently selected buffer, perhaps `bat` previewer is a better for for you? It runs in the external process and is an external binary.

**Comment by ColinKennedy** [comment]
I figured it runs in the main thread but thought to mention it just in case. And yep, I'll probably use bat instead
