### ISSUE TITLE
[feature] ability to provide -1 for colors

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1048]
At first i tried this plugin last weekends and i absolutely love this one. Great job, thank you!

About my problem. I like minimal style and don't like gutter in fzf. I found solution to delete this one, but it's a little bit tricky.

Before:
<img width="983" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/53742299/19b11919-e500-4717-90d0-eb56ab467585">

With setting:
```lua
require('fzf-lua').files {       
	fzf_args = '--color=gutter:-1'
}
```
<img width="983" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/53742299/b123ac22-4948-443f-a7f2-a115797f60e5">

I would like to do this with `fzf_color` option.

**Comment by ibhagwan** [comment]
The 3rd argument in the table is passed raw (#413), so this would do what you’re asking:
```lua
fzf_colors = {
  ["gutter"] = { nil, nil, -1 },
}
```
Alternatively, you can color it with the same bg as neovim with:
```lua
fzf_colors = {
  ["gutter"] = { "bg", "Normal" },
}
```

**Comment by kaiphat** [comment]
Thank you! It works!
