### ISSUE TITLE
Change tab select key

### ISSUE THREAD

**Issue by bwintertkb** [ibhagwan/fzf-lua#1054]
Hey guys,

first of all great plugin! it has replaced and enhanced telescope for me :) I did have one question, is there a way in which I can modify the key used to add selections to the quick fix menu? I have a habit of moving down the options using tab and shift tab to move up (but tab add the item to the quick fix). Is there a way that I can change that keybind?

Thanks again!

**Comment by ibhagwan** [comment]
Fzf-lua defaults do not contain a default binding for tab/shift-tab, these come from fzf’s defaults:
https://github.com/ibhagwan/fzf-lua/blob/3b3cc17c7bb91f6bbef7166c0756f89a189c4db4/lua/fzf-lua/defaults.lua#L84-L97

You can modify fzf’s keybinds under `keymap.fzf`, the default is `tab='select'`, you want to add `['tab']='down'` (and shift-tab for up), `man fzf` to see all bind options.

**Comment by bwintertkb** [comment]
Legend thank you!

**Comment by ibhagwan** [comment]
> Legend thank you!

Great, closing :)

Feel free to reopen if you need further clarifications.
