### ISSUE TITLE
[Windows] Interface doesn't open when `shellslash` option is set

### ISSUE THREAD

**Issue by dddddjent** [ibhagwan/fzf-lua#1055]
### Info

- Operating System: Windows10 22H2
- Shell: PowerShell7
- Terminal: Wezterm
- `nvim --version`: NVIM v0.10.0-dev-1038+gc3e176f6e
- `fzf --version`: 0.46.1 (3c0a630)

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({ "telescope" })
```
</details>

### Description 
There are 2 problems.
The first one: 
```
E5108: Error executing lua: ... Files (x86)/nvim/share/nvim/runtime/lua/vim/_system.lua:80: timeout must be >= 0
stack traceback:
	[C]: in function 'wait'
	... Files (x86)/nvim/share/nvim/runtime/lua/vim/_system.lua:80: in function 'wait'
	...pData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/utils.lua:933: in function 'io_system'
	...pData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/utils.lua:996: in function 'fzf_version'
	...Data/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/config.lua:485: in function 'normalize_opts'
	...l/nvim-data/lazy/fzf-lua/lua/fzf-lua/providers/files.lua:44: in function 'files'
```
So I changed this line `local proc = vim.system(cmd):wait()` to `local proc = vim.system(cmd,{timeout=1000}):wait()` and the error disappeared.

The second one:
After the modification above, whatever window I try to open will quickly disappear and the only text in that window is "The syntax of the command is incorrect".

**Comment by ibhagwan** [comment]
This doesn't reproduce with the latest nightly, moreover I can see that the call for `vim.wait` in `runtime/lua/vim/_system.lua` has moved to line 95 and has a default timeout:
https://github.com/neovim/neovim/blob/0fcbda59871ebc5fc91cac7fa430a4a93f6698c2/runtime/lua/vim/_system.lua#L95

Can you update your neovim to the latest nightly (NVIM v0.10.0-dev-2445+g2e1f5055a) and try again?

**Comment by dddddjent** [comment]
The first problem has gone, but the second one still exists.

**Comment by ibhagwan** [comment]
> The first problem has gone, but the second one still exists.

Any other error messages in `:messages`? Does this happen to all pickers or just files? Did you try grep? LSP? How about something as simple as:
```lua
:= require'fzf-lua'.fzf_exec({ 1, 2, 3 })
```

**Comment by ibhagwan** [comment]
Also do you have `rg` or `fd` installed? Can you post the output of `:FzfLua files debug=true` (in `:messages`)?

**Comment by dddddjent** [comment]
Now I've found the problem. I shouldn't do `vim.opt.shellslash = true`. I can't remember why would I add this to my configuration. Removed this and all the problems have gone.

**Comment by ibhagwan** [comment]
> Now I've found the problem. I shouldn't do `vim.opt.shellslash = true`. I can't remember why would I add this to my configuration. Removed this and all the problems have gone.

Ty for letting me know, I still have to check why this causes the problem and either fix it or alert the user of the existence of this option.

**Comment by ibhagwan** [comment]
@dddddjent  with https://github.com/ibhagwan/fzf-lua/commit/fcf9806a423d0083a38abaf9c641e2b805186e98 this issue can be safely closed, ty for letting me know about this rather peculiar option :-)

**Comment by dddddjent** [comment]
Now I remember why I set this. Toggle term requires this to properly pipe commands into temrinal under Windows.

**Comment by ibhagwan** [comment]
> Now I remember why I set this. Toggle term requires this to properly pipe commands into temrinal under Windows.

I’m pretty sure this is better solved on toggleterm side with a better escaping sequence but anyhow, fzf-lua should work with this option.

Btw, I noticed Telescope also has some issues with the option, for example, the help_tags picker doesn’t work when it’s turned on.

**Comment by ibhagwan** [comment]
@dddddjent searching through the toggleterm issues, it does seem that `shellslash` is a workaround as the author never attempted to solve Windows https://github.com/akinsho/toggleterm.nvim/issues/236

**Comment by dddddjent** [comment]
> @dddddjent searching through the toggleterm issues, it does seem that `shellslash` is a workaround as the author never attempted to solve Windows [akinsho/toggleterm.nvim#236 (comment)](https://github.com/akinsho/toggleterm.nvim/issues/236#issuecomment-1146569561)

Yeah I had to tweak a lot to make nvim and its plugins work on Windows
