### ISSUE TITLE
`FZF_PREVIEW_COLUMNS` not recognized on Windows 11

### ISSUE THREAD

**Issue by yavorski** [ibhagwan/fzf-lua#1056]
### Info

- Operating System: `Windows-11`
- Shell: `pwsh core`
- Terminal: `Windows Terminal`
- `nvim --version`: ` v0.9.5`
- `fzf --version`: `0.46.1`
- `delta --version`:  `0.16.5`

- [ ] The issue is reproducible with `mini.sh`

<details open>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  lsp = {
    code_actions = {
      previewer = "codeaction_native",
      preview_pager = [[ delta --hunk-header-style="omit" --file-style="omit" --width=$FZF_PREVIEW_COLUMNS ]],
    }
  }
})
```
</details>

### Description 

It looks like `$FZF_PREVIEW_COLUMNS` is not recognized from `fzf-lua`.
The same setup works on `wsl` and `linux`, it does not work on `windows`.
Any workaround would be helpful. 
10x!

![image](https://github.com/ibhagwan/fzf-lua/assets/3436517/fa27c772-0fd6-4507-8665-7ef5253b2e0c)

**Comment by ibhagwan** [comment]
On Windows, fzf-lua uses cmd.exe to wrap its commands, that includes preview triggers, cmd.exe doesn’t know about `$`, you need to use the Windows convention of `%FZF_PREVIEW_COLUMNS%`, here’s how I set it up on my personal config:
https://github.com/ibhagwan/nvim-lua/blob/b01e4d4be35896156846eb35cc624b67ad0d71de/lua/plugins/fzf-lua/setup.lua#L224-L226

**Comment by ibhagwan** [comment]
Perhaps for simplicity’s sake I can make the substitution by code so uses don’t have to worry about that.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b697e269475b07c191afcb89fc8d4708d9b9f8a4

@yavorski, latest commit on main/windows (both branches are the same now) takes care of automatic var substitution so you can still use `$FZF_PREVIEW_COLUMNS` .
