### ISSUE TITLE
[feauture] reset cursor position

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1059]
Have i nice day!

I migrated from telescope and i like behaviour, when cursor position is reset is i type something in prompt.
Will be great if i could set this ability via config.

Thank you!

**Comment by ibhagwan** [comment]
This would be controlled by fzf (the binary) and not fzf-lua, you can probably do that by adding an fzf bind for `change`, read man fzf and see if there is an action that does what you want, you can then add it with `fzf_args=--bind=change:…`

**Comment by ibhagwan** [comment]
This seems to do what you want:
```lua
:= require"fzf-lua".files { fzf_args = "--bind=change:first" }
```

**Comment by ibhagwan** [comment]
You can add  `fzf_args` to the original setup call:
```lua
:= require"fzf-lua".setup { fzf_args = "--bind=change:first" }
```

**Comment by kaiphat** [comment]
Nice, it works. I tried to add this to `fzf_opts`. Thank you!

**Comment by ibhagwan** [comment]
> Nice, it works. I tried to add this to `fzf_opts`. Thank you!

`fzf_opts["--bind"]` gets overidden by when generating the bind string from `keymap.fzf`, technicaly you could add:
```lua
require("fzf-lua").setup({
  keymap = { fzf = ["change"] = "first" }  },
})
```

But since `keymap.fzf` doesn't merge with the defaults you'd need to add all the default binds as well.
