### ISSUE TITLE
Small README change

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/fzf-lua#106]
Hello. I was following the README to get setup with fzf-lua. Firstly, thank you for doing a great job on this. Under `Commands` -> `Git`, it shows `git_branch` as a possible command. I think this should be changed to `git_branches` right? Again, very small change, but I thought I should mention it.

**Comment by ibhagwan** [comment]
Good catch.

You’re welcome to submit a PR for it if you’d like to be a contributor, otherwise I’ll address this in the next commit.

**Comment by hqkhan** [comment]
Sure thing. I'd be happy to!

**Comment by hqkhan** [comment]
#107 addresses this minor change.

**Comment by ibhagwan** [comment]
Merged, tysm! :)
