### ISSUE TITLE
buffer list is not shown

### ISSUE THREAD

**Issue by chenyuhang55555** [ibhagwan/fzf-lua#1063]
### Info

- Operating System: Ubuntu 5.4.0-146-generic
- Shell: zsh
- Terminal: iTerm2
- `nvim --version`: v0.7.0
- `fzf --version`: 0.46.1 (3c0a630)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require'fzf-lua'.setup {
        global_resume = true,
        global_resume_query = true,
        winopts = {
                height = 0.95,
                width = 0.95,
                preview = {
                        scrollbar = 'float',
                },
                fullscreen = false,
                vertical       = 'down:45%',      -- up|down:size
                horizontal     = 'right:60%',     -- right|left:size
                hidden         = 'nohidden',
                title = true,
        },
        keymap = {
                -- These override the default tables completely
                -- no need to set to `false` to disable a bind
                -- delete or modify is sufficient
                builtin = {
                        ["<c-f>"]      = "toggle-fullscreen",
                        ["<c-r>"]      = "toggle-preview-wrap",
                        ["<c-p>"]      = "toggle-preview",
                        ["<c-y>"]      = "preview-page-down",
                        ["<c-l>"]      = "preview-page-up",
                        ["<S-left>"]   = "preview-page-reset",
                },
                fzf = {
                        ["esc"]        = "abort",
                        ["ctrl-c"]     = "unix-line-discard",
                        ["ctrl-y"]     = "half-page-down",
                        ["ctrl-l"]     = "half-page-up",
                        ["ctrl-i"]     = "beginning-of-line",
                        ["ctrl-a"]     = "end-of-line",
                        ["alt-a"]      = "toggle-all",
                        ["f3"]         = "toggle-preview-wrap",
                        ["f4"]         = "toggle-preview",
                        ["shift-down"] = "preview-page-down",
                        ["shift-up"]   = "preview-page-up",
                        ["ctrl-j"]     = "down",
                        ["ctrl-k"]     = "up",
                },
        },
  previewers = {
    cat = {
      cmd             = "cat",
      args            = "--number",
    },
    bat = {
      cmd             = "bat",
      args            = "--style=numbers,changes --color always",
      theme           = 'Coldark-Dark', -- bat preview theme (bat --list-themes)
      config          = nil,            -- nil uses $BAT_CONFIG_PATH
    },
    head = {
      cmd             = "head",
      args            = nil,
    },
    git_diff = {
      cmd_deleted     = "git diff --color HEAD --",
      cmd_modified    = "git diff --color HEAD",
      cmd_untracked   = "git diff --color --no-index /dev/null",
      -- pager        = "delta",      -- if you have `delta` installed
    },
    man = {
      cmd             = "man -c %s | col -bx",
    },
    builtin = {
      syntax          = true,         -- preview syntax highlight?
      syntax_limit_l  = 0,            -- syntax limit (lines), 0=nolimit
      syntax_limit_b  = 1024*1024,    -- syntax limit (bytes), 0=nolimit
    },
  },
  files = {
    -- previewer      = "bat",          -- uncomment to override previewer
                                        -- (name from 'previewers' table)
                                        -- set to 'false' to disable
    prompt            = 'Files❯ ',
    multiprocess      = true,           -- run command in a separate process
    git_icons         = true,           -- show git icons?
    file_icons        = true,           -- show file icons?
    color_icons       = true,           -- colorize file|git icons
    -- executed command priority is 'cmd' (if exists)
    -- otherwise auto-detect prioritizes `fd`:`rg`:`find`
    -- default options are controlled by 'fd|rg|find|_opts'
    -- NOTE: 'find -printf' requires GNU find
    -- cmd            = "find . -type f -printf '%P\n'",
    find_opts         = [[-type f -not -path '*/\.git/*' -printf '%P\n']],
    rg_opts           = "--color=never --files --hidden --follow -g '!.git'",
    fd_opts           = "--color=never --type f --hidden --follow --exclude .git",
  },
  buffers = {
    prompt            = 'Buffers❯ ',
    file_icons        = true,         -- show file icons?
    color_icons       = true,         -- colorize file|git icons
    sort_lastused     = true,         -- sort buffers() by last used
  },
}
```

</details>

### Description 
FzfLua cannot show the current buffer list, even missing my active buffer.
<img width="1887" alt="Screenshot 2024-02-28 at 13 19 10" src="https://github.com/ibhagwan/fzf-lua/assets/24860629/0f4daac6-c32d-41f5-8b83-a378f028a154">
while I do have my current buffer, listed by :buffers
<img width="1887" alt="Screenshot 2024-02-28 at 13 18 46" src="https://github.com/ibhagwan/fzf-lua/assets/24860629/c63872cc-8e96-4284-b1f9-575e7bf2998f">

This issue appears after I updated my vim plugins recently without changing my config (I haven't done this in ~2 years. It worked fine before). Please let me know if I missed providing any necessary info.

**Comment by ibhagwan** [comment]
I see you didn't check the `The issue is reproducible with mini.sh` - have you tried with mini.sh and it worked as expected or you just skipped this part?

> This issue appears after I updated my vim plugins recently without changing my config (I haven't done this in ~2 years. It worked fine before)

You're using neovim 0.7 which is pretty old by now, this could be an issue related from updates of other plugins as well, for example,  `nvim-web-devicons` says it requires neovim >= 0.7 but in my experience it doesn't work properly unless you're on 0.8.

Can you try changing `file_icons=false` and `git_icons=false` and let me know if that helps?
Also does `files` work as expected?

**Comment by ibhagwan** [comment]
Just checked nvim-treesitter requires 0.9.2, nvim-lspconfig requires 0.8, there could be a hidden crash here related to number of underlying plugins you updated that no longer support 0.7.

**Comment by chenyuhang55555** [comment]
@ibhagwan Thank you for your quick response. I'm not familiar with these extensions before so I've spent some time exploring. Tried the following:
- Updated neovim to 0.9.5
- Updated nvim-treesitter

Old issue is gone (buffers will show correctly). 
New issue is introduced unfortunately - 

`E5108: Error executing lua ...g/nvim/plugged/fzf-lua/lua/fzf-lua/providers/buffers.lua:211: ....chen/.config/nvim/plug
ged/fzf-lua/lua/fzf-lua/utils.lua:890: title must be string or array
stack traceback:
        [C]: in function 'fzf_exec'
        ...g/nvim/plugged/fzf-lua/lua/fzf-lua/providers/buffers.lua:211: in function <...g/nvim/plugged/fzf-lua/lua/fz
f-lua/providers/buffers.lua:171>
        ...ng.chen/.config/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:78: in function 'run_command'
        ...ng.chen/.config/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:100: in function 'load_command'
        [string ":lua"]:1: in main chunk`

This error msg shows up when I run `:FzfLua buffers` the first time.
<img width="1420" alt="Screenshot 2024-02-28 at 18 50 27" src="https://github.com/ibhagwan/fzf-lua/assets/24860629/eaf757b2-845d-4f81-ada3-58c91a4fc6f4">


If I hit enter and run the same command again, it displays weirdly. After pressing esc, it seems to quit, but I lose my buffer and have to quit nvim, so it's barely usable.
<img width="1417" alt="Screenshot 2024-02-28 at 18 44 58" src="https://github.com/ibhagwan/fzf-lua/assets/24860629/ce84996d-ceb9-45d9-815f-f76b72a8915e">


> I see you didn't check the `The issue is reproducible with mini.sh` - have you tried with mini.sh and it worked as expected or you just skipped this part?

fzf-lua works fines in sandbox, so it's not reproducible

> Can you try changing `file_icons=false` and `git_icons=false` and let me know if that helps? Also does `files` work as expected?

False git_icons, file_icons don't help. `FzfLua files` gives the same issue

**Comment by ibhagwan** [comment]
Remove `title = true` under your `winopts` and the issue will be resolved.

**Comment by chenyuhang55555** [comment]
@ibhagwan Bravo, issue solved. Thank you!

**Comment by ibhagwan** [comment]
> @ibhagwan Bravo, issue solved. Thank you!

Great, Ty for the update @chenyuhang55555!
