### ISSUE TITLE
[Feature Request] nvim-notify support

### ISSUE THREAD

**Issue by ofseed** [ibhagwan/fzf-lua#1065]
The only reason I could not replace telescope with fzf-lua now is nvim-notify only support telescope.
Could fzf-lua provide integration with fzf-lua so that users can search nvim-notify history like telescope?

**Comment by ibhagwan** [comment]
> The only reason I could not replace telescope with fzf-lua now is nvim-notify only support telescope. Could fzf-lua provide integration with fzf-lua so that users can search nvim-notify history like telescope?

How does Telescope support nvim-notify? Is it a Teslescope extension or code calling the Telescope API from within nvim-notify? If you can provide an example I can look into it.

**Comment by ofseed** [comment]
nvim-notify did that, you can show and search nvim-notify history like this:
![image](https://github.com/ibhagwan/fzf-lua/assets/61115159/cc303fe8-f836-46ee-adee-7775d29981cb)

And if I select a message and press '<CR>`, the message will be shown in a floating-window
![image](https://github.com/ibhagwan/fzf-lua/assets/61115159/0aa76adc-f2d0-4c30-bd56-7c20119a6ae7)

nvim-notify bundle with a telescope extension, here is how nvim-notify supports it: https://github.com/rcarriga/nvim-notify/blob/master/lua/telescope/_extensions/notify.lua.

**Comment by ibhagwan** [comment]
In this cas it’s better to open the feature request on the nvim-notify repository as the code should be written there.

Fzf-lua really cannot be any easier, if you feel like it you can probably write the PR to nvim-notify yourself
https://github.com/ibhagwan/fzf-lua/wiki/Advanced

**Comment by ibhagwan** [comment]
I’m going to close this issue as IMHO this code shouldn’t be in this repo and maintained by me, many plugins that have a fuzzy interface and support fzf-lua write the code using the API and maintain it themselves, for example , in dressing.nvim you can decide which backend to use telescope or fzf-lua, same thing for neoclip, obsidian and many other plugins.

**Comment by ofseed** [comment]
Thank you, maybe I will try to do that.

**Comment by ofseed** [comment]
After reading the docs, I found that it seems that no API can create a function or command so that I can call something like `:FzfLua notify` or `require("fzf-lua").notify()`. Would it be better to add such an API?

**Comment by ibhagwan** [comment]
> After reading the docs, I found that it seems that no API can create a function or command so that I can call something like `:FzfLua notify` or `require("fzf-lua").notify()`. Would it be better to add such an API?

As I mentioned the code should be in the nvim-notify side, what you’re describing is an addition to this plugin which isn’t the right place for this code.

**Comment by ofseed** [comment]
I know what you mean, my suggestion is to provide an API so that we can call these extended functions inside fzf-lua. Like, nvim-notify provided telescope integration by itself, but I can call `:Telescope notify` or `require("telescope").extensions.notify.notify()` to use the custom extension provided by nvim-notify.

There maybe no differences under the hood, but personally I think it is more convenient and beautifull.

**Comment by vinoff** [comment]
Sorry but from a user perspective:

- Is it currently possible to have access to nvim errors via fzf-lua?

**Comment by ibhagwan** [comment]
> Sorry but from a user perspective:
> 
> * Is it currently possible to have access to nvim errors via fzf-lua?

You’re welcome to submit a PR.

**Comment by vinoff** [comment]
> > Sorry but from a user perspective:
> > 
> > * Is it currently possible to have access to nvim errors via fzf-lua?
> 
> You’re welcome to submit a PR.

I know, you have said that elsewhere (?). Maybe you read my comment in a negative light, that was not the goal. I was just wondering if one can see nvim errors (whether rcarriga's notify or just from plain nvim) from fzf-lua.
