### ISSUE TITLE
Running neovim builtin commands like :q, :wqa, :wq and other..

### ISSUE THREAD

**Issue by qbnil** [ibhagwan/fzf-lua#1066]
Probably it's just me, but i couldn't seem to find the way to run these commands using fzf-lua. I want to replicate something similar to fine-cmdline if you know that plugin (https://github.com/VonHeikemen/fine-cmdline.nvim). I know that i can run these using my command history, but thats boring. Probably this should be somehow added to commands which you already have in misc. Thx in advance

**Comment by ibhagwan** [comment]
At first glance what you’re after is out of scope of this plugin, you can already find all the commands you executed with `command_history`, you can also edit these instead of running with ctrl-e, why would we need yet another floating window to run ex commands within fzf-lua, how is that related to fzf/fuzzy finding and what would be the benefit?

**Comment by qbnil** [comment]
Surely you don't need to add this, i just want you to guide me how could i possibly implement this, because it's enough plugins i have already, why would i need an extra one if i can possible make this work through fzf-lua

**Comment by ibhagwan** [comment]
> Agreed, it brings almost no effort, it's just for the looks, would be nice to be able to have a floating window to run the commands as you do it regularly

Who that would be nice that is something you can easily craft yourself with `nvim_open_win`, IMHO this is outside of this plugin’s scope nor would I want to maintain random functions unrelated to the core functionality of this plugin which is centered around fuzzy funding / fzf.

**Comment by qbnil** [comment]
Alright, thx anyways

**Comment by ibhagwan** [comment]
> Surely you don't need to add this, i just want you to guide me how could i possibly implement this, because it's enough plugins i have already, why would i need an extra one if i can possibly make this work through fzf-lua

You can explore the code in the plugin you linked above, I don’t see what benefit fzf-lua beings to the table here, this is a framework for running fzf not neovim UI, for that you have `nui.nvim` for example.

Just in case I’m missing something and you do need fzf, take a look at the API, running custom commands as as easy as:
```lua
:lua require'fzf-lua'.fzf_exec({1,2,3})
```

https://github.com/ibhagwan/fzf-lua/wiki/Advanced

**Comment by ibhagwan** [comment]
> Agreed, it brings almost no effort, it's just for the looks, would be nice to be able to have a floating window to run the commands as you do it regularly

What you can do is hijack the `command_history` and create a custom bind for executing the command from the prompt if you don’t find anything you like:
> pressing enter will run the selected command but `ctrl-x` will execute what’s in the prompt
```lua
require'fzf-lua'.setup({
  command_history = {
    actions = {
      ["ctrl-x"] = function (_, _)
        local query = require("fzf-lua").get_last_query()
        vim.cmd(query)
      end,
    },
  }
})
```

**Comment by qbnil** [comment]
> > Agreed, it brings almost no effort, it's just for the looks, would be nice to be able to have a floating window to run the commands as you do it regularly
> 
> While that might be nice that is something you can easily craft yourself with `nvim_open_win`, IMHO this is outside of this plugin’s scope nor would I want to maintain random functions unrelated to the core functionality of this plugin which is centered around fuzzy funding / fzf.

Wow, i didn't think about that one, no overhead at all, thx a bunch, worked like a churm, you killed it

**Comment by ibhagwan** [comment]
> Wow, i didn't think about that one, no overhead at all, thx a bunch, worked like a churm, you killed it

I'm assuming you mean the `ctrl-x` bind :-)

That's great! closing the issue.

**Comment by ibhagwan** [comment]
@qbnil, FYI with the latest commit (https://github.com/ibhagwan/fzf-lua/commit/5483f2fc95712b715acb5f5e94cd8e217df1d24c) I made the above snippet a tiny bit shorter:
```lua
require'fzf-lua'.setup({
  command_history = {
    actions = {
      ["ctrl-x"] = function (_, opts)
        vim.cmd(opts.last_query)
      end,
    },
  }
})

```

**Comment by qbnil** [comment]
Awesome, even better now
