### ISSUE TITLE
[Discuss] display value and actual value 

### ISSUE THREAD

**Issue by qanyue** [ibhagwan/fzf-lua#1072]
### Info

- Operating System: wsl ubuntu
- Shell:zsh 
- Terminal:weztern 
- `nvim --version`:nightly 
- `fzf --version`: 0.29 

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
                                 local x = require'fzf-lua'.make_entry.file(value, {file_icons=true, color_icons=true})
                                 if not x then 
                                     x = value
                                 end
                                fzf_cb(x, function()
                                    coroutine.resume(co)
                                end)
```
</details>

### Description 
I use make_entry to beautiy the file path ,but i found it difficult to recover the original path, I read the code ,it seems we have to use `:match()` to get true path ,will you consider set a actual  value to split it to simplify development ?

**Comment by ibhagwan** [comment]
> I use make_entry to beautiy the file path ,but i found it difficult to recover the original path, I read the code ,it seems we have to use :match() to get true path ,will you consider set a actual value to split it to simplify development ?

Adding another entry just for the true value would double the memory consumption of fzf and hinder performance, I only do that when it makes no big difference (for example `help_tags` has hidden value file the text file).

If you’re already using internal, why not use `path.entry_to_file` or disable the icons?

**Comment by ibhagwan** [comment]
> and will `fn_transform` to use such as lambda function to be applyed for every input when use fzf_cb?

I don’t see why not, that’s what happens in fzf-lua both multiprocess options (main neovim thread or external headless process).

**Comment by ibhagwan** [comment]
> for function type content it seems not work?

If you tell me in a bit more details what you’re trying to achieve and post your code I’ll be able to help more.

**Comment by ibhagwan** [comment]
> Someone want use Mini.visit for its oldfiles can use this code

I understand what you mean now, `fn_transform` is only used when processing the output of shell commands, you already have a processing function, you don’t need that`make_entry.file` in the loop (like you have commented), is the way to go.

**Comment by ibhagwan** [comment]
Btw, I would also add `opts.cwd` in order to make the paths relative but that’s personal preference.
