### ISSUE TITLE
[bug] Gutter background

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1076]
After last update i see gutter:
<img width="1056" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/53742299/5ddf749d-ea3c-4759-9133-c459e19536b7">

How it was before:
![image](https://github.com/ibhagwan/fzf-lua/assets/53742299/dc0305b7-59d6-4cd8-965b-cf519efc0424)

My settings:
```lua
			fzf_colors = {
				['fg'] = { 'fg', 'Comment' },
				['fg+'] = { 'fg', 'Comment' },
				['pointer'] = { 'fg', '@label' },
				['info'] = { 'fg', '@label' },
				['bg+'] = { 'bg', 'Visual' },
				['hl'] = { 'fg', '@label' },
				['hl+'] = { 'fg', '@label' },
				['gutter'] = { nil, nil, -1 },
			},
```

**Comment by ibhagwan** [comment]
Why did you close this issue? I’m assuming there has been a confusion with #1075?

I made some improvements to fzf_colors, if you want to pass only raw arg without specifying a color use a string instead:
```lua
['gutter'] = '-1'
```

**Comment by kaiphat** [comment]
> Why did you close this issue?

I'm sorry, i saw two the same issues, so i close one.

**Comment by ibhagwan** [comment]
> > Why did you close this issue?
> 
> I'm sorry, i saw two the same issues, so i close one.

no problem, if `['gutter'] = '-1'` we can close this issue as well.

**Comment by kaiphat** [comment]
Yes, it works as always :) Thank you)
