### ISSUE TITLE
List filename entries relative to cwd

### ISSUE THREAD

**Issue by sainttttt** [ibhagwan/fzf-lua#1079]
Is there a way for fzf-lua to display the filenames relative to the current working directory? Right now it seems the default behavior lists the filename including the cwd and possibly more. I'd just like to see the path relative to cwd if that would be possible at all. Thanks!

**Comment by ibhagwan** [comment]
> Is there a way for fzf-lua to display the filenames relative to the current working directory? Right now it seems the default behavior lists the filename including the cwd and possibly more. I'd just like to see the path relative to cwd if that would be possible at all. Thanks!

By default it should display relative paths, if you can provide more details I will be able to tell you why this isn't happening for you.

In any event, adding `{ cwd = <directory> }` to your call will make the paths relative to the directory, if you want to use the current working directory set it to `{ cwd = vim.loop.cwd() }`.

**Comment by sainttttt** [comment]
Thank you, I think you are right it was the default behavior. I've resolved the issue, thanks for the prompt reply!
