### ISSUE TITLE
Using `^` to search the beginning doesn't work properly

### ISSUE THREAD

**Issue by bigH** [ibhagwan/fzf-lua#1080]
### Info

- Operating System: macos
- Shell: zsh
- Terminal: iTerm2
- `nvim --version`:
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```
- `fzf --version`: `0.46.1 (brew)`

- [ ] The issue is reproducible with `mini.sh` (**never tried, but I don't expect it to be an issue**)

<details>
<summary>fzf-lua configuration</summary>

```lua
local fzf = require('fzf-lua')

local actions = fzf.actions
fzf.setup({
  'fzf-native',
  actions = {
    files = {
      ['default'] = actions.file_edit
    }
  },
  previewers = {
    git_diff = {
      pager = "delta --width=$FZF_PREVIEW_COLUMNS"
    }
  }
})

n('<LEADER>e', function()
  fzf.files({ cmd = 'fd' })
end)

n('<LEADER>E', function()
  fzf.files({ cmd = 'fd --no-ignore' })
end)
```
</details>

### Description 

I'm unable to search from the beginning of the string. See:
![not working](https://github.com/ibhagwan/fzf-lua/assets/2367531/c79b14c2-dff3-463f-ad7f-c8c8094a5287)

OTOH, if I include the folder icon in my search, it works:
![workaround](https://github.com/ibhagwan/fzf-lua/assets/2367531/cf80b092-77f0-4de8-be8c-67c2005d303a)

I expect the use of `^` to work despite dev icons.

**Comment by ibhagwan** [comment]
That’s because fzf doesn’t interpret the icon as not part of the string, if you want that or work add `file_icons = false`.

**Comment by ibhagwan** [comment]
By using the same logic fzf-lua uses for parsing the file entries we can utilize fzf's `--nth` (with `--delimiter`) to be able to ignore the icons in the search:
```lua
local fzf = require("fzf-lua")
fzf.files({
  git_icons = false,
	fzf_opts = {
    ["--delimiter"] = string.format("[:%s]", fzf.utils.nbsp),
    ["--nth"] = "2..",
  },
})
```

![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/f228cf42-b280-45ba-a683-d74971502b42)

**Comment by bigH** [comment]
Great plugin BTW. I use `fzf` a lot both in vim and out of it!

Thanks for the solution. I'll change my config to this and try it.

Since many users probably want this to work properly with icons, the default experience with icons should be sensible. This solution should be baked into the plugin.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/106554585dbb66171d75799bde4a30d31324cdf4

@bigH, should work for all file-type pickers (buffers, args, git-files, etc).

**Comment by bigH** [comment]
Thanks for doing this. I'll test the latest release soon.
