### ISSUE TITLE
blines search broken by commit a5b32c3

### ISSUE THREAD

**Issue by micheleCTDE** [ibhagwan/fzf-lua#1081]
I use `:FzfLua blines search=<word to search>` to find all instances of a specific word in an open buffer. This is link to some shortcut keys, so I can search for the work under curson with just three key strokes.
Commit a5b32c3 has broken this and I am simply presented with the same result as `:FzfLua blines`, without the search for the selected word. I then need to type the word manually to get the previous behavior.
As far as I have researched thorugh the site, there is no special config changes required, so it seems a regression to me.

**Comment by ibhagwan** [comment]
That’s by design, technically `search` is for grep args, the  prompt input is `query`, that way you can grep for a regex and preemptively enter the fuzzy query, it was wrong before, use `FzfLua blines query=<word to search>` instead?

**Comment by micheleCTDE** [comment]
ah, great! works like a charm when using `query`. I could not find this documented anywhere, either I looked into the wrong place or it is not there. MAybe a good idea to add it to the doc in the latter case.

Great plugin as always! Thank you for your continued effort!

**Comment by ibhagwan** [comment]
> ah, great! works like a charm when using `query`. I could not find this documented anywhere, either I looked into the wrong place or it is not there. Maybe a good idea to add it to the doc in the latter case.
> 
> Great plugin as always! Thank you for your continued effort!

Docs can always be improved admittedly, there’s only one me and I always prefer to code than to document :)

**Comment by micheleCTDE** [comment]
> there’s only one me and I always prefer to code than to document :)

:+1:  eh eh, I know the feeling :-)

**Comment by ibhagwan** [comment]
> > there’s only one me and I always prefer to code than to document :)
> 
> 👍 eh eh, I know the feeling :-)

Try my latest addition `:FzfLua awesome_colorschemes` let me know if it was worth it over the docs ha ha

**Comment by micheleCTDE** [comment]
Indeed impressive work :+1:
