### ISSUE TITLE
[BUG] Wrong handling of special folders on Windows

### ISSUE THREAD

**Issue by alanfzf** [ibhagwan/fzf-lua#1082]
### Info

- Operating System: Windows 11 pro 23H2
- Shell: PowerShell 7.4.1
- Terminal: Windows Terminal 1.18.3181.0
- `nvim --version`:
```
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```
- `fzf --version`:
```
0.47.0 (98ee5e6) (WinGet)
```
<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
  file_icon_padding = " ",
  keymap = {
    builtin = {
      -- neovim `:tmap` mappings for the fzf win
      ["<F1>"] = "toggle-help",
      ["<F2>"] = "toggle-fullscreen",
      -- Only valid with the 'builtin' previewer
      ["<F3>"] = "toggle-preview-wrap",
      ["<F4>"] = "toggle-preview",
      -- Rotate preview clockwise/counter-clockwise
      ["<F5>"] = "toggle-preview-ccw",
      ["<F6>"] = "toggle-preview-cw",
      ["<C-d>"] = "preview-page-down",
      ["<C-u>"] = "preview-page-up",
    },
    fzf = {
      -- fzf '--bind=' options
      ["ctrl-z"] = "abort",
      ["ctrl-n"] = "unix-line-discard",
      ["ctrl-f"] = "half-page-down",
      ["ctrl-b"] = "half-page-up",
      ["ctrl-a"] = "beginning-of-line",
      ["ctrl-e"] = "end-of-line",
      -- Only valid with fzf previewers (bat/cat/git/etc)
      ["f3"] = "toggle-preview-wrap",
      ["f4"] = "toggle-preview",
      ["ctrl-d"] = "preview-page-down",
      ["ctrl-u"] = "preview-page-up",
    },
  },
  fzf_opts = {
    ["--cycle"] = true,
    ["--color"] = "bg+:-1",
  },
  previewers = {
    builtin = {
      syntax = true, -- preview syntax highlight?
      syntax_limit_l = 0, -- syntax limit (lines), 0=nolimit
      syntax_limit_b = 1024 * 1024, -- syntax limit (bytes), 0=nolimit
      limit_b = 1024 * 1024 * 10, -- preview limit (bytes), 0=nolimit
    },
  },
})
```
</details>

### Description 
On windows when theres a file inside a subfolder with a rare name like `(website)` or `[id]` the picker opens a empty buffer not correspondig with the actual content, it seems like the name of the folder gets concatenated with the parent folder.

https://github.com/ibhagwan/fzf-lua/assets/29936954/0348c954-30e5-4611-98df-b9dfeb19811e

**Comment by ibhagwan** [comment]
Ty for the report @alanfzf,  this seems like a bug that wouldn’t be limited to Windows, I’ll check tomorrow and fix it.

**Comment by alanfzf** [comment]
I see, so this a issue on the neovim side?, i was able to find some similar issues on other plugins like [Telescope](https://github.com/nvim-telescope/telescope.nvim/issues/1303

**Comment by ibhagwan** [comment]
@alanfzf came up with a relatively easy solution which is to "normalize" the path before opening it (i.e. replacing forward slashes with backslahes), neovim seems to like that more.

**Comment by ibhagwan** [comment]
Just make sure to pull rebase as I force pushed typos in the comment :-)

https://github.com/ibhagwan/fzf-lua/commit/963749be811850178bd901fecab081492ba8f4d0
