### ISSUE TITLE
combine bat and image support

### ISSUE THREAD

**Issue by kapral18** [ibhagwan/fzf-lua#1084]
Hi. I am thoroughly enjoying bat previewer for ultimate speed.
But I see that only builtin renderer exclusively supports image extensions.
Is there any way to combine the 2?
For example to use builtin previewer image files and for the rest use bat
while scrolling through the files list?

**Comment by ibhagwan** [comment]
Not possible ATM, the previewers are fundementally different, one is native to fzf (renders inside fzf in the terminal) and the other is a neovim window, that would require new code which I don't plan on adding anytime soon.
