### ISSUE TITLE
[BUG] Run fzf-lua with skim failed

### ISSUE THREAD

**Issue by Spxg** [ibhagwan/fzf-lua#1085]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: NVIM v0.10.0-dev-2442+gfe74716cb
- `skim --version`: sk 0.10.4

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({ "skim" })
```
</details>

### Description 
The problems introduced by this commit [feat: exclude icons from fuzzy matching](https://github.com/ibhagwan/fzf-lua/commit/106554585dbb66171d75799bde4a30d31324cdf4). This `--nth` argument is not work for `skim`.
```lua
opts.fzf_opts["--nth"] = opts.fzf_opts["--nth"] or "-1.."
```
![img_v3_028t_8ab689ff-e9e4-448c-8403-0ffd9efe93eg](https://github.com/ibhagwan/fzf-lua/assets/17252397/11d1009a-d6f3-4bb2-91a1-9388e75bc1ed)

**Comment by ibhagwan** [comment]
> This --nth argument is not work for skim.

My bad, I didn’t test it with skim. I do recall it does support the flag so I’m confused why this doesn’t work, I’ll fix it.

**Comment by Spxg** [comment]
> > This --nth argument is not work for skim.
> 
> My bad, I didn’t test it with skim. I do recall it does support the flag so I’m confused why this doesn’t work, I’ll fix it.

Actually this is a `skim` bug, I will fix it in my fork branch

**Comment by ibhagwan** [comment]
> > > This --nth argument is not work for skim.
> > 
> > 
> > My bad, I didn’t test it with skim. I do recall it does support the flag so I’m confused why this doesn’t work, I’ll fix it.
> 
> Actually this is a `skim` bug, I will fix it in my fork branch

Nice, let me know when you fixed it and what went wrong?

In any event, I’ll make sure this works with a workaround as I can’t have this broken for everyone else but you.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/9a414ab6c3bec5b9f2b18e3753bb99cf6d72405c

@Spxg,  the latest commit around the bug by using `=` for cmd flags (instead of just space), so instead of using `--nth "-1.."`  we now use `--nth="-1.."`  which works as expected.

**Comment by Spxg** [comment]
> [9a414ab](https://github.com/ibhagwan/fzf-lua/commit/9a414ab6c3bec5b9f2b18e3753bb99cf6d72405c)
> 
> @Spxg, the latest commit around the bug by using `=` for cmd flags (instead of just space), so instead of using `--nth "-1.."` we now use `--nth="-1.."` which works as expected.

I fixed this "spaces" problem and upgraded to `clap 4` to solve some wired problems. https://github.com/Spxg/skim

**Comment by Spxg** [comment]
> > > > This --nth argument is not work for skim.
> > > 
> > > 
> > > My bad, I didn’t test it with skim. I do recall it does support the flag so I’m confused why this doesn’t work, I’ll fix it.
> > 
> > 
> > Actually this is a `skim` bug, I will fix it in my fork branch
> 
> Nice, let me know when you fixed it and what went wrong?
> 
> In any event, I’ll make sure this works with a workaround as I can’t have this broken for everyone else but you.

<img width="897" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/17252397/58d1407b-0f0d-4410-9e6d-029ecfd1aab0">

Looking at the code, I found that the author actually handles negative numbers, but the `-` sign will be specially processed by clap (Command Line Argument Parser for Rust). But clap provides a flag to control this behavior: https://docs.rs/clap/latest/clap/struct.Arg.html#method.allow_hyphen_values.

**Comment by ibhagwan** [comment]
> > > > > This --nth argument is not work for skim.
> > > > 
> > > > 
> > > > My bad, I didn’t test it with skim. I do recall it does support the flag so I’m confused why this doesn’t work, I’ll fix it.
> > > 
> > > 
> > > Actually this is a `skim` bug, I will fix it in my fork branch
> > 
> > 
> > Nice, let me know when you fixed it and what went wrong?
> > In any event, I’ll make sure this works with a workaround as I can’t have this broken for everyone else but you.
> 
> <img alt="image" width="897" src="https://private-user-images.githubusercontent.com/17252397/312208469-58d1407b-0f0d-4410-9e6d-029ecfd1aab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzE1NjMsIm5iZiI6MTcxMDI3MTI2MywicGF0aCI6Ii8xNzI1MjM5Ny8zMTIyMDg0NjktNThkMTQwN2ItMGYwZC00NDEwLTllNmQtMDI5ZWNmZDFhYWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE5MjEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYjYwYzBkMjZjNGMyNWFmNzVjOTcyYWFiZDRjNWMwODhlNmY1YWU3YWVmNTEyODA3ZGNkMzFiNmIzZDQwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbKrxzLAkBIdi8iVDNJA5zEScJrg_edAQ6wGNRCXlq0">
> Looking at the code, I found that the author actually handles negative numbers, but the `-` sign will be specially processed by clap (Command Line Argument Parser for Rust). Fortunately clap provides a flag to control this behavior: https://docs.rs/clap/latest/clap/struct.Arg.html#method.allow_hyphen_values.

Very nice! I recently also used clap but had no idea about this behavior.

Btw, have you see [this fork](https://github.com/kimono-koans/two_percent/tree/vendored) from https://github.com/lotabout/skim/issues/561 claiming to have better performance than fzf?

If this is true I would’ve loved for this to be PR’d and merged.

**Comment by Spxg** [comment]
> > > > > > This --nth argument is not work for skim.
> > > > > 
> > > > > 
> > > > > My bad, I didn’t test it with skim. I do recall it does support the flag so I’m confused why this doesn’t work, I’ll fix it.
> > > > 
> > > > 
> > > > Actually this is a `skim` bug, I will fix it in my fork branch
> > > 
> > > 
> > > Nice, let me know when you fixed it and what went wrong?
> > > In any event, I’ll make sure this works with a workaround as I can’t have this broken for everyone else but you.
> > 
> > 
> > <img alt="image" width="897" src="https://private-user-images.githubusercontent.com/17252397/312208469-58d1407b-0f0d-4410-9e6d-029ecfd1aab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzE1NjMsIm5iZiI6MTcxMDI3MTI2MywicGF0aCI6Ii8xNzI1MjM5Ny8zMTIyMDg0NjktNThkMTQwN2ItMGYwZC00NDEwLTllNmQtMDI5ZWNmZDFhYWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE5MjEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYjYwYzBkMjZjNGMyNWFmNzVjOTcyYWFiZDRjNWMwODhlNmY1YWU3YWVmNTEyODA3ZGNkMzFiNmIzZDQwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbKrxzLAkBIdi8iVDNJA5zEScJrg_edAQ6wGNRCXlq0">
> > Looking at the code, I found that the author actually handles negative numbers, but the `-` sign will be specially processed by clap (Command Line Argument Parser for Rust). Fortunately clap provides a flag to control this behavior: https://docs.rs/clap/latest/clap/struct.Arg.html#method.allow_hyphen_values.
> 
> Very nice! I recently also used clap but had no idea about this behavior.
> 
> Btw, have you see [this fork](https://github.com/kimono-koans/two_percent/tree/vendored) from [lotabout/skim#561](https://github.com/lotabout/skim/issues/561) claiming to have better performance than fzf?
> 
> If this is true I would’ve loved for this to be PR’d and merged.

I don't know much about optimizing performance, but I think these optimizations are effective.
