### ISSUE TITLE
Compatibility with neovim master?

### ISSUE THREAD

**Issue by fsouza** [ibhagwan/fzf-lua#109]
neovim master just changed the signature for the LSP handlers (https://github.com/neovim/neovim/pull/15504), which causes many things to stop working on fzf-lua.

What's your policy for changes like that? I realize master doesn't have to be stable and this change just happened today, but wanted to check with you before sending a pull request or something like that.

**Comment by ibhagwan** [comment]
I was waiting for this LSP change, shouldn’t be a problem to make it work on both stable and master at the same time.

**Comment by ibhagwan** [comment]
Should work now on both stable and master.
