### ISSUE TITLE
Latest nvim-dap breaks dap_breakpoints search in fzf-lua

### ISSUE THREAD

**Issue by shmerl** [ibhagwan/fzf-lua#1093]
fzf-lua still can find dap breakpoints, but it can't jump to them due to some incorrect resulting file name composing. And trying to delete a breakpoint from fzf-lua hangs the editor.

**Comment by ibhagwan** [comment]
Just tried and I don’t have this problem, can you check which commit how have of nvim-dap and update the plug-in?

Once fully updated can you toggle a few breakpoints, run `:lua _G.dump(require("dap.breakpoints").get())` and post the output?

Can you also post a screenshot of fzf-lua’s DAP breakpoints screen?

**Comment by shmerl** [comment]
nvim dap commit: c1695e500c7d552a0a19953a9aefcc89178fb1af which is latest.

Output of `:lua _G.dump(require("dap.breakpoints").get())`

```
{ { {                                                                                                                                                                                                                                               
      line = 10
    }, {
      line = 13
    } } }
```

Screen:

![fzf_debug](https://github.com/ibhagwan/fzf-lua/assets/310927/e9eedc39-3d89-4c6d-8cf1-5f017c1b8e3a)

**Comment by ibhagwan** [comment]
> The issue shows up as "unable to stat file" with some weird `[1] ` added to it. Actual file is there in my case it's `$HOME/tmp/debug/test.c` and everything else works fine with it

I see, can you pinpoint specific files/lines where this happens or is it totally random?

**Comment by shmerl** [comment]
Pretty random, happens with a bunch of different files. Also tried two different systems - both have the same symptom.

**Comment by shmerl** [comment]
Nope, same problem with fzf 0.48.1.

**Comment by shmerl** [comment]
Also tried with random files - same problem it doesn't depend on adapter type. Something just generates the name incorrectly for the right pane adding some kind of buffer index may be?

**Comment by shmerl** [comment]
Removed all extra plugins - same problem. Now I'm starting to suspect it's down to nevim or OS differences.

nvim: v0.9.5
Happens on Debian testing for me.

**Comment by shmerl** [comment]
Hmm, also tried some older commit of nvim-dap and the same issue happens. So may be it's not a recent regression (I haven't really tried doing such search recently).

**Comment by ibhagwan** [comment]
> Removed all extra plugins - same problem. Now I'm starting to suspect it's down to neovim or OS differences.
> 
> nvim: v0.9.5 Happens on Debian testing for me.

I’ll do some digging, ty for the through investigation!

**Comment by ibhagwan** [comment]
Apparently I've been using the buffer numbers for `dap_breakpoints` for a more accurate preview (in case the working copy changed), can you post a screnshot of `dap_breakpoints` when running (should disable the buffer display hide):
```lua
:lua require("fzf-lua").dap_breakpoints({fzf_opts={["--with-nth"]=false}})
```

**Comment by ibhagwan** [comment]
Also, would be great if you can post your `setup` options as well as `:lua print(vim.env.FZF_DEFAULT_OPTS)`

**Comment by ibhagwan** [comment]
I'm also suspecting your fzf-lua is stuck on some weird commit, can you confirm what's your current fzf-lua commit?

**Comment by shmerl** [comment]
Fzf-lua in main branch, commit 5104ac1744b92f888ef9f1d4bb6ff14e700c7a37. Let me check other details

**Comment by shmerl** [comment]
`:lua print(vim.env.FZF_DEFAULT_OPTS)`: `nil`

Very simple loading with Lazy.nvim:

```
{
  -- fzf search
  'ibhagwan/fzf-lua'
}
```

**Comment by ibhagwan** [comment]
> Very simple loading with Lazy.nvim:

Interesting, btw does `buffers` work as expected or has the same issue with preview?

How about the output of `lua require("fzf-lua").dap_breakpoints({fzf_opts={["--with-nth"]=false}})` I want to see if the buffer appears correctly inside the brakets (judging by the preview it looks accurate).

**Comment by shmerl** [comment]
`:lua require("fzf-lua").dap_breakpoints({fzf_opts={["--with-nth"]=false}})`

Produces this:

![fzf_debug2](https://github.com/ibhagwan/fzf-lua/assets/310927/b7124a65-3f42-4203-b138-0d81c80afe7f)

**Comment by ibhagwan** [comment]
> Produces this:

Yap, this looks perfectly intact, I'm confused why `path.entry_to_file` is failing here.

**Comment by shmerl** [comment]
`:buffers` shows this:

![image](https://github.com/ibhagwan/fzf-lua/assets/310927/fde52734-ed51-4931-81cf-43b7cd649e98)

**Comment by ibhagwan** [comment]
I meant `:FzfLua buffers` - it works similarly to dap breakpoints in the sense it uses the buffer for preview, also `:FzfLua lines`.

**Comment by shmerl** [comment]
![image](https://github.com/ibhagwan/fzf-lua/assets/310927/12787fef-60d3-42ed-b014-50814cba19fd)

![image](https://github.com/ibhagwan/fzf-lua/assets/310927/740eeeb8-9b3b-40a4-87f8-0b432644dd03)

**Comment by shmerl** [comment]
Nothing in the right pane for buffers.

**Comment by ibhagwan** [comment]
> Nothing in the right pane for buffers.

So buffers has the same issue as dap breakpoints or a different issue?

**Comment by shmerl** [comment]
Here is full view. No error or anything reported there:

![image](https://github.com/ibhagwan/fzf-lua/assets/310927/c43b7a67-bb63-4a9c-a3ae-849e7a1f2ccf)

**Comment by ibhagwan** [comment]
If buffers has the same issue can you try with `mini.sh` perhaps it's somehow related to your config after all?

```sh
sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"
```

This will redownload fzf-lua into `/tmp` and run it from there with no configuration at all, you can open files with `<c-p>` and then buffers with `<c-\>`.

**Comment by ibhagwan** [comment]
> Here is full view. No error or anything reported there

There's no problem here, you have only one buffer which is set as header (no preview), if you wish for it to be previewed you can use `:FzfLua buffers sort_lastused=false`.

**Comment by shmerl** [comment]
I opened a few more files - buffers work fine, preview is populated too so this error doesn't occur for buffers.

**Comment by ibhagwan** [comment]
> I opened a few more files - buffers work fine, preview is populated too so this error doesn't occur for buffers.

Now I am seriously confused why this is happening lol

**Comment by shmerl** [comment]
Can I add some debug output somewhere to sew how the path is composed?

**Comment by ibhagwan** [comment]
> Can I add some debug output somewhere to sew how the path is composed?

You can run`:FzfLua dap_commands previewer=bat debug=true` and we'll be able to see what gets passed exactly from fzf:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/5d8ef8a2-39de-4725-ad5b-0113f8ad8e1e)

**Comment by ibhagwan** [comment]
You can then take the line fzf passes in the args and pass it to `path.entry_to_file` like this:
```lua
:lua _G.dump(require("fzf-lua").path.entry_to_file(<line>))
```
For example:
```lua
:lua _G.dump(require("fzf-lua").path.entry_to_file("[1] foo " .. require("fzf-lua").utils.nbsp .. "/path/
to/file"))
```

Outputs:
```lua
{
  bufname = "/home/bhagwan/.config/nvim/lua/plugins/fzf-lua/init.lua",
  bufnr = 1,
  col = 1,
  line = 1,
  path = "/path/to/file",
  stripped = "/path/to/file",
  terminal = false
}
```

**Comment by shmerl** [comment]
I guess you meant `:FzfLua dap_breakpoints previewer=bat debug=true`?

Let me try that.

**Comment by shmerl** [comment]
First it shows this:

```
[Fzf-lua]: FZF_DEFAULT_COMMAND: VIMRUNTIME='/tmp/.mount_nvim607If9/usr/share/nvim/runtime' '/tmp/.mount_nvim607If9/usr/bin/nvim' -n --headless --clean --cmd 'lua vim.g.did_load_filetypes=1; loadfile([[/home/user/.local/share/nvim/lazy/fzf-lua/lua/fzf-
lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/run/user/1000/fzf-lua.1710891161.816397.1]], fnc_id=7 , debug=true})'  || true
[Fzf-lua]: fzf cmd: fzf --header ':: <^[[38;2;255;235;205mctrl-x^[[0m> to ^[[38;2;255;64;64mdelete^[[0m' --ansi --layout 'reverse' --prompt 'DAP Breakpoints> ' --delimiter '[\]:]' --with-nth '2..' --preview-window 'nohidden:border:nowrap:right:60%:+{3}-
/2' --preview 'VIMRUNTIME='\''/tmp/.mount_nvim607If9/usr/share/nvim/runtime'\'' '\''/tmp/.mount_nvim607If9/usr/bin/nvim'\'' -n --headless --clean --cmd '\''lua vim.g.did_load_filetypes=1; loadfile([[/home/user/.local/share/nvim/lazy/fzf-lua/lua/fzf-lu
a/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/run/user/1000/fzf-lua.1710891161.816397.1]], fnc_id=8 , debug=true})'\'' -- {}' --bind 'ctrl-u:unix-line-discard,ctrl-z:abort,shift-down:preview-page-down,f4:toggle-preview,f3:toggle-preview-w
rap,shift-up:preview-page-up,alt-a:toggle-all,ctrl-a:beginning-of-line,ctrl-e:end-of-line,ctrl-b:half-page-up,ctrl-x:unbind(ctrl-x)+execute-silent(VIMRUNTIME='\''/tmp/.mount_nvim607If9/usr/share/nvim/runtime'\'' '\''/tmp/.mount_nvim607If9/usr/bin/nvim'\
'' -n --headless --clean --cmd '\''lua vim.g.did_load_filetypes=1; loadfile([[/home/user/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/run/user/1000/fzf-lua.1710891161.816397.1]], fnc_id=9 , debu
g=true})'\'' -- {+})+reload(VIMRUNTIME='\''/tmp/.mount_nvim607If9/usr/share/nvim/runtime'\'' '\''/tmp/.mount_nvim607If9/usr/bin/nvim'\'' -n --headless --clean --cmd '\''lua vim.g.did_load_filetypes=1; loadfile([[/home/user/.local/share/nvim/lazy/fzf-l
ua/lua/fzf-lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/run/user/1000/fzf-lua.1710891161.816397.1]], fnc_id=7 , debug=true})'\'' -- {+}),ctrl-f:half-page-down,load:rebind(ctrl-x)' --border 'none' --print-query --expect 'alt-l,alt-q,ctr
l-t,ctrl-v,ctrl-s,ctrl-c,esc,ctrl-q' --info 'inline' --height '100%' > '/tmp/nvim.user/bXXlct/38'
```

**Comment by ibhagwan** [comment]
> First it shows this:

For our issue I’m more interested in the debug info showed by the previewer.

**Comment by shmerl** [comment]
File name is messed up:

![fzf_debug3](https://github.com/ibhagwan/fzf-lua/assets/310927/3cbc4e04-2fca-4569-886a-c38f1563c22f)

**Comment by shmerl** [comment]
So which line should I try to pass?

**Comment by ibhagwan** [comment]
I shouldn've noticed earlier you had no `nvim-web-devicons` installed which was setting `file_icons=false` and apparently this never worked properly without icons :-)

Should work with https://github.com/ibhagwan/fzf-lua/commit/c0ff7068b331f58619c2eb74624ede3e549ea7ea.

Ty for your patience and debugging efforts!

**Comment by shmerl** [comment]
Thank you!
