### ISSUE TITLE
`symbol_style = false` does not have effect

### ISSUE THREAD

**Issue by tomtomjhj** [ibhagwan/fzf-lua#1098]
### Info

- `nvim --version`: current HEAD

fzf-lua configuration

```lua
require'fzf-lua'.setup { lsp = { symbols = { symbol_style = false } } }
```

### Description 
The docs say that `symbol_style = false` means "disable", but it still shows the kind, like `symbol_style = 3`.

The problem is that it `symbol_style = false` leads to this branch where `_sym2style` is set to `kind`. 

https://github.com/ibhagwan/fzf-lua/blob/1df84a4c77de7e240fa0e7719f8a2a2a9106ba43/lua/fzf-lua/providers/lsp.lua#L687-L688

**Comment by ibhagwan** [comment]
I’m not sure about this @tomtomjhj, `false` changes the display to no icons no highlights, basically the name that comes back from the LSP and nothing else, I don’t think it should hide the kind, for that you can pass your own custom formatter:

> symbol_style=3
![IMG_1978](https://github.com/ibhagwan/fzf-lua/assets/59988195/d8a14dee-7453-4000-b45c-06488def652d)

> symbol_style=false
![IMG_1979](https://github.com/ibhagwan/fzf-lua/assets/59988195/aefcb72c-1e1e-43f4-a6b1-5c6e05d949c7)


If you want the info hidden set `symbol_style=false` and use your own `symbol_fmt`:
> You can return an empty string here too
```lua
-- this goes under `lsp.symbols`
symbol_fmt = function(s, opts) return "[" .. s .. "]" end,
```

**Comment by ibhagwan** [comment]
Also the name is `symbol_style`, “style” implies icons and highlights, not to disable symbol (kind) completely.

**Comment by tomtomjhj** [comment]
Oh thanks!
