### ISSUE TITLE
Files provider with cwd opening empty buffer if not opened from same directory as passed in cwd

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#11]
Hi again :)

with mapping such as:

```lua
lua require("fzf-lua").files({ cwd = vim.env.DOTFILES })
```

I have noticed that when I run it from `~` directory it will properly show me my dot files, but when I open one it opens empty buffer relative to my current dir (`~`), for example, picking up `nvim/init.lua` from picker it will open non existing `~/nvim/init.lua`. I think it did work when I first set it up but didn't heavily used it since.

**Comment by ibhagwan** [comment]
I’m going to test this soon and see for myself, just one question: in the title you wrote `oldfiles` but in the example you’re using `files` - which one has the issue?

**Comment by gegoune** [comment]
Ah, apologies, I have edited title after I realised it was for different mapping than I initially though but missed that bit. Edited now.

**Comment by ibhagwan** [comment]
Should be fixed now.

**Comment by gegoune** [comment]
Superb, it works, thanks a lot!
