### ISSUE TITLE
No result for files()

### ISSUE THREAD

**Issue by winston0410** [ibhagwan/fzf-lua#110]
First of all, thank you for your effort! I have just tried out the plugin with `:lua require('fzf-lua').files()`, but it returns 0 result in the popup. I am trying that in the `$HOME` directory, so there should be a lot of files.

Is there something that I have to config with? Issue with `sudo`?

**Comment by ibhagwan** [comment]
It's either an issue with your config or a bug, I'm sure we can solve it, a few questions:

- Do you have `fd` installed? if not do you have `find` in your system (you can find out by typing `which find` or `type find` in the shell)?
- It's possible you have a different version of the above utilities that doesn't work with the default flags, can you try running the below commands and let me know which (if any) works and which doesn't?

```lua
-- Basic 'fd'
:lua require('fzf-lua').files({ cmd = "fd" })
-- this is the default 'fd' command:
:lua require('fzf-lua').files({ cmd = "fd --color never --type f --hidden --follow --exclude .git --exclude node_modules --exclude '*.pyc'" })
-- Basic 'find'
:lua require('fzf-lua').files({ cmd = "find -L . -type f" })
-- this is the default 'find' command:
:lua require('fzf-lua').files({ cmd = "find -L . -type f -printf '%P\n'" })

```

**Comment by hqkhan** [comment]
I wanted to ask a question about default search utility that `files` uses. Below is my `files` config which is the one provided in README. Since `cmd` is empty, does it default to `fd` if it's installed?
```
  files = {
    -- previewer         = "cat",       -- uncomment to override previewer
    prompt            = 'Files ❯ ',
    cmd               = '',             -- "find . -type f -printf '%P\n'",
    git_icons         = true,           -- show git icons?
    file_icons        = true,           -- show file icons?
    color_icons       = true,           -- colorize file|git icons
    actions = {
      ["default"]     = actions.file_edit,
      ["ctrl-s"]      = actions.file_split,
      ["ctrl-v"]      = actions.file_vsplit,
      ["ctrl-t"]      = actions.file_tabedit,
      ["ctrl-q"]      = actions.file_sel_to_qf,
      ["ctrl-y"]      = function(selected) print(selected[2]) end,
    }
  },
```

**Comment by ibhagwan** [comment]
> I wanted to ask a question about default search utility that `files` uses. Below is my `files` config which is the one provided in README. Since `cmd` is empty, does it default to `fd` if it's installed?
> 
> ```
>   files = {
>     -- previewer         = "cat",       -- uncomment to override previewer
>     prompt            = 'Files ❯ ',
>     cmd               = '',             -- "find . -type f -printf '%P\n'",
>     git_icons         = true,           -- show git icons?
>     file_icons        = true,           -- show file icons?
>     color_icons       = true,           -- colorize file|git icons
>     actions = {
>       ["default"]     = actions.file_edit,
>       ["ctrl-s"]      = actions.file_split,
>       ["ctrl-v"]      = actions.file_vsplit,
>       ["ctrl-t"]      = actions.file_tabedit,
>       ["ctrl-q"]      = actions.file_sel_to_qf,
>       ["ctrl-y"]      = function(selected) print(selected[2]) end,
>     }
>   },
> ```

Yes, files defaults to `fd`, fallback to `find`. Grep defaults to `rg` fallback to `grep`.

If you want to change only the default flags and not the command you can add `fd_opts` or `find_opts` under `files` (it’s not on the README but they will be read).

**Comment by hqkhan** [comment]
> > I wanted to ask a question about default search utility that `files` uses. Below is my `files` config which is the one provided in README. Since `cmd` is empty, does it default to `fd` if it's installed?
> > ```
> >   files = {
> >     -- previewer         = "cat",       -- uncomment to override previewer
> >     prompt            = 'Files ❯ ',
> >     cmd               = '',             -- "find . -type f -printf '%P\n'",
> >     git_icons         = true,           -- show git icons?
> >     file_icons        = true,           -- show file icons?
> >     color_icons       = true,           -- colorize file|git icons
> >     actions = {
> >       ["default"]     = actions.file_edit,
> >       ["ctrl-s"]      = actions.file_split,
> >       ["ctrl-v"]      = actions.file_vsplit,
> >       ["ctrl-t"]      = actions.file_tabedit,
> >       ["ctrl-q"]      = actions.file_sel_to_qf,
> >       ["ctrl-y"]      = function(selected) print(selected[2]) end,
> >     }
> >   },
> > ```
> 
> Yes, files defaults to `fd`, fallback to `find`. Grep defaults to `rg` fallback to `grep`.
> 
> If you want to change only the default flags and not the command you can add `fd_opts` or `find_opts` under `files` (it’s not on the README but they will be read).

Oh awesome! I remember doing that in `fzf.vim`. Happy to see it works similarly here. Thanks!

**Comment by winston0410** [comment]
@ibhagwan Thank you for the help! It is me forgetting to install `fd`. Closing this now.

**Comment by yarthur** [comment]
Apparently, the `-printf` is not a supported flag for POSIX find (according to [this SO thread](https://unix.stackexchange.com/questions/272491/bash-error-find-printf-unknown-primary-or-operator), anyway). It may be worth noting in the README that if you're not using a GNU implementation, you have another reason to install `fd` (or document how to configure for the basic `find` command as [suggested above](https://github.com/ibhagwan/fzf-lua/issues/110#issuecomment-913866352)).

**Comment by ibhagwan** [comment]
> Apparently, the `-printf` is not a supported flag for POSIX find (according to [this SO thread](https://unix.stackexchange.com/questions/272491/bash-error-find-printf-unknown-primary-or-operator), anyway). It may be worth noting in the README that if you're not using a GNU implementation, you have another reason to install `fd` (or document how to configure for the basic `find` command as [suggested above](https://github.com/ibhagwan/fzf-lua/issues/110#issuecomment-913866352)).

Good find! I'm surprised it hadn't come up before, I guess most people who use this plugin already have `fzf` and `fd` installed.

Worth noting it can still work without the `-printf` but the filenames will be prepended with `./`, a better solution to updating the README would be to test the `find` command and modify it accordingly if it doesn't support `printf`.

**Comment by ibhagwan** [comment]
@yarthur, Do you have access to the non-GNU version of `find`?

If so, can you paste the output of `find --version` and also run `find . -type f -printf '%P\n'` (should fail as you mentioned) and then check the exit code using `echo $?`?

This way I can make the necessary code adjustments for non-GNU find.

**Comment by yarthur** [comment]
I'm on a Mac, macOS Catalina. I don't know from GNU vs POSIX, I just read that on the StackOverflow thread. So while I assume my issue was due to being on a non-GNU version, I'm well out of my depth in many regards here. That said...

`find --version` returns the following:
```sh
find: illegal option -- -
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

`find . -type f -printf '%P\n'` returns the following:
`find: -printf: unknown primary or operator`

Following up with `echo $?` returns `1`.

Finally, running `man find` (trying to find some info on how to get the version), I noticed there is a `--print` and a `--print0`, but no `--printf` flag, as you might expect at this point.

I hope that helps. If there's anything else I can do, let me know.

**Comment by ibhagwan** [comment]
At first I thought about automatically adjusting the find options for the user but didn't really like the idea, the output with POSIX find still sucks (will prepend `./` before each file) and since apparently this issue isn't that common I opted for warning the user when using POSIX find with the default options:
```
POSIX find does not support the '-printf' option. Install 'fd' or set 'files.find_opts' to '-type f'.
```

Self explanatory I would hope, if you still wish to make it work with POSIX find, remove the incompatible flags:
```lua
require("fzf-lua").setup({
  files = {
    find_opts = '-type f'
  }
})
```

Relevant commit: https://github.com/ibhagwan/fzf-lua/commit/4b59a5d31de2cea7845a6f52665376aab48a1a3b

**Comment by yarthur** [comment]
I figured the best solution for this was documentation-based; it just seemed like the effort (or the compromises) needed to make it work would be too much. I think this is great!
