### ISSUE TITLE
fzf-vim profiles crash with eveforest colortheme

### ISSUE THREAD

**Issue by XXiaoA** [ibhagwan/fzf-lua#1100]
### Info

- Operating System: arch linux
- Shell: fish
- Terminal: wezterm
- `nvim --version`: NVIM v0.10.0-dev-2671+gdc110cba3c
- `fzf --version`: 0.48.0 (091b7eac)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
    "fzf-vim"
})
```
</details>

### Description 
When we use `fzf-vim` profile and [everforest](https://github.com/sainnhe/everforest), we will get the message
```
   Warn  12:19:21 PM notify.warn [Fzf-lua] fzf error 2: invalid color specification: bg+:#2e383c:cursorcolumn
```
if we want to use FzfLua command to fuzzyfind

https://github.com/ibhagwan/fzf-lua/assets/62557596/bd57bf0f-6e58-44d8-aeb2-e388bdda5ca1

**Comment by ibhagwan** [comment]
Ty for the report @XXiaoA, should work after https://github.com/ibhagwan/fzf-lua/commit/8cb22465e1ef532cb5fcd7d1fc06da46893cfdc8.

**Comment by XXiaoA** [comment]
Thanks for your great work, it was fixed!

**Comment by ibhagwan** [comment]
> Thanks for your great work, it was fixed!

Ty for the update @XXiaoA!
