### ISSUE TITLE
UI select broken in visual mode

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#1101]
### Info

- Operating System: Ubuntu
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: 0.9.5
- `fzf --version`: 0.45

```lua
require("fzf-lua").register_ui_select({
    winopts = {
        height = 0.30,
        width = 0.45,
    },
})

vim.keymap.set("x", "gt", function()
    local list = { "test", "test2", "test3", "test4" }
    vim.ui.select(list, { prompt = "testvis" }, function (s)
        vim.print(s)
    end)
end)

})
```

Similarly to a recently fixed issue which was causing other pickers to close in visual mode, there is an issue with ui.select which seems to 'act' the same, once opened ui.select/fzf is immediately closed.

**Comment by asmodeus812** [comment]
Maybe related - 97b455afe4a6c4d5a7f5c7b2dcab35a86b537872

**Comment by ibhagwan** [comment]
> Maybe related - [97b455a](https://github.com/ibhagwan/fzf-lua/commit/97b455afe4a6c4d5a7f5c7b2dcab35a86b537872)

Most likely similar issue, I’ll fix it.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7322954aa3e3363fb48666f7e7b7fd05da413915

@asmodeus812, should work now.
