### ISSUE TITLE
live_grep open buffers?

### ISSUE THREAD

**Issue by sainttttt** [ibhagwan/fzf-lua#1104]
Is there a way currently to run a live_grep only on the current open buffers? What about the current buffer only? Or the results of a fuzzy search? I know that there is a glob feature but looking for something more than that. Thanks!

**Comment by ibhagwan** [comment]
> Is there a way currently to run a live_grep only on the current open buffers?

Not out of the box but you can probably very easily craft a command that first uses `vim.api.nvim_list_bufs()`, builds an `rg` command from it and feeds it to `live_grep` options as `{ cmd = ... }`.

There is however `:FzfLua lines` which fuzzy searches all open buffers.

> What about the current buffer only?

`:FzfLua lgrep_curbuf` which can transform into `:FzfLua grep_curbuf` (fuzzy) with `ctrl-g` (and vice versa, fuzzy back to live).

 The `xxx_curbuf` variants have their own "resume context" so the fuzzy query/regex search arg are preserved between `ctrl-g` toggles and `:FzfLua resume`.

**Comment by ibhagwan** [comment]
> Or the results of a fuzzy search?

You can send the results the quick fix with `alt-q` and then use `:FzfLua quickfix` to fuzzy the quickfix.

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if you need more help.
