### ISSUE TITLE
Git Error When Updating fzf-lua

### ISSUE THREAD

**Issue by xeon826** [ibhagwan/fzf-lua#1105]
### Info

- Operating System: Ubuntu 22.04
- Shell: Bash
- Terminal: Alacritty
- `nvim --version`: NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
- `fzf --version`: 0.29 (devel)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

In my plugins.lua
```
  use { 'ibhagwan/fzf-lua',
    -- optional for icon support
    requires = { 'nvim-tree/nvim-web-devicons' }
  }

```
In init.lua
```
require('fzf-lua').setup({'fzf-vim'})
```
</details>

### Description 
When updating fzf-lua with `:PackerUpdate` I get an error 
```
 ✗ Failed to update ibhagwan/fzf-lua
  Errors:
    fatal: Not possible to fast-forward, aborting.
    5f1f4b2
```

**Comment by ibhagwan** [comment]
This means you probably caught a rare force push I did, you have to either delete the plug-in and reinstall or change your package manager to `git pull --rebase` instead.

**Comment by ibhagwan** [comment]
ref: https://github.com/wbthomason/packer.nvim/issues?q=pull+rebase++

Btw, highly recommend switching packer to lazy, last commit on packer was 7 months ago…

**Comment by xeon826** [comment]
I went to the plugin directory and pulled with rebase and it's fixed, I'll keep in mind about packer/lazy as well, thank you.

**Comment by ibhagwan** [comment]
> I went to the plugin directory and pulled with rebase and it's fixed, I'll keep in mind about packer/lazy as well, thank you.

Great, ty for the update.
