### ISSUE TITLE
Builtin previewer shows empty buffer

### ISSUE THREAD

**Issue by toupeira** [ibhagwan/fzf-lua#1107]
### Info

- Operating System: Debian sid
- Shell: Bash
- Terminal: Tilix
- `nvim --version`: NVIM v0.9.5, LuaJIT 2.1.1700206165

- `fzf --version`: 0.48.1 (d579e33)

- [x] The issue is reproducible with `mini.sh`

### Description 

The builtin previewer just shows an empty buffer, using `bat` works fine. I don't see any error messages.

Screenshot from `mini.sh`:

![image](https://github.com/ibhagwan/fzf-lua/assets/6501/e163e8b5-9655-4b14-b7f9-3834cb14ca34)

**Comment by ibhagwan** [comment]
- Is there any error in `:messages`?
- Is this error limited to `files` or also `grep`, `buffers`, `autocmds`, `help`, etc?
- Can you run `:FzfLua files debug=v` and post a screenshot of the output?
- Can you run `:FzfLua files debug=true _base64=false` and post the command in `:messages`?

**Comment by toupeira** [comment]
@ibhagwan thanks, info is at the very end of this comment, but I realized now it's due to my `$FZF_DEFAULT_OPTS` :facepalm: 

Specifically `--preview-window 'right,50%,hidden,<60(up,70%,hidden)'`, without that the builtin previewer works :tada: 

This option should probably be stripped inside `fzf-lua`, since it has its own setup for the preview?

Another issue I have now is that scrolling the preview doesn't work, probably my default shortcuts from `$FZF_DEFAULT_OPTS` interfere here too?

My FZF config is at https://github.com/toupeira/dotfiles/blob/main/etc/profile.d/fzf.sh, the relevant bindings are:

```sh
  --bind ctrl-e:preview-down
  --bind ctrl-y:preview-up
  --bind ctrl-f:preview-half-page-down
  --bind ctrl-b:preview-half-page-up
```

And in my Vim config I have:

```lua
      keymap = {
        builtin = {
          ['<F1>']  = 'toggle-help',
          ['<C-_>'] = 'toggle-preview',
          ['<C-e>'] = 'preview-down',
          ['<C-y>'] = 'preview-up',
          ['<C-f>'] = 'preview-half-page-down',
          ['<C-b>'] = 'preview-half-page-up',
        },
        -- remove defaults, still uses $FZF_DEFAULT_OPTS
        fzf = {},
      },
```

This worked fine with the `bat` previewer since I guess FZF was handling it on its own, but not with the builtin one. Maybe `--bind` arguments should be stripped too (I'm fine with having to duplicate them in my Vim config), or otherwise only those that clash with `keymap.builtin`?

<details><summary>Original comment with debug info</summary>

> Is there any error in :messages?

@ibhagwan no, only this startup message from `mini.sh`:

```
|| [Fzf-lua] |<C-\> buffers|<C-p> files|<C-g> grep|<C-l> live grep|<C-k> builtin|<F1> help|
```

> Is this error limited to files or also grep, buffers, autocmds, help, etc?

No, all of these show a blank preview (`help` -> `help_tags`?)

> Can you run :FzfLua files debug=v and post a screenshot of the output?

I assume you mean these lines in the FZF window, right?

![image](https://github.com/ibhagwan/fzf-lua/assets/6501/3be4f245-1fe3-481a-9395-eeef539c692c)

> Can you run :FzfLua files debug=true _base64=false and post the command in :messages?

```
|| [Fzf-lua]: fzf cmd: fzf --expect 'alt-q,alt-l,ctrl-c,ctrl-q,esc,ctrl-g,ctrl-s,ctrl-v,ctrl-t' --ansi --info 'default' --bind 'zero:execute-silent(mkdir '\''/tmp/nvim.schtube/rDvfZW/6'\'' && VIMRUNTIME='\''/usr/share/nvim/runtime'\'' '\''/usr/bin/nvim'\'' -n --headless --clean --cmd '\''lua vim.g.did_load_filetypes=1; loadfile([[/tmp/fzf-lua.tmp/nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/run/user/1000/fzf-lua.1711660535.80365.1]], fnc_id=6 , debug=true})'\'' -- ),ctrl-b:half-page-up,ctrl-a:beginning-of-line,ctrl-e:end-of-line,alt-a:toggle-all,f3:toggle-preview-wrap,f4:toggle-preview,shift-down:preview-page-down,ctrl-z:abort,ctrl-u:unix-line-discard,shift-up:preview-page-up,ctrl-f:half-page-down' --print-query --preview 'VIMRUNTIME='\''/usr/share/nvim/runtime'\'' '\''/usr/bin/nvim'\'' -n --headless --clean --cmd '\''lua vim.g.did_load_filetypes=1; loadfile([[/tmp/fzf-lua.tmp/nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/run/user/1000/fzf-lua.1711660535.80365.1]], fnc_id=5 , debug=true})'\'' -- {}' --layout 'reverse' --prompt '/etc/dotfiles/' --header ':: <^[[38;2;255;235;205mctrl-g^[[0m> to ^[[38;2;255;64;64mDisable .gitignore^[[0m' --preview-window 'nohidden:right:0' --height '100%' --delimiter '[ ]' --nth '-1..' --border 'none' --multi > '/tmp/nvim.schtube/rDvfZW/8'
```

Also tried with Neovim 0.10 now from the Ubuntu PPA (0.10.0~ubuntu1+git202401242104-b280d57db-862fdbd52-c148bd039~ubuntu23.04.1), but builtin previews don't work there either.

</details>

**Comment by ibhagwan** [comment]
> but I realized now it's due to my $FZF_DEFAULT_OPTS 🤦
> This option should probably be stripped inside fzf-lua, since it has its own setup for the preview?

100% this option should be stripped and I’m confused why it’s not (I also use FZF_DEFAULT_OPTS), fzf-lua should work regardless of any external variable setting, I’ll do some testing what special about your setting that makes this fail.

The same applies for your bind settings, fzf-lua specifies these directly via the command line and therefore fzf-lua binds should take priority (which AFAIK worked fine for myself and anyone else) - I will have to do some digging but rest assured this will be solved :)

**Comment by ibhagwan** [comment]
I’m starting to think we should never proxy $FZF_DEFAULT_OPTS unless specifically instructed by the user.

I am a bit conflicted though as I believe many users already have all kinds of customizations there (colors, binds, etc) and I’d hate for these to be lost via a breaking update that forces users onto a configuration change.

**Comment by toupeira** [comment]
@ibhagwan sweet, thank you! :+1: 

I noticed it's the `,<60(up,70%,hidden)` part that's causing trouble (which works like `flip_columns` in fzf-lua), without that it works too.

Oh and regarding your second comment just now: Yes I definitely want to keep most of my `$FZF_DEFAULT_OPTS` inside Vim too, as you say in the README having a uniform experience is very nice indeed :grinning: 

My two cents to help with your conflict:

- For `--preview-window`:
  - Not sure if this could be considered a bug in FZF, that it's ignoring the argument the plugin is passing? Or maybe there's something else going on with the fliip syntax I'm using.
  - Otherwise it might be fine to unconditionally strip this inside the plugin (i.e. re-export the envvar with the argument removed), although actually doing that could get tricky with quotes etc.
- For `--bind` arguments:
  - These could be stripped with an opt-in (or opt-out) flag maybe, although it seems tricky too.
  - Maybe FZF needs a `--unbind` option, so you could call that for all builtin shortcuts?
  - Or a `--unbind-all` to start with a blank slate, and force plugin users to redefine all shortcuts?

**Comment by ibhagwan** [comment]
> For `--preview-window`
> Otherwise it might be fine to unconditionally strip this inside the plugin (i.e. re-export the envvar with the argument removed), although actually doing that could get tricky with quotes etc.

I'm also thinking this is the right solution, although tricky I'm sure I can find a proper strip pattern for this.

> For `--bind` arguments
> Maybe FZF needs a --unbind option
> Another issue I have now is that scrolling the preview doesn't work, probably my default shortcuts from $FZF_DEFAULT_OPTS interfere here too?

Since you're using the builtin previewer the preview scroll is not an fzf bind but a neovim bind:
- Does scrolling the previewer work with the default `mini.sh`?
- What does `<F1>` help show? Do you see the correct binds for preview scrolling (as my screenshot below)?

![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/1047611c-c841-477d-8502-fbfcf08790e9)

**Comment by ibhagwan** [comment]
@toupeira, https://github.com/ibhagwan/fzf-lua/commit/348cb6b9dc56a8eb963468b4e83b5e9abb438023 should strip `--preview-window`, it should take care of both formats (spaced flag and also `--preview-window=...`) with or without quotes.

That gave me another idea, the newer syntax you used for esentially mimicing `flip_columns` should be intergrated into fzf_lua (if fzf's version satisfies the requirement), that way we also get `flip_columns` for `bat` previewers, `git_status` and other native previewers, if you want to PR it let me know or I'll do it myself.

Will await to close this issue until we figure out why your preview scroll binds don't work.

**Comment by toupeira** [comment]
> Does scrolling the previewer work with the default mini.sh?

It does, with the default Shift-Up/Down bindings. It also still works even if I add them to `$FZF_DEFAULT_OPTS` too like this:

```
  --bind shift-down:preview-down
  --bind shift-up:preview-up
```

And actually I removed my other bindings from `$FZF_DEFAULT_OPTS` now and they still don't work in the builtin previewer, so I'm afraid this was a red herring :sweat_smile: Looks like the problem is on the Vim side.

> What does <F1> help show? Do you see the correct binds for preview scrolling (as my screenshot below)?

This seems correct:

![image](https://github.com/ibhagwan/fzf-lua/assets/6501/ea40998b-9335-48ea-b225-607e23738c3b)

Somehow I sometimes land in normal mode inside the FZF window after pressing F1, but I can't reproduce it again now. Is there a proper way to leave insert mode? Then I could check the maps, I managed to do that for `:imap <C-e>` and it said `No mapping found`. Maybe another plugin or part of my configuration is interfering.

**Comment by toupeira** [comment]
> https://github.com/ibhagwan/fzf-lua/commit/348cb6b9dc56a8eb963468b4e83b5e9abb438023 should strip --preview-window, it should take care of both formats (spaced flag and also --preview-window=...) with or without quotes.

@ibhagwan applied locally, this works great! :+1: 

> That gave me another idea, the newer syntax you used for esentially mimicing flip_columns should be intergrated into fzf_lua (if fzf's version satisfies the requirement), that way we also get flip_columns for bat previewers, git_status and other native previewers, if you want to PR it let me know or I'll do it myself.

Nice idea! I'm afraid I'm still very new to Lua so I'll leave that to you :wink:

**Comment by ibhagwan** [comment]
@toupeira, hold on the commit I linked, the pattern wasn't perfect, I reversed it for the time being :-)

> It does, with the default Shift-Up/Down bindings. It also still works even if I add them to $FZF_DEFAULT_OPTS too like this
>  ```
> --bind shift-down:preview-down
>  --bind shift-up:preview-up
>```


These do nothing in the context of the neovim previewer, the builtin previewer uses neovim binds unrealted to fzf/terminal.

> And actually I removed my other bindings from $FZF_DEFAULT_OPTS now and they still don't work in the builtin previewer, so I'm afraid this was a red herring 😅 Looks like the problem is on the Vim side.

Correct, due to what I mentioned above.

> Somehow I sometimes land in normal mode inside the FZF window after pressing F1, but I can't reproduce it again now. Is there a proper way to leave insert mode? Then I could check the maps

Fzf-lua is essentially a terminal window, in neovim, you can "exit" to nomal mode (from terminal) using `<C-\><C-n>`, you can then use `:verbose tmap <s-down>` or `:verbose tmap <C-b>` which should reply with:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/061ac95e-a65d-4e73-a122-672952b8e053)

You can also test the scroll by running:
```lua
:lua require('fzf-lua.win').preview_scroll(1)
```

**Comment by ibhagwan** [comment]
> @ibhagwan applied locally, this works great! 👍

Can you verify with https://github.com/ibhagwan/fzf-lua/commit/b983b6c3fde43821ab86ecb04b9449b9004c8ca1, the preview one had a greedy match which was causing a malformed $FZF_DEFAULT_OPTS under certain conditions.

As for your mappings I now see the issue, you have setup wrong, these aren't fzf style binds so the string only applies to what is available within fzf-lua, you should set these specifically to:
```lua
  -- Yours show `preview-half-page...` which doesn't exist in fzf-lua
  ["<C-f>"]    = "preview-page-down",
  ["<C-b>"]    = "preview-page-up",
```

**Comment by toupeira** [comment]
> Fzf-lua is essentially a terminal window, in neovim, you can "exit" to nomal mode (from terminal) using <C-\><C-n>

TIL, thanks!

> Can you verify with https://github.com/ibhagwan/fzf-lua/commit/b983b6c3fde43821ab86ecb04b9449b9004c8ca1, the previous (now detached) commit had a greedy match which was causing a malformed $FZF_DEFAULT_OPTS under certain conditions.

Still works! :+1: And yes the previous version ate my `--bind` arguments :grinning: 

> As for your mappings I now see the issue, you have it setup wrong, these aren't fzf style binds so the string only applies to what is available within fzf-lua, you should set these specifically to:

Ooh gotcha, sorry about that too then! These work perfectly, so I think this issue can be closed.

I kinda like having single-line and half-page movements, so I'll probably look into submitting a PR to add those actions and learn some more Lua. Do I understand correctly that the code at https://github.com/ibhagwan/fzf-lua/blob/b983b6c3fde43821ab86ecb04b9449b9004c8ca1/lua/fzf-lua/previewer/builtin.lua#L347-L350 basically just simulates Ctrl-d / Ctrl-u keypresses in the preview buffer?

**Comment by ibhagwan** [comment]
> basically just simulates Ctrl-d / Ctrl-u keypresses in the preview buffer?

Correct! So essentially these are already “half” buffer movements.

> kinda like having single-line and half-page movements, so I'll probably look into submitting a PR to add those actions and learn some more Lua. 

You’re obviously a very capable programmer. Lua is easier than you think, looking forward to your PRs :)


> so I think this issue can be closed.

will close.

**Comment by ibhagwan** [comment]
@toupeira, my account apparently was shadow banned foe less than 24 hours due to an auto bot issue, it’s been cleared now but it’s very possible you didn’t receive the above notifications from me so check out the above comments / commits.

**Comment by toupeira** [comment]
@ibhagwan oh thanks, yes I didn't get a notification from your previous message :+1:  I did see the 404s and your thread on Reddit, glad it got resolved! :grinning: 

https://github.com/ibhagwan/fzf-lua/commit/cc4cb064b49c17ec39bad2263c1547aff464859a looks cool and works great here, thanks!

I wish you a happy easter weekend.

**Comment by ibhagwan** [comment]
> I wish you a happy easter weekend.

Ty and happy holidays! 🙏
