### ISSUE TITLE
Use lsp_finder with the result of lsp_workspace_symbols ?

### ISSUE THREAD

**Issue by athanase** [ibhagwan/fzf-lua#1108]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I am wondering if it would be possible to use `lsp_finder` feature with the result of a previous request from `lsp_workspace_symbols` or `lsp_document_symbols` for example.

Lets say I want to search all uses of a class I don't quit remember the name. I would first use the `lsp_workspace_symbols` which would help me find the name of the class I am looking for. And When pressing enter, the result (the symbol) would then be passed to the `lsp_finder` to find how it is used and where. 

Any idea on how to achieve this ? Would the best way be to use the plugin actions ?

Note: this plugin is certainly the most useful for me while working on code. Thanks for all the work.

**Comment by ibhagwan** [comment]
> Any idea on how to achieve this ? Would the best way be to use the plugin actions ?

## Option 1

What you need to do is first generate the LSP parameters for your query using:
https://github.com/ibhagwan/fzf-lua/blob/0c884bb24ab0fef204f315f34e711b13ece0ea9f/lua/fzf-lua/providers/lsp.lua#L409-L413

And then make sure that the finder function uses these parameters instead of the ones generated from the cursor position, these would probably need to be set here:
https://github.com/ibhagwan/fzf-lua/blob/0c884bb24ab0fef204f315f34e711b13ece0ea9f/lua/fzf-lua/providers/lsp.lua#L632

I’m also unsure how this would plan out with incoming/outgoing calls as these requires calling the LSP twice so you’d need to play with the code a bit to make this work.

## Option 2

Another option would be to move the cursor to the position of the symbol you wish to query / hack `core.__CTX` to make fzf-lua think it’s cursor is somewhere else and then run `lsp_ finder`
https://github.com/ibhagwan/fzf-lua/blob/0c884bb24ab0fef204f315f34e711b13ece0ea9f/lua/fzf-lua/core.lua#L237-L248

My instinct tells me option (2) is a bit easier but I can’t say I have thought this through properly.

**Comment by athanase** [comment]
Thank you for taking the time to answer this. 
It isn't trivial but I will try to give a shot at option 2.

**Comment by ibhagwan** [comment]
@athanase, turnsout we don't need to hijack the context, just send custom `lsp_params`, use the laest commit https://github.com/ibhagwan/fzf-lua/commit/455b94a8bd379888f7e6bd932cc256cb3918e529 and this `setup` and press `ctrl-y` to invoke `lsp_finder` for the selected symbol:
```lua
require("fzf-lua").setup({
  lsp = {
    symbols = {
      actions = {
        ["ctrl-y"] = function(selected, opts)
          local file = require("fzf-lua").path.entry_to_file(selected[1], opts)
          require("fzf-lua").lsp_finder({
            cwd = vim.loop.cwd(),
            lsp_params = {
              position = {
                line = file.line - 1,
                character = file.col - 1,
              },
              textDocument = { uri = vim.uri_from_fname(file.path) },
              context = { includeDeclaration = true },
            }
          })
        end
      },
    },
  }
})
```

**Comment by athanase** [comment]
Thanks again for taking the time for this feature. I pulled the latest version but I have an error when using the ctrl-y action in the symbol finder window.

```
  Error  08:23:30 PM notify.error [Fzf-lua] fn_selected threw an error: ...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:546: attempt to index field 'result' (a nil value)
stack traceback:
	.../jit/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:222: in function '__index'
	...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:546: in function <...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:538>
	...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:648: in function 'lsp_finder'
	/home/jit/.config/nvim/lua/plugins/fzf.lua:245: in function 'action'
	...t/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/actions.lua:72: in function 'act'
	.../jit/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:137: in function 'fn_selected'
	.../jit/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:215: in function <.../jit/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:214>
	[C]: in function 'xpcall'
	.../jit/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:214: in function <.../jit/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:208>
```

**Comment by ibhagwan** [comment]
@athanase, seems to be unrelated issues with incoming/outgoing calls, https://github.com/ibhagwan/fzf-lua/commit/78d25f820adf417517fe2e2525eb822b538c248f should fix it.

Can you also let me know which LSP server that was so I can see why call hierarchy behaves differently there?

**Comment by athanase** [comment]
@ibhagwan, the commit fixes the error and now the `lsp_finder` opens properly but with an empty result.

The LSP server I use is clangd.

`LspInfo` output
```
Client: clangd (id: 1, bufnr: [9, 8])
 	filetypes:       c, cpp, objc, objcpp, cuda, proto
 	autostart:       true
 	root directory:  xxx/test
 	cmd:             xxx/llvm-17.0.6-x86_64/bin/clangd -j=20 --background-index --clang-tidy --clang-tidy-checks=* --all-scopes-completion --cross-file-rename --completion-style=detailed --header-insertion-decorators --header-insertion=iwyu --pch-storage=memory)
```

**Comment by athanase** [comment]
I played with this feature a little bit and the problem does not come from the plugin I think.

I can find a specific symbol using `lsp_live_workspace_symbol` and if I open the file containing that symbol. I can also use lsp_find and I have complete list of all the usages. If I then do the same and use `ctrl-y` to open `lsp_finder` from within `lsp_live_workspace_symbol` it works.

But if have never opened the file since opening neovim (rather starting the LSP server I guess) the list of usages in `lsp_finder` is empty.

I do not know the internals of LSP servers, but it is as if `clangd` does not return a valid result for usages of one symbol if the file containing that symbol was never opened.

**Comment by ibhagwan** [comment]
That makes sense @athanase, if you don’t mind a buf switch you can run `actions.file_edit` and then the custom finder code, might not solve it if clangd needs a few seconds to load the data.

**Comment by athanase** [comment]
Ok. I will also try to fiddle with clangd's options (like background indexing stuff) tomorrow to see if this changes something also and report back to you.

**Comment by athanase** [comment]
No luck with the options of clangd. Disappointing but I don't think I have the skills to go further and try to solve this.

**Comment by ibhagwan** [comment]
As I mentioned if you don't mind the buffer switch you can probably get better results with:
```lua
       ["ctrl-y"] = function(selected, opts)
          require("fzf-lua").actions.file_edit(selected, opts) -- this should make the buffer switch
          local file = require("fzf-lua").path.entry_to_file(selected[1], opts)
          require("fzf-lua").lsp_finder({ ... })
```

Unfortuntaely I cannot do more than this, if the LSP doesn't preload certain symbols that's out of the scope of fzf-lua, it can only show the response of the LSP server.

**Comment by athanase** [comment]
Oups sorry, forgot about that. You are right, I don't mind the buffer switch. This add-on really perfects my daily use of fzf-lua !

**Comment by ibhagwan** [comment]
> Ok. I will also try to fiddle with clangd's options (like background indexing stuff) tomorrow to see if this changes something also and report back to you.

Well I hope this would work, sometimes the LSP requires some loading time ☺️ but if you didn’t change the default the request should be asynchronous so I’m hoping this works.
