### ISSUE TITLE
Git branch reflog

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/fzf-lua#111]
I wasn't getting any branches when trying to use this command. I tried running the `cmd` in the terminal and it complains about `--reflog` flag. I removed it and tried again in `nvim`. It started working as before. Wanted to check on this to see if this is a bug. I haven't tried all the other git commands but I did try `git_commits` which works fine with the flag. 

```
    branches = {
      prompt          = 'Branches❯ ',
      cmd             = "git branch --all --color --reflog",
      preview         = "git log --graph --pretty=oneline --abbrev-commit --color {1}",
      actions = {
        ["default"] = actions.git_switch,
      },
    },
```

**Comment by ibhagwan** [comment]
This was added by @jpe90 in PR #87, I’m not exactly sure what this does in the context of `git branches`.

It does work on my end so it’s possible it’s something related to your git version, can you post the output of `git —version`?

**Comment by hqkhan** [comment]
Oh gotcha. Here's output of `git --version` -> `git version 2.33.0`.

**Comment by ibhagwan** [comment]
I understand what happened now, in #88, @jpe90 added the `--reflog` in the wrong place to the README by mistake :-)

By copying the entire setup function from the README, you also accidentally copied the mistake, `git branches` should not have `--reflog`.

Fixed the README.
