### ISSUE TITLE
Bug: live_grep and live_grep related commands do not open anything.

### ISSUE THREAD

**Issue by ajkdrag** [ibhagwan/fzf-lua#1111]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.0-dev-2680+gd3e51603b

### Fzf version (`fzf --version`)

0.24 (devel)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

I used the quickstart script. When I hit Ctrl-L, nothing happens, no buffer, window opens.

**Comment by ibhagwan** [comment]
- Does anything else work `files`, `buffers`, etc?
- Does it work if you run `:FzfLua live_grep`?
- Does `ctrl-k` work?
- Is there any error in `:messages`?
- What terminal are you using and is it possible you have an overriding map for `ctrl-l`?

**Comment by ajkdrag** [comment]
Yes. Files, grep and everything else works fine.
Only think is anything with live_ doesn't open the UI.
When i run the Lua function directly live_grep, nothing happens in my neovim. I am using bash.
I can share my .dotfiles if needed.

**Comment by ibhagwan** [comment]
- Do you have `rg` installed?
- Does `:FzfLua live_grep rg_glob=false` work?
- What about `:FzfLua live_grep_native`?
- Does `:FzfLua grep_xxx`  variants work properly?
- Can you post a screnshot of the screen that opens up after `:FzfLua grep_project debug=true` (I'm interested in the `[DEBUG]` line inside fzf)?
- Does `:lua require("fzf-lua").fzf_live("rg -e")` work?
- How about `:lua require("fzf-lua").fzf_live("grep <query> *")`?

**Comment by ibhagwan** [comment]
Btw, I just realized your truly ancient fzf version which isn’t even supported by the maintainer of fzf itself.

I’ll make sure this works because I can but if you upgrade your fzf version this is most likely going to work and you’ll also get a better UI experience as the new versions contain quality of life improvements.

**Comment by ajkdrag** [comment]
Thanks, it works fine with updated fzf.
