### ISSUE TITLE
Bug: helptags preview doesn't work on windows

### ISSUE THREAD

**Issue by p00f** [ibhagwan/fzf-lua#1112]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Windows

### Shell

nu

### Neovim version (`nvim --version`)

NVIM v0.10.0-dev-2709+g00e9c6955

### Fzf version (`fzf --version`)

0.48.1 (d579e33)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({
    "fzf-native",
    winopts = {
        row = 1,
        width = 1,
        height = 0.4,
    }
})
require("fzf-lua").register_ui_select()
```

## Steps to reproduce
1) `:FzfLua helptags`
2) search for any built in help tag, for example `help`
3) Look at the preview window

`[bat error]: 'Files\Neovim\share\nvim\runtime\doc\helphelp.txt': The system cannot find the path specified.`

This is probably because the path is not quoted when giving it to bat - selecting the help tag works, and the full path is `C:/Program Files/Neovim/share/nvim/runtime/doc/helphelp.txt` - notice the space in `Program Files`, and that bat is trying to open `Files/...`

**Comment by ibhagwan** [comment]
Ty for the report @p00f, should work after https://github.com/ibhagwan/fzf-lua/commit/c838d9c8ebf208262463c6db0ec9af4d61c6b6fb.
