### ISSUE TITLE
Feature: Offer creating a git branch via git_branches

### ISSUE THREAD

**Issue by pBorak** [ibhagwan/fzf-lua#1114]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Hey, before I start, I'd really appreciate the work you've done on this plugin. It's easily my favorite and most used plugin that covers almost all of my use cases.

There's one thing that I miss, though. It would be cool if `git_branches` offered functionality to create a branch when a user inputs a branch that does not exist. Please let me know if you can see this being implemented into the core, or if I should rather bake the solution on my own and provide it as a default action in my own setup. Once again thank you for this great plugin ❤️ 

https://github.com/ibhagwan/fzf-lua/assets/45797239/19786317-adb4-4bcf-b300-ad32770beb2b

**Comment by ibhagwan** [comment]
Sure we can add that, however, I believe a proper way to add it would be another keybind, I don’t want to rely on having no fuzzy matches as you can still have a match while the exact typed branch doesn’t exist.

**Comment by pBorak** [comment]
Certainly, that would be effective! We can include a keybind for adding or deleting branches, similar to how Telescope operated.

https://github.com/nvim-telescope/telescope.nvim/blob/4626aaa2bcfdacf55fd6d44b430e2df81b2403ff/doc/telescope.txt#L3040

**Comment by ibhagwan** [comment]
@pBorak, try out the latest commit https://github.com/ibhagwan/fzf-lua/commit/abbd1fa8943583c6ccfa5be74238e7fb270d864d, as discussed it adds 2 new actions `ctrl-a` to add a branch (using prompt input for the name) and `ctrl-x` to delete the selected branch.

Below are the defaults (added to the main README) so you can control the behavior if you want to create branch+switch (default just creates the branch) or force delete unmerged branches:
```lua
require("fzf-lua").setup({
  git = {
    branches = {
      actions  = {
        ["default"] = actions.git_switch,
        ["ctrl-x"]  = { fn = actions.git_branch_del, reload = true },
        ["ctrl-a"]  = { fn = actions.git_branch_add, field_index = "{q}", reload = true },
      },
      -- If you wish to add branch and switch immediately
      -- cmd_add  = { "git", "checkout", "-b" },
      cmd_add  = { "git", "branch" },
      -- If you wish to delete unmerged branches add "--force"
      -- cmd_del  = { "git", "branch", "--delete", "--force" },
      cmd_del  = { "git", "branch", "--delete" },
    },
  }
})
```

**Comment by pBorak** [comment]
Thank you, it works perfectly.

**Comment by ibhagwan** [comment]
> Thank you, it works perfectly.

Fantastic, Ty for the update.
