### ISSUE TITLE
Bug:  `buffers` sets wrong buffer as "current buffer" if the actual current buffer is nobuflisted

### ISSUE THREAD

**Issue by tomtomjhj** [ibhagwan/fzf-lua#1117]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Ubuntu 22.04

### Shell

bash

### Neovim version (`nvim --version`)

0.10 b3f9da952

### Fzf version (`fzf --version`)

0.48.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--bind alt-a:select-all,alt-d:deselect-all,alt-t:toggle-all --color=dark

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Describe the bug / steps to reproduce

```
./scripts/mini.sh
:e README.md
:new
:set nobuflisted
:FzfLua buffers
```

![image](https://github.com/ibhagwan/fzf-lua/assets/19489738/81fff860-2705-4fe0-add7-b27b3e2d4d8e)
`README.md` is shown as the "current buffer" in the fzf window, rendering it not selectable, despite that the actual current buffer is the new empty nobuflisted buffer.

**Comment by ibhagwan** [comment]
Ty @tomtomjhj for reporting this.

Seems like a somewhat contrived example, I think the proper solution here would be always add the current buffer regardless of `buflisted` setting.

**Comment by ibhagwan** [comment]
@tomtomjhj, https://github.com/ibhagwan/fzf-lua/commit/b5e08be6835e7ef81d0b90ac58c185e276a771cd ignores `buflisted` for the current buffer.

**Comment by tomtomjhj** [comment]
Thank you! I stumbled on this issue when using a plugin that sets nobuflisted for the buffer that displays various information associated with some "main" buffer.
