### ISSUE TITLE
Unable to preview commits when using branch view

### ISSUE THREAD

**Issue by lynndylanhurley** [ibhagwan/fzf-lua#112]
This is my config:

```lua
-- local actions = require "fzf-lua.actions"
require('fzf-lua').setup {
  git = {
    commits = {
      cmd = 'git log --graph --color=always --date=short --format="%ad %C(auto)%h%d %an %s %C(black)%C(bold)%cr"'
    }
  }
}
```

This produces the branch graph view that I need to do my work. The problem is that the previewer is unable to parse the commit hash from the list items (see attached).

<img width="1061" alt="Screen Shot 2021-09-06 at 9 06 39 PM" src="https://user-images.githubusercontent.com/468037/132273510-45242531-8a00-48a1-ada0-738d206d87f8.png">

I'm guessing that I just need to pass in a smarter `preview` command. Can you think of anything that would work for the graph view?

**Comment by lynndylanhurley** [comment]
Was able to figure this out. 

This config:

```lua
require('fzf-lua').setup {
  git = {
    commits = {
      cmd = 'git log --graph --color=always --date=short --format="%ad %C(auto)%h%d %an %s %C(black)%C(bold)%cr"',
      preview = [[echo "{}" | grep -o "[a-f0-9]\{7\}" | head -1 | xargs -I % sh -c 'git show --color=always % | less -R']]
    }
  }
}
```

Produces this (attached):

![fzf-graph](https://user-images.githubusercontent.com/468037/132275864-46498a0c-a8f9-4230-b3f9-122ff684dcce.gif)

**Comment by ibhagwan** [comment]
Creative solution :-)

Just FYI, the default fzf delimiter (customizable if you wish), is space, that means that you could also just change the fzf placholder to `{3}` but that would only wouldn't solve the branches where you have more than 3 spaces before the commit hash, so your solution is spot on.
