### ISSUE TITLE
Bug: FzfLua command not available when plugin is installed using rocks.nvim

### ISSUE THREAD

**Issue by xm31** [ibhagwan/fzf-lua#1121]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

v0.10.0-dev-2739+ge2224a793 

### Fzf version (`fzf --version`)

0.48.0 (091b7eac)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--border

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

With [rocks.nivm](https://github.com/nvim-neorocks/rocks.nvim) installed run:
```
:Rocks install fzf-lua
```
 The `FzfLua` command is not available.
![image](https://github.com/ibhagwan/fzf-lua/assets/22982204/795d0ce1-e720-4e4a-bfd4-6cd14a20ebf7)

It is worth mentioning that `lua require('fzf-lua').files()` works just fine.

The issue is not reproduced when fzf-lua is installed using  [lazy.nvim](https://github.com/folke/lazy.nvim) or even when in installed from the git repository with [rocks-git](https://github.com/nvim-neorocks/rocks-git.nvim)

**Comment by ibhagwan** [comment]
@mrcjkb created the lua-rocks template, do you know why this happens?

Perhaps it’s time to update https://github.com/ibhagwan/fzf-lua/blob/main/plugin/fzf-lua.vim (which creates the commands and doesn’t seem to be loaded) to lua, I wonder if that will help.

**Comment by ibhagwan** [comment]
@xm31, should work after the latest commit, Ty @mrcjkb!

**Comment by ibhagwan** [comment]
FYI, this prompted https://github.com/ibhagwan/fzf-lua/commit/cd966d7e556b91d56b2cf3582d1a5b4f937a8f0e so we now have auto-completion the command arguments (auto-generated from defaults):
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/8aceb150-91b3-4a9e-8217-9acb1f5c6c7f)

It's also possible to supply nested options to the command such as:
```
:FzfLua files winopts.fullscreen=true
```

**Comment by xm31** [comment]
It sounds great! I will give it a try. Now I am waiting for the luarocks-release action to be triggered.

**Comment by ibhagwan** [comment]
Ty @xm31, currently planning integration with `nvim-cmp` with documentation window for fzf-lua opts so it should be even better.
