### ISSUE TITLE
Bug: bcommit `preview` `{file}` placeholder is shellescaped but `cmd` `{file}` is not

### ISSUE THREAD

**Issue by oedotme** [ibhagwan/fzf-lua#1129]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

macOS

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.49.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

```sh
  --height 40% --reverse --multi --preview-window noborder --no-separator
  --prompt '› ' --pointer '›' --marker '›'
  --color=fg:6,bg:-1,hl:2,gutter:-1,border:6
  --color=fg+:6,bg+:15,hl+:5
  --color=info:2,prompt:6,pointer:5
  --color=marker:2,spinner:2,header:2
  --bind ctrl-y:preview-up,ctrl-e:preview-down,ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down
```

### Describe the bug / steps to reproduce

Running `git_bcommits` on a file that contains parenthesis `()` fails with the default `cmd` used:

```lua
{
  git = {
    bcommits = {
      cmd = 'git log --color --pretty=format:"..." {file}',
      preview = 'git show --color {1} -- {file}',
    },
  },
}
```

```sh
[Command failed: git log --color --pretty=format:"..." src/(app)/file.js]
```

However with the `preview` command, `{file}` seems to be replaced with the filename wrapped by double quotes.

At the moment using a custom `cmd` with double quotes around `{file}` gets it to work:

```lua
{
  git = {
    bcommits = {
      cmd = 'git log --color --pretty=format:"..." "{file}"',
      preview = 'git show --color {1} -- {file}',
    },
  },
}
```

**Comment by ibhagwan** [comment]
Ty for the report @oedotme!

Fixed in https://github.com/ibhagwan/fzf-lua/commit/36df11e3bbb6453014ff4736f6805b5a91dda56d.

**Comment by oedotme** [comment]
Thanks for the quick fix!
