### ISSUE TITLE
Live grep and then open file in new buffer?

### ISSUE THREAD

**Issue by winston0410** [ibhagwan/fzf-lua#113]
I have just tried out live grep, and it works great. But one thing I am unable to achieve is I want to launch the file pressing Enter from the result list. Is it possible right now?

**Comment by winston0410** [comment]
Figured this out myself:

```lua
			require("fzf-lua").setup({
				fzf_layout = "reverse-list",
				files = {
					cmd = "fd",
					git_icons = true, -- show git icons?
					file_icons = true, -- show file icons?
					color_icons = true, -- colorize file|git icons
				},
				grep = {
					prompt = "",
					actions = {
						["Enter"] = actions.file_edit,
					},
				},
			})
```

**Comment by ibhagwan** [comment]
> Figured this out myself:
> 
> ```lua
> 			require("fzf-lua").setup({
> 				fzf_layout = "reverse-list",
> 				files = {
> 					cmd = "fd",
> 					git_icons = true, -- show git icons?
> 					file_icons = true, -- show file icons?
> 					color_icons = true, -- colorize file|git icons
> 				},
> 				grep = {
> 					prompt = "",
> 					actions = {
> 						["Enter"] = actions.file_edit,
> 					},
> 				},
> 			})
> ```

This is interesting, the default action supposed to be `Enter` already, what is your setup? What is your default key to select with fzf in the shell?

**Comment by winston0410** [comment]
For the default key to select with fzf in shell, do you mean the keybinding which trigger fzf in shell? I think I haven't set it in `.zshrc`, thats why I bumped into this error. Not sure how to make handling this more graceful though.
