### ISSUE TITLE
Bug: Empty preview keeps popup when resize in split window

### ISSUE THREAD

**Issue by jamestansx** [ibhagwan/fzf-lua#1130]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Arch Linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.48.1 (9ffe951f)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

```
--color=fg:#737c73,bg:#181616,hl:#8ba4b0 
--color=fg+:#c5c9c5,bg+:#282727,hl+:#8ba4b0 
--color=info:#c4b28a,prompt:#c4b28a,poin ter:#8ea4a2
--color=marker:#8ea4a2,spinner:#8ea4a2,header:#8ba4b0
```

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({
    winopts = {
        border = false,
        preview = {
            hidden = "hidden",
        },
        on_create = function()
            vim.wo.statusline = " > fzf"
        end,
    },
    winopts_fn = function()
        local split = "belowright new"
        local height = math.floor(vim.o.lines * 0.2)

        return {
            split = string.format("%s | resize %s", split, height),
        }
    end,
})
```

### Describe the bug / steps to reproduce

Resizing the terminal will cause an empty preview to show up while Fzf is in split window, but not in float window.

https://github.com/ibhagwan/fzf-lua/assets/45304579/30c168ef-962a-4fc4-a5c9-82765e31aba5

**Comment by jamestansx** [comment]
Setting `previewer` to false in `files` should solve the problem

```lua
files = { previewer = false  }
```

**Comment by ibhagwan** [comment]
This is due to the auto-layout that changes the preview rotation upon resize on `flex` layout:
https://github.com/ibhagwan/fzf-lua/blob/36df11e3bbb6453014ff4736f6805b5a91dda56d/lua/fzf-lua/core.lua#L345-L353

Obvipisly this is a bug, I’ll make sure this also works as expected when starting hidden.

**Comment by ibhagwan** [comment]
> Another thing is that when using bat as the default previewer, flex layout doesn't work as how builtin previewer would. It would always be on the right (the default location).


It works, but the the width trigger is a bit smaller, the split window width is a bit smaller than neovim so you need to resize a bit more.

**Comment by jamestansx** [comment]
Weirdly, I can't seem to make it work. The only config changes I made is

```lua
        preview = {
            default = "bat",
        },
```

https://github.com/ibhagwan/fzf-lua/assets/45304579/e89e8aea-fee6-4c48-83de-e81957ff1d6b

**Comment by ibhagwan** [comment]
> Weirdly, I can't seem to make it work. The only config changes I made is

Can you run `:FzfLua files debug=true` and post the output command in `:messages`?

It should contain the transformer that does the auto resize, check out the `--bind` flag:
```
--bind 'f4:toggle-preview,alt-a:toggle-all,shift-down:preview-page-down,ctrl-z:abort,ctrl-b:half-page-up
,ctrl-a:beginning-of-line,resize:transform([ $FZF_COLUMNS -le 130 ] && echo change-preview-window:down:45% || ech
o change-preview-window:right:60%),ctrl-e:end-of-line,ctrl-f:half-page-down,f3:toggle-preview-wrap,shift-up:previ
ew-page-up,ctrl-u:unix-line-discard'
```

Btw, this seems to be a much more complex issue to solve with the builtin previewer due to the way this currently works, there's a neovim float which is covering an empty fzf preview window, since there currently isn't a variable to determine if the current preview is hidden this causes all sorts of issues with the resize/toggle, I'm afraid there's not much I can do here other than disable this functionality when using the builtin previewer and starting `hidden` and even that isn't really a solution as things get messy if you then use F4 for toggle (layouts can mismatch).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/8161cb9e0fcaab67dab0b99916932605f11aad6b

I pushed the workaround for starting hidden, note that this will cause another issue since now the underlying fzf layout won't adapt if you resize and then toggle with F4 you might see this:

![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/7a317bbc-08c4-4d42-af96-4a4536b66f2f)

The only solution current'y is to start `nohidden` or disable `flex`, we'll have to wait for fzf to introduce another env var for determing the hidden status (or use a temp file which I'd like to avoid).

**Comment by jamestansx** [comment]
> Can you run :FzfLua files debug=true and post the output command in :messages?

```
[Fzf-lua]: FZF_DEFAULT_COMMAND: fd --color=never --type f --hidden --follow --exclude .git || true
[Fzf-lua]: fzf cmd: fzf --expect "ctrl-c,ctrl-q,alt-l,alt-q,esc,ctrl-g,ctrl-s,ctrl-t,ctrl-v" --multi --bind "ctrl-z:abort,shift-down:preview-page-down,f4:toggle-preview,f3:toggle-preview-wrap,shift-up:preview-page-up,alt-a:toggle-all,resize
:transform([ $FZF_COLUMNS -le 120 ] && echo change-preview-window:down:45% || echo change-preview-window:right:60%),ctrl-e:end-of-line,ctrl-a:beginning-of-line,ctrl-b:half-page-up,ctrl-u:unix-line-discard,ctrl-f:half-page-down" --preview-wi
ndow "nohidden:border:nowrap:right:60%" --preview 'VIMRUNTIME="/usr/share/nvim/runtime" "/usr/bin/nvim" -n --headless --clean --cmd "lua vim.g.did_load_filetypes=1; loadfile([[/home/jamestansx/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shel
l_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/run/user/1000/fzf-lua.1712947636.15400.1]], fnc_id=1 , debug=true})" -- {}' --print-query --height "100%" --border "none" --info "inline-right" --header ":: <^[[38;2;255;235;205mctrl-g^
[[0m> to ^[[38;2;255;64;64mDisable .gitignore^[[0m" --ansi --layout "reverse" --delimiter "[:]" --prompt "~/" > "/tmp/nvim.jamestansx/kLNPjH/1"
```



Yes it does contain the transformer. One thing I noticed is that if I debug with `--bind resize:transform-header(echo $FZF_COLUMNS)`, it doesn't print any value. But, putting `zero` binding from `builtin` to `fzf` does work.

**Comment by jamestansx** [comment]
> https://github.com/ibhagwan/fzf-lua/commit/8161cb9e0fcaab67dab0b99916932605f11aad6b
This works fine.
> The only solution current'y is to start nohidden or disable flex
I think this is okay for now. Thanks for the quick fix!

**Comment by ibhagwan** [comment]
> Yes it does contain the transformer. One thing I noticed is that if I debug with --bind resize:transform-header(echo $FZF_COLUMNS)

Perhaps a combination of binds triggering a bug in fzf? If the transformer appears in the commands but doesn’t do anything might be an upstream issue.

> I think this is okay for now. Thanks for the quick fix!

Alright, I’ll close this for the time being until further upstream changes.

**Comment by jamestansx** [comment]
> One thing I noticed is that if I debug with --bind resize:transform-header(echo $FZF_COLUMNS), it doesn't print any value.

Though weirdly, adding `zero` binding like how the `builtin` previewer does would make it works. I wonder is it just on my side that the `resize` binding doesn't work?

```diff
diff --git a/lua/fzf-lua/previewer/fzf.lua b/lua/fzf-lua/previewer/fzf.lua
index b4ee701..183e284 100644
--- a/lua/fzf-lua/previewer/fzf.lua
+++ b/lua/fzf-lua/previewer/fzf.lua
@@ -441,4 +441,16 @@ function Previewer.help_tags:cmdline(o)
   return act
 end
 
+function Previewer.base:zero(_)
+  self._zero_lock = self._zero_lock or path.normalize(vim.fn.tempname())
+  local act = string.format("execute-silent(mkdir %s && %s)",
+    libuv.shellescape(self._zero_lock),
+    shell.raw_action(function(_, _, _)
+      vim.defer_fn(function()
+        vim.fn.delete(self._zero_lock, "d")
+      end, self.delay or 0)
+    end, "", self.opts.debug))
+  return act
+end
```
