### ISSUE TITLE
Feature: use `kitten icat` for previewing images

### ISSUE THREAD

**Issue by yujinyuz** [ibhagwan/fzf-lua#1136]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

When you run `kitten icat /path/to/img.jpeg` it displays the image properly within the terminal.

<img width="1159" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/10972027/58e0111a-5f63-42ba-960e-686cc409f267">

I tried using that command as a previewer but can't seem to get it to work.

<img width="1463" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/10972027/631c9bf0-81ab-4412-bb19-c3e4a26351c9">

```
    previewers = {
      builtin = {
        extensions = {
          ['png'] = { 'kitten', 'icat' },
          ['webp'] = { 'kitten', 'icat' },
          ['jpg'] = { 'kitten', 'icat' },
        },
      },
    },
```

It also works with the `fzf-preview.sh` command provided inside `fzf`'s repository

<img width="1728" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/10972027/d4477631-8b4b-4327-ba22-afe007a13379">

**Comment by ibhagwan** [comment]
Not sure why you're getting the binary file message (probably misconfiguration).

In any event, this cannot work as `kitty icat` isn't supported inside a neovim terminal (https://github.com/neovim/neovim/issues/12991), open a neovim terminal and you'll see this:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/493d7f3e-03d8-4e77-bad1-23589a80de16)

**Comment by yujinyuz** [comment]
@ibhagwan Shame that it doesn't work on neovim (yet). Anyway thanks for the prompt response!

**Comment by Whenrow** [comment]
It seems the feature has been implemented in https://github.com/neovim/neovim/pull/37914 🎉
