### ISSUE TITLE
Bug: Error while calling lua chunk

### ISSUE THREAD

**Issue by labdiynez** [ibhagwan/fzf-lua#1137]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Unraid

### Shell

zsh

### Neovim version (`nvim --version`)

0.9.5

### Fzf version (`fzf --version`)

0.50

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

-

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

If I use mini.sh I can use hotkeys no problem but I use vim-plug after installing the plugin can't use hotkeys and sorry I'm a newbie.

```
Error detected while processing /root/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: ...t/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/init.lua:399: '<eof>' expected near
 'vim'
stack traceback:
        [C]: in function 'error'
        vim/_init_packages.lua: in function <vim/_init_packages.lua:0>
        [C]: in function 'require'
        /root/.config/nvim/init.lua:17: in main chunk
Press ENTER or type command to continue
```

/root/.config/nvim/init.lua
```
local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug('ibhagwan/fzf-lua', { ['branch'] = 'main' })
Plug('nvim-tree/nvim-web-devicons')
vim.call('plug#end')

vim.api.nvim_set_keymap("n", "<C-\\>", [[<Cmd>lua require"fzf-lua".buffers()<CR>]], {})
vim.api.nvim_set_keymap("n", "<C-k>", [[<Cmd>lua require"fzf-lua".builtin()<CR>]], {})
vim.api.nvim_set_keymap("n", "<C-p>", [[<Cmd>lua require"fzf-lua".files()<CR>]], {})
vim.api.nvim_set_keymap("n", "<C-l>", [[<Cmd>lua require"fzf-lua".live_grep_glob()<CR>]], {})
vim.api.nvim_set_keymap("n", "<C-g>", [[<Cmd>lua require"fzf-lua".grep_project()<CR>]], {})
vim.api.nvim_set_keymap("n", "<F1>", [[<Cmd>lua require"fzf-lua".help_tags()<CR>]], {})

require("fzf-lua").utils.info(
  "|<C-\\> buffers|<C-p> files|<C-g> grep|<C-l> live grep|<C-k> builtin|<F1> help|")

```

**Comment by ibhagwan** [comment]
I’m really not sure if this is how to use vim plug, it seems like it’s expecting vimscript and getting lua?
```
init.lua:399: '<eof>' expected near 'vim'
```

I’m not well versed in vimscript nor do I want to be, but this doesn’t look like an fzf-lua bug, as you yourself wrote with `mini.sh` it all works.

If you’re using neovim I’d recommend using [lazy.nvim](https://github.com/folke/lazy.nvim) for plug-in manager.

**Comment by labdiynez** [comment]
> I’m really not sure if this is how to use vim plug, it seems like it’s expecting vimscript and getting lua?
> 
> > `init.lua` doesn’t even have line 399…
> 
> ```
> fzf-lua/lua/fzf-lua/init.lua:399: '<eof>' expected near 'vim'
> ```
> 
> I’m not well versed in vimscript nor do I want to be, but this doesn’t look like an fzf-lua bug, as you yourself wrote with `mini.sh` it all works.
> 
> If you’re using neovim I’d recommend using [lazy.nvim](https://github.com/folke/lazy.nvim) for plug-in manager.

Thanks for the quick help and the nice plugin, I enjoyed it. Now it works like a charm.
