### ISSUE TITLE
Feature: Only show files in oldfiles, ignore directories

### ISSUE THREAD

**Issue by FooSoft** [ibhagwan/fzf-lua#1138]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Thank you for this excellent project, I love fzf-lua! One small tweak to make things even better would be to have an option to ignore non-file entries (such as directories) in the `oldfiles` listing. Please note that I'm not talking about excluding the contents of a directory, but the actual directory itself!

I often browse directories in vim using vim-dirvish, which ends up adding the directory path to `oldfiles`. Attempting to preview these results in a "Preview is not supported for binary files", which is incorrect since it's not even a file. Having these directory entries show up in `oldfiles` just adds noise, so ideally there would be a way to disable it. I imagine that something could be done similar to how named pipes were avoided in the following commit:

https://github.com/ibhagwan/fzf-lua/commit/416b4745dbcfbba92fd9d29cad3f30ece6a6a4f3

![Screenshot_20240416_190329](https://github.com/ibhagwan/fzf-lua/assets/544478/90c5511f-a12b-4678-9f0b-8b720ab43fb1)

**Comment by ibhagwan** [comment]
Ty for the kind words @FooSoft, I would actually consider this a bug, `file_is_reabable` shouldn’t return true for direcrory entries, I’ll fix that.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/62cb8f37b3a017e6b2401726c96e02498f332b70

@FooSoft, should work as expected now.

**Comment by FooSoft** [comment]
@ibhagwan works perfectly, thanks for the incredibly fast turnaround!
