### ISSUE TITLE
Default mappings suggestions

### ISSUE THREAD

**Issue by krady21** [ibhagwan/fzf-lua#114]
I wanted to suggest some alternative default mappings for `<Ctrl-d>` and `<Ctrl-u>`. I think that most of the time you don't even need to scroll half page down or up through the fzf search results (which is a testament to how good the fuzzy finding algorithm is). My suggestion is to use `<Ctrl-u>` to delete backwards to the start of the line, which would make it compatible with the readline binding that behaves the same in insert mode in vim. I use this quite often in insert mode instead of pressing `<Ctrl-w>` a couple of times. I think that fzf, like other terminal programs, uses `<Ctrl-d>` as the EOF special control character, which is used to close the program.
I think these bindings would make a little bit more sense and will be more similar to how they are used in other places inside the editor or by the terminal version of fzf. Different mappings could be found for scrolling half page down or half page up in the meantime.

I just wanted to give my two cents here and this is certainly open to discussion. You obviously have the last word regarding default mappings so feel free to close this if you don't think the suggestions are relevant or if you don't agree with them.

**Comment by ibhagwan** [comment]
Personally, While I do miss the `ctrl-u` functionality my `ctrl-d|ctrl-u` muscle memory is too strong to make me override.

I guess it’s a all a matter of personal preference, that’s why it’s customizable, I don’t object to changing the defaults and customizing if I need to, the question is what would make the most sense for most users (who not all customize) and since I already went with it and a decent amount of users are already using it I’d be weary of changing their defaults.

**Comment by mcchrish** [comment]
I'd like to add that there's probably a lot of users that are coming from fzf.vim and trying out this plugin. I guess one way to welcome them and have less friction is to have a closer default to fzf.vim.
It's also probably stubborn muscle memory at this point that the first things I did after moving to fzf-lua was make the looks and keybindings as close to fzf.vim.

**Comment by ibhagwan** [comment]
> I'd like to add that there's probably a lot of users that are coming from fzf.vim and trying out this plugin. I guess one way to welcome them and have less friction is to have a closer default to fzf.vim.
> It's also probably stubborn muscle memory at this point that the first things I did after moving to fzf-lua was make the looks and keybindings as close to fzf.vim.

I understand, I still think it's very subjective, although anecdotal, I used `fzf.vim` for a long time and one of the first things I did when installing it was to change the default binds to what I was using in my shell which was based on keybinds I was used to from using vim.

I think the best way forward is just to have superb documentation which is definitely lacking ATM, I've been so busy with the code that I kept procrastinating the wiki part.

**Comment by krady21** [comment]
My reasoning was that most of the time people don't even need to scroll that much through the results list. I don't recall if i ever needed to go more than 2-3 lines up or down. Meanwhile, I have used `<Ctrl-u>` in a lot of places to delete until the beginning of a line, including inside vim.

**Comment by ibhagwan** [comment]
Alright, I'm think I'm getting into something I feel comfortable with that doesn't conflict with any default binds and is pretty comfortable too, this will be coupled with changing the default `ctrl-q` to send to quickfix list with `alt-q` so that you can just `toggle-all + send to qf` without leaving the `alt` key (as `ctrl-a` is now restored to `beggining-of-line`).

The below will be the new binds, anyone has any objections/recommendations (btw, I know I don't need to specify binds that are already default as `ctrl-u|d` but might be nice so users know what it does from the README?)?

```lua
    fzf_binds           = {
        'f2:toggle-preview',
        'f3:toggle-preview-wrap',
        'shift-down:preview-page-down',
        'shift-up:preview-page-up',
        'ctrl-d:delete-char/eof',
        'ctrl-u:unix-line-discard',
        'ctrl-f:half-page-down',
        'ctrl-b:half-page-up',
        'alt-a:toggle-all',
    },
```

**Comment by ibhagwan** [comment]
I just pushed the change with a "deprecated" warning for those relying on `ctrl-q` to send to quickfix list, this looks good IMO.

**Comment by kdheepak** [comment]
I can't remember whose config I stole this from but I have the following bound to enter: 

```lua
local function should_qf(selected)
  if #selected <= 2 then
    return false
  end

  for _, sel in ipairs(selected) do
    if string.match(sel, "^.+:%d+:%d+:") then
      return true
    end
  end

  return false
end

local function edit_or_qf(selected, opts)
  if should_qf(selected) then
    actions.file_sel_to_qf(selected, opts)
    vim.cmd("cc")
  else
    actions.file_edit(selected, opts)
  end
end
```

If I'm multiple selecting, I almost always want to open the results in the quickfix window.

**Comment by ibhagwan** [comment]
> I think we should add example configurations in the Wiki. Users can contribute to that quite easily.

Oh the dreaded Wiki

**Comment by ibhagwan** [comment]
No complaints about the new defaults, closing.
