### ISSUE TITLE
Bug: Cannot toggle fullscreen when using winopts.split

### ISSUE THREAD

**Issue by adambarjo** [ibhagwan/fzf-lua#1146]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux openSUSE-Tumbleweed

### Shell

Zsh

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.50 (0.50.0)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=fg:#908caa,bg:-1,hl:#31748f --color=fg+:#e0def4,bg+:#1f1d2e,hl+:#9ccfd8 --color=info:#f6c177,prompt:#31748f,pointer:#ebbcba --color=marker:#c4a7e7,spinner:#f6c177,header:#6e6a86 --reverse

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({
  winopts = {
    split = "aboveleft new",
  },
})
```

### Describe the bug / steps to reproduce

Steps to reproduce:
- Open FzfLua
- Press F2 to toggle fullscreen

Nothing happens when I do this, it stays inside the split. When I press F1, it shows in the list of keymaps that F2 will toggle fullscreen. I wonder if this is a limitation of the split option, if so, maybe it should not be in the help list when enabled to avoid confusion?

Amazing work on this plugin btw, I use it everyday.

**Comment by ibhagwan** [comment]
Unfortunately full screen is not supported with the split command only with floating window.

You  can use a floating window and try emulating a split by using full width and row=1.

**Comment by ibhagwan** [comment]
Closing as this is not planned ATM, feel free to reopen if you're having issues setting up the float in a similar layout to a vertical/horizontal split.
