### ISSUE TITLE
Bug: tmux buffer_list item selection won't yank into the unnamed register

### ISSUE THREAD

**Issue by morhaham** [ibhagwan/fzf-lua#1149]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

0.9.5

### Fzf version (`fzf --version`)

0.44.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
return {
  "ibhagwan/fzf-lua",
  -- optional for icon support
  dependencies = { "nvim-tree/nvim-web-devicons" },
  opts = function()
    local actions = require("fzf-lua").actions
    return {
      keymap = {
        fzf = {
          ["ctrl-a"] = "toggle-all",
        },
      },
      actions = {
        files = {
          ["default"] = actions.file_edit_or_qf,
          ["ctrl-s"] = actions.file_split,
          ["ctrl-v"] = actions.file_vsplit,
          ["ctrl-t"] = actions.file_tabedit,
          ["ctrl-q"] = actions.file_sel_to_qf,
          ["ctrl-l"] = actions.file_sel_to_ll,
        },
        buffers = {
          -- providers that inherit these actions:
          --   buffers, tabs, lines, blines
          ["default"] = actions.buf_edit,
          ["ctrl-s"] = actions.buf_split,
          ["ctrl-v"] = actions.buf_vsplit,
          ["ctrl-t"] = actions.buf_tabedit,
        },
      },
    }
  end,
  keys = {
    {
      "<leader>ff",
      "<cmd>lua require('fzf-lua').files({ resume = true, fd_opts = '--color=never --type f --hidden --follow --no-ignore' })<CR>",
      desc = "Find files",
    },
    {
      "<leader><leader>",
      "<cmd>lua require('fzf-lua').git_files({ resume = true })<CR>",
      desc = "Find git files",
    },
    {
      "<leader>fb",
      '<cmd>lua require("fzf-lua").buffers()<CR>',
      desc = "Find buffers",
    },
    {
      "<leader>fq",
      '<cmd>lua require("fzf-lua").quickfix()<CR>',
      desc = "Find in quickfix list",
    },
    {
      "<leader>fl",
      '<cmd>lua require("fzf-lua").loclist()<CR>',
      desc = "Find in location list",
    },
    {
      "<leader>fa",
      '<cmd>lua require("fzf-lua").args()<CR>',
      desc = "Find in argument list",
    },
    {
      "<leader>/",
      "<cmd>lua require('fzf-lua').live_grep({ resume = true })<CR>",
      desc = "Live grep",
    },
    {
      "<leader><C-_>", -- since tmux maps <C-/> to <C-_>
      "<cmd>lua require('fzf-lua').live_grep({ cmd = [[rg --color=always --smart-case -uuu ]] })<CR>",
      desc = "Live grep no ignores",
    },
  },
}

```

### Describe the bug / steps to reproduce

entering `:FzfLua tmux_buffers`, I select one item with `<CR>`. I cannot see it in the unnamed register.
<img width="1651" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/3867713/3484eeff-6748-4d8d-9eda-2f5d5102722e">
<img width="1587" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/3867713/8ab2df1b-30aa-4d91-af8b-d296b169557d">

**Comment by ibhagwan** [comment]
@morhaham, ty for the report, should work as expected with https://github.com/ibhagwan/fzf-lua/commit/2a1bb74da8e409d8c534a8f43d7fb0f8acc85207.

**Comment by morhaham** [comment]
> @morhaham, ty for the report, should work as expected with [2a1bb74](https://github.com/ibhagwan/fzf-lua/commit/2a1bb74da8e409d8c534a8f43d7fb0f8acc85207).

hi, it yanks to the unnamed register `"`, but not to the default clipboard register`*`. So with `smartyank` I can't use `p` directly to paste. Btw thank you for these amazing plugins..

**Comment by ibhagwan** [comment]
Ty for your kind words @morhaham.

You can set the `register` opt to use any register:
https://github.com/ibhagwan/fzf-lua/blob/2a1bb74da8e409d8c534a8f43d7fb0f8acc85207/lua/fzf-lua/actions.lua#L845

```lua
:FzfLua tmux_buffers register=*
```

**Comment by ibhagwan** [comment]
> edit: ok I found that when i remove clipboard = "unnamedplus" from the options now i can paste directly with p. Maybe smartyank should disable this option by default?

@morhaham, from the smartyank README:

> In addition I also wanted separation between neovim and the system clipboard so I started using `:set clipboard=""`

I am not a big fan of force overriding users config options (especially clipboard), smartyank assumes you’re already been through the journey of messing with the clipboard option and returning to the default of not polluting your system’s primary/secondary by using `clipboard=unnamedplus` (which sends every `d/c` op into the system clipboard).

These lines from my personal config might be a tell :)

https://github.com/ibhagwan/nvim-lua/blob/dfb2132e6d519f3a18e067847a9b166cbac58d8c/lua/options.lua#L15-L19
```lua

-- DO NOT NEED ANY OF THIS, CRUTCH THAT POULLUTES REGISTERS
-- vim clipboard copies to system clipboard
-- unnamed     = use the * register (cmd-s paste in our term)
-- unnamedplus = use the + register (cmd-v paste in our term)
-- o.clipboard         = 'unnamedplus'
```
