### ISSUE TITLE
Bug: Commit f1c65ed breaks fzf-vim preset

### ISSUE THREAD

**Issue by K9-guardian** [ibhagwan/fzf-lua#1155]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.29

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
   "fzf-vim",
})
```

### Describe the bug / steps to reproduce

I get this error when trying to use `:Files` with the fzf-vim preset. This is the error with `mini.sh`
```
E5108: Error executing lua [string ":lua"]:1: ...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:579: attempt to index field '--info' (a boolean value)
stack traceback:
        [C]: in function 'files'
        [string ":lua"]:1: in main chunk
``` 
I rolled back my `fzf-lua` to 4555533 (parent of f1c65ed) and I don't get this error. I'm guessing something in this commit changed how the preset is supposed to inherit the fzf options.

**Comment by ibhagwan** [comment]
@K9-guardian, shuold work as expected with https://github.com/ibhagwan/fzf-lua/commit/9e7b9f8d79c1a7b470b9d979e0a7dbf1a181ed67, ty for the report!
