### ISSUE TITLE
Using `FzfLua live_grep cwd /path/to/current_folder` gives different results than `FzfLua live_grep cwd .`

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#116]
When using `/path/to/current_folder` as cwd, i.e. when using the explicit path to any folder, the picker always shows the absolute path of files in the picker. For paths that are nested, it makes it harder to see what the name of the files, and requires horizontal scrolling. 

On the left is `Telescope live_grep cwd=/Users/USERNAME/gitrepos/HELICS.jl` and on the right is `FzfLua live_grep cwd=/Users/USERNAME/gitrepos/HELICS.jl`:

<img width="1680" alt="Screen Shot 2021-09-07 at 3 18 16 PM" src="https://user-images.githubusercontent.com/1813121/132412335-10881fdb-e4b9-4297-9d03-24bd66865d9c.png">

**Comment by ibhagwan** [comment]
Shouldn't be a problem to fix, I can make the file names relative same way `files()` show relative results when using `cwd`.

**Comment by kdheepak** [comment]
That'd be great! Thank you so much. 

I guess less important, but it would also be nice if you could add 

1) `--header=searching in $cwd` to `live_grep`. 
2) dev file icons to `live_grep` the way it works in `files`.

**Comment by ibhagwan** [comment]
> 1. `--header=searching in $cwd` to `live_grep`.
> 2. dev file icons to `live_grep` the way it works in `files`.

1. Why do we need a header when the prompt is already showing what you’re searching for (unless you want the `cwd` there?)
2. Not possible, when using `change:reload` fzf doesn’t run any callback so I can’t do any processing to the lines, that’s why it’s missing to begin with.

**Comment by kdheepak** [comment]
For 1. yeah, I wanted the `cwd` in there. I use `live_grep` across multiple repos often. 

For 2. oh, that's unfortunate. All good then :)

**Comment by ibhagwan** [comment]
`cwd` should now be displayed properly for both `grep` and `live_grep`.

Added search header options to both `grep` and `live_grep`, for `live_grep` it will only display the `cwd` since the search term is always at the prompt, `cwd` will only be displayed if changed from default.
