### ISSUE TITLE
Bug: FzfLuaNormal not working in nvim nightly

### ISSUE THREAD

**Issue by towry** [ibhagwan/fzf-lua#1161]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.0-dev-build-20231109-1627-gefaf37a2b Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Fzf version (`fzf --version`)

0.50.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

not matter

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

https://github.com/ibhagwan/fzf-lua/discussions/1160

### Describe the bug / steps to reproduce

[Not needed for now, see the discussion for detail.](https://github.com/ibhagwan/fzf-lua/discussions/1160)

**Comment by ibhagwan** [comment]
@towry, I verified https://github.com/ibhagwan/fzf-lua/commit/b107fb7a3893bcfb2d27b6f397cf290b3e0d1ca7 with the latest nightly, can you also verify?

**Comment by towry** [comment]
mini.sh works, but my config doesn't, i need to investigate further.

**Comment by ibhagwan** [comment]
> mini.sh works, but my config doesn't, i need to investigate further.

You might be overriding the `fg|bg` with fzf_colors, is `FzfLuaBorder` working for you now (the border is a separate window unaffected by `fzf_colors`)?

**Comment by towry** [comment]
If i run min.sh in /tmp, it works. but not working if running inside $HOME/

**Comment by ibhagwan** [comment]
> If i run min.sh in /tmp, it works. but not working if running inside $HOME/

Why would the path make any difference to neovim highlights, maybe you have a mismatch of runtimes and the said change that caused this issue somehow prevents this from working?

This is highly suspicious as I didn’t remove any highlight from the float windows I just added setting `NormalFloat` on top of the already set `Normal`.

**Comment by towry** [comment]
I notice your mini.sh doesn't use `--clean` this affect the difference. with --clean, it will work.

**Comment by towry** [comment]
```vim
augroup vimrc | autocmd! | augroup end

set nocompatible
set number
set laststatus=2

" change this to your local coc.nvim location.
set runtimepath^=/Users/towry/.local/share/nvim/lazy/fzf-lua
filetype plugin indent on
syntax on

set expandtab shiftwidth=4 tabstop=4 softtabstop=4
```

1. run `nvim -u mini.vim`
2. run `:FzfLua files hls.normal=IncSearch hls.border=IncSearch`

![image](https://github.com/ibhagwan/fzf-lua/assets/8279858/eba91fed-af05-4de3-a8bc-2ab334cc2d8b)

**Comment by ibhagwan** [comment]
Actually I know what this bug is, it's something I already fixed in `cmp_src` branch, specifying two dotted options with the `:FzfLua hls.normal=... hls.border=...` can randomly bug out (one will be missing) due to map ordering.

This will probably work for you:
```lua
:lua require("fzf-lua").files({ hls = { normal="IncSearch", border="IncSearch" } })
```

Let me know if the above works for you that would confirm my assumption regarding the already fixed bug and I'll merge the branch even though it's WIP the code is settled, only `OPTIONS.md` is not yet complete.

**Comment by towry** [comment]
Yes, it seems random.

https://github.com/ibhagwan/fzf-lua/assets/8279858/fc4da003-d7f0-4517-a004-cecbd9d39711

**Comment by ibhagwan** [comment]
> Yes, it seems random.

This is a bug with the `:FzfLua` command parser (which I already fixed in the `cmp_src` branch), the lua variant of the command will work:
```lua
lua require("fzf-lua").files({ hls = { normal="IncSearch", border="IncSearch" } })
```

**Comment by towry** [comment]
The cmp_src doesn't work with my config, strange, must be some plugin affected.

**Comment by ibhagwan** [comment]
> The cmp_src doesn't solve the highlight issue with my config, strange, must be some plugin affected.

Does the lua command I posted also fail randomly? If so that might be the case.

If only the `:FzfLua ...` command variant fails randomly that would be a bug in fzf-lua.

**Comment by towry** [comment]
The lua command doesn't work, no random.

**Comment by ibhagwan** [comment]
> The lua command doesn't work, if using my config, no random. I will try to narrow down specific config that cause this.

Alright, let me know what you find, I will merge `cmp_src` soon so we can have that to test as well.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/eed06a7a9a28aeb47659b609999813d1bedc1a00

@towry, `cmp_src` was merged so the `:FzfLua ...` variant shouldn't be bugged anymore when specifying more than one "dotted" option (e.g. `hls.normal`).

**Comment by towry** [comment]
It is https://github.com/tknightz/telescope-termfinder.nvim

after i commented out `require('telescope').load_extension('termfinder')`, fzf-lua highlights works ok.

**Comment by ibhagwan** [comment]
> after i commented out require('telescope').load_extension('termfinder'), fzf-lua highlights works ok.

Very interesting, keep me posted if you find out why this plugin conflicts with fzf-lua highlights.

**Comment by towry** [comment]
@ibhagwan actually, fzf-lua conflicted with toggleterm.terminal module.

If id run `:lua require('toggleterm.terminal')` (or open ToggleTerm), this issue will happen.

**Comment by towry** [comment]
The cause is toggleterm's shade_filetypes https://github.com/akinsho/toggleterm.nvim?tab=readme-ov-file#set-terminal-shading

If i remove this option, no issue.

**Comment by ibhagwan** [comment]
In my config I have `shade_terminals = true` but my  `shade_filetypes` is empty and don’t have this issue.

Fzf-lua’s filetype is set to `fzf` and you’re effectively telling toggleterm to take over the highlight and modify its shade, I’m not sure what toggleterm does to modify the shade but perhaps it fails to restore the FloatBorder hlgroup when it does that?

**Comment by towry** [comment]
My initial shade_filetypes is `{ 'none' }`, it will cause toggleterm to override the terminal highlights.

Every time fzf is started, toggleterm will change the highlights:

<img width="443" alt="截屏2024-04-30 22 05 02" src="https://github.com/ibhagwan/fzf-lua/assets/8279858/a33b6f41-ae99-4e18-b140-e0c8fd72012f">

**Comment by ibhagwan** [comment]
> Every time fzf is started, toggleterm will change the highlights:

I know, I also use but with  the `shade_termianls` option.
