### ISSUE TITLE
Bug: Duplicate tag `fzf-lua-opts-commands` in `doc/fzf-lua-opts.txt`

### ISSUE THREAD

**Issue by dpetka2001** [ibhagwan/fzf-lua#1165]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux Mint 21.3

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.0-dev-3045+gefaf37a2b

### Fzf version (`fzf --version`)

0.50.0 (f97d275)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--layout=reverse --bind='ctrl-r:reload(rg --hidden --files)' --header='Press CTRL-R to reload ' --border -m --bind 'ctrl-v:execute(nvim {+})','ctrl-d:reload(find . -type d)'

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

When updating with `lazy.nvim` the docs fail to build due to duplicate tag `fzf-lua-opts-commands` in `doc/fzf-lua-opts.txt`. Some other name needed for the second tag in https://github.com/ibhagwan/fzf-lua/blob/da3e7e1fc07286d3534185cc80438e2a2f82bfcc/doc/fzf-lua-opts.txt#L1217

**Comment by mohamad-supangat** [comment]
same here after upgrade to the lathes version

**Comment by ibhagwan** [comment]
Sorry about that everyone, it was late night and I rushed to to merge a feature branch due to it containing a fix for another issue ( #1161).

https://github.com/ibhagwan/fzf-lua/commit/4694946a77cec2d8e27c95f587de058a2a0ea311 should fix it.

**Comment by ibhagwan** [comment]
Appeently a few more tags caused duplicates as `grep_cword` and `grep_cWORD` generate the same tag, just verified docs are now working post https://github.com/ibhagwan/fzf-lua/commit/a4bce02bf854e043da77a18f5cdf74543c7115ec.
