### ISSUE TITLE
Bug: lsp_code_actions throws error

### ISSUE THREAD

**Issue by Perry3D** [ibhagwan/fzf-lua#1172]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Windows 10

### Shell

cmd

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.48.1 (d579e33)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({ 'borderless_full' })
})
```

### Describe the bug / steps to reproduce

When executing `:FzfLua lsp_code_action` i get sometimes the following error message:
```
Error executing vim.schedule lua callback: ...m-data/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:257: 'replacement string' item contains newlines
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	...m-data/lazy/fzf-lua/lua/fzf-lua/previewer/codeaction.lua:257: in function 'populate_preview_buf'
	...nvim-data/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:263: in function 'populate_preview_buf'
	...nvim-data/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:280: in function 'fn'
	vim/_editor.lua:477: in function 'cb'
	vim/_editor.lua:263: in function <vim/_editor.lua:262>
```

For me it is reproducible with a cpp file and clangd as lsp server. For example with the following code action: 
```
1. Member reference type 'std::string *' (aka 'basic_string<char, char_traits<char>, allocator<char>> *') is a pointer; did you mean to use '->'? (fix available) (clang) [typecheck_member_reference_suggestion] [typecheck_member_reference_suggestion]
```
in line 6 (`hello.empty()`) of the following example cpp:
```cpp
#include <string>

int main(int argc, char *argv[])
{
  std::string* hello = new std::string("world");
  hello.empty()

  return 0;
}

```

I pulled the latest version of fzf-lua (cb208cd24bacac5893249ea3a8624d705d2135f9) and clangd is also the latest version (18.1.3).

**Comment by ibhagwan** [comment]
Just tested the same code on Linux, works fine, I’m assuming this is a Windows specific bug, perhaps clang adds `\r`’s on windows that create this bug
![IMG_2078](https://github.com/ibhagwan/fzf-lua/assets/59988195/613b6be1-361b-41b5-b658-edd4cdc26422)

I’ll test this tomorrow on my Windows VPS, hopefully this reproduces or we’ll test some tentative fixes on the lines.

In the meantime can you test `:FzfLua lsp_code_actions previewer=codeaction_native` and let me know if that works for you?

**Comment by Perry3D** [comment]
`:FzfLua lsp_code_actions previewer=codeaction_native` works fine.

**Comment by ibhagwan** [comment]
@Perry3D, should work post https://github.com/ibhagwan/fzf-lua/commit/bec242dfa7fce45335d39e8a092f284572ca6bbf.

**Comment by Perry3D** [comment]
I can confirm your fix.

Thank you very much for the fast response 👍

**Comment by ibhagwan** [comment]
Ty for the update @Perry3D!
