### ISSUE TITLE
Feature: Files and recent files in the same picker (like smar-open extension for telescope)

### ISSUE THREAD

**Issue by hadyelzayady** [ibhagwan/fzf-lua#1174]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

in files picker, show recent files as default and when all files in the project are searchable too, just like smart-open neovim plugin that uses telescope 
https://github.com/danielfalk/smart-open.nvim

**Comment by ibhagwan** [comment]
Hi @hadyelzayady,

Due to perf reasons this isn't something I plan on doing/maintining, there a rew discussions/issues regarding picker-combining which you can get a lead on if you wish to do this yourself, for exmaple #1140.

**Comment by ibhagwan** [comment]
I looked at https://github.com/danielfalk/smart-open.nvim, this is an endless rabbithole, there are so many variables and so many personal preferences determining which files should be at the top and potentially so many improvements that are workflow dependent, definitely not something I plan on getting myself into :-)

IMHO, you're better off opening a feature request in `smar-open.nvim` to add support fzf-lua as backend, [the API](https://github.com/ibhagwan/fzf-lua/wiki/Advanced) is super simple and there are quite a few plugins that support fzf-lua as backend (neoclip, dressing, octo to name a few), that way you can enjoy the inevitable improvements that would come from smart-open.
