### ISSUE TITLE
Bug: showing preview laggs behind when searching through the result

### ISSUE THREAD

**Issue by idelice** [ibhagwan/fzf-lua#1177]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

mac 14.3

### Shell

zsh

### Neovim version (`nvim --version`)

0.9

### Fzf version (`fzf --version`)

0.44.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

When searching files, live-grep, live-grep-native, live-grep-glob, and returning a list of 50+ files (the amount really doesn't matter tbh), and i go up/down through the list, the preview is not immediately updated.

An example would be holding down arrow down/up button going through the list, it only updates when i stop pressing the buttons.

**Comment by ibhagwan** [comment]
> An example would be holding down arrow down/up button going through the list, it only updates when i stop pressing the buttons.

There is a denounce mechanism in place by design, IMHO it doesn’t make any sense to load the previewer while scrolling.

If you want to disable the denounce, use `winopts.preview.delay`, you can test how that feels with:
```lua
:FzfLua files winopts.preview.delay=0  
```

If you want that permanently use `setup’.
