### ISSUE TITLE
"'fzf_opts' are automatically shellescaped" warning when using preview_action_cmd

### ISSUE THREAD

**Issue by homerours** [ibhagwan/fzf-lua#1183]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

0.9.5

### Fzf version (`fzf --version`)

0.42.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Describe the bug / steps to reproduce

Hello,

I am having an issue when running:
```
:lua require('fzf-lua').fzf_exec('ls -1U', { preview = require('fzf-lua').shell.preview_action_cmd(function(items) return "echo test" end)})  
```
Fzf-lua outputs first a warning
```
[Fzf-lua] `fzf_opts` are automatically shellescaped. Please remove surrounding quotes from --preview='VIMRUNTIME='\''/usr/local/Cellar/neovim/0.9.5/share/nvim/runtime'\'' '\''/usr/
local/Cellar/neovim/0.9.5/bin/nvim'\'' -n --headless --clean --cmd '\''lua loadfile([[/var/folders/p5/d2vwwq012jl87z7_zypnlz240000gn/T/fzf-lua.tmp/nvim/site/pack/vendor/start/fzf-l
ua/lua/fzf-lua/shell_helper.lua]])().rpc_nvim_exec_lua({fzf_lua_server=[[/var/folders/p5/d2vwwq012jl87z7_zypnlz240000gn/T/nvim.leo/cseuA0/fzf-lua.1715155540.3055.1]], fnc_id=5 })'\
'' -- {+}'
```
and then the correct picker/previewer appears after pressing enter.
Is there a way to get rid of this ? Thank you.
For context, I am trying to make a simple "directory previewer", running 'ls -1UpC' on the selected folder. I have been using so far `opts.preview = 'ls -1UpC {}', however, when the selected entry is e.g. `~/`, the preview command does not perform the tilde expansion. I am therefore trying to feed `preview_action_cmd` with
```lua
local function ls_previewer(items)
     return "ls -1UpC " .. vim.fs.normalize(items[1])
end
```
but I am getting the warning described above. Is there a better way (e.g. a builtin directory previewer or something to deal better with this tilde issue) of achieving this ? Many thanks !

**Comment by ibhagwan** [comment]
I should probably allow to set `preview` directly as a function and make the switch to a shell preview action in the code myself, users don’t need to worry about internals to this extent.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a8e1659edcec45ab41c64940d1efe06335e95faf

@homerours, after the latest commit you need not worry yourself about the internals.

If  set a function for preview the returned string will be displayed in the preview, for example:
```lua
:= require("fzf-lua").fzf_exec("ls",{preview=function(s) return "s[1]: "..s[1] end})
```

For more involved setup you can send a preview spec as a table with `fn` set to the callback (replicating the above example):
```lua
:= require("fzf-lua").fzf_exec("ls",{preview={fn=function(s) return "s[1]: "..s[1] end}})
```
Using a shell command for preview (which is what you're after) use `type="cmd"` as part of the spec:
```lua
:= require("fzf-lua").fzf_exec("ls",{preview={type="cmd",fn=function(s) return "echo s[1]: "..s[1] end}})
```

You can also control what gets sent to the function using fzf's FIELD INDEX EXPRESSIONS, by default `{}` (cursor line item) is sent, in the example below we display the prompt text in the preview:
```lua
:= require("fzf-lua").fzf_exec("ls",{preview={field_index="{q}",fn=function(s) return "q: "..s[1] end}})
```
Another exmaple sending all selected items (with `--multi` using `tab`) to the preview:
```lua
:= require("fzf-lua").fzf_exec("ls",{preview={field_index="{+}",fn=function(s) return table.concat(s,"\n") end}})
```

**Comment by ibhagwan** [comment]
The wiki was updated to reflect the latest changes
https://github.com/ibhagwan/fzf-lua/wiki/Advanced#preview-fzf-native

Ty @homerours for triggering this useful change :-)

**Comment by homerours** [comment]
Awesome, thank you so much @ibhagwan ! That's exactly the API I was looking for :)
