### ISSUE TITLE
Bug: fuzzy search doesn't keep filenames always visible

### ISSUE THREAD

**Issue by cap-mfm** [ibhagwan/fzf-lua#1185]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

0.10

### Fzf version (`fzf --version`)

0.48.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

n.a.

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
//
```

### Describe the bug / steps to reproduce

When searching without fuzzy search, filenames are kept always visible in the results list, while witching to fuzzy search focuses the result on the match highlight, losing sight of the filename for the result. Is it possible to keep the filename always visible even when fuzzy searching?

**Comment by ibhagwan** [comment]
This isn’t a bug, should’ve been opens in discussions.

Fzf the binary doesn’t have any awareness of file names, only the strings passed down to it, when you fuzzy match you’re gonna be shown what is fuzzy matched, using `:FzfLua files formatter=path.filename_only` keeps the filename first and should solve your issue.
