### ISSUE TITLE
Bug: Cannot select results with "FzfLua lsp_finder"

### ISSUE THREAD

**Issue by GerardHH** [ibhagwan/fzf-lua#1191]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.9.5 Release

### Fzf version (`fzf --version`)

0.49.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--height 90% --layout=reverse --border --cycle

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
-- Used by lazy.nvim
return {
	"ibhagwan/fzf-lua",
	version = "*",
	dependencies = {
		"nvim-tree/nvim-web-devicons",
	},
	lazy = true,
	event = "LspAttach",
	keys = {
		-- FZF
		{ "<leader>fB", "<CMD>FzfLua builtin<CR>", desc = "FZF builtin commands" },
		{ "<leader>fC", "<CMD>FzfLua commands<CR>", desc = "FZF plugin/user commands" },
		{ "<leader>fH", "<CMD>FzfLua command_history<CR>", desc = "FZF command history" },
		{ "<leader>fR", "<CMD>FzfLua registers<CR>", desc = "FZF registers" },
		{ "<leader>fS", "<CMD>FzfLua spell_suggest<CR>", desc = "FZF spelling suggestion" },
		{ "<leader>fb", "<CMD>FzfLua buffers<CR>", desc = "FZF buffers" },
		{ "<leader>fc", "<CMD>FzfLua grep_cword<CR>", desc = "FZF current word" },
		{ "<leader>ff", "<CMD>FzfLua files<CR>", desc = "FZF find files" },
		{ "<leader>fh", "<CMD>FzfLua search_history<CR>", desc = "FZF search history" },
		{ "<leader>fj", "<CMD>FzfLua jumps<CR>", desc = "FZF jumplist" },
		{ "<leader>fk", "<CMD>FzfLua keymaps<CR>", desc = "FZF keymaps" },
		{ "<leader>fo", "<CMD>FzfLua oldfiles<CR>", desc = "FZF oldfiles" },
		{ "<leader>fr", "<CMD>FzfLua resume<CR>", desc = "FZF resume" },
		{ "<leader>fs", "<CMD>FzfLua live_grep<CR>", desc = "FZF string" },
		{ "<leader>ft", "<CMD>FzfLua help_tags<CR>", desc = "FZF help tags" },
		-- LSP
		{ "<leader>lD", "<CMD>FzfLua lsp_workspace_diagnostics<CR>", desc = "LSP workspace diagnostics (fzf)" },
		{ "<leader>lS", "<CMD>FzfLua lsp_document_symbols<CR>", desc = "LSP document symbols (fzf)" },
		{ "<leader>la", "<CMD>FzfLua lsp_code_actions<CR>", desc = "LSP code action (fzf)" },
		{ "<leader>ld", "<CMD>FzfLua lsp_document_diagnostics<CR>", desc = "LSP document diagnostics (fzf)" },
		{ "<leader>lf", "<CMD>FzfLua lsp_finder<CR>", desc = "LSP find all locations (fzf)" },
		{ "<leader>lr", "<CMD>FzfLua lsp_references<CR>", desc = "LSP references (fzf)" },
	},
	opts = {
		"telescope",
		winopts = {
			fullscreen = true,
			preview = {
				layout = "vertical",
				vertical = "up:70%",
			},
		},
	},
	config = function(pkg, opts)
		require(pkg.name).setup(opts)
		vim.cmd("FzfLua register_ui_select")
	end,
}
```

### Describe the bug / steps to reproduce

Hello!

I've noticed that when I try `FzfLua lsp_finder` on a function, the keybindings that allow a user to select results do not work. For instance `alt+a` (select all results) or what I originally wanted `ctrl+q` (select all and push to quickfix list) doesn't push antything to the quickfix list.

The small test code that I used to test this was (clangd is used as the LS):
```cpp
struct S {
  int get() const;
};

int S::get() const { return 42; }

int main() {
  S s;
  return s.get();
}
```
The following "modes" don't allow selection:
1. lsp_finder.
2. lsp_..._symbols (non of the variants)
3. lsp_code_actions (though this one makes sense that it doesn't).

Other "modes" do work.

I think this is not correct, otherwise I could use some assistence in pushing results of `FzfLua lsp_finder` to the quickfix list.

**Comment by ibhagwan** [comment]
Are you using the latest commit? Symbols was fixed in #1184 and `lsp_finder` does allow selection:
![IMG_2098](https://github.com/ibhagwan/fzf-lua/assets/59988195/06be6126-04d0-4198-9ad2-c2eb5a3e3cd5)

Though I’m unsure where you’d be inheriting `--no-multi` can you try the below and let me know which works and which doesn’t:
```vim
:FzfLua lsp_finder fzf_opts.--multi=true
:FzfLua lsp_finder fzf_opts.--no-multi=false
:FzfLua lsp_finder fzf_opts.--multi=true fzf_opts.--no-multi=false
```

**Comment by ibhagwan** [comment]
@GerardHH, https://github.com/ibhagwan/fzf-lua/commit/eb51d83c4099f8a372332350395bda270832cfea should fix your issue.

**Comment by GerardHH** [comment]
@ibhagwan You seem to be right, when I try your first and third suggestion it works.

Supprisingly the `no-multi=false` did not though.

In anycase, the issue is on my side. Thank you :)

**Comment by ibhagwan** [comment]
> Supprisingly the no-multi=false did not though.
> In anycase, the issue is on my side. Thank you :)

That’s because the issue **is not on your side**, `--multi=true` was missing from LSP which is now fixed in https://github.com/ibhagwan/fzf-lua/commit/eb51d83c4099f8a372332350395bda270832cfea.

**Comment by GerardHH** [comment]
Just for completeness sake, the "lsp_finder" and "lsp…symbols" work on my side as well, without the fzf argument override "--multi=true".

Thank you for your quick response.

**Comment by ibhagwan** [comment]
Ty for the confirmation @GerardHH
