### ISSUE TITLE
Feature: Provide a File Navigator like nvim-telescope/telescope-file-browser.nvim

### ISSUE THREAD

**Issue by carlesba** [ibhagwan/fzf-lua#1192]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I'm missing something like nvim-telescope/telescope-file-browser.nvim for fzf-lua.

This extension allows you to see current directory within telescope panels and navigate up/down the tree. You can even create/delete/rename files/directories.

It's very versatile as you can quickly filter in the list and apply the action you need. 

Currently, FzfLua doesn't show directories. I couldn't find a way to navigate either, so I guess it should be provided by the plugin itself.

Extra:

Telescope allows Normal/Insert Modes in the prompt. This is very helpful as allows the user to customize actions in normal mode. This particular extension (nvim-telescope/telescope-file-browser.nvim) makes it very easy with Normal mode: C will crate, Y will duplicate, D will delete files, etc.

Something like this would make FzfLua easier to use.

**Comment by ibhagwan** [comment]
I consider this out of scope, there are so many alternatives and personal preferences for this type of functionality I do not wish to maintain, if you really want you can make it yourself, there are a few examples out in the wild recreating this using the API (not that hard), for example:
https://github.com/michel-garcia/fzf-lua-file-browser.nvim

**Comment by ibhagwan** [comment]
> thanks for the suggestion! didn't know about it

There are a few others hiding inside issues, some include code, if you need help with your generated code post it here and I’ll help you refine it.
