### ISSUE TITLE
Feature: Option to hide "<ctrl-g> to Disable .gitignore" and other hints

### ISSUE THREAD

**Issue by LonelyMusicDisc** [ibhagwan/fzf-lua#1195]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Add an option to hide hints like "<ctrl-g> to Disable .gitignore" for those who want a leaner picker, and for those who know those commands by heart.

**Comment by ibhagwan** [comment]
This has been asked for many times and already exists (both will hide the header, search the issues to learn more):
```lua
:FzfLua files no_header_i=true
:FzfLua files header=false
```

**Comment by LonelyMusicDisc** [comment]
Not sure how I missed that, thanks!
