### ISSUE TITLE
Bug: Global previewer = false doesn't work

### ISSUE THREAD

**Issue by amesaine** [ibhagwan/fzf-lua#1197]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Debian 12

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.38.0 (debian)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
previewer = false
})
```

### Describe the bug / steps to reproduce

When set globally, previewer isn't disabled for any of the fzf-lua commands.

When set locally, the previewer is disabled properly. 

```
local fzf = require "fzf-lua"
vim.keymap.set("n", "w", function()
    fzf.files({
        previewer = false
    })
end
```

What im trying to do here is make previewer disabled by default and explicitly enable it when setting keymaps.

**Comment by amesaine** [comment]
I tried this which works for my use case.

```
winopts = {
    preview = { hidden = "hidden" }
}
```

**Comment by amesaine** [comment]
Nevermind, I missed the fact that these must be placed inside a defaults table.

```
require("fzf-lua").setup({ defaults = { file_icons = false } })
```

It'd be good to
- make this the first code snippet in https://github.com/ibhagwan/fzf-lua/blob/main/OPTIONS.md#general-usage.
- Include this in https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#default-options

**Comment by ibhagwan** [comment]
> Include this in https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#default-options


https://github.com/ibhagwan/fzf-lua/blob/e412b1b0db62ccfccee41d994da87923eb2d8abd/README.md?plain=1#L796-L801
