### ISSUE TITLE
Bug: attempt to call field 'tbl_contains'

### ISSUE THREAD

**Issue by qbnil** [ibhagwan/fzf-lua#1199]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Windows

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v.0.9.5

### Fzf version (`fzf --version`)

0.46.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

-

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
This happens when i perform a regular file search, i recently moved to lazy.nvim, could it be an issue? All the errors seem to be going from /previewers/builtin.lua. The error gets thrown during the time i type in the letters.
```

### Describe the bug / steps to reproduce

with lazy as your pm, start searching for the files using this keymap config:
 vim.keymap.set({ "n" }, "<leader>;", function()
    require("fzf-lua").files({
        cmd = "fd --type f --hidden --follow --exclude '.git' --exclude '.local' --exclude '.cache' --exclude '.android' --exclude 'undodir' --exclude '.npm' --exclude '.mozilla' --exclude '.codeium' --exclude 'systemd' --exclude 'libreoffice' --exclude 'xournalpp' --exclude '.gnupg' --exclude 'gtk-2.0' --exclude 'gtk-3.0' --exclude 'mps-youtube' --exclude 'skypeforlinux' --exclude 'spotify' --exclude 'go' --exclude '.pki' --exclude 'mps' --exclude 'youtube-viewer' --exclude 'dconf' --exclude 'tpm' --exclude '.Xauthority' --exclude '.cargo' --exclude '.rustup' --exclude 'venv' --exclude 'functions' --exclude 'vscode-php-debug' --exclude 'node_modules' --exclude '.symfony5'",
        winopts = { preview = { hidden = "nohidden" } },
        fzf_opts = {['--color'] =  'gutter:-1'},
    })
end, { silent = true, desc = "Fuzzy search files" })

**Comment by qbnil** [comment]
Alr, apperantly i had to clear everthing up in my ~/.local/share/nvim/site

**Comment by ibhagwan** [comment]
> Alr, apparently i had to clear everthing up in my ~/.local/share/nvim/site

Possible update issue on your package manager side as I just ran a few updates to adjust for the neovim 0.10/0.11 nightly.
