### ISSUE TITLE
file_tabedit not working

### ISSUE THREAD

**Issue by euglevi** [ibhagwan/fzf-lua#12]
The action corresponding to file_tabedit does not work for me. I tried to change the key associated to the action but still no luck. It is to note that the same action for buffers works fine.

I am wondering if this as something to do with the vim command:

```
M.file_tabedit = function(selected)
  local vimcmd = "tanbew"
  M.vimcmd_file(vimcmd, selected)
end
```

When I change it into `tabe` things seem to be working again.

**Comment by ibhagwan** [comment]
Fixed, there was a typo, `tanbew` instead of `tabnew` :-)

**Comment by euglevi** [comment]
A not obvious one, I would say :) I was really left wondering what `tanbew` was! 

Then, as far as I understand from the Nvim documentation `tabe` and `tabnew` are the same command.

Thank you very much! And very good work on the plugin!
