### ISSUE TITLE
Bug: No module utils on LSP

### ISSUE THREAD

**Issue by GregBowyer** [ibhagwan/fzf-lua#1200]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.45.0 (0.45.0)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--no-sort --bind 'f1:execute(less -f {}),f2:execute-silent(vim {})+abort,ctrl-y:execute-silent(echo {} | xc lip)+abort' --multi --color dark --cycle

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
-- with lazy
    {
        "ibhagwan/fzf-lua",
        lazy = false,
        dependencies = { "nvim-tree/nvim-web-devicons" },
        opts = {{"fzf-vim", "fzf-native", "telescope"}},
        keys = {
            { "<C-n>", "<cmd>FzfLua lsp_document_symbols<CR>", desc="Browse document symbols" },
            { "<C-N>", "<cmd>FzfLua lsp_workspace_symbols<CR>", desc="Browse workspace symbols" },
            { "<C-T>", "<cmd>FzfLua files<CR>", desc="Fuzzy find file" },
        },
    },
```

### Describe the bug / steps to reproduce

I seem to get this

```
:FzfLua lsp_code_actions
Error executing Lua callback: ...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:20: module 'utils
' not found:
        no field package.preload['utils']
cache_loader: module utils not found
cache_loader_lib: module utils not found
        no file '/nix/store/0qf88pz9y8dbbcxv0063qrrimsaphymj-luajit-2.1.1693350652-env/share/lua/5.1/utils.
lua'
        no file '/nix/store/0qf88pz9y8dbbcxv0063qrrimsaphymj-luajit-2.1.1693350652-env/share/lua/5.1/utils/
init.lua'
        no file '/nix/store/0qf88pz9y8dbbcxv0063qrrimsaphymj-luajit-2.1.1693350652-env/lib/lua/5.1/utils.so
'
stack traceback:
        [C]: in function 'require'
        ...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:20: in function 'check_capabilities'
        ...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:924: in function <...al/share/nvim/lazy
/fzf-lua/lua/fzf-lua/providers/lsp.lua:918>
        .../greg/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/cmd.lua:33: in function 'run_command'
        ...e/greg/.local/share/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:12: in function <...e/greg/.local/share
/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:11>
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/53698d7ff093592228d14a509933ce403b3b8f9f

@GregBowyer, whoops, ty for the report!

**Comment by GregBowyer** [comment]
Np I was quick on the draw updating
