### ISSUE TITLE
Bug: can not jump to location when nvim is open as manpager

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#1204]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0-dev-9e2f378

### Fzf version (`fzf --version`)

0.51.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--ansi --border --bind page-up:preview-up,page-down:preview-down,?:toggle-preview

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
local fzf_history_dir = vim.env.HOME .. '/.local/share/nvim/fzf-history'
if vim.fn.isdirectory(fzf_history_dir) == 0 then
  vim.fn.system { 'mkdir', '-p', fzf_history_dir, }
end

local fzf_lua = require 'fzf-lua'

local sel_to_qf = function(selected, opts)
  local qf_list = {}
  for i = 1, #selected do
    local file = fzf_lua.path.entry_to_file(selected[i], opts)
    local text = selected[i]:match ':%d+:%d?%d?%d?%d?:?(.*)$'
    table.insert(qf_list, {
      filename = file.bufname or file.path,
      lnum = file.line,
      col = file.col,
      text = text,
    })
  end
  vim.fn.setqflist(qf_list)
  vim.cmd 'FzfLua quickfix'
end

local function file_edit_or_qf(selected, opts)
  if #selected > 1 then
    return sel_to_qf(selected, opts)
  else
    fzf_lua.actions.file_edit(selected, opts)
  end
end

fzf_lua.setup {
  keymap = {
    builtin = {
      ['<F1>'] = 'toggle-help',
      ['<F2>'] = 'toggle-fullscreen',
      ['<F3>'] = 'toggle-preview',
      ['<PageDown>'] = 'preview-page-down',
      ['<PageUp>'] = 'preview-page-up',
      ['<Home>'] = 'preview-page-reset',
    },
    fzf = {
      ['tab'] = 'toggle',
      ['ctrl-a'] = 'toggle-all',
      ['ctrl-f'] = 'half-page-down',
      ['ctrl-b'] = 'half-page-up',
    },
  },
  fzf_opts = {
    ['--layout'] = 'default',
    ['--history'] = fzf_history_dir .. '/fzf-lua',
    ['--history-size'] = '10000',
  },
  actions = {
    files = {
      ['enter']  = file_edit_or_qf,
      ['ctrl-s'] = fzf_lua.actions.file_vsplit,
    },
  },
  files = {
    git_icons = false,
  },
  grep = {
    git_icons = false,
    file_icons = false,
    color_icons = false,
  },
}
```

### Describe the bug / steps to reproduce

When running nvim as man pager:

```sh
export MANPAGER='nvim +Man!'
```

Then we can not jump to locations with FzfLua.

```sh
aws configure set help
```

```nvim
:FzfLua loclist
```

<img width="1961" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/22189661/d2601ab8-a346-460e-b26b-6c4e566d8e05">

**Comment by sandangel** [comment]
It works with `gO` (ge-oh)

**Comment by ibhagwan** [comment]
@sandangel with https://github.com/ibhagwan/fzf-lua/commit/8c15b6672462ccc07f19ce2339af020f8076edb9 should work as expected.
