### ISSUE TITLE
Feature: nvim-dap process id picker

### ISSUE THREAD

**Issue by JosefLitos** [ibhagwan/fzf-lua#1206]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Default `require'dap.utils'.pick_process` is basically unusable. In [here](https://youtu.be/Ul_WPhS2bis?feature=shared&t=873) I've some nice picker (probably telescope) for this function. Since there are already a few dap pickers, I though if there could be another one added.

**Comment by ibhagwan** [comment]
Hi @JosefLitos, I agree this is something that’s needed, in fact I have created one for myself in my own config:
https://github.com/ibhagwan/nvim-lua/blob/68d04e8ecdb03ef9f4bd23c0fb30d204a2fa4bf2/lua/utils.lua#L473-L504

That said I do not wish to maintain a generic one for fzf-lua, process pickers is an endless robot hole with filters  (name, user, root, children, etc) and endless formatting preferences (just look at `ps`), on top of that it would have to account for cross platform and Windows.

**Comment by JosefLitos** [comment]
I will look into it, thank you.
