### ISSUE TITLE
Bug: libuv error on man_pages search

### ISSUE THREAD

**Issue by qbnil** [ibhagwan/fzf-lua#1208]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Windows

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.46.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

-

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
vim.keymap.set(
      "n",
      "<leader>fm",
      "<cmd>lua require'fzf-lua'.man_pages({fzf_opts = {['--color'] =  'gutter:-1'}})<cr>"
)
```

### Describe the bug / steps to reproduce

This happens on first neovim enter, i start to search for man docs and i get this error on windows: Error executing vim.schedule lua callback: ...chi/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/libuv.lua:651: attempt to index local s ('a nil value'). The wierd thing is that it only happens on windows, which is not reproducable on linux, If i ignore the issue and start to search the docs i get these errors in the preview window: man: can't chmod (null): Bad address and also man: can't unlink (null): Bad address. I already have man-db installed and ran sudo mandb to populate everything. I really don't know what's causing this behaviour

**Comment by ibhagwan** [comment]
> The wierd thing is that it only happens on windows, which is not reproducable on linux

Man pages is not supported on Windows and shouldn't even open, do you mean WSL on windows?

**Comment by ibhagwan** [comment]
> This happens on first neovim enter, i start to search for man docs

Can you post a screenshot of the line where the manpage fails, for example:
```
aa-enabled(1)      test whether AppArmor is enabled
```

Also, can you test whether this happens when running without preview?
```lua
:FzfLua manpages previewer=false
```

**Comment by qbnil** [comment]
> > The wierd thing is that it only happens on windows, which is not reproducable on linux
> 
> Man pages is not supported on Windows and shouldn't even open, do you mean WSL on windows?

yes

**Comment by qbnil** [comment]
> > This happens on first neovim enter, i start to search for man docs
> 
> Can you post a screenshot of the line where the manpage fails, for example:
> 
> ```
> aa-enabled(1)      test whether AppArmor is enabled
> ```
> 
> Also, can you test whether this happens when running without preview?
> 
> ```lua
> :FzfLua manpages previewer=false
> ```

when i disable the previewer, everything starts to work except the error on top which says: man: can't set the locale, but i reconfigured my locale-gen so i'll check what's up after the reboot

**Comment by qbnil** [comment]
The previewer not working is still a puzzle tho

**Comment by qbnil** [comment]
![Снимок экрана 2024-05-20 162327](https://github.com/ibhagwan/fzf-lua/assets/130576530/c5ea536c-2178-4f80-b6f0-8f46700eaf97)

**Comment by ibhagwan** [comment]
This is still a bug that needs to be resolved, the screenshot tells us why the bug happens, the first line of output isn’t a valid format of a man entry due to this:
```
man: can’t set the locale; make sure…
```

I’ll add a safety check for this type of output.

**Comment by ibhagwan** [comment]
@qbnil, should work with preview with https://github.com/ibhagwan/fzf-lua/commit/6573114a289b1b0772dadb71b7cc86686614eb51.

Pressing enter on the first line will raise an exception as this is obviously not a valid man entry, you shuold probably fix that on your WSL install, quick search shows:
https://unix.stackexchange.com/questions/87116/what-do-i-need-to-do-with-man-cant-set-the-locale-make-sure-lc-and-lang

**Comment by qbnil** [comment]
![изображение](https://github.com/ibhagwan/fzf-lua/assets/130576530/8631af0b-9904-4aa3-bee2-f6553abb9032)
pulled the latest commit, still gettting this

**Comment by ibhagwan** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/130576530/332115206-8631af0b-9904-4aa3-bee2-f6553abb9032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTkzNDAsIm5iZiI6MTcxNjIxOTA0MCwicGF0aCI6Ii8xMzA1NzY1MzAvMzMyMTE1MjA2LTg2MzFhZjBiLTk5MDQtNGFhMy1iZWUyLWY2NTUzYWJiOTAzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxNTMwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjZmNzU3ZDA3YmUxMDEwMmU4MjU0Yzk1ZWI3NDU1NDY3NWE0NDliMDJlNDM0YzI3MTUyZjA5N2E5Y2Y0ZGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xLNYCpaOqr_u0fccLLDgE_zU1_WND6Lj6MRJubMFuE0) pulled the latest commit, still gettting this

That’s the output of your man command which has issues not a problem with fzf-lua, run it in the shell and the output will have these errors.

As I wrote above you have issues with man which you need to fix.

**Comment by qbnil** [comment]
![изображение](https://github.com/ibhagwan/fzf-lua/assets/130576530/c2934fc7-8e2c-4f89-bbb5-69d85584fe9b)
![изображение](https://github.com/ibhagwan/fzf-lua/assets/130576530/b5a83032-ab6b-414f-bddd-704bec91e017)
this error shouldn't affect the preview tho or i'm wrong?

**Comment by qbnil** [comment]
i don't get the man: can't chmod/unlink when just using man frome the cmd

**Comment by ibhagwan** [comment]
> i don't get the man: can't chmod/unlink when just using man from the cmd

You’re probably using a pager and it goes to the err stream, trust me the issue is with your setup, nothing I can do about it anymore.

**Comment by qbnil** [comment]
Alr, gotcha np

**Comment by ibhagwan** [comment]
You can use `:FzfLua manpages previewer=man_native` which will be closer to pure shell man but you still have to fix the setup (“can’t set the locale, etc).

**Comment by qbnil** [comment]
![изображение](https://github.com/ibhagwan/fzf-lua/assets/130576530/13920ee2-26cf-4dd2-a989-11c589738534)
It's working, so you thing that all the problems come from the locale thing, even the bad address one?

**Comment by ibhagwan** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/130576530/332119643-13920ee2-26cf-4dd2-a989-11c589738534.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjAyMjIsIm5iZiI6MTcxNjIxOTkyMiwicGF0aCI6Ii8xMzA1NzY1MzAvMzMyMTE5NjQzLTEzOTIwZWUyLTI2Y2YtNGRkMi1hOTg5LTExYzU4OTczODUzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxNTQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjI1Nzc2Mzg1MGEyYjEzOWMxNTljY2I1NzlhNmI0NTEzMjg2YTg4NGZmODBjZDU4NGQ3Nzg5YmMzNWE5ZjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k3NUG3WobpETsfe9x8QvnxW0PIG4UTXdEiHc1oM1frc) It's working with this: :FzfLua manpages previewer=man_native, so you thing that all the problems come from the locale thing, even the bad address one?

Yes, fzf-lua has no awareness of troff, it’s your WSL setup 100%, search for the error messages online 

https://github.com/pimutils/khal/issues/598

**Comment by qbnil** [comment]
alr, you right on this one for sure, gotta fix it myself, you can close the issue then completely
