### ISSUE TITLE
Feature: regexp filter for lsp_references

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1209]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Hello my dear friend:)
I see that lsp workspace symbols method has this feuture.
I would like to filter `lsp_references`from `import.*from.*`. I know that i can use:

```ts
require('fzf-lua').lsp_references {
	fzf_opts = { ['--query'] = '!import' },
}
``` 
But i don't want to see filter in prompt.
Thank you!

**Comment by ibhagwan** [comment]
Added the same `regex_filter` that exists in symbols to locations, that means refs, defs and even finder, for example:
```lua
:FzfLua lsp_finder regex_filter=func
```
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/c818e547-4596-4943-bc16-29c6cf39753e)


For exclusions (as you're after) look into lua string patterns but I'm not really sure if you can get `!import` without more changes in the code.

**Comment by ibhagwan** [comment]
@kaiphat, post https://github.com/ibhagwan/fzf-lua/commit/a9e5755721c0f24cd1635ea4ff181df5b1bd5dd4 it is now possible to use an exclude pattern:
```lua
:FzfLua lsp_references regex_filter={"import.*from.*",exclude=true}
-- equal to:
:lua require("fzf-lua").lsp_finder({ regex_filter = {"import.*from.*",exclude=true} })
```
