### ISSUE TITLE
Marks fzf preview does not navigate to line on <CR>

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#121]
Been playing with the "marks" fzf preview. When navigating to the mark in the fzf preview and then press "enter" nvim does not navigate to the line number where the mark is placed.

**Comment by ibhagwan** [comment]
> Been playing with the "marks" fzf preview. When navigating to the mark in the fzf preview and then press "enter" nvim does not navigate to the line number where the mark is placed.

Do you mean column? I now see I used `'` (first non blank character on mark line) to navigate to mark instead of “`”  (exact mark position).

Does this happen with all marks? Can you post a screenshot of the failed mark before pressing enter as there might be an issue with the mark extraction regex.

**Comment by ibhagwan** [comment]
I can't seem to reproduce this, I tried with both low cap marks (same file) and capitalized marks (cross-file), all this does is get the mark and run `'<mark>`, I'm not sure why this fails you, are there specific marks with an issue or all of them?

**Comment by ldelossa** [comment]
@ibhagwan can't seem to reproduce it now either. Strange, I had it occuring on a mark within the same file. 

That being said, looks like color preview for my marks preview window is not working.

**Comment by ibhagwan** [comment]
> @ibhagwan can't seem to reproduce it now either. Strange, I had it occuring on a mark within the same file.
> 
> That being said, looks like color preview for my marks preview window is not working.

That’s because it wasn’t implemented yet, this is still the old poor man’s previewer, I’m actually working on it right now (as well as for man pages and help tags).

**Comment by ldelossa** [comment]
Thanks :) going to close for now until I can reproduce.

**Comment by ibhagwan** [comment]
FYI, marks builtin previewer was implemented.

**Comment by ldelossa** [comment]
Thank you! Just want to say how much im enjoying fzf-lua. If you have a patreon or anything similar ill buy you a ☕ .

**Comment by ibhagwan** [comment]
> Thank you! Just want to say how much im enjoying fzf-lua. If you have a patreon or anything similar ill buy you a ☕ .

Ty for the kind words.
