### ISSUE TITLE
Bug: FzfLua buffers NPE with term buffer

### ISSUE THREAD

**Issue by rx2130** [ibhagwan/fzf-lua#1213]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

v0.10.0

### Fzf version (`fzf --version`)

0.52.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

In macOS VM with mini.sh:
:term
:enew
:FzfLua buffers
Then I would see
<img width="1728" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/54578696/b2f9ae93-4070-471d-bd80-ca5637f3e58c">

I think the problem is https://github.com/ibhagwan/fzf-lua/blob/a9e5755721c0f24cd1635ea4ff181df5b1bd5dd4/lua/fzf-lua/path.lua#L102 where title is using and path is nil for terminal. I tried adding a simple if nil check would solve this.

**Comment by ibhagwan** [comment]
Ty @rx2130! Title shouldn’t have been null, fixed in https://github.com/ibhagwan/fzf-lua/commit/b442569ab827f72e344236c598b02cb9dc754e9f.
