### ISSUE TITLE
Feature: Avoid opening in winfixbuf windows

### ISSUE THREAD

**Issue by sarmong** [ibhagwan/fzf-lua#1214]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

When fzf-lua is opened from a window with `winfixbuf`, a file cannot be edited in that window, so it throws an error.

Possible solution: 
Check if a window that the file is going to be open in has `winfixbuf` then choose another window - previously selected by the user (if possible to determine).

**Comment by ibhagwan** [comment]
Why should we prevent fzf-lua from opening? Not all pickers end up in a file edit action, what if you want to explore the symbols or buffer lines and then go to the selected item within the same buffer? What if you wanted to open help? You get the idea.

I believe the best course of action here is to display a proper warning why the edit failed (similar behavior when trying to switch from an unsaved buffer with `nohide`.

**Comment by sarmong** [comment]
I didn't say `prevent fzf-lua from opening`. I said `Check if a window that the file is going to be open in has winfixbuf then choose another window`.

I am talking about file editing action only. It would be nice improvement if the plugin would automatically choose another window to open file in.

**Comment by ibhagwan** [comment]
> It would be nice improvement if the plugin would automatically choose another window to open file in.

What if there are multiple windows? What if there isn’t one?

There are window selection plugins out there which can easily integrate with fzf-lua as a custom action but this is too nuanced to just code as is and too much work that is out of the scope of this plugin otherwise, therefore I’m going to take the “display a warning” approach.
