### ISSUE TITLE
Plugin commands fail

### ISSUE THREAD

**Issue by diocletiann** [ibhagwan/fzf-lua#1215]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-92+g52389e724

### Fzf version (`fzf --version`)

0.52.1 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
  {
    "ibhagwan/fzf-lua",
    -- optional for icon support
    dependencies = { "nvim-tree/nvim-web-devicons" },
    config = function()
      -- calling `setup` is optional for customization
      require("fzf-lua").setup({})
    end
  },
```

### Describe the bug / steps to reproduce

When I install with lazy (slimmed down LazyVim), this happens on all commands. Using mini.sh works as intended.

```
Error executing Lua callback: ...nvim/lazy/fzf-lua/lua/fzf-lua/providers/colorschemes.lua:83: vim/_editor.lua:0: nvim_exec2(): Vim(autocmd):E216: No such event: <buffer=5> lua require("fzf-
lua").redraw()
stack traceback:
        [C]: in function 'fzf_exec'
        ...nvim/lazy/fzf-lua/lua/fzf-lua/providers/colorschemes.lua:83: in function <...nvim/lazy/fzf-lua/lua/fzf-lua/providers/colorschemes.lua:22>
        ...s/xxx/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/cmd.lua:33: in function 'run_command'
        ...rs/xxx/.local/share/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:12: in function <...rs/xxx/.local/share/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:11>
```

**Comment by ibhagwan** [comment]
> Using mini.sh works as intended.

> nvim_exec2(): Vim(autocmd):E216: No such event: <buffer=5>

This makes me thing this is related to an autocmd you have configured, can you disable your autocmds and see which one causes this issue?

If you link your config I can take a look and see if I can guess where this is potentially coming from?

**Comment by diocletiann** [comment]
> > Using mini.sh works as intended.
> 
> > nvim_exec2(): Vim(autocmd):E216: No such event: <buffer=5>
> 
> This makes me thing this is related to an autocmd you have configured, can you disable your autocmds and see which one causes this issue?
> 
> If you link your config I can take a look and see if I can guess where this is potentially coming from?

Wow thanks for the fast response! This was the culprit:
```
vim.api.nvim_create_augroup("VimResized", { clear = true })
```

**Comment by diocletiann** [comment]
It was meant to disable this: https://github.com/LazyVim/LazyVim/blob/0f6ff53ce336082869314db11e9dfa487cf83292/lua/lazyvim/config/autocmds.lua#L26

**Comment by ibhagwan** [comment]
> `vim.api.nvim_create_augroup("VimResized", { clear = true })`

This just creates the group, is there any autocmd attached to the group, maybe an upstream bug since the group is named at the same name of an existing event?

**Comment by diocletiann** [comment]
> > `vim.api.nvim_create_augroup("VimResized", { clear = true })`
> 
> This just creates the group, is there any autocmd attached to the group, maybe an upstream bug since the group is named at the same name of an existing event?

LazyVim adds this by default (link above):
```lua
-- resize splits if window got resized
vim.api.nvim_create_autocmd({ "VimResized" }, {
  group = augroup("resize_splits"),
  callback = function()
    local current_tab = vim.fn.tabpagenr()
    vim.cmd("tabdo wincmd =")
    vim.cmd("tabnext " .. current_tab)
  end,
})
```
All I did was remove my `clear = true` line and now fzf-lua works.

**Comment by ibhagwan** [comment]
> It was meant to disable this: https://github.com/LazyVim/LazyVim/blob/0f6ff53ce336082869314db11e9dfa487cf83292/lua/lazyvim/config/autocmds.lua#L26

It’s a bit different than what you wrote, I can check later when not AFK why this causes an issue:
```lua
vim.api.nvim_create_autocmd({ "VimResized" }, {
  group = augroup("resize_splits"),
  callback = function()
    local current_tab = vim.fn.tabpagenr()
    vim.cmd("tabdo wincmd =")
    vim.cmd("tabnext " .. current_tab)
  end,
})
```

I’m confused though why this caused an issue for you as this gets called only when neovim window is resized, I’ll explore this later.

**Comment by ibhagwan** [comment]
> All I did was remove my clear = true line and now fzf-lua works.

Ty for this lead.

**Comment by diocletiann** [comment]
Yea just to clarify, LazyVim's autocmd is now active, and fzf-lua works.

**Comment by ibhagwan** [comment]
@diocletiann, while I can't reproduce this issue with `{ clear = true }` I have some suspecion why this may happen, can you try with the latest commit https://github.com/ibhagwan/fzf-lua/commit/96a92ce5aa334225ba2a2d06ee5660ab42c1318b?

**Comment by diocletiann** [comment]
@ibhagwan the latest commit fixed the issue with `{ clear = true }` line uncommented. Thank you, love this plugin!

**Comment by ibhagwan** [comment]
Ty for the update and the kind words @diocletiann ❤️
