### ISSUE TITLE
Document symbol does not go to line if buffer is modified

### ISSUE THREAD

**Issue by Massolari** [ibhagwan/fzf-lua#122]
When I list document's symbols and press Enter to go to a symbol, if the buffer is modified, it doesn't work.

Here is a video showing the bug:

https://user-images.githubusercontent.com/12272702/132588951-ab0657ed-ebb5-45e5-8362-29f7cbed38ab.mov

Additional information: The preview is outdated, but the list shows the correct symbol's line

**Comment by ibhagwan** [comment]
> When I list document's symbols and press Enter to go to a symbol, if the buffer is modified, it doesn't work.

Should work now.

> Additional information: The preview is outdated, but the list shows the correct symbol's line

That's because the previewer reads the file from the disk, I should probably fix that to use existing buffer instead, feel free to open a new issue for that if you want to track it.
