### ISSUE TITLE
Feature: Assign  lua functions to actions

### ISSUE THREAD

**Issue by anderson-silva-concordia** [ibhagwan/fzf-lua#1225]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

What I'm trying to do (I don't know if it is possible) is to open the directory of a file in [oil.nvim](https://github.com/stevearc/oil.nvim). So the code would look to something like this.
```lua
    require("fzf-lua").setup({
      actions = {
        files = {
          ["alt-o"] = function(file)
            require("oil").open(file)
          end
        }
      }
    })
```

**Comment by ibhagwan** [comment]
See https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-acts

**Comment by ibhagwan** [comment]
I’m sorry to close this but you obviously have done even a simple search as requested, there are much more complex examples in both the docs/wiki/README and the issues.
