### ISSUE TITLE
Feature: Can fzf-lua be configured so that pressing ESC sends it to the background instead of closing it? 

### ISSUE THREAD

**Issue by Marskey** [ibhagwan/fzf-lua#1229]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

This way, I can resume my last search status exactly where I left off. The current resume feature only redoes the search with the same query, which causes the previous search state to be lost.

**Comment by ibhagwan** [comment]
ATM, this is not possible, it’s an interesting idea might be worth exploring.

**Comment by abkrm** [comment]
+1 on this feature request. I use this feature a lot and would be nice to have it supported in fzf-lua.

**Comment by konosubakonoakua** [comment]
> ATM, this is not possible, it’s an interesting idea might be worth exploring.

In LazyVim, `<esc><esc>` is mapped to set current window to normal mode, we can copy text freely then. Could we have the same feature in fzf-lua? @ibhagwan :D

**Comment by folke** [comment]
If you're on Neovim >= 0.10, then you can use the keymap below to toggle any floating window.

```lua
local function toggle_floats()
  local floats = {}
  local any_hidden = false
  for _, win in ipairs(vim.api.nvim_list_wins()) do
    local config = vim.api.nvim_win_get_config(win)
    if config.relative ~= "" then
      floats[win] = config
      if config.hide then
        any_hidden = true
      end
    end
  end
  for win, config in pairs(floats) do
    config.hide = not any_hidden
    vim.api.nvim_win_set_config(win, config)
  end
end

vim.keymap.set({ "n", "t" }, "<c-;>", toggle_floats)
```

**Comment by lttb** [comment]
I've been using a similar to folke's solution with nvim >= 0.10 for some time, and in general it works fine (see the video example) - it switches the focus to the buffer, and restores the cursor position in the next fzf search  

my workflow:
- mapping to start the fzf search - it'll either open the previous search window or start the new one 
- `<enter>` to go to the selected entry - it'll hide the current search float window to resume later

references to the actual config:
- fzf lua
  https://github.com/lttb/nvim/blob/05161ec23444b921c10aad3a5a3a506fcd4fcef6/lua/lttb/plugins/fzf.lua#L46-L92
- toggle_floats
  https://github.com/lttb/nvim/blob/05161ec23444b921c10aad3a5a3a506fcd4fcef6/lua/lttb/dev/toggle_floats.lua

**demo**:

https://github.com/ibhagwan/fzf-lua/assets/11135392/32f974b0-9aac-4744-9824-2fb5c1e84efc


**fzf-lua action example**
```lua
  {
    'ibhagwan/fzf-lua',
    keys = function()
      local fzf = require('fzf-lua')
      local actions = require('fzf-lua.actions')

      return {
        utils.cmd_shift('f', {
          function()
            local tf = require('lttb.dev.toggle_floats')

            if tf.is_hidden('fzf') then
              tf.toggle_floats('fzf')

              return
            end

            fzf.grep_project({
              actions = {
                ['enter'] = {
                  function(selected, opts)
                    tf.toggle_floats('fzf', function()
                      actions.file_edit(selected, opts)
                    end)
                  end,
                  actions.resume,
                },
              },
            })
          end,
          desc = 'fzf: search',
        }),
      }
    end,
  },
```

**toggle_floats.lua** 
```lua
local M = {}

local registry = {}

function M.is_hidden(name)
  local reg = registry[name]
  return reg and #reg.hidden_w > 0
end

function M.toggle_floats(name, callback)
  registry[name] = registry[name] or { hidden_w = {}, last_w = nil }
  local reg = registry[name]

  local wins = vim.api.nvim_list_wins()

  if #reg.hidden_w > 0 then
    for _, w in ipairs(reg.hidden_w) do
      vim.api.nvim_win_set_config(w, { hide = false })
    end

    if reg.last_w then
      vim.api.nvim_set_current_win(reg.last_w)

      vim.schedule(function()
        vim.api.nvim_feedkeys('i', 'n', false)
      end)
    end

    reg.hidden_w = {}
    reg.last_w = nil

    return
  end

  reg.last_w = vim.api.nvim_get_current_win()

  for id, w in ipairs(wins) do
    local win_config = vim.api.nvim_win_get_config(w)

    if
      win_config.relative == 'editor'
      -- ignore mini map (TODO: find a better detection way)
      and win_config.zindex ~= 10
    then
      vim.api.nvim_win_set_config(w, { hide = true })
      table.insert(reg.hidden_w, w)
    end
  end

  vim.opt.eventignore:append('WinLeave')
  vim.opt.eventignore:append('BufLeave')
  vim.api.nvim_set_current_win(1000)

  vim.schedule(function()
    if callback then
      callback()
    end

    vim.opt.eventignore:remove('WinLeave')
    vim.opt.eventignore:remove('BufLeave')
  end)
end

return M
```

**Comment by ibhagwan** [comment]
I also thought about the new float hide in neovim 0.10 but this provides a solution only for users with 0.10 and only using floats, there are also users using splits or fzf-tmux.

In general, I’m not too happy with the current state of the window class code since it had many iterations and is a bit messy, it started by only making a window for fzf with no preview buffer (at first, only native previewers were supported, like fzf.vim), then the “builtin” neovim buffer preview, splits, and fzf-tmux.

I’d hate to continue contributing to this mess without first splitting the window class to a base object and having a class for each `FzfLuaFloat`, `FzfLuaSplit`, etc, each having their own `:hide()` callback (which may or may not be supported, e.g. fzf- tmux), that will also open up the window creation for other frameworks like nui.nvim, etc.

That said, this change is a “luxury” change since everything is pretty much working so I need to get inspired to find the time for this :)

**Comment by ibhagwan** [comment]
- [x] First step of the refactor was the ugly preview layout generation code :-) https://github.com/ibhagwan/fzf-lua/commit/235119b859d1d3dc136a5dbfd24b626b5af72130

**Comment by ibhagwan** [comment]
See #1371 for more info, default bind set to `<A-Esc>`.

**Comment by ibhagwan** [comment]
Forgot to mention how this addresses the issue of replacing the default `<esc>` with hide:
```lua
require("fzf-lua").setup({
  keymap = {
    builtin = {
      true, -- inherit all other default binds
      ["<Esc>"] = "hide",
    }
  }
})
```

Can also be set for an individual bind:
```vim
:FzfLua files keymap.builtin.<esc>=hide
```

Or for a specific picker (or picket "set", e.g. `grep`):
```lua
:lua require("fzf-lua").setup({ files = { keymap = { builtin = { ["<Esc>"] = "hide" } } } })
```

**Comment by Marskey** [comment]
The feature didn't work as I expected. It should be like what @lttb posted: hide the window and then resume, including the cursor position.

**Comment by abkrm** [comment]
@Marskey I haven't tried @lttb's solution, but I tested the latest version of Fzf-Lua and I think it works as expected (by me). Attaching a screen record for how it behaves for me:
![output1](https://github.com/user-attachments/assets/8b7fb538-c405-40c8-916e-bb6e82796bbf)

**Comment by ibhagwan** [comment]
> The feature didn't work as I expected. It should be like what @lttb posted: hide the window and then resume, including the cursor position.

Can you try with the default keybind `alt-escape`?

Perhaps your key mapping isn’t working or mapped to something else, one way to check if your window is actually hidden is to run `:FzfLua unhide`, with “unhide” it won’t fall back to resume, if unhide yields nothing your window wasn’t hidden.

Also can you press `F1` and see if your mapping worked? My `F1` (with the default) below:
![IMG_2372](https://github.com/user-attachments/assets/6f3282ca-f719-46ab-aa5b-e91764206f16)

**Comment by Marskey** [comment]
My bad, my config did not inherit the default keybind

**Comment by ibhagwan** [comment]
Ty @Marskey for the confirmation.

Note that it’s not meant to restore the cursor, the new functionality sends the fzf process to the background  so if you have a long running fd in a large project it you can send it to background and come back to it when the enumeration finishes.

**Comment by Marskey** [comment]
@ibhagwan after I resumed, then I use fzf.buffers will occurd follwing error
```
Error executing vim.schedule lua callback: ...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:313: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [builtin#36]: at 0x010523481c
        ...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:313: in function 'fn'
        ...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:77: in function <...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:76>
```

**Comment by ibhagwan** [comment]
> @ibhagwan after I resumed, then I use fzf.buffers will occurd follwing error
> 
> ```
> Error executing vim.schedule lua callback: ...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:313: vim/shared.lua:0: t: expected table, got nil
> stack traceback:
>         [builtin#36]: at 0x010523481c
>         ...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:313: in function 'fn'
>         ...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:77: in function <...key/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:76>
> ```

Can you help me reproduce this? Does this happen all the time with buffers (I assume not)? Is a certain sequence required to trigger this bug? Does this happen on selection / up/down / ctrl-x?

**Comment by Marskey** [comment]
@ibhagwan my config
```
local actions = require("fzf-lua").actions
require("fzf-lua").setup {
  "telescope",
  defaults = { formatter = "path.filename_first" },
  winopts = {
    height = 0.90,
    width = 0.77,
    preview = {
      wrap = "wrap",
      layout = "vertical", -- horizontal|vertical|flex
      vertical = "down:50%", -- right|left:size
      hidden = "hidden", -- hidden|nohidden
    },
  },
  fzf_opts = { ["--layout"] = "reverse", ["--marker"] = "+" },
  fzf_colors = {
    ["gutter"] = "-1",
  },
  hls = {
    cursorline = "CursorLine",
    cursorlinenr = "CursorLineNr",
  },
  grep = {
    rg_opts = "--column --line-number --no-heading --color=always -L --smart-case --max-columns=4096 -e",
  },
  keymap = {
    builtin = {
      ["<Esc>"] = "hide",
      ["<F1>"] = "toggle-help",
      ["<c-n>"] = "toggle-fullscreen",
      -- Only valid with the 'builtin' previewer
      ["<F3>"] = "toggle-preview-wrap",
      ["<c-p>"] = "toggle-preview",
      ["<F5>"] = "toggle-preview-ccw",
      ["<F6>"] = "toggle-preview-cw",
      ["<C-d>"] = "preview-page-down",
      ["<C-u>"] = "preview-page-up",
      ["<S-left>"] = "preview-page-reset",
    },
    fzf = {
      ["ctrl-z"] = "abort",
      ["ctrl-f"] = "forward-char",
      ["ctrl-b"] = "backward-char",
      ["ctrl-a"] = "beginning-of-line",
      ["ctrl-e"] = "end-of-line",
      ["alt-a"] = "toggle-all",
      -- Only valid with fzf previewers (bat/cat/git/etc)
      ["f3"] = "toggle-preview-wrap",
      ["f4"] = "toggle-preview",
      ["ctrl-d"] = "preview-page-down",
      ["ctrl-u"] = "preview-page-up",
    },
  },

  actions = {
    files = {
      ["default"] = actions.file_edit_or_qf,
      ["ctrl-s"] = actions.file_split,
      ["ctrl-v"] = actions.file_vsplit,
      ["ctrl-t"] = actions.file_tabedit,
    },
  },
}
```
I figure out  that ` ["<Esc>"] = "hide",` is the reason cause this error. after opening `fzf.files`, press `esc` to hide it, then use `fzf.buffers`.

**Comment by ibhagwan** [comment]
Does the interface open at all? What happens if you `:FzfLua buffers previewer=false`?

**Comment by Marskey** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/6f73612e-f9b1-4407-9124-4946dd8337f9">

after `:FzfLua buffers previewer=false`

**Comment by ibhagwan** [comment]
Ty @Marskey, I have a good idea now where this might come from.

**Comment by Marskey** [comment]
If I use <M-esc> It will work normally

**Comment by ibhagwan** [comment]
@Marskey, should work as expected after https://github.com/ibhagwan/fzf-lua/commit/19c52910dce1a95f01fc2dc3c7c7458ad425b887.

**Comment by matthewgrossman** [comment]
I have a usecase that involves using `hide` to effectively cache the results of the most recent search.

One of my current workflow issues is that my `:FzfLua grep_project` takes quite a bit; each time I open it up it takes ~10s before the line counter at the top right stops moving. Ideally, I'd be able to do this loading once per vim-session, rather than on each query (I realize this is called out in the [docs](https://github.com/ibhagwan/fzf-lua/blob/5dec364c9dedec00dcd6d06e323d7bc7f8d6b596/doc/fzf-lua-opts.txt#L1109-L1112), but the habit of using fuzzy-finding from the start of the search is a hard habit to shake).

What I'd like is something like this:

1. open `:FzfLua grep_project`
2. select my option(s), hit enter.
3. This would do the normal things that enter does (`file_edit_or_qf`), but rather than close the search, it'd just `hide` the search
4. opening `FzfLua grep_project resume=true` should reopen search, with the files already loaded. Now, I can simply delete my last query and start fuzzy-finding immediately

I realize this means leaving an open process of `fzf` during the entirety of my editing session, but I don't have an issue with it. I view it as paying a price for having an always-loaded index of the lines in my project ¯\_(ツ)_/¯

Does this seem reasonable or feasible? Happy to move this into a separate ticket if you think it's worth exploring.

**Comment by ibhagwan** [comment]
> One of my current workflow issues is that my :FzfLua grep_project takes quite a bit; each time I open it up it takes ~10s before the line counter at the top right stops moving

This shouldn’t happen, try disabling git and file icons and delete `--sort` from your rg options, depending on the project size the enumeration can take a while but results should come in immediately.

I would also argue that `grep_project` isn’t the right place to start in a big project as it’s simply feeding all lines in the project into fzf which is inefficient, start with `live_grep`, narrow down the results and then `ctrl-g` into fuzzy.

> select my option(s), hit enter.

You can modify the `enter` action to `{ fn = actions.file_sel_to_qf, exec_silent=true }`, that way you’ll be able to create quickfix lists with each enter which you can then explore with `:FzfLua quickfix_stack`.

If you wish to hide the interface after the enter you can create a custom action that creates (or modifies) the quickfix list and then calls `:FzfLua hide` at the end.


> opening FzfLua grep_project resume=true should reopen search, with the files already loaded. Now, I can simply delete my last query and start fuzzy-finding immediately

Call `:FzfLua resume` or `:FzfLua unhide` to unhide the process.

> I realize this means leaving an open process of fzf during the entirety of my editing session, but I don't have an issue with it. I view it as paying a price for having an always-loaded index of the lines in my project ¯_(ツ)_/¯

Hiding the process indeed leaves a separate process until you call resume/unhide but unfortunately the current architecture doesn’t support more than one hidden process so any call to `:FzfLua xxx` will terminate the hidden process.

> Does this seem reasonable or feasible? Happy to move this into a separate ticket if you think it's worth exploring.

Feasible yes, but doing this right requires an architecture change which I’m not planing on doing ATM.
