### ISSUE TITLE
When change to a branch, in some cases, it checkouts the last commit

### ISSUE THREAD

**Issue by Massolari** [ibhagwan/fzf-lua#123]
When using `git_branches` and selecting a brach.
It checkouts the commit hash:

https://user-images.githubusercontent.com/12272702/132595556-909feccf-181e-4800-aad5-b0ab5c5d9ca9.mov

In the first two branches, it worked as expected, but any other branch like "feature/foo" or "enhancement/bar" it checkouts the last commit of that branch

**Comment by ibhagwan** [comment]
The git branches action runs `git switch --detach <branch>` for branches with `/` in their name, I'm thinking this might be the issue here as the original intention was to do this for remote branches.

Can you run a few tests in the command line with `--detach` and without and lmk which works and which doesn't for your branches?

**Comment by gegoune** [comment]
I think it's invalid assumption that `/` will only appear in remote branches. It's pretty common to name branches such as `author/feature` I think.

**Comment by ibhagwan** [comment]
> I think it's invalid assumption that `/` will only appear in remote branches. It's pretty common to name branches such as `author/feature` I think.

You’re right, can you recommend a git checkout / switch command that will work for all types of branches?

**Comment by gegoune** [comment]
Not sure, I was always just doing `git checkout <branch>` but maybe there is an easy way to check if branch is local or remote (maybe [this](https://gist.github.com/iridiumcao/714d3d0a9137ce614c26e4e10d185291)?) and run `--detach` only for remote branches?

**Comment by ibhagwan** [comment]
Maybe @jpe90 who helped with the git actions has an idea?

What if I just check for the word “remotes”? Is there any chance of having a remote branch that doesn’t start with “ remotes”?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/81ed9c4d6b584b890bd5ee45c41b40f2b3f3b19d should fix it.

I changed the check to see if the branch starts with `remotes`, based on quick search this seems consistent behavior that can be relied upon.
