### ISSUE TITLE
Bug: Slow on Small Repo

### ISSUE THREAD

**Issue by allcentury** [ibhagwan/fzf-lua#1230]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac M1

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.52.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({})
local fzf = require('fzf-lua')
vim.keymap.set('n', '<leader>ff', fzf.files, {})
vim.keymap.set('n', '<leader>fgt', fzf.git_files, {})
vim.keymap.set('n', '<leader>fg', fzf.live_grep, {})
vim.keymap.set('n', '<leader>fb', fzf.buffers, {})
vim.keymap.set('n', '<leader>fh', fzf.help_tags, {})
vim.keymap.set('n', '<leader>fw', function() fzf.grep({ search = vim.fn.expand('<cword>') }) end, { noremap = true, silent = true })
```

### Describe the bug / steps to reproduce

First, I love this plugin and want to give my thanks for creating it.  I only have this issue on a jekyll repo that is very small (I'm happy to invite you to it).  In the video below you'll see I:

1. start nvim
2. search for the word 'post' - it hangs for 10+ seconds 

If i do the same with mini, it doesn't hang for 10 seconds but still is very slow.

In the video I then call fzf from the command line and via vim without issue (it's fast and works as expected).   My hunch is the first file it tries to load a preview of is a big (720kb) minified javascript file (I don't get why this file is first, it's not the first file lexicographically). 

![fzf-lua-slow](https://github.com/ibhagwan/fzf-lua/assets/5561166/925d0531-a85d-4530-85d4-7131f8a39c89)

**Comment by ibhagwan** [comment]
It’s most unrelated to fzf and likely due to the previewer having to open the minified files and enabling treesitter.

Try:
```lua
:FzfLua files previewer=false
:FzfLua files previewer=bat
```

If these do work you can disable treesitter parsing for the problematic extensions and it will solve you tissue.

**Comment by ibhagwan** [comment]
To disable tree sitter in the built in previewer go to the README default options section and look under `previewer.builtin.treesitter.disable`.

**Comment by allcentury** [comment]
@ibhagwan wow, appreciate such a speedy response and ya I had a feeling it was the minified file.  Changing it to bat worked, thanks again!

**Comment by ibhagwan** [comment]
> @ibhagwan wow, appreciate such a speedy response and ya I had a feeling it was the minified file. Changing it to bat worked, thanks again!

Bat is used natively within fzf and is also an external process so it’s  not going to hang your neovim main thread.

While you can try to match your colors scheme it will be slightly different, if you still preferred the builtin previewer which is a neovim buffer disabling treesitter will make it faster with the default syntax highlighting.

**Comment by ibhagwan** [comment]
Btw @allcentury, I can see from your video you’re using icons but lacking a compatible font (any nerd font should work) and all the icons appear as `?`, if you don’t care for the icons, disable both `git_icons` and `file_icons` and you’ll get an additional performance boost.
