### ISSUE TITLE
Bug: fzf-lua breaks lazy loading of nvim-cmp

### ISSUE THREAD

**Issue by raulchen** [ibhagwan/fzf-lua#1231]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

msg

### Neovim version (`nvim --version`)

v0.10.0

### Fzf version (`fzf --version`)

0.50.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

N/A

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

Hi, thanks for this awesome plugin.

I noticed that, after a recent change, fzf-lua now will eagerly require nvim-cmp ([code pointer](https://github.com/ibhagwan/fzf-lua/blame/b92220ec838c195eb1c711daa69c905b1d7b8d8c/plugin/fzf-lua.lua#L30)).
Previously I lazily loaded nvim-cmp on "InsertEnter" to reduce startup time. 

I'm wondering if there is a chance to make this lazy, or at least add a flag to disable this. Thank you!

**Comment by ibhagwan** [comment]
you’re correct, this is done in order to have the picker and option docs available with nvim-cmp.

> I'm wondering if there is a chance to make this lazy, or at least add a flag to disable this. Thank you!

Sure we can fix that, perhaps a lazy check if lazy is available and have cmp loaded, I will look into it.

**Comment by bew** [comment]
note: I don't think you should check if lazy is available, pkg loading can be implemented without lazy, and shouldn't break either way

**Comment by ibhagwan** [comment]
> note: I don't think you should check if lazy is available, late pkg loading can be implemented without lazy, and shouldn't break either way

Of course it’s very easy to check using `package.loaded`, but assuming someone has cmp installed in any other mean than lazy.nvim, the package is most likely located in the start folded and is ok to be be required, I’m assuming (perhaps a wrong assumption) the users who care about sequencing and lazy loading would be lazy.nvim users.

Any suggestions for sound logic are welcome, I’d love to avoid yet another customization option unless necessary.

**Comment by ibhagwan** [comment]
> Are you seeing a limitation with only checking using `package.loaded` ?

Not a limitation but I personally find it desirable to load cmp when we setup the command source even if it’s in the `opt` dir, I’ll think about it.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/509b66642fa903d02444f136d773f8ede6a781c5 fixes lazy loading, it seems there's no side effect to registering the cmp source first time as the user attempts to first complete `:FzfLua ...`.
