### ISSUE TITLE
Bug: different prompts for the same configurations

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1232]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Macos

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.52.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
[link](https://github.com/kaiphat/dotfiles/blob/master/nvim/lua/plugins/fzf.lua)
```

### Describe the bug / steps to reproduce

It was okay earlier, but now for lsp code action i see it:
![image](https://github.com/ibhagwan/fzf-lua/assets/53742299/a791cec1-dc57-41ea-acaa-e4b61764c4b4)

But for lsp workspace symbols:
![image](https://github.com/ibhagwan/fzf-lua/assets/53742299/3b04e560-c1b5-46d1-8d86-548c4177f784)

You can see different caret and horizontal line.

**Comment by kaiphat** [comment]
```lua
				code_actions = {
					prompt = build_prompt(),
					async_or_timeout = 5000,
					-- when git-delta is installed use "codeaction_native" for beautiful diffs
					-- try it out with `:FzfLua lsp_code_actions previewer=codeaction_native`
					-- scroll up to `previewers.codeaction{_native}` for more previewer options
					previewer = false,
				},

```


```lua
				symbols = {
					prompt = build_prompt(),
					async_or_timeout = true, -- symbols are async by default
					symbol_style = 1, -- style for document/workspace symbols
					-- false: disable,    1: icon+kind
					--     2: icon only,  3: kind only
					-- NOTE: icons are extracted from
					-- vim.lsp.protocol.CompletionItemKind
					-- icons for symbol kind
					-- see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolKind
					-- see https://github.com/neovim/neovim/blob/829d92eca3d72a701adc6e6aa17ccd9fe2082479/runtime/lua/vim/lsp/protocol.lua#L117
					symbol_icons = {
						File = '󰈙',
						Module = '',
						Namespace = '󰦮',
						Package = '',
						Class = '󰆧',
						Method = '󰊕',
						Property = '',
						Field = '',
						Constructor = '',
						Enum = '',
						Interface = '',
						Function = '󰊕',
						Variable = '󰀫',
						Constant = '󰏿',
						String = '',
						Number = '󰎠',
						Boolean = '󰨙',
						Array = '󱡠',
						Object = '',
						Key = '󰌋',
						Null = '󰟢',
						EnumMember = '',
						Struct = '󰆼',
						Event = '',
						Operator = '󰆕',
						TypeParameter = '󰗴',
					},
					-- colorize using Treesitter '@' highlight groups ("@function", etc).
					-- or 'false' to disable highlighting
					symbol_hl = function(s)
						return '@' .. s:lower()
					end,
					-- additional symbol formatting, works with or without style
					symbol_fmt = function(s, opts)
						return '[' .. s .. ']'
					end,
					-- prefix child symbols. set to any string or `false` to disable
					child_prefix = true,
					fzf_opts = {
						['--tiebreak'] = 'begin',
					},
				},

```

**Comment by ibhagwan** [comment]
This isn’t a bug, you are inheriting `--no- separator` in your fzf_opts from the defaults, you can negate that by setting it to false under `lsp.symbols` or removing this line:
https://github.com/kaiphat/dotfiles/blob/c26377378d00a346f76e2f923c2db1c491d259f0/nvim/lua/plugins/fzf.lua#L498

**Comment by kaiphat** [comment]
I mean that i want to have `--no-separator` how in symbols:) But code action view doesn't inherit it.

**Comment by kaiphat** [comment]
Ant caret also)

**Comment by ibhagwan** [comment]
Or did you mean why isn’t code Addison inherenting your settings in defaults?

how are you calling code actions? With `:FzfLua lsp_code_actions` or  `register_ui_select` and then calling `vim.lsp.buf.code_actions`?

**Comment by kaiphat** [comment]
Yep:)

```lua
		map({ 'n', 'v' }, '<space>la', function()
			require('fzf-lua').lsp_code_actions {}
		end)

```

**Comment by kaiphat** [comment]
With register the same behaviour.

**Comment by ibhagwan** [comment]
Got it, I’ll check why this happens when I’m not AFK.

**Comment by ibhagwan** [comment]
@kaiphat, should be fixed in https://github.com/ibhagwan/fzf-lua/commit/a859019c06a43a80819556799591b4b03f96bc90.

**Comment by kaiphat** [comment]
Yes, it works as well, thank you!
