### ISSUE TITLE
Feature: Auto-select when there is only 1 match

### ISSUE THREAD

**Issue by Grazfather** [ibhagwan/fzf-lua#1235]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I would like the ability to configure certain search commands (e.g. lsp_definitions) to skip the fuzzy search and immediately go to the single result when there is only one.

I found this discussion: https://github.com/ibhagwan/fzf-lua/discussions/1156

But it seems that that doesn't work for specific commands (or I am doing it incorrectly)

When I bind
```lua
 (require("fzf-lua")).lsp_definitions({fzf_opts = {["--select-1"] = true}}
```
I get an error
```
⁠ E5108: Error executing lua: ...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:917: ...raca/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:574: attempt to index local 'v' (a boolean value
)
stack traceback:
        [C]: in function 'fn'
        ...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:917: in function <...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:906>
```

**Comment by Grazfather** [comment]
That never came up in my search, and I don't see it documented anywhere.

**Comment by Grazfather** [comment]
Just tried it out. Works great. Would be nice to add to the docs/wiki.

**Comment by ibhagwan** [comment]
> Just tried it out. Works great. Would be nice to add to the docs/wiki.

Been in the wiki forever
https://github.com/ibhagwan/fzf-lua/wiki#lsp-single-result

**Comment by ibhagwan** [comment]
Btw, there is also `ignore_current_line` and `includeDeclaration`, the options document is WIP.

**Comment by Grazfather** [comment]
Ah, I see. Unfortunately github search didn't let me find it when searching the wiki, and I must have ctrl-f'd for the wrong word e.g. 'match' instead of result.

That rocks

**Comment by ibhagwan** [comment]
Btw @Grazfather, I just tried
```lua
:FzfLua lsp_definitions fzf_opts.-1=true
```

And it works as expected, moreso, I can't seem to find a connection of the error message to the line references, suspecting you're not in the most recent update, can you check with the latest commit (`--select-1` should not be an issue)?

**Comment by Grazfather** [comment]
Yeah I am not sure why it was causing the issue either, but adding the line is what caused it, since I use that binding all the time. Strangely if I just run `:lua (require("fzf-lua")).lsp_definitions({fzf_opts = {["--select-1"] = true}})` as an ex command it seems to work. No big deal.
