### ISSUE TITLE
Bug: custom action with `prefix` and `fn` never calls `fn`

### ISSUE THREAD

**Issue by folke** [ibhagwan/fzf-lua#1241]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

0.11

### Fzf version (`fzf --version`)

0.53

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

""

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
files = {
          actions = {
            ["ctrl-t"] = {
              fn = function(selected, opts)
                -- this never gets called
                vim.notify(vim.inspect({ selected = selected, opts = opts }))
              end,
              prefix = "select-all",
            },
          },
        },
})
```

### Describe the bug / steps to reproduce

I would like to add official support for fzf-lua to trouble.nvim, but I don't seem to be able to have any custom action working when it's combined with `prefix="select-all"`.

It always seems to open the results in the quickfix instead.

I've seen there's quite a few recent commits related to binds/expect, so those may be related.

To reproduce:
- Open `:FzfLua files`.
- Press `<c-t>`.
- All files will be added to the quickfix lists and the custom `fn` won't be executed.

**Comment by folke** [comment]
Possibly Related:
* https://github.com/ibhagwan/fzf-lua/discussions/1109#discussioncomment-8961907
* https://github.com/ibhagwan/fzf-lua/commit/04f4c5c66ae5ba6512d2add3c7ffa60401b4c9ec
* https://github.com/junegunn/fzf/commit/41bcbe342ff70020bd7aa776ca041205aa970f43

**Comment by ibhagwan** [comment]
Ty @folke for all your work and for this report ❤️ 

I wrote this code before 0.53 was released, apparently there is still an issue with combing both expect and bind flags even after the change making it hard to accurately determine the bind that was pressed, with the latest commit I solved the issue by removing the usage of `--expect` altogether.

**Comment by folke** [comment]
Thanks for merging!!

I just finished the trouble integration: https://github.com/folke/trouble.nvim?tab=readme-ov-file#fzf-lua

Right now, I expose four actions:
* `open`: open the selected entries in trouble
* `open_all`: open all entries in trouble
* `add`: add selected entries to existing list in trouble
* `add_all`: add all entries to existing list in trouble

For **Telescope**, I only have `open` and `add` and use `all` when there's no selection or the selection when multiple items are selected.

I assume something similar to Telescope is not possible with **fzf**?

So if no items or only one item is selected, do `select-all`, otherwise `accept`.

**Comment by ibhagwan** [comment]
> I assume something similar to Telescope is not possible with fzf?
> So if no items or only one item is selected, do select-all, otherwise accept.

 Fzf v0.46 added an env var `FZF_SELECT_COUNT` so it should be possible to do with a `transform` prefix that checks and echoes `select-all` if select count is 0 or 1.

That said, the condition would probably need to be different for windows as it’s run under `cmd.exe`.

I have another idea, if it’s possible to access all of trouble items regardless of the selection we can have the trouble `open` action check for `#selected < 2` and if true send all trouble items to quickfix?

**Comment by folke** [comment]
I'm not sure I understand your second idea.

If there's a way for me to get all the items and still be able to know which ones were selected, then that would be great. But can I do that?

Let's say the user does `FzfLua files`. They then drill down to search query `lua`.

Or do you mean to do this in two steps using `resume` or something like that?

**Comment by ibhagwan** [comment]
> I'm not sure I understand your second idea.

That’s because I misunderstood what we are after, I thought there is a list of trouble “locations” and the action we’re after is sending these to quick fix.

I had imagined a picker of trouble items fed from an arbitrary lua source (e.g. something like `trouble.get_all()`) and using that source to build the quickfix list when `#selected == 0`.

I now understand you’re trying to send **other pickers items into trouble**.

> If there's a way for me to get all the items and still be able to know which ones were selected, then that would be great. But can I do that?

Not possible with fzf ATM but the `transform` approach with the env var should work, I’ll try to craft something and let you know if it works.

**Comment by ibhagwan** [comment]
Hi @folke,

Test on Linux/Mac, this does what you want (pressing `ctrl-t` selects all items if none are selected):
```lua
require('fzf-lua').fzf_exec(
  { "a", "b", "c", "d" },
  {
    actions = {
      ["ctrl-t"] = {
        fn = function(sel)
          print("no items:", #sel)
        end,
        prefix = "transform([ $FZF_SELECT_COUNT -eq 0 ] && echo select-all)",
      },
    },
  })
```

I didn't test but the condition on windows could be:
```lua
    prefix = "IF %FZF_SELECT_COUNT% LEQ 0 (echo select-all)"
```

**Comment by folke** [comment]
Works great, thanks!!

**Comment by ibhagwan** [comment]
> Works great, thanks!!

FYI, just tested on windows and it works as well, but I noticed I forgot to wrap the prefix in `transform`:
```lua
    prefix = "transform(IF %FZF_SELECT_COUNT% LEQ 0 (echo select-all))"
```

Left a comment on your commit in the approperiate line.
