### ISSUE TITLE
Bug: Unsupported action

### ISSUE THREAD

**Issue by dpetka2001** [ibhagwan/fzf-lua#1242]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

nvim v0.11 latest nightly

### Fzf version (`fzf --version`)

0.53

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--layout=reverse --cycle --bind='ctrl-r:reload(rg --hidden --files)' --header='Press CTRL-R to reload ' --border -m --bind 'ctrl-v:execute(nvim {+})','ctrl-d:reload(find . -type d)'

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  opts.keymap = vim.tbl_deep_extend("force", require("fzf-lua").defaults.keymap, {
    fzf = {
      ["ctrl-q"] = "select-all+accept",
    },
  })
})
```

### Describe the bug / steps to reproduce

After latest commit update I get the following error when live grepping for something and pressing the keymap `ctrl-q` in my configuration (it actually happens with other pickers as well: `files` and `buffers` that I tried)
```
[Fzf-lua] unsupported action: ' README.md:126:13:- [ibhagwan/fzf-lua](https://dotfyle.com/plugins/ibhagwan/fzf-lua)<a href="https://dotfyle.com/plugins/ibhagwan/fzf-lua">', type:nil
```
Reverting to commit `9ecc8f6` does not produce this issue.

**Comment by ibhagwan** [comment]
Ty for the report @dpetka2001! should be fixed after https://github.com/ibhagwan/fzf-lua/commit/993fce4991b28064eb3f34146c51ee85ca808135.

**Comment by gengdz** [comment]
I am also having this problem now

Error info: 

```bash
[Fzf-lua] unsupported action: '', type:nil
``` 
some information that might be useful:

```bash
❯ fzf --version
0.53.0 (brew)
```

@dpetka2001 Are you able to work normally now under LazyVim?

**Comment by dpetka2001** [comment]
No, it's not working again. Something changed in `0e08cea` commit, it seems. Reverting to commit `b59bb9a` fixes the issue. @ibhagwan any ideas?

**Comment by ibhagwan** [comment]
I’ll check why this fails, I did more changes to this part of the code in commit 788a4939e48f80f4715972d823050d9080a8a53d, did you try with the latest commit?

**Comment by dpetka2001** [comment]
`fzf-lua` that is installed is on commit `c56717d` which seems to be the latest. Still same behavior.

**Comment by ibhagwan** [comment]
Should work again with https://github.com/ibhagwan/fzf-lua/commit/5c404c613832e39c5caf8753d1b099d7abd1f1b8.

**Comment by dpetka2001** [comment]
Can confirm. Thanks again for your swift response as always :smile:

**Comment by dpetka2001** [comment]
@ibhagwan Sorry to bother you again. But I seem to remember that `select-all+accept` used to open all files in the picker (pls correct me if I remember wrong). With your latest fix the error did go away, but now the behavior is to send the files to the quickfixlist instead of opening them. If that is intended behavior, that's ok. I just seem to remember a different behavior if I'm not mistaken.

**Comment by ibhagwan** [comment]
> @ibhagwan Sorry to bother you again. But I seem to remember that `select-all+accept` used to open all files in the picker (pls correct me if I remember wrong). With your latest fix the error did go away, but now the behavior is to send the files to the quickfixlist instead of opening them. If that is intended behavior, that's ok. I just seem to remember a different behavior if I'm not mistaken. But maybe I'm mistaken, that's why I ask for clarification.
> 
> PS: Unfortunately, it seems I bothered you for nothing. I did remember wrong and I just had to change `actions.files["default"] = actions.file_edit` to achieve what I wanted. Sorry about that.

Correct @dpetka2001, `file_edit_or_qf` sends any selection over 1 file to the qf, Ty for the update!
