### ISSUE TITLE
Bug: multiline = 1 causes no buffers to be shown when using :FzfLua buffers

### ISSUE THREAD

**Issue by brphilly** [ibhagwan/fzf-lua#1252]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.53.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--cycle --layout=reverse --bind ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    defaults = { multiline = 1 },
})
```

### Describe the bug / steps to reproduce

Using the setup options above, open multiple buffers and run `:FzfLua buffers`. None of the buffers are visible (except the current buffer).

As I was making this issue I realised if you do `require('fzf-lua').setup({grep = { multiline = 1 }})` (i.e. set multiline inside the grep table instead of defaults table) it works correctly.

**Comment by ibhagwan** [comment]
> As I was making this issue I realised if you do require('fzf-lua').setup({grep = { multiline = 1 }}) (i.e. set multiline inside the grep table instead of defaults table) it works correctly.

Correct, it does make no sense to use this currently anywhere aside LSP/grep.

Nevertheless it should've worked as the setting works globally and could one day be used for any other picker including buffers, fixed in https://github.com/ibhagwan/fzf-lua/commit/ac4900872cc6aa0c37a03fc6e7901ec59aa00378.
