### ISSUE TITLE
Feature: Operation Record

### ISSUE THREAD

**Issue by rgzntrade** [ibhagwan/fzf-lua#1256]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Record searches in different modules
For example, file search.
Open file search
First search A
then B
Close file search

Open file search
Press ctrl+up arrow
Search B appears
Press ctrl+up arrow
Search A appears
Close file search

**Comment by ibhagwan** [comment]
Already exists, use `--history`, by default will setup ctrl-p|n for previous|next, you can have a combined history file or a history per picker(s):
https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-setup-input-history-keybinds
