### ISSUE TITLE
Integration with focus.nvim

### ISSUE THREAD

**Issue by eshepelyuk** [ibhagwan/fzf-lua#1260]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

It could be great to have a new native actions that leverage [focus.nvim](https://github.com/nvim-focus/focus.nvim) for opening files in new split.

I.e. instead of relying on vim split defaults or declaring hotkeys for vertical\horizonal split, the plugin can provide a new action that calls [FocusSplitNicely](https://github.com/nvim-focus/focus.nvim?tab=readme-ov-file#splitting-nicely) functionality, so plugin users could set it as a default actuon for opening a file.

Currently, I am integrating it like this.

```lua
local focus = require("focus")
local fzf_path = require "fzf-lua.path"
require("fzf-lua").setup({
	actions = {
		files = {
			["default"] = function(selected, opts)
				local e = fzf_path.entry_to_file(selected[1], opts)
                                focus.split_nicely(e.path)
                                vim.api.nvim_win_set_cursor(0, {e.line, e.col - 1})
			end,
		},
	},
})
```

**Comment by ibhagwan** [comment]
Never heads about this plugin before but it looks great.


Unfortunately, this is an endless rabbit hole, I cannot maintain an endless amount of plug-in integrations, that’s why the API exists as you so nicely demonstrated :)
