### ISSUE TITLE
Bug: `formatter={'path.filename_first',2}` doesn't open file correctly if in root(project root) directory

### ISSUE THREAD

**Issue by shubham-cpp** [ibhagwan/fzf-lua#1265]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux - Archlinux kernel 6.9

### Shell

fish and zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.53.0 (c4a9ccd6)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--cycle --marker='+' --keep-right --bind=ctrl-j:preview-down --bind=ctrl-k:preview-up

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

Consider you have opened a project(any project), and if you run the `FzfLua files` with the updated `path.filename_first` then files at root level of the project wont open correctly.
Without the **2** (`:lua require('fzf-lua').files({formatter={'path.filename_first'}})`), things work as expected

```lua
:lua require('fzf-lua').files({formatter={'path.filename_first',2}})
```

Below I've attached the video

![output_optimized](https://github.com/ibhagwan/fzf-lua/assets/31388020/0c5cfcf6-2f56-42e0-bdbf-214e35c1130d)

**Comment by ibhagwan** [comment]
Ty for the report @shubham-cpp! I’ll take a look later today when not AFK.

**Comment by ibhagwan** [comment]
@shubham-cpp, should work as expected after https://github.com/ibhagwan/fzf-lua/commit/691a8589d301efbc9e9e7694244d40e5d6ffffc6.
