### ISSUE TITLE
Using a key binding for :FzfLua files has a delay.  Entering in CMD mode :FzfLua files, does not

### ISSUE THREAD

**Issue by esn89** [ibhagwan/fzf-lua#1276]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

v0.10.0

### Fzf version (`fzf --version`)

0.53.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=fg:#d3c6aa,fg+:#d3c6aa,bg:#2e383c,bg+:#495156 --color=hl:#a7c080,hl+:#83c 092,info:#afaf87,marker:#dbbc7f --color=prompt:#e67e80,spinner:#d699b6,pointer:#7 fbbb3,header:#87afaf --color=border:#7a8478,label:#d3c6aa,query:#d3c6aa --border= "sharp" --border-label="fzf" --border-label-pos="0" --preview-window="border-roun ded" --prompt="> " --marker=">" --pointer="◆" --separator="─" --scrollbar="│" --l ayout="reverse" --info="right" --preview "bat --style=numbers --color=always --th eme=\"Catppuccin Frappe\" --line-range :500 {}"

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
            files = {
                previewer = 'bat',
                cwd_prompt = false,
                prompt = ' > ',
                fd_opts = [[--color=never --type f --hidden --follow --exclude .git --exclude venv ]],
                rg_opts = [[--color=never --files --hidden --follow -g "!.git" -g "!venv/"]],
            },
            buffers = {
                prompt = ' > ',
            },
            grep = {
                prompt = ' 󰮗 > ',
            },
            keymap = {
                fzf = {
                    ['ctrl-c'] = 'abort',
                    ['ctrl-q'] = 'select-all+accept',
                    ['ctrl-d'] = 'preview-page-down',
                    ['ctrl-u'] = 'preview-page-up',
                },
            },
        })


and in my `~/.config/nvim/init.lua`:

```
vim.keymap.set('n', '<Leader>o', ':FzfLua files<CR>', { noremap = true, silent = true })
```
```

### Describe the bug / steps to reproduce

In my project directory, which has about 15 files or so, there is about a 1-2 second delay to seeing the FzfLua window, when I hit the hotkeys of:  `spacebar + o` and this will do `:FzfLua files`.

My <Leader> is spacebar.

However, when I type out the command in Neovim `:FzfLua files <i press enter here>` it is instantaneous.

**Comment by ibhagwan** [comment]
This isn't a bug, if you have other mappings the you set to `<leader>o<other keys>`, neovim will wait to see if you pressed the second key in the sequence, figure out which mappings you have starting with `<leader>o` or  use `nowait` to tell neovim to not wait for a second key:
```lua
vim.keymap.set("n", "<leader>o", "<cmd>FzfLua files<CR>", { desc = "FzfLua", nowait = true })
```

**Comment by esn89** [comment]
aaah.  gotcha.  This `nowait` is a savior!  Thank you SO MUCH.
