### ISSUE TITLE
Bug: Selection in menu does not have a highlight group

### ISSUE THREAD

**Issue by aj-sarama** [ibhagwan/fzf-lua#1277]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

v0.10.0

### Fzf version (`fzf --version`)

0.53.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
return
{
	{
		"ibhagwan/fzf-lua",
		-- optional for icon support
		dependencies = { "nvim-tree/nvim-web-devicons" },
		config = function()
			-- calling `setup` is optional for customization
			require("fzf-lua").setup({})
		end
	},
	{ "nvim-tree/nvim-web-devicons" }
}
```

### Describe the bug / steps to reproduce

1. Open menu using :FzfLua
2. Use up/down arrows to select an option
3. Notice color of the highlighted line that indicates the current selection
4. Open :FzfLua highlights
5. No match will be found for the background of the selection highlight

**Comment by ibhagwan** [comment]
Not sure what you mean, I just did the sequence you're describing (opening `highlights` from the `:FzfLua` menu) and I have background for the selection:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/2fe9d957-311b-4153-a3ae-f1c2c0d26862)

 This could be an issue with your config/colorscheme, why haven't you tried with `mini.sh`?

Please try with `mini.sh` and provide more details and screenshots so I can better understand this issue.

**Comment by aj-sarama** [comment]
In your screenshot, you have '@comment' highlighted with a pink bar next to it. There are no FzfLua HL groups corresponding to those colors.

**Comment by ibhagwan** [comment]
> In your screenshot, you have '@comment' highlighted with a pink bar next to it. There are no FzfLua HL groups corresponding to those colors.

These are controlled by fzf, see man fzf (this is either marker or pointer), you can set these using `fzf_colors` or if you set `fzf_colors=true` you can use the corresponding fzf hl group, FzfLuaFzfPointer/FzfLuaFzfMarker

https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#highlights

**Comment by ibhagwan** [comment]
This one is pointer:
```lua
:FzfLua files fzf_colors=true hls.fzf.pointer=Directory
```
![IMG_2190](https://github.com/ibhagwan/fzf-lua/assets/59988195/f83e8c1b-4993-4607-8849-5a2f85187c61)
