### ISSUE TITLE
Bug: when open fzf-lua split below, another tab `sh` appear

### ISSUE THREAD

**Issue by leaxoy** [ibhagwan/fzf-lua#1278]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-273+g948f2beed-Homebrew

### Fzf version (`fzf --version`)

0.53.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    winopts = {
        split = "belowright new",
        border = 'none'
    }
})
```

### Describe the bug / steps to reproduce

<img width="855" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/8556349/e6885dd1-4d50-46f1-ba07-5b5718b92652">

**Comment by ibhagwan** [comment]
Doesn’t reproduce on my end, makes me think this is something related to your config, either split options or an autocmd.

We can test this theory if you clone fzf-lua locally, modify https://github.com/ibhagwan/fzf-lua/blob/main/scripts/init.lua to use a split and then run `/path/to/fzf-lua/scripts/mini.sh`.

**Comment by leaxoy** [comment]
I used `LazyVim`, and enable `fzf-lua` extra, then my config is:
```lua
  {
    "fzf-lua",
    optional = true,
    keys = {},
    opts = function(_, opts)
      opts[0] = "skim"
      opts.winopts = vim.tbl_deep_extend("force", opts.winopts or {}, {
        split = "belowright new",
        border = 'none'
      })
      -- opts.fzf_opts = vim.tbl_deep_extend('force', opts.fzf_opts or {}, { ["--layout"] = "default" })
    end,
  }
```

I'm not sure if it's because of LazyVim. I'll try to provide a minimal reproduction configuration later.

**Comment by ibhagwan** [comment]
> I'm not sure if it's because of LazyVim. I'll try to provide a minimal reproduction configuration later.

Use the instructions I posted above with cloning fzf-lua, one edit to the minimal init, very simple.

**Comment by ibhagwan** [comment]
Installed LazyVim and tested this, it's not a bug, I believe this is how bufferline is configured in LazyVim to display any new buffer in a new tab, fzf-lua runs fzf in a terminal and using it in a split equates to running `:new | term`, run it and you'll see similar result (depending on your default `$SHELL`):
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/6af80bd1-3ab1-461e-a9f6-614ab8c30cb3)

**Comment by leaxoy** [comment]
Thanks a lot, indeed, I used minimal configuration and it did not reproduce.
