### ISSUE TITLE
Bug: Can't use ENTER to open result in a new tab

### ISSUE THREAD

**Issue by LarsMichelsen** [ibhagwan/fzf-lua#1279]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

v0.9.5

### Fzf version (`fzf --version`)

0.53.0 (c4a9ccd)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
                actions = {
                    files = {
                        ["enter"] = actions.file_tabedit,
                    },
                },
})
```

### Describe the bug / steps to reproduce

Since the commit 04f4c5c66ae5ba6512d2add3c7ffa60401b4c9ec I am not able to use the ENTER key to select some item from the search list.

Steps to reproduce:

1. CTRL + A to start a search.
2. Insert some text to match a file
3. Hit ENTER

Expected result: The selected file is opened in a new tab.
Current result: The search list is closed without a file being opened.

Alternatively using CTRL + T opens the file in a tab as expected.

**Comment by ibhagwan** [comment]
I’ll make sure it works again, for the time being change it to `default` and it will work.

**Comment by ibhagwan** [comment]
@LarsMichelsen ty for the report, post https://github.com/ibhagwan/fzf-lua/commit/b922357d60a8d998a42d09129796811e60851d76 both `default` and `enter` should behave the same.

**Comment by LarsMichelsen** [comment]
Thanks a lot for the quick fix. Works as expected.
