### ISSUE TITLE
Hide file name in document_symbol

### ISSUE THREAD

**Issue by Massolari** [ibhagwan/fzf-lua#128]
Is there a way to now show file names when listing document's symbols?

I'm asking because I have this situation:
![image](https://user-images.githubusercontent.com/12272702/132881402-4e24cb99-a3ad-4b43-abb4-4adb55fc58f6.png)

I'm looking for a symbol, and it's matching with the file name.

In document_symbol the file name is irrelevant because it's the same for all symbols.

**Comment by ibhagwan** [comment]
There is currently no way to remove the file names, they are needed for the preview to be able to display them.

However, fzf has an option to ignore certain fields when fuzzy finding with the flag `—nth`, can you try running and let me know if this works for you?

```lua
:lua require'fzf-lua'.lsp_document_symbols({ fzf_cli_args = '--nth 2,-1' })
```

I should probably add this by default to `document_symbols` as nobody expects to search for the file name while searching in the current document.

**Comment by Massolari** [comment]
Looks like it doesn't work
![image](https://user-images.githubusercontent.com/12272702/132883695-5b5f3341-b085-45e6-9aca-3df50069af3b.png)

**Comment by Massolari** [comment]
This way works, apparently:
![image](https://user-images.githubusercontent.com/12272702/132884176-d96c69b4-19de-4d06-8938-d8379592b96b.png)

**Comment by ibhagwan** [comment]
The first option worked too, I just tested this:
```lua
:lua require('fzf-lua').lsp_document_symbols({ fzf_cli_args = "--nth 2,-1" })
```

Even though it shows the filenames in the display it wouldn't search the filenames:
![screenshot-1631290158](https://user-images.githubusercontent.com/59988195/132884439-7ad8d028-d83f-4973-abca-55f8804162a3.png)

**Comment by ibhagwan** [comment]
Oh nice! for some reason I wasn't sure if fzf would still pass the field to the previewer when hiding it with `--with-nth` I guess you answered this question :-)

I guess we can close this issue.

**Comment by Massolari** [comment]
Oh, I didn't try to search. Good to know!
Thanks for point me out to the solution!
