### ISSUE TITLE
Bug: unsupported action 'enter'

### ISSUE THREAD

**Issue by johnny-mh** [ibhagwan/fzf-lua#1282]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

v0.10.0

### Fzf version (`fzf --version`)

0.50.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})


I'm just using lazyvim default settings (no custom options)
```

### Describe the bug / steps to reproduce
Thanks for building `fzf-lua` plugin :)

hit `<leader>ca` (code action) and press `1<enter>` on code action modal

        
<img width="1103" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/1061205/64738346-90a2-4c0d-b605-6e5b3065ff27">

then an warning modal popup.

<img width="394" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/1061205/16702cc7-a773-4512-847f-ab330db288c8">

**Comment by ibhagwan** [comment]
Probably related to my latest commit https://github.com/ibhagwan/fzf-lua/commit/0e08ceab0e354ec9450d93c39aef512a34b17d1b, checking.

**Comment by ibhagwan** [comment]
Ty for reporting @johnny-mh, should work with https://github.com/ibhagwan/fzf-lua/commit/788a4939e48f80f4715972d823050d9080a8a53d.

**Comment by johnny-mh** [comment]
@ibhagwan it works! thank you
