### ISSUE TITLE
Bug: Not setting 'toggle-preview' keybinding for fzf causes empty preview when opened in split

### ISSUE THREAD

**Issue by usualwitch** [ibhagwan/fzf-lua#1286]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-285+gceea6898a8

### Fzf version (`fzf --version`)

0.53.0 (c4a9ccd6)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

none

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup{
  defaults = {
    winopts = {
      split = 'botright new',
      preview = {
        hidden = 'hidden',
      },
    },
  },
  keymap = {
    builtin = {
      ['<C-f>'] = 'toggle-preview',
    },
    fzf = {
      -- ['f4'] = 'toggle-preview',  -- only works correctly if this line is uncommented
    },
  },
}
```

### Describe the bug / steps to reproduce

![empty-preview](https://github.com/ibhagwan/fzf-lua/assets/47266849/90a95249-5b03-4369-8d2d-38da009a10bf)

When using this split-window configuration, the preview window will always be empty.

Through some testing, I found that setting the 'toggle-preview' keybinding in both `keymap.builtin` and `keymap.fzf` resolves this problem for split window. This problem doesn't happen for floating window.

I don't know how to config the `keymap` option for mini.sh, so haven't tested it with mini.sh.

**Comment by ibhagwan** [comment]
> When using this split-window configuration, the preview window will always be empty.
> Through some testing, I found that setting the 'toggle-preview' keybinding in both keymap.builtin and keymap.fzf resolves this problem for split window. This problem doesn't happen for floating window.

This will happen only with the built in previewer (not with bat/git status/etc), the reason for this is that in order to display the preview in a neovim buffer and not cover fzf’s interface we generate an empty shell previewer just as a “space holder”, it’s not perfect yet and has some issues with hide/unhide and especially with auto preview rotation (based on flip_columns).

I’ll look into this specific scenario as I still don’t understand the connection to the toggle keybind.
