### ISSUE TITLE
Border issue on builtin previewer

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#129]
Hi again! So, if I set `winopts_raw` to function returning such table:

```lua
{
  border = { { "▎", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { "▎", "NormalFloat" }, { "▎", "NormalFloat" } },
  col = 48,
  height = 38,
  relative = "editor",
  row = 17,
  style = "minimal",
  width = 144,
  window_on_create = <function 1>
}
```

I get such  errors

```
Error executing vim.schedule lua callback: .../nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/win.lua:506: attempt to concatenate local 'bar_char' (a table value)
```

when I make preview visible (hidden by default). Preliminary tests show that it only errors when previewed file has more lines than preview window.

Issue seems to be gone if `previewers.builtin.scrollbar` is set to `false`.

Also, is it possible to set custom border for builtin previewer?

Thanks!

**Comment by ibhagwan** [comment]
That’s due to the already somewhat hacky nature of `winopts_raw` I don’t think anyone but you uses it :)

You can totally customize the border of the previewer not not with winopts_raw, as the border is basically drawn manually from the border chars array (and in your case fails due to the addition of highlights.

why don’t you do this?

```lua
  winopts = {
    borderchars         = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
    hl_border           = 'NormalFloat',
  }
  winopts.raw = {
    border = nil,
   …
  }
```

This way the border will be drawn properly with the highlight of your choice for both windows.

**Comment by gegoune** [comment]
> I don’t think anyone but you uses it :)

:)

That does indeed work without causing any issues. Thanks! I removed `border` from `winopts_raw` (please don't take that function away from me, it nicely generates dimensions and position depending on nvim window size. :) and used `win opts.win_border` as suggested.

I'll need to find a way to omit nested tables and return just list of characters from my border table which I want to keep as is because I pass it to many other plugins, etc and don't want to have to change it in too many places if I feel like changing my border. :)

**Comment by gegoune** [comment]
Ah, nice, that commit simplifies things for me, but unfortunately it does't seem like highlight group from `win_border` are taken into account - `hl_border` still seems to be necessary.

**Comment by ibhagwan** [comment]
>That does indeed work without causing any issues. Thanks! I removed border from winopts_raw (please don't take that function away from me, it nicely generates dimensions and position depending on nvim window size. :) and used win opts.win_border as suggested.

Not planning on taking it away :-)

>I'll need to find a way to omit nested tables and return just list of characters from my border table which I want to keep as is because I pass it to many other plugins, etc and don't want to have to change it in too many places if I feel like changing my border. :)

I actually just did that as soon as you opened the issue, you may not need to omit your `border` variable after all, the code below will just strip it of highlights, or maybe use this code in your own config?

https://github.com/ibhagwan/fzf-lua/blob/2bc6c1b07974dca881f41c5f3a7e4d33f8665e02/lua/fzf-lua/win.lua#L296-L304

> Out of curiosity, is there easier/better way of doing this:

Looks like we came up with a similar solution, I just wanted to make sure it's only 8 characters and nothing else.

**Comment by ibhagwan** [comment]
> Ah, nice, that commit simplifies things for me, but unfortunately it does't seem like highlight group from `win_border` are taken into account - `hl_border` still seems to be necessary.

Yes, `hl_border` is always necessary since it's not a real border, it's actually the `Normal` highlight of the dedicated border window and the characters are drawn manually, that's the only way I can support the scroll bar and title.

**Comment by gegoune** [comment]
Ah, it is necessary for preview window, true. Just noticed that.

Also, I am getting that error again now:

```
Error executing vim.schedule lua callback: .../nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/win.lua:516: attempt to concatenate local 'bar_char' (a table value)
```

and once again just turning off scrollbar fixes the issue.

**Comment by ibhagwan** [comment]
Can you post your exact `winopts` and `winopts_raw` so I can reproduce and fix?

**Comment by gegoune** [comment]
```lua
  previewers = {
    builtin = {
      hidden = true,
      keymap = {
        toggle_hide = '<C-p>',
      },
      scrollbar = false, -- this fixes the issue
      -- scrollchar = '│',
    },
  },
  winopts = {
    win_border = require('utils').left_border,
    hl_normal = 'NormalFloat',
    hl_border = 'NormalFloat',
  },
  winopts_raw = require('utils').floatArgs,
```

and `floatArgs` is

```lua
M.floatArgs = function()
  local columns = vim.o.columns
  local lines = vim.o.lines

  local width = math.floor(columns - (columns * 2 / 5))
  local height = math.floor(lines - (lines * 1 / 3))

  if columns < 120 then
    width = math.floor(columns - (columns * 1 / 5))
  end

  return {
    relative = 'editor',
    row = lines - height - 3,
    col = math.floor((columns - width) / 2),
    width = width,
    height = height,
    style = 'minimal',
    window_on_create = function()
      vim.api.nvim_buf_set_keymap(0, 't', '<Esc>', '<C-c>', { nowait = true, silent = true })
    end,
  }
end
```

**Comment by ibhagwan** [comment]
Should be fixed now.

**Comment by gegoune** [comment]
Still getting that error.

**Comment by ibhagwan** [comment]
This is some strange stuff, idk how your scrollchar turns into a table but it should be fixed now regardless.

**Comment by gegoune** [comment]
It still errors the same with latest master. :( I might just disable scrollbar altogether.

**Comment by ibhagwan** [comment]
Is there any chance of your plugin not updated properly? it shouldn’t be possible to have scrollchar as a table now.
Does this happen with an empty setup()?

Can you make sure it’s updated and post the error again? Maybe the error is on the same line but not the same error  (the fix is based on your original error posted).

There is no way I’m letting this stay unsolved.

**Comment by gegoune** [comment]
```shell
~ ❯ cd ~/.local/share/nvim/site/pack/packer/start/fzf-lua
fzf-lua main ❯ git rev-parse HEAD
eb7973f92650237fc1b49e76e21cf74283486d06
```

So on latest master, so far so good. :)

No errors on empty `setup({})`.

Error happens as soon as I add

```lua
  winopts = {
    win_border = require('utils').left_border,
  },
```

and is this one:
```
Error executing vim.schedule lua callback: .../nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/win.lua:517: attempt to concatenate local 'bar_char' (a table value)
```

Returned `left_border` is:

```lua
{ { "▎", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { "▎", "NormalFloat" }, { "▎", "NormalFloat" } }
```

Thanks for your persistence. :)

**Comment by ibhagwan** [comment]
Should be solved now 10000% :-)

**Comment by gegoune** [comment]
And it is! Thanks for being awesome!

**Comment by gegoune** [comment]
@ibhagwan btw, side effect of your fixes is that passing `border` as part of `winopts_raw = require('utils').floatArgs,` also works now. This is my preferred method as I can reuse that function for other windows and retain same border without having to specify it per plugin. Awesome! :) ❤️

**Comment by ibhagwan** [comment]
Ty @gegoune!  happy you got it to work exactly how you wanted :+1:
