### ISSUE TITLE
Bug: Vertical Preview Layout has started failing (It seems to not work with the builtin previewer anymore)

### ISSUE THREAD

**Issue by Emille1723** [ibhagwan/fzf-lua#1290]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [x] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Manjaro Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.52.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=fg:#bec0d3,bg:-1,hl:#50fa7b --color=fg+:#f8f8f2,bg+:#3E4F5D,hl+:#50fa7b --color=info:#bd93f9,prompt:#bd93f9,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#50fa7b,header:#8ABAB8,query:#f8f8f2 --color=border:#6272a4,scrollbar:#6272a4,preview-scrollbar:#6272a4,label:#6272a4,gutter:-1,separator:#bd93f9 --highlight-line --layout=reverse --no-height --border=top --preview-window="right,55%" --prompt="🔍" --pointer="▇ " --marker=" 󱞩" --margin="2.5%,0,0,0" --info=default --scrollbar=▌▐ --border-label="[ M-a:d  C-s:da  C-e: dc  M-d:dc  C-f:n  M-j:na  M-k:nc  M-l:ca  M-;:cc  M-r: cc  C-x:   C-c: ]" --preview-label-pos="3:bottom" --preview-window="60%,border-rounded" --bind="esc:become(exit 0;)" --bind="alt-bspace:clear-query"  --bind="alt-a:become(tmux send-keys fzd Enter)" --bind="ctrl-s:become(tmux send-keys fzda Enter)" --bind="ctrl-e:become(tmux send-keys cdPrevPATH Enter;tmux send-keys fzdc Enter)" --bind="alt-d:become(tmux send-keys fzdc Enter)" --bind="ctrl-f:become(tmux send-keys fzn Enter)" --bind="alt-j:become(tmux send-keys fzna Enter)" --bind="alt-k:become(tmux send-keys fznc Enter)" --bind="alt-l:become(tmux send-keys fzca Enter)" --bind="alt-;:become(tmux send-keys fzcc Enter)" --bind="alt-r:become(tmux send-keys cdPrevPATH Enter;tmux send-keys fzcc Enter)" --bind="ctrl-x:abort+become(tmux send-keys cdPrevPATH Enter;tmux send-keys clear Enter)" --bind="ctrl-c:abort" --bind="ctrl-d:preview-page-down" --bind="ctrl-u:preview-page-up" --bind="alt-v:replace-query" --cycle --ellipsis=STR --ansi

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    "telescope",
	fzf_colors = {
		-- ["fg"]          = { "fg", "#d3D3D3" },
		["fg"]          = { "fg", "#bec0d3" },
		["bg"]          = { "bg", "Normal" },
		["hl"]          = { "fg", "#50fa7b" },
		-- ["fg+"]         = { "fg", "#ffffff" },
		["fg+"]         = { "fg", "#f8f8f2" },
		["bg+"]         = { "bg", "#3E4F5D" },
		["hl+"]         = { "fg", "#50fa7b" },
		["info"]        = { "fg", "#bd93f9" },
		-- ["prompt"]      = { "fg", "#bd93f9" },
		-- ["prompt"]      = { "fg", "#9FE8C3" },
		["prompt"]      = { "fg", "TelescopePreviewTitle" },
		["pointer"]     = { "fg", "#ff79c6" },
		["marker"]      = { "fg", "#50fa7b" },
		["spinner"]     = { "fg", "#50fa7b" },
		["header"]      = { "fg", "#6272a4" },
		["gutter"]      = { "bg", "Normal" },
		["border"]      = { "fg", "#6272a4" },
		-- ["query"]       = { "fg", "#ffffff" },
		["query"]       = { "fg", "#f8f8f2" },
	},
	hls = {
		border = "TelescopeBorder",
		-- title = "TelescopeResultsTitle",
		title = "HeaderFzfLua",
		header_text = "TelescopeResultsTitle",
		-- cursor = { bg = "HeaderFzfLua" },
		-- cursor = { bg = "#ffffff" },
		-- preview_title = "TelescopeResultsTitle",
		preview_title = "PreviewTitleFzfLua",
	},
	previewers = {
		bat = {
			cmd = "bat",
			-- args = "--color=always --style=numbers,changes,grid",
			args = "--color=always --style=numbers,changes --wrap=character",
			-- args = "--color=always --style=numbers,changes",
			-- args = "--color=always --style=changes",
			theme = 'myDracula'
		},
		builtin = {
			syntax = true,
			treesitter = { enable = true, disable = { "tmux" } }
		}
	},
	winopts = {
		fullscreen = true,
		-- row = 0.5,
		-- height = 1,
		-- width = 1,
		title = "",
		title_pos = "center",
		border = "none",
		preview = {
			-- default
			layout = 'horizontal',
			horizontal = "right:65%",
			-- testing
			-- layout = 'vertical',
			-- vertical = "up:70%",
			border = 'noborder',
			wrap = "wrap",
			scrollbar = false,
			-- title_pos = "left",
			winopts = {
				number = false,
				cursorline = false
			}
		},
		on_create = function()
			-- <S-down> & <S-up> are the defaults to move up & down on a preview
			-- Remapping them to <C-d> & <C-u> elsewhere weren't working
			-- Works here
			vim.cmd.normal { "", bang = true }
			vim.keymap.set({ "t" }, "<C-d>", "<S-down>", { silent = true, buffer = true })
			vim.keymap.set({ "t" }, "<C-u>", "<S-up>", { silent = true, buffer = true })
			vim.b.miniindentscope_disable = true
		end,
		on_close = function()
			vim.keymap.set({ "t" }, "<C-d>", "<nop>", {})
			vim.keymap.set({ "t" }, "<C-u>", "<nop>", {})
			vim.b.miniindentscope_disable = false
		end
	},
	-- to experiment with at some point
	keymap = {
		builtin = {
			-- ['<C-/>'] = 'toggle-help',
			-- ['<C-a>'] = 'toggle-fullscreen',
			-- ['<C-i>'] = 'toggle-preview',
			-- ['<C-f>'] = 'preview-page-down',
			-- ['<C-b>'] = 'preview-page-up',
		},
		fzf = {
			-- ["ctrl-q"] = actions.files_sel_to_qf, -- leaving this files_sel_to_qf option alone on seems to be working
			["ctrl-c"] = "abort",
			-- ["ctrl-a"] = "toggle-all",
			["ctrl-q"] = "select-all+accept",
		},
	},
	actions = {
		files = {
			["default"] = fzf_lua.actions.file_edit_or_qf,
			["ctrl-l"]  = fzf_lua.actions.arg_add,
			["ctrl-s"]  = fzf_lua.actions.file_split,
			["ctrl-v"]  = fzf_lua.actions.file_vsplit,
			["ctrl-t"]  = fzf_lua.actions.file_tabedit,
			-- ["ctrl-q"]  = fzf_lua.actions.file_sel_to_qf,
			-- ["ctrl-q"] = actions.files_sel_to_qf,
			["alt-q"]   = fzf_lua.actions.file_sel_to_ll,
		},
	},
	defaults = { formatter = "path.filename_first" }, -- this replaces the Special_fzf_lua function
	fzf_opts = {
		['--layout'] = 'reverse', --prefereed
		-- ['--layout'] = 'reverse-list',
		['--info'] = 'right',
		['--ansi'] = '',
		['--no-multi'] = '', -- fallback
		-- ['--tac'] = '' -- reverse the order of the input
		-- ['--with-nth'] = '2..',
		-- ['--delimiter'] = '\\s',
		-- ['--tiebreak'] = 'begin,index',
	},
	files = {
		-- previewer = "bat",
		prompt = "  Files   ",
		cwd_prompt = false,
		cmd = "fd --type f -H --exclude='.git'",
		-- formatter = "path.filename_first",
		fzf_opts = { ["--tiebreak"] = "end" },
		-- cwd_header = true,
		-- cwd = helpers.git_root(),
		-- cwd = vim.loop.cwd(),
		actions = {
			["ctrl-q"] = actions.files_sel_to_qf, -- leaving this files_sel_to_qf option alone on seems to be working
		}
	},
	oldfiles = {
		-- prompt = "Find Recent Files 🔍",
		-- prompt = "    ",
		prompt = "  Recent Files   ",
		cwd = vim.loop.cwd(),
		-- formatter = "path.filename_first",
		cwd_header = true,
		cwd_only = true,
		stat_file = true,
		include_current_session = true
	},
	keymaps = {
		-- prompt = "Find Keymaps 🔍",
		-- prompt = "    ",
		prompt = "  Keymaps   ",
		winopts = { preview = { hidden = 'hidden' } }
	},
	buffers = {
		-- prompt = "Find Open Buffers 🔍",
		-- prompt = "    ",
		prompt = "  Buffers   ",
		no_action_zz = true,
        path_shorten   = true, -- defaults to 1 when true
		formatter = false,
		-- formatter = "path.filename_first", -- doesn't work well here
		cwd_only = true,
		actions = {
			["ctrl-d"] = false,
			["ctrl-x"] = { fn = actions.buf_del, reload = true }
		}
	},
	diagnostics = {
		-- prompt = "Find Diagnostics 🔍",
		-- prompt = "    ",
		prompt = "  Diagnostics   ",
		cwd_only = true,
		git_icons = true,
		path_shorten = true,
		file_icons = false
		-- severity_only = 1 -- adjust per keymap, default is commented off
	},
	lsp = {
		cwd_only = true,
		async_or_timeout = true, -- default => 5000
		git_icons = true,
		code_actions = {
			-- prompt = "Code Actions 🔍",
			-- prompt = "    ",
			prompt = "  Code Actions   ",
			previewer = 'codeaction_native',
			preview_pager = "delta --side-by-side --width=$FZF_PREVIEW_COLUMNS --hunk-header-style='omit' --file-style='omit'",
		},
		symbols = {
			symbol_icons = kind
		}
	},
	grep = {
		-- prompt = "Search String in CWD 🔍",
		-- prompt = "    ",
		prompt = "  Grep String   ",
		-- formatter = "path.filename_first",
		no_header = false,
		no_header_i = false,
		-- change color of the file path in the matched results
		-- rg_opts = "--column --line-number --no-heading --color=always --colors='path:fg:white' --colors='match:style:bold' --smart-case --max-columns=4096 -e", -- my default
		-- rg_opts = "--column --line-number --trim -p --line-buffered --no-heading --color=auto --colors='path:fg:white' --colors='match:style:bold' --smart-case --max-columns=4096 -e",
		-- rg_opts = [[--hidden --column --line-number --no-heading]]
		-- 	.. [[ --color=always --smart-case -g "!.git" -e]],
		actions = {
			["ctrl-q"] = actions.files_sel_to_qf, -- leaving this files_sel_to_qf option alone on seems to be working
		},
		-- trying out the plugin author's config for grep
		debug = false,
		rg_glob = true,
		rg_opts = [[--hidden --column --line-number --no-heading]]
			.. [[ --color=always --smart-case -g "!.git" -e]],
		fzf_opts = {
			["--history"] = fzf_lua.path.join({ vim.fn.stdpath("data"), "fzf_search_hist" }),
		},
	},
	highlights = {
		-- prompt = "    ",
		prompt = "  Highlights   ",
	},
	marks = {
		-- prompt = "    ",
		prompt = "  Marks   ",
	},
	search_history = {
		-- prompt = "    ",
		prompt = "  Search History   ",
	},
	command_history = {
		-- prompt = "    ",
		prompt = "  Command History   ",
	},
	jumps = {
		-- prompt = "    ",
		prompt = "  Jump List   ",
	},
	registers = {
		-- prompt = "    ",
		prompt = "  Registers   ",
	},
	-- help_tags = {
	--     -- prompt = "    ",
	--     prompt = "  Help Tags   ",
	-- },
	git = {
		status = {
			prompt = " Git Status   ",
			-- formatter = "path.filename_first",
			actions = {
				["right"]   = false,
				["left"]    = false,
				["ctrl-x"]  = false,
				["ctrl-s"]  = false,
			}
		}
	}

})
```

### Describe the bug / steps to reproduce

I normally use vertical layouts for grep. They've stopped working and I'm not sure if this a potential bug or an issue with my config. Any feedback is greatly appreciated.

Preview options for grep:
local vertical_preview = {
	layout = "vertical",
	vertical = "up:75%"
}

Grep Keymaps:
local keymap = vim.keymap
local opts = { silent = true, noremap = true }
local ok, fzf_lua = pcall(require, "fzf-lua")

opts.desc = "Find String within the CWD"
keymap.set("n", "<leader>fs", function()
    pcall(require, "nvim-treesitter")
    return fzf_lua.grep_project({ winopts = { title = "   Find String 🔤   ", preview = vertical_preview } })
end, opts)

opts.desc = "Find String in Current Buffer"
keymap.set("n", "<leader>fw", function()
    -- return require("fzf-lua").grep_curbuf({ winopts = { title = "   Find in Current Buffer 🔤   ", preview = vertical_preview } })
    return fzf_lua.grep_curbuf({ winopts = { title = "   Find in Current Buffer 🔤   ", preview = vertical_preview } })
end, opts)

It now results in the following:
![fzf-lua-error](https://github.com/ibhagwan/fzf-lua/assets/22212587/e7930043-43c3-48d6-80c4-fdef3f78ad37)

**Comment by ibhagwan** [comment]
I’ll check, this is most likely related to https://github.com/ibhagwan/fzf-lua/commit/235119b859d1d3dc136a5dbfd24b626b5af72130.

**Comment by ibhagwan** [comment]
I can't seem to reproduce this, I want to see which line of code is causing this error, would you be able to post the full stack trace from `:messages`?

**Comment by Emille1723** [comment]
messages:
E5108: Error executing lua: ...l/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/grep.lua:140: ...config/local/share/nvim/lazy/fzf-lua/lua/fzf-lua/win.lua:571: 'height' key must be a positive Integer
stack traceback:
	[C]: in function 'fzf_exec'
	...l/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/grep.lua:140: in function <...l/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/grep.lua:95>


I get the same error when I add a height value of 1 or .9

**Comment by ibhagwan** [comment]
I'm not 100% sure as I wasn't able to replicate your issue exactly but hopefully https://github.com/ibhagwan/fzf-lua/commit/c71aec07187e7a174f2664fe5a97a5da78940ea5 solves the issue.

Can you let me know?

**Comment by Emille1723** [comment]
It's working now
Thanks a lot for your help and the work you continue to do on this plugin!

**Comment by ibhagwan** [comment]
Ty for the update @Emille1723!
