### ISSUE TITLE
Bug: fzflua builtin is not working properly

### ISSUE THREAD

**Issue by wingedseraph** [ibhagwan/fzf-lua#1291]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

windows 11 wsl

### Shell

fish

### Neovim version (`nvim --version`)

nvim 0.10

### Fzf version (`fzf --version`)

0.53.0 (c4a9ccd)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

-i  --reverse --cycle --margin=2 --preview-window noborder --prompt="> " --marker=">" --pointer="◆" --scrollbar="" --layout=reverse --no-preview --bind=Tab:down,ctrl-space:to ggle --color=fg:#d0d0d0,fg+:#d0d0d0,bg:-1,bg+:-1 --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00 --color=prompt:#d7005f,spinner:-1,pointer:-1,header:#87afaf --colo r=border:-1,label:#aeaeae,query:#d9d9d9

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({
				winopts = {
					width = 1,
					height = 1,
					border = "none",
				},
			})
```

### Describe the bug / steps to reproduce

hey, just recently stopped working any functions from the list of builtin, I tried different things and nothing helps, and as I see that there is no problem with mini.sh so it is somewhere in my configuration, but I still hope that you can tell me what could be the problem?

https://github.com/ibhagwan/fzf-lua/assets/143389903/c6c3cc1f-1d86-4ed8-8f90-bd9e83c6f811

**Comment by ibhagwan** [comment]
Very strange indeed but don’t worry we’ll get to the bottom of it.

First can you try with an empty setup, so we can rule out any fzf-lua configuration option?
```lua
require("fzf-lua").setup({})
```

> hey, just recently stopped working

Do you recall what happened to make it stop working? Was it an fzf-lua update?
Can you pin fzf lua to commit https://github.com/ibhagwan/fzf-lua/commit/5c404c613832e39c5caf8753d1b099d7abd1f1b8 and let me know if it works (I’m suspicious of this commit https://github.com/ibhagwan/fzf-lua/commit/235119b859d1d3dc136a5dbfd24b626b5af72130)?

Can you post a link to your neovim config so I can try and reproduce this locally?

**Comment by wingedseraph** [comment]
> First can you try with an empty setup, so we can rule out any fzf-lua configuration option?

an empty setup was tried - nothing changed
> Can you pin fzf lua to commit https://github.com/ibhagwan/fzf-lua/commit/5c404c613832e39c5caf8753d1b099d7abd1f1b8 and let me know if it works (I’m suspicious of this commit https://github.com/ibhagwan/fzf-lua/commit/235119b859d1d3dc136a5dbfd24b626b5af72130)?

as for commits, I've tried them too, tried variants since May - no change (5c404c6, 235119b - double-checked no change)

> Do you recall what happened to make it stop working? Was it an fzf-lua update?


unfortunately I can't even imagine what could have done such a thing to break the plugin. the problem is that 
I use fzflua -function- 90% of the time and only sometimes the builtin menu with function selection, and I just didn't notice the problem right away

neovim config - https://github.com/wingedseraph/nvim  
in this variation of the configuration I disabled all plugins except lazy and fzf-lua double-checked that everything was also not working and uploaded it to github

(my configuration may be a messy web sorry about that, but I've tried to disable anything that might interfere with a quick look at the problem)

**Comment by wingedseraph** [comment]
error found. in my config lua/misc/save_cursor_location.lua breaks fzflua behavior
https://github.com/wingedseraph/nvim/blob/main/lua/misc/save_cursor_location.lua

**Comment by ibhagwan** [comment]
> error found. in my config lua/misc/save_cursor_location.lua breaks fzflua behavior https://github.com/wingedseraph/nvim/blob/main/lua/misc/save_cursor_location.lua

Ty @wingedseraph! saved me some time I was just debugging your config locally lol
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/a796fe26-a89f-410e-8452-879f016c6e37)
