### ISSUE TITLE
Bug: Error because textDocument/documentHighlight isn't supported in the current buffer

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#1294]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Fedora 40

### Shell

fish

### Neovim version (`nvim --version`)

v0.11.0-dev-286+g38a1d41ac

### Fzf version (`fzf --version`)

0.44.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=fg:#f8f8f2,bg:#0e1419,hl:#e11299,fg+:#f8f8f2,bg+:#44475a,hl+:#e11299,info:#f1fa8c,prompt:#5 0fa7b,pointer:#ff79c6,marker:#ff79c6,spinner:#a4ffff,header:#6272a4 --cycle

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  fzf_opts = {
    ['--info'] = 'default',
    ['--layout'] = 'reverse-list',
  },
  global_git_icons = false,
  files = {
    winopts = {
      preview = { hidden = 'hidden' },
    },
  },
  oldfiles = {
    include_current_session = true,
    winopts = { preview = { hidden = 'hidden' } },
  },
})
```

### Describe the bug / steps to reproduce

During the last couple of days I've seen the error below pop up once in a while when using the files picker. It doesn't always happen, but lately I've been working on a simple Rust project.

![image](https://github.com/ibhagwan/fzf-lua/assets/62502207/3b5fc4c8-1eb5-4f10-89d4-1aee75471a8a)

**Comment by ibhagwan** [comment]
This seems to me to be coming from an auto command making a request to `textDocument/documentHighlight` which happens on `BufEnter` triggered by the `vim.cmd` from fzf-lua’s buf switch, fzf-lua does not make such request, ever.

**Comment by MariaSolOs** [comment]
Okay, I will explore my config and other plugins! Sorry for the noisy issue.

**Comment by ibhagwan** [comment]
> Okay, I will explore my config and other plugins! Sorry for the noisy issue.

Did you find the culprit? We can leave this open until you have a solution, I’m still doubtful it’s fzf-lua but you never know.

**Comment by MariaSolOs** [comment]
> Did you find the culprit? We can leave this open until you have a solution, I’m still doubtful it’s fzf-lua but you never know.

I'm pretty sure the issue is coming from `ccc.nvim`. I tried disabling it for now to validate my hypothesis.

**Comment by ibhagwan** [comment]
> > Did you find the culprit? We can leave this open until you have a solution, I’m still doubtful it’s fzf-lua but you never know.
> 
> I'm pretty sure the issue is coming from `ccc.nvim`. I tried disabling it for now to validate my hypothesis.

Nice find, ty for the update @MariaSolOs!

**Comment by MariaSolOs** [comment]
Ehhh so after investigating this further it seems to be caused by an autocommand I wrote 😅 Yet I'm quite confused about the error...

I have the following in my `on_attach` function:
```lua
   if client.supports_method(methods.textDocument_documentHighlight) then
        local under_cursor_highlights_group =
            vim.api.nvim_create_augroup('mariasolos/cursor_highlights', { clear = false })
        vim.api.nvim_create_autocmd({ 'CursorHold', 'InsertLeave', 'BufEnter' }, {
            group = under_cursor_highlights_group,
            desc = 'Highlight references under the cursor',
            buffer = bufnr,
            callback = vim.lsp.buf.document_highlight,
        })
        vim.api.nvim_create_autocmd({ 'CursorMoved', 'InsertEnter', 'BufLeave' }, {
            group = under_cursor_highlights_group,
            desc = 'Clear highlight references',
            buffer = bufnr,
            callback = vim.lsp.buf.clear_references,
        })
    end
```

And so the error message seems to indicate that somehow there's no client supporting `textDocument/documentHighlight` in the 1st callback, despite the outer if-check...

**Comment by ibhagwan** [comment]
> And so the error message seems to indicate that somehow there's no client supporting `textDocument/documentHighlight` in the 1st callback, despite the outer if-check...

Maybe an upstream bug? Can you check which buffer is this failing on? Would be interesting to see if this is triggered by one of your existing buffers or an fzf-lua buffer (although the preview shouldn’t trigger LSP attach).

**Comment by MariaSolOs** [comment]
> Maybe an upstream bug? Can you check which buffer is this failing on? Would be interesting to see if this is triggered by one of your existing buffers or an fzf-lua buffer (although the preview shouldn’t trigger LSP attach).

Yep I'll try adding extra logging there to have more information when I see the bug. It doesn't always happen, I would say it happen < 5% of the times I use the Files/Recent Files picker.

**Comment by ibhagwan** [comment]
> Yep I'll try adding extra logging there to have more information when I see the bug. It doesn't always happen, I would say it happen < 5% of the times I use the Files/Recent Files picker.

Does it happen when you open the picker (most likely from preview) or after selecting the file (I.e. from the edit action).

**Comment by MariaSolOs** [comment]
> Does it happen when you open the picker (most likely from preview) or after selecting the file (I.e. from the edit action)?

It always happen after selecting the entry, so I don't think it's the preview.

**Comment by ibhagwan** [comment]
> > Does it happen when you open the picker (most likely from preview) or after selecting the file (I.e. from the edit action)?
> 
> It always happen after selecting the entry, so I don't think it's the preview.

Than most likely this happens due to the `BufEnter` event of the selected entry.
