### ISSUE TITLE
Bug: fuzzy finder (`lua require("fzf-lua").grep_curbuf()`) search by line number, not text only

### ISSUE THREAD

**Issue by damanis** [ibhagwan/fzf-lua#1302]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

0.10.0

### Fzf version (`fzf --version`)

0.53.0 (c4a9ccd)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
My config configures preview option only.
```

### Describe the bug / steps to reproduce

Run `lua require("fzf-lua").grep_curbuf()` in any file with more than 15 lines, fuzzy find is active. Type `12` — line number 12 shown in output even it does not have chars `1` and `2`. Switch to regex mode — works properly.
Lines number shown in both modes.

**Comment by ibhagwan** [comment]
That’s by design so you can search line numbers too, if you wish to exclude lines add `['--nth']='2..’` to fzf_opts, try it with `:FzfLua grep_curbuf fzf_opts.--nth=2..`

**Comment by damanis** [comment]
OK. So, the is no issue. Thank you.
