### ISSUE TITLE
Bug: fail with error: Unknown option 'winfixbuf'

### ISSUE THREAD

**Issue by mangelozzi** [ibhagwan/fzf-lua#1303]
# Context

It broke at this commit:
```
commit 0c4458b0f0d12970e54c8cd7c5ad60676edcf764 (HEAD -> main)
Author: bhagwan <bhagwan@disroot.org>
Date:   Fri May 24 08:37:14 2024 -0400

    feat: provide warning for ’winfixbuf’ (closes #1214)
```

This is the commit before that works:
```
commit b442569ab827f72e344236c598b02cb9dc754e9f (HEAD -> main)
Author: bhagwan <bhagwan@disroot.org>
Date:   Wed May 22 22:06:12 2024 -0400

    fix(previewer): term buffer title (closes #1213)
```

### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

22.04.2-Ubuntu 

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.0-dev-fcfc87c Build type: RelWithDebInfo LuaJIT 2.1.1695266395 Run "nvim -V1 -v" for more info

### Fzf version (`fzf --version`)

0.36.0 (2023011)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"
```

### Describe the bug / steps to reproduce

1. `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"`
2. ` :FzfLua`
3.  Select files
4. Select a file
5. Instead of opening the file you will get the error:
```
[Fzf-lua] fn_selected threw an error: ...m/site/pack/vendor/start/fzf-lua/lua/fzf-lua/actions.lua:138: Unknown option 'winfixbuf'
stack traceback:
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:235: in function <...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:229>
^I[C]: in function '__index'
^I...m/site/pack/vendor/start/fzf-lua/lua/fzf-lua/actions.lua:138: in function 'vimcmd_file'
^I...m/site/pack/vendor/start/fzf-lua/lua/fzf-lua/actions.lua:190: in function 'action'
^I...m/site/pack/vendor/start/fzf-lua/lua/fzf-lua/actions.lua:88: in function 'act'
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:148: in function 'fn_selected'
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:228: in function <...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:227>
^I[C]: in function 'xpcall'
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:227: in function <...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:221>
```

**Comment by ibhagwan** [comment]
Update the the 0.10 release, you’re using nightly which didn’t yet include the `winfixbuf` commit.

**Comment by ibhagwan** [comment]
@mangelozzi, https://github.com/ibhagwan/fzf-lua/commit/023b95078f9cc28ce67d7a7a6b4ea1bc7cfa488d should solve this issue regardless.
