### ISSUE TITLE
Bug: buffers when default.formatter=path.filename_first doesn't open file correctly if in root(project root) directory

### ISSUE THREAD

**Issue by kronolynx** [ibhagwan/fzf-lua#1304]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.52.1 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

﻿﻿--color=bg+:#414559,bg:#303446,spinner:#f2d5cf,hl:#e78284     --color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf     --color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require "fzf-lua".setup {
  defaults = {
    git_icons = false,
    formatter = "path.filename_first",
  }
}
```

### Describe the bug / steps to reproduce

When `defaults.formatter = "path.filename_first"` switching opened buffers using `:FzfLua buffers` doesn't open files that are at the the root of the current working directory, in the screenshot is not possible to switch to `README.md` or `OPTIONS.md`

<img width="610" alt="Screenshot 2024-06-27 at 14 30 52" src="https://github.com/ibhagwan/fzf-lua/assets/6961824/943934eb-4665-4985-bee7-00fa8af8ac94">

the bug is similar to #1265
Steps to reproduce:

1. Open two or more files (one of them at the root of the current working directory)
2. run `:FzfLua buffers`
3. try to switch to the file at the root

**Comment by ibhagwan** [comment]
Ty for the report @kronolynx, should work as expected with https://github.com/ibhagwan/fzf-lua/commit/41ea49cfc1b3f0586753bbeb7850474f28dc22cf.

**Comment by jellydn** [comment]
Hi @ibhagwan This https://github.com/ibhagwan/fzf-lua/commit/41ea49cfc1b3f0586753bbeb7850474f28dc22cf is fixing for v1 but it's broken on v2.

```lua
defaults = {
        -- VS Code style, v2 is broken, use v1
        -- formatter = { "path.filename_first", 2 },
        formatter = { "path.filename_first" },
      },
```

<img width="1698" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/870029/640ba3a7-7d6c-477d-ae86-a9ab48fc03f2">

**Comment by ibhagwan** [comment]
Ty @jellydn, try with https://github.com/ibhagwan/fzf-lua/issues/1304, should work as expected.

**Comment by jellydn** [comment]
Great. Thanks @ibhagwan 👏
