### ISSUE TITLE
Feature:  Support transparent gutter via highlight group

### ISSUE THREAD

**Issue by scottmckendry** [ibhagwan/fzf-lua#1306]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I'm currently in the process of adding support for Fzf-lua to my colorscheme and noticed that setting the `bg` property of `FzfLuaFzfGutter` to `"NONE"` does not make it transparent. Setting it to a solid color works fine, however.

Is this something that could be supported in the future?

**Comment by ibhagwan** [comment]
Fzf runs in a neovim terminal, the gutter color needs to be translated into an ansi escape sequence and `NONE` has no color, while I could translate it manually to `-1` it would be hacky.

Why don’t you set your `fzf_colors = { ['gutter’] = '-1' }`, if you wanted to do so without calling setup (e.g. in a color scheme) you can set `vim.g.fzf_colors`:
https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#fzf-colors

**Comment by scottmckendry** [comment]
Thanks! I think I can make that work with the vim.g variable.

**Comment by ramojus** [comment]
This doesn't seem to be working anymore. Even if I set this color via command with `:lua require'fzf-lua'.files({ hls={["gutter"] = "-1"} })`, the gutter is still not transparent:
![image](https://github.com/user-attachments/assets/3250e3db-bdda-43ba-8aaf-75af6da07c72)

**Comment by ibhagwan** [comment]
> This doesn't seem to be working anymore. Even if I set this color via command with `:lua require'fzf-lua'.files({ hls={["gutter"] = "-1"} })`, the gutter is still not transparent: ![image](https://private-user-images.githubusercontent.com/41536253/399181957-3250e3db-bdda-43ba-8aaf-75af6da07c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MDA5NDMsIm5iZiI6MTczNTUwMDY0MywicGF0aCI6Ii80MTUzNjI1My8zOTkxODE5NTctMzI1MGUzZGItYmRkYS00M2JhLThhYWYtNzVhZjZkYTA3YzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDE5MzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMzljNzc1MDkzZjcwZjg0MmIxMmRjN2U0ZjE4MTc2MGE1ZTBkYzFhZTk5YTQ1MzYyM2E1ZjM2MjEyMDBlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AQlzLXB_RI4QtgK0nl43NBftx5qhaKwsr8c5ECJ-vJM)

Because you’re setting it in the wrong place, gutter should be under `fzf_colors`.

**Comment by ibhagwan** [comment]
Set the first index to true and you’ll get both the generated theme and override:
```lua
require('fzf-lua').setup {
    fzf_colors = {
        true,  --  this
        ["gutter"] = "-1",
    }
}
```

This is mentioned in the fzf_colors part of the README under the default options, I should probably add it at the bottom fzf_colors part of the README too.

**Comment by ramojus** [comment]
That's nicer, thanks for your help!
I'm still a bit hesitant to use this. Would you perhaps be interested in a PR that would allow to just use a highlight group with `"NONE"` value?

**Comment by ibhagwan** [comment]
> That's nicer, thanks for your help! I'm still a bit hesitant to use this. Would you perhaps be interested in a PR that would allow to just use a highlight group with `"NONE"` value?

I’m thinking a better option, if the resulting color is none set it to `-1` (just for fzf_colors).
