### ISSUE TITLE
Bug: Opening a single file when multiple files are shown still opens them in QuickFix. 

### ISSUE THREAD

**Issue by guzman109** [ibhagwan/fzf-lua#1308]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

PopOS

### Shell

zsh

### Neovim version (`nvim --version`)

v0.10.0

### Fzf version (`fzf --version`)

sk 0.10.4

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
{
    "ibhagwan/fzf-lua",
    opts = {
      defaults = require("fzf-lua.profiles.skim"),
      winopts = {
        preview = {
          default = "bat",
          scrollbar = "false",
        },
      },
      fzf_opts = {
        ["--no-scrollbar"] = false,
      },
      actions = {
        ["default"] = actions.file_edit,
      },
    },
  },
```

### Describe the bug / steps to reproduce

I'm using LazyVim and set it up to use fzf-lua. When I go to fzf-lua to open a file and multiple files are shown, they still go to the QuickFix even though I set the option to open the single file I select either wise. Also, sometimes the file is not shown in the QuickFix.

Using LazyVim:
<space>ff (Open fzf-lua navigator)
<tab> to go a file in a directory with multiple files
<enter> selected file to open.

**Comment by ibhagwan** [comment]
This is a config issue:
```lua
      actions = {
        files = {
          ["default"] = actions.file_edit,
        }
      },
```

**Comment by guzman109** [comment]
Ah ok, just made the change and it now it just opens all the files leading up to the file I want to open only.

![Screenshot from 2024-06-28 10-31-13](https://github.com/ibhagwan/fzf-lua/assets/42706936/ce4492d5-e4d5-4b46-aaba-ea40e7f1f7c5)
![Screenshot from 2024-06-28 10-31-00](https://github.com/ibhagwan/fzf-lua/assets/42706936/7d5fb61e-928a-47cb-a35e-e3de51a1a1cd)

**Comment by ibhagwan** [comment]
> Ah ok, just made the change and it now it just opens alot of files and not just the one I want to open only.

In the screenshot I see you’ve marked these to open, why are you marking the files if you do not want them to open?

If you want to disable marking add `--no-multi` to your fzf_opts, otherwise marking files to open and then having them open is expected behavior.

**Comment by ibhagwan** [comment]
I think you’re “scrolling” with tab (which is multi-select), you’re marking the files not scrolling, use arrows or `ctrl-j|k` to scroll, or change the default ‘tab|shift-tab` binds to `up|down`.

**Comment by guzman109** [comment]
Yep, that was the issue. Thanks for your help
