### ISSUE TITLE
Direct lua callbacks in the mappings documentation

### ISSUE THREAD

**Issue by shmerl** [ibhagwan/fzf-lua#1310]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I think this kind of example can be rewritten in more pure lua:

```
vim.keymap.set("n", "<c-P>", "<cmd>lua require('fzf-lua').files()<CR>", { silent = true })
```

as

```
vim.keymap.set("n", "<c-P>", function() require('fzf-lua').files() end, { silent = true })
```

Since `vim.keymap.set` supports Lua functions in `rhs` parameter.

**Comment by ibhagwan** [comment]
README was written before this was possible with neovim 0.5, can be simplified even more:
```lua

vim.keymap.set("n", "<c-P>", require('fzf-lua').files, { silent = true })
```

**Comment by shmerl** [comment]
A bit unrelated, but what's the point of `silent=true`? Supposedly it's for not echoing the mapping in the command line, but I don't get anything even without setting `silent=true`. Am I missing something or new default in neovim is `silent=true`?

**Comment by ibhagwan** [comment]
> A bit unrelated, but what's the point of `silent=true`? Supposedly it's for not echoing the mapping in the command line, but I don't get anything even without setting `silent=true`. Am I missing something or the default in neovim for `vim.keymap.set` is `silent=true`?

I’m not 100% sure but I think lua callback or `<cmd>` commands are already silent, it would probably make a difference if you mapped rhs to `:lua …`.

**Comment by shmerl** [comment]
Ah, yes. You are right - just tested a mapping with `:` instead of `<Cmd>` or callback and it's indeed echoing it unless silent is added.
