### ISSUE TITLE
Bug: multiline = 1 causes all entries to be selected when using :FzfLua git_commits

### ISSUE THREAD

**Issue by brphilly** [ibhagwan/fzf-lua#1315]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.53.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--cycle --layout=reverse --bind ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    defaults = { multiline = 1 },
})
```

### Describe the bug / steps to reproduce

`:FzfLua git_commits` with `multiline = 1` in the defaults table has a bug similar to #1252 except this time it seems like all git commits entries are selected at once and ctrl-n or ctrl-p don't do anything.

**Comment by ibhagwan** [comment]
ty @brphilly, multiline needed to be disabled for all git pikcers that pipe shell commands directly, that inclues `bcommits`, `tags` and `branches`, should be fixed with https://github.com/ibhagwan/fzf-lua/commit/24a1616df5f27d1286e5113cf176693de4111d21.

**Comment by brphilly** [comment]
Thanks for the fix and the great plugin!
