### ISSUE TITLE
Bug: lsp_definitions and lsp_references ignore_current_line weird behavior

### ISSUE THREAD

**Issue by pBorak** [ibhagwan/fzf-lua#1316]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Macos Sonoma 14.5

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.52.1 (6432f00)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

 --highlight-line   --info=inline-right   --ansi   --layout=reverse   --border=none   --color=bg+:#2d3f76   --color=bg:#080808   --color=border:#589ed7   --color=fg:#c8d3f5   --color=gutter:#080808   --color=header:#ff966c   --color=hl+:#65bcff   --color=hl:#65bcff   --color=info:#545c7 e   --color=marker:#ff007c   --color=pointer:#ff007c   --color=prompt:#65bcff   --color=query:#c8d3f5:regular   --color=scrollbar:#589ed7   --color=separator:#ff966c   --color=spinner:#ff007c

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Describe the bug / steps to reproduce

When using either `FzfLua lsp_definitions ignore_current_line=true` or `FzfLua lsp_references ignore_current_line=true`, the LSP fails to find the reference or definition when the result is on the same line number but in a different file. Moving the method one line above / below solves the issue so I guess it has to be associated to line numbers comparison.

Please refer to the video below for reproduction.

```lua
-- test.lua
local M = {}

function M.method_referenced_in_different_file_in_the_same_line() end

return M
```

```lua
-- test2.lua
local test = require('test')

local reference_that_should_be_visible = test.method_referenced_in_different_file_in_the_same_line()
```

https://github.com/ibhagwan/fzf-lua/assets/45797239/ed55c2d8-e8d6-46db-aa4f-f57d09d7a136

Weirdly enough, for the Lua LSP, I can reproduce the issue only with references. With other LSPs, such as Ruby's Solargraph, the issue affects both definitions and references.

**Comment by ibhagwan** [comment]
Ty for reporting @pBorak, https://github.com/ibhagwan/fzf-lua/commit/3b91c1a471160bd8620bdca8f18743d954994daa should fix the "same line different file" issue and hopefully also fix the other LSP's such as Ruby, lmk?

**Comment by ibhagwan** [comment]
> Weirdly enough, for the Lua LSP, I can reproduce the issue only with references

`lua_ls` apparently sends a different response for definitions where the line is at `range.start.line` for references, and `targetRange.start.line` for definitions/implementations, I suspect Ruby (and the others you tested) all use  `range.start.line`.


If my assumptions are correct https://github.com/ibhagwan/fzf-lua/commit/3b91c1a471160bd8620bdca8f18743d954994daa should fix all LSPs.

**Comment by pBorak** [comment]
@ibhagwan https://github.com/ibhagwan/fzf-lua/commit/3b91c1a471160bd8620bdca8f18743d954994daa indeed fixed the issue for all LSPs I tested. Stellar work as always, thank you so much ❤️
