### ISSUE TITLE
Feature: set the background color for the preview window

### ISSUE THREAD

**Issue by qbnil** [ibhagwan/fzf-lua#1318]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Hey, i was looking for a way to change the bg color of the preview window. Looked up your docs and figured out that there is a hl field for that:
![image](https://github.com/ibhagwan/fzf-lua/assets/130576530/798d5378-21af-4426-a8ad-5300f29f94e9)
but it won't work, even tho the title color works for some reason. I wanted to set the background to be the same color as the search window on the left:
![image](https://github.com/ibhagwan/fzf-lua/assets/130576530/3209791b-82a0-4c10-933b-331b09cd6a20)
This is the way i do it right now in my rose-pine theme config:
![image](https://github.com/ibhagwan/fzf-lua/assets/130576530/a92f8b2b-eb3a-49ee-a430-92646e9adf3b)

**Comment by ibhagwan** [comment]
This is a configuration issue, is something overriding your hl group?

This works as expected when both linking the group or manually specifying one via `hls.preview_normal`:
![IMG_2242](https://github.com/ibhagwan/fzf-lua/assets/59988195/88ab2b9c-8d63-4dbb-859e-5edd8e685592)
![IMG_2241](https://github.com/ibhagwan/fzf-lua/assets/59988195/a929643c-c5f1-4fd2-bc09-cfc4d0e430c6)

**Comment by qbnil** [comment]
there should be nothing that overrides it, that's weird, i can send my rose-pine config, probably it causes the issue

**Comment by qbnil** [comment]
![image](https://github.com/ibhagwan/fzf-lua/assets/130576530/0cac4151-4638-4525-aaae-12e2e7c0e6ba)
with the second command it starts to work

**Comment by qbnil** [comment]
i just wanted to do it here in the highlight_groups section in rose-pine conf like so:
        highlight_groups = {
            ['@function.builtin.lua'] = { italic = false },
            ['@lsp.type.comment'] = { italic = true },
            ['@lsp.typemod.function.defaultLibrary.lua'] = { italic = false },
            Comment = { italic = true },
            DiagnosticUnnecessary = { italic = false },
            TabLine = { bg = 'none' },
            TabLineSel = { bg = 'none' },
            TabLineFill = { bg = 'none' },
            StatusLine = { fg = '#ffffff', bg = '#2c2a2c' },
            StatusLineNC = { link = "StatusLine" },
            NormalFloat = { bg = '#272627' },
            FloatBorder = { bg = '#272627' },
            FzfLuaTitle = { bg = '#272627' },
            FzfLuaPreviewTitle = { bg = '#262626' },
            FzfLuaPreviewNormal = { bg = '#262626' },
        }

**Comment by ibhagwan** [comment]
It’s either a configuration issue or a bug, can you check if the highlight is defined when you run `:FzfLua highlights`? Can you try adding a `fg` color and see if that works?

**Comment by qbnil** [comment]
alr, i just got rid of transparency being enabled in my rose-pine config and everything started to work normally, looks like a bug to me

**Comment by ibhagwan** [comment]
> alr, i just got rid of transparency being enabled in my rose-pine config and everything started to work normally, looks like a bug to me

 It’s not a bug, your bg is being overridden probably due to the transparency you enabled.

In any event this isn’t an fzf-lua issue.

**Comment by qbnil** [comment]
Sure, it's not, messed it up somewhere myself

**Comment by ibhagwan** [comment]
> Sure, it's not, messed it up somewhere myself

As I mentioned, explore your highlight groups `:FzfLua highlights`, they’re most likely not what you think or it would have worked.

**Comment by ibhagwan** [comment]
You also didn’t post your configuration, I suspect you overrode `hls.preview_normal` in your setup.

**Comment by qbnil** [comment]
return {
    'asilvam133/rose-pine.nvim',
    name = 'rose-pine',
    lazy = false,
    opts = {
        styles = {
            bold = true,
            italic = false,
            -- transparency = true,
        },
        highlight_groups = {
            ['@function.builtin.lua'] = { italic = false },
            ['@lsp.type.comment'] = { italic = true },
            ['@lsp.typemod.function.defaultLibrary.lua'] = { italic = false },
            Comment = { italic = true },
            DiagnosticUnnecessary = { italic = false },
            TabLine = { bg = 'none' },
            TabLineSel = { bg = 'none' },
            TabLineFill = { bg = 'none' },
            StatusLine = { fg = '#ffffff', bg = '#2c2a2c' },
            StatusLineNC = { link = "StatusLine" },
            NormalFloat = { bg = '#272627' },
            FloatBorder = { bg = '#272627' },
            FzfLuaTitle = { bg = '#272627' },
            FzfLuaPreviewTitle = { bg = '#262626' },
            FzfLuaPreviewNormal = { bg = '#5E5757' },
        },
    },
    config = function(_, opts)
        require('rose-pine').setup(opts)
        vim.cmd('colorscheme rose-pine-main')
        vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#272727' })
        vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#525252' })
    end,
}
this is the config as for now
