### ISSUE TITLE
The position of the preview window is wrong when using latest neovim nightly

### ISSUE THREAD

**Issue by uga-rosa** [ibhagwan/fzf-lua#132]
![image](https://user-images.githubusercontent.com/82267684/133122725-6547b165-fe52-49d3-9ace-e304ff2974bf.png)

I haven't changed the settings, but the position has gone wrong.

**Comment by ibhagwan** [comment]
I haven’t done any changes to this code, what is your preview layout set to?
Also run these and let me know the result?
```lua
:lua print(vim.o.lines, vim.o.columns)
```

**Comment by ibhagwan** [comment]
Also, what happened with empty `setup` (or at least empty `winopts`)? And what happens when you press `F2` - does the preview expand to max size properly?

**Comment by uga-rosa** [comment]
```lua
:lua print(vim.o.lines, vim.o.columns)
43 188
```

I didn't originally set up `winopts`. `F2` seems to be functioning correctly.

![image](https://user-images.githubusercontent.com/82267684/133129533-5356a07b-ec5b-4223-be9d-71c32607b195.png)

**Comment by uga-rosa** [comment]
I don't remember changing that setting... I wonder why.

**Comment by ibhagwan** [comment]
Just tried with the same lines/columns as yours (43,188) with `preview_horizontal  = 'right:60%'`:

![screenshot-1631555038](https://user-images.githubusercontent.com/59988195/133131813-a6531773-c50a-4b73-923e-9bdbbd555f9a.png)

What are your `winopts`? maybe something there messed it up (height, width, row, col)?

**Comment by uga-rosa** [comment]
Even if you change the `winopts,` the relative positions of the two windows will remain misaligned.
For example, if I set all of them to 0.5, it will look like this.

![image](https://user-images.githubusercontent.com/82267684/133132934-1c9016df-8422-4eb4-8a11-32c4dd00be6d.png)

**Comment by ibhagwan** [comment]
Seems like the values are correct just the `anchor` parameter is in the wrong place, I'm pretty sure this has something to do with your setting that gets the code confused, what are your `preview_horizontal`, `preview_vertical` and `preview_layout` set to?

**Comment by uga-rosa** [comment]
None of these are set. Is it referring to any global variables?

This is my fzf-lua config
```lua
require("fzf-lua").setup({
  previewers = {
    builtin = {
      title = false,
      keymap = {
        page_up = "<C-u>",
        page_down = "<C-d>",
        page_reset = "<C-g>",
      },
    },
  },

  files = {
    cmd = "fd -t f",
    actions = {
      ["default"] = actions.file_edit,
      ["ctrl-x"] = actions.file_split,
      ["ctrl-v"] = actions.file_vsplit,
      ["ctrl-t"] = actions.file_tabedit,
    },
  },

  oldfiles = {
    actions = {
      ["default"] = actions.file_edit,
      ["ctrl-x"] = actions.file_split,
      ["ctrl-v"] = actions.file_vsplit,
      ["ctrl-t"] = actions.file_tabedit,
    },
  },

  lsp = {
    icons = {
      Error = { icon = " ", color = "red" },
      Warning = { icon = " ", color = "yellow" },
      Information = { icon = " ", color = "blue" },
      Hint = { icon = " ", color = "magenta" },
    },
  },

  helptags = { previewer = { split = "topleft" } },
  manpages = { previewer = { split = "topleft" } },

  file_icon_padding = " ",
})
```

**Comment by ibhagwan** [comment]
Using your exact setup with the exact same window size (see the printout of lines,columns at the `:` prompt):

![screenshot-1631557266](https://user-images.githubusercontent.com/59988195/133136382-7d5b8dae-1f37-4939-8211-faaf5ab7cc59.png)
:


I thought this line might have been the issue as it assumes the preview layout is the first string before the `:`, but since you're using the defaults this has me confused:
https://github.com/ibhagwan/fzf-lua/blob/7acb6826c178c66947735c12f35eb642b9c53def/lua/fzf-lua/win.lua#L145

**Comment by uga-rosa** [comment]
I've removed all other plugins and it still doesn't go away, so I don't see the point :_(

**Comment by ibhagwan** [comment]
Can you try playing around setting `preview_horizontal` with different values and also try setting`preview_layout = vertical` and play around with the values in `preview_vertical` and let me know if different values or the vertical layout works?

I still can’t figure out the source of this issue so I’m trying to isolate it.

**Comment by ibhagwan** [comment]
> I've removed all other plugins and it still doesn't go away, so I don't see the point :_(

The issue here isn’t other plugins, it’s obviously within fzf-lua, try changing the values and seeing which setup works and which doesn’t so we can figure out the source of the issue.

**Comment by uga-rosa** [comment]
I was wondering if some variables were being overwritten by other plugins (since I have a new plugin).

Both settings (horizontal and vertical) appear to be working fine. They are off, though.

**Comment by ibhagwan** [comment]
> I was wondering if some variables were being overwritten by other plugins (since I have a new plugin).
> 
> Both settings (horizontal and vertical) appear to be working fine. They are off, though.

Alright I found the issue, you updated to neovim nightly, I just tried the nightly and I have the exact same issue.

I regularly test against the nightly, I believe I tested a couple of days ago and it wasn't happening, it's a new issue.

**Comment by ibhagwan** [comment]
Ok, so turns out `nvim_open_win({win = 'relative'})` wasn't working when the relative window was a floating window, the fix was merged 2 days ago, [see neovim issue #14770](https://github.com/neovim/neovim/pull/14770).

I'll work on a fix that accounts for both versions.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/f4e531b08a18b42d641f02e1fb4f19ad8744bf89 should fix it

**Comment by uga-rosa** [comment]
It's fixed. Tysm!!
