### ISSUE TITLE
Bug: FzfLua grep_cword selects all when multiline = 1

### ISSUE THREAD

**Issue by yujinyuz** [ibhagwan/fzf-lua#1321]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.53.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--layout="default" --height="40%" --info="inline-right" --color="bg+:#414559,bg:-1,spinner:#f2d5cf,hl:#e78284,gutter:-1" --color="fg:#c6d0f5,header:#e7828 4,info:#ca9ee6,pointer:#f2d5cf" --color="marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284"

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    'default-title',
    actions = {
      files = {
        ['default'] = actions.file_edit,
        ['ctrl-s'] = actions.file_split,
        ['ctrl-v'] = actions.file_vsplit,
        ['ctrl-t'] = actions.file_tabedit,
        ['alt-q'] = actions.file_sel_to_qf,
      },
      buffers = {
        ['default'] = actions.buf_edit,
        ['ctrl-s'] = actions.buf_split,
        ['ctrl-v'] = actions.buf_vsplit,
        ['ctrl-t'] = actions.buf_tabedit,
      },
    },
    winopts = {
      preview = {
        delay = 0,
        layout = 'flex',
        flip_columns = 130,
      },
      height = 0.75,
      width = 0.80,
    },
    fzf_opts = {
      ['--no-hscroll'] = '',
      ['--layout'] = 'default',
    },
    keymap = {
      builtin = {
        ['<C-d>'] = 'preview-page-down',
        ['<C-u>'] = 'preview-page-up',
        ['<C-h>'] = 'toggle-preview',
        ['<C-y>'] = 'toggle-preview-wrap',
        ['<C-b>'] = 'toggle-preview-cw',
      },
    },
    files = {
      fd_opts = '--strip-cwd-prefix ' .. defaults.files.fd_opts,
      git_icons = false,
    },
    git = {
      files = {
        cmd = defaults.git.files.cmd .. ' --cached --others --deduplicate',
        git_icons = false,
        file_icons = false,
      },
    },
    grep = {
      git_icons = false,
      file_icons = false,
      multiline = 1,
    },
    on_create = function()
      vim.keymap.set('t', '<Esc>', '<C-c>', { buffer = 0 })
    end,

})
```

### Describe the bug / steps to reproduce

ensure multiline = 1

Run `:FzfLua grep_cword`

<img width="842" alt="Screenshot 2024-07-06 at 14 42 22" src="https://github.com/ibhagwan/fzf-lua/assets/10972027/b8f4eb15-8e47-4458-ad19-b21eab51c3e4">

**Comment by ibhagwan** [comment]
Should work as expected with https://github.com/ibhagwan/fzf-lua/commit/30e8e962405c274d7766dda207e1761a0105929c, Ty for the report @yujinyuz.

**Comment by yujinyuz** [comment]
Thanks @ibhagwan 

Seems to be working now as expected
