### ISSUE TITLE
Bug: builtin fzf print-query broke the plugin

### ISSUE THREAD

**Issue by illia-danko** [ibhagwan/fzf-lua#1324]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.52.1 

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

❯ echo $FZF_DEFAULT_OPTS      --no-mouse     --layout=reverse     --height 40%     --border     --multi     --exact     --preview-window=hidden     --bind='alt-w:execute-silent(echo -n {} | xclip -in -selection c)'     --bind='ctrl-e:print-query'     --bind='ctrl-b:half-page-up'     --bind='ctrl-f:half-page-down'     --bind='ctrl-u:preview-half-page-up'     --bind='ctrl-d:preview-half-page-down'     --bind='alt-p:toggle-preview'     --bind='ctrl-a:toggle-all'     --color=gutter:-1,fg:-1,fg+:-1,pointer:1,hl:2,hl+:2,bg+:8      --no-mouse     --layout=reverse     --height 40%     --border     --multi     --exact     --preview-window=hidden     --bind='alt-w:execute-silent(echo -n {} | xclip -in -selection c)'     --bind='ctrl-e:print-query'     --bind='ctrl-b:half-page-up'     --bind='ctrl-f:half-page-down'     --bind='ctrl-u:preview-half-page-up'     --bind='ctrl-d:preview-half-page-down'     --bind='alt-p:toggle-preview'     --bind='ctrl-a:toggle-all'     --color=gutter:-1,fg:-1,fg+:-1,pointer:1,hl:2,hl+:2,bg+:8      --no-mouse     --layout=reverse     --height 40%     --border     --multi     --exact     --preview-window=hidden     --bind='alt-w:execute-silent(echo -n {} | xclip -in -selection c)'     --bind='ctrl-e:print-query'     --bind='ctrl-b:half-page-up'     --bind='ctrl-f:half-page-down'     --bind='ctrl-u:preview-half-page-up'     --bind='ctrl-d:preview-half-page-down'     --bind='alt-p:toggle-preview'     --bind='ctrl-a:toggle-all'     --color=gutter:-1,fg:-1,fg+:-1,pointer:1,hl:2,hl+:2,bg+:8      --no-mouse     --layout=reverse     --height 40%     --border     --multi     --exact     --preview-window=hidden     --bind='alt-w:execute-silent(echo -n {} | xclip -in -selection c)'     --bind='ctrl-e:print-query'     --bind='ctrl-b:half-page-up'     --bind='ctrl-f:half-page-down'     --bind='ctrl-u:preview-half-page-up'     --bind='ctrl-d:preview-half-page-down'     --bind='alt-p:toggle-preview'     --bind='ctrl-a:toggle-all'     --color=gutter:-1,fg:-1,fg+:-1,pointer:1,hl:2,hl+:2,bg+:8

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
fzf_lua.setup({
    winopts = {
      fullscreen = true,
      number = false,
      preview = {
        vertical = "down:50%",
        horizontal = "right:50%",
        flip_columns = 160,
      },
    },
    keymap = {
      builtin = {
        ["<A-p>"] = "toggle-preview",
        ["<C-d>"] = "preview-page-down",
        ["<C-u>"] = "preview-page-up",
        ["<F1>"] = "toggle-help",
        ["<F2>"] = "toggle-fullscreen",
      },
      fzf = {},
    },
  })
```

### Describe the bug / steps to reproduce

I have --bind='ctrl-e:print-query' is coming from $FZF_DEFAULT_OPTS

And I would like to use this functionality in fzf-lua.

If I execute something like `lua require("fzf-lua").fzf_exec({"foo", "bar"}) ` , then type something and press 'ctrl-e' the plugin is terminated:

![image](https://github.com/ibhagwan/fzf-lua/assets/8293386/1d68adce-74d4-4cab-9999-fb5244ed3dfd)

I also looked at an workaround which allows me to print what I type exactly (not coming from matched lines), but I was not succeed on this.

**Comment by ibhagwan** [comment]
> And I would like to use this functionality in fzf-lua.

Fzf-lua uses print query internally to save the last query (for resume, etc), if you want to do something when ctrl-e is pressed you’ll need to define it as an action and use `opts.last_query` to print the typed query:
```lua
:lua require"fzf-lua".fzf_exec({1,2},{
  actions={
    ["ctrl-e"]=. function(sel,opts) 
      print(opts.last_query)
    end } 
  })
```

**Comment by illia-danko** [comment]
@ibhagwan  thank you, after an hour I finally find a way how to integrate actions mapping into the 3rd party plugin which uses  fzf-lua.
