### ISSUE TITLE
Bug: SVG preview with Chafa not working

### ISSUE THREAD

**Issue by mangelozzi** [ibhagwan/fzf-lua#1328]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

22.04.2-Ubuntu 

### Shell

bash

### Neovim version (`nvim --version`)

sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"

### Fzf version (`fzf --version`)

0.36.0 (2023011)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

Firstly much love for you and this project, and big thank you!

I have `chafa` installed to be able to preview SVG's, I can run on the command line `chafa /path/to/some.svg` and it works. In Neovim I can run `:!chafa -h` and it works. So I have ruled that out the executable.

The wiki says [here](https://github.com/ibhagwan/fzf-lua/wiki#can-fzf-lua-preview-media-files)

> To do so you will need to configure previewer.builtin.extensions with a shell command per extension, the shell command will then run in a neovim terminal buffer inside the preview window.

I am guessing the wiki is out of date because in the default configuration in the README.md it has the configuration already present:

``` lua
previewers = {
   ...
    builtin = {
      ...
      extensions      = {
        -- neovim terminal only supports `viu` block output
        ["png"]       = { "viu", "-b" },
        -- by default the filename is added as last argument
        -- if required, use `{file}` for argument positioning
        ["svg"]       = { "chafa", "{file}" },
        ["jpg"]       = { "ueberzug" },
      },
```

We see that `svg` is already setup. I tried adding it to my setup just incase and it still did not work. When I preview a svg file, it previews the text of the svg not the chafa render.

On a site note [ueberzug](https://github.com/seebye/ueberzug) is archived, and has made it not trivial to install (pushed only a read me notice to the repo).

These features are just nice to haves, the cherry's on top of an amazing plugin, cheers!

**Comment by ibhagwan** [comment]
Have you tried displaying an svg file in the term with chafa?

The README options are mere suggestions, I cannot guarantee how external tools are going to operate.

**Comment by mangelozzi** [comment]
> Have you tried displaying an svg file in the term with chafa?
> 
> The README options are mere suggestions, I cannot guarantee how external tools are going to operate, fzf-lua just runs the command, the output is out of my control.

Did you see this part of the issue I wrote:
> I have chafa installed to be able to preview SVG's, I can run on the command line chafa /path/to/some.svg and it works. In Neovim I can run :!chafa -h and it works. So I have ruled that out the executable.

This is what it looks like from the terminal:
![image](https://github.com/user-attachments/assets/2cac34a3-40a0-4b15-80fc-3f1768d9b787)

This is what it looks like in fzf-lua:
![image](https://github.com/user-attachments/assets/28fba916-350c-400f-a858-f99a8e1b04e0)

It's not the rendering of chafa, its that chafa is not used.
Further more did you see my point about the conflicting data in the wiki and README.md on how to set it up?

**Comment by ibhagwan** [comment]
> It's not the rendering of chafa, its that chafa is not used.

I’ll check.

> On a site note [ueberzug](https://github.com/seebye/ueberzug) is archived, and has made it not trivial to install (pushed only a read me notice to the repo).

The README doesn’t point to the archived ueberzug but instead to [jstkdng/ueberzugpp](https://github.com/jstkdng/ueberzugppj).

> I am guessing the wiki is out of date because in the default configuration in the README.md it has the configuration already present:

I guess I could clarify the README is just suggesting a configuration when it comes to extensions, by default these aren’t defined.

**Comment by mangelozzi** [comment]
Thanks for looking into it

> The README doesn’t point to the archived ueberzug but instead to [jstkdng/ueberzugpp](https://github.com/jstkdng/ueberzugppj).

I followed this link (shown in the image below) from the [WIKI](https://github.com/ibhagwan/fzf-lua/wiki#can-fzf-lua-preview-media-files), I think it's a stray link to the old `seebye` repo that probably could be updated
![image](https://github.com/user-attachments/assets/8893ea4d-56b8-44eb-b06a-ba4f0d37c083)

> 
> > I am guessing the wiki is out of date because in the default configuration in the README.md it has the configuration already present:
> 
> I guess I could clarify the README is just suggesting a configuration when it comes to extensions, by default these aren’t defined.
Okay I see, that would be great, "default settings" misleads one into thinking it's already setup, and one only needs to change it if one wish to have an alternate behavior.
Cheers!

**Comment by ibhagwan** [comment]
svg extension with chafa works fine on my end, I suspect `chafa` isn't detected by your neovim env, can you run `:= vim.fn.executable("chafa")` and post the output?

> I followed this link (shown in the image below) from the [WIKI](https://github.com/ibhagwan/fzf-lua/wiki#can-fzf-lua-preview-media-files), I think it's a stray link to the old seebye repo that probably could be updated

The Wiki is open edit, you could change it yourself if you wanted, anyways, the Wiki is now updated to ueberzugpp.

**Comment by mangelozzi** [comment]
> svg extension with chafa works fine on my end, I suspect `chafa` isn't detected by your neovim env, can you run `:= vim.fn.executable("chafa")` and post the output?

It just outputs `1` (I did clear the history before running it, and checked with :mess to ensure there wasnt more. 

And this test works inside of neovim:
```
:!chafa /home/michael/linkcube/src/core/pack/icon/static/icon/validation_tick.svg                                                                                                    
^[[0m                      ^[[0m                                                                                                                                                              
                   ^[[38;2;0;81;0m▄^[[38;2;0;115;0;48;2;0;69;0m▅^[[0m^[[38;2;0;110;0m▅^[[0m                                                                                                   
                 ^[[38;2;0;82;0m▄^[[38;2;0;64;0;48;2;0;112;0m▘^[[38;2;0;114;0;48;2;0;126;0m▘^[[38;2;0;128;0;48;2;0;127;0m┈^[[38;2;0;100;0;48;2;0;126;0m▂^[[0m                                 
               ^[[38;2;0;84;0m▄^[[38;2;0;66;0;48;2;0;113;0m▘^[[38;2;0;114;0;48;2;0;126;0m▘^[[38;2;0;128;0;48;2;0;127;0m┈^[[38;2;0;101;0m▂^[[0m^[[7m^[[38;2;0;113;0m▄^[[0m^[[38;2;0;76;0m▘^[[0m
                                                                                                                                                                                              
             ^[[38;2;0;85;0m▄^[[38;2;0;69;0;48;2;0;113;0m▘^[[38;2;0;114;0;48;2;0;126;0m▘^[[38;2;0;128;0;48;2;0;127;0m┈^[[38;2;0;102;0;48;2;0;126;0m▂^[[0m^[[7m^[[38;2;0;114;0m▄^[[0m^[[38;2;0;
73;0m▘^[[0m  ^[[0m                                                                                                                                                                            
           ^[[38;2;0;86;0m▄^[[38;2;0;71;0;48;2;0;113;0m▘^[[38;2;0;114;0;48;2;0;126;0m▘^[[38;2;0;128;0;48;2;0;127;0m┈^[[38;2;0;94;0;48;2;0;124;0m▁^[[0m^[[7m^[[38;2;0;114;0m▄^[[0m^[[38;2;0;70;
0m▘^[[0m    ^[[0m                                                                                                                                                                             
^[[38;2;0;86;0m▗^[[38;2;0;118;0;48;2;0;68;0m▄^[[38;2;0;115;0;48;2;0;70;0m▆^[[0m^[[38;2;0;90;0m▄^[[0m     ^[[38;2;0;87;0m▄^[[38;2;0;113;0;48;2;0;72;0m▆^[[38;2;0;126;0;48;2;0;115;0m▆^[[38;2;0;
128;0;48;2;0;127;0m┈^[[38;2;0;96;0;48;2;0;124;0m▁^[[0m^[[7m^[[38;2;0;114;0m▄^[[0m^[[38;2;0;68;0m▘^[[0m      ^[[0m                                                                             
^[[7m^[[38;2;0;80;0m▃^[[0m^[[38;2;0;89;0;48;2;0;121;0m▃^[[38;2;0;128;0;48;2;0;126;0m┊^[[38;2;0;127;0;48;2;0;117;0m▆^[[38;2;0;74;0m▝^[[0m^[[38;2;0;90;0m▄^[[0m ^[[38;2;0;88;0m▄^[[38;2;0;114;0;
48;2;0;71;0m▆^[[38;2;0;126;0;48;2;0;115;0m▆^[[38;2;0;128;0;48;2;0;127;0m┈^[[38;2;0;103;0;48;2;0;126;0m▗^[[0m^[[7m^[[38;2;0;114;0m▄^[[38;2;0;66;0m▆^[[0m        ^[[0m                          
  ^[[7m^[[38;2;0;93;0m▄^[[0m^[[38;2;0;88;0;48;2;0;122;0m▃^[[38;2;0;128;0;48;2;0;126;0m┊^[[38;2;0;127;0;48;2;0;117;0m▆^[[48;2;0;97;0m▆^[[48;2;0;117;0m▆^[[38;2;0;128;0;48;2;0;127;0m┈^[[38;2;0;
100;0;48;2;0;126;0m▗^[[0m^[[7m^[[38;2;0;106;0m▃^[[38;2;0;67;0m▆^[[0m          ^[[0m                                                                                                           
    ^[[7m^[[38;2;0;93;0m▄^[[0m^[[38;2;0;87;0;48;2;0;121;0m▃^[[38;2;0;119;0;48;2;0;127;0m▁^[[38;2;0;97;0;48;2;0;126;0m▗^[[0m^[[7m^[[38;2;0;105;0m▃^[[38;2;0;68;0m▆^[[0m            ^[[0m       
      ^[[7m^[[38;2;0;85;0m▅^[[38;2;0;67;0m▆^[[0m              ^[[0m                                                                                                                           
                                                                                                                                                                                              
Press ENTER or type command to continue
```

> > I followed this link (shown in the image below) from the [WIKI](https://github.com/ibhagwan/fzf-lua/wiki#can-fzf-lua-preview-media-files), I think it's a stray link to the old seebye repo that probably could be updated
> 
> The Wiki is open edit, you could change it yourself if you wanted, anyways, the Wiki is now updated to ueberzugpp.
Sorry, I see now there is an edit button, I should have done it.

I use the nightly appimage, so I thought that might be the issue, so I tried using the latest stable appimage and got the same result (just returns `1` for the request command and does not show the preview):
```
NVIM v0.10.0                                                                               
Build type: Release                                                                                  
LuaJIT 2.1.1713484068
```

**Comment by ibhagwan** [comment]
> It just outputs 1

That’s the expected output, this means `chafa` is detected and should work if it’s configured properly.

As we already established, the README incorrectly suggests the default options, could this be a configuration issue on your end (missing/typo/incorrect tree)? Can you post a link to your config so I can take a look?

**Comment by mangelozzi** [comment]
Okay great, thought `0` would mean success. 
But anyways I tested with the none app image version, still same result. I forgot I had deleted the `previewers` config section after refering to the default settings in the readme. So I added it back, and it worked. I must have configured it wrong. So sorry to waste your time. I checked it many times against the wiki and the readme before opening but I must have had my config object wrong. Thank you for your help! Sorry I really tried (on multiple occasions) to get it working before opening this.

**Comment by ibhagwan** [comment]
> Okay great, thought `0` would mean success. But anyways I tested with the none app image version, still same result. I forgot I had deleted the `previewers` config section after refering to the default settings in the readme. So I added it back, and it worked. I must have configured it wrong. So sorry to waste your time. I checked it many times against the wiki and the readme before opening but I must have had my config object wrong. Thank you for your help! Sorry I really tried (on multiple occasions) to get it working before opening this.

No worries, Ty @mangelozzi 🙏
