### ISSUE TITLE
binding page-up, page-down to preview-page-* doesn't work

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#133]
Hi, I have tried to bind `page-up` and `page-down` to `preview-page-up` and `preview-page-down` but it doesn't work. Is there any issue? Using `shift-up` and `shift-down` works though.

```lua
  use {'ibhagwan/fzf-lua', requires = {'vijaymarupudi/nvim-fzf', 'kyazdani42/nvim-web-devicons'}, config = function()
    require('fzf-lua').setup {
      winopts = {
        hl_border        = 'Normal',
      },
      fzf_layout         = 'default',
      fzf_binds          = {
        ["page-down"]    = "preview-page-down",
        ["page-up"]      = "preview-page-up",
      },
    }
  end}

```

also in the README

```lua
      builtin = {
        keymap = {
          page_up       = '<PageUp>',     -- preview scroll up
          page_down     = '<PageDown>',   -- preview scroll down
        },
      },
```

I tried to change it but only `shift-up` and `shift-down` works

**Comment by ibhagwan** [comment]
The `fzf_binds` only work when using fzf as the previewer, you can try it out by setting `default_previewer = “bat”`, pretty sure this would work.

Now regarding the builtin previewer, let’s see if the mapping took effect first, while fzf-lua is open press `<C-\>< C-n>` to exit insert mode and then run `:tmap <PageUp>` and let me know the result?

**Comment by ibhagwan** [comment]
Just tested this and the mapping command does work, when I run `tmap <PageUp>` (on the fzf win) I get:
```vim
:tmap <PageUp>
t  <PageUp>    *@<Cmd>lua require('fzf-lua.previewer.builtin').base.scroll(-1)<CR>
```

I'm not sure if you're in the same situation but I have a mac laptop keyboard so I have to send `<function key>+<arrow up|down>` in order to simulate `page-up|down`.

**Comment by sandangel** [comment]
I'm also using a mac. Let me try this. Thanks ^^

**Comment by ibhagwan** [comment]
> I'm also using a mac. Let me try this. Thanks ^^

I’m using a Mac laptop but running Linux so your experience may vary.

**Comment by sandangel** [comment]
hi @ibhagwan , I have tried, only the `fzf_binds` works after changing `default_previewer` to `bat`. I think the key map setting should not depend on the `previewer` though.

For `builtin`,  I have tried, but it said `No mapping found`.

**Comment by ibhagwan** [comment]
> hi @ibhagwan , I have tried, only the `fzf_binds` works after changing `default_previewer` to `bat`. I think the key map setting should not depend on the `previewer` though.

There probably is room to merge the options, the reason for difference is because the `bat` previewer is internal to fzf and the builtin is a neovim window.

> For `builtin`, I have tried, but it said `No mapping found`.

The code for the mapping works evidently we see it with `<S-down|up>`, that suggests maybe your neovim doesn't accept `<PageUp|PageDown>` mappings? have you tried mapping anything else in the terminal using `<PageUp>` `<PageDown>`?

Maybe as a test we can do a global mapping, what happens if you do this?
```vim
tnoremap <PageUp> <C-\><C-n>:lua require('fzf-lua.previewer.builtin').base.scroll(-1)<CR>i
tnoremap <PageDown> <C-\><C-n>:lua require('fzf-lua.previewer.builtin').base.scroll(1)<CR>i
```

**Comment by sandangel** [comment]
hi, I just check again and it was a misconfigured issue. I missed the `previewers` before the `builtin`. I think we could have some config validation. 😅

**Comment by ibhagwan** [comment]
> hi, I just check again and it was a misconfigured issue. I missed the `previewers` before the `builtin`. I think we could have some config validation. 😅

Thanks for letting me know!
