### ISSUE TITLE
Bug: Preview Layout = 'vertical' is not being applied

### ISSUE THREAD

**Issue by alwaysamer** [ibhagwan/fzf-lua#1335]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [x] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Fzf version (`fzf --version`)

0.52.1 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=fg:-1,fg+:-1,bg:-1,bg+:-1 --color=hl:#5ea1ff,hl+:#5ef1ff,info:#afaf87,marker:#5eff6c --color=prompt:#ff5ea0,spinner:#ff5ef1,pointer:#bd5eff,header:#87afaf --color=border:#262626,label:#aeaeae,query:#d9d9d9 --color=fg:-1,fg+:-1,bg:-1,bg+:-1 --color=hl:#5ea1ff,hl+:#5ef1ff,info:#afaf87,marker:#5eff6c --color=prompt:#ff5ea0,spinner:#ff5ef1,pointer:#bd5eff,header:#87afaf --color=border:#262626,label:#aeaeae,query:#d9d9d9

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
            winopts = {
                border = "single",
                preview = {
                    title = false,
                    scrollbar = false,
                }
            },
            hls = {
                border = "FloatBorder",
                normal = "NONE",
                preview_normal = "NONE",
                preview_border = "FloatBorder",
            }

})
```

### Describe the bug / steps to reproduce

Hello,

I am currently setting up lsp_code_actions with the option split = 'belowright new'. The only issue with that is when I use Neovim without an external monitor, meaning on my Mac display, FzfLua recognizes the display as too small and forces the 'flex' view, meaning splitting the preview window horizontally instead of vertically. I am trying to circumvent this behavior with layout='vertical'. However, it seems like the layout option is not properly recognized by FzfLua and, strangely enough, it forces the horizontal view instead ( even on my external which makes sense since there is no flex anymore). The configuration I have entered above is my general configuration, and the following is how I set up the lsp_code_action specifically.

```lua
require('fzf-lua').lsp_code_actions({
                    winopts = {
                        split = "belowright new",
                        preview = {
                            layout = 'vertical',
                        }
                    },
                })
```

Here is a screenshot if it helps:
![image](https://github.com/user-attachments/assets/6ce2ca06-ce77-42d6-80cc-db3c192eb6ac)

**Comment by ibhagwan** [comment]
Have you tried `horizontal` instead?

Take a look at the default options, `vertical` means the preview is either up or down and `horizontal` means left or right.
```lua
      vertical       = 'down:45%',      -- up|down:size
      horizontal     = 'right:60%',     -- right|left:size
```

As for the flex not being detected correctly that would depend on the output of `:= vim.api.nvim_win_get_width(0)`.

**Comment by alwaysamer** [comment]
Cool that seems to have done it, Thanks! 👍
