### ISSUE TITLE
Bug: FzfLua oldfiles takes 10+ seconds to load

### ISSUE THREAD

**Issue by yanghu** [ibhagwan/fzf-lua#1336]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.44.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

11:11:36 AM msg_show   lua print(os.getenv('FZF_DEFAULT_OPTS'))  --inline-info --reverse --exact --color=fg+:#F8F8F8,bg+:#515559,pointer:#F8F8F8,marker:226 --bind=ctrl-e:select-all+accept --bind=ctrl-d:half-page-down --bind=ctrl-u:half-page-up 11:11:36 AM msg_show   lua print(os.getenv('FZF_DEFAULT_OPTS')) --bind=ctrl-t:toggle+down 11:11:36 AM msg_show   lua print(os.getenv('FZF_DEFAULT_OPTS')) --bind=ctrl-b:toggle+up 11:11:36 AM msg_show   lua print(os.getenv('FZF_DEFAULT_OPTS')) --bind=ctrl-g:select-all+accept 

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
				global_resume = true,
				previewers = {
					builtin = {
						title_fnamemodify = function(t, width)
							local min_left_padding = 4
							local min_right_padding = 4
							local max_text_width = width - min_left_padding - min_right_padding
							if #t > max_text_width then
								return "..." .. t:sub(#t - max_text_width + 3 + 1, #t)
							end
							return t
						end,
					},
				},
				keymap = {
					builtin = {
						["ctrl-u"] = "half-page-up",
						["ctrl-d"] = "half-page-down",
						["<C-f>"] = "preview-page-down",
						["<C-b>"] = "preview-page-up",
						["<C-a>"] = "toggle-all",
						-- ["<C-q>"] = "",
					},
					fzf = {
						["ctrl-u"] = "half-page-up",
						["ctrl-d"] = "half-page-down",
						["ctrl-f"] = "preview-page-down",
						["ctrl-b"] = "preview-page-up",
						["ctrl-a"] = "toggle-all",
						-- ["ctrl-q"] = "select-all+accept",
					},
				},
				winopts = bottom_row,
				file_ignore_patterns = {},
				blines = {
					fzf_opts = {
						["--no-multi"] = false,
						["--multi"] = true,
					},
				},
				builtin = {
					winopts = right_column,
				},
				colorschemes = {
					winopts = right_popup,
				},
				diagnostics = {
					winopts = right_column,
				},
				files = {
					prompt = "Files❯ ",
					path_shorten = 4,
					actions = {
						["ctrl-e"] = actions.file_edit,
					},
				},
				filetypes = {
					winopts = {
						relative = "cursor",
						width = 0.14,
						row = 1.01,
					},
				},
				git = {
					branches = {
						winopts = right_column,
					},
					bcommits = {
						winopts = right_column,
					},
					commits = {
						winopts = right_column,
					},
					status = {
						winopts = right_column,
					},
				},
				grep = {
					-- cmd = 'ugrep -RIjnkzs --hidden --ignore-files --exclude-dir=".git"',
					rg_opts = "--column --trim --line-number --no-heading --color=always --smart-case --max-columns=4096 -e",
					path_shorten = 4,
					winopts = bottom_row,
					-- winopts = {
					-- 	fullscreen = true,
					-- },
					formatter = "path.filename_first",
					actions = {
						["ctrl-q"] = actions.file_sel_to_qf,
					},
				},
				grep_curbuf = {
					fzf_opts = {
						["--no-multi"] = false,
						["--multi"] = true,
					},
				},
				highlights = {
					winopts = right_column,
				},
				keymaps = {
					actions = {
						["default"] = require("fzf-lua.actions").keymap_edit,
					},
				},
				lgrep_curbuf = {
					fzf_opts = {
						["--no-multi"] = false,
						["--multi"] = true,
					},
				},
				lines = {
					fzf_opts = {
						["--no-multi"] = false,
						["--multi"] = true,
					},
					actions = {
						["ctrl-q"] = actions.file_sel_to_qf,
					},
				},
				spell_suggest = {
					winopts = {
						relative = "cursor",
						width = 0.2,
						row = 1.01,
					},
				},

})
```

### Describe the bug / steps to reproduce

Either run `:FzfLua oldfiles` or trigger it via keymap. The preview UI loads but the content appears after seconds, sometimes 10+ seconds.
 
Other FzfLua commands doesn't have the same issue. (like "files", etc)

I tried to use profile.nvim and found most time are spent in `fzf-lua.fzf.raw_fzf`

for the record, using telescope to see old files doesn't have this delay.

**Comment by ibhagwan** [comment]
Is there an issue with the preview, what happens if you use `:FzfLua oldfiles previewer=false`?

**Comment by ibhagwan** [comment]
Also try `:FzfLua oldfiles stat_file=false`?

**Comment by yanghu** [comment]
> Also try `:FzfLua oldfiles stat_file=false`?

`stat_file=false` solved the issue.  Any suggestion on further debugging this or would it be okay to turn of stat?

**Comment by ibhagwan** [comment]
> > Also try `:FzfLua oldfiles stat_file=false`?
> 
> `stat_file=false` solved the issue. Any suggestion on further debugging this or would it be okay to turn of stat?

It’s totally ok to turn of stat, but it means that one of your files (probably one of the first ones) is causing the delay while the code is trying to determine accessibility with `vim.uv.fs_stat` which means the inaccessible files aren’t being filtered.

You can attempt to run `fs_stat` for each and see which one but unless it’s a special file which can be filtered in a different way I’m not sure what I can do to speed up `vim.uv`.

**Comment by yanghu** [comment]
Thanks.  

yes stat on old files will cause delays since I have lots of paths that are remote mounted. (and some may be invalid already)

I'll just disable stat since inaccessible files is not a big concern really. 

Anywhere I can apply the "stat_file=false" for all my "oldfiles" command? 
I tried to add to my fzf-lua setup opt:

```
oldfiles={
  fzf_opts= { ["--stat_file"] = false }
}
```

but seems it's not working.

**Comment by ibhagwan** [comment]
> Thanks.
> 
> yes stat on old files will cause delays since I have lots of paths that are remote mounted. (and some may be invalid already)
> 
> I'll just disable stat since inaccessible files is not a big concern really.
> 
> Anywhere I can apply the "stat_file=false" for all my "oldfiles" command? I tried to add to my fzf-lua setup opt:
> 
> ```
> oldfiles={
>   fzf_opts= { ["--stat_file"] = false }
> }
> ```
> 
> but seems it's not working.

This isn’t an fzf shell option (what fzf_opts is for), just add `stat_file = false` under oldfiles.

**Comment by yanghu** [comment]
Thank you!
