### ISSUE TITLE
Feature: Filter tags before displaying it with Ffz-lua

### ISSUE THREAD

**Issue by maxencetholomier** [ibhagwan/fzf-lua#1341]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

First of all I would like to thank you for this plugin.

It allow me to use fzf-tmux pop-up after switching to nvim, which is not possible with telescope or other similar plug-in.

The documentation is also well written.

## New feature 

With the following command all tags are display : 

```lua
require('fzf-lua').tags()
```
I would like to filter the tags to reject some "kinds". 

For exemple, for C++ files I would like to remove all tags with kinds "m". 

```bash
$ ctags --list-kinds=C++

d  macro definitions
e  enumerators (values inside an enumeration)
f  function definitions
g  enumeration names
h  included header files
l  local variables [off]
m  class, struct, and union members
p  function prototypes [off]
s  structure names
t  typedefs
u  union names
v  variable definitions
x  external and forward variable declarations [off]
z  function parameters inside function or prototype definitions [off]
L  goto labels [off]
D  parameters inside macro definitions [off]
c  classes
n  namespaces
A  namespace aliases [off]
N  names imported via using scope::symbol [off]
U  using namespace statements [off]
Z  template parameters [off]
```

NB: I've searched in [ADVANCED CUSTOMIZATION](https://github.com/ibhagwan/fzf-lua/wiki/Advanced) and in the old issues but not found anything related to this.

**Comment by ibhagwan** [comment]
Ty for the kind words @maxencetholomier.

If you wish to permanently excluded these types I’m pretty sure you can filter these out while generating the tags file.

If you wish to exclude these types dynamically you can use fzf’s syntax, for example, excluding anything with the word function `:FzfLua tags query=!function`.

Although not a filter, I recommend using `:FzfLua tags_live_grep` to narrow down your search scope and then pressing `ctrl-g` to switch to fuzzy mode, this helps a lot getting to what you need more easily (similar to normal live_grep -> grep).

As for a built in ability to filter certain types in tags within fzf-lua, there is no such functionality and I have no plans on adding said filter ATM.

**Comment by maxencetholomier** [comment]
## Previous message comment 

Sorry I was a little bit slow to reply. 

Unfortunately  : 
- I cannot filter the file as I'm using it in vim to C-]. I just want some kinds not appearing with Fzf-Lua.
- By default the kinds are not display so the solution with ctrl-g was not possible. 

Following a solution inspired by your previous messages : 

## Solution

Generate the Ctags files with line number.

```bash
ctags-universal --fields=+n  -R .  # add line number to tags 
```

Create the script filter-tags 

```bash
#!/bin/bash

remove_tags_file_metadata='1,11d'
remove_prefix_line_number='s/line://g'
remove_kinds_z=('$4 != "z"')

cat ${1} | sed --expression "${remove_tags_file_metadata}" \
	--expression "${remove_prefix_line_number}" |
	awk "${remove_kinds_z[@]}"
```

Add this into init.lua 

```lua
function split(inputstr, sep)
	if sep == nil then
		sep = "%s" -- default separator is whitespace
	end
	local count = 0
	for str in string.gmatch(inputstr, "([^" .. sep .. "]+)") do
		count = count + 1
		if count == 2 then
			return str
		end
	end
	return nil -- return nil if there's no second element
end

_G.fzf_test = function(opts)
	opts = opts or {}
	opts.prompt = "Tags>"
	opts.preview = "bat -p --color=always {2} --highlight-line={5}  "
	opts.actions = {
		["ctrl-t"] = function(selected)
			vim.cmd("tabnew " .. split(selected[1], "\t"))
		end,
		default = function(selected)
			vim.cmd("e " .. split(selected[1], "\t"))
		end,
	}
	opts.fzf_opts = {
		["--delimiter"] = "\t",
		["--preview-window"] = "top:wrap,+{5}+3/3",
	}
	if vim.fn.filereadable("tags") == 1 then
		require("fzf-lua").fzf_exec("filter-tags tags", opts)
	else
		print("No tags files here")
	end
end

vim.keymap.set("n", "<leader>pt", "<cmd>lua _G.fzf_test()<CR>")
```

## Comment 

Sorry for the lua part, I'm not using it very often. 
I hope it will help people :)
And thanks you again for the help !
