### ISSUE TITLE
Bug: FzfLua helptags with external plugin gives error

### ISSUE THREAD

**Issue by dhruvinsh** [ibhagwan/fzf-lua#1342]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.54.0 (9e92b6f)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

   --highlight-line   --info=inline-right   --ansi   --layout=reverse   --border=none   --color=bg+:#2d3f76   --color=bg:#1e2030   --color=border:#589ed7   --color=fg:#c8d3f5   --color=gutter:#1e2030   --color=he ader:#ff966c   --color=hl+:#65bcff   --color=hl:#65bcff   --color=info:#545c7e   --color=marker:#ff007c   --color=pointer:#ff0 07c   --color=prompt:#65bcff   --color=query:#c8d3f5:regular   --color=scrollbar:#589ed7   --color=separator:#ff966c   --color =spinner:#ff007c    --highlight-line   --info=inline-right   --ansi   --layout=reverse   --border=none   --color=bg+:#2d3f76   --color=bg:#1e2030   --color=border:#589ed7   --color=fg:#c8d3f5   --color=gutter:#1e2030   --color=he ader:#ff966c   --color=hl+:#65bcff   --color=hl:#65bcff   --color=info:#545c7e   --color=marker:#ff007c   --color=pointer:#ff0 07c   --color=prompt:#65bcff   --color=query:#c8d3f5:regular   --color=scrollbar:#589ed7   --color=separator:#ff966c   --color =spinner:#ff007c

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  files = {
      prompt = "F❯ ",
      cwd_prompt = false,
      formatter = "path.filename_first",
  },
})
```

### Describe the bug / steps to reproduce

I have Fzf-Lua installed and 'mini.align' installed as well.

`FzfLua helptags` I can search for `MiniAlign` docs without any issue, but as soon as I try to open, it give me error,

```
[Fzf-lua] fn_selected threw an error: vim/_editor.lua:0: nvim_exec2(): Vim(help):E149: Sorry, no help for mini.align
stack traceback:
^I...e/ds/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:235: in function <...e/ds/.local/share/nvim/lazy/fzf-lua/lua/fzf
-lua/core.lua:229>
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I...s/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/actions.lua:111: in function 'vimcmd'
^I...s/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/actions.lua:572: in function 'action'
^I...s/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/actions.lua:92: in function 'act'
^I...e/ds/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:148: in function 'fn_selected'
^I...e/ds/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:228: in function <...e/ds/.local/share/nvim/lazy/fzf-lua/lua/fzf
-lua/core.lua:227>
^I[C]: in function 'xpcall'
^I...e/ds/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:227: in function <...e/ds/.local/share/nvim/lazy/fzf-lua/lua/fzf
-lua/core.lua:221>

```

![image](https://github.com/user-attachments/assets/d59c1b30-f34e-4e85-b807-cd84b0b60b61)
![image](https://github.com/user-attachments/assets/b7945eea-006a-4d95-a8c4-c84d8263cf7c)

**Comment by ibhagwan** [comment]
That’s because of #1296, you’re most likely lazy loading `mini.nvim`, if you try to do the same after using any mini module once (therefore loading the plug-in), it will work.

I’ll look into a workaround for lazy loaded help tags.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/0b41d2f13241e59a1ff94e70a31fcad5c5b2aef6

**Comment by dhruvinsh** [comment]
> you’re most likely lazy loading mini.nvim

Yes you are right. I saw the help text while searching and thought opening a help file still be possible.

As soon as I removed the Lazy loading it works as expected.

Ps. I tried the lastest commit that you pushed for this issue, but still issue there. You must be aware of it but just documenting here.

**Comment by ibhagwan** [comment]
> Ps. I tried the lastest commit that you pushed for this issue, but still issue there. You must be aware of it but just documenting here.

The commit you’re referring to is unrelated I wrote the wrong issue number by mistake in the comment.

If you look at the commit in #1296 you’ll see the runtime is manually added from the yet unloaded packages from lazy.nvim, prior to that tags from packages that aren’t loaded yet wouldn’t appear in the list.

The solution here is manually loading the package (in the code) when we detect the package wasn’t loaded yet or adding lazy.nvim’s plugin paths before executing `:help …`.

Another solution would be to lazy load the package when help is called inside lazy.nvim but that’s up to @folke to decide if this makes sense.

**Comment by ibhagwan** [comment]
> As soon as I removed the Lazy loading it works as expected

Btw you don’t have to disable lazy loading, if you activate anything within the mini package it will be lazy loaded after which calling help with fzf-lua will also work, this only happens if you run help for lazy loaded packages before they were called.

**Comment by folke** [comment]
See the PR for a fix.

**Comment by dhruvinsh** [comment]
Thank you @ibhagwan and @folke
