### ISSUE TITLE
Bug: backdrop flash when open `FzfLua colorschemes`

### ISSUE THREAD

**Issue by xuanhung1509** [ibhagwan/fzf-lua#1345]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.54.1 (50fa90d)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
default setup will do it
```

## Step to reproduce:
Just enter command `FzfLua colorschemes`.

https://github.com/user-attachments/assets/f94d9eef-916b-489d-849b-38c19966d6ec

You will see the backdrop color (which is 60% black, by default) render first, then the color of your current colorscheme will render above that window.

This only happens on opening, navigating the colorschemes works fine.

With my little neovim lua knowledge, maybe we need to disable the backdrop on "colorschemes" arg, or render the backdrop window **after** the colored window, with the backdrop's z-index smaller than the colored window?

**Comment by ibhagwan** [comment]
> This only happens on opening, navigating the colorschemes works fine.

> With my little neovim lua knowledge, maybe we need to disable the backdrop on "colorschemes" arg, or render the backdrop window after the colored window, with the backdrop's z-index smaller than the colored window?

Trying to optimize the z-index or even debugging this issue is a waste of time IMHO, colorschemes are meant to change colors, if this flashes once on open I can live with this “bug”.

I’ll disable the backdrop for color schemes since I assume you’d want to preview the real colors.

**Comment by xuanhung1509** [comment]
Man, I love `fzf-lua` =))

**Comment by ibhagwan** [comment]
> Man, I love `fzf-lua` =))

Ty @xuanhung1509!
