### ISSUE TITLE
Not compatible with Lua 5.1

### ISSUE THREAD

**Issue by juru1234** [ibhagwan/fzf-lua#1346]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Hi, sadly this plugin isn't compatible with neovim built with Lua 5.1 (not with LuaJIT). Eg. Ubuntu 24.04 ships such a neovim version for ppc64el, riscv64 and s390x  (https://packages.ubuntu.com/noble/neovim) because LuaJIT isn't available on all architectures. Maybe you can add to the requirements, that Lua 5.2 or LuaJIT is needed for fzf-lua? I think the main problem here are the `goto`'s in the code.

**Comment by juru1234** [comment]
Lua 5.1 is also the default in neovim: https://neovim.io/doc/user/lua.html

**Comment by ibhagwan** [comment]
I had no idea this was a thing, I’ll look into it.

Any clues on how to build neovim without LuaJIT on my x64 would save me some research time :)

**Comment by juru1234** [comment]
Thank you. Sorry, I have no idea but I can try to look it up. I tried it on s390x Ubuntu.

**Comment by ibhagwan** [comment]
Btw, how do you manage your plugins? It seems `lazy.nvim` also doesn’t support Lua51:
https://github.com/folke/lazy.nvim/blob/9a374a0fb4d3ac42dac4a129d4bead7252473c77/lua/lazy/init.lua#L56
```lua
return vim.notify("lazy.nvim requires Neovim built with LuaJIT", vim.log.levels.ERROR, { title = "lazy.nvim" })
```

**Comment by ibhagwan** [comment]
Also Telescope, https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#getting-started:
```
Getting Started

This section should guide you to run your first builtin pickers.

Neovim v0.9.0 or the latest neovim nightly commit is required for telescope.nvim to work.
The neovim version also needs to be compiled with LuaJIT, we currently do not support Lua5.1 because of some ongoing issues.
```

**Comment by juru1234** [comment]
Yes, Lazy requires LuaJIT. I use VimPlug but also Packr should work. That's why I wanted to switch from Telescope to fzf-lua :D

**Comment by ibhagwan** [comment]
> Yes, Lazy requires LuaJIT. I use VimPlug but also Packr should work. That's why I wanted to switch from Telescope to fzf-lua :D

There aren’t any references to `jit` or `ffi` in the code, if it’s just the goto’s there is only a handful of locations which can be easily replaced with a condition, if you can help me test this theory with a git clone on your machine it would be very helpful until I figure out how to build without LuaJIT.

**Comment by juru1234** [comment]
This worked for me on x64:
```
cmake -S cmake.deps -B .deps -G Ninja -D CMAKE_BUILD_TYPE=Release -D USE_BUNDLED_LUA=ON
cmake --build .deps
cmake -B build -G Ninja -D PREFER_LUA=ON -D CMAKE_BUILD_TYPE=Release
cmake --build build
cmake --install build --prefix your/installation/path
```

**Comment by juru1234** [comment]
```
❯ ./nvim --version
NVIM v0.10.0
Build type: Release
Lua 5.1
Run "nvim -V1 -v" for more info
```

**Comment by ibhagwan** [comment]
Tyvm @juru1234! built successfully, I’ll see what I can do:
![IMG_2333](https://github.com/user-attachments/assets/6c937552-a4a1-4792-9bbe-935ad1c28164)

**Comment by juru1234** [comment]
Yeah, exactly the same error I ran into.... Thank you very much.

**Comment by ibhagwan** [comment]
@juru1234, try the latest commit https://github.com/ibhagwan/fzf-lua/commit/cfb213134534dbeee2657a57242bca2cf42fa1a8, I tested most pickers (that I could, no LSP, etc) and it seems to work.

There's a good chance some issue might still be lurking, for example, `string.format` with non-string args (works on LuaJIT) so we can keep this issue open until everything is ironed out.

**Comment by juru1234** [comment]
Thank you so much it works now! I tried LSP with code actions and diagnostics and this also works. Do you have an idea how I can test this `string.format` thing?

**Comment by ibhagwan** [comment]
> Thank you so much it works now! I tried LSP with code actions and diagnostics and this also works. Do you have an idea how I can test this `string.format` thing?

We’d have to search the entire code based for both `string.format` and `:format` and explore of the args have a possibility of being non-strings, I can only think think of one ATM where I intended to print the function address and use it as string key but there may be other unintentional args that may be nil by error.

If most things work I wouldn’t be too worried about it, keep using the plug-in and if something raises an exception open an issue and I’ll fix it.

**Comment by juru1234** [comment]
@ibhagwan I will stress test the setup next week :) 
Just for your information: https://github.com/neovim/neovim/issues/29817

**Comment by clason** [comment]
To be clear, plugins can absolutely require LuaJIT (if they have a good, documented, reason); they should just handle non-LuaJIT builds (which are to be assumed to be the default) gracefully like lazy.nvim and make this very clear in the README. It's just Neovim itself that guarantees Lua 5.1 compatibility _and nothing else_.

As for building Neovim against PUC Lua, see https://github.com/neovim/neovim/blob/5fc25ecc7a383a4bed2199774ed2e26022456ca3/.github/workflows/test.yml#L112.

**Comment by ibhagwan** [comment]
Ty @clason and @juru1234 for the linked discussions and raising my awareness about it, I don’t see any reason why fzf-lua wouldn’t be able to continue supporting non-LuaJIT builds, I personally dislike breaking changes and prefer adding support where possible, hell fzf-lua still works on neovim 0.5 (which I still test with the old AppImage) lol

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a8a3466f83bf7391bdceb5131d7edc4308ff5430

@juru1234, found one such instance, the `<F1>` help is generated automatically from the actions, if an action was set to a function without a description it would print `table:<addr>` or `function:<addr>` which abused the automatic `string.format` conversion.

**Comment by ibhagwan** [comment]
> @ibhagwan Is there a way to sponsor you and your project?

That would not be necessary @juru1234, but tysm for the compliment ❤️

**Comment by ibhagwan** [comment]
Closing as completed, @juru1234 feel free to reopen or open a new issue if you find any new errors with lua51.
