### ISSUE TITLE
Feature: search and paste bibtex entries

### ISSUE THREAD

**Issue by mathjiajia** [ibhagwan/fzf-lua#1347]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Similar to https://github.com/nvim-telescope/telescope-bibtex.nvim
but with fzf-lua

**Comment by ibhagwan** [comment]
This a somewhat esoteric extension that can be easily replicable with the `fzf_exec` API (and many other examples found in issues), that's why it exists as I do not wish to maintain every functionality imaginable.
