### ISSUE TITLE
Bug: broken preview border when leftcol > 0

### ISSUE THREAD

**Issue by librolibro** [ibhagwan/fzf-lua#1348]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-226+g7215512100

### Fzf version (`fzf --version`)

0.54.0 (9e92b6f1)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color="16,hl:-1:reverse,hl+:-1:reverse,fg+:15,bg+:0" --bind=ctrl-p:half-page-up --bind=ctrl-n:half-page-down --bind=ctrl-y:preview-up --bind=ctrl-e:preview-down --bind=ctrl-u:preview-ha lf-page-up --bind=ctrl-d:preview-half-page-down --bind=shift-tab:ignore --bind=tab:toggle

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  winopts = {
    preview = {
      horizontal = "left:60%",
    },
  },
  fzf_opts = {
    ["--no-hscroll"] = true,
  },
  keymap = {
    builtin = {
      -- ["<F2>"] = "toggle-fullscreen",
      ["<F5>"] = "toggle-preview-ccw",
      ["<F6>"] = "toggle-preview-cw",
      ["<C-y>"] = "preview-up",
      ["<C-e>"] = "preview-down",
      ["<C-u>"] = "preview-page-up",
      ["<C-d>"] = "preview-page-down",
    },
    fzf = {
      ["ctrl-p"] = "half-page-up",
      ["ctrl-n"] = "half-page-down",
      ["shift-tab"] = "ignore",
      ["tab"] = "toggle",
    },
  },
})
```

### Describe the bug / steps to reproduce

When there is 'wrap' option enabled (or if it's not but first screen column is actually the first one row column, **winsaveview()**.leftcol == 0) then everything is fine. But otherwise ('wrap' disabled and the buffer view is shifted to the right, e.g. with 'zl' keymap) then preview border is also shifting no matter what position (left/right/top/bottom) it has. Some images to demonstrate it.

Test buffer with this silly content:

![image](https://github.com/user-attachments/assets/b1ca8289-9171-4cea-8c8e-e156c3b5b242)

Wrap is enabled, everything if fine:

![image](https://github.com/user-attachments/assets/8b7523db-56fa-4a9e-a225-35f3f0d5e9e9)

Wrap is disabled, but **winsaveview()**.leftcol == 0 (also fine):

![image](https://github.com/user-attachments/assets/8a398c89-e6b9-411a-92a9-cdd2b1bc4916)

Wrap is disabled, line content is longer than the window width, some horizontal split was applied. That's where strange things happen:

![image](https://github.com/user-attachments/assets/6408ea39-6bed-4788-a21d-a9011f0c21ff)

Bottom preview is also have this "shifty" behavior and the more shift view has the more shift preview border will have :)

![image](https://github.com/user-attachments/assets/0f27126f-181d-4e37-860b-99923cd18b1c)

The screens were made on default configuration but my config (with left-side preview) also shows previews with this strange shift.

**Comment by ibhagwan** [comment]
Ty @librolibro, I will check why this happens, I’m a bit confused with your terminology though as when you write “wrap is enabled” the screenshot behavior displays a line with `nowrap` (one long line).

To clear, all I need to recreate this bug is a very long line (longer than current `columns` allow) and `:set nowrap`?

**Comment by librolibro** [comment]
Yeah, my fault, that was a mistyping :)

Yes, to reproduce this bug you need a long line, **'nowrap'** - and then you need to shift the buffer view (zh/zl or just jump forward on the line)

**Comment by librolibro** [comment]
I'll play with my config settings later - probably one of them causes this problem.

**Comment by ibhagwan** [comment]
> I'll play with my config settings later - probably one of them causes this problem.

Alright, lmk what you find out, once reproduced this is most likely an easy fix.

**Comment by librolibro** [comment]
```bash

**Comment by ibhagwan** [comment]
Tysm @librolibro! This is indeed reproduced only with `:setlocal`:
![IMG_2339](https://github.com/user-attachments/assets/9fc48b64-4a61-48bd-aa70-61f96de680bb)

Might be an upstream issue, I’ll do some digging.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5565f4bfe304df30c35962a982f14d8de1043336

@librolibro I have no idea why this fixed it, I had an old workaround that set the border wrap to `false` locally, for some reason it caused this behavior only when the originating window local `wrap` was also set, most likely an upstream issue but doesn't matter much as I'm going to remove the use of a separate border window anyways soon.

**Comment by librolibro** [comment]
Yeah, this commit fixed the problem, thanks a lot!
