### ISSUE TITLE
allow live_grep with cwd option

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#135]
Is it possible to allow `cwd` option with `live_grep` command? Sometimes I only want to grep search in a specific folder

```vim
nnoremap <silent> <leader>F  :lua require('fzf-lua').live_grep({ cwd = vim.fn.fnamemodify(vim.fn.bufname('%'), ':h') })<cr>
```

**Comment by ibhagwan** [comment]
It should have worked,  this is probably a bug, will keep you posted.

**Comment by ibhagwan** [comment]
Just tested this again thoroughly and it worked as expected, for example

```lua
:lua require('fzf-lua').live_grep({ cwd = "~/dots", search = "test" })`
```
![screenshot-1631722744](https://user-images.githubusercontent.com/59988195/133471267-3b5bc8bf-35a5-4847-bbf6-27c1d7097593.png)

With the current file parent command (as you posted):
```lua
:lua require('fzf-lua').live_grep({ cwd = vim.fn.fnamemodify(vim.fn.bufname('%'), ':h') })
```
![screenshot-1631722976](https://user-images.githubusercontent.com/59988195/133471778-2a54bd56-a35b-49b8-9d95-12278f15645f.png)

Btw there's a shorter version of your command (also worked for me):
```lua
:lua require('fzf-lua').live_grep({ cwd = vim.fn.expand('%:h') })
```

I tested with both 0.5 and the nightly, both worked - can you make sure your plugin is fully up to date?

**Comment by sandangel** [comment]
okay, I will try it again. thanks ^^

**Comment by ibhagwan** [comment]
> okay, I will try it again. thanks ^^

Let me know if you still need help or if it’s working as you expect we can close the issue.

**Comment by sandangel** [comment]
sorry I quit using fzf-lua because of various bugs at that time. Now I decided to give it a try and it's working properly. thank you very much... I think you have improved this plugin a lot. @ibhagwan. 

I was searching for this problem, then I found this issue and I didn't realize this is my own question. 😅. After I followed and it works properly, I thought "wait a minute..." then I saw my name as the author of the issue. 😆

**Comment by ibhagwan** [comment]
> sorry I quit using fzf-lua because of various bugs at that time. Now I decided to give it a try and it's working properly. thank you very much... I think you have improved this plugin a lot. @ibhagwan.

No worries @sandangel and ty for the kind words, this plugin has been through a lot since then, we’re now in issue number ~350, happy to hear it’s working as expected now :)
