### ISSUE TITLE
Bug: actions.resums inserts `i` character

### ISSUE THREAD

**Issue by TheBlob42** [ibhagwan/fzf-lua#1350]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.54.1 (also tested with 0.36.0)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
> The issue as not reproducible with `mini.sh` as we need a call to `fzf.actions.resume`


local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    }
end
vim.opt.runtimepath:prepend(lazypath)

require('lazy').setup({
    {
        -- fuzzy find stuff using `fzf`
        'ibhagwan/fzf-lua',
        config = function()
            local fzf = require('fzf-lua')
            local test = function()
                fzf.fzf_exec({ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, {
                    actions = {
                        ['default'] = {
                            function(selected)
                                print("selected: " .. selected[1])
                                fzf.files()
                            end,
                            -- this is the important line
                            -- commenting this "fixes" the issue
                            fzf.actions.resume
                        }
                    }
                })
            end
            vim.keymap.set('n', '<C-p>', test)
        end
    }
})
```

### Describe the bug / steps to reproduce

When using [actions.resume](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#action-resume) in any custom fzf call an `i` character is automatically inserted into the next input. A similar issue was reported to `fzf` [here](https://github.com/junegunn/fzf.vim/issues/1235) however the thread does not come to a "real" solution. Or at least none that I really understand :sweat_smile:  Furthermore the issue only occurred to me after an update of the `fzf-lua` plugin (I was for a long time on commit `9c005ec0` then updated to `023b9507`). Removing any call to `actions.resume` fixes the issue. Maybe you got an idea what introduced this behavior.

Here is an example video with the provided example configuration. You can see at the end that there is an `i` character which was not typed by the user:
https://github.com/user-attachments/assets/76e5a344-0ce3-4183-9cf3-9bf6855eb4a9

**Comment by ibhagwan** [comment]
While this may be a bug in detecting the current mode (had issues with this before), there’s a clear issue with your code, you’re attempting to open the interface twice, first by calling `files` and then `resume`, why do you need to call `resume`, it does nothing here as it will try to resume the newly opened `files`.

If you wish to resume the written query use `opts.last_query`:
```lua
                        ['default'] = {
                            function(selected, opts)
                                print("selected: " .. selected[1])
                                fzf.files({ query = opts.last_query }) -- this already opens the interface
                            end,
                        }
```

**Comment by TheBlob42** [comment]
I see that I misunderstood the use case for `resume` then. My thinking was that I would need to use it in order to avoid any "flashing" of the fzf window/split in case of calling fzf again from an action and that the resume call was required in order to prevent this.

I had this "wrong" code for months now and never realized it till I came across this "bug". Thanks for the clarification, this can be closed then :slightly_smiling_face:

**Comment by ibhagwan** [comment]
> I see that I misunderstood the use case for resume then. My thinking was that I would need to use it in order to avoid any "flashing" of the fzf window/split in case of calling fzf again from an action and that the resume call was required in order to prevent this.

> I had this "wrong" code for months now and never realized it till I came across this "bug". Thanks for the clarification, this can be closed then 🙂

Wrapping the function in `{}` or using `{ fn = <func>, noclose = true }` both prevent the flash, resume is used to continue where you left off (say you wanted to resume the original fzf_exec).

**Comment by TheBlob42** [comment]
That is what I already have, so no idea how I got the idea that I also need to add `resume` in this case. Thanks for making this clear and this awesome plugin that could not live without :heart:
