### ISSUE TITLE
Feature: Set custom headers

### ISSUE THREAD

**Issue by mosheavni** [ibhagwan/fzf-lua#1351]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

when I add a custom action, I want to see a hint for it, but the function to customize headers does not exist from my search.
can I optionally do something like:

```lua
require('fzf-lua').git_branches {
  actions = {
    ['ctrl-r'] = {
      fn = function(selected)
        -- some logic
      end,
      reload = true,
      header = 'to rename branch',
    },
    ['ctrl-d'] = {
      fn = function(selected)
        -- some logic
      end,
      reload = true,
      header = 'to delete branch',
    },
  },
}
```

thanks!

**Comment by mosheavni** [comment]
> You can add any header with `header = …`, for example `:FzfLua files header=foo`.
> 
> If you’re looking for custom header generation for actions that would require some work as I need to refactor how the toggle actions headers are generated.

the thing is I use some custom functions and a different cmd on my `git_branches` so I cannot call `:Fzflua git_branches` unfortunately.
Since I add these extra actions, I want to show them on the hint/header bar

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/81e7345697d65f6083c681995d230b2d73492233

@mosheavni, you can now add custom headers exactly as you specified in the OP.

```lua
:lua require("fzf-lua").files({
  actions={ ["alt-G"] = { fn=function(sel) print("sel",sel[1]) end, header="print"} }
})
```
![image](https://github.com/user-attachments/assets/c52e8103-e1f2-473a-9399-4f376c6d20a3)

For more complex headers (e.g. live_grep to grep) you can also provide a function and pass an object in the opts (or test against any known option/variable):
```lua
:lua require("fzf-lua").files({
  _myvar="foo", -- if you need to pass custom data
  actions={ 
    ["alt-G"] = {
      fn=function(sel) print("sel",sel[1]) end,
      header=function(o) return o._myvar end
    } 
  },
})
```
![image](https://github.com/user-attachments/assets/ad3e3bcf-2b90-439a-b329-a4075ab1e0e3)

**Comment by mosheavni** [comment]
awesome @ibhagwan !!!
I have a long header, any chance to break it into 2 lines?

**Comment by ibhagwan** [comment]
> awesome @ibhagwan !!! I have a long header, any chance to break it into 2 lines?

Yes, you need to supply `--header-lines` to tell fzf how many lines to set as header, you can send `\n` as part of the action header, just make sure to set the correct number of header lines:
```lua
:lua require("fzf-lua").files({ header="line1\nline2", fzf_opts={["--header-lines"]=2} })
```
![IMG_2365](https://github.com/user-attachments/assets/4affa927-70e6-4220-a13f-04996469d98c)

**Comment by ibhagwan** [comment]
I forgot you can utilize `header_separator` as `\n` and `header_ prefix` to remove the `::`, you don’t need to manually define anything:
```lua
require("fzf-lua").files({
  header_prefix =  "",
  header_separator = "\n",
  actions = {
    ["alt-G"] = { fn = function(sel) print("sel", sel[1]) end, header = "peform G" },
    ["alt-g"] = { fn = function(sel) print("sel", sel[1]) end, header = "peform g" },
    ["alt-y"] = { fn = function(sel) print("sel", sel[1]) end, header = "peform y" }
  }
})
```

![IMG_2368](https://github.com/user-attachments/assets/88e4f5fd-c573-45ee-9479-665847d795b3)

**Comment by ibhagwan** [comment]
@mhogeveen, I didn't take that into account as `fzf_exec` does the bare minimal setup of the options (highlights, headers, etc), for the time being you'd have to manually call the `set_header` func:
```lua
local opts = {
  path = "~/.config/nvim",
  prompt = 'Projects > ',
  actions = {
    ['default'] = function(selected)
      vim.cmd("cd " .. selected[1])
    end,
    ['ctrl-d'] = {
      fn = function()
        vim.cmd "cd ~/.dotfiles"
      end,
      header = "open dotfiles",
    },
  }
}

opts = require("fzf-lua").config.normalize_opts(opts, {})  -- Inherit global opts (highlights, etc)
opts = require("fzf-lua").core.set_header(opts, { "actions" })  -- Setup header string from actions tbl

require('fzf-lua').fzf_exec("ls " .. opts.path,
  vim.tbl_deep_extend("force", opts, {
    fn_transform = function(option)
      return opts.path .. '/' .. option
    end
  })
)
```

**Comment by mhogeveen** [comment]
@ibhagwan Works like a charm! Thanks a bunch

**Comment by ibhagwan** [comment]
> @ibhagwan Works like a charm! Thanks a bunch

I should probably make that work directly as you first posted, I’ll think about it :)

**Comment by gennaro-tedesco** [comment]
Is it possible that in syntax like
```lua
fn = function()
  vim.cmd 'cd ~/.dotfiles'
end,
header = 'open dotfiles',
```
the header only shows if the function is non-anonymous? Namely I have noticed that if
```lua
{...
fn = my_function_reference,
header = 'title'
}
```
then the `title` shows as registered and associated to the action keymap. If instead I assign an anonymous function
```lua
{...
fn = function(sel)
  my_function_reference(sel)
end,
header = 'title',
}
```
it does not.

**Comment by ibhagwan** [comment]
> Is it possible that in syntax like
> 
> fn = function()
>   vim.cmd 'cd ~/.dotfiles'
> end,
> header = 'open dotfiles',
> the header only shows if the function is non-anonymous? Namely I have noticed that if
> 
> {...
> fn = my_function_reference,
> header = 'title'
> }
> then the `title` shows as registered and associated to the action keymap. If instead I assign an anonymous function
> 
> {...
> fn = function(sel)
>   my_function_reference(sel)
> end,
> header = 'title',
> }
> it does not.

Use `header = function(opts) return "header"  end` you can inject a variable into opts or use any other logic you wish to return the header string.

**Comment by ibhagwan** [comment]
@gennaro-tedesco, see an example from the above post: https://github.com/ibhagwan/fzf-lua/issues/1351#issuecomment-2257295589

**Comment by gennaro-tedesco** [comment]
I have tried that too, however it still does not show. Does it make a difference if this is for a custom picker rather than a pre-defined one? Practically speaking the example is [here](https://github.com/gennaro-tedesco/nvim-possession/blob/e4f1a3eb8e8cce8bae1242725fa0e703ec78f4a9/lua/nvim-possession/init.lua#L180) (in one of my plugins, `nvim-possession`), where the injection does not show in the help (`F1`) even if I indicate it as `header = function(opts) return opts.var  end` (or hardcoded string).

Strangely enough, if the function signature of the action is a direct call to reference (without wrapping it in `function() ... end`) then all works smoothly 🤔

**Comment by ibhagwan** [comment]
> I have tried that too, however it still does not show. Does it make a difference if this is for a custom picker rather than a pre-defined one? Practically speaking the example is [here](https://github.com/gennaro-tedesco/nvim-possession/blob/e4f1a3eb8e8cce8bae1242725fa0e703ec78f4a9/lua/nvim-possession/init.lua#L180) (in one of my plugins, `nvim-possession`), where the injection does not show in the help (`F1`) even if I indicate it as `header = function(opts) return opts.var end` (or hardcoded string).
> 
> Strangely enough, if the function signature of the action is a direct call to reference (without wrapping it in `function() ... end`) then all works smoothly 🤔


Gotcha @gennaro-tedesco, open a feature request linking this issue and I’ll fix it

**Comment by gennaro-tedesco** [comment]
Thank you, I have opened https://github.com/ibhagwan/fzf-lua/issues/2311.
