### ISSUE TITLE
Bug: Incorrect FZF version mentioned in Dependencies in README.md

### ISSUE THREAD

**Issue by rrivas33** [ibhagwan/fzf-lua#1352]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux Ubuntu 22.04

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.29 (devel)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

The Dependencies section in the README.md files states the the fzf version required is > 0.25 which is not correct. When I tried running the fzf-lua plugin in neovim I get the following error:

```
[Fzf-lua] fzf error 2: unknown option: --no-scrollbar
```

It seems this option was added in [fzf 0.36.0](https://github.com/junegunn/fzf/blob/c50812518e8651fc681db3c26f37e4d143b75873/CHANGELOG.md?plain=1#L710).

**Comment by ibhagwan** [comment]
There is no such option added in fzf-lua, you’re probably using LazyVim or another distribution that adds it, why haven’t you tested with `mini.sh`?
