### ISSUE TITLE
Feature: Highlight grep string in default buffer preview

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#1354]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Currently when running `grep_cword` (as an example), and using the default settings, the word under the cursor is not highlighted in the preview. Here's an example where I searched for `\bsetup\b`:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e3946412-8223-42dc-a7b4-1d80924f302e">

I was wondering if it were possible to highlight the word in the preview. If there are performance issues, perhaps an option to trigger the highlight after a delay or a key press.

**Comment by ibhagwan** [comment]
> I was wondering if it were possible to highlight the word in the preview. If there are performance issues, perhaps an option to trigger the highlight after a delay or a key press.

Not a performance issue, currently the only information known to the previewer is the line/columns of the match, if you look carefully you can see the letter `s` is highlighted (using `FzfLuaCursor` hl group).

To achieve what you’re adter would require passing the current search regex to the previewer and also adjusting the `rg` regex to a vim style regex for match highlighting.

**Comment by kdheepak** [comment]
Thanks for the quick reply. The preview is a headless vim instance right? I guess I'm not sure what I should change to get this effect.

**Comment by ibhagwan** [comment]
> Thanks for the quick reply. The preview is a headless vim instance right? I guess I'm not sure what I should change to get this effect.

The preview is rendered on main insane but is triggered from fzf using a headless instance lua call, you don’t need to do anything, I have to explore this further :)

**Comment by ibhagwan** [comment]
Btw, you can see how it would look (and the code for it)  with `btags` (requires the `ctags` binary) as it searches for the tag using `vim.fn.match`.

I just realized it’s you @kdheepak, I was answering quickly on mobile and didn’t see the username :)

I’m traveling ATM so if you want to explore this there are a few ways we can do this, for live_grep we need to access `{q}` either by passing additional data or maybe using `opts.last_query` but I can’t recall ATM if it gets saved with each keystroke or just when the interface is closed/toggled, for all `grep_xxx` variants it should be easier as the regex can be found in `opts.search`.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/8f95109515301eea8c503fc4b17d6e51b54ef83a @kdheepak


![image](https://github.com/user-attachments/assets/9d5279db-3977-4af8-a8a9-39b05997a54a)
