### ISSUE TITLE
Bug: When a directory name contains multibyte characters, the shortened path displayed in prompt is wrong.

### ISSUE THREAD

**Issue by uga-rosa** [ibhagwan/fzf-lua#1355]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac M3

### Shell

fish

### Neovim version (`nvim --version`)

0.10.0

### Fzf version (`fzf --version`)

0.52.1 (6432f00)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--height 50% --reverse

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
As is.


require('fzf-lua').setup({})
```

### Describe the bug / steps to reproduce

It seems that if the directory name contains multibyte characters (e.g. `これは日本語です`), the first character is not taken correctly.
Characters are not displayed and the cursor position is off.

![image](https://github.com/user-attachments/assets/d174cdfd-a8dd-4854-8667-593a5661374b)

- Example when only the alphabet is used and not broken

![image](https://github.com/user-attachments/assets/1c085ed9-afe3-41c1-9dcb-acf51dbaf698)

The built-in function `pathshorten()` handles multibyte characters correctly. If your own pure Lua functions do not handle them well, this is a good choice.

**Comment by ibhagwan** [comment]
> The built-in function pathshorten() handles multibyte characters correctly. If your own pure Lua functions do not handle them well, this is a good choice.

Unfortunately that’s not a good choice, path manipulation happens inside a libuv callback, using `vim.fn.pathshorten` will result in:
```
E5560: Vimscript function must not be called in a lua loop callback
```

I’m sure I can fix it within the `path` module.

**Comment by uga-rosa** [comment]
Can `vim.schedule` help you?

Hope you can solve this problem. There are libraries like this one that may be of some help.
https://github.com/uga-rosa/utf8.nvim

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/57ed2503ce35d7a697d99810797bc12893cd16a6

@uga-rosa, should work as expected now.

**Comment by uga-rosa** [comment]
Thank you! It's no longer broken.

**Comment by ibhagwan** [comment]
> Thank you! It's no longer broken.

Ty for the update @uga-rosa!
