### ISSUE TITLE
Feature: layout similar to Telescopes .get_cursor() layout for spelling, LSP actions etc 

### ISSUE THREAD

**Issue by benfrain** [ibhagwan/fzf-lua#1356]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Recently swapped to fzf-lua and like it a lot. The only thing I really miss from Telescope is its [get_cursor()](https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#themes) theme option which is cursor relative and pops up a smaller window to select from. It is great for spelling suggestions and LSP code actions. Wonder if that is something that could potentially be added? Here is the original issue for the feature on Telescope: https://github.com/nvim-telescope/telescope.nvim/pull/878

**Comment by ibhagwan** [comment]
Already exists: `:FzfLua <xxx> winopts.relative=cursor`

**Comment by benfrain** [comment]
> Already exists: `:FzfLua <xxx> winopts.relative=cursor`

Is this in the docs? Just tried and it doesn't seem to do anything

```
km.set(
  "n",
  "<leader>s",
  ':lua require("fzf-lua").spell_suggest({ winopts = { relative = cursor } })',
  { desc = "Spell Suggesting" }
)
```

**Comment by ibhagwan** [comment]
> > Already exists: `:FzfLua <xxx> winopts.relative=cursor`
> 
> Is this in the docs? Just tried and it doesn't seem to do anything
> 
> ```
> km.set(
>   "n",
>   "<leader>s",
>   ':lua require("fzf-lua").spell_suggest({ winopts = { relative = cursor } })',
>   { desc = "Spell Suggesting" }
> )
> ```

Not in the docs but can be found in issues, it’s an argument to `nvim_open_win`, the way you set it up won’t work you have no variable named cursor, winopts.relative is a string argument so you have to wrap cursor in single or double quotes, i.e `'cursor'`

**Comment by ibhagwan** [comment]
See https://github.com/ibhagwan/fzf-lua/issues/545#issuecomment-1281230306

**Comment by benfrain** [comment]
That's perfect, thanks. Just in case it helps future travellers, here is some copy and paste goodness:

```
vim.keymap.set(
  "n",
  "<leader>s",
  ":lua require'fzf-lua'.spell_suggest({ winopts = {relative='cursor',row=1.01, col=0, height=0.2, width=0.2} })<cr>",
  { desc = "Spell Suggesting" }
)

```

**Comment by ibhagwan** [comment]
Ty @benfrain

**Comment by benfrain** [comment]
By the way, just recorded a video on migrating from Telescope to FZF-LUA https://youtu.be/pJincazaOaw

**Comment by ibhagwan** [comment]
> By the way, just recorded a video on migrating from Telescope to FZF-LUA https://youtu.be/pJincazaOaw

Great video @benfrain! While quickly skimming through I think you make a good case for changing the defaults for at least spell suggest to be relative to cursor.

LSP code actions might be a bit different as some might like a bigger window due to the preview of text edits.

**Comment by ibhagwan** [comment]
@benfrain, https://github.com/ibhagwan/fzf-lua/commit/1ac27d5734ccd057ef2b46a8644022913f37b89e
