### ISSUE TITLE
Sometimes it is resizing my other windows after closing fzf-lua

### ISSUE THREAD

**Issue by augustocdias** [ibhagwan/fzf-lua#136]
Hi,

Sometimes after I close the window from `fzf-lua` It resizes my windows and even pressing `<C-w>=` doesn't work to resize it back. I have to close the window and open a new one to make it back to what it was...

I suspect it has something to do with `nvim-tree` since the size of the window becomes the same.

![Screenshot 2021-09-15 at 15 10 42](https://user-images.githubusercontent.com/1080789/133439531-1c725d19-b8c8-4b6f-8ccc-5a5b36095009.png)
the grey boxes are just to not show the code since it is work related...

**Comment by ibhagwan** [comment]
> Sometimes after I close the window from fzf-lua It resizes my windows and even pressing <C-w>= doesn't work to resize it back.

Can you find a pattern in the issue or is it totally random, do you keep the tree open at all times when working?

I’ll do some testing on my end as well with nvim tree.

**Comment by ibhagwan** [comment]
I did some testing with `kyazdani42/nvim-tree.lua` and it seems to work fine no matter where I open the popup from.

Fzf-lua doesn't have any code to resize windows other than the fzf and popup window, is it possible you have some autocmd's running or that somehow the file is being opened inside the nvim-tree scratch buffer?

The more you can expand on when the issue happens the faster I'll be able to solve it.

**Comment by augustocdias** [comment]
I understand... I'm trying to find the pattern. So far it happened more often only on the first time, but it was not always... 

I don't have the tree opened at all times.

**Comment by ibhagwan** [comment]
Let me know what you find out.

**Comment by ibhagwan** [comment]
Is your nvim config on GitHub? Maybe it’s an interaction with some plugin? Might also help me solve issue #105.

**Comment by augustocdias** [comment]
Yes. Here:

https://github.com/augustocdias/dot-files/tree/main/.config/nvim

To reenable the shortcut in the terminal you can simply change the last line in the `term.lua` to:

```lua
vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
```

**Comment by augustocdias** [comment]
I have a suspicion. I disabled the auto open from nvim-tree and since then it hasn't happened again...

My workflow was:
1. Open an empty nvim
2. Run OpenSession my_project. This would restore previous window layouts and the tree would disappear
3. When I ran a command or open and cancel with fzf-lua, sometimes the issue would happen

**Comment by ibhagwan** [comment]
Are you referring to this option `nvim_tree_auto_open` in `nvim-tree`?

**Comment by augustocdias** [comment]
Yes

**Comment by ibhagwan** [comment]
Sorry for mixing the issues here (referring to #105), I just tried your config and still wasn't able to reproduce the orphaned preview window issue, however I did notice something that happens in your config that doesn't happen in my case and seems more related to this issue than #105.

When using `<C-p>` on a fresh instance of nvim, not selecting any file and closing with `<C-c>` will cause nvim to quit, I thought it was `let g:nvim_tree_auto_close = 1` but I have that in my config too and it doesn't seem to happen.

**Comment by augustocdias** [comment]
That didn't happen to me 😅

**Comment by ibhagwan** [comment]
What’s your neovim `:version`?

**Comment by augustocdias** [comment]
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```

**Comment by ibhagwan** [comment]
> ```
> NVIM v0.5.0
> Build type: Release
> LuaJIT 2.1.0-beta3
> Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
> Compiled by brew@BigSur
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"
> 
> Run :checkhealth for more info
> ```

Seems like default brew installation, nothing special here...

**Comment by ibhagwan** [comment]
> That didn't happen to me 😅

Ok so this one is the auto open feature combined with auto close, if no other buffer is open nvim tree will recognize it’s the only buffer and quit nvim, so technically it does what it’s supposed to do.

**Comment by ibhagwan** [comment]
> I have a suspicion. I disabled the auto open from nvim-tree and since then it hasn't happened again...

I'm going to close this issue until we can gather more info on what causes this behavior and whether this is an fzf-lua issue or nvim-tree/auto-open issue.

If you can find out what causes this or reproduce this consistently reopen this issue and I'll look more deeply into it.
