### ISSUE TITLE
Bug: Wrong matchparen highlight applied to backdrop

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#1361]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

v0.11.0-dev-509+gbdff50dee

### Fzf version (`fzf --version`)

v0.11.0-dev-509+gbdff50dee

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

0.53.0 (c4a9ccd)

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  fzf_colors = {
    bg = { 'bg', 'Normal' },
    gutter = { 'bg', 'Normal' },
    info = { 'fg', 'Conditional' },
    scrollbar = { 'bg', 'Normal' },
    separator = { 'fg', 'Comment' },
  },
})
```
I'm not including all of my configuration (since it's a bit long) but I think these are the only relevant to the issue. Let me know if you want me to provide something else.

### Describe the bug / steps to reproduce

Alright this is a strange one. It seems like the highlight applied with `MatchParen` is different with the picker backdrop.

Notice how the highlight applied to the closing brace matches what I set in the color theme:
![image](https://github.com/user-attachments/assets/4938e462-28f5-4f9a-a896-a50b1bc8b8b5)

Now notice what happens when I open the `lgrep_curbuf` picker:
![image](https://github.com/user-attachments/assets/5b73327f-6132-4301-b259-dc17a91750fc)

As you can notice, the matching pair is now underlined with red in line 117.

**Comment by ibhagwan** [comment]
Hi @MariaSolOs,

> Alright this is a strange one.

Indeed, TBH I don't know how much I can control this, I'm pretty sure that neovim changes these colors based on the amount `winblend` applied.

How does this look with different values, e.g. `:FzfLua files winopts.backdrop=30` (70/90/etc)?

How does it look with different backdrop hl, e.g. `:FzfLua files hls.backdrop=IncSearch winopts.backdrop=60`?

The code for this is pretty straight forward, mostly copied from lazy.nvim, as you can see it just sets it's own highlight and sets `winblend`:
https://github.com/ibhagwan/fzf-lua/blob/0c7cd0169cb8433f4f3b102bf6d4c0c7e0a20446/lua/fzf-lua/win.lua#L349-L364

**Comment by MariaSolOs** [comment]
> How does this look with different values, e.g. `:FzfLua files winopts.backdrop=30` (70/90/etc)?

I just tried changing tweaking this and it made no difference to the red underline. Same with changing the backdrop.

It's interesting because it doesn't happen with the floating terminal from lazy.nvim. I use it to display `lazygit`, and notice the lack of the underline in line 3:
![image](https://github.com/user-attachments/assets/4a3ea19b-7e60-4403-9c7d-363d515c347e)

Versus with `fzf-lua`:
![image](https://github.com/user-attachments/assets/2fb031ae-90cd-4635-86e7-9b29b8727cb4)

**Comment by ibhagwan** [comment]
Can you try and figure out what highlight group is that in your color scheme? If we can figure out the group I can attempt to see what triggers it.

**Comment by MariaSolOs** [comment]
I don't think it's set by my color theme because if I change the color in my palette I still see the same red color. I've tried going through the built-in highlight groups and I haven't seen anything suspicious. I also can't just `:Inspect` it since the backdrop doesn't let me focus the code :/

I know how weird this is and it's also not life-threatening, so I'm okay with leaving as is and I'll come back when I'm able to get more information.

**Comment by ibhagwan** [comment]
> I know how weird this is and it's also not life-threatening, so I'm okay with leaving as is and I'll come back when I'm able to get more information.

Sure, we can leave this open and investigate when inspiration for deep neovim exploration comes by, this will probably require reading the code of the runtime’s matchup and the events it triggers when losing focus - that would be my first hunch.

**Comment by ibhagwan** [comment]
Btw, if you disable match paren by adding `vim.g.loaded_matchparen=1` to your config, does the issue go away along with the plugin?

**Comment by MariaSolOs** [comment]
> Btw, if you disable match paren by adding `vim.g.loaded_matchparen=1` to your config, does the issue go away along with the plugin?

It does!

**Comment by ibhagwan** [comment]
> > Btw, if you disable match paren by adding `vim.g.loaded_matchparen=1` to your config, does the issue go away along with the plugin?
> 
> It does!

Then my initial guess of some autocmd in the MatchParen plugin is pretty close, at least we now know the entire “bug” is contained in one runtime file (AFAIK it’s a very small plugin).

**Comment by ibhagwan** [comment]
This file, my vinscript knowledge is pretty sparse but it’s only 265 lines, shouldn’t be hard to find the culprit:

https://github.com/neovim/neovim/blob/master/runtime/plugin/matchparen.vim

**Comment by MariaSolOs** [comment]
> This file, my vinscript knowledge is pretty sparse but it’s only 265 lines, shouldn’t be hard to find the culprit:
> 
> https://github.com/neovim/neovim/blob/master/runtime/plugin/matchparen.vim

Well my vimscript expertise is also quite poor hehe. What I don't understand is why the highlight differs from the one I have in my color theme.

**Comment by ibhagwan** [comment]
> Well my vimscript expertise is also quite poor hehe. What I don't understand is why the highlight differs from the one I have in my color theme.

Well, for that you’ll have to debug the file, should pretty easy with old school “comment until I find the code section doing X”

**Comment by MariaSolOs** [comment]
That's fair. I'll close this issue for now and investigate! Unfortunately the change would need to be done all the way in vim and then picked up by neovim, but oh well.

**Comment by ibhagwan** [comment]
If you find some variable or some harmless hack I can add to the backdrop window config / variables, lmk and I’ll be happy to add it to the code.

**Comment by MariaSolOs** [comment]
Okay I fixed it by changing using `{ sp = '#FFFFFF', underline = true }` instead of `{ fg = '#FFFFFF', underline = true }` when calling `vim.api.nvim_set_hl('MatchParen', opts)` (I want to underline the matching pairs with a white line). I think that the right way to indicate the color for the underline adornment is with the `sp` property, but for some reason it's only troublesome when the backdrop is applied (??).

Oh well, mystery solved. As always, thanks @ibhagwan for bearing with me <3

**Comment by ibhagwan** [comment]
Ty for the update @MariaSolOs 🎉
