### ISSUE TITLE
Feature: make globals.cwd accept a function instead of a string

### ISSUE THREAD

**Issue by alanfzf** [ibhagwan/fzf-lua#1366]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

As i was reading the [docs](https://github.com/ibhagwan/fzf-lua/blob/main/OPTIONS.md#global-options), i noticed that `globals.cwd` doesn't accept a function as a value to calculate the current working directory this makes specifiyng the root of your workspace a bit unflexible, and makes your keymaps be repetitive and a bit ugly, i was thinking that allowing this option to accept a function to calculate dynamically the current working directory would be awesome, and would make things a lot easier.

![image](https://github.com/user-attachments/assets/18c3d549-b21f-4402-b3cf-89f75837931f)

here is a example of the stuff that im facing right now:

![image](https://github.com/user-attachments/assets/00c25e3e-66be-44f9-ac38-af4102dcf620)

if i want all pickers that accept a cwd to have a [dynamic] default cwd, i would have to specify it in each one of them. instead of just putting it in the global section.

**Comment by ibhagwan** [comment]
This argument can be made for any option not just `cwd`, for static options set for everything (e.g. `file_icons`) you need to use the `setup.defaults` table (not directly in setup).

For dynamic options, send a function as `opts` and return all the options you want:
```lua
lua require("fzf-lua").files(function() return { cwd = "~/.config/nvim" } end)
```
