### ISSUE TITLE
Bug:   [Fzf-lua] Unable to init vim.regex with "myfunc -- spec/**", couldn't parse regex: Vim:E871: (NFA regexp) Can't have a multi follow a multi

### ISSUE THREAD

**Issue by aaronlifton** [ibhagwan/fzf-lua#1368]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-211+g37bf4c572

### Fzf version (`fzf --version`)

0.53.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

  --height=90% --layout=reverse --info=right --border rounded --margin=1   --color=bg+:#2d3f76   --color=bg:#1e2030   --color=border:#589ed7   --color=fg:#c8d3f5   --color=gutter:#1e2030   --color=header:#ff966c   --color=hl+:#65bcff   --color=hl:#65bcff   --color=info:#545c7e   --color=marker:#ff007c   --color=pointer:#ff007c   --color=prompt:#65bcff   --color=query:#c8d3f5:regular   --color=scrollbar:#589ed7   --color=separator:#ff966c   --color=spinner:#ff007c 

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
Default lazyvim fzf configuration (https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/fzf.lua), 
with additional configuration:

    opts = function(_, opts)
      opts.files.actions["alt-v"] = opts.files.actions["alt-h"]
      opts.files.actions["alt-h"] = nil
      opts.grep.actions["alt-v"] = opts.grep.actions["alt-h"]
      opts.grep.actions["alt-h"] = nil
    end,
```

### Describe the bug / steps to reproduce

When i search via `live_grep_glob` with `rg_glob = true, git_icons=false`, for something like `myfunc -- spec/**/*`, the following error pops up as a notification many times in a row:

The only other options I'm passing to live_grep_glob are custom actions.
```
Warn  11:33:32 notify.warn [Fzf-lua] Unable to init vim.regex with "myfunc -- spec/**/*", couldn't parse regex: Vim:E871: (NFA regexp) Can't have a multi follow a multi
```

This also happens when searching for `myfunc -- spec/**`, but it doesn't happen when no multi is used, ie. `myfunc -- spec/*/*`, but that doesn't recursively search directories.

I believe the recent change with the regex parsing might have caused this, as it wasn't happening before today. I was able to fix this on my machine by using commit `0c7cd0169cb8433f4f3b102bf6d4c0c7e0a20446`.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/508a842c3d3acb3ea99170e41d8ec9dc40cbb593

Ty for the report @aaronlifton, should be ok now, I missed the glob part when adding the improvement for #1354, the pattern should be highlighted properly now when globs are used.
