### ISSUE TITLE
Bug: fzf-lua 'lines' matches filenames

### ISSUE THREAD

**Issue by Grazfather** [ibhagwan/fzf-lua#1369]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.0

### Fzf version (`fzf --version`)

0.29.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

The Lines function works great, but I noticed if I want to search for a filename, and I have that file open, then it'll match against every line in the file. I think that it should probably only match the content of the file, or maybe have a config that allows it to only do that.
<img width="1166" alt="Screenshot_7_31_24__5_25 PM" src="https://github.com/user-attachments/assets/02ed8d31-408b-4c59-bf24-cb4ba164fc47">

**Comment by Grazfather** [comment]
Seems it's because the `bufname` is part of the entry, which we almost definitely want. I am not sure if there is a way to get the bufname (filename for `lines`) to show in the results without it being part of what fzf searches over. Since we are searching open files, then, maybe the buf number can be used instead of the filename.

**Comment by ibhagwan** [comment]
This is by design, since `lines` contains all buffers sometimes you may actually want to match on filenames.

If you wanna skip the filenames:
```lua
FzfLua lines fzf_opts.--with-nth=2..
```
For permanent setup:
```lua
require("fzf-lua").setup({
  lines = { fzf_opts = {["--with-nth"] == "2.." } },
})
```

**Comment by Grazfather** [comment]
That works brilliantly! Thank you.

**Comment by ArbitRandomUser** [comment]
i'm on the latest commit and i see that the behaviour is to not match the filenames anymore .

just thought i'd bring to notice since you said this is by design.

**Comment by ibhagwan** [comment]
> i'm on the latest commit and i see that the behaviour is to not match the filenames anymore .
> 
> just thought i'd bring to notice since you said this is by design.
> 
> (i prefer not matching filenames though)

I matched the layout/functionality with fzf.vim’s `Lines`, if someone wants the filename match they can run:
```vim
:FzfLua lines fzf_opts.--nth=2..
```

Also, if you don’t like the treesitter highlighting of the lines:

```vim
:FzfLua lines winopts.treesitter=false
```

**Comment by Grazfather** [comment]
I think @ArbitRandomUser  is implying that you don't need to do that anymore.
