### ISSUE TITLE
Bug: Manpages previewer does not work

### ISSUE THREAD

**Issue by WieeRd** [ibhagwan/fzf-lua#1372]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

Nushell (Also tried in Bash)

### Neovim version (`nvim --version`)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1720049189

### Fzf version (`fzf --version`)

0.54.0 (9e92b6f1)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  "telescope",
  winopts = { backdrop = 100 },
})
```

### Describe the bug / steps to reproduce

`:FzfLua manpages`
![image](https://github.com/user-attachments/assets/7e2e3864-c51f-48f6-9570-3abcdb6a0994)

`:FzfLua manpages previewer=man_native`
![image](https://github.com/user-attachments/assets/63e153a8-f4ef-44c6-8e11-cc87ee3eddac)

Only the preview is like that, upon `<CR>` the man page itself renders well.
What should I do to trace down more information about the problem?

**Comment by ibhagwan** [comment]
That’s a problem with your spesifc system, try to run in the shell `man -c nvim`, you’ll most like get the same error, once you fix that man previewer will work as expected.

**Comment by ibhagwan** [comment]
Btw, if `man nvim` works (without the `-c`) you can change your preview command:
```lua
require'fzf-lua'.setup({
  previewers = { man = { cmd = "man %s | col -bx" } },
})
```

**Comment by ibhagwan** [comment]
Also see https://github.com/ibhagwan/fzf-lua/issues/826#issuecomment-1650152071, the solution I posted above should work, feel free to reopen if you can’t fix it.

**Comment by WieeRd** [comment]
So this is mostly due to the difference between the 2 major provider of the `man` command: `man-db` and `mandoc`.
I tried both packages, with and without the `-c` flag. And it turns out `mandoc` actually works without the `-c` flag as well.
Is there a reason why you put this flag by default? Did it not use to work without it?

**Comment by ibhagwan** [comment]
> So this is mostly due to the difference between the 2 major provider of the `man` command: `man-db` and `mandoc`. I tried both packages, with and without the `-c` flag. And it turns out `mandoc` actually works without the `-c` flag as well. Is there a reason why you put this flag by default? Did it not use to work without it?

I don’t recall the exact reason, it was long time ago and I wasn’t aware of the many different man providers, user contributions helped sort it out as well, the fact this isn’t more of an issue tells me this is still rare so I’d like to avoid changing the command yet again only to find out some obscure man version on a Mac/Linux that doesn’t work as intended due to missing the `-c` arg.

**Comment by WieeRd** [comment]
Understandable, sometimes it's best to not change what has been working.

However, `man-db` is far more common than `mandoc` in many distros.
Ubuntu, Fedora, OpenSUSE etc. uses it by default, and on Arch `man-db` is in `core` while `mandoc` is in `extra`.
So I imagine this issue with the default option would apply to many people.
Although it's easy to fix it, it's nice to have a default working out of the box.

What do you think about setting a different option if `man-db` or macOS is detected and falling back to the current default otherwise? Would you accept it if I make a PR on it?

**Comment by ibhagwan** [comment]
> Understandable, sometimes it's best to not change what has been working.
> 
> However, `man-db` is far more common than `mandoc` in many distros. Ubuntu, Fedora, OpenSUSE etc. uses it by default, and on Arch `man-db` is in `core` while `mandoc` is in `extra`. So I imagine this issue with the default option would apply to many people. Although it's easy to fix it, it's nice to have a default working out of the box.
> 
> What do you think about setting a different option if `man-db` or macOS is detected and falling back to the current default otherwise? Would you accept it if I make a PR on it?

If you can detect it in a consistent manner that would be welcome, MacOS already has a different default:
https://github.com/ibhagwan/fzf-lua/blob/ae22b4bb8d7d514717253ff956ca3ce53fb01a30/lua/fzf-lua/defaults.lua#L169

The issue with such PR is that it would have to be done outside of the defaults as running man command at startup would affect neovim startup time when loading the plugin which wouldn’t be acceptable.

**Comment by WieeRd** [comment]
```lua
local t0 = os.clock()
local mandb = vim.fn.executable("mandb") == 1
local t1 = os.clock()
print(t1 - t0)
print(mandb)
```

```
3.0000000000197e-05
true
```

Yep, it should be fine.

**Comment by ibhagwan** [comment]
> ```lua
> local t0 = os.clock()
> local mandb = vim.fn.executable("mandb") == 1
> local t1 = os.clock()
> print(t1 - t0)
> print(mandb)
> ```
> 
>  ```
> 3.0000000000197e-05
> true
> ```
> 
> Yep, it should be fine.

Nope, this is on your machined, I had a vim.fn.executable call to detect git-delta and it caused a delay for some users so I changed to a lazy detection (you can see in the code).

This will have to be a function called on previewer init, like delta:
https://github.com/ibhagwan/fzf-lua/blob/ae22b4bb8d7d514717253ff956ca3ce53fb01a30/lua/fzf-lua/defaults.lua#L20-L23

**Comment by WieeRd** [comment]
Noted. I'll work on this tomorrow.

**Comment by ibhagwan** [comment]
@WieeRd, https://github.com/ibhagwan/fzf-lua/commit/afcc4b76ad3ab80526b6f1932a1514b22de8c187

If this still doesn't work feel free to submit a PR fixing this section:
https://github.com/ibhagwan/fzf-lua/blob/afcc4b76ad3ab80526b6f1932a1514b22de8c187/lua/fzf-lua/defaults.lua#L24-L39

**Comment by WieeRd** [comment]
Works great! Thank you for the quick response and fixes.
