### ISSUE TITLE
Feature: can calls to vim.lsp.buf.code_action() not invoke FZF?

### ISSUE THREAD

**Issue by benfrain** [ibhagwan/fzf-lua#1373]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I have the following mapping:

```lua
km.set("n", "<leader>ca", function()
  vim.lsp.buf.code_action()
end, { desc = "Code Actions" })
```

Before using FZF-LUA, this would bring up standard Neovim UI. Since switching to FZF-LUA, it brings up the code actions in a FZF-LUA window. Is there a way to stop it doing that?

**Comment by ibhagwan** [comment]
> Before using FZF-LUA, this would bring up standard Neovim UI. Since switching to FZF-LUA, it brings up the code actions in a FZF-LUA window. Is there a way to stop it doing that?

FzfLua does not take over the neovim UI unless you called `:FzfLua register_ui_select`, `:FzfLua lsp_code_actions` is technically a hack that registers for `ui.select` calls `vim.lsp.buf.code_action()` and deregisters from `ui.select’.

The only other reason you’re seeing fzf-lua is if you have `dressing.nvim` installed and fzf-lua set as its backend.

**Comment by benfrain** [comment]
Hmmm, very odd, I have dressing installed but haven't done anything beyond simply including it. But at least I know where to look now, thanks.

**Comment by ibhagwan** [comment]
> Hmmm, very odd, I have dressing installed but haven't done anything beyond simply including it. But at least I know where to look now, thanks.

If you setup `opts` in the lazy.nvim spec that would be calling it’s `setup` function which will auto detect fzf-lua and register for ui.select.
