### ISSUE TITLE
Bug: Can't use files cwd together with a vim.fn.stdpath

### ISSUE THREAD

**Issue by Balssh** [ibhagwan/fzf-lua#1375]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Arch Linux

### Shell

ZSH

### Neovim version (`nvim --version`)

NVIM 0.10.1

### Fzf version (`fzf --version`)

0.54

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

Nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
config = function()
      -- calling `setup` is optional for customization
      require('fzf-lua').setup {
        'fzf-native',
        defaults = {
          git_icons = false,
          file_icons = false,
          color_icons = false,
        },
      }
      require('fzf-lua').register_ui_select()
      vim.keymap.set('n', '<leader>sf', require('fzf-lua').files, { desc = '[S]earch [F]iles' })
      vim.keymap.set('n', '<leader>sg', require('fzf-lua').live_grep, { desc = '[S]earch by [G]rep' })
      vim.keymap.set('n', '<leader>sd', require('fzf-lua').diagnostics_document, { desc = '[S]earch [D]iagnostics' })
      vim.keymap.set('n', '<leader>sr', require('fzf-lua').resume, { desc = '[S]earch [R]esume' })
      vim.keymap.set('n', '<leader><leader>', require('fzf-lua').buffers, { desc = '[S]earch [B]uffers' })
      vim.keymap.set('n', '<leader>sw', require('fzf-lua').grep_cword, { desc = '[S]earch [W]ord' })
      vim.keymap.set('n', '<leader>s.', require('fzf-lua').oldfiles, { desc = '[S]earch Recent Files' })
      -- vim.keymap.set('n', '<leader>sn', require('fzf-lua').files { cwd = vim.fn.stdpath 'config' }, { desc = '[S]earch [N]eovim files' })
    end,
```

### Describe the bug / steps to reproduce

The line
```lua
vim.keymap.set('n', '<leader>sn', require('fzf-lua').files { cwd = vim.fn.stdpath 'config' }, { desc = '[S]earch [N]eovim files' })
```
Crashes NeoVim at start with the following error:
![image](https://github.com/user-attachments/assets/6c2a9ecb-7dcc-4edb-806a-742c886685c0)

The same concept works if I try:
```lua
:lua require('fzf-lua').files { cwd = vim.fn.stdpath 'config' }
```
Couldn't find something related to this and it's a bit frustrating as anything else worked perfectly.

**Comment by ibhagwan** [comment]
That’s not a bug with fzf-lua, it’s an issue with your confit/distribution, the error isnt in fzf-lua (from the screenshot you posted), as you also noted yourself running the below directly works.
```lua
:lua require('fzf-lua').files { cwd = vim.fn.stdpath 'config' }
```

**Comment by ibhagwan** [comment]
Btw, this is not how you define a keymap (read `:help vim.keymap.set`):
> This is wrong and why you have the error
```lua
vim.keymap.set('n', '<leader>sn', require('fzf-lua').files { cwd = vim.fn.stdpath 'config' },
  { desc = '[S]earch [N]eovim files' })
```

> Do this and it will work:

```lua

```lua
vim.keymap.set('n', '<leader>sn', function() require('fzf-lua').files { cwd = vim.fn.stdpath 'config' } end,
 { desc = '[S]earch [N]eovim files' })
```
