### ISSUE TITLE
Bug: Unable to send results to trouble.nvim

### ISSUE THREAD

**Issue by niba** [ibhagwan/fzf-lua#1376]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

mac

### Shell

fish

### Neovim version (`nvim --version`)

v0.10.0

### Fzf version (`fzf --version`)

0.46.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

LazyVim default configuration. Code from lazyvim repo
```lua
 if LazyVim.has("trouble.nvim") then
        config.defaults.actions.files["ctrl-t"] = require("trouble.sources.fzf").actions.open
      end
```

### Describe the bug / steps to reproduce

I'm unable to send results to trouble.nvim. I get an error every time I try to do it.

I use LazyVim and decided to try fzf.lua. I have the default configuration for both trouble.nvim and fzf.lua. I'm not sure if the bug is on fzf.lua's side or trouble.nvim's side, but Folke is on holiday until the end of August, so I decided to ask here first. Here is the link to the trouble action: https://github.com/folke/trouble.nvim/blob/main/lua/trouble/sources/fzf.lua

This is the log
```
   Error  08:20:02 notify.error [Fzf-lua] fn_selected threw an error: ...share/nvim/lazy/trouble.nvim/lua/trouble/sources/fzf.lua:55: attempt to perform arithmetic on field 'col' (a nil value)
stack traceback:
	...niba/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:237: in function '__sub'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/fzf.lua:55: in function 'item'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/fzf.lua:85: in function 'add'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/fzf.lua:107: in function 'fn'
	...a/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/actions.lua:87: in function 'act'
	...niba/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:148: in function 'fn_selected'
	...niba/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:230: in function <...niba/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:229>
	[C]: in function 'xpcall'
	...niba/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:229: in function <...niba/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:223>
```

**Comment by ibhagwan** [comment]
This issue should be opened in `trouble.nvim`, the code responsible for this isn’t in fzf-lua:
```
...share/nvim/lazy/trouble.nvim/lua/trouble/sources/fzf.lua:55
```

**Comment by ibhagwan** [comment]
For the upstream issue: the bug is most likely due to commit https://github.com/ibhagwan/fzf-lua/commit/2106d3dd5e44095f6b5c361e1a504398a70048b6 which doesn’t return line/col from `path.file_to_entry` so it’s required to check for their existence in the return table.

@niba, if you pin fzf-lua to commit https://github.com/ibhagwan/fzf-lua/commit/0c7cd0169cb8433f4f3b102bf6d4c0c7e0a20446 you probably won’t have this issue.

**Comment by ibhagwan** [comment]
@niba, can you try https://github.com/ibhagwan/fzf-lua/commit/580a20c58a714de566305756ad15384304ab9aae? Altough this is upstream, it is very likely a fix for this issue.

**Comment by niba** [comment]
@ibhagwan  error is fixed but I only open one entry

The action that is attached to the binding is here
https://github.com/folke/trouble.nvim/blob/6efc446226679fda0547c0fd6a7892fd5f5b15d8/lua/trouble/sources/fzf.lua#L115

and it uses this prefix
`local smart_prefix = require("trouble.util").is_win() and "transform(IF %FZF_SELECT_COUNT% LEQ 0 (echo select-all))"
  or "transform([ $FZF_SELECT_COUNT -eq 0 ] && echo select-all)"`

which was suggested in this issue #1241 

I believe it should open all results. Do you have any suggestions what I can do to try fix it?

**Comment by ibhagwan** [comment]
> Update:
I use the fish shell which doesn't support bash syntax. This can be a problem. I will test it later. I'm leaving this comment because it can be helpful for others

Unrelated

> Updating my fzf fixed the problems. Thanks

Correct, using `prefix` in actions require fzf 0.53:

https://github.com/ibhagwan/fzf-lua/blob/580a20c58a714de566305756ad15384304ab9aae/lua/fzf-lua/actions.lua#L24
