### ISSUE TITLE
buffers() fzf window exits insert mode when previewing a terminal buffer

### ISSUE THREAD

**Issue by mcchrish** [ibhagwan/fzf-lua#138]

**Comment by ibhagwan** [comment]
I tested buffers with terminals and had to apply a workaround to be able to scroll the window, does this happen all the time? When you scroll? Where does the focus go and do you have an ability to recover from the situation?

**Comment by mcchrish** [comment]
Probably "focus" is not the right term. Actually what happens is it exits insert mode in fzf window and goes to insert mode.
So every time I scroll into a terminal buffer, the window goes to normal mode. It's possible to recovery by going to insert mode again.

**Comment by ibhagwan** [comment]
Does this happen only after scrolling or simply having the buffer in the preview window causes this?

I’m still not happy with the way I was able to enable preview scrolling for terminal buffers and need to rework that.

**Comment by mcchrish** [comment]
Seems ok when I set `previewer = false`.

**Comment by ibhagwan** [comment]
> Seems ok when I set `previewer = false`.

Well of course it is preview related for sure, does this happen only on scrolling simply having the selected buffer a terminal?

**Comment by mcchrish** [comment]
Just checked, only happens on scrolling to a terminal buffer.

**Comment by ibhagwan** [comment]
> Just checked, only happens on scrolling to a terminal buffer.

Ty for letting me know, just the push I needed to finally fix the terminal buffer scrolling, I kept getting `Vim(normal):Can't re-enter normal mode from terminal mode` when trying to scroll the terminal buffer with `!norm ^D` so I had to implement an ugly workaround to "solve" that, it works in my case but I'm not totally surprised this has unintended consequences, the way it works is before issuing the scroll command it sends `<C-\\><C-n>` and then sends an `i` at the end to go back to insert mode which could potentially conflict with all sorts of mappings and autocmd's.

**Comment by ibhagwan** [comment]
Ok, so turns out that [this is a known neovim issue](https://github.com/neovim/neovim/issues/4895#issuecomment-303073838) and my ugly workaround using `feedkeys` is actually the way to go.

Now the only issue is why feeding the keys to exit insert mode and scroll is working but the last `i` to get back into insert mode doesn't work in your case, can you post the output of `:tmap`?

**Comment by ibhagwan** [comment]
I just committed a change to use `:startinsert` instead of `i` - can you update your plugin and let me know if that works for you?

**Comment by mcchrish** [comment]
No luck.

https://user-images.githubusercontent.com/7200153/133586094-5d04b9bb-9e80-42e7-b7bf-abe8199985ca.mov

**Comment by ibhagwan** [comment]
I honestly don’t know what causes this, when you preview scroll you should see the command typed in the `:` command line (due to `feedkeys`) - do you see it there? Does it contain `vim.cmd(“startinsert”)`?

**Comment by mcchrish** [comment]
I think some configuration of mine is actually influencing the behavior:
```vim
autocmd BufWinEnter,WinEnter * if &buftype == 'terminal' | startinsert | endif
autocmd BufLeave * if &buftype == 'terminal' | stopinsert | endif
```
It's a config where entering a terminal buffer will automatically starts in insert-mode.

A variation of this https://vi.stackexchange.com/a/3765

I'm willing to close this issue as I don't see the problem anymore when I remove these config. And I'm not a frequent user of built-in terminal anyway. But my concern is that this config is quite common enough that lots of people will encounter the same problem.

**Comment by mcchrish** [comment]
Maybe `noautocmd` option can help?
```
                              • `noautocmd` : If true then no buffer-related
                                autocommand events such as |BufEnter|,
                                |BufLeave| or |BufWinEnter| may fire from
                                calling this function.
```

**Comment by ibhagwan** [comment]
The terminal scroll command is (and was) already sent with `noautocmd` (shortened to `noa`):

https://github.com/ibhagwan/fzf-lua/blob/c4a829e83e5ef7b269287fbd32ac4c76a8a77594/lua/fzf-lua/previewer/builtin.lua#L235-L236

I don’t think there’s much I can do in this case, the `nvim_win_call` probably causes a window switch thus triggering a `BufLeave` which triggers your auto command.

Maybe you can exclude the autocmd from running on buffers with `filetype = fzf`?

**Comment by mcchrish** [comment]
> Maybe you can exclude the autocmd from running on buffers with `filetype = fzf`?

Still doesn't work. I'll be removing the autocmd since I'm not using it that much anyway.
