### ISSUE TITLE
Feature: ability to pass argument for specific table of files to be searched

### ISSUE THREAD

**Issue by l-bowman** [ibhagwan/fzf-lua#1383]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Sorry in advance if this is already in the issues - I looked and couldn't find it. I'd like to be able to pass a custom table of files in an argument as the basis for a grep or inverse grep search. In practice, I want to grep or inverse grep the file contents of files within a quickfix list. Here is how I achieve this with Telescope:      

```lua
      local builtin = require("telescope.builtin")

      local search_qflist = function(mode)
        local qflist = vim.fn.getqflist()
        local filetable = {}
        local hashlist = {}

        for _, value in pairs(qflist) do
          local name = vim.api.nvim_buf_get_name(value.bufnr)

          if not hashlist[name] then
            hashlist[name] = true
            table.insert(filetable, name)
          end
        end

        local args = { search_dirs = filetable }

        if mode == "live_grep" then
          builtin.live_grep(args)
        elseif mode == "inverse_live_grep" then
          args.additional_args = { "--files-without-match" }
          builtin.live_grep(args)
        elseif mode == "find_files" then
          builtin.find_files(args)
        else
          print("Invalid mode specified")
        end
      end
```

**Comment by ibhagwan** [comment]
No such option unfortunately, you can probably achieve that with a custom script but that’s not something I wish to do or maintain.

An alternative that IMHO solves 99% of the use cases is using live grep with a glob (to narrow down the selected list of files) and then switching to fuzzy grep with a narrowed down set.

Closing as not planned.

**Comment by l-bowman** [comment]
> No such option unfortunately, you can probably achieve that with a custom script but that’s not something I wish to do or maintain.
> 
> An alternative that IMHO solves 99% of the use cases is using live grep with a glob (to narrow down the selected list of files) and then switching to fuzzy grep with a narrowed down set.
> 
> Closing as not planned

I work on a huge project and use this type of recursive searching all the time to narrow down a subset of files with a particular pattern. I can't justify switching from Telescope until I find a way to replicate this feature. Commonly, I might start by generating a quickfix list of certain file types by name or extension, refine this list with a grep of their contents, refine again with an inverse grep for a pattern that I don't care about, etc. It's an extremely fast an effective approach for identifying all instances of a particular pattern and modifying it.

**Comment by ibhagwan** [comment]
> > No such option unfortunately, you can probably achieve that with a custom script but that’s not something I wish to do or maintain.
> > An alternative that IMHO solves 99% of the use cases is using live grep with a glob (to narrow down the selected list of files) and then switching to fuzzy grep with a narrowed down set.
> > Closing as not planned
> 
> I work on a huge project and use this type of recursive searching all the time to narrow down a subset of files with a particular pattern. I can't justify switching from Telescope until I find a way to replicate this feature. Commonly, I might start by generating a quickfix list of certain file types by name or extension, refine this list with a grep of their contents, refine again with an inverse grep for a pattern that I don't care about, etc. It's an extremely fast an effective approach for identifying all instances of a particular pattern and modifying it.

I understand, but for performance reasons this would have to be done at a shell solution level as it needs to run as a separate command, otherwise spawning the process one by one for the quick fix list will lead to horrible performance.

This also means I’ll have to find a solution for windows for this, overall not something I wish on doing ATM.

>  I can't justify switching from Telescope until I find a way to replicate this feature. 

Totally understand and there’s nothing wrong with that.

That said, you can easily craft a chained shell command (using `&&`) to search all the quick fix files/directories, probably an hour of work if you’re proficient in shell and some neovim API to enumerated the qf, I just don’t want to get into that rabbit hole with windows and the endless customization requests that will follow such feature.

**Comment by l-bowman** [comment]
No worries. Thanks for the feedback.

**Comment by ibhagwan** [comment]
Actually this is much simpler than I previously thought and can be achieved without command chaining and can work on windows seamlessly with both `grep` and `rg` using the `-r` option, both the below produce the required result:
```sh
grep -r "fzf-lua" ~/.config/nvim/lua/plugin ~/.local/share/nvim
rg -r "fzf-lua" ~/.config/nvim/lua/plugin ~/.local/share/nvim
```

I’ll add this option as well as a `grep_quicfix` / `lgrep_quickfix` pickers.

**Comment by l-bowman** [comment]
> Actually this is much simpler than I previously thought and can be achieved without command chaining and can work on windows seamlessly with both `grep` and `rg` using the `-r` option, both the below produce the required result:
> 
> ```shell
> grep -r "fzf-lua" ~/.config/nvim/lua/plugin ~/.local/share/nvim
> rg -r "fzf-lua" ~/.config/nvim/lua/plugin ~/.local/share/nvim
> ```
> 
> I’ll add this option as well as a `grep_quicfix` / `lgrep_quickfix` pickers.

Cool! Any method of searching that operates on the contents of a quickfix list unlocks a lot of power since the results can be refined again and again through any series of filters. Being able to see the results generate in real time in a live window would be so great. Thanks!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/98c1beb226783603d3759c5b39aa5d96e8e4d611

@l-bowman see the above commit notes for more info, should be self explanatory and you probably won't need any custom code (from the OP) due to `grep_quickfix` and `lgrep_quickfix`.

**Comment by ibhagwan** [comment]
Btw, important to note that I opted to unlike `lgrep_curbuf` I opted to share the resume data so running `:FzfLua lgrep_quickfix resume=true` will continue using the previous live grep regex / fuzzy query. This behavior made sense to me but I’m open to quickfix / loclist having separate resume data.

**Comment by ibhagwan** [comment]
> Thanks for working on this!

Try it out and lmk if this solves your issue?

**Comment by l-bowman** [comment]
> > Thanks for working on this!
> 
> Try it out and lmk if this solves your issue?

Is there a way to perform a files-type search on a quickfix list?

**Comment by ibhagwan** [comment]
> > > Thanks for working on this!
> > 
> > 
> > Try it out and lmk if this solves your issue?
> 
> Is there a way to perform a files-type search on a quickfix list? It's helpful to go back to a view of just the files with a pattern after performing a sequence of refinements on the quickfix list.

The glob search works with `lgrep_quickfix`, if you set `grep.rg_glob = true` (in setup), you can type `foo -- *.lua` to limit your search to lua files.

You can also run `:FzfLua lgrep_quickfix rg_glob=true` for the same effect.

**Comment by l-bowman** [comment]
> > Thanks for working on this!
> 
> Try it out and lmk if this solves your issue?

One more thing I am trying to test. How do I invert searches such as file search, grep, and live_grep?

**Comment by ibhagwan** [comment]
For live_grep you’ll need to use regex inversion or you can replace `rg_glob_fn` to accept raw rg args and supply the rg invert flag (can’t recall ATM which flag that is):
https://github.com/ibhagwan/fzf-lua/wiki#live-grep-custom

In regular grep (I.e fuzzy) you can use `!` for exclusion and then space with your next search: `!foo bar` - exclude foo, fuzzy match bar.
