### ISSUE TITLE
Feature: support sorting results for builtin action 'file_sel_to_qf' 

### ISSUE THREAD

**Issue by n00bmind** [ibhagwan/fzf-lua#1388]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

One of the features I love of this plugin is the ability to send the query results to the quickfix window, however when doing so all the results get scrambled and end up in a random order, meaning if I want to traverse said results with :cn / :cp I'll be jumping around my entire codebase like crazy, which was driving me a bit nuts.

I was surprised to see that apparently nobody has mentioned this issue before, so it may be something weird in my configuration? (my config for fzf-lua itself is really pretty basic..)

Anyway, I thought this should be a relatively easy add as an config option, so you may want to consider that.. in any case, I've written a little workaround for the time being, and I thought I'd share it to see if it may help others, or perhaps in case there's a better way to do what I'm trying to do..

Here's what I'm doing:

in config/nvim/lua/utils.lua:
```
vim.cmd[[
    function! CompareQuickfixEntries(i1, i2)
        if bufname(a:i1.bufnr) == bufname(a:i2.bufnr)
            return a:i1.lnum == a:i2.lnum ? 0 : (a:i1.lnum < a:i2.lnum ? -1 : 1)
        else
            return bufname(a:i1.bufnr) < bufname(a:i2.bufnr) ? -1 : 1
        endif
    endfunction

    function! SortQFList()
        let sortedList = sort(getqflist(), 'CompareQuickfixEntries')
        " Replace existing list
        call setqflist(sortedList, 'r')
    endfunction
]]

-- Sort QF entries by file,line
function M.sort_qf()
    vim.fn.SortQFList()
end
```
(I know you can probably achieve the same using lua only, but I couldnt be bothered..)

then in the config for fzf-lua:
```
                defaults = {
                    formatter = "path.filename_first",
                    -- Open QF in a split and sort results by file / line
                    copen = function(selected, opts)
                        require('utils').sort_qf()
                        vim.cmd('botright copen')
                    end,
                    actions = {
                        -- Send results to quickfix list
                        ['ctrl-q'] = {
                            fn = actions.file_sel_to_qf, prefix = 'select-all+'
                        },
                    },
                },
```

**Comment by ibhagwan** [comment]
It’s a good idea to be done as a default, I don’t think this needs a config option, I don’t think anyone will complain they need the list unordered, and if so we can revisit adding an option then.

**Comment by ibhagwan** [comment]
@n00bmind, https://github.com/ibhagwan/fzf-lua/commit/f3e630cdbd5da1a8252d970f90aa85626593affd adds default sorting by filename/line/col.

**Comment by n00bmind** [comment]
wow, thanks for the extremely fast turnaround!
