### ISSUE TITLE
Bug: 'error executing luv callback' in live_grep with mini.icons

### ISSUE THREAD

**Issue by nimr0d** [ibhagwan/fzf-lua#1391]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

linux (NixOS-unstable)

### Shell

fish

### Neovim version (`nvim --version`)

v0.11.0-nightly+b991319

### Fzf version (`fzf --version`)

0.54.3

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--bind=alt-e:down --bind=alt-i:up

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    defaults = {
    file_icons = 'mini',
  },
})
```

### Describe the bug / steps to reproduce

Typing a few non-alphanumeric regex characters in the live grep causes this error message with a stack traceback to show up in the left search window.

Further attempts to start any instance of fzf-lua crash due to MiniIcons:load_icons receiving a 'self._state' with value vim.NIL.

**Comment by ibhagwan** [comment]
> Typing a few non-alphanumeric regex characters in the live grep causes this error message with a stack traceback to show up in the left search window.


It would be helpful if you can provide the full stack trace from `:messages` and better yet if you can provide exact steps for me to reproduce this (does it fail due to a specific file? etc).

**Comment by ibhagwan** [comment]
> I don't know how to copy the stack trace, but here is a screenshot. I'm not sure how helpful it is.

I need to see the line and column where it fails in the code, can you close the preview with F4 and also press `ctrl-/` to enable wrap and screenshot again?

Also, any specific steps I can reproduce this, any extension this fails on or is it random?

**Comment by ibhagwan** [comment]
That’s much better I can see which lines are failing.

If you change to devicons does it work?

**Comment by ibhagwan** [comment]
@nimr0d, should work as expected with https://github.com/ibhagwan/fzf-lua/commit/64a305a2490e48c44be9f5a489e01b995dd58c92, lmk if otherwise?
