### ISSUE TITLE
Bug: 'Process failed to start' on MSYS2

### ISSUE THREAD

**Issue by drop-stones** [ibhagwan/fzf-lua#1396]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Windows

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.54.3 (af4917d)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Describe the bug / steps to reproduce

I am using nvim on [msys2](https://www.msys2.org/docs/what-is-msys2/), which is a unix-like environment on Windows.
After installing fzf-lua and running fzf, I get the following error.

command: `:FzfLua files`

Error Log:
```log
Error executing Lua callback: ...nvim\site\pack\vendor\start\fzf-lua/lua/fzf-lua/core.lua:242: Vim:E903: Process failed to start: unknown error: "C:\Users\s2h6i\scoop\apps\msys2\2024-07-27\usr\bin\cmd"
stack traceback:
        [builtin#36]: at 0x7ffc6fd82f80
        ...nvim\site\pack\vendor\start\fzf-lua/lua/fzf-lua/core.lua:242: in function <...nvim\site\pack\vendor\start\fzf-lua/lua/fzf-lua/core.lua:221>
        ...\nvim\site\pack\vendor\start\fzf-lua/lua/fzf-lua/cmd.lua:35: in function 'run_command'
        ...p\nvim\site\pack\vendor\start\fzf-lua\plugin\fzf-lua.lua:12: in function <...p\nvim\site\pack\vendor\start\fzf-lua\plugin\fzf-lua.lua:11>
```

This error is reproducible with `mini.sh` (`sh` can be used in msys2).
I expect the error is due to the handling of paths and special characters, but I don't know the details.

Also, there is no problem using fzf-lua on powershell (and using telescope.nvim on msys2/powershell).

**Comment by ibhagwan** [comment]
> I expect the error is due to the handling of paths and special characters, but I don't know the details.

I doubt this is the issue, it seems it cannot run `cmd.exe` inside the MSYS2 env?

I’m wondering if the env is considered windows or Unix by neovim, can you run the below and lmk the output of the various commands?

```lua
:= vim.fn.has("win32")
:= vim.fn.has("win64")
:= vim.fn.executable(‘cmd.exe')
:= vim.fn.executable(‘sh')
:!cmd
:!sh -c ls
```

**Comment by ibhagwan** [comment]
It might msys2 path translation after all, can you try setting the below and seeing if fzf-lua works after?
```lua
:lua vim.env.MSYS2_ARG_CONV_EXCL='*'
-- should print *
:= os.getenv('MSYS2_ARG_CONV_EXCL')
```

**Comment by drop-stones** [comment]
> can you run the below and lmk the output of the various commands?

Here are the results:

```
:= vim.fn.has("win32")
1

:= vim.fn.has("win64")
1

:= vim.fn.executable(‘cmd.exe')
1

:= vim.fn.executable(‘sh')
1

:!cmd /c dir
Microsoft Windows [Version 10.0.22631.3958]
(c) Microsoft Corporation. All rights reserved.
%F{green}%n@%m%f %F{magenta}MINGW64%f %F{yellow}%~%f %# 

:!sh -c ls
error.log
init.lua
lazy-lock.json
lazyvim.json
LICENSE
lua
README.md
stylua.toml
```

>  can you try setting the below and seeing if fzf-lua works after?

fzf-lua did not work and output the same error.

```
E5108: Error executing lua: ...ppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/core.lua:242: Vim:E903: Process failed to start: unknown error: "C:\Users\s2h6i\scoop\apps\msys2\2024-07-27\usr\bin\cmd"
stack traceback:
	[builtin#36]: at 0x7ffc6fc62f80
	...ppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/core.lua:242: in function 'open'
	...a/Local/nvim-data/lazy/LazyVim/lua/lazyvim/util/pick.lua:75: in function 'open'
	...a/Local/nvim-data/lazy/LazyVim/lua/lazyvim/util/pick.lua:83: in function <...a/Local/nvim-data/lazy/LazyVim/lua/lazyvim/util/pick.lua:82>
```

**Comment by ibhagwan** [comment]
Interesting results, I’m still unsure why this fails but the code is obviously treating MinGW as windows and tries to execute via cmd.exe.

Can you post the result of `:= vim.fn.executable('mkfifo')`?, I’m thinking we can treat this as WSL and run fzf-lua as if it was on Linux/Mac.

**Comment by drop-stones** [comment]
The result of  `:= vim.fn.executable('mkfifo')` is `1` in msys2 and WSL2.
But the result is `0` in powershell.

**Comment by ibhagwan** [comment]
> The result of `:= vim.fn.executable('mkfifo')` is `1` in msys2 and WSL2. But the result is `0` in powershell.

Perfect, I think we can treat MinGW as a *NIX/BSD env, when I get home later I’ll create a branch that tests this theory and if it works for you we can merge it.

**Comment by ibhagwan** [comment]
If you wish to help me and save some time it would be great to determine the best way to detect an MSYS2/MinGW env, perhaps an environment variable that exists only on MSYS2 env?

**Comment by ibhagwan** [comment]
Perhaps checking for environment variables `MSYSTEM` or `MSYS_HOME`?

Can you check the return val of `:= vim.env.MSYSTEM` and `:= os.getenv('MSYSTEM')` (should be the same)?

**Comment by ibhagwan** [comment]
Can you try the [`msys2` branch](https://github.com/ibhagwan/fzf-lua/tree/msys2)?

**Comment by drop-stones** [comment]
> If you wish to help me and save some time it would be great to determine the best way to detect an MSYS2/MinGW env, perhaps an environment variable that exists only on MSYS2 env?
> Perhaps checking for environment variables MSYSTEM or MSYS_HOME?

Sorry for the late replying.
Yes, I think `MSYSTEM` is correct.
FYI: https://stackoverflow.com/questions/65527286/how-to-check-if-my-program-is-running-on-mingwor-msys-shell-or-on-cmd

> Can you check the return val of := vim.env.MSYSTEM and := os.getenv('MSYSTEM') (should be the same)?

Both had the same value, `MINGW64` (my subsystem name).

> Can you try the [msys2 branch](https://github.com/ibhagwan/fzf-lua/tree/msys2)?

I tried, but another error occured.

```
E5108: Error executing lua: ...ppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/core.lua:242: Vim:E475: Invalid argument: expected valid directory
stack traceback:
	[builtin#36]: at 0x7ffc5ade2f80
	...ppData/Local/nvim-data/lazy/fzf-lua/lua/fzf-lua/core.lua:242: in function 'open'
	...a/Local/nvim-data/lazy/LazyVim/lua/lazyvim/util/pick.lua:75: in function 'open'
	...a/Local/nvim-data/lazy/LazyVim/lua/lazyvim/util/pick.lua:83: in function <...a/Local/nvim-data/lazy/LazyVim/lua/lazyvim/util/pick.lua:82>
```

The directory path may have a windows-style path.
FYI: https://www.msys2.org/docs/filesystem-paths/

If you need any confirmation, I can help!

**Comment by ibhagwan** [comment]
> The directory path may have a windows-style path.

If I have to deal with paths conversion again I don’t think I can solve it blind without access to a Windows with MSYS2 installed.

I’m wondering which path is better, making the original error (cmd.exe) to work or making `sh` work.

In any event I don’t know how much time I have to dedicate for this ATM as I have no access to the windows VM I used for development anymore.

**Comment by ibhagwan** [comment]
Looking at the original error I think it fails as it’s trying to run a `cmd` that isn’t cmd.exe but some other cmd command that’s part of msys2?

As an experiment, can you run the original branch and either fix neovim PATH so `cmd.exe` is first (`C:\Windows\System32`?) or temporarily rename the cmd in the scoop directory so it doesn’t get called `C:\Users\s2h6i\scoop\apps\msys2\2024-07-27\usr\bin\cmd`?

**Comment by drop-stones** [comment]
> As an experiment, can you go back to fzf-Lia’s main branch and either fix neovim PATH so cmd.exe is first (C:\Windows\System32?) or temporarily rename the cmd in the scoop directory so it doesn’t get called C:\Users\s2h6i\scoop\apps\msys2\2024-07-27\usr\bin\cmd?

It works without error!!
In msys2, `cmd` exist in `/usr/bin` but `cmd.exe` only exist in `/c/Windows/system32/`.

```
❯ where cmd
/usr/bin/cmd
/bin/cmd
/c/Windows/system32/cmd
❯ where cmd.exe
/c/Windows/system32/cmd.exe
```

So we need to change `cmd` to `cmd.exe` to fix this error.

**Comment by ibhagwan** [comment]
> So we need to change cmd to cmd.exe to fix this error.

I guessed it would work and was already ahead of it :)

can you try https://github.com/ibhagwan/fzf-lua/commit/02b6c780687a1bacf4ece1072f0a3da5ae3fe900? If it works I’ll merge to main.

**Comment by ibhagwan** [comment]
Actually since you said `cmd.exe` works I removed the `C:\windows\system32` part in https://github.com/ibhagwan/fzf-lua/commit/4fd77178eeabfaf41bb251639687ef8de456d94e, so just try latest on msys2 branch?

**Comment by drop-stones** [comment]
I have confirmed that `files/grep` command works in msys2/powershell with https://github.com/ibhagwan/fzf-lua/commit/0b13c6e1ceffd5abf799e9966d4185fcd9fe682f !!

Thank you for the quick response :)

**Comment by ibhagwan** [comment]
> I have confirmed that `files/grep` command works in msys2/powershell with [0b13c6e](https://github.com/ibhagwan/fzf-lua/commit/0b13c6e1ceffd5abf799e9966d4185fcd9fe682f) !!
> 
> Thank you for the quick response :)

Fantastic, fixed the commit message and will merge in a sec.

**Comment by ibhagwan** [comment]
Merged, ty for the debugging efforts!
