### ISSUE TITLE
Feat request: Add a fuzzy finder over available commands (builtins)

### ISSUE THREAD

**Issue by shadmansaleh** [ibhagwan/fzf-lua#14]
Can you please add a fuzzy finder that shows currently available [commands](https://github.com/ibhagwan/fzf-lua#commands) . like telescopes builtins ?

That will make newer commands more discoverable :)

Also I think a ex command like `:Telescope` will be awesome .

**Comment by ibhagwan** [comment]
These are good ideas, once I’m done adding providers I’ll add those as well.

A couple days ago I added one of my larger batch of commands for the builtin LSP but there are still many more to add which you can see in the [TODO section](https://github.com/ibhagwan/fzf-lua#TODO)

**Comment by gegoune** [comment]
It's on the todo list.

**Comment by shadmansaleh** [comment]
> A couple days ago I added one of my larger batch of commands for the builtin LSP

That's the thing . I just came for a revisit on the repo and saw the newer addition, thought to myself ohh I didn't know these were available . That made me realize I was really missing telescopes buitins.

**Comment by ibhagwan** [comment]
> > A couple days ago I added one of my larger batch of commands for the builtin LSP
> 
> That's the thing . I just came for a revisit on the repo and saw the newer addition, thought to myself ohh I didn't know these were available . That made me realize I was really missing telescopes buitins.

Totally understandable, I sometimes work fast so it won't be long hopefully :-)

**Comment by ibhagwan** [comment]
```lua
:lua require('fzf-lua').builtin()
```

Also accepts additional options (windows layout, prompt, etc):
```lua
:lua require('fzf-lua').builtin({winopts = {win_height = 0.55, win_width = 0.30}})
```
