### ISSUE TITLE
Fd search from git root, if not found falling back to the current dir?

### ISSUE THREAD

**Issue by winston0410** [ibhagwan/fzf-lua#140]
I want to make my `fd` search starts in the directory from where my `.git` lives. If not found, then fall back to the current working directory.

I cannot find anything useful from the readme, and I have searched a bit in the whole project:

https://github.com/ibhagwan/fzf-lua/search?q=root

Seems like there are some helper functions already. Is this kind of functionality provided right now? If not I would love to help this out because I need this desparately.

**Comment by ibhagwan** [comment]
Coincidentally in my [nvim config I have a similar functionality in a function called `set_cwd`](https://github.com/ibhagwan/nvim-lua/blob/f9bc19ab22e5640d21f18cac7700da3741ea8e83/lua/utils.lua#L88-L100) which sets the current working directory to either git root or the parent folder of the current file.

The code for `git_root` can be found inside “path.lua”, you can either copy it to your project or `require'fzf-lua.path'.git_root(…)`:

https://github.com/ibhagwan/fzf-lua/blob/2cd88dc8558c20e14d6e8e76df3c36d9ccd758a6/lua/fzf-lua/path.lua#L173-L181

Modify the function from my nvim config to return the `cwd` instead of setting it and call `files` with the `cwd` param:
```lua
:lua require'fzf-lua'.files({ cmd = YOUR_CWD_FUNCTION() })
```

**Comment by ibhagwan** [comment]
I wrote it for you, 2 different options (the first option adds a "bonus" search header so you can see what folder you're searching):

```lua
function M.files_git_or_cwd(opts)
  -- version 1: uses files for both git and cwd
  if not opts then opts = {} end
  opts.cwd = require'fzf-lua.path'.git_root(vim.loop.cwd(), true) or vim.loop.cwd()
  opts.fzf_cli_args = ('--header="cwd = %s"'):format(vim.fn.shellescape(opts.cwd))
  require'fzf-lua'.files(opts)
end
```

```lua
function M.files_git_or_cwd()
  -- version 2: uses `git ls-files` for git dirs
  -- change to `false` if you'd like to see message when not in a git repo
  if require'fzf-lua.path'.is_git_repo(vim.loop.cwd(), true) then
    require'fzf-lua'.git_files()
  end
  require'fzf-lua'.files()
end
```

**Comment by winston0410** [comment]
Thanks for the help, and I will test this later tonight. Closing now.

**Comment by winston0410** [comment]
Btw how can I pass a table to a lua function that is mapped in a keymap? Right now I am using a workaround like this, but this would throw error when I use this config on a new machine, as the the package is not installed yet.

```lua
local function getCwd()
	local path = require("fzf-lua.path").git_root(vim.loop.cwd(), true) or vim.loop.cwd()
	local header = ('--header="cwd = %s"'):format(vim.fn.shellescape(path))
	print("chek path", path)
	return { cwd = path, fzf_cli_args = header }
end

local function searchFiles()
	local opts = getCwd()

	require("fzf-lua").files(opts)
end

local function liveGrep()
	local opts = getCwd()

	require("fzf-lua").live_grep(opts)
end

local function init(use)
	use({
		"ibhagwan/fzf-lua",
		requires = {
			"vijaymarupudi/nvim-fzf",
			"kyazdani42/nvim-web-devicons",
		},
		config = function()
			local actions = require("fzf-lua.actions")

			require("fzf-lua").setup({
				winopts = {
					win_height = 1,
					win_width = 1,
				},
				fzf_layout = "reverse-list",
				files = {
					prompt = "Fd❯ ",
					cmd = "fd",
					git_icons = true, -- show git icons?
					file_icons = true, -- show file icons?
					color_icons = true, -- colorize file|git icons
				},
				grep = {
					prompt = "Rg❯ ",
					actions = {
						["Enter"] = actions.file_edit,
					},
				},
			})

			for _, mode in ipairs({ "n", "v" }) do
				vim.api.nvim_set_keymap(mode, ",m", "<cmd>lua require('plugins.fzf-lua').searchFiles()<cr>", {
					silent = true,
					noremap = true,
				})
                
				vim.api.nvim_set_keymap(mode, ",pm", "<cmd>lua require('fzf-lua').files_resume()<cr>", {
					silent = true,
					noremap = true,
				})

				vim.api.nvim_set_keymap(mode, ",g", "<cmd>lua require('plugins.fzf-lua').liveGrep()<cr>", {
					silent = true,
					noremap = true,
				})

				vim.api.nvim_set_keymap(mode, ",pg", "<cmd>lua require('fzf-lua').live_grep_resume()<cr>", {
					silent = true,
					noremap = true,
				})
			end
		end,
	})
end

return {
	init = init,
	searchFiles = searchFiles,
	liveGrep = liveGrep,
}
```

And seems like the `cwd` opts is not picked up internally, I get the header but the `fd` is still searching in the cwd. I will create a PR for that

**Comment by ibhagwan** [comment]
You can pass any option directly like this:

```lua
require("fzf-lua").files({
  path = …,
  fzf_cli_args = …,
  …
})
```

Unfortunately that won’t solve your new machine issue, I just put this at the top of my config file for each plugin:
```lua
if not pcall(require, 'fzf-lua') then return end
```

**Comment by ibhagwan** [comment]
> And seems like the cwd opts is not picked up internally, I get the header but the fd is still searching in the cwd. I will create a PR for that

https://github.com/ibhagwan/fzf-lua/commit/f3f373beafe82de7bdbc26b724a31047f805a05e this makes sure `cwd` is respected in files no matter the command.
