### ISSUE TITLE
Bug: when path.filename_first is set for formatter $ is not respected

### ISSUE THREAD

**Issue by DimitrisDimitropoulos** [ibhagwan/fzf-lua#1400]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish1

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-604+g9768e88f3

### Fzf version (`fzf --version`)

0.54.1 (Fedora)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--min-height=30 --layout=reverse --cycle --info=inline --no-scrollbar                                                           --preview-window 'right,50%,border-left,<50(down,40%,border-top)'                                                               --preview 'bat --style=numbers --color=always --line-range :500 {}'                                                             --bind=alt-k:first                                                                                                              --bind=alt-j:last                                                                                                               --bind=alt-h:toggle-preview                                                                                                     --bind=alt-u:preview-half-page-up                                                                                               --bind=alt-d:preview-half-page-down 

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  fzf_opts = {
    ['--no-scrollbar'] = true,
    ['--cycle'] = true,
    ['--info'] = 'inline',
    ['--separator'] = ' ',
    ['--pointer'] = '>',
    ['--preview-window'] = 'right,50%,border-left,<50(down,40%,border-top)',
  },
  fzf_colors = { ['gutter'] = { 'bg', 'Normal' } },
  diagnostics = { fzf_opts = { ['--pointer'] = '│' } },
  grep = {
    prompt = 'rg>',
    rg_opts = '--hidden --no-heading --color=always --max-columns=4096 --smart-case --line-number --column --with-filename --glob !.git --glob !build --glob !spell --glob !lockfiles --glob !LICENSE',
  },
  files = {
    cmd = 'rg --files --smart-case --color=never --follow --glob !.git --glob !build --glob !spell --glob !lockfiles',
    cwd_prompt = true,
    cwd_prompt_shorten_len = 1,
  },
  oldfiles = {
    include_current_session = true,
  },
  keymap = {
    builtin = {
      ['<A-a>'] = 'toggle-fullscreen',
      ['<A-d>'] = 'preview-page-down',
      ['<A-u>'] = 'preview-page-up',
      ['<A-w>'] = 'toggle-preview-cw',
      ['<A-h>'] = 'toggle-preview',
      ['<A-k>'] = 'first',
      ['<A-j>'] = 'last',
    },
    fzf = {
      ['ctrl-q'] = 'select-all+accept',
      ['alt-h'] = 'toggle-preview',
      ['alt-u'] = 'preview-page-up',
      ['alt-d'] = 'preview-page-down',
      ['alt-k'] = 'first',
      ['alt-j'] = 'last',
    },
  },
  winopts = {
    height = 0.97,
    width = 0.95,
    border = vim.g.border_style,
    preview = {
      default = 'bat',
      horizontal = 'right:50%',
      delay = 50,
      scrollbar = false,
      winopts = { number = false },
    },
  },
  previewers = {
    bat = {
      cmd = 'bat',
      args = '--color=always --style=changes --line-range :512',
      theme = 'gruvbox-dark',
    },
  },
})
```

### Describe the bug / steps to reproduce

Firstly, I want to thank you for your awesome plugin! 
Generally the $ option is respected when using path.filename_first option. I do not think my config has anything to do with the issue, since it is totally reproducible.
Steps: 
1. Try the `FzfLua files formatter={"path.filename_first"} ` command type something like `.lua$` and the output is the files ending in `lua` only in the directory where nvim is opened and not on all the directories inside
2. Try `FzfLua files formatter={"path.filename_first",2}` command type the same and the output is indeed correct. However, there is not highlighting in the matched part
3. Try `FzfLua files` and everything works as expected.
 This is not a huge bug more of a slight annoyance that I wanted to report. I am not sure if this is known, since there is some work done, as far as I understand. Feel free to close this if it known.
 Thank you for taking the time and effort reviewing this issue and please pardon any mistakes! :)

**Comment by ibhagwan** [comment]
Ty for the kind words @DimitrisDimitropoulos.

Unfortunately these are the limitations of fzf, the string is searched as it appears on string with no awareness for paths and [there are no plans to change that upstream](https://github.com/junegunn/fzf/issues/3854).

> Try FzfLua files formatter={"path.filename_first",2} command type the same and the output is indeed correct. However, there is not highlighting in the matched part

This is because v2 is an fzf hack, the path is copied twice to an invisible part at the end of the string (so you can match according to path original order) and that part of the string is then highlighted.

>  I am not sure if this is known, since there is some work done, as far as I understand. Feel free to close this if it known.

Indeed this is known and “by design” and there isn’t much I can do about it, personally I prefer the `path.dirname_first` formatter (highlight of the dir part).
