### ISSUE TITLE
Feature: min_width and min_height

### ISSUE THREAD

**Issue by kaiphat** [ibhagwan/fzf-lua#1401]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Would be great to have `min_width` and `min_height` options in absolute variables. I often to change window size in tmux :)

**Comment by ibhagwan** [comment]
I think this falls under “customization”, you can easily achieve that by setting `winopts = function() …`, you can then decide which values to return including min and max.

I’d rather avoid yet another obscure config option for a single user for something that can be achieved with `winopts` as a function (which I believe is called on resize too, if that’s not the case I’ll fix it).

**Comment by ibhagwan** [comment]
See #1040 how to use `winopts_fn`, you can also use `vim.o.columns`  and `vim.o.lines` to determine the current neovim size if you need to use that in your calc.

**Comment by kaiphat** [comment]
Thank you! It's enough for me:)

> I believe is called on resize too
Actually, it doesn't recalculate width dynamically, but it's unnecessary i think

**Comment by ibhagwan** [comment]
> Thank you! It's enough for me:)
> Actually, it doesn't recalculate width dynamically, but it's unnecessary i think

Great, closing this issue then, if you change your mind on the resize I can always add it later.
