### ISSUE TITLE
Actions from LSP windows

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#141]
Hey there, 

Often I want to do a "fzf lsp_definitions" and open the definition in a new tab. 

Does the lsp fzf list support actions like other lists such as "buffers" ?

**Comment by ibhagwan** [comment]
All file-like providers (files, grep, git, lsp, quicklist, oldfiles) have the same default action mappings, in short, the answer is yes, try it :)

**Comment by ldelossa** [comment]
ahh I see what I did wrong, I was using:

```
    actions = {
      ["default"]    = actions.buf_edit,
      ["alt-s"]      = actions.buf_split,
      ["alt-v"]      = actions.buf_vsplit,
      ["alt-t"]      = actions.buf_tabedit,
      ["alt-x"]      = actions.buf_del,
    }
``` 

instead of 

```
    actions = {
      ["default"]     = actions.file_edit,
      ["alt-s"]      = actions.file_split,
      ["alt-v"]      = actions.file_vsplit,
      ["alt-t"]      = actions.file_tabedit,
      ["alt-q"]      = actions.file_sel_to_qf,
      ["ctrl-y"]      = function(selected) print(selected[2]) end,
    }
```

(I remap since ctrl-v, ctrl-t, etc... are used for my terminal)
