### ISSUE TITLE
Feature: Add support for the iterm image protocol

### ISSUE THREAD

**Issue by WafiWadud** [ibhagwan/fzf-lua#1416]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

when the image previewer is chafa with the format set to iterm, it displays nothing. So I kindly ask of you to add support for the iterm image protocol (for context, I use wezterm on arch linux. wezterm has support for the iterm image protocol)

**Comment by ibhagwan** [comment]
It’s not supported inside a a neovim terminal, try to run chafa onside `:term` you’ll see it doesn’t work.

There is an issue for that upstream if I recall correctly.

**Comment by ibhagwan** [comment]
Also see #1136, https://github.com/neovim/neovim/issues/12991.
