### ISSUE TITLE
Bug: Misaligned entries in `helptags` output using Lazy.nvim

### ISSUE THREAD

**Issue by marcinmdev** [ibhagwan/fzf-lua#1417]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Windows + Linux

### Shell

zsh, powershell

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.54.3 (af4917db)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--no-separator --layout=reverse --inline-info

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
{
  "ibhagwan/fzf-lua",
  config = function()
    require("fzf-lua").setup({ "fzf-native", fzf_colors = true })
  end,
,
```

### Describe the bug / steps to reproduce

Helptags output is misaligned probably due to emoji encoding messing with line width. 

Steps to reproduce:
1. Use https://github.com/folke/lazy.nvim plugin manager
2. install fzf-lua
3. execute `:FzfLua helptags`

Output:

![2024-08-27_13-08-1724759195](https://github.com/user-attachments/assets/0ec5d956-e4da-42d5-89d3-70be8f822b46)

Tested in alacritty and Neovide (Arch Linux) and Neovide and windows terminal in Windows 11. Using FantasqueSansM Nerd Font Mono, tested with Noto Sans Mono and default Neovide font (which was Fira Code Nerd Font at the time).

Aditionally scrolling the output messes it even more:

![2024-08-27_13-08-1724759766](https://github.com/user-attachments/assets/d83720e4-5b4c-4a63-a8ca-5e06631f6541)

**Comment by ibhagwan** [comment]
From the screenshot I can see the native fzf previewer for helptags is  used which means the border is drawn by the fzf process itself, this will have to be fixed upstream.

**Comment by ibhagwan** [comment]
Closing as upstream.
