### ISSUE TITLE
Bug: fzf_colors does nothing without termguicolors

### ISSUE THREAD

**Issue by liskin** [ibhagwan/fzf-lua#1422]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.9.5

### Fzf version (`fzf --version`)

0.46.1 (debian)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--preview-window=border-left --info=inline-right

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    fzf_colors = true
})
```

### Describe the bug / steps to reproduce

If `termguicolors` is off (which is the default!), `fzf_colors = true` ends up not doing anything (no `--color` passed to fzf).
That's because it relies on `utils.hexcol_from_hl` which expects to get a `#rrggbb` or a color name, but with `notermguicolors`, `synIDattr` returns `ctermfg`/`ctermbg`, which is just a number.

The following seems to help:
```diff
--- ./lua/fzf-lua/utils.lua
+++ ./lua/fzf-lua/utils.lua
@@ -647,7 +647,7 @@ end
 function M.hexcol_from_hl(hlgroup, what, mode)
   if not hlgroup or not what then return end
   local hexcol = synIDattr(hlgroup, what, mode)
-  if hexcol and not hexcol:match("^#") then
+  if hexcol and not hexcol:match("^#") and not hexcol:match("^%d+$") then
     -- try to acquire the color from the map
     -- some schemes don't capitalize first letter?
     local col = M.COLORMAP()[hexcol:sub(1, 1):upper() .. hexcol:sub(2)]
```

It does seem like a bit of a hack, mainly because the "hexcol" in the function name is inaccurate now.

No special colorscheme is needed to reproduce this, just the default nvim 0.9 colorscheme with TERM=xterm-256color

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b00a6708c5d70ecf5d51d5b58d33bf4451cfa358 

Ty @liskin, implemented your suggestion, although this is somehwat of a "hack" and as you mentioned the name might be misleading it should not be a problem as `ansi_from_hl` validates the hex return val.

In https://github.com/ibhagwan/fzf-lua/commit/48275e0a647aadf561318a3cf19bfe00b6f537dd I also fixed devicon library icon colors when  using `notermguicolors`.

**Comment by liskin** [comment]
Awesome, thanks :tada:
