### ISSUE TITLE
Bug: `complete_path` ignores binary files

### ISSUE THREAD

**Issue by typhooncamel** [ibhagwan/fzf-lua#1425]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev

### Fzf version (`fzf --version`)

0.46.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--extended --inline-info

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({
      vim.keymap.set({ "i" }, "<C-x><C-f>",
      function()
        require("fzf-lua").complete_path() end,
        { silent = true, desc = "Fuzzy complete path" })
    })
```

### Describe the bug / steps to reproduce

When completing a path/filename using `complete_path()`, if the file I'm trying to get at is a binary file, it does not show up. In a directory with a mix of files, only text files are shown. I'm not sure if this is a bug or an option that can be set, or whether it uses gitignore as a basis for that, and if so how that can be changed.

**Comment by ibhagwan** [comment]
This isn’t a bug, the command is auto detected and will prioritize `fd` over find, you can see what command is run if you add `debug=true` to the options, whatever `fd` returns is what you’ll see in the list, it’s probably being ignored becuse of `gitignore`, try adding no ignore to the command (remove debug when you’re done debugging):
```lua
require("fzf-lua").setup({
      vim.keymap.set({ "i" }, "<C-x><C-f>",
      function()
        require("fzf-lua").complete_path({ cmd = 'fd --no-ignore', debug = true }) end,
        { silent = true, desc = "Fuzzy complete path" })
    })
```

**Comment by typhooncamel** [comment]
Apologies for mislabeling. Your suggestion however doesn't seem to work for some reason (as in, completion stops working altogether). Also, from what I can tell, gitignore either takes precendence over, or is merged with, an fd ignore file if it exists.

**Comment by ibhagwan** [comment]
> Apologies for mislabeling. Your suggestion however doesn't seem to work for some reason (as in, completion stops working altogether). Also, from what I can tell, gitignore either takes precendence over, or is merged with, an fd ignore file if it exists.

What does it mean “stops working altogether”, does it not complete or you get an empty list? My suggestion is a mere **suggestion** on how to teoubleshoot this, experiment with debug and different fd/find commands, try the same commands in the shell under the same cwd and find where the issue lies.

If there’s a bug, please provide more details why you believe this is a bug.

**Comment by typhooncamel** [comment]
I meant there's an empty list. I understand it is not a bug, now just trying to understand how to configure it. I'll do as you suggested and compare with the shell. Thanks.

**Comment by ibhagwan** [comment]
> I meant there's an empty list

That means either the command I used is wrong or you don’t have fd installed, use `debug=true` and look at the first line, run the same command in the shell, the same output should appear in fzf-lua, find why the output doesn’t contain binaries and you have a solution.

Debug output:

![IMG_2502](https://github.com/user-attachments/assets/8b84ce81-e58d-4c1b-acd5-bc967e79727a)
