### ISSUE TITLE
[ Feature Request ] FZF search open vim tabs

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#143]
Hello, 

Is it possibe to create a data source for vim tabs? I utilize tabs and buffers quite a bit, fuzzy searching my tabs would be nice as well. Thanks!

**Comment by ibhagwan** [comment]
I don't really used tabs in nvim but after experimenting with this a bit I realized if I were to use tabs they'd essentially be my `buffers` and I'd want the same features as showing the current tab in header, etc.

Turns out I could do it pretty quickly building on top of the `buffers` code, try it out.

The only thing I was debating was do I display the buffer numbers or not, I opted to leave it looking exactly like `buffers` for consistency, it also accepts the same params as `buffers`

```lua
:lua require'fzf-lua'.tabs({ ignore_current_buffer = true })
```

**Comment by gegoune** [comment]
Would it be possible to have `sort_lastused` as well, pretty please?

**Comment by gegoune** [comment]
`ignore_current_buffer` should it not be `ignore_current_tab`? :)

**Comment by ldelossa** [comment]
Havent tried this yet but just wanted to chime in on your comments. 

A "tab" in vim shouldn't be thought as an alternative way to use a buffer. Instead a "tab" should be thought of as "another arrangement of windows over your currently opened buffers" 

Its a bit subtle but you could imagine that you buffer-a and buffer-b opened in tab-a in a split. You now realize you need to compare a section of buffer-a and buffer-b which is much lower in both buffers. This is when youd open a new tab, preserving your original mental state in tab-a, but having tab-a be any new set of windows which help you further explorer buffer-a ans buffer-b

**Comment by ibhagwan** [comment]
> Havent tried this yet but just wanted to chime in on your comments.
> 
> A "tab" in vim shouldn't be thought as an alternative way to use buffers. Instead a "tab" should be thought of as "another arrangement of windows over your currently opened buffers"
> 
> Its a bit subtle but you could imagine that you buffer-a and buffer-b opened in tab-a in a split. You now realize you need to compare a section of buffer-a and buffer-b which is much lower in both buffers. This is when youd open a new tab, preserving your original mental state in tab-a, but having tab-b be any new set of windows which help you further explorer buffer-a and buffer-b

I think it’s very subjective, nvim is a very personalized and flexible software, some people use buffers as you’re used to them from GUI IDEs.

Being honest I didn’t really like this solution it was just easy to implement on top of buffers, feel free to improve on this implementation, maybe the best way to go here is to add all buffers inside all tabs with a tree like display which buffer is inside which tab?

https://github.com/ibhagwan/fzf-lua/blob/c4a829e83e5ef7b269287fbd32ac4c76a8a77594/lua/fzf-lua/providers/buffers.lua#L253-L283

**Comment by ibhagwan** [comment]
> `ignore_current_buffer` should it not be `ignore_current_tab`? :)

It should work, whatever works for `buffers` should work here, this is simply calling buffers with a different buffer set and a different default action.

**Comment by ldelossa** [comment]
Maybe a bit subjective but if you begin to use them in the former way things begin to break down. 

I think these explain it well:
http://vimdoc.sourceforge.net/htmldoc/tabpage.html
https://vim.fandom.com/wiki/Using_tab_pages

let give your changes a try in. If it simply moves you from tab to tab then it should work great.

**Comment by ibhagwan** [comment]
> If it simply moves you from tab to tab then it should work great.

The way it works and the display is similar to buffers but it only displays the active win/buffer in each tab so if you’re running 4 tabs and 8 buffers you’d still see only 4 buffers (the active ones), selecting a buffers moves you to the correct tab.

It would probably be nicer to have a tree-like display showing which buffers are under which tabs but it was more work than I was willing to invest in this.

**Comment by ldelossa** [comment]
@ibhagwan ohh so you made it similar to https://github.com/vim-ctrlspace/vim-ctrlspace ? "per tab buffers" for lack of a better term? 

If so, this is great as well, I very much enjoy that flow.

**Comment by ibhagwan** [comment]
> @ibhagwan ohh so you made it similar to https://github.com/vim-ctrlspace/vim-ctrlspace ? "per tab buffers" for lack of a better term?
> 
> If so, this is great as well, I very much enjoy that flow. One of my requested features for fzf.vim! So thanks.
> 
> I had originaly just meant "put the tab names into fzf, let you move to them via fzf" which I think is even simpler then this.

If you can send me a screenshot of how it looks like in `vim-ctrlspace` I can make it look (and work) the same, I’m still debating if I should add the tab number to the display as it’s not very meaningful IMO.

**Comment by ldelossa** [comment]
@ibhagwan so playing with your newest push. 

This starts to break down when you have the same buffer open in both tabs. 

I don't have ctrl-space installed but it maintains a view of buffers per tab. It images "tabs" as a new "workspace". 

In normal vim buffers are global, tabs are "views" of those buffers. If you wanted a tab which *just* had a few buffers available to it you're out of luck. 

In ctrl-space as soon as you open a new tab, only buffers opened inside that tab are displayed in it's buffer list. 

This workflow can be pretty decisive, some people love it, some people hate it, your call on whether you want fzf to be "general" or incorporate a workflow centric feature like whats described above.

**Comment by ldelossa** [comment]
This how vim shows tabs with using `tabs` command:

```
:tabs                                                                                                                                                                                   
Tab page 1
>   pkg/bpf/bpf.go
    pkg/bgp/log/log.go
Tab page 2
#   pkg/bgp/log/log.go
```

A "general" approach for fzf to present this information would be having "FzfLua tabs" display "tab page 1" and "tab page 2" as selectable. 

If taking the most general approach a call to 'FzfLua buffers' would show *just* 
```
    pkg/bgp/log/log.go
    pkg/bpf/bpf.go
```

Selecting a buffer would open it in what ever window you currently have selected.

**Comment by ibhagwan** [comment]
Try it now, should be what you're looking for:

![screenshot-1631996538](https://user-images.githubusercontent.com/59988195/133907614-eb388a6a-2de0-4509-9791-f5f9502d53c0.png)

The default action is `buf_switch` to an existing buffer which can also be used in `buffers` if you want to switch between to different windows inside the current tab:

```lua
:lua require'fzf-lua'.buffers({
  current_tab_only = true,
  actions = { ["default"] = require'fzf-lua.actions'.buf_switch }
})
```

**Comment by ibhagwan** [comment]
> Would it be possible to have `sort_lastused` as well, pretty please?

Unfortunately no more `sort_lastused` as it doesn't make much sense here.

**Comment by ldelossa** [comment]
@ibhagwan this is pretty awesome! You kinda got something unique here where you can do a workspace like workflow AND a normal tab workflow. This is awesome. Probably worth throwing on reddit to show the community how this feature works out. 

Only found a small issue. When opening the same buffer in both tabs the preview window for each buffer shows the same content. 

For example: 
    open file-a in tab-a.
    open fila-a in tab b.
    scroll fila-a in tab-b to some other area of the file. 
    open `FzfLua tabs`. 

you'll notice the preview for both buffers just seems to "pick one". Not sure how or which one it picks. This is not a big issue tho, just a small bug.

**Comment by ibhagwan** [comment]
> @ibhagwan this is pretty awesome! You kinda got something unique here where you can do a workspace like workflow AND a normal tab workflow. This is awesome. Probably worth throwing on reddit to show the community how this feature works out.

Idk if this alone justifies a reddit post :-)



> Only found a small issue. When opening the same buffer in both tabs the preview window for each buffer shows the same content.
> 
> For example:
> open file-a in tab-a.
> open fila-a in tab b.
> scroll fila-a in tab-b to some other area of the file.
> open `FzfLua tabs`.
> 
> you'll notice the preview for both buffers just seems to "pick one". Not sure how or which one it picks. This is not a big issue tho, just a small bug.

That's due to `vim.fn.getbufinfo` prioritizing the current tab/win buffer, https://github.com/ibhagwan/fzf-lua/commit/7e946aa515b5761814a152feed85c44567f96588 should fix it.

**Comment by ldelossa** [comment]
> Idk if this alone justifies a reddit post :-)
Your call. 

> That's due to vim.fn.getbufinfo prioritizing the current tab/win buffer, 7e946aa should fix it.

Fixed! Thanks for this. Closing out the issue.
