### ISSUE TITLE
Bug: Problem in awesom colorscheme picker

### ISSUE THREAD

**Issue by Kemphire** [ibhagwan/fzf-lua#1430]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.54

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({
			winopts = {
				backdrop = 70,
			},
		})
```

### Describe the bug / steps to reproduce

When i try to switch theme using awesom_colorscheme picker it show error

'''sh
[Fzf-lua] Unable to packadd  darcula.nvim: vim/_editor.lua:0: nvim_exec2(): Vim(packadd):E919: Directory not found in 'packpath': "pack/
*/opt/darcula.nvim"
'''
for any colorscheme i select the error is more or less same

but this doesn't happens with default colorscheme picker

![image](https://github.com/user-attachments/assets/0123d8b4-afe7-44ef-a3d7-3bbc689c9e52)

**Comment by ibhagwan** [comment]
Can you post a screenshot of the icon next to the theme? Is it showing as downloaded? Can you try to delete and redownload (ctrl-x, ctrl-r) and post the output of `:messages`?

Should be something like
![IMG_2635](https://github.com/user-attachments/assets/e566d82b-51ac-4566-afca-c1708425394a)

**Comment by Kemphire** [comment]
@ibhagwan thanks for your quick response, i was so dumb to not download the theme before using it.
so it is okay to say that this was not a bug of fzf lua.

Thank you again for such amazing neovim plugin.

**Comment by ibhagwan** [comment]
Ty @Kemphire!

**Comment by descentcare** [comment]
![-210248_temp](https://github.com/user-attachments/assets/7b8abf76-e112-4772-8162-41655d914892)
C:\Users\user\AppData\Local\Temp\nvim\fzf-lua\pack\fzf-lua\opt\apprentice.nvim does exist
same problem
It works in wsl, but not on windows
