### ISSUE TITLE
Bug: preview highlighting is not using theme for git_commits

### ISSUE THREAD

**Issue by stefanwatt** [ibhagwan/fzf-lua#1431]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux - NixOS

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.11.0-nightly+7b7c95d

### Fzf version (`fzf --version`)

0.52.1

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
fzflua.setup({
	keymap = { fzf = { ["ctrl-q"] = "select-all+accept" } },
})
```

### Describe the bug / steps to reproduce

Run:
```lua
require('fzf-lua').git_commits()
```
The preview highlighting is not using my theme.
![image](https://github.com/user-attachments/assets/7869c866-1175-4b26-95ef-0fd3776ff9b4)

 However when running:
```lua
require('fzf-lua').git_files()
```
highlighting is correct.
![image](https://github.com/user-attachments/assets/2f3ce7d9-c8b4-445f-9ae3-07d13d2df0be)

**Comment by ibhagwan** [comment]
This isn’t a bug, the git previewers use fzf’s native shell previewer, with git the `delta` utility is auto detected and used which is what you see (something like `git diff | delta`).

The second screenshot uses the “builtin” previewer which is a neovim buffer that does use your colorscheme.

**Comment by ibhagwan** [comment]
Btw, if you wish to theme git diff type previews, read the upstream repo in https://github.com/dandavison/delta, you can modify the git pager settings using the  `preview_pager` option.

**Comment by stefanwatt** [comment]
ok thanks
wasn't sure what to set `preview_pager` to at first, but I `commits.preview_pager = false` seems to work

**Comment by ibhagwan** [comment]
> ok thanks wasn't sure what to set `preview_pager` to at first, but I `commits.preview_pager = false` seems to work

That disables the pager altogether, you can probably experiment with `delta --list-themes` and find something you like.
