### ISSUE TITLE
Updating window content without closing and reopening

### ISSUE THREAD

**Issue by henriquehbr** [ibhagwan/fzf-lua#144]
Is it possible to update the `cmd` output of the current floating window rather than "replacing" it with a new one?

I'm currently working on the implementation of a file browser using `fzf-lua` as a base, when i select a element from the list and invoke a new instance of fzf, it briefly flashes on the screen, it's subtle, but noticeable enough when you do it for 3-4 times, is there any way to prevent such flickering from happening?

**Comment by ibhagwan** [comment]
It's not possible using the current API but if you want to be adventurous you can explore an implementation using Fzf's events and actions, the way I would go about it is map `enter` to `execute:reload(<cmd {q}>)` maybe?

Basically what you're trying to do is recreate it at the shell/terminal level, if it can work in the shell you can make `fzf-lua` do the same using similar command line arguments.

Another option would be to add this functionality to Fzf-lua where instead of closing the window you just run another instance of `core.fzf`, it may or may not be a big deal.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/dcc8eaf295f0942d1540cdb4e3da02c51d8b9614 this adds 2 new functionalities aimed towards your use case:

1. Option to specify `no_win_close` - what this does is prevent the window from closing when fzf is terminated, note that this is only aimed to be used in special cases since if you use that for example with `files` and then select a file, the buffer will be opened in the popup.

2. The ability to "reuse" the fzf window, before this change calling a fzf-lua function when the popup is open would result in a warning to close the current window, now the window will be overwritten instead. This also reuses the current layout and will therefor not work when using commands with different layout/previewers.

That said, I believe this can solve your use case, the way to try it is as follows:

```lua
:lua require'fzf-lua'.files({ no_win_close = true })
-- press <Esc> or <C-c> to terminate fzf,
-- the fzf window should now display "[Process exited 130]"
-- press <C-\><C-n> to enter normal mode and run:
:lua require'fzf-lua'.buffers()
-- 'buffers' should open in the same window without a reopen
```

Note that reusing the window can also work without `no_win_close = true`, the option is only useful when you'd like to keep the window open after a selection (I'm assuming you need this option to prevent closing of the window after pressing `<CR>` on a directory to `cd` into it):
```lua
:lua require'fzf-lua'.files()
-- press <C-\><C-n> to enter normal mode and run:
:lua require'fzf-lua'.buffers()
-- Again, 'buffers' should open in the same window without a reopen
```

**Comment by henriquehbr** [comment]
Indeed, it worked as expected, the floating window is not flashing anymore when selecting directories, but i've noticed 2 issues:

- If i try to open a file as before (`vim.cmd('e ' .. selected)`), it gets opened on the floating window buffer instead of opening the selected file on the current neovim instance
    - I even tried removing the `vim.cmd`, expecting the file to be opened when selected (due to be running a `.files()` picker) but nothing happens, the floating window just stands there until it's closed
- When i press Esc to exit, there's this `[Process exited 130]` you mentioned on the first code example, do you have any ideas of how i skip it? in a way that instead of pressing Esc twice, we only need to press once without even seeing such message

**Comment by ibhagwan** [comment]
I’ll add a command to set the `no_close` option to whatever you want so basically you’ll run `require'fzf-lua'.set_noclose(false)` before your selection and then open the file normally.

Wil  update this thread when I add it.

**Comment by ibhagwan** [comment]
Ok I reworked this thing a tiny bit, the option is now called `autoclose` (not `no_close` anymore).

Now you can either call the provider directly with `autoclose = false`:
```lua
:lua require'fzf-lua'.files({ autoclose = false })
```

Or while the window is open call `fzf-lua.win.set_autoclose` method:
```lua
:lua require'fzf-lua.win'.set_autoclose(false)
```

You can also retrieve the current window `autoclose` state (default is `true`):
```lua
-- will return `nil` if no active window is found
:lua print(require'fzf-lua.win'.autoclose())
```

**Comment by henriquehbr** [comment]
Many thanks for the updates and the quick response! :)

I've tried again, updating to the latest version and strictly following your instructions, but unfortunately couldn't get it working as expected, here's the config i've used:

```lua
local fzf = require 'fzf-lua'
local is_empty = require 'helpers.is_empty'

function fzf_navigation(options)
    local default_options = {
        cmd = 'ls -1a --group-directories-first --color=always | tail -n +2',
        autoclose = false -- added
    }

    default_options.actions = {
        ['default'] = function(selected)
            fzf_navigation { entry = selected[2] }
        end
    }

    options = vim.tbl_extend('force', default_options, options or {})

    if options.entry == '..' or fn.isdirectory(options.entry) == 1 then
        options.cwd = fn.fnamemodify(options.entry, ':p:h')
        fzf.files(options)
    elseif not is_empty(options.entry) then
        require 'fzf-lua.win'.set_autoclose(true) -- added
        cmd('e ' .. options.entry)
        require 'fzf-lua.win'.set_autoclose(false) -- added
    else
        fzf.files(options)
    end
end

return fzf_navigation
```

The current problem is that using the config above, when a file is selected, it's still displayed in `fzf-lua` floating window buffer, just like before, and this window persists on the screen, it doesn't closes even when pressing Esc

Another thing i've noticed, is that this time, i can see on the tabline that the selected file is now being properly opened, so i guess that's a win, congratulations for the great job on this plugin, loving it so far!

**Comment by ibhagwan** [comment]
The issue here is when you function is called, the fzf process has already terminated and the `autoclose` test already happened, you setting it to `true` has no effect, what you should be doing instead is call the `close` function of the window which can be triggered with:
```lua
lua require('fzf-lua.win').win_leave()
```

**Comment by henriquehbr** [comment]
It worked, no flashing and now the files are being opened properly, thank you!

But now, only one problem remains, i'm still scratching my head to get this `.set_autoclose(true)` working, is there any kind of `esc` or `exit` action where i can enable `autoclose` whenever the floating window is about to close?

**Comment by ibhagwan** [comment]
`set_autoclose(true)` is exactly that but the issue for you is that once your function is called fzf was already terminated and the window was technically already supposed to be closed, the only way out of it is manually calling `win_leave()`.

If you can explain in more details what's the use case you're trying to solve I'll be able to better help you.

**Comment by henriquehbr** [comment]
For this case in particular, i really think we need a way to map the Esc key to `.win_leave()`, besides that, i can't see a way of achieving such behavior, taking into consideration that fzf will always terminate before `set_autoclose(true)` can run

**Comment by ibhagwan** [comment]
> For this case in particular, i really think we need a way to map the Esc key to `.win_leave()`, besides that, i can't see a way of achieving such behavior, taking into consideration that fzf will always terminate before `set_autoclose(true)` can run

You can always add a mapping using `:tmap` but I still don't understand what do you mean, which part are you having issues with? after the file selection?

**Comment by henriquehbr** [comment]
As mentioned before, the problem boils down to:

> When i press Esc to exit, there's this `[Process exited 130]` you mentioned on the first code example, do you have any ideas of how i skip it? in a way that instead of pressing Esc twice, we only need to press once without even seeing such message

I think having to add a map would be a bit "hacky", and very probably, it would interfere with other tools that make use of neovim terminal (unless such mapping is unmapped after being used, but it would become a bit unpractical)

Currently, is there any way to make the Esc key recogonizable by `fzf-lua` actions?

**Comment by ibhagwan** [comment]
Ok, fixed it for you with a few improvements:
- Only set `autoclose = true` for directories so you don't need to call `win_leave()` before opening a file, to do that I used `nvim-fzf` preview "action" which gets called each time the selected item changes (basically a previewer) 
- Mapped `<Esc>` to `win_leave()`, to do that you have to use `esc` as that's how fzf refers to it (`man fzf` to see the available binds, look for section "Available Actions")


```lua
function M.nav(options)
    local fn = vim.fn
    local cmd = vim.cmd
    local fzf = require'fzf-lua'

    local default_options = {
        cmd = 'ls -1a --group-directories-first --color=always | tail -n +2',
        autoclose = false -- added
    }

    default_options.actions = {
        ['default'] = function(selected)
            M.nav { entry = selected[2] }
        end,
        ['esc'] = function(_)
            require 'fzf-lua.win'.win_leave()
        end,
    }

    options.preview = require("fzf.actions").action(function(args)
        local file = args[1]:match("[^" .. require'fzf-lua.utils'.nbsp .. "]*$")
        if file == '..' or fn.isdirectory(file) == 1 then
          require 'fzf-lua.win'.set_autoclose(false)
        else
          require 'fzf-lua.win'.set_autoclose(true)
        end
    end, "{}")

    options = vim.tbl_extend('force', default_options, options or {})

    if options.entry == '..' or fn.isdirectory(options.entry) == 1 then
        options.cwd = fn.fnamemodify(options.entry, ':p:h')
        fzf.files(options)
    elseif options.entry and #options.entry>0 then
        cmd('e ' .. options.entry)
    else
        fzf.files(options)
    end
end
```

**Comment by henriquehbr** [comment]
Many thanks for your time and effort @ibhagwan! i think we can close this one, not only the original issue was addressed, but also a few other ones were

Just a quick question, wouldn't just calling `.win_leave()` be more "lightweight" in terms of logic, as there would be less code involved, and taking into consideration that the `preview` action is executed whenever the type of selection change, it would be slightly less responsive due to the extra processing being done under the hood, even though in some cases it's barely noticeable, shouldn't it be something to consider?

**Comment by ibhagwan** [comment]
> Many thanks for your time and effort @ibhagwan! i think we can close this one, not only the original issue was addressed, but also a few other ones were
> 
> Just a quick question, wouldn't just calling `.win_leave()` be more "lightweight" in terms of logic, as there would be less code involved, and taking into consideration that the `preview` action is executed whenever the type of selection change, it would be slightly less responsive due to the extra processing being done under the hood, even though in some cases it's barely noticeable, shouldn't it be something to consider?

You’re probably right, but for some reason this wasn’t working for me without the preview trick, plus, it’s another “showcase” if you wanted to do something more complex.

Anyways, I think it’s safe to close this issue now, cheers :)
