### ISSUE TITLE
Feature: Pickers to show git blame and git line history for a particular line.

### ISSUE THREAD

**Issue by 231tr0n** [ibhagwan/fzf-lua#1442]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Hi ibhagwan! Is it in the scope of fzf-lua to add a picker for git blame of a file and entire blame history of a single line in a git file.

**Comment by ibhagwan** [comment]
> picker for git blame of a file

Need to think about it, what is the purpose of this? To search changes by specific committers? What will it pick? The selected line?

> history of a single line in a git file

If you map a key to in visual mode to `git_bcommits` and visually select a single line (or range) you’ll get the commit history specific to the range.

**Comment by 231tr0n** [comment]
> > picker for git blame of a file
> 
> Need to think about it, what is the purpose of this? To search changes by specific committers? What will it pick? The selected line?
> 
> > history of a single line in a git file
> 
> If you map a key to in visual mode to `git_bcommits` and visually select a single line (or range) you’ll get the commit history specific to the range.

For the first question, when you pick a line it just goes to that line maybe.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/f8e56d067066d19caf130ad7cd50c4fa1265b3a4

@231tr0n, finnally got to it, I found the neded functionality closes to `git_bcommits` so I replicated most of the functionality, notes:
- Default command will display the output of `git blame --color-lines {file}`.
- `enter` goes to selected line
-  `ctrl-{v|s|t}` will open the index buffer in split/tab
- `ctrl-y` will yank the commit hash so it can be pasted with `p`.
- Preview shows the relevent commit and also supports `git_pager` setting which is auto-detected to `delta`.

![image](https://github.com/user-attachments/assets/dcfb5a34-06b2-4998-8c37-b466304ccadc)

**Comment by 231tr0n** [comment]
> [f8e56d0](https://github.com/ibhagwan/fzf-lua/commit/f8e56d067066d19caf130ad7cd50c4fa1265b3a4)
> 
> @231tr0n, finnally got to it, I found the neded functionality closes to `git_bcommits` so I replicated most of the functionality, notes:
> 
>     * Default command will display the output of `git blame --color-lines {file}`.
> 
>     * Used from visual mode will display only the range using `-L start,end`.
> 
>     * `enter` goes to selected line
> 
>     * `ctrl-{v|s|t}` will open the index buffer in split/tab
> 
>     * `ctrl-y` will yank the commit hash so it can be pasted with `p`.
> 
>     * Preview shows the relevent commit and also supports `git_pager` setting which is auto-detected to `delta`.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/59988195/371335923-dcfb5a34-06b2-4998-8c37-b466304ccadc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTMyNDYsIm5iZiI6MTcyNzQxMjk0NiwicGF0aCI6Ii81OTk4ODE5NS8zNzEzMzU5MjMtZGNmYjVhMzQtMDZiMi00OTk4LThjMzctYjQ2NjMwNGNjYWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA0NTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MDExZDVkYTgyZGEwNThlYWUyZWMyMWI0NTIyYTFhMzljMzk4NzBhYzUxYzVjNzk4NDNmOTYxNWQxN2U4YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hHGtpQaoKaygUA5jaUNs_CciFCRiEtOtZYzXyN0lFFE)

Awesome! Will try it out. Thank you for considering adding this.
