### ISSUE TITLE
Bug: Files with % aren't displayed in the preview pane when using grep-like commands

### ISSUE THREAD

**Issue by lgrosz** [ibhagwan/fzf-lua#1443]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Ubuntu Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-131+gf55767afe

### Fzf version (`fzf --version`)

0.42.0 (d471067)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=bg+:#414559,bg:#303446,spinner:#f2d5cf,hl:#e78284 --color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf --color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({ })
```

## Reproduction steps

1. Create a file, `my_%_file` with some searchable content
2. Use `:FzfLua live_grep` to search for the content

## Behavior

The preview window says "cannot stat file..." with the `%` removed from the filename

## Expected behavior

The preview window should display as if the filename didn't have a `%` in it

## Additional Information

- This only happens with grep-like command, not commands like `:FzfLua files`
- I am using `rg`

**Comment by hagnerd** [comment]
This does work as expected with `FzfLua live_grep_native` so I assume the `live_grep` implementation needs to do something to make sure that any `%` is escaped properly.

More info on [escape patterns](https://www.lua.org/pil/20.2.html) in Lua .

**Comment by ibhagwan** [comment]
You’re correct it’s an easy fix I just haven’t gotten to it yet.

**Comment by ibhagwan** [comment]
Very confusing, this doesn't seem to reproduce, I added a debug print right after the previewer `fs.stat` and it seems to work without additional escaping:
![image](https://github.com/user-attachments/assets/394ec823-edf8-405c-800b-f46342ef319a)


I also use Linux, tried with both `bash` shell, neovim nightly and fzf v0.42 and it seems to work, any addiotnal info to help me reproduce this would be great.

**Comment by nenahp** [comment]
Seems to be here:
https://github.com/ibhagwan/fzf-lua/blob/985e1002b5dc70f8196ea0605bbfffc8c8407e31/lua/fzf-lua/make_entry.lua#L401-L404

**Comment by ibhagwan** [comment]
Ty @nenahp! I didn’t realize the entry itself is wrong not the preview, plus this only happens when the resulting entry has the file ansi colored which is why it wasn’t happening on my system.

**Comment by lgrosz** [comment]
Hi, I apologize for the late response! Yes, it's the preview of the file, not the file name. I'll pull down the fix and verify its fixed it for me!
<img width="1728" alt="Screenshot 2024-09-14 at 9 44 57 AM" src="https://github.com/user-attachments/assets/addc5f22-acad-4b07-ba03-5f05da522332">
<img width="1728" alt="Screenshot 2024-09-14 at 9 45 23 AM" src="https://github.com/user-attachments/assets/a5e757f6-2218-4c7a-a081-3749449fd28d">

**Comment by lgrosz** [comment]
Fixed. Thank you!

**Comment by ibhagwan** [comment]
Ty for the update @lgrosz !
