### ISSUE TITLE
Feature: Navigation with <C-d> and <C-u>

### ISSUE THREAD

**Issue by hexcowboy** [ibhagwan/fzf-lua#1444]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I'm trying to navigate my fzf windows with <C-d> and <C-u> but they don't appear to do anything.

**Comment by ibhagwan** [comment]
This isn’t a feature request, not even sure what you mean… read the docs/wiki and you’ll figure it out.

**Comment by hexcowboy** [comment]
It's a normal vim motion to us <C-u> and <C-d> to navigate. I can map them like this but it would be nice to have them as default behavior.

```lua
require("fzf-lua").setup({
    keymap = {
        fzf = {
            ["ctrl-d"] = "half-page-down",
            ["ctrl-u"] = "half-page-up",
        },
    },
})
```

**Comment by ibhagwan** [comment]
Fzf uses deadline defaults, for example, `ctrl-e` goes to end of line, I have no intentions to change the defaults after almost 3 years that the plug-in exists, the configuration options are there for a reason.
