### ISSUE TITLE
Feature: Treesitter Symbol Search

### ISSUE THREAD

**Issue by scienceplease** [ibhagwan/fzf-lua#1447]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Enable searching treesitter symbols akin to Telescope's `builtin.treesitter`.

Notionally, `ts_symbols` could search all buffer symbols, while `ts_functions`, `ts_variables`, `ts_classes`, etc. could be defined to search a specific subset of symbols. Alternatively (or additionally), `ts_symbols` could accept a criteria to filter on particular symbol types.

**Comment by ibhagwan** [comment]
I’ve seen this in Telescope but I’m not sure I find the value in this, in between lsp symbols and btags/blinds I can’t think of anything I would like to find in a file and can’t or would a scenario where I’d prefer to open a tree sitter picker instead.

What’s the use case for this that isn’t covered by the pickers I mentioned?

**Comment by scienceplease** [comment]
Searching across LSP symbols is absolutely better as you say, but it is often the case that languages/syntaxes have treesitter grammars but no LSP. Sometimes project files/structure can be too large for certain LSPs, in which case only Treesitter is enabled.

Being able to search across tokens with certain semantics is helpful for the same reason `lsp_typedefs`, `lsp_implementations`, etc. are helpful. To your point, regular string search can get you to the same place but search results can be quite cluttered without pre-filtering (depending on the structure of your code). 

Telescope pickers can be used alongside `fzf-lua` to search treesitter symbols, it just depends on how you want to position `fzf-lua`. Would you expect users to have both installed and configured? Personally, I would just use one or the other.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/0a59302db460b1ea291c13bcb98e13b672f284dd

![image](https://github.com/user-attachments/assets/fe694991-eada-411f-9544-24ab8f64c9ff)
