### ISSUE TITLE
Feature: Picker for showing undo history and restoring state.

### ISSUE THREAD

**Issue by 231tr0n** [ibhagwan/fzf-lua#1450]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I think there was a similar issue related to undo history https://github.com/ibhagwan/fzf-lua/issues/617 where someone was trying to create a custom action for undo history.
I wanted to know if it was feasible to add a undo history picker to fzf-lua.

**Comment by ibhagwan** [comment]
Anything is feasible, but unfortuthely I find this to be out of scope and not something I wish to maintain, the API is very simple to use and the [advanced wiki](https://github.com/ibhagwan/fzf-lua/wiki/Advanced) contains all info you need to implement this using fzf-lua.
