### ISSUE TITLE
Bug: live_grep resume doesn't work if skim is used

### ISSUE THREAD

**Issue by loyd** [ibhagwan/fzf-lua#1453]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

sk 0.10.4

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
mini.sh + `:lua require('fzf-lua').setup({'skim'})`
```

### Describe the bug / steps to reproduce

`FzfLua resume` shows empty window when used with the `skim` backend due to https://github.com/ibhagwan/fzf-lua/blob/a34542d466b46be19198d16199e5245d27e89a9e/lua/fzf-lua/core.lua#L461

I think it should be noted in the documentation (if you prefer to close this issue).

This is because `skim` doesn't print commands with `--print-query`, only query: https://github.com/lotabout/skim/issues/437.

**Comment by ibhagwan** [comment]
> I think it should be noted in the documentation (if you prefer to close this issue).

As I mentioned in https://github.com/ibhagwan/fzf-lua/issues/963#issuecomment-2366808781, skim is a dead project and I highly recommend using only fzf.

We can add this (and other skim limitations) to the Wiki (it’s open edit to all btw) but it’s not high on my priority list as almost nobody uses skim (for a good reason), this issue in and of itself can be considered said documentation :)
