### ISSUE TITLE
search = '' option doesn't work with blines

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#146]
Hi, I'm trying to add 
```vim
xnoremap <silent><expr> <leader>k ":\<C-U>lua require('fzf-lua').blines({ search = require('fzf-lua.utils').get_visual_selection() })\<cr>"
```
but `search = ` option is not working with `blines`. Could we make it work like `live_grep`?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/1a2e198f1b0d4109cffb00ad9a6e985ac28d28c0

This should do what you're looking for.
