### ISSUE TITLE
Bug: when using `split`, vim resize while fzf is open causes wrong `cmdheight` on close

### ISSUE THREAD

**Issue by jfly** [ibhagwan/fzf-lua#1462]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

v0.11.0-nightly+69553f7

### Fzf version (`fzf --version`)

0.55.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    winopts = {
      split = "belowright new",
      height = 0.4,
      preview.hidden = "hidden",
    };
})
```

### Describe the bug / steps to reproduce

Open fzf-lua, resize neovim, and then close fzf lua. You'll be left with an empty space at the bottom that I cannot figure out how to make go away (other than restarting neovim). `:FzfLua redraw` doesn't fix things.

This is easiest to just see in a video, here you go:

https://github.com/user-attachments/assets/18046175-d045-4c40-b669-bd402c0590b0

**Comment by jfly** [comment]
That's it! Before bug: `cmdheight=1`. After bug: `cmdheight=12`. `:set cmdheight=1` fixes it.

**Comment by ibhagwan** [comment]
> That's it! Before bug: `cmdheight=1`. After bug: `cmdheight=12`. `:set cmdheight=1` fixes it.

Thanks for the video which made this clear and for confirming @jfly, I’ll fix it shortly.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d76cc35a2945beb4d916050a8ad34b7daf1b4054

@jfly, should work as expected now.

**Comment by jfly** [comment]
That works great! Thank for for the quick response and quick fix =)
