### ISSUE TITLE
Feature: Send marks to quickfix list (including lowercase [A-Za-z]). Maybe `goto_mark_or_qf` action?

### ISSUE THREAD

**Issue by serranomorante** [ibhagwan/fzf-lua#1465]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Hi!

I noticed 

```lua
keymap = {
  fzf = {
        ---https://github.com/ibhagwan/fzf-lua/issues/546#issuecomment-1736076539
        ["ctrl-q"] = "select-all+accept",
```

has no effect on **marks**. So we are not able to send marks from the previewer into the quickfix list.
I tried to implement this as a custom action, but failed as there's no easy way for me to get the buffer integer from marks that have a text instead of a filename `(mark, line, col, path/text)`. I needed that buffer integer so I can pass it to `vim.api.nvim_buf_get_mark(...)` to get the lowercase marks (not only the global marks).

Having something like `file_edit_or_qf` for marks would be appreciated!

Also, currently fzf-lua marks have a `[--no-multi] = true` default that should be removed if this gets implemented so we can "select" multiple marks and send them to the quickfix list.

Thanks!

**Comment by serranomorante** [comment]
This gets the job done (and is enough for me), but

1. No implementation for loclist
2. Only work with marks **in current buffer list**
3. Is not performance efficient

> utils.lua
```lua
local M = {}

---@class FzfLuaOpts
---@field prompt string

---@param selected string[]
---@param opts FzfLuaOpts
M.sel_marks_to_qf = function(selected, opts, is_loclist)
  local qf_list = {}

  for i = 1, #selected do
    local mark, line, col, filepath = (selected[i]):match("%s(.)%s+(%d+)%s+(%d+)%s*(.*)$")
    for _, buf in ipairs(vim.api.nvim_list_bufs()) do
      local buf_line = vim.api.nvim_buf_get_mark(buf, mark)
      if tostring(buf_line[1]) == tostring(line) then
        table.insert(qf_list, {
          bufnr = buf,
          filename = vim.api.nvim_buf_get_name(buf),
          lnum = line,
          col = col,
          text = "(" .. mark .. ") " .. filepath,
        })
      end
    end
  end

  vim.fn.setqflist({}, " ", {
    nr = "$",
    items = qf_list,
    title = opts.prompt,
  })
  vim.cmd("botright copen")
end

---@param selected string[]
---@param opts FzfLuaOpts
M.goto_mark_or_qf = function(selected, opts)
  local fzf_lua = require("fzf-lua")

  if #selected > 1 then
    return M.sel_marks_to_qf(selected, opts)
  else
    return fzf_lua.actions.goto_mark(selected, opts)
  end
end

return M
```

Then on your regular fzf config:

> your fzf-lua config
```lua
local utils = require("utils")

setup({
    marks = {
      fzf_opts = {
        ["--no-multi"] = false,
        ["--multi"] = true,
      },
      actions = {
        ["enter"] = fzf_utils.goto_mark_or_qf,
      },
    },
})
```

**Comment by ibhagwan** [comment]
> This gets the job done (and is enough for me)

Looks great, if this works for you we can close this issue, most people either don’t use marks or use only a few marks it as “harpoon” style in which case the defaults work, if this becomes more popular I’ll add it in a more robust way but after 3+ years I doubt it will be the case :)
