### ISSUE TITLE
Feature: git.around 

### ISSUE THREAD

**Issue by GopherJ** [ibhagwan/fzf-lua#1466]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

sometime while reviewing a commit we would like to jump to commits around the current commit. So it'll be good to highlight the current one and show 3 commits before and 3 commits after

example implementation:

```
			function garound()
				local current_commit = system("git rev-parse HEAD"):gsub("\n", "")
				local cmd = string.format(
					"git log --pretty=oneline --reverse --all | rg --color=always --no-line-number -C 3 %s",
					current_commit
				)
				require("fzf-lua").fzf_exec(cmd, {
					actions = {
						["default"] = function(selected)
							open_commit_fzf(selected[1])
						end,
					},
				})
			end

			vim.api.nvim_create_user_command("GAround", garound, {})

```

**Comment by GopherJ** [comment]
btw I didn't see a git show previewer

**Comment by ibhagwan** [comment]
> btw I didn't see a git show previewer

Both `git_bcommits` and `git_blame` have git show previewer, maybe this can work with `git_bcommits({ cmd = … })`.

**Comment by GopherJ** [comment]
git_bcommits is for file
git_around I'd assume the person is in the middle of the commit history and wants to jump next/prev

**Comment by ibhagwan** [comment]
> git_bcommits is for file git_around I'd assume the person is in the middle of the commit history and wants to jump next/prev

Quite honestly I don’t think we need to have a picker in fzf-lua for wfey single git command out there, that’s why it’s all very easy to achieve with `fzf_exec`.

**Comment by GopherJ** [comment]
yes just want to see if navigate is a good one to be added by default

**Comment by ibhagwan** [comment]
> yes just want to see if navigate is a good one to be added by default

Maybe  you can reuse one of the `actions.git_xxx` code?

**Comment by GopherJ** [comment]
sure
