### ISSUE TITLE
Bug: previewer throws exception when no parser is found for the filetype of the currently selected file

### ISSUE THREAD

**Issue by jcapblancq** [ibhagwan/fzf-lua#1472]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-322+ge7020306a 

### Fzf version (`fzf --version`)

ebb89e4

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=fg:#f2f3f3,hl:#ffb65b,fg+:#f2f3f3,bg+:#353b45,hl+:#ffb65b,info:#61afef,prompt:#5a84e5,pointer:#f3f383,marker:#62ea76,spinner:#8c62e0,header:#353b45

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
local fzflua = require("fzf-lua")
local actions = require("fzf-lua.actions")

fzflua.setup({
	buffers = {
		file_icons = true,
		color_icons = false,
	},
	diagnostics = {
		file_icons = true,
		color_icons = false,
	},
	grep = {
		actions = {
			["ctrl-q"] = {
				fn = actions.file_edit_or_qf,
				prefix = "select-all+",
			},
		},
	},
	files = {
		file_icons = true,
		color_icons = false,
		fd_opts = "--color=always --type f --hidden --follow --exclude .git",
		actions = {
			["ctrl-q"] = {
				fn = actions.file_edit_or_qf,
				prefix = "select-all+",
			},
		},
	},
	fzf_opts = { ["--layout"] = "default", ["--marker"] = "+", ["--cycle"] = "" },
	winopts = {
		width = 0.9,
		height = 0.8,
		preview = {
			hidden = "nohidden",
			vertical = "up:30%",
			horizontal = "right:30%",
			layout = "horizontal",
			flip_columns = 120,
			delay = 10,
			winopts = { number = true },
		},
	},
	keymap = {
		builtin = {
			false, -- do not inherit from defaults
			["<C-d>"] = "preview-page-down",
			["<C-u>"] = "preview-page-up",
		},
	},
})
```

### Describe the bug / steps to reproduce

Hi,

The problem started roughly 3 days ago. It seems to be related to the commit: https://github.com/ibhagwan/fzf-lua/commit/a1f834b37506ca77c47fa99cd3f5e9ed3f4102d2

When I locally revert to a pcall, everything works fine. Am I missing an option? 

Thanks for the great plugin and support.

**Comment by ibhagwan** [comment]
Are you on the latest fzf-lua commit which containts https://github.com/ibhagwan/fzf-lua/commit/ebb89e4e4065e31b029eee8f618e1ca660f41f35?

**Comment by ibhagwan** [comment]
> still throws an exception.

- Are you using the latest nightly?
- Can you post the details of the exception so I can see which line of code fails?
