### ISSUE TITLE
Duplicated references on .lsp_references()

### ISSUE THREAD

**Issue by crates51** [ibhagwan/fzf-lua#1473]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

MAC

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.47.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
return {
  "ibhagwan/fzf-lua",
  dependencies = { "kyazdani42/nvim-web-devicons" },
  config = function() end,
}
```

### Describe the bug / steps to reproduce

`:lua require ('fzf-lua').lsp_references() `return duplicated results

works well with `:lua vim.lsp.references()` or with Telescope (as shown in bellow video)

https://github.com/user-attachments/assets/6b14dc30-4f6c-4e3a-b8bd-866eb95c9db9

![image](https://github.com/user-attachments/assets/a9a5bd11-febb-4f76-88ff-118d96cc8f74)

**Comment by ibhagwan** [comment]
Can you post the output of `:LspInfo`?

**Comment by crates51** [comment]
![image](https://github.com/user-attachments/assets/e3c1dc22-6c87-4752-bf6f-44f7172e36aa)

 ```
Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /Users/musteatavladislav/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: pyright (id: 1, bufnr: [19, 3])
 	filetypes:       python
 	autostart:       true
 	root directory:  /Users/musteatavladislav/Documents/work-related/repos/iris/iris-be
 	cmd:             /Users/musteatavladislav/.local/share/nvim/mason/bin/pyright-langserver --stdio
 
 Client: pylsp (id: 2, bufnr: [19, 3])
 	filetypes:       python
 	autostart:       true
 	root directory:  /Users/musteatavladislav/Documents/work-related/repos/iris/iris-be
 	cmd:             /Users/musteatavladislav/.local/share/nvim/mason/bin/pylsp
 
 Configured servers list: emmet_ls, prismals, solargraph, graphql, cssls, svelte, lua_ls, pylsp, tailwindcss, html, pyright, ts_ls
 
 Deprecated servers: tsserver -> ts_ls

```

**Comment by crates51** [comment]
I am using pylsp for diagnostics and pyright for the rest (jump to defintion .. etc)
In the past i was only using :lua vim.lsp.references() (with a plugin for quickfix window preview plugin) but i decided to remove that quickfix window preview plugin and fully embrace fzf-lua


Perhaps fzf-lua doesn't digest well that i use 2 servers(?)(pylsp and pyright) ?

**Comment by crates51** [comment]
In my lspconfig.lua

These are my handlers:
```

    local pyright_handlers = {
      ["textDocument/publishDiagnostics"] = function() end,
      ["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, { border = "single", max_width = 100 }),
      ["textDocument/signatureHelp"] = vim.lsp.with(
        vim.lsp.handlers.signature_help,
        { border = "single", max_width = 50 }
      ),
    }

    local pylsp_handlers = {
      ["callHierarchy/incomingCalls"] = function() end,
      ["callHierarchy/outgoingCalls"] = function() end,
      ["textDocument/codeAction"] = function() end,
      ["textDocument/completion"] = function() end,
      ["textDocument/declaration"] = function() end,
      ["textDocument/definition"] = function() end,
      ["textDocument/documentHighlight"] = function() end,
      ["textDocument/documentSymbol"] = function() end,
      ["textDocument/formatting"] = function() end,
      ["textDocument/hover"] = function() end,
      ["textDocument/implementation"] = function() end,
      --["textDocument/publishDiagnostics"] = function() end,
      ["textDocument/rangeFormatting"] = function() end,
      ["textDocument/references"] = function() end,
      ["textDocument/rename"] = function() end,
      ["textDocument/signatureHelp"] = function() end,
      ["textDocument/typeDefinition"] = function() end,
      ["window/logMessage"] = function() end,
      ["window/showMessage"] = function() end,
      ["window/showDocument"] = function() end,
      ["window/showMessageRequest"] = function() end,
      ["workspace/applyEdit"] = function() end,
      ["workspace/symbol"] = function() end,
    }
    lspconfig["pyright"].setup({
      handlers = pyright_handlers,
      capabilities = capabilities,
      on_attach = on_attach,
    })

    lspconfig["pylsp"].setup({
      handlers = pylsp_handlers,
      -- capabilities = capabilities,
      on_attach = on_attach,
      settings = {
        pylsp = {
          configurationSources = {
            "flake8",
          },
          plugins = {
            jedi_definition = {
              enabled = false,
            },
            jedi_completion = {
              enabled = false,
            },
            pycodestyle = {
              enabled = false,
              --maxLineLength = 100,
            },
            pyflakes = {
              enabled = false,
            },
            mccabe = {
              enabled = false,
            },
            flake8 = {
              enabled = true,
              ignore = { "E128", "E131", "E201", "E202", "E251", "E501", "W503", "W504" },
            },
            pylsp_mypy = {
              enabled = false, -- For this to work well, an pylsp-mypy.cfg is neccesary inside the root folder
              -- Also, inside the conda env pylsp_mypy must be installed, an example can be found below
            },
            pylint = {
              enabled = true,
              args = { "--rcfile=~/.config/nvim/lua/vlad/plugins/lsp/pylint_rc.rc" },
            },
          },
        },
      },
    })
```

And only pylsp handles the references:

      ["textDocument/references"] = function() end,

**Comment by ibhagwan** [comment]
> Perhaps fzf-lua doesn't digest well that i use 2 servers(?)(pylsp and pyright) ?

In fact, fzf-lua, digests these all too well, you have 2 clients attached so you’re getting the references from both.

> These are my handlers:

I’m not sure how these are taken into account in the API, fzf-lua uses `buf_request_all` when used in sync mode (default for references):
https://github.com/ibhagwan/fzf-lua/blob/ebb89e4e4065e31b029eee8f618e1ca660f41f35/lua/fzf-lua/providers/lsp.lua#L481

And `buf_request` with `async=true`:
https://github.com/ibhagwan/fzf-lua/blob/ebb89e4e4065e31b029eee8f618e1ca660f41f35/lua/fzf-lua/providers/lsp.lua#L553

Can you try both below and see if it makes a difference?
```lua
:FzfLua lsp_references async=true
:FzfLua lsp_references async=false
```

If both these don’t work I’m not sure how I can take into account your custom handlers.

**Comment by ibhagwan** [comment]
> works well with `:lua vim.lsp.references()` or with Telescope (as shown in bellow video)

Are you sure about the Telescope part? Telescope uses the same API to get the refs, it uses `vim.lsp.buf_request_all` which then calls `vim.lsp.buf_request` (same as fzf-lua with `async=true`).

I installed both `pyright` and `pylsp`, my findings are as follows:
- `:lua vim.lsp.references()` will return one set of the results from the first available attached client
- Both fzf-lua and Telescope return results from both attached LSP clients
- The above is true even after setting up custom LSP handlers with empty lua functions (makes no difference)
- Telescope defaults to ignoring the current line which is the same as `:FzfLua lsp_references ignore_current_line=true`

Looking at the neovim docs:
```md
buf_request_all({bufnr}, {method}, {params}, {handler})
    Sends an async request for ALL active clients attached to the buffer and
    executes the `handler` callback with the combined result.

buf_request_sync({bufnr}, {method}, {params}, {timeout_ms})
    Sends a request to ALL server and waits for the response of all of them.
```

The above API's curently do not contain any parameter to limit which servers handle the request nor would this be the right approach for this, settting the handlers to empty doesn't restrict the request as well so it achieves nothing for this purpose.

You can test if you suceeded with the below one-liner, note my `ruff_lsp` doesn't have a refs provider and therefore won't return references:
```lua
:lua for _, c in ipairs(vim.lsp.get_clients({bufnr=0})) do print(c.id, c.name,c.server_capabilities["referencesProvider"]~=nil) end
```

Your best bet into solving this is to disable the `textDocument/references` capability by disabling the `referencesProvider` in the lsp config, I tried setting `capabilities.textDocument.references = false` but it didn't work, this probably needs a bit more research on your end, start from here https://github.com/neovim/nvim-lspconfig/issues/960.

Closing this issue as unrelated to fzf-lua.

**Comment by crates51** [comment]
I showed in the initial video the behaviour of Telescope. i can put another one:

https://github.com/user-attachments/assets/d0924aac-1278-450e-9f50-d9d2f8398566

I tought fzf-lua should show the equivalence of vim.lsp.buf.references() when it comes to references, perhaps i was wrong.

I appreciate for your research in trying to solve this issue, i think i will stick with telescope with this one.

Thanks

**Comment by ibhagwan** [comment]
> I tought fzf-lua should show the equivalence of vim.lsp.buf.references() when it comes to references, perhaps i was wrong.

Fzf-lua uses the neovim API, whatever is retuned is what will be displayed.

IMHO, if the LSP client supports and enumerates refs it should be shown, the correct way to control that is via capabilities.

> I appreciate your research in trying to solve this issue, i think i will stick with telescope with this one.

Absolutely nothing wrong with that.
