### ISSUE TITLE
Bug: preview toggles when chaging from full screen to normal size and viceversa

### ISSUE THREAD

**Issue by Masber** [ibhagwan/fzf-lua#1479]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux Ubuntu 24.04.1

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.55.0 (fc69308)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
{ -- FZF Lua
    'ibhagwan/fzf-lua',
    -- optional for icon support
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
      -- local actions = require 'fzf-lua.actions'

      -- calling `setup` is optional for customization
      require('fzf-lua').setup {
        defaults = {
          file_icons = false,
          color_icons = false,
          git_icons = false,
          icon_padding = false,
          -- debug = true,
        },
        winopts = {
          height = 0.25,
          width = 1,
          row = 1,
          -- split = 'belowright new',
          -- border = 'none',
          backdrop = 100, -- background opacity
          preview = {
            default = 'bat', -- using `bat` to show file content
            hidden = 'hidden',
          },
        },
        files = {
          -- prompt = 'Files❯ ',
          cwd_prompt = false,
          multiprocess = true, -- run command in a separate process
          formatter = 'path.filename_first',
          fd_opts = ' --no-ignore --hidden', -- if `fd` is installed, then fzf-lua will use it instead of `find` see https://github.com/ibhagwan/fzf-lua/discussions/1475#discussioncomment-10852903
        },
        code_actions = {
          prompt = 'Code Actions> ',
          async_or_timeout = 5000,
          -- when git-delta is installed use "codeaction_native" for beautiful diffs
          -- try it out with `:FzfLua lsp_code_actions previewer=codeaction_native`
          -- scroll up to `previewers.codeaction{_native}` for more previewer options
          previewer = 'codeaction',
        },
      }
      -- vim.keymap.set('n', '<leader>sd', require('fzf-lua').git_files, { desc = 'Search in Documents (polybox)' })
      vim.keymap.set('n', '<leader>sf', require('fzf-lua').git_files, { desc = 'Search Git files' })
      vim.keymap.set('n', '<leader>sg', require('fzf-lua').grep_project, { desc = 'Search Grep' })
      vim.keymap.set('n', '<leader>sa', require('fzf-lua').files, { desc = 'Search All files' })
      vim.keymap.set('n', '<leader>sd', require('fzf-lua').diagnostics_workspace, { desc = 'Search Diagnostics' })
      vim.keymap.set('n', '<leader>ca', require('fzf-lua').lsp_code_actions, { desc = 'Code Actions' })
    end,
  },
```

### Describe the bug / steps to reproduce

I have in my configuration `winopts.preview.hidden = 'hidden'` because I only want to see the preview when I need it (using F4 key to toggle). This initially works meaning, the preview is hidden when I open the 'search file', however, when I toggle the full screen, then the preview also toggles and shows on screen.

How to reproduce:

1. open neovim
2. press `<leader>sf` to search for files
3. Note preview is hidden (expected behavior)
4. press F2 to toggle fzf-lua full screen
5. Note preview now shows on screen (this is not desired since I did not pressed F4)
6. Hide the preview again by pressing F4 (preview is hidden now)
7. toggle fzf-lua full screen by pressing F2 again
8. Note preview now also shows (this is not desired since I hided the preview in earlier and also in the configuration)

**Comment by ibhagwan** [comment]
That happens due to the combination of a "native" fzf previewer (bat) and `flex` layout, fzf-lua will use an fzf "transformer" that changes the layout (vertical or horizontal) based on the available columns:
https://github.com/ibhagwan/fzf-lua/blob/ace9968be267b034e450be4feaf6e9107bc34fbd/lua/fzf-lua/core.lua#L391-L395.

This transfomer is executed on any resize including fullscreen toggle, while I can include the initial preview state (hidden/nohidden) in the transformer that would  not solve this issue as any resize will make the previewer either hidden or hidden based on the initial state.

Unfortunately fixing this issue is not that easy as AFAIK fzf doesn't provide access to an enviroment var that lets us know if the preview is hidden or not, I tried to conditionally toggle the previewer in the transformer using  `$FZF_PREVIEW_LINES` but it doesn't seem to work.

You can workaround this issue by avoiding the `flex` layout, set `winopts.preview.layout` to `vertical` or `horizontal` which doesn't use the transformer

**Comment by Masber** [comment]
thank you, I can set the preview layout to horizontal as a work around

**Comment by ibhagwan** [comment]
> thank you, I can set the preview layout to horizontal as a work around

Ty for the update, closing.
