### ISSUE TITLE
cannot disable --info=inline + map esc to close fzf

### ISSUE THREAD

**Issue by alexzanderr** [ibhagwan/fzf-lua#148]
![image](https://user-images.githubusercontent.com/54772464/134179440-175a79ae-6c7d-45c2-bfed-910454ad3309.png)
this is info inline fzf config, i dont want this.

i tried disabling it from setup {} with `  fzf_args            = '--exact -i -m --info=default'`

it doesnt work.

and another problem: i am unable to find `close_mapping` for closing fzf popup.
i cant close it with `ctlr-q`, but i want to close it from `<esc>`

**Comment by alexzanderr** [comment]
![image](https://user-images.githubusercontent.com/54772464/134180696-eb7c8aaf-9c7b-4e35-8ee3-4717b9c7790a.png)
okey i found in `fzf` man page. there is an abort event which is triggered by default with `esc` or `c-q`, however, ctrl-q works in nvim, but esc doesnt.


and this is my config for fzf_binds, just doesnt work...
```lua
  fzf_binds           = {               -- fzf '--bind=' options
	["esc"] = "abort"
  },
```

**Comment by alexzanderr** [comment]
> lua require('fzf-lua').files({ fzf_info = "--info=default" })

this works, thanks.

about the <esc>, yea it works. it just gets out of insert mode in fzf. it doesnt get me out of fzf popup.

**Comment by alexzanderr** [comment]
ups, i have this `:tmap <Esc>`

**Comment by alexzanderr** [comment]
it works now. i've disabled the mapping. thanks man

**Comment by ibhagwan** [comment]
> ups, i have this `t <Esc> * <C-\><C-N>`
> now makes sense, this also happens in `telescope`
> and every terminal buffer.

Telescope isn't a terminal buffer though.

**Comment by alexzanderr** [comment]
> > ups, i have this `t <Esc> * <C-\><C-N>`
> > now makes sense, this also happens in `telescope`
> > and every terminal buffer.
> 
> Telescope isn't a terminal buffer though.

but i had the same problem. i was put in normal mode in telescope input after pressing esc.
