### ISSUE TITLE
Bug: disable `--ansi` in fzf prints escape chars related to colors?

### ISSUE THREAD

**Issue by Masber** [ibhagwan/fzf-lua#1482]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linus Ubuntu 24.04.1

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.55.0 (fc69308)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
{ -- FZF Lua
    'ibhagwan/fzf-lua',
    -- optional for icon support
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
      -- local actions = require 'fzf-lua.actions'

      -- calling `setup` is optional for customization
      require('fzf-lua').setup {
        fzf_opts = { ['--ansi'] = false, ['--border'] = 'rounded' }, -- Disable fzf --ansi coloring for better performance https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-get-maximum-performance-out-of-fzf-lua
        defaults = {
          file_icons = false, -- better performance https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-get-maximum-performance-out-of-fzf-lua
          color_icons = false,
          git_icons = false, -- better performance https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-get-maximum-performance-out-of-fzf-lua
          icon_padding = false,
          -- debug = true,
        },
        winopts = {
          height = 0.25,
          width = 1,
          row = 1,
          -- split = 'belowright new',
          -- border = { '', '─', '', '', '', '', '', '' },
          border = 'none',
          backdrop = 100, -- background opacity
          preview = {
            default = 'bat_native', -- using `bat_vative` in preview for better performance https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-get-maximum-performance-out-of-fzf-lua
            hidden = 'hidden',
            wrap = 'wrap',
            layout = 'horizontal',
          },
        },
        files = {
          -- prompt = 'Files❯ ',
          cwd_prompt = false,
          multiprocess = true, -- run command in a separate process
          -- formatter = 'path.filename_first',
          fd_opts = ' --type f --no-ignore --hidden ', -- if `fd` is installed, then fzf-lua will use it instead of `find` see https://github.com/ibhagwan/fzf-lua/discussions/1475#discussioncomment-10852903
        },
        -- CUSTOMIATION - 06/10/2024 - keep it simple... try to use vim/neovim low level capabilities to make the app more responsive
        -- code_actions = {
        --   prompt = 'Code Actions> ',
        --   async_or_timeout = 5000,
        --   -- when git-delta is installed use "codeaction_native" for beautiful diffs
        --   -- try it out with `:FzfLua lsp_code_actions previewer=codeaction_native`
        --   -- scroll up to `previewers.codeaction{_native}` for more previewer options
        --   previewer = 'codeaction',
        -- },
      }
      -- vim.keymap.set('n', '<leader>sd', require('fzf-lua').git_files, { desc = 'Search in Documents (polybox)' })
      vim.keymap.set('n', '<leader>sf', require('fzf-lua').git_files, { desc = 'Search Git files in project' })
      vim.keymap.set('n', '<leader>sg', require('fzf-lua').grep_project, { desc = 'Search Grep in project' })
      vim.keymap.set('n', '<leader>sa', require('fzf-lua').files, { desc = 'Search All files in project' })
      vim.keymap.set('n', '<leader>sD', function()
        require('fzf-lua').files { cmd = 'fd "/home/msopena/polybox/Documents/"' }
      end, { desc = 'Search All files in project' })
      vim.keymap.set('n', '<leader>sd', require('fzf-lua').diagnostics_workspace, { desc = 'Search Diagnostics' })

      vim.keymap.set('n', '<leader>gr', function()
        require('fzf-lua').lsp_references { jump_to_single_resuilt = true, includeDeclaration = false, ignore_current_line = true }
      end, { desc = 'Go to References' })
      vim.keymap.set('n', '<leader>gd', function()
        require('fzf-lua').lsp_definitions { jump_to_single_result = true }
      end, { desc = 'Go to Definitions' })
      vim.keymap.set('n', '<leader>gD', function()
        require('fzf-lua').lsp_declarations { jump_to_single_result = true }
      end, { desc = 'Go to Declarations' })
      vim.keymap.set('n', '<leader>gi', function()
        require('fzf-lua').lsp_implementations { jump_to_single_result = true }
      end, { desc = 'Go to Implementations' })
      vim.keymap.set('n', '<leader>gt', function()
        require('fzf-lua').lsp_typedefs { jump_to_single_result = true }
      end, { desc = 'Go to Type Definitions' })
      vim.keymap.set('n', '<leader>gf', require('fzf-lua').lsp_finder, { desc = 'Go to Finder (find all)' })
      -- CUSTOMIATION - 06/10/2024 - keep it simple... try to use vim/neovim low level capabilities to make the app more responsive
      -- vim.keymap.set('n', '<leader>ca', require('fzf-lua').lsp_code_actions, { desc = 'Code Actions' })
    end,
  },
```

### Describe the bug / steps to reproduce

I have disabled ansi in fzf because I don't mind about colors and I prioritize responsiveness.
However I realized, the escape chars for colors are not escaped making difficult to understand the fzf results (see screenshot below)

![image](https://github.com/user-attachments/assets/b64666ac-2cd9-4344-a955-8a1af1d12c27)

**Comment by ibhagwan** [comment]
The performance gains by `--ansi` are because fzf will not try to detect ansi escape codes and display colors, but this isn't a bug, if you're using `--ansi` also make sure the ripgrep results never use colors by using a custom `grep.cmd` or `grep.rg_opts` (see the default command in the README and add `--color=never`).

**Comment by ibhagwan** [comment]
You can add `debug=true` to see the underlying command to see if you did it right (see the first DEBUG line):
![image](https://github.com/user-attachments/assets/c80be479-ff8c-48d3-a34c-c28347d07cc4)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/1e03541de4d8a169defe83bb4d7abfba450c63a1

@Masber, I added `--ansi` to the `max-perf` profile, you can now use:
```lua
require("fzf-lua").setup({ "max-perf" })
-- Or if you prefer window titles instead of prompt titles
require("fzf-lua").setup({ { "default-title", "max-perf" } })
```

**Comment by Masber** [comment]
why not `fzf_opts = { ['--ansi'] = false },` under root?

**Comment by ibhagwan** [comment]
> why not `fzf_opts = { ['--ansi'] = false },` under root?

I have tested all the pickers with it, some other pickers like lsp still have colors, I’d welcome a PR for it if you test the pickers and set the appropriate `hls.xxx` to  false.

**Comment by abenz1267** [comment]
I'm not entirely sure if it's related, but when i use `path.filename_first` as a formatter for grep i get this still:

![image](https://github.com/user-attachments/assets/8ad60e20-4dec-4c82-9978-909c97b177b4)

**Comment by ibhagwan** [comment]
> I'm not entirely sure if it's related, but when i use `path.filename_first` as a formatter for grep i get this still:
> 
> ![image](https://private-user-images.githubusercontent.com/7055955/378058609-8ad60e20-4dec-4c82-9978-909c97b177b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjQ1NDEsIm5iZiI6MTcyOTMyNDI0MSwicGF0aCI6Ii83MDU1OTU1LzM3ODA1ODYwOS04YWQ2MGUyMC00ZGVjLTRjODItOTk3OC05MDljOTdiMTc3YjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTlUMDc1MDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJkYTI5M2RmYzNkMzQ2NmYwNmM2YWJmZmFmM2I0MGNlMGRmMGYyNzhlNmQ3ZGM4NTY2M2MzNDZkOWY0YWQ0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.evhHxBmqIUFDt85LZ9g9B5IyaOByCnl6Blkx0lrGIbc)

Yes, 100% related that’s the ansi escape sequence for the highlight `FzfLuaDirPart`, unlink it or set `hls.dir_part = false` to remove the escape sequence.

**Comment by esn89** [comment]
<img width="1012" alt="Image" src="https://github.com/user-attachments/assets/9f7198b9-d05d-45df-a19d-cdce7c128990" />

I am getting something similar here.  How can I fix this?

My FZF_DEFAULT_OPTS are:
```
--color=fg:#d4be98,fg+:#d4be98,bg:#32302F,bg+:#495156 --color=hl:#a9b665,hl+:#89B482,info:#A89984,marker:#DDC7A1 --color=prompt:#EA6962,spinner:#D3869B,pointer:#7DAEA3,header:#87afaf --color=border:#7C6F64,label:#d4be98,query:#d4be98 --border="sharp" --border-label="fzf" --border-label-pos="0" --preview-window="border-rounded" --prompt="> " --marker=">" --pointer="◆" --separator="─" --scrollbar="│" --layout="reverse" --info="right" --preview "bat --style=numbers --color=always --theme=\"gruvbox-material-dark\" --line-range :500 {}"```

**Comment by ibhagwan** [comment]
> I am getting something similar here. How can I fix this?

That's the icon color escape sequence, you have a few options:
- Remove icons with file_icons = false
- Remove icon coloring with  `color_icons=false`
- Set `fzf_opts["--ansi"] = true` to enable ANSI escape sequence parsing in fzf

**Comment by esn89** [comment]
hmm, no luck here.  I've set that like so:

```lua
return {
    'ibhagwan/fzf-lua',
    -- optional for icon support
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
        -- calling `setup` is optional for customization
        require('fzf-lua').setup({
            winopts = {
                preview = {
                    default = 'bat',
                    layout = 'flex',
                },
            },
            files = {
                -- previewer = 'bat',
                cwd_prompt = false,
                prompt = ' > ',
                fd_opts = [[--color=never --type f --hidden --follow --exclude .git --exclude venv ]],
                rg_opts = [[--color=never --files --hidden --follow -g "!.git" -g "!venv/"]],
            },
            buffers = {
                prompt = ' > ',
            },
            grep = {
                prompt = ' 󰮗 > ',
                rg_opts = '--no-column --column --line-number --no-heading --color=always --smart-case --max-columns=2048 -g "!.git" -g "!venv/" -e',
            },
            fzf_opts = {
                ['--ansi'] = true,
            },
            keymap = {
                builtin = {
                    ['ctrl-r'] = 'toggle-preview-ccw',
                },
                fzf = {
                    ['ctrl-c'] = 'abort',
                    ['ctrl-q'] = 'select-all+accept',
                    ['ctrl-d'] = 'preview-page-down',
                    ['ctrl-u'] = 'preview-page-up',
                },
            },
        })
    end,
}
```

**Comment by ibhagwan** [comment]
@esn89, I can't reproduce this with your config or FZF_DEFAULT_OPTS, can you try with `mini.sh`?

If that still fails open a new issue and we'll handle it separately.

With your config and default opts:

![Image](https://github.com/user-attachments/assets/01c1548a-7fe9-4609-a8ea-a6bb7464027d)
