### ISSUE TITLE
`live_grep` no longer focuses the preview on the matched line

### ISSUE THREAD

**Issue by haze** [ibhagwan/fzf-lua#149]
Title says all, I can record a webm/gif if that would help and/or provide debugging info.

Here's my config:

```lua
require'fzf-lua'.setup {
  winopts = {
    split = 'belowright new',
    win_row = 1,
  },
  preview_border = 'noborder',
  preview_vertical = 'down:80%',
  default_previewer = 'bat',
  files = {
    git_icons = false,
    file_icons = false,
    color_icons = false,
  },
  lsp = {
    git_icons = false,
    file_icons = false,
    color_icons = false,
  },
}
```

NOTE: the line is properly highlighted, it's just not centered / brought to attention within the preview window
I've also tried changing the default preview mechanism from bar to the built in one, but that didn't fix anything.

Seems this was broken in c876f8315afb7e3da491ad496bed68deed74f570

**Comment by ibhagwan** [comment]
The `--delimiter` flag was overwritten after the interactive functions rework, took the opportunity to rework how I process fzf flags.

https://github.com/ibhagwan/fzf-lua/commit/a11f5eb9d4c7cfee5ed18d7d84ce51a553c7b021 should fix it.

**Comment by gegoune** [comment]
Seems like work done in this commit caused fzf to ignore `--color`s specified in environment variable `FZF_DEFAULT_OPTS`.

**Comment by ibhagwan** [comment]
> Seems like work done in this commit caused fzf to ignore `--color`s specified in environment variable `FZF_DEFAULT_OPTS`.

Try now :-)

**Comment by gegoune** [comment]
You are the best, thank you! :)

**Comment by ibhagwan** [comment]
> You are the best, thank you! :)

Ty!
