### ISSUE TITLE
Bug: Failed to run `config` for fzf-lua

### ISSUE THREAD

**Issue by leimath** [ibhagwan/fzf-lua#1491]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

WSL2 + Ubuntu-24.04

### Shell

bash with GNU Screen

### Neovim version (`nvim --version`)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### Fzf version (`fzf --version`)

Nil. Using skim 0.10.4

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
return {
  "ibhagwan/fzf-lua",
  config = function()
    require("fzf-lua").setup({
		fzf_bin = 'sk',
		})
  end
}

``
```

### Describe the bug / steps to reproduce

Installed skim with cargo, with Lazy.nvim installed fzf-lua. Set the fzf-bin. 
Open nvim.

```lua

Failed to run `config` for fzf-lua

Vim:Failed to start server: no such file or directory

# stacktrace:
  - /fzf-lua/lua/fzf-lua/init.lua:40
  - fyz.lua:4 _in_ **config**
  - ~/.config/nvim/lua/redacted/core/packman.lua:21
  - ~/.config/nvim/lua/redacted/core/init.lua:2
  - ~/.config/nvim/init.lua:1
```

Edit: Tried with fzf as a dep as well but still same error.

**Comment by leimath** [comment]
https://github.com/ibhagwan/fzf-lua/issues/1243

Annoying

**Comment by ibhagwan** [comment]
> Leave it too much of a drag to try to fix.

I’m sure there is a fix but unfortunately this is outside the realm of fzf-lua.

**Comment by leimath** [comment]
> > Leave it too much of a drag to try to fix.
> 
> I’m sure there is a fix but unfortunately this is outside the realm of fzf-lua.

`nvim-fzf` works fine ootb. At this point I won't try to dig deeper, not worth it to see some files.
Nice plugin btw. 
Thanks!
