### ISSUE TITLE
Bug: seting cwd in global options is irrelevant

### ISSUE THREAD

**Issue by sidesteps** [ibhagwan/fzf-lua#1494]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

6.10.10-arch1-1

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.55.0 (fc693080)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--bind=ctrl-j:down,ctrl-k:up 

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
fzfLua = require('fzf-lua')
fzfDir = os.getenv('ProjectDir') or '.' 
fzfLua.setup({fzf_colors = true, cwd = fzfDir})
vim.keymap.set('n', '<localleader>f', fzfLua.files) 

})
```

### Describe the bug / steps to reproduce

`ProjectDir` env var is set. It is not empty and is a valid path.

The above setup should respect `cwd` when calling `files` for example. It doesn't.

**Comment by ibhagwan** [comment]
`cwd` isn’t a global setting, it’s picker specific, if you wish to add a setting to all pickers (similarly to `file_icons|git_icons`) add it under `defaults`:
```lua
fzfLua.setup({ fzf_colors = true, defaults = { cwd = fzfDir} })
```

**Comment by sidesteps** [comment]
Thnaks, how about updating README.md to:

Use `setup()` If you wish for a setting to persist and not have to send it using the call
arguments, e.g:
```lua
require('fzf-lua').setup{
  defaults = {
    cwd = "/root/dir/for/all/pickers"
  }
  winopts = {
    ...
  }
}
```

**Comment by ibhagwan** [comment]
> Thanks, how about updating README.md to:

> Use setup() If you wish for a setting to persist and not have to send it using the call
arguments, e.g:

No need, the README already contains a similar explanation under default options:
https://github.com/ibhagwan/fzf-lua/blob/5dec364c9dedec00dcd6d06e323d7bc7f8d6b596/README.md?plain=1#L812-L818

**Comment by sidesteps** [comment]
I beg to differ, anyways, dealers choice
