### ISSUE TITLE
Bug: RIPGREP_CONFIG_PATH is not having any effect

### ISSUE THREAD

**Issue by serranomorante** [ibhagwan/fzf-lua#1499]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

arch linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-865+g99e0facf3-dirty

### Fzf version (`fzf --version`)

0.55.0 (fc693080)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--layout=reverse --border

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  grep = {
    RIPGREP_CONFIG_PATH = "path to your .ripgreprc",			
  }
})
```

### Describe the bug / steps to reproduce

1. Put any `.ripgreprc` on your home dir (example at the bottom)
2. Execute `FzfLua live_grep debug=true`
3. Fzf is still using the default rg_opts and not the .ripgreprc file

```sh
# Add my 'web' type.
--type-add
web:*.{html,css,js}*

# Add my 'lock' type.
--type-add
lock:*-lock.{json,yaml}

--pcre2
--multiline
--column
--line-number
--no-heading
--smart-case
--max-columns=4096
```

**Comment by serranomorante** [comment]
So this option is no longer available? I understand. Thanks!

```lua
require("fzf-lua").setup({
  grep = { RIPGREP_CONFIG_PATH = vim.env.RIPGREP_CONFIG_PATH }
})
```

**Comment by ibhagwan** [comment]
> So this option is no longer available? I understand. Thanks!
> 
> ```lua
> require("fzf-lua").setup({
>   grep = { RIPGREP_CONFIG_PATH = vim.env.RIPGREP_CONFIG_PATH }
> })
> ```

What do you mean no longer available? It’s available and working.

**Comment by ibhagwan** [comment]
> Fzf is still using the default rg_opts and not the .ripgreprc file

The RIPGREP_CONFIG_FILE is passed as an env var to the fzf process, I assume some of the options in the file will be overwritten by `rg_opts`, if you wish for these to be overwritten then you can set `rg_opts = ''` just make sure that at the minimum you have both column and line numbers in the entries.

**Comment by serranomorante** [comment]
You're right it works, sorry. I got confused by trusting too much on the `debug=true` flag which seems to not show the `RIPGREP_CONFIG_PATH` options and only the `rg_opts` ones. That's fine.

Thanks!

**Comment by ibhagwan** [comment]
> You're right it works, sorry. I got confused by trusting too much on the `debug=true` flag which seems to not show the `RIPGREP_CONFIG_PATH` options and only the `rg_opts` ones. That's fine.
> 
> Thanks!

Ty for the update @serranomorante!
