### ISSUE TITLE
Expose lua functions as commands

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#15]
What do you think about exposing all providers as commands? `:FzfFiles`, etc?

**Comment by ibhagwan** [comment]
I gave it some thought at first, it’s certainly not a bad idea, especially if you give users the option to set their own prefix so the commands won’t conflict with anything else.

That said, IMO it’s a low priority feature, I’d rather add git providers (commits, branches) and built in vim commands like registers, marks, etc before these “luxury” features.

**Comment by gegoune** [comment]
Absolutely! Feel free to close it or keep open as a reminder. I for one would map most of my day to day pickers to keys, but sometimes I might want to use some of the less common ones for which I would not have a mapping and using commands with power of autocompletion would make it easier, but as you said, low priority.

**Comment by shadmansaleh** [comment]
I think instead of having separate commands for different things like fzf.vim . Exposing all of them through a single command like `:Telescope` will be better .

**Comment by ibhagwan** [comment]
> I think instead of having separate commands for different things like fzf.vim . Exposing all of them through a single command like `:Telescope` will be better .

Just added this to the latest commit, you can now run `:FzfLua <cmd> <args>` exactly like Telescope **with auto-complete** (I borrowed and modified it's `command.lua` from Telescope).

For example this is how you'd run the `files` command:
```vim
:FzfLua files cwd=~/.config/nvim prompt=VimRc>
```
