### ISSUE TITLE
toggle fullscreen for builtin previewers doesn't make fzf search windows fullscreen.

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#150]
Hi, I think we should make the toggle fullscreen apply to both fzf search window and preview window.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7a554bb2b2aeeaa45c418d51bff10fdedcae4b59 closes this issue.

The builtin previewer keymap options were migrated, see `keymap.builtin` in the README, default keybind remains `<F2>`.
