### ISSUE TITLE
Feature: respect `RIPGREP_CONFIG_PATH` by default

### ISSUE THREAD

**Issue by looshch** [ibhagwan/fzf-lua#1506]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

i think respecting `RIPGREP_CONFIG_PATH` by default makes more sense since it’s a global, rc-family configuration, so naturally i imagine more people would tend to prefer it to be acknowledged as opposed to explicitly opting into it. If one doesn’t want it, setting it to `false` or something should do the job. What do you think? Thanks!

**Comment by ibhagwan** [comment]
We’ve been through this discussion already see #1266, the decision was against this.

**Comment by ibhagwan** [comment]
No worries, Ty @looshch for your interest in the project!
