### ISSUE TITLE
Feature: Filter specific symbols in lsp_document_symbols

### ISSUE THREAD

**Issue by wustho** [ibhagwan/fzf-lua#1517]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Currently seems like lsp_document_symbols shows all symbols in buffer (classes, functions, variables). It would be nice to have a feature so that we can filter out some symbols like 'variables'. There was this feature in telescope some kinda like
```
    --                 lsp_document_symbols = {
    --                     ignore_symbols = {
    --                         'variable',
    --                         'property',
    --                     },
    --                 },
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/issues/1209

**Comment by xixiaofinland** [comment]
@ibhagwan I know this is closed already, but I couldn't figure out how to exclude two strings.
Such as "Variable" and "Field", 
I attempt "Field|Variable" as below, but it seems to use the exact match rather than as "A or B" pattern

```
function() fzf.lsp_document_symbols({ regex_filter = { "Field|Variable", exclude = true } }) end
```

**Comment by ibhagwan** [comment]
> @ibhagwan I know this is closed already, but I couldn't figure out how to exclude two strings. Such as "Variable" and "Field", I attempt "Field|Variable" as below, but it seems to use the exact match rather than as "A or B" pattern
> 
> ```
> function() fzf.lsp_document_symbols({ regex_filter = { "Field|Variable", exclude = true } }) end
> ```

The string is matched with lua’s `string.match` when used with `exclude` that would turn into `not string.match(…, “<pattern>”)`.

I don’t think lua has an OR operation in its patterns, use a function and instead and have your own filtering (you can also use `vim.regex` this way):
```lua
regex_filter = function(str)
  if str:match('a') or str:match('b') then return false end
end
```

There’s an example on how to use regex with this somewhere in the issues.

**Comment by xixiaofinland** [comment]
i get it working like so just in case somebody needs it in the future.

```
                        regex_filter = function(item, _)
                            if item.kind:match('Struct') or item.kind:match('Enum') or item.kind:match('Method') then
                                return true
                            else
                                return false
                            end
                            -- if item.kind:match('Variable') or item.kind:match('Field')
                            -- then
                            --     return false
                            -- else
                            --     return true
                            -- end
                        end
```

**Comment by ibhagwan** [comment]
Ty @xixiaofinland, although you can probably simplify this by using vim.regex.
