### ISSUE TITLE
Fuzzy grep

### ISSUE THREAD

**Issue by hnspn** [ibhagwan/fzf-lua#152]
how can we make the grep command (using rg) fuzzy.
the original plugin fzf.vim's :Rg command is fuzzy

**Comment by ibhagwan** [comment]
`grep` is fuzzy,`live_grep` is not (uses new `rg` each keystroke.

If you wish to use fuzzy for a live grep result set just exit the live grep and run `FzfLua grep_last`, the search query is saved so your last live grep should open up within grep so you can fuzzy find on the result set.

**Comment by hnspn** [comment]
thanks

**Comment by breuerfelix** [comment]
@ibhagwan is there a way to implement this as an extra command? the last grep is not saved across multiple neovim starts. everytime i start a new neovim session, i first have to exit the "grep for" question.

or maybe what about a permanent config setting that users can specify live_grep to be fuzzy or not?  i loved this feature of the normal fzf and i really cant find sh* without fuzzy ahah :D
