### ISSUE TITLE
Bug: Builtin preview scroll misbehaviors

### ISSUE THREAD

**Issue by MrConnorKenway** [ibhagwan/fzf-lua#1525]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

macOS 14.6.1

### Shell

zsh

### Neovim version (`nvim --version`)

v0.10.2

### Fzf version (`fzf --version`)

0.55.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
{
  'ibhagwan/fzf-lua',
  dependencies = { 'nvim-tree/nvim-web-devicons' },
  config = function()
    require('fzf-lua').setup {
      'default-title',
      files = {
        git_icons = false
      },
      winopts = {
        preview = {
          default = 'builtin',
          delay = 10
        }
      },
      previewers = {
        builtin = {
          treesitter = { enable = true }
        }
      },
      keymap = {
        builtin = {
          ['<C-u>'] = 'preview-page-up',
          ['<C-d>'] = 'preview-page-down'
        }
      }
    }
  end
}
```

### Describe the bug / steps to reproduce

# Issue 1:
Sometimes preview-half-page-up only scrolls up one line rather than half page. 
## To reproduce
Execute `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"`, run `:FzfLua files`, and press "shift-arrow down" to scroll down half page, the first line number of preview window becomes 20:
<img width="1489" alt="image" src="https://github.com/user-attachments/assets/e9ffc0f1-e296-4491-a991-35c971bc0440">
Now press "shift-arrow up", the first line becomes 19 instead of 1:
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/968c12ea-20f6-425e-abd8-1f3353ce8112">
Press "shift-arrow up" again, the first line becomes 1.
# Issue 2:
Preview-page-up only scrolls up half page instead of whole page. I've check fzf previewer like bat, and the preview scroll is normal.

**Comment by ibhagwan** [comment]
> Sometimes preview-half-page-up only scrolls up one line rather than half page.
> Preview-page-up only scrolls up half page instead of whole page. I've check fzf previewer like bat, and the preview scroll is normal.

That is somewhat by design, the neovim previewer sends `ctrl-d|u` to the buffer and this is it’s behavior when close to the top of the buffer (unlike `ctrl-f|b`), I’m not sure why that is but that’s how neovim works, if you wish to fix that it’s better to discuss this upstream.

**Comment by MrConnorKenway** [comment]
Thanks your fast comment for issue 1. Sorry to bother but I still want to know why I can't scroll a whole page back.

**Comment by MrConnorKenway** [comment]
Oh, another question. In telescope.nvim I can scroll to to the top of buffer using one `<C-u>`, so telescope does not use neovim's builtin previewer? But their document says that

> The default previewers are from now on `vim_buffer_` previewers. They use vim buffers for displaying files and use tree-sitter or regex for file highlighting.

I think this sort of sounds like builtin previewer?

**Comment by ibhagwan** [comment]
Idk what telescope does now exactly but as far as I recall the preview sends ctrl-u/d to scroll, if you want to match Telescope’s behavior change `keymap.builtin` to `preview-half-page-{up|down}` (instead of full page which sends ctrl-b/f).

Here’s my original comment in the code for this issue:

https://github.com/ibhagwan/fzf-lua/blob/8af7f00a11fbeb33a88cf95c951460eb8b1fb531/lua/fzf-lua/previewer/builtin.lua#L360-L374


I modified the ctrl-b hack to also scroll up to top if the change is just 1 line, it’s not perfect and depending on the size of the preview near the top it will sometimes scroll 2 lines (and only then you can press another scroll to top), although I could fix this to scroll by relative number of lines by manually moving the cursor I won’t think this issue is worth the time, if you’re really bothered by it change the key maps to `preview-half-page-{up|down}` which don’t have this issue.

**Comment by nyngwang** [comment]
> > Sometimes preview-half-page-up only scrolls up one line rather than half page.
> > Preview-page-up only scrolls up half page instead of whole page. I've check fzf previewer like bat, and the preview scroll is normal.
> 
> That is somewhat by design, the neovim previewer sends `ctrl-d|u` to the buffer and this is it’s behavior when close to the top of the buffer (unlike `ctrl-f|b`), I’m not sure why that is but that’s how neovim works, if you wish to fix that it’s better to discuss this upstream.

@ibhagwan  Hi, I'm using the following config but `<shift-{up,down}>` always call `preview-half-page-{up,down}` regardless the quoted line:

```lua
        keymap = {
          builtin = {
            -- neovim builtin window.
            ['<S-up>'] = 'preview-page-up',
            ['<S-down>'] = 'preview-page-down',
            ['<F1>'] = 'toggle-preview',
            ['<F2>'] = 'toggle-fullscreen',
            ['<F3>'] = 'toggle-help',
          },
          fzf = {
            -- fzf's native previewer.
            ['shift-up'] = 'preview-page-up',
            ['shift-down']   = 'preview-page-down',
            ['f1'] = 'toggle-preview',
          },
        },
```

**Comment by phanen** [comment]
It first did a full page scroll, but then `utils.zz()` center your view point, so visially scroll back half-page: 
https://github.com/ibhagwan/fzf-lua/blob/15d5cd9a74da7f8739030a5c411c046c70f66a60/lua/fzf-lua/previewer/builtin.lua#L496.

Workaround:
```
:FzfLua files winopts.preview.winopts.scrolloff=1000
:FzfLua live_grep_glob winopts.preview.winopts.scrolloff=1000
```
