### ISSUE TITLE
Bug: Zoxide command in Fzf-lua with sed breaks preview

### ISSUE THREAD

**Issue by esn89** [ibhagwan/fzf-lua#1526]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.2

### Fzf version (`fzf --version`)

0.56.2 (MacPorts)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color=fg:#d4be98,fg+:#d4be98,bg:#32302F,bg+:#495156 --color=hl:#a9b665,hl+:#89B482,info:#A89984,marker:#DDC7A1 --color=prompt:#EA6962,spinner:#D3869B,pointer:#7DAEA3,header:# 87afaf --color=border:#7C6F64,label:#d4be98,query:#d4be98 --border="sharp" --border-label="fzf" --border-label-pos="0" --preview-window="border-rounded" --prompt="> " --marker= ">" --pointer="◆" --separator="─" --scrollbar="│" --layout="reverse" --info="right" --preview "bat --style=numbers --color=always --theme=\"gruvbox-material-dark\" --line-range  :500 {}"  

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
_G.fzf_dirs = function(opts)
    local fzf_lua = require('fzf-lua')
    opts = opts or {}
    opts.prompt = ' 📁 '
    opts.fn_transform = function(x)
        return fzf_lua.utils.ansi_codes.cyan(x)
    end
    opts.preview = 'eza --color=always -T -L 3 {}'
    opts.actions = {
        ['default'] = function(selected)
            if selected[1] == nil then
                vim.notify_once('derp')
                return
            end
            vim.cmd('cd ' .. selected[1])
        end,
    }
    fzf_lua.fzf_exec('zoxide query -l', opts)
end
```

### Describe the bug / steps to reproduce

I have a function here which simply sends the zoxide query -l list of directories to fzf to be "fuzzy-found".

The moment I change the bottom command to:

`zoxide query -l | sed #/Users/me/#~#` it breaks.  The preview window cannot do `eza` on it, even though, the sed command works and I can see the list of folders to be fuzzy-found.

**Comment by ibhagwan** [comment]
> it breaks. The preview window cannot do eza on it, even though, the sed command works and I can see the list of folders to be fuzzy-found.

What do you mean breaks? What does the preview show?

**Comment by esn89** [comment]
So this works in the shell:

```
zoxide query -l | sed s#/Users/me/#~# | fzf --preview='eza --color=always -T -L 3 {}'
```

I will try with quotes

**Comment by esn89** [comment]
Actually I lied, the above line that I just talked about in the previous comment does NOT work.  The preview shows nothing.

**Comment by ibhagwan** [comment]
> Actually I lied, the above line that I just talked about in the previous comment does NOT work. The preview shows nothing.

Well, solve it in the shell and fzf-lua will most likely work as well, although the exact command slightly differs and uses `FZF_DEFAULT_COMMAND` and wrapped in `sh -c '…'`.

**Comment by ibhagwan** [comment]
I did some testing, all of the variants I tested works for me, your issue is most likely bad command or perhaps replacing `Users` with `me` in the path is your issue?

In any event, this isn’t an issue with fzf-lua, feel free to reopen if you have an example the proves otherwise.

**Comment by esn89** [comment]
What was the command you used to make it work?

**Comment by ibhagwan** [comment]
Same
