### ISSUE TITLE
[ Feature Request ] Git Status takes you to first line of Hunk

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#153]
I was fixing up some code in a rebase today and I wanted to quickly navigate to a merge conflict hunk. 

I utilized "FzfLua git_status" which was helpful enough to show me the merge conflict hunk. 

![image](https://user-images.githubusercontent.com/5642902/134532033-4e4ac850-d316-413c-ac03-0bc3a9e9af54.png)

It would be nice if hitting "enter" on this fzf entry navigated Nvim to the start of that Hunk.

**Comment by ibhagwan** [comment]
> I could also see a "FzfLua git_diff" being used this way as well. Food for thought.

`git_status` is essentially `git_diff`, if you want something that shows only diffs (I.e. no untracked or deleted), you can just change the git status `cmd = 'git diff --name-only'`.

> It would be nice if hitting "enter" on this fzf entry navigated Nvim to the start of that Hunk.

Sure would be a nice addition, but it would come with a few caveats and inconsistencies: which chunk to navigate to when it comes to multiple changes in the same files? Not having this functionality for deleted and untracked files.

The implementation is also no straight forward as it requires to run an external command on selection, parse the git output and then decide which line is the correct one.

I don’t think it’s worth the effort, there are better tools for hunk and change management and it’s better to use those instead, my workflow use s[gitsigns](https://github.com/lewis6991/gitsigns.nvim/) for hunk management, after opening a file from `git_status` I use `]c` `[c` to navigate back and forth between hunks, from there I can preview, blame, stage/unstage, etc.

**Comment by ldelossa** [comment]
Fair enough, thanks for consideration. I will def take a look at gitsigns.

**Comment by ibhagwan** [comment]
> Fair enough, thanks for consideration. I will def take a look at gitsigns.

This one is also pretty good for a more in depth `git status` exploration, also written in lua: [diffview.nvim](https://github.com/sindrets/diffview.nvim).

**Comment by ldelossa** [comment]
thanks a ton. will check em' out.
