### ISSUE TITLE
Feature: a `toggle_exact` action

### ISSUE THREAD

**Issue by tristan957** [ibhagwan/fzf-lua#1534]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I tried searching for a similar issue, but it would be awesome to have a `toggle_exact` action which toggles fzf's `--exact flag`. Sometimes, I just want to exactly live grep a project.

**Comment by ibhagwan** [comment]
It’s pointless to add a new action for every imaginable flag, use `toggle_flag` option or create your own customization, see https://github.com/ibhagwan/fzf-lua/pull/1502 for more info.
