### ISSUE TITLE
Bug: Default keymaps doesn't work with newer version of skim

### ISSUE THREAD

**Issue by pr4th4m** [ibhagwan/fzf-lua#1536]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

v0.10.2

### Fzf version (`fzf --version`)

sk 0.12.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--layout=reverse --border

### Is the problem reproducible with `mini.sh`?

- [x] My issue is reproducible with `mini.sh`
- [x] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
      fzf_bin  = 'sk',
})
```

### Describe the bug / steps to reproduce

With newer version of sk (0.12.0), I am getting two issues

1. Invalid tiebreak option
```
[Fzf-lua] fzf error 2: error: invalid value 'index' for '--tiebreak <TIEBREAK>'
```
As as work around I added below, I guess default `index` option needs to be changed
```
fzf_opts = {
   ["--tiebreak"] = "score",
},
```

2. `<ctrl-g>` mapping doesn't work, popup just disappears. Infact, I tried custom actions as well, they don't seem to work as well.
```
files = {
  actions   = {
     ["ctrl-i"] = { actions.toggle_ignore },
     ["ctrl-g"] = { actions.toggle_hidden },
  }
}
```

**Comment by ibhagwan** [comment]
Skim has recently moved to its own org and restated development in high pace, there’s a new version almost every day, v12.0 added the reload action which I plan to add support for (seamless refresh of the actions).

I’ll give it some more time for the development blitz to settle down and make the necessary adjustments.

**Comment by pr4th4m** [comment]
That sounds fair, thanks 👍🏼

**Comment by ibhagwan** [comment]
I did some testing, all the issues mentioned here are upstream bugs.

> Invalid tiebreak option

Already solved in https://github.com/skim-rs/skim/pull/609 (works with v0.13).

> <ctrl-g> mapping doesn't work, popup just disappears. Infact, I tried custom actions as well, they don't seem to work as well.

Newly introduced issue, still bugged with 0.13, opened an issue upstream:  https://github.com/skim-rs/skim/issues/622

**Comment by pr4th4m** [comment]
@ibhagwan thanks for following this up. I agree with what you said earlier, to wait till initial development spike cools off

**Comment by ibhagwan** [comment]
Both issues fixed upstream on HEAD, closing.
