### ISSUE TITLE
issue with performance and fzf-lua is changing terminal title

### ISSUE THREAD

**Issue by alexzanderr** [ibhagwan/fzf-lua#154]
https://user-images.githubusercontent.com/54772464/134674543-98f68662-7485-4d38-b83c-c6e95ea52650.mp4

for me. fzf-lua is very slow compared to fzf.vim (im using lua config)

i really love fzf and this plugin.

when searching with preview, scrolling up and down the terminal title is changed with the previewed file name. is it somewhere in my settings a `change terminal title` or this plugin is doing the `change terminal title` ?

and is there a way to make this plugin run faster?

i've noticed that in fzf.vim, the preview is not made instantly if the user is scrolling down/up fast.

here in fzf-lua the preview comes up almost instantly and i think this is reason for bad performance.

**Comment by alexzanderr** [comment]
okey i found that i had `set title`. i've set title to `fasle`, the terminal title is not changing anymore.

but the performance is still bad.

**Comment by alexzanderr** [comment]
another question (to not open another issue): how do i change the fzf-lua `cursor shape`
![image](https://user-images.githubusercontent.com/54772464/134677271-6f8892b9-5579-48d3-8be7-c597d319b93e.png)

right now its `block`, i want it i-beam

**Comment by ibhagwan** [comment]
Ok, we have many different options to enhance performance and match it to `fzf.vim`, just need to isolate the issue first.

- Press `F4` to close the builtin previewer. Does this happen when the previewer is off too?
- Try with `bat` previewer (same as `fzf.vim`), in your setup function try with 2 different options:
  + `default_ previewer = 'bat’`
  + `default_ previewer = 'bat_native’`
- Does this happen only in `live_grep` or also in `files` and other providers?
- If this happens in `files` too, what happens when you run without icons/colors and removing the `—ansi` option:
```lua
:lua require'fzf-lua’.files({ file_icons = false, git_icons = false,  fzf_ansi = '' })
```

> another question (to not open another issue): how do i change the fzf-lua cursor shape
image, right now its block, i want it i-beam

Fzf-lua opens a terminal inside neovim to run fzf, the cursor shape is controlled by the neovim terminal emulator, I haven’t played around with changing the cursor shape, see the discussion below, if you can figure out how to change the cursor when running `:new | term` the same will apply to fzf-lua:

https://github.com/neovim/neovim/issues/3681

**Comment by ibhagwan** [comment]
More on how to change the term cursor, maybe the lead you need

https://github.com/neovim/neovim/issues/2475

**Comment by alexzanderr** [comment]
this fixed the performance `default_previewer = 'bat'`

but there is another problem. `live_grep` is very slow on huge project. i mean its working fine. but when writing fast, deleting fast writing again fast and deleting again and writing again is a very expensive operation. the cpu is spiking and sometimes, when i close `fzf live_grep` with esc, the cpu is still spiking with all 8 cores (`rg --files ...` in the background) over 10 seconds. even after a long time after i closed fzf popup

**Comment by alexzanderr** [comment]
about the cursor, that issues dont help.

**Comment by ibhagwan** [comment]
> this fixed the performance `default_previewer = 'bat'`
> 
> but there is another problem. `live_grep` is very slow on huge project. i mean its working fine. but when writing fast, deleting fast writing again fast and deleting again and writing again is a very expensive operation. the cpu is spiking and sometimes, when i close `fzf live_grep` with esc, the cpu is still spiking with all 8 cores (`rg --files ...` in the background) over 10 seconds. even after a long time after i closed fzf popup

Can you try `:FzfLua live_grep_native` instead?

Also, can you let me know what was the `rg` command that you ran with live grep and `fzf.vim` so we can match the setup you had with `fzf.vim`?

**Comment by ibhagwan** [comment]
> about the cursor, that issues dont help.

You’re gonna have to do some research on your own then to see if this is solvable, as I mentioned fzf-lua has no control on neovim’s terminal emulator cursor shapes.

**Comment by alexzanderr** [comment]
this is the `rg` command. its use in `fzf.vim` and `fzf-lua`
![image](https://user-images.githubusercontent.com/54772464/134815076-8adef0f8-4575-4244-87bf-b432de2b3fa1.png)


wow `:FzfLua live_grep_native` is really fast, but what is the difference?

**Comment by alexzanderr** [comment]
hmm, now i understand.


> basically "continue" the search next time you open live_grep.

i saw that, its annoying


how about `live_grep_resume` ?

**Comment by ibhagwan** [comment]
> hmm, now i understand.
> 
> > basically "continue" the search next time you open live_grep.
> 
> i saw that, it’s annoying
>
> how about `live_grep_resume` ? i guess has the same behaviour

They are both the same function, for people to get acquainted with the functionality I change the default to to the resume veraion, it’s very easy to disable by running `:FzfLua live_grep continue_last_search=false`.

I might change the default back to no resume, I’m getting annoyed with it too.

**Comment by alexzanderr** [comment]
cool. thanks a lot for support and docs.

**Comment by ibhagwan** [comment]
> cool. thanks a lot for support and docs.

Ty, I’ll keep this thread open until I explore if I can make `live_grep` as performant as `live_grep_native`.

Btw, the docs are actually the only big task left for me in this project, that is completing the Wiki.

**Comment by alexzanderr** [comment]
add me ( `alexzander#5442` ) on discord, please, to talk more about your great plugin.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/70c0337f8e18272c0f1ea9ef370eecbd9f4ef18f changes the default live grep to `live_grep_native`.

https://github.com/ibhagwan/fzf-lua/commit/fdae33b04765b53b902e35f12b1b12d8d3350ade should solve the performance issue by killing previously running search when executing a new one.

**Comment by alexzanderr** [comment]
cool. im gonna check it out.

**Comment by shmerl** [comment]
Sorry for the tangent, but what is the difference between live_grep and live_grep_native? The first runs `rg` and the second doesn't?

**Comment by ibhagwan** [comment]
> Sorry for the tangent, but what is the difference between `live_grep` and `live_grep_native`? The first runs `rg` and the second doesn't?

The earlier runs the command within a neovim headless wrapper (to add icons, etc), the latter runs the `rg` command directly in the shell with no wrapper.

**Comment by shmerl** [comment]
Can  you please also add live_grep_glob_native for parity?

Thanks!

**Comment by ibhagwan** [comment]
> Can you please also add `live_grep_glob_native` for parity?
> 
> Thanks!

Not possible, the entire point of "native" is to not have any processing done at all by neovim/fzf-lua and have fzf and the shell responsible for everything (thus "native").
