### ISSUE TITLE
Bug: `bad argument #2 to 'format' (number expected, got nil)`

### ISSUE THREAD

**Issue by meshy** [ibhagwan/fzf-lua#1540]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Ubuntu Linux 22.04.5 LTS

### Shell

zsh

### Neovim version (`nvim --version`)

v0.11.0-dev

### Fzf version (`fzf --version`)

0.29 (devel)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

When I run `:FzfLua`, I see this error:

```
Error executing Lua callback: ...lie/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/utils.lua:1184: bad argument #2 to 'format' (number expected, got nil)                       
stack traceback:                                                                                                                                                             
        [C]: in function 'format'                                                                                                                                            
        ...lie/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/utils.lua:1184: in function 'version_str_to_num'                                                                   
        ...lie/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/utils.lua:1194: in function 'fzf_version'                                                                          
        ...ie/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/config.lua:494: in function 'normalize_opts'                                                                        
        ...rlie/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/init.lua:433: in function <...rlie/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/init.lua:432>                       
        ...arlie/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/cmd.lua:35: in function 'run_command'                                                                            
        ...harlie/.local/share/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:12: in function <...harlie/.local/share/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:11>
```

I don't know Lua, but I think that this is caused by https://github.com/ibhagwan/fzf-lua/commit/e2f7165788ab36431680867d087d093470cc236e, which does not account for the fact that some version numbers do not include a third (bug-patch) number.

The version of fzf that Ubuntu 22.04 installs is 0.29, and running `fzf --version` gives `0.29 (devel)`.

Thanks for this great tool!

**Comment by rpbaptist** [comment]
I have the same error on Ubuntu 24.04.1 LTS. I fixed it by putting the `fzf` binary into my local user bin path and letting Neovim know about it.

https://github.com/junegunn/fzf/releases

**Comment by ibhagwan** [comment]
> I don't know Lua, but I think that this is caused by https://github.com/ibhagwan/fzf-lua/commit/e2f7165788ab36431680867d087d093470cc236e, which does not account for the fact that some version numbers do not include a third (bug-patch) number.

> The version of fzf that Ubuntu 22.04 installs is 0.29, and running fzf --version gives 0.29 (devel).

Ty @meshy, you are correct, on my machine I tested older versions and the minor was displayed as `0.29.0`, so I assumed wrongly all versions have a patch num.

Should work as expected after https://github.com/ibhagwan/fzf-lua/commit/dcbf999caf9782a6ce252f5c6837120a540461ad.

> I have the same error on Ubuntu 24.04.1 LTS. I fixed it by putting the fzf binary into my local user bin path and letting Neovim know about it.

@rpbaptist, the bug was with fzf-lua, the likely reason this worked for you is the versions you let neovim know about most lkely has a patch number in the `fzf --version` output whereas the one in your global path didn't.
