### ISSUE TITLE
Feature: Make git_bcommits follow renamed files

### ISSUE THREAD

**Issue by mikehaertl** [ibhagwan/fzf-lua#1544]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

The `git_bcommits` command does not list the full history if a file was renamed in some previous commit. Other tools like [vim-fugitive](https://github.com/tpope/vim-fugitive)'s `:0GClog` can handle this.

I tried to add a `--follow` option here and it now showed also the commits before the file was renamed. But the preview window does not work for these older commits.
https://github.com/ibhagwan/fzf-lua/blob/3bd795ab8536435a1d61b8f394d83c88d1494403/lua/fzf-lua/defaults.lua#L396-L397

**Comment by ibhagwan** [comment]
The preview command is `git show --color {commit sha} -- {file}` which is most likely why it fails for commits where the file was named differently , if you can find a command that can handle the renames it would work.

> The git_bcommits command does not list the full history if a file was renamed in some previous commit. Other tools like [vim-fugitive](https://github.com/tpope/vim-fugitive)'s :0GClog can handle this.

If you can save me some time and research the logic behind the fugitive command I’m sure I can replicate the behavior.

**Comment by mikehaertl** [comment]
Fugitive works a bit different: It opens the quickfix list and every entry represents one specific version of the current file. So when you select an entry in the qf window, it shows the full file at that commit.

It does nifty things, to achieve this: It first fetches the commit log in a custom format by a command like this:

```
git '--no-pager' '-c' 'diff.context=0' '-c' 'diff.noprefix=false' \
    'log' '--no-color' '--no-ext-diff' '--pretty=format:fugitive %h %P^I%H %s' '--summary' '--follow' \
    ./myfile.txt
```

The output not only includes the commit hashes and messages but also any mode changes and rename operations. It then seems to parse all the data from this output and also detects renaming operations. This way it can also get the old name of the file. It all happens around here I think:

https://github.com/tpope/vim-fugitive/blob/320b18fba2a4f2fe3c8225c778c687e0d2620384/autoload/fugitive.vim#L6026-L6034

A rename line looks like this in the output:
```
 rename path/to/{oldname.txt => newname.txt} (77%)
```

This all seems pretty sophisticated - I don't think it's easy to do something similar with fzf-lua.

**Comment by ibhagwan** [comment]
> It does nifty things, to achieve this: It first fetches the commit log in a custom format by a command like this:
> This all seems pretty sophisticated - I don't think it's easy to do something similar with fzf-lua.

Anything is possible but I also believe not absolutely everything has to be implemented, bang for the buck here, just to get bcommits rename history I don’t think is worth the complexity.

**Comment by mikehaertl** [comment]
@ibhagwan I desperately was missing this feature so I gave it another try after I learned about `--with-nth` option in fzf. See pull request.

Disclaimer: I admittedly had some help from an AI agent - I hope that's acceptable. The solution really seems to work fine though.
