### ISSUE TITLE
Bug: [Fzf-lua] invalid previewer 'bat  --paging=never --style=plain --theme=base16'

### ISSUE THREAD

**Issue by GopherJ** [ibhagwan/fzf-lua#1549]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1723675123 Run "nvim -V1 -v" for more info

### Fzf version (`fzf --version`)

0.54.3 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--bind 'ctrl-p:up,ctrl-n:down'

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
				files = {
					fd_opts = "--type f " .. vim.fn.getenv("FD_DEFAULT_COMMAND"):gsub("^fd%s*", ""),
				},
				git = {
					files = {
						cmd = "git status --porcelain | awk '{print $2}'",
					},
				},
				fzf_bin = "fzf-tmux",
				fzf_opts = {
					["--border"] = "sharp",
					["--no-separator"] = "",
				},
				fzf_colors = {
					["bg"] = { "bg", "Normal" },
					["fg"] = { "fg", "Normal" },
					["border"] = { "fg", "Normal" },
				},
				fzf_tmux_opts = { ["-p"] = "80%,90%" },
				winopts = { preview = { default = "bat  --paging=never --style=plain --theme=base16" } },
				manpages = { previewer = "man_native" },
				helptags = { previewer = "help_native" },
				tags = { previewer = "bat_async" },
				btags = { previewer = "bat_async" },
			})
```

### Describe the bug / steps to reproduce

invalid previewer

**Comment by ibhagwan** [comment]
This isn't a bug, `bat` is the name of the previewer table, if you want to define a different command use `previewers.bat`:
```lua
require("fzf-lua").setup({
  previewers = {
    bat = {
      cmd   = "bat",
      args  = "--paging=never --style=plain",
      theme = "base16"',
    },
  }
})
```
