### ISSUE TITLE
Feature: Loop around results with <C-p>/<C-n>

### ISSUE THREAD

**Issue by TheJoeSchr** [ibhagwan/fzf-lua#1564]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Hi, 
New user here, coming from telescope because of the LazyVim changes. I searched the wiki and grep'ed through the repo for this, but couldn't find a resolution.

My issue/feature request is this: When I for e.g. grep something, I often want to jump to the end of the list. In telescope I could do this by pressing "up" `<C-p>` when the cursor is on the first result (see image).
![image](https://github.com/user-attachments/assets/958cafb9-2219-4c07-acf2-c2338a7cffb8)

In fzf-lua that doesn't seem to work, would be great if this could be enabled.

Thanks

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/issues/861

**Comment by TheJoeSchr** [comment]
Thanks so much, sorry for not finding the existing issue

**Comment by ibhagwan** [comment]
> Thanks so much, sorry for not finding the existing issue

No worries, the names of the functionality you’re after isn’t always straight forward (cycle vs wrap).
