### ISSUE TITLE
Bug: when filtering and there are no longer results, the preview window sometimes opens with `nil`

### ISSUE THREAD

**Issue by folke** [ibhagwan/fzf-lua#1567]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

arch

### Shell

fish

### Neovim version (`nvim --version`)

nightly

### Fzf version (`fzf --version`)

0.56.3

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

not set

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

When opening document symbols, and typing a string that would not match, the preview window seems to open with `nil`.

![image](https://github.com/user-attachments/assets/2404266e-4d9c-4537-88bc-5398968d34f9)

**Comment by ibhagwan** [comment]
> When opening document symbols, and typing a string that would not match, the preview window seems to open with `nil`.

I think this might be related to the symbol filtering combined with fzf’s `zero` event, I’ll look into it.

**Comment by folke** [comment]
Awesome, thanks!
