### ISSUE TITLE
Bug: fzf crawls to a halt when scrolling through the preview on file search

### ISSUE THREAD

**Issue by srodrigo** [ibhagwan/fzf-lua#1568]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.2

### Fzf version (`fzf --version`)

N/A installed today with ./install --bin as per README

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup {
        winopts = {
          height = 0.95,
          width = 0.95,
        },
      }
```

### Describe the bug / steps to reproduce

I couldn't record too much to avoid the size limit, but, as seen on the video, if I scroll through the preview, it gets slower and slower until it just freezes. Then it continues after a few seconds but very laggy and slow. I'm trying to scroll during all the video, even when it shows the scroll has stopped and then continues.

1. Preview a file that makes the preview window scroll.
2. Scroll up and down for a few seconds. It starts crawling until it halts.

https://github.com/user-attachments/assets/2e268f5b-b7d4-4758-9cee-2bfecee6b15e

**Comment by ibhagwan** [comment]
Probably related to treesitter, might be related to the beta of #1552.

- Do you have `nvim-treesitter-context` installed?
- Can you try the below and lmk which of these solves the issue?
```vim
:FzfLua buffers  previewer.treesitter.context=false
:FzfLua buffers  previewer.treesitter.enable=false
:FzfLua buffers  previewer.syntax=false
```

**Comment by srodrigo** [comment]
Thanks for having a look :)

> Probably related to treesitter, might be related to the beta of #1552.

> * Do you have `nvim-treesitter-context` installed?

Nope.

> * Does this happen on all filetypes or just some (`.cs` as demonstrated)?

I also tried with `.tsx` files, as C# files make my NeoVim a bit slow. But I have the same behaviour.

I just tried `.md` and plain text files, and I get the same behaviour even on short files where the preview doesn't need much scrolling.

> * Can you try the below and lmk which of these solves the issue?
> 
> ```viml
> :FzfLua buffers  previewer.treesitter.context=false

I get the same issue on a plain text file (131).

> :FzfLua buffers  previewer.treesitter.enable=false

I get the same issue on the same plain text file.

> :FzfLua buffers  previewer.syntax=false

I get the same issue on the same plain text file.

> ```

**Comment by srodrigo** [comment]
One thing I've noticed is that I can reproduce the issue very quickly if I just hold `<S-down>`. It takes a longer time to reproduce if I press and release quickly.

**Comment by ibhagwan** [comment]
> One thing I've noticed is that I can reproduce the issue very quickly if I just hold `<S-down>`. It takes a longer time to reproduce if I press and release quickly.

Perhaps some auto command in your config is causing this? Can you try with `mini.sh`?

**Comment by srodrigo** [comment]
> > One thing I've noticed is that I can reproduce the issue very quickly if I just hold `<S-down>`. It takes a longer time to reproduce if I press and release quickly.
> 
> Perhaps some auto command in your config is causing this? Can you try with `mini.sh`?

Good call. I've just tried `mini.sh` and I get the exact same behaviour.

**Comment by ibhagwan** [comment]
I can't seem to reproruce this, can you try [1568](https://github.com/ibhagwan/fzf-lua/tree/1568) branch and let me know if this feels better and if you see fzf-lua messages saying `skip page-down` (or up) in `:messages`?

**Comment by ibhagwan** [comment]
I have a feeling this is related to the preview scrollbar of type `border` and setting `winopts.preview.scrollbar` to `false` (disable) or `float` will work better, if you can confirm my suspecion the solution is near.

**Comment by ibhagwan** [comment]
@srodrigo, I believe https://github.com/ibhagwan/fzf-lua/commit/f07f0d310c12cbd62ab48148cd760cfa606e8117 is in high liklihood to solve this issue.

Kindly reopen the issue if I'm wrong or confirm it's solved?

**Comment by srodrigo** [comment]
> I can't seem to reproruce this, can you try [1568](https://github.com/ibhagwan/fzf-lua/tree/1568) branch and let me know if this feels better and if you see fzf-lua messages saying `skip page-down` (or up) in `:messages`?
> 
> Also can you try the below and lmk if any of these makes a difference?
> 
> ```lua
> :FzfLua buffers winopts.preview.scrollbar=border -- the default
> :FzfLua buffers winopts.preview.scrollbar=float
> :FzfLua buffers winopts.preview.scrollbar=false
> ```

Sorry, just logged in now.

> @srodrigo, I believe [f07f0d3](https://github.com/ibhagwan/fzf-lua/commit/f07f0d310c12cbd62ab48148cd760cfa606e8117) is in high liklihood to solve this issue.

This indeed solved the issue! It works with the default settings.

Thank you so much @ibhagwan :)

**Comment by ibhagwan** [comment]
> This indeed solved the issue! It works with the default settings.

Ty for the confirmation, happy my hunch worked and that was the issue :-)

Was also a much needed change anyways.
