### ISSUE TITLE
Don't preview binary files

### ISSUE THREAD

**Issue by mcchrish** [ibhagwan/fzf-lua#157]
Maybe the preview window just indicate that the file is binary instead.

**Comment by mcchrish** [comment]
Sometimes it leaves a floating artifact
<img width="299" alt="Screen Shot 2021-09-30 at 7 11 17 AM" src="https://user-images.githubusercontent.com/7200153/135360862-2dce3061-5170-4934-9d3c-cc0c593c42d6.png">
.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/28f3bcac27b6dbab37102336a22a38b81a6c4089

Should work on every system where the `file` binary exists.
