### ISSUE TITLE
Bug: Detect fzf or skim error

### ISSUE THREAD

**Issue by TwIStOy** [ibhagwan/fzf-lua#1574]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev

### Fzf version (`fzf --version`)

0.56.3

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

I config the `fzf_bin` path to `/nix/store/00878rfga84z9hzc176dy7skm6m45x2c-fzf-0.56.3/bin/fzf`. There's a substring "sk" in it. So `fzf-lua` seems to treat this path a 'skim' binary.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/8d35de5dac11f6fed7f03ae2e314c39c899d0846

Ty for the report @TwIStOy, honestly not sure how this hasn't come up before :-)
