### ISSUE TITLE
Feature: Allow Path Formatters to work on LSP Symbols

### ISSUE THREAD

**Issue by unlimitedsola** [ibhagwan/fzf-lua#1575]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I tried setting both `opts.lsp.formatter` and [`opts.defaults.formatter`](https://github.com/LazyVim/LazyVim/blob/2d7a04be47b94010fd6c1a2be0283c0d4e5738ae/lua/lazyvim/plugins/extras/editor/fzf.lua#L97), they don't seem to take effect on `workspaceSymbols`, despite the response contains a file path or alike.

Please forgive me if this is something that's already possible. I've dug down this rabbit hole for 20+ hrs already and I believe this is not currently achievable through configuration. The path formatter and symbol handler code, in my humble opinion, is very challenging to read and wrap my head around.

My goal was to truncate the path (or trim some prefix) for workspace symbols as they often involve absolute paths that are outside of the current working directory therefore very long to display (e.g.: `~/.local/share/nvim/{runtime/lazy}/*` for `lazy.nvim` or `~/.cargo/registry/src/index.crate.io-<hashstring>/*` for Rust projects). `path_shorten` alone doesn't feel enough to provide a good enough UX because knowing the last few path components in full would be very helpful in a lot of scenarios.
Hopefully, there can be an easier and straight-forward way to achieve such customization, thanks!

**Comment by ibhagwan** [comment]
> Please forgive me if this is something that's already possible. I've dug down this rabbit hole for 20+ hrs already and I believe this is not currently achievable through configuration. The path formatter and symbol handler code, in my humble opinion, is very challenging to read and wrap my head around.

That’s correct, it’s complicated, for a reason, some of the longer running operations are running in an external process neovim “wrapper” process which runs the lua code to handle entries and / add icons / etc.

I’ll look into it.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/73e7f5f93b65028b9fc94a27a4c80611ff8ba2a0

@unlimitedsola, the symbol formatter was preventing the path formatter functions from being set, I added the option for more than one formatter in the code which solves the issues rather elegantly.

**Comment by unlimitedsola** [comment]
Hi, thank you for working on this!

After reading through your change, I'm still confused about how this formatter mechanism works, specifically:

- If I make my own formatter, say `opts.formatters.path.truncate = { from, to }`, it doesn't work if I reference it in `opts.lsp.formatter` for `workspaceSymbols`. However, it affects `references` method as expected, but my simple implementation breaks the preview completely, see below.
- I'm assuming that I was supposed to set `_from, _to`? I'm not able to comprehend what's the difference between `_from` and `_to` from the comment alone, could you explain what's the rationale behind such mechanism and how should I code my `_from` and `_to` differently in contrast to their normal variants?

Coding a simple formatter with both `from` and `to` simply returning the "Hello world" string breaks the preview for `textDocument/references`. In my simple mind, I'm expecting a function named "formatter" to be only for transformation used for displaying, not altering the entries data.
I'm unsure about what contract a developer should hold when writing formatters. The only documentation I'm able to find about this is in the `defaults.lua` file you just changed. However, the documentation in that file alone doesn't really help me to understand the problem underscored variants are trying to solve. Could you help explain it further? Thanks!

**Comment by unlimitedsola** [comment]
The reason I'm trying to make my own formatter is because I wanted to implement a specific path formatting behavior as described below:

1. Define a maximum column width for path: `fname_width`, let's say it defaults to 60
2. If a given path length is shorter than the defined `fname_width`, then it is displayed as-is.
3. If the path is longer than `fname_width` then shorten the path segments from left to right one by one, except the left most and right most two (excluding filename), until it fits. For example, this transforms path `/usr/share/nvim/runtime/lua/vim/_meta/vimfn.lua` to `/usr/share/n/r/l/vim/_meta/vimfn.lua`
4. If the above step still doesn't fit, then replace shortened segments with ellipses until it fits, e.g.: `/usr/share/.../vim/_meta/vimfn.lua`
5. If it still doesn't fit, shorten left path segments, e.g.: `/u/s/.../vim/_meta/vimfn.lua`.
6. As the last resort, truncate the path string if still can't fit: `.../vim/_meta/vimfn.lua`.

This is somewhat analogy to the Telescope's `path_display.shorten` mechanism, when configured with `path_display.shorten = { len =1, exclude = { 1, 2, -2, -1}` but with few tweaks:
- display as much as possible if we are able to.
- replace shortened path segments with ellipses to avoid truncating left-most segments when possible
Telescope's `path_display` documentation can be found [here](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/lua/telescope/config.lua#L301-L395).

A good example of how this can improve UX is demonstrated in a telescope issue [here](https://github.com/nvim-telescope/telescope.nvim/issues/895), with the screenshot below (note how the second candidate gets shortened and still being very helpful):
![image](https://github.com/user-attachments/assets/09292d97-b1cc-4d85-9f93-64dece12dc40)

I wish there could be an interface for such configurations that works similarly to Telescope's, which is IMO a bit easier to comprehend and customize for users who don't have deep knowledge of the codebase. Designing a nicer interface might be a lot to ask, but I believe it would definitely help with this plugin's success. ❤️

**Comment by ibhagwan** [comment]
> Designing a nicer interface might be a lot to ask, but I believe it would definitely help with this plugin's success. ❤️

Regarding this, you're 100% right, that's why the formatter "interface" isn't documented in the advanced Wiki, I'm not comforatble exposing that as it's not really an "interace", this was mostly done so that I can add formatters in the code, the only real API's are the `fzf_exec` and `fzf_live` which I've done work to make sure are easy enough to comprehend and work with.

I'd love to have a better interface for the formatters (and other things too), I wish to also refactor the actions/keymap and combine it all to one big "bind" table and not have this mixture of fzf and neovim binds, but at the end of the day it's a very small % of users that are using these APIs so it's a lot of work and investment and somewhat small "ROI".

Of course I'd love to have people helping with design / docs / APIs with PRs and what not but unfortunately 2+ years later that  is yet to happen, even the Wiki which is open edit has barely 10 edits that aren't mine.

**Comment by unlimitedsola** [comment]
Thanks for the explanation! I wish I could help you with some of the work once I had enough grasp of the inner workings.

> Now this becomes extra complex when running formatters on the output of commands like rg/fd/etc as it needs to be done in the external process, so the function is written as a lua string and is then loaded using `loadstring` by the external processor.

By the "external processor" do you mean `fzf/rg/fd`? Not sure if I get this correctly, do you mean there are external processors that can execute lua code, **or** you pass the lua code string along with the entry string to the `fzf/fd/...` so that you could preserve some context?

**Comment by ibhagwan** [comment]
> By the "external processor" do you mean fzf/rg/fd? Not sure if I get this correctly, do you mean there are external processors that can execute lua code, or you pass the lua code string along with the entry string to the fzf/fd/... so that you could preserve some context at entry level?

There’s a headless wrapper neovim process running lua code responsible for parsing entries, formatting, adding icons, etc, take a look at `libuv.wrap_stdio`, and experiment with adding `debug=true` and `debug=v` (verbose) and you’ll understand more.
