### ISSUE TITLE
Bug: many light-background color schemes render with insufficient contrast

### ISSUE THREAD

**Issue by cwlbraa** [ibhagwan/fzf-lua#1576]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

MacOS

### Shell

zsh

### Neovim version (`nvim --version`)

 v0.10.2

### Fzf version (`fzf --version`)

0.57.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [x] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

my mini.sh preview comes out dark and contrast is fine.

### Fzf-lua configuration

[lazyvim v14.4.0 defaults](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/fzf.lua)

### Describe the bug / steps to reproduce

vim.o.background=light color schemes often have insufficient contrast for the name of a selected match. attached below are screenshots of "default" and [gruvbox](https://github.com/ellisonleao/gruvbox.nvim/issues/373) light-bg color schemes using a file-find dialogue.

it seems to default to white, which is obviously a problem when the background is, by configuration, nearly-white.

![Screenshot 2024-12-16 at 2 21 22 PM](https://github.com/user-attachments/assets/66e5f33c-746b-454d-bdb7-bf6f19d02d56)
![Screenshot 2024-12-16 at 10 03 32 AM](https://github.com/user-attachments/assets/695d7002-22f9-45ea-b9b5-299bd4d61e79)

**Comment by cwlbraa** [comment]
[also submitted an issue to gruvbox earlier](https://github.com/ellisonleao/gruvbox.nvim/issues/373)

**Comment by ibhagwan** [comment]
Most highlights are linked to neovim highlight groups and others are conditional based on light or dark - if you have suggestions based on these I can change these, otherwise I feel this is under the responsibility  of the color scheme / user to customize.

**Comment by cwlbraa** [comment]
how would I figure out which highlight group is in use here? it does seem like some light themes successfully provide a non-white color here.

**Comment by cwlbraa** [comment]
also thanks for the quick reply and the sweet plugin, I was surprised to see folke switched out telescope, but also pleasantly surprised by how fast fzf-lua is. I was using [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim) prior to this new version and fzf-lua does seem like an improvement even over that :)

**Comment by ibhagwan** [comment]
> how would I figure out which highlight group is in use here? it does seem like some light themes successfully provide a non-white color here (tokyonight-day). black would be a better default if it's easy to inject a conditional around bg for this particular color selection.

It’s in the init.lua code not sure if I wrote the light color in the README, I’m afk but I’ll check later and we can decide.

**Comment by ibhagwan** [comment]
> also thanks for the quick reply and the sweet plugin, I was surprised to see folke switched out telescope, but also pleasantly surprised by how fast fzf-lua is. I was using [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim) prior to this new lazyvim release and fzf-lua does seem like an improvement even over that :)

Ty for the kind words :)

**Comment by ibhagwan** [comment]
Take a look at the `is_light`  theme values, I’d welcome any suggestions as I don’t use light scheme myself, a PR would be welcome too if you wanna contribute:
https://github.com/ibhagwan/fzf-lua/blob/304253e4c637fd5fc92cbc50707993130615808a/lua/fzf-lua/init.lua#L79-L103

**Comment by cwlbraa** [comment]
lazyvim is using fzf_colors=true, so looking harder at those specifically. maybe that's not a good approach, idk.

I can tell it's not "Special" that's the problem here, that's the letter-match color, orange, as defined in gruvbox.nvim... 

my struggle is that idk which hl group is actually in use here, fg+ feels plausible from playing with FZF_DEFAULT_OPTS with raw fzf on the side, but over there that highlights the whole line, not just the filename.... is this FzfLuaFilePart?

**Comment by ibhagwan** [comment]
> lazyvim is using fzf_colors=true, so looking harder at those specifically. maybe that's not a good approach, idk.
> 
> I can tell it's not "Special" that's the problem here, that's the letter-match color, orange, as defined in gruvbox.nvim...
> 
> my struggle is that idk which hl group is actually in use here, fg+ feels plausible from playing with FZF_DEFAULT_OPTS with raw fzf on the side, but over there that highlights the whole line, not just the filename.... is this FzfLuaFilePart?

Screenshot and mark which highlights you’re after and I’ll tell you.

**Comment by cwlbraa** [comment]
![Screenshot 2024-12-16 at 10 03 32 AM](https://github.com/user-attachments/assets/695d7002-22f9-45ea-b9b5-299bd4d61e79)

it's the letters `orscheme.lua` in this screenshot

**Comment by cwlbraa** [comment]
it is indeed FzfLuaFilePart, changed that to special and now everything's orange

**Comment by cwlbraa** [comment]
so the problem is that I'm getting that set to "@none"... Normal would be fine here I think?

**Comment by ibhagwan** [comment]
> so the problem is that I'm getting that set to "@none"... Normal would be fine here I think?

There was a reason why we set it to @none, can’t recall why ATM, I think it was the background issue, but if you found which highlight you want just set it to whatever you want, alternatively remove the formatter and it won’t be used at all with `formatter=false`.

**Comment by cwlbraa** [comment]
lemme submit a lil PR, I really just wanna fix it for my fellow light-theme-but-lotsa-defaults users

**Comment by ibhagwan** [comment]
> lemme submit a lil PR, I really just wanna fix it for my fellow light-theme-but-lotsa-defaults users

But changing to Normal might work for you colorshceme but not for others, even on light.

**Comment by ibhagwan** [comment]
It might a specific colorscheme issue, perhaps `@none` needs to be fixed in the light version of your color scheme.

**Comment by cwlbraa** [comment]
> But changing to Normal might work for you colorshceme but not for others, even on light.

maybe, but wouldn't that imply that white is a good highlight color on a light background? that doesn't seem right, like black is obviously a bad choice on a dark background. I might be starting from bad assumptions here, though- do themes set @none?

doesn't matter now, though, this changed from under me after 304253e4c637fd5fc92cbc50707993130615808a and before 21849312a3eae7d8115a83b7a3f9c54a4e29c611:

now on gruvbox the highlights look like this:
![Screenshot 2024-12-17 at 1 09 15 PM](https://github.com/user-attachments/assets/543bb5c6-034c-4197-bf8c-ebe777edb555)

and similar in other light themes: 
![Screenshot 2024-12-17 at 1 16 24 PM](https://github.com/user-attachments/assets/4f7f3384-cdd7-4a7b-a424-abd760a072c7)
Derek:
![Screenshot 2024-12-17 at 1 17 19 PM](https://github.com/user-attachments/assets/76ce8538-b386-45a0-b999-d154a07e29ac)
morning:
![Screenshot 2024-12-17 at 1 17 41 PM](https://github.com/user-attachments/assets/1cbdd446-8ec5-4b87-b07f-2ddb38c540e9)
tokyonight-day:
![Screenshot 2024-12-17 at 1 18 10 PM](https://github.com/user-attachments/assets/8826b35e-5784-496c-86e4-7888a7428c62)
cappuccin-latte:
![Screenshot 2024-12-17 at 1 19 43 PM](https://github.com/user-attachments/assets/27341804-484d-489b-b532-fef682ba0b74)

**Comment by cwlbraa** [comment]
presumably this commit? lots of color stuff batched in there https://github.com/ibhagwan/fzf-lua/commit/7836b37b1d7f4786b8c8804bac29beb3926a56a7#diff-e7713342cff0f9fcdb22d64f0e3a0d7d6ff9c1d468778610f201f65cf738f51cR938

**Comment by cwlbraa** [comment]
> It might a specific colorscheme issue, perhaps @none needs to be fixed in the light version of your color scheme.

yeah agreed, come to think of it, this is actually corroborated by the fact that some light themes, particularly tokyonight-day, have a color supplied for this highlight that makes sense.

![Screenshot 2024-12-17 at 1 34 48 PM](https://github.com/user-attachments/assets/13ab131a-92af-4080-90bf-2a0d16a6b8f9)

that said I'm happy to have been able to provide a litany of theme-gore screenshots for whatever the issue is on main, but I'll leave that one to you :)

**Comment by ibhagwan** [comment]
> presumably this commit? lots of color stuff batched in there

Strange, I don’t recall changing anything relating `FzfLuaFilePart`

That’s the gutter highlight, I usually set it to `-1` in my color scheme / config which makes it transparent.

> that said I'm happy to have been able to provide a litany of theme-gore screenshots for whatever the issue is on main, but I'll leave that one to you :)

Any recommendations that are good for all schemes including default are welcome :)

**Comment by cwlbraa** [comment]
> Strange, I don’t recall changing anything relating FzfLuaFilePart

yeah the gutter thing is orthogonal to the FzfLuaFilePart @none thing.

> I usually set it to -1 in my color scheme / config which makes it transparent.

so the black bars are caused by this change?

```
- When enabled `fzf_colors` will automatically set `hl,hl+` to
  `-1:reverse` which changes the background of the character,
  this is done to make the TS highlights more distingished
``` 

I don't ever custom-configure my color schemes or how those schemes interact with various plugins. It's too prone to breakage when hl groups move around, and too hard to reverse-engineer the association between the rendered UI element and the code that colors it.

It's much easier to just change to a colorscheme that works with the plugins I want, or change the plugins to ones that work with my desired color scheme. Like I'm just running gruvbox dark rn, and when I feel the need to switch back to a light theme (in the summer when the glare gets bad at my desk lol) I'll swap back to telescope-fzf-native if I have to. 

Putting in the work upstream is worth it if everybody gets working light themes, but I really don't care enough to make it work for just me XD

**Comment by ibhagwan** [comment]
The reason for the change in latest commits is that `fzf_colors=true` is being overwritten, see #1582, once I fix that you'll be back with the issue, but if you like the default colors, why not set `fzf_colors=false` and not rely on the auto-generated colorscheme?

**Comment by cwlbraa** [comment]
I gave it a try on main, and while you fixed the black bars on fzf_colors=true, setting that to false causes them to come back

**Comment by ibhagwan** [comment]
Ok so I downloaded your colorscheme (even added it to "awesome_colorschemes"), the issue here is different, seems like an fzf bug (unsure yet), when `bg+` is specified without `fg+`  seems to create this messy color, try the below command with and without `fg+`:
> With `fg+`, no problem
![image](https://github.com/user-attachments/assets/16f93a1d-04c1-465f-8cba-a186e3e821e6)

> Without `fg+`, the color isn't inherited from the main fzf `fg`:
![image](https://github.com/user-attachments/assets/db549d27-533a-49d8-9538-e874e17c89e6)

https://github.com/ibhagwan/fzf-lua/commit/aa5b00209a3cb127ba57b62cd868dfabb87d1862

In any event I added a workaround for this in the latest commit whereas the fg color has a fallback to FzfLuaNormal `fg`, so the light version now also works with `fzf_colors=true`:
![image](https://github.com/user-attachments/assets/2836bfa8-f2e4-4af4-93bd-3da7d3e0c240)

The issue still somewhat remains when using a formatter, since `@none` is a cleared hlgroup, the bug I described above is back.

**Comment by cwlbraa** [comment]
amazing, thanks! back to the light!

**Comment by cwlbraa** [comment]
![Screenshot 2024-12-17 at 4 29 11 PM](https://github.com/user-attachments/assets/ada018d4-f672-4838-b793-d90459698da8)
was literally writing you a PR description and came back here to grab the issue # XD

**Comment by ibhagwan** [comment]
> amazing, thanks! back to the light!

Ty for the update!

> was literally writing you a PR description and came back here to grab the issue # XD

Issue wasn't with `@none`,  when `fzf_colors=true`, `fg+` was taking "fg" of `CursorLine` which is cleared (there's only "bg") an having only `--color=bg+:...` without `fg+` causes this issue, still trying to figure out if this is inteded behavior for fzf or a bug.

**Comment by ibhagwan** [comment]
Turns out this isn't an fzf bug, it's just that having a light `bg` color with a cleared `fg` color the original fzf light color fg color is shown which is hard to see with an already light background.

**Comment by ibhagwan** [comment]
Yes, this issue is now complete to my liking, this is how it looks like with the neovim default colorscheme:
> `:set bg=light | FzfLua files fzf_colors=true formatter=path.dirname_first`
![image](https://github.com/user-attachments/assets/2de98b31-6453-41c2-bf8f-0f8ce1570bec)

> `:set bg=dark | FzfLua files fzf_colors=true formatter=path.dirname_first`
![image](https://github.com/user-attachments/assets/dc21525e-e9ed-4327-bb70-fb8cc4cab192)
