### ISSUE TITLE
how can i customzie  fmt of  output，i want make output More readable

### ISSUE THREAD

**Issue by paopaol** [ibhagwan/fzf-lua#158]
current output format

``` 
/abosolute/path/project/path1/path2/path3/code.cpp
/abosolute/path/project/path/something.cpp
```

expected output format

```
code.cpp                        |   /abosolute/path/project/path1/path2/path3/
something.cpp                   |   /abosolute/path/project/path/
```

**Comment by ibhagwan** [comment]
This is not currently not possible, this would require major changes to the way fzf-lua works.

In your case I would recommend to make the query relative so you can ignore the absolute path part:

```lua
:lua require'fzf-lua'.files({ cwd = '/abosolute/path/project' })
```

**Comment by paopaol** [comment]
I forked a copy and implemented some new commands based on the existing code, which will work. And I found that after changing to this display format, the match rate for my search has also improved. Because in most cases, the file name is what I want, and I don't care about the parent directory of the file. And now because the file is displayed in the front, fzf also matches the preceding string first.

![微信截图_20210930225624](https://user-images.githubusercontent.com/6983082/135480517-951ab65f-8b12-4f9c-9c63-f2a0d5de84cf.png)

**Comment by paopaol** [comment]
I forked a copy and implemented some new commands based on the existing code, which will work. And I found that after changing to this display format, the match rate for my search has also improved. Because in most cases, the file name is what I want, and I don't care about the parent directory of the file. And now because the file is displayed in the front, fzf also matches the preceding string first.

![微信截图_20210930225624](https://user-images.githubusercontent.com/6983082/135480517-951ab65f-8b12-4f9c-9c63-f2a0d5de84cf.png)

**Comment by ibhagwan** [comment]
> I forked a copy and implemented some new commands based on the existing code, which will work. And I found that after changing to this display format, the match rate for my search has also improved. Because in most cases, the file name is what I want, and I don't care about the parent directory of the file. And now because the file is displayed in the front, fzf also matches the preceding string first.
> 
> ![微信截图_20210930225624](https://user-images.githubusercontent.com/6983082/135480517-951ab65f-8b12-4f9c-9c63-f2a0d5de84cf.png)


FYI, I deleted a duplicate comment.

Looks great! As long as this is optional and the interface to format is clear and also works with the different options (`cwd`, etc), I’d be happy to accept a PR if you wish.

**Comment by ibhagwan** [comment]
Closing this for now, feel free to submit your PR if you're still up for it!
