### ISSUE TITLE
Bug: fzf_colors is expected to be a table in normalize_opts

### ISSUE THREAD

**Issue by stormherz** [ibhagwan/fzf-lua#1582]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Windows, WSL

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.2

### Fzf version (`fzf --version`)

0.56.3 (add1aec)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

The problem seems to be related to the commit 7836b37b

`normalize_opts` now expects `fzf_colors` as a part of  ` -- Merge required tables from globals` to be a table, but according to docs it can be set to boolean value to inherit colors from the color scheme. 

Right now it fails with the following (not the real code, just to get the gist of it):

```lua
fzf_lua.fzf_exec(some_results, { fzf_colors = true })
```

Not sure it was intended or is there a new way of generally specifying global color inheritance

**Comment by ibhagwan** [comment]
Ty for the report @stormherz! sohuld work as expected with https://github.com/ibhagwan/fzf-lua/commit/c5011720fa56d5a92598aa32a93c7c6df6a3ac9f.

**Comment by stormherz** [comment]
@ibhagwan well that was fast =) many thanks, works like a charm!
