### ISSUE TITLE
Bug: fail to launch fzf after hiding `blines()` window

### ISSUE THREAD

**Issue by phanen** [ibhagwan/fzf-lua#1583]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

linux

### Shell

bash

### Neovim version (`nvim --version`)

nightly

### Fzf version (`fzf --version`)

0.56.3 (add1aec6)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require("fzf-lua").setup({ keymap = { builtin = { ["<esc>"] = "hide" } } })
```

### Describe the bug / steps to reproduce

1. Launch `blines()` from `builtin()` menu (rather than just launch `blines()`).
2. `<esc>` to hide window.
3. Launch `blines()` from `builtin()` menu again. (no window popup this time)
4. Then launch fzf whatever e.g. `files()`, it crash.
```
E5108: Error executing lua ...phan/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:245: .../phan/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/win.lua:55: assertion failed!
stack traceback:
        [builtin#36]: at 0x65153ea59f50
        ...phan/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:245: in function 'files'
        [string ":lua"]:1: in main chunk
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/691c392827d875dbe00f3041af980c9187dec1f3

Ty @phanen! there's always one edge case to be missed lol
