### ISSUE TITLE
Feature: cycling through prompt history

### ISSUE THREAD

**Issue by fdschmidt93** [ibhagwan/fzf-lua#1587]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Disclaimer: I've quickly grepped through the project and docs, if I've missed it I'm terribly sorry!

Apologies for also not being able to help more on the treesitter PR, but my PhD is keeping me busy. Glad to see it has landed on main :)

Have you considered implementing something like [telescope-smart-history.nvim](https://github.com/nvim-telescope/telescope-smart-history.nvim/) smart history for `fzf-lua`? 
Essentially, it stores for the tuples of `(picker, cwd)` the history of prompts to be able to cycle through that history when the picker is opened.

At the time, this was implemented in SQLite, but `vim.json` should be perfectly sufficient for this.

If this is something you'd consider, maybe I'd take a crack at it on Sunday (or eventually... :sweat_smile: not sure if there's time until after mid-February, so please just get on it _in case_ it itches you to implement).

E: I should do work, but playing around for 10 minutes to set text in fzf prompt.

```lua
local api = vim.api
api.nvim_create_autocmd("FileType", {
  pattern = "fzf",
  callback = function(args)
    vim.schedule(function()
      vim.keymap.set("t", "X", function()
        local keys = "<C-u>"
        api.nvim_feedkeys(api.nvim_replace_termcodes(keys, true, false, true), "ni", true)
        vim.schedule_wrap(vim.paste)({ "test" }, -1)
      end, { buffer = args.buf })
    end)
  end,
})

return {
  "ibhagwan/fzf-lua",
  config = function()
    require("fzf-lua").setup {
      on_create = function()
        -- called once upon creation of the fzf main window
        -- can be used to add custom fzf-lua mappings, e.g:
      end,
      winopts = {
        treesitter = {
          enabled = true,
        },
        height = 0.8, -- Full height
        width = 0.8, -- Full width
        preview = {
          layout = "vertical",
          vertical = "up:40%", -- Place preview window at the top, occupying 40% of the height
        },
        border = "thicccc", -- Optional: sets a single border around the window
      },
      fzf_opts = {
        ["--layout"] = "reverse-list", -- Similar to `prompt_position = "top"`
      },
    }
  end,
}
```

Seems to work :smile: But I'm sure there's better ways to do this.

**Comment by ibhagwan** [comment]
Have you tried https://github.com/ibhagwan/fzf-lua/wiki#custom-history or is this something very different?

**Comment by fdschmidt93** [comment]
Ah, thank you very much, I overlooked this!

What I want can easily be achieved by wrapping history around picker and cwd :)
