### ISSUE TITLE
Feature: Add ignore_duplicates option for `fzf --history`

### ISSUE THREAD

**Issue by SadEagle** [ibhagwan/fzf-lua#1588]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

As i understand this plugin uses  default `fzf --history` [opt](https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-setup-input-history-keybinds)
But `fzf` itself doesn't support an option to ignore duplicates. It's implemented via shell scripts

It would be good to add history ignore opts for example zsh-like `hist_ignore_dups` and 'hist_ignore_all_dups`.
Without one of this options it may be hard to use this feature effectively

Alternatively, is there a custom way to implement this?

**Comment by nenahp** [comment]
A poor idea is binding an action on each confirm then `sed` out this entry from history file...

**Comment by ibhagwan** [comment]
While I can do this in fzf-lua perhaps more suitable upstream?

https://github.com/junegunn/fzf/pull/1940
