### ISSUE TITLE
Bug: error when FZF_DEFAULT_OPTS contains `--select-1`

### ISSUE THREAD

**Issue by hb0nes** [ibhagwan/fzf-lua#1589]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

MacOS

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 

### Fzf version (`fzf --version`)

fzf --version 0.56.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--no-mouse --height 50% -1 --reverse --multi --inline-info

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

I cannot use FzfLua buffers anymore. The window opens and closes immediately with the errors seen below.
If I switch between the buffers manually and try it, the error changes a bit.

From:
Fzf-lua] unsupported action: '[1]  #    hieradata/nodes/ld4-mas-01-prd

To:
[Fzf-lua] unsupported action: '[2]  #    hieradata/nodes/ld4-mas-01-tst

And back again.

Steps to reproduce:
Run mini.sh. Open a couple buffers (:edit a, :edit b, etc.)
:FzfLua buffers
:messages

[Fzf-lua] |<C-\> buffers|<C-p> files|<C-g> grep|<C-l> live grep|<C-k> builtin|<F1> help|
[Fzf-lua] unsupported action: '[1]  #    bla:1', type:nil
[Fzf-lua] unsupported action: '[1]  #    bla:1', type:nil

**Comment by ibhagwan** [comment]
I see a few important bug fixes relating to reload acitons since v0.56, could this possibly be a bug in fzf `0.56`? 

Would it possible for you to upgrade to 0.56.3 or 0.57.0 while I go test this on my wife's mac (lol) as this isn't reproducible on my Linux?

**Comment by ibhagwan** [comment]
Ok, found the issue, unlreated to fzf version, it's due to `FZF_DEFAULT_OPTS`, unsure what yet but if you nullify that in neovim you can work around it for now, run `:lua vim.env.FZF_DEFAULT_OPTS=nil`

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d51d93337e06c289ca1a0f31249b15e982170843 @hb0nes, should work as expected now regardless of your FZF_DEFAULT_OPTS.

**Comment by hb0nes** [comment]
Awesome. Made quick work of this one! Thanks. Will check out the commit
when I get home, you got me curious now.

**Comment by buraksirma** [comment]
I still have same issue on the latest commit. I put `:lua vim.env.FZF_DEFAULT_OPTS=nil` to my config for now. 

The environment var is set to one below, on my side.
```
--color=bg+:#313244,bg:-1,spinner:#f5e0dc,hl:#f38ba8 --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8
```

**Comment by ibhagwan** [comment]
@buraksirma, I found a better solution for this, can you update to https://github.com/ibhagwan/fzf-lua/commit/1fd9c17730369b73d61b4b7b6295c908b93599cf and let me know?

**Comment by ibhagwan** [comment]
Btw, the previous soltution was to remove the `-1|--select-1` from FZF_DEFAULT_OPTS, I actually realized that using `-1` was broken since the addtions of the `print(...)` action with fzf v0.53 so I made the adjustments for this to work again.

@hb0nes, now if you have 2 buffers open, since the current buffer is set as a header line, running `:FzfLua buffers` should respect the `-1` in your FZF_DEFAULT_OPTS and change to the alternate buffer immediately.

If you remove the `-1` your default opts you can also do this to try it out:
```vim
" both are the considered the same flag in fzf
:FzfLua buffers fzf_opts.-1=true
:FzfLua buffers fzf_opts.--select-1=true
```

**Comment by buraksirma** [comment]
@ibhagwan It works now. Thanks for the quick action :rocket:

**Comment by ibhagwan** [comment]
> @ibhagwan It works now. Thanks for the quick action 🚀

Great! ty for the update @buraksirma!

**Comment by ibhagwan** [comment]
I apologize I had to revert this commit due to #1594, I'll fix this later not in a rush when I have more time today.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/cd9ab4ed3f44d062e511aa9de41ccf815f0ec962

Ok, hopefully no edge cases this time :-)

**Comment by ibhagwan** [comment]
@xfzv, you’re not doing anything wrong, I’ll check why this fails.

**Comment by ibhagwan** [comment]
@xfzv, I can't reprodue this on my config or with `mini.sh` with 0.10.3/nightly, I open 2 buffers and run and it works perfectly (switching immediately since the current buffer is set to header line):
```lua
:FzfLua buffers fzf_opts.-1=true
-- or (same)
:FzfLua buffers fzf_opts.--select-1=true
-- or via default opts
:lua vim.env.FZF_DEFAULT_OPTS="--select-1"
```

Please open a new issue so I can track and we'll try to figure out why this isn't working for you.
