### ISSUE TITLE
Bug: Pressing <Esc> on empty results creates a new empty `esc` buffer

### ISSUE THREAD

**Issue by somnam** [ibhagwan/fzf-lua#1594]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

bash

### Neovim version (`nvim --version`)

v0.10.2

### Fzf version (`fzf --version`)

0.57.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
    winopts = {
      height = 0.85,
      width = 0.65,
      col = 0.50,
      backdrop = 100,
      preview = {
        default = command.bat({ cmd_only = true }),
        layout = "vertical",
        winopts = { number = false },
      },
    },
    fzf_opts = {
      ["--history"] = vim.fn.stdpath("data") .. "/fzf_lua_history",
    },
    fzf_colors = true,
    previewers = {
      bat = {
        args = command.bat({ args_only = true, color = true, into_shell = true }),
      },
      builtin = {
        treesitter = { enable = false },
      },
    },
    defaults = {
      git_icons = false,
      file_icons = false,
    },
    files = {
      prompt = "Files❯ ",
      cmd = command.find({ into_shell = true }),
    },
    grep = {
      prompt = "Words❯ ",
      cmd = command.grep({ into_shell = true, color = true }),
      rg_glob = command.executable("rg"),
    },
    manpages = { previewer = "man_native" },
    helptags = { previewer = "help_native" },
})
```

### Describe the bug / steps to reproduce

1. Generate a search that returns no results, e.g. 
* list files in an empty folder
* filter out all files by a non-existing name
2. Hit `Esc` button on keyboard
3. A new, empty buffer is created with name `esc`

https://github.com/user-attachments/assets/b920b700-c548-46c1-927a-970a9b8d2a5c

**Comment by ibhagwan** [comment]
That’s a regression from my last commit regarding `—select-1`, Ty for reporting I’ll fix it shortly .
