### ISSUE TITLE
Feature: hide picker on "Enter" instead closing it to preserve selected entry after FzfLua resume

### ISSUE THREAD

**Issue by miroshQa** [ibhagwan/fzf-lua#1595]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

We can already launch FzfLua live_grep, type some query, select desired entry and then [hide picker] (https://github.com/ibhagwan/fzf-lua/issues/1229#issuecomment-2261917590), after that when we launch FzfLua resume we will open this picker again and previously selected entry will stay selected.

But how can I achieve this behavior after pressing "Enter" to edit file? Because now when I use FzfLua resume it will reset previously selected entry, although it is surely possible to preserve it because we can already hide and unhide picker.

**Comment by ibhagwan** [comment]
Already completed, set to `alt-esc` by default, see #1229 how to customize.

**Comment by miroshQa** [comment]
Sorry, I probably didn't explain this well. 

I know about alt-esc, but it just hides the picker and doesn't do anything. 

But I want to go to edit file by pressing enter and then resume with previously selected entry as if I hide the picker.
Check out this video: https://imgur.com/a/pPG6viZ

As you can see, I can restore the previous picker state after I hide the picker using alt-esc, but when I press enter to edit file, then the previously selected entry is reset.

**Comment by miroshQa** [comment]
> Already completed, set to `alt-esc` by default, see #1229 how to customize.

Sorry, I probably didn't explain this well. 

I know about alt-esc, but it just hides the picker and doesn't do anything. 

But I want to go to edit file by pressing enter and then resume with previously selected entry as if I hide the picker.
Check out this video: https://imgur.com/a/pPG6viZ

As you can see, I can restore the previous picker state after I hide the picker using alt-esc, but when I press enter to edit file, then the previously selected entry is reset.

**Comment by miroshQa** [comment]
😢
I should probably try to learn the workflow with send to quick fix list then.

Also, I wonder if it is possible to ask the author of fzf to add some necessary functionality that will allow fzf-lua to implement resume after accept?

**Comment by miroshQa** [comment]
> > But I want to go to edit file by pressing enter and then resume with previously selected entry as if I hide the picker.
> > As you can see, I can restore the previous picker state after I hide the picker using alt-esc, but when I press enter to edit file, then the previously selected entry is reset.
> 
> Unfoeuntley not possible without a serious redesign as fzf temrinates the process upon an “accept” (any action).

😢
I should probably try to learn the workflow with send to quick fix list then.

Also, I wonder if it is possible to ask the author of fzf to add some necessary functionality that will allow fzf-lua to implement resume after accept?

**Comment by miroshQa** [comment]
> > But I want to go to edit file by pressing enter and then resume with previously selected entry as if I hide the picker.
> > As you can see, I can restore the previous picker state after I hide the picker using alt-esc, but when I press enter to edit file, then the previously selected entry is reset.
> 
> Unfoeuntley not possible without a serious redesign as fzf temrinates the process upon an “accept” (any action).


😢
I should probably  learn the workflow with send to quick fix list then.

Also, I wonder if it is theoretically possible to ask the author of fzf to add some necessary functionality that will allow fzf-lua to implement resume after accept?

**Comment by ibhagwan** [comment]
> I should probably learn the workflow with send to quick fix list then.

It's not that hard, IMHO it's core to vim/neovim, you also have the loclist (local list to buffer) and also `quickfix_stack` and `locllist_stack` which act as list(s) history,  with `:cdo` and `:cfdo` you can do anything.

> Also, I wonder if it is theoretically possible to ask the author of fzf to add some necessary functionality that will allow fzf-lua to implement resume after accept?

That's not required as ther feature are already there but this would require a major redesign of fzf-lua.

**Comment by miroshQa** [comment]
Wow, that works, @phanen! However, sometimes the restored position is incorrect (I haven't found a strict reproduction yet, but it usually happens when there are a lot of entries). I guess it's because the search query reruns each time I reopen the picker, and fzf search isn't deterministic? Also, it works only for the files picker. Is there a way to do this for live grep as well?

**Comment by ibhagwan** [comment]
> I guess it's because the search query reruns each time I reopen the picker, and fzf search isn't deterministic?

That’s because rg/fd runs multithreaded so can’t guarantee result ordering, can be solved by adding `--sort` to the rg/fd flags.

**Comment by ibhagwan** [comment]
@phanen, that’s a very interesting idea, I’m AFK and wondering what happens when you use `exec_silent` instead of `reload`?

**Comment by ibhagwan** [comment]
Or, another idea, use `exec_silent` and instead of hide, using `nvim_win_call` in the context of the calling window with `opts.__CTX.winnr`.

**Comment by miroshQa** [comment]
> > I guess it's because the search query reruns each time I reopen the picker, and fzf search isn't deterministic?
> 
> That’s because rg/fd runs multithreaded so can’t guarantee result ordering, can be solved by adding `--sort` to the rg/fd flags.

That seems to solve the issue. I'm not sure about performance degradation, but it works pretty well with 90k files, although I can see some twitching (which I can live with) when I reopen the picker.

The most interesting part is whether I can restore the live_grep picker in a similar way.

Also, how can I configure fzf-lua to prefer using rg over fd? (I didn't find a sort flag for fd.)

**Comment by ibhagwan** [comment]
> I can see some short twitching (which I can live with) when I reopen the picker.

Because the window is closed, action performed and window is reopened, that’s why I wanted to try with `nvim_win_call` without hide, but I’m AFK for the foreseeable future.

> Also, how can I configure fzf-lua to prefer using rg over fd? (I didn't find a sort flag for fd.)

Set `files.cmd`, it will override the command auto detect.

**Comment by ibhagwan** [comment]
> Wow, I don't know how it works, but using exec_silent instead of reload seems to resolve all the problems I listed above. (It works with live grep, with no twitching, and the position is always restored correctly event without --sort flag)

There why I wanted to try, it uses fzf execute-silent  action which doesn’t close the fzf process that’s why you don’t need anything else.

**Comment by ibhagwan** [comment]
@miroshQ, another interesting idea since I recently made it so the window won’t exit when swapping out of it is using winopts.split to open in a split as a perma win you can get in and out of.

I’ll try it when I get a chance.

**Comment by miroshQa** [comment]
Some other questions.

The documentation for actions.files says that only the following picker will inherit these mappings. But how can I apply these mapping to all existing pickers (helptags, manpages, jumps, etc.)?

```lua
    actions = {
        -- Below are the default actions, setting any value in these tables will override
        -- the defaults, to inherit from the defaults change [1] from `false` to `true`
        files = {
          -- true,        -- uncomment to inherit all the below in your custom config
          -- Pickers inheriting these actions:
          --   files, git_files, git_status, grep, lsp, oldfiles, quickfix, loclist,
          --   tags, btags, args, buffers, tabs, lines, blines
          -- `file_edit_or_qf` opens a single selection or sends multiple selection to quickfix
          -- replace `enter` with `file_edit` to open all files/bufs whether single or multiple
          -- replace `enter` with `file_switch_or_edit` to attempt a switch in current tab first
          ["enter"]       = actions.file_edit_or_qf,
          ["ctrl-s"]      = actions.file_split,
          ["ctrl-v"]      = actions.file_vsplit,
          ["ctrl-t"]      = actions.file_tabedit,
          ["alt-q"]       = actions.file_sel_to_qf,
          ["alt-Q"]       = actions.file_sel_to_ll,
        },
      }

```

**Comment by ibhagwan** [comment]
> The documentation for actions.files says that only the following pickers will inherit these mappings. But how can I apply these mapping to all existing pickers at once (helptags, manpages, jumps, dap_breakpoints, etc.)?


You’d need to add this separately for any picker that doesn’t inherit from the file actions (because they do something else, not file edit).

I’m gonna be AFK for a while so here’s my suggestion - open a feature request for this issue and I’ll implement something perhaps more robust and maybe improve on the solution with nvim_win_call without hide (so no window flash) if that’s possible.

**Comment by miroshQa** [comment]
I didn't understand about windows flash; I didn't notice anything like that. The solution above is perfect and gives me the exact resume behavior I have with telescope, so I have nothing to complain about anymore. However, I think the 'select entry' behavior mentioned above should apply to all pickers by default. I'm going to open an issue for that now, as you suggested.

**Comment by phanen** [comment]
> @phanen, that’s a very interesting idea, I’m AFK and wondering what happens when > you use exec_silent instead of reload?

@ibhagwan 
If you select only one entry each time, they are the same. 
If you select multiple entries(`--multi`)
* `exec_silent` does nothing but hide when you hide enter
* `reload` also cancel all your selection.

I think that's expected behavior for fzf: `execute-silent` won't do anything to tui while `reload` actually replace your list?
```sh
head -c 1048576 /dev/urandom | base64 | fzf --multi --bind 'ctrl-a:execute-silent:head -c 1048576 /dev/urandom | base64' --bind 'ctrl-b:reload:head -c 1048576 /dev/urandom | base64'
```
