### ISSUE TITLE
Hidden preview still partially shows

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#160]
Hey, after updating today (seems like it is https://github.com/ibhagwan/fzf-lua/commit/7a554bb2b2aeeaa45c418d51bff10fdedcae4b59 that broke it) I am seeing some partial preview on the very right of fzf floating window. It seems like it's just a scroller and some characters, sinlge column wide:
<img width="118" alt="Screenshot 2021-10-04 at 02 09 10" src="https://user-images.githubusercontent.com/69750637/135778143-969d6d9d-b483-47e6-b32c-8b109e9842a1.png">
<img width="80" alt="Screenshot 2021-10-04 at 02 09 21" src="https://user-images.githubusercontent.com/69750637/135778153-0fffeccf-caae-4490-9f20-18ff29892300.png">

it does go away when I unhide preview and hide it again (with `toggle-preview` mapping).

I have updated my configuration: removed `previewers.builtin.hidden = true` and set `preview_opts = 'hidden'`.
I disabled `winopts_raw` but it didn't fix the issue. :)

**Comment by ibhagwan** [comment]
I can't find in which issue you posted your `setup()` function, can you post it again here so I can reproduce?

**Comment by gegoune** [comment]
Should have post it immediately. Sorry! So:


```lua
require('fzf-lua').setup {
  -- experimental
  lua_io = true,

  keymap = {
    builtin = {
      ['<C-p>'] = 'toggle-preview',
    },
    fzf = {
      ['ctrl-p'] = 'toggle-preview',
      ['shift-down'] = 'preview-page-down',
      ['shift-up'] = 'preview-page-up',
      ['ctrl-u'] = 'unix-line-discard',
      ['ctrl-f'] = 'half-page-down',
      ['ctrl-b'] = 'half-page-up',
      ['ctrl-a'] = 'beginning-of-line',
      ['ctrl-e'] = 'end-of-line',
      ['alt-a'] = 'toggle-all',
    },
  },

  -- Previewers
  preview_opts = 'hidden',
  previewers = {
    builtin = {
      scrollchar = '│',
    },
  },

  -- Window
  winopts = {
    hl_normal = 'NormalFloat',
    hl_border = 'NormalFloat',
  },
  winopts_raw = require('hi.utils').floatArgs,

  -- Commands
  buffers = { prompt = 'Buffers: ', ignore_current_buffer = true, sort_lastused = true },
  files = { prompt = 'Files: ' },
  grep = { prompt = 'Rg: ', input_prompt = 'Grep for: ' },
  oldfiles = { prompt = 'History: ' },
  tabs = { prompt = 'Tabs: ' },

  -- fzf args
  fzf_args = '--margin=3,6',
  fzf_layout = 'default',
}
```

and floatArgs is returning 
```lua
{
  border = { { "▎", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { " ", "NormalFloat" }, { "▎", "NormalFloat" }, { "▎", "NormalFloat" } },
  col = 48,
  height = 38,
  relative = "editor",
  row = 16,
  style = "minimal",
  width = 144,
  window_on_create = <function 1>
}
```
for current window.

**Comment by ibhagwan** [comment]
Silly bug when changing variable names, should work now, lmk otherwise?

**Comment by gegoune** [comment]
Works nicely again, thanks a lot! ❤️

**Comment by ibhagwan** [comment]
> Works nicely again, thanks a lot! heart

Ty!

**Comment by ibhagwan** [comment]
Btw, I noticed you’re setting `previewers.builtin.scrollchar` in what seems like an attempt to hide the scrollbar? If that’s the case I think it’s better to use `scrollbar = false` which avoids calling the scrollbar draw altogether.

I was finally able to add a proper screencast to the README (took a while to find the right program for that), let me know what you think?

**Comment by gegoune** [comment]
I am just changing it to something thinner, less invasive.

Showcase looks nice! Good job!

It shows one issue I saw locally too, which I kept on forgetting to report as I use previews very rarely. What I mean is 'blinking', or highlight changing of commented out lines in preview. Do you know why that's happening?

**Comment by ibhagwan** [comment]
> I am just changing it to something thinner, less invasive.

Good idea, I’ll try it, I’m annoyed by this bulky thing too lol

> Showcase looks nice! Good job!

Ty!

> It shows one issue I saw locally too, which I kept on forgetting to report as I use previews very rarely. What I mean is 'blinking', or highlight changing of commented out lines in preview. Do you know why that's happening?

That is currently “by design”, as everything happens asynchronously, the file is first read and its lines are fed into the preview buffer, only then filetype is set and syntax highlight is turned on, therefore there’s a similar effect to what you’d experience if you edit a new file and then run `:set filetype=…`.

One way to solve it would be to delay displaying of the buffer until after the filetype was set, or setting the filetype beforehand which could potentially slow down nvim as it will have to work much harder with potential syntax redraws, TBH I was never really bothered by it so I didn’t look into solving this design flaw.

**Comment by gegoune** [comment]
Ah, I see. As I said I barely use preview so it does not annoy me too much, but it is pretty much in my eyes when I see it. :) Completely up to you if you want to 'fix' it or not.

**Comment by ibhagwan** [comment]
> Ah, I see. As I said I barely use preview so it does not annoy me too much, but it is pretty much in my eyes when I see it. :) Completely up to you if you want to 'fix' it or not.

Surely I can look into it , why not, I’ll open a “reminder issue”

**Comment by ibhagwan** [comment]
FYI, I know you're not really into previewers but I just added the functionality to "rotate" the previewer (`<F5>/<F6>` by default), might make it easier on you to see all the results even when the previewer is visible by rotating it.

I'm posting this here because based on your posted keybinds this functionality won't be enabled for you (it only maps implicit entries, does not merge with defaults), try it out and let me know what you think and also try out the fullscreen option as it affects not only the preview but the entire fzf window, these are the binds you want to add:

```lua
  keymap = {
    builtin = {
      ["<F2>"]      = "toggle-fullscreen",
      -- Rotate preview clockwise/counter-clockwise
      ["<F5>"]      = "toggle-preview-ccw",
      ["<F6>"]      = "toggle-preview-cw",
    },
...
```

**Comment by ibhagwan** [comment]
> It shows one issue I saw locally too, which I kept on forgetting to report as I use previews very rarely. What I mean is 'blinking', or highlight changing of commented out lines in preview. Do you know why that's happening?

https://github.com/ibhagwan/fzf-lua/commit/5bdb21355892c1cf87fe37456cb3b8488ff5960f closed #162 so this should be solved as well.

**Comment by gegoune** [comment]
Full screen option is nice, will keep that mapping! Not sure if I would ever use the rotating feature though.

As a side question - why not merge mappings with default? I think it's way more common case that users wants to add/change handful of mappings keeping defaults as they are. nvim-tree does it nicely now, you can change default, add to it or disable them all with some flag which I don't recall now.

**Comment by ibhagwan** [comment]
> Full screen option is nice, will keep that mapping! Not sure if I would ever use the rotating feature though.
> 
> As a side question - why not merge mappings with default? I think it's way more common case that users wants to add/change handful of mappings keeping defaults as they are. nvim-tree does it nicely now, you can change default, add to it or disable them all with some flag which I don't recall now.

I’m slowly merging all options that make sense, first step was to combine them all under the `keymap` table, next step would probably be merging those that make sense, the reason they’re currently separate is that there’s a clear separation between the options that are sent with the fzf `—bind` flag and the other options which are set using nvim `:tmap` on the window, I’m still unsure how to merge them all in a non confusing way, to add to the confusion fzf has different naming for its options, what is `<C-p>` in nvim is `ctrl-p` in fzf style binds.

Any ideas and suggestions are welcome, if you think the nvim-tree way makes sense can you link what you refer to below so I can look into it?

**Comment by gegoune** [comment]
Ah, it's not what I meant actually. I though you said that if I am setting up *any* of my own mappings then default ones will not be applied on top of them, so I will only end up with what is implicitly set in config. I am aware of the fact that you are managing two 'types' of mappings, not sure if there is a nice way, or a way at all, to combine them. I am absolutely fine with having distinction there.

**Comment by ibhagwan** [comment]
> Ah, it's not what I meant actually. I though you said that if I am setting up _any_ of my own mappings then default ones will not be applied on top of them, so I will only end up with what is implicitly set in config. I am aware of the fact that you are managing two 'types' of mappings, not sure if there is a nice way, or a way at all, to combine them. I am absolutely fine with having distinction there.

I understand now, I could do easily do either way, ignore the default or add them on top, I was not sure what makes most sense here **for both fzf and builtin mappings**, given that people have very opinionated preferences for their fzf binds I decided to let the user override the table entirely and to make it consistent I copied the behavior for the builtin mappings too.
