### ISSUE TITLE
Bug: keybinding tipp "<alt-h> to Include hidden files..." is not accurate, after change of keybinding

### ISSUE THREAD

**Issue by N3bukadne7ar** [ibhagwan/fzf-lua#1605]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Fzf version (`fzf --version`)

0.57.0 (0476a65)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
opts = {
      defaults = {
        formatter = "path.filename_first",
        -- formatter = "path.dirname_first",
      },

      files = {
        cwd_prompt = false,
        actions = {
          ["ctrl-i"] = { actions.toggle_ignore },
          ["ctrl-h"] = { actions.toggle_hidden },
        },
      },
      grep = {
        actions = {
          ["ctrl-i"] = { actions.toggle_ignore },
          ["ctrl-h"] = { actions.toggle_hidden },
        },
      },

      winopts = {
        treesitter = {
          enabled = true,
          fzf_colors = { ["hl"] = "-1:reverse", ["hl+"] = "-1:reverse" },
        },
        preview = {
          layout = "vertical", -- horizontal|vertical|flex
        },
        on_create = function()
          -- called once upon creation of the fzf main window
          -- can be used to add custom fzf-lua mappings, e.g:
          --   vim.keymap.set("t", "<C-j>", "<Down>", { silent = true, buffer = true })
        end,
        -- called once _after_ the fzf interface is closed
        -- on_close = function() ... end
      },
}
```

### Describe the bug / steps to reproduce

Hi!
I have a minor problem with the UI. When running a grep / or file search, the pluging displays a helpful message on some keybindings at the top of the results window
![image](https://github.com/user-attachments/assets/11b927ba-0603-4ade-8c62-1854e085f6ee)
This is awesome, unfortunately the provided info does not update with my custom keybindings. I have updated the toggle hidden & and ignored actions to <ctrl-h/i> instead of <alt-h/i>. These rebinds are functional, it is just the help text that is not synced somehow. 

Can I fix this via config?

I have tried unbinding the original keybinding first, but this leads to an error (Which I am not versed enough in lua to understand)

```
-- doesn't work: Leads to errors:
["ctrl-i"] = { },          
["alt-i"] = { actions.toggle_ignore },
```
Thanks in advance!

**Comment by ibhagwan** [comment]
The `alt-h` isn't default in fzf-lua and comes from LazyVim, in your actions set it to false, assuming it will override the LazyVim config the message should go away:
```lua
        actions = {
          ["ctrl-i"] = { actions.toggle_ignore },
          ["ctrl-h"] = { actions.toggle_hidden },
          ["alt-h"] = false,
        },
```

**Comment by N3bukadne7ar** [comment]
Thanks for the reply! I found a solution as well. Indeed, Lazyvim already sets keybindings and I was just adding more on top. With this config I am clearing the respective "actions" entries, keeping only my new bindings. This solves the issue.

```lua
-- plugins/fzf.lua

local config = require("fzf-lua.config")
local actions = require("fzf-lua.actions")

return {
  {
    "ibhagwan/fzf-lua",
    opts = function(_, opts)
   
      opts.files["actions"]= {
        ["ctrl-i"] = { actions.toggle_ignore },
        ["ctrl-h"] = { actions.toggle_hidden },
      }

      opts.grep["actions"]= {
        ["ctrl-i"] = { actions.toggle_ignore },
        ["ctrl-h"] = { actions.toggle_hidden },
      }
    end,
  },
}

```
