### ISSUE TITLE
Integration with project.nvim

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#161]
Not sure if you are using [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim) but it comes with telescope integration. I am not sure how it works exactly as I dont have telescope installed but I was thinking that instead of trying to disable it (https://github.com/ahmedkhalf/project.nvim/issues/29)  I could actually use it.

Do you think it's easy to write custom command that would source that file and perform an action on selected item? I am thinking that maybe an action could be to open nvim-tree or oldfiles filtered by selected project. Or maybe have one of them as default and other under some other key?

What do you think?

**Comment by ibhagwan** [comment]
> Not sure if you are using [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim) but it comes with telescope integration. I am not sure how it works exactly as I dont have telescope installed but I was thinking that instead of trying to disable it ([ahmedkhalf/project.nvim#29](https://github.com/ahmedkhalf/project.nvim/issues/29)) I could actually use it.
> 
> Do you think it's easy to write custom command that would source that file and perform an action on selected item? I am thinking that maybe an action could be to open nvim-tree or oldfiles filtered by selected project. Or maybe have one of them as default and other under some other key?
> 
> What do you think?

Regardless of how this is done should be pretty easy, as long as the information is available to Telescope or via an API of sorts.

I wouldn’t want to maintain additional providers that are dependent on other plugins and having to worry about when they make changes but I can use this thread to write a small Fzf-Lua function that would do exactly what you want, shouldn’t he hard at all.

Let me know what is the functionality you’re exactly after? I would assume fuzzy searching a list of most recent projects or is there something more to this?

I’m not sure how close this is to what you’re after but I wrote an extension for myself that takes a list of project directories from and let’s you switch between them setting `cwd` to the git root of the project, take a look at:

https://github.com/ibhagwan/nvim-lua/blob/d3c5c65fb593da69b6eadeb5e2426fae20ca0f98/lua/plugins/fzf-lua/init.lua#L231-L288

**Comment by gegoune** [comment]
Ah, wasn't really asking to add and forever support it, more asking for help for a function to add to my local config. I think to start I would like to see a list of those projects and as default action fire oldfiles with path set to selected project. Will have a look at your function bit later.

**Comment by ibhagwan** [comment]
> Ah, wasn't really asking to add and forever support it, more asking for help for a function to add to my local config. I think to start I would like to see a list of those projects and as default action fire oldfiles with path set to selected project. Will have a look at your function bit later.

This should be very easy to do, if you let me know where the projects list is stored I will write the function down below.

**Comment by gegoune** [comment]
Awesome, thanks! Seems like it's `vim.fn.stdpath("data")/project_nvim/project_history`.

**Comment by ibhagwan** [comment]
> Awesome, thanks! Seems like it's `vim.fn.stdpath("data")/project_nvim/project_history`.

Would you be able to provide a sample of the contents of the file so I can parse it properly?

**Comment by ibhagwan** [comment]
Well this should work then, very similar to my `workdirs` function I linked above without the shenanigans of putting the previous workdir at the top of the list.

```lua
function M.projects(opts)
  if not opts then opts = {} end

  local prjects_path = vim.fn.stdpath("data") .. "/project_nvim/project_history"
  if not vim.loop.fs_stat(prjects_path) then return end
  local project_dirs = vim.fn.readfile(prjects_path)

  local iconify = function(path)
    local ansi_codes = require'fzf-lua.utils'.ansi_codes
    local is_cwd = (path == vim.loop.cwd())
    local icon = is_cwd and ansi_codes.magenta('')
      or ansi_codes.blue('')
    path = require'fzf-lua.path'.relative(vim.fn.expand(path), vim.fn.expand('$HOME'))
    return ("%s  %s"):format(icon, path)
  end

  coroutine.wrap(function ()
    local entries = {}
    for _, path in ipairs(project_dirs) do
      entries[#entries+1] = iconify(path)
    end

    local fzf_fn = function(cb)
      for _, entry in ipairs(entries) do
        cb(entry, function(err)
          if err then return end
          cb(nil, function() end)
        end)
      end
    end

    opts.fzf_opts = {
      ['--no-multi']        = '',
      ['--prompt']          = 'Projects❯ ',
      ['--preview-window']  = 'hidden:right:0',
    }

    local selected = require'fzf-lua.core'.fzf(opts, fzf_fn)
    if not selected then return end
    local pwd = require'fzf-lua.path'.join({
      vim.fn.expand('$HOME'), selected[1]:match("[^ ]*$")
    })
    require'utils'.set_cwd(pwd)
  end)()
end
```

**Comment by gegoune** [comment]
Awesome, thanks so much! Made couple of modifications (removed icons :)) - it works, but how would I immediately open old files for selected project? Or, I can fink of a case where project would not have been accessed in a while so no files for it are in oldfiles, would it be possible to detect such case and display files in such case?

**Comment by ibhagwan** [comment]
> Awesome, thanks so much! Made couple of modifications (removed icons :)) - it works, but how would I immediately open old files for selected project? Or, I can fink of a case where project would not have been accessed in a while so no files for it are in oldfiles, would it be possible to detect such case and display files in such case?

Anything is possible with a little bit of code.

> how would I immediately open old files for selected project?
```lua
...
    vim.cmd("cd " .. newcwd)
    require'fzf-files'.oldfiles({ cwd = newcwd })
    end)()
end
```

> can fink of a case where project would not have been accessed in a while so no files for it are in oldfiles, would it be possible to detect such case and display files in such case?

Add the below before calling `oldfiles`:

```lua
  local t = {}
  for _, file in ipairs(vim.v.oldfiles) do
    if vim.loop.fs_stat(file) and
      require'fzf-lua.path'.is_relative(file, newcwd) then
      table.insert(t, file)
    end
  end
  if vim.tbl_isempty(t) then return end
```

These are quick code sketches, I haven't test it but you get the idea.

**Comment by ibhagwan** [comment]
It's been two weeks so I'm assuming this works well for you :-)

If you need more help feel free to reopen the issue.

**Comment by gegoune** [comment]
Hey, sorry, got too busy to get back to it. will try it out again when I am free.

**Comment by ahmedkhalf** [comment]
Hello, author of project.nvim here, you can use:
```lua
require("project_nvim").get_recent_projects()
```
to get recent projects in project.nvim

**Comment by ibhagwan** [comment]
> Hello, author of project.nvim here, you can use:
> 
> ```lua
> require("project_nvim").get_recent_projects()
> ```
> 
> to get recent projects in project.nvim

This is great! tysm @ahmedkhalf, this will make the above even easier, I should probably add a section in the wiki/README for integration with other plugins.
