### ISSUE TITLE
Bug: `FzfLua lsp_definitions` throwing an error

### ISSUE THREAD

**Issue by ficcdaf** [ibhagwan/fzf-lua#1610]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-1035+g50e63c817

### Fzf version (`fzf --version`)

0.56.3 (add1aec6)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--height 50% --layout=default --border --color=hl:#933737

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
Folke's LazyVim default FzfLua settings.
```

### Describe the bug / steps to reproduce

Attempting to run the command `FzfLua lsp_definitions jump_to_single_result=true ignore_current_line=true` via LazyVim's default keymap `gd` results in the following error: 

```
   Error  11:11:52 PM msg_show.lua_error Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: Cannot serialise function: type not supported
stack traceback:
	[C]: in function 'encode'
	/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: in function 'encode_and_send'
	/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:334: in function 'request'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:673: in function 'request'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:882: in function 'buf_request'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:945: in function 'buf_request_all'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:966: in function 'buf_request_sync'
	...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:496: in function 'fn_contents'
	...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:662: in function <...al/share/nvim/lazy/fzf-lua/lua/fzf-lua/providers/lsp.lua:658>
	...e/fic/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/cmd.lua:35: in function 'run_command'
	/home/fic/.local/share/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:12: in function </home/fic/.local/share/nvim/lazy/fzf-lua/plugin/fzf-lua.lua:11>
```

It happened using `basedpyright` and `lua_ls`, I have not tested other language servers yet.

**Comment by ibhagwan** [comment]
Seems you're using a rather old neovim nightly build, the error seems to come from the runtime, can you please update to the latest nightly (works for me with `lua_ls`) and also try on 0.10.2 and let me know?

**Comment by ficcdaf** [comment]
It works both on the latest nightly and on 0.10.2, thank you very much!
I didn't realize my install was so outdated. I was using the `neovim-nightly-bin` AUR package, and replacing it with `neovim-git` fixed the issue. Thanks!

**Comment by ibhagwan** [comment]
Yap, your build is `1035` (in the OP), we're currently on `1383` :-)
