### ISSUE TITLE
Bug: Highlights search does not respect fzf_color option in the setup

### ISSUE THREAD

**Issue by ronisbr** [ibhagwan/fzf-lua#1617]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

macOS

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.1

### Fzf version (`fzf --version`)

0.55.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({ fzf_colors = true })
```

### Describe the bug / steps to reproduce

If you are using a light theme, you see that if I setup fzf-lua with `fzf_colors = true`, the colors are correctly applied to all finders except the one for highlights.

If I call `require("fzf-lua").highlights()`, the output is:

![Screenshot 2024-12-20 at 10 33 55](https://github.com/user-attachments/assets/b226d83a-1639-48f4-9476-2d6570276393)

Notice that the black line is not compatible with my theme. However, if I call `require("fzf-lua").highlights({ fzf_colors = true })`, then everything works perfectly:

![Screenshot 2024-12-20 at 10 34 38](https://github.com/user-attachments/assets/c0d5991a-0a22-4dfc-808d-620d076e2f44)

**Comment by ibhagwan** [comment]
This isn’t a bug, I recently changed the colors of highlights to be `reverse` as I found it better to experience the colors this way (vs override with fuzzy matching color):
https://github.com/ibhagwan/fzf-lua/blob/dd1aa78c189cd4a2a8686710aa548276b1185671/lua/fzf-lua/defaults.lua#L768

To override these, set the below to whatever you want or `false` to inherit from global:
```lua
require('fzf-lua').setup({ highlights = { fzf_colors = { ["hl"] = false, ["hl+"] = false }} })
-- or in the call directly
:lua require('fzf-lua').highlights({  fzf_colors = { ["hl"] = false, ["hl+"] = false } })
```

**Comment by ronisbr** [comment]
It is working perfectly now! Thanks @ibhagwan !
