### ISSUE TITLE
Look into reducing syntax highlighting delay in the builtin previewer

### ISSUE THREAD

**Issue by ibhagwan** [ibhagwan/fzf-lua#162]
Currently the builtin previewer first feeds the lines into the preview buffer and only then enables syntax highlighting which makes the preview window colors appear to “flicker” right as the highlights are enabled.

Explore if this can be solved by setting `filetype` before the lines are fed into the buffer (could be a perf issue?).

**Comment by ibhagwan** [comment]
Seems to be no significant perf issue, https://github.com/ibhagwan/fzf-lua/commit/5bdb21355892c1cf87fe37456cb3b8488ff5960f closes this.

**Comment by gegoune** [comment]
It definitely looks better now, thanks!
