### ISSUE TITLE
Bug: `73e7f5f93b65` break `complete_line`/`complete_bline`

### ISSUE THREAD

**Issue by phanen** [ibhagwan/fzf-lua#1627]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-1405+g99aa6bfd98

### Fzf version (`fzf --version`)

0.56.3 (add1aec6)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

73e7f5f93b65 break `complete_line`/`complete_bline`

**Comment by ibhagwan** [comment]
What does break mean? Not complete or does the interface not open?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a4f1644efaa0e3be884096711fcd5f7bf90c494c

FYI, it's the refactor of lines/blines that broke this https://github.com/ibhagwan/fzf-lua/commit/7836b37b1d7f4786b8c8804bac29beb3926a56a7 as the formatting of the line changed, should work as expected now.
