### ISSUE TITLE
Bug: The file path is not correct in results when shorten path is enabled

### ISSUE THREAD

**Issue by cpcopy** [ibhagwan/fzf-lua#1633]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.10.2

### Fzf version (`fzf --version`)

0.54.3 (af4917d)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
grep = {
            winopts = {
                preview = { hidden = "hidden" },
            },
            path_shorten = true,              -- 'true' or number, shorten path?
            formatter = "path.filename_first",
            fzf_opts = {
                ["--delimiter"] = "[:\t]",
                -- Separated by tab and ':', 1: file icon+name, 2: file path 3: line number, it is dependes on rg_opts whether column or line number is enabled or not.
                ["--with-nth"] = '1,3..',
                -- Search fileds
                ["--nth"] = '1..',
            },
            rg_opts = '--type c --line-number --no-heading --color=always --smart-case --max-columns=4096 -e',
        },
```

### Describe the bug / steps to reproduce

There are two files `xxx/max/map.h` and `xxx/min/map.h`. In file `xxx/min/map.h`, it has a string `OFFLOAD_MIN`. When grep the string, it will return the result, but the file path is `xxx/max/map.h` if check in review window or trouble.nvim window.
The issue only happens when shorten path is enabled. It looks like it finds the first file path matched with shorten path.

**Comment by ibhagwan** [comment]
Unfortunately without keeping extra metadata per entry (which is undesirable for many reasons) this is not fixable as the “lengthen” will meet the first path, you can play around with `path_shorten=2` to solve it but other than that this isn’t not something worth fixing IMHO.

**Comment by cpcopy** [comment]
I see. Thanks for explanation. Would it better to add a note for shorten path configuration?

**Comment by ibhagwan** [comment]
> I see. Thanks for explanation. Would it better to add a note for shorten path configuration?

Best place would be in OPTIONS.md but I don’t think it’s there yet, adding it in the “default optional” the info would be drowned, there’s a PR to give more clarify to the README but it’s not there yet.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/pull/2520, https://github.com/ibhagwan/fzf-lua/commit/cea4145d3509294e4f549ec47836c4c444702ff7

You can now use `winopts.path_shorten` instead of `path_shorten` for an extmarks based approach.

**Comment by cpcopy** [comment]
> [#2520](https://github.com/ibhagwan/fzf-lua/pull/2520), [cea4145](https://github.com/ibhagwan/fzf-lua/commit/cea4145d3509294e4f549ec47836c4c444702ff7)
> 
> You can now use `winopts.path_shorten` instead of `path_shorten` for an extmarks based approach.

So nice for the update. Tried on the latest version. I met two problems. 

1. If `formatter = "path.filename_first"`, no file name is shown.
2. Don't know why there are several lines at the right side of result window.

<img width="614" height="219" alt="Image" src="https://github.com/user-attachments/assets/3fdbc9f9-8839-48e8-bc27-f30db6d3b7e5" />

**Comment by ibhagwan** [comment]
> > [#2520](https://github.com/ibhagwan/fzf-lua/pull/2520), [cea4145](https://github.com/ibhagwan/fzf-lua/commit/cea4145d3509294e4f549ec47836c4c444702ff7)
> > You can now use `winopts.path_shorten` instead of `path_shorten` for an extmarks based approach.
> 
> So nice for the update. Tried on the latest version. I met two problems.
> 
> 1. If `formatter = "path.filename_first"`, no file name is shown.
> 2. Don't know why there are several lines at the right side of result window.
> 
> <img alt="Image" width="614" height="219" src="https://private-user-images.githubusercontent.com/80554779/560827496-3fdbc9f9-8839-48e8-bc27-f30db6d3b7e5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzMxNDE4NDQsIm5iZiI6MTc3MzE0MTU0NCwicGF0aCI6Ii84MDU1NDc3OS81NjA4Mjc0OTYtM2ZkYmM5ZjktODgzOS00OGU4LWJjMjctZjMwZGI2ZDNiN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzEwVDExMTkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MDBjOWE1ZjA2YzM1NTdkMjQxZmYzNmNmODFmNzY2ODI4ODQ4ODUyODkwYzY5NmM4OGUzNWQxNTM0MjZiOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A5ttEFidRfz-cCTkgMLPG5GDzrUPB6E-6hQ5obxcVqE">

Ty @cpcopy, will take a look as part of #2607
