### ISSUE TITLE
`manpages()` show no result after `hide()`

### ISSUE THREAD

**Issue by phanen** [ibhagwan/fzf-lua#1634]
## config
```lua
require("fzf-lua").setup({ keymap = { builtin = { ["<esc>"] = "hide" } } })
```

## repro
* `FzfLua manpages`
* `<esc>`
* `FzfLua manpages`, then it show nothing

**Comment by phanen** [comment]
A patch work for me.
```diff
diff --git a/lua/fzf-lua/core.lua b/lua/fzf-lua/core.lua
index 28f97d8..5c8a002 100644
--- a/lua/fzf-lua/core.lua
+++ b/lua/fzf-lua/core.lua
@@ -414,6 +414,7 @@ M.fzf = function(contents, opts)
   -- convert "exec_silent" actions to fzf's `execute-silent` binds
   opts = M.convert_reload_actions(opts.__reload_cmd or contents, opts)
   opts = M.convert_exec_silent_actions(opts)
+  if (opts.__resume_key == "manpages") then vim.wait(100) end
   local selected, exit_code = fzf.raw_fzf(contents, M.build_fzf_cli(opts, fzf_win),
     {
       fzf_bin = opts.fzf_bin,
```

**Comment by ibhagwan** [comment]
> A patch work for me.

Ty @phanen, but this is a hack, resume after hide should display the already existing fzf process, I’d like to better find out why this happens rather than hack it.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/fb73caf4ea10f07f064d69029f5c768f0dd8273b

The new process was getting killed by the old coroutine yielding and having the `was_hidden()` exit condition right below the kill.
