### ISSUE TITLE
Feature: could we make the help window configurable?

### ISSUE THREAD

**Issue by Bekaboo** [ibhagwan/fzf-lua#1638]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

Currently, the help window is hard-coded to open at the bottom of the screen, which can overlap with the fzf window when using split layout:

Before opening help:
![image](https://github.com/user-attachments/assets/d4b4b403-6d6d-4891-9fdf-619fe27afe36)

After opening help:
![image](https://github.com/user-attachments/assets/21b88264-607e-4dba-bf00-04cdadc250b3)

If putting at top with `border = "single"`:

![image](https://github.com/user-attachments/assets/3ef39ca2-eb64-462d-9fcf-a55e22aa2cba)

Could we expose an option `help_winopts` that accepts a table as the parameter passed to `vim.api.nvim_open_win()` so user can customize the border and position of the help window? I am glad to submit a PR for it.

**Comment by ibhagwan** [comment]
> Could we expose an option help_winopts that accepts a table as the parameter passed to vim.api.nvim_open_win() so user can customize the border and position of the help window? I am glad to submit a PR for it.

Im thinking maybe it’s better to supply a `help_open_win` opt, the option will be a function responsible for opening a new window, you can then set whatever options you want in `nvim_open_win` or even open in a top split using `vim.cmd(…)`?

This would also simplify the config (one single opt) as I don’t foresee too many users customizing the help window.

**Comment by Bekaboo** [comment]
> Im thinking maybe it’s better to supply a help_open_win opt, the option will be a function responsible for opening a new window, you can then set whatever options you want in nvim_open_win or even open in a top split using vim.cmd(…)?


Sounds great, thanks!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/24dff52a65aa71189425363bd2678c70c2ac8f41

Added my changes on top of your commit, made the option picker local so you can now do this per call (because why not):
```lua
require("fzf-lua").files({
  help_open_win = function(buf, enter, opts)
    opts.border = 'single'
    opts.row = 0
    opts.col = 0
    return vim.api.nvim_open_win(buf, enter, opts)
  end,
})
```

Note that I moved your changes from `fzf-lua-opts.txt`to `OPTIONS.md` as that's the original source of the options, the file is then auto-generated with [ts-vimdoc.nvim](https://github.com/ibhagwan/ts-vimdoc.nvim).
