### ISSUE TITLE
feat: delay on opening preview (also fix lags on fast scroll)

### ISSUE THREAD

**Issue by UnkwUsr** [ibhagwan/fzf-lua#164]
The main reason of adding it is lags when you fast scroll list of files with preview toggled on. I've tested with preview off, and there is no lags. So I think a small delay would fix it.

**Comment by ibhagwan** [comment]
Is the lag a new issue from the last commit? I just enabled instant syntax highlighting on the preview window which may have caused this issue.

**Comment by UnkwUsr** [comment]
No, I was at dca31060e21a367234e8f2a6fabc3051ab85fe9c and lags already exist. But now I also checked out your last commit with "instant syntax highlighting" and see that lags  increased heavily.

**Comment by UnkwUsr** [comment]
Also, done some research and found that "first" lags started at commit 28f3bcac27b6dbab37102336a22a38b81a6c4089 (disable preview for binary files)

**Comment by ibhagwan** [comment]
Try the latest commit https://github.com/ibhagwan/fzf-lua/commit/29ae04d73f7289fc17d99c08649b58f46a87bdce, it adds a default 60ms delay, solved fast scrolling for me, you can see the preview stays empty until you release the down arrow, you can change the delay (or disable it) by setting `previewers.builtin.delay`.

Let me know if that works better?

> Also, done some research and found that "first" lags started at commit 28f3bca (disable preview for binary files)

I have to find a better method to detecting binary files anyways, I don't know why but `file --dereference --mime` thinks some of my `.lua` files are binary...

**Comment by UnkwUsr** [comment]
Works good. Now it fast as if preview completely disabled. Thank you!

**Comment by ibhagwan** [comment]
> Works good. Now it fast as if preview completely disabled. Thank you!

Just found a small issue with the logic, incoming commit a few minutes to make it even faster.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/9454bcbad98654d8a4dc88a06d15985bd53acd1f changes the logic of the skip to be faster (not a string compare), and also increases the delay to 100ms to match how the native fzf preview works which  [according to this uses a 100ms delay](https://github.com/junegunn/fzf/issues/2417#issuecomment-809886535)

**Comment by UnkwUsr** [comment]
Thank you! 100ms delay looks better. Should I test/check anything else?

**Comment by ibhagwan** [comment]
> Thank you! 100ms delay looks better. Should I test/check anything else?

Not ATM, I'm currently working on fixing the binary test, if you want I'll alert you here so you can test if after.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/510aca8658a954e152bd5e97cdad4fd6b09b7ea7 restores binary test for the preview, shouldn't affect performance at all but you're welcome to test and let me know if it does :-)

**Comment by UnkwUsr** [comment]
Hmmmm... With `delay = 100`, of course, there is no performance affect, but i tried with `delay = 0` to test real performance, and... Found that enabling binary checking have huge performance affect (I'm comparing commits 9454bcbad98654d8a4dc88a06d15985bd53acd1f and 510aca8658a954e152bd5e97cdad4fd6b09b7ea7). I tried to disable syntax highlighting by only commenting this lines https://github.com/ibhagwan/fzf-lua/blob/510aca8658a954e152bd5e97cdad4fd6b09b7ea7/lua/fzf-lua/previewer/builtin.lua#L280-L289 (not sure how it clear), and tried to test again: disabled binary checking vs new binary checking (perl -B). My conclusion is that with enabled syntax highlighting, binary checking have huge performance affect, but with disabled syntax highlighting I can't say that I see difference between disabled and enabled binary checking.

About preview rotation: can't imagine when it can be used, but I'm not fan of beauty, so maybe for someone it can be useful:D.
P.S. now i go to sleep, so please don't wait me for answer :D. Sorry

**Comment by ibhagwan** [comment]
> Hmmmm... With delay = 100, of course, there is no performance affect, but i tried with delay = 0 to test real performance, and... Found that enabling binary checking have huge performance affect (I'm comparing commits 9454bcb and 510aca8). I tried to disable syntax highlighting by only commenting this lines 

You didn't need to comment any lines to disable syntax highlighting, you can set `previewers.builtin.syntax = false`.

> disabled binary checking vs new binary checking (perl -B). My conclusion is that with enabled syntax highlighting, binary checking have huge performance affect, but with disabled syntax highlighting I can't say that I see difference between disabled and enabled binary checking.

I'll try and check why there's a connection when I have more time, in any event I don't see this as an issue as I don't see any practical use to disabling the delay, given that it works fine with the 100ms delay it's safe to leave this issue for now.

> P.S. now i go to sleep, so please don't wait me for answer :D. Sorry

Good night!
