### ISSUE TITLE
Bug: previewer doesn't handle rg --fixed-strings

### ISSUE THREAD

**Issue by abdennourzahaf** [ibhagwan/fzf-lua#1641]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.2

### Fzf version (`fzf --version`)

0.57.0

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
   grep = {
    rg_opts = "--column --line-number --no-heading --color=always --fixed-strings --smart-case --max-columns=4096 -e",
  },
})
```

### Describe the bug / steps to reproduce

`:lua require("fzf-lua").live_grep({ rg_opts = "--column --line-number --no-heading --color=always --fixed-strings --smart-case --max-columns=4096 -e" })` and input "(".
It should show the correct items but the previewer will throw `[Fzf-lua] Unable to init vim.regex with "\v(", couldn't parse regex: Vim:E54: Unmatched (`

**Comment by abdennourzahaf** [comment]
Btw, awesome plugin!

**Comment by ibhagwan** [comment]
> Btw, awesome plugin!

Ty friend, should work as expected post https://github.com/ibhagwan/fzf-lua/commit/7307943791d7531a8a04f6ccbc5ac8e3292ea467.
