### ISSUE TITLE
Feature: support searching modified / unsaved buffers

### ISSUE THREAD

**Issue by andreihh** [ibhagwan/fzf-lua#1647]
### Have you RTFM'd?

- [X] I have done proper research

### Feature Request

I like to check if I have any unsaved changes before stashing / committing changes to Git.

So far, I tried three workflows:

1. Run `:ls +` to list the modified buffers, run `:b ${bufnr}` to open each modified buffer, and run `:DiffOrig` (see `:help :DiffOrig`) to inspect the unsaved changes in diff view before saving.
2. Run `:FzfLua buffers query='+'` as an approximation for searching for modified buffers (falsely include files that contain `+` in their path / name), and then run `:DiffOrig`.
3. Create a custom picker for modified buffers, and then run `:DiffOrig`:
```lua
function()
  local unsaved_buffers = {}
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    local is_saved = vim.api.nvim_get_option_value("modified", { buf = buf })
    local bufname = vim.api.nvim_buf_get_name(buf)
    if is_saved then
      table.insert(unsaved_buffers, bufname)
    end
  end
  require("fzf-lua").fzf_exec(unsaved_buffers, {
    prompt = "Buffers>",
    previewer = "builtin",
    actions = { default = require("fzf-lua").actions.file_edit },
  })
end,
```

It would be great if there was a native picker with the following features:
- Uses a flavor of the default `buffers()` picker (i.e., highlights buffer number, flags, etc.)
- Displays only modified buffers
- Allows selecting the current buffer as well (important for the preview)
- Preview shows diffs (similar to the `git_diff` previewer) between in-memory buffer state and file-on-disk state
- Besides the default action of opening the buffer, also provide an action to write changes for the currently selected buffer (e.g., bound to `<C-w>` for "write" or `<C-s>` for "save")

Alternatively, at least provide an option to the default `buffers()` picker to filter buffers by flags (e.g., `FzfLua buffers flags='+'` should only list modified buffers). While missing some of the nice-to-haves, like the diff view, it would at least remove the need of writing a custom picker.

**Comment by ibhagwan** [comment]
Honestly, that’s a bit too niche to have its own picker, between buffers and git_status this is sufficient for 99% of the use cases.


> Run :FzfLua buffers query='+' as an approximation for searching for modified buffers (falsely include files that contain + in their path / name)

Files with + are pretty rare and those can be moved to the bottom of the list by using `--tiebreak=begin`.

> Alternatively, at least provide an option to the default buffers() picker to filter buffers by flags (e.g., FzfLua buffers flags='+' should only list modified buffers). While missing some of the nice-to-haves, like the diff view, it would at least remove the need of writing a custom picker.

I can provide a `buffer` option (table) where you can supply your own list of buffers if you’d like.

**Comment by andreihh** [comment]
> I can provide a buffer option (table) where you can supply your own list of buffers if you’d like.

That would work as well!

**Comment by andreihh** [comment]
Also: is there an option to allow selecting / previewing the current buffer? Or would it be possible to add such an option?

**Comment by ibhagwan** [comment]
> Also: is there an option to allow selecting / previewing the current buffer? Or would it be possible to add such an option?

```vim
:FzfLua buffers fzf_opts.--header-lines=false
-- disabling sort also disables the header 
:FzfLua buffers sort_lastused=false
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/dbc5bd14e72ba680df44906e957b0a821121726b

Works for both `buffers` and `lines`:
```vim
:FzfLua buffers buffers={113,102,134}
:FzfLua lines buffers={1}
```
With lua:
```lua
:lua require("fzf-lua").buffers({buffers={1}})
```
