### ISSUE TITLE
Operation not supported on socket

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#165]
Just updated plugin (and nvim-fzf, so sorry if breaking change is there) and getting this printed out in fzf's window:

```
/bin/sh: /var/folders/zm/t9yhs_ts7fzcyvm64l5zyk1w0000gn/T/nvimzJYjkD/3: Operation not supported on socket

[Process exited 1]
```

Message in cmdwindow says: 
```
...l/share/nvim/site/pack/packer/start/nvim-fzf/lua/fzf.lua:29: attempt to index local 'file' (a nil value)
```

I am on macOS.

**Comment by gegoune** [comment]
Yes, going back to commit prior to https://github.com/vijaymarupudi/nvim-fzf/commit/d87d87978a973208dcfa76ab429000e478ae3ea1 fixes it, so it's upstream.

**Comment by ibhagwan** [comment]
> Yes, going back to commit prior to [vijaymarupudi/nvim-fzf@d87d879](https://github.com/vijaymarupudi/nvim-fzf/commit/d87d87978a973208dcfa76ab429000e478ae3ea1) fixes it, so it's upstream.
> 
> @vijaymarupudi would you want me to open issue in your repository?

Good catch, [I see it was already reverted](https://github.com/vijaymarupudi/nvim-fzf/commit/bc222a3173e570331c77a4a8f9eb9d440b893149)

**Comment by vijaymarupudi** [comment]
Thanks gegoune, I'm sorry about that, working on fixing it!

**Comment by gegoune** [comment]
@vijaymarupudi No need to apologise, great thanks for all your hard work guys!
