### ISSUE TITLE
Bug: Commit `d99996b` breaks `lsp_references` preview when using `bat` as previewer

### ISSUE THREAD

**Issue by somnam** [ibhagwan/fzf-lua#1651]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

bash

### Neovim version (`nvim --version`)

v0.10.3

### Fzf version (`fzf --version`)

0.57.0 (0476a65)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
  winopts = {
    height = 0.85,
    width = 0.65,
    col = 0.50,
    backdrop = 100,
    preview = {
      default = "bat",
      layout = "vertical",
      winopts = { number = false },
    },
  },
  fzf_opts = {
    ["--history"] = vim.fn.stdpath("data") .. "/fzf_lua_history",
  },
})
```

### Describe the bug / steps to reproduce

Commit `d99996b`  breaks `lsp_references` preview when using `bat` as default previewer.
Issuing `FzfLua lsp_references` shows `'<null>: NO SUCH FILE OR ACCESS DENIED` error in preview window instead of file contents:

<img width="752" alt="image" src="https://github.com/user-attachments/assets/7849b3d3-2761-45b7-92d0-45862a154784" />

**Comment by ibhagwan** [comment]
Ty @somnam, I know what happened here, will be fixed shortly.

**Comment by chrisgeo** [comment]
Just in case you needed on more, similar error:

```
stack traceback:
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:107: in function 'job'
	...s/.local/share/nvim/lazy/codeium.nvim/lua/codeium/io.lua:186: in function 'shell_open'
	...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:71: in function 'callback'
	...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:109: in function '_on_choice'
	...re/nvim/lazy/fzf-lua/lua/fzf-lua/providers/ui_select.lua:52: in function 'action'
	...s/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/actions.lua:117: in function 'act'
	...re/nvim/lazy/fzf-lua/lua/fzf-lua/providers/ui_select.lua:121: in function 'exec_choice'
	...re/nvim/lazy/fzf-lua/lua/fzf-lua/providers/ui_select.lua:145: in function 'fn_selected'
	...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:235: in function <...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:234>
	[C]: in function 'xpcall'
	...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:234: in function <...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:226>
stack traceback:
	...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:242: in function <...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:236>
	[C]: in function 'error'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:107: in function 'job'
	...s/.local/share/nvim/lazy/codeium.nvim/lua/codeium/io.lua:186: in function 'shell_open'
	...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:71: in function 'callback'
	...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:109: in function '_on_choice'
	...re/nvim/lazy/fzf-lua/lua/fzf-lua/providers/ui_select.lua:52: in function 'action'
	...s/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/actions.lua:117: in function 'act'
	...re/nvim/lazy/fzf-lua/lua/fzf-lua/providers/ui_select.lua:121: in function 'exec_choice'
	...re/nvim/lazy/fzf-lua/lua/fzf-lua/providers/ui_select.lua:145: in function 'fn_selected'
	...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:235: in function <.../.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:234>
	[C]: in function 'xpcall'
	...hris/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:234: in function <.../.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:226>

```
Setup:
I just use whatever LazyVim offers out of the box or in extras.

Use-Case:
Bring Codeium up in LazyVim, select `Auth`

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b4153da4825f86c7dbc540c5fc238ccc8c24d75a

@somnam, this should fix it.

@chrisgeo, can you check if the latest solves your issue as I'm not sure if it's the same.

**Comment by ibhagwan** [comment]
@chrisgeo, looking at the stack trace this seems like an unrelated issue and is most likely a bug in the codium plugin,, stack trace leads me here:
https://github.com/Exafunction/codeium.nvim/blob/27d2b1ce8c7ba14dbf6e4504bdea8e5548be5476/lua/codeium/io.lua#L186

I suggest opening an issue upstream: https://github.com/Exafunction/codeium.nvim/issues

**Comment by somnam** [comment]
Thank you @ibhagwan for such a quick response 🙇‍♂️

**Comment by chrisgeo** [comment]
@ibhagwan it helped, thank you. I funny enough uninstalled codedium once before that as well.

**Comment by ibhagwan** [comment]
> @ibhagwan it helped, thank you. I funny enough uninstalled codedium once before that as well.

Wild stuff as I don’t see the connection but good to know :)
