### ISSUE TITLE
Bug: Long lines are getting cutoff when using the delta previewer

### ISSUE THREAD

**Issue by aweis89** [ibhagwan/fzf-lua#1655]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1734355927

### Fzf version (`fzf --version`)

0.56.3 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--multi --layout=reverse --color=light --bind='ctrl-p:toggle-preview' --bind='ctrl-s:toggle+down' --bind='ctrl-y:select-all' --bind='ctrl-d:half-page-down,ctrl-u:half-page-up' --bind='ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up' --bind='ctrl-/:change-preview-window(down,50%,border-top|hidden|)'

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

When running `FzfLua git_commits` or `FzfLua git_status` long lines are getting cutoff instead of wrapped. Running `git diff <sha>` in the terminal does not produce the same effect. In both cases, `delta` is set as the git pager with the latest version installed.

**Comment by ibhagwan** [comment]
That’s not a bug, with native prefiew wrapping is controlled by fzf, press F3 to toggle wrap (default bind, customizable), or set `winopts.preview.wrap` to make wrapping the starting default.
