### ISSUE TITLE
Bug: unwanted "i" automatically inserted everywhere

### ISSUE THREAD

**Issue by dimbleby** [ibhagwan/fzf-lua#1659]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

bash

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-1449+gb5cb69f8a4

### Fzf version (`fzf --version`)

0.57.0 (fd513f8a)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

nil

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [X] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup({
})
```

### Describe the bug / steps to reproduce

eg `:lua require('fzf-lua').buffers()`, per this asciinema recording https://asciinema.org/a/Qu41Lixu9zDtS9lJfTPsO007w

I see that https://github.com/ibhagwan/fzf-lua/commit/43c3a47c28d4fa93e18450516dbf7fc14e102a42 seems to have been in this ballpark, so perhaps you are aware of this already

**Comment by ibhagwan** [comment]
> I see that https://github.com/ibhagwan/fzf-lua/commit/43c3a47c28d4fa93e18450516dbf7fc14e102a42  seems to have been in this ballpark, so perhaps you are aware of this already

Correct, are you experiencing this with HEAD?
How you tried with `mini.sh`?
Do you have an `autocmd` in your config for TermOpen?

**Comment by ibhagwan** [comment]
My hunch was right, you have an autocmd for TermOpen that already executes `startinsert`:
https://github.com/dimbleby/dotfiles/blob/298242bf6e1102a5ca993894ea4d8eb24c63fa05/.config/nvim/lua/config/autocmds.lua#L2-L7.

Fixed in https://github.com/ibhagwan/fzf-lua/commit/c054a21cd22cef41c62ce96247040abccaab8dbc

**Comment by dimbleby** [comment]
haha, slightly stalker-ish but nice detective work!  Thanks for the fix

**Comment by ibhagwan** [comment]
> haha, slightly stalker-ish but nice detective work! Thanks for the fix

I run a tight ship here no bugs allowed lol

**Comment by jmbaur** [comment]
I believe this issue has cropped back up, I'm currently running on b1d2b0dc146cb9260209da4d7ab754adb0a2653d but have tried the HEAD of main as well (currently a03d68e40eea835a1cdbd9f93049708dab3621e6)

**Comment by ibhagwan** [comment]
> I believe this issue has cropped back up, I'm currently running on [b1d2b0d](https://github.com/ibhagwan/fzf-lua/commit/b1d2b0dc146cb9260209da4d7ab754adb0a2653d) but have tried the HEAD of main as well (currently [a03d68e](https://github.com/ibhagwan/fzf-lua/commit/a03d68e40eea835a1cdbd9f93049708dab3621e6))

The OP issue was due to a terminal autocmd, test with mini.sh and see if you have an autocmd as described in this thread?

Also the behavior is about to change so this may get resolved, you can test with the branch from PR #2501?

**Comment by jmbaur** [comment]
I'm also using `startinsert` on `TermOpen`. I was able to reproduce using `mini.sh` and a blank config (no autocmd) with nvim 0.12-dev (pretty recent), but interestingly not with nvim 0.11. Regardless, the PR you linked above does fix the issue for me on 0.12 (while keeping my original config and everything!)

**Comment by ibhagwan** [comment]
@jmbaur FYI #2501 was merged so this should be solved on main.

**Comment by jmbaur** [comment]
> @jmbaur FYI #2501 was merged so this should be solved on main.

Thank you! Much appreciated
