### ISSUE TITLE
live_grep doesn't seem to working

### ISSUE THREAD

**Issue by sun617** [ibhagwan/fzf-lua#166]
![image](https://user-images.githubusercontent.com/1286238/135948233-cc772d83-eb32-4174-8bc5-ca010b863c32.png)

Environment:
- ArchLinux
- NVIM v0.5.1
- ripgrep 13.0.0
- fzf 0.27.2
- sk 0.9.4

**Comment by ibhagwan** [comment]
`live_grep` doesn’t run on empty queries, did you try typing?

If you want it to run empty queries run `require'fzf-lua'.live_grep({ exec_empty_query = true })`

**Comment by sun617** [comment]
when i try typing, command failed
![image](https://user-images.githubusercontent.com/1286238/135951480-a88a287b-8062-4ca0-af97-6949e5bd5ce5.png)

**Comment by ibhagwan** [comment]
What shell are you using? any chance you’re using `fish`?

Can you also please try `live_grep_resume` instead?

**Comment by sun617** [comment]
- Yes, i am using `fish`
- `live_grep_resume` is working expectedly 
- `live_grep({  exec_empty_query = true })`
  - first it list up candidates
    ![image](https://user-images.githubusercontent.com/1286238/135953646-5c696c07-bba7-4968-8976-f8eb7d00c572.png)
  - then when i typing
    ![image](https://user-images.githubusercontent.com/1286238/135953760-c04966cb-34c5-483e-96c8-ebc3dfaf8539.png)

**Comment by ibhagwan** [comment]
Ok, I’ll wrap the command with `sh -c` to work around the fish shell, for the time being you can use the `resume` version, they should be equivalent except that `resume` has the ability to save the typed query and then continues the search where you last stopped (can be disabled).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/67163f4c5fb8f19ecdca7e99f6eb99bb48e52a95 should solve it, try and let me know?

**Comment by sun617** [comment]
solved, thanks!
