### ISSUE TITLE
Register LSP providers as LSP handlers

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#17]
How about making fzf-lua in drop in replacement for `ojroques/nvim-lspfuzzy` and making all LSP related providers register themselves as handlers so they can be invoked by native LSP related commands/keymaps? Could be behind an option.

**Comment by ibhagwan** [comment]
I thought about it, I also looked at `nvim-lspfuzzy` and even took some ideas from the plug-in code, I’m not a big fan of replacing the builtin functionality, most ppl never call any lsp function directly but rather use the `g…` mappings which they can simply map to fzf-lua instead, I’m not sold on the use case yet.

**Comment by ibhagwan** [comment]
Closing this for now, unless there's much demand for this I'll revisit the idea, this can be easily worked around with mappings should someone wish to do this.
