### ISSUE TITLE
Move up and down the list with different bindings

### ISSUE THREAD

**Issue by iovis** [ibhagwan/fzf-lua#170]
This may be a very dumb question but I don't seem to figure this one out.

I recently started trying out your plugin (great work, btw) and I usually navigate the FZF items with `ctrl-j` and `ctrl-k`. I saw that the arrows worked but every time I tried the bindings I mentioned it just cancels and goes back to my buffer.

I tried:
```lua
require('fzf-lua').setup {
  keymap = {
    builtin = {
      -- [...]
      ["ctrl-j"] = "down",
      ["ctrl-k"] = "up",
    }
  },
  fzf = {
    ["ctrl-j"] = "down",
    ["ctrl-k"] = "up",
  },
}
```

But I can seem to make it work. Any hints on what I may be doing wrong?

**Comment by iovis** [comment]
Nvm, I fixed it with the following:
```vim
augroup fzf_commands
  autocmd!
  autocmd FileType fzf tnoremap <silent> <buffer> <c-j> <down>
  autocmd FileType fzf tnoremap <silent> <buffer> <c-k> <up>
augroup end

```

**Comment by iovis** [comment]
I see I had the `fzf`  outside the `keymap` table, I knew I sucked haha. 

After I figured out the `autocmd` part I had enough clues to check what might be going on and I found the culprit in:
```vim
tnoremap <c-h> <c-\><c-n><C-w>h
tnoremap <c-j> <c-\><c-n><C-w>j
```

Which I have to move between panes (not sure why, because I use tmux so I never really use the embedded terminal, but I'm weird like that). I commented out those lines and the bindings worked as expected, so now I know exactly why it was not working as I expected and why I couldn't effectively control it with the plugin settings or the `FZF_DEFAULT_OPTS`.

Thanks a lot for your patience and for clarifying!

**Comment by ibhagwan** [comment]
Fantastic! I hate leaving issues unsolved with ugly workarounds, nothing like getting to the bottom of a "vodoo issue" :-)

Btw, if you need specific bindings or initializers for the fzf main window you can also use a lesser known feature `window_on_create`:

```lua
  winopts = {
    window_on_create = function()
      print("this gets called once upon opening the fzf window")
      -- so you can use vim.cmd("setlocal ...")
    end
  }
```

**Comment by ibhagwan** [comment]
This is great!

One day when I get to complete the [dreaded Wiki](https://github.com/ibhagwan/fzf-lua/wiki) FAQ I'll add this to it as well lol

**Comment by ibhagwan** [comment]
> Just run into the same issue :) Thanks for your great work btw.

Ty!

**Comment by LoydAndrew** [comment]
I'm trying to move from init.vim to init.lua settings. And with init.lua C-J and C-D do not work - they close the window. When I switched to init.vim - it works as suspected.  I tried this thing https://github.com/ibhagwan/fzf-lua/issues/170#issuecomment-936991432 without any luck.  
My config. 
```lua
local status_ok, fzf_lua = pcall(require, "fzf-lua")
if not status_ok then
  return
end
local actions = fzf_lua.actions

fzf_lua.setup ({
previewers = {
    git_diff = {
     pager           = "delta"
    }
},
files = {
    -- previewer         = "cat",       -- uncomment to override previewer
    prompt            = 'files❯ ',
    cmd               = "rg --files --no-ignore-vcs  -g '!*venv*' -g '!*node_modules*' -g '!*pyc*' -g '!*.environ' -g '!*dist*' -g '!*build'",             -- "find . -type f -printf '%P\n'",
    git_icons         = true,           -- show git icons?
    file_icons        = true,           -- show file icons?
    color_icons       = true,           -- colorize file|git icons
    actions = {
      -- set bind to 'false' to disable
      ["default"]     = actions.file_edit,
      ["ctrl-s"]      = actions.file_split,
      ["ctrl-v"]      = actions.file_vsplit,
      ["ctrl-t"]      = actions.file_tabedit,
      ["alt-q"]       = actions.file_sel_to_qf,
      -- custom actions are available too
      ["ctrl-y"]      = function(selected) print(selected[1]) end,
    }
  },
  keymap = {
    -- These override the default tables completely
    -- no need to set to `false` to disable a bind
    -- delete or modify is sufficient
    builtin = {
      -- neovim `:tmap` mappings for the fzf win
      ["<F2>"]        = "toggle-fullscreen",
      -- Only valid with the 'builtin' previewer
      ["<F3>"]        = "toggle-preview-wrap",
      ["<F4>"]        = "toggle-preview",
      -- Rotate preview clockwise/counter-clockwise
      ["<F5>"]        = "toggle-preview-ccw",
      ["<F6>"]        = "toggle-preview-cw",
      ["<C-d>"]    = "preview-page-down",
      ["<C-u>"]      = "preview-page-up",
      ["<S-left>"]    = "preview-page-reset",
    },
    fzf = {
      -- fzf '--bind=' options
      -- Only valid with fzf previewers (bat/cat/git/etc)
      -- ["ctrl-u"]        = "unix-line-discard",
      ["ctrl-j"] = "down",
      ["ctrl-k"] = "up",
      ["ctrl-f"]        = "half-page-down",
      ["ctrl-b"]        = "half-page-up",
      ["ctrl-a"]        = "beginning-of-line",
      ["ctrl-e"]        = "end-of-line",
      ["alt-a"]         = "toggle-all",
      -- Only valid with fzf previewers (bat/cat/git/etc)
      ["f3"]            = "toggle-preview-wrap",
      ["f4"]            = "toggle-preview",
    },
  },
grep = {
    prompt            = 'grep❯ ',
    input_prompt      = 'Grep For❯ ',
    git_icons         = true,           -- show git icons?
    file_icons        = true,           -- show file icons?
    color_icons       = true,           -- colorize file|git icons
    rg_opts = '--hidden --column --line-number --no-heading --color=always --smart-case -g "!node_modules/" -g "!idea" -g "!.vscode" -g "!venv" -g "!.mypy_cache" -g "!build" -g "!dist"  -g "!__pycache__" -g "!tags" -g "!*.git" -g "!package-lock.json" -g "!.environ" -g "!*pot"'
  },
})

```

**Comment by ibhagwan** [comment]
@LoydAndrew, it sounds to me like your setup function isn’t being called when used with `init.lua`, not sure which package manager you’re using but if using packer you have to call your setup function as part of the `config` event.

**Comment by LoydAndrew** [comment]
There is a hundred percent it's loading. Cause I replace prompt input 
![Screenshot_2022-01-02_21-28-18](https://user-images.githubusercontent.com/28489428/147887235-e4c8aedb-3c2c-4fdb-a960-1c92f0d98647.png)

**Comment by ibhagwan** [comment]
What if you create an empty function with a print statement inside, does that get called?
> you can use `window_on_create` or `on_create`, should be the same thing

```lua
require'fzf-lua'.setup {
  winopts = {
    on_create        = function()
      print("on_create")
    end,
  }
}
```

**Comment by LoydAndrew** [comment]
Yeah, it is called. 
![Screenshot_2022-01-02_21-51-07](https://user-images.githubusercontent.com/28489428/147887724-cada5558-ea60-4e00-a7aa-cfcf75684ea5.png)

**Comment by ibhagwan** [comment]
- Can you post how do you define the mappings inside `on_create`?
- Once `fzf` win hs open can you press `<c-w>:tmap<cr>` and post the output, this will show us if the `<C-j>` mapping exist

**Comment by LoydAndrew** [comment]
Can you help, please. How can I press this sequence <c-w>:tmap<cr> ? 
My definition of on_create function 
```lua
            require("fzf-lua").setup({
                on_create = function()
                    local tnoremap = function(lhs, rhs)
                        vim.api.nvim_buf_set_keymap(0, "t", lhs, rhs, { silent = true, noremap = true })
                    end

                    print("on_create")
                    tnoremap("<c-j>", "<down>")
                    tnoremap("<c-k>", "<up>")
                end,
```  
But, the thing is I don't even have this mapping when I'm using init.vim. But on init.lua it doesn't work anyway (with or without).

**Comment by ibhagwan** [comment]
The same code you posted works fine on my setup, perhaps you have another conflicting bind somewhere, maybe another plugin that takes over that bind with it's defaults? that would explain why you didn't need these bindings with `init.vim` as `ctrl-j|k` are the default for `up|down` in `fzf` and do not need to be defined.

You can also try to force these binds inside `fzf` by adding the below to the `keymap.fzf` table:
```lua
  keymap = {
    fzf = {
      ...
      ...
      -- Copy the default binds and add these below
      ["ctrl-j"]        = "down",
      ["ctrl-k"]        = "up",
    },
  },
```

> Note that if you have something else that overrides `<C-j>|<C-k>` inside neovim the above will likely not help as the neovim binds will have priority of the terminal binds.

**Comment by LoydAndrew** [comment]
Yes, thank you! Found that bastard in toggleterm mappings, sorry for that. While, I'm on it maybe you can help me with this question, cause it applies to mappings as well: 
```lua
 keymap = {
    -- These override the default tables completely
    -- no need to set to `false` to disable a bind
    -- delete or modify is sufficient
    builtin = {
      -- neovim `:tmap` mappings for the fzf win
      ["<F2>"]        = "toggle-fullscreen",
      -- Only valid with the 'builtin' previewer
      ["<F3>"]        = "toggle-preview-wrap",
      ["<F4>"]        = "toggle-preview",
      -- Rotate preview clockwise/counter-clockwise
      ["<F5>"]        = "toggle-preview-ccw",
      ["<F6>"]        = "toggle-preview-cw",
      ["<C-d>"]    = "preview-page-down",
      ["<C-u>"]      = "preview-page-up",
      ["<S-left>"]    = "preview-page-reset",
    },
    fzf = {
      -- fzf '--bind=' options
      -- Only valid with fzf previewers (bat/cat/git/etc)
      -- ["ctrl-u"]        = "unix-line-discard",
      ["ctrl-j"] = "down",
      ["ctrl-k"] = "up",
      ["ctrl-f"]        = "half-page-down",
      ["ctrl-b"]        = "half-page-up",
      ["ctrl-a"]        = "beginning-of-line",
      ["ctrl-e"]        = "end-of-line",
      ["alt-a"]         = "toggle-all",
      -- Only valid with fzf previewers (bat/cat/git/etc)
      ["f3"]            = "toggle-preview-wrap",
      ["f4"]            = "toggle-preview",
    },
  }, 
  ``` 
  These mappings work with  live_grep, find_files etc. But don't work with git commands. Is it intentantional, is there a way to make it work. Again, sorry for polluting this closed issue
   ["<C-d>"]    = "preview-page-down",
      ["<C-u>"]      = "preview-page-up",

**Comment by ibhagwan** [comment]
No problem @LoydAndrew, with git commands the preview is not a neovim buffer (AKA the “builtin” previewer) but a previewer drawn by fzf itself, to scroll up/down in the fzf previewer you need to add two more fzf-style bindings (`shift-down` instead of `<S-down>` etc) under `keymap.Fzf`:
```lua

fzf = {
      …
      ["shift-down"]  = "preview-page-down",
      ["shift-up"]    = "preview-page-up",
    },
```
