### ISSUE TITLE
Seeing two Files promps

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#171]
Hello,

After recent update I see two "Files" prompts when performing 'FzfLua files'

![image](https://user-images.githubusercontent.com/5642902/136392910-04e7a990-fa6d-4e74-9d74-815895ff85f2.png)

Is this expected? 

config: https://github.com/ldelossa/dotfiles/blob/master/nvim/fzf.lua

**Comment by ldelossa** [comment]
Also noticing some strange rendering when a search pattern is entered:

![image](https://user-images.githubusercontent.com/5642902/136393437-3550aaf7-a3a7-4702-ae34-4a6ac3b3a19d.png)

**Comment by ibhagwan** [comment]
Does this happen in the shell too or just in neovim? Is this a rendering issue in neovim terminal emulator or fzf?

I’m wondering if there’s anything I can do from my end to alleviate this issue.

**Comment by ldelossa** [comment]
if I just run 'fzf' in my terminal, the contents is clipped off way before it hits the top of the screen. Any way you'd like me to try and test/reproduce outside of neovim?

**Comment by ldelossa** [comment]
actually, it looks fine, but prompt is at bottom:

![image](https://user-images.githubusercontent.com/5642902/136477206-65c82d7b-b2df-47c1-9362-a25f1789f897.png)

**Comment by ibhagwan** [comment]
> ~if I just run 'fzf' in my terminal, the contents is clipped off way before it hits the top of the screen~. Any way you'd like me to try and test/reproduce outside of neovim?

Perhaps it would be beneficial to try with different neovim versions?

One thing worth trying would be running fzf in the neovim terminal (without fzf-lua), just run ‘:new | term` make it the only window and run fzf inside it? Might not be exactly the same thing as the window wouldn’t be a float window but it’s worth a try.

On that note might also be worth trying to uncomment `winopts.split` and seeing if this also happens in a split win setup.

**Comment by ldelossa** [comment]
so odd, i can't reproduce once again, on same laptop now. 

TBH, I may chalk this up being on a new wayland DE/WM.
