### ISSUE TITLE
ctrl-q quits, doesn't toggle cmd mode with skim

### ISSUE THREAD

**Issue by danngreen** [ibhagwan/fzf-lua#173]
I was looking for a way to use fzf syntax with live_grep, such as:
```
find-me !exclude-me 'exact-match
```
and I came across the following comment in a closed issue:

------

Alternatively if you use [`skim` - rust version of fzf](https://github.com/lotabout/skim), you can use live grep and press `ctrl-q` to toggle back and forth between fuzzy and exact match (with `live_grep`)

_Originally posted by @ibhagwan in https://github.com/ibhagwan/fzf-lua/issues/152#issuecomment-925895502_

------

So I put `fzf_bin='sk'` in my config, and now sk works great. But, while ctrl-q toggles interactive mode when I use skim from the command line, hitting ctrl-q  just closes the fzf-lua window when I use it with FzfLua live_grep.

If I comment out these lines in config.lua:
```
M.globals.files = {
...
      -- ["ctrl-q"]        = function()
      --   utils.info("'ctrl-q|ctrl-a' has been deprecated in favor of 'alt-q|alt-a'")
      -- end
```

then ctrl-q will toggle modes when using FzfLua live_grep. 

It seems that the utils.info message says ctrl-q is deprecated anyways, so this would cause no harm to remove these lines, right? I can post a pull request for this if you like.

What this means is that we can switch modes in FzfLua live_grep to input fzf syntax (! and '), and then ctrl-q back to the normal mode to fuzzy filter the file contents. So that's great. But not ideal, since there are two modes, each with a different syntax, and one that filters only file contents, and the other filters file names plus file contents. So it gets confusing when using it.

My main question is: Do you have any comments on how to use fzf syntax when live_grepping? (that is, being able to exclude with ! and exact match with '). 
I suppose I could write a script to convert the fzf syntax to rg syntax (--glob and -e), like live_grep_glob does. Would that be the best way?

The original fzf-vim plug handles fzf syntax perfectly with "live grepping", but I find it difficult to customize because of the VimL. So it'd be great if this plug-in could do it. Perhaps I'm missing something obvious?

Oh, and thanks for all your work on this!

**Comment by ibhagwan** [comment]
>It seems that the utils.info message says ctrl-q is deprecated anyways, so this would cause no harm to remove these lines, right? I can post a pull request for this if you like.

In order to use `ctrl-q` with `sk` you have to “undo” the default binding by setting it to `false`, the below is from my own config:

```lua

grep = {
    prompt            = 'Rg❯ ',
    input_prompt      = 'Grep For❯ ',
    actions           = { ["ctrl-q"] = false },
    -- 'true' enables file and git icons in 'live_grep'
    -- degrades performance in large datasets, YMMV
    experimental      = true,
  }
```

> The original fzf-vim plug handles fzf syntax perfectly with "live grepping", but I find it difficult to customize because of the VimL. So it'd be great if this plug-in could do it. Perhaps I'm missing something obvious?

If you can explain to me in detail what `fzf.vim` does I can replicate the behavior, I’m wondering how the above happens, perhaps it’s not live grep but rather something more akin to `lines` but with the entire lines of the project? If so you can simple run `grep` with an empty query (`grep({ search = '' })`) and then you can “fzf” all lines of the project, **but this wouldn’t be called `live_grep`**.
