### ISSUE TITLE
Bug: LSP client not detected after LspRestart

### ISSUE THREAD

**Issue by kazhala** [ibhagwan/fzf-lua#174]
Hi,

Awesome plugin, really appreciate your effort.

Not really sure if this is a limitation or bug. All lsp related commands would run fine without issues, but after running LspRestart or LspStop + LspStart, fzf-lua can no longer detected the lsp client and will raise the message `[Fzf-lua] LSP: no client attached`.

OS: Windows WSL2, MacOS

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3

Thanks,
Kevin

**Comment by ibhagwan** [comment]
Good catch, should be working now

https://github.com/ibhagwan/fzf-lua/commit/7025700c667d71c6f54f9b7c2115cb9e30749dbd

**Comment by ibhagwan** [comment]
Ty for the update!
