### ISSUE TITLE
FZF files slow  to load on large code bases

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#178]
Hey once again.

I use fzf-lua for kernel development. My typical setup is running a VM and using ssh-fs to mount the vm's kernel source code on my machine so I can have access to my normal editor and plugins. 

I understand ssh-fs can be problematic, but the issue I'm facing seems to only be within fzf-lua. 

The issue is a long wait time for 'files' command, which does not appear directly when I run fzf. 

https://user-images.githubusercontent.com/5642902/136702623-50a4fc37-9d36-4eac-aff0-f48140da31d3.mp4

I attach a screencap where I show the difference in fzf-lua files and running fzf alone.

**Comment by ibhagwan** [comment]
Fzf-lua doesn’t wait for the `fd` or `find` command to finish, it runs asynchronously and should start displaying results as soon as they appear in the output.

It appears as though the command takes time to display the initial result, below is the default command, perhaps one of the flags is causing the delay, run this in the shell (without nvim or fzf) and see if you get the same delay:

```sh
fd --color never --type f --hidden --follow --exclude .git --exclude node_modules --exclude '*.pyc'
```

If the above has a delay but fzf doesn’t we can find out what command is your default by looking inside `$FZF_DEFAULT_COMMAND`, when you find what command runs fast enough add `fd_opts` under `setup({ files  = { … } })` to match the “good” command and you’ll be good to go.

**Comment by ldelossa** [comment]
@ibhagwan running:
`fd --color never --type f --hidden --follow --exclude .git --exclude node_modules --exclude '*.pyc'` 

produced no delay. 

I don't seem to be setting that env variable to something else either:

```
~/git/dotfiles master*
  ag --hidden FZF_DEFAULT_COMMAND
```
produces no output.

**Comment by ldelossa** [comment]
@ibhagwan okay the `git rev-parse --show-toplevel` produces no delay.

you're correct if I jump to "../" and run fzf files, its lag free once again. So sounds like your suspicions about .git folder is promising.

**Comment by ibhagwan** [comment]
> @ibhagwan okay the `git rev-parse --show-toplevel` produces no delay.
> 
> you're correct if I jump to "../" and run fzf files, its lag free once again. So sounds like your suspicions about .git folder is promising.

Then it must be the `git status -s` to get the icons, that’s why I mentioned to try with `git_icons = false`, did you try that?

**Comment by ldelossa** [comment]
yup, that fixed it. Thanks again! I'll disable this from here on.
