### ISSUE TITLE
Add GitFiles?

### ISSUE THREAD

**Issue by sQVe** [ibhagwan/fzf-lua#18]
👋

First I'd like to thank you for all the time put into this. Looks amazing so far!

One thing, that I use commonly, which is missing from the TODO is the `GitFiles?` command. It gives you a `git status` list so you easily can go to modified files etc.

**Comment by ibhagwan** [comment]
It was implemented on release, did you try the below?

```lua
:lua require('fzf-lua').git_files()
```

**Comment by ibhagwan** [comment]
Btw, if you don't like the output and would like a different set of files, set the `cmd` variable to whatever suits your needs, for example to view only modified files change your mapping to:

```lua
:lua require('fzf-lua').git_files({ cmd = "git ls-files --modified" })
```

**Comment by sQVe** [comment]
> It was implemented on release, did you try the below?
> 
> ```lua
> :lua require('fzf-lua').git_files()
> ```

Yes. But that is not the same thing. In `fzf-vim` there is `GitFiles` and `GitFiles?`. The first gives you all files that is tracked by Git whereas the second gives you a list of modified and untracked files.

**Comment by sQVe** [comment]
See https://github.com/junegunn/fzf.vim/issues/129#issuecomment-326644618.

**Comment by ibhagwan** [comment]
> Yes. But that is not the same thing. In `fzf-vim` there is `GitFiles` and `GitFiles?`. The first gives you all files that is tracked by Git whereas the second gives you a list of modified and untracked files.

This should give you the output you want:
```lua
:lua require('fzf-lua').git_files({ cmd = "git ls-files --exclude-standard --cached --others" })
```
Just create a mapping for it or another lua function in your config calling `git_files()` with the above parameters.

**Comment by sQVe** [comment]
That would exclude the information about the status of the individual files though, right?

**Comment by gegoune** [comment]
It will show git statuses if that's what you are asking, just try it.

**Comment by ibhagwan** [comment]
> That would exclude the information about the status of the individual files though, right?

Nope, if you'd like to exclude the status you need to also turn off `git_icons`:

```lua
:lua require('fzf-lua').git_files({ cmd = "git ls-files --modified --others", git_icons = false })
```

**Comment by sQVe** [comment]
Ah, now I get it. I'll try it out as soon as I'm at my computer. Cheers! 🍻

**Comment by ibhagwan** [comment]
> Ah, now I get it. I'll try it out as soon as I'm at my computer. Cheers! beers

Great, I'll close the issue then, feel free to reopen it if this isn't what you wanted or you have any other questions.

**Comment by ibhagwan** [comment]
FYI, latest commit has this functionality as a builtin `git_status`, using `cmd = "git status -s"` which you can control in `git.status.cmd` with `git diff --color` as previewer which you can control at `previewers.git_diff.cmd` or send directly as a function argument with

```lua
require'fzf-lua`.git_status({ cmd = ... })
```
