### ISSUE TITLE
Difficulty writing custom extension with preview window

### ISSUE THREAD

**Issue by jebaum** [ibhagwan/fzf-lua#184]
I'm trying to port the last of my custom fzf.vim stuff over to fzf-lua and couldn't get preview windows to work. I read through #57 and am not sure what I'm missing, wondering if this might be a rarely hit bug or if I'm doing something wrong.

I'm trying to create a provider that will use [xurls](https://github.com/mvdan/xurls) to pick out all the URLs in a file, load them into fzf, and let me pick ones to open. Everything works except for the preview window:

```lua
function openURLs(selected)
  local argstring = ''
  for k,v in ipairs(selected) do
    argstring = argstring .. ' ' .. v
  end
  os.execute("firefox --new-tab" .. argstring)
end

function getURLs()
  require('fzf-lua').grep({
    -- previewer = false,
    raw_cmd = 'xurls ' .. vim.api.nvim_buf_get_name('%'),
    search = ' ',
    search_header = "put header here later",
    preview = "echo {}",
    prompt = 'URLs in file ❯ ',
    actions = {
      ["default"] = openURLs,
    },
  })
end
```

Ideally I'd like to replace that `preview` config with something that will show the part of the buffer where the URL appears. The issue I'm having is that the `preview` option seems to be getting set in FZF in a way that FZF doesn't expect, or maybe is escaped. The error I get when running the above code is this:

`[Fzf-lua] fzf error 2: unknown option: {}`

Is this expected, and I'm just using the option wrong? I tried setting `fzf_opts[--preview]` as well and that didn't seem to be used at all. Also may not be ideal that I'm trying to piggyback on the `grep` function, but I'm not sure what the "right" way to do it is short of duplicating all the window settings and what not that `fzf-lua`sets up and calling the `nvim-fzf` API directly

**Comment by gennaro-tedesco** [comment]
Apologies for commenting on a closed issue: I am trying to replicate a similar example as the above using the builtin preview as per [examples in the wiki](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#neovim-builtin-preview); however, when I try to populate the preview `MyPreviewer:populate_preview_buf` with entries as above, I get an exception in
```lua
function MyPreviewer:populate_preview_buf(entry_str)
  vim.api.nvim_buf_set_lines(self.preview_bufnr, 0, -1, false, {
  ...
``` 
that `self.preview_bufnr` is `nil`: I tried to replicate it with a clean configuration but I still get the same error.

**Comment by ibhagwan** [comment]
This is an old issue, the code has been updated since, you need to use `set_preview_buf`, for example, see the implementation of `man_pages’:
https://github.com/ibhagwan/fzf-lua/blob/455744b9b2d2cce50350647253a69c7bed86b25f/lua/fzf-lua/previewer/builtin.lua#L889-L900

**Comment by gennaro-tedesco** [comment]
Great, it works fine by adding `set_preview_buf`, thank you! However I have noticed that the previewer disappears while scrolling through the entries and needs to be explicitly invoked back (say via F4): is this maybe related to `actions.resume` in some way or should it work fine (and maybe I am making a mistake somewhere)?

**Comment by ibhagwan** [comment]
> Great, it works fine by adding `set_preview_buf`, thank you! However I have noticed that the previewer disappears while scrolling through the entries and needs to be explicitly invoked back (say via F4): is this maybe related to `actions.resume` in some way or should it work fine (and maybe I am making a mistake somewhere)?

I don’t see how `resume` is related, you mean it disappears when you scroll entries or when you try to scroll the preview window? Neither should happen, link or post your code and I’ll take a look, the easiest way is just to copy the `man_pages` preview code (or any other previewer) and adjust it to your needs.

**Comment by gennaro-tedesco** [comment]
I am using the same code from the wiki, namely
```lua
local builtin = require("fzf-lua.previewer.builtin")
local MyPreviewer = builtin.base:extend()

function MyPreviewer:new(o, opts, fzf_win)
	MyPreviewer.super.new(self, o, opts, fzf_win)
	setmetatable(self, MyPreviewer)
	return self
end

function MyPreviewer:populate_preview_buf(entry_str)
	local tmpbuf = self:get_tmp_buffer()
	vim.api.nvim_buf_set_lines(tmpbuf, 0, -1, false, {
		string.format("SELECTED FILE: %s", entry_str),
	})
	self:set_preview_buf(tmpbuf)
	self.win:update_scrollbar()
end

-- Disable line numbering and word wrap
function MyPreviewer:gen_winopts()
	local new_winopts = {
		wrap = false,
		number = false,
	}
	return vim.tbl_extend("force", self.winopts, new_winopts)
end
```
(plus the addition of `set_preview_buf` as suggested).  I see the behaviour shown in the screenshot below


https://user-images.githubusercontent.com/15387611/211368167-ff54c0f0-870f-4f29-aad5-20641132c75f.mov

P. S. If you prefer I can open a new issue to avoid polluting this one (unless it's trivial).

**Comment by ibhagwan** [comment]
@gennaro-tedesco, this might be related to #604, seems I introduced a bug with this commit: https://github.com/ibhagwan/fzf-lua/commit/2ef7fe0d00234e1744010d9c1afe1c4492a242af

**Comment by ibhagwan** [comment]
@gennaro-tedesco, can you try with the latest commit (https://github.com/ibhagwan/fzf-lua/commit/e337b533c32fbc2533309bb94ee146b98da271fe), if it still doesn't work open a new issue and we'll handle it there.

**Comment by gennaro-tedesco** [comment]
I'm again referring to this issue as all-things-inbuilt-previewer :). I want to pass an external option to 
```lua
function MyPreviewer:populate_preview_buf(entry_str)
```
(think of it as a user configuration) but I don't understand where in the constructor such option must be initialised (I presume this is more or a lua object oriented question than plugin specific). I have tried defining the class method as
```lua
function MyPreviewer:populate_preview_buf(entry_str, config)
```
and then invoking it as
```lua
fzf.files({
    ...
    previewer = session_previewer(user_config),
    ...
```
but  this gives an exception of `win` option being `nil`. I suppose one may also pass the external parameters as option to the fzf picker altogether, but I haven't found a way :/.

**Comment by ibhagwan** [comment]
You can pass the user config as any other fzf-lua option and then access the the options under `self.opts`, for example if you run `fzf_lua.files({ cwd = … })`, you can find the value with `self.opts.cwd`.
