### ISSUE TITLE
Checking out new branch

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/fzf-lua#190]
I noticed that I was getting an error of `git "switch" is not a command` when trying to change branches. `git checkout` under `actions.lua` is used for checking out specific commits. Is there a different way of checking out branches? I changed `local cmd = path.git_cwd("git switch ", opts.cwd)` on line `275` to `local cmd = path.git_cwd("git checkout ", opts.cwd)` and I am able to switch between branches. Am I missing something about "git switch"?

**Comment by ibhagwan** [comment]
Probably a version issue, what your git ver? Probably doesn’t have [`git-switch`](https://git-scm.com/docs/git-switch/2.23.0)

**Comment by hqkhan** [comment]
Oh, that makes sense. My git version is `2.17.1`. I'll update my git version.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a49e26c2f0b995b375979130aaecab6413a6dd1e this should take care of this regardless.
