### ISSUE TITLE
[ Feature Request ] Support Octo

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#193]
Octo has an inflight PR which decouples its usage of only telescope. 

The PR stubs out the necessary methods an "fzf-lua" provider would need to implement:

https://github.com/pwntester/octo.nvim/blob/f18d610e74eef1a430c4953cad0db9e6fb4fbc21/lua/octo/pickers/fzf-lua/provider.lua

Are you interested in defining these methods?

**Comment by ibhagwan** [comment]
Going to close this for now, if someone wants to pick up this task feel free to open.

**Comment by nyngwang** [comment]
> That said, this will require quite a bit of code and troubleshooting/QA, not overly excited about being responsible for code in another plugin.

I like this decision. Please don't couple with too many plugins unless you're sure that the maintainer is as passion as you.

**Comment by ibhagwan** [comment]
FYI, this is now supported, references:
#759
https://github.com/pwntester/octo.nvim/pull/396
https://github.com/pwntester/octo.nvim/pull/404
