### ISSUE TITLE
Keep preview window upon after deleting buffer

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/fzf-lua#196]
When looking at all opened buffers, the buffer closes as soon as I issue the keybinding to `actions.buf_del`. Would it be possible to have the fzf window stay open so I can close multiple buffers and have the window dynamically update per `buf_del` call? I noticed that there is an option for `autoclose` in `core.lua` but I don't think I can change it via my `fzf-lua` config. I could very well be mistaken. Thanks in advance.

**Comment by ibhagwan** [comment]
FYI, the default behavior of `ctrl-x` action in `buffers` will refresh the window instead, you can see in the README the action now points to a table of actions, the seond which is the new global `resume` function:

```lua
    actions = {
        ["default"]       = actions.buf_edit,
        ["ctrl-s"]        = actions.buf_split,
        ["ctrl-v"]        = actions.buf_vsplit,
        ["ctrl-t"]        = actions.buf_tabedit,
        ["ctrl-x"]        = { actions.buf_del, actions.resume },
    },
```

**Comment by nyngwang** [comment]
This is absolutely great! Now I have more points to say NeoVim (with fzf-lua) is better than VSCode!

**Comment by hqkhan** [comment]
Hello @ibhagwan. It's been a while. First of all, thank you for adding `actions.resume` as part of `fzf-lua`. I think it's a great addition. I've been having some issues with closing buffers and I finally managed to at-least reproduce it. 

The problem:

Issuing `actions.buf_del` hotkey when the buffer that is being deleted is numbered `1` causes an error. Currently, the floating window will show "Process exited 0". 

To reproduce:

Launch `nvim`. Open 2 files. You can issue `:buffers` to check which buffer isn't `1` and close the `1` buffer. This causes the error. 

Here is the [line](https://github.com/ibhagwan/fzf-lua/blob/c3b23be371b75a1aa54adfc64a9bc268c29cb2c3/lua/fzf-lua/actions.lua#L244) responsible for the error in `actions.lua`. I was actually still using the custom function you wrote for me [here](https://github.com/ibhagwan/fzf-lua/issues/196#issuecomment-952287384) until I encountered this error. Using the custom function actually got me some traceback error which pointed to line 244 in actions.lua. Otherwise using `actions.resume`, I don't get anything except "Process exited 0". I don't know how to get logs or traceback from nvim plugins. 

Now, onto line 244. Here is the snippet of relevant code:
 
```
if curbuf ~= entry.bufnr or lnum ~= entry.line then
      -- make sure we have valid column
      entry.col = entry.col and entry.col>0 and entry.col or 1
      vim.api.nvim_win_set_cursor(0, {tonumber(entry.line), tonumber(entry.col)-1})
    end
```
I had a question as to why the conditional is NOT `if (curbuf ~= entry.bufnr or lnum ~= entry.line) and vimcmd ~= "bd" then`. Shouldn't there be a check that if a buffer is being deleted, then we shouldn't be changing our cursor anywhere. Line 244 is here because it's an over-arching function that takes care of a bunch of actions related to buffers. I did change the conditional to what I wrote above and it fixed my issue. Now, I'm not sure if what I did was a band-aid to the problem so I wanted to check in with you.

**Comment by ibhagwan** [comment]
Tysm @hqkhan for the fantastic troubleshooting, you're not missing anything, when I oroginally wrote the actions resume didn't exist so that is something I missed.

https://github.com/ibhagwan/fzf-lua/commit/bb73779107c589776740d5f2fed0740b3b25e5f8 - this adds your suggestions and aslo encapsulates the `zz` command as it makes no sense to call it after deleting a buffer.

Ty!

**Comment by hqkhan** [comment]
Awesome! Ty for pushing that in so quickly.
