### ISSUE TITLE
Combine `tabs` and `live_grep`

### ISSUE THREAD

**Issue by alopatindev** [ibhagwan/fzf-lua#198]
Thanks for this awesome plugin!

I'd like to have some kind of universal search: basically `live_grep` that shows matching results from currently open tabs as priority.

Any suggestion how to achieve this behavior? Thanks.

**Comment by ibhagwan** [comment]
Closing this for now, feel free to open this if you need more help.

**Comment by alopatindev** [comment]
Thanks, that helped. Wish we had composable providers (+ outputs deduplication), so any of them could be easily combined together.

If anyone interested — I was able to get behavior close enough to what I was looking for. The solution is based on `tabs`, `lines` and `grep` providers. Additionally I made files search based on `git_files` and `files`.

Both use `tab drop`, which switches to existing tab, if the file is already open.

Limitations: no proper deduplication and can't switch to new unsaved tabs.

[It's here](https://github.com/alopatindev/dotfiles/blob/02e34fd71011f9a717f534f650c1eb2ed01fc4e1/common/home/.config/nvim/lua/fzf-lua-ext.lua). Usage:
```viml
let g:rg_opts = '
  \ --line-number --no-column --no-heading --fixed-strings --smart-case --no-ignore --hidden --follow --color always
  \ --glob "*.{c,C,cfg,conf,config,cpp,css,cxx,ebuild,go,h,hpp,hs,html,ini,j2,jade,java,js,lua,md,php,pl,py,rb,rs,scala,sh,sql,styl}"
  \ --glob "{Dockerfile,.gitignore,README,INSTALL,Makefile,Gemfile}"
  \ --glob "!{.git,build,node_modules,vendor,target}/*" '

nnoremap <F3> :lua relevant_files()<cr>
imap <F3> <esc>:lua relevant_files()<cr>
vmap <F3> <esc>:lua relevant_files()<cr>

nnoremap <F4> :lua relevant_grep()<cr>
imap <F4> <esc>:lua relevant_grep()<cr>
vmap <F4> <esc>:lua relevant_grep()<cr>

lua << EOF
require('fzf-lua-ext')
require('fzf-lua').setup {
  winopts = {
    border = 'none',
    fullscreen = true,
    preview = {
      border = 'noborder',
      wrap = 'wrap',
      scrollbar = false,
      layout = 'vertical',
      title = false,
      vertical = 'up:50%',
    }
  },
  grep = {
    rg_opts = vim.g.rg_opts,
    prompt = '> ',
  },
}
EOF
```

**Comment by ibhagwan** [comment]
Looks great! Good job deciphering the internal code, I didn’t have API in mind when I designed this so the documentation isn’t really there.
