### ISSUE TITLE
Map <Esc> to <C-c>

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#2]
How can I map `<Esc>` to `<C-c>` to exit FZF floating window with ease?

This is code I had working for regular FZF:

```lua
fzf = {                                                                                             
  {                                                                                                 
    "TermOpen",                                                                                     
    "term://*FZF",                                                                                  
    [[lua vim.api.nvim_buf_set_keymap(0, "t", "<Esc>", "<C-c>", { nowait = true, silent = true })]],
  },                                                                                                
},                                                                                                  
```
(Hope you dont mind me showing you the wrapper for autocmd I use, you get the idea what it does.)

I tried to amend `term*`regexp to  match terminal windows opened by your plugin but with no success.

**Comment by ibhagwan** [comment]
I think we should be able to do make it work by doing a local buffer mapping in the window creation event, which saves us an autocmd as the one you describe above.

Add this to your global config options:

```
window_on_create = function()
    vim.cmd("set winhl=Normal:Normal")  -- popup bg to match normal windows
    vim.api.nvim_buf_set_keymap(0, "t", "<Esc>", "<C-c>", { nowait = true, silent = true })
  end
```

let me know if that works for you and I’ll close the issue then.

**Comment by gegoune** [comment]
Ah, that's very nice and clean. I did change `winhl` so have that callback function in my configuration but didn't think about adding key map there, neat!
