### ISSUE TITLE
Not properly closing floating window sometimes

### ISSUE THREAD

**Issue by sQVe** [ibhagwan/fzf-lua#20]
👋🏼 

I've noted that I sometimes get a empty floating window after either closing or opening a new file with `fzf-lua`. I can replicate it consistently but it works in most cases. The examples uses https://github.com/sQVe/30s when I open it at the root and then run `git_files` to open `src/handler.js`.

https://user-images.githubusercontent.com/2284724/126829936-0a878bce-2d1e-4593-91ee-eaa5970ed87c.mp4

**Comment by ibhagwan** [comment]
> I've noted that I sometimes get a empty floating window after either closing or opening a new file with `fzf-lua`. I can replicate it consistently but it works in most cases. The examples uses https://github.com/sQVe/30s when I open it at the root and then run `git_files` to open `src/handler.js`.

I downloaded your code and tried to reproduce this issue without any luck. I have a few questions that might help me identify the source of the issue more clearly.

>after either closing or opening a new file with `fzf-lua`

What do you mean by closing? how do you close a file with `fzf-lua`? do you mean opening the buffer list and pressing `ctrl-x` to close the buffer?

>I can replicate it consistently

Are there any special circumstances where this issue happens? does it happen only on `git_files` or also with `files`? does it happen only in a specific project? does it happen when you open the buffer list too?

Anything else you can think of that will clue me in on the source of the issue?

**Comment by ibhagwan** [comment]
I did some more digging, if I remove the window close command, I am left with a window like in your case but with a terminated process `[process exited 0]` which perhaps provides a clue that your terminal or fzf doesn't close properly for some reason.

When this happens again can you find out if your `fzf` process is stuck by running `ps-ef | grep fzf`?

Also, can you provide the output of `fzf --version`?

![screenshot-1627089432](https://user-images.githubusercontent.com/59988195/126853569-6ed61e6d-3eee-4388-b52c-20ae082df1d7.png)

**Comment by ibhagwan** [comment]
I suspect the issue might be in [`nvim-fzf`](https://github.com/vijaymarupudi/nvim-fzf), it seems that the call to `vim.cmd("bw!...")` in [fzf.lua line 202](https://github.com/vijaymarupudi/nvim-fzf/blob/master/lua/fzf.lua#L202) is failing to kill the terminal (beats me why).

I applied a potential fix in [my fork of nvim-fzf](https://github.com/ibhagwan/nvim-fzf), would you be able to temporarily replace your `nvim-fzf` plugin with my fork and let me know if it works better for you?

For `packer.nvim`:
```lua
use { 'ibhagwan/fzf-lua',
  requires = {
    'ibhagwan/nvim-fzf',
    'kyazdani42/nvim-web-devicons' }
}
```
For `vim-plug`:
```lua
Plug 'ibhagwan/fzf-lua'
Plug 'ibhagwan/nvim-fzf'
Plug 'kyazdani42/nvim-web-devicons'
```

**Comment by BoogieDog** [comment]
When I have `gleipnir/dashboard-nvim` on my settings I got this issue, so atm I disabled it.
now it works fine

**Comment by ibhagwan** [comment]
> When I have `gleipnir/dashboard-nvim` on my settings I got this issue, so atm I disabled it.
> now it works fine

Thanks for the lead, I'll download it and check why it does that.

**Comment by sQVe** [comment]
> What do you mean by closing? how do you close a file with `fzf-lua`? do you mean opening the buffer list and pressing `ctrl-x` to close the buffer?

I mean clozing `fzf` either by opening a buffer or by <kbd>Escape</kbd>.

**Comment by sQVe** [comment]
@ibhagwan @BoogieDog Closing or removing `drashboard` seems to fix the issue.

**Comment by ibhagwan** [comment]
> @ibhagwan @BoogieDog Closing or removing `drashboard` seems to fix the issue.

Yep I was just able to reproduce this easily by installing `dashboard-nvim`, that's a big step towards fixing this :-)

**Comment by sQVe** [comment]
I'm surprised that this hasn't been reported before as `dashboard` is a widely popular plugin. Maybe it was introduced not long ago?

**Comment by ibhagwan** [comment]
> I'm surprised that this hasn't been reported before as `dashboard` is a widely popular plugin. Maybe it was introduced not long ago?

This plugin is a week old so probably not so many dashboard+fzf-lua users yet

**Comment by ibhagwan** [comment]
Ok, so I'm not really sure what in `dashboard` is causing this weird behavior but adding a forced `wincmd q` to to the term window (which ends the process successfully) solves it.

The fix had to be done in `nvim-fzf`, I created  [`nvim-fzf` PR#16](https://github.com/vijaymarupudi/nvim-fzf/pull/16)  for this fix and other issues but it will have to wait for @vijaymarupudi to approve it.

For now use my fork of [`nvim-fzf`](https://github.com/ibhagwan/nvim-fzf):
```lua
use { 'ibhagwan/fzf-lua',
  requires = {
    'ibhagwan/nvim-fzf',
    'kyazdani42/nvim-web-devicons' }
}
```

Let me know if this fixes your issue and I'll close this issue.

**Comment by sQVe** [comment]
@ibhagwan Just has a moment to test your fork and it does indeed solve my issues. 👍🏼

Closing.
