### ISSUE TITLE
fatal: ambiguous argument '...' Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#200]
The `git_status` seems not to work with a folder name containing some dashes?

__Update__: OK, it's not dashes but spaces of my folder name: UVa Practice.

<img src="https://user-images.githubusercontent.com/24765272/139519119-efc63795-cf9e-4726-b4c6-0182dded6f6f.png" width="500">

**Comment by ibhagwan** [comment]
I don't think it's the dashes, or it wouldn't work on `fzf-lua` itself (contains dashes on my local disk).

This has to be something else, does this work on other folders with no dashes on your system? what's your git version?

**Comment by nyngwang** [comment]
I got the reason, one of my folder names in the file path contains a space!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d5a73bbaf7c08d2ee6fb3cf5e9a640fe88c5e3b4 should fix it

**Comment by heygarrett** [comment]
I'm experiencing this issue on a rename:
![CleanShot 2023-09-02 at 15 44 03](https://github.com/ibhagwan/fzf-lua/assets/1154912/efd5cbae-5a83-42dc-85dd-b9e51416accf)

Should I file a new issue?

**Comment by ibhagwan** [comment]
> I'm experiencing this issue on a rename: ![CleanShot 2023-09-02 at 15 44 03](https://user-images.githubusercontent.com/1154912/265226154-efd5cbae-5a83-42dc-85dd-b9e51416accf.png)
> 
> Should I file a new issue?

What’s your `git --version` @heygarrett?

**Comment by heygarrett** [comment]
```
❯ git --version
git version 2.42.0
```

**Comment by ibhagwan** [comment]
> ❯ git --version
> git version 2.42.0

I think this is related to file icons - can you try to enable it and also try with `mini.sh`?

**Comment by heygarrett** [comment]
Are file icons enabled by default when using `mini.sh`? They appear to be:
![CleanShot 2023-09-02 at 16 47 29](https://github.com/ibhagwan/fzf-lua/assets/1154912/3a7f04bf-d111-4278-bf64-4db9b133649f)

**Comment by heygarrett** [comment]
@ibhagwan You are correct; the issue disappears if I install `nvim-web-devicons` as a dependency.

**Comment by ibhagwan** [comment]
> @ibhagwan You are correct; the issue disappears if I install `nvim-web-devicons` as a dependency in my own config.

@heygarrett, would you mind opening a new issue about this and I’ll fix it there?

**Comment by heygarrett** [comment]
Sure, no problem!

**Comment by heygarrett** [comment]
@ibhagwan https://github.com/ibhagwan/fzf-lua/issues/864 👍

**Comment by nyngwang** [comment]
I think this issue just happened again.

**Comment by ibhagwan** [comment]
> update2: found the solution [by using {file} instead of %s](https://github.com/ibhagwan/fzf-lua/blob/3d526d24436312cf4e05fbd27452ab2d0ef383cc/doc/fzf-lua.txt#L780_L781), thanks for the clear documentation!

@nyngwang, although to made the change (normalized all file placeholders as `{file}`), I left backward compact code to make sure `%s` still works:
https://github.com/ibhagwan/fzf-lua/blob/3d526d24436312cf4e05fbd27452ab2d0ef383cc/lua/fzf-lua/previewer/fzf.lua#L320-L323

I understand you got the solution, I’ll still check what happened there :)

**Comment by ibhagwan** [comment]
@nyngwang, it was my bad, I didn't test the `%s` backward compat, I forgot to assign the format result :)

It's better to use `{file}` but in any event  https://github.com/ibhagwan/fzf-lua/commit/a3e8f0c6a5a802dffc0dc8772c63cd4e3cd8ef07 should fix it.
