### ISSUE TITLE
I have to open two files to make `git_status` runnable?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#201]
As title. When I open a git-tracking project with some files modified but not yet commit, I cannot trigger `git_status`(with my own key-binding) before I open a second file(can be any) of the same project. Any idea?

**Comment by ibhagwan** [comment]
Does the `git_status` window open empty or does the not open at all before you have two files changed?

For me, `git_status` can always open but will open empty when no files are changed, there is nothing in code limiting git status from opening with results or without, if your window doesn’t open at all I suspect it might not be fzf-lua’s fault.

**Comment by nyngwang** [comment]
> Does the `git_status` window open empty or does the not open at all before you have two files changed?
> 
> For me, `git_status` can always open but will open empty when no files are changed, there is nothing in code limiting git status from opening with results or without, if your window doesn’t open at all I suspect it might not be fzf-lua’s fault.

Thanks for your kindly reply.

I understood and expected to see the empty window shown when no file is changed. But I've experienced two situations:

1. It blinks. The empty window was shown and disappeared very quickly.
2. As my OP.

I'm using packer.nvim and these are the settings near to the `config = function() ... end`:

```
use {
  'ibhagwan/fzf-lua',
  requires = {
    'vijaymarupudi/nvim-fzf',
    'kyazdani42/nvim-web-devicons'
  },
  config = function()
    require'fzf-lua'.setup {
      winopts = { -- Only valid when using a float window
        border = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
        height = 0.65,
        width = 0.7,
        row = 0.9,
        col = 200,
        preview = {
          default = 'bat',
          title = false,
          wrap = 'nowrap',
          vertical = 'up:80%',
          layout = 'vertical'
        }
      }
    }
  end
}
```

**Comment by ibhagwan** [comment]
If the window flashes something tells me `git status -s` returns an unexpected result or an error.

While the problem persists, can you run (from inside neovim) `:git status -s` and paste the output here?

**Comment by nyngwang** [comment]
Oh, I'm stupid. I moved these key-mappings of the LSP's `server:setup { ... }` and now everything works. Sorry for the falsy bug-report. That's why I have to open a file to trigger the LSP so these key-mappings will be set.

**Comment by ibhagwan** [comment]
No worries, happens to everyone :)
