### ISSUE TITLE
Scrolling in preview window with the mouse

### ISSUE THREAD

**Issue by RaZ0rr-Two** [ibhagwan/fzf-lua#202]
I am not able to scroll in the preview window. I am using the example configuration provided in the README.

Uncommenting 

```
preview = {
      -- default     = 'bat',           -- override the default previewer?
```
allows me to scroll the preview window in all `:Fzflua files` commands. But for all remaining commands (helptags, lines) the preview window is no interactive. Scrolling there scrolls the buffer that you have opened instead.

( BTW Thank you for this plugin. fzf.vim has been my fav plugin for a long time. Wanted to switch to lua but was reluctant to move to telescope. This is the saviour)

**Comment by ibhagwan** [comment]
The default previewer is a neovim floating window, by uncommenting `bat` you delegate the preview functionality (and the keybind) to `fzf`. Maybe there is an issue with neovim’s `shift` mapping in your case.

- Can you restore the default previewer again and try any of the other default mappings?
- Does `<F4>` toggle the preview hidden? Does `<F2>` toggle full screen? `<F5>/<F6>`?
- While fzf-lua is active with a preview window, press `<C-\><C-n>` to get into normal mode and run:
  + `:tmap <S-down>`, what does the output show?
  + `:lua require'fzf-lua.win'. preview_scroll(1)`, does this scroll the preview down?

**Comment by RaZ0rr-Two** [comment]
This command 

`:tmap <S-down>`

gave the output

`t  <S-Down>    *@<Cmd>lua require('fzf-lua.win').preview_scroll(1)<CR>`

And `:lua require'fzf-lua.win'. preview_scroll(1)` did scroll the preview.

But when I scroll in preview, the buffer behind scrolls

**Comment by ibhagwan** [comment]
> ~`<F4>` is bound to another window manager key~ (Unbounded and working). All other function keys work.
> 
> This command
> 
> `:tmap <S-down>`
> 
> gave the output
> 
> `t <S-Down> *@<Cmd>lua require('fzf-lua.win').preview_scroll(1)<CR>`
> 
> And `:lua require'fzf-lua.win'.preview_scroll(1)` did scroll the preview.
> 
> But when I scroll in preview, the buffer behind scrolls

This is very helpful, so the keybind works but for some reason it scrolls the calling window instead of the preview window.

I’m confused why calling `lua require('fzf-lua.win').preview_scroll(1)` manually while using the bind has a different behavior given that they call the same function, would you be able to try with a [minimal init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua)? This will help us understand if there’s a config issue causing this (another plugin, autocmd, etc).

**Comment by RaZ0rr-Two** [comment]
I tried the minimal lua config.

`nvim -u fzf-min.lua`

But same problem. THere's a difference tho.

I can now (with minimal vim lua) click in preview window and select things. Previously it would close as soon as I clicked on preview window. 

In minimal lua, scrolling actually scrolls the main window instead of preview window even if scrolled in any of those two windows.

In non-minimal it scrolls buffer, acting if preview window is non-existant.

**Comment by ibhagwan** [comment]
> (Its late now maybe look at some day later. Thank you)

Good night :)

Certainly sounds like there is some sort of bug here, what’s your neovim version?

Can you try with the [neovim 0.5.1 appimage](https://github.com/neovim/neovim/releases/download/stable/nvim.appimage)?

> I can now (with minimal vim lua) click in preview window and select things. Previously it would close as soon as I clicked on preview window.

This is probably not fzf-lua related, there are no handlers for mouse at all, I don’t even have mouse enabled in my neovim.


> In minimal lua, scrolling actually scrolls the main window instead of preview window even if scrolled in any of those two windows.
> In non-minimal it scrolls buffer, acting if preview window is non-existant.

Not sure I understand the difference, by “main” window do you mean the fzf window?

Since you mentioned manually calling `:lua require('fzf-lua.win').preview_scroll(1)` works there is another thing we can try, the terminal buffer scroll uses the same method but calls it differently (due to neovim terminal limitations), can you try running `:new | term` and filling it with lines (run `ls -la ~` few times or `cat <big file>`) and then run `:FzfLua buffers` and see if you can scroll the terminal window?

**Comment by RaZ0rr-Two** [comment]
By main window I meant fzf buffer window. 

I didn't get last para. But all others (disabling mouse) scrolls in fzf buffer even when I am scrolling in preview window. 

Is the scrolling working for you?
Can I checkout your config

**Comment by ibhagwan** [comment]
> I didn't get last para. But all others (disabling mouse) scrolls in fzf buffer even when I am scrolling in preview window.

Terminal buffer scroll works a bit differently, I wanted you to test with a terminal buffer, you can start one with `:term` and just fill it with content, then open `:FzfLua buffers` and see if you can preview scroll the terminal buffer.


> Is the scrolling working for you? Can I checkout your config

[My config is here](https://github.com/ibhagwan/nvim-lua) but I’m not sure if that would solve it, for me the minimal init.lua you tried before also works (which doesn’t work for you), so this might be the same case again.

Did you manage to try with  [neovim 0.5.1 appimage](https://github.com/neovim/neovim/releases/download/stable/nvim.appimage)

**Comment by ibhagwan** [comment]
My comment in this commit https://github.com/ibhagwan/fzf-lua/commit/e0ff9e501cd507966aa537f7973b25bb7fd8b874 closed this issue (apparently `fix #<id>` also closes).

Try the latest commit and let me know if the preview scroll works for you?

**Comment by RaZ0rr-Two** [comment]
> 
> Terminal buffer scroll works a bit differently, I wanted you to test with a terminal buffer, you can start one with `:term` and just fill it with content, then open `:FzfLua buffers` and see if you can preview scroll the terminal buffer.
> 
I tried this but there is no output for this `:FzfLua buffers` that allows for scrolling.
> 
> Did you manage to try with [neovim 0.5.1 appimage](https://github.com/neovim/neovim/releases/download/stable/nvim.appimage)
>
 I tried it but same issue. One thing I could confirm is that,

```
  keymap = {

    builtin = {

      ["<S-down>"]    = "preview-page-down",
      ["<S-up>"]      = "preview-page-up",

    },
```

With these on, I can scroll in the preview window using Shift + (Down/Up) arrow keys

**Comment by ibhagwan** [comment]
> With these on, I can scroll in the preview window using Shift + (Down/Up) arrow keys.

That’s how you’re supposed to use the builtin preview scroll to begin with, what were you doing until now?

> Same. Even after updating

I don’t understand, you mentioned you can scroll with `<S-down|up>`, but now you’re saying it is the same, how are you trying to scroll? With the mouse?

**Comment by RaZ0rr-Two** [comment]
> 
> That’s how you’re supposed to use the builtin preview scroll to begin with, what were you doing until now?
> 
> I don’t understand, you mentioned you can scroll with `<S-down|up>`, but now you’re saying it is the same, how are you trying to scroll? With the mouse?

I am sorry for the confusion but I was trying to scroll with the mouse. Not the Shift + arrow keys combo. I was able to use that when using bat as the default previewer so that I thought it would be possible with the built-in previewer as well.

**Comment by ibhagwan** [comment]
Great timing I was just in the process of writing a reply and your post came in :-)

Reading through this whole thread I now understand we had a miscommunication error and what you meant was "unable to scroll **with the mouse**",  I just tried enabling the neovim mouse with `:set mouse=a` and trying to scroll and the behavior is exactly as you mentioned in the OP (and the rest of your replies).

**Unfortunately scrolling the preview with the mouse is not supported, I'll have to explore if that's possible with a temp buffer and what will be the implications for the code for such change.**

**Comment by RaZ0rr-Two** [comment]
No worries, this is not an essential feature. I created this issue thinking it was bug or an issue with my own config and seek help to fix it. But if it's something difficult to implement or even if its simple but time consuming, I rather not have it. Having this plugin maintained like this is way better than having mouse scrolling. Shift + arrow keys scrolling will soon become intuitive for me.

**Comment by ibhagwan** [comment]
> No worries, this is not an essential feature. I created this issue thinking it was bug or an issue with my own config and seek help to fix it. But if it's something difficult to implement or even if its simple but time consuming, I rather not have it. Having this plugin maintained like this is way better than having mouse scrolling. Shift + arrow keys scrolling will soon become intuitive for me.

Let me explore before closing, might be simple to fix :)

**Comment by ibhagwan** [comment]
Turns out fixing this wasn't a big deal and for now it seems to not affect anything else in the code, this does come with a few limitations (for now):

- The window is scroll-able but not click-able (so you can't select contents with the mouse), fixing this requires the cleanup code to be called from the `WinClosed` event as opposed to the `WinLeave` event which does come with some unintended consequences.

- Scrolling works but does not update the `fzf-lua` preview scrollbar, I'm looking into fixing this with the `WinScrolled` event.

**Comment by RaZ0rr-Two** [comment]
Thank you for the quick fix. I'm sorry some time was wasted due to miscommunication. 

> At least we got your mouse scroll to work, update to the latest commit 82cd9c1 and you can try it out!

I haven't tried this update yet, but there was a simple workaround that my dumb brain couldn't figure out earlier.

```

  keymap = {
    builtin = {
      ["<ScrollWheelDown>"]    = "preview-page-down",
      ["<ScrollWheelUp>"]      = "preview-page-up",
    },
```

**Comment by ibhagwan** [comment]
> Thank you for the quick fix. I'm sorry some time was wasted due to miscommunication.
> 
> > At least we got your mouse scroll to work, update to the latest commit [82cd9c1](https://github.com/ibhagwan/fzf-lua/commit/82cd9c15c3e9834d659173effa2e1ffa9f1094c5) and you can try it out!
> 
> I haven't tried this update yet, but there was a simple workaround that my dumb brain couldn't figure out earlier.
> 
> ```
> 
>   keymap = {
>     builtin = {
>       ["<ScrollWheelDown>"]    = "preview-page-down",
>       ["<ScrollWheelUp>"]      = "preview-page-up",
>     },
> ```

I thought about it but I didn't like this solution because this comes at the expense of the main fzf window scroll, with the above mapping you can't use the mouse to scroll the fzf results, it will scroll the preview instead.

Restore these to `Shift` and try the latest update, I guarantee it will work.

**Comment by RaZ0rr-Two** [comment]
Yes, its working great. Can scroll both fzf window and preview window. Can scroll with shift arrow keys as well. All good. Thank you!!
