### ISSUE TITLE
Cannot preview sometimes when using `live_grep()` and `files()`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#204]
As title. The result can be shown correctly in the input-area, but it cannot be previewed.

## My settings

```
      require'fzf-lua'.setup {
        winopts = { -- Only valid when using a float window
          border = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
          height = 0.65,
          width = 0.7,
          row = 0.9,
          col = 200,
          preview = {
            default = 'cat',
            title = false,
            wrap = 'nowrap',
            vertical = 'up:80%',
            layout = 'vertical'
          }
        },
        files = {
          cmd = 'fd -H',
          prompt = ' File $ '
        },
        grep = {
          prompt = ' Word $ ',
          cmd = "rg --vimgrep",
          color_icons = false,
          file_icons = false,
        }
```

## Result

<img src="https://user-images.githubusercontent.com/24765272/140395404-31efa43e-5dc1-4671-9757-fd38a1bc73e8.png" width="600">

<img src="https://user-images.githubusercontent.com/24765272/140395589-2483415c-8354-46c5-b226-1ef4dae3ef3f.png" width="600">

**Comment by ibhagwan** [comment]
I responded to this on #203, it's probably due to differences between POSIX `cat` and GNU `cat`, you can define the arguments by adding this section to your `setup()`:

```lua
require'fzf-lua'.setup {
  previewers = {
    cat = {
      cmd = "cat",
      args = "",
    },
  }
}
```

**Comment by nyngwang** [comment]
> > > Can you try with `winopts.preview.default = 'bat_native'`?
> > 
> > 
> > This one works! Wow!
> 
> Great! I'd still like to solve it for `bat`/`cat`, does this work at all for different contents? can you tell what file contents consistently fails? Maybe we should discuss this under #204?

^Context

**Comment by nyngwang** [comment]
> [...] does this work at all for different contents? [...]

Yes, only that line with URL will fail.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/454b0ba48c89f05ca16023cb34b1ae21c30ff8af fixed now.

I introduced this bug by mistake when fixing #195, my regex was wrong and matched URLs even if they weren't at the start of the line :-)

**Comment by nyngwang** [comment]
Now the same happens when `head` as previewer:

<img src="https://user-images.githubusercontent.com/24765272/140937326-511b3547-2f2a-4fbf-a951-2db7eba870a6.png" width="1100">

my settings:

```
winopts = {
  ...
  preview = {
    default = 'head',
    title = false,
    wrap = 'nowrap',
    vertical = 'up:80%',
    layout = 'vertical'
  }
},
...
previewers = {
  cat = {
    cmd = "cat",
    args = ""
  },
  head = {
    cmd = "head",
    args = ""
  }
}
```

**Comment by ibhagwan** [comment]
Something is wrong here, your result doesn’t contain a line number, because of that it seems that regex that check for `^%a://` matches, what command are you using for `live_grep`? It has to have at least line numbers (preferable column number) too for the preview to know which line to show.

The `rg` results should appear as `<file>:<line>:<col>:<content>`, to do that add `--column --line-number` to your `rg` command.

**Comment by nyngwang** [comment]
I use `cmd = "rg -g '!{.git,node_modules,package-lock.json,yarn.lock,Library,tags}'"` for `grep`

**Comment by ibhagwan** [comment]
Can you add `--column --line-number` to your command and try?

**Comment by nyngwang** [comment]
I tried this one:

```
          cmd = "rg "..
            "-g '!{.git,node_modules,package-lock.json,yarn.lock,Library,tags}' "..
            "--max-filesize 100K ".. 
            "--column "..
            "--line-number ",
```

My current solution is to avoid scrolling through the result list(this makes my mac very hot by the way). Now I type more keywords instead. I will try my best to help later, need to work. 

<img src="https://user-images.githubusercontent.com/24765272/141054322-d469b291-fcb5-48f6-bce4-5ce6c168597a.png" width="500">

**Comment by ibhagwan** [comment]
Does this also happen if you turn off the preview?
Does `:FzfLua grep search=''` work better or does it have the same issue?

**Comment by ibhagwan** [comment]
Can we work on all these previewer issues in #211?

I’m getting confused which issues are still relevant.

**Comment by nyngwang** [comment]
> Can we work on all these previewer issues in #211?
> 
> I’m getting confused which issues are still relevant.

OK.
