### ISSUE TITLE
Tags functionality breaks on code with tab characters

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#206]
Using `:FzfLua tags` and `:FzfLua btags` on code with tab characters present fails and emits an error message.

## Reproduction
1. Create the following file in its own directory:
    ```c
    #define MACRO	1

    int main(void)
    {
        return 0;
    }
    ```
    Note the tab character present after `MACRO` and before `1`.

2. Go to the directory containing the file and generate tags: `ctags -R`

    The following was my result using Universal Ctags:
    ```
    !_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
    !_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
    !_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
    !_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
    !_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
    !_TAG_PROGRAM_URL	https://ctags.io/	/official site/
    !_TAG_PROGRAM_VERSION	0.0.0	//
    MACRO	test.c	/^#define MACRO	/;"	d	file:
    main	test.c	/^int main(void)$/;"	f	typeref:typename:int
    ```
    Note again the tab character immediately after `MACRO`.

3. Open the file in Neovim and run `:FzfLua tags`
4. The resulting pop-up window is not populated and an error message is emitted:
    ```
    Error executing vim.schedule lua callback: ...onfig/nvim/bundle/fzf-lua/lua/fzf-lua/providers/tags.lua:42: attempt to index 
    local 'pattern' (a nil value)
    ```

## Investigation
The error message refers to [line 42](https://github.com/ibhagwan/fzf-lua/blob/78895876c25b3b6c20d4230dfbd8d9fc3ec868dc/lua/fzf-lua/providers/tags.lua#L42) in `tags.lua`.

I believe this issue is due to the splitting of each `tags` line by tab character as performed on [line 73](https://github.com/ibhagwan/fzf-lua/blob/78895876c25b3b6c20d4230dfbd8d9fc3ec868dc/lua/fzf-lua/providers/tags.lua#L73). The `delimiter` is defined as tab earlier on [line 69](https://github.com/ibhagwan/fzf-lua/blob/78895876c25b3b6c20d4230dfbd8d9fc3ec868dc/lua/fzf-lua/providers/tags.lua#L69).

For this example, [fields[3]](https://github.com/ibhagwan/fzf-lua/blob/78895876c25b3b6c20d4230dfbd8d9fc3ec868dc/lua/fzf-lua/providers/tags.lua#L83) will contain `/^#define MACRO` and not include the terminating `/`. This will cause the [text match](https://github.com/ibhagwan/fzf-lua/blob/78895876c25b3b6c20d4230dfbd8d9fc3ec868dc/lua/fzf-lua/providers/tags.lua#L39) that looks for the search patterns to result in `nil`. The following [gsub call](https://github.com/ibhagwan/fzf-lua/blob/78895876c25b3b6c20d4230dfbd8d9fc3ec868dc/lua/fzf-lua/providers/tags.lua#L42) will fail resulting in the error message above.

**Comment by ibhagwan** [comment]
Tysm for the detailed explanation and reproduction steps!

https://github.com/ibhagwan/fzf-lua/commit/c45c06218fb280e63d92d6597fdafc423259eb14 this fixed it.
