### ISSUE TITLE
Tags functionality does not work properly for files with DOS line endings

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#207]
Using `:FzfLua tags` or `:FzfLua btags` on code with DOS line endings may yield results that point to line 1 instead of the actual lines of the tags.

## Reproduction

1. Create the following file named `test.c` in its own directory:
    ```c
    #include <stdio.h>
    
    int main(void)
    {
        return 0;
    }
    ```

2. Make sure the file is using DOS line endings: `:se ff=dos`
3. Save the file, then go to the directory containing the file and generate tags: `ctags -R`

    The following was my result using Universal Ctags:
    ```
    !_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
    !_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
    !_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
    !_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
    !_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
    !_TAG_PROGRAM_URL	https://ctags.io/	/official site/
    !_TAG_PROGRAM_VERSION	0.0.0	//
    main	test.c	/^int main(void)$/;"	f	typeref:typename:int
    ```
    Note the use of `$` at the end of the search pattern.

4. Run `:FzfLua tags`
5. The result shows `main` located at line 1, instead of the correct line 3:
![image](https://user-images.githubusercontent.com/37260523/140584755-9fb4075a-ee98-4710-88bd-08ff3a661b37.png)

## Investigation

For this example, the search pattern for `main` is `^int main(void)$`. I suspect that this is not found because of the ending `)$`. The carriage return found in DOS line endings may not be accounted for by the end of line `$`.

[This portion](https://github.com/ibhagwan/fzf-lua/blob/c45c06218fb280e63d92d6597fdafc423259eb14/lua/fzf-lua/providers/tags.lua#L37-L43) of the search pattern processing seems most relevant. The pattern is not found due to the explanation above and an early return of `line` is performed, which was initially assigned `1`.

**Comment by ibhagwan** [comment]
Great find!

I'm wondering, can this even happen given that this plugin does not work on windows?

**Comment by shyun3** [comment]
I came across this when using WSL and accessing files in the Windows filesystem.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b3add55b4608ffaed27cc7a11c613dce8675b0ac should work now.
