### ISSUE TITLE
Does  `require'fzf-lua'.git_files()` support excluding folders like `node_modules/`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#209]
As title.

**Comment by nyngwang** [comment]
I just found a work-around as shown below. But I think an option `[ ]`-field that I can add some strings into it will be much user-friendly.

```
grep = {
  prompt = 'Word $ ',
  -- WARNING: Run `brew install ripgrep` to install ripgrep.
  cmd = "rg --vimgrep -g '!{.git,node_modules,package-lock.json}'",
  -- ...
}
```

**Comment by ibhagwan** [comment]
There are many different ways you can exclude `node_modules`:

- for `git _files` you can use a `.gitignore` file
- for `files` you can add the exclusion to `fd_opts` (with the `—exclude` flag)
- as you discovered, the way to do this for `grep` is using `rg_opts` (or by modifying `cmd`)

> And this simple fix also increases the performance and coloring issues in my case too.

Obviously using `—vimgrep` and excluding a big folder  is going to be faster and colorless (the default options uses `—color=always`).

> how about this:

For now I don’t want to add a unified way of exclusion as it will require to modify the underlying commands differently each time, some users don’t have `fd` or `rg` so I’d have to adjust for `find` and `grep`, the other solution would be to filter the results inside fzf-lua which will be horrible for performance.

**Comment by nyngwang** [comment]
Say there are 4000+ results after I typed some keywords. The CPU usage goes to 99.7% and nvim frozen after the cursor reached the last result (and passed by many large files).
