### ISSUE TITLE
`files.{fd,find}_opts` is undocumented

### ISSUE THREAD

**Issue by jamesob** [ibhagwan/fzf-lua#213]
These are very useful options (e.g. https://github.com/ibhagwan/fzf-lua/issues/178#issuecomment-939505769) but they are not mentioned in any documentation. 

I'll file a PR adding them if I get time.

**Comment by ibhagwan** [comment]
`rg_opts` does appear in the README customization under `grep.rg_opts`, I can add `fd_opts` in the same manner.

If you wish to PR with a more detailed explanation feel free to do so [for the fzf-lua Wiki](https://github.com/ibhagwan/fzf-lua/wiki).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/cd0cb50717343745b7c5e89c448b372a29521d26

Added `fd_opts` to README in the above commit.
