### ISSUE TITLE
How to open multiple files as buffers instead of listing them in the quicklist?

### ISSUE THREAD

**Issue by ahmedelgabri** [ibhagwan/fzf-lua#214]
How to open multiple files as buffers instead of listing them in the quicklist? I'd like to have the same behaviour as `fzf.vim` which will open the files directly instead of the `fzf-lua` behavior which lists them in a quicklist.

**Comment by ibhagwan** [comment]
The default action points to `actions.file_edit_or_qf`, you need to set it to `file_edit` instead:

```lua
    files = {
      actions = {
        ["default"] = require("fzf-lua.actions").file_edit,
      …
      }
    }
```

**Comment by ahmedelgabri** [comment]
> The default action points to `actions.file_edit_or_qf`, you need to set it to `file_edit` instead:

I guess the `README.md` needs to be updated then, because it says `file_edit` is the default & that's why I opened the issue :) https://github.com/ibhagwan/fzf-lua#customization

Thanks!

**Comment by ibhagwan** [comment]
> > The default action points to `actions.file_edit_or_qf`, you need to set it to `file_edit` instead:
> 
> I guess the `README.md` needs to be updated then, because it says `file_edit` is the default & that's why I opened the issue :) https://github.com/ibhagwan/fzf-lua#customization
> 
> Thanks!

Yap I noticed that too when I was writing my reply to you, I’ll update it next commit :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/767b8f73c7eea25bb1a79ee94b1f2ab1082aaf9d fixed, ty @ahmedelgabri!
