### ISSUE TITLE
Provide way to control the buffer settings of previewer..

### ISSUE THREAD

**Issue by megalithic** [ibhagwan/fzf-lua#215]
@ibhagwan -- i can't say enough how awesome this plugin is and continues to be!

i'm tracking down some performance issues with the previewer (i'm using bat, and have disabled some of the slower features -- border/scrollbar/title that seems to have afflicted performance for me) and noticed the previewer is using `cursorlineopts="both"` as a default; I'd love to be able to alter this to just `number` as it tends to be more performant for me (I typically have to shell into a dev environment and work on code that way, so there's already a slight performance hit for me). 

https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/previewer/builtin.lua#L49-L62

Thanks!

**Comment by ibhagwan** [comment]
> @ibhagwan -- i can't say enough how awesome this plugin is and continues to be!

ty!

> i'm using bat

These options don’t apply to the `bat` previewer, both `bat`/`bat_native` previewers stream the bat output into fzf and use fzf’s previewer (as opposed to the “builtin” previewer which uses a neovim buffer)

> the previewer is using `cursorlineopts="both"` as a default

If I recall correctly, it used to be `number` but it was set to `both` as part of a user’s PR and I can’t recall what was the issue ATM.

> I'd love to be able to alter this to just `number`

Shouldn’t be hard to do, I’ll add this next commit and update this thread.

That said, if you’re looking for top speed make sure you are actually using the `bat` previewer (the line of code you linked is only run if you’re using the neovim builtin previewer), more than a month ago I moved the default previewer setting under `winopts.preview.default` (see [README#customization](https://github.com/ibhagwan/fzf-lua/blob/main/README.md))- perhaps you’re still using the old location and the setting doesn’t apply?

Also, check out [How do I get maximum performance out of fzf-lua?](https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-get-maximum-performance-out-of-fzf-lua)

**Comment by ibhagwan** [comment]
I see https://github.com/megalithic/dotfiles/commit/5652afde082e6a75812e851cf4aae98ef630c42c `bat_native` solved it for you :-)

Do you still find this change needed or can we close this for now?

**Comment by megalithic** [comment]
Thanks again!

**Comment by ibhagwan** [comment]
FYI, the solution to #218 takes care of the original request as well.
