### ISSUE TITLE
documentation fix: grep rg_opts -g remove *

### ISSUE THREAD

**Issue by ruirayxue** [ibhagwan/fzf-lua#216]
https://github.com/ibhagwan/fzf-lua/blob/767b8f73c7eea25bb1a79ee94b1f2ab1082aaf9d/doc/fzf-lua.txt#L487
https://github.com/ibhagwan/fzf-lua/blob/767b8f73c7eea25bb1a79ee94b1f2ab1082aaf9d/README.md#L453

should be `"--color=always --smart-case -g '!{.git,node_modules}/'",`, otherwise it won't exclude those folder correctly.

**Comment by ibhagwan** [comment]
Ty!

I probably should just add this to the FAQ and match the option with what is the default in:
https://github.com/ibhagwan/fzf-lua/blob/767b8f73c7eea25bb1a79ee94b1f2ab1082aaf9d/lua/fzf-lua/config.lua#L236-L237

And add a similar explanation to `fd|find_opts` (under `files`).

**Comment by ruirayxue** [comment]
np. 

I personally open help page more often than the source code, as I can get fuzzy match help_tags yet no straightforward way for me to reach source code. IIRC in Telescope I could lands related source code directly by `C-v` `Builtin` fuzzy search. Tho I'm not sure if this it worth your effort.

**Comment by ibhagwan** [comment]
I’m with you on that, I’d rather stay in the neovim ecosystem if possible, I also use `help_tags` when applicable but sometimes it is not enough, the way I went about it is created this small specialization which is mapped to `<leader>ep` (“edit plugins”), this way I can search the source code of my installed plugins:

```lua
function M.installed_plugins(opts)
  if not opts then opts = {} end
  opts.prompt = 'Plugins❯ '
  opts.cwd = vim.fn.stdpath "data" .. "/site/pack/packer/"
  fzf_lua.files(opts)
end
```

 > taken from https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/fzf-lua/init.lua#L237

**Comment by ruirayxue** [comment]
Awesome tip thanks! Will check out your dotfiles see what else I can steal :)

**Comment by ibhagwan** [comment]
> Awesome tip thanks! Will check out your dotfiles see what else I can steal :)

My favorite pastime is browsing neovim dotfiles :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5609b3d08b784b307f1e9c8f9706d6153d54cc38 addresses this.

Also added to the Wiki: [How do I exclude paths (e.g. 'node_modules')?](https://github.com/ibhagwan/fzf-lua/wiki#exclude-paths)
