### ISSUE TITLE
[Question]: would this plugin support windows in the future

### ISSUE THREAD

**Issue by younger-1** [ibhagwan/fzf-lua#217]
As the title.

**Comment by ibhagwan** [comment]
I’m not ruling this out but it require a decent amount of work and adjustments for design decisions that didn’t take this into account (shell commands, piping, using UNIX utilities, etc) all which require access to a windows machine which I don’t own.

Adding support blindly wouldn’t work so it would have to be a PR from a user who owns windows and is determined to make this work, if someone wants to do that I’d be more than happy to help and provide support  but it will have to be “driven” by someone other than myself.

In the meantime windows users can use [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) which a few users reported works perfectly with.

**Comment by younger-1** [comment]
Thank you for your reply!
