### ISSUE TITLE
[Feature request] Expose Preview:gen_winopts() items

### ISSUE THREAD

**Issue by lcrockett** [ibhagwan/fzf-lua#218]
Cheers on this excellent plugin ! The live grep functionality works wonders in foreign codebases.

I noticed that parts of the builtin previewer do not seem to be configurable (unless I missed it in the documentation). For instance, i'd like to control line numbers in the builtin previewer, as in not show them. It looks like [here](https://github.com/ibhagwan/fzf-lua/blob/e5948a8c50330f7003a59415d0af9729e55d898b/lua/fzf-lua/previewer/builtin.lua#L96) these options are set as static values.

Are they exposed in any way ? And if not, can they be exposed so users can override defaults ?

**Comment by ibhagwan** [comment]
They aren’t exposed yet, shouldn’t be a problem to expose these options, I’ll add it next commit.

**Comment by ibhagwan** [comment]
Under [customization](https://github.com/ibhagwan/fzf-lua#customization) take a look at `winopts.preview.winopts`, you can override or add any options you want to the preview win, defaults are:
```lua
...
      winopts = {
        number            = true,
        relativenumber    = false,
        cursorline        = true,
        cursorlineopt     = 'both',
        cursorcolumn      = false,
        signcolumn        = 'no',
        list              = false,
        foldenable        = false,
        foldmethod        = 'manual',
      },
...
```

**Comment by lcrockett** [comment]
That was lightning fast, cheers mate. This works like a charmadillo !

**Comment by ibhagwan** [comment]
> That was lightning fast, cheers mate. This works like a charmadillo !

Haven’t heard this one before, cheers :)
