### ISSUE TITLE
Tags may not jump to correct location for constructs with similar prefixes

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#219]
If a tag's search pattern without the ending `$` can yield multiple results, `:FzfLua tags` or `:FzfLua btags` may not jump to the correct location.

## Reproduction

1. Create the following file named `test.c` in its own directory:
```c
#include <stdio.h>

static void print(void);

int main()
{
    print();
}

static void print(void)
{
    printf("Hello, world!\n");
}
```

2. Save the file, then go to the containing directory and generate tags: `ctags -R`

    The following was my result using Universal Ctags:
    ```
    !_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
    !_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
    !_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
    !_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
    !_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
    !_TAG_PROGRAM_URL	https://ctags.io/	/official site/
    !_TAG_PROGRAM_VERSION	0.0.0	//
    main	test.c	/^int main()$/;"	f	typeref:typename:int
    print	test.c	/^static void print(void)$/;"	f	typeref:typename:void	file:
    ```

3. Run `:FzfLua tags` and highlight the tag for the `print()` function. Note how the line number is recorded as 3:
![tempsnip](https://user-images.githubusercontent.com/37260523/142709985-61fc525f-118c-4ae1-877f-cdc37aee3af5.png)

4. Jump to the tag and confirm the cursor is moved to line 3.

## Investigation

The previous case should have jumped to line 10, not the function prototype on line 3. Note how the search pattern for `print` does not include a `;` before the `$`: `/^static void print(void)$/`. This is clearly supposed to match the function definition. By default, tags are not generated for function prototypes in C files.

I believe this is most likely due to the solution implemented for issue #207, committed in b3add55. Since the change effectively removed the `$` in tags, the result of the pattern search yields line 3 in this case instead of the correct line 10.

A fix would most likely have to correctly handle the `$` and all of the surrounding complications.

## Alternative proposal

If you don't want to deal with the `$`, search patterns can be sidestepped entirely by using the `-n` option with `ctags`. Here is my result on the previous example:
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	//
main	test.c	5;"	f	typeref:typename:int
print	test.c	10;"	f	typeref:typename:void	file:
```

Of course, adding support for this mode does not actually fix this issue. But it would at least allow users to configure things on their end to get the correct behavior.

**Comment by ibhagwan** [comment]
You’re correct with your analysis of the issue. I also don’t believe the `-n` is a proper solution, IMO the power of tags comes from being able to search for the pattern so you can still find it even if the code changes, if you rely on the line number and don’t constantly regenerate the tags you’ll end up with incorrect line numbers.

Both this and the `dos` newline issue in #207 are edge cases, the issue with handling `$` properly is that I’d have to query each file one more time and handle it differently for each file format, not very elegant…

The optional solution would be to revert the fix from #207 and instead find an `rg` option that would be able to match $ for newline with `dos` format, alternatively I can ignore the line searches altogether and  do what Telescope does which is search for the pattern within the neovim buffer, the issue with the latter is that I cannot do that with the native previewers (`bat`, `cat`, etc) so the functionality wouldn’t be consistent between previewers.

Do you find yourself working with `dos` files a lot or was it just some test you did for #207?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a45ea4dec51fbb03349c6fb74401579ed3bdf910 - this implements a test file format (with cache), in the case of 'fileformat=dos' it replaces the rg search pattern `$` with `\r$`.

It should work accurately now with both 'unix' and 'dos'.

**Comment by shyun3** [comment]
Looks like you got to this already but I'll respond to some of your previous comments.

There is a `--crlf` option for `rg` that seems relevant. The man page even mentions that an equivalent translation for `$` could be `(?:\r??$)`.

Sometimes I work on projects that are meant to be built on Windows but I still prefer using Neovim.

**Comment by ibhagwan** [comment]
> There is a `--crlf` option for `rg` that seems relevant. The man page even mentions that an equivalent translation for `$` could be `(?:\r??$)`.

Interesting, I just read the `rg` man entry for `--crlf`, I'm now wondering if my replacement of `$ -> \r$` is enough or is it better if I remove that and just add `--crlf` instead, the issue is the latter wouldn't work if the user doesn't have `rg` installed (the command defaults to `grep`).

Since I'm also using the perl regex engine with `grep` I could change the pattern to `\r??$` (should work for both `rg` and `grep`) but I think `\r$` should work for most cases, I don't understand why there would be optional 2 characters between the `\r` and the `$`.

**Comment by shyun3** [comment]
According to the [Rust regex syntax](https://docs.rs/regex/1.5.4/regex/#repetitions) (which is what `rg` uses), `??` means zero or one in an ungreedy fashion where a single `?` is greedy. I think Perl syntax also supports this.

**Comment by ibhagwan** [comment]
Oh I see, so it would match both `$` and `\r$`, so theoretically I could even remove the file format check and use this regex instead for both `unix` and `dos`. 

I’ll test this when I get a chance.

**Comment by ibhagwan** [comment]
Ty @shyun3, the `\r??$` seems to work great for all formats for both `rg` and `grep`!

The latest commit https://github.com/ibhagwan/fzf-lua/commit/2f97f24c16d3f2701072c5da43a400bafdc7a830 makes the proper modifiations.

**Comment by shyun3** [comment]
It looks like the latest codebase has a regression in this behavior. @ibhagwan could you take a look at this again?

**Comment by ibhagwan** [comment]
The latest changes use `vim.search` to find the patterns so the previous regex fixes don’t apply (unless you go go back to `bat` previewer), I’ll revisit this again.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5396fa198f4cbe31cb2763f36b6aa2cce9b86953 fixed.
