### ISSUE TITLE
Weird sporadic error when attempting to use either live_grep or file search

### ISSUE THREAD

**Issue by haze** [ibhagwan/fzf-lua#222]
<img width="1528" alt="CleanShot 2021-11-21 at 16 18 27@2x" src="https://user-images.githubusercontent.com/15584994/142779260-9bd8e88c-1499-4f9b-b7e8-9fc93ccc8b5f.png">

fzf-lua seems to work fine initially for a couple of minutes, but after around 5-10 or so of work, this error randomly pops up and I'm forced to restart vim to continue using the plugin. I have no idea where to begin looking to see what the issue could be.

I think it's worth noting that after I clear the above error message, this is left in the buffers place:

<img width="1473" alt="CleanShot 2021-11-21 at 16 19 44@2x" src="https://user-images.githubusercontent.com/15584994/142779292-bd44ae9f-c478-42a0-9f33-b1a61f6bccc4.png">

**Comment by ibhagwan** [comment]
Interesting issue… it appears that the `mkfifo` which is used to create the output pipe is failing, consequently failing the pipe open command.

https://github.com/ibhagwan/fzf-lua/blob/63ed48baf98ebfd5b03a40cce9a606bc61c47ad1/lua/fzf-lua/fzf.lua#L50

If my analysis is correct, to understand why `mkfifo` is failing I can add code which would print the error when that happens.

Before we go down this route:

- Although random, does this happen consistently every time after 5-10 mins?
- What is your `mkfifo` and `neovim` versions?
- Can you try with the [official 0.5.1 appimage](https://github.com/neovim/neovim/releases/download/v0.5.1/nvim.appimage)?
- Can you try with [minimal init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua)?

**Comment by haze** [comment]
> Although random, does this happen consistently every time after 5-10 mins?
I never time it this precisely, but it's after some amount of work.

> What is your mkfifo and neovim versions?
Standard macOS mkfifo (`/usr/bin/mkfifo`) and `NVIM v0.6.0-dev` built from `neovim-devel` on macports (sorry I don't know which revision this is, I usually build it myself but I just switched laptops and needed an editor fast)

> Can you try with the official 0.5.1 appimage?
Just installed 0.5.1 and will let you know if I experience the same issue

> Can you try with minima init.lua
Here is my current config:
```lua
require'fzf-lua'.setup {
  winopts = {
    split = 'belowright new',
    win_row = 1,
  },
  preview_border = 'noborder',
  preview_vertical = 'down:80%',
  default_previewer = 'bat',
  files = {
    git_icons = false,
    file_icons = false,
    color_icons = false,
  },
  lsp = {
    git_icons = false,
    file_icons = false,
    color_icons = false,
  },
}
```

I will try using the minimal init.lua and report back

**Comment by ibhagwan** [comment]
> Standard macOS mkfifo (/usr/bin/mkfifo) and NVIM v0.6.0-dev built from neovim-devel on macports (sorry I don't know which revision this is, I usually build it myself but I just switched laptops and needed an editor fast)

You can run `:version` inside neovim to get your exact version and build.

I'm also investigating what could cause this, let me know what you come up with.

**Comment by ibhagwan** [comment]
@haze, can you try the latest commit https://github.com/ibhagwan/fzf-lua/commit/8d87ef366e15e0ca567960d5f26ab9c4138fadce?

I have a strong suspection I found the issue, turns out that neovim doesn't guarantee the existence of the neovim temporary directory returned from `tempname()` which in turn causes `mkfifo` to fail.

If you're interested you can read about it below
https://github.com/neovim/neovim/issues/1432
https://github.com/neovim/neovim/pull/11284

The latest commit replaces `tempname` with a function that verifies the existence of the parent directory and on faliure reverts to using `os.tmpname()` instead.

Give it a a good run and let me know if this solves the issue for you?

**Comment by haze** [comment]
I've downloaded the update and will report back on whether or not this fixes my issue :)

**Comment by ibhagwan** [comment]
I'm assuming no news means good news, if you still need more help feel free to reopen the issue.

**Comment by haze** [comment]
@ibhagwan I haven't programmed in a while, but it looks fixed on my end. Sorry about the ghost, and good work. Thank you :D

**Comment by ibhagwan** [comment]
Happy to hear this was solved :-)
