### ISSUE TITLE
It seems that `lsp_references` will not find usage in all subfolders

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#223]
The expected behaviour is this: I want to find the line:

```
ac->init_machine = kvm_init;
```
<img src="https://user-images.githubusercontent.com/24765272/143239852-c7e3d8f4-1c7e-48cd-9cda-5458244ce69a.png" width="500">

But if I keep calling `lsp_references` many times into this file, then try to call `lsp_references` again on  
the `ac->init_machine` of the line

```
ret = acc->init_machine(ms);
```

The result doesn't show the `kvm_init`:

<img src="https://user-images.githubusercontent.com/24765272/143241735-68ef5954-edeb-4e6a-a3f9-29d03daa656f.png" width="500">

----

(The source code is from QEMU.)

**Comment by nyngwang** [comment]
Update: after some re-try if I directly open the folder of the file `accel-softmmu.c` and call the `lsp_references` I still cannot find the reference to the line `ac->init_machine = kvm_init;`, which lies in the subfolder, `kvm/`, of the folder containing `accel-softmmu.c`.

**Comment by nyngwang** [comment]
Update: after some retries if I use `live_grep_native`, the `ac->init_machine = kvm_init;` will be listed in the search results.

**Comment by ibhagwan** [comment]
Most likely this is an issue related to the LSP server / configuration, can you check the references using:
```lua
: lua vim.lsp.buf.references()
```
If you’re getting the exact same results the issue is not within fzf-lua.

**Comment by nyngwang** [comment]
> If you’re getting the exact same results the issue is not within fzf-lua.

@ibhagwan Just confirmed it that the results are the same. Sorry for my false alarm.
