### ISSUE TITLE
Feature request: support coc.nvim

### ISSUE THREAD

**Issue by jannes** [ibhagwan/fzf-lua#224]
I would love to be able to get the same functionality already implemented for native LSP, but for coc.nvim. Would you be fine to have this included as part of this plugin?

**Comment by ibhagwan** [comment]
Hi @jannes, at the moment I have no plans on putting in the time to support `coc.nvim`. If anyone wants to invest the time in this I’m more than willing to guide them through and make the necessary API changes should those be required.

Personally, I prefer the neovim LSP, it doesn’t require nodejs, the configuration is pretty simple (IMO) and it feels more natural inside neovim. At the speed it’s pickup up now (both in development and adoption) I don’t see any reason to use anything else.

Any specific reason you prefer `coc.nvim`?

**Comment by jannes** [comment]
Hey @ibhagwan, thanks for the swift reaction! I completely understand your point, I do think native LSP is going to be what the ecosystem settles on eventually. I've been using other editors with Vim bindings for a while and just coming back to Neovim now to try out new features (LSP & Treesitter). I feel like currently native LSP is still a bit immature and the required plugins to make everything work (including autocomplete) are more in flux, so I settled on using coc.nvim for now.

**Comment by ibhagwan** [comment]
> Hey @ibhagwan, thanks for the swift reaction! I completely understand your point, I do think native LSP is going to be what the ecosystem settles on eventually. I've been using other editors with Vim bindings for a while and just coming back to Neovim now to try out new features (LSP & Treesitter). I feel like currently native LSP is still a bit immature and the required plugins to make everything work (e.g autocomplete, auto-update LSP servers) are more in flux, so I settled on using coc.nvim for now.

I agree with you, it does require a bit of setup but if you are willing to go the extra mile and invest some time in your configuration it does feel like a full on IDE, granted, this is a bit different than the “minimal plugin” approach but it’s totally worth it IMO and is not as “bloaty” as this might sound.

Feel free to give [my lua config](https://github.com/ibhagwan/nvim-lua) a whirl, has LSP with auto complete and auto install setup (using `nvim-cmp` and `nvim-lsp-install`), works really well and a joy to use while still keeping true to minimalis and default binds so you’re not “out of the water” when you don’t have your plugin setup.

**Comment by nyngwang** [comment]
@jannes I would recommend using native LSP since you said: "... just coming back to __Neovim__". The reason is simple: Neovim supports __Lua__ natively, and it would be a pity if you don't take advantage of it. With Lua, you can:

- [Write your own script ergonomically](https://github.com/tjdevries/astronauta.nvim)
- Embrace tons of [state-of-the-art plugins](https://github.com/rockerBOO/awesome-neovim), just like this one: fzf-lua :)

While Coc.nvim is great. it's too heavy in my honest opinion. By using it you have to have every LSP-related feature to depend on it. And the author is not very kind to the folks using his plugin.

I will add more comments later.

**Comment by ibhagwan** [comment]
Hi @jannes, have you seen [antoinemadec/coc-fzf](https://github.com/antoinemadec/coc-fzf)?

**Comment by jannes** [comment]
No, I hadn't seen this before, thanks for the pointer! I just tried it out and it works very well :)

**Comment by ibhagwan** [comment]
Great!

Seeing that there's an alternative and I'm not going to do this anytime soon I'm going to close this for now.

If someone decideds to PR this in the future and need my help they're welcome to reopen.

**Comment by jqhr** [comment]
coc.nvim has a lot of features not only lsp. Such as async complete (Coc's completion algorithm beats nvim-cmp completely), built-in snippets function to support snippets for vim snippets and lsp style,  multiple cursor support.
And more.
For now,  nvim's lsp has not support all lsp feature. And coc's extensions was not only for lsp. Also for other utils, like explorer, coc-markdown-preview, coc-pairs.
I both like fzf and coc very much.
It was a pity for close this pr

**Comment by ibhagwan** [comment]
> It was a pity for close this pr

This was a feature request, not a PR, you’re welcome to submit a PR if you wish, personally I sing have any plans to deal with vim and js code in order to support a plug-in that is IMHO going to be outdated by developments in neovim.

**Comment by jqhr** [comment]
I'm very sorry

**Comment by hexh250786313** [comment]
@jqhr It's not difficult to make the coc source work in fzf-lua, as both provide efficient APIs. This is how I implemented lsp-references: https://github.com/hexh250786313/dotfiles/blob/main/.config/nvim/lua/modules/fzf/plugins/lsp.lua

And by the way, @ibhagwan I'm curious about how you manage to keep the cursorline at the target position while scrolling the previewer?(It feels a bit odd to ask this in this issue, but I'm too lazy to open another one, so I'll just ask here)
