### ISSUE TITLE
How to open multiple search results of `.live_grep_native()`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#226]
As title. I usually come into a situation where I want to open all the files that contain a certain keyword. The current solution is that if I have 18 search results then I have to run `live_grep_native()` 18 times and record the pages that haven't been open as tabs. Any advice?

**Comment by nyngwang** [comment]
OK, I just found that I can use `<C-i>` to mark all the files and hit __Enter__ to open a list of all the marked search results in a drawer-like window. But I have to hit __Enter__ to see the file and the cursor will enter the file too. Is it possible to preview the file without changing the cursor position?

**Comment by ibhagwan** [comment]
>drawer-like window

This is called “quickfix” list, you can go back and forth between results with `:cprev`/`:cnext`, or close the list with `:cclose`.

Why don’t you just try the quickfix provider in fzf-lua:
```lua
:FzfLua quickfix
```

**Comment by ibhagwan** [comment]
It's also worth noting you can create your own function to deal with the selection, the below opens each one in a new tab by pressing `ctrl-y`:

```lua
require'fzf-lua'.setup {
  grep = {
    actions = {
      ["ctrl-y"]      = function(selected)
        for _, e in ipairs(selected) do
          local file = require'fzf-lua'.path.entry_to_file(e)
          vim.cmd("tabnew " .. file.path)
        end
      end,
    },
  },
}
```

**Comment by nyngwang** [comment]
> It's also worth noting you can create your own function to deal with the selection, the below opens each one in a new tab by pressing `ctrl-y`:
> 
> ```lua
> require'fzf-lua'.setup {
>   grep = {
>     actions = {
>       ["ctrl-y"]      = function(selected)
>         for _, e in ipairs(selected) do
>           local file = require'fzf-lua'.path.entry_to_file(e)
>           vim.cmd("tabnew " .. file.path)
>         end
>       end,
>     },
>   },
> }
> ```

If I just want to open the one my cursor hover on and open it in the new tab, how can I modify the script to do so?

**Comment by ibhagwan** [comment]
If you wish to have Fzf-lua remain open you need to implement it a bit differently with fzf’s `execute`:

```lua
function _G.my_live_grep(opts)
  if not opts then opts = {} end
  local action = require("fzf-lua.shell").action(function(selected)
    for _, e in ipairs(selected) do
      local file = require'fzf-lua'.path.entry_to_file(e)
      vim.cmd("tabnew " .. file.path)
    end
  end, "{+}")
  opts.actions = { ["ctrl-y"] = false }
  opts.fzf_cli_args  = ("--bind=ctrl-y:execute-silent:%s"):format(action)
  require'fzf-lua'.buffers(opts)
end
```

and then call your own function instead with `:lua _G.my_live_grep()`

**Comment by nyngwang** [comment]
I got error message if I change `tabnew ` to `enew `.

**Comment by ibhagwan** [comment]
I see, I just tried it and it does close the window, that's because when `tabnew` is performed the fzf window `WinLeave` is triggered which in turn closes the fzf main window.

It's possible to work around this with the `autoclose` property and other workarounds like deleting the autocommands for closing the window and then restoring them but at the moment I do not intend to add new code just for this.

If you're willing to invest a bit in learning lua the way I would do it is like this:
- Use fzf-lua `winopts.on_create` event to remove the `WinLeave` autocmd
- Set new `autocmd WinLeave` to your own function that looks for a global variable to decide whether or not to call `require('fzf-lua.win').win_leave()`
- Set the global variable to ignore the `WinLeave` event inside the `ctrl-y` function

It's not that complicated but it's a bit hacky and unless you know your way around lua and neovim I wouldn't bother with it and I don't think it's helpful if I write it myself without you understanding what it does or how to debug it.

**Comment by ibhagwan** [comment]
> but I need to get the absolute path of the file.

If you want the full path you can prepend the path with `vim.loop.cwd()`.

@nyngwang if you need to do more complex customizations you're going to need to invest some time in understanding the neovim lua API and basic functions in lua (string concat, etc).

**Comment by nyngwang** [comment]
It seems that I just succeeded! I dive into some code of `nvim-tree.lua` and got this working:

```
actions = {
  ["ctrl-y"] = function(selected)
    for _, e in ipairs(selected) do
      local file = require'fzf-lua'.path.entry_to_file(e, require'nvim-tree.lib'.Tree.cwd)
      print(file)
      require'nvim-tree.lib'.open_file('preview', file.path)
    end
  end,
},
```

While this will close the search results list, I can just combine this with the second script you have written!

**Comment by ibhagwan** [comment]
`require'nvim-tree.lib'.open_file`
Idk what this does behind the scenes (it’s a function from `nvim-tree`), but as long as it works why not use it :)

**Comment by nyngwang** [comment]
> It seems that I just succeeded! I dive into some code of `nvim-tree.lua` and got this working:
> 
> ```
> actions = {
>   ["ctrl-y"] = function(selected)
>     for _, e in ipairs(selected) do
>       local file = require'fzf-lua'.path.entry_to_file(e, require'nvim-tree.lib'.Tree.cwd)
>       print(file)
>       require'nvim-tree.lib'.open_file('preview', file.path)
>     end
>   end,
> },
> ```
> 
> While this will close the search results list, I can just combine this with the second script you have written!

It seems that combining this one with the second one of yours will cause some bug(a `nvim-tree.lua` mechanism is triggered and it required me to choose which window to open the buffers).

But it's still very satisfying: Now I can use `<tab>` to mark multiple results to open in new buffers. I think it's time to try `live_grep_resume`!

**Comment by nyngwang** [comment]
I like the current result :) While I wondering whether `live_grep_resume` is derived from `live_grep` or `live_grep_native`. Is there any performance degradation if I move from `live_grep_native` to `live_grep_resume`?

https://user-images.githubusercontent.com/24765272/143672599-0e5f6c64-9406-43b3-97d1-264142648ab1.mov

**Comment by ibhagwan** [comment]
> While I wondering whether live_grep_resume is derived from live_grep or live_grep_native. Is there any performance degradation if I move from live_grep_native to live_grep_resume?

`live_grep_resume` is simply `live_grep({ continue_last_search = true })`.

`live_grep_native` “lives” inside the fzf ecosystem, it doesn’t call back neovim every keystroke so the search term can never be saved so it cannot support `resume`.

**Comment by ibhagwan** [comment]
Closing for now, if you need more help or have issues with `live_grep_resume` feel free to reopen this issue or create a new one.
