### ISSUE TITLE
[Fzf-lua] fzf error 2: invalid preview window layout: nohidden:right:0

### ISSUE THREAD

**Issue by darzok0914** [ibhagwan/fzf-lua#227]
hi, I wanted to try this plugin but as soon as I want to start the command :lua require('fzf-lua').files()

nothing displays and I have this error:
[Fzf-lua] fzf error 2: invalid preview window layout: nohidden:right:0

I didn't configure anything, just literally installed the pluging and wanted to try it out. 
I am using neovim 0.5.1, I also have the classic fzf installed as well as telescope, could it be a conflict ?

**Comment by darzok0914** [comment]
I am running fzf 0.20.0 and I use ubuntu 20.04
just to be sure I cleaned my fzf vim by commenting out   Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
then deleting and reinstalling again.

**Comment by darzok0914** [comment]
ok problem solved, I did a sudo apt remove fzf and then out of curiosity I did a fzf --version and I got 0.27.2 displayed. I don't really understand what happened but it seems to have solved the problem.

**Comment by ibhagwan** [comment]
> ok problem solved, I did a sudo apt remove fzf and then out of curiosity I did a fzf --version and I got 0.27.2 displayed. I don't really understand what happened but it seems to have solved the problem.

You had an old version of the fzf binary installed which didn’t support the preview options.

For the record, it doesn’t matter how you install fzf, either globally on your machine or using the plugin `junegunn/fzf`, the only requirement is having an fzf version that could accept the preview params (0.23 I believe but not sure).

Glad you were able to sort this out.
