### ISSUE TITLE
improvement suggestion 

### ISSUE THREAD

**Issue by darzok0914** [ibhagwan/fzf-lua#230]
hey, I'm back :)

So I love having the preview when I do a BLines. There is one thing I wish was better to make it really perfect so hopefully I can describe it easily:

When we go trough the results, the preview buffer reloads every time which ideally we shouldn't want as when using BLines, it is always the same buffer only the cursor line changes. 
do you think it would be possible not to reload the buffer in the preview window but only update the cursor line? 

I'm not quite sure how you do the preview but my high level understanding is that you use vim buffer itself, we can use this function to set the cursor line in the current buffer:
    :call cursor(current_line, current_col)

What do you think?

**Comment by ibhagwan** [comment]
It’s a good idea, let me look into it.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/000d65b43b4572734fe109c35f2116955c21ea01 - this commit does exactly that. however, I didn't limit this to `lines|blines`, this now also applies to when the matches are from the same file in `grep|live_grep`, the preview buffer will only be reloaded when it recognizes it's a different file/buffer.

**Comment by darzok0914** [comment]
Thanks for considering this suggestion, I've updated the plugin and noticed the change :)
One thing though, if we go fast through the results, the preview doesn't refresh, I think it can make sense when we do a git_files or files search as I might speed things up. However for things like BLines it would be best if the preview was refreshing at the same time as the cursor goes through the results, no matter the speed. hopefully what I'm saying makes sense. 

What do you think ? is it even something possible to do?

**Comment by ibhagwan** [comment]
The default preview delay is 100ms (same as fzf's native preview functionality), this is done to prevent overloading neovim with file/buffer reads when scrolling fast, the setting can be controlled by setting `winopts.preview.delay` globally but I wouldn't recommend that for reasons I just mentioned.

If you wish to change it just for `blines` you can send a specialized winopts table just for that with the call:
```lua
:lua require'fzf-lua'.blines({ winopts = { preview = { delay = 0 } } })
```

**Comment by darzok0914** [comment]
that does exactly what I wanted, this is really nice for blines thanks so much
