### ISSUE TITLE
FzfLua grep_project

### ISSUE THREAD

**Issue by darzok0914** [ibhagwan/fzf-lua#231]
hi, 

When running :FzfLua grep_project or :lua require'fzf-lua'.grep_project()
![image](https://user-images.githubusercontent.com/72544332/144521089-ba8300a8-ab58-47ea-8242-9a03a570fe8c.png)

maybe I'm just being silly, I'll try to play with the settings and see how to go around this issue

**Comment by ibhagwan** [comment]
This shouldn’t happen, `grep_project` is just a shortcut to `grep({ search = '' })` - what happens if you run a simple grep with an input string for search?

Did you play around with `rg_opts` because there shouldn’t be `—maxs` option in the defaults if I recall correctly?

**Comment by ibhagwan** [comment]
Just checked the code again there's no way it can send the argument `--maxs` unless `rg_opts`, `cmd` or `raw_cmd` were specified somewhere in your `setup()` function (under `grep`) or in your keymaps.

**Comment by xsteadfastx** [comment]
i have exact the same problem since today!

**Comment by xsteadfastx** [comment]
if i manually set the plugin to commit 253b9413eb116081aa81becda67ed9ccbccbb0a6 in packer... it works again.

**Comment by darzok0914** [comment]
- what happens if you run a simple grep with an input string for search? -> the same thing happens
- Did you play around with rg_opts because there shouldn’t be —maxs option in the defaults if I recall correctly? -> not at all

**Comment by xsteadfastx** [comment]
> * what happens if you run a simple grep with an input string for search? -> the same thing happens
this maxs error comes on all rg actions from fzf-lua. how can i invoke that grep manually? 

>     * Did you play around with rg_opts because there shouldn’t be —maxs option in the defaults if I recall correctly? -> not at all

nope... i posted my full config here: https://gist.github.com/xsteadfastx/04c98383ad376b646698becac0f10f3e#file-init-lua-L319

**Comment by darzok0914** [comment]
I can confirm that commit 253b9413eb116081aa81becda67ed9ccbccbb0a6 works well for me too

**Comment by xsteadfastx** [comment]
checked all commits since  253b941. it starts to fail with 7b0e658db59cc25fb8405067284d032ac477e055

**Comment by ibhagwan** [comment]
Ok, this was embarassing I decided to "optimize" the single buffer/empty search query results with `rg` as it was addding column `:1` after each result which made no sense, I forgot that `-` was a special character in the lua string patterns so it was matching other characters and modifying the `rg` flags erronously.

https://github.com/ibhagwan/fzf-lua/commit/ae40b13517bc1865d11b3a264b7959d02529b4af - this should close it, let me know if you're still having issues I might remove this optimization alltogether.

**Comment by xsteadfastx** [comment]
Hi,

On Fr, 03. Dez 07:34, ibhagwan wrote:
> Ok, this was embarassing I decided to "optimize" the single buffer/empty search query results with `rg` as it was addding column `:1` after each result which made no sense, I forgot that `-` was a special character in the lua string patterns so it was matching other characters and modifying the `rg` flags erronously.
> 
> https://github.com/ibhagwan/fzf-lua/commit/ae40b13517bc1865d11b3a264b7959d02529b4af - this should close it, let me know if you're still having issues I might remove this optimization alltogether.

thank you for the fix and the explanation. but mostly for this really
sweet plugin. :)

**Comment by ibhagwan** [comment]
> thank you for the fix and the explanation. but mostly for this really sweet plugin. :)

Ty! :-)

**Comment by darzok0914** [comment]
yep it fixed the problem, that was amazingly quick
