### ISSUE TITLE
[Question] How to correctly grep the content I want?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#233]
While this is probably not a problem related to this project, I think it will be extremely helpful if you could provide some searching examples with the `FzfLua live_grep` that use multiple keywords to find some results.

My current settings are as follow:

```
config = function()
  require'fzf-lua'.setup {
    grep = {
      cmd = "rg --vimgrep --hidden "..
        "--glob '!{.git,node_modules,package-lock.json,yarn.lock,Library,tags}' ",
      color_icons = false,
    }
  }
end
```

For example if I want to search every line of the form: `WARNING: [...] should be fixed immediately.`. What I expect to do is typing something like this in the search window:

```
WARNING + immediately
```

But this didn't work.

**Comment by ibhagwan** [comment]
`live_grep` uses perl/rust regex format, try searching for `WARNING.*immediately`.

It's probably a good idea to add a few examples in the Wiki but as long as you understand it's just a regex there are endless of regex guides out there that probably do a better job than myself.

**Comment by nyngwang** [comment]
Thanks for your kindly reply. This solves my problem 🙇
