### ISSUE TITLE
Duplicated results on `live_grep_resume` after delete all keywords.

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#234]
As title.

<img src="https://user-images.githubusercontent.com/24765272/144697011-a01b3280-b041-45c8-93a3-ccd14f59f1be.png" width="700">

**Comment by ibhagwan** [comment]
It's not duplicate results per-se, it seems your `rg` is returning a line match for each character in the line, you can see the columns are increasing every line (i.e. `.zshenv:1:1:`, `.zshenv:1:2`.

Is your plugin fully updated? I fixed an issue earlier today that may or may not be related, when the search query is empty (when you delete all the words) it should delete the `--column` option so it shuldn't even show the column number (as it makes no sense when there is no search).

Another option is that you have `rg_opts` defined or `cmd` that adds a flag to match each character instead of by line?

**Comment by ibhagwan** [comment]
I found out from issue #233 that you're using `cmd = "rg --vimgrep --hidden "`, I just tested it and this is what's causing the problem, `--vimgrep` doesn't play well with an empty search string, see below:

```sh
~ ❯ cat test.txt
line1
line2
~ ❯ rg --vimgrep '' test.txt
test.txt:1:1:line1
test.txt:1:2:line1
test.txt:1:3:line1
test.txt:1:4:line1
test.txt:1:5:line1
test.txt:1:6:line1
test.txt:2:1:line2
test.txt:2:2:line2
test.txt:2:3:line2
test.txt:2:4:line2
test.txt:2:5:line2
test.txt:2:6:line2
~ ❯ rg --line-number --column '' test.txt
1:1:line1
2:1:line2
```

**Comment by ibhagwan** [comment]
This is definitely the issue, from the `rg` manual, it doesn't work well with empty strings as this means everything matches:
```help
       --vimgrep
           Show results with every match on its own line, including line
           numbers and column numbers. With this option, a line with more than
           one match will be printed more than once.
```

Why don't you replace `rg --vimgrep` with `rg --line-number --column --color=never`?

**Comment by nyngwang** [comment]
Before I saw your last comment (at this moment). I just get rid of this with the following settings:

```
grep = {
  ...
  rg_opts =
    "--column "..
    "--line-number "..
    "--no-heading "..
    "--case-sensitive "..
    "--hidden "..
    " "..
    "--max-columns 200 "..
    "--max-filesize 1M "..
    "--max-depth 10 "..
    " "..
    "--glob '!.local/share' "..
    "--glob '!.config/nvim/plugin' "..
    "--glob '!.Trash' "..
    "--glob '!Library' "..
    "--glob '!Documents' "..
    "--glob '!Pictures' "..
    " "..
    "--glob '!.git' "..
    "--glob '!node_modules' "..
    "--glob '!package-lock.json' "..
    "--glob '!yarn.lock' "..
    "--glob '!tags' "..
    " ",
...
```

Not related to this question but I would like to know your idea on whether my continuous usage and/or the ordering of `--glob` will cause some performance issue or not.

**Comment by ibhagwan** [comment]
>The frozen grep problem mentioned in Neovim got frozen after holding <C-J> to scroll down the results of live_grep() #211 is remedied by the option `--max-depth 10`.

That's not a real solution but rather a workaround, the settings makes it so directories beyond depth of `10` aren't searched, that means you have a deep directory tree with many files (probably with matches too) that cause this behavior, if you wish we can still work on it on a new issue. 

Does  `live_grep_native` have the same issue or this is just for `live_grep` and `live_grep_resume`?

>I would like to know your idea on whether my continuous usage and/or the ordering of --glob will cause some performance issue or not.

I'm not an expert on `rg` performance, I just use it as a search tool. That said, I doubt `--glob` (or `--iglob`) would cause a performance issue as it's just excluding files from being searched at all, I would argue it would increase performance as `rg` needs to search less files.

Btw, if you need to modify the `--glob` arguments dynamically you can also use `live_grep_glob`, you can #167 to understand how it works, or specifically [this comment](https://github.com/ibhagwan/fzf-lua/issues/167#issuecomment-936682252):

![fzf-glob](https://user-images.githubusercontent.com/59988195/136248999-cab6e76e-ea63-4432-aa69-3d6c4b70eb32.gif)

**Comment by nyngwang** [comment]
Since I really need the `..._resume` features, there would be less possible that I tune my settings back to `live_grep_native`. I don't know what "glob" means but I will definitely give it a try (if I understand the usage linked). Regarding my problem:

> I would like to know your idea on whether my continuous usage and/or the ordering of --glob will cause some performance issue or not.

I want to know whether there is a way to "one-line" all things I want to exclude so the process will only be run once. My current solution contains many `--glob`, and this made me think that something would be run N times rather than one time.

**Comment by ibhagwan** [comment]
>Since I really need the ..._resume features, there would be less possible that I tune my settings back to live_grep_native. I don't know what "glob" means but I will definitely give it a try (if I understand the usage linked). Regarding my problem:

"glob" means dynamically adding `--glob` or (`--iglob` to the `rg` flags), if you read #167 issue you'll understand.

>I want to know whether there is a way to "one-line" all things I want to exclude so the process will only be run once. My current solution contains many --glob, and this made me think that something would be run N times rather than one time.

There should be no difference between specifying many `--glob` vs a "one-line", read the `rg` manual to get your answers.
