### ISSUE TITLE
Could you provide `actions` field for `oldfiles`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#236]
As title. I expected this would work:

```
oldfiles = {
  actions = {
    ["ctrl-y"] = preview_like_nvimtree,
  },
},
```

It seems that [this line](https://github.com/ibhagwan/fzf-lua/blob/1d6ea8d38100b9b4b4f1e49626697c9c41a6759c/lua/fzf-lua/config.lua#L270) will not include my custom actions:

```
actions             = M.globals.files.actions,
```

In my current experience, `oldfiles` is much more useful than `FzfLua files` since I will want to jump back to __all__ those buffers I once opened (and deleted to reduce the number of buffers). I will expect there will be a new feature `oldfiles_resume` as you've made `files_resume` for `files`!

**Comment by nyngwang** [comment]
Sorry, I just realized that `<ctrl-t>` does this exactly by default...

**Comment by nyngwang** [comment]
The final result is satisfying! I'm using this one:

```
oldfiles = {
  actions = {
    ["default"] = actions.file_edit,
  },
},
```

I really love this plugin! Now (I hope) there is no frustration (to me) regarding file navigation. Thank you so much for building and maintaining this project! I will definitely recommend people to use it!

**Comment by ibhagwan** [comment]
Glad you were able to sort this out by yourself :-)
