### ISSUE TITLE
The `FzfLua files` will still show directory in the result list when `--type f` is added.

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#237]
As title. Screenshot:

<img src="https://user-images.githubusercontent.com/24765272/144706061-e550f29d-c93a-4969-89c5-7542530e01e2.png" width="700">

**Comment by nyngwang** [comment]
Remove `cmd = 'fd'` seems to resolve the problem. But I would like to keep it to remind myself that I have to install `fd` as dependency.

**Comment by ibhagwan** [comment]
The executed command is auto-detected, it gives priority to `fd`  but if it cannot find `fd` it will run `find`, judging by the outout in the OP it seems you have a non-GNU version of `find` and `fd` wasn't installed? if it was actually `fd` then you needed to specify `--type` (and not `-type`).

If you specify `cmd` you basically override everything and tell fzf-lua to use `fd` no matter if it's installed or not, that will fail on machines where `fd` is not installed effectively reminding you to install `fd`.

This is the relevant part from the README, the way `find|fd` options work is the same as `rg|grep`:
```lua
    -- executed command priority is 'cmd' (if exists)
    -- otherwise auto-detect prioritizes `fd` over `find`
    -- default options are controlled by 'fd|find_opts'
    -- NOTE: 'find -printf' requires GNU find
    -- cmd            = "find . -type f -printf '%P\n'",
    find_opts         = [[-type f -not -path '*/\.git/*' -printf '%P\n']],
    fd_opts           = [[--color never --type f --hidden --follow ]] ..
            [[--exclude .git --exclude node_modules --exclude '*.pyc']],
```

If you want to properly remind youreslf you need to install `fd` why don't you add something like this to your setup:
```lua
if vim.fn.executable("fd") ~= 1 then
    vim.notify("Please install 'fd'...", vim.log.levels.WARN)
end
```

**Comment by nyngwang** [comment]
I copied the wrong options and then realized that (after some hours) I should use `fd_opts`.

---

Regarding:

>  If you specify cmd you basically override everything and tell fzf-lua to use fd no matter if it's installed or not, that will fail on machines where fd is not installed effectively reminding you to install fd.

I'm sure that I have `fd` installed via homebrew. But if I add the option `cmd = fd` then the problem described will happen.

**Comment by ibhagwan** [comment]
>I have checked that I have fd installed (via homebrew). But if I add the option cmd = fd back the problem indeed happens as described.

`cmd` overrides evrything, that means that when you specifcy `cmd`, `fd_opts` **are ignored**, running `fd` without any option willl list directories by design, if you wish to ignore directories add the options you want to `cmd`, i.e. `cmd = 'fd --type f`.
