### ISSUE TITLE
Calling commands from builtin does not enter INSERT mode in fzf window

### ISSUE THREAD

**Issue by Utoma** [ibhagwan/fzf-lua#238]
calling commands from the command line are unaffected. the fuzzy finder hangs when using builtin -> anycommand

**Comment by ibhagwan** [comment]
Can you provide more information what's happening? which command are failing? is it just `files` for exmaple or all?  does the same command work when run outside of the `builtin`? what neovim/fzf versions are you using?

**Comment by Utoma** [comment]
sorry, the commands work from builtin but picker is unusable. calling them directly works fine. Here's a link to a image https://imgur.com/5zlFAy0 . the top  was called directly from a mapped key, the bottom from builtin. notice the cursor is at the bottom of the picker (green background) which scrolls but selects/highlights nothing 

Packer updated fzf-lua today, neovim version 0.6

**Comment by ibhagwan** [comment]
Oh, I see what's happening here, it's just not entering INSERT mode after being called from `builtin`, press `i` after the call from builtin and you'll be able to interact with the window.

Let me change the title of this post and try to figure out why this happens.

In the meantime can you run the below and let me know the result?
```lua
-- should return 'true' or 'false'
:lua print(vim.tbl_isempty(vim.fn.getcompletion('ModeChanged', 'event')))
```

**Comment by ibhagwan** [comment]
Btw, from the screenshot it seels you do not have `fd` installed, (non-GNU `find` prepends `./` before paths), I'd highly recommend installing [`fd`](https://github.com/sharkdp/fd) for better functionality and performance.

Same goes for [`rg` (ripgrep)](https://github.com/BurntSushi/ripgrep) if you don't have it for better `grep` functionality.

**Comment by ibhagwan** [comment]
Don't need to test or reply to the earleir comment latest commit should solve this for you.

**Comment by Utoma** [comment]
the print command returns true

i do have fd installed although i may have changed the config in the past

**Comment by ibhagwan** [comment]
FYI, the `./` prefix seems to be a new thing since `fd` v8.3.0 (see [chanelog](https://github.com/sharkdp/fd/blob/master/CHANGELOG.md)) now requires adding `--strip-cwd-prefix` to remove the prefix.

I don't really want to test `fd` version to conditonally add this option so fzf-lua now does the stripping if necessary.
