### ISSUE TITLE
Files with absolute path are not previewed correctly

### ISSUE THREAD

**Issue by zeertzjq** [ibhagwan/fzf-lua#24]
Steps to reproduce:
1. Open a C source file with the following content:
```
#include <stdlib.h>
int main() {
  void *p = malloc(8);
  free(p);
}
```
2. Put cursor on `malloc`.
3. Run `:lua require('fzf-lua').lsp_definitions()`
4. The plugin tried to prepend CWD to the path of the file previewed by `bat`, and `bat` cannot find the file.

**Comment by ibhagwan** [comment]
Same issue as #22, the way previews are done with an external command I can’t control it ATM but I plan to work on it this week and make the previewer more flexible by having nvim stream the file contents to fzf, with either bat or even treesitter highlighted content.

**Comment by ibhagwan** [comment]
Should be fixed in the latest commit, lmk if otherwise?

**Comment by zeertzjq** [comment]
@ibhagwan The last commit seems to break file preview completely. Even files with relative paths cannot be previewed.

**Comment by ibhagwan** [comment]
Is it only broken

**Comment by zeertzjq** [comment]
> Another thing, I applied a fix to `nvim-fzf` when the search/LSP output has special characters that can confuse the previewer, [PR#18](https://github.com/vijaymarupudi/nvim-fzf/pull/18) which wasn’t merged yet, can you try with my fork? Just replace `vijaymarupudi/nvim-fzf` with `ibhagwan/nvim-fzf`.

![Screenshot_20210804_084041](https://user-images.githubusercontent.com/35768171/128103791-df2e23a1-8c8d-40dc-a390-a64d043b1fc8.png)

**Comment by zeertzjq** [comment]
It seems to work after I set `$SHELL` to `/usr/bin/sh`.

**Comment by ibhagwan** [comment]
> It seems to work after I set `$SHELL` to `/usr/bin/sh`.

I figured something in the shell is messing up running the command (that extracts the file name), what’s your default shell? `bash`?

**Comment by zeertzjq** [comment]
> > It seems to work after I set `$SHELL` to `/usr/bin/sh`.
> 
> I figured something in the shell is messing up running the command (that extracts the file name), what’s your default shell? `bash`?

Actually setting `$SHELL` to `bash` also works. My default shell is `fish` and it doesn't support backtick expansion.

**Comment by ibhagwan** [comment]
> > > It seems to work after I set `$SHELL` to `/usr/bin/sh`.
> > 
> > 
> > I figured something in the shell is messing up running the command (that extracts the file name), what’s your default shell? `bash`?
> 
> Actually setting `$SHELL` to `bash` also works. My default shell is `fish` and it doesn't support backtick expansion.

Good find, I can probably solve this by setting `vim.env.SHELL` to `sh` but I hate overriding the users' environment variables, I'll have to think of a better way.

**Comment by ibhagwan** [comment]
> > > > > It seems to work after I set `$SHELL` to `/usr/bin/sh`.
> > > > 
> > > > 
> > > > I figured something in the shell is messing up running the command (that extracts the file name), what’s your default shell? `bash`?
> > > 
> > > 
> > > Actually setting `$SHELL` to `bash` also works. My default shell is `fish` and it doesn't support backtick expansion.
> > 
> > 
> > Good find, I can probably solve this by setting `vim.env.SHELL` to `sh` but I hate overriding the users' environment variables, I'll have to think of a better way.
> 
> `nvim-fzf` seems to use `termopen()` which can accept environment variables.

I was just looking into it, perhaps I can add it to the PR, let's test it first, I'll let you know soon when I commit this change to my fork of `nvim-fzf`.

**Comment by ibhagwan** [comment]
Just updated my fork of `nvim-fzf`, let me know if it works for you?

**Comment by zeertzjq** [comment]
It works.

**Comment by ibhagwan** [comment]
Ty!
