### ISSUE TITLE
Buffer Id is increasing, and messing with `:b#` command

### ISSUE THREAD

**Issue by rod-stuchi** [ibhagwan/fzf-lua#240]
I thing I have a silly question, there is a way to avoid this (the same happens with Telescope), if I page over a list of files with:

```
:lua require('fzf-lua').files({ fzf_opts = {['--layout'] = 'reverse-list'} })
```

![image](https://user-images.githubusercontent.com/19471811/144767966-53465429-093c-469f-ae33-e4e7b7a1673f.png)

Thank you for the initiative to port fzf.vim to lua

**Comment by ibhagwan** [comment]
When using the builtin previewer each time you hover over a file it gets loaded into a new unlisted buffer, unfortuntaely, this will increase the internal neovim buffer index.

If you wish to avoid that you can use the native fzf previewer which does not use a neovim buffer but an external utility (`cat/bat/head`) to display the preview within fzf, the downside of it is that you lose the neovim syntax highlighting, you can probably find a close-enough syntax highlight theme with `bat --list-themes` but it won't match your neovim colorscheme one-to-one.

If you have `bat` intalled, you can add this to your setup function:
```lua
require'fzf-lua'.setup {
  winopts = {
    preview = { default = 'bat' }
  }
}
```

**Comment by rod-stuchi** [comment]
Nice, thank you so much, that solve the my issue.
