### ISSUE TITLE
Feature request: FzfLua resume (like CocListResume)

### ISSUE THREAD

**Issue by uga-rosa** [ibhagwan/fzf-lua#241]
Thanks for the great plugin.
I think it would be useful to have a command like CocListResume to reopen the picker that was executed just before.
It would be nice to be able to restore the input state as currently implemented in `file_resume` and `live_grep_resume`.

**Comment by ibhagwan** [comment]
Anything specific you're missing, I would assume most of the functionality revolves around files/searches, between `files_resume`, `grep_last` and `live_grep_resume` most of it is covered, the LSP part could probably use that.

**Comment by uga-rosa** [comment]
Yes, it would be useful for things like references.
I prefer to have a single command that I can use with the thought of "I want to execute the previous operation again" (although in reality, I'm probably mapping it).

**Comment by ibhagwan** [comment]
Added with the last commit, require a tiny bit of refactoring but turned out better than I expected, can even resume custom implemtations if done right :-)

Try it out and let me know?

**Comment by uga-rosa** [comment]
Amazing!!
It's exactly what I was looking for. Thank you very much!

**Comment by ibhagwan** [comment]
Just fixed a tiny issue of the typed query being saved between different providers, for exmaple, open `files`, type a query, open `grep` and then open `resume` - the typed query from `files` would be entered into the `grep` prompt.

Let me know if you find any other issues?

**Comment by uga-rosa** [comment]
So far, it's working without any problems. I'll let you know if I have any problems.
