### ISSUE TITLE
Two sets of references in lsp results

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#242]
Hey there, 

I noticed today when using fzf-lua as the the handler for lsp references I get two sets of the same references with different paths. One set with absolute paths and the other with relative. 

![image](https://user-images.githubusercontent.com/5642902/145093033-4459c3ec-bdee-42fe-bd8b-91c9ecc24a13.png)

**Comment by ibhagwan** [comment]
I did commit a bit of a change today, but the lsp provider was untouched, it may still be related though, what does `:lua vim.lsp.buf.references()` output? do you get duplicates there too?

**Comment by ldelossa** [comment]
Does not seem like it:

![image](https://user-images.githubusercontent.com/5642902/145095727-272d2807-7c84-457a-8f25-612c658b35ac.png)

(lines end at 8)

**Comment by ibhagwan** [comment]
I looked again and I'm not sure what is happening here, the screenshot you just sent seems to be refernces of a different object from the OP.

A few questions so we can clarify this further:
- Does this happen all the time or just some of the times?
- Does this also happen with defintions?
- What is the cwd in the OP (is it `~/.config/nvim/after/calltree.nvim`?)
- Is it possible you have copies of the `ui.lua` file in two different locations?

**Comment by ldelossa** [comment]
Ah I think 
* Is it possible you have copies of the ui.lua file in two different locations?
is the issue. 

I have some symlinking going on between my .config file and my dotfiles repo.

**Comment by ibhagwan** [comment]
> I have some symlinking going on between my .config file and my dotfiles repo.

What happens if you remove the symlink?

**Comment by ldelossa** [comment]
Solves the issue. thanks a lot!

**Comment by ibhagwan** [comment]
> Solves the issue. thanks a lot!

Ty for the update!  I still wonder why `lua vim.lsp.buf.references()` doesn’t return duplicates, fzf-lua doesn’t do complex processing here aside from adding the icons and some minor modifications.

**Comment by ldelossa** [comment]
you know, that's a good question. let me experiment a bit more.
