### ISSUE TITLE
Question: pasting from registers

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#244]
Hey there, 

Fuzzy searching registers have been proving to be very useful.

Is it possible to write an action in which hitting "enter" on a register entry will write the line into the buffer where your cursor is?

**Comment by ibhagwan** [comment]
Yes pretty easy too if you have a bit of lua knowledge, the way I'd go about it is to create a specialization of the `registers` function that saves the current buffer number and position in the `opts` table, override the "default" action with your own action (does the writing to the bufer, etc) and then call the exiting `registers` function with your new options, roughly something like this:

```lua
function M.test(opts)
  if not opts then opts = {} end
  opts._curbuf = vim.api.nvim_get_current_buf()
  opts._curpos = vim.fn.getpos(".")
  opts.actions = {
      ["default"] = function(selected)
      -- parse the line and do your writing here
      -- with vim.api.nvim_buf_set_lines
      -- all the information you need is below
      local line, col = opts._curpos[2], opts._curpos[3]
      print(selected[1], opts._curbuf, line, col)
    end
  }
  fzf_lua.registers(opts)
end
```

**Comment by ldelossa** [comment]
Thanks a lot.

**Comment by ibhagwan** [comment]
Closing for now, lmk if you need more help?

**Comment by iovis** [comment]
For posterity, if someone comes googling and wants something like this, this is what I have implemented:

```lua
-- Registers (paste register or apply macro)
local extract_register_from = function(result)
  -- `selected[1]` is going to be "[2] contents of register 2"
  return result:match("^%[(.)%]")
end

vim.keymap.set("n", "+r", function()
  local opts = {}

  opts.actions = {
    ["default"] = function(selected)
      local register = extract_register_from(selected[1])
      vim.cmd('normal "' .. register .. "p")
    end,
    ["@"] = function(selected)
      local register = extract_register_from(selected[1])
      vim.cmd("normal @" .. register)
    end,
  }

  fzf_lua.registers(opts)
end, { desc = "fzf_lua.registers" })
```

I'm sure this snippet can be improved haha

**Comment by ibhagwan** [comment]
FYI @iovis @ldelossa, due to #540 this is now the default action for registers, the new action is `actions.paste_register`.

**Comment by ldelossa** [comment]
Awesome. I think that makes a lot of sense.

**Comment by RayZ0rr** [comment]
A little extra for those who don't want to paste from the register immediately:
```lua
  registers = {
    actions = {
	['ctrl-p'] = function(selected)
	  local reg = selected[1]:match("%[(.-)%]")
	  local ok, data = pcall(vim.fn.getreg, reg)
	  if ok and #data > 0 then
	    vim.fn.setreg(vim.v.register,data)
	  end
	end
    }
```

Reference taken from [fzf-lua actions paste_regsiter](https://github.com/ibhagwan/fzf-lua/blob/292de730ebbd3834e87f864c8c4115dc1035db37/lua/fzf-lua/actions.lua#L705)
