### ISSUE TITLE
"<Space>" instead of " " for keymaps

### ISSUE THREAD

**Issue by rrykim** [ibhagwan/fzf-lua#246]
Hi,

Just a quick suggestion, how about using `keymap.lhs:gsub(" " , "<Space>")` in the `add_keymap` function?
https://github.com/ibhagwan/fzf-lua/blob/028460f72827300e58a241171e975882e99c4a71/lua/fzf-lua/providers/nvim.lua#L193

**Comment by ibhagwan** [comment]
Absolutely, I wasn't really using `keymaps`, had no idea space was misrepresented like this, fixed, ty! :-)
