### ISSUE TITLE
Builtin previewer not being updated for nameless buffers

### ISSUE THREAD

**Issue by tobiwild** [ibhagwan/fzf-lua#250]
Reproduce:

- Create 2 buffers with `:enew` and add some content
- run `:FzfLua buffers`
- switch between the two entries

Result:

- the previewer is not updating the content

Issue is probably this:
```
	if
		(entry.bufnr and entry.bufnr == self.loaded_entry.bufnr)
		or (entry.path and entry.path == self.loaded_entry.path)
	then
		return false
	end
```
`path` is `[No name]` in both cases.

**Comment by ibhagwan** [comment]
Accurate analysis, fixed :-)

Tysm!
