### ISSUE TITLE
new default setting for `multiprocess=true` breaks files and gitfiles commands

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#251]
with no changes and updating the plugin this morning (did not set multiprocessing), the files and git files command stopped working properly.

When you trigger them, the split opens and you see options but the display is all messed up and its glitched out in the center of the new buffer. adding `multiprocess=false` to `files` config fixes the issue.

Here is a screenshot of the glitch:
<img width="752" alt="Screen Shot 2021-12-12 at 12 14 22" src="https://user-images.githubusercontent.com/16427330/145727993-a0d1af96-b6dc-4e52-958c-b740b42e89b2.png">

This issue exists on both the default macOS terminal, and kitty terminal and also both on Neovim HEAD and Stable.

**Comment by ibhagwan** [comment]
Ty for the report @ViRu-ThE-ViRuS! would you be able to run `:lua require'fzf-lua'.files({ multiprocess=true, debug=true })`? This will print the shell command to `:messages`, then copy it and run in the terminal and let me know if you see any errors?

**Comment by ibhagwan** [comment]
I'm pretty sure this happens because the external commad throws a lua error which messes up the display, the command does seem to partially succeed as it did return results, possibly something in custom configs I didn't take into account, can you post your setup function so I can try with your config?

**Comment by ViRu-ThE-ViRuS** [comment]
```
'nvim' -n --headless --clean --cmd 'lua loadfile([[/Users/viraat-chandra/.local/share/nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[rg --files
 --follow --smart-case --hidden --no-ignore -g "!{.DS_Store,.cache,venv,.git,.clangd,.ccls-cache}" 2> /dev/null]],git_icons=false,file_icons=true,color_icons=true},[[_G._devicons_path='\''/
Users/viraat-chandra/.local/share/nvim/site/pack/packer/start/nvim-web-devicons/lua/nvim-web-devicons.lua'\''; _G._fzf_lua_server='\''/var/folders/v4/2cp1ct4d3f15n5y64_lln1z80000gn/T/nvimiJ
YoL9/1'\''; return require("make_entry").file]],[[return require("make_entry").preprocess]])'
```

^^ this is the output for 
```lua
:lua require("fzf-lua").files({multiprocess=true, debug=true})
```

- with and without `giticons` is the same glitchy behavior with `multiprocess=true`, it doesn't seem to make a difference.
- tested on latest pull

**Comment by ibhagwan** [comment]
Tysm @ViRu-ThE-ViRuS, this is very helpful! together with the information provided by @jdrouhard in #248 I feel I can tackle this further, once I'm done and it's working the performance should be a joy even on huge codebases :-)

**Comment by ibhagwan** [comment]
@ViRu-ThE-ViRuS, thanks to the help of @jdrouhard we've managed to get to the bottom of this, can you try and let me know if this works for you now?

**Comment by ViRu-ThE-ViRuS** [comment]
@ibhagwan yes! the glitch has been fixed. Amazing work :)

**Comment by ibhagwan** [comment]
Tysm @ViRu-ThE-ViRuS, you've been a great help :-)
