### ISSUE TITLE
Exclude filename when searching in tags

### ISSUE THREAD

**Issue by yujinyuz** [ibhagwan/fzf-lua#253]
Thanks for this awesome plugin! 

I've been using this plugin for quite a few days and the tags finder feels as fast as fzf.vim's `:Tags` thanks to the last update

Is it possible to exclude the filename from being matched?

This is from fzf.vim

<img width="666" alt="Screen Shot 2021-12-13 at 11 12 52" src="https://user-images.githubusercontent.com/10972027/145746666-506b8742-c2f3-464f-ad50-e53ce7cc039b.png">

This is from fzf-lua

<img width="444" alt="Screen Shot 2021-12-13 at 11 08 23" src="https://user-images.githubusercontent.com/10972027/145746313-4ca9039d-2885-4dd8-b9fb-1a2629fd299f.png">

However, I get correct output when I type it in all caps
<img width="425" alt="Screen Shot 2021-12-13 at 11 13 48" src="https://user-images.githubusercontent.com/10972027/145746729-55c8d978-6f90-40d4-819e-485eee8cf7aa.png">

**Comment by ibhagwan** [comment]
Absolutely:

```lua
-- exclude matching anything past the 2nd ':' (i.e. match 3rd field onwards)
:lua require'fzf-lua'.tags({ fzf_cli_args="--nth=3.." }
-- it's also possible to hide the names instead by using '--with-nth' (great for `btags`)
:lua require'fzf-lua'.btags({ fzf_cli_args="--with-nth=3.." }
```

**Comment by yujinyuz** [comment]
Thanks for the fast reply!

**Comment by ibhagwan** [comment]
FYI,

https://github.com/ibhagwan/fzf-lua/commit/31a678e4dedb418fd011f31333ff7111e16aaae6 - as of this commit this is no longer required, `btags` will now hide the buffer name by default:

![screenshot-1639440966](https://user-images.githubusercontent.com/59988195/145909678-75194357-e058-4c29-8e96-ba2a6b3cdcd0.png)
