### ISSUE TITLE
[tabs] - tabs out of sync with fzf

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#257]
Hello,

It appears FzfLua tabs can become out-of-sync with the actual present tab pages. 

https://user-images.githubusercontent.com/5642902/146050176-4da3bde8-a322-4dae-a871-56ba2530f05b.mp4

When they become out of sync selecting a tab to move to breaks.

**Comment by ibhagwan** [comment]
At a moment when this breaks, without moving between tabs can you post the output of:

```lua
:tabs
```

```lua
:lua __G.dump(:lua _G.dump(vim.api.nvim_list_tabpages())
-- followed by one call per tab, e.g. for tab #1, #2
:lua _G.dump(vim.api.nvim_tabpage_list_wins(1))
:lua _G.dump(vim.api.nvim_tabpage_list_wins(2))
```
^The above is how it's done in fzf-lua, I don't really have much control over the output other than calling these API's, I remember my tabs being messed up too I then found out that I had an autocmd for `colorcolumn` that was causing that, I could never find the connection why (possible neovim bug) just that it was messing up my tabs.

**Comment by ibhagwan** [comment]
Both `tabs` and `buffers` were reworked in the latest commits, I doubt this was related but let me know if this still happens and if it does please run the command I listed?

Btw, `ctrl-x` in both tabs and buffers will no wipe the selected buffers (if possible) and reload the windows (using the new `resume`), pretty convinient to clean up buffers.

**Comment by ldelossa** [comment]
Tabs seem to be acting much better now. Just tested it out, sorry for delay. I can't reproduce this issue after your latest commits were pulled down.

**Comment by ibhagwan** [comment]
Ty for Thor update, the code was refactored and many things changed, might have helped.
