### ISSUE TITLE
Devicons broken after last update

### ISSUE THREAD

**Issue by krims0n32** [ibhagwan/fzf-lua#260]
Hi, thank you for writing and releasing this plugin!

I have a small issue since the last update, all the devicons show the default (document) icon instead of filetype specific icon. This is since the last fzf-lua update you pushed. They work fine in NvimTree and bufferline.

![image](https://user-images.githubusercontent.com/661853/146179294-a7eefc6a-6919-41a2-bb5c-a45c8262f520.png)

**Comment by ibhagwan** [comment]
It's most likely related to the multiprocess performance enhancement, let's do two things:

First, disable `multiprocess` and see if it will work again (most likely will):
```lua
-- it's only enabled for grep/files
-- add 'multiprocess=false' under both
require'fzf-lua'.setup {
  files = {
    multiprocess      = false,
  },
  grep = {
    multiprocess      = false,
  },
}
```

It would be much appreciated if we can debug this further and see why this fails.

If you set 'multiprocess=true,debug=true' fzf-lua will print the neovim external command to `:messages`, can you please post it here so we can try and figure out why devicons fail to load when running externally.

```lua
-- it's only enabled for grep/files
-- add 'multiprocess=false' under both
require'fzf-lua'.setup {
  files = {
    multiprocess      = true,
    debug             = true,
  },
  grep = {
    multiprocess      = true,
    debug             = true,
  },
}
```

Note that you don't have to do this via the `setup()` function, you can also send `debug` or `multiprocess` directly when calling the provider:
```lua
:lua require'fzf-lua'.files({ debug=true,multiprocess=true })
```

**Comment by krims0n32** [comment]
Hi! Correct, it works without multiprocessing enabled.

It seems `_G._devicons_path` is not defined in the command though. Any idea?

```
'vi' -n --headless --clean --cmd 'lua loadfile([[/home/js/.local/share/nvim/plugged/fzf-lua//lua/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[fd --color never --type f
 --hidden --follow --exclude .git --exclude node_modules --exclude '\''*.svg'\'' --exclude '\''*.pyc'\'' --exclude '\''*.ttf'\'' --exclude '\''*.woff'\'' --exclude '\''*.jpg'\
'' --exclude '\''*.png'\'' --exclude '\''*.gif'\'' --exclude '\''*.mp4'\'']],git_icons=true,file_icons=true,color_icons=true},[[_G._fzf_lua_server='\''/tmp/nvimRFW9In/1'\''; r
eturn require("make_entry").file]],[[return require("make_entry").preprocess]])
```

**Comment by ibhagwan** [comment]
We found the issue. that was my second suspicion, the plug-in couldn’t detect devicons in the runtime, perhaps because you’re using vim plug and I use packer they appear differently.

Can you post the result of this command:
```lua
:lua _G.dump(vim.api.nvim_list_runtime_paths())
```

**Comment by ibhagwan** [comment]
Actually forget it I have an idea how to extract the path better, will have a solution in 15 mins :)

**Comment by ibhagwan** [comment]
Took a bit longer than I thought but my initial idea was close, should be working now :-)

Lmk?

**Comment by krims0n32** [comment]
Fixed. Thanks!

**Comment by ibhagwan** [comment]
If you get a chance and have a large code base try the new multiprocess option on it? performance should be stellar, feel free to report back in #248 :-)

**Comment by krims0n32** [comment]
Yes I have it enabled now :)
