### ISSUE TITLE
[Question] Discrepancy between wiki and readme.

### ISSUE THREAD

**Issue by blmhemu** [ibhagwan/fzf-lua#262]
Wiki lists `vijaymarupudi/nvim-fzf` as dependency
```
use { 'ibhagwan/fzf-lua',
  requires = {
    'vijaymarupudi/nvim-fzf',
    'kyazdani42/nvim-web-devicons'
  }
}
```
But readme does not.
```
use { 'ibhagwan/fzf-lua',
  -- optional for icon support
  requires = { 'kyazdani42/nvim-web-devicons' }
}
```
Which one to follow ? (PS: New to nvim. Sorry if trivial)

**Comment by ibhagwan** [comment]
The dependency was recently dropped, I forgot to update the Wiki, follow the README :)

**Comment by blmhemu** [comment]
Hey ! One more unrelated question. If I need to change just a part of the config, can I do it ? I am getting below error when trying to force vertical preview.

**Comment by nyngwang** [comment]
@blmhemu If you look it closely, the option `preview` is nested inside `winopts = {...}`.

**Comment by blmhemu** [comment]
Sorry for disturbing and thanks for the help! My bad  😑

**Comment by nyngwang** [comment]
@blmhemu Don't worry. The important thing is that you solved the problem. The maintainer of this repo. has also helped me a lot along the way.

**Comment by ibhagwan** [comment]
Ty @nyngwang!

**Comment by ibhagwan** [comment]
> Sorry for disturbing and thanks for the help! My bad expressionless

Don't worry about it @blmhemu, feel free to open any question you have even if you feel it's not the most "sophisticated", we all start somwhere :-)
