### ISSUE TITLE
`live_grep_glob`: lua/fzf-lua/utils.lua:83: E5560: nvim_exec must not be called in a lua loop callback

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#263]
As title. The error message:

```
Error executing luv callback:
...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/utils.lua:83: E5560: nvim_exec must not be called in a lua loop callback
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/utils.lua:83: in function 'warn'
        ...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/utils.lua:158: in function <...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/utils.lua:156>
Press ENTER or type command to continue
```

My settings:

```
rg_opts =
  "--column "..
  "--line-number "..
  "--no-heading "..
  "--case-sensitive "..
  "--hidden "..
  -- Disable: `-u` for .gitignore, `-uu` for hidden files/Dirs, and `-uuu` for binary files.
  "--unrestricted "..
  " "..
  "--max-columns 200 "..
  "--max-filesize 200K "..
  "--max-depth 10 "..
  " "..
  "--glob '!.npm' "..
  "--glob '!.nvm' "..
  "--glob '!.tmux' "..
  "--glob '!.cache' "..
  "--glob '!.vscode' "..
  "--glob '!.local/share' "..
  "--glob '!.config/nvim/plugin' "..
  "--glob '!.Trash' "..
  "--glob '!Library' "..
  "--glob '!Documents' "..
  "--glob '!Pictures' "..
  " "..
  "--glob '!.git' "..
  "--glob '!node_modules' "..
  "--glob '!package-lock.json' "..
  "--glob '!yarn.lock' "..
  "--glob '!tags' "..
  " ",
```

It's strange that I did add the option `--glob '!.Trash'` while the error seems to say that it's trying to access something in the `.Trash/`. As img shown:

<img src="https://user-images.githubusercontent.com/24765272/146364231-dcdf3715-ae43-443a-92a2-e172ab712292.png" width="500">

What I think relevant:

```
-g, --glob <GLOB>...
        Include or exclude files and directories for searching that match the given
        glob. This always overrides any other ignore logic. Multiple glob flags may be
        used. Globbing rules match .gitignore globs. Precede a glob with a ! to exclude
        it. If multiple globs match a file or directory, the glob given later in the
        command line takes precedence.

        As an extension, globs support specifying alternatives: *-g ab{c,d}* is
        equivalet to *-g abc -g abd*. Empty alternatives like *-g ab{,c}* are not
        currently supported. Note that this syntax extension is also currently enabled
        in gitignore files, even though this syntax isn't supported by git itself.
        ripgrep may disable this syntax extension in gitignore files, but it will
        always remain available via the -g/--glob flag.

        When this flag is set, every file and directory is applied to it to test for
        a match. So for example, if you only want to search in a particular directory
        'foo', then *-g foo* is incorrect because 'foo/bar' does not match the glob
        'foo'. Instead, you should use *-g 'foo/**'*.
```

It says `the glob given later in the command line takes precedence.` so I think `--glob '!.Trash'` somehow overwritten.

And consider the last paragraph:

> [...] because 'foo/bar' does not match the glob 'foo'. Instead, you should use `-g 'foo/**'`.

While currently my `"--glob '!.git' "` also works.

**Comment by nyngwang** [comment]
To be more specific, the error always happens when I finished typed `some_key -- *` and about to type the next char.

**Comment by nyngwang** [comment]
I just solved this issue by providing Alacritty _Full Disk Access_ in System Preferences > Security & Privacy > Privacy > Full Disk Access.

**Comment by ibhagwan** [comment]
This error comes from the fact the plugin fails to display a warning message, it's only by chance that the `glob` option made this happen, this is the code where it failed:

```lua
function M.warn(msg)
  vim.cmd('echohl WarningMsg')
  M._echo_multiline("[Fzf-lua] " .. msg)
  vim.cmd('echohl None')
end
```

The reason is neovim cannot call this in certain situations unless wrapped within a `vim.defere_fn` statement, what I'm intested is what was the warning message it was trying to display, I'll try to reporoduce it and get to the source of where this was hapenning and why is this related to disk access.

The interesting thing is that there's no call for `utils.warn` in the `grep|live` code routes.

**Comment by LoydAndrew** [comment]
Don't know if this is a related issue but live_grep_glob stops working `hello --*.go` returns no results.

![Screenshot_2021-12-16_18-35-44](https://user-images.githubusercontent.com/28489428/146411954-9416e79f-5efc-4f53-a5d1-e48a1bebebf3.png)


 The last commit where it's working is d5994bf06245fb58fa817e14388eb7397da73b54

**Comment by ibhagwan** [comment]
> Don't know if this is a related issue but live_grep_glob stops working `hello --*.go` returns no results.
> 
> ![Screenshot_2021-12-16_18-35-44](https://user-images.githubusercontent.com/28489428/146411954-9416e79f-5efc-4f53-a5d1-e48a1bebebf3.png)
> 
> The last commit where it's working is [d5994bf](https://github.com/ibhagwan/fzf-lua/commit/d5994bf06245fb58fa817e14388eb7397da73b54)

Can you run this with `:FzfLua live_grep_glob debug=true` so we can see the underlying command (should be printed in the top line)?

**Comment by LoydAndrew** [comment]
![Screenshot_2021-12-16_18-47-49](https://user-images.githubusercontent.com/28489428/146413648-3c16aabb-857b-4eba-bb3f-2d16e2539461.png)

**Comment by ibhagwan** [comment]
Found the original issue, fzf-lua preview was trying to read a file which the user has no permissions for (`Trash` in your case) and then failing to display the warning message as the nvim API wasn't allowed to be called at that point in time - that's why "Full Disk Access" solved the issue for you as it was no longer failing to access the file.

[The latest commit ](https://github.com/ibhagwan/fzf-lua/commit/18837e117460fe45657d3a0dc37db6c3eb0e4a5f) this commit solves this issue (by wrapping the warning call with `vim.schedule`), in the case of inacessible files the warning message will now appear properly in the `:messages` window, like so:

```sh
[Fzf-lua] Unable to open file '/root/.ssh/config', error: EACCES: permission denied: /root/.ssh/config
```

**Comment by nyngwang** [comment]
@ibhagwan While this suppresses the warning, the problem that those pre-excluded files will be shown when typing `-- *` still exists. And since that users are not sure about whether the keyword is wrapped by other chars or not is the common case, as the demo-video you posted in some issue, you have to write this `-- *foo* -- *bar* ...`, and this is very cumbersome to me. I will prefer a syntax that I can write `-- foo -- bar` and when I'm very sure that a key is not wrapped, I can then write `-- foo --x bar` to match the path `.../fo.../o.../.../bar/...`.

**Comment by ibhagwan** [comment]
> @ibhagwan While this suppresses the warning, the problem that those pre-excluded files will be shown when typing `-- *` still exists. And since that users are not sure about whether the keyword is wrapped by other chars or not is the common case, as the demo-video you posted in some issue, you have to write this `-- *foo* -- *bar* ...`, and this is very cumbersome to me. I will prefer a syntax that I can write `-- foo -- bar` and when I'm very sure that a key is not wrapped, I can then write `-- foo --x bar` to match the path `.../fo.../o.../.../bar/...`.

This is a very specific use case, I expect most users using the `glob` function to know it uses the `--iglob` flag and how it's working, it was implemented to begin with for users who know what it is and requested it.

If you wish to have a different implementation I can expose a config option that you can write your implementaion yourself, i.e.:

```lua
  grep = {
    glob_fn = function(query)
      ..
      return whatever_you_want
    end,
  }
```
