### ISSUE TITLE
Add support for jump list

### ISSUE THREAD

**Issue by mikeslattery** [ibhagwan/fzf-lua#264]
Add support for browsing `:jumps` and `:changes`.  Selection should take you to that location.

See also https://github.com/junegunn/fzf.vim/issues/865

**Comment by ibhagwan** [comment]
Added with preview similar to `marks`, reading the thread you linked I also experienced some inconsistency jumping to the selected item with `norm! <jump> \<C-o.` so I implemented it a bit differently by using the filename where applicable and making the assumption that if the text isn't an accessible file it's probably in the current buffer.

The latter assumption isn't always correct but seems good enough as if non exist the jump is moot anyways.

**Comment by ibhagwan** [comment]
My commit comment closed this issue, I'll reopen it until you try it out and we confirm it works to your liking :-)

```lua
:lua require'fzf-lua'.jumps()
-- or
:FzfLua jumps
```

**Comment by ibhagwan** [comment]
Oops forgot to implement `changes`, took 6 more lines of code...
```lua
:lua require'fzf-lua'.changes()
-- or
:FzfLua changes
```

**Comment by mikeslattery** [comment]
Thanks!  Works great so far.  It's part of my daily workflow now, so I'll let you know if there are any issues.

**Comment by ibhagwan** [comment]
Alright then, closing the issue for now.
