### ISSUE TITLE
Is there a way to disable the default FZF keymaps?

### ISSUE THREAD

**Issue by tamirzb** [ibhagwan/fzf-lua#266]
I have my own FZF bindings, set through the `FZF_DEFAULT_OPTS` environment variable. The problem is that some of these are overwritten by fzf-lua's default bindings.
Is there a way to completely disable fzf-lua's default bindings? I know I could just copy my bindings from `FZF_DEFAULT_OPTS` to my neovim lua config, but I'd rather keep a consistent configuration across both neovim and outside of it, so I'd rather configure this in a single position.

If there is no such way, how about adding a boolean to configure whether to use these default bindings? I don't mind creating a PR myself, but I want to know if it's something that's needed or am I missing something.

**Comment by ibhagwan** [comment]
It’s easy to disable, just put `= false` to every keybind you wish to disable under `keymaps.fzf`, same for the `actions` mapppigns.

**Comment by tamirzb** [comment]
Actually I took a closer look at it and I realized I made a mistake previously. It seems to me that there is a bug with overwriting the FZF keymaps.

First of all, if I follow your advice and put this in my configuration:
```lua
require('fzf-lua').setup({
    keymap = {
        fzf = {
            ["ctrl-u"] = false,
        }
    }
})
```

I get this error message:

```
E5108: Error executing lua ...ig/nvim/plugged/fzf-lua/lua/fzf-lua/providers/module.lua:42: /home/zb/.config/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:106: attempt to index
 local 'v' (a boolean value)
stack traceback:
        [builtin#35]: at 0x7fbcb8e46460
        ...ig/nvim/plugged/fzf-lua/lua/fzf-lua/providers/module.lua:42: in function <...ig/nvim/plugged/fzf-lua/lua/fzf-lua/providers/module.lua:8>
        /home/zb/.config/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:79: in function 'run_command'
        /home/zb/.config/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:87: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

But also, if I just put an empty table there, like this:
```lua
require('fzf-lua').setup({
    keymap = {
        fzf = {}
    }
})
```

FZF just disappears immediately after I open it. I suspect my keymap configuration doesn't actually overwrite the default one in any way, but is rather used instead of the existing one (and that `false` is not a supported value, and that an empty ones gets an error from FZF).

**Comment by ibhagwan** [comment]
It's my bad I recalled incorrectly what I did there, having an empty table is the correct way to go as the keymap table doesn't get merged with the defaults.

I'll have a fix shortly.

**Comment by ibhagwan** [comment]
Both options should work for you now, an empty table as well as `false` as value, though I probably thought about exacrtly this use case when I chose not to merge the bind table with the default config so you can easily just override it with your own table, but I forgot to check for an empty table :-)

Anyways, this should do what you want now:
```lua
require('fzf-lua').setup({
  keymap = {
    fzf = {}
  }
})
```

**Comment by tamirzb** [comment]
Amazing, thank you very very much!
