### ISSUE TITLE
The `resume` resumes itself

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#267]
As title. Have tried it after `live_grep_glob` and `files`, it blinks.

**Comment by ibhagwan** [comment]
I don't understand what this means?

If I run `files` and then `resume` I get `files`, if I run `live_grep_glob` and then `resume` I get `live_grep_glob` - what is happening in your case and what do you expect?

**Comment by nyngwang** [comment]
I have a shortcut to run `FzfLua`. If I run `files`/`live_grep_glob` and then `resume`, the `FzfLua` typed the word "resume" blinks.

**Comment by ibhagwan** [comment]
Can you post your shortcut? what happens if you do it without the shortcut and just run `:FzfLua resume`?

**Comment by nyngwang** [comment]
https://user-images.githubusercontent.com/24765272/146630351-c6ef3cd6-d581-49df-998e-16568a6663b5.mov

And the shortcut:

```
vim.api.nvim_set_keymap('n', '<Leader>j', '<cmd>lua require("fzf-lua").builtin()<CR>', NOREF_NOERR_TRUNC)
```

**Comment by nyngwang** [comment]
> Can you post your shortcut? what happens if you do it without the shortcut and just run :FzfLua resume?

If that then no bug. Now we all know where the bug is.

**Comment by ibhagwan** [comment]
Well of course this isn't goint to work, you're running resume from the `builtin`, `resume` is a global function it saves anything you do, `builtin` is also an fzf-lua window, by running resume from within the builtin you're asking it to resume itself.

You need to change your mapping to:
```lua
lua require("fzf-lua").builtin({ no_global_resume=true })
```

**Comment by ibhagwan** [comment]
I changed this to the default, so you don't need to change your mapping if you updated to the latest commit.

**Comment by nyngwang** [comment]
@ibhagwan Thank you. While I know someone requested this feature, but I still miss the old `files_resume`. There are cases I need to keep/resume two things in parallel: files I was searching(via `live_grep_resume`), and words I was searching(`files_resume`).

**Comment by ibhagwan** [comment]
> @ibhagwan Thank you, this fixes the problem. On the other hand, I know someone requested this `resume` feature, but I still miss the old `files_resume`. There are cases I need to keep/resume two things in parallel: files I was searching(via `live_grep_resume`), and words I was searching(`files_resume`).

Unforutnately, `resume` and `files_resume` can't co-exist as they both use the same `change:execute` event of fzf, there can only be one specified.

However, in your case `live_grep` uses different mechanism for resume (`change:reload`) event so you can switch between the two easily, what you need to do is set your `grep|live_grep` to `no_global_resume = true` and then you can use the `resume` only for `files`.

`live_grep_resume` is still a separate function and should work even with:
```lua
-- First open files
lua require'fzf-lua'.files()
-- This will not overwrite the `files` resume data
:lua require'fzf-lua'.live_grep_resume({ no_global_resume = true })
-- Now if you open `resume`, it should open `files`
lua require'fzf-lua'.resume()
-- You can still open `live_grep_resume` and it will continue where you left of
:lua require'fzf-lua'.live_grep_resume({ no_global_resume = true })
```

You can also add `no_global_resume = true` in the setup under `grep`:
```lua
require'fzf-lua'.setup({
  grep = {
    no_global_resume = true,
  }
})
```
