### ISSUE TITLE
The custom command of `git_status` doesn't work on some cases

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#268]
As title. I have the following config:

```
git = {
  status = {
    actions = {
      ["default"] = actions.file_edit,
      ["ctrl-y"] = function(selected)
        for _, file in ipairs(selected) do
          -- do whatever you want with the file
          vim.fn.system('git add ' .. file)
        end
      end
    },
  }
}
```

I just tested it on the other project and it works. But it fails on the project I'm working on. More info will be added soon.

**Comment by nyngwang** [comment]
Resolved. There are spaces in the file path. I modified the config to:

```
vim.fn.system('git add "' .. file .. '"')
```

**Comment by ibhagwan** [comment]
Btw, the right way to solve this is wrap the filename with `vim.fn.shellescape(file)`, so you can handle all sorts of characters the shell can’t handle without escaping.

**Comment by nyngwang** [comment]
@ibhagwan Thank you!
