### ISSUE TITLE
How to display filename from `files` that is too long?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#269]
As title. And another issue is that is it possible to set something so that these filenames won't be shown. That is: Ignore those results that are just ridiculously related to the keywords I typed. For example in the following img I won't expect that `vim` matches: **V**ers**i**ons/A/**M**odules/. If I could set a distance, e.g. `3` so since `i` and `M` has a distance of `6` (since 6 chars in between, non-inclusive), it wont' match.

<img src="https://user-images.githubusercontent.com/24765272/146669266-2c1898b4-1b1b-4516-bd14-c16fcc8fc3da.png" width="500">

**Comment by ibhagwan** [comment]
You can make your call like this:
```lua
:lua require('fzf-lua').lsp_workspace_symbols({ fzf_opts = { ['--keep-right'] = '' } })
-- or 
:lua require('fzf-lua').lsp_workspace_symbols({ fzf_cli_args = '--keep-right' })
```

See discussion in #151.

**Comment by ibhagwan** [comment]
Closing for now, let me know if the `--keep-right` did not provide an adequte solution.

**Comment by nyngwang** [comment]
Why it's called `lsp_workspace_symbols` while in the img I was using `files`?

**Comment by ibhagwan** [comment]
> I haven't tried the solution you gave, but why it's called `lsp_workspace_symbols` while in the img I was using `files`?

It was an example I copied from #151, you can use the same `fzf_cli_args` in any function.
