### ISSUE TITLE
[Feature Request] I would like to have a floating window to create/add new `filename` under a folder?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#272]
It's just an idea, so I won't describe the details. In my current scenario, I have to use a plugin called `nvim-tree.lua` to create a file under a folder. I will first open the file-tree then navigate to the appropriate place(and probably need to expand some folders) and then hit the shortcut to append the file (it will prompt me in the `:` cmdline about the file name). It's inconvenient for me on the "moving cursor to the right place" part.

The best scenario I can imagine is that I would use some key-comb. to trigger a floating window, and in that window, I would enter part of the parent directory, some candidates will be shown for me to select. Finally, I would hit enter, then it will prompt me the file name(and I can specify any file ext.) I want to create.

**Comment by ibhagwan** [comment]
Out of the scope of this plugin IMO but this shouldn't prevent you from doing your own customiztaion using the `require'fzf-lua'.fzf` and `require'fzf-lua'.fzf_files` API's.

Read #57 if you'd like to engage in writing this :-)
