### ISSUE TITLE
[ Feature Req ] Window hopping

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#274]
Hey there,

maybe this isnt a great idea, but we have a buffers command which changes the current window to the selected buffer. 

Would it make sense to have a "windows" command as well? That sets the current window to the selected on?

**Comment by ibhagwan** [comment]
Not sure I understand exacly what this action would but pretty sure it would just be a couple of `nvim_win_xxx` commands at most of a custom action.

If you can please explain the use case in a bit more detail I'm pretty sure I can help you get the custom action right.

**Comment by ldelossa** [comment]
Use case would be: 

i have two windows side by side, and i want to jump between them.

**Comment by ibhagwan** [comment]
You can already achieve that by changing your buffer action from `buf_edit` to `buf_switch` instead (the one used by `tabs`):

```lua
:lua require'fzf-lua'.buffers({ actions = { ["default"] = require'fzf-lua.actions'.buf_switch } })
```

**Comment by ldelossa** [comment]
Thank you!!

**Comment by nyngwang** [comment]
This is cool!

**Comment by nyngwang** [comment]
> You can already achieve that by changing your buffer action from `buf_edit` to `buf_switch` instead (the one used by `tabs`):
> 
> ```lua
> :lua require'fzf-lua'.buffers({ actions = { ["default"] = require'fzf-lua.actions'.buf_switch } })
> ```

But if I have only one window in a tab, will it fall back to the default behaviour?

**Comment by ibhagwan** [comment]
> But if I have only one window in a tab, would it fall back to the default behaviour (i.e. it change the buffer of the current window the cursor's on)?

Not sure TBH, but you could create your own mapping and test how many tabs are:
```lua
  actions = { ["default"] = function(selected, opts)
    return #vim.api.nvim_list_tabpages() > 1 and actions.buf_switch(selected, opts)
      or actions.buf_edit(selected, opts)
  end
```

**Comment by nyngwang** [comment]
> `    return #vim.api.nvim_list_tabpages() > 1 and actions.buf_switch(selected, opts)`

Why it's `#vim` not `vim` here? Does it matter?

**Comment by ibhagwan** [comment]
Well in your case then, although not perfect, I would do this:
```lua
actions = { ["default"] = function(selected, opts)
  -- switch if possible
  actions.buf_switch(selected, opts)
  -- open the buffer, would do nothing if same buffer
  -- although you could probably add a test here if this is needed
  actions.buf_edit(selected, opts)
end
```

**Comment by nyngwang** [comment]
This is great!
