### ISSUE TITLE
Running `:FzfLua grep_curbuf previewer=bat` gives errors

### ISSUE THREAD

**Issue by shubham-cpp** [ibhagwan/fzf-lua#276]
<details>

<summary>
Neovim Version
</summary>

```bash
NVIM v0.7.0-dev+751-g67bb01ae2
Build type: Release
```

</details>

<details>

<summary>
Packer config
</summary>

```lua
use({ "ibhagwan/fzf-lua", event = "BufWinEnter", config = get_config("fzf-lua") })
```

</details>

<details>

<summary>
Fzf-lua config
</summary>

```lua
local fzf = require("fzf-lua")
local actions = require("fzf-lua.actions")
fzf.setup({
	fzf_opts = { ["--info"] = "hidden" },
	icons = {
		["?"] = { icon = "?", color = "magenta" },
		["M"] = { icon = "★", color = "red" },
		["D"] = { icon = "✗", color = "red" },
		["A"] = { icon = "+", color = "green" },
	},
	files = {
		winopts = {
			height = 0.45,
			width = 0.32,
			row = 0.52,
			col = 0.47,
		},
		previewer = { _ctor = false },
		actions = { ["alt-enter"] = actions.file_tabedit },
	},
	buffers = { actions = { ["alt-enter"] = actions.file_tabedit } },
	blines = { actions = { ["alt-enter"] = actions.file_tabedit } },
	bcommits = { actions = { ["alt-enter"] = actions.file_tabedit } },
})

```

</details>

## Error 
![image](https://user-images.githubusercontent.com/31388020/147360424-5abb3434-c70c-4c7e-bd43-aa19e2d5e5e4.png)

### Notes
This error only occurs for bat, not for cat or builtin

**Comment by ibhagwan** [comment]
Looks like you're using `~/.config/bat/config`, with the `--italic-text` option which is also specified by the `fzf-lua` config, you need to either modify fzf-lua default `bat` preview command under `previewers.bat.cmd` or sepcify that you're using a config file instead.

See #28 for more details.

**Comment by ibhagwan** [comment]
To make things simpler just add this to your setup function:
```lua
require'fzf-lua'.setup {
  previewers = {
    bat = {
      cmd = "bat",
      args = "", -- delete all args so it uses your config instead
    },
  }
}
```

**Comment by shubham-cpp** [comment]
Sorry for this stupidity

**Comment by ibhagwan** [comment]
> Sorry for this stupidity

Don't worry about it! it's not supidy at all, how on earth could you have guessed this :-)

**Comment by shubham-cpp** [comment]
Yes, I did search issues similar to this but #28 might have gone under my eyes. Next time I'll check it twice
