### ISSUE TITLE
`bat` preview not working when `~/.config/bat/config` exists

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#28]
I have a file `~/.config/bat/config`:

```
# Set the theme
--theme="GitHub"

--color=always

# Show line numbers, Git modifications, file header and grid
--style="numbers,changes,header,grid"

# Use italic text on the terminal (not supported on all terminals)
--italic-text=always

# Use "gitignore" highlighting for ".ignore" files
--map-syntax .ignore:.gitignore
```

If I use `fzf-lua` I get `--italic-text` provided more than once:

<img width="837" alt="Screen Shot 2021-07-30 at 9 16 30 AM" src="https://user-images.githubusercontent.com/1813121/127674420-f1d5d3e0-a01b-46e6-b647-651f6035187b.png">

### Workaround

The solution for me was to explicitly set the `preview_cmd`, e.g.:

```
    use {
      'ibhagwan/fzf-lua',
      requires = {
        'kyazdani42/nvim-web-devicons', -- optional for icons
        'vijaymarupudi/nvim-fzf',
      },
      config = function()
        require'fzf-lua'.setup {
          preview_cmd = 'bat',
        }
      end,
    }
```

I thought I'd open an issue to share in case you wanted to fix this / if someone else was running into the same issue.

**Comment by ibhagwan** [comment]
Tysm, I didn’t know some options could conflict with others, I’ll fix it either by removing the `—italic-text` option or perhaps there is a flag that tells bat to ignore the config file.

**Comment by kdheepak** [comment]
Just removing `--italic-text` still may not resolve other conflicts. The easiest change is probably that bat_opts` should be empty by default?

https://github.com/ibhagwan/fzf-lua/blob/ea38de4d7c8b2a7a718b712ddd8530e71f4b7270/lua/fzf-lua/config.lua#L66

I imagine most people that use `fzf` with a preview either have a `~/.config/bat/config` or have aliased their `bat` to be `bat --italic-text=always ...`. 

Alternatively, you can check if `~/.config/bat/config` exists, and if it doesn't you can use the `bat_opts` that you are using right now.

**Comment by ibhagwan** [comment]
Probably better to find that option that ignores the config file, I’m sure there has to be one, I’ll look for it later.

Testing for the config file in `$XDG_DATA_HOME` is also a good option, I plan to rework the preview part anyways and also add other preview options I might add it then.

**Comment by kdheepak** [comment]
https://github.com/sharkdp/bat#output-style

It looks like you can use the `BAT_STYLE` environment variables to override the config file. So you can probably just pass `bat_opts` to the environment variable when you spawn the bat process.

**Comment by kdheepak** [comment]
There’s also `export BAT_CONFIG_PATH="/path/to/bat.conf"`, and you can put `bat_opts` in a file in this repo and use this instead.

**Comment by ibhagwan** [comment]
One of these will easily solve it, tysm :)

I’ll leave this issue open until I commit the fix.

**Comment by ibhagwan** [comment]
Should be fixed in latest commit, lmk if otherwise.

**Comment by kdheepak** [comment]
Hi @ibhagwan, this fix works in that it doesn't cause the bug but it has made it such that I cannot use my `~/.config/bat/config`. Any suggestions?

**Comment by ibhagwan** [comment]
Let me think about it, I’m rewriting the previewer code completely as we speak, I’ll address it there.

**Comment by ibhagwan** [comment]
Just commited a fix for this, look at the new setup options for previewers [in the README](https://github.com/ibhagwan/fzf-lua#Customization), in your case I'd set it up as follows:
```lua
previewers = {
...
    bat = {
      cmd             = "bat",
      args            = "",
      theme           = nil,
      config          = nil,            -- nil uses $BAT_CONFIG_PATH
    },
...
```
or
```lua
```lua
previewers = {
...
    bat = {
      cmd             = "bat",
      args            = "",
      theme           = nil,
      config          = "~/.config/bat/config"
    },
...
```
```

**Comment by ahmedelgabri** [comment]
> Just commited a fix for this, look at the new setup options for previewers [in the README](https://github.com/ibhagwan/fzf-lua#Customization), in your case I'd set it up as follows:
> 
> ```lua
> previewers = {
> ...
>     bat = {
>       cmd             = "bat",
>       args            = "",
>       theme           = nil,
>       config          = nil,            -- nil uses $BAT_CONFIG_PATH
>     },
> ...
> ```
> 
> or
> 
> ```lua
> ```lua
> previewers = {
> ...
>     bat = {
>       cmd             = "bat",
>       args            = "",
>       theme           = nil,
>       config          = "~/.config/bat/config"
>     },
> ...
> ```

Tried both & I get an empty preview. 

<img width="1345" alt="Screenshot 2021-08-30 at 20 40 31" src="https://user-images.githubusercontent.com/63876/131388422-18da9324-3f29-4055-adf0-1d68022b9728.png">

**Comment by ibhagwan** [comment]
> > Just commited a fix for this, look at the new setup options for previewers [in the README](https://github.com/ibhagwan/fzf-lua#Customization), in your case I'd set it up as follows:
> > ```lua
> > previewers = {
> > ...
> >     bat = {
> >       cmd             = "bat",
> >       args            = "",
> >       theme           = nil,
> >       config          = nil,            -- nil uses $BAT_CONFIG_PATH
> >     },
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```lua
> > ```lua
> > previewers = {
> > ...
> >     bat = {
> >       cmd             = "bat",
> >       args            = "",
> >       theme           = nil,
> >       config          = "~/.config/bat/config"
> >     },
> > ...
> > ```
> 
> Tried both & I get an empty preview.
> 
> <img alt="Screenshot 2021-08-30 at 20 40 31" width="1345" src="https://user-images.githubusercontent.com/63876/131388422-18da9324-3f29-4055-adf0-1d68022b9728.png">

It doesn't seem like you're running the bat previewer, this seems like it's using the new builtin default previewer, in which case there might an issue here I need to fix but I'm confused if this is the default previewer why is there no title or scrollbar at the right side, if that's the case let's open a new issue about the default previewer so this doesn't get lost.

If you want to use the `bat` previewer please add `default_previewer   = "bat"` to your setup function.
