### ISSUE TITLE
grep_project doesn't support loading to quickfix list

### ISSUE THREAD

**Issue by SimonMandlik** [ibhagwan/fzf-lua#280]
If I select more than one file in `:FzfLua files` and press Enter, a quickfix list is populated.

Is it possible to do a similar thing for Rg results? With default settings, a quickfix is populated, but with buffers named after matched lines, not after files they are contained in.

Setting something like

```
...
grep= {
actions = {
            ["default"] = actions.grep_sel_to_qf,
            }
}
...
```

didn't help either.

This is a functionality I use quite a lot and is possible in `fzf.vim` (https://github.com/junegunn/fzf.vim/issues/185). Is there a better way to achieve this with `fzf-lua`?

**Comment by ibhagwan** [comment]
It should be the default behavior, all files providers (grep and git included) use the same default action `actions.file_edit_or_qf` which sends anything more than one entry to the quick fix list.

Does it work for any other `grep` or `live_grep` provider? If not this is a bug and I’ll fix it.

**Comment by SimonMandlik** [comment]
It works like that for `files` but not for `grep_project`.

`files`:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/16707112/147420984-a902c585-0ee2-4629-b600-a06ffcf4d386.png">

Pressing <CR> takes me to:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/16707112/147420994-b058cb08-5f02-4188-8830-db648acc59f1.png">

whereas in `grep_project`:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/16707112/147420999-6bb71ccc-515f-406c-bdd1-89ae6dec1622.png">

Pressing <CR> opens new buffers named as matched lines, which is not very useful:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/16707112/147421011-60c601f4-1296-469a-ab1a-99a12cd7e903.png">

**Comment by ibhagwan** [comment]
The default action should be exactly as files, I’ll test it later why this isn’t the case, in the meantime try the below.


This should open any selection **over one item** in the quickfix list:
```lua
grep = {
  actions = {
      ["default"] = actions.file_edit_or_qf
   }
}
```

This should open any selection **one item or more** in the quickfix list:
```lua
grep = {
  actions = {
      ["default"] = actions.file_sel_to_qf
   }
}
```

**Comment by ibhagwan** [comment]
I just tried it and the default action sends any selection over one item into the qf, could this be a configuration issue on your end? can you try with an empty config?

**Comment by ibhagwan** [comment]
Reading the OP again, this seems like a bug, it might be related to the fact you're missing the column number in the `grep|rg` output, can you post your `grep` customiztion?

If you're using `rg` make sure you have both `--column --line-number` in the command?

I'll test later when I have more time why this happens and fix it.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b35d03f4ee4b21f406bbfc0eac4edfa915a63d5b this should fix it.

**Comment by billyvg** [comment]
@ibhagwan this doesn't seem to work for me for `grep_project`:

![image](https://user-images.githubusercontent.com/79684/181305999-51d52e30-edd7-4def-81a8-46070126b0ad.png)

And then if I `:copen`, it's blank:
![image](https://user-images.githubusercontent.com/79684/181306061-f45512f3-541f-43a0-a4b0-61ba16b09c5d.png)


I can use `alt-q` to add selection to qf, but I would like to add *all* results to qf so that I can find/replace.

**Comment by ibhagwan** [comment]
> I can use alt-q to add selection to qf, but I would like to add all results to qf so that I can find/replace.

If you can add selection you can also add all by pressing `<A-a>` and then `<C-q>`, what do you mean exactly by “not working for me”?

If you mean you wish to send all to quickfix when there is no selection at all (similar to Telescope), take a look at  #416.

**Comment by billyvg** [comment]
Ah, `<A-a>` + `<A-q>` does what I want - will take a look at #416 as well, thanks!
