### ISSUE TITLE
Display cwd in `files` and other queries

### ISSUE THREAD

**Issue by SimonMandlik** [ibhagwan/fzf-lua#281]
It would be nice to have an option to display cwd in `files` and other query types. Fzf.vim does it like this:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/16707112/147421078-5de6c013-5d12-4b74-9207-cc9d7997f8bc.png">

whereas fzf-lua like this

<img width="248" alt="image" src="https://user-images.githubusercontent.com/16707112/147421126-0222d4d1-39b7-4d1f-a05c-b5a246b6a3a5.png">

Displaying cwd helps with navigation across the project. Sometimes, I work on a project with `git submodule` in it and have two separate vim instances for each. The fastest way to check whether I'm in the correct instance is by checking the first line in fzf. There is plenty of other options to do that, but afaik they all require displaying cwd all the time (e.g. in status line) or getting out of the fzf window.

**Comment by ibhagwan** [comment]
`cwd` is displayed as header line when supplied to the provider, it doesn’t show otherwise.

Test it with:
```lua
:FzfLua files cwd=<any directory>
```

I didn’t test it as I’m not near my computer but I think it should work too if you supply the current directory as cwd:
```lua
:lua require'fzf-lua'.files({ cwd=vim.loop.cwd() })
```

I may have disabled the header if cwd matches the current directory, let me know if  this doesn’t work for you I’ll enable it, the above should work for `git` and `grep` as well.

**Comment by ibhagwan** [comment]
```lua
:lua require'fzf-lua'.files({ cwd=vim.loop.cwd() })
```
Ok, just checked the code the above only works when the current working directory differs from the current one, if this is important to you I can add an option to force displaying the `cwd` in the header.

This is how it looks like when cwd differs from the current working dir:
![screenshot-1640562208](https://user-images.githubusercontent.com/59988195/147422601-d98de831-99bf-4354-8637-839c91eee71a.png)

**Comment by ibhagwan** [comment]
Latest commit added new option to force display the `cwd` header line regardles of your current working directory:

```lua
:lua require'fzf-lua'.files({ show_cwd_header=true })
-- or
:FzfLua files show_cwd_header=true
-- can also be used to hide the header when not wanted:
:lua require'fzf-lua'.files({ show_cwd_header=false, cwd="~/.config/nvim" })
```
