### ISSUE TITLE
Preview binary test fails when filename contains lua string pattern special characters

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#285]
<details collaps>
<summary>NeoVim Version Info.</summary>
<code>NVIM v0.7.0-dev+792-gc46f7caad</code>
<br>
<code>Build type: Release</code>
<br>
<code>LuaJIT 2.1.0-beta3</code>
</details>

## Problem

As title. I just tried the new option `show_cwd_header=true` mentioned in #281 . While I got an error as shown in the following pic:

<img src="https://user-images.githubusercontent.com/24765272/147670524-7c211e41-2818-4b40-aba2-9c46dbe48029.png" width="800">

And I'm pretty sure that this is because I recently wrote a very little plugin myself (followed your advice to learn lua). When I commented out my lines of the plugin, the error disappears.

I guess maybe adding one more condition like `and vim.opt.filetype ~= "..."` would solve it. But I don't know what to add.

Here is the code:

```
vim.cmd'au CursorHold * pwd'
vim.cmd'au BufEnter * call v:lua.change_cwd_to_grandparent()'
vim.api.nvim_set_keymap('n', '<Leader>prr', '<cmd>lua _G.reset_project_root(); print("Project Root Has Been Reset"); _G.change_cwd_to_grandparent()<CR>', NOREF_NOERR_TRUNC)
_G.__PROJECT_ROOT_CONST = {
  "GitHub",
  "GitHub%-2",
}
function _G.reset_project_root()
  for k in pairs(_G.__PROJECT_ROOT) do
    local found = false
    for kk in pairs(_G.__PROJECT_ROOT_CONST) do
      if k == kk then
        found = true
        break
      end
    end
    if not found then
      _G.__PROJECT_ROOT[k] = nil
    end
  end
end
vim.api.nvim_set_keymap('n', '<Leader>pra', '<cmd>lua table.insert(_G.__PROJECT_ROOT, vim.fn.input("Extend Project Root: ")); _G.change_cwd_to_grandparent()<CR>', NOREF_NOERR_TRUNC)
_G.__PROJECT_ROOT = {
  "GitHub",
  "GitHub%-2",
}
function _G.change_cwd_to_grandparent()
  if (
    -- Don't use `string.find` or you will match when `vim.bo.buftype` is `''` empty string!
    vim.bo.buftype ~= "terminal"
    and vim.opt.filetype ~= "dashboard"
    and vim.opt.filetype ~= "NvimTree"
  ) then
    local test_path = "%:p:h"
    local count = 0
    while (
      count+1 <= 2
      and string.len(vim.fn.expand(test_path .. ":h")) >= string.len(vim.fn.expand("$HOME"))
    ) do
      local found_root = false
      for idx = 1, #_G.__PROJECT_ROOT do
        local _, last = string.find(vim.fn.expand(test_path .. ":h"), _G.__PROJECT_ROOT[idx])
        if string.len(vim.fn.expand(test_path .. ":h")) == last then
            found_root = true
            break
        end
      end
      if found_root then break end
      test_path = test_path .. ":h"
      count = count + 1
    end
    vim.api.nvim_set_current_dir(vim.fn.expand(test_path))
  end
end
```

**Comment by nyngwang** [comment]
OK after some tests I just realized that it's the filename `[1][98f3...].xml` that causes the error. But I still don't know how to fix the bug.

**Comment by ibhagwan** [comment]
> I just tried the new option `show_cwd_header=true`

This bug is not related to the above option, the function that fails seems to be `vim.fn.expand` (`utils.lua:148`) which doesn't like the `[]` characters found in the filename (they are "special" in lua string patterns), I'll do some testing the fix might be as simple as lua-escaping the special characters `[ -> %[` or `] -> %]`, already have a function for that:

https://github.com/ibhagwan/fzf-lua/blob/3eb5baa6e9beff2fdc51c6152707206a0ab80a26/lua/fzf-lua/utils.lua#L126-L133

**Comment by ibhagwan** [comment]
I'm not sure if this is intended neovim behavior or not but it seems like a neovim bug, it has no issues with the hypeh symbol but when it's in between 2 digits it fails with `Vim:E944: Reverse range in character class`:

```lua
:lua print(vim.fn.expand("~/file[2-1].ext"))
-- Fails with:
E5108: Error executing lua Vim:E944: Reverse range in character class
stack traceback:
        [C]: in function 'expand'
        [string ":lua"]:1: in main chunk
```
But this works:
```lua
:lua print(vim.fn.expand("~/file[2\\-1].ext"))
```

In any event, the latest commit fixes this: https://github.com/ibhagwan/fzf-lua/commit/9a71718c1e359987f77d7e65331c076b3e622c2e
