### ISSUE TITLE
Assign a number for each entry in the result list?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#286]
As title. I would like to know how many entries I have passed through.

<img src="https://user-images.githubusercontent.com/24765272/147808296-b97e4a7e-7f47-4049-a870-696cafd1d257.png" width="600">

**Comment by ibhagwan** [comment]
This would require adding a formatting function that would modify entries on input and also handle the modified format upon preview/selection, similar thing was requested in #158.

Unless someone decides to do this themselves and submit a PR I have no plans on adding such functionality myself.
