### ISSUE TITLE
Error When Running Commands

### ISSUE THREAD

**Issue by JuniorSuperTux** [ibhagwan/fzf-lua#288]
Executing commands such as files, blines, lines, grep, tabs, buffers, and more causes the following error:
```
Error executing vim.schedule lua callback: ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:69: Vim(mkview):E32: No file name 
```
Note: I'm using the example config in the README

**Comment by ibhagwan** [comment]
> Note: I'm using the example config in the README

Which parts? did you copy all if it?

It's pretty hard to understand from this description what's going on, it seems that this happens due to a preview failure:

- Can you try without preview (either set `winopts.preview.hidden = 'hidden'` or press `<F4>` to close
- Can you identify which files cause this issue and if there's something unique in these files (special chars, spaces, etc)
- Does this also happen if you switch to `bat` previewer (set `winopts.preview.default = 'bat'`).

**Comment by JuniorSuperTux** [comment]
> Can you try without preview (either set winopts.preview.hidden = 'hidden' or press <F4> to close
I notice that every time I open a window with previewer, the previewer overlaps with the selection window. The size of the previewer is also strange. The first time pressing F4 fixes that, but the normal size just stayed that way (F4 doesn't disable the previewer).
Setting `winopts.preview.hidden = 'hidden'` disabled the previewer, and errors are gone.
> Can you identify which files cause this issue and if there's something unique in these files (special chars, spaces, etc)
Every file is the same. Even empty files.
> Does this also happen if you switch to bat previewer (set winopts.preview.default = 'bat').
No, it doesn't happen after setting the previewer to bat. But in some cases the previewer used isn't bat. It's still the default previewer with the errors.

**Comment by ibhagwan** [comment]
From the screenshot it seems you modified at least some parts of the default config, the default border is `rounded` and the border in the screenshot seems like `single`.

Although this should never happen I tend to think this is a configuration related isssue (probablt `winopts` related), can you try with no configuration at all, just an empty `setup` function:
```lua
require'fzf-lua'.setup {}
```

If this does work try to add your configuration sections one by one until we find the offending lines.

It would also be helpful if you can post your exact configuration here so I can try to reproduce it as well.

**Comment by JuniorSuperTux** [comment]
Even with no configurations at all, the same error still exists. And what happens are the same as my first and second comment. Perhaps this plugin requires Neovim V0.6? My `nvim --version` output is as the following:
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-PzR5es/neovim-0.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-PzR5es/neovim-0.5.1/build/config -I/build/neovim-PzR5es/neovim-0.5.1/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-PzR5es/neovim-0.5.1/build/src/nvim/auto -I/build/neovim-PzR5es/neovim-0.5.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by ibhagwan** [comment]
>In the config in the README there's something like this:
>```lua
>    border           = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
>```

Correct but this actually does further confirm what I was saying regarding `single`, look at the corners how they lool like in my setup vs yours (rounded edges vs sharp edges).

Mine:
![screenshot-1641063728](https://user-images.githubusercontent.com/59988195/147858148-03812704-c4ce-439e-aa34-d295f56a8a1b.png)

Yours:
![screenshot-1641063767](https://user-images.githubusercontent.com/59988195/147858161-123266bd-73b9-4c47-9c3a-8ff2888a9942.png)


**Regarding neovim version requirements:**

>Even with no configurations at all, the same error still exists. And what happens are the same as my first and second comment. Perhaps this plugin requires Neovim V0.6?

I test every commit against both `0.5` and `0.5.1` app images from [neovim releases page](https://github.com/neovim/neovim/releases) and it works fine, the only requirement is `neovim > 0.5`, just tested with the below and it works:

```console
:version
NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wa
ll -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototyp
es -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATE
D_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner
/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr
/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/bu
ild/include
Compiled by runner@fv-az87-829

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

I do see difference in the compilation flags though, would you be able to download the [official neovim 0.5.1 appimage](https://github.com/neovim/neovim/releases/download/v0.5.1/nvim.appimage) and test against it?

Would also be helpful if you can test against [0.6.1 appimage](https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage)

This issue is the only ever reported with this behavior, I'd like to get to the bottom of it.

**Comment by ibhagwan** [comment]
I think I may have some lead here, it seems that `nvim_create_buf` either fails or does not return a buffer number in your version of neovim, can you run `:help nvim_create_buf` and post the result here, should look something like:

```help
nvim_create_buf({listed}, {scratch})                       *nvim_create_buf()*
                Creates a new, empty, unnamed buffer.

                Parameters: ~
                    {listed}   Sets 'buflisted'
                    {scratch}  Creates a "throwaway" |scratch-buffer| for
                               temporary work (always 'nomodified'). Also sets
                               'nomodeline' on the buffer.

                Return: ~
                    Buffer handle, or 0 on error

                See also: ~
                    buf_open_scratch
```

Also run:
```lua
:lua print(vim.api.nvim_create_buf(false, true))
```

And let me know what is the result of the above code (should return a number)?

**Comment by JuniorSuperTux** [comment]
> I think I may have some lead here, it seems that `nvim_create_buf` either fails or does not return a buffer number in your version of neovim, can you run `:help nvim_create_buf` and post the result here, should look something like:

It looks exactly like yours.

> And let me know what is the result of the above code (should return a number)?

Returned number 8.

**Comment by JuniorSuperTux** [comment]
Test against 0.6.1 AppImage:

```
Error executing vim.schedule lua callback: ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:69: Vim(mkview):E32: No file name                                                        
stack traceback:                                                                                                                                                                                
        [C]: in function 'nvim_win_set_buf'                                                                                                                                                     
        ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:69: in function 'set_tmp_buffer'                                                                                            
        ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:79: in function 'clear_preview_buf'                                                                                         
        ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:118: in function 'display_entry'                                                                                            
        ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:154: in function 'fn'                                                                                                       
        ...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/shell.lua:68: in function 'fn'                                                                                                        
        ...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/shell.lua:40: in function <...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/shell.lua:39>     
```

Testing against 0.5.0 AppImage:
```
Error executing vim.schedule lua callback: ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:69: Vim(mkview):E32: No file name    
```

Testing against 0.5.1 AppImage:
As 0.5.0

**Comment by ibhagwan** [comment]
I’m wondering if this is related to your neovim config (`autocmd`’s?) or another plugin interaction, would you be able to test with no other config other than this [minimal init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua), note you’d have to remove (or move) all other files out of `~/.config/nvim` and save this file as `init.lua`, the rest should happen automatically once you start neovim.

**Comment by JuniorSuperTux** [comment]
I can confirm that this is not a problem related to this plugin itself now. Removing all my config files and using only the minimal config file of this plugin seems to work. Do you have any advice on which kind of plugin might be causing this issue?

**Comment by ibhagwan** [comment]
> I can confirm that this is not a problem related to this plugin itself now. Removing all my config files and using only the minimal config file of this plugin seems to work. Do you have any advice on which kind of plugin might be causing this issue?

Thank you for your patience debugging this, unfortunately without seeing your config or list of plugins it's very hard for me to try to guess, this usually comes down to some unnecessarily intrusive `autocmd` that manipulates new buffers (messing up with the creation of the preview buffer in our case).

As painful as that may be there's one way to find out and that is adding config sections back one by one and testing each time to see which part causes the issue (might not necessarily be a plugin).

I'll leave this issue open until you figure out the cause, perhaps there's a workaround or an easy fix I can direct you to add to your config.

**Comment by JuniorSuperTux** [comment]
I found out what's causing the issue... should have noticed it already.
I have the following for saving folds:
```vim
  autocmd BufWinLeave * mkview
```
This is what was causing the issue. The filetype of the preview window differs from file to file, so I don't know how I can exclude the autocmd for the preview window. Do you have any suggestion on how I could exclude the preview window?

**Comment by ibhagwan** [comment]
I don't know the purpose of running `mkview` but my first instinct would be to limit the execution of the `autocmd` only in buffers where you need it and exclude everywhere else.

For exmaple, you can use this function to determine if a window is floating:
```vim
function! IsFloating(id) abort
    let l:cfg = nvim_win_get_config(a:id)
    return !empty(l:cfg.relative) || l:cfg.external
endfunction
```

And then run the autocmd only if the window is not floating:
```vim
autocmd BufWinLeave * if | !IsFloating(0) | mkview | endif
```

I didn't test this so I can't guarantee this works, there could be many different approaches depending on what you're trying to acieve, maybe something similar to the above that checks if the buffer is hidden or scratch, read `:help scratch` and `:help hidden` to learn more how to achieive what you need.

**Comment by JuniorSuperTux** [comment]
Hmm, the config doesn't seem to work. It's now showing error messages when using nvim-cmp:
```
Error executing vim.schedule lua callback: ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/window.lua:188: Vim(if):E15: Invalid expression: | !IsFloating(0) | mkview | endif```

**Comment by ibhagwan** [comment]
I’m not sure why as nvim-cmp also uses a float for the menu.

I would try to find a different event than `BufLeave` and go on a different route altogether achieving what you’re trying to do.
