### ISSUE TITLE
Is there a way to get oldfiles show paths relative to current directory when `cwd_only = true`?

### ISSUE THREAD

**Issue by mapperr** [ibhagwan/fzf-lua#289]
Sometimes I have projects buried in my filesystem, so opening oldfiles I see the fzf popup showing me something like this:

```
/home/user/directory/subdirectory/project/src...
/home/user/directory/subdirectory/project/src/...
/home/user/directory/subdirectory/project/README.md
/home/user/directory/subdirectory/project/src/...
```

It can be handy to have a less cluttered popup for old files when `cwd_only = true` using relative paths.

**Comment by ibhagwan** [comment]
You can force removal of a certain prefix with the `cwd` argument:

```lua
:lua require'fzf-lua'.oldfiles({ cwd = "~" })
-- or
:FzfLua oldfiles cwd=~
-- In your case
:lua require'fzf-lua'.oldfiles({ cwd = "~/directory/subdirectory" })
```

**Comment by nyngwang** [comment]
@mapperr: If you're using a plugin for filetree then there probably would be an option to toggle what you want to achieve. E.g. I'm using nvim-tree.lua, and the two options: `udpate_cwd` and `update_to_buf_dir.enable` look promising.

**Comment by mapperr** [comment]
I took @ibhagwan suggestion and mapped my oldfiles call this way:

`map("n", "<space>u", ":lua require'fzf-lua'.oldfiles({ cwd = vim.fn.getcwd() })<CR>")`

and it works as expected.

@nyngwang I don't know, I wanted something independent of other plugins, so the solution above is a perfect fit for me.


Thx to both! : )
