### ISSUE TITLE
Show `grep` string in UI

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#29]
When running `grep_cword`, it would be nice to show what cword is currently being grepped for in the UI somewhere. Sometimes I run it and don't realize that the search isn't what I want until I look at the highlighted text as part of the search.

**Comment by ibhagwan** [comment]
Good idea, I’ll add it as a header line in fzf.

**Comment by ibhagwan** [comment]
Added this functionality by default to `grep_cword`, `grep_cWORD` and `grep_visual`, if you want to disable it or control the prefix string (`no_header = true` will disable this functionality):

```lua
:lua require('fzf-lua').grep_cWORD({ no_header = false, search_header = "searching" })
```
