### ISSUE TITLE
How to detect that the cursor is on the input field of `files`, `history`, ... etc.?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#290]
As title.

**Comment by ibhagwan** [comment]
Not sure what you're trying to achieve, try `:help nvim_win_get_cursor` and `:help nvim_list_wins()`.

**Comment by nyngwang** [comment]
I want to change the current working directory only when the cursor is not on the floating window/terminal of fzf-lua.

**Comment by ibhagwan** [comment]
I would recommend using an `autocmd` instead and checking the window is either floating window or that it's `filetype=fzf`.

**Comment by nyngwang** [comment]
Sorry for my vague question. I just resolved this problem: A plugin I created has a bug related to another plugin called `FTerm.nvim`. And I was detecting `vim.opt.filetype` while the correct one should be `vim.bo.filetype`. And that `filetype=fzf` is helpful for me in the future debugging.

**Comment by nyngwang** [comment]
For future readers:

I just encountered this hours ago to fix a plugin. You can use `vim.api.nvim_win_get_config(0).relative == ""` to check that it is **NOT** a floating window.
