### ISSUE TITLE
[Fzf-lua] No diagnostics found

### ISSUE THREAD

**Issue by RCSalomao** [ibhagwan/fzf-lua#292]
Hello,

at first the functions **FzfLua lsp_document_diagnostics** and **FzfLua lsp_workspace_diagnostics** were working as intended showing the diagnostics from the document or workspace, respectively. But recently, even if the lsp reports the presence of diagnostics errors and warnings, these both functions show nothing.
in :messages it only appears:
[Fzf-lua] No diagnostics found
[Fzf-lua] No workspace diagnostics found
I know that on the last days the interface for vim.lsp.diagnostic has changed to vim.diagnostic. Is it the reason that FzfLua lsp_document_diagnostics and lsp_workspace_diagnostics are showing nothing?

By the way, thanks a lot for the plugin. It's really good.

**Comment by ibhagwan** [comment]
Actually the commit just before the latest (https://github.com/ibhagwan/fzf-lua/commit/41b657e823f3f0fdfe199450e17fa1e893a1eaed) made the necessary adjustments for the new `vim.diagnostic` interface but I made a small error which made it seem as if there were no diagnostics at certain scenarios.

Should be fixed now :-)

**Comment by ibhagwan** [comment]
> By the way, thanks a lot for the plugin. It's really good.

And Ty <3

**Comment by RCSalomao** [comment]
Oh yes, it's working back again.
Thanks for the speedy fix c:
