### ISSUE TITLE
Show key mappings in popup while using fzf

### ISSUE THREAD

**Issue by miki725** [ibhagwan/fzf-lua#294]
First thank you for this plugin! I was just switching from `fzf.vim` to more lua-centric setup. Telescope and this package were my top contenders. This package won hands down in speed! Telescrope ran out of memory or was pretty slow trying to search large tags files whereas fzf handled it like a champ.

One thing which I did find appealing in Telescope as a newcomer is the ability to show a popup with all the keyboard shortcuts while using Telescope. You can see its simply `?` in [key mappings](https://github.com/nvim-telescope/telescope.nvim#default-mappings).

Might be useful feature to add here as well for new users until the shortcuts are memorized. Thoughts?

**Comment by ibhagwan** [comment]
Ty for the kind words @miki725.

It’s a great idea, it would have to be dynamically generated though as each user has different bindings, I’ll leave this issue open until I get inspired enough one day to do it :)

**Comment by ibhagwan** [comment]
Happy to say this was added last commit, check it out by pressing `<F1>` (default, modifiable) on any fzf-lua popup.

Note that if you modified the default bindigns you have to expclicitly add this new bind under `keymap.builtin` as the default table here doesn't get merged:
```lua
keymap = {
    builtin = {
      ["<F1>"] = "toggle-help",
      -- rest of your binds
    }
  }
```

And this is how it looks like:

![image](https://user-images.githubusercontent.com/59988195/149610865-63bdd11d-6a9a-47b4-b11d-16a8eb274eb3.png)


As you can see from the screenshot I have one custom bind action that doesn't have proper text (`ctrl-y`), this is easy to fix by registering your custom functions with:

```lua
require'fzf-lua.config'.set_action_helpstr(<custom function>, '<help string>')
```

**Comment by miki725** [comment]
this looks great! can confirm after update it works without issues for me. didnt expect it so fast. thank you!

**Comment by ibhagwan** [comment]
> this looks great! can confirm after update it works without issues for me. didnt expect it so fast. thank you!

Happy you found it useful, it’s a great feature, ty for the idea :)

**Comment by nyngwang** [comment]
This is awesome!
