### ISSUE TITLE
change cursor shape

### ISSUE THREAD

**Issue by dripware** [ibhagwan/fzf-lua#296]
is it possible to change how the cursor looks?
i want to change it from looking like this ` █ `
to this ` | `

**Comment by ibhagwan** [comment]
I haven’t tested this but it seems you can change the the cursor shape in the terminal using `guicursor`:
https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal

If this does work you can use `setlocal guicursor` in the `winopts.on_create` function which runs each time the fzf-lua main window is created.

Referring to this part of the README:
```lua
    on_create = function()
      -- called once upon creation of the fzf main window
      -- can be used to add custom fzf-lua mappings, e.g:
      --   vim.api.nvim_buf_set_keymap(0, "t", "<C-j>", "<Down>",
      --     { silent = true, noremap = true })
    end,
```

**Comment by dripware** [comment]
it seems like changing the cursor shape is not possible in neovim's terminal yet. [](url)
