### ISSUE TITLE
Why the builtin file previewer is slower than telescope?

### ISSUE THREAD

**Issue by dripware** [ibhagwan/fzf-lua#298]
the builtin file previewer with treesitter syntax highlighting is slower than telescope builtin previewer

**Comment by ajitid** [comment]
Shame that I still see a flickering effect even when I keep delay to 0, I really like this plugin. @ibhagwan is there an option to not to keep showing previous file preview until the next one is loaded. Maybe then this flickering will disappear:

![anim-rg](https://user-images.githubusercontent.com/26769888/155058167-ea0710cd-1265-4434-bcdd-60a7a68fcc98.gif)

_The one that pops up from the bottom first is Telescope_

**Comment by ibhagwan** [comment]
>  @ibhagwan is there an option to not to keep showing previous file preview until the next one is loaded?

Unfortunately not, that would require changes to the window object that quite honestly aren’t worth it IMO for this negligible flicker.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/0fa4f3d7d7deaa22320e0c9c157aeeed1f7e0141

@ajitid @nyngwang - I looked into it, required a bit of modifications to the `Preview` objects but it works very smooth now.

Update to the latest commit and try it out?

**Comment by ajitid** [comment]
With this change and a delay of 60 ms it works much better for me, thanks!

**Comment by ibhagwan** [comment]
> With this change and a delay of 60 ms it works much better for me, thanks!

Is it comprable to Telescope now?

**Comment by ajitid** [comment]
Telescope behavior is a bit different, it's previewer is still smoother than what FZF Lua provides (checked on an unplugged laptop), but also it doesn't render large files by default which this library does.

**Comment by ajitid** [comment]
BTW I was looking into this library's resume feature, it doesn't put back the cursor where it was, is this intentional?

**Comment by ibhagwan** [comment]
> BTW I was looking into this library's resume feature, it doesn't put back the cursor where it was, is this intentional?

Do you mean cursor position of the input prompt? `resume` only saves the last provider run and last typed query, it doesn't save the cursor position of the input prompt.

**Comment by ajitid** [comment]
Oh no, I meant if I press ctrl-j a two times, and then press esc and then do `:Fzf resume`, it focuses on the very first item rather than the third item that was selected before I closed FZF

**Comment by ibhagwan** [comment]
> Oh no, I meant if I press ctrl-j a two times, and then press esc and then do `:Fzf resume`, it focuses on the very first item rather than the third item that was selected before I closed FZF

I just saw your edit after I wrote this reply, my edited reply:
> the selection is externally controlled by fzf which makes it a bit more complicated.

That said, since the input prompt is saved you shouldn't be too far from your selection when typing something and then running `resume`.
