### ISSUE TITLE
highlight filenames with different colors in git_files based on their git status

### ISSUE THREAD

**Issue by dripware** [ibhagwan/fzf-lua#299]
so there is already icon support for git_files and it's amazing! but is it possible to also change colors of filenames based on their git status?

**Comment by ibhagwan** [comment]
Not currently but if you wish to change the filenames based on the icon color configuration (I prefer to avoid an additional config section) I can add a new setting `color_files` which will control that.

**Comment by ibhagwan** [comment]
I just tested this setting as part of the `core.make_entry` so it can be added to any provider that supports git indicators (`files`, `grep`, etc), not really loving it but if you really want this I can keep it:

![image](https://user-images.githubusercontent.com/59988195/148984625-af4648b3-c796-4f5e-917c-0d18a475ecfa.png)

**Comment by ibhagwan** [comment]
Closing this for now, let me know if you still need this feature as appears in the above post, otherwise I won't add it as I don't think it's very appealing visually but that's just me :-)
