### ISSUE TITLE
Disable preview window by default

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#3]
How can I hide preview window by default? I would like it only to be implicitly toggled by keymap.

Also, I was wondering if you would consider adding global keybinding (actions) that would apply to each 'function' rather than having to repeat them for each element. I know I can use variable to pass them, but if I am not changing anything else for given provider then it would simplify my configuration.

Nice plugin btw!

**Comment by ibhagwan** [comment]
>How can I hide preview window by default? I would like it only to be implicitly toggled by keymap.

From the `fzf` manual: you need to add `hidden` to the preview options, I should have probably worded this option better but you can add it to the `preview_wrap` configuration like this: `preview_wrap = 'nowrap:hidden'`, alternatively you can also add it individually to each preview layout option so you can have it hidden only for vertical by adding this instead: `preview_vertical    = 'down:45%:hidden'.

> Also, I was wondering if you would consider adding global keybinding (actions) that would apply to each 'function' rather than having to repeat them for each element. I know I can use variable to pass them, but if I am not changing anything else for given provider then it would simplify my configuration.

I’ll add it to next commit, should be quite useful for say a custom action that copies to clipboard.

> Nice plugin btw!

ty!

**Comment by ibhagwan** [comment]
Just an FYI, I added `preview_opts` so it's more natural to add custom fzf preview options other than stuffing it in `preview_wrap`.

**Comment by gegoune** [comment]
Saw it in the commit, thanks, it does make more sense indeed.
