### ISSUE TITLE
Add `buftype` / `filetype` to the terminal window

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#30]
Some plugins such as lualine have special casing for buffers that have buftype or filetype `FZF`. If `buftype` / `filetype` was added to this it could take advantage of that.

**Comment by ibhagwan** [comment]
`buftype` is set to `fzf` (small cap), `nvim-fzf`set it, see [fzf.lua#L133](https://github.com/vijaymarupudi/nvim-fzf/blob/master/lua/fzf.lua#L133):

```lua
...
vim.cmd[[set ft=fzf]]
...
```
