### ISSUE TITLE
Jump to existing window-split when using `lsp_references/definitions`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#301]
As title. How to customize fzf-lua to achieve this. Have taken a look about the implementation but still don't know how to do so.

For `buffers` I already have the following, so I expect this can be done:
```
["default"] = function(selected, opts)
  -- switch if possible
  actions.buf_switch(selected, opts)
  -- open the buffer, would do nothing if same buffer
  -- although you could probably add a test here if this is needed
  actions.buf_edit(selected, opts)
end
```

**Comment by ibhagwan** [comment]
Have you tried adding the same `default` action under `lsp.actions`?

**Comment by nyngwang** [comment]
@ibhagwan Did. Now the original `<CR>` behaviour also disappears.

**Comment by nyngwang** [comment]
I try debugging this by using this:

```
["default"] = function(selected, opts)
  print("selected = " .. selected[1])
end
```

but nothing gets printed. Is this related?

**Comment by nyngwang** [comment]
> I’m not sure then, possibly due to different formatted entries? if this is the behavior you wish then investigate the `selected` object using `_G.dump` and see how entries differ (from say `files`) and then either adjust it to make it work or copy the buffer switch action code and customize it for LSP entries:
> 
> https://github.com/ibhagwan/fzf-lua/blob/533ca71fe4889c636b7c5a70bb78e38263f228ea/lua/fzf-lua/actions.lua#L226-L238

Tried copy-paste, got the same result: nothing happened

**Comment by ibhagwan** [comment]
Are you using `jump_to_single_result`? if so you have to use `jump_to_single_result_action`, see #124

**Comment by nyngwang** [comment]
@ibhagwan This is my first time knowing about this option. How do I check whether I'm using it or not?

**Comment by ibhagwan** [comment]
If you don’t have it set to true it’s not used, I’ll later get to my computer and see why your print isn’t getting called.

**Comment by nyngwang** [comment]
My full settings related to fzf-lua:

```
use {
  -- WARNING: fzf-lua does not include fzf. Run `brew install fzf --HEAD` first!
  'ibhagwan/fzf-lua',
  requires = {
    'kyazdani42/nvim-web-devicons'
  },
  config = function()
    local actions = require "fzf-lua.actions"
    require'fzf-lua'.setup {
      -- NOTE: Prefer case-insensitive search on: files, buffers.
      fzf_cli_args = "-i",
      winopts = {
        border = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
        height = 0.8,
        width = 0.5,
        row = 0.9,
        col = 0.9,
        preview = {
          -- default = 'builtin',
          title = false,
          wrap = 'nowrap',
          vertical = 'down:80%',
          layout = 'vertical',
          delay = 100
        }
      },
      lsp = {
        file_icons = false,
        git_icons = false,
        lsp_icons = false,
        actions = {
          ["ctrl-y"] = function(selected, opts)
            local tabnr = selected[1]:match("(%d+)%)")
            if tabnr then
              vim.cmd("tabn " .. tabnr)
            else
              tabnr = vim.api.nvim_win_get_tabpage(0)
            end
            local bufnr = tonumber(string.match(selected[1], "%[(%d+)"))
            if bufnr then
              local winid = utils.winid_from_tab_buf(tabnr, bufnr)
              if winid then vim.api.nvim_set_current_win(winid) end
            end
          end
        }
      },
      buffers = {
        actions = {
          ["default"] = function(selected, opts)
            -- switch if possible, or change the current one.
            actions.buf_switch(selected, opts)
            actions.file_edit(selected, opts)
          end
        }
      },
      files = {
        show_cwd_header=true,
        prompt = ' File $ ',
        -- WARNING: Run `brew install fd` to install fd.
        fd_opts =
          "--hidden "..
          "--no-ignore "..
          "--ignore-case "..
          "--type f "..
          -- "--max-depth 15 "..
          " "..
          "--exclude .local "..
          "--exclude .npm "..
          "--exclude .nvm "..
          "--exclude .tmux "..
          "--exclude .cache "..
          "--exclude .vscode "..
          " "..
          "--exclude .DS_Store "..
          "--exclude .git "..
          "--exclude node_modules "..
          "--exclude package-lock.json "..
          "--exclude yarn.lock "..
          "--exclude tags "..
          " ",
        actions = {
          -- WARNING: Required to prevent qf-list on multi-selection.
          ["default"] = actions.file_edit,
        }
      },
      oldfiles = {
        actions = {
          -- WARNING: Required to prevent qf-list on multi-selection.
          ["default"] = actions.file_edit,
        },
      },
      -- NOTE: TERM -- *include_path* !*exclude_path*
      grep = {
        show_cwd_header=true,
        no_global_resume = true,
        continue_last_search = true,
        prompt = ' Word $ ',
        -- WARNING:
          -- Run `brew install ripgrep` to install ripgrep.
          -- Restrict the range to search by <Enter> and <C-]>.
        actions = {
          -- WARNING: Required to prevent qf-list on multi-selection.
          ["default"] = actions.file_edit,
        },
        rg_opts =
          "--column "..
          "--no-heading "..
          "--color=never "..
          "--line-number "..
          "--case-sensitive "..
          " "..
          "-u ".. -- Disable: `-u` for .gitignore, `-uu` for hidden files/Dirs, and `-uuu` for binary files.
          "--hidden "..
          "--max-columns 200 "..
          "--max-filesize 500K "..
          "--max-depth 20 "..
          " "..
          "--glob '!.DS_Store' "..
          "--glob '!.git' "..
          "--glob '!node_modules' "..
          "--glob '!package-lock.json' "..
          "--glob '!yarn.lock' "..
          "--glob '!tags' "..
          " "..
          "--glob '!.config/nvim/plugin' "..
          "--glob '!.npm' "..
          "--glob '!.nvm' "..
          "--glob '!.tmux' "..
          "--glob '!.cache' "..
          "--glob '!.vscode' "..
          "--glob '!.local/share' "..
          "--glob '!Documents' "..
          "--glob '!Pictures' "..
          "--glob '!Library' "..
          " ",
        color_icons = false,
      },
      git = {
        status = {
          actions = {
            -- WARNING: Required to prevent qf-list on multi-selection.
            ["default"] = actions.file_edit,
            ["ctrl-y"] = function(selected)
              for _, file in ipairs(selected) do
                -- do whatever you want with the file
                vim.fn.system('git add "' .. file .. '"')
              end
            end
          },
        }
      }
    }
  end
}
vim.keymap.set('n', '<Leader>j', function() require'fzf-lua'.builtin() end, NOREF_NOERR_TRUNC)
vim.keymap.set('n', '<Leader>d', function() require'fzf-lua'.lsp_definitions() end, NOREF_NOERR_TRUNC)
vim.keymap.set('n', '<Leader>r', function() require'fzf-lua'.lsp_references() end, NOREF_NOERR_TRUNC)
```

**Comment by ibhagwan** [comment]
I just added the below to my config and it works, where did you add your default action? you need to add a new section caled `lsp` to your setup:

```lua
require'fzf-lua'.setup {
  lsp = {
    actions = {
      ["default"] = function(selected, opts)
        require'fzf-lua.actions'.buf_switch(selected, opts)
        require'fzf-lua.actions'.file_edit(selected, opts)
      end,
    },
  },
}
```

**Comment by nyngwang** [comment]
@ibhagwan I have a section called `lsp` in my last comment. I also copy-pasted the new one you given, while it doesn't work. Does these two functions has any requirement (e.g. the `cwd` has to include both files)?

**Comment by ibhagwan** [comment]
> @ibhagwan I have a section called `lsp` in my last comment. I also copy-pasted the new one you just gave, while it doesn't work too: the cursor stays in the same location. Do these two functions have any requirement(e.g. the `cwd` has to include both files) to run correctly?

No requirements, it should work regardless, just tested with your neovim version and it works, not sure why `print` doesn't get called on your setup, does your custom `ctrl-y` mapping from above work? what happens if you paste the code in a different mapping instead of `default`?

**Comment by nyngwang** [comment]
I found that this one works: `require'fzf-lua.actions'.file_edit(selected, opts)` but this one doesn't: `require'fzf-lua.actions'.buf_switch(selected, opts)`.

> does your custom ctrl-y mapping from above work?

No. I'm think about whether this is caused by other plugins.

**Comment by ibhagwan** [comment]
You can copy paste the contents of `buf_switch` and see what causes this to fail (line by line), if it gets called I doubt if this is related to another plugin but you never know.

**Comment by nyngwang** [comment]
@ibhagwan  Could you print an example of the content of `selected[1]` for me?

**Comment by nyngwang** [comment]
While I cannot debug without knowing what the _ the value `selected[1]` is in my case, and why not `print` doesn't work. Is it possible to write the content of `selected[1]` to a file using NeoVim's APIs? I have tested this with almost half of my plugins uninstalled. Does your implementation of `lsp` reuse another one in some other sections?

**Comment by nyngwang** [comment]
@ibhagwan  OK great, now I got it printed, while it seems that there is no field that matches the pattern `%[(%d+)`

<img src="https://user-images.githubusercontent.com/24765272/149405046-d219fbc9-c9c8-4428-afe8-171339700d22.png" width="500">

**Comment by ibhagwan** [comment]
As I wrote, the regex can only match when the entry contains buffer number (enclosed inside `[]`) so if you wish to further pursue this you're going to have to write code that would enumreate existing buffers/fileames and figure out if your entry already has en exisiting buffer you can switch into.

**Comment by nyngwang** [comment]
@ibhagwan: OK, now the switching is working. Still trying to put the cursor to the right line.

**Comment by nyngwang** [comment]
@ibhagwan What does this line mean?

```
vim.lsp.util.jump_to_location(entry)
```

I'm trying to refactor my code. Currently I have `row`, `col`. How to set the cursor to the buffer I'm not currently on?

**Comment by ibhagwan** [comment]
Last commit adds a new action named `file_switch`, it searches for the selected file in the current tab windows only and if found will switch over to the tab and also jump to the corrent line/column.

It comes as is I don't want to make new changes to it, if you wish it to behave differently (i.e. open a new buffer if not found) then either copy paste it contents and modify to your liking or combine it with `file_edit`:
```lua
["default"] = function(selected, opts)
  -- switch if possible, does nothing if it can't find an existing buffer
  -- returns true if buffer was switched into, false otherwise
  if not actions.file_switch(selected, opts) then
    actions.file_edit(selected, opts)
  end
end
```

The code for it can be found below:
https://github.com/ibhagwan/fzf-lua/blob/75ee949bb58ebd4b2a230a6213caab561fe64b3f/lua/fzf-lua/actions.lua#L176-L199

**Comment by nyngwang** [comment]
> ```lua
> ["default"] = function(selected, opts)
>   -- switch if possible, does nothing if it can't find an existing buffer
>   -- returns true if buffer was switched into, false otherwise
>   if not actions.file_switch(selected, opts) then
>     actions.file_edit(selected, opts)
>   end
> end
> ```

@ibhagwan Thanks! If you implement one then I use yours for sure :)

**Comment by nyngwang** [comment]
@ibhagwan: I just found that `_G.dump` useful for debugging! It this a built-in function or it's provided by fzf-lua?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/blob/0f4ca97bb7063c73897b8c55204456bb88cddc3b/lua/fzf-lua/utils.lua#L1-L7
