### ISSUE TITLE
The path under the same project are shown differently on `buffers`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#302]
As title. Would be better understood using picture:

<img src="https://user-images.githubusercontent.com/24765272/149377065-4d2decbc-10bb-45c3-8071-e5cb1dea4d09.png" width="800">

while the project structure looks like this:

- the `server.py` is under `src/bot/`
- the `ser1.py` is under `src/mods/server/`

<img src="https://user-images.githubusercontent.com/24765272/149377241-2107fe5c-25bf-4ed5-8ccf-74da0d661381.png" width="400">

So I will expect the best UX is to only show path up-to `src/`, i.e. the first common parent.

**Comment by ibhagwan** [comment]
This doesn’t seem like a bug, your current working directory in the photo is apparently `…/bot`, you can verify that with `:pwd`, otherwise the file would appear as `bot/server.py`. Therefore the second file on the list is actually outside the current working directory and has its full path displayed.

**Comment by nyngwang** [comment]
While if I still want the parent directory to be the first common one, is it possible?

**Comment by ibhagwan** [comment]
Why don't you just initiate the function with:
```lua
:lua require'fzf-lua'.files({ cwd='~/GitHub/CryptoBee/src' })
```

**Comment by nyngwang** [comment]
> What you should be asking yourself is, why do you keep changing your current working directory? when I work on a project I have a working directory that doesn't get changed only unless I switch to another project.

Your point is reasonable. But it doesn't solve this:

> To me, comparing `server.py` with `.../another/one/with/path/that/is/just/so/long/ser1.py` doesn't make sense.

**Comment by nyngwang** [comment]
> What you should be asking yourself is, why do you keep changing your current working directory?

In one of the projects that I'm working on, it has three sub-directories: `web/`, `graph/`, `auth/` under the same folder. When I use `files`, `live_grep_glob`, etc., I don't want to see files under the other sub-directories. It doesn't help to show that many results.

**Comment by ibhagwan** [comment]
> > What you should be asking yourself is, why do you keep changing your current working directory?
> 
> In one of the projects that I'm working on, it has three sub-directories: `web/`, `graph/`, `auth/` under the same Repo. folder. When I use `files`, `live_grep_glob`, etc., I don't want to see files under the other sub-directories. It doesn't help to show that many results.

Unfortuntely I can't help with this, that's how `rg` works, if you wish to exclude duplicate files you'd have to implement your own processor with ignore lists.

**Comment by nyngwang** [comment]
OK, then we keep this one closed.
