### ISSUE TITLE
Duplicate LSP definitions for multiple columns 

### ISSUE THREAD

**Issue by sirupsen** [ibhagwan/fzf-lua#303]
Hey @ibhagwan, hope all's well :)

I wanted to replace my `Ctrl-[` mapping with `fzf-lua`, getting a bit tired of the quickfix list... 

However, I'm noticing that I often get duplicates, e.g.

![image](https://user-images.githubusercontent.com/97400/149539339-94a8092d-4b94-4c41-b8f4-b019ef5d0154.png)

One seems to reference column 1, the other 5.

`lua vim.lsp.buf.definition()` doesn't open a list, just jumps to column 1.

There's a related issue https://github.com/ibhagwan/fzf-lua/issues/242. I cleaned up some symlinks, but otherwise can't get it to remove the other result.

BTW have you considered just jumping to the result if there's only one or allowing an option for it? I'm using `--select-1` passed to `fzf`, but it has a flicker opening the box, of course

**Comment by ibhagwan** [comment]
>BTW have you considered just jumping to the result if there's only one or allowing an option for it? I'm using --select-1 passed to fzf, but it has a flicker opening the box, of course

Not needed, there's an option for that named `jump_to_single_result`, it was implemented as one of the first requests, see #13.

As for the other issue there's no much manipulation done other than beautifying the entries given to the plugin by the neovim LSP API, can you run the below (adjusted to your file) and see if you get one or two resutls?

```lua
-- Try both columns 1 and 5, I believe line is zero-based so in your case it's 27-1
:lua _G.dump(vim.lsp.buf_request_sync(0, "textDocument/definition", { position = {character=1, line=26}, textDocume
nt={ uri="file:///home/...<FULL PATH OF FILE>" }}))
:lua _G.dump(vim.lsp.buf_request_sync(0, "textDocument/definition", { position = {character=5, line=26}, textDocume
nt={ uri="file:///home/...<FULL PATH OF FILE>" }}))
```

**Comment by ibhagwan** [comment]
Just tested it on my setup and I'm getting a single definition, using neovim 0.6.1 using `pylsp` as a language server. What versions are you using?

Sometimes neovim/LSP can get buggy and show duplicates, can you also try restarting the LSP server and neovim?

**Comment by sirupsen** [comment]
> Not necessary, there's an option for that named jump_to_single_result, it was implemented as one of the first requests, see #13.

Somehow missed this, thank you!

> see if you get one or two results?

Looks like it... I tried a couple of character/line combinations until I got output and no error:

````lua
_G.dump(vim.lsp.buf_request_sync(0, "textDocument/definition", { position = {character=5, line=27}, textDocument={ uri="file:///Users/simon/src/github.com
/org/repo/main/integrations/twitter/utils.py" }}))
```

Gave me:

```
{
  [2] = {
    result = { {
        range = {
          end = {
            character = 16,
            line = 27
          },
          start = {
            character = 4,
            line = 27
          }
        },
        uri = "file:///Users/simon/src/github.com/org/repo/main/integrations/twitter/utils.py"
      } }
  },
  [3] = {
    result = { {
        range = {
          end = {
            character = 0,
            line = 27
          },
          start = {
            character = 0,
            line = 27
          }
        },
        uri = "file:///Users/simon/src/github.com/org/repo/main/integrations/twitter/utils.py"
      } }
  }
}
```

When setting it to `character=1`, I get nothing.

> Sometimes neovim/LSP can get buggy and show duplicates, can you also try restarting the LSP server and neovim?

I restarted a few times, yeah, same thing.

I track `HEAD`, which I guess could be related... I needed something from it at some point, can't remember exactly what.

```
NVIM v0.7.0-dev+875-g39a35dd00
```

I'm using `pyright`, version `1.1.146`.

**Comment by ibhagwan** [comment]
I see… that makes me wonder what `vim.lsp.buf.definition` does differently, you can try using the asynchronous interface and see if that makes any difference by sending `{ async = true }` as an option to `lsp_definitions`.

**Comment by sirupsen** [comment]
Hah, `async = true` fixed it! Thank you so much! I don't deserve your responsiveness!

One other thing... do not feel obligated to respond. I am not sure I understand, but somehow `jump_to_single_result` is showing the floating window for `fzf` is showing momentarily:

![CleanShot 2022-01-14 at 14 04 42](https://user-images.githubusercontent.com/97400/149571116-10d11144-0e40-4217-8b0f-7e99dc828efd.gif)
 
Do you want me to update the docs on `async = true`? I don't quite understand why it works, so unsure how to avoid someone else opening a ticket like mine.

**Comment by ibhagwan** [comment]
Here's the explanation of the `async` difference which will also shed light on the window flash with `jump_to_single_result`:

Neovim has two different API interfaces to query LSP data:

1. `vim.lsp.buf_request_sync`, as it's name is a sync interface, you make a request, the UI hangs until the results come in - that is `async = false` and is the default for `lsp_definitions`, `lsp_references`, etc.

2. `vim.lsp.buf_request` is an async interface, you supply a callback, it returns immedietly and the callback will be called when the results are ready - that is `async = true`, that is the reason why the window has to appear momentarily with `async = true`, there's no way to know if the  results will come back empty (or a single result) so the fzf window must be open to recieve it and then closed if not needed.

I'm still unsure why is there a difference in the results between interfaces (1) and (2) and whether this is a neovim bug or not since `vim.lsp.buf.definition` does work as intended.
