### ISSUE TITLE
lua require('fzf-lua').files() respects .gitignore always

### ISSUE THREAD

**Issue by jorgebef** [ibhagwan/fzf-lua#304]
As per the documentation, I can't seem to find why or how to disable this as I would like to be able to search also the files that are in my .gitignore.

I understand that `!{.git,node_modules}/*` is set for rg_options, so it doesn't search in those folder by default (which is fantastic), but how could I allow for the files that are ignored to appear in the search result?
I'm most likely missing something as the plugins is very configurable.

Absolutely fantastic plugin btw, insanely performant even compared to telescope with no additions.

I'm absolutely in love <3

**Comment by ibhagwan** [comment]
Files uses prioritizes `fd` over `rg` (over `find`), is it possible you have `fd` installed? if so you need to override `fd_opts` and make sure to add `--no-ignore`:
```lua
:lua require'fzf-lua'.files({ fd_opts = '--color=never --type f --hidden --follow --no-ignore' })
```

If you're using `rg` you use `rg_opts` instead:
```lua
:lua require'fzf-lua'.files({ rg_opts = '--color=never --files --hidden --follow --no-ignore' })
```

If you wish to force a specific command you can use `cmd` instead, for example forcing `rg`:
```lua
:lua require'fzf-lua'.files({ cmd = 'rg --color=never --files --hidden --follow --no-ignore' })
```

>Absolutely fantastic plugin btw, insanely performant even compared to telescope with no additions.
> I'm absolutely in love <3

Ty <3

**Comment by ibhagwan** [comment]
Btw, these options don't need to be sent with each call, you can also set this up permanently during `setup()`, look under `files` section under [README#Customiztaion](https://github.com/ibhagwan/fzf-lua#customization), you can see all the default options there.

Also note that `grep|live_grep` have different `rg_opts` which would also need to be modified if you wish to search inside `.gitignore`.

**Comment by jorgebef** [comment]
Thank you, that solves it!
For whatever reason I was still using the initial config from a while back that didn't have the `fd_opts`.
Closing the issue.
