### ISSUE TITLE
Plugin uses a lot of cpu

### ISSUE THREAD

**Issue by Stanislav-Lapata** [ibhagwan/fzf-lua#305]
Thanks for your plugin. When I open plugin window it uses a lot of cpu 
```
os: macOS Monterey 
os version: 12.1
fzf-lua version: 32b2cdb5105575ed9fa76d4f7482427ceb6edbd0
```

My config
```lua
local utils = require('utils')


require('fzf-lua').setup({
  fzf_bin = 'sk',
})

utils.map('n', '<leader>f', ':FzfLua files<CR>')
utils.map('n', '<leader>b', ':FzfLua buffers<CR>')
utils.map('n', '<leader>g', ':FzfLua grep<CR>')
utils.map('v', '<leader>s', '"jy :FzfLua grep_visual<CR>')
utils.map('n', '<leader>s', ':FzfLua grep_cword<CR>')
utils.map('n', '<leader>l', ':FzfLua grep_last<CR>')
```

https://user-images.githubusercontent.com/12072329/149622201-72af2700-b8bf-426c-aeb9-4be2405275bf.mov

**Comment by ibhagwan** [comment]
It seems you’re using `sk`, I had another user on Mac report similar behavior with `sk` on Mac - does the same happens when you use `fzf`?

As much as I personally like `sk` it does seem to have almost stopped being maintained, it barely has any updates in two years.

**Comment by Stanislav-Lapata** [comment]
@ibhagwan you are right. Problem with skim

**Comment by ibhagwan** [comment]
Ty for the update @Stanislav-Lapata !
