### ISSUE TITLE
error on first Jump To Definition after opening Neovim 

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#306]
**using neovim HEAD**

the first jump to definition on any symbol (valid / invalid) causes the following errors to be printed to cmd line, even though the jump is successful. 

``` lua
jump_to_location must be called with valid offset encoding
locations_to_items must be called with valid offset encoding
```

This error occurs even when there are multiple definitions to jump to, and the FZF selector has to pop up.

**Comment by ibhagwan** [comment]
Can confirm this happens to me as well with the latest nightly, this warning is printed by neovim itself and seems harmless for the moment, I'll have to do some more digging what changed in neovim and what is required to make this go away.

I can't find any info or additonal paramters required in `:help locations_to_items` so this might even be an issue with HEAD which can go away, will keep this issue open to track.

**Comment by ibhagwan** [comment]
Solved by adding `vim.lsp.get_client_by_id(ctx.client_id).offset_encoding` as a second parameter to both APIs (`vim.lsp.util.locations_to_items` / `vim.lsp.util.jump_to_location`).

Also seems to be backwards compatible and doesn't break anything even with neovim `0.5.1`.

**Comment by ViRu-ThE-ViRuS** [comment]
Anazing! Thanks for the great work :)
