### ISSUE TITLE
Custom lsp prompt is always prefixed

### ISSUE THREAD

**Issue by JSteitz** [ibhagwan/fzf-lua#308]
https://github.com/ibhagwan/fzf-lua/blob/79371f0d9f1f2bdb39e3f01cd797644fb15e61e2/lua/fzf-lua/providers/lsp.lua#L277-L279

Is this intentional? If yes, I would like to have the option to disable the prefixes.
My use case is having an icon for each provider. Only LSP does something different.

`opts.prompt` and `config.globals.lsp.prompt` are always the same.
```
lsp config part (if you can't see the icon, there is one)
...
  lsp = {
    prompt = '  ',
    cwd_only = true,
    icons = {
      ['Error'] = { icon = vim.fn.sign_getdefined('DiagnosticSignError')[1].text },
      ['Warning'] = { icon = vim.fn.sign_getdefined('DiagnosticSignWarn')[1].text },
      ['Information'] = { icon = vim.fn.sign_getdefined('DiagnosticSignInfo')[1].text },
      ['Hint'] = { icon = vim.fn.sign_getdefined('DiagnosticSignHint')[1].text },
    }
  }
...
```

**Comment by ibhagwan** [comment]
LSP is a collection of many different providers which I avoided listing separately in the config, the best way to achieve what you want is to include the prompt in your command mapping, I.e.:

```lua
require'fzf-lua’.lsp_definitions({ prompt = 'defs> '})
```

**Comment by JSteitz** [comment]
Ahh I understand. But I would still see it as a feature request.
Maybe with a flag `prompt_include_name = true` or something. Or possibly also accept a function for prompt, to set it dynamically.

For the reason: It works differently from other providers and people would expect it to work the same (as I did).

**Comment by ibhagwan** [comment]
Certainly can be done, just to make sure, you wish to have the prompt icon alone without the LSP provider labels, correct?

**Comment by JSteitz** [comment]
Yes, that's correct.

**Comment by ibhagwan** [comment]
Ty for this issue, the behavior is now more consistent:

- `prompt` now overrides all LSP provider prompts
- new option `prompt_postfix` mimics the old behavior where the prompt is added after the LSP label
