### ISSUE TITLE
How does the `FzfLua files` command recurse all subdirectory files?

### ISSUE THREAD

**Issue by ztoiax** [ibhagwan/fzf-lua#309]

**Comment by ibhagwan** [comment]
Fzf-lua runs a shell command that traverses the tree, by default it will recurse all files under the current working directory.

The command priority is first `fd` -> `rg` -> `find`, in that order, depending on what you have installed, you can control the options send to the command under `files.fd_opts`, etc.

**Comment by ztoiax** [comment]
How do I set the default option to `rg` instead of `fd`?

**Comment by ibhagwan** [comment]
```lua
require'fzf-lua'.files({ cmd = 'rg --color=never --files --hidden --follow --no-ignore' })
```
