### ISSUE TITLE
How to use custom reload command

### ISSUE THREAD

**Issue by fanliver** [ibhagwan/fzf-lua#31]
I have a shell script, let's call `vim_rg`, that take some globs and search query as input parameters. That script executes RipGrep to find the `search query` in the content of the files filtered by the globs.
Example: 
```
vim_rg "!*test.txt *my_package* | my_function"
```
It will search for keyword `my_function` in all non-test files whose paths contain `my_package`.

How can I configure `fzf-lua` to accept `vim_rg {q}` as the reload command? I would like to search with globs in my nvim?

**Comment by fanliver** [comment]
f[zf.vim supports it with `change:reload` in the options.](https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration) Can I do the similar thing with `fzf-lua`

**Comment by ibhagwan** [comment]
You can supply whatever extra cli options you want (each call or globally) if you set the `fzf_cli_args` variable, these will be appended to `fzf`.

If you tell me exactly what you’re trying to achieve perhaps we can eliminate the shellscript altogether and recreate everything with `fzf-lua`, the live grep function uses the `change:reload` mechanism.

**Comment by fanliver** [comment]
What I want is to support file glob in the query string when I am typing in fzf-lua.
For example:
After running the following vim command `:lua require('fzf-lua').live_grep()`, I would like to type `!*test* *my_package* | my_function` to search for the word `my_function` in all *non-test* files whose paths contains `my_package`.

The vertical bar character (`|`) is just my convention to separate between the globs and the keyword, you can change it to whatever you want.

To achieve this, we will use `change:reload` binding in fzf and `--iglob` option in ripgrep.

What do you think?

**Comment by ibhagwan** [comment]
I’ll have to look deeper into the code tomorrow and let you know but this seems fairly easy to do in `fzf-lua`, worst case it will take a few minor code adjustments on my end.

**Comment by fanliver** [comment]
Sounds great. Looking forward to your change. Thank you.

**Comment by ibhagwan** [comment]
You can provide any command you want to the `live_grep` function by supplying `{ cmd = <command> }`, `fzf-lua` will then pass the `{q}` for you as well (as the initial query if you supplied one with `search = "<term>"`).

Basically the current live grep is equivalent to:
```lua
:lua require('fzf-lua').live_grep( { cmd = "rg --column --line-number --no-heading --color=always --smart-case" })
```
`fzf-lua` then builds 2 commands, the initial command which will be the command specified with `cmd` along with the search path specified by `search` and either a `filename` or `cwd` as a search scope.

The second command which is then sent to `change:reload` will be the same command with `{q} || true` appended:
```sh
rg --column --line-number --no-heading --color=always --smart-case {q} || true
```

If you're still having issue, please supply the full `fzf` (and `rg`) command you're running and I'll make it work for you.

**Comment by ibhagwan** [comment]
I was able to find [your dotfiles `vig_rg.fish`](https://github.com/fanliver/dot-files/blob/master/fish/functions/vim_rg.fish) and I now understand what you meant regarding the separator, the solution is pretty simple, all you need to do is use `live_grep` with a custom command and add your preferred `--iglob=<glob>`.

For example, the below will run `live_grep` on all files that aren't `.lua`:
```lua
:lua require('fzf-lua').live_grep( { cmd = 'rg --vimgrep --iglob="!*.lua"' })
```

**Comment by fanliver** [comment]
Thank you very much for your suggestion.
However, I would like to type the globs dynamically instead of putting a fixed glob in the keymapping. 
That's why I wrote the fish script `vim_rg`.

So far, I see that fzf-lua pass `-- {q}` to `vim_rg` script instead of `{q}`. I have to update the script a bit for this.

**Comment by fanliver** [comment]
Everything works perfectly for me now with `:lua require('fzf-lua').live_grep({ cmd = "vim_rg" })`

**Comment by ibhagwan** [comment]
> Everything works perfectly for me now with `:lua require('fzf-lua').live_grep({ cmd = "vim_rg" })`

I was just about to offer this solution exactly :-)

Out of curiosity what did you have to updated in your script to adjust for the `-- {q}`, I only added it to be extra safe with potential special chars in search queries, I can modify the code so you can supply that optional part and omit it if need be.

**Comment by fanliver** [comment]
Actually, I think it is my bad in the script. 
Reading the script you see that I try to split the arguments of `vim_rg` by the separator `>` to get the globs and the keyword.
When I type `*.kt* > myService` in fzf-lua, I expect the input arguments of `vim_rg` is the same. However, they are not. The arguments are actually `-- *.kt > myService` (prefixed by `-- `). Therefore, after the split, globs are `--` and `*.kt` which is wrong.
So I changed the `vim_rg` script to ignore `--` in the argument list.

**Comment by ibhagwan** [comment]
Happy you got it to work!

**Comment by fanliver** [comment]
I made[ a little CLI tool](https://github.com/fanliver/vimrg) for this.
Just build/download the `vimrg` executable and put it to your $PATH.
Then use Vim command `:lua require('fzf-lua').live_grep({ cmd = "vimrg" })` to open a fzf-lua window which supports glob filtering.
[The syntax can be found here](https://github.com/fanliver/vimrg#syntax-for-vimrg-as-a-cli-tool)

**Comment by ibhagwan** [comment]
Really cool, def going in the Wiki (when I finally get to it ha ha)

**Comment by ibhagwan** [comment]
Take a look at #167, I just provided a solution for this that wasn't available at the time. With a similar issue reopened I realized we can now do this without an external program.
