### ISSUE TITLE
Multiprocess does not use configured dev icons

### ISSUE THREAD

**Issue by JSteitz** [ibhagwan/fzf-lua#311]
After debugging why my Icons in `files()` are different to `oldfiles()`, I found the potential issue.
In my configuration I'm setting/changing some icons (also adding a Space @see #307 ) .

In `oldfiles()` everything is fine.
`files()` on the other side uses multiprocess and the command to run includes only the devicon plugin without my changes.

As I see it, it is a limitation to multiprocess and the only workaround for now is to disable it.

**Comment by ibhagwan** [comment]
> As I see it, it is a limitation to multiprocess and the only workaround for now is to disable it.

Correct, multiprocess uses a separate neovim process which loads its own instance of devicons, unfortunately that means any custom devicon config is lost.

**Comment by ibhagwan** [comment]
Added a solution for this in the latest commit, you have to add the path to your custom devicons setup file like this:

```lua
require'fzf-lua.config'._devicons_setup = "~/.config/nvim/lua/plugins/devicons.lua"
```

Note that the file cannot have any other `require` other than `nvim-web-devicons`, attempting to load any other modules will fail as they're not included in `package.path`, below is a file I test with:

```lua
local res, devicons = pcall(require, "nvim-web-devicons")

if not res then
  return
end

devicons.setup({
  override = {
    sol = {
      icon = "ﲹ",
      color = "#a074c4",
      name = "Sol"
    }
  };
})
```

**Comment by ibhagwan** [comment]
@jdrouhard, you might also be interested in this issue and it’s solution, if I recall correctly you mentioned something about a special devicons setup and having to submit a PR to devicons.

**Comment by ibhagwan** [comment]
FYI, https://github.com/ibhagwan/fzf-lua/commit/604eadfcf69b90cf9e508767ad217107520ce4d4 - this commit makes the additional setup step unnecesary, overrides should works seamlessly now.
