### ISSUE TITLE
Delta doesnt take full width in git_status preview

### ISSUE THREAD

**Issue by nikbrunner** [ibhagwan/fzf-lua#313]
Hi there,
first of all , thank you for your amazing work with this plugin! For a long time I used Telescope, but its just so annoyingly slow in bigger projects. With your Plugin, and of course the work of so many others, this perfectly solves this issue. :)

I have one little problem, for which I didn't found any open or closed issue. When using `delta` as a git pager, it doesn't take the full available width. In Lazygit or just in the Terminal itself it is no problem.

Any help would be appreciated! :)

### My environment

- M1 Pro 2020
- Kitty Terminal
- [My Dotfiles for your Plugin](https://github.com/nikbrunner/nibru.nvim/blob/with_fzflua/lua/user/fzf-lua.lua)

### Screenshots

This is `git_status` with `delta` as a pager

![image](https://user-images.githubusercontent.com/46924729/149674602-2c621c14-de8f-4af9-8595-bf7546feb7cd.png)

This is with LazyGit

![image](https://user-images.githubusercontent.com/46924729/149674610-1e3d3aa5-14d1-4b6c-b70c-0fa2e6910eeb.png)

![image](https://user-images.githubusercontent.com/46924729/149674613-f6536b36-1d3c-44ed-b940-9a7eb8a41eaa.png)

**Comment by ibhagwan** [comment]
Ty for the kind words @nikbrunner!

First I see in the screenshot you can also benefit from modifying `winopts.hl.border`, the default is set to `Normal` which doesn't seem to fit your colorscheme, perhaps setting it to `FloatBorder` would be better :-)

As for the `delta` issue, I'm not sure why this happens, just tested with `kitty` and it doesn't happen in my setup, with `git_diff` (unlike, `files`, `grep`, etc), fzf-lua uses `fzf` native previewer capability, it runs the command and sends it to `fzf` to render inside the preview window, would you be able to run the below command in the terminal **inside a git repo with modified files** move the cursor to a modified file and see how the delta preview has the same issue in the terminal directly?

> Note that this will only show preview if you're on a modified file

```sh
fd | fzf --preview-window='nohidden' --preview='git diff --color HEAD {} | delta'
```

**Comment by ibhagwan** [comment]
Found few related issues upstream(s):
https://github.com/dandavison/delta/issues/368
https://github.com/junegunn/fzf.vim/issues/1219
https://github.com/wfxr/forgit/issues/121

Can you try setting `git_diff.pager` to `delta --width ${FZF_PREVIEW_COLUMNS-$COLUMNS}`?

**Comment by nikbrunner** [comment]
Hi there @ibhagwan! Thank you for your quick reply :)

> As for the `delta` issue, I'm not sure why this happens, just tested with `kitty` and it doesn't happen in my setup, with `git_diff` (unlike, `files`, `grep`, etc), fzf-lua uses `fzf` native previewer capability, it runs the command and sends it to `fzf` to render inside the preview window, would you be able to run the below command in the terminal **inside a git repo with modified files** move the cursor to a modified file and see how the delta preview has the same issue in the terminal directly?
> 
> > Note that this will only show preview if you're on a modified file
> 
> ```shell
> fd | fzf --preview-window='nohidden' --preview='git diff --color HEAD {} | delta'
> ```

I had to install `fd` with brew for this, but after running it it looked like this

![image](https://user-images.githubusercontent.com/46924729/149729599-9b0c97ea-f525-4690-9445-799c8ed2ff5e.png)

> Can you try setting `git_diff.pager` to `delta --width ${FZF_PREVIEW_COLUMNS-$COLUMNS}`?
> 
> > **Edit:** it seems you're also using `side-by-side` so the pager command should be `delta --side-by-side --width ${FZF_PREVIEW_COLUMNS-$COLUMNS}`

So this looks like this. Its better, but now its taking up too much space.. 😁 
BTW. I tried the same thing with iTerm and it looks the same

![image](https://user-images.githubusercontent.com/46924729/149729699-a8937ab5-9244-4973-a176-f61e9265cabb.png)

**Comment by ibhagwan** [comment]
> I had to install fd with brew for this, but after running it it looked like this

Ty :)  I could easily rewrite the command to work with `rg` or even `find` - at least we now know the issue is consistent and is related to fzf/delta (regardless of fzf-lua).

> So this looks like this. Its better, but now its taking up too much space.. 😁
BTW. I tried the same thing with iTerm and it looks the same

Ok, so this might be a bug in either fzf or delta, either `delta` calculates wrong width or fzf is providing wrong width with `$FZF_PREVIEW_COLUMNS`.

- Can you run `echo $COLUMNS` in the term and let me know the result?
- Also run, so we can see the width provided by `fzf`:
```sh
ls| fzf --preview-window='nohidden' --preview='echo $FZF_PREVIEW_COLUMNS'
```

- You can also try to play with the pager command `width` parameter and set it to different hard coded numbers and let me know what width work `delta --width 80`?

**Comment by ibhagwan** [comment]
Ok, I was able to reproduce (and solve) this on MacOS. Btw, only happens when specifying `--side-by-side`.

It also turns out that `$FZF_PREVIEW_COLUMNS` wasn't relayed properly to the git command, so **make sure to update to the latest fzf-lua commit** and then set your pager to:
```lua
    git_diff = {
      pager           = "delta --width $FZF_PREVIEW_COLUMNS",
    },
```

Should work properly after that no matter what width or layout you're using.

**Comment by nikbrunner** [comment]
Yes! After an Update and this settings it works now perfectly :) Thank you!

**Comment by ibhagwan** [comment]
FYI, it’s now possible to configure pager in n easier way (I.e. you don’t need to duplicate the preview command or use `previewers.git_diff.pager`), all you need to do is define `preview_pager = 'delta -w $FZF_PREVIEW_COLUMS'` and place it under `git.status`, `git.commits` or `git.bcommits`.

**Comment by nikbrunner** [comment]
Thank you for the update :)
