### ISSUE TITLE
code actions with nvim-jdtls not working

### ISSUE THREAD

**Issue by abenz1267** [ibhagwan/fzf-lua#314]
Hi (again... i must be annoying),

some code actions don't work using nvim-jdtls, same problem as with f.e. telescope:

`No delegateCommandHandler for java.action.organizeImports`

Maybe see this for reference: https://github.com/mfussenegger/nvim-jdtls/pull/192

Regards

Edit: i also just realized code actions with gopls don't work. f.e. organize imports or add import. no error though. just doesn't work.

**Comment by ibhagwan** [comment]
>Hi (again... i must be annoying),

Dw about it, every issue makes this plugin better :-)

Not sure how to handle this issue though, in the linked jdtls issue there's no alternative suggested other than using the builtin menu `vim.lsp.buf.code_action()`, I'll do some more digging, any addittional info you can provide will be helpful as I never programmed in Java or tested jdtls.

>Edit: i also just realized code actions with gopls don't work. f.e. organize imports or add import. no error though. just doesn't work.

I just installed `gopls` and tried it, it worked with `0.6.1` but failed with the nightly,  similar to #306 with `0.7` the API requires an addtional `offset_encoding` paramter to be sent to `vim.lsp.util.apply_workspace_edit`.

If you're using the nightly update to the latest commit and code actions should work again, below is my test with `gopls`:

![Peek 2022-01-17 09-07](https://user-images.githubusercontent.com/59988195/149814652-65ad40e4-7d22-4806-95b0-de38233dc081.gif)

**Comment by abenz1267** [comment]
yes, seems to be fixed for Go.

As for the Java problem: as I understood it's a matter of fzf-lua missing some code_action implementations (...or having them 'wrong'). I will see if i can find out what's missing.

**Comment by abenz1267** [comment]
Apparently being able to use vim.ui.select with fzf-lua would solve the issue.

see https://github.com/nvim-telescope/telescope-ui-select.nvim

regards

**Comment by ibhagwan** [comment]
> Apparently being able to use vim.ui.select with fzf-lua would solve the issue.
> 
> see https://github.com/nvim-telescope/telescope-ui-select.nvim
> 
> Meaning: using fzf-lua for the vim.ui.selection instead of the native one.
> 
> regards

I know about `vim.ui.select` but it’s not a solution for this issue but rather a workaround, if implemented the UI for `lsp.but.code_action` will be replaced with fzf-lua to be used instead of the neovim default menu, then upon selection neovim executes the selection.

I haven’t looked into it yet, I’m not sure if it can be implemented for code actions only or, when defined, it takes over other LSP selectors too.

If that’s the only solution than it’s more of a “feature request” as it’s a new approach with a new implementation, I’ll leave this issue open until I can get to the bottom of this.

**Comment by abenz1267** [comment]
Hm, i'd agree this seems like a new feature rather than a bug. Personally i'd def. like it. Having a consistent experience is rather valuable. Right now i only use the in-build vim.ui.select for JDTLS .... having it in fzf-lua (and therefore also filterable) would be nice.

**Comment by ibhagwan** [comment]
Let me look into it, might be rather simple.

**Comment by ibhagwan** [comment]
Added in the latest commit, all you have to do now is call:
```lua
:lua require'fzf-lua'.register_ui_select()
```

**Comment by abenz1267** [comment]
i actually got out of bed again to test this. works like a charm! really good job with this plugin man. i used telescope before, but it's unusable with the main project at work, because it's too slow. no issues with this one. thanks a ton!

**Comment by ibhagwan** [comment]
You're welcome! just added the ability to send custom options to it (any other option that works with fzf-lua should work here), for example:
```lua
:lua require'fzf-lua'.register_ui_select({ prompt='Test> ', winopts = { win_height=0.30, win_width=0.60 } })
```

**Comment by abenz1267** [comment]
i noticed that if you are in visual mode, f.e. for vim.lsp.buf.range_code_action(), then you don't enter insert mode automatically.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5b5270684fb4b4b56da719a7d608a7ae8059cf08 fixed

**Comment by ibhagwan** [comment]
FYI, latest commit https://github.com/ibhagwan/fzf-lua/commit/8e37ef6e21e5619fce83c37aac1c1cc93157d070 also makes sure it works properly with `resume`, it's pretty cool as you can open the last code action anywhere else in the document and still apply it, watch the below:

- Code action: ignore diag for single line
- Undo + go to start of file
- Open code action again with resume
- Apply ignore single file

![Peek 2022-01-18 13-41](https://user-images.githubusercontent.com/59988195/150023543-da802cca-b07c-4696-bec3-048d1d0da317.gif)
