### ISSUE TITLE
files throws system loop

### ISSUE THREAD

**Issue by patchworkCode** [ibhagwan/fzf-lua#316]
Just downloaded fzf-lua to try from fzf, but the basic file search doesn't work and causing system loops.

System: MacOS
Neovim 6.0 Nightly

![image](https://user-images.githubusercontent.com/62321034/150043897-39673b21-8a80-40a5-b2c1-fa2341644fec.png)

**Comment by ibhagwan** [comment]
This seems related to #287, you’re running it at the home directory level where some proprietary OSX directories are inaccessible which throws the errors that overflow into `fzf`- I’m still unsure if it’s an fzf bug or fzf-lua.

Try running it inside an actual project and not at your home dir and it will work.

Alternatively you can turn off `multiprocess` either through `setup` or by running the command like this:
```lua
:lua require'fzf-lua'.files({ multiprocess = false })
```

What fzf version are you using?

**Comment by patchworkCode** [comment]
Yes, I'm using the most recent version of Fzf-Lua which I installed about 2 hrs ago. I tend to do a file search to a project by Nvim-ing @ my home directory. It's strange because the functionality works fine on vanilla fzf and telescope. Trying it as you mentioned, running it from a project directory works.

What worked like a charmed and also solved some other (minor) issues I had was disabelling multiprocess 😄, my searches would be cluttered by deeper os binary files etc which I never needed.

**Comment by patchworkCode** [comment]
oops no, I was actually still in my projects directory. Issues persists when running fzf-lua from the home directory quite interestingly. Have no idea why

**Comment by patchworkCode** [comment]
Ok I am satisfied! I'ved fixed the issue by mapping a key to that comand you mentioned in my vim config. I can search how I did before on vanilla fzf!

**Comment by ibhagwan** [comment]
> Ok I am satisfied! I'ved fixed the issue by mapping a key to that comand you mentioned in my vim config. I can search how I did before on vanilla fzf!

Just committed a change that should solve the issue in the OP, turns out OSX doesn't like output being directed to stderr, so I sent it to stdout instead.

Tested on a Mac and it works, can you try as well and let me know if that solves the isssue for you as well so I can close this issue?

Btw, I highly recommend re-enabling `multiprocess` as the performance and responsiveness is much better.

```lua
-- both options below are equal 'multiproces=true'
-- is the default so you don't really need to specify it
:lua require'fzf-lua'.files()
:lua require'fzf-lua'.files({ multiprocess = true })
```

**Comment by ibhagwan** [comment]
Btw, if you're bothered with all the inaccessible folders showing up in fzf you can just redirect stderr to `/dev/null`, based on the error format here it seems like you're using `rg` (rather than `fd`) so in your case you can use this command:

```lua
:lua require'fzf-lua'.files({ cmd = "rg --color=never --files --hidden --follow -g '!.git' 2>/dev/null" })
```

Just incase I'm mistaken and you're using `fd`, you can use this:
```lua
:lua require'fzf-lua'.files({ cmd = "fd --color=never --type f --hidden --follow --exclude .git 2>/dev/null" })
```

**Comment by patchworkCode** [comment]
Yup it all works well now, I also tried the commands you reccomended which work wonderfully too, thanks!

**Comment by patchworkCode** [comment]
you were also right, disabling multiprocess did hinder performance a lot

**Comment by ibhagwan** [comment]
> you were also right, disabling multiprocess did hinder performance a lot

Yap! Multiprocess is a game changer, it separates running the commands and the icon processing in a separate neovim process.

It’s a relatively new feature (2 months or so) but I believe this issue was the last outstanding one for multiprocess, should be rock solid now :)
