### ISSUE TITLE
lsp_ functions should skip the fzf window when there is only one option

### ISSUE THREAD

**Issue by fanliver** [ibhagwan/fzf-lua#32]
It would be really nice to skip the `fzf` window if there is only one option when we use lsp_ functions, especially, the `lsp_definitions` function usually comes with only one option.
For example this is my `lsp_definitions` for a python function

![image](https://user-images.githubusercontent.com/6322508/128109091-0dae88ca-2051-4e8a-baa7-aa99b34286b3.png)

**Comment by ibhagwan** [comment]
Already solved in #13.

Map your function to:
```lua
lua require('fzf-lua').lsp_definitions({ jump_to_single_result = true })
```
