### ISSUE TITLE
Send all current search results to QuickFix list

### ISSUE THREAD

**Issue by nikbrunner** [ibhagwan/fzf-lua#324]
Hi there,
Thanks you again for your great PlugIn!
I am just missing one feature. Maybe I am missing or not seeing something, but one of my favourite features of Telescope was, to send all current search results to the QuickFix list  via <kbd>Ctrl-q</kbd>. 

I found out that there is a default mapping for <kbd>Ctrl-i</kbd>, which seems to be not listed in the README, to select multiple entries and when pressing <kbd>Enter</kbd> the selection gets send to the QF List. 

But how can I send all current results to the QF list? 
Is there are default mapping for this or do I must build a mapping with a custom function?

**Comment by ibhagwan** [comment]
> I found out that there is a default mapping for Ctrl-i, which seems to be not listed in the README, to select multiple entries and when pressing Enter the selection gets send to the QF List.

There is no such bind defined by fzf-lua, this is probably coming from your shell setup defined by `FZF_DEFAULT_OPTS`.

> But how can I send all current results to the QF list? Is there are default mapping for this or do I must build a mapping with a custom function?

Since the defult action already sends multiple selection to quickfix this can be easily achieved by creating a new fzf bind (or modifying the existing one) to perform both select-all and accept:

```lua
require'fzf-lua'.setup {
  keymap = {
    fzf = {
      -- your other fzf binds
      ...
      -- modify the current 'toggle-all' bind:
      ["alt-a"]         = "select-all+accept",
    }
  }
}
```

**Comment by nikbrunner** [comment]
@ibhagwan Thank you! This solves it for me!

**Comment by strdr4605** [comment]
This is my setting:

```lua
fzf_lua.setup({
  -- fzf_bin = "/Users/strdr4605/.local/share/nvim/site/pack/packer/start/fzf/bin/fzf",
  fzf_opts = {
    ["--layout"] = "default",
    -- ["--ansi"] = false,
  },
  keymap = {
    fzf = {
      ["ctrl-q"] = "select-all+accept",
    }
  },
  grep = {
    -- rg_opts = "--column --line-number --no-heading --color=never --smart-case --max-columns=512",
    file_icons = false,
    git_icons = false,
  },
  winopts = {
    split = "belowright new",
    preview = {
      default = "bat_native",
      horizontal = "right:40%",
    },
  },
})
```

I never used `fzf` before `fzf-lua`, so I may not understand how it works, but in order to send the current search to QuickFix, I have to press `ctrl-q` twice (in Terminal mode of `fzf-lua`). Is this because of my other settings? what am I doing wrong?

**Comment by ibhagwan** [comment]
> I never used fzf before fzf-lua, so I may not understand how it works, but in order to send the current search to QuickFix, I have to press ctrl-q twice (in Terminal mode of fzf-lua). Is this because of my other settings? what am I doing wrong?

This is not how it should behave, what if you remove the customization, do you have to press `ctrl-q` once or twice to select all? What about other binds? What happens if you change to a different key?

Above are some troubleshooting steps, you can also try with the `minimal_init.lua` (provided by this project), modify the keybind part and see if this works as expected,

**Comment by strdr4605** [comment]
> what if you remove the customization, do you have to press ctrl-q once or twice to select all?

`ctrl-q` closes the `fzf-lua` window

> What happens if you change to a different key?

Nothing happens when I mapped to `alt-a`

![fzf-lua](https://user-images.githubusercontent.com/16056918/186888372-c0a3578b-f025-4b29-b388-48bdbc7fe446.gif)

**Comment by ibhagwan** [comment]
@nikbrunner what version of fzf are you using? What happens if you setup a `select-all+accept` in the terminal (without neovim), does it work?

**Comment by nikbrunner** [comment]
> @nikbrunner what version of fzf are you using? What happens if you setup a `select-all+accept` in the terminal (without neovim), does it work?

I am sorry, but I don't use this Plugin any more. I got a new Laptop since then, and I don't remember what version of `fzf` I was using at the time. :(

**Comment by ibhagwan** [comment]
Opps, the question was actually meant to @strdr4605 :)

Ty @nikbrunner!

**Comment by strdr4605** [comment]
```bash
 fzf --version
0.32.1 (4993d19)
```

looks like something is not working on my machine with `alt-a`
![fzf-lua-2](https://user-images.githubusercontent.com/16056918/186906912-330c44a0-94af-4ed7-a086-ab6b35d646be.gif)

But I tried mapping `ctrl-q` and it selects and exit with the results.
When `ctrl-a` is mapped, pressing `ctrl-q` closes with no results (as expected I guess).

![fzf-lua-3](https://user-images.githubusercontent.com/16056918/186907630-ae0353ae-4891-458b-96b6-cbfa6d26356f.gif)

Now, I mapped again `ctrl-q` in fzf-lua but it does not work (pressing twice, closes the window without opening quickfix)

But using `ctrl-w` as a keymap works. Although, I would like to use `ctrl-q` as a keymap.
I think this is a corner issue on my machine, sorry for bothering

**Comment by ibhagwan** [comment]
Perhaps you have a conflict with another plug-in? Even with minimal init fzf-lua doesn’t erase the other plugins as I didn’t want to mess with ppl’s configs.

I would also check existing terminal mappings for `ctrl-q` with `:verbose tmap <c-q>`.

**Comment by cpcopy** [comment]
I also meet the similar issue. If I map the `select-all+accept` action to `<c-t>`, it will close the results. If I use `<c-q>` instead, it works fine.
