### ISSUE TITLE
Ugly buffers view in GUI

### ISSUE THREAD

**Issue by damanis** [ibhagwan/fzf-lua#326]
Buffers view looks good in terminal nvim, but ugly in GUI. Tested in neoray and fvim.
Config:
  require'fzf-lua'.setup {
    buffers = {
      prompt            = 'Buffers❯ ',
      file_icons        = false,         -- show file icons?
      color_icons       = false,         -- colorize file|git icons
      sort_lastused     = false,         -- sort buffers() by last used
      multiprocess      = false,
    }
  }
![fzflua](https://user-images.githubusercontent.com/65733488/150684169-7dcb0535-dfbf-4200-9815-44c6730ff259.png)

**Comment by ibhagwan** [comment]
This is the `nbsp` character used to display an “invisible space” in the terminal:
https://github.com/ibhagwan/fzf-lua/blob/0f4ca97bb7063c73897b8c55204456bb88cddc3b/lua/fzf-lua/utils.lua#L33


What font are you using in the GUI app? Is there any way to set a custom font?

**Comment by damanis** [comment]
Tested two fonts: Go_Mono and Lucida_Console

**Comment by ibhagwan** [comment]
> Tested two fonts: Go_Mono and Lucida_Console.

How about any of the “nerd fonts” series?


> Possible configure simple space?

Yes it’s possible to change it to anything else, the issue is that some string manipulations rely on “find the last nbsp character”, if you change it to regular space you’ll have issues with spaced files/folders and other unintended behaviors.

You can try to change it by setting:
```lua
:lua require'fzf-lua.utils'.nbsp = ' '
```

**Comment by damanis** [comment]
Config works, thanks.
So, there is no issue, configuration only (font, 'nbsp').

**Comment by ibhagwan** [comment]
> Config works, thanks.
> So, there is no issue, configuration only (font, 'nbsp').

As I mentioned if you have files with spaces in them you’ll have issues.

**Comment by ibhagwan** [comment]
FYI, while dealing with a similar issue (#347) I recalled you can actually use the "old" fzf-lua `nbsp` character instead, `0xA0`, this should work better than space and you won't have issues with regular space:
```lua
:lua require'fzf-lua.utils'.nbsp = "\xc2\xa0"
```
