### ISSUE TITLE
Feature request: exact match

### ISSUE THREAD

**Issue by jarodsong6** [ibhagwan/fzf-lua#328]
Would be good to have exact match option.
Adding `--fixed-strings` to `rg_opts` does not give the result as expected.
For example, when I rg --fixed-strings `get(` outside vim I get the result, 
but get no results inside of vim with searching by `lua require('fzf-lua').grep()`

**Comment by ibhagwan** [comment]
You should get results when using `grep({ search = 'get(' })` if you’re not getting results it’s a bug, I tested all special characters with `grep_cword` and `grep_visual`.

Can you expand more on what isn’t working or what is a missing functionality in your opinion?

Note that `grep` does the regex escape for you but with `live_grep` you’re actually searching for a regex so you need to use `get\(` to escape the bracket.
