### ISSUE TITLE
require('fzf-lua').live_grep({ cmd = "echo " }) does not work

### ISSUE THREAD

**Issue by fanliver** [ibhagwan/fzf-lua#33]
```
require('fzf-lua').live_grep({ cmd = "echo " })
```
With the above Lua code, I expect the fzf window to show up and the item list only contains 1 item `-- xxx` where `xxx` is whatever I am typing. 
However, it doesn't work like that. 

![image](https://user-images.githubusercontent.com/6322508/128158497-6ecfb9f2-ec48-4c3f-9897-248f618915c9.png)

As you can see from the image, I typed `something` but the item list only show `--`.

Are you aware of this issue?

**Comment by fanliver** [comment]
I expect the above code should work the same as the code below:
```
local fzf = require("fzf")

coroutine.wrap(function()
  local result = fzf.fzf(
        {},
        "--bind 'change:reload:echo {q} || true'"
    )
  -- result is a list of lines that fzf returns, if the user has chosen
  if result then
    print(result[1])
  end
end)()

```

![image](https://user-images.githubusercontent.com/6322508/128160236-ac7d6368-e6cb-40a0-81a5-ffc7825d4378.png)

**Comment by ibhagwan** [comment]
Fixed by removing the `--` from the command, if required we can just add it to the `cmd` string.
