### ISSUE TITLE
ca 0.3 second lag upon closing FzfLua buffer window by hitting `<c-[>` or `<esc>`

### ISSUE THREAD

**Issue by zijian-x** [ibhagwan/fzf-lua#332]
Is there anything one can do to remove the minimal lag, which occurs except only when closing by hitting `<c-c>`? 

The lag is not prominent but it sometimes just doesn't quit when you want to quickly type something right after closing the window: for example if you want to type something right after leaving FzfLua files buffer by hitting `<c-[>` or `<esc>`, it would not quit but accept the input.

Though there is no lag at all when closing the window via `<c-c>`.

I've tested with the [minimal_config](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua) and it's the same. Does it maybe have to do with vim's event? Because afaik the only difference between `<esc>` and `<c-c>` is that i_ctrl-c would not trigger insertleave event.

**Comment by zijian-x** [comment]
https://user-images.githubusercontent.com/43778097/152159739-ddb69aba-c4c2-4bea-826c-b337cbc79cdd.mp4


Here is a video to show how it is sometimes still accepting input after hitting either `<esc>` or `<c-[>` because of the minimal lag.

**Comment by ibhagwan** [comment]
Do you have the same difference in exiting from INSERT mode to NORMAL mode between `Esc` and `C-c`?
What terminal are you using?
Are you running neovim inside tmux?

Read more about how to eliminate escape delay in neovim [here](https://www.johnhawthorn.com/2012/09/vi-escape-delays/) and let me know if this solves your issue?

**Comment by zijian-x** [comment]
No it doesn't have the same lag when swtiching between every mode in nvim and `<c-c>` and `<esc>` and `<c-[>` behaves all identically. And the `ttimeoutlen` in my config is already set to `0` and `timeoutlen` is normally set to 1 sec.

Terminal is alacritty and the shell is zsh and I do not use tmux, just plain terminal. I use vi mode on zsh and it does not have any lag going from insert to normal because of this line in my zshrc: `bindkey -rpM viins '\e'`, I suppose it removes every keymap starting with the escape keycode. I've also tried to set `KEYTIMEOUT=1` and it did not work either. 

And also I use `floaterm` and toggling it is as snappy as hitting `<c-c>` for `FzfLua buffers` & escaping to normal from insert. Floaterm also uses the terminal buffer, which is why I assumed that this is not an individual issue because it seems like I did not misconfigure nvim for it to lag.

**Comment by zijian-x** [comment]
I just realized is swallows the first character after hitting `<esc>`, is there maybe an internal `tmap` that causes the lag as I've tried with the minimal init.lua and it still behaves like this.

**Comment by ibhagwan** [comment]
>I just realized is swallows the first character after hitting `<esc>`, is there maybe an internal tmap that causes the lag as I've tried with the minimal init.lua and it still behaves like this.

There's a tmap for both `<esc>` and `<C-c>` that does the same thing, it attempts to save the typed query so that it can resume the typed query with `:FzfLua resume`.

Can you adding `global_resume_query = false` to your setup function?


Also I know you said it's not happening between normal to insert mode but it would still be worth a try to add this to your `.zshrc`:
```sh
export KEYTIMEOUT=1
```

**Comment by zijian-x** [comment]
Just tried both options and it still lags compared with escaping through `<C-c>` and thus swallows the first character after escape. Been trying to shoot a demo video but the frame rate is low enough so that the lag isn't actually visible on video at all.

https://user-images.githubusercontent.com/43778097/152256220-f2ab923f-36da-47ae-8d7d-e01407b02e82.mp4

I just wanted to know if this is an individual specific issue which only occurs on my machine and not on anybody else's. There wasn't any previously opened issue related to this at all.

**Comment by ibhagwan** [comment]
> I just wanted to know if this is an individual specific issue which only occurs on my machine and not on anybody else's. There wasn't any previously opened issue related to this at all.

Not sure if this is only you but this is the only issue opened about this so far.

Can you press `<c-\><c-n>:tmap<cr>` while on the Fzf window and see if the `<Esc>` tmap is gone after setting `global_resume_query=false`?

**Comment by zijian-x** [comment]
Yes after setting `global_resume_query=false` & hitting `<c-\><c\n>` and querying maps using `:tmap`, there is no map associated with `<esc>` anymore.

![image](https://user-images.githubusercontent.com/43778097/152332646-8ce589d5-97f0-4994-80cb-b9e5e09356d4.png)

I tried again but this time removed all the other plugins(PackerCleaned) beside `FzfLua`, set both `timeoutlen` and `ttimeoutlen` to 0, added `global_resume = false, global_resume_query=false` to [minimal init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua) config function, sourced it and restarted nvim, hit `<c-p>` open fzflua and it still waits for the next character even though if there is a map for `<esc>`.

![image](https://user-images.githubusercontent.com/43778097/152335012-d64f8d2c-599e-4e95-ab52-806449b33c16.png)

No lag for `<C-c>` as always, only `<esc>`, `<C-[>`.

But now I found out that if I input `a` right after hitting `<esc>`, is toggles and (de)selects all the items, so it seems there is somehow a map for toggling_all.


https://user-images.githubusercontent.com/43778097/152335489-225189d9-ea8e-4a8f-8e46-5041a4d37ec9.mp4

**Comment by ibhagwan** [comment]
Good finds @zijian-x, is it possible you have a default mapping inherited from the shell in your `$FZF_DEFAULT_OPTS`?

An easy way to see if that’s the case is to open a new terminal inside neovim (or even in the shell) with `:new | term` and running an arbitrary command, for example `ls | fzf` and seeing if you experience the same behavior without fzf-lua?

**Comment by zijian-x** [comment]
My goodness yes it has the exact same minuscule lag as in `fzf-lua`, even on a bare terminal and not inside neovim it swallows the first character after hitting escape, and I never noticed it myself while using `fzf` all the time!

Which is to say that this is not an `fzf-lua` issue at all, it just reflects how `fzf` behaves. But the only difference is that, in `fzf` it does not toggle select all items when giving an `a` straight after escape when using `ls | fzf -m`, it only swallows any one character that is given along with the escape keycode after a little bit of testing so far.

And yes I do have the following `fzf` environment variables set in the shell profile:
```
export FZF_DEFAULT_OPTS='--layout=reverse --height=50%'
export FZF_DEFAULT_COMMAND='fd -uu -L -E ".git" -E ".cache" -E ".backup"'
```

But I've just tried to remove these entries and after re-login it is still no avail.

**Comment by ibhagwan** [comment]
What fzf version are you using?

I'm on `0.29 (devel)`.

**Comment by zijian-x** [comment]
![image](https://user-images.githubusercontent.com/43778097/152381061-df75e77d-d391-428f-ace3-42013cd5ad41.png)

installed from the official repo and should be the newest version.

**Comment by ibhagwan** [comment]
What if you try to explicitly bind `esc`?

```sh
ls | fzf --bind=esc:abort
```

**Comment by zijian-x** [comment]
Still the same. I also tried cleaning up all my `fzf` shell mappings and not sourcing `/usr/share/fzf/key-bindings.zsh`, tried `ls | fzf --bind=esc:abort` and no avail...

**Comment by zijian-x** [comment]
`<C-c>` quitting works as smooth as butter as always...

**Comment by ibhagwan** [comment]
From https://github.com/junegunn/fzf/issues/2052

>You can set $ESCDELAY environment variable to a smaller value than the default 100.

**Comment by zijian-x** [comment]
My god never would I have thought that it's intentionally set. That solves it man and you are the best!
