### ISSUE TITLE
Strange result from `actions.buffers`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#333]
I'm trying to refactor my setup config of fzf-lua. I got the following result: Indeed it has switched the current buffer from `nvim_ide.lua` to the `UX.lua`, while there is one more floating window(from the `vim.fn.getwininfo(...)` the field `terminal` is `0`) with non-trasparent background, and occupied the filter input area.

<img src="https://user-images.githubusercontent.com/24765272/152216869-efd89b92-8ada-4a68-97a8-d281d4d77b6b.png" width="700">

I tried to close that with `:q`, I got this resulting buffer that _stays_ there:

<img src="https://user-images.githubusercontent.com/24765272/152217651-6c224f73-4e36-4e22-8753-50a0203ea928.png" width="700">

One more `:q` will result in this:

<img src="https://user-images.githubusercontent.com/24765272/152218052-85a66352-f802-4b10-b898-87794a4eecc7.png" width="700">

---

### Debug info.

Initially, I thought this is caused by my own plugin that change the cwd. But after some testing, the problem still persists after I remove it. I will try taking out more plugins that possibly cause this bug.

**update**: If I remove the focus.nvim the result is like this:

<img src="https://user-images.githubusercontent.com/24765272/152219975-e94592d6-2de1-436d-8a0f-4afffecdd728.png" width="700">

**update2**: If I remove my own NeoZoom.lua, which is the only plugin that facilitates the `<CR>` key, I still got the same result.

My nvim version: (while I think this might not be relevant since I experience this many days ago)

```
NVIM v0.7.0-dev+995-g255935903
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by ibhagwan** [comment]
I don’t understand what you changed to make this happen? If you revert your setup refactoring does the plugin work as before?

Can you post your refactored setup so I can try to reproduce this?

**Comment by nyngwang** [comment]
My bad. I incorrectly reference this syntax from the README.md:

```lua
actions = {
  -- actions inherit from 'actions.files' and merge
  ["right"]   = { actions.git_unstage, actions.resume },
  ["left"]    = { actions.git_stage, actions.resume },
},
```

If you change back to the way you mentioned in https://github.com/ibhagwan/fzf-lua/issues/301#issuecomment-1012409299 then all things are correct now. My final settings:

```lua
        actions = {
          files = { default = actions.file_edit },
          oldfiles = { default = actions.file_edit },
          grep = { default = actions.file_edit },
          buffers = { default = function (...)
            actions.file_switch(...)
            actions.file_edit(...)
          end },
          git = {
            status = { default = function (...)
              actions.file_switch(...)
              actions.file_edit(...)
            end }
          },
          lsp = {
            default = actions.file_vsplit,
            ['ctrl-y'] = actions.file_edit,
          }
        },
```

**Comment by ibhagwan** [comment]
The settings you posted do nothing… the only tables that matter are `actions.files` and `actions.buffers`.

The entire point of this config addition was that you wouldn’t have to define actions per provider, `grep`, `oldfiles` (and all file based providers) all inherit from `actions.files`.

You only need to set `actions.files.default` to change the default action for all files providers.

**Comment by nyngwang** [comment]
@ibhagwan: Should I move the `lsp = {}` back to the outermost key of `setup {}`?

**Comment by ibhagwan** [comment]
> @ibhagwan: Should I move the `lsp = {}` back to the outermost key of `setup {}`?

Yes, `lsp` should be topmost and your custom actions should be defined under `lsp.actions` - the end result for your LSP actions are the defaults in `actions.files` merged with `lsp.actions` (prioritizing the ones under `lsp`).

**Comment by nyngwang** [comment]
OK, Thank you!

**Comment by ibhagwan** [comment]
I’ll make sure this is clear in the README

**Comment by nyngwang** [comment]
I remember you mentioned this before in some old comments. But I didn't put much attention to it since no error occurred. Thanks for the update!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/adc622112b40fddbe250821edfb27f80ebe5869f
