### ISSUE TITLE
fzf-lua\path.lua error on start

### ISSUE THREAD

**Issue by cpkio** [ibhagwan/fzf-lua#334]
### Steps to reproduce

0. Windows 10 x64. Neovim runs from `C:\NvimTest` with `$XDG*` environment variables pointing to it, so the plugins are sourced from `C:\NvimTest\nvim-data\site\pack\user\start`, and configuration file is sourced from `nvim\init.lua`.
1. `git clone` repo to `C:\NvimTest\nvim-data\site\pack\user\start`
2. Copy `require'fzf-lua'.setup{…}` from Customization section in README to `nvim\init.lua` for test purposes.
3. Run `nvim`.

### Result

```
Error detected while processing C:\NvimTest\nvim\init.lua:                                                                                        
E5113: Error while calling lua chunk: ...m-data\site\pack\user\start\fzf-lua\lua\fzf-lua\path.lua:114: attempt to index local 'path' (a nil value)
```

**Comment by ibhagwan** [comment]
Unfortunately this plugin does not support windows, it's probably not a huge deal to fix but requires a windows machine which I don't have, PRs welcome :-)
