### ISSUE TITLE
New actions that preview the `lsp_definitions` in floating window?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#335]
It seems that there is no built-in way to open the result in a floating window. To achieve similar the current way are `file_split`, `file_tabedit`, etc. I think this might be a good idea, since with `file_split` one will have to manually close it, and it's inconvenient when the definition is on the same file.

If this would be possible in the future, I would expect the setup to be something like this(possibly some options to restrict the max/min-window-height and an above/below-current-line option):

```lua
actions = {
  buffers = { default = actions.float_win }
}
```

**Comment by ibhagwan** [comment]
I currently have no plans on adding this behavior as it would require extra (IMO, unncessary) customiztaion to be done properly for location, size, borders, etc.

Should be pretty easy to add something that would be a fit for your needs alone using a a custom action and `:help nvim_open_win`.
