### ISSUE TITLE
Preventing quickfix buffers from appearing in buffers provider?

### ISSUE THREAD

**Issue by oncomouse** [ibhagwan/fzf-lua#337]
In fzf.vim, I believe quickfix and location list buffers don't show up when calling the `:Buffers` command. Is there a way to prevent fzf-lua from displaying these buffers?

**Comment by ibhagwan** [comment]
Do you mean the buffer named `[Quickfix list]` or the buffers that were sent to the quickfix list?

I just tested it and buffers appear in the `buffers` picker whenever they're opened and appear in `:ls`, the `[Quickfix list]` buffer doesn't show up unless `show_unlisted=true` is specified.

**Comment by oncomouse** [comment]
That's weird. It's showing up for me, even when `show_unlisted=false` is explicitly set in my config. Does `[Quickfix list]` not show up the results of `:ls` for you? It does in show up for me.

If that's the case, I've probably done something to my quickfix list.

**Comment by oncomouse** [comment]
I just tried starting Neovim with a minimal `init.lua` and I do see the the `[Quickfix list]` buffer in the `buffers` picker.

Steps to reproduce with the config (below):

~~~
:copen
:wincmd p
:require("fzf-lua").buffers()
~~~

Doing so, I see two buffers in the picker, one for the new buffer and one for the empty quickfix list.

Here's the configuration I used:

~~~lua
-- luacheck: globals vim dotfiles
local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/opt/packer.nvim"
if vim.fn.empty(vim.fn.glob(install_path)) == 1 then
	vim.fn.jobstart({ "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path }, {
		on_exit = function()
			vim.cmd("packadd packer.nvim")
			vim.cmd("PackerSync")
		end,
	})
end
vim.cmd("packadd packer.nvim")
require("packer").startup({
	function(use)
		use({
			{ "wbthomason/packer.nvim", opt = true },
			{
				"ibhagwan/fzf-lua",
				config = function()
					require("fzf-lua").setup({
						buffers = {
							show_unlisted = false,
						},
					})
					vim.api.nvim_add_user_command("Buffers", function()
						require("fzf-lua").buffers()
					end, {
						force = true,
					})
				end,
				requires = { "kyazdani42/nvim-web-devicons" },
			}, -- FZF Client
		})
	end,
})
~~~

**Comment by ibhagwan** [comment]
I was also able to reproduce this with the [minimal init.lua](https://github.com/ibhagwan/fzf-lua/blob/main/minimal_init.lua) supplied bu this plugin.

The weird thing is that with my config the `[Quickfix list]` doesn't appear in the output of `:ls` but with the minimal config it does show up with `:ls`.

I'll have to dig more to see which setting controls this behavior, technically I could hardcode filter of quicklist buffers but it does make sense to show everything listed with `:ls` so I'd rather find the setting that controls that.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/330742a4c00162aefbe4996192d50f5342955c41 latest commit takes care of this in the code, will now show quick fix and location list buffers unless `show_quickfix=true` is specified.
