### ISSUE TITLE
The `FzfLua buffers` doesn't work when the current buffer is `[No Name]`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#338]
As title. This might be caused by my wrong config, so here is the part I think relevant:

```
        actions = {
          files = { default = actions.file_edit },
          buffers = { default = function (...)
            actions.file_switch(...)
            actions.file_edit(...)
          end },
        },
```

**Comment by ibhagwan** [comment]
By "doesn't work" you mean the default action doesn't work or does the UI not open?

**Comment by ibhagwan** [comment]
Also, why is your default action for buffers doing a `file_switch` (and not a `buf_switch`)?

This is how it should be:
```lua
actions = {
          files = { default = actions.file_edit },
          buffers = { default = function (...)
            actions.buf_switch(...)
            actions.buf_edit(...)
          end },
        },
```

**Comment by nyngwang** [comment]
Closing this because I'm noob, lol. I change all `buf_...` to `file_...` since I originally used all `buf_` and something like `lsp_references` or `lsp_definitions` didn't work.

**Comment by ibhagwan** [comment]
Use `buf_` only for entries which contain buffer numbers, that would be buffers, tabs, lines and blines.

By using `actions.buffers` you’re setting all buffer providers in one place but the logic still applies.

**Comment by ibhagwan** [comment]
FYI, added 2 new shortcut actions:
- `buf_switch_or_edit`
- `file_switch_or_edit`

defined as:
```lua
M.buf_switch_or_edit = function(...)
  M.buf_switch(...)
  M.buf_edit(...)
end

M.file_switch_or_edit = function(...)
  M.file_switch(...)
  M.file_edit(...)
end
```


So now you can make the customization shorter:
```lua
  actions = {
    files = { default = actions.file_edit },
    buffers = { default = actions.buf_switc_hor_edit }
  },
```
