### ISSUE TITLE
lsp_workspace_symbols() shows the same file name (of the current buffer) in loaded fzf list 

### ISSUE THREAD

**Issue by greenhat** [ibhagwan/fzf-lua#34]
Hey! Thank you for fzf-lua! It's awesome!

**Comment by ibhagwan** [comment]
> Hey! Thank you for fzf-lua! It's awesome!

Ty!

Not sure I understand the issue, would you be able to point it out with an image or describe it more clearly?

**Comment by greenhat** [comment]
Sure! Here is how it looks:
![image](https://user-images.githubusercontent.com/180349/128674273-dbe19109-41fc-464c-a994-8b8f1c6cbdd3.png)

If I open file `type.rs` and call `lsp_workspace_symbols()` it shows as if symbols are defined in `types.rs`. Actually, all of those symbols are defined in other files. Columns and rows seems legit though.

**Comment by ibhagwan** [comment]
Should be working now.
