### ISSUE TITLE
grep special regex chars fails when SHELL is fish

### ISSUE THREAD

**Issue by leiserfg** [ibhagwan/fzf-lua#340]
I'm trying to search for function calls in a project, but neither  `(`, `\(`, `"("`, `"\("` work, and therefore I can't match parenthesis and neither user regex classes.

**Comment by ibhagwan** [comment]
When using `grep` fzf-lua does the regex escaping for you, running `grep({ search='call(' })` should work.

`live_grep` on the other hand passes the query as is to `rg` so that requires escaping special chars with `\`.

Try to visually select a function with its bracket and use `grep_visual`, it should work.

Once you’re in the fzf window of any grep command (not live grep), no need to escape anything, fuzzy machine should work as well.

**Comment by ibhagwan** [comment]
If you're still having issues run with `debug=true`, it will print the underlying command as first line into fzf and you can run it in the shell and see why it's not returning resulsts for you.

```lua
:lua require'fzf-lua'.grep({ debug = true, search='pcall(' })
```
As you can see below, searching for `pcall(` got translated into the regex `pcall\(`:
![image](https://user-images.githubusercontent.com/59988195/153245267-aa5fc3ff-6e6d-491c-b62c-1df73f69e689.png)

**Comment by leiserfg** [comment]
Thanks for the help, the  issue happens for instance if I call:
```vim
lua require'fzf-lua'.grep({ debug = true, no_esc=true, search=[[function.*\(]]})      
```
rg complains as :
```
regex parse error:  function.*\\( 
error: unclosed group
```
because the \ is being scaped,
the same happens if I don't use  `no_esc`  but a bit worse  `function.\\*\\\\\\(` .

Actually, I usually use the interactive way (calling `grep` without args and putting the search in the prompt) but the same happens there, like if the grep were always escaped and without  no_esc it where escaped twice.

**Comment by ibhagwan** [comment]
>```lua
>lua require'fzf-lua'.grep({ debug = true, no_esc=true, search=[[function.*\(]]})
>```
I just tried this and it works for me, what are your `grep` settings?

![image](https://user-images.githubusercontent.com/59988195/153274560-3023267b-7f50-481d-8a82-fefe54449de0.png)

Can you post the command debug output?

**Comment by ibhagwan** [comment]
I'm not sure why this is happening on your system, just tested this on both Mac/Linux with both `rg` and `grep` and I don't have the double `\` escape issue when using `no_esc=true`.

**Comment by leiserfg** [comment]
This is what I get for your comand
```sh
'vi' -n --headless --clean --cmd 'lua loadfile([[/home/leiserfg/.local/share/nvim/site/pack/packer/start/fzf-lua/lu
a/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[rg --column --line-number --no-heading --color=always --smar
t-case --max-columns=512 '\''function.*\\\\('\'' ]],git_icons=false,file_icons=true,color_icons=true},[[_G._devicon
s_path='\''/home/leiserfg/.local/share/nvim/site/pack/packer/start/nvim-web-devicons/lua/nvim-web-devicons.lua'\'';
 _G._fzf_lua_server='\''/tmp/nvimIjy45L/1'\''; return require("make_entry").file]],[[return require("make_entry").p
reprocess]])'
```

**Comment by leiserfg** [comment]
I don't have any custom configuration besides `default_previewer = "bat"`  but that is not related, and I'm using Linux, could it be because I use fish?

**Comment by leiserfg** [comment]
Yes, it's because of fish, just forced my shell to be bash  (by `export SHELL=/usr/bin/bash`), and then it works fine.

**Comment by ibhagwan** [comment]
>Yes, it's because of fish, just forced my shell to be bash (by `export SHELL=/usr/bin/bash`), and then it works fine.

I was just going to suggest trying with `bash` or `zsh`.

I think I found the issue, I'm using vim's `vim.fn.shellescape` to escape the command, the below is from `:help shellescape`:

```help
shellescape({string} [, {special}])			*shellescape()*
		Escape {string} for use as a shell command argument.

		If 'shell' contains "fish" in the tail, the "\" character will
		be escaped because in fish it is used as an escape character
		inside single quotes.
```

I'm testing to see how can I avoid that and what other implications this may have.

**Comment by ibhagwan** [comment]
The telescope `escape_chars` is not a shell escaping command, it's the equivlent of fzf-lua's `rg_escape`:
https://github.com/ibhagwan/fzf-lua/blob/b273a358a7a33bebcf6e5c1ef1adc25439083023/lua/fzf-lua/utils.lua#L103-L110

It seems I need to create a copy of `shellescape` that doesn't have the fish shell `\` escape.

**Comment by leiserfg** [comment]
Maybe you could use `shellscape` and then replace `\\` with `\` if the shell is fish, which should be easier to implement.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b033e406caa0824e0e9ae006d9d0a18e3cd1fa72

Should work now both the special characters and the resume.
