### ISSUE TITLE
Oldfiles takes long to open

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#343]
When I enter `:FzfLua oldfiles`, it can take about a second or two to open. But `:o` pulls up the old files immediately. There are about 2400 files in there right now. On another system, there are about 170 old files and both `:o` and `:FzfLua oldfiles` open immediately. Could the performance of this be improved?

My `shada` setting in Neovim is `!,'80000,<50,s10,h`. I am also using the `include_current_session` option for fzf-lua oldfiles.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/8591f3c8464dd1baaf801c5e8acf6d663c56cf6d this commit should improve the speed significantly.

`oldfiles` was one of the first providers I implemented, TBH without much thought for performance, with the latest changes the interface is async and sohuld be more responsive, additioanlly I disabled the filesystem test for files (was probably part of the issue) unless the user specifically requests by passing `stat_file = true`:
```lua
-- only send this if you wish to remove files that no
-- longer exist on disk as this can be quite costly
:lua require'fzf-lua'.oldfiles({ stat_file=true })
```

Try it out and let me know if this solves your issue?

**Comment by ibhagwan** [comment]
Alright, I think I've got this done properly now, latest commit makes sure the interface opens regardless of the amount of files, just tested it with artficially inflating  my oldfiles up to 1M files, the UI always stays responsive as results are pouring in, took about 7 seconds to finish with `stat_file=false` and roughly double the time with `stat_file=true` (which is the default).

If you're still having issues feel free to reopen this.

**Comment by shyun3** [comment]
This is much more responsive, thanks!

**Comment by ibhagwan** [comment]
Great! tysm for the update :-)
