### ISSUE TITLE
Buggy history with `oldfiles`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#344]
I have checked that I don't have any file called `nvim_ide.lua` at the root of my file system, but it's reported in the `FzfLua oldfiles`.

<img src="https://user-images.githubusercontent.com/24765272/153720000-d3df7f43-eb2a-409c-bebd-04fb7ca7e2dd.png" width="600">

And something doesn't look like a file, `term://~/...`, also got shown:

<img src="https://user-images.githubusercontent.com/24765272/153720071-3b05df56-7c92-42b2-9f2e-1345e7d706e2.png" width="600">

What's wrong?

**Comment by ibhagwan** [comment]
This is related to #343, this file was probably generated by a plugin and then deleted (if you run `:oldfiles` you can see it), I changed the default to not check for file existence in the file-system for performance reasons.

I'm probably going to restore this behavior as default but for now you can use:
```lua
:lua require'fzf-lua'.oldfiles({ stat_file=true })
```

**Comment by ibhagwan** [comment]
Just restored the default to `true` I think it's better practice, only if performance is an issue it should be set to `false`.

**Comment by nyngwang** [comment]
Just confirmed that the problem is resolved. Thanks for the fix!
