### ISSUE TITLE
Is it possible to wrap the line typed in the input area on greping via `FzfLua live_grep` series.

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#345]
Hi, I would like to make a feature request that if it's possible to wrap the input area, since I have too many things to grep (but yup I don't want to adjust the width of this floating window):

<img src="https://user-images.githubusercontent.com/24765272/153818609-ad91f08a-c1a9-4e3d-99a2-b920ac8a4889.png" width="700">

(Btw, the good news: I usually need to grep through more than 3,000 files, and with fzf-lua this job can be done gracefully. Cheers! 🥂)

**Comment by ibhagwan** [comment]
That’s not something I can control, if there’s no such option in `man fzf` you’d have to ask for this feature [upstream](https://github.com/junegunn/fzf).

**Comment by nyngwang** [comment]
Just for sure, I meant wrapping the line I typed which follows the "Word $". OK, I will find a time to ask there.

**Comment by ibhagwan** [comment]
> Just for sure, I meant wrapping the line I typed which follows the "Word $". OK, I will find a time to ask there.

Yes, the input line is part of the fzf interface, there's really not much I can do here.
