### ISSUE TITLE
How to hit <C-P> to populate previous search in fzf window?

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#349]
### Description 

Hi, in `fzf.vim`, When I do `Rg`, I can populate previous search string in the fzf window by hitting `<C-P>` . But It seems like the behavior is different here. I see we have the `resume` search, but that's inconvenient that we need to use another key mapping for `Rg resume`, while with the `fzf.vim` I can just have 1 key map for `Rg`, then `<C-P>` for going through the search history.

**Comment by ibhagwan** [comment]
> go backward-forward search string history by <C-P>, <C-N>

For this I’d have to refactor the logic of saving the typed query for `resume` to save a history of all search strings and typed queries, I’ll change this issue to a feature request and consider it one day when I get inspired.

The issue I have with this is how to make the logic work, if we’re already saving query history shouldn’t the queries typed in `files` be saved as well? Should search strings be saved alongside typed queries? What happens if I press `ctrl-p` while on `files` or `lsp_`, should history be saved per category or combined between all providers. Then comes user preferences, what if the answers to the above are a mixed bag? At that point I have to add some new options to control the behavior as not all users are alike.

Only once the logic is clear I can do it properly.

**Comment by sandangel** [comment]
have you tried the fzf.vim before? I think the author saved the history for each provider. 
And he only saved typed queries (on fzf). So files or lsp_ is the same with grep, when user type something and hit enter, the typed query is saved.

For the first version I would recommend to stick with the behavior from fzf.vim, since most users coming from there, so we should preserve the same experience.

**Comment by sandangel** [comment]
As I remember users are allowed to specify the file path for the search history of each provider, so if they want they can use the same file path for all providers.

**Comment by kaihowl** [comment]
Without handling the edge case of first creating the folder structure to save the history, I can get basic history working with
```
local fzf_history_dir = vim.fn.expand('~/.local/share/fzf-history')
require('fzf-lua').setup{
  -- [...]
  fzf_opts = {
     -- [...]
     ['--history']     = fzf_history_dir .. '/' .. 'myhistory'
  },
}
```

**Comment by ibhagwan** [comment]
Tysm @kaihowl, I didn’t know this existed, after reading the manual entry for `--history` seems to be exactly what @sandangel was talking about:

```man
--history=HISTORY_FILE
Load search history from the specified file and update the file on completion.
When enabled, CTRL-N and CTRL-P are automatically remapped to next-history and previous-history.

--history-size=N
Maximum number of entries in the history file (default: 1000).
The file is automatically truncated when the number of the lines exceeds the value
```

@sandangel, can you try what @kaihowl suggested?

**Comment by sandangel** [comment]
oh yeah. I think it does the job. thank you very much @kaihowl and @ibhagwan ❤️

**Comment by teto** [comment]
would love to have this builtin (this is the one thing I miss from telescope), if not at least the tip should be in the wiki. The solution works great but the folder needs to exist.

**Comment by ibhagwan** [comment]
> would love to have this builtin (this is the one thing I miss from telescope), if not at least the tip should be in the wiki. The solution works great but the folder needs to exist.

The Wiki is open edit for everyone :)

**Comment by teto** [comment]
I've updated the wiki

**Comment by ibhagwan** [comment]
Ty @teto! I updated it once more with adittional exmaple for a separate history for `files` and `grep`.

https://github.com/ibhagwan/fzf-lua/wiki#custom-history

**Comment by nyngwang** [comment]
My use case: I usually run neovim inside tmux, and I also use terminal-buffer inside neovim. To make <C-n>, <C-p> has the behaviour like neovim is not running inside tmux, I remapped <C-n>,<C-p> to sends Up/Down arrow keys.

@ibhagwan Then, given my use case, how could I facilitate this feature...

**Comment by ibhagwan** [comment]
> My use case: I usually run neovim inside tmux, and I also use terminal-buffer inside neovim. To make , has the behaviour like neovim is not running inside tmux, I remapped , to sends Up/Down arrow keys.
> 
> @ibhagwan Then, given my use case, how could I facilitate this feature...? (i.e. with the option `fzf_opts['--history']`)

You can use `keymaps.fzf` to bind different keys to `next-history` and `previous-history` (fzf defaults are `ctrl-n` and `ctrl-p`).
