### ISSUE TITLE
Does sane defaults prefers fd/bat/rg? [Documentation]

### ISSUE THREAD

**Issue by mizhozan** [ibhagwan/fzf-lua#35]
I searched the repo to see if I need to config fzf-lua and force it use fd/bat/rg e.g. [here](https://github.com/ibhagwan/fzf-lua/wiki#recommended-setup), but as newbie couldn't find this information. Would someone confirm if a user still needs to customize the plugin, or the fd/bat/rg would automatically prioritize over alternatives. 

Plus it would be great if this be explicit in the documentation.

**Comment by ibhagwan** [comment]
Yes, the defaults will prefer `fd`, `rg` and `bat`.

I’ll make this is clear when I get to completing [the Wiki](https://github.com/ibhagwan/fzf-lua/wiki).
