### ISSUE TITLE
grep regex support (maybe as an option?)

### ISSUE THREAD

**Issue by doongjohn** [ibhagwan/fzf-lua#350]
maybe there is another way that I can use regex without surrounding the `search_query` with single quotes but this worked for me

grep.lua
```diff
...
  -- do not escape at all
  if not (no_esc == 2 or opts.no_esc == 2) then
    -- we need to use our own version of 'shellescape'
    -- that doesn't escape '\' on fish shell (#340)
    search_query = libuv.shellescape(search_query)
  end

-  return string.format('%s %s %s', command, search_query, search_path)
+  return string.format("%s '%s' %s", command, search_query, search_path)
end
...
```

**Comment by ibhagwan** [comment]
You shouldn’t need to use single quotes, it will break when you want to use single quotes as part of your search.

If you wish to use regex directly you can use `grep({ no_esc=true, search='REGEX' })` or you can use `live_grep` which accepts regex in the query prompt.

**Comment by ibhagwan** [comment]
Read #340 for some more examples how to use regex and how to debug the generated `rg` command.

**Comment by doongjohn** [comment]
thanks for the explanation!
