### ISSUE TITLE
lsp_code_actions - Error: Cannot deepcopy object of type userdata - (Flutter)

### ISSUE THREAD

**Issue by ljgago** [ibhagwan/fzf-lua#353]
### Info

- Operating System: Ubuntu 20.04
- Shell: zsh
- Terminal: Gnome terminal
- `nvim --version`: v0.6.1
- `fzf --version`: 0.29.0 (dc975e8)

- [x] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  fzf_opts = {
    ["--layout"] = "default",
  }
})
```
</details>

### Description 

I am writing flutter code with `akinsho/flutter-tools.nvim` and I when use `:FzfLua lsp_code_actions` I have the follow error:

```
Error executing vim.schedule lua callback: ...packer/start/fzf-lua/lua/fzf-lua/providers/ui_select.lua:122: vim/shared.lua:47: Cannot deepcopy object of type userdata
stack traceback:
        [builtin#36]: at 0x560d4738ae90
        ...packer/start/fzf-lua/lua/fzf-lua/providers/ui_select.lua:122: in function 'select'
        ...mount_vGFyMRT/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:557: in function 'on_code_action_results'
        ...mount_vGFyMRT/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:575: in function 'callback'
        /tmp/.mount_vGFyMRT/usr/share/nvim/runtime/lua/vim/lsp.lua:1472: in function 'handler'
        /tmp/.mount_vGFyMRT/usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```
With `:Telescope lsp_code_actions` or with `:lua vim.lsp.buf.code_action()` works fine.
(If after the error I run again `:lua vim.lsp.buf.code_action()` it fails as if the error will remain in memory)  

I found that `vim.deepcopy()` in this line produce the issue:
https://github.com/ibhagwan/fzf-lua/blob/1d19980551375cde90757ae034d1ffa71dd61bad/lua/fzf-lua/core.lua#L59

**Comment by ibhagwan** [comment]
Added a falback for `vim.deepcopy`, hopefully it should work without any changes.

In addition, by default the code detects the existence of `vim.ui.select` and uses that for the code action interface, I also added an option named `ui_select` (default:`true`) to control this behavior so you can now also call code actions in the old way (enumerate code actions directly from the LSP, similar to Telescope).

If you updated to the latest commit and it still doesn't work run:
```lua
:lua require'fzf-lua'.lsp_code_actions({ ui_select = false })
```

**Comment by ljgago** [comment]
Thanks! is working!
This worked with the default setting.

Thanks very much!
