### ISSUE TITLE
tags error: `tags\: No such file or directory (os error 2)`

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#357]
### Info

- Operating System: MacOS
- Shell: fish
- Terminal: kitty
- `nvim --version`: HEAD
- `fzf --version`: 0.29.0

- [x] The issue is reproducible with `minimal_init.lua`

### Description 

`tags` file exists in project root dir, which is where nvim is started and which is where lsp is rooted at.
- `FzfLua tags` works fine and reads the correct tags file.
- `FzfLua tags_grep_cword` works fine as well
-  `FzfLua tags_live_grep` does not work, and the following error is printed after typing any character
`tags\: No such file or directory (os error 2)`. When I copy the `tags` file to `tags\` in the same directory, even this starts working.

**Comment by ViRu-ThE-ViRuS** [comment]
this is what I see with debug flag in `tags_live_grep`:
```
> [DEBUG]: rg --column --color=always --hidden --follow --no-heading --smart-case --no-ignore -g "!{.DS_Store,.cache,venv,.git,.clangd,.ccls-cache,*.o,build,*.dSYM}" 'adsf' \tags\\
```

the tags file name is not passed correctly ^^

**Comment by ibhagwan** [comment]
Similar issue to #340, I just forgot to apply the fish shell fix when `live_grep`'ing a single file.

https://github.com/ibhagwan/fzf-lua/commit/66dcd313d8de30adf4030f02932349631e5ab892 - should work now.
