### ISSUE TITLE
`require('fzf-lua').grep({search=''})` does not respect `rg_opts`

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#359]
<img width="858" alt="Screen Shot 2022-03-08 at 15 45 00" src="https://user-images.githubusercontent.com/16427330/157344856-67886b51-fc3a-4c06-95dd-c1aba5cebb58.png">
<img width="1009" alt="Screen Shot 2022-03-08 at 15 44 51" src="https://user-images.githubusercontent.com/16427330/157344861-68002211-98f2-4994-ba31-077073df78f5.png">

the same command called in different ways ^^
one follows rg options where I ask for the line / col
one doesn't

are these commands supposed to do the same thing? I can see even the results are different with one showing the search string explicitly one not?

this doesn't happen when you pass non empty string to lua call: `require('fzf-lua').grep({search=' '})`. this call follows rg_opts

**Comment by ibhagwan** [comment]
These aren’t the same commands, as you with the first command you’re searching for `''` and in the second you’re searching for an actual empty string.

When using the `:FzfLua` variant you don’t need to add quotes as it’s considered a string already (both are the same result below):
```lua
:FzfLua grep search=123
require('fzf-lua').grep({search=' 123'})
```

Not really sure how to send an empty lua string with the `:FzfLua` command, I’ll look into it but if that’s what you’re after why not run `:FzfLua grep_project` (shortcut to empty string grep)?

**Comment by ViRu-ThE-ViRuS** [comment]
I see, but the functionality im looking for is the following: 

`utilsstatusline` finds the match as `status line` in `utils.lua` file (option just one keypress up)...
so its kind of a filter through both file and content (the online line preview), and its more useful than you would think haha XD

![Screen Shot 2022-03-09 at 01 20 40](https://user-images.githubusercontent.com/16427330/157411480-d71380a3-b927-4f1e-be25-7d740f2fd0dc.png)


ill switch to the use of `FzfLua grep search=` then, no need to duplicate functionality!

**Comment by ibhagwan** [comment]
> utilsstatusline finds the match as status line in utils.lua file

Another thing you can try is use `live_grep_glob`:
```lua
require('fzf-lua').live_grep_glob({ search='statusline -- utils.lua' })
```

I also added a new feature yesterday where you can “edit” the search/grep string, press `<Ctrl-i>`to toggle between grep and live_grep, so the workflow would be to toggle to live_grep, reduce the matches to roughly what you want and then switch back to grep (with the live grep string) for further refinement using fuzzy matching.
