### ISSUE TITLE
Handle file system loop errors

### ISSUE THREAD

**Issue by kyangk** [ibhagwan/fzf-lua#360]
### Info

- Operating System: Linux
- Shell: Bash
- Terminal: gnome-terminal
- `nvim --version`:

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `fzf --version`:
```
0.29.0 (dc975e8)
```

- [ ] The issue is reproducible with `minimal_init.lua` (I didn't try)

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

Projects might have symlinks that cause file system loops. Both find and rg will print out something on stderr. fzf-lua seems to print these messages in the file list window. Can we have fzf-lua ignore these just like how fzf does?

```
$ rg --files --follow | grep loop
File system loop found: ./<path A> points to an ancestor ./<path Z>
File system loop found: ./<path B> points to an ancestor ./<path Z>
```

```
$ find -L . | grep loop
find: File system loop detected; ‘./<path A>’ is part of the same file system loop as ‘./<path Z>’.
find: File system loop detected; ‘./<path B>’ is part of the same file system loop as ‘./<path Z>’.
```

**Comment by ibhagwan** [comment]
All you need to do is send the command error stream to `/dev/null`, in your examples:
```lua
:lua require'fzf-lua'.files({cmd='rg --files --follow 2>/dev/null'})
:lua require'fzf-lua'.files({cmd='find -L . 2>/dev/null'})
```

**Comment by ibhagwan** [comment]
Btw, if you're still experimenting/configuting your plugin I recommend adding `debug=true` so you can see how the underlying command is constructed, for exmaple:
>`:lua require'fzf-lua'.files({fd_opts="--color=never --type f --hidden --follow --exclude .git 2>/dev/null",debug=true})`
![image](https://user-images.githubusercontent.com/59988195/157395594-9e2924ae-5786-4015-8591-732b06fd22db.png)
