### ISSUE TITLE
Feature request: Allow pasting from buffers into fzf prompt

### ISSUE THREAD

**Issue by kmoschcau** [ibhagwan/fzf-lua#362]
Hi, it would be really useful, if I could for example paste my last vim search into the live_grep prompt input. I tried doing so with Ctrl-r, but that doesn't work.

**Comment by ibhagwan** [comment]
FzfLua runs in a terminal buffer, if you wish to paste from a register you need to first enter normal mode using `<C-\><C-n>`, I have the below in [my own key maps](https://github.com/ibhagwan/nvim-lua/blob/f2ba434bc35fa1732f1a4a6d00f8752244426b13/lua/keymaps.lua#L72):
```lua
remap('t', '<M-r>', [['<C-\><C-N>"'.nr2char(getchar()).'pi']],
    { noremap = true, expr = true })
```
