### ISSUE TITLE
Feature request: Show only relative paths in fzf oldfiles

### ISSUE THREAD

**Issue by bartoszmaka** [ibhagwan/fzf-lua#363]
Hi. Currently the oldfiles command shows files with their full, absolute paths

<img width="2395" alt="image" src="https://user-images.githubusercontent.com/12910127/157860076-bd750cec-f976-45ff-8cb8-6e80c547bd3e.png">

I'm wondering if this would be much work, to add an option, which would make the oldfiles list show only relative paths, like e.g `files` command does.

<img width="2347" alt="image" src="https://user-images.githubusercontent.com/12910127/157860259-037e6238-4870-4b9f-985f-9e54a0eb0145.png">

**Comment by ibhagwan** [comment]
Use the `cwd` option to control the relative path.

> both commands are the same:
```lua
:FzfLua oldfiles cwd=~
:lua reauire'fzf-lua'.oldfiles({ cwd='~' })
```

**Comment by nyngwang** [comment]
Is it possible to set this using `setup {}`?

**Comment by ibhagwan** [comment]
> @ibhagwan: Is it possible to set this using `setup {}`?

Yes, any call option can be specified under the same category inside `setup`, just add it under `oldfiles`:
```lua
require'fzf-lua'.setup {
  oldfiles = {
    cwd= '~'
  }
}
```

**Comment by ibhagwan** [comment]
I personally use two different mappings for `oldfiles`, the reason the second mapping is a function is because I often change my working directory, this makes sure I get the updated `pwd` and not just the one I opened nvim under.

> [source](https://github.com/ibhagwan/nvim-lua/blob/f2ba434bc35fa1732f1a4a6d00f8752244426b13/lua/plugins/fzf-lua/mappings.lua#L42)
```lua
map_fzf('n', '<leader>fh', "oldfiles", { cwd = "~" })
map_fzf('n', '<leader>fH', "oldfiles", function()
  return {
    cwd = vim.loop.cwd(),
    show_cwd_header = true,
    cwd_only = true,
  }
end)
```
