### ISSUE TITLE
`border = "none"` keeps border as part of width/height

### ISSUE THREAD

**Issue by cwqt** [ibhagwan/fzf-lua#364]
### Info

- Operating System: macOS
- Shell: fish
- Terminal: kitty
- `nvim --version`: NVIM v0.7.0-dev+1186-g83fc91433
- `fzf --version`: 0.28.0 (brew)

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
  fzf_opts = {
    ["--ansi"] = "",
    ["--prompt"] = "-",
    ["--info"] = "inline",
    ["--height"] = "100%",
    ["--layout"] = "default",
  },
  winopts = {
    height = 0.5,
    width = 1,
    row = 200, -- 1=bottom isn't true, setting it to some silly high number puts the window at the bottom though
    col = 0,
    border = "none",
    preview = {
      border = "noborder",
      scrollbar = false,
      title = false,
      layout = "horizontal", -- horizontal|vertical|flex
    },
  },
})
```
</details>

### Description 

Setting `winopts.border` to `"none"` keeps a character of width as part of the total dimensions of the floating window, e.g.

## With border
<img width="477" alt="Screenshot 2022-03-13 at 3 45 20 pm" src="https://user-images.githubusercontent.com/61694629/158067812-a596e4f3-2652-4df4-bef0-42d35ebd97b4.png">

## Without border
<img width="354" alt="Screenshot 2022-03-13 at 3 45 29 pm" src="https://user-images.githubusercontent.com/61694629/158067817-5ada5877-d047-4647-8b58-1f3a519ea882.png">

## fzf.vim for comparison
<img width="310" alt="Screenshot 2022-03-13 at 3 45 59 pm" src="https://user-images.githubusercontent.com/61694629/158067822-5493031e-7f9e-4e5b-88ed-d7cce0f2986e.png">

See there's 1 character at the sides of the floating window? whereas in fzf.vim it's flush against the side.
Also vertically, there's a row of empty characters from the bottom of the cmdline, whereas fzf.vim there is no empty rows.

**Comment by ibhagwan** [comment]
That’s not currently possible, as it stands the border is its own window with manual drawing of the border characters (hence the ability to draw the preview title), I’ll check the code later to see if it’s possible (without completely botching the layout) to increase the inner preview window (where `fzf` is spawned).

On another note, if your wish is to have the window at the bottom with no borders, have you tried using a bottom split by setting `winopts.split` to `belowright new`?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/326ec9e1d0da22f30d5296ccb95eac989766117f - should work as you want now regardless of `winopts.split` setting.

One more comment regarding:
>`row = 200, -- 1=bottom isn't true, setting it to some silly high number puts the window at the bottom though`

Technically you could have set it to `0.99` for the same effect, the reason I disabled it for `1` was that I wanted to give users the option to use integers for absolute `(row,col)` positioning when setting `row|col>=1`, the above commit changes that to `row|col>=2,2` so you can now set it to `1` for bottom.

>Not that I think this has many use cases but users that now wish to use `1,1` for absolute positioning can use `1.01,1.01`).

**Comment by cwqt** [comment]
thanks for the quick fix! :) 

> On another note, if your wish is to have the window at the bottom with no borders, have you tried using a bottom split by setting winopts.split to belowright new?

I did try that initially, but that shifts the buffer contents up by the height of the fzf window

> Technically you could have set it to 0.99 for the same effect, the reason I disabled it for 1 was that I wanted to give users the option to use integers for absolute (row,col) positioning when setting row|col>=1, the above commit changes that to row|col>=2,2 so you can now set it to 1 for bottom.



Yes I read about that at https://github.com/ibhagwan/fzf-lua/issues/180#issuecomment-939946339 a bit after posting this issue, I think the way you've done it now makes more sense ^^


One more thing, is it possible to provide an option to make `row=1` mean to be on top of the statusline? See this vid:

https://user-images.githubusercontent.com/61694629/158082077-d33ca5e4-4c08-46be-a143-fbc70c5da10b.mov

The statusline just shows the filename, which is pretty useless to me while searching...

**Comment by ibhagwan** [comment]
>One more thing, I think the positioning code is off-by-one now, row=1 should mean to be on top of the statusline right?
>The statusline just shows the filename, which is pretty useless to me while searching... should look like the fzf.vim screenshot I posted in OP

I'm not sure why this happens, the total available height is automatically calculated and `row` set to `1` **should override the statusline**, I tried replicating your setup and mine does cover the status line.

Few questions so we can get to the bottom of this:
>I'm trying to understand which one is calculated wrongly, the starting row or the window height.
- Does toggling fullscreen (`<F2>` default bind) cover the statusline?
- Does setting `row=200` solve this issue?
- Can you please post the response you get to:
```vim
:set columns? lines? cmdheight?
```
And also if you can start FzfLua while the cursor is on line 1 and let me know what is the last line not covered by the preview window (e.g. `38` in your screen capture).

**Comment by ibhagwan** [comment]
I can't seem to reproduce this issue, tried both odd and even window heights, different `cmdheight` with your almost identical setup and it covers my statusline:

![image](https://user-images.githubusercontent.com/59988195/158084855-9911b4b1-b7b3-4548-a96a-8957bbd85d32.png)

**Comment by ibhagwan** [comment]
> Though even in your setup there's a 1 row gap between -- TERMINAL -- and the fzf search input, which is where my statusline is - so if we can remove that gap then maybe it'd fix mine too?

The reason I have this gap is by design, the code adjusts to `cmdheight` which is set to 2 in my setup vs in your setup where it’s set to 1, when I `:set cmdheight=1` it covers my status line all the way to to the bottom, would be interesting to see what happens if you set `cmdheight` to different numbers in your setup.

Ty for the detailed reply and linking your dot files, I’ll update soon with my findings.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/fccdaeb07527a1c7ac65f39167724f3ed38d0514 - should work now, turn out it was your custom border characters:
```lua
border = { "─", "─", "─", " ", "", "", "", " " },
```

Turns out there's a diference between an empty string (`""`) and a string containing space (`" "`), nvim will detect the empty string and use the available space to adjust the window up or down, this works for both bottom and top borders.

The latest commit makes the same adjustments we did earlier for `none` for the top and bottom borders individually.

**Comment by cwqt** [comment]
Ahh okay, just updated and looks great!

<img width="190" alt="image" src="https://user-images.githubusercontent.com/61694629/158268844-08993b99-3316-433a-ae2d-2d75613c6dff.png">
