### ISSUE TITLE
feature: switch between `grep_cword` and `live_grep_glob`

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#365]
I am thinking on the lines of how the newly added action `grep_lgrep` allows us to search for a string, then switch to lgrep to filter out files, then switch back for even more filtering and so on...

an action to switch between `grep_cword` and `live_grep_glob` would be useful, as it would allow us to search the current word, and then filter out  which files we want to look for it in: (much better than switching first then retyping search term:

<img width="759" alt="Screen Shot 2022-03-13 at 20 19 35" src="https://user-images.githubusercontent.com/16427330/158099303-d1ed14ac-6738-45b2-a128-25a2595ea7d0.png">
here, I could switch to glob mode and filter out `.h` files easily, rather than 

maybe a `lgrep_glob` and `grep_glob` (or maybe a combined action for any grep mode into `glob` mode)

**Comment by ViRu-ThE-ViRuS** [comment]
unrelated:
- how to remove that weird grey column above the `>` current entry. I have it even in normal terminal `fzf`.

**Comment by ibhagwan** [comment]
> an action to switch between `grep_cword` and `live_grep_glob` would be useful

I also use mainly `live_grep_glob`, I’ll think what is most intuitive way to do this, currently the `ctrl-g` switches to live grep, what if it’s as simple as an option  that makes it switch to`live_grep_glob` instead? The only tricky part would be to maintain the `iglob` arguments when switching to regular grep, shouldn’t be a big deal.

> how to remove that weird grey column above the > current entry. I have it even in normal terminal fzf for some reason?

That’s the `gutter` color, FzfLua knows how to translate neovim highlights to terminal ones, all you have to do is set it to `Normal` and it will disappear, below is my `fzf_colors` (from my `setup`):
> you don’t need to specify all, only use the ones you wish to modify
```lua
  fzf_colors = {
    ["fg"] = { "fg", "CursorLine" },
    ["bg"] = { "bg", "Normal" },
    ["hl"] = { "fg", "Comment" },
    ["fg+"] = { "fg", "ModeMsg" },
    ["bg+"] = { "bg", "CursorLine" },
    ["hl+"] = { "fg", "Statement" },
    ["info"] = { "fg", "PreProc" },
    ["prompt"] = { "fg", "Conditional" },
    ["pointer"] = { "fg", "Exception" },
    ["marker"] = { "fg", "Keyword" },
    ["spinner"] = { "fg", "Label" },
    ["header"] = { "fg", "Comment" },
    ["gutter"] = { "bg", "Normal" },
  }
 ```

**Comment by ibhagwan** [comment]
Btw, I’m happy to learn someone is actually using this new feature and understand it’s power :)

**Comment by ibhagwan** [comment]
Added new option under grep, `grep.rg_glob`, when specified, glob parsing will be enabled and will also be considered when switching between grep and live grep with the `ctrl-g` action (`grep_lgrep`).

You can either set it up during `setup` or not at all, starting `live_grep_glob` or `live_grep({ rg_glob=true })` 
 (both are the same now) makes it so the `ctrl-g` action enables it for grep as well.

If you enable it during `setup` any `grep` call will use glob parsing:
```lua
require'fzf-lua'.setup {
  grep = {
    rg_glob = true,
  },
}
```

You can now use the default separator `--` in any `grep` call, i.e.:
```
:lua require'fzf-lua'.grep({ search="pcall( -- *tree*", debug=true })
```

will result in:
![image](https://user-images.githubusercontent.com/59988195/158276264-26fb8acf-42b8-4ba1-8094-88745ca4f185.png)

And pressing `ctrl-g` will result in:
![image](https://user-images.githubusercontent.com/59988195/158276327-f3998d5b-2d6e-4dd3-a806-3707f19d3a2b.png)

**Comment by ViRu-ThE-ViRuS** [comment]
this works great with `live_grep` as it with this option set, it works exactly like `live_grep_glob`!!!!! It is not working with `live_grep_native` tho (neither does `grep_lgrep` work with it).

Also, this is new, I get error when I switch use `grep_lgrep` in `tags` with an empty query:
```
Error executing vim.schedule lua callback: ...te/pack/packer/opt/fzf-lua/lua/fzf-lua/previewer/fzf.l
ua:221: attempt to perform arithmetic on field 'line' (a string value)
stack traceback:
        ...te/pack/packer/opt/fzf-lua/lua/fzf-lua/previewer/fzf.lua:221: in function 'fn'
        .../nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/shell.lua:121: in function 'fn'
        .../nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/shell.lua:41: in function <.../nvim/site/p
ack/packer/opt/fzf-lua/lua/fzf-lua/shell.lua:40>
```

**Comment by ViRu-ThE-ViRuS** [comment]
im not sure if this is a bug, so im not making a new issue:

I have to set `tags.actions` to set:
```lua
['ctrl-g'] = false,
```

otherwise, I see the `<c-g> to live grep` while in the `tags` command, using which doesn't make sense (because its already live grep) and also pressing `<c-g>` causes it to error out / glitch.

also, going from `grep_cword` -> `grep_lgrep` -> delete entered text -> `grep_lgrep` again causes this:
```
[Fzf-lua] fzf error 1: <null>
```
notification to be printed, its like a glitch but it remains functional.

**Comment by ibhagwan** [comment]
> It is not working with live_grep_native tho (neither does grep_lgrep work with it).

It’s not meant to work with the native version, as it’s name suggests it runs `rg` piped in the shell directly, it cannot do any processing this way.

> in tags, using grep_lgrep causes this to be printed out:

What were you searching for? Is your `tags` file named `1`? Is it possible you were searching for something that doesn’t exist as a tag?

> furthermore, the query isn't carried when doing tags -> grep_lgrep. tags_live_grep -> grep_lgrep works fine as expected.

This is by design, tags have their own `last_search` variable, they aren’t the same and shouldn’t mix up IMO.

> [Fzf-lua] fzf error 1: <null>

This is harmless, the reason it’s there is because sometimes exit code `1` has a meaningful error, I’ll remove it when the message is empty.

**Comment by ibhagwan** [comment]
> [Fzf-lua] Unable to find pattern '0=unsorted, 1=sorted, 2=foldcase' in file '1'

This is printed when using the `bat` previewer with tags, this seems to be a non existent tag in a file named `1`?

If you can print the selected line while this happens we can further investigate why this failed.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/c11cb21e9053a7e00b7a54e4c25216bc98283681:

>```
>[Fzf-lua] fzf error 1: <null>
>```

Won't show up anymore when switching with empty queries.

>```
>[Fzf-lua] Unable to find pattern '0=unsorted, 1=sorted, 2=foldcase' in file '1'
>```

Prepended the word `preview` to the warning message, if you believe this is wrong and the tag still exists can you send a screenshot of the selected line and the corresendponding tag it should go to and we'll find out why the tag grep failed.

**Comment by ibhagwan** [comment]
> furthermore, the query isn't carried when doing tags -> grep_lgrep. tags_live_grep -> grep_lgrep works fine as expected.

I think I understand what you're saying now, this is again, by design, when you're using `tags` you're just fuzzy matching it's not suppose to be carried to the live grep variant, `live_grep` is meant to limit the search by modifying the underlying `rg` grep string, the typed query when fuzzy matching shouldn't mean much, even in `grep` (not `tags`) the typed query never carries over to `live_grep`.

There might be a use case where the typed query in `grep` can carry over to `live_grep` when the original grep string is empty but I fear this might even cause more confusion to how this is supposed to work.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/0219921e4169ff25270f20efc7d709ab13df8acd - scrap the last comment, it will work how you want it now, when using an empty grep string with both `tags` and `grep` the last typed query will be considered the grep string, so now this should work:
1. start `grep` with an empty string (or `grep_project` or `tags`)
2. type a query: `foo`
3. press `ctrl-g` to switch to `live_grep`
4. the grep string should appear as `foo`

Note that past this point if you press `ctrl-g` again you'll actually perform `grep({ search='foo' })` and any subsequent typing won't be included in the switch back to `live_grep` as it will switch back to modifying `foo`.

**Comment by ViRu-ThE-ViRuS** [comment]
> Note that past this point if you press ctrl-g again you'll actually perform grep({ search='foo' }) and any subsequent typing won't be included in the switch back to live_grep as it will switch back to modifying foo. 

Yep! this is what I was talking about, it works as expected now. Thanks for working on this, I think the commands are more consistent in behavior now!

**Comment by ViRu-ThE-ViRuS** [comment]
> Prepended the word preview to the warning message, if you believe this is wrong and the tag still exists can you send a screenshot of the selected line and the corresendponding tag it should go to and we'll find out why the tag grep failed.

Okay, I think the new error message helped me narrow it down:

<img width="754" alt="Screen Shot 2022-03-15 at 18 41 01" src="https://user-images.githubusercontent.com/16427330/158499742-478d76f3-6b5c-4851-a83d-a410ad7b186a.png">


As you can see, I am seeing results from he top section of the ctags file generated using the cmd: `ctags -R --excmd=combine`

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_EXCMD	combineV2	/number, pattern, mixed, or combineV2/
!_TAG_OUTPUT_FILESEP	slash	/slash or backslash/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PATTERN_LENGTH_LIMIT	96	/0 for no limit/
!_TAG_PROC_CWD	/Users/viraat-chandra/.config/nvim/	//
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	5.9.0	//
....
<tags start after this>
```
tags file ^^


this second I believe is supposed to be ignored when parsing the tags file.
This is where the `1` file error came from.

**Comment by ibhagwan** [comment]
>this second I believe is supposed to be ignored when parsing the tags file.
>This is where the 1 file error came from.

You're correct, this issue only happens when running `tags_grep` (or `ctrl-g`) or `tags_live_grep` and not with plain `tags` -  when running `tags` the executed command is  `rg -v '^!_TAG_' <ctag_file>` which excludes these but when running the grep and live grep variants the command must search for the grep string and I couldn't find a way to add the `-v ...` part to exclude the ctag headers.

It didn't seem a big deal to me so I didn't bother searching for a way to exclude and include in the same `rg` search, I'll give it another shot.

Another option was to exclude it during processing but due to the way my external processor works (the `multiprocess=true` thingie) returning empty lines when I detect a tag creates excess empty lines, solving that would require a deeper intervention in the `libuv.spawn.process_lines` function which might be costly for performance (plus, it's working so well and everything depends on it now so I don't wanna mess with it):

> As you can see below if I return empty strings when non-tag lines are detected the `\n` still remains:
https://github.com/ibhagwan/fzf-lua/blob/def8abf58667c4d2c9cabdaa5297c793e511a582/lua/fzf-lua/libuv.lua#L152-L158

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/33dae2a6b94e1e58c08f265aacd0eae44c911ae5 - try now, I added a pipe command excluding the ctag headers  when using tags grep and live grep.

**Comment by ViRu-ThE-ViRuS** [comment]
yep! All fixed now, amazing work @ibhagwan , as always :)!!!!!

**Comment by ibhagwan** [comment]
> yep! All fixed now, amazing work @ibhagwan , as always :)!!!!!

Ty <3

**Comment by nyngwang** [comment]
Cool, I'm using this :)
