### ISSUE TITLE
man_pages says can't chmod

### ISSUE THREAD

**Issue by mikesart** [ibhagwan/fzf-lua#368]
The current man cmd is set to `man -c`, but on my Linux system that produces the below error.

I've overridden the default to have just `man %s | col -bx` and it's working great now, but filing this just in case someone else hits it.

Thanks!

> $ man -c printf | col -bx
> man: can't chmod (null): Bad address
> man: can't unlink (null): Bad address
> printf.

> $ man --version
> man 2.10.1

**Comment by ibhagwan** [comment]
Ty for the report @mikesart.

This is what `-c` does on my machine, the below from `man`'s own man page:
```help
     -c      Copy the manual page to the standard output instead of using
             less(1) to paginate it.  This is done by default if the standard
             output is not a terminal device.
```

My man doesn't have a `-v` or `--version` flag, I was able to get the version from the package name:
```text
man-pages-5.13_2                        Linux Documentation Project (LDP) manual pages
```

Can you check if you have a mention of the `-c` flag does in your man version?

**Comment by mikesart** [comment]
Mine says this:

```
     -c, --catman
              This option is not for general use and should only be used
              by the catman program.
```

Interesting there are two man versions so different. I had no idea.

**Comment by ibhagwan** [comment]
Since this issue didn’t come up until now I would assume the more prevalent version is the one that supports `-c`, maybe we can just add a note in the README regarding the different `man` versions?

**Comment by mikesart** [comment]
Turns out I have this one:

https://nongnu.org/man-db/

Which distro are you using? More for curiosity than anything else.

And sure - happy to resolve however you feel is best. I've got this fixed in my .vimrc so I'm all good. :) Thanks!

**Comment by ibhagwan** [comment]
>Turns out I have this one:
>https://nongnu.org/man-db/

I wonder which distros use that, the `-c` flag also works on MacOS so I assume Apple also uses `man-pages`.

> Which distro are you using? More for curiosity than anything else.

I'm using [Void Linux](https://voidlinux.org/), which distro are you using?

> And sure - happy to resolve however you feel is best. I've got this fixed in my .vimrc so I'm all good. :) Thanks!

I'll add a note to the README in the next commit, will wait to close this issue until I do so.

**Comment by mikesart** [comment]
I'm running Debian Testing w/ xfce. Thanks ibhagwan!

```
System:
  Host: mikesart-tr3 Kernel: 5.16.0-4-amd64 x86_64 bits: 64
    Desktop: Xfce 4.16.0 Distro: Debian GNU/Linux bookworm/sid
Machine:
  Type: Desktop System: Gigabyte product: TRX40 AORUS PRO WIFI v: -CF
  Mobo: Gigabyte model: TRX40 AORUS PRO WIFI
    UEFI: American Megatrends LLC. v: F4p date: 04/12/2021
CPU:
  Info: 64-core model: AMD Ryzen Threadripper 3990X bits: 64 type: MT MCP
    cache: L2: 32 MiB
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 3840x1600~60Hz
  OpenGL:
    renderer: AMD Radeon RX 5700 (NAVI10 DRM 3.44.0 5.16.0-4-amd64 LLVM 13.0.1)
    v: 4.6 Mesa 21.3.7
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/4edaa792ff1ef07414365d7facabdac622747cc9 -  added this note above the setting:
```lua
-- NOTE: remove the `-c` flag when using man-db
```
