### ISSUE TITLE
Internal dependency on mkfifo 

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#369]
Tried running the plugin on windows but noticed that there is a dependency on the executable - https://man7.org/linux/man-pages/man3/mkfifo.3.html. Is it possible to make the plugin more cross-platform ?

**Comment by ibhagwan** [comment]
This plugin is only supported on Linux/Mac (as stated in the REDME), supporting windows would take more than just replacing `mkfifo` (which is probably possible if you copy over the windows support code from [`nvim-fzf`](https://github.com/vijaymarupudi/nvim-fzf)), there are other little tricks like shell piping and I assume a few more incompatibilities.

I don’t have access to windows and if I’m being honest I don’t enjoy working on it, as I mentioned in the past I won’t do it myself but would welcome a PR.

**Comment by ibhagwan** [comment]
Closing, if you are capable and wish to embark on the wndows support route feel free to reopen and I'll do my best to help with the code.
