### ISSUE TITLE
Horizontal/vertical split

### ISSUE THREAD

**Issue by dfangx** [ibhagwan/fzf-lua#37]
Hi is there a way to open the fzf window in a horizontal/vertical split rather than a popup?

**Comment by ibhagwan** [comment]
Currently no, I thought about it but it's too big of a refactor right now, at least before I finish all the providers and add the builtin preview with treesitter, for which I might have to include a rather large code change, might be easier to add support for it then, might not.

**Comment by ibhagwan** [comment]
Just added the change, was simpler than I thought, you can either set `winopts.split` option during setup to [set this globally](https://github.com/ibhagwan/fzf-lua#Customization) or individually for each call as per the below:

```lua
-- "new"           : split below
-- "aboveleft new" : split above
-- "vnew"          : split right
-- "aboveleft vnew : split left
:lua require('fzf-lua').files({ winopts = { split = "new" } })
```
