### ISSUE TITLE
`FzfLua grep` will trigger prompt rather than floating window on the first run

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#370]
### Info

- Operating System: macOS 12.3
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: NVIM v0.7.0-dev+1292-ge9b53f3fb
- `fzf --version`: 0.29.0 (brew)

- [x] The issue is reproducible with `minimal_init.lua`

### Description 

I expect that the floating window should be opened at the first call of `FzfLua grep`, while I got:

The floating window is shown after I press `<ESC>` to exit the command mode. And the subsequent `<ESC>` cannot close the floating window correctly.

https://user-images.githubusercontent.com/24765272/159203816-b428644f-60bb-4961-b35d-45836f178838.mov

**Comment by ibhagwan** [comment]
This is not a bug, it’s by design, if you don’t supply any `search` term it prompts for what you’d like to grep for, , if you want to avoid the prompt run `require'fzf-lua'grep( { search = '' } )` or use it’s shortcut `grep_project`.

**Comment by nyngwang** [comment]
@ibhagwan: Thanks for the info. And I have tried both, while it seems that the prompt will still appear after I fresh-start a nvim process?

**Comment by nyngwang** [comment]
> `:lua require'fzf-lua'grep({ search = '' })` - this shows a prompt? Any other options used?

@ibhagwan Yes, I use exactly this command. Now I fallback to use `require'fzf-lua'.live_grep_glob()` which doesn't have this problem.
