### ISSUE TITLE
Tags provider doesn't handle C functions with array parameters

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#371]
### Info

- Operating System: WSL Ubuntu 20.04
- Shell: bash
- Terminal: Windows Terminal
- `nvim --version`: 0.6.0
- `fzf --version`: 0.27.0

- [x] The issue is reproducible with `minimal_init.lua`

### Description 
`:FzfLua tags` does not seem to parse C functions that have array parameters. For example, take the following program:
```c
#include <stdio.h>

void f(int x[3])
{
}

int main(void)
{
}
```

For this code, `:FzfLua tags` returns line 1 for function `f()` which is incorrect.

Running `ctags -R`, the resulting tags file I get is:
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	//
f	test.c	/^void f(int x[3])$/;"	f	typeref:typename:void
main	test.c	/^int main(void)$/;"	f	typeref:typename:int
```

I'm guessing the brackets are the culprit here.

**Comment by ibhagwan** [comment]
> I'm guessing the brackets are the culprit here.

The brackets are culprit indeed and some other special chars seem to be an issue as well, I’ll solve this for both the builtin previewer and the `bat` previewer soon.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/97a63e66bfc74cd32dec04ae7358dc96b184a3a2 - this takes care of all special charaters, tested with the below C file:

If you can think of another special case I missed below let me know.

```cpp
#include <stdio.h>

const char s01[] = "[\\[]~$?*|{}()^%-+./'%\"\r\n\t";
const char s02[] = "\\";
const char s03[] = "[";
const char s04[] = "]";
const char s05[] = "~";
const char s06[] = "$";
const char s07[] = "?";
const char s08[] = "*";
const char s09[] = "|";
const char s10[] = "{";
const char s11[] = "}";
const char s12[] = "(";
const char s13[] = ")";
const char s14[] = "^";
const char s15[] = "%";
const char s16[] = "-";
const char s17[] = "+";
const char s18[] = ".";
const char s19[] = "/";
const char s21[] = "\"";
const char s22[] = "'";
const char s23[] = "%";
const char s24[] = "\r";
const char s25[] = "\n";
const char s26[] = "\t";

void f(int x[3], const char s[]="[\\[]~$?*|{}()^%-+./'%\"\r\n\t")
{
}

int main(void)
{
}
```

**Comment by ibhagwan** [comment]
Btw, not sure if you’re also using Telescope, I opened a PR on Telescope with a similar fix so this should work well there too

https://github.com/nvim-telescope/telescope.nvim/pull/1806
