### ISSUE TITLE
Issue with Kitty in fzf highlighted line

### ISSUE THREAD

**Issue by ivanddm** [ibhagwan/fzf-lua#376]
### Info

- Operating System: macOS
- Shell: Zsh
- Terminal: Kitty
- `nvim --version`: 0.7.0
- `fzf --version`: 0.27.3

### Description 

I'm having this issue in my Kitty terminal (not in Alacritty or iTerm). There is a cursor border in between the icon and the file name (i.e., whenever there is a space in the highlighted line). I tried figuring this out in my kitty config but didn't find a culprit. Perhaps someone can shed some light on why this is showing.

![CleanShot 2022-04-02 at 02 07 29@2x](https://user-images.githubusercontent.com/20104703/161353245-359ed967-aa84-4839-a0e2-deb7e7fe5b8c.png).

Thanks in advance!

**Comment by ibhagwan** [comment]
It might be either the icon padding (kitty supports double width icons) or your font’s support for the nbsp character, can you try adding either of the below to your setup function and lmk which solves it?

> from the README:
```lua
  -- uncomment if your terminal/font does not support unicode character
  -- 'EN SPACE' (U+2002), the below sets it to 'NBSP' (U+00A0) instead
  nbsp = '\xc2\xa0',
```

```lua
  -- double-width icon rendering
  file_icon_padding = ' ',
```

**Comment by ivanddm** [comment]
Thanks for such quick reply.... `nbsp = '\xc2\xa0` did the trick 🙏🏻. I didn't see this in the README, sorry about that. `file_icon_padding = ' '` helps in rendering the icons in Kitty a bit better, but does not solve the issue. I really like Kitty but its issues with rendering some fonts makes me go back to Alacritty or iTerm (although those have other issues as well).

Thanks again!

**Comment by ibhagwan** [comment]
> Thanks for such quick reply.... `nbsp = '\xc2\xa0` did the trick 🙏🏻. I didn't see this in the README, sorry about that. `file_icon_padding = ' '` helps in rendering the icons in Kitty a bit better, but does not solve the issue. I really like Kitty but its issues with rendering some fonts makes me go back to Alacritty or iTerm (although those have other issues as well).
> 
> Thanks again!

The icons come from `nvim-web-devicons`, if you still wish to use kitty you can always override the problematic icons in devicon’s setup function, for example:

```lua
require("nvim-web-devicons").setup({
  override = {
    sol = {
      icon = "♦",
      color = "#a074c4",
      name = "Sol"
    }
  };
})
```
