### ISSUE TITLE
Error when previewing Html files

### ISSUE THREAD

**Issue by ivanddm** [ibhagwan/fzf-lua#377]
I love fzf and your plugin adds amazing features to it. Thanks a lot for this.

Btw. I was happily surprise when I saw you were the author of this plugin which I landed at by chance. I used Arch linux for quite awhile and your picom compositor is so famous and was in my default config since the beginning to add rounded corners! Thanks a lot for your contributions to the open source community.

### Info

- Operating System: macOS
- Shell: Zsh
- Terminal: Kitty/Alacritty/iTerm
- `nvim --version`: 0.7.0
- `fzf --version`:  0.27.3

### Description 

I'm getting the following error when previewing an `html` file, it seems to be related to treesitter:

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/20104703/161354161-3d774d0e-dcf2-41f9-8e7f-a766cf363d54.png">

I don't get this error with Telescope or fzf.vim, though.

https://user-images.githubusercontent.com/20104703/161354258-7c34f8e5-83ae-48be-8c9d-dd9995c9615e.mp4

**Comment by ibhagwan** [comment]
Ty for the kind words @ivanddm! I love fzf too as you can tell :)

This error seems to be coming from treesitter when fzf lua tried to enable syntax highlighting - can you try opening the file and running `filetype detect`?

**Comment by ivanddm** [comment]
Thanks for such quick reply!

So when running `filetype detect` in the `html` file I'm getting this error:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/20104703/161361354-0f837094-a8d6-469d-a204-909d9498d889.png">

**Comment by ibhagwan** [comment]
> So when running filetype detect in the html file I'm getting basically the same error as above

I guess we found the issue :)

From my experience reinstalling the treesitter html module may help (using `:TSUinstall` `:TSInstall`) otherwise it might be a treesitter bug at which case you can disable treesitter for html and maybe open an issue with [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter/issues)?

Before you disable the html treesitter module I would actually try to disable the `incremental_selection` module of treesitter (since that’s where the bug appears to be):

> change to `enable = false`
```lua
require'nvim-treesitter.configs'.setup {
…
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = '<CR>',
      scope_incremental = '<CR>',
      node_incremental = '<Tab>',
      node_decremental = '<S-Tab>',
    },
  },
…
```

**Comment by ivanddm** [comment]
Yes, disabling `incremental_selection` makes the error disappears. I think I can live without that feature. Will open the issue with nvim-treesitter though.

Thanks again!

**Comment by ibhagwan** [comment]
>Yes, disabling incremental_selection makes the error disappears. I think I can live without that feature. Will open the issue with nvim-treesitter though.

I agree, it's nost a must have feature but I must mention I did test the latest nightly with an `html` file and I don't have this issue and since this pops up during an auto command is it possible there's some conflict with an autocmd in your neovim config?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a52aa5087d4032682a57163cb9ff462b492a4d42 - FYI, this commits wraps the `filetype detect` in a `pcall` so it would now fail silently (i.e. no syntax highlighting) instead of raising the annoying execption.

**Comment by ivanddm** [comment]
>  I did test the latest nightly with an html file and I don't have this issue and since this pops up during an auto command is it possible there's some conflict with an autocmd in your neovim config?

I will explore in my config, most likely that is the problem then. Thanks again!
