### ISSUE TITLE
[ Help ] Integrating vim.ui.select with fzf-lua

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#379]
Hello, 

I'm writing a question. 

I've been using `vim.ui.select` quite a bit in my own plugins. 

I think one of the purposes of that is for other picker plugins to override it. 

Is this currently possible with fzf-lua? I.e. I can use `vim.ui.select` in my plugin and if someone has fzf-lua installed the selection criteria will get popped into a fzf-lua window?

**Comment by ibhagwan** [comment]
Have you seen `:FzfLua register_ui_select`?

> FYI, `code_actions` already works this way by registering and de-registering upon win leave.

**Comment by ldelossa** [comment]
Wow its that simple. Thanks, this works!

**Comment by ibhagwan** [comment]
> Wow its that simple. Thanks, this works!

Lots of goodies were added since we last conversed, look at the list of providers in the README maybe you’ll, find other interesting additions / customizations :)

**Comment by ldelossa** [comment]
Thanks a lot

**Comment by ldelossa** [comment]
@ibhagwan one other small follow up question. I added this to the end of my fzf.lua config

```
-- register FzfLua to handle vim.ui.select
vim.cmd("FzfLua register_ui_select")
```

When opening vim I now get an error 
```
[Fzf-lua] vim.ui.select already registered to fzf-lua
```

I don't think I call setup twice in anyway. 

If I remove above line, my plugin no longer uses fzf-lua for selection.

**Comment by ibhagwan** [comment]
My bet would be something with your config/setup, the message wouldn’t appear unless this is called twice, could be your plugin manager calling the file twice?

To test my theory you can add a global variable in your config file for fzf-lua (e.g. `vim.g.fzf_lua_config_called = true`) and prevent the file from being further loaded if the variable exists and see if that helps, if this solves your issue your file is def called twice.

**Comment by ldelossa** [comment]
Cool, let me debug a bit and get back to you.

**Comment by ldelossa** [comment]
Yup found it, my color scheme functions source fzf.lua file again to set the appropriate fzf colors. Thanks!
