### ISSUE TITLE
Installation with packer: 'fzf' is not a valid executable, aborting. Please make sure 'fzf' is installed.

### ISSUE THREAD

**Issue by strdr4605** [ibhagwan/fzf-lua#383]
### Info

- Operating System: MacOS
- Shell: zsh
- Terminal: iTerm
- `nvim --version`: 
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```
- `fzf --version`:
  - No installed globally
  - Located at `~/.local/share/nvim/site/pack/packer/start/fzf/bin/fzf`

- [x] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
local status_ok, fzf_lua = pcall(require, "fzf-lua")
if not status_ok then
  return
end

fzf_lua.setup {
  -- fzf_bin = "/Users/strdr4605/.local/share/nvim/site/pack/packer/start/fzf/bin/fzf"
}
```
</details>

### Description 

I installed this plugin with packer. I did not have fzf installed so I followed the guide with

```lua
  use { "junegunn/fzf", run = "./install --bin" }
  use "ibhagwan/fzf-lua"
```

<img width="394" alt="Screenshot 2022-04-13 at 10 05 08" src="https://user-images.githubusercontent.com/16056918/163139659-f65feaa8-9b3e-4058-84e9-7683266563dc.png">

Are you sure that we need to run `./install --bin`? If yes then fzf-lua should pickup fzf from `~/.local/share/nvim/site/pack/packer/start/fzf/bin/fzf`.

In order to work probably I have to install fzf globally or set my config to

```lua
fzf_lua.setup {
  fzf_bin = "/Users/strdr4605/.local/share/nvim/site/pack/packer/start/fzf/bin/fzf"
}
```

I think the easiest is to write in docs that fzf should be installed globally.

Or fzf-lua should pick up the fzf binary from packer folder.

**Comment by ibhagwan** [comment]
>I think the easiest is to write in docs that fzf should be installed globally.

Easiest? yes. Correct? not IMO :-)

>Or fzf-lua should pick up the fzf binary from packer folder.

https://github.com/ibhagwan/fzf-lua/commit/f7f54dd685cfdf5469a763d3a00392b9291e75f2 - this uses `fzf#exec` (provided by the fzf plugin) to determine the fzf binary path anywhere in the neovim runtime.
