### ISSUE TITLE
Search for related files

### ISSUE THREAD

**Issue by abenz1267** [ibhagwan/fzf-lua#384]
How would i go about searching for related files? For example if i currently work on "MyComponent.tsx" i'd like to search for all files starting with "MyComponent". I figured i'd create a keybind and pass some opts into it..but i'm not sure which opt and i'd first have to spit the current filename at `.` anyways and then take the first result of that array as the search argument to fzf... yeah?

Regards

**Comment by ibhagwan** [comment]
You can use any variation of the current file name (extracted using `vim.fn.expand('%')` and then run `files({ fzf_cli_args = [[--query='<filename>']] })`.

**Comment by ibhagwan** [comment]
Just tested this (`fzf_opts` and `fzf_cli_args` are interchangable):
```lua
:lua require'fzf-lua'.files({ fzf_opts = { ["--query"] = vim.fn.expand('%:t:r') } })
```

**Comment by abenz1267** [comment]
works like a charm!

**Comment by abenz1267** [comment]
sorry for necroing this, but i didn't feel like it's worth opening a new issue:

`files()` doesn't support jump_to_single_result, right? Would be quite handy to support it  think. 
Just for the use-case here:

Lets say you have a frontend project with css-modules. So you have 2 files: `MyComponent.js` and `MyComponent.module.css`

Searching for related files the function call above will give you 2 search results, the one file you called it from and the other file. Usually ofc you just want the other file. So jumping straight to that file isntead of opening the results would be nice.

Technically it's ofc not 1 result, since you get 2 results. Maybe there is a way around that?

**Comment by ibhagwan** [comment]
Unfortunately there is no such functionality but you can create your own `files` specialization and either count the lines in the fzf buffer or maybe you can use the [`--select-1` fzf flag](https://www.mankier.com/1/fzf#--select-1)

**Comment by abenz1267** [comment]
Sadly using the -1 flag doesn't work, because it also returns the initial file so you have 2 results. --select-1 only works if there's only 1 result.

**Comment by ibhagwan** [comment]
> Sadly using the -1 flag doesn't work, because it also returns the initial file so you have 2 results. --select-1 only works if there's only 1 result.

Well in this case your only other option is to create your own copy of the `files` command, get the number of lines in the buffer and when it meets your conditions use `feedkey` to send the required keys to select+confirm.

The functions isn't very long and easily replicable, start here:

https://github.com/ibhagwan/fzf-lua/blob/5722fd62fd737392eae2c3aa1fb103629d7bd564/lua/fzf-lua/providers/files.lua#L36-L43

**Comment by abenz1267** [comment]
`:lua require'fzf-lua'.files({fzf_opts = { ['--exact -1 --query'] = '\"!'..vim.fn.expand('%:e')..' '..vim.split(vim.fn.expand('%:t:r'), '.', true)[1]..'\"' } })<CR>`

This is my whole function call now in case you wonder. this works. It'll now alternate between 2 files :-).

**Comment by ibhagwan** [comment]
Very nice!

**Comment by abenz1267** [comment]
The only thing i'm missing now is the "^" modificator for searching strings that start with, see https://www.mankier.com/1/fzf. But as soon as i start the query with "^" nothing gets found at all.
