### ISSUE TITLE
Message Popup

### ISSUE THREAD

**Issue by sharklasers996** [ibhagwan/fzf-lua#385]
Hi, this is a great plugin, love it, one thing I couldn't figure out how to do - is there a way to show messages at the bottom after performing an action?

In `git_branches`, after switching to a branch, a message is printed `[Fzf-lua] Switched to branch 'master'` but it doesn't appear at the bottom, I can only see it with `:messages`, maybe it's my setup? This happens with default fzf-lua config, any help would be appreciated

**Comment by ibhagwan** [comment]
That is setup dependent, fzf-lua only performs the `print` it cannot control how messages are scrolled, if the text doesn’t have enough space the message will scroll, try using 2 lines for messages by setting `:set cmdheight=2`.

**Comment by sharklasers996** [comment]
Thanks!
