### ISSUE TITLE
 nvim-web-devicons overrides not working in fzf-lua

### ISSUE THREAD

**Issue by doongjohn** [ibhagwan/fzf-lua#386]
### Info

- Operating System: Windows11 WSL2 (Void linux)
- Shell: fish
- Terminal: neovim
- `nvim --version`: 0.6.1
- `fzf --version`: 0.30

- [ ] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description

nvim-web-devicons override works with Telescope but not fzf-lua
```lua
require'nvim-web-devicons'.setup {
  override = {
    nim = {
      icon = "",
      color = "#f3d400",
      cterm_color = "220",
      name = "Nim",
    },
    nims = {
      icon = "",
      color = "#f3d400",
      cterm_color = "220",
      name = "NimScript",
    },
    nimble = {
      icon = "",
      color = "#f3d400",
      cterm_color = "220",
      name = "Nimble",
    },
}
```

Telescope:
![image](https://user-images.githubusercontent.com/40219740/163713864-1cab0782-20d7-4e49-88af-0d81a9d51e33.png)

fzf-lua:
![image](https://user-images.githubusercontent.com/40219740/163713874-ac883508-ae79-4362-8e9d-26da81732692.png)

**Comment by ibhagwan** [comment]
Duplicate #311.

Either set `multiprocess=false` or set `_devicons_setup` [as explained in the wiki](https://github.com/ibhagwan/fzf-lua/wiki#how-can-i-use-custom-devicons-with-multiprocess)

**Comment by ibhagwan** [comment]
FYI, https://github.com/ibhagwan/fzf-lua/commit/604eadfcf69b90cf9e508767ad217107520ce4d4 - this commit makes the additional setup step unnecesary, overrides should works seamlessly now.
