### ISSUE TITLE
Move from `vim.lsp.diagnostics` to `vim.diagnostics`

### ISSUE THREAD

**Issue by P1n3appl3** [ibhagwan/fzf-lua#388]
While the lua api originally included diagnostics as part of the lsp client, that functionality has been moved to its own module and the `vim.lsp.diagnostics` functions are now deprecated.

Outside of keeping up with the upstream nvim api, migrating here would also be helpful so that non-lsp linters work with fzf-lua. For example I use [shellcheck](https://github.com/koalaman/shellcheck) which works fine with all other nvim diagnostics functionality, but doesn't work with fzf-lua just because it checks for an attached language server before opening the diagnostics.

## Changes Required

1. The check for whether clients are attached should be removed from the diagnostics handler. If there is no lsp server (and no other diagnostics) then the user will now see "No diagnostics found" rather than "LSP: no client attached", which makes more sense.
2. Follow `:h deprecated` to migrate to the appropriate new `vim.diagnostics` api.
3. Possibly change the command names from `lsp_document_diagnostics` to just `document_diagnostics` (as well as for `workspace`) and move them out of the lsp section in the docs. Since this would be a breaking change maybe the old names should alias the new ones, or maybe it's not worth changing the names at all.

**Comment by ibhagwan** [comment]
Aside from one, all instances of `vim.lsp.diagnostics` in the code are there for backward compatibility with older neovim versions, it's harmless and makes it so `fzf-lua` is comptabile with versions as early as `0.5` (I have all version AppImages and regularly test them), I don't wish to compatibility as some Linux distributions are stuck with an older version of neovim until they get an update.

The only instance where `vim.lsp.diagnostics` is always used is to create the LSP paramters to determine if code actions exist before invoking the `vim.ui.select` interface (not technically necessary if `register_ui_select` was already called):
https://github.com/ibhagwan/fzf-lua/blob/5060b677e02ba7ce408e7827c8187140e3dd910d/lua/fzf-lua/providers/lsp.lua#L355

I would assume there's currently no alternative to that as [Telescope is also using this for it's code actions](https://github.com/nvim-telescope/telescope.nvim/blob/831f76a809d9f09724d9f3825a3660ed714470d9/lua/telescope/builtin/lsp.lua#L170).

> The check for whether clients are attached should be removed from the diagnostics handler. If there is no lsp server (and no other diagnostics) then the user will now see "No diagnostics found" rather than "LSP: no client attached", which makes more sense.

I believe it still makese sense to alert the user that a client isn't attached vs "No diagnostics found", it's more informative and tells you something is wrong with your LSP setup as you have no LSP server attached (vs not having any diagnostics).

> Follow :h deprecated to migrate to the appropriate new vim.diagnostics api.

As mentioned above, I don't intend to deprecate anything unless I absolutely must, why remove functionality that's already there? 0.5/0.6 users already have no other option for fuzzy finding as Telescope only supports 0.7 and above (and will soon probably be only the nightly).

> Possibly change the command names from lsp_document_diagnostics to just document_diagnostics (as well as for workspace) and move them out of the lsp section in the docs. Since this would be a breaking change maybe the old names should alias the new ones, or maybe it's not worth changing the names at all.

Debatable, although the naming makes more sense with the new API, diagnostics usually means LSP issues for 99% of the users.

>Outside of keeping up with the upstream nvim api, migrating here would also be helpful so that non-lsp linters work with fzf-lua. For example I use [shellcheck](https://github.com/koalaman/shellcheck) which works fine with all other nvim diagnostics functionality, but doesn't work with fzf-lua just because it checks for an attached language server before opening the diagnostics.

For your user case I can add a flag which skips the LSP attach test, lmk if you want that?

**Comment by P1n3appl3** [comment]
Thanks for the quick response. I didn't consider the backwards compatibility aspect, totally agree that there's not enough value to switching at the moment given that you'd lose support for 0.5 (although i assume eventually it will be necessary when the deprecated functions are removed). Also I think `vim.diagnostic.get(0, {lnum = N})` does work as an alternative to `vim.lsp.diagnostic.get_line_diagnostics()` but i guess that's beside the point.

I'd be happy with a flag to disable the check for lsp server attached. Stuff like [cspell](https://github.com/streetsidesoftware/cspell), [https://github.com/cpplint/cpplint](https://github.com/cpplint/cpplint), and [markdownlint](https://github.com/DavidAnson/markdownlint) are all just CLI tools that emit lints which get added to my nvim diagnostics with no language server in-between, so it'll be nice to be able to fzf through their diagnostics.

I still feel like the check doesn't make much since. `vim.diagnostic.goto_next` and `vim.diagnostic.get` work fine with no lsp attached and the consumer of the diagnostics shouldn't care where they come from, but if non-lsp diagnostics are that uncommon then i don't mind the default behavior including the check.

Also thanks so much for the plugin! It makes using nvim quite pleasant and has worked great for me so far.

**Comment by ibhagwan** [comment]
> Thanks for the quick response. I didn't consider the backwards compatibility aspect, totally agree that there's not enough value to switching at the moment given that you'd lose support for 0.5 (although i assume eventually it will be necessary when the deprecated functions are removed). Also I think vim.diagnostic.get(0, {lnum = N}) does work as an alternative to vim.lsp.diagnostic.get_line_diagnostics() but i guess that's beside the point.

If you look at the code, `vim.lsp.diagnostics` is only used when `vim.diagnostic` doesn’t exist (I.e. is `nil`), it can potentially work forever like this as `vim.lsp.diagnostics` will never be called on any version containing `vim.diagnostic`:

https://github.com/ibhagwan/fzf-lua/blob/5060b677e02ba7ce408e7827c8187140e3dd910d/lua/fzf-lua/providers/lsp.lua#L565-L568

> `vim.diagnostic.get(0, {lnum = N})` does work as an alternative to `vim.lsp.diagnostic.get_line_diagnostics()`

I’ll test, if it works the same, I’ll give it priority over `vim.lsp` as the above example.

 > I still feel like the check doesn't make much sense. vim.diagnostic.goto_next and vim.diagnostic.get work fine with no lsp attached and the consumer of the diagnostics shouldn't care where they come from, but if non-lsp diagnostics are that uncommon then i don't mind the default behavior including the check.

Alright, you convinced me, I’ll do the change soon and keep this post updated :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/1bf2a294c8361eecf748d4d5b0e988bdc331c035

>Also I think `vim.diagnostic.get(0, {lnum = N})` does work as an alternative to `vim.lsp.diagnostic.get_line_diagnostics()`

Was a bit more complicated than just switching to the new API, the resulting table needed to be converted to the `get_line_diagnostics` style to form a valid LSP `textDocument/codeAction` request:

https://github.com/ibhagwan/fzf-lua/blob/1bf2a294c8361eecf748d4d5b0e988bdc331c035/lua/fzf-lua/providers/lsp.lua#L346-L371

>I still feel like the check doesn't make much sense. vim.diagnostic.goto_next and vim.diagnostic.get work fine with no lsp attached and the consumer of the diagnostics shouldn't care where they come from, but if non-lsp diagnostics are that uncommon then i don't mind the default behavior including the check.

The check is not longer performed on newer clients that have `vim.diagnostic`, on older clients where diagnostics are still tied to the LSP the check remains.
https://github.com/ibhagwan/fzf-lua/blob/1bf2a294c8361eecf748d4d5b0e988bdc331c035/lua/fzf-lua/providers/lsp.lua#L543-L549

**Comment by ibhagwan** [comment]
Closing, lmk if you need more help with this.
