### ISSUE TITLE
Feature request: resizing the native previewer window on the fly

### ISSUE THREAD

**Issue by arsham** [ibhagwan/fzf-lua#389]
Hi,

Is it possible to assign a key to rotate the preview size?

Having looked into the code, I found the following line, which calculates the preview size:
https://github.com/ibhagwan/fzf-lua/blob/5060b677e02ba7ce408e7827c8187140e3dd910d/lua/fzf-lua/win.lua#L274

I wanted to have a global action (on file or buffer objects), which would simulate what fzf does with this bindings:
```zsh
--bind 'ctrl-/:change-preview-window(right,80%|hidden|right,20%|right)'
```

I'm thinking of changing the `winopts.preview.horizontal` value, and reload/redraw the preview.

Thank you.

**Comment by ibhagwan** [comment]
> Is it possible to assign a key to rotate the preview size?

No such option currently.

> I'm thinking of changing the winopts.preview.horizontal value, and reload/redraw the preview.

Didn’t test this but I believe you can do that with a custom action that calls `require'fzf-lua'.resume({ winopts = … })` with your desired rotation/size.

**Comment by arsham** [comment]
It works perfectly! Thank you.

**Comment by ibhagwan** [comment]
I’d that doesn’t work (or doesn’t work to your liking) you can always create your own neovim bind using the `on_create` event (from the README):
```lua

    on_create = function()
      -- called once upon creation of the fzf main window
      -- can be used to add custom fzf-lua mappings, e.g:
      --   vim.api.nvim_buf_set_keymap(0, "t", "<C-j>", "<Down>",
      --     { silent = true, noremap = true })
    end,
```

You can then duplicate the preview rotation code and do whatever you want with the logic:

https://github.com/ibhagwan/fzf-lua/blob/5060b677e02ba7ce408e7827c8187140e3dd910d/lua/fzf-lua/win.lua#L1061-L1088

**Comment by arsham** [comment]
How can I access the `FzfWin` object from within the `on_create` callback?

**Comment by ibhagwan** [comment]
> How can I access the `FzfWin` object from within the `on_create` callback?

Oops, I forgot you have no accesss to the local `_self` var, update to https://github.com/ibhagwan/fzf-lua/commit/782abfd69c47bbeb672ca7f03584d8fb8cdb4179 and use:
```lua
local self = require'fzf-lua.win'.__SELF()
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/e5ce0700f8a12aee42d2e6068f0c9d3c6fe8b45b - try it out, default actions (configurable via `setup`, works similar to `files`, `grep`, etc) are:
```lua
  blines = {
    actions = {
      -- single selection jumps to location, multiple selection goes to quickfix
      ["default"]     = { actions.buf_edit_or_qf },
      -- explicit bind to send to quickfix
      ["alt-q"]       = { actions.buf_sel_to_qf }
    },
  }
```

**Comment by arsham** [comment]
A part of the snippet above is to call the `generate_layout` function, and it is not exposed. Do you have a recommendation to generate the layout without copying the whole code?

**Comment by ibhagwan** [comment]
> A part of the snippet above is to call the `generate_layout` function, and it is not exposed. Do you have a recommendation to generate the layout without copying the whole code?

https://github.com/ibhagwan/fzf-lua/commit/1b200d3bdc26a7e94a83f4136529a279ffba7de7

Be sure to use the syntactic sugar `self:generate_layout` or call `self.generate_layout(self, ...)` as the function is defined with `:` for convinient access to the `self` object.

**Comment by arsham** [comment]
Awesome, thanks!
