### ISSUE TITLE
How to detect that some files are added-to/removed-from staged files by fzf-lua?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#391]
As title. I have only one question so I skipped the template. These are the expect behaviours:

1. If I add some changes to the file but don't stage them via fzf-lua or git command via neovim terminal, then nothing will be detected.
2. If I add some changes to the file and stage some of them using fzf-lua or git command via neovim terminal, then I want to catch such event.

**Comment by ibhagwan** [comment]
> @ibhagwan Is git_exec(...) synchronous or asynchronous? And how would you solve this kind of problem, if it's OK to be shared.

`git_exec` just runs the command in the shell, it’s **sync**.

Personally, I wouldn’t use `sleep`, it can easily error out if the hunk staging takes longer than 50ms (for whatever reason), I’d find the async callback and run `vim.fn.winrestview(view)` **in or after the callback is called**.

**Comment by nyngwang** [comment]
I think this is a very easy problem for you. But then it will be not related to fzf-lua. Anyway, here is the async function, if you're interested in:

https://github.com/tanvirtin/vgit.nvim/blob/9a2ef0b0edede4dcf35cc53801eed4c7cdd15605/lua/vgit.lua#L198-L200

**Comment by ibhagwan** [comment]
> I think this is a very easy problem for you. But then it will be not related to fzf-lua. Anyway, here is the async function, if you're interested: (If you do solve it please share it with me!)

It’s probably not that hard but from what you linked it seems you have to override some of the code of the `vgit` as it doesn’t seem to expose the interface for modification.

**Comment by ibhagwan** [comment]
Closing as this issue doesn't seem relevant any longer.
