### ISSUE TITLE
[Question] How to disable showing large minified files in `GitStatus`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#392]
As title. This caused a large slowdown.

### Description 

<img src="https://user-images.githubusercontent.com/24765272/164603533-08984415-1617-4a93-b6e0-d7e33f5c967c.png" width="600">

my current config is as follows (I don't have a field for git status.) I also want to know if it's possible to define it once for all the other functions like `files`, `grep`? Thanks in advanced.

```lua
require('fzf-lua').setup {
  -- some parts omitted.
  files = {
    prompt = ' File $ ',
    show_cwd_header = true,
    fd_opts =
      "--hidden "..
      "--no-ignore "..
      "--ignore-case "..
      "--type f "..
      -- "--max-depth 15 "..
      " "..
      "--exclude .local "..
      "--exclude .npm "..
      "--exclude .nvm "..
      "--exclude .tmux "..
      "--exclude .cache "..
      "--exclude .vscode "..
      " "..
      "--exclude .git "..
      "--exclude __pypackages__ "..
      "--exclude node_modules "..
      "--exclude package-lock.json "..
      "--exclude yarn.lock "..
      "--exclude tags "..
      "--exclude .DS_Store "..
      " "
  },
```

**Comment by ibhagwan** [comment]
What do you mean “large minified files? Do you wish to disable preview for these files or remove them from status?

The git status command is defined under `git.status.cmd` and the default value is `git status -s`, if you wish to filter out some files you can pipe a grep command and exclude whatever you want, for example you can set it to `git status -s | rg -v “foo”` - this will exclude all lines containing foo but you can craft any regex, say you wanted to exclude deleted files you can try `git status -s | rg -v “^ D”` which will exclude all lines starting with space D.

**Comment by nyngwang** [comment]
> [..] Do you wish to disable preview for these files or remove them from status?

Just disable the preview! Because I will still need to use the Left/Right-Arrow-stage-unstage feature!

**Comment by ibhagwan** [comment]
Look at the README under `previewers.git_diff`, you can set `cmd_deleted` to whatever you want:
```lua
git_diff = {
      cmd_deleted     = "echo Preview is disabled for deleted files.",
      cmd_modified    = "git diff --color HEAD",
      cmd_untracked   = "git diff --color --no-index /dev/null",
    },
```

**Comment by ibhagwan** [comment]
I think I understand what you want now, “minified” probably meant modified?

If so, what you need to do is write a small script (in any language, sh, bash, python, perl, whatever you’re comfortable with), the script should accept the file path as the first argument `$1` and check it’s size, if it’s above a certain size you can return “Preview disabled for <file>…”, otherwise it should return the git diff using `git diff --color HEAD` then set `cmd_modified = '/home/user/bin/my_git_diff.sh'` and you’ll have what you want.

**Comment by nyngwang** [comment]
> I think I understand what you want now, “minified” probably meant modified?

Oh, I got what you mean. My bad. Minified is just a way to describe the `.js` file compressed into one single line as shown in my picture.

**Comment by nyngwang** [comment]
Is it possible to disable the preview based on the line length or line number? Just use `cmd_deleted` is not very good because I will also need to `git add` such files.

**Comment by nyngwang** [comment]
WIth command `git diff --color HEAD -- 'docs/main.0f2ae283.bundle.js' | cut -c -200` I got from terminal output:

```js
-(self.webpackChunkwebsite_dosi=self.webpackChunkwebsite_dosi||[]).push([[179],{8201:function(e,t,n){"use strict";n.d(t,{O:function(){return i}});var i=function(){function e(){this.hoverCursor=""
\ No newline at end of file
```

but in fzf-lua there are two problems:

## The coloring is gone

<img src="https://user-images.githubusercontent.com/24765272/164622944-b8dc3f11-e774-4201-adb9-e0ecd5096234.png" width="600">

## Command doesn't work inside fzf-lua

```zsh
git diff --color --no-index /dev/null -- docs/index.html | cut -c -220
```

this will print on the terminal, there is no output in fzf-lua;

<img src="https://user-images.githubusercontent.com/24765272/164627577-c00b12ec-ac8f-4a6a-9ea0-082a76d86c44.png" width="600">

**Comment by nyngwang** [comment]
@ibhagwan: I think I need your help implementing this. It's too hard for me. My target is to not create additional file(s) to achieve this. I have tried many methods but none of them works.

1. I want to keep the color output of git.
2. I want to either truncate files with column number > 200. (So this drastically decrease the size of the frontend "minified files"), or, simply disable the previewing of such files(since they're not meant to be read by human.)

**Comment by ibhagwan** [comment]
Update plugin to https://github.com/ibhagwan/fzf-lua/commit/5722fd62fd737392eae2c3aa1fb103629d7bd564 and set:

```lua
      cmd_modified    = "git diff --color HEAD %s | cut -c -200",
      -- or (both should work)
      cmd_modified    = "git diff --color HEAD %s | less -SEX",
```

**Comment by nyngwang** [comment]
@ibhagwan: Does this also work with `cmd_untracked`?

**Comment by ibhagwan** [comment]
> @ibhagwan: Does this also work with `cmd_untracked`?

All `git_diff` commands, untracked and deleted as well, the `%s` in the middle of the command is the lua format placeholder for the filename so you can play with it any way you wish, for untracked use:
```lua
  cmd_untracked   = "git diff --color --no-index /dev/null %s | cut -c -200"
```

**Comment by nyngwang** [comment]
@ibhagwan: Fzf-lua the best plugin! Now it's so smooth when doing selection! Thank you!

**Comment by nyngwang** [comment]
How to do the same for `files`, `buffers`, and `live_grep_glob`?

**Comment by ibhagwan** [comment]
> How to do the same for `files`, `buffers`, and `live_grep_glob`?

The builtin previewer is a different story since it’s a neovim buffer, there are no options to control line width but you can play with syntax / size limit under  `previewers.builtin`:

```lua
builtin = {
      syntax          = true,         -- preview syntax highlight?
      syntax_limit_l  = 0,            -- syntax limit (lines), 0=nolimit
      syntax_limit_b  = 1024*1024,    -- syntax limit (bytes), 0=nolimit
      limit_b         = 1024*1024*10, -- preview limit (bytes), 0=nolimit
 }
```

If you switch to `bat` previewer you can use the `cut` command but I’m pretty sure it will have a bad effect on the code syntax highlighting.

**Comment by nyngwang** [comment]
@ibhagwan: the problem is that these files are not necessarily large in file size, but the codes of these files are compressed into "one line"(line width > 2000), which causes serious "frozen" on navigation.

**Comment by ibhagwan** [comment]
> @ibhagwan: the problem is that these files are not necessarily large in file size, but the codes of these files are compressed into "one line"(line width > 2000), which causes serious "frozen" on navigation.

There’s not much I can do about this here other than a custom async file reader to read files and cut their lines after certain length which is not something I intend to do.

You can try using `bat` previewer instead and if you’re still having issues you can add `| cut -…` to it’s arguments.
