### ISSUE TITLE
Error executing lua: /usr/local/share/nvim/runtime/lua/vim/uri.lua:105: URI must contain a scheme: .../About/index.module.css

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#393]
### Info

- Operating System: macOS 12.3.1
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`:

    ```
    NVIM v0.8.0-dev+33-g116a3f468
    Build type: Release
    LuaJIT 2.1.0-beta3
    ```

- `fzf --version`: `0.30.0 (brew)`

- [ ] The issue is reproducible with `minimal_init.lua`: I think this cannot be reproduced via minimal since it will need `tsserver`, `cssmodule_ls`, etc.

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

I have a shortcut to run `vim.lsp.buf.definition()`. Initially, it did work. But suddenly it didn't: (Sorry that I cannot have a full-screen video, this is a private project.)

To be more specific, it's this is a TypeScript project and the file I ran against is a `foo.module.css` file. The problem only happened in such files.(i.e. There is no problem running this shortcut against the `Page` in the DEMO) I have created a type definition file for it:

```ts
declare module '*.module.css'
declare module '*.module.scss'
```

https://user-images.githubusercontent.com/24765272/164749364-c87549a5-b872-4339-8617-b0fada11270d.mov

```
E5108: Error executing lua: /usr/local/share/nvim/runtime/lua/vim/uri.lua:105: URI must contain a scheme: /Users/ningwang/Unity/MyProj/src/App/About/index.module.css
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/nvim/runtime/lua/vim/uri.lua:105: in function 'uri_to_fname'
        /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1575: in function 'locations_to_items'
        .../pack/packer/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:38: in function 'handler'
        .../pack/packer/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:207: in function 'set_lsp_fzf_fn'
        .../pack/packer/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:300: in function 'v'
        .../pack/packer/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:835: in function 'lsp_definitions'
        [string "..."]: in function <[string "..."]:0>
Press ENTER or type command to continue
```

**Comment by ibhagwan** [comment]
The issue seems to come from neovim’s lsp source code,

```
/usr/local/share/nvim/runtime/lua/vim/uri.lua:105: in function 'uri_to_fname'
/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1575: in function 'locations_to_items'
```

Does this happen only for definitions or for references, symbols, etc?
Does this happen only for specific files or all files?

**Comment by nyngwang** [comment]
@ibhagwan: I just got a similar conclusion after some testing. The error only occurs If I have `cssmodules_ls` installed. I'm pretty sure it's the culprit because I remove all LSP clients when testing.

> Does this happen only for definitions or for references, symbols, etc?

There is no problem with `lsp_references`. It occurs on:

1. `lsp_definitions`
2. `lsp_implementations`

**Comment by ibhagwan** [comment]
>I just got a similar conclusion after some testing. The error only occurs If I have cssmodules_ls installed. I'm pretty sure it's the culprit because I removed all LSP clients and add them back one by one when testing. So it's good news that this is not related to neovim,tsserver, etc, which I think is harder to fix.

Good find, closing.

If this becomes relvant again you can reopen.

**Comment by nyngwang** [comment]
So I should ask the maintainer of `cssmodules_ls` for help?

**Comment by ibhagwan** [comment]
> So I should ask the maintainer of `cssmodules_ls` for help?

That would probably be the best guess though if it were me, and since this is lua code, I'd first try to get more details what causes this issue by placing some `print` statemets around the runtime's `/usr/local/share/nvim/runtime/lua/vim/uri.lua:105` to understand what is exaclty causing this failure.

**Comment by nyngwang** [comment]
`local URI_SCHEME_PATTERN = '^([a-zA-Z]+[a-zA-Z0-9.+-]*):.*'`

I know very little about regex. So it seems that `foo.module.css` will break this scheme?
