### ISSUE TITLE
Equivalent of `vim.g.fzf_layout = { down = "40%" }`

### ISSUE THREAD

**Issue by WhyNotHugo** [ibhagwan/fzf-lua#395]
Hi! I'm currently using the `junegunn/fzf` plugin, but a lot of the VimL<>Lua interop is a pain, so I'm trying to switch to this plugin.

Is it possible to achieve a layout similar to using `vim.g.fzf_layout = { down = "40%" }`?

I basically want a regular split with the fzf prompt, and not a floating panel... Any chance this could be supported?

### Info

- Operating System: ArchLinux
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: v0.7.0
- `fzf --version`: 0.30.0 (2093667)

**Comment by ibhagwan** [comment]
Yes, this is supported, lookat the `winopts.split` setting, for a down split set it to `belowright new`: 

```lua
require'fzf-lua'.setup {
  winopts = {
    split         = "belowright new",   -- "belowright new"  : split below
                                        -- "aboveleft new"   : split above
                                        -- "belowright vnew" : split right
                                        -- "aboveleft vnew   : split left
  }
}
```

**Comment by WhyNotHugo** [comment]
I was too busy looking for `layout` options and through the code, and didn't think to look for `split`. :facepalm:

**Comment by WhyNotHugo** [comment]
Many thanks!

**Comment by ibhagwan** [comment]
>I was too busy looking for layout options and through the code, and didn't think to look for split. 🤦
> Many thanks!

No worries! don't hestiate to ask anything :-)
