### ISSUE TITLE
Ignore current file with `files()`

### ISSUE THREAD

**Issue by WhyNotHugo** [ibhagwan/fzf-lua#396]
I'd like to ignore the current file when using `require("fzf-lua").files()`. E.g.: If the current file is `init.lua`, then don't show that file in the fzf prompt.

Pretty much as described in https://github.com/junegunn/fzf.vim/issues/695.

The workarounds described there can be adapted too, but maybe it's possible to support this out-of-the-box?

**Comment by WhyNotHugo** [comment]
I tries this, but it still shows up:

```lua
  local cmd = ("fd --exclude %s"):format(vim.fn.shellescape(vim.fn.expand("%")))
  print(cmd)
  require("fzf-lua").files({ cmd })
```

However, checking the value with `:messages`, it would seem to be correct.

**Comment by WhyNotHugo** [comment]
Oh, correct syntax is:

```lua
  require("fzf-lua").files({ cmd = cmd })
```

Mixing up my languages here. Thanks!

**Comment by WhyNotHugo** [comment]
Oh, actually, that fails when the current buffer is an unsaved file. Correct version is:

```lua
  local current = vim.fn.shellescape(vim.fn.expand("%"))
  local cmd
  if current ~= "" then
    cmd = string.format("fd --exclude %s", current)
  else
    cmd = "fd"
  end
  require("fzf-lua").files({ cmd = cmd })
```

I think this would be nice to have in a flag in `fzf-lua`, something like:

```lua
require("fzf-lua").setup({
  files = {
    exclude_current = true
  }
})
```

Do you think that's reasonable? I can send a PR if so.

**Comment by ibhagwan** [comment]
Nice job @WhyNotHugo!

TBH, there are so many different customizations already hidden within PRS, also in order to add this I’d need to adjust it to all use cases whether it’s `rg`, `fd` or even `find` is used, don’t think it’s worth it, someone can always find the PR copy the code.

**Comment by WhyNotHugo** [comment]
I'll close this then; anyone needing guidance has the above example as a reference.

Thanks again for the help!

**Comment by ibhagwan** [comment]
@WhyNotHugo FYI, if you wanted to make the command a one liner (preferable as a mapping IMO) you could use this (also added `--type f` to exclude directories):
> The "complete" default `fd` options are `--color=never --type f --hidden --follow --exclude .git`
```lua
:lua require'fzf-lua'.files({ cmd = #vim.fn.expand('%')==0 and "fd --type f" or
  ('fd --type f --exclude %s'):format(vim.fn.shellescape(vim.fn.expand('%'))) })
```

**Comment by WhyNotHugo** [comment]
If I open a file `Cargo.toml`, the above solution will exclude anything matching the glob `Cargo.toml`, so files like `subproject/Cargo.toml` don't show up.

Note that if I open `subproject/Cargo.toml`, then `Cargo.toml` _does_ show up, because the flag in this case ends up being `--exclude subproject/Cargo.toml`.

I've read the man page for `fd` twice, and don't see any option that would help work around this. Any insight is welcome.

**Comment by ibhagwan** [comment]
> If I open a file `Cargo.toml`, the above solution will exclude anything matching the glob `Cargo.toml`, so files like `subproject/Cargo.toml` don't show up.
> 
> Note that if I open `subproject/Cargo.toml`, then `Cargo.toml` _does_ show up, because the flag in this case ends up being `--exclude subproject/Cargo.toml`.
> 
> I've read the man page for `fd` twice, and don't see any option that would help work around this. Any insight is welcome.

Maybe you can use `file_ignore_patterns` instead and use a lua string pattern (sort of a regex)?

**Comment by ibhagwan** [comment]
@WhyNotHugo, totally forgot about #884, you can run:
```lua
:FzfLua files ignore_current_file=true
```

**Comment by WhyNotHugo** [comment]
Thanks, @ibhagwan !
