### ISSUE TITLE
[Git] Wrong renaming indicator (the arrow sign)

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#398]
Forgive me for omitting the template because I think they're not related. It should be `App/index.css` renamed to `App/index.module.css`

![image](https://user-images.githubusercontent.com/24765272/165295352-da68084a-9361-4162-aae7-f760964e71dd.png)

**Comment by ibhagwan** [comment]
Can run `git short -s` in the command line? What does it show regarding this rename?

**Comment by nyngwang** [comment]
Oops, I have committed this onto my Repo. Let me try to reproduce it.

**Comment by nyngwang** [comment]
> All FzfLua does is parses the output, [...]

This is not a big deal actually, and from this, I think the result is probably "not as I'd think". I just thought that this plugin feature need to be perfect, because I like it, lol.

**Comment by ibhagwan** [comment]
> From this, I think the result is probably "not as I'd think". This is not a big deal actually, I just thought that this feature need to be perfect, because I like it, lol.

I usually prefer “perfect” too but in this case it would create an entire set of new issues of “what constitutes a rename” and also “how to stage/unstage” a rename, IMO not only it’s not worth it but I actually prefer the output to be **as close as possible to `git status`** because you never want to be “far from the source” and it makes you understand the underlying git better.

**Comment by nyngwang** [comment]
FYI, I cannot reproduce it as the following. So I just experienced a *strange* result from git itself:

<img src="https://user-images.githubusercontent.com/24765272/165304117-1a6bd2cf-99ba-4ed4-b7ed-a957d739593d.png" width="500">

**Comment by ibhagwan** [comment]
> FYI, I cannot reproduce it as the following. So I just experienced a strange result from git itself:

Most probably.

> I totally agree with this! I think we can safely close this now! I totally agree with this! I think we can safely close this now!

Closing.
