### ISSUE TITLE
Some LSP functionalities are not behaving correctly

### ISSUE THREAD

**Issue by arsham** [ibhagwan/fzf-lua#399]
### Info

- Operating System: `Arch Linux`
- Shell: `zsh`
- Terminal: `kitty`
- `nvim --version`: `v0.8.0-dev+77-g9a1920e223`
- `fzf --version`: `0.30 (devel)`

### Description 
With `fzflua = require("fzf-lua")`:

`fzflua.lsp_workspace_symbols()`: always shows empty results.
`fzflua.lsp_incoming_calls()`: always shows one item, which is the definition of the symbol.
`fzflua.lsp_typedefs()`: prints the following error: 
```
[Fzf-lua] Error executing 'textDocument/typeDefinition': RPC[Error] code_name = unknown, code = 0, message = "start pos is not valid"
```
`fzflua.lsp_outgoing_calls()`: is not implemented, but it would be great if you could implement this feature.

I have run these on a go project. Calling the `vim.lsp.buf.*` functions work normally.

Thank you!

**Comment by ibhagwan** [comment]
Couple of questions:

- Did this work for you properly in the past (i.e. `lsp_workspace_symbols`) with a neovim version that isn't `0.8` nightly?
- What type of language server are you using and what version? (I would assume `gopls`?)

**Comment by arsham** [comment]
Good question.
* I'm not sure. I've recently started using fzf-lua. However, they work by calling the LSP functions directly. For example `:lua vim.lsp.buf.workspace_symbol()` fills up the qflist. I've checked all other functions and they work as expected.
* `gopls` `v0.8.3`.

**Comment by ibhagwan** [comment]
>`:lua vim.lsp.buf.workspace_symbol()`

`gopls` doesn't seem to support an empty `workspace/symbol`  query, try `:FzfLua lsp_live_workspace_symbols` instead (works similarly to `live_grep` where each keystrokes generates a new query)?

> `[Fzf-lua] Error executing 'textDocument/typeDefinition': RPC[Error] code_name = unknown, code = 0, message = "start pos is not valid"`

This seems accurate, I just tried `:lua vim.lsp.buf.type_definition()` and I get the same error from neovim: `gopls: 0: start pos is not valid`

**Comment by arsham** [comment]
> `gopls` doesn't seem to support an empty `workspace/symbol` query, try `:FzfLua lsp_live_workspace_symbols` instead (works similarly to `live_grep` where each keystrokes generates a new query)?
> 

That is correct. I am thinking of using the live version in my library. I would recommend documenting this behaviour.

> This seems accurate, I just tried `:lua vim.lsp.buf.type_definition()` and I get the same error from neovim: `gopls: 0: start pos is not valid`
>

You are right. Please accept my apologies, I didn't pay enough attention to this one. Do you reckon it is a (Neovim's) `LSP` problem or the `gopls`'s?

**Comment by ibhagwan** [comment]
>You are right. Please accept my apologies, I didn't pay enough attention to this one. Do you reckon it is a (Neovim's) LSP problem or the gopls's?

Unsure TBH.

>`fzflua.lsp_incoming_calls()`: always shows one item, which is the definition of the symbol.
>`fzflua.lsp_outgoing_calls()`

That's due to the way it was implemented in #387, turns out you first need to call `textDocument/prepareCallHierarchy`, select an item (if more than one result) and then send the selected item as context for `callHierarchy/incomingCalls` (or `callHierarchy/outgoingCalls`), look at the code for `vim.lsp.buf.incoming_calls()` within `$VIMRUNTIME/lua/vim/buf.lua`

Bottom line: this needs an implementation adjustment which I'm working on.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/52dedd28d8ca325cb3e4cf65ef52915b5be238eb - try it out `lsp_incoming_calls` and `lsp_outgoing_calls`.

**Comment by arsham** [comment]
They work perfectly. Many thanks!

**Comment by ibhagwan** [comment]
> They work perfectly. Many thanks!

Ty! Testing your PR #401 will update soon, saved me some time I had it in my TODO list :-)

**Comment by arsham** [comment]
Happy to help.
