### ISSUE TITLE
nvim crashes when icons are enabled but not installed

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#4]
I was just playing around when noticed that fzf-lua kills my nvim on many providers. After bit of debugging I realised it's happening then `file_icons` is set to `true` but no icons are installed. Probably some guard somewhere is needed.

**Comment by ibhagwan** [comment]
Good catch! I thought I had this solved in the code by using `pcall`:

`file_icons          = true and pcall(require, "nvim-web-devicons"),`

Regardless it should never crash even with it being forced to `true`, I’ll do some more testing and keep you posted,

**Comment by ibhagwan** [comment]
Should be fixed now, default icon will be applied when `nvim-web-devicons` is not installed.
