### ISSUE TITLE
Change `resolved_capabilities` to `server_capabilities`

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#402]
With neovim v0.8, it appears that `resolved_capabilities` is deprecated: https://github.com/neovim/neovim/pull/17814

It appears to be only these two lines that are affected:

```
fzf-lua/lua/fzf-lua/providers/lsp.lua
432:code_action = client.resolved_capabilities.code_action
795:if client.resolved_capabilities[feature] then
```

**Comment by kdheepak** [comment]
I should have read the code instead of just `grep`ing. This is already fixed.

**Comment by ibhagwan** [comment]
Good timing :)

It was actually done today #401.

**Comment by kdheepak** [comment]
Should have realized you’d have already taken care of it :)

**Comment by ibhagwan** [comment]
> Should have realized you’d have already taken care of it :)

Actually it was @arsham :)
