### ISSUE TITLE
hide file path in buffers

### ISSUE THREAD

**Issue by ayushnix** [ibhagwan/fzf-lua#404]
### Info

- Operating System: Arch Linux
- Shell: dash (sh)
- Terminal: foot
- `nvim --version`: v0.7.0
- `fzf --version`: 0.30.0

<details>
<summary>fzf-lua configuration</summary>

```lua
local ok, fzf = pcall(require, 'fzf-lua')
if not ok then
  vim.notify('unable to find fzf-lua')
  return
end

if vim.fn.executable('fzf') ~= 1 then
  vim.notify('fzf is not installed')
  return
end

fzf.setup {
  winopts = {
    preview = {
      default = 'cat',
      -- hidden = 'hidden',
      winopts = {
        number = false,
        cursorline = false,
      },
    },
  },
  fzf_opts = {
    ['--prompt'] = '∑ ',
    ['--margin'] = '3%,1%',
    ['--pointer'] = '► ',
    ['--info'] = 'hidden',
    ['--layout'] = 'default',
  },
  previewers = {
    cat = {
      cmd = 'busybox cat',
      args = '-n',
    },
    bat = {
      args = '',
    },
  },
  files = {
    prompt = 'f: ',
    git_icons = false,
    file_icons = false,
    color_icons = false,
    fd_opts = "-c never -t f -H -E '.cache/' -E '.git/'",
  },
  buffers = {
    prompt = 'b: ',
    file_icons = false,
    color_icons = false,
    fzf_opts = {
      ['--delimiter'] = '/',
      ['--with-nth'] = '-1',
    },
  },
  lsp = {
    -- make lsp requests synchronous so they work with null-ls
    async_or_timeout = 3000,
  },
}

fzf.all_files = function()
  fzf.files {
    prompt = 'f: ',
    git_icons = false,
    file_icons = false,
    color_icons = false,
    cmd = "fd . ~/ /data -c never -t f -H -E '.cache/' -E '.git/'",
  }
end
```
</details>

### Description 

I'm trying to hide the complete file path and just show the file name when using `buffers`. I tried using `-d '/'` and `--with-nth='-1'` with fzf on the CLI and it works as expected but not when using fzf-lua. I get an error saying `attempt to index a nil value`. Not sure what changes I made but earlier I was able to access the `buffers` screen but the entire file path and the name were hidden.

**Comment by ibhagwan** [comment]
Not sure why this didn't work for you, both commands below generate the same `fzf` command line args:
```lua
:lua require'fzf-lua'.buffers({ fzf_args = '--delimiter=/ --with-nth=-1' })
:lua require'fzf-lua'.buffers({ fzf_opts = { ["--delimiter"] = "/", ["--with-nth"] = "-1" }})
```
Results in:
![image](https://user-images.githubusercontent.com/59988195/166155724-8ba77467-488a-4c12-acbd-a99be4e3c568.png)

**Comment by ayushnix** [comment]
I'm using

```
    fzf_opts = {
      ['--delimiter'] = '/',
      ['--with-nth'] = '-1',
    },
```

right now and I've updated fzf-lua to 033ffc9 and I'm still getting these errors

```
E5108: Error executing lua ...ack/packer/opt/fzf-lua/lua/fzf-lua/providers/buffers.lua:197: ...te/pack/packer/opt/fzf-lua/lua/fzf-lua/previewer/fzf.lua:53: attempt to index a nil value
stack traceback:
        [builtin#36]: at 0x7fe59d913ef0
        ...ack/packer/opt/fzf-lua/lua/fzf-lua/providers/buffers.lua:197: in function <...ack/packer/opt/fzf-lua/lua/fzf-lua/providers/buffers.lua:164>
        ...re/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/cmd.lua:79: in function 'run_command'
        ...re/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/cmd.lua:100: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

**Comment by ibhagwan** [comment]
Oh I see what’s happening, the previewer is failing for some reason, can you try with hidden previewer and then tell me what file/buffer name causes this?

Are you using `bat` previewer?

TBH, I don’t even like this solution as it doesn’t work well with icons or files that don’t contain `/` (directly under cwd).

How about I add a `filename_only` option to buffers/tabs?

**Comment by ayushnix** [comment]
> can you try with hidden previewer and then tell me what file/buffer name causes this?

If I uncomment `hidden` and use this,

```
fzf.setup {
  winopts = {
    preview = {
      default = 'cat',
      hidden = 'hidden',
      winopts = {
...
...
```

I still get the same error, irrespective of the buffer I'm on.

> Are you using bat previewer?

No, `busybox cat`.

> How about I add a filename_only option to buffers/tabs?

Yup, that sounds much better than fzf hacks.

**Comment by arsham** [comment]
@ibhagwan I'm thinking maybe you could add the `filename` like so:
(ignore the spaces around `\t`, left them just to be clear)
```
[buf_num] \t state \t icon \t path:line \t filename:line
```
Now, by default you can use:
```
[--with-nth"] = "1..4",
```
If someone wants only the `filename`:
```
[--with-nth"] = "1..3,4",
```

**Comment by ayushnix** [comment]
Thanks @ibhagwan!

**Comment by ibhagwan** [comment]
@ayushnix, https://github.com/ibhagwan/fzf-lua/commit/a0ac8021deccf09c87ed5e74ba2f2cce9637ccf7:

> works with either `bat` or the builtin previewer
```lua
:FzfLua buffers filename_only=true
-- or
:lua require'fzf-lua'.buffers({ filename_only = true })
```

The above commit also fixes the bug you encountered in case one day someone decides to use the fzf `--delimiter` hacks with fzf native previewers.

@arsham, Viable solution perhaps but seems to a bit cumbersome for something that can easily be solved with a couple lines of lua code :-)

If another request comes up where it's the better solution I'll reconsider.

**Comment by ibhagwan** [comment]
> Thanks @ibhagwan!

Ahead of my explanatory comment, you're welcome! :-)
