### ISSUE TITLE
ask for help - solution for long paths in results list

### ISSUE THREAD

**Issue by zhengpd** [ibhagwan/fzf-lua#408]
Hi, anyone know how to shorten the displayed paths in results window? like screenshot below:

![20220506_220350_cleanshot](https://user-images.githubusercontent.com/13469685/167149125-6e476307-5c57-4443-aa8e-0068bd57515e.jpg)

I'm searching tags from ruby gems. The long paths cause the matching texts hidden in results.

I tried searching the issues but didn't find a solution. Appreciate any help.

**Comment by ibhagwan** [comment]
ATM, there is no path shortening option, you can make the path somewhat shorter by supplying `cwd` which will shorten the path by making it relative but that isn’t relative in your case because the Ruby gem paths are under your home directory.

What you can do is run `tags({ fzf_args = '--keep-right' })` which will make sure the right part of the line is visible.

https://www.mankier.com/1/fzf#--keep-right

**Comment by zhengpd** [comment]
@ibhagwan Thank you for the help. I didn't know the `--keep-right` option before. It's what I expected. Now I'm using the fzf_opts:

```lua
  fzf_opts = {
    ['--keep-right'] = ''
  },
```

**Comment by ibhagwan** [comment]
I wanted to give an option for path shortening, never looked deeply into it because it requires transforming back from the shortened path to full path for actions (otherwise I have to keep all entries in memory which isn’t feasible).

I’ll look into it when I have more time.

**Comment by ibhagwan** [comment]
FYI, https://github.com/ibhagwan/fzf-lua/commit/b614a9d315512ec4ce9c1df41474e5ab8e12f7df - all file-based providers (files, grep, tags, lsp, etc) now support the `path_shorten` option, you can supply either `true` or a number that defines how many characters to use in each path part.

>`:FzfLua lsp_workspace_symbols path_shorten=1`
![image](https://user-images.githubusercontent.com/59988195/167231120-b56a3bdc-a693-41a6-8d99-a3cf7b57d253.png)

>`:FzfLua lsp_workspace_symbols path_shorten=2`
![image](https://user-images.githubusercontent.com/59988195/167231131-3cbccd22-7388-483d-ad62-a889afaf54bb.png)
