### ISSUE TITLE
Errors on any command "Invalid Border style 'rounded'"

### ISSUE THREAD

**Issue by aprowe** [ibhagwan/fzf-lua#41]
Hi, upon any command,  I get 
```
floating_window.lua:23: invalid border style "rounded"
```
Using nvim 0.5.0
Hopefully I can get this to work!

**Comment by ibhagwan** [comment]
`rounded` is the default parameter sent to the popup window, I’m not sure why this isn’t accepted by your neovim version:

Lets try two things, first try to specify the border chars directly by running this on startup:

```lua
require'fzf-lua'.setup {
  winopts = {
    -- split         = "new",           -- open in a split instead?
    win_height       = 0.85,            -- window height
    win_width        = 0.80,            -- window width
    win_row          = 0.30,            -- window row position (0=top, 1=bottom)
    win_col          = 0.50,            -- window col position (0=left, 1=right)
    -- win_border    = false,           -- window border? or borderchars?
    win_border       = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
    window_on_create = function()         -- nvim window options override
      vim.cmd("set winhl=Normal:Normal")  -- popup bg match normal windows
    end,
  }
}
```

If this doesn’t work I suspect it’s something with your neovim version, can you try with the [official 0.5 appimage](https://github.com/neovim/neovim/releases/download/stable/nvim.appimage)?

**Comment by aprowe** [comment]
Ah, that fixed it. Thanks. 
This is what I had: 
```
NVIM v0.5.0-dev
LuaJIT 2.0.4
```
Compared to 
```
NVIM v0.5.0
LuaJIT 2.1.0-beta3
```
So maybe the LuaJIT version matttered, or 0.5.0-dev was much different than 0.5.0. Can't remember where it came from, maybe was a nightly

**Comment by ibhagwan** [comment]
I still wonder what it wouldn't accept a documented parameter.

Ty for the update!
