### ISSUE TITLE
Add git stash

### ISSUE THREAD

**Issue by Shatur** [ibhagwan/fzf-lua#410]
In Telescope we have [git_stash](https://github.com/nvim-telescope/telescope.nvim#git-pickers) command to look for available stashes. It would be nice to have something like this here too.

**Comment by Shatur** [comment]
Thank you!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/23034bb022b28fb26e07532ad99ecdd6681095f6 - added a new command `git_stash`.

Default commands:
`<CR>` - `git stash apply` (requires confirmation with `y`)
`<C-x>` - drop a stash

> Multi-select is disabled since dropping multiple stashes messes up the numbering of stashes (due to `pop`) and therefore can cause unintended consequences, same goes for applying multiple patches.

![image](https://user-images.githubusercontent.com/59988195/168182346-9f0c1d3f-3f2a-4282-907e-c71018b4f110.png)

**Comment by Shatur** [comment]
>  <C-x> - drop a stash

Maybe we could have a shortcut for `pop`?

**Comment by ibhagwan** [comment]
> > - drop a stash
> 
> Maybe we could have a shortcut for `pop`?

Added a new action `git_stash_pop`, defaults stay the same, you can either define a new keybind or change the default action (to `pop` instead of `apply`):

```lua
require'fzf-lua'.setup{
  git = {
    stash = {
      actions = {
        ["default"] = require'fzf-lua'.actions.git_stash_pop,
      },
    },
  }
}
```

**Comment by Shatur** [comment]
Thanks!
