### ISSUE TITLE
Sort files in files provider

### ISSUE THREAD

**Issue by Shatur** [ibhagwan/fzf-lua#411]
The issue is just a question. With default settings files in `files` picker sorted in unexpected way:

![изображение](https://user-images.githubusercontent.com/22453358/168182553-bb8e4ba6-861e-4fce-9439-b7c29dfb980f.png)

Is it possible to achieve behavior like this:

![изображение](https://user-images.githubusercontent.com/22453358/168182611-1a24076f-14b8-4664-860e-7ff54a2ad233.png)

(I just opened `sk` from terminal without any arguments)

**Comment by ibhagwan** [comment]
Do you have `fd` or `rg` installed or both?

I suspect you don't have `fd` intstalled (no problem at all) in which case the command will default to `rg --color=never --files --hidden --follow -g '!.git'`, which doesn't specify any sorting, due to `rg` being multi-threaded it can sometimes show subfolder results first, from `man rg`:
```man
       --sort SORTBY
           This flag enables sorting of results in ascending order. The
           possible values for this flag are:

               none      (Default) Do not sort results. Fastest. Can be multi-threaded.
               path      Sort by file path. Always single-threaded.
               modified  Sort by the last modified time on a file. Always single-threaded.
               accessed  Sort by the last accessed time on a file. Always single-threaded.
               created   Sort by the creation time on a file. Always single-threaded.
```

Adding a sort to the command should solve your issue:
```lua
:lua require'fzf-lua'.files({ cmd = "rg --sort=path --color=never --files --hidden --follow -g '!.git'" })
```

> You can also set the above permanently during `setup` by modifying `files.rg_opts` (see the README)

**Comment by Shatur** [comment]
It works, but only with `fzf`. If `fzf_bin = 'sk'` - this settings doesn't have any effect. Is this expected?

**Comment by Shatur** [comment]
Is it possible to just use `sk` / `fzf` to search for files? They produce the expected results.

**Comment by ibhagwan** [comment]
>It works, but only with fzf. If fzf_bin = 'sk' - this settings doesn't have any effect. Is this expected?

`fzf_bin` shouldn't have any effect on list population, the list is populated in the order the shell command ouputs the lines.

> Is it possible to just use `sk` / `fzf` to search for files? They produce the expected results.

That is essentially what happens, the difference is the command used to populate `fzf|sk`, you're still running a command in the shell only that it's determined `$FZF_DEFAULT_COMMAND`.

Few quesions:
- Can you post the output from your shell of `echo $FZF_DEFAULT_COMMAND`?
- Do you have `fd` installed (if so, we can try with `fd`)
- Can you try with `:FzfLua files multiprocess=false`?
- Can you run `:FzfLua files debug=true`? this will output the shell comman to `:messages`:
  + Paste the command here so I can inspect it
  + Run the `nvim --headless ... ` command in the shell and see if the output is sorted properly?

**Comment by ibhagwan** [comment]
My bad, I just re-read your quesion and realized your it was about something totally different :-)

This is controlled by `fzf|sk` tiebreak algorithm:

>`man fzf`:
```man
       --tiebreak=CRI[,..]
              Comma-separated list of sort criteria to apply when the scores
              are tied.

              length  Prefers line with shorter length
              begin   Prefers line with matched substring closer to the
              beginning
              end     Prefers line with matched substring closer to the end
              index   Prefers line that appeared earlier in the input stream

              - Each criterion should appear only once in the list
              - index is only allowed at the end of the list
              - index is implicitly appended to the list when not specified
              - Default is length (or equivalently length,index)
              - If end is found in the list, fzf will scan each line backwards
```

>`man sk`:
```man
       --tiebreak=CRI[,..]
              Comma-separated list of sort criteria to apply when the scores
              are tied.

              score   Score of the fuzzy match algorithm
              index   Prefers line that appeared earlier in the input stream
              begin   Prefers line with matched substring closer to the
              beginning
              end     Prefers line with matched substring closer to the end

              - Each criterion could be negated, e.g. (-index)
              - Each criterion should appear only once in the list
```

I'm not sure what youre default `tiebreak` options for `sk` is but this should do the trick:

```lua
:lua require'fzf-lua'.files({ fzf_cli = "--tiebreak=begin" })
```
If you wish to set this as default for all providers add this to your global `fzf_opts`:
```lua
require'fzf-lua'.setup {
  fzf_opts = {
    ['--tiebreak'] = 'begin',
  },
}
```

**Comment by Shatur** [comment]
> Can you post the output from your shell of echo $FZF_DEFAULT_COMMAND?

Empty.

> Do you have fd installed (if so, we can try with fd)

Yes, I have. How can I try it?

> Can you try with :FzfLua files multiprocess=false?

The same issue.

> Can you run :FzfLua files debug=true? this will output the shell comman to :messages: 

```
|| 'nvim' -n --headless --clean --cmd 'lua loadfile([[/home/gena/.config/nvim/pack/plugins/start/fzf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[fd --color=never --type f --hidden --follow --exclude .git]],git_icons=true,file_icons=true,color_icons=true},[[_G._devicons_path='\''/home/gena/.config/nvim/pack/plugins/start/nvim-web-devicons/lua/nvim-web-devicons.lua'\''; _G._fzf_lua_server='\''/tmp/nvimmzN6g9/0'\''; return require("make_entry").file]],[[return require("make_entry").preprocess]])'
```

> :lua require'fzf-lua'.files({ fzf_cli = "--tiebreak=begin" })

No effect :(
This issue exists if I use `sk`.

Here is my configuration:

```lua
local fzf = require('fzf-lua')
fzf.setup({
  fzf_bin = 'sk', -- If I comment out this line, `rg_opts` works.
  files = {
    rg_opts = "--color=never --sort=path --files --hidden --follow -g '!.git'",
  },
})
```

**Comment by ibhagwan** [comment]
From what I can see you already have `fd` installed and `fzf-lua` is already using it (search inside the `nvim --headless` line), that means you don't really need `rg_opts` as `rg` isn't used for listing files (it is used for `grep` however).

>No effect :(
>This issue exists if I use `sk`

I just tested with `sk` and I also have the same issue regardless of what `tiebreak` I use, it seems to be a bug with `sk` when `file_icons` are enabled, it seems the glyphs are confusing the `sk` algorithm which doesn't happen with `fzf`.

You can try it out yourself with `require'fzf-lua'.files({file_icons=false})` (you'll get the same shell output you wanted).

You can open an issue [upstream](https://github.com/lotabout/skim/issues) but quite honestly the project seems dead, no issues are being fixed and there are barely any commits in the last 2 years, I ditched `sk` for exactly the same reasons.

**Comment by Shatur** [comment]
Thank you a lot!
Right, I don't need `rg_opts`. Also it works with `fzf` as I expect by default even with `fd` deleted.

> You can open an issue [upstream](https://github.com/lotabout/skim/issues) but quite honestly the project seems dead, no issues are being fixed and there are barely any commits in the last 2 years, I ditched sk for exactly the same reasons.

Sad to hear. Probably will switch to fzf then.

**Comment by ibhagwan** [comment]
Btw, when using `file_icons=false`, the command is piped directly to `fzf|sk`, if you wish to remove the `./` prefix from all entries (`fd` adds those) you can add `--strip-cwd-prefix` to your `fd_opts` (you can also do it in the shell via `$FZF_DEFAULT_COMMAND`):
```lua
require'fzf-lua'.setup({
  fzf_bin = 'sk',
  files = {
    fd_opts = "--color=never --type f --hidden --follow --exclude .git --strip-cwd-prefix",
  },
})
```

**Comment by Shatur** [comment]
I like file icons, better just stick with `fzf`, I don't have much preference :)

**Comment by Shatur** [comment]
I just assumed that `sk` could be a little faster.

**Comment by ibhagwan** [comment]
> I just assumed that `sk` could be a little faster.

Misconception:
https://github.com/lotabout/skim/issues/317

**Comment by Shatur** [comment]
Interesting, thanks for the info!
