### ISSUE TITLE
Unable to map ctrl+enter

### ISSUE THREAD

**Issue by Shatur** [ibhagwan/fzf-lua#412]
In FZF mapping `ctrl-m` works as <kbd>Ctrl</kbd> + <kbd>m</kbd> and as <kbd>Ctrl</kbd> + <kbd>Enter</kbd>. But with this plugin `ctrl-m` works only as <kbd>Ctrl</kbd> + <kbd>m</kbd>. Is it possible to map an action to <kbd>Ctrl</kbd> + <kbd>Enter</kbd>?

**Comment by nyngwang** [comment]
FYI: Ctrl+M is Enter in NeoVim.

**Comment by ibhagwan** [comment]
I haven’t tried mapping Ctrl+Enter, even though 0.7 provides distinction between `C-m` and `<CR>` I’m still not sure `<C-CR>` is a valid mapping. If you can make this mapping work inside neovim then you can make it work within FzfLua using the `on_create` callback.

**Comment by Shatur** [comment]
Oh, got it, thank you. I just assumed that I have to set it in `actions`.

**Comment by Shatur** [comment]
Sorry, my bad, I should have started with it. I trying like this:

```lua
fzf.setup({
  keymap = {
    builtin = {
      ['<C-CR>'] = 'default',
    },
  },
}
```

Is this wrong?

**Comment by ibhagwan** [comment]
> Is this wrong?

Honestly, I don’t know I never tried this mapping but this goes on to be mapped using `:tmap`, if you can figure out how to represent Ctrl-Enter in neovim as a mapping you can use the same one here, I’m pretty sure `<C-CR>` isn’t a valid mapping but I may be wrong.

**Comment by ibhagwan** [comment]
Also I’m not sure what you’re trying to do, there is no `default` mapping under `keymap.builtin` if you wanted to confirm selection that mapping would have to be part of the fzf mappings (and not a neovim mapping), fzf has different syntax for it’s mappings, you might be able to make it work by setting this under  `keymap.fzf` as `['ctrl-enter'] = 'accept'` (or maybe `confirm`? Check the Fzf man page).

**Comment by ibhagwan** [comment]
Read the “available keys” section in [fzf’s man page](https://www.mankier.com/1/fzf),  `alt-enter` is listed but it doesn’t look like `ctrl-enter` is a valid bind.

**Comment by Shatur** [comment]
Will use `on_create`.

**Comment by ibhagwan** [comment]
> Will use `on_create`.

If `<C-CR>` is a valid neovim mapping then using `on_create` to `tmap` it is the only way to make this work.

**Comment by nyngwang** [comment]
To @Shatur:

Could you elaborate more on how you map `<C-Enter>` in neovim? In my case, both Enter and Ctrl-Enter sends `
`(shown as `^M` in neovim).

**Comment by Shatur** [comment]
I use Neovim Qt
