### ISSUE TITLE
Add the ability to set style in fzf_colors

### ISSUE THREAD

**Issue by Shatur** [ibhagwan/fzf-lua#413]
FZF allows to set [styles in colors](https://github.com/junegunn/fzf/issues/1663). But `fzf_colors` doesn't allow to set them.
It would be nice to add additional boolen parameters for `bold` and `italic`.

**Comment by ibhagwan** [comment]
For backward compatibility nothing changes in current behavior, to add styling support use the 3rd+ slot in the color table, any argument in the 3rd slot onward will be relayed to the `--color` option as the `<color name>:<table argument>`.

For exmaple:
```lua
  fzf_colors = {
    ["hl"] = { "fg", "Comment", "underline:reverse:-1" },
  }
```

Will generate the following command line argument:
```sh
fzf ... --color=hl:<nvim_comment_fg_color>,hl:underline:reverse:1 ...
```
>To specify multiple raw styling arguments you can keep adding specifications past the 3rd slot.

The above results in the following highlight (underline+reverse color pallete):
![image](https://user-images.githubusercontent.com/59988195/168404361-45d24c3e-209d-4901-a9f9-5f9547ae2990.png)

**Comment by Shatur** [comment]
Thank you!
