### ISSUE TITLE
No such file or directory errors

### ISSUE THREAD

**Issue by Shatur** [ibhagwan/fzf-lua#414]
### Info

- Operating System: ArchLinux
- Shell: bash
- Terminal: Alacritty
- `nvim --version`: NVIM v0.7.0
- `fzf --version`: 0.30.0 (2093667)

### Description 

I see the following when some files unacessible:

![изображение](https://user-images.githubusercontent.com/22453358/168424238-809b4216-cfe0-43e9-8ef6-f9bcde9345a3.png)

To reproduce:

1. `git clone --recursive git@github.com:crow-translate/crow-translate.git`
2. `cd crow-translate`
3. `nvim`
4. `:Fzf files`

**Comment by ibhagwan** [comment]
This reminds me of #287: this happens due to error messages being redirected to `stderr`, it was solved by redirecting the errors to `stdout` instead, however, this behavior was only experienced on macs, Linux could handle lua’s `stderr` with no issue.

This can easily be solved applying the same solution as #287 but it’s not optimal, I’d rather have lua’s `io.stderr` behave properly, I’ll do some research on this.

In the meantime you can easily avoid that by redirecting the underlying command to `/dev/null`, if you’re using `fd` you can add `2 > /dev/null` to the end of your `fd_opts`.

**Comment by ibhagwan** [comment]
Would you be able to test branch `414`?

https://github.com/ibhagwan/fzf-lua/tree/414

> if you’re using packer you just need to add `branch = '414'` to the `use` function.

**Comment by Shatur** [comment]
Tried, the same result.
Above I provided steps to 100% reproduce the issue.

**Comment by ibhagwan** [comment]
It might be an `fzf` issue (althought I experience the same with `sk`), the errors are generated by trying to access invalid symbolic links which prints to `stderr`, the behavior in the shell is consistent with `fzf-lua`, try running the below in the terminal (within the `crow` project):

```sh
rg --files --hidden --follow | fzf
```

Resulting in:
![image](https://user-images.githubusercontent.com/59988195/168442782-bcca7173-03ce-432e-92d9-ac8b6ff067c3.png)

For now you can use 2 different workarounds:

(1) redirect `stderr` to `/dev/null`:
```lua
:lua require'fzf-lua'.files({cmd = "rg --files --hidden --follow 2>/dev/null"})
```

(2) disable `mutliprocess` (WARNING: will have performance impact on large projects):
```lua
:lua require'fzf-lua'.files({multiprocess=false})
```

Technically, the solution I used for #287 (blanket redirect of `stderr` into `stdout`) would work here too but before I make this change I'd like to understand what causes `fzf` to behave in this way as it should be able to handle the `stderr` stream. It's not really sound logic to eliminate the `stderr` stream.

**Comment by Shatur** [comment]
> (1) redirect stderr to /dev/null:

Yes, using this one, configured it globally.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d4ab66551bfa3f4207bca6b6ba4c7a60427fdde8 - this commit adds a few workarounds to control the behavior of the libuv wrapper within FzfLua, there are now a few different ways to solve your issue that don't require modification of any command.

(1) You can instruct FzfLua to discard the error stream altogether:
```lua
:lua require'fzf-lua'.files({stderr=false})
```

(2) You can redirect `stderr` to `stdout` (the default on MacOS) so you can still see if you have errors within the `fzf` output:
```lua
:lua require'fzf-lua'.files({stderr_to_stdout=true})
```

(3) Not sure why anyone would do this but it's also possible to redirect the error stream to a file:
```lua
:lua require'fzf-lua'.files({stderr='/home/user/<path to error file>'})
```

Note that difference between (1) and (2), discarding the error stream means you won't see errors at all and total number of results will be only the accessible files, in the case of your project that's `8376` files:

> `:lua require'fzf-lua'.files({cmd = "rg --files --hidden --follow -g '!.git'", stderr=false})`
![image](https://user-images.githubusercontent.com/59988195/168445592-1bdbf706-0da4-4666-a833-479147f3b76f.png)

While redirecting `stderr` to `stdout` adds the inaccessible files as error entries resulting in `20257` entries:
>`:lua require'fzf-lua'.files({cmd = "rg --files --hidden --follow -g '!.git'", stderr_to_stdout=true})`

![image](https://user-images.githubusercontent.com/59988195/168445620-b40c14f5-f700-409f-86a7-393c8c8643ad.png)

Many of which are the errors:
![image](https://user-images.githubusercontent.com/59988195/168445638-e09ffd5c-2d38-44cc-a4ed-235c71c2cae6.png)


I'm still unsure why `fzf|sk` can't handle `stderr` properly (as evident by running `rg --files --hidden --follow | fzf` in the shell) but this should conclude this issue, if I find any new info I'll update this thread.

**Comment by ibhagwan** [comment]
https://github.com/junegunn/fzf/issues/1901 - somewhat old issue but it seems that`rg` output to `stderr` is causing a graphic glitch (same one we experienced in this issue) and the `fzf` maintainer also recommended redirecting errors to `/dev/null` so I'm pretty sure there's nothing else to be done for this issue other than discard/redirect `stderr`.

**Comment by Shatur** [comment]
Thanks! But is it possible to set it globally?

**Comment by ibhagwan** [comment]
> Thanks! But is it possible to set it globally?

Not globally because you don't need it globally, this only affects providers which run in `multiprocess` (FzfLua's headless shell wrapper, used to enhance performance by running an external neovim process) which means only `files`, `grep` and `git` (which doesn't need this probably) will be affected by this setting.

You can set this semi-globally with:
```lua
require'fzf-lua'.setup {
  files = {
    stderr = false,  -- or `stderr_to_stdout = true` if you prefer
  },
  grep = {
    stderr = false,
  },
}
```

**Comment by Shatur** [comment]
Yes, this is exactly what I meant, thanks again!
