### ISSUE TITLE
Smart send to quickfix

### ISSUE THREAD

**Issue by Shatur** [ibhagwan/fzf-lua#416]
In Telescope we have `smart_send_to_qf` action. It works the same as the dumb one, but if there is no selection - it sends everything into quickfix.

fzf-lua currently send only the currently highlighted item if there is no selection. Maybe replace this behavior with the "smart"?

**Comment by ibhagwan** [comment]
Not really a fan of this idea, the logic doesn’t seem intuitive, if nothing is selected then why would anyone wish for it to go to quikfix? Plus, the way Fzf works is that `<CR>` treats the current cursor as selected item so I think  it will be hard to differentiate between a single selection or the default action.


However if this is your wish you can easily create a custom action handler and do whatever you wanted based on the number of items selected, make a local copy of the function below in your own config and then set the default action handler to your own function:
https://github.com/ibhagwan/fzf-lua/blob/d4ab66551bfa3f4207bca6b6ba4c7a60427fdde8/lua/fzf-lua/actions.lua#L289-L295

**Comment by Shatur** [comment]
> Not really a fan of this idea, the logic doesn’t seem intuitive, if nothing is selected then why would anyone wish for it to go to quikfix? 

But if you using `buf_sel_to_qf` when you don't have selection having a single item in quickfix isn't useful. If I want to just send all items to qf, selecting all items seems like an extra action that can be replaced with with useless single item in qf.
But thanks for the workaround, will use it :)

**Comment by Shatur** [comment]
How can I select all elements programmatically?

**Comment by ibhagwan** [comment]
> How can I select all elements programmatically?

Since the select all is controlled by fzf you need to use `feedkeys` to send your select all keybind to the terminal.

**Comment by ibhagwan** [comment]
> But if you using`buf_sel_to_qf` when you don't have selection having a single item in quickfix isn't useful. If I want to just send all items to qf, selecting all items seems like an extra action that can be replaced with with useless single item in qf.

I agree, that’s why the default action is `buf_edit_or_qf`, where a single item is an opened and multiple items are sent to qf.

**Comment by ibhagwan** [comment]
Btw, unless you’e doing this for buffers/blines/lines you need to use the `file_` variants, I.e. `file_edit_or_qf`.

**Comment by Shatur** [comment]
> I agree, that’s why the default action is buf_edit_or_qf, where a single item is an opened and multiple items are sent to qf.

Oh, sorry, I was confused with `file_sel_to_qf`. This action isn't useful and I trying to improve it.

I think I won't be able to use it inside my customized `buf_edit_or_qf`? Because `selected` is already populated.

**Comment by ibhagwan** [comment]
> I think I won't be able to use it inside my customized buf_edit_or_qf? Because selected is already populated.

You’re correct, when the action function is called fzf has already exited, to achieve what you want I think you need to define a special bind during `on_create` that will use `vim.fn.feedkeys` to send the bind sequence of `select-all+accept` (I.e. send `alt-a+enter`).

**Comment by Shatur** [comment]
Thank you!

**Comment by Shatur** [comment]
Is it possible to execute an action like `buf_edit_or_qf` in a mapping in `on_create`?

**Comment by ibhagwan** [comment]
> Is it possible to execute an action like `buf_edit_or_qf` in a mapping in `on_create`?

Only via `feedkeys`.

**Comment by Shatur** [comment]
Okay, thanks!

**Comment by Shatur** [comment]
But how can I detect the number of selected items in `on_create`?..

**Comment by ibhagwan** [comment]
> But how can I detect the number of selected items in `on_create`?..

There is no way.

**Comment by Shatur** [comment]
Got it, then it impossible to implement :(

**Comment by ibhagwan** [comment]
> Got it, then it's impossible to implement :(

Unfortunately the number of selected is held in the fzf process.

**Comment by ibhagwan** [comment]
I was able to do roughly what you're after with `files` customization, can probably be optimized and perhaps there is also a better solution than the hacky `vim.defer_fn` (to send `<CR>` after a short delay), but this key is using fzf's `execute-silent` action.

I also tried adding `--bind=ctrl-g:execute-silent:<...> --bind=ctrl-g:+accept`, it does perform both the `execute-silent` and the `accept` but it doesn't seem to take into account the `select-all` items, only the cursor item.

Play around with the below, I'm sure you'll get it to do what you want:
```lua
M.files = function(opts)
  opts = opts or {}
  local raw_act = fzf_lua.shell.raw_action(function(selected)
    if #selected == 1 then
      vim.api.nvim_feedkeys(
        vim.api.nvim_replace_termcodes("<M-a>",
          true, false, true), 'n', true)
      vim.defer_fn(function()
        vim.api.nvim_feedkeys(
          vim.api.nvim_replace_termcodes("<CR>",
            true, false, true), 'n', true)
      end, 100)
    end
  end, "{+}")
  opts.fzf_args = ('--bind=ctrl-g:execute-silent:%s'):
    format(vim.fn.shellescape(raw_act))
  return fzf_lua.files(opts)
end
```

**Comment by Shatur** [comment]
Thank again you a lot!
