### ISSUE TITLE
Code action handler does not properly combine actions from multiple sources

### ISSUE THREAD

**Issue by jose-elias-alvarez** [ibhagwan/fzf-lua#42]
Hello again! I've found an issue that occurs when calling `:FzfLua lsp_code_actions` when a buffer has multiple LSP clients that can provide code actions:

![Screen Shot 2021-08-13 at 3 18 29 PM](https://user-images.githubusercontent.com/54108223/129313671-b1987568-abd0-49d2-8e4f-2858707a7bc7.png)

The first 5 actions are provided by null-ls, and the bottom 4 are from lua-language-server. (It's rare to have multiple LSP clients that can provide code actions, but I think the issue isn't specific to null-ls and would happen with actual language servers).

The two issues are:

1. Indexes aren't incremented to account for multiple actions
2. Only the top set of code actions works. Selecting a lua-language-server action actually executes the top action with a matching index, meaning that selecting `1: Mark `ajskdlajdk` as defined global` executes `1: Preview hunk`.

I suspect the issue is that the handler is called once for each result, which means it's called twice for each language server. I was able to fix this specific issue with the following changes, but I'm not sure if it's robust enough to use as-is:

```diff
diff --git a/lua/fzf-lua/providers/lsp.lua b/lua/fzf-lua/providers/lsp.lua
index 91fc1f0..45818b3 100644
--- a/lua/fzf-lua/providers/lsp.lua
+++ b/lua/fzf-lua/providers/lsp.lua
@@ -156,12 +156,14 @@ local function set_lsp_fzf_fn(opts)
         opts.lsp_handler.method, err.message or "nil"))
     else
       local results = {}
+      local combined_results = {}
       local cb = function(text) table.insert(results, text) end
       for _, v in pairs(lsp_results) do
         if v.result then
-          opts.lsp_handler.handler(opts, cb, opts.lsp_handler.method, v.result)
+          vim.list_extend(combined_results, v.result)
         end
       end
+      opts.lsp_handler.handler(opts, cb, opts.lsp_handler.method, combined_results)
       if vim.tbl_isempty(results) then
         utils.info(string.format('No %s found', string.lower(opts.lsp_handler.label)))
       elseif not (opts.jump_to_single_result and #results == 1) then
```

**Comment by ibhagwan** [comment]
Your suspicion and analysis of what the issue here is spot on, I knew this was possible but I didn’t have any way to test multiple LSP clients so I had no idea what the result sets would look like and in what order they’ll be called.

At first glance your solution seems good but I think this also requires a fix in the async part of the function (the lines you changed are only executed when `async = false`) so it would probably be wiser to fix it inside `code_action_ handler`.

Will keep you posted tomorrow.

**Comment by ibhagwan** [comment]
Fixed (hopefully) inside `code_action_handler`, I have no way of testing this, let me know if that works for you?

**Comment by jose-elias-alvarez** [comment]
Yes! Both the indexes and selecting code actions works perfectly now. Thank you!
