### ISSUE TITLE
windows: pipe error

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#420]
default config, 
```
[Fzf-lua] fzf error 2: io.stdout:write error: Broken pipe
```

using fzf in wsl 2 on windows, this error even with default config. 
using `files` command here (with few basic rg options) with debug=true, command was: 

```
'nvim' -n --headless --clean --cmd 'lua loadfile([[/home/viraatc/.local/share/nvim/site/pack/packer/opt/fzf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[rg --files --hidden --follow --no-heading --smart-case --no-ignore -g "!{.DS_Store,.cache,venv,.git,.clangd,.ccls-cache,*.o,build,*.dSYM,tags}"]],git_icons=false,file_icons=true,color_icons=true},[[_G._devicons_path="/home/viraatc/.local/share/nvim/site/pack/packer/opt/nvim-web-devicons/lua/nvim-web-devicons.lua"; _G._fzf_lua_server="/tmp/nvim1jNHXA/1"; return require("make_entry").file]],[[return require("make_entry").preprocess]])'
```

which does execute in the wsl terminal properly, with icons and outputs popping up, but doesnt work inside neovim where i get a flicker and this error message (the broken pipe one). how do i investigate this?

**Comment by ibhagwan** [comment]
Are you using nightly or `0.7`? if you're using nightly I suspect this might have to do with the changes that also caused #409 (which I'm about to commit a fix soon, in it's final testing stage).

**Comment by ibhagwan** [comment]
Until we figure this out you can just use `multiprocess=false` it most likely will work.

**Comment by ViRu-ThE-ViRuS** [comment]
yup, my mistake. this was the fzf version issue. was using default ubuntu without knowning.

**Comment by ibhagwan** [comment]
> yup, my mistake. this was the fzf version issue. was using default ubuntu without knowning.

No worries, ty for letting me know!
