### ISSUE TITLE
Grep Speed Questions

### ISSUE THREAD

**Issue by mikesart** [ibhagwan/fzf-lua#422]
I'm using the latest (eb3d2d1).

I'm working on a very large codebase and do the following:

```
:FzfLua live_grep
ObjObjects -- *.cpp
```
It's taking about 1:20 minutes. Doing this at the root of the same codebase:
```
time rg -g "*.cpp"  ObjObjects
```
Takes less than 1.5 seconds.

Do you have any suggestions to figure out what's going on here? This is pretty unusable at the moment... Thanks!

**Comment by ibhagwan** [comment]
```sh
time rg -g "*.cpp"  ObjObjects
```

This is probably not the same command run by FzfLua, run `:FzfLua live_grep debug=true` and inspect the underlying command at the top and see how the `rg` flags differ, you are most likely running different flags like `--hidden` or `--follow` which would have different time than vanilla `rg`.

If you’re running the exact same command generated by FzfLua and still see difference in the timing disable `git_icons` and `file_icons` both can sometime add processing time, especially `git_icons` in huge project as it requires testing every match against the git status output.

If all else fails please post the wrapper command that appears in `:messages` when using `debug=true` and we’ll try to run it in the shell directly (with minor modifications) and understand what’s causing the issue.

**Comment by mikesart** [comment]
Well, it's fast today. Not sure what was going on yesterday but now I know what to do to debug it if it happens again.
Thanks ibhagwan.

**Comment by ibhagwan** [comment]
> Well, it's fast today. Not sure what was going on yesterday but now I know what to do to debug it if it happens again. Thanks ibhagwan.

Ty @mikesart, lmk if this happens again, I have "zero tolerance" policy for performance issues :-)

**Comment by nyngwang** [comment]
> [..] I have "zero tolerance" policy for performance issues :-)

Best nvim-plugin maintainer identified during first-half 2022.

**Comment by ibhagwan** [comment]
> > [..] I have "zero tolerance" policy for performance issues :-)
> 
> Best nvim-plugin maintainer identified during first-half 2022.

Ty @nyngwang for always being so supportive :)
