### ISSUE TITLE
Trying to convert cmd that I had in fzf.vim with proximity to lua

### ISSUE THREAD

**Issue by afewyards** [ibhagwan/fzf-lua#423]
```
function! s:list_cmd()
  let base = fnamemodify(expand('%'), ':h:.:S')
  return base == '.' ? $FZF_DEFAULT_COMMAND : printf($FZF_DEFAULT_COMMAND . ' | proximity-sort %s', expand('%'))
endfunction

command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'source': s:list_cmd(),'options': ['--prompt=> ','--tiebreak=index', '--info=inline', '--layout=reverse']}) , <bang>0)
```

I'm kind of stuck with this. Above is how I have it setup with vim.fzf and it works perfectly. I searches the project and then sorts the results based on the current directory with proximity-sort

could someone assist me in writing this to this plugin?

thanks

**Comment by ibhagwan** [comment]
How about this:

> the below can be easily mapped to a command, it doesn’t take into account your '.' dir test but I’m sure you can take it from here
```lua
:lua require'fzf-lua'files({ cmd = ('%s | proximity-sort %s'):format(vim.env.FZF_DEFAULT_COMMAND, vim.fn.expand('%')) })
```

**Comment by ibhagwan** [comment]
I wrote it for you, also improved the logic as it had some flaws and didn't really require `fnamemodify()`, put the below in your `init.vim` (or any other sourced `.vim` file):

> Note: I'm not sure how `proximity-sort` works so you might need to change `vim.fn.expand('%')` to full path when the search is outside of your `cwd` (i.e. using `vim.fn.expand('%:p')` or other `help filename-modifiers`).

```vim
lua << EOF
_G.files_proximity = function(opts)
  opts = opts or {}
  opts.cmd = vim.env.FZF_DEFAULT_COMMAND 
  if vim.fn.expand('%:p:h') ~= vim.loop.cwd() then
    opts.cmd = opts.cmd .. (" | proximity-sort %s"):format(vim.fn.expand('%'))
  end
  opts.prompt = "> "
  opts.fzf_opts = {
    ['--info']      = 'inline',
    ['--layout']    = 'reverse',
    ['--tiebreak']  = 'index',
  }
  require'fzf-lua'.files(opts)
end
EOF

command! -bang -nargs=? -complete=dir Files lua _G.files_proximity()
```

**Comment by afewyards** [comment]
@ibhagwan there is only one error, when it is in the project root. it wont search. it will just stay empty. after I've opened a file it works like a charm though. any thoughts?

**Comment by ibhagwan** [comment]
@afewyards add `opts.debug = true` somewhere in the function and it will add the underlying command as first result with the prefix `[DEBUG]`, my guess is that it’s adding the `proximity-sort` when it’s not needed.

Can you run `:lua print(vim.fn.expand('%:p:h'), vim.loop.cwd())` and paste the result here?

We probably have to make an exception for the project root, the output for the above will help me is find out what the condition we need to avoid is.

**Comment by afewyards** [comment]
this is from the debug when I trigger it ```'/snap/nvim/2181/usr/bin/nvim' -n --headless --clean --cmd 'lua loadfile([[/home/k/.local/share/nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[
rg --files --hidden --smart-case --glob "!.git/*"]],git_icons=true,file_icons=true,color_icons=true},[[_G._devicons_path='\''/home/k/.local/share/nvim/site/pack/packer/start/nvim-web-devico
ns/lua/nvim-web-devicons.lua'\''; _G._fzf_lua_server='\''/tmp/nvimS5piwC/1'\''; return require("make_entry").file]],[[return require("make_entry").preprocess]])'```

and this is from the output from that command, just my home dir ```/home/k/Sites/a-dam-nextjs /home/k/Sites/a-dam-nextjs```

**Comment by ibhagwan** [comment]
Hmm… strange, the command seems perfectly ok and the condition also worked and proximity wasn’t added, which is confirmed by the internal `cmd` argument:
```sh
rg --files --hidden --smart-case --glob "!.git/*"
```

Does the line above also match `[DEBUG]` the debug line within the fzf UI window?

If you can help me with the exact steps to reproduce this I can look into it, do I just open neovim inside a project without opening any buffer and run the command?

**Comment by afewyards** [comment]
Exactly I open the command up right after I opened vim up in a project lib.

**Comment by ibhagwan** [comment]
>Exactly I open the command up right after I opened vim up in a project lib.

I did try that before I posted it and it works well, I'm not sure why this happens as the command seems valid in what you posted, can you try changing the line:

```lua
opts.cmd = vim.env.FZF_DEFAULT_COMMAND
```
to:
```lua
opts.cmd = 'rg --files --hidden --smart-case'
```

And let's see if this works without the `--glob` flag? I have no idea why would that be the issue but it's worth a shot.

**Comment by ibhagwan** [comment]
I replciated your `$FZF_DEFAULT_COMMAND` and opened `files` with no buffer opened, my neovim wrapper command is identical to yours (using my paths) and I do get results at project root, very strange:
```sh
'nvim' -n --headless --clean --cmd 'lua loadfile([[/home/bhagwan/.local/share/nvim/site/pack/packer/opt/f
zf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[ rg --files --hidden --smart-case --glob
"!.git/*"]],git_icons=false,file_icons=true,color_icons=true},[[_G._devicons_path='\''/home/bhagwan/.loca
l/share/nvim/site/pack/packer/opt/nvim-web-devicons/lua/nvim-web-devicons.lua'\''; _G._devicons_setup='\'
'~/.config/nvim/lua/plugins/devicons.lua'\''; _G._fzf_lua_server='\''/tmp/nvimXJ9Alb/1'\''; return requir
e("make_entry").file]],[[return require("make_entry").preprocess]])'
```

Do you get results if you run `:FzfLua files` at the projec root? what does `FzfLua files debug=true` print?

**Comment by ibhagwan** [comment]
I’m thinking there is also a small chance `startify` or another `autocmd` changes your working directory until you open a buffer? It’s a small chance but it’s worth a try to pass `cwd` to FzfLua, can you add the below to the function?

```lua
  opts.cwd = vim.loop.cwd()
```

You can then view `cwd` as a header by either adding `opts.show_cwd_header = true` or by running:
```lua
:lua _G.files_proximity({ show_cwd_header = true })
```

You can also avoid modifying the function and run:
```lua
:lua _G.files_proximity({ cwd = vim.loop.cwd(), show_cwd_header = true })
```

**Comment by afewyards** [comment]
So it looks like the cwd is correctly set to the right directory and the `:FzfLua files` also does not output anything. On the other hand `:FzfLua git_files` does output files. which is not ideal as that prevents me from jumping to newly added files.

I'm a bit lost for words..

**Comment by afewyards** [comment]
even when I change the cmd to just 'rg --files' it outputs nothing. but if I open up my float term it just displays all my files from the directory. so it isn't the RG

**Comment by ibhagwan** [comment]
What’s even more confusing is that it works when adding the `proximity-sort`…

Let’s start eliminating things:
- Do you have `fd` installed by any chance so we can test it?
- What happens if you run `:lua require'fzf-lua'.files({ cmd 'find -L . -type f' })`?
- What happens if you run `:FzfLua files multiprocess=false`?
- What happens if you run `:FzfLua files git_icons=false file_icons=false`?
- What is the version of your `rg`, `fzf` and `neovim`?
- Does `:FzfLua grep` (or `live_grep`) work properly?

**Comment by ibhagwan** [comment]
Also can you run this in the shell inside different folders and see if you get any results (the result should be I list of files with icons)?

```sh

'/snap/nvim/2181/usr/bin/nvim' -n --headless --clean --cmd 'lua loadfile([[/home/k/.local/share/nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio({debug=true,cmd=[[ rg --files --hidden --smart-case --glob "!.git/*"]],git_icons=true,file_icons=true,color_icons=true},[[_G._devicons_path='\''/home/k/.local/share/nvim/site/pack/packer/start/nvim-web-devico ns/lua/nvim-web-devicons.lua'\''; return require("make_entry").file]],[[return require("make_entry").preprocess]])'
```

**Comment by afewyards** [comment]
> * Do you have `fd` installed by any chance so we can test it?
I do now
> * What happens if you run `:lua require'fzf-lua'.files({ cmd = 'find -L . -type f' })`?
This output the directory
> * What happens if you run `:FzfLua files multiprocess=false`?
Empty
> * What happens if you run `:FzfLua files git_icons=false file_icons=false`?
This outputs the directory
> * What is the version of your `rg`, `fzf` and `neovim`?
ripgrep v12.1
fzf 0.29
nvim 0.7
> * Does `:FzfLua grep` (or `live_grep`) work properly?
Both do not work
> * Can you try running it in a folder that isn’t a git repo (it could be `.gitignore`?)
No change
>* Also can you run this in the shell inside different folders and see if you get any results (the result should be I list of files with icons)?
This just outputs normally in different kind of folders

**Comment by ibhagwan** [comment]
Ok, I’m starting to lean into an issue displaying the git or file icons, can you try both files and grep separately with git/file icons set to false?
 
 Also, what happens if you pipe the nvim headless command into `| fzf  --ansi`

**Comment by afewyards** [comment]
Yeah both work if I disable icon sets. also it's A LOT faster then. 

Do not really know what command you are talking about when you say nvim headless command.

**Comment by ibhagwan** [comment]
> Yeah both work if I disable icon sets. also it's A LOT faster then.

It should be faster as it doesn’t require any processing, but still it shouldn’t be that much faster unless running `git status` is very costly on your repo.


The headless command is the one from this comment https://github.com/ibhagwan/fzf-lua/issues/423#issuecomment-1133386682

You mentioned it had proper output, did it also output icons? What happens if we pipe it into fzf (which is what fzf lua does).

What terminal/font are you using?

**Comment by afewyards** [comment]
>The headless command is the one from this comment https://github.com/ibhagwan/fzf-lua/issues/423#issuecomment-1133386682
>You mentioned it had proper output, did it also output icons? What happens if we pipe it into fzf (which is what fzf lua does).

This seems to work with file icons on the left side for the filenames

>What terminal/font are you using?

Running Kitty with Operator Mono

**Comment by ibhagwan** [comment]
Also which icon set is the problem? Git or files?

**Comment by afewyards** [comment]
Both. if I only disable one or the other it won't work

**Comment by afewyards** [comment]
BTW I'm happy the way it is now without the icons TBPH. But if you do want to get to the bottom of this I'm all yours.

**Comment by ibhagwan** [comment]
> BTW I'm happy the way it is now without the icons TBPH. But if you do want to get to the bottom of this I'm all yours.

Ty, I would like to understand why this happens, especially since this is the first time ever this comes up after so many uses installed this plugin.

The fact this works perfectly in the shell including icons confuses me, I’ll try to think what can cause this and maybe ask you to try some things.

> and also a very big thank you for assisting me in this matter!

My pleasure.

**Comment by ibhagwan** [comment]
@afewyards, unresolved vodoo issues like this one drives me crazy :-)

I've given it more thought and can't think of anything that would cause such strange behavior where everything works fine in the shell but not inside neovim, if you're ok with it I'd like to try a few different settings, can you try the below commands and confirm which one works and which one doesn't?

```lua
-- using `find`
-- with multiprocesss
:lua require'fzf-lua'.files({cmd="find -type f", multiprocess=true, git_icons=true, file_icons=true})
:lua require'fzf-lua'.files({cmd="find -type f", multiprocess=true, git_icons=false, file_icons=true})
:lua require'fzf-lua'.files({cmd="find -type f", multiprocess=true, git_icons=true, file_icons=false})
-- assuming this one should work since our "solution" was to disable the icon sets
:lua require'fzf-lua'.files({cmd="find -type f", multiprocess=true, git_icons=false, file_icons=false})
-- without multiprocess
:lua require'fzf-lua'.files({cmd="find -type f", multiprocess=false, git_icons=true, file_icons=true})
:lua require'fzf-lua'.files({cmd="find -type f", multiprocess=false, git_icons=false, file_icons=true})
:lua require'fzf-lua'.files({cmd="find -type f", multiprocess=false, git_icons=true, file_icons=false})
```

If you can repeat the above with `cmd = "rg --color=never --files --no-ignore"` and `cmd = "fd --color=never --type f --no-ignore"` would be great:

```lua
-- using `rg`
:lua require'fzf-lua'.files({cmd="rg --color=never --files --no-ignore", multiprocess=true, git_icons=true, file_icons=
true})
...
:lua require'fzf-lua'.files({cmd="rg --color=never --files --no-ignore", multiprocess=false, git_icons=true, file_icons=
true})
-- using `fd`
:lua require'fzf-lua'.files({cmd="fd --color=never --type f --no-ignore", multiprocess=true, git_icons=true, file_icons
=true})
...
:lua require'fzf-lua'.files({cmd="fd --color=never --type f --no-ignore", multiprocess=false, git_icons=true, file_icons
=true})
```

Anything else you can think of that can isolate our issue and understand what is the exact scenario where it fails or better yet help me reproduce the issue would be of great help.

**Comment by ibhagwan** [comment]
Another thing that might give us good info, since you mentioned that `_G.files_proximity()` doesn’t work at the root of the project but if a sub folder buffer is opened it does work (when `proximity-sort` is piped), is the same true for `files`? Does it also start working as soon as file in a sub folder is open?
