### ISSUE TITLE
Feature request/question: start with preview off, but allow toggling it to on?

### ISSUE THREAD

**Issue by fsouza** [ibhagwan/fzf-lua#424]
### Description 

Omitted the other parts of the template because this is more a feature request/question (I couldn't find how to do it, but maybe it's possible and I just missed it). I'm curious if it's possible to have preview enabled, but with the display "toggled off" by default? The idea is to open the fuzzy finder for files without preview, but allow me to toggle it `on` on demand. If I set the previewer to "off" I can't toggle it back on.

Thanks for this amazing project!

**Comment by ibhagwan** [comment]
Set `winopts.preview.hidden` to `hidden` (default is `nohidden`) and then use keybind (default: `F4`) to toggle it back on

**Comment by fsouza** [comment]
> Set `winopts.preview.hidden` to `hidden` (default is `nohidden`) and then use keybind (default: `F4`) to toggle it back on

oh god I can't read. Thank you for the quick response!
