### ISSUE TITLE
[Question] Can "commands" work similarly to "command_history" ?

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#425]
### Description 
Hey there. 

I'm starting to use "commands" similar to a command palette in `VSCode`. When you use "command_history" it allows you to hit \<CR\> to immediately issue the command or \<Ctrl-e\> to edit it. 

In the "commands" dialogue we don't get these options and hitting \<CR\> seemingly puts you into command edit mode. Is it possible to emulate the same options as "command_history" for the "commands" dialogue?

**Comment by ibhagwan** [comment]
Yes, just change the default action to match the one from `commands_history`.
```lua
require'fzf-lua'.setup {
  nvim = {
    commands = {
      actions = {    
        -- default is actions.ex_run
        ["default"] = require'fzf_lua'.actions.ex_run_cr,
      },
    },
  }
}
```

**Comment by ldelossa** [comment]
@ibhagwan I'm attempting to update my fzf config with the follwing:

```
  commands = {
    prompt              = 'Commands> ',
    actions = {
      ["default"]       = actions.ex_run_cr,
    },
  },
```

to achieve the same goals as above. If this correct? I can't seem to get the "<CR>" behavior happening on the commands fuzzy searching modal.

**Comment by ibhagwan** [comment]
> @ibhagwan I'm attempting to update my fzf config with the follwing:
> 
> ```
>   commands = {
>     prompt              = 'Commands> ',
>     actions = {
>       ["default"]       = actions.ex_run_cr,
>     },
>   },
> ```
> 
> to achieve the same goals as above. If this correct?

Not sure if I understand, does it not execute <CR> after the command with this action set up?

>  I can't seem to get the "" behavior happening on the commands fuzzy searching modal.

What do you mean by this?

**Comment by ldelossa** [comment]
With the above configuration, selecting a command from "commands" doesnt execute <cr>. Instead it leaves it in the status bar and i need to hit "<cr>" again.

**Comment by ibhagwan** [comment]
I just tried running this directly and it works, does this work for you?
```lua
:lua require'fzf-lua'.commands({actions={["default"] = require'fzf-lua'.actions.ex_run_cr}})
```

BTW, I edited your comment, without encapsulating `<CR>` in backquotes it shows up as `""`.

**Comment by ldelossa** [comment]
hmm, it does work if I type it directly. I changed my keybinding to this:

`remap('n', '<C-c>', '<cmd>lua require("fzf-lua").commands({actions={["default"] = require("fzf-lua").actions.ex_run_cr}})<CR>', opts)`

And it works fine, but it  didn't seem to like when I had it in the fzf config supplied to setup function.

**Comment by ibhagwan** [comment]
>  it didn't seem to like when I had it in the fzf config supplied to setup function.

Did you make sure it’s under the `nvim` section? I may have made this part confusing, it made sense at the time to put the neovim providers under a different section :)

```lua
require'fzf-lua'.setup {
  nvim = {
    commands = {
      actions = { ["default"] = require'fzf_lua'.actions.ex_run_cr },
    },
  }
}
```

**Comment by ldelossa** [comment]
yup! that did it. I had it in the highest level block :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/c90a88b354ae12736760f623000d91b438b04234

FYI @ldelossa, due to the above not really making much sense anymore I unpacked all the nvim options under globals, so you don't need to use the `nvim` section anymore:
```lua
require'fzf-lua'.setup {
  commands = {
    actions = { ["default"] = require'fzf_lua'.actions.ex_run_cr },
  },
}
```

**Comment by ldelossa** [comment]
Awesome, this makes way more sense to my brain
