### ISSUE TITLE
Ability to call a neovim command after using fzf-lua

### ISSUE THREAD

**Issue by AndOrangutan** [ibhagwan/fzf-lua#426]
I was wondering if there was any good way to call a command after I am done using fzf-lua and have chosen a result.

My goal is to have my dashboard have a button that will use fzf-lua to pick and `index.md` file from one of my notebooks, then run some commands (specifically `:ZkCd` a command that changes into the selected notebook's directory). Here is the line that I currently have written up:
```lua
dashboard.button( "n", "   > Notebooks", [[:lua require("fzf-lua").files({ cwd = "~/Dropbox/Notebooks", cmd = "fd -e md -g 'index.md'"})<cr>]]),
```
While I can just concatenate other commands on with pipes, they all get called when the button is pressed. Is there any sort of way I can detect once fzf-lua has closed, or maybe just call the commands afterwards? 

Thank you in advance.

**Comment by ibhagwan** [comment]
Why don’t you add a global action handler and then map it as the `default` action?

```lua
_G.my_open = function(selected)
  vim.cmd('ZkCd ' .. selected[1])
end

require'fzf-lua'.files({ cwd = "~/Dropbox/Notebooks",
  cmd = "fd -e md -g 'index.md'", actions = { ['default'] = G.my_open }})
```

**Comment by AndOrangutan** [comment]
I tried looking through the documentation, but couldn't really figure out what `actions` does. Does it change the default action of the picker?

 I still want it to maintain the original functionality of the `.files` picker, where it opens the selected file, I just then want the ability to run the `ZkCd` command. The snippet you provided seems to just run the `ZkCd` command.

**Comment by ibhagwan** [comment]
Actions is a map of functions that process your selection based on the keybind you pressed with `default` being what’s called when you press `Enter`.

This should do what you want:
```lua
_G.my_open = function(selected, opts)
  require'fzf-lua'.actions.file_edit(selected, opts)
  vim.cmd('ZkCd')
end
```

**Comment by AndOrangutan** [comment]
That works beautifully, thank you so much :D
Love your work, really liking fzf-lua since changing from Telescope.

**Comment by ibhagwan** [comment]
> That works beautifully, thank you so much :D
> Love your work, really liking fzf-lua since changing from Telescope.

Ty @AndOrangutan
