### ISSUE TITLE
Q: Is it possible to jump to the first modified line tracked by Git?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#427]
As title. When I selected the item from the floating window of `git_status`, I will be happy to see that the cursor moves to the first modified line (modified/deleted/added).

**Comment by ibhagwan** [comment]
> As title. When I selected the item from the floating window of `git_status`, I will be happy to see that the cursor moves to the first modified line (modified/deleted/added).

If you have a gitgutter-like plugin (I.e. `gitsigns` or `vgit`) you can create a custom action that calls `file_edit` and calls `require'gitsigns'.next_hunk()` right after (in the case of `gitsigns`, read `vgit` docs to find the equivalent, I think the function is `hunk_down`).

**Comment by nyngwang** [comment]
> [..] (in the case of gitsigns, read vgit docs to find the equivalent, I think the function is hunk_down)

Sorry for my late reply. It turns out that vgit.nvim needs some time to do initialization (the signs will show up after some delay), so the call won't take effect on the first try. The following calls after initialization all work well. This is not related to fzf-lua so can be safely closed.
