### ISSUE TITLE
Which event to use if I want to `startinsert` when a terminal buffer is selected via `FzfLua buffers`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#428]
As title. I have tried these two but they didn't work:

```lua
vim.cmd('autocmd BufEnter,BufWinEnter,TermOpen term://* startinsert')
```

with these in config:

```lua
actions = {
  files = { default = actions.file_edit },
  buffers = { default = actions.buf_switch_or_edit },
},
```

**Comment by ibhagwan** [comment]
Why is `buffers` not opening in insert mode to begin with?

If you’re calling buffers from another fzf-lua window you need to call `actions.ensure_insert_mode()`, that’s what’s called after opening any interface from `:FzfLua builtin`.

**Comment by nyngwang** [comment]
I just extended the `buffers = { default = actions.buf_switch_or_edit },` to include `actions.ensure_insert_mode()`, but got the same result. This is resulting config:

```lua
buffers = { default = function (...)
  actions.buf_switch_or_edit(...)
  actions.ensure_insert_mode(...)
end },
```

**Comment by ibhagwan** [comment]
This action should be called after calling `:FzfLua buffers`, this does nothing in the way you used it above.

You still didn’t answer why is it not opening in insert mode to begin with? How are you calling it?

**Comment by nyngwang** [comment]
After some trying I got this from `:message`:

```
[Fzf-lua] ':b 9' failed: Vim(normal):Can't re-enter normal mode from terminal mode
```

> You still didn’t answer why is it not opening in insert mode to begin with? How are you calling it?

I'm trying terminal buffers today, and now I want to use the following shortcut that I have been using for months:

```lua
  vim.keymap.set('n', '<C-B>', function () require('fzf-lua').buffers() end, NOREF_NOERR_TRUNC)
```

But it used to open all selected buffer(s) in normal mode, and this is correct and expected. Now things are different since I'm too lazy to press `i` myself to be able to type something into the terminal buffer.

Maybe this would help:

https://user-images.githubusercontent.com/24765272/171233870-b24fab63-2278-4483-899d-d0a67fe95b6c.mov

When the background became black, it means that it had entered the insert mode of the terminal buffer.

**Comment by ibhagwan** [comment]
Try this:

```lua
vim.keymap.set('n', '<C-B>', function () require('fzf-lua').buffers(); require('fzf-lua.actions').ensure_insert_mode() end, NOREF_NOERR_TRUNC)

```

**Comment by nyngwang** [comment]
wokennnnnnnnnnnn up and found it workkkkkkkkkkkkkkk! LOVE you!

**Comment by ibhagwan** [comment]
I was gonna suggest to try different modes other than `n` from `:help feedkeys` but seems like you solved it already :)

Closing this issue then.

**Comment by ibhagwan** [comment]
Forgot to mention you probably want to do this only for terminals:

```lua
buffers = { default = function (...)
  actions.buf_switch_or_edit(...)
  if vim.bo.buftype == 'terminal' then
    vim.api.nvim_feedkeys('i', 'n', true)
  end
end },
```
