### ISSUE TITLE
Using fzf-lua as vim.ui.select behaves unexpectedly in insert mode

### ISSUE THREAD

**Issue by oncomouse** [ibhagwan/fzf-lua#429]
I've been using fzf-lua as my `vim.ui.select` function to choose digraphs (code is [here](https://github.com/oncomouse/dotfiles/blob/master/conf/vim/lua/select-digraphs/init.lua) and [here](https://github.com/oncomouse/dotfiles/blob/master/conf/vim/plugin/select-digraphs.lua)). Everything works great except for one thing: one of the calls to `vim.ui.select` is triggered by a map for insert mode. When I trigger it, fzf-lua pops up as expected, but Neovim is in normal mode instead of terminal mode, so I have to press `i` and then everything works as normal from there.

This isn't a big deal, but I don't have to do this on any other fzf-lua maps I'm using (and it also works as expected in the visual and normal mode bindings when I'm working with digraphs, so I'm pretty sure it's because the call is made from insert mode). Is it possible to start fzf-lua in terminal mode when it's being used as `vim.ui.select` and triggered from an insert-mode mapping?

**Comment by ibhagwan** [comment]
Ty for this report @oncomouse, this can happen under some circumstances (for example when opening an fzf-lua window from another) for which I added the `ensure_insert_mode` code in actions.lua.

I’ll add the call to `ensure_insert_mode` after the opening of `vim.ui.select`, I’ll do some testing and update this thread.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/fe3e1082c1dcfe401b87178b812c200a221fa8da - should fix it.

Ignore my previous comment as a better and more generic solution was applied and calling `actions.ensure_insert_mode` is no longer required (will now print a deprecated warning instead).
