### ISSUE TITLE
Integrate with trouble.nvim

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#431]
Hi, I would like to ask if we can open quickfix when select multiple items with trouble.nvim instead of the default one?

**Comment by ibhagwan** [comment]
You can create a custom handler and then use the `trouble.nvim` API/command when multiple items are selected, something like this:

```lua
_G.my_action = function(selected, opts)
  if #selected>1 then
    -- code from `actions.file_sel_to_qf`
    local qf_list = {}
    for i = 1, #selected do
      local file = require'fzf-lua'.path.entry_to_file(selected[i])
      local text = selected[i]:match(":%d+:%d?%d?%d?%d?:?(.*)$")
      table.insert(qf_list, {
        filename = file.path,
        lnum = file.line,
        col = file.col,
        text = text,
      })
    end
    -- this sets the quickfix list, you may or may not need it for 'trouble.nvim'
    vim.fn.setqflist(qf_list)
    -- call the command to open the 'trouble.nvim' interface
    vim.cmd("<trouble nvim command>")
  else
    require'fzf-lua'.actions.file_edit(selected, opts)
  end
end

-- set as the default action for LSP (or whichever provider you want
require'fzf-lua'.setup {
  lsp = {
    actions = { ['default'] = _G.my_action }
  }
}

-- you can also set it directly in the calling arguments
require'fzf-lua'.lsp_references({ actions = { ['default'] = _G.my_action } })
```

**Comment by sandangel** [comment]
thanks a lot. I will give it a try.

**Comment by ibhagwan** [comment]
If you don’t need to modify the quickfix contents you can use this shortened version instead:

```lua
_G.my_action = function(selected, opts)
  if #selected>1 then
    -- build the quickfix list from the selected items
   require'fzf-lua'.actions.file_sel_to_qf(selected, opts)
    -- call the command to open the 'trouble.nvim' interface
    vim.cmd("<trouble nvim command>")
  else
    require'fzf-lua'.actions.file_edit(selected, opts)
  end
end
```

**Comment by sandangel** [comment]
> 

This version will open both the default quickfix and `trouble`

**Comment by ibhagwan** [comment]
> > If you don’t need to modify the quickfix contents you can use this shortened version instead:
> 
> This version will open both the default quickfix and `trouble.nvim` The first version will only open `trouble.nvim`
> 
> that is because of this line: https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/actions.lua#L170

That’s correct.

**Comment by BilderLoong** [comment]
For anyone who later finds this issue. Trouble.nvim has builtin-action for fzf-lua: https://github.com/folke/trouble.nvim?tab=readme-ov-file#fzf-lua
