### ISSUE TITLE
[Feature Request] Disabling All Previewers

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#433]
### Info

- Operating System: arch linux
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.7.0
- `fzf --version`: 0.30.0 (2093667)

- [ x] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
This is a purely cosmetic request. 
I don't like previewers and I will never use them. My configuration becomes polluted with 
```lua
<picker> = { previewer = false }
```
for every single picker.
I would like to simply be able to pass `previewer = false` as a global option when I setup fzf-lua instead of redefining the option for each picker.

Similarly is true of the "prompt" option, in which I need to redefine the prompt to the same value for each picker, although I am less bothered by this.

**Comment by ibhagwan** [comment]
Why don’t you use `winopts.preview.hidden` instead?

If set this `hidden` all previewers are essentially turned off.

**Comment by barrett-ruth** [comment]
Ah, I did not see it was indented under `winopts` in the documentation. My mistake.

**Comment by ibhagwan** [comment]
> Ah, I did not see it was indented under `winopts` in the documentation. My mistake.

It’s probably not very clear, the options grew with the project which first supported only fzf shell previews (I.e `bat`), after a while refactoring the options is something I try to avoid in order not to break anyone’s config.

**Comment by nyngwang** [comment]
> [..] avoid in order not to break anyone’s config.

Best nvim plugin maintainer 2022.

**Comment by kshenoy** [comment]
> Why don’t you use winopts.preview.hidden instead?

Hi, I'm just switching from vim to neovim and I'm not very familiar with the lua syntax. Could you please share how to do that? Also, lets say I want to disable it just for a single command eg. `FzfLua buffers`, how do I do that?

**Comment by ibhagwan** [comment]
If you wanna do it for a single command use:
```lua
:lua require'fzf-lua'.buffers({ winopts = { preview = { hidden = 'hidden' }}})
```
If you wish to have it configured for all providers in your `init.vim`:
```lua
lua << EOF
require('fzf-lua').setup({
  winopts = { preview = { hidden = 'hidden' }}}
})
EOF
```

**Comment by ibhagwan** [comment]
Doesn’t look like you’re missing anything, perhaps it’s not getting called? You can try adding `print` statements to the config function.

If the below works and setup doesn’t it’s most likely an issue with your config:
```lua
:lua require'fzf-lua'.buffers({ winopts = { preview = { hidden = 'hidden' }}})
```

**Comment by kshenoy** [comment]
Sigh, it's the config. I should've checked that first. Thanks for your help!
