### ISSUE TITLE
[Feature Request] Cleaner buffer names in `buffers`

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#436]
I need to familiarize myself with pull requests -- sorry I didn't do one here.
`:FzfLua buffers` completely expands the home directory when listing out buffer paths.

Adding the below code to line 121 of `lua/fzf-lua/providers/buffers.lua` turns all instances of $HOME into the shorter '~' character while still retaining functionality:
```lua
  bufname = bufname:gsub(os.getenv 'HOME', '~', 1)
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7817c4205ea8e0039d098ee59877f22f6a18a8f8

No worries, I added it with a slight improvemnts:
- Make sure the path starts with $HOME (instead of `gsub(..., 1)`)
- Use `vim.env.HOME` instead of a call to `os.getenv`

```lua
  bufname = bufname:gsub("^"..vim.env.HOME, "~")
```

**Comment by ibhagwan** [comment]
Btw, this is how you send a PR:

- While logged in to GitHub, navigate to this repository's URL
- Scroll to the top and press the fork icon, that should create a fork under your own GitHub user
- Clone your fork locally: `git clone git@github.com:barret-ruth/fzf-lua.git`
- Make your changes, commit and push (this pushes the commits to your fork)
- Navigate to your fork's PR page `https://github.com/barret-ruth/fzf-lua/pulls`
- Click "New pull request" (top right) and follow the prompts
- Congratulations on your first PR :-)

It's worth noting, you can then keep adding commits or rebase/force push, etc, the PR will contain all commits from your branch so for example if you rebase/squash and force push the PR will be updated with your latest changes.

**Comment by barrett-ruth** [comment]
By the way, what are your thoughts on doing this for `FzfLua quickfix` (and location lists)? Seems like it is a copy-paste fix.

**Comment by ibhagwan** [comment]
Not exactly copy-paste as this also required minor adjustment in the builtin previewer but here you go:

https://github.com/ibhagwan/fzf-lua/commit/62f67b61949141bd633eca50297fd10884c248a6
