### ISSUE TITLE
[Question] How to configure git_bcommits to use delta (like git_status)

### ISSUE THREAD

**Issue by idevat** [ibhagwan/fzf-lua#440]
For `git_status` it is possible to configure to use `delta` - something like this:
```
previewers = {
  git_diff = {
    pager = "delta --width $FZF_PREVIEW_COLUMNS",
  }
}
```
Is it possible to configure `delta` also for `git_bcommits`?

**Comment by ibhagwan** [comment]
Absolutely, take a look at the README's `preview` argument for `commits|bcommits`, that's the command fzf will run to display the commit preivew, all you need to do pipe it into `delta`:

```lua
require'fzf-lua'.setup {
  git = {
    commits = {
      preview = "git show --pretty='%Cred%H%n%Cblue%an%n%Cgreen%s' --color {1} | delta --width $FZF_PREVIEW_COLUMNS",
    },
    bcommits = {
      preview = "git show --pretty='%Cred%H%n%Cblue%an%n%Cgreen%s' --color {1} | delta --width $FZF_PREVIEW_COLUMNS",
    },
}
```

**Comment by idevat** [comment]
I tried it and got:
```
error: Found argument '--rotate-to' which wasn't expected, or isn't valid in this context

USAGE:
  delta --width <width>
```
It looks like `--rotate-to` is added to the preview command: 
https://github.com/ibhagwan/fzf-lua/blob/bf3a4e12fbc64a039a07c53ca54c210afb5376af/lua/fzf-lua/providers/git.lua#L112-L114

**Comment by ibhagwan** [comment]
>It looks like `--rotate-to` is added to the preview command

You're correct, my bad I only tested it with `commits`, with `bcommits` fzf-lua attempts to display the relevant part of the commit using the `--rotate-to` flag.

https://github.com/ibhagwan/fzf-lua/commit/e42a757faf3c2307f95037a57916415005321862 - this should solve it.

**Comment by idevat** [comment]
Great! Now it works perfectly. Thanks!

**Comment by ibhagwan** [comment]
FYI, it’s now possible to configure pager in n easier way (I.e. you don’t need to duplicate the preview command or use `previewers.git_diff.pager`), all you need to do is define `preview_pager = 'delta -w $FZF_PREVIEW_COLUMS'` and place it under `git.status`, `git.commits` or `git.bcommits`.
