### ISSUE TITLE
Cycle through search results when reaching the bottom

### ISSUE THREAD

**Issue by yujinyuz** [ibhagwan/fzf-lua#442]
### Info

- Operating System:
- Shell:
- Terminal:
- `nvim --version`:
- `fzf --version`:

- [ ] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

Is there an option or something to cycle through search results similar to telescope?

Here's a video where I just keep on pressing `<C-j>` and it goes back to the top of the list

https://user-images.githubusercontent.com/10972027/173167870-73d623b3-42e7-472f-b263-05bf1d49b0eb.mp4

**Comment by ibhagwan** [comment]
This behavior is controlled by the fzf binary, this should do what you want:
```lua
-- can also be added to 'setup' for convenience
require'fzf-lua'.files({ fzf_opts = { ['--cycle' = '' } })
```

**Comment by yujinyuz** [comment]
Thanks for the fast response!
