### ISSUE TITLE
[Question] LSP symbol_fmt 

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#443]
### Info

- Operating System: arch
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.7
- `fzf --version`: 0.30

- [x] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
    lsp = {
        symbol_fmt = function(s)
            return 'a' .. s
        end
    }
})
```
</details>

### Description 
I may be misunderstanding what `symbol_fmt` does (I read through everything on the README and source), but it seems like it modifies whatever symbols shown in an LSP picker. To be clear, by symbol I mean Function, Variable, Property, etc. surrounded by brackets. However, defining my own `symbol_fmt` or `symbol_style` seems to not change how the LSP symbols are displayed (like above); they are always surrounded in brackets.

**Comment by ibhagwan** [comment]
You understood perfectly, I'm confused why this would happen, just tried minimal setup with your `symbol_fmt` which resulted in the below:
```lua
fzf_lua.setup {
  lsp ={
    symbol_fmt = function(s)
      return 'a ' .. s
    end
  },
}
```
![image](https://user-images.githubusercontent.com/59988195/173171623-70a80aa3-baa7-41e6-af17-512dbd38a0ca.png)


Is it possible your setup isn't being called properly? what happens if you add the argument directly to the call?

```lua
:lua require'fzf-lua'.lsp_document_symbols({ symbol_fmt = function(s) return 'a '..s end })
```

**Comment by barrett-ruth** [comment]
Actually I didn't. From your screenshot is seems like the *icon* is being modified (perhaps `icon_format` would've been a more appropriate name) not the *symbol* (which I believe to be the actual text "Variable" or "Function").

**Comment by ibhagwan** [comment]
> Actually I didn't. From your screenshot is seems like the _icon_ is being modified (perhaps `icon_format` would've been a more appropriate name) not the _symbol_ (which I believe to be the actual text "Variable" or "Function").

That's true, the issue is LSP options are a bit of a mess due to having all LSP providers bunched into one table and I wanted a name that would make it clear only the symbol are affected by this option, perhaps `symbol_kind_` prefix would've been better, this is a relatively new option (last week) so there's still time to modify it's name.

Before we agree on a more approperiate name I'd like to first figure out why it's not working for you.

**Comment by ibhagwan** [comment]
On second thought I'm not sure if we're on the same page, the `symbol_fmt` takes care of **both the symbol kind icon and the symbol kind text**, controlling what's "inside the brackets" is done with `symbol_style`:

```lua
lua require'fzf-lua'.lsp_document_symbols({ symbol_fmt = function(s) return '('..s..')' end, symbol_styl
e=1 }
```
![image](https://user-images.githubusercontent.com/59988195/173172360-d519fabd-9542-4d9c-82ec-e550960dd408.png)



```lua
lua require'fzf-lua'.lsp_document_symbols({ symbol_fmt = function(s) return '('..s..')' end, symbol_styl
e=2 })
```
![image](https://user-images.githubusercontent.com/59988195/173172353-aa0c3e7a-81ef-4143-8c99-bfc6ebd1d56b.png)

```lua
lua require'fzf-lua'.lsp_document_symbols({ symbol_fmt = function(s) return '('..s..')' end, symbol_styl
e=3 })
```
![image](https://user-images.githubusercontent.com/59988195/173172369-e17540bb-cbed-47a4-91f7-ae128b5b4201.png)

**Comment by barrett-ruth** [comment]
Ok, one last clarification -- exactly what string does `symbol_fmt` modify?

Is the string it receives of form "\<icon\> \<lspkind\>" or solely "\<icon\>"?

If it is the latter, then the behavior on my machine is expected, as ...

you just updated your response with `symbol_style.` There we go!

**Comment by ibhagwan** [comment]
> Ok, one last clarification -- exactly what string does `symbol_fmt` modify?
> Is the string it receives of form "<icon> <lspkind>" or solely "<icon>"?
> If it is the latter, then the behavior on my machine is expected, as ...
> you just updated your response with `symbol_style.` There we go!

As you probably figured from my latest comment `symbol_fmt` modifies the either `icon`, `icon kind` or `kind` depending on your `symbol_style` setting.

**Comment by barrett-ruth** [comment]
Well... now I can modify an item kind. However, due to the fact that icons or colored, is there a sane way to go about modifying the kinds?

One Function symbol looks like this, for example:
^[[38;2;169;182;101mFunction^[[0m

**Comment by ibhagwan** [comment]
> Well... now I can modify an item kind. However, due to the fact that icons are colored, is there a sane way to go about modifying the kinds?
> 
> One Function symbol looks like this, for example: ^[[38;2;169;182;101mFunction^[[0m

You can disable the coloring by setting `symbol_hl_prefix = false` and then color manually in your format function.

A note regarding how highlights work: the default value is `symbol_hl_prefix = 'CmpItemKind'` which means that symbol kinds inherit highlights from `nvim-cmp` (which most neovim oriented colorschemes set) so for example `Property` will be highlighted with the `CmpItemKindProperty` group.

If you wish to change that, just use any prefix you want, for example `symbol_hl_prefix = 'MyPrefix'` and then use `:highlight! link MyPrefixProperty TSProperty` to link it to any highlight you want.

**Comment by ibhagwan** [comment]
@barrett-ruth FYI, `symbols` has its own category in the options under `lsp.symbols`, it maintains backward compat so you won’t be affected but the correct place of the `symbol_` customizations is now under `lsp.symbols`.

Diagnostics was also moved out to its own category (outside `lsp`), as `vim.diagnostic` doesn’t require an LSP client since `vim.diagnostic` was introduced.

**Comment by barrett-ruth** [comment]
Nice, that works well.

As a small nitpick, I think the signs for the diagnostics should attempted to be grabbed from the sign group "DiagnosticSign<Severity>" (along with their highlight as well). A lot of plugins randomly choose their own signs and they end up using symbols that aren't contained within my font. Let me know what you think.

**Comment by ibhagwan** [comment]
> As a small nitpick, I think the signs for the diagnostics should attempted to be grabbed from the sign group "DiagnosticSign" (along with their highlight as well). A lot of plugins randomly choose their own signs and they end up using symbols that aren't contained within my font. Let me know what you think.

That's a great improvement actually, I would say we can also use the highlights `DiagnosticSignError`, etc, will keep you posted.

**Comment by barrett-ruth** [comment]
I would like to do a PR for this. For now I just need to know:

Should I use the current values you've defined as fallbacks if a diagnostic sign/highlight isn't defined? Or just outright replace everything?

**Comment by ibhagwan** [comment]
@barrett-ruth, try out the latest commit, contains both the new highlight groups and the diagnostic sign (and highlight) integration with neovim's `DiagnosticSignXXX`, overrides can be customized uneder `diagnostic.signs`.

New highlight explanation can be found under [`README.md#Customizing-Highlights](https://github.com/ibhagwan/fzf-lua#customizing-highlights=).
