### ISSUE TITLE
[Feature Request] LSP Document Symbol line/col info

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#444]
Sorry for the continuous onslaught of issues.

So, when looking at general LSP info via `lua vim.lsp.buf. <method>()` nvim sends the results to a quickfix list with file, line and col info. Mostly this is useless but occassionally things are redefined in a file and the line number helps me know what I'm clicking on - right now it's just a blind guess. Furthermore, `lsp_live_workspace_symbols` and of course `vim.lsp.buf.document_symbol` support this.

Is there a way to add this to `lsp_document_symbols` or should I be using another tool for the job?

**Comment by ibhagwan** [comment]
I'm not sure I understand what you mean, both documents and workspace symbols behave identically, both can have entries sent to the quickfix list by selecting multiple entries and pressing `<CR>` or `<A-q>` (unless you changed the default actions).

The only difference is that `lsp_document_symbols` hides the filename by default as it's not releant since all symbols are from the current buffer, if you wish to see the filename you can change it by overridng the `--with-nth` option (default = `2..`) but that should have no effect on the "send to quickfix" functionality, it's purely cosmetic:

```lua
:lua require'fzf-lua'.lsp_document_symbols({ fzf_opts = { ['--with-nth']=false } })
```

**Comment by ibhagwan** [comment]
Is it possible you used the `path_shorten` option? I just discovered a bug where the option would be ignored when using the send to quickfix action resulting in shortened paths in the quickfix list.

https://github.com/ibhagwan/fzf-lua/commit/1a1d794f48b169ef87a72d6125d493ce484ae520 - this commit takes care of it.

**Comment by barrett-ruth** [comment]
To your first response, that's exactly what I meant - I wanted to just show lines and columns without the buffername. `--with-nth` and `--delimiter` solved that perfectly. Glad you caught the other bug in the meantime.

**Comment by ibhagwan** [comment]
> To your first response, that's exactly what I meant - I wanted to just show lines and columns without the buffername. `--with-nth` and `--delimiter` solved that perfectly. Glad you caught the other bug in the meantime.

FYI, this issue might also affect your code in #435, if one day you decide to use `path_shorten` (makes a lot of sense in `lsp_workspace_symbols` due to long library paths out of cwd) be sure to change this line:
```lua
local file = require'fzf-lua'.path.entry_to_file(selected[i])
```
to:
>By supplyng `entry_to_file` with `opts` we're letting the function know that
> `path_shorten` was used so it knows to expand the file glob properly
```lua
local file = require'fzf-lua'.path.entry_to_file(selected[i], opts)
```

**Comment by nyngwang** [comment]
@ibhagwan Sorry for my commenting old issue here. But it seems that I'm setting the `path_shorten` wrong?

<img src="https://user-images.githubusercontent.com/24765272/191167762-9195fcbb-2b31-46be-8c87-a8679abfcbc0.png" width="600>

**Comment by ibhagwan** [comment]
> @ibhagwan Sorry for my commenting old issue here. But it seems that I'm setting the `path_shorten` wrongly? The paths seems not shorten when calling `FzfLua lsp_workspace_symbols`.

It’s not configured by default you have to add it to `setup` or call `: FzfLua lsp_workspace_symbols path_shorten=true`

**Comment by nyngwang** [comment]
@ibhagwan I added it to `setup.files.path_shorten` and set it to true but it didn't work. So the only possible way is to call it like `:FzfLua lsp_workspace_symbols path_shorten=true`?

**Comment by ibhagwan** [comment]
> @ibhagwan I added it to `setup.files.path_shorten` and set it to true but it didn't work. So the only possible way is to call it like `:FzfLua lsp_workspace_symbols path_shorten=true`?

It should work via setup (just tested it), you either did something wrong or there’s a bug I need to fix.

**Comment by ibhagwan** [comment]
@ibhagwan workspace symbols has its own config section, define it under `lsp.symbols.path_shorten` (I.e `lsp = { symbols = { path_shorten = true } }`).

**Comment by nyngwang** [comment]
@ibhagwan Great, it works!
