### ISSUE TITLE
[Feature Request] Include buffer local commands

### ISSUE THREAD

**Issue by tobiwild** [ibhagwan/fzf-lua#445]
I'd love to see buffer local commands in `:FzfLua commands` like so:
```lua
  local global_commands = vim.api.nvim_get_commands {}
  local buf_commands = vim.api.nvim_buf_get_commands(0, {})
  local commands = vim.tbl_extend('force', {}, global_commands, buf_commands)
```
Currently I use a custom fzf action to include them. I also have to check that `k` is a string in here:
```lua
  for k, _ in pairs(commands) do
    table.insert(entries, utils.ansi_codes.magenta(k))
  end
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/704d801d50234da3d96e35c18ab3598383fed365

Ty for the suggesion @tobiwild.

I thought it made sense to slightly improve on this and display buffer local commands with different color at the top of the list, let me know if have any issues with that I can modify this behavior or make it optional:
![image](https://user-images.githubusercontent.com/59988195/173244542-dd6442ba-5c22-4986-87d7-55c76566d605.png)
