### ISSUE TITLE
[Feature Request] Automatically select definition in `lsp_definitions`

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#446]
After calling `FzfLua lsp_definitions` on a symbol with one definition, I believe the sole entry should be automatically selected and cursor moved to it (e.g. behave exactl like `vim.lsp.buf.definition()`.

**Comment by ibhagwan** [comment]
One of the oldest request, take a look at #13.

**Comment by ibhagwan** [comment]
FYI, it’s also found [in the wiki: LSP: jump to location for single result](https://github.com/ibhagwan/fzf-lua/wiki#lsp-jump-to-location-for-single-result), although incomplete with much room for improvement it has good information for power users, worth taking a look.
