### ISSUE TITLE
Oldfiles only showing one entry

### ISSUE THREAD

**Issue by luisvgs** [ibhagwan/fzf-lua#447]
### Info

- Operating System: EndeavourOS
- Shell: zsh
- Terminal: Kitty
- `nvim --version`: 0.7.0
- `fzf --version`: 0.30

- [ ] The issue is reproducible with `minimal_init.lua`

### Description 
Hi, I've been using `fzf-lua` for a while, and after recent updates I noticed that when running `:FzfLua oldfiles` it only shows one entry (e.g: History> 1/1), when it used to show a long list of my most recent opened files. There's any configuration step or breaking change that I'm missing? My config file looks as follows: 
```
require("fzf-lua").setup({
	files = {
		previewer = false,
	},
	oldfiles = {
		previewer = false,
	},
})
```
Any further suggestion would be deeply appreciated, thanks in advance.

**Comment by ibhagwan** [comment]
Seems this got intruduced in https://github.com/ibhagwan/fzf-lua/commit/62f67b61949141bd633eca50297fd10884c248a6 while addressing #436.

https://github.com/ibhagwan/fzf-lua/commit/396eae2610ad0b4e1a0ff01ca6d3742377c935ae - this should solve it.

**Comment by luisvgs** [comment]
@ibhagwan thank you, works like a charm.

**Comment by ibhagwan** [comment]
Oops, I accidentally left a debug print in the code, just forced pushed to https://github.com/ibhagwan/fzf-lua/commit/2d2ee02d17349daa372704be30fdd8765c3364a1 so you might have to `git pull --rebase`.
