### ISSUE TITLE
[Bug] jump_file_to_single_result_action broken

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#448]
### Info

- Operating System: arch
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.7
- `fzf --version`: 0.30

- [x] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
Simply running
```lua
require 'fzf-lua'.lsp_definitions {
    sync = true,
    jump_to_single_result = true,
    jump_to_single_result_action = require 'fzf-lua.actions'.file_vsplit
}
```
results in:
E5108: Error executing lua ...e/nvim/site/pack/paqs/start/fzf-lua/lua/fzf-lua/path.lua:15: bad argument #1 to 'string_
byte' (string expected, got nil)
stack traceback:
        [C]: in function 'string_byte'
        ...e/nvim/site/pack/paqs/start/fzf-lua/lua/fzf-lua/path.lua:15: in function 'starts_with_separator'
        ...vim/site/pack/paqs/start/fzf-lua/lua/fzf-lua/actions.lua:92: in function 'vimcmd_file'
        ...vim/site/pack/paqs/start/fzf-lua/lua/fzf-lua/actions.lua:144: in function 'jump_to_location'
        ...te/pack/paqs/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:36: in function 'handler'
        ...te/pack/paqs/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:236: in function 'set_lsp_fzf_fn'
        ...te/pack/paqs/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:328: in function 'v'
        ...te/pack/paqs/start/fzf-lua/lua/fzf-lua/providers/lsp.lua:986: in function 'lsp_definitions'
        [string ":lua"]:1: in main chunk

This happens to me with symbols with definitions both within and out of the file name.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/57402a41ac6f983640c41af43ce0c37929e61c43 - fixed.
