### ISSUE TITLE
[Question] Simple Custom Live Extension

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#449]
I am aware of #57, but even after reading through the examples you made, I cannot figure this issue out. I am attempting to replicate ThePrimeagen's [git-worktree](https://github.com/ThePrimeagen/git-worktree.nvim) plugin, namely to port the telescope extension to fzf-lua. The details of the implementation are already finished by him, I just have trouble with generating a simple picker. 

I need to filter the command `git worktree list` into fzf. I need no previews or anything fancy - a simple *live* picker with my custom actions. My attempt to do so is below, which fails in many aspects - the query doesn't fuzzy find with respect to `git worktree list`, firstly previews the git history rather than `git worktree list`, etc. Any help would be appreciated.
```lua
function(opts)
    local path = require 'fzf-lua.path'
    local core = require 'fzf-lua.core'
    local config = require 'fzf-lua.config'
    opts = config.normalize_opts(opts, config.globals.git)

    opts.cwd = path.git_root(opts.cwd)
    local cmd = path.git_cwd('git worktree list', opts.cwd)

    -- this gets called every keystroke, setup for this
    -- is done inside 'set_fzf_interactive_cmd(opts)'
    opts._reload_command = function(query)
        return cmd .. (#query > 0 and '-S ' .. vim.fn.shellescape(query) or '')
    end

    opts.exec_empty_query = true
    opts = core.set_fzf_interactive_cmd(opts)

    coroutine.wrap(function()
        local selected = core.fzf(opts)
        if not selected then
            return
        end
        actions.act(opts.actions, selected, opts)
    end)()
end
```

**Comment by ibhagwan** [comment]
It's been a while since #57, I now use a different approach for live grep which uses a separate process altogether using `nvim --headless` (search for `multiprocess`) for performance reasons, for your relatively simply task I don't think that's required (as it compliates using external modules a bit) so the above is the right approach.

I modified it a bit to be able to support `:FzfLua resume` properly and also have a basic preview that displays the command and selected item as a baseline for your code, do with it what you please:
```lua
function M.test(opts)

  local fzf = require('fzf-lua')
  opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)

  -- not a must, this just checks we're inside a
  -- git repo or prints an error to ':messages'
  if not fzf.path.git_root(opts) then return end

  -- this adds `-C <cwd>` to the command
  local cmd = fzf.path.git_cwd('git worktree list', opts)
  opts.cmd = cmd

  opts._reload_command = function(query)
    print("query", query)
    opts.cmd = cmd .. (#query > 0 and '-S ' .. vim.fn.shellescape(query) or '')
    return opts.cmd
  end

  -- simple preview that displays the command/selected item
  local prev_act = fzf.shell.action(function (args)
    return ("[command]:\t %s\n[selected line]: %s"):format(opts.cmd, args[1])
  end, nil, opts.debug)
  opts.fzf_opts['--preview'] = prev_act

  -- this is for resume to recall the function entirely
  -- which is required when running "live" query types
  opts.__FNCREF__ = opts.__FNCREF__ or fzf.utils.__FNCREF__()
  opts.query = opts.query or fzf.config.__resume_data.last_query

  opts.exec_empty_query = true
  opts = fzf.core.set_fzf_interactive_cmd(opts)

  -- use 'core.fzf_wrap' instead of 'core.fzf' for resume
  -- support, otherwise actions won't work when resuming
  fzf.core.fzf_wrap(opts, opts.fzf_fn, function(selected)

    if not selected then return end
    fzf.actions.act(opts.actions, selected, opts)

  end)()
end
```

**Comment by ibhagwan** [comment]
Btw, if you can also "transform" the command output, for exmaple if you wanted to color the output, etc, you can use `opts._fn_transform` for that, I edited the above comment to reflect that as well by addng a simple prefix before each line.

**Comment by barrett-ruth** [comment]
Thanks for the color info, I was going to ask about that next. With regard to actions, I declare opts.actions as the following inside the picker:
```lua
local delete_worktree = function(selected, opts) [[ stuff ]] end
opts.actions = {
    ['ctrl-d'] = { delete_worktree, actions.resume },
}
```
However, pressing `<c-d>` when I open the picker seems to do nothing at all.

**Comment by ibhagwan** [comment]
What happens if you `print` before `actions.act`? What does `selected` contain?

**Comment by barrett-ruth** [comment]
```lua
print(selected)
```
yields whatever input I typed into the prompt a.k.a. the user input (if printed before `actions.act`).
However, `delete_worktree` seems to not be called.
Below is how I pass in actions to `fzf.actions.act` - are you sure this is correct?
```lua
fzf.actions.act({
    ['ctrl-d'] = { delete_worktree, actions.resume },
}, selected, opts)
```

**Comment by ibhagwan** [comment]
I’ll check the code later when I’m on the computer, can you try setting a `default` action too?

**Comment by barrett-ruth** [comment]
Default action yields nil and similar behavior. No rush, thanks for the responses. I think the picker setup is fundamentally flawed as it isn't fuzzy finding the output correctly.

**Comment by ibhagwan** [comment]
> Default action yields nil and similar behavior. No rush, thanks for the responses. I think the picker setup is fundamentally flawed as it isn't fuzzy finding the output correctly.

It’s not flawed, this is how “live” query works using fzf’s `reload` action, every keystroke generates a new command, fuzzy finding is disabled by design, if you need fuzzy finding you need to think of a different design without reloading the query.

**Comment by barrett-ruth** [comment]
Yes sorry, by flawed I meant the approach I wanted to take was flawed. I see what you mean now.

**Comment by ibhagwan** [comment]
That makes things extra simple:
```lua
function M.test(opts)
  local fzf = require('fzf-lua')
  opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)

  if not fzf.path.git_root(opts) then return end
  opts.cmd = fzf.path.git_cwd('git worktree list', opts)
  
  fzf.core.fzf_wrap(opts, opts.cmd, function(selected)
    if not selected then return end
    fzf.actions.act(opts.actions, selected, opts)
  end)()
end
```

**Comment by ibhagwan** [comment]
With actions, (note you need the `default` action, even it does nothing:
```lua
function M.test2(opts)
  local fzf = require('fzf-lua')
  opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)

  if not fzf.path.git_root(opts) then return end
  opts.cmd = fzf.path.git_cwd('git worktree list', opts)

  opts.actions = {
    ["default"] = { function(sel) print("sel", sel[1]) end, fzf.actions.resume },
    ["ctrl-y"]  = { function(sel) print("sel", sel[1]) end, fzf.actions.resume },
  }

  fzf.core.fzf_wrap(opts, opts.cmd, function(selected)
    if not selected then return end
    fzf.actions.act(opts.actions, selected, opts)
  end)()
end
```

**Comment by barrett-ruth** [comment]
That works perfect. Now I can press `<c-d>` and a branch is deleted. However, with `actions.resume` this deletion is not reflected, even though the git worktree has been removed. Just like calling `actions.buf_del` how can I make the list reflect real-time changes?

**Comment by ibhagwan** [comment]
>That works perfect. Now I can press `<c-d>` and a branch is deleted. However, with actions.resume this deletion is not reflected, even though the git worktree has been removed. Just like calling actions.buf_del how can I make the list reflect real-time changes and update after keypress?

Can I see your code? it must be a bit different than what I posted, I just tested the code with a simple `ls` provider and it works as expected, when running `resume` the command is then executed again and an updated list is shown.

> Note that if you update to https://github.com/ibhagwan/fzf-lua/commit/86804f7462301718e83397cc282d95b9f898589d, `default` action is no longer required.
```lua
function M.test(opts)
  local fzf = require('fzf-lua')
  opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)

  opts.cmd = "ls"

  opts.actions = {
    ["ctrl-x"]  = { function(sel)
        print("sel", opts.cwd .."/"..sel[1])
        vim.fn.delete(opts.cwd .."/"..sel[1])
    end, fzf.actions.resume },
  }

  fzf.core.fzf_wrap(opts, opts.cmd, function(selected)
    if not selected then return end
    fzf.actions.act(opts.actions, selected, opts)
  end)()
end
```

**Comment by ibhagwan** [comment]
>Furthermore, is there a way to access the query? I finished everything (I swear, hah) except one function which needs to parse the typed in query.

The typed query can be accessed with:
```lua
:lua print(require'fzf-lua'.config.__resume_data.last_query)
```

**Comment by barrett-ruth** [comment]
Thanks. By the way I see earlier you talked about `opts._fn_transform`. I don't see your use of that function actually included in your response where you edited it.

**Comment by ibhagwan** [comment]
> Thanks. By the way I see earlier you talked about `opts._fn_transform`. I don't see your use of that function actually included in your response where you edited it.

`_fn_transform` is only used in the “live” commands, the code I posted later simply pipes the command to fzf, I.e. what actually runs is `ls | fzf <options>`, that’s why I’m confused why your `resume` won’t update properly as it re-runs the command in the shell and simply displays the output in fzf.

If you wish to manipulate the command and process the output you need to use the livuv command wrapper:
```lua
  opts.cmd = libuv.spawn_nvim_fzf_cmd(
    {
      cwd = opts.cwd,
      cmd = 'git worktree list'
    },
    -- this gets called for each output line
    function(x)
      return x
    end)
```

**Comment by barrett-ruth** [comment]
Ok, got it. Here is my working solution that I will post on the other repository, can you do a quick visual check for any obvious bugs? Thanks.

```lua
local fzf = require 'fzf-lua'
local actions = require 'fzf-lua.actions'

-- One of my example actions
local create_worktree = function(_)
    local query = fzf.config.__resume_data.last_query
    if require('utils').empty(query) then
        return
    end

    local path, branch, upstream = unpack(vim.split(vim.trim(query), ' '))
    branch = not branch and vim.fn.fnamemodify(path, ':t') or branch

    require('git-worktree').create_worktree(path, branch, upstream)
end

return {
    git_worktrees = function(opts)
        opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)

        opts.cmd = fzf.path.git_cwd('git worktree list | sed "s|$HOME|~|g"', opts)

        opts.actions = {
            ['default'] = switch_worktree,
            ['ctrl-a'] = { create_worktree, actions.resume },
            ['ctrl-d'] = { delete_worktree, actions.resume },
            -- etc.
        }

        fzf.core.fzf_wrap(opts, opts.cmd, function(selected)
            if not selected then
                return
            end
            actions.act(opts.actions, selected, opts)
        end)()
    end,
}
```

**Comment by barrett-ruth** [comment]
Also, I'm fine with hardcoding the color strings, but I would like the output to be colored. `git worktree list` itself doesn't yield colored output - is there a more "neovim-like" method to surround the `path` and `branch` strings in the example code above with a highlight?

**Comment by ibhagwan** [comment]
>Ok, got it. Here is my working solution that I will post on the other repository, can you do a quick visual check for any obvious bugs? Thanks.

Looks great!

> Also, I'm fine with hardcoding the color strings, but I would like the output to be colored. `git worktree list` itself doesn't yield colored output - is there a more "neovim-like" method to surround the `path` and `branch` strings in the example code above with a highlight?

As mentioned in the previous comment, wrap your `opts.cmd` with the `libuv` wrapper (I don't think you need `git_cwd` since the command would be run inside `opts.cwd`):
```lua
  opts.cmd = fzf.libuv.spawn_nvim_fzf_cmd(
    {
      cwd = opts.cwd,
      cmd = 'git worktree list | sed "s|$HOME|~|g"'
      -- if the above doesn't work with a custom `cwd` you can always use
      -- cmd = fzf.path.git_cwd('git worktree list | sed "s|$HOME|~|g"', opts)
    },
    -- this gets called for each output line
    function(x)
      return fzf.utils.ansi_codes.green(x)
    end)
```

You can also use `utils.ansi_from_hl` to construct a terminal color escape sequence from neovim highlight groups but it will require a bit of a workaround since it calls vim functions (`synIDattr`) that aren't allowed inside a lua coroutine (it will fail with `E5560: vimL function must not be called in a lua loop callback`).

If you wish to see an example of a terminal RBG escape sequence run:
```lua
:lua print(require'fzf-lua'.utils.ansi_from_hl("ErrorMsg", "test"))
-- this wraps the text with the escape sequence based on your current
-- colorscheme highlights, e.g.: ^[[38;2;252;81;78mtest^[[0m
```

**Comment by ibhagwan** [comment]
If you really wanted to use `utils.ansi_from_hl` there are probably many ways to go about it but here's one decntly acceptable "hack" (can add as many highlights as you want):
```lua
  local colormap = {
      ["ErrorMsg"] = fzf.utils.ansi_from_hl("ErrorMsg", "<placeholder>")
  }

  opts.cmd = fzf.libuv.spawn_nvim_fzf_cmd(
    {
      cwd = opts.cwd,
      cmd = 'ls'
    },
    -- this gets called for each output line
    function(x)
      return colormap["ErrorMsg"]:gsub("<placeholder>", x)
    end)
```

**Comment by ibhagwan** [comment]
@barrett-ruth, I'm working on providing a better API, could simplify your code, see https://github.com/ibhagwan/fzf-lua/wiki/Advanced

**Comment by barrett-ruth** [comment]
@ibhagwan Thanks, the API looks a lot better - even easier than telescope integration which I think is the main draw to that plugin.
However, I'm unable to see how I could translate the following code into using the api because of the following:
1. How to integrate the `fzf.path.git_cwd` (a.k.a, run the cmd in the correct directory)
2. I use  `fzf.libuv.spawn_nvim_fzf_cmd` and then color this output with an anonymous function using hard-coded string manipulation - however, this seems like an extremely niche use case so it's perfectly reasonable for this not to be included in the API.
```lua
        opts.cmd = fzf.libuv.spawn_nvim_fzf_cmd({
            cmd = fzf.path.git_cwd(
                'git worktree list | sed "s|$HOME|~|g"',
                opts
            ),
        }, function(x)
            local parsed = parse_entry(x)

            local first_whitespace = { x:find '%s+' }
            local _, second_whitespace_begin = x:find '.*%S%s'
            local _, second_whitespace_end = x:find '.*%s+'

            local colored = table.concat {
                fzf.utils.ansi_codes.blue(parsed.path),
                x:sub(unpack(first_whitespace)),
                fzf.utils.ansi_codes.yellow(parsed.hash),
                x:sub(second_whitespace_begin, second_whitespace_end),
                fzf.utils.ansi_codes.green('[' .. parsed.branch .. ']'),
            }

            return colored
        end)
```

**Comment by ibhagwan** [comment]
1. `git_cwd` just returns a string command with, you can still use it just the same instead of `contents`
2. It’s not a niche use case IMO, that’s why you have [`opts.n_transform`](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-cont-cmd-trans)

Also, I don’t think you even need `git_cwd`, if you supply `cwd` as part of the options the command would be run in the context of the supplied folder, your code should look like:
```lua

require'fzf-lua'.fzf_exec('git worktree list | sed "s|$HOME|~|g"', {
    fn_transform = function(x)
      local parsed = parse_entry(x)

      local first_whitespace = { x:find '%s+' }
      local _, second_whitespace_begin = x:find '.*%S%s'
      local _, second_whitespace_end = x:find '.*%s+'

      local colored = table.concat {
          fzf.utils.ansi_codes.blue(parsed.path),
          x:sub(unpack(first_whitespace)),
          fzf.utils.ansi_codes.yellow(parsed.hash),
          x:sub(second_whitespace_begin, second_whitespace_end),
          fzf.utils.ansi_codes.green('[' .. parsed.branch .. ']'),
      }
            
      return colored
    end,
    actions = { … },
    -- can also supply working directory if you wish
    -- cwd = <a working directory>,
   
  })
```

**Comment by barrett-ruth** [comment]
Awesome. Works perfectly.

**Comment by ibhagwan** [comment]
@barrett-ruth I took a look at your [worktrees.lua@dotfiles](https://github.com/barrett-ruth/dots/blob/main/nvim/lua/paqs/worktree.lua), your `git_cwd` does nothing, the only reason you’d want to use it is if you want to have an option to run your worktrees on a separate working directory, I.e. `worktrees({ cwd = … })` (which you can still do in my example code using. `cwd`).

As for `normalize_options`, it’s also not required in this case, all it does is provide default options for your functions that are merged from `fzf-lua.config.global.git`, if you want a different prompt (or any other options) you can supply it as part of `fzf_exec(cmd, { prompt = …, actions = … })`.

**Comment by barrett-ruth** [comment]
Hey @ibhagwan , coming back to this way later.

Right now I have below:
```lua
local parse_entry = function(entry)
    local parsed = vim.split(entry, '%s+')

    return {
        path = parsed[1],
        hash = parsed[2],
        branch = parsed[3]:sub(2, #parsed[3] - 1),
    }
end

local actions, fzf = require 'fzf-lua.actions', require 'fzf-lua'

return {
    git_worktrees = function()
        local wt = require 'git-worktree'

        fzf.fzf_exec('git worktree list | sed "s|$HOME|~|g"', {
            fn_transform = function(x)
                local parsed = parse_entry(x)

                local first_whitespace = { x:find '%s+' }
                local _, second_whitespace_begin = x:find '.*%S%s'
                local _, second_whitespace_end = x:find '.*%s+'

                local colored = table.concat {
                    fzf.utils.ansi_codes.blue(parsed.path),
                    x:sub(unpack(first_whitespace)),
                    fzf.utils.ansi_codes.yellow(parsed.hash),
                    x:sub(second_whitespace_begin, second_whitespace_end),
                    fzf.utils.ansi_codes.green('[' .. parsed.branch .. ']'),
                }
                return colored
            end,
            actions = {
                ['default'] = function(selected)
                    local parsed = parse_entry(selected[1])

                    wt.switch_worktree(parsed.branch)
                end,
                ['ctrl-a'] = {
                    function()
                        local query = fzf.config.__resume_data.last_query

                        if query == nil or query == '' then
                            return
                        end

                        local path, branch, upstream =
                            unpack(vim.split(vim.trim(query), ' '))
                        branch = not branch and vim.fn.fnamemodify(path, ':t')
                            or branch

                        wt.create_worktree(path, branch, upstream)
                    end,
                    actions.resume,
                },
                ['ctrl-d'] = {
                    function(selected)
                        local parsed = parse_entry(selected[1])

                        wt.delete_worktree(parsed.branch, true)
                    end,
                    actions.resume,
                },
            },
        })
    end,
}
```

This has worked fine the entire time, but now I have two questions:

1. Can you point me to a newer extension api that exists (if it is different than the above?)
2. Whenever I create a worktree, it is properly made and fzf resumes as specified by actions.resume. However, the picker does not update. Obviously, "resume" doesn't re-run the command specified. In this case though I would like to create a new worktree and then be able to switch to it. With the above code I have to create a new corktree with <c-a>, exit the picker, then fire up fzf-lua again to select it. Is there a way around this? Thanks.

**Comment by ibhagwan** [comment]
1. Nothing has changed in `fzf_exec`, the wiki is still accurate: https://github.com/ibhagwan/fzf-lua/wiki/Advanced


> However, the picker does not update. Obviously, "resume" doesn't re-run the command specified
2. Actually, the string command is the only content that is cached, the command should be run again and your worktree should be updated.
Another option, is the swap the resume call to a recursion and call ‘git_worktrees()` again but my preference would be to understand why your list isn’t getting updated properly, you can run this with `debug=true` and look at the underlying fzf command and investigate.

**Comment by barrett-ruth** [comment]
@ibhagwan this actually happens because git-worktree.nvim executes commands (eg delete a git worktree) asychronously so the changes don't seem to come up in time. Any advice for how to fix this?

**Comment by ibhagwan** [comment]
> @ibhagwan this actually happens because git-worktree.nvim executes commands (eg delete a git worktree) asychronously so the changes don't seem to come up in time. Any advice for how to fix this?

In this case you’d need to explore the code of `git-worktree.nvim` and find out if you can hook into the job callback and run the resume only once the job was finished, alternately you can hack an ugly workaround using `vim.schedule` with a sufficient enough delay.

**Comment by quolpr** [comment]
@barrett-ruth did you find a fix? Used your plugin, but came to the same problem recently

**Comment by barrett-ruth** [comment]
no actually, causing me to abandon trying to figure this out. - @ibhagwan any insight into how to deal with updating a picker after an asynchronous command?
