### ISSUE TITLE
Custom file query

### ISSUE THREAD

**Issue by sharadmv** [ibhagwan/fzf-lua#45]
Thanks for the great work on this plugin!

I had a question about a more flexible way of specifying what files to query with grep. Let's say I have a custom command `relevant-files` that prints out a list of files/directories (it can change depending on what the CWD is). I'd like `fzf-lua` to use this command in the call to `rg` (something like `rg --vimgrep {q} -- $(relevant-files)`). Is there a way to support this? 

I already tried using the `cwd`/`filename` options, setting them to `-- $(relevant-files)` but there is some shell escaping that prevents the command from working. After disabling the escaping, things seem to work but I also had to modify the `get_grep_command` function to add `--` before `search_path`. Any ideas on how to make this possible?

**Comment by ibhagwan** [comment]
I noticed there is inconsistency between how `cmd` behaves in `files` vs `grep` what if I change `get_grep_ cmd` to work as it does in [`get_files_cmd`](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/files.lua#L12), I.e. you can pass any command you want by using `cmd = …` and you’ll be responsible for the shell escaping, will that work for you?

**Comment by ibhagwan** [comment]
Without changing any existing functionality I added `raw_cmd` option to both `files` and `grep` - can you try sending your entire command to `grep({ raw_cmd = ... })` and let me know if that works for you?

**Comment by sharadmv** [comment]
I think something like that could work but I do need to inject the search query at some point. The `raw_cmd` won't have the search query from `live_grep` in it.

Ideally I want a final query that looks like this:
```
rg {q} -- $(relevant-files)
```

Does that make sense?

**Comment by ibhagwan** [comment]
What happens if you simply send `live_grep({ raw_cmd = “rg {q} -- $(relevant-files)” })`?

Looking at the code this will send this command (with `|| true` added) to the `reload` event, the only issue is it might not work due to the initial command being invalid, I didn’t test it yet.

Another option is I can add another `raw_filespec` variable that would replace filename/cwd without the shell escape and add `—` to the command.

This is easily solve-able in many ways I’m just trying to find something that would make sense in the future that wouldn’t make me go “what is this and why did I add it” lol

**Comment by sharadmv** [comment]
The initial command does not seem to be working :(. There's no visible error but the search is not working. The `{q}` causes a regex error when I try running the command manually.

**Comment by ibhagwan** [comment]
> The initial command does not seem to be working :(. There's no visible error but the search is not working. The `{q}` causes a regex error when I try running the command manually.

Ok, I added `filespec` as an option that would be added with no shell escape, I didn't add the `--` so users can have the option to omit that if they wish, to achieve the command you're after use
```lua
:lua require('fzf-lua').live_grep({ filespec = '-- $(relevant-files)' })
```

Let me know if this works for you?

**Comment by sharadmv** [comment]
Yes it works! Thank you for the quick turnaround!

**Comment by ibhagwan** [comment]
Nice :-)
