### ISSUE TITLE
[Question] Picker-specific Options

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#450]
If you recall, I found out how to show line and column numbers (but *not* filenames) for `lsp_document_symbols` with the following setup:
```lua
    lsp = {
        fzf_opts = {
            ['--with-nth'] = '2..',
            ['--delimiter'] = ':',
        },
    }
```

However, if I perform any other lsp search, I am left *without* filenames when I *do* want them (e.g. lsp references can be found in across many files). I basically want to enable this feature solely for `lsp_document_symbols`. However, if I attempt to pass these opts to fzf via 
```lua
require('fzf-lua').lsp_document_symbols { fzf_opts = ... }
```
The picker doesn't even pop up.
Furthermore, defining something like 
```lua
lsp_document_symbols = {
    fzf_opts = ...
}
```
in the `setup` has no effects either. Is there a way to do this?

**Comment by ibhagwan** [comment]
Btw, hiding file names is actually the default for `lsp_document_symbols` (not workspace though) so you might not even need any special config.

**Comment by barrett-ruth** [comment]
I spelled delimiter incorrectly in my config but not in the issue. Jesus.
