### ISSUE TITLE
[Bug] `grep` double-escaping special characters

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#451]
With global resume, type in `\(\{` to `live_grep` or `live_grep_native` query.
Exit out and then `FzfLua resume`
Query field is populated with `\\\(` (double-escaped)

Setup:
```lua
require('fzf-lua').setup {
    global_resume = true,
    global_resume_query = true,
```

**Comment by barrett-ruth** [comment]
This occurs only in live_grep, not in files(), for example.

**Comment by ibhagwan** [comment]
This was happening only with `live_grep_native` which is a convinient shortcut to `live_grep({git_icons =false, file_icons=false, rg_glob=false})` (or `rg_glob` not specified), I'm assuming these are your `grep` options, so in your case  `live_grep` was equivalent to `live_grep_native`.

https://github.com/ibhagwan/fzf-lua/commit/ae99fed33f553a8fd38d020b5b72fb3e0afc2655 - should work as expected now.
