### ISSUE TITLE
[Bug] Tags search is failing when tags file is under $HOME

### ISSUE THREAD

**Issue by zahidkizmaz** [ibhagwan/fzf-lua#452]
### Info

- Operating System: Macos and ArchLinux
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.7.0
- `fzf --version`: 0.30.0

### Description 

Thank you for the great plugin and great work. I really appreciate and love using it.

My issue started after this commit 62f67b61949141bd633eca50297fd10884c248a6. I started seeing tag search failing. If I go to prior commit and install the plugin things are working fine.

I think it might be related to location of my tags file. Which is under `$HOME/.cache/tags`.

**Here is the screenshot of the error I see when I try to do a tag search:**

![grafik](https://user-images.githubusercontent.com/15658403/174019517-661e6559-94d4-45bb-9f29-3cb2983291d0.png)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/52326a6444eccccc826f1c03970387d6459c2ba2 

Can you update to the latest commit and let me know if the issue is resolved?

**Comment by zahidkizmaz** [comment]
That fixed it. Thanks a lot for the quick fix. 👍

**Comment by ibhagwan** [comment]
Ty for the report @zahidkizmaz!
