### ISSUE TITLE
The starting char `<` is missing on resume of `live_grep_glob`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#454]
### Info

- Operating System: macOS 12.4
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: NVIM v0.8.0-dev
- `fzf --version`: 0.30.0 (brew)

### Description 

Run  `require('fzf-lua').live_grep_glob()` and type `<C-w>` then press Esc, and then resume(with `resume=true`) it, the search words became `C-w>`, i.e. the first `<` is missing.

part of the config: (let me know when the entire config is needed!)

```lua
grep = {
  prompt = ' Word $ ',
  no_global_resume = true,
  resume = true,
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/6a4392564b818061731c6a39fcc116ff9fc97dd0 - should work now.

Ty for the report @nyngwang!

**Comment by nyngwang** [comment]
I did see your kindly, decent fix but have no time to reply. Thank you!
