### ISSUE TITLE
Custom command

### ISSUE THREAD

**Issue by sheoak** [ibhagwan/fzf-lua#456]
I would like to create a custom command using Fzf-lua but I can't find the answer in the current document, not sure it's event possible?

Need:
1. I want to pipe the result of github cli commands `gh` (list of pull request, list of issues…) to fzf
2. I want to be able to execute command on the selected items (close PR, view issue…). I suppose I would need to customize actions for this custom type in the setup.

Thanks!

**Comment by ibhagwan** [comment]
Read #449 for more info (similar request):

```lua
function M.test(opts)
  local fzf = require('fzf-lua')
  opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)

  opts.cmd = 'gh …'

  opts.actions = {
    ["ctrl-y"]  = { function(sel) print("sel", sel[1]) end, fzf.actions.resume },
  }

  fzf.core.fzf_wrap(opts, opts.cmd, function(selected)
    if not selected then return end
    fzf.actions.act(opts.actions, selected, opts)
  end)()
end
```

**Comment by sheoak** [comment]
I missed that issue, sorry! Thanks for the quick reply, I will have a look, very helpful!

**Comment by jamischarles** [comment]
Was just going to post the exact same question! I was looking for `:FzfLua run` but didn't find it. This will work. Thx!

**Comment by ibhagwan** [comment]
> Was just going to post the exact same question! I was looking for `:FzfLua run` but didn't find it. This will work. Thx!

Note that if your command outputs filenames and doesn’t require any special handling you can run

```lua
:lua require'fzf-lua'.files({ cmd = '<your command>' })
-- with action override
:lua require'fzf-lua'.files({ cmd = '<your command>', actions = { ['default'] = function(selected, opts) …<do something>… end } })


```

**Comment by jamischarles** [comment]
@ibhagwan Oh man. I just need to share this:

```lua 
 map("n", "<Leader>m", ':lua require(\'fzf-lua\').files({cmd = "fre --sorted", actions = {["ctrl-x"] = {function(selected) vim.cmd(":!fre --delete ".. selected[1]) end, require"fzf-lua.actions".resume} }})<CR>') 
 -- FIXME: Can we cache this somehow to speed it up?
```

Oh man this has me so jazzed up. Doing this in vimscript would have taken me HOURS of research, then I'd give up. This took me 10-20min use fzf-lua and lua.

Here's what it does:
1. Maps `<leader>m` to show a `frecency` list using the `fre` CLI tool.
2. When I hit `<Ctrl-x>` in the list it runs the `fre` CLI command to delete the item from the dataset.
3. resumes with the search.

Amazing!!!
Thank you for this @ibhagwan

**Comment by ibhagwan** [comment]
> Oh man this has me so jazzed up. Doing this in vimscript would have taken me HOURS of research, then I'd give up. This took me 10-20min with fzf-lua and lua.

I feel this closely, this is one of the main reasons I embarked on this project, even now after pretty much a finished plugin I still struggle with vimscript :)

You wrote it perfectly, I wouldn’t change a thing, maybe add a header line if it makes sense?

> -- FIXME: Can we cache this somehow to speed it up?

Unfortunately fzf doesn’t support a caching equivalent so the command has to run each time the interface is opened (which also happens on `resume`), if running the command `fre` is pretty slow you could cache its output inside fzf-lua (as a simple `{}` table) and then feed fzf lines from the table (as opposed to a command), but then you’d have to manage the table yourself, for example when you delete an item using `<C-x>`you’d need to also delete the item from the table (or empty the table and repopulate it from the `fre` command).

If you’re interested I can help you write this function but unless `fre` is fundamentally slow I don’t suspect you’d gain much performance benefit here, let me know.

**Comment by ibhagwan** [comment]
@sheoak, @jamischarles, in an effort to improve the API / extensibllity I have added `fzf_exec` (via https://github.com/ibhagwan/fzf-lua/commit/61684c6395dc16272166a0b4896e4ff3522b1127).

I intend to add proper API documentation to the Wiki, but before then it's impotant to note the exmaple from above can be siginificantly simplified, this code:
```lua
function M.test(opts)
  local fzf = require('fzf-lua')
  opts = fzf.config.normalize_opts(opts, fzf.config.globals.git)

  opts.cmd = 'gh …'

  opts.actions = {
    ["ctrl-y"]  = { function(sel) print("sel", sel[1]) end, fzf.actions.resume },
  }

  fzf.core.fzf_wrap(opts, opts.cmd, function(selected)
    if not selected then return end
    fzf.actions.act(opts.actions, selected, opts)
  end)()
end
```
Can now be represented by:
```lua
:lua require'fzf-lua'.fzf_exec("gh ...", { actions={ ['default']=function(sel) print("sel",sel[1]) end } })
```

**Comment by ibhagwan** [comment]
Still WIP but [wiki#Advance](https://github.com/ibhagwan/fzf-lua/wiki/Advanced) covers all of this thread, I intent to keep updating more advacned concepts as "live" commands and previewer support.

**Comment by jamischarles** [comment]
Awesome! thanks @ibhagwan !!

**Comment by nyngwang** [comment]
@ibhagwan If you have time, I would also like to know your introduction on `lsp_{document|workspace}_symbols` (with/without the `live` feature). My current understanding is that language servers somehow provide more information than just `grep` or `live_grep`. (I tend to stick to the latter because it works even on files without lsp loaded, so it's more portable)

**Comment by ibhagwan** [comment]
> @ibhagwan If you have time, I would also like to know your introduction on `lsp_{document|workspace}_symbols` (with/without the `live` feature). These commands caught my eye when I was reading old issues on fzf-lua(Yup, I subscribed to receive all notifications, and get accumulated). My current understanding is that language servers somehow provide more information than just `grep` or `live_grep`. (I tend to stick to the latter because it works even on files without lsp loaded, so it's more portable)

TBH, I didn’t research deeply the LSP protocol/spec and what info is provided by the LSP server, I just implemented the basic queries that were needed in order to make the interface work and comparable to working with LSP in an IDE (like VSCode, etc). I also mostly use grep/live_grep.
