### ISSUE TITLE
git_icons change expected order of the list

### ISSUE THREAD

**Issue by monkoose** [ibhagwan/fzf-lua#458]
Currently `git_icons` adds its field to the search scope. Because of that search order is not what expected and any fzf entry with `git_icons` on it more likely would be at the bottom of the list.
There is fzf flag `-n` or `--nth=` that can exclude some fields from the search scope. 

**Can this field be excluded from search scope by default when `git_icons = true`?**

Personally I do not use `file_icons` so maybe they behave the same, haven't tested.

**Comment by ibhagwan** [comment]
This is a bit more complicated as `nth` flags require sending the special fzf-lua `nbsp` delimiter to fzf which will change the field index of all other commands that already use `:` delimiter to hide certain elements (for example, hiding file name in `blines` and `lsp_document_symbols`).

If you don’t care about the above I can help you find the right flags to send via `fzf_opts`  to achieve what you want but I would prefer to avoid adding that by default to all providers.

I can try to think of other strategies but due to the way fzf works we’re a bit limited in this specific case.

**Comment by ibhagwan** [comment]
You’re correct but let’s take for example the entry `M filename:line:column`, when you use `:` as a delimiter the filename is index 1, so now you can hide the filename with `--with-nth=2..` but when you add the nbsp as delimiter the filename now becomes field number 2 so you now need to use `--with-nth=3..`.

It’s not a huge deal as the code relies less on the use of nth options but it can still complicate the logic of some providers so I’d rather not make this default behavior.

**Comment by ibhagwan** [comment]
In addition some users may view this as desired behavior since you can search for `M` to find modified files, using `nth` you’ll lose this functionality.

**Comment by monkoose** [comment]
Ok, thank you. If you don't want to change any behavior i'm gonna close this.

Will just use `git_icons = false` on my side. There is no option to disable it for every provider, only option for each provider separately, right?

**Comment by ibhagwan** [comment]
Use `global_git_icons` https://github.com/ibhagwan/fzf-lua/issues/188#issuecomment-1154172463

**Comment by ibhagwan** [comment]
Hi @monkoose, I'm not sure why this happens in your setup, I just tested this with different options (`file_icons` and `color_icons`) and the `M` icon doesn't make any difference in the entry order both when opening the interface and when fuzzy searching:

![image](https://user-images.githubusercontent.com/59988195/175798252-6328bcba-c0ba-4553-b53a-ebb0fd6e7549.png)

**Comment by monkoose** [comment]
Without any query it doesn't affected for sure. Try to limit it with lets say `fzf` for your example.

**Comment by monkoose** [comment]
Same for any grep search, but only when `ctlr-g` is pressed and another limit query entered.
Like lets imagine two files in the same dir `one.lua` and `two.lua` all contain word `hello`, one is modified and two is not. If you grep for `he` then press `C-g` and type `llo` the `two.lua` file became the first one in the list.
