### ISSUE TITLE
List out projects and switch between them

### ISSUE THREAD

**Issue by tarunsharma20** [ibhagwan/fzf-lua#461]
Hello,

First of all thanks for the plugin. I am using it from last 6 months, without any issue.

These days i am working on multiple repositories/projects at once. I am looking for a command to list out all configured projects and switch between them. I totally migrated from [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) to fzf-lua, only looking for an alternative of [telescope-project.nvim](https://github.com/nvim-telescope/telescope-project.nvim).

Thanks!

**Comment by ibhagwan** [comment]
Relatble, I also had such a requirement so I [created `workdirs` for myself](https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/fzf-lua/init.lua#L345-L397=), all it does is read a lua file with a table containing my current projects and then `cd`'s between them.

I think this issue is very subjective and I feel full-blown project management feature will be a bottomless hole of feature requests :-)

Another idea that was just posted a few hours ago, https://github.com/ibhagwan/fzf-lua/issues/456#issuecomment-1165964826 uses frecency to manage their projects, might be of interest to you.

**Comment by tarunsharma20** [comment]
I mean if we can have a config where we can define different projects. Inside project if we found any .git or other source code we can consider it as separate project.

configuration 
```
myConfig= { '~/foo', '~/lorem'}
```

Directory structure 
```
foo/
 - bar.txt
 - ipsum/
   - .git/
   - foo.js
   - bar.js
- baz/
  - .git/
  - file.json
 
 lorem/
 - dolor.txt
 - sit.php
```
Explorer

-------------------------------------------------------------------------
|                                                                                                                          |
|                                                                                                                          |
|                                                                                                                          |
|                                                                                                                          |
|                                                                                                                          |

I guess if we can just switch between them, then we have everything already. I mean we already can search, find file and do other stuff.

**Comment by ibhagwan** [comment]
This can easily be created, I introduced a new API to simplify creation of such extensions: https://github.com/ibhagwan/fzf-lua/wiki/Advanced

I'd recommend using [`content` as a function](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-cont-fnc) which runs `find -type d` inside each of your folders from `myConfig` and adds the subfolders using `fzf_cb` (as demonstrated in the link).

Let me know if you need help and I'll help you create it.

**Comment by tarunsharma20** [comment]
It's not working for me even simple example like:
`:lua require'fzf-lua'.fzf_exec({ "line1", "line2" })`

Getting error:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'fzf_exec' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk

**Comment by ibhagwan** [comment]
Your code doesn’t recognize `fzf_ exec`, can you make sure you have the latest commit?

**Comment by igray** [comment]
@tarunsharma20 Hopefully this helps, but I was able to replicate the Telescope functionality by placing this at the bottom of my config file for [telescope-project](https://github.com/nvim-telescope/telescope-project.nvim):
```
local fzf_status_ok, fzflua = pcall(require, "fzf-lua")
if not fzf_status_ok then
	return
end

vim.api.nvim_create_user_command(
  "FzfProject",
  function()
    local opts = {}
    opts.prompt = "Projects> "
    opts.actions = {
      ['default'] = function(selected)
        vim.cmd("FzfLua files cwd=" .. selected[1])
      end
    }
    -- projects are returned oldest first
    local projects = project.get_recent_projects()
    local recent_projects = {}
    for i=#projects, 1, -1 do
      recent_projects[#recent_projects+1] = projects[i]
    end
    fzflua.fzf_exec(recent_projects, opts)
  end,
  { nargs = 0 }
)
```
This assumes that `project` was first initialized by something like `local status_ok, project = pcall(require, "project_nvim")`. The above snippet would replace something like:
```
local tele_status_ok, telescope = pcall(require, "telescope")
if not tele_status_ok then
	return
end

telescope.load_extension("projects")
```

Now, when I run `:FzfProject`, it uses Fzf-Lua to first search my projects, then pick a file from that project, which then switches to the other project. Note that I'm reversing the list returned by `get_recent_projects()` because the telescope plugin places the searchbar below the projects, while Fzf-Lua searches from the top.

**Comment by ibhagwan** [comment]
Looks great @igray !

> Note that I'm reversing the list returned by `get_recent_projects()` because the telescope plugin places the searchbar below the projects, while Fzf-Lua searches from the top.

This can be controlled by `fzf_opts['--layout']` option if you wish to have the same layout as Telescope.

**Comment by igray** [comment]
@ibhagwan Thank you so much for this plug-in as well as the new `fzf_exec`! I was having performance issues with Telescope and recently switched. This was the final piece to replace it completely.

**Comment by ibhagwan** [comment]
> @ibhagwan Thank you so much for this plug-in as well as the new `fzf_exec`! I was having performance issues with Telescope and recently switched. This was the final piece to replace it completely.

Ty @igray! I'm still working on the API so keep an eye on the Wiki page, I plan to add much more advanced customiztaions and preview integrations.

**Comment by tarunsharma20** [comment]
@ibhagwan  @igray Thank you so much. Finally basic stuff working after updating fzf-lua.

```
_G.fzf_dirs = function(content, opts)
  local fzf_lua = require'fzf-lua'
  opts = opts or {}
  opts.prompt = "Projects> "
  opts.actions = {
    ['default'] = function(selected)
      vim.cmd("cd " .. selected[1])
    end
  }
  fzf_lua.fzf_exec(content or {}, opts)
end

vim.keymap.set('n', '<leader>p', '<cmd>lua _G.fzf_dirs({"~/workshop/test-1", "~/workshop/test"})<CR>')
```

Now i have to just find all repositories inside defined directories and list them to.

**Comment by ibhagwan** [comment]
@tarunsharma20, you can use `vim.fn.systemlist` to run `find` or `fd` for every folder in the list, you can then merge the results by using `vim.tbl_extend`, let me know if you need help shouldn’t be more than a few lines of code.

I would also recommend to store your projects in a `.lua` file:
```lua
-- place this inside ~/.config/nvim/lua/projects.lua
return {
  "~/workshop/test-1",
  "~/workshop/test",
}
```
You can then use it in your mapping:
```lua
_G.fzf_dirs(require'projects.lua')
```

**Comment by ibhagwan** [comment]
@tarunsharma20 here you go:
> Note: 
```lua
_G.fzf_dirs = function(dirs, opts)
  local fzf_lua = require'fzf-lua'
  opts = opts or {}
  opts.prompt = "Projects> "
  opts.actions = {
    ['default'] = function(selected)
      vim.cmd("cd " .. vim.fn.expand(selected[1]))
    end
  }
  local contents = {}
  local cwd = vim.loop.cwd()
  -- Running `_G.fzf_dirs()` with no arguments will enumerate
  -- all subfolders under the current working directory (cwd)
  dirs = dirs or { cwd }
  for _, d in ipairs(dirs) do
    local subs = vim.fn.systemlist({"find", vim.fn.expand(d), "-type", "d"})
    if type(subs) == 'table' then
      contents = vim.tbl_extend("keep", contents,
        -- optional: display paths relative to current working directory
        vim.tbl_map(function(x) return fzf_lua.path.relative(x, cwd) end, subs))
    end
  end
  fzf_lua.fzf_exec(contents, opts)
end
```

**Comment by tarunsharma20** [comment]
Thank guys,

Finally I have something i was looking for:
```
_G.fzf_dirs = function(projects, opts)
  local fzf_lua = require'fzf-lua'
  local repos = {} 

  projects = projects or {}
  opts = opts or {}
  opts.prompt = "Projects> "
  opts.actions = {
    ['default'] = function(selected)
      vim.cmd("cd " .. repos[selected[1]])
    end
  }

  local max_depth = opts.max_depth or 5

  for _, project in ipairs(projects) do
    local key = string.match(project, ".*/(.*)")
    local absolute_path = vim.fn.expand(project)

    repos[key] = absolute_path

    local git_dirs = scan.scan_dir(absolute_path, {
      depth = max_depth,
      add_dirs = true,
      hidden = true,
      search_pattern = "%.git$"
    })

    for _, val in ipairs(git_dirs) do
      local git_dir = string.gsub(val, "/.git$", '')
      key = string.match(git_dir, ".*/(.*)")
      repos[key] = git_dir
    end
  end

  local dirs = {}
  for key in pairs(repos) do
    dirs[#dirs+1] = key
  end

  fzf_lua.fzf_exec(dirs or {}, opts)
end
```

I don't know lua. So if you have any suggestions to improve code above, then let me know.

There is only problem i noticed so far is `fzf_lua.fzf_exec` take time to execute even with simple table. I am also gonna try it with `vim.api.nvim_create_user_command` as suggested by @igray

**Comment by ibhagwan** [comment]
>There is only problem i noticed so far is fzf_lua.fzf_exec take time to execute even with simple table.

The way the code is structured `fzf_exec` only runs once you populated the final table, it probably takes time to run all your pleanary scans and glob matching, unfortunately both lua and neovim are single threaded and it takes some tricks to get the best performance.

There are many ways to go about it, you can use `fzf_exec(<function>, opts)` (instead of table) and populate the entries as they are found (that is assuming pleanary `scan_dir` is async, you might also want to run longer lasting operations inside a lua `coroutine` (you can see exmaples of how I do it in my code, for example [oldfiles.lua](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/oldfiles.lua#L29=)).

However, if you don't know lua well or wish to go the absolute best performance (and also easier route) you can create a shell script that outputs the list of directories and use it as contents, that way the entire scan will be run as an external process (using neovim's `jobstart`) piped into fzf and you'll get best performance and maximum UI responsivness.

> this is the equivalent of running `~/list-projects.sh | fzf` in the shell
```lua
  ...
  fzf_lua.fzf_exec("~/list-projects.sh", opts)
```

**Comment by tarunsharma20** [comment]
But, then it might not run in windows machine, and I am trying to avoid external dependency as much as possible. We already have pleanary as dependency, so trying to utilise it.

**Comment by ibhagwan** [comment]
> But, then it might not run in windows machine, and I am trying to avoid external dependency as much as possible. We already have pleanary as dependency, so trying to utilise it.

Then I'd say you have to embark on the `coroutine` route, also, find out if you can run `scan_dir` in an async way, optimally you'd want a callback for each found directory so you can call fzf-lua's callback to feed directories as they are found.

**Comment by tarunsharma20** [comment]
I'll try to improve it and will do some refactoring, but for now I am more than happy. I got exactly what i was looking for. Thanks for beautiful plugin, now i can get rid of telescope completely.

If anyone else looking for same, can have a look my overall setup to get and select projects.

fzf-project.lua
```lua
local fzf_status_ok, fzf_lua = pcall(require, "fzf-lua")
if not fzf_status_ok then
  return
end

local scan_status_ok, scan = pcall(require, "plenary.scandir")
if not scan_status_ok then
  return
end

local M = {}

M.projects = function(projects, opts)
  local repos = {}

  projects = projects or {}
  opts = opts or {}
  opts.prompt = "Projects> "
  opts.actions = {
    ['default'] = function(selected)
      vim.cmd("cd " .. repos[selected[1]])
    end
  }

  local max_depth = opts.max_depth or 5

  for _, project in ipairs(projects) do
    local key = string.match(project, ".*/(.*)")
    local absolute_path = vim.fn.expand(project)

    repos[key] = absolute_path

    local git_dirs = scan.scan_dir(absolute_path, {
      depth = max_depth,
      add_dirs = true,
      hidden = true,
      search_pattern = "%.git$"
    })

    for _, val in ipairs(git_dirs) do
      local git_dir = string.gsub(val, "/.git$", '')
      key = string.match(git_dir, ".*/(.*)")
      repos[key] = git_dir
    end
  end

  local dirs = {}
  for key in pairs(repos) do
    dirs[#dirs+1] = key
  end

  table.sort(dirs, function(a, b) return a:lower() < b:lower() end)

  fzf_lua.fzf_exec(dirs or {}, opts)
end

return M
```
keymap.lua
```lua
map('n', '<leader>fp', '<cmd>lua require("user.fzf.fzf-projects").projects({"~/workshop/my-projects", "~/rnd"})<CR>')
```

Also if all are happy, we can close this ticket :)

**Comment by ibhagwan** [comment]
Beautiful work @tarunsharma20, don't hesitate to reopen if you have any other questions.

If you need more customizations keep an eye open on the Wiki https://github.com/ibhagwan/fzf-lua/wiki/Advanced, I keep adding stuff to it, note that if you wish to try the `fzf_phony` API you currently need to use the [`develop`](https://github.com/ibhagwan/fzf-lua/tree/develop) branch.

**Comment by nyngwang** [comment]
Why I got the first item empty?

<img src="https://user-images.githubusercontent.com/24765272/193571376-a08fdb78-6669-42e3-9717-f24db3d06ba0.png" width="600">
