### ISSUE TITLE
[Bug report] Preview window is small regardless of `preview_horizontal`

### ISSUE THREAD

**Issue by kohane27** [ibhagwan/fzf-lua#463]
Hello there. Hope you're doing well.

Thank you for creating this plugin; it makes finding files a breeze.

## Description

This gif is produced from not setting anything at all:

https://user-images.githubusercontent.com/57322459/176359915-7d6e01ab-bae5-4fc7-a579-e8510f9cdb9e.mp4

As you can see, the result window is big but the preview window is small.

At the status line is `37 121` which is from `:lua print(vim.o.lines, vim.o.columns)`.

Below is produced from setting `preview` to `horizontal = "left:80%"`:

![screenshot-2022-06-29-13-14-28](https://user-images.githubusercontent.com/57322459/176359957-beeabf84-6ee0-40fa-940b-027bf6ae2408.png)

No matter how I tweak the percentage value, it seems the result window takes up the same amount space (which is way too big).

I looked into a similar issue: [The position of the preview window is wrong when using latest neovim nightly](https://github.com/ibhagwan/fzf-lua/issues/132). But I'm on `v0.7.0`.

## Not reproducible with minimal init

```
nvim -u <((echo "lua << EOF") && (curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/minimal_init.lua) && (echo "EOF"))
```

![screenshot-2022-06-29-13-32-13](https://user-images.githubusercontent.com/57322459/176359982-5f8adbea-ecab-43e7-8807-dd4f40393168.png)

## Info

Operating System: Linux
Shell: zsh
Terminal: Kitty
`nvim --version`: NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3
`fzf --version`: 0.30.0 (tarball)

Any input is much appreciated. Thank you:)

**Comment by kohane27** [comment]
Solution: It's a conflict with [beauwilliams/focus.nvim](https://github.com/beauwilliams/focus.nvim). The solution is already in [Issue #325](https://github.com/ibhagwan/fzf-lua/issues/325). Thank you again!

**Comment by ibhagwan** [comment]
> Solution: It's a conflict with [beauwilliams/focus.nvim](https://github.com/beauwilliams/focus.nvim). The solution is already in [Issue #325](https://github.com/ibhagwan/fzf-lua/issues/325). Thank you again!

I was just going to reply and ask if you tested with `minimal_init.lua` but you were quite fast :-)

Saved me loads of time as I totally forgot about #325.

**Comment by kohane27** [comment]
@ibhagwan 

Thank you for such a quick reply.

When I realized it's not reproducible with minimal init, I know it's something wrong from my end.

Hopefully this issue helps others too (given it has more relevant keywords).

> Saved me loads of time as I totally forgot about #325.

Just doing my part to be a responsible citizen of our open-source community. Thank you again. I'm really really enjoying `fzf-lua`:)

**Comment by ibhagwan** [comment]
Ty for the kind words @kohane27! Appreciate your diligence on this issue, definitely not the easiest to find :)

I just committed a pretty massive update so don’t hesitate to open an issue for even the most obscure issues.
