### ISSUE TITLE
live_grep: search in specified directory, search in specified file extensions only

### ISSUE THREAD

**Issue by pure-bliss** [ibhagwan/fzf-lua#465]
I have been recently trying to move from fzf.vim, and I have some trouble making some custom functions work. With fzf.vim I have been using the following functions:

```
" this only returns a command line argument for ag, to use .gitignore if present
function! GetIgnoreStringForAg()
  if filereadable('./.gitignore')
      return '--path-to-ignore ./.gitignore'
  endif

  return ''
endfunction

function! AgDirFn(filepath)
  let ignorestring = GetIgnoreStringForAg()
  call fzf#vim#ag_raw(ignorestring . ' "^(?=.)" ./' . a:filepath, fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}))
endfunction

function! AgFilesFn(files)
  let ignorestring = GetIgnoreStringForAg()
  call fzf#vim#ag_raw(ignorestring . ' -G ' . a:files . ' "^(?=.)" ', fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}))
endfunction
```

I wrote these myself, so sorry for the naming.

 * `AgDirFn` is for searching in specific directories only, like `:AgDir backend/`. Similar to `:FzfLua files cwd=~/`, but this acts like 'grep_project', and searches among the contents of files in 'backend/' for example.

 * `AgFilesFn`is for searching specific types of files. I used it like `:AgFiles .tsx`. It might be used to search files matching the pattern, but I mainly used it to match file extensions.

Is such behavior possible with fzf.lua? If so, where should I start reading / looking? I saw that there is a 'Question' tag, so I hope its okay to ask this here. Thanks!

**Comment by ibhagwan** [comment]
First let me recommend you start familiarizing yourself with lua and gearing more towards lua functions, that also helps me help you as I am not proficient in vimscript, at the current state lua can do pretty much everything for you inside neovim.

`AgDir` can be just an alias to `:FzfLua grep_proect cwd=<folder>` or the lua version `:lua require'fzf-lua'.grep_project({ cwd = "<folder>" })`:
```lua
-- delimiter is ':' by default
:command! -nargs=1 AgDir lua require'fzf-lua'.grep_project({ cwd=<q-args>, fzf_opts={ ["--nth"]="4" } })
-- you can then call it exactly as you described
:AgDir backend
```

As for limiting to specific globs you can do so in a couple of different ways, first if you `rg` installed and enable `rg_glob` (under `grep` options) you can send glob separator to any `grep` operation, for example you can run:
```lua
-- anything past the ` --` separator is then translated to `--iglob=` argument
:lua require'fzf-lua'.grep({ search="foo -- *.lua" })
```
Note that you can then press `<C-g>` to switch to `live_grep` and edit the search string and then press `<C-g>` again to return to fuzzy matching.

If you're using `ag` or wish to further customize how the glob argument is parsed you can supply your own `rg_glob_fn` as  explained in #373.

Using this approach your custom command should be
```lua
-- here we need to use <args> to avoid the surrounding quotes
:command! -nargs=1 AgFiles lua require'fzf-lua'.grep({ search=" -- <args>", fzf_opts={ ["--nth"]="4" } })
-- And call the function like this
:AgFiles *.lua
```

**Comment by pure-bliss** [comment]
> `AgDir` can be just an alias to `:FzfLua grep_proect cwd=<folder>` or the lua version `:lua require'fzf-lua'.grep_project({ cwd = "<folder>" })`:

Oh nice, so `cwd` works with `grep_project` too. I tried it before, but I must have configured something incorrectly, and the second paremeter for `AgDir` did not get through. My bad, and its awesome that it has `cwd` option. Thanks!

For the file extension part... It seems like I'm having issues with the `<C-g>` map. I can't really explain, so here is a short video of it:

https://user-images.githubusercontent.com/83361786/176941778-fd144e12-b3a0-4d8c-8fc8-b7ee8423042f.mp4

I'm sure that showing the keys I pressed during the video would be good, but I didn't find any fast solution for that. Here are some things that happened in the video:

 * At first I tried the command you mentioned, but for some reason it didn't work, I need a bit of time to investigate how it should work.
 * The interesting part happens at aroud 00:13, I press `<C-g>`. For some reason the search input and result window gets popped to the buffer in the back, and goes fullscreen.
 * After searching for `Test`, I press enter on the first result. Vim exits.
 * Then opening `grep_project`, and switching to live grep makes it enter in a weird state, where most of the keys don't work, and `<C-c>` exits vim completely.

I'll have to investigate what causes this. I don't have `<C-g>` mapped to anything else, and I tried to remap it to `<C-e>`, but had the same results. Maybe there is some conflict with my settings, or plugins, even though I don't have an extreme amount of them.

Meanwhile I'll try to experiment with the settings, and see if I'll find anything

**Comment by ibhagwan** [comment]
> For the file extension part... It seems like I'm having issues with the `<C-g>` map. I can't really explain, so here is a short video of it:

Ty for the video @pure-bliss, this doesn’t look right, let’s try to bisect the issue one step at a time:

- Open files write some query at the prompt and run `:FzfLua resume`:  does it work properly? Does it also restore the query prompt correctly?
- Repeat same resume test with `:FzfLua live_grep` - any difference?

Now let’s emulate  `<C-g>`:
- run `:FzfLua grep search=test`
- run `:FzfLua grep_last` - does this work properly?
- run `:FzfLua live_grep resume=true` - does it resume the original query?
- edit the query and run `:FzfLua grep resume=true` - does it open correctly with the search string in the header?


In addition, if you can post (or link) your config I can try to reproduce it on my end, it might be some plugin with an autocmd messing up the resume operation.

**Comment by ibhagwan** [comment]
At second look into the video, the command does what it’s supposed to do switching between the modes but the windows get messed up, from that split moment on all bets are off and when you `<C-c>` fzf-lua closes its own window which is your main neovim window so it quits.

I suspect this is a config issue (probably a conflict with another plugin’s autocmd), can you try with `minimal-init.lua` provided with this plugin?

You can do so in one command:
```
nvim -u <((echo "lua << EOF") && (curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/minimal_init.lua) && (echo "EOF"))
```

**Comment by pure-bliss** [comment]
Yes, I have just figured out, that If I comment out these 2 lines from my init.vim, then everything works as it should: 

```
autocmd TermClose * :q " close terminal on shell exit without having to press any key ('Process exited ....')
autocmd Syntax * normal zR " open all folds
```

Adding this to `minimal-init.lua` reproduces the issue:

```
vim.cmd([[
autocmd TermClose * :q
autocmd Syntax * normal zR
]])
```

If I have `autocmd Syntax * normal zR` set then pressing `<C-g>` a few time causes the prompt to close with `Process exited ...` text.

I'll have to figure out some other solution to achieve what I did with those autocmds, and will still need to experiment to make that file extension based filtering.

**Comment by ibhagwan** [comment]
>I'll have to figure out some other solution to achieve what I did with those autocmds, and will still need to experiment to make that file extension based filtering.

The usual route with other similar issues is an exclusion for `fzf` filetype (fzf-lua sets the terminal filetype to `fzf`), I didn't test this and I'm rough on vimscript but something like (I'm not sure if it needs `&ft` or `ft` is eough...):
```lua
vim.cmd([[
autocmd TermClose * if &ft!="fzf" | :q | endif
autocmd Syntax * if &ft!="fzf" | normal zR | endif
]])
```

**Comment by pure-bliss** [comment]
Yes, this works, seems like this was the issue with the `<C-g>` . Also thanks for the other code snippets, they were very useful!
