### ISSUE TITLE
Cannot jump to correct position from the selected list of `lines` or `blines` results

### ISSUE THREAD

**Issue by 7c78** [ibhagwan/fzf-lua#466]
### Info

- Operating System: 20.04
- Shell: bash
- Terminal: default
- `nvim --version`:  0.7.0
- `fzf --version`: 0.30.0

### Description

I do a search by `lines` or `blines`. Then I select some lines by using `tab` key. The selected lines only have filename without their folder. As its cause, I cannot jump to the correct line.

**Comment by ibhagwan** [comment]
Ty for the report @7c78, I messed it up as part of the API refactor commit, https://github.com/ibhagwan/fzf-lua/commit/786d06bc51de2dba9ccf5b80571ad03c65080f80 - this should fix it.
