### ISSUE TITLE
[Feature Request] Jump to exact column

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#469]
When using `live_grep` and searching for something, I expect the cursor to land on the exact location of the match - it seems redundant to have to search for something, be put at the beginning of the line, then seek for it again.

I'm not surprised if I configured something wrong. Let me know.

**Comment by ibhagwan** [comment]
Do you mean when pressing enter on a selection? It should go to the exact line and column, if it’s not then something is wrong.

**Comment by barrett-ruth** [comment]
Had a custom `rg_opts` and didn't include `--column`

**Comment by ibhagwan** [comment]
> Had a custom `rg_opts` and didn't include `--column`

Yap that’s def not gonna work without a column number, good find.
