### ISSUE TITLE
[Question] Diagnostic Padding

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#470]
To be short, I have the following config:
```vim
sign define DiagnosticSignError text=>
```

I call `FzfLua lsp_workspace_diagnostics`, and there is an extra space (a total of two, I know there should always be one) between the diagnostic sign and the diagnostic message despite the definition above.

However, this makes sense because after calling `vim.fn.sign_getdefined('DiagnosticSignError')`, the following table is returned:

```lua
{ {
    name = "DiagnosticSignError",
    text = "> ",
    texthl = "DiagnosticError"
  } }
```

As you can see neovim just decides to add an extra space in the text field, I guess for rendering a neat signcolumn.

So, 
1. Does this happen to you as well?
2. If so, I think you could just hard code the removal of the space - it's not like neovim is ever going to change that.

**Comment by ibhagwan** [comment]
> 1. Does this happen to you as well?

Yes

> 2. If so, I think you could just hard code the removal of the space - it's not like neovim is ever going to change that.

https://github.com/ibhagwan/fzf-lua/commit/248efd1ffc3cb32edfe3896cf175a2e33c715252 - wrapped in `vim.trim`.

**Comment by barrett-ruth** [comment]
Last annoying nitpick: 

[here](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/diagnostic.lua#L173) you add two nbsp - `files`, `grep`, `man_pages`, etc all have one nbsp.

**Comment by ibhagwan** [comment]
That's because the usual suspects for diag icons are quite wide.

Current:
![image](https://user-images.githubusercontent.com/59988195/177922672-5b130fcb-8af7-4ef8-a5ca-55d03bdf6d3f.png)

One space:
![image](https://user-images.githubusercontent.com/59988195/177922564-520089c0-aa7c-4674-a802-7daf4bf86dc2.png)

I think I'll add this as a separate setting `sign_padding` so you can control yourself if you wish to have 0 padding or more.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/ee19eda2e3b2c7e627c94e0daf9c93ab17027ab1 - should work the way you want now, new setting `diagnostic.icon_padding`, default adds no padding so you shouldn't need to define it in your case.
