### ISSUE TITLE
Help with custom command, opening file from branch using fugitive `Gvsplit`

### ISSUE THREAD

**Issue by ibhagwan** [ibhagwan/fzf-lua#471]
Context: https://www.reddit.com/r/neovim/comments/vu7v92/custom_complete_for_nvim_create_user_command/

@pure-bliss, let me know if you need more help with this.

> **Notes:**
>   - For file type entries I prefer using `files` to `fzf_exec`, you get the benefit of multiprocessing (running the command in an external process) as wel as automatic entry processing (icons, relative paths, shortening paths, etc) so you can also skip calling `fn_transform` and `make_entry.file` since these will be done automatically for you
>   - With `files` we also get the automatic previewer and action configurations, that's why I disabled both `default` and `ctrl-s` actions, assuming OP doesn't need/want those
>   - When using file icons (either through `files` or `fn_transform`) the `selected` array will now contain entries with icons which must be stripped with `path.entry_to_file` before being sent to to the fugitive command
>  - During development, I highly recommend using `vim.pretty_print` at strategic locations so you can inspect the contents of ceratain objects, use ':messages' to inspect the output of objects containing more than one line

```lua
vim.api.nvim_create_user_command(
  'ListFilesFromBranch',
  function(opts)
    require 'fzf-lua'.files({
      cmd = "git ls-tree -r --name-only " .. opts.args,
      prompt = opts.args .. "> ",
      actions = {
        ['default'] = false,
        ['ctrl-s'] = false,
        ['ctrl-v'] = function(selected, o)
          -- use vim.pretty_print to see what's inside objects:
          -- vim.pretty_print(selected)
          local file = require'fzf-lua'.path.entry_to_file(selected[1], o)
          local cmd = string.format("Gvsplit %s:%s", opts.args, file.path)
          print("running:", cmd)
          vim.cmd(cmd)
          vim.cmd("windo diffthis")
        end
      },
    })
  end,
  {
    nargs = 1,
    force = true,
    complete = function()
      local branches = vim.fn.systemlist("git branch --all --sort=-committerdate")
      if vim.v.shell_error == 0 then
        return vim.tbl_map(function(x)
          return x:match("[^%s%*]+"):gsub("^remotes/", "")
        end, branches)
      end
    end,
  })
```

**Comment by pure-bliss** [comment]
Many thanks for the help :) This is just what I was trying to achieve. Will only have time on Monday to put it to a use, but was able to play it with a bit.

The only minor issue I found is that I think the preview window doesn't show the correct content of the file on the branch given, it shows the version which is on the current branch. Furthermore preview won't load for files that only exists on the inspected branch. I think I'll have to further investigate the wiki (https://github.com/ibhagwan/fzf-lua/wiki/Advanced#preview-overview) in attempt to make it work, but in my use case I'm sure I won't need the preview window, so its not a problem at all, and will probably disable it.

Thanks again for the help, and the awesome plugin!

**Comment by pure-bliss** [comment]
Yes, this is perfect! I over complicated, and thought about making it work with with the built in previewer, so treesitter and everything works, but this is just as good :) Thanks again :)

**Comment by ibhagwan** [comment]
> Yes, this is perfect! I over complicated, and thought about making it work with with the built in previewer, so treesitter and everything works, but this is just as good :) Thanks again :)

It’s possible, but as you mentioned would complicate things a bit, especially since the builtin previewer API wasn’t reworked yet and isn’t not as straight forward as the Fzf preview.

I do however think there may be an improvement here that would be even better: what if instead of using `git show` you use `git diff --color=always  <branch> HEAD -- <file>` or better yet it `git diff <branch> HEAD -- <file> | delta`, this way you can see the diff in the preview and don’t even have to press `ctrl-v` unless you’re interested in this specific change?

**Comment by ibhagwan** [comment]
I just tested this myself, it's actually quite lovely to explore changes in files from a specific branch (vs `HEAD`) like this, `delta` makes it extra nice:

```lua
vim.api.nvim_create_user_command(
  'ListFilesFromBranch',
  function(opts)
    require 'fzf-lua'.files({
      cmd = "git ls-tree -r --name-only " .. opts.args,
      prompt = opts.args .. "> ",
      actions = {
        ['default'] = false,
        ['ctrl-s'] = false,
        ['ctrl-v'] = function(selected, o)
          local file = require'fzf-lua'.path.entry_to_file(selected[1], o)
          local cmd = string.format("Gvsplit %s:%s", opts.args, file.path)
          vim.cmd(cmd)
        end,
      },
      previewer = false,
      preview = require'fzf-lua'.shell.raw_preview_action_cmd(function(items)
        local file = require'fzf-lua'.path.entry_to_file(items[1])
        return string.format("git diff %s HEAD -- %s | delta", opts.args, file.path)
      end)
    })
  end,
  {
    nargs = 1,
    force = true,
    complete = function()
      local branches = vim.fn.systemlist("git branch --all --sort=-committerdate")
      if vim.v.shell_error == 0 then
        return vim.tbl_map(function(x)
          return x:match("[^%s%*]+"):gsub("^remotes/", "")
        end, branches)
      end
    end,
  })
```

**Comment by ibhagwan** [comment]
Added to the Wiki as the first advanced user example:

https://github.com/ibhagwan/fzf-lua/wiki/Advanced#branch-files

**Comment by pure-bliss** [comment]
Nice, I hope other finds this useful too :) I think what the preview shows is a personal preference, and fortunately can be changed easily. I'll have to use it for a bit to see which preview suits me the most. But its really good, that we can change the content of the preview easily!

**Comment by ibhagwan** [comment]
Closing this, let me know if you ever need more help.
