### ISSUE TITLE
Avoid center of cursor line after confirm action on file entry

### ISSUE THREAD

**Issue by tobiwild** [ibhagwan/fzf-lua#472]
I like to use `FzfLua oldfiles` to quickly jump between the recently opened files. It seems that on every FZF confirm `zz` is being executed to center the cursor line. This means my view is changing all the time. I would expect the confirm action to work like using `:edit` only.
But I would also be fine to use a custom action in my configuration 😄

**Comment by ibhagwan** [comment]
How about a `no_action_zz` option?

**Comment by ibhagwan** [comment]
Update to https://github.com/ibhagwan/fzf-lua/commit/af60eb72af920d0c6524162374f60569f8f6db54

You can either `:FzfLua quickfix no_action_zz=true` or if you wish for the setting to be permanent:
```lua
require'fzf-lua'.setup {
  quickfix = { no_action_zz = true }
}
```

**Comment by nyngwang** [comment]
@ibhagwan I assume this option can also be added to `setup.files`, `setup.grep`, etc?

**Comment by ibhagwan** [comment]
> @ibhagwan I assume this option can also be added to `setup.files`, `setup.grep`, etc? If so, is it possible to have one option to make this the default behavior?

Yes, you can put it anywhere you want, as for another option to make it the default I would prefer not to add that, there is already a ton of options (some undocumented) and it just creates more mess, unless it’s a super common request (which this one isn’t) I avoid adding new options.
