### ISSUE TITLE
commit 236b305a adds odd white border

### ISSUE THREAD

**Issue by acro5piano** [ibhagwan/fzf-lua#473]
Hi, thank you for the great library as always.

### Info

- Operating System: Arch Linux with i3
- Shell: Fish
- Terminal: Alacritty
- `nvim --version`: NVIM v0.7.2
- `fzf --version`: 0.30.0 (tarball)

- [ ] The issue is reproducible with `minimal_init.lua`

Sorry, I couldn't run the script.

<details>
<summary>fzf-lua configuration</summary>

```lua
fzf_lua.setup({
	winopts = {
		height = 0.9, -- window height
		width = 0.9, -- window width
	},
	keymap = {
		fzf = {
			-- fzf '--bind=' options
			-- If we have empty table here, fzf-lua respects fzf built-in keymap for c-f and c-b.
		},
	},
	previewers = {
		git_diff = {
			pager = "delta --true-color=never", -- I don't know why, but --true-color=never is needed in nvim + tmux environment
		},
	},
})
```
</details>

### Description 

![image](https://user-images.githubusercontent.com/10719495/178148899-13cd6306-bf4d-47af-8c0f-c504713c8bbe.png)

Please take a look my screenshot above. I can say that commit 236b305a (feat: new FzfLuaXXX highlights, updated README) produced that.

I think this change might affect it and try to fix it, but my current skill is not enough to achieve that. Sorry.

https://github.com/ibhagwan/fzf-lua/commit/236b305a1821c79038ab907d08441ff8e0724818#diff-e7713342cff0f9fcdb22d64f0e3a0d7d6ff9c1d468778610f201f65cf738f51c

```
require("packer").startup(function(use)
	use({ "ibhagwan/fzf-lua", commit = "236b305a1821c79038ab907d08441ff8e0724818" }) -- adds the white border
	-- use({ "ibhagwan/fzf-lua", commit = "989674058e1645bac149606237bbe6156d0ddeec" }) -- work as expected
end)
```

**Comment by ibhagwan** [comment]
The default border changed to  the `FloatBorder` highlight, this is probably what is set by your color scheme, you can run `:FzfLua highlights` and search for it.

You have a few  ways to fix it, either link the highlight to `Normal` (can do this in your init.vim or init.lua:
Vimscript:
```vim
:hi! link FzfLuaBorder Normal
```
Lua:
```lua
:lua vim.api.nvim_set_hl('FzfLuaBorder', { link = Normal })
```

if you prefer you can also set it via `setup`:
```lua

require('fzf-lua').setup{
  winopts = {
    hl = { border = "Normal", }
  }
}
```

**Comment by acro5piano** [comment]
@ibhagwan Thank you for your quick and kind response. All of your solutions works like a charm. You're genius, I appreciate your support as always!

**Comment by ibhagwan** [comment]
Ty for the kind words @acro5piano!

Actually it was an oversight on my end, I shouldn’t have changed the default border highlight after so long, https://github.com/ibhagwan/fzf-lua/commit/95c859b4e4d90bd275bc4ba70da6b1e04118cec1 - this restored it to 'Normal' so you can skip the fix if you wish :)

**Comment by acro5piano** [comment]
Okay, I'm looking forward to the next update! For the time being, I'll use `hl = { border = "Normal" }` as the current workaround.

**Comment by ibhagwan** [comment]
> Okay, I'm looking forward to the next update! For the time being, I'll use `hl = { border = "Normal" }` as the current workaround.

Commit was already pushed so you can update if you wish.

**Comment by acro5piano** [comment]
Thanks!!
