### ISSUE TITLE
Save last line position for `resume`

### ISSUE THREAD

**Issue by krady21** [ibhagwan/fzf-lua#474]
It would be nice if the `resume` command would also save and restore the cursor position, not just replay the previous results. This would help in situations where the last fzf command has a long list of suggestions.

**Comment by ibhagwan** [comment]
> It would be nice if the `resume` command would also save and restore the cursor position, not just replay the previous results. This would help in situations where the last fzf command has a long list of suggestions.

I explored it in the past, fzf is an external terminal program which doesn’t have functionality to help with this issue, on top of that results not always come in the same order (for example `rg` multi-threading) so even if I restore the cursor to the same line you’re not guaranteed to land at the same spot so unfortunately the solution would be not only hacky (sending scroll keys to the term) but also incomplete.
