### ISSUE TITLE
subcommand indexing or "fzf.vim & fzf-lua difference"

### ISSUE THREAD

**Issue by RomanYakovenko** [ibhagwan/fzf-lua#475]
Hello. I am a long time user of fzf.vim plug-in. Recently, I discovered this plug-in and decided to try. 

I use "\\" to find the correct command. It is much faster for me.
map <leader><leader> :FzfLua commands <cr>

fzf.vim introduced all commands on the "top" level, so I can easily find "BTags" or BLines", for example. 

fzf-lua implements all commands as the FzfLua arguments, thus they are not listed in the total list of commands. 

I do like fzf-lua decision, after all it is much easier to see all the commands it handles, but since my typing skills are not great, it takes me much longer to get to the right command.

Is it possible to list all second level commands in the "commands" list? I mean without forcing me to create aliases? 

Thank you.

**Comment by ibhagwan** [comment]
Try `:FzfLua builtin`, you’ll get a list of all the commands inside fzf so you can fuzzy search them.

If that doesn’t meet your needs you can always create copies of the commands with any name you want using `:command!`.

**Comment by mcchrish** [comment]
`cnoreabbrev` can also be an alternative.

**Comment by RomanYakovenko** [comment]
Thank you very much. I understand those options. I hoped to find solution that will not force me to define "shortcuts". fzf-lua is not the only plug-in that use such technique.

**Comment by ibhagwan** [comment]
> Thank you very much. I understand those options. I hoped to find solution that will not force me to define "shortcuts". fzf-lua is not the only plug-in that use such technique.

We’ll it’s either you define it or I have to define it for everyone which then becomes another configuration option, given that most are ok with the current approach I think we can live with it :)

**Comment by RomanYakovenko** [comment]
Once again - thank you.
