### ISSUE TITLE
[Feature request] Git diff action

### ISSUE THREAD

**Issue by sseneca** [ibhagwan/fzf-lua#476]
Inspired by [this](https://reddit.com/r/neovim/comments/vfb6me/i_once_said_that_neovims_fold_is_ugly_and_lagging/) post, where the user calls fzf.vim's BCommits and then presses enter on the commit, which then opens it as a diff. A new action (maybe `actions.git_diff`) that is the default for `bcommits` instead of `actions.git_buf_edit` I think would be pretty cool.

**Comment by ibhagwan** [comment]
Doesn’t need a feature request, why don’t you do this (I have a similar mapping):

```lua
git = {
  bcommits = {
    actions = {
      ["ctrl-v"] = function(…)
        require'fzf-lua'.actions.git_buf_vsplit(…)
        vim.cmd("windo diffthis")
      end
    }
  }
}
```

**Comment by sseneca** [comment]
This works very well, thank you :)
