### ISSUE TITLE
Remove Hint to Switch Search when `live_grep_native`

### ISSUE THREAD

**Issue by riazufila** [ibhagwan/fzf-lua#479]
![image](https://user-images.githubusercontent.com/46749569/179462988-e69846e3-2bee-4c8d-80ca-a561fbb3c8e8.png)

When running the command `live_grep_native`, how can I clear the line above it `:: <ctrl-g> to Fuzzy Search`?

**Comment by riazufila** [comment]
```
require("fzf-lua").setup({
	grep = {
		actions = {
			["ctrl-g"] = false,
		},
	}
})
```
Solved with this.

**Comment by ibhagwan** [comment]
With this you disabled the switch from fuzzy to live grep, you can hide the interactive header without disabling the action with `no_header_i = true`.
