### ISSUE TITLE
`--rotate-to=` is only in newest versions of git

### ISSUE THREAD

**Issue by jdrouhard** [ibhagwan/fzf-lua#48]
As the title states, `--rotate-to=` is only in git 2.31 and newer. I get the following when using preview with the "git_bcommits" provider:

> fatal: unrecognized argument: --rotate-to=

Most distributions (and macOS) aren't shipping git 2.31 yet. It might be good to either check the git version, or use a fallback or a different mechanism if the git diff command fails in the git bcommits provider.

**Comment by ibhagwan** [comment]
I had no idea, thanks for letting me know, do you know if there’s an alternative?

I’ll certainly add a check for git version before adding it to the `bcommits` preview command.

**Comment by ibhagwan** [comment]
Should be fixed in the latest commit.
