### ISSUE TITLE
How to enable fuzzy search in `live_grep` by default?

### ISSUE THREAD

**Issue by billyvg** [ibhagwan/fzf-lua#482]
### Description 

I'm trying to use `live_grep` / `live_grep_native` and I see that you can press ctrl-g to enable fuzzy searching. How can I use `live_grep` with the fuzzy search enabled by default?

**Comment by ibhagwan** [comment]
Use `grep` or `grep_project` instead, `live_grep` is by definition no fuzzy search:

https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep

**Comment by billyvg** [comment]
🤦‍♂️ - Thanks, I only looked through the "Advanced" section for some reason.

**Comment by nyngwang** [comment]
I really love the wiki of fzf-lua, as it now helps me review some details that I once asked and got answered but I unfortunately had forgot. I (almost) can imagine it could become a book explaining how to facilitate this great plugin. Awesome :)

**Comment by ibhagwan** [comment]
> > Use grep or grep_project instead, live_grep is by definition no fuzzy search:
> > https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep
> 
> I really love the wiki of fzf-lua, as it just helped me review some details that I once asked and got answered but I, unfortunately, had forgotten. I can (almost) imagine it could become a paper book explaining how to facilitate this great plugin. Probably some animal could be the model of the front-cover.
> 
> In short: Awesome wiki :)

It’s been mostly me updating the Wiki but it’s important to note it’s open to public editing so free free to ad shout own stuff :)
