### ISSUE TITLE
open in tabs > use emtpy default buffer if it's the only one

### ISSUE THREAD

**Issue by abenz1267** [ibhagwan/fzf-lua#483]
Hi,

this is just a very small nit-pick / suggestion:

"often times" i start nvim, open the "old files" fzf-search and open a few files, mark them and then open them in tabs. This always leaves me with the default no-name empty buffer. I'd be nice if it wouldn't.

Any thoughts on this? Maybe should be configurable?

Regards

**Comment by ibhagwan** [comment]
How about (you can also set this action globally via `actions.files`):
```lua
  require'fzf-lua'.files({
    actions = {
      ['ctrl-t'] = function(selected, opts)
        local buflist = vim.api.nvim_list_bufs()
        if #buflist == 1 and #vim.api.nvim_buf_get_name(buflist[1])==0 then
          local first = { table.remove(selected, 1) }
          require'fzf-lua'.actions.file_edit(first, opts)
          require'fzf-lua'.actions.file_tabedit(selected, opts)
        else
          require'fzf-lua'.actions.file_tabedit(selected, opts)
        end
      end
    }
  })
```

**Comment by ibhagwan** [comment]
@abenz1267, closing for now, let me know if you need more help.
