### ISSUE TITLE
Ignore dir / files (using gitignore?)

### ISSUE THREAD

**Issue by tmnvanderberg** [ibhagwan/fzf-lua#486]
Hi and thanks for your plugin :).

Is there some way to ignore a directory when using :FzfLua files? For example fzf.vim offers exclusion based on gitignore. 

kind regards, Timon

**Comment by Jlll1** [comment]
`FzfLua files` does use `.gitignore` to ignore files, at least it does for me. There's also `FzfLua git_files` you could try out, but it lists out all files in the repository, without regard for your current directory.

**Comment by tmnvanderberg** [comment]
Weird, it doesn't seem to work for me. Are you using any settings to enable it?

**Comment by ibhagwan** [comment]
> Weird, it doesn't seem to work for me. Are you using any settings to enable it?

No specific setting required but you can override whatever you want, take a look at all the default `files` options in the README, it used `fd` if found, then `rg` and lastly `find`, whatever comes back from the command is what you’ll see in the interface, test what works best for you in the shell and then you can set the `cmd` argument, for example:

```lua
lua require'fzf-lua'.files({ cmd = "rg --color=never --files --hidden --follow -g '!.git'" })
```

**Comment by tmnvanderberg** [comment]
Installing rg fixed my issue, so I suspect the git filtering might be broken for find (?). If you want I can confirm that and provide more details.

**Comment by tmnvanderberg** [comment]
Thanks for the help guys! :+1:

**Comment by tmnvanderberg** [comment]
Closing this for now :)

**Comment by ibhagwan** [comment]
Default find command is `find -type f -not -path '*/\.git/*' -printf '%P\n'` but it does require GNU find so that might have been the issue, in any even having `rg` installed is recommended and also much better integrated with the different `grep` providers (better performance, glob support, etc).

**Comment by ibhagwan** [comment]
> edit: there was a syntax error in my gitignore, that's probably the cause (?)

Not sure if that was the issue as `find` doesn’t check gitignore at all, the default find command ignores the git folder **not gitignore**, this functionality isn’t supported by find.

**Comment by tmnvanderberg** [comment]
Thanks, that makes sense.
