### ISSUE TITLE
Question: Map Keys to registers() functionality

### ISSUE THREAD

**Issue by prashanth-hegde** [ibhagwan/fzf-lua#487]
### Info

- Operating System: Mac OSX Monterey 12.4
- Shell: `fish`
- Terminal: `alacritty`
- `nvim --version`: `0.7.2` 
- `fzf --version`: `0.30.0` 

### General question:
Thanks for this wonderful plugin. This is so cool! FZF is a tool I can't live without, and `fzf-lua` takes it to the next level!
I have a general question about setting up fzf lua to use registers

### Description 
So, we have `:registers` and fzf-lua provides a convenience function `lua require('fzf-lua').registers()` to open up a window to browse registers. So far, so good.. 
At this point, I would like to scroll using the arrow keys, and bind `<C-P>` or `<M-P>` to paste the selection using `vim.api.nvim_paste()` or `vim.api.nvim_put()`. 
I could't find any documentation that explains how to setup keys for a given function? Is it possible to do that? I tried a few permutations with `require'fzf-lua'.actions` to no avail. Any help/guidance is appreciated. 

Thank you in advance!

**Comment by ibhagwan** [comment]
Ty for the kind words @prashanth-hegde!

There aren’t many builtin actions for registers but it’s easy to build one yourself (can also be added to the `setup` call):

```lua
lua require('fzf-lua').registers({
  actions = {
    -- use fzf keybind notation for actions
    ['ctrl-p'] = function(selected, opts)
      -- selected[1] will contain the selected line, regex parse it to get the register name
      local register = selected[1]:match('%[(.*)%]')
      .. do your paste ..
    end
  }
})
```

**Comment by prashanth-hegde** [comment]
Thank you, 
I believe I had tried this permutation before. Here's the command that I tried specifically, and nothing seemed to happen, which is why I had to reach out. 

```
:lua require('fzf-lua').registers({actions = {['default'] = function(selected, _) print("hello world") end}})
```

**Comment by ibhagwan** [comment]
Just tried your command and I see the print message, did you check inside `:messages`?
Does the same work with `files`?
What version of neovim/fzf are you using and have you tried with `minimal_init.lua` supplied by this project?

**Comment by prashanth-hegde** [comment]
Apologies, I messed it up. Yes, you're right. It's showing up in `:messages`.
For completeness, here's a working function that I am able to get working. Thank you for all the help! Greatly appreciate it! 

```lua
fzflua.registers({
  actions = {
      ['default'] = function(selected, _)
      local register = selected[1]:match('%[(.*)%]')
      local contents = vim.fn.getreg(register)
      vim.api.nvim_paste(contents, true, -1)
      end
  }
})
```

**Comment by ibhagwan** [comment]
Great work @prashanth-hegde :-)
