### ISSUE TITLE
Previewers are not very responsive compared to telescope

### ISSUE THREAD

**Issue by 33kk** [ibhagwan/fzf-lua#488]
### Info

- Operating System: Arch Linux
- Shell: zsh
- Terminal: kitty
- `nvim --version`: NVIM v0.8.0-dev-nightly
- `fzf --version`: 0.31.0 (a0ef898)
- `sk --version`: 0.9.4

- [ ] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup {
	fzf_bin = "sk",
	winopts = {
		preview = {
			-- default = 'bat',
			delay = 0
		}
	}
}
```
</details>

### Description 

fzf-lua previewers have a really noticeable delay, while telescope is basically instant. I tried setting delay to 0, but it doesn't help at all, the delay still feels exactly like it did before with `fzf`. With `sk` it feels more responsive but causes an error: [https://im.pepega.club/r1k1sy.mp4](https://im.pepega.club/r1k1sy.mp4)

**Comment by ibhagwan** [comment]
This is most likely unrelated to fzf-lua, [fzf has an intentional (IMO it’s a good thing) debounce delay of 100ms](https://github.com/junegunn/fzf/issues/2417#issuecomment-809886535), doesn’t matter if you’re using bat previewer or builtin, fzf still needs to fire the command (a `neovim --headless …` shell command) to let fzf-lua know it needs to update the previewer.

Quite honestly I don’t see this as an issue, the preview still opens fast enough without it being spammy, why would anyone need an immediate response from the previewer while holding down arrow?

**Comment by 33kk** [comment]
It's an issue for me because it feels pretty weird to have a huge delay on the previewer while scrolling. I guess I'll try patching fzf to remove the delay

**Comment by 33kk** [comment]
It does remove the delay in terminal, but it's still super slow in nvim

**Comment by ibhagwan** [comment]
> It does remove the delay in terminal, but it's still super slow in nvim, even with the bat previewer somehow? Works perfectly fine with `./fzf --preview "bat --color=always {}"`

Maybe because it still needs to run `neovim --headless` and connect over RPC to the main instance, try with `previewer = 'bat_native'`, does it make any difference?

**Comment by ibhagwan** [comment]
Btw, I'm not sure what went wrong in your setup, maybe it's not getting called properly? here's mine with `delay = 0`, as you can see it's pretty immediete:

![Peek 2022-07-26 14-37](https://user-images.githubusercontent.com/59988195/181116834-87bf20f1-5774-458f-959a-e8cbbaff81d5.gif)

**Comment by 33kk** [comment]
Seems to be called fine :shrug: 
![image](https://user-images.githubusercontent.com/23123008/181117096-d1581a13-23a4-4976-ba0b-1b2b3f78e7c1.png)

**Comment by ibhagwan** [comment]
Does it behave the same with `minimal_init.lua`?

See my updated comment screencast (with delay), the behavior in your video with the default delay is odd, with 100ms delay it shouldn't even attempt to display the preview until the key is released.

**Comment by 33kk** [comment]
With `minimal_init.lua` and `delay=2000`` the delay seems to be about 5s, weird

**Comment by ibhagwan** [comment]
I watched your video again in detail, something is definitely off, it's not supposed to be like that, I also ran mine with `bat` previewer (`winopts.preview.delay` doesn't natter in this case) it's flying for me, this requires a deeper investigation.

**Comment by 33kk** [comment]
I feel like this could be related to me using neovim-git, I'll try downgrading

**Comment by 33kk** [comment]
That was it :thinking:

**Comment by ibhagwan** [comment]
Probably something related to the RPC comms between the instances.

Is it now working as expected with `delay = 0`?

**Comment by 33kk** [comment]
Or not? Still i don't feel any difference between 100 and 0 https://im.pepega.club/fvbhl9.mp4

**Comment by ibhagwan** [comment]
> Or not? Still i don't feel any difference between 100 and 0 https://im.pepega.club/fvbhl9.mp4

Something is still off, this doesn’t seem like 100ms with the default delay.

**Comment by 33kk** [comment]
OHH, right, the `minimal_init.lua` doesn't clear plugins, it's working as expected after i nuked the packer directory, maybe you shouldn't disable `auto_clean` :sweat_smile:

**Comment by ibhagwan** [comment]
> OHH, right, the `minimal_init.lua` doesn't clear plugins, it's working as expected after i nuked the packer directory, maybe you shouldn't disable `auto_clean` 😅 Time to figure out which plugin was slowing it down

Issues that require clearing the plugin directory to solve are extremely rare I’d feel so bad nuking people’s configs :)

I might consider changing the strategy of minimal unit to a temporary download and using `PACKPATH`.

 Keep this thread updated with your findings which plugin caused this?

**Comment by 33kk** [comment]
I feel like it might be a lot of things combined, not sure yet

**Comment by 33kk** [comment]
Can I somehow get the time preview takes to fully render?

**Comment by ibhagwan** [comment]
> Can I somehow get the time preview takes to fully render?

Not without modifying the source

**Comment by ibhagwan** [comment]
Closing since this we discovered this isn’t a bug, feel free to open if you want need my help or want to continue the discussion.
