### ISSUE TITLE
command not found: nvim

### ISSUE THREAD

**Issue by s-taylor** [ibhagwan/fzf-lua#49]
I have installed fzf-lua for the first time, and I am getting an issue where the right pane shows `zsh:1: command not found: nvim`
I have nvim aliased to point to the appimage in my terminal (running Ubuntu 20.04 on WSL) but it seems inside vim/fzf it cannot find the binary?
The file list launches fine though. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/5457267/130025845-4bfe0dea-3c45-42a0-9381-802d5b6f6ad5.png)

**Comment by ibhagwan** [comment]
The issue lies within `nvim-fzf` as it hardcodes the preview action strings as `nvim`, funny enough just today [an  issue was opened about this with nvim-fzf](https://github.com/vijaymarupudi/nvim-fzf/issues/25)

**Comment by s-taylor** [comment]
Ah, thankyou.
