### ISSUE TITLE
can winopts.width be a function?

### ISSUE THREAD

**Issue by haolian9** [ibhagwan/fzf-lua#491]
### Info

- Operating System: archlinux
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: 
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `fzf --version`: 0.30.0 (tarball)

- [x] The issue is reproducible with `minimal_init.lua`

```lua
require('fzf-lua').setup({
    winopts = { width = function() end},
})
```

### Description 

i want to control the winopts.height dynamically, for example, `if vim.o.columns > 150 then 0.6 else 0.9`.

i surely can change it by `require'fzf'.config.globals.winopts.width = my_proper_width_calculator()` just before invoking fzf's ui, but i'm wondering if this can be provided by the plugin itself.

**Comment by haolian9** [comment]
i just realized `VimResized`might be another good approach, i kind of like it

**Comment by ibhagwan** [comment]
You can also use `winopts_fn` as a function that returns a `winopts` table, whatever returns from `winopts_fn` overrides the values inside `winopts`, so in your case:

```lua
require'fzf-lua'.setup {
  winopts_fn = function()
    return { width = my_proper_width_calculator() }
  end
}
```

**Comment by haolian9** [comment]
great to know, thanks!
