### ISSUE TITLE
default action closes windown even when action.resume is especified on the action table for fzf_exec

### ISSUE THREAD

**Issue by henrique-smr** [ibhagwan/fzf-lua#494]
### Info

- Operating System: Fedora 36
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.7.2
- `fzf --version`: 0.30.0

- [ X ] The issue is reproducible with `minimal_init.lua`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
global_resume = true,
global_resume_query = true,
})
```
</details>

### Description 

I'm developing a plugin that uses fzf-lua as a smart picker for building command arguments incrementally.
I have the following function:

```lua
function M.NxFZFListGeneratorOptions(plugin, runner)
	local fzf = require("fzf-lua")

	local opts = {}
	local generator = plugin .. ":" .. runner

	fzf.fzf_exec(core.NxGetGeneratorsOptions(plugin, runner), {
		prompt = "Nx " .. generator .. " > ",
		preview = fzf.shell.raw_preview_action_cmd(function()
			local cmd_preview_str = "npx nx g " .. generator .. " --dryRun" .. utils.parseOpts(opts)
			return "echo '" .. cmd_preview_str .. "' && " .. cmd_preview_str
		end),
		actions = {
			['default'] = {
				function(items)
					local opt = string.gsub(items[1], "=.*", "")
					vim.ui.input({
						prompt = opt .. " "
					}, function(input)
						if input ~= nil or input ~= "" then
							opts[opt] = input
						else
							opts[opt] = nil
						end
					end)
				end,
				fzf.actions.resume
			},
			['ctrl-r'] = function()
				local cmd_str = "npx nx g " .. generator .. utils.parseOpts(opts)
				vim.api.nvim_exec(":split | terminal " .. cmd_str, false)
			end
		},
		fn_transform = function(x)
			local opt = string.gsub(x, "=.*", "")
			if opts[opt] ~= nil then
				opt = opt .. "=" .. opts[opt]
			end
			return opt
		end
	})
end
```
this fuzzy finds me a list of arguments, and when i select one (default action), it prompts me the value i want for that argument. Then it resumes with an updated list of arguments, each one followed by "=" and the value i entered for them.

A month ago it was working just fine, but now when the default action is fired, it closes fzf-lua window, and when it resumes, it takes the current windown i'm working on. Or does nothing if the current buffer is not writable

**Comment by henrique-smr** [comment]
I have found the issue.

I had this autocmd set which was closing the windown:
```lua
vim.cmd [[
 	augroup CloseTerminal
 		autocmd!
 		autocmd TermClose * if !v:event.status | exe 'bdelete! '..expand('<abuf>') | endif
 	augroup end
]]
```

**Comment by ibhagwan** [comment]
Ty for letting me know! Mind sharing a link to your plugin?

**Comment by henrique-smr** [comment]
> Ty for letting me know! Mind sharing a link to your plugin?

Shure! [henrique-smr/nx.nvim](https://github.com/henrique-smr/nx.nvim)

**Comment by ibhagwan** [comment]
> > Ty for letting me know! Mind sharing a link to your plugin?
> 
> Shure! [henrique-smr/nx.nvim](https://github.com/henrique-smr/nx.nvim)

Nice work! :)
