### ISSUE TITLE
Scrolling on preview window when using delta

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/fzf-lua#495]
### Info

- Operating System:
- Shell: Bash
- Terminal: iTerm2
- `nvim --version`: 0.7.2
- `fzf --version`: 0.30.0

### Description 
I couldn't find this issue mentioned elsewhere. Currently, I'm piping my git diff output to delta. The preview for delta does not have scroll option like it normally does. Is there a way to be able to scroll the preview window from delta? I have `preview_pager   = vim.fn.executable("delta")==1 and "delta --width=$FZF_PREVIEW_COLUMNS --line-numbers"` in my config file for commits and bcommits specifically. 

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/22674069/183690646-b712249d-4f04-4eb3-a92c-6381cba43436.png">

There are a lot of changes in the preview window but I can't scroll on that window.

**Comment by ibhagwan** [comment]
The previewer used with git is the fzf native previewer, it’s controlled by fzf in the terminal, it is scrollable using fzf binds that are defined under `keymap.fzf`, the defaults are `shift-{up|down} ` but you can change it to whatever you’d like.

**Comment by hqkhan** [comment]
Got it. Thank you!
