### ISSUE TITLE
Looking for help writing a perforce extension

### ISSUE THREAD

**Issue by kshenoy** [ibhagwan/fzf-lua#497]
### Info

- Operating System: Linux
- Shell: bash
- Terminal: xterm
- `nvim --version`: 0.7.2
- `fzf --version`: 0.29.0

### Description 
We use perforce at work so I'm trying to write some functions similar to the git_files, git_status etc. I looked at providers/git.lua and based my functions on those as well as some in path.lua. This is what I have:

```lua
local core  = require "fzf-lua.core"
local utils = require "fzf-lua.utils"
local config = require "fzf-lua.config"

local M = {}

-- Check if currently in a Perforce repo
M.is_p4_repo = function(opts, noerr)
    local _, err = utils.io_systemlist("p4 info")
    return not (err ~= 0)
end

-- Get the root of the repo
M.get_root = function(opts, noerr)
    local output, err = utils.io_systemlist("p4 info")
    if err ~= 0 then
        if not noerr then utils.info(unpack(output)) end
        return nil
    end
    return utils.strsplit(output[4], ' ')[3]
end

-- Get the files in the repo
M.files = function(opts)
    if not opts then opts = {} end
    opts.cwd = opts.cwd or M.get_root(opts)
    if not opts.cwd then return end
    opts.cmd = opts.cmd or "p4 have " .. opts.cwd .. "/..."
    opts.prompt = opts.prompt or "P4Files> "
    opts.fn_transform = function(x)
        return utils.strsplit(x, ' ')[3]
    end

    -- Set other options from git and override as required
    opts = config.normalize_opts(opts, config.globals.git.files)
    opts.git_icons = false
    local contents = core.mt_cmd_wrapper(opts)
    opts = core.set_header(opts, opts.headers or {"cwd"})
    return core.fzf_exec(contents, opts)
end

-- Get the status
M.status = function(opts)
    if not opts then opts = {} end
    opts.cmd = opts.cmd or "p4 opened"
    opts.cwd = opts.cwd or M.get_root(opts)
    opts.prompt = opts.prompt or "P4Status> "
    opts.fn_transform = function(x)
        local output, err = utils.io_system("p4 where " .. utils.strsplit(x, ' ')[1])
        return utils.strsplit(output, ' ')[3]
    end

    -- Set other options from git and override as required
    opts = config.normalize_opts(opts, config.globals.git.files)
    opts.git_icons = false
    local contents = core.mt_cmd_wrapper(opts)
    opts = core.set_header(opts, opts.headers or {"cwd"})
    return core.fzf_exec(contents, opts)
end

return M
```

I've managed to get `is_p4_repo`, `get_root` and `files` working. However, I'm stuck on the status command.

[`p4 opened`](https://www.perforce.com/manuals/cmdref/Content/CmdRef/p4_opened.html) is the perforce analogue of `git status` and it produces output in the following format:
```
depot-file - actionchnum change (type) [lock-status]
```

depot-file is the path to the file in the central perforce repository and not the actual path to the file in the local system so I run [`p4 where`](https://www.perforce.com/manuals/cmdref/Content/CmdRef/p4_where.html#p4_where). This takes the `depot-file` and prints 3 things - files' locations relative to the top of the depot, relative to the top of the client workspace, and the full path to the file on the local system eg. assuming the perforce repo has been created in /home/user/p4_repo and we've modified a single file called foo at the root of the repo:

```
$ p4 opened -s
//depot/foo.txt - edit default change

$ p4 where //depot/foo.txt
//depot/foo.txt //client/foo.txt /home/user/p4_repo/foo.txt
```
 
I'm using `fn_transform` to split the output of `p4 opened -s` which would be the input to the transform function, split it on whitespace and take the first column and call `p4 where` on it using `utils.io_systemlist`. However, when I do that I get the following error:

```
Error executing luv callback:
...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/utils.lua:626: E5560: vimL function must not be called in a lua loop callback
stack traceback:
        [C]: in function 'system'
        ...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/utils.lua:626: in function 'io_system'
        /home/kshenoy/.config/nvim/lua/fzf-lua/perforce.lua:76: in function 'fn_transform'
        ...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/libuv.lua:176: in function 'process_lines'
        ...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/libuv.lua:213: in function <...vim/site/pack/packer/start/fzf-lua/lua/fzf-lua/libuv.lua:188>
```

I'm not sure what I'm missing here.

**Comment by ibhagwan** [comment]
Fzf-lua uses `libuv` (`vim.loop`) to spawn shell commands, `fn_transform` is then called within the context of the libuv callback, as the message states you cannot call any vimL functions (`io_system` calls `vim.fn.system`) in the callbacks, this is a neovim limitation.

There are many ways to work around this, the first is to use lua IO directly (`io.popen`) instead of `vim.fn` functions by adding `true` as a second call arg (`use_lua_io`):
https://github.com/ibhagwan/fzf-lua/blob/4777dd572aea462695f41342ed8ccbdb15045ae0/lua/fzf-lua/utils.lua#L617-L628

Personally I don’t think this is very efficient as it needs to spawn another shell (running `p4 where`) for each entry which may become an issue if you have a big repo with many changed files, a better way IMHO would be to use `xargs` and `cut` (or `sed|awk|perl`, whichever you prefer) to get a list of files directly from the initial command as the initial command runs in a different process and won’t affect the main neovim process, this is roughly what I would use:
```
p4 opened -s | cut -d' ' -f1 | xargs p4 where
```
You can then use `cut` again to avoid using `fn_transform` if you wish:
```
p4 opened -s | cut -d' ' -f1 | xargs p4 where | cut -d' ' -f3
```

**Comment by kshenoy** [comment]
Thanks! That is the same command that I use on the shell.

**Comment by ibhagwan** [comment]
Closing, if you need more help don’t hesitate to reach out again!

**Comment by kshenoy** [comment]
Hi, is there a good way to get data from 2 sources? eg. in my case there are two places that files can reside. The first is in the perforce controlled repository that I can get at using the `perforce.files` function from above and the other is some dir which I want to run the regular `files` command in.

**Comment by ibhagwan** [comment]
> Hi, is there a good way to get data from 2 sources? eg. in my case there are two places that files can reside. The first is in the perforce controlled repository that I can get at using the `perforce.files` function from above and the other is some dir which I want to run the regular `files` command in.

Take a look at #485, many different approaches for this.
