### ISSUE TITLE
Is it possible to redraw the modal when terminal size changes?

### ISSUE THREAD

**Issue by acro5piano** [ibhagwan/fzf-lua#498]
### Info

- Operating System: Linux
- Shell: Fish
- Terminal: Alacritty
- `nvim --version`: `v0.7.2`
- `fzf --version`: `0.31.0 (a0ef898)`

### Description 

Hi, thank you for this amazing library. Is it possible to redraw the fzf modal on terminal size changed?

My use-case is that:

- Using multiple tmux panes
- I'm running `fzf-tmux` on the left pane
- I run fzf-lua command (like `:lua require("fzf-lua").git_files()` ) to seek around my workspace files
- I maximize the left pane to focus on the content

In that time, I'm very happy if `fzf-lua` redraw the modal so that I can see the result using the whole maximized window. Currently I'm re-running `:lua require("fzf-lua").git_files()` again. I actually map `:lua require("fzf-lua").git_files()` to `<Leader>gf`, so re-running the command is not hard task, but not ideal.

Please take a look for the gif.

![out](https://user-images.githubusercontent.com/10719495/184093569-84f0de80-bbcf-49ca-80eb-76a87748af22.gif)

What do you think? If you agree with me, I would like to try to solve this. 
Thanks!

**Comment by ibhagwan** [comment]
Redrawing isn’t currently implemented, the only workaround is what you’re already doing which is reopening the interface.

I’ve tagged this issue as enhancement and I’ll take a look at this when I have more time.

**Comment by acro5piano** [comment]
@ibhagwan Thank you for the quick reply! I'm looking forward to the enhancement.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/c8d0a0274e9c35473bb67556e292a3f97d0f28fe - adds new command `:FzfLua redraw` to recalculate and redraw the layout when terminal size changes.

Can be used with `VimResized` event to redraw the fzf-lua window automatically, for example, I have the following autocmd:
```lua
vim.api.nvim_create_autocmd("VimResized", {
  pattern = '*',   
  command = 'tabdo wincmd = | lua require("fzf-lua").redraw()'
})
```

I use tmux to create new panes which triggers the `VimResized` event and fzf-lua redraws automatically:
![Peek 2022-08-11 11-11](https://user-images.githubusercontent.com/59988195/184169034-4495ec06-c484-437d-8ba3-3e6426024e9d.gif)

**Comment by acro5piano** [comment]
@ibhagwan I've confirmed the functionality - it works quite well! Thank you very much!!

**Comment by Akianonymus** [comment]
> [c8d0a02](https://github.com/ibhagwan/fzf-lua/commit/c8d0a0274e9c35473bb67556e292a3f97d0f28fe) - adds new command `:FzfLua redraw` to recalculate and redraw the layout when terminal size changes.
> 
> Can be used with `VimResized` event to redraw the fzf-lua window automatically, for example, I have the following autocmd:
> 
> ```lua
> vim.api.nvim_create_autocmd("VimResized", {
>   pattern = '*',   
>   command = 'tabdo wincmd = | lua require("fzf-lua").redraw()'
> })
> ```
> 
> I use tmux to create new panes which triggers the `VimResized` event and fzf-lua redraws automatically: ![Peek 2022-08-11 11-11](https://user-images.githubusercontent.com/59988195/184169034-4495ec06-c484-437d-8ba3-3e6426024e9d.gif) [ ![Peek 2022-08-11 11-11](https://user-images.githubusercontent.com/59988195/184169034-4495ec06-c484-437d-8ba3-3e6426024e9d.gif) ](https://user-images.githubusercontent.com/59988195/184169034-4495ec06-c484-437d-8ba3-3e6426024e9d.gif) [ ](https://user-images.githubusercontent.com/59988195/184169034-4495ec06-c484-437d-8ba3-3e6426024e9d.gif)

The autocmd should be added to the wiki or readme, would be helpful to many people.

**Comment by ibhagwan** [comment]
>The autocmd should be added to the wiki or readme, would be helpful to many people.

Great idea @Akianonymus:
https://github.com/ibhagwan/fzf-lua/wiki#auto-redraw=

**Comment by ibhagwan** [comment]
Please noe this is no longer required since #505, I'll update the wiki accordingly.

**Comment by nyngwang** [comment]
@ibhagwan Wow, I don't even know this feature has been done, and even without any settings! Awesome!
