### ISSUE TITLE
[Question] How to refresh the data without closing current fzf-lua screen?

### ISSUE THREAD

**Issue by deathmaz** [ibhagwan/fzf-lua#499]
Hi, thank you very much for a very useful plugin. I'm trying to make a custom command that would work with https://github.com/ahmedkhalf/project.nvim. What i did currently is this:
```lua
  vim.keymap.set('n', '\\p',
    function()
      local history = require("project_nvim.utils.history")
      local results = history.get_recent_projects()

      fzf_lua.fzf_exec(results, {
        actions = {
          ['default'] = {
            function(selected)
              fzf_lua.files({ cwd = selected[1] })
            end,
          },
          ['ctrl-d'] = {
            function(selected)
              history.delete_project({ value = selected[1] })
            end,
            fzf_lua.actions.resume -- How to rerun everything with refreshed results?
          }
        }
      })
    end,
    opts)
```
I don't understand how to rerun the whole thing without closing the current fzf-lua window with refreshed results. The use case is when i press `ctrl-d` to delete the entry from the history file. This is done via `history.delete_project` function. After the entry was deleted i would like to still see the fzf-lua screen but with refreshed list, which comes from `history.get_recent_projects()` function. Right now i do `fzf_lua.actions.resume` to keep the lua screen opened, but i don't know how to refresh the data inside the list. Could you please help? Thank you very much in advance.

**Comment by ibhagwan** [comment]
Right now your results is a static variable, it gets retrieved only once, when you resume the old history list is still used, it never gets refreshed.

What you want to do is use [contents to a function](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-cont-fnc), that way resume will call the function and refresh the list, something like:

```lua

  vim.keymap.set('n', '\\p',
    function()
      fzf_lua.fzf_exec(function(cb)
        local history = require("project_nvim.utils.history")
        local results = history.get_recent_projects()
        for _, e in ipairs(results) do
          cb(e)
        end
        cb()
      end,
      {
        actions = {
          ['default'] = {
            function(selected)
              fzf_lua.files({ cwd = selected[1] })
            end,
          },
          ['ctrl-d'] = {
            function(selected)
              history.delete_project({ value = selected[1] })
            end,
            fzf_lua.actions.resume -- How to rerun everything with refreshed results?
          }
        }
      })
    end,
    opts)
```

**Comment by deathmaz** [comment]
It worked, just had to move `local history = require("project_nvim.utils.history")` out of the scope of `zf_lua.fzf_exec(function(cb)`
```lua  
vim.keymap.set('n', '\\p',
    function()
      local history = require("project_nvim.utils.history")
      fzf_lua.fzf_exec(function(cb)
        local results = history.get_recent_projects()
        for _, e in ipairs(results) do
          cb(e)
        end
        cb()
      end,
        {
          actions = {
            ['default'] = {
              function(selected)
                fzf_lua.files({ cwd = selected[1] })
              end,
            },
            ['ctrl-d'] = {
              function(selected)
                history.delete_project({ value = selected[1] })
              end,
              fzf_lua.actions.resume
            }
          }
        })
    end,
    opts)
```
Thank you very much for the help and nice plugin!

**Comment by nyngwang** [comment]
@ibhagwan How to use `fzf_lua.fzf_exec` inside `setup.buffers.actions`? Or this is not recommended?

**Comment by towry** [comment]
> > @ibhagwan How to use `fzf_lua.fzf_exec` inside `setup.buffers.actions`? Or this is not recommended?
> 
> No problem, you can call whatever you want from the actions, it will override the existing fzf-lua interface, just make sure to wrap the function inside a table to prevent the “flash” as it tells fzf-lua to reuse the interface rather than close and reopen.

I am trying to bind ['ctrl-m'] = { function() end } in files actions, but when i presss 'ctrl-m', the fzf-window shows process exit 0. (window is not closed).

**Comment by ibhagwan** [comment]
> > > @ibhagwan How to use `fzf_lua.fzf_exec` inside `setup.buffers.actions`? Or this is not recommended?
> > 
> > 
> > No problem, you can call whatever you want from the actions, it will override the existing fzf-lua interface, just make sure to wrap the function inside a table to prevent the “flash” as it tells fzf-lua to reuse the interface rather than close and reopen.
> 
> I am trying to bind ['ctrl-m'] = { function() end } in files actions, but when i presss 'ctrl-m', the fzf-window shows process exit 0. (window is not closed).
> 
> i am trying to integrate flash.nvim.

Remove the `{}` wrapping to tell fzf-lua to close, just do `['ctrl-m'] = function() end`
