### ISSUE TITLE
Unable to disable border / custom border

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#5]
Two things here.

* `win_border = false` does not hide border
* would be nice to be able to provide custom border characters, so table as accepted by `nvim_open_win`

**Comment by ibhagwan** [comment]
> does not hide border

I’ll check, I might have missed it when I refactored the config.

> would be nice to be able to provide custom border characters, so table as accepted by nvim_open_win

This should be really easy to add but I see it’s currently not an option in `nvim-fzf`, as evident in [floating_window.lua](https://github.com/vijaymarupudi/nvim-fzf/blob/master/lua/fzf/floating_window.lua).

We can open an issue for @vijaymarupudi, once he adds that I’ll add the passthrough in my code as well.

**Comment by gegoune** [comment]
I can see that nvim-fzf allows to set border, but that is then passed to fzf, which is not what I am after here. I want to style floating window itself. And no border to be drawn by fzf. @vijaymarupudi, would you be willing to make it configurable?

**Comment by ibhagwan** [comment]
Opened [this issue] for `nvim-fzf`, as for the no border for the fzf window it was a typo in my config parser, just fixed it, once I fix fix the "no devicons crash" issue you opened I'll commit both (shouldn't be long).

**Comment by ibhagwan** [comment]
>win_border = false does not hide border

This should be fixed with the latest commit, I'll leave this issue open until we sort out the borderchars customization as well.

**Comment by gegoune** [comment]
Crazy fast! https://github.com/vijaymarupudi/nvim-fzf/commit/b523a51df9794a3b524a8d07af967e39262e0d7f Thanks @vijaymarupudi!

**Comment by vijaymarupudi** [comment]
You're welcome :)

**Comment by ibhagwan** [comment]
Try now with (order of chars matter):
```
win_border          = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' }
```

Took me some time because I'm still confused what on earth in my code is changing `FloatBorder` highlight after I switch windows, but the issue seems to be in some other part of my config and not this plugin :-)

**Comment by gegoune** [comment]
Perfect, works like a charm!

**Comment by ibhagwan** [comment]
Alright then, closing this issue.

I found my "other" issue, apparently `lsp-signature` sets `hi default FloatBorder guifg = #777777` **only** if `FloatBorder` wasn't previously set, turns out my custom embark colorscheme doesn't set it.

**Comment by gegoune** [comment]
Ah, that's not very nice of it, don't think it should be doing it. It can set up local highlight group for the window.
