### ISSUE TITLE
Grepping with actual regular expressions

### ISSUE THREAD

**Issue by fsouza** [ibhagwan/fzf-lua#50]
Thank you for this great project!

One thing that I'm missing that I had previously was the ability to grep with actual regular expression, instead of an exact string.

Would you take a patch that allows users to invoke grep() with search set to a regular expression? (i.e. support setting no_esc to true [here](https://github.com/ibhagwan/fzf-lua/blob/82a477420d34e6d8611d6b02ba1edb58c6e4ee2b/lua/fzf-lua/providers/grep.lua#L83))

**Comment by fsouza** [comment]
After opening this I realized I can just use raw_cmd x)

**Comment by ibhagwan** [comment]
Good find, I added this recently due to a similar request, I really need to complete this wiki :)
