### ISSUE TITLE
Native previewer scroll not working

### ISSUE THREAD

**Issue by shiradofu** [ibhagwan/fzf-lua#500]
### Info

- Operating System: Mac OS Montery v12.4
- Shell: zsh
- Terminal: wezterm
- `nvim --version`:  v0.7.0
- `fzf --version`: 0.32.0 (brew)

- [x] The issue is reproducible with `minimal_init.lua`

### Description 

When cursor being at the top of the natve preview window, it cannot get scrolled.
This bug seems to be introduced here. https://github.com/ibhagwan/fzf-lua/commit/519dbf067bc54a19f5bd57fa86dedecf13bfb1fe#

#### Details

When the curosr is at the top of the window, the followings are running during the scroll:

- in Previewer.base:scroll()
`^D`
- utils.zz() is called,
`zvzz → L → ``     `
- then comes back to Previewer.base:scroll and run
`vim.api.nvim_win_set_cursor(preview_winid, self.orig_pos)`

And the last `nvim_win_set_cursor` get the cursor back to the first line, and end up preventing the scroll.

### Possible solution

In order to highlight the match line, I think neovim's `sign` feature can be used.
https://neovim.io/doc/user/sign.html

The code below is a very rough implementation example, but on my machine it has worked well.

```diff
function Previewer.buffer_or_file:set_cursor_hl(entry)

  -- ...

  self.orig_pos = api.nvim_win_get_cursor(0)

+  local bufnr = api.nvim_win_get_buf(0)
+  vim.cmd(([[
+    sign unplace * buffer=%d
+    sign define FzfNativePreviewMatchLine linehl=CursorLine
+    sign place %d name=FzfNativePreviewMatchLine line=%d buffer=%d
+  ]]):format(bufnr, math.random(99999), self.orig_pos[1], bufnr))

-  fn.clearmatches()
-
-  if self.win.winopts.__hl.cursor and not (lnum<=1 and col<=1) then
-    fn.matchaddpos(self.win.winopts.__hl.cursor, {{lnum, math.max(1, col)}}, 11)
-  end
  end)
end
```
```diff
 function Previewer.base:gen_winopts()
   local winopts = {
     wrap = self.win.preview_wrap,
+    cursorline = false,
   }
   return vim.tbl_extend("keep", winopts, self.winopts)
 end
```

I don't have much time now and I'm sorry I can't implement this by myself.
I hope this could be a help!

**Comment by ibhagwan** [comment]
Ty @shiradofu for the detailed explanation! Don’t worry about it I’ll deal with it when I get a chance.

**Comment by ibhagwan** [comment]
Just tried reproducing this and scrolling seems fine when the cursor is at the top, can you further expand what fails or what you believe can be improved?

The commit you mentioned intentionally disables the cursor highlight when the selected line is out of bounds, say you searched for something the cursor line will highlight the match, when scrolling it makes no sense to display it as the matched line is not contained inside the preview, this is part of a change I did for #462.

> In order to highlight the match line, I think neovim's sign feature can be used.

I know about this but still prefer the cursor line highlight.

**Comment by shiradofu** [comment]
I tested a few times with changing conditions, and I found that it depends on the height of neovim.

When `&lines` is 39, it has no problem at the top, but at the bottom the scroll has get stucked.

https://user-images.githubusercontent.com/43514606/184757991-7127ca4b-d9c6-411d-b06f-5d242535d057.mov

When `&lines` is 40, scroll is not available at both ends.

https://user-images.githubusercontent.com/43514606/184758028-a2096153-be0f-4f99-9e1d-a1836c3cd8a6.mov

**Comment by ibhagwan** [comment]
@shiradofu, I see, I’ll do some testing, this feels like a bug.

**Comment by ibhagwan** [comment]
Still struggling to reproduce this, I tried the exact same setup (even used the same file you used), the preview contains the same number of lines (tried both 12 & 13 lines in preview) and it scrolls just fine.

The call to [`vim.api.nvim_win_set_cursor` @ line 275](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/previewer/builtin.lua#L275=) is there to set the correct highlight after a scroll if the matching line **is still contained in the preview window** (which seems to be working as expected in your recording too), I'm not sure if that's the issue as setting the cursor line shouldn't prevent the scroll and it only gets called if the cursor line is found within the boundries of the preview window (`wininfo[1].{topline|botline}`, lines 271-272).

Perhaps a neovim setting in conjuntion with `vim.api.nvim_win_set_cursor`? Are you certain that's the line causing the issue in your case?

![Peek 2022-08-16 04-12](https://user-images.githubusercontent.com/59988195/184867057-e44936a4-68fe-4aa5-8d87-27a42e1fd3a1.gif)

**Comment by shiradofu** [comment]
Thanks for investigating!

> setting the cursor line shouldn't prevent the scroll

I don't think that's always the case.
In my first comment, I said that when scroll down happens, the following keymaps and command run.
`^D → zvzz → L → `` → vim.api.nvim_win_set_cursor(preview_winid, self.orig_pos)`

And if the cursor is at the top of the line, `vim.api.nvim_win_set_cursor` get back it to the first line, and prevent scrolling like this:

https://user-images.githubusercontent.com/43514606/184902312-7a92c835-f4cc-42f9-8170-4a4cb751134d.mov

At first the cursor is on line 10, so the last `10G` is equivalent to `vim.api.nvim_win_set_cursor`.
(This behavior depends on neovim height, sometimes the line 10 goes out of the visible range.)

But as long as watching your recording, the same thing seems to happen, which causes no problems.
I totally have no idea about it...

> Are you certain that's the line causing the issue in your case?

I'm fairly sure on this, because everything works well if it's commented out.

https://user-images.githubusercontent.com/43514606/184904496-6923d1e4-c773-4a48-8ef3-7944dfd7d727.mov

FYI, I could reproduce this in a rockylinux docker container.
This is the script I used.

```sh
docker run --rm -it rockylinux:9.0 /bin/bash

# inside docker container
dnf -y install epel-release
dnf -y install neovim git findutils
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all
exec -l $SHELL

git clone https://github.com/ibhagwan/fzf-lua
cd fzf-lua
printf "\nvim.cmd 'hi CursorLine ctermbg=red'\n" >> minimal_init.lua
nvim -u minimal_init.lua
```

(Additionaly, I use wezterm version `0220805-075344-ef532fc7`, but I think this has nothing to do with it because I could reproduce it also on iTerm.)

**Comment by ibhagwan** [comment]
Turns out this happens when `scrolloff` setting is unmodified (default value is `0`), https://github.com/ibhagwan/fzf-lua/commit/0e0bc7a6009059da25078ec1eb551dc8f87d219b - this commit sets `scroloff=1` locally in the preview buffer which solves the issue.

**Comment by shiradofu** [comment]
It works. Thanks a lot!
