### ISSUE TITLE
[Feature Request] Up/Down navigation with j/k

### ISSUE THREAD

**Issue by Akianonymus** [ibhagwan/fzf-lua#501]
Some context, i use better-escape.nvim plugin and have mapped my jk to escape. Now in telescope prompt i can go to normal mode with jk and then navigate list with just j and k.

SO, would it be possible to emulate that in fzf-lua ?

**Comment by ibhagwan** [comment]
Given that fzf-lua is a terminal window I don’t think it’s going to be as useful as you think, press `<C-\><C-n>` and you’ll be able to exit to normal mode and test it out, if you feel that’s useful you can create a custom terminal mapping for Fzf-lua only using the `on_create` callback:

https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-set-custom-keybinds

**Comment by Akianonymus** [comment]
Well, my goal was to make j and k behave like it does in terminal mode with ctrl+n and ctrl+p

Anyway, given its a terminal windows, probably not possible.

**Comment by ibhagwan** [comment]
> Well, my goal was to make j and k behave like it does in terminal mode with ctrl+n and ctrl+p
> 
> Anyway, given its a terminal windows, probably not possible.

You can create a custom mapping as explained in the wiki link I posted that maps `j|k` to`nvim_feedkeys` that sends a key sequence for up/down in the terminal.

**Comment by Akianonymus** [comment]
Thank you for redirecting me to that. It didn't fully solve my problem but i found a workaround.

```lua
      on_create = function()
        local function feedkeys(normal_key, insert_key)
          vim.keymap.set("n", normal_key, function()
            vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("i", true, false, true) or "", "n", true)
            vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(insert_key, true, false, true) or "", "n", true)
            vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-\\><C-n>", true, false, true) or "", "n", true)
          end, { nowait = true, noremap = true, buffer = vim.api.nvim_get_current_buf() })
        end
        feedkeys("j", "<c-n>")
        feedkeys("k", "<c-p>")
        feedkeys("f", "<c-f>")
        feedkeys("b", "<c-b>")
        feedkeys("q", "<Esc>")
      end,
```

Yes, very hacky. Basically when in normal terminal mode, on pressing j, it change to insert mode, execute <c-n> for next item, then exit from insert mode. Would love alternative solutions as going to insert mode triggers Insert autocmds unnecessarily.

So, i mapped j to `<c-n>`, k to `<c-p>`, f to `<c-f>` and so on. Basically i don't want to keep my finger on ctrl all the time ( Picked this habit as it works like this in telescope, probably a niche use case )

Here is a recording showing that ( whatever navigation is happening in the video is just j, k, f and b ).


https://user-images.githubusercontent.com/32216346/185426170-352524b5-638a-489f-b105-8333be03d3a9.mp4

**Comment by ibhagwan** [comment]
> Yes, very hacky. Basically when in normal terminal mode, on pressing j, it change to insert mode, execute for next item, then exit from insert mode. Would love alternative solutions as going to insert mode triggers Insert autocmds unnecessarily.

If you don’t mind being extra hadky you can use `vim.cmd(':noautocmd lua vim.api.nvim_feedkeys …')` (instead of calling the API directly).

> So, i mapped j to <c-n>, k to <c-p>, f to <c-f> and so on. Basically i don't want to keep my finger on ctrl all the time ( Picked this habit as it works like this in telescope, probably a niche use case )
> Here is a recording showing that ( whatever navigation is happening in the video is just j, k, f and b ).

Niche, but looks great :)

**Comment by Akianonymus** [comment]
> > Yes, very hacky. Basically when in normal terminal mode, on pressing j, it change to insert mode, execute for next item, then exit from insert mode. Would love alternative solutions as going to insert mode triggers Insert autocmds unnecessarily.
> 
> If you don’t mind being extra hadky you can use `vim.cmd(':noautocmd lua vim.api.nvim_feedkeys …')` (instead of calling the API directly).

Ohh i missed that, thanks.

> 
> Niche, but looks great :)

<3

By the way, great plugin. Need that -Osuperfastultrainstinct speed, very important.

**Comment by ibhagwan** [comment]
> Need that -Osuperfastultrainstinct speed, very important.

Totally, ty @Akianonymus ❤️

**Comment by merveillevaneck** [comment]
awesome plugin btw, really great for perf and VERY nice API. 

although i must say i am surprised there aren't more folks asking about the hjkl and other vim motion navigation. since it is the default on telescope, i would have imagined more people want to retain vim motions to navigate. i still use fzf-lua in spite of that, but sometimes i wonder what life would be like.

thanks for the link to the wiki stuff, very useful!

**Comment by ibhagwan** [comment]
Ty for the kinds words @merveillevaneck, although I could hack my way to the solution it would be too much effort for an imperfect solution, this is better done upstream but unfortunately [wont happen anytime soon](https://github.com/junegunn/fzf/issues/384).
