### ISSUE TITLE
Insert mode mappings

### ISSUE THREAD

**Issue by majjoha** [ibhagwan/fzf-lua#507]
### Info
- Operating System: macOS 12.5.1
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.7.2
- `fzf --version`: 0.32.1

### Description 
Thank you for a great plugin! I used to use [fzf.vim](https://github.com/junegunn/fzf.vim), and I am happy that I've switched. However, I've not found a way to use it in insert mode to, for instance, search for file paths as documented [here](https://github.com/junegunn/fzf.vim#mappings).

How would I be able to do this with FzfLua?

**Comment by ibhagwan** [comment]
> How would I be able to do this with FzfLua?

It's probably possible and I would guess not very complicated to recreate [using the API](https://github.com/ibhagwan/fzf-lua/wiki/Advanced) but it isn't implmeneted out of the box with fzf-lua.

Insert mode fuzzy completion somewhat overlaps with [`nvim-cmp`](https://github.com/hrsh7th/nvim-cmp) which most neovim lua users already have installed (for example, fuzzy path completion with [`cmp-path`](https://github.com/hrsh7th/cmp-path)) so I felt this was out of scope and didn't invest time on this.

**Comment by ibhagwan** [comment]
> After experimenting with the API, I think I should be able to implement a somewhat simple setup for fuzzy finding files in insert mode.
> 
> Ideally, I want to fuzzy find completion options provided by an LSP server (in this case, [Marksman](https://github.com/artempyanykh/marksman)), but this seems quite a bit more complex and perhaps also not doable with the API exposed by FzfLua.

Let me know what you come up with and if you need help.

**Comment by majjoha** [comment]
Will do! Thanks.
