### ISSUE TITLE
Is it possible to create a file or folder if it doesn't exist when searching for it?

### ISSUE THREAD

**Issue by sseneca** [ibhagwan/fzf-lua#508]
Example behaviour could be pressing "enter" after searching for a file that doesn't exist will create the file at the path specified and open it for editing in a buffer

**Comment by ibhagwan** [comment]
You can use a custom action (use the `default` action for `enter`) and call `vim.fn.system` to perform a system operation (I.e. `mkdir`/`touch`), if you need the last typed text from the Fzf prompt it’s saved in `require'fzf-lua'config.__resume_data.last_query`.

**Comment by sseneca** [comment]
Thank you, so this is what I have at the moment:

```lua
require('fzf-lua').setup({
  actions = {
    files = {
      ['default'] = actions.file_edit_or_qf,
      ['ctrl-s'] = actions.file_split,
      ['ctrl-v'] = actions.file_vsplit,
      ['ctrl-t'] = actions.file_tabedit,
      ['alt-q'] = actions.file_sel_to_qf,
      ['ctrl-c'] = function()
        local last_query = require('fzf-lua').config.__resume_data.last_query
        vim.fn.system('touch ' .. last_query)
      end,
      ['ctrl-d'] = function()
        local last_query = require('fzf-lua').config.__resume_data.last_query
        vim.fn.system('mkdir ' .. last_query)
      end,
    },
  },
})
```

I have a couple more questions:

1. Is there a way to have a `ctrl-shift-e` bind? Initially I wanted `touch` to be `ctrl-e` and `mkdir` to be `ctrl-shift-e`, but it didn't seem to let me
2. Do you know how to make it so it opens the file to edit/folder to view in the buffer afterwards?

**Comment by sseneca** [comment]
That's great, thank you! Both for the great plugin and for your really quick (and useful) help!
