### ISSUE TITLE
Q: How to search multiple dirs

### ISSUE THREAD

**Issue by changyiyao** [ibhagwan/fzf-lua#509]
Is there an easy way or best practice to implement function to [search multiple dirs](https://github.com/smartpde/neoscopes#telescope-integration) (or similar to [workspace folders](https://github.com/neoclide/coc-lists/blob/master/src/files.ts#L85) in coc)?

**Comment by ibhagwan** [comment]
You’d have to create your own customization that traverses the folder list for you, you can get some ideas of the options to do so in #485.
