### ISSUE TITLE
Actions for git commits/b_commits 

### ISSUE THREAD

**Issue by jpe90** [ibhagwan/fzf-lua#51]
Currently, the git_commits and  git_bcommits will let you inspect the diffs of each commit, but I didn't see any actions available with the results. Potential actions include:

- opening previous commits in a read only buffer
- checking out previous commits
- resetting to previous commits

Would it be feasible to add any of these?

**Comment by ibhagwan** [comment]
Most certainly, this is actually quite easy to add yourself by creating a custom action function.

Some of these make sense to be shipped as default actions, if you wish to provide the specific git command line to perform some of these actions I can easily add these actions and have them as an option.

**Comment by jpe90** [comment]
Since the UI seems to display abbreviated hash ids, I think the commands would be:
- git show [abbreviated commit hash]:[path to file] 
(it seems you need the ":[path]" or it will show the diff rather than the full file)
- git checkout [abbreviated commit hash]
- git reset --soft [abbreviated commit hash]
- git reset --soft [abbreviated commit hash]

**Comment by ibhagwan** [comment]
Ty, I’ll add these as soon as I’m done with my current task (builtin previewer).

**Comment by jpe90** [comment]
I'm happy to give it a try this weekend if you would like, I haven't worked with lua or neovim plugin development before but I wouldn't mind giving it a shot. No worries if you would rather implement it yourself though.

**Comment by jpe90** [comment]
I made an attempt at checkout functionality and opening previous commits and added them as defaults. I figured it made sense to have checkout functionality associated with project-wide commits and viewing an old version of a file to be associated with buffer commits. Let me know what you think.

**Comment by ibhagwan** [comment]
Your PR was just tested and merged, I believe we can close this issue.
