### ISSUE TITLE
on-demand loading providers in fzf-lua/init.lua

### ISSUE THREAD

**Issue by haolian9** [ibhagwan/fzf-lua#511]
some providers i personally never get a chance to use, yet i still need to load them all. so i'd propose a little trick to lazy load providers also expose them as apis.

```
do
  local function lazy(bind, mod, meth)
    return function(...)
      local fn = require(mod)[meth]
      M[bind] = fn
      return fn(...)
    end
  end

  M.resume = lazy("resume", "fzf-lua.core", "fzf_resume")

  M.files = lazy("files", "fzf-lua.providers.files", "files")
  M.args = lazy("args", "fzf-lua.providers.files", "args")
 -- ...
end
```

do you think this change is worth it?

**Comment by haolian9** [comment]
(the above function may be a bit verbose, i made it this way for more lsp friendly)

**Comment by ibhagwan** [comment]
It’s not a bad idea for sure, but the question is, do you think it will save a considerable amount of loading time? I’d like to test if and see the actual benefit rather than just jump on the “lazy load everything” bandwagon :)

**Comment by haolian9** [comment]
regards to the “lazy load everything” bandwagon, i am not a fan of it. i just want to keep the program do less things i dont need.

**Comment by ibhagwan** [comment]
> regards to the “lazy load everything” bandwagon, i am not a fan of it. i just want to keep the program do less things i dont need.

I'll do some testing when I have more time, if it's even slightly worth it I will implement something along your code.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/6588e57785ac9ca5b6e020ea3e53790dba4c50cb - this shaves 2-3ms of the loading time, not critical by any means but the change is rather harmless.

**Comment by haolian9** [comment]
i had been too mean to nvim in last couple weeks. at that time, i even crafted myself a plugin manager that not bound to nvim's runtime, set &rtp directly in case nvim dont load vim-plug's 84k vimscript code. during this fever, i noticed fzf-lua loads some providers i will never use, so this issue is opened.
i do saw some improvements for shorter loading time and lesser RSS usage; about the improvements, i hesitated to mention them at first. after those days, i'd say it's not the 80% part need to optimize. i feel sorry for opening such an issue.

thank you for this awesome plugin!

**Comment by ibhagwan** [comment]
Ty @haolian9, any improvement is a good improvement :)
