### ISSUE TITLE
Use live_grep with specific file types?

### ISSUE THREAD

**Issue by superDross** [ibhagwan/fzf-lua#512]
I am looking to restrict fzf-lua live_grep feature only on specific file-types (markdown) in a specific directory.

I can get this working on a specific directory (as below) but do not know how to restrict on filetype.

```vim
lua require('fzf-lua').live_grep({cwd = vim.g.session_directory}) 
```
I was wondering if this is possible?

**Comment by ibhagwan** [comment]
Make sure `rg` is installed, then either setup `rg_glob = true` or use `live_grep_glob` and search for `foo -- *.md *.markdown`.

You can use as many globs as you want, can also exclude using `!` and then press `ctrl-g` to fuzzy find on top.

**Comment by superDross** [comment]
Thanks for the quick reply I really appreciate it.

This works fine if I type it in directly into the FZF floating window but does not work if I try it programmatically.

```vim
lua require('fzf-lua').live_grep({rg_glob=true, cwd = vim.g.session_directory, search='this -- *.md'})
```
I get the following output in the floating window.
```
*Rg> this \-\- \*\.md  < 0/0 (0) 
 :: <ctrl-g> to Fuzzy Search, cwd: .tickets
```

**Comment by ibhagwan** [comment]
That’s because default search does a regex escape, you need to also send it with `no_esc = true`:
```lua

lua require('fzf-lua').live_grep({rg_glob=true, no_esc=true, search='this -- *.md'})

```

**Comment by superDross** [comment]
Thanks. That did the trick.

It would be nice if there was a separate key for for filetype restrictions.

For example, something like the below to restrict only for text and markdown files.
```lua
lua require('fzf-lua').live_grep({rg_glob=true, no_esc=true, search='this', filetypes={'md', 'txt'}})
```
Although, I suppose this is outside of the scope of this issue.

I'll close it now, thanks again.

**Comment by ibhagwan** [comment]
There is something similar for ignoring specific file patterns:
https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-ignore-specific-file-patterns

Although, I would argue, it’s not as efficient as rg globs, with the former fzf-lua has to do the filtering, with the latter rg filters the files so they are never processed by fzf-lua which is much more performant, also, with rg globs you aren’t limited to file types but rather file glob patterns.

In any event, you can easily recreate what you’re after with a simple lua function that iterates your `filetypes` table and postfix the types to the search string as globs.
