### ISSUE TITLE
How do I change the default key mapping to my own habitual keys

### ISSUE THREAD

**Issue by louisrc3ys** [ibhagwan/fzf-lua#513]
For example: map jk to Ese, otherwise I can only press up and down the left and right keys, you know, I don't want to get my hand out of the core key area, thanks

**Comment by ibhagwan** [comment]
Look at the [default options in the REDME](https://github.com/ibhagwan/fzf-lua#default-options), look under `keymap`.

**Comment by louisrc3ys** [comment]
Thank you very much! Can be set to NORMAL and INSERT, like nvim, this will be much easier.

**Comment by louisrc3ys** [comment]
Thank you very much! Can be set to NORMAL and INSERT? like nvim, this will be much easier.

**Comment by ibhagwan** [comment]
> Thank you very much! Can be set to NORMAL and INSERT? like nvim, this will be much easier.

Not sure what you mean but you can pretty much set any keys you want, use `:help nmap` for normal and `:help imap` for insert mode mappings.

**Comment by louisrc3ys** [comment]
Yesh,That's what I want, thanks for the reply.😉

**Comment by ibhagwan** [comment]
Closing for now, feel free to open if you need more help.
