### ISSUE TITLE
How to modify fzf-lua split properties?

### ISSUE THREAD

**Issue by luisvgs** [ibhagwan/fzf-lua#514]
According to the [documentation](url) one can change the ``fzf-lua`` layout to open in a split instead of a pop up window. For my taste the split occupies almost half of my screen. I wonder if is possible to decrease the height of it? Thanks in advance. I appreciate the effort putted in the plugin.

### Info

- Operating System: Arch
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: v0.7.0
- `fzf --version`: 0.33.0

**Comment by ibhagwan** [comment]
The `split` is a command run by neovim before opening the window, default split size is determined by neovim (not fzf-lua), however, you can modify the split option and issue a `resize` to control the split size, for example:

> Play around with the sizes using `:belowright new | resize -10` until you get to the size you want and then configure fzf-lua

```lua
require'fzf-lua'.setup {
  winopts = {
    split = 'belowright new | resize -10'
  }
}
```

**Comment by luisvgs** [comment]
Thank you @ibhagwan!

**Comment by ibhagwan** [comment]
FYI @luisvgs, I recently learned you can set the exact number of lines as part of the `new` command by prefixing it with a number, for example, this would hardcore the split to 10 lines size:
```lua
require'fzf-lua'.setup {
  winopts = {
    split = 'belowright 10new'
  }
}
```
