### ISSUE TITLE
tabs() command fix

### ISSUE THREAD

**Issue by lbrayner** [ibhagwan/fzf-lua#515]
### Info

- Operating System:
- Shell:
- Terminal:
- `nvim --version`:
- `fzf --version`:

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

Tab numbers and handles do not always match. Let's say you restore a session
with 3 tabs with `nvim -S session.vim`. After VimEnter, the output of `lua
print(vim.inspect(vim.api.nvim_list_tabpages()))` is `{ 1, 2, 3 }`, i.e., the
indices (or tab numbers) match the handle. Once you move a tab, this is no
longer true. For example: if you're on tab no. 1 and do a `:tabm`, the output of
`lua print(vim.inspect(vim.api.nvim_list_tabpages()))` will be `{ 2, 3, 1 }`.
So, to fix `tabs()` you have to tweak
[winid_from_tab_buf](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/utils.lua#L499).
`nvim_tabpage_list_wins` takes a tab handle, not `tabnr`. To get the handle, use
`tabnr` as an index to `nvim_list_tabpages()` like this:

```lua
local function winid_from_tab_buf(tabnr, bufnr)
  local tabhandle = vim.api.nvim_list_tabpages()[tabnr]
  for _, w in ipairs(vim.api.nvim_tabpage_list_wins(tabhandle)) do
    if bufnr == vim.api.nvim_win_get_buf(w) then
      return w
    end
  end
  return nil
end
```

**Comment by ibhagwan** [comment]
Ty for this issue @lbrayner.

After investigation I did find a bug that happens after a `:tab` but it wasn't in `winid_from_tab_buf`, `actions.buf_switch` action was using `:tabn <idx>` command which does get confused after a tab move:
https://github.com/ibhagwan/fzf-lua/blob/0944e1e85fc74c7c006c696b74b7af3acf345d8b/lua/fzf-lua/actions.lua#L297

Since the tab "numbers" used by fzf-lua are already tab handles there is no issue with `winid_from_tab_buf`, 
https://github.com/ibhagwan/fzf-lua/commit/7c5890daaa0ad3f9d793112594fdecbec09ccad6 - this replaces `:tabn` with `vim.api.nvim_set_current_tabpage` which solves the issue.

**Comment by ibhagwan** [comment]
This does raise another issue whether we wish to keep using tab handles for the display output of `:FzfLua tabs`, I’m still conflicted which one makes more sense, having consistency in tab “numbers” by using the underlying neovim index, or using the tab number as it is positioned (serially, which changes with every tab move).

**Comment by lbrayner** [comment]
Great! I also found another error in [opts._list_bufs](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/buffers.lua#L272), which would be fixed by using the index instead of the handle:

```lua
  opts._list_bufs = function()
    local res = {}
    for i, t in ipairs(vim.api.nvim_list_tabpages()) do
      for _, w in ipairs(vim.api.nvim_tabpage_list_wins(t)) do
        local b = vim.api.nvim_win_get_buf(w)
        -- since this function is called after fzf window
        -- is created, exclude the scratch fzf buffers
        if __STATE.bufmap[b] then
          opts._tab_to_buf[i] = opts._tab_to_buf[i] or {}
          opts._tab_to_buf[i][b] = i
          table.insert(res, b)
        end
      end
    end
    return res
  end
```

**Comment by lbrayner** [comment]
I'm assuming the intention is to show the tab number, which is useful as a prefix to the `gt` jump.

**Comment by ibhagwan** [comment]
> I'm assuming the intention is to show the tab number, which is useful as a prefix to the `gt` jump.

That’s a good point, in that sense the tab handle is useless, TBH I rarely use tabs in my workflow, tabs provider was a user request.

I’ll modify the behavior later and keep you posted.

**Comment by lbrayner** [comment]
Excellent, thank you. Tabs are essential to my workflow and the tabs() command is perfect.

The fix for `opts._list_bufs` provided above is incompatible with https://github.com/ibhagwan/fzf-lua/commit/7c5890daaa0ad3f9d793112594fdecbec09ccad6, so I'll come up with a working fix.

**Comment by ibhagwan** [comment]
> Excellent, thank you. Tabs are essential to my workflow and the tabs() command is perfect.
> 
> The fix for `opts._list_bufs` provided above is incompatible with [7c5890d](https://github.com/ibhagwan/fzf-lua/commit/7c5890daaa0ad3f9d793112594fdecbec09ccad6), so I'll come up with a working fix.

Dw about it, I’ll be closer to a keyboard soon and fix the logic :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/f42fbf06e6b3c5d9cfa9ad92589f8f5ecf3a315f - this should work the way you described, tab numbers in `:FzfLua tabs` now reflet the tab index according to the current tab order.

**Comment by lbrayner** [comment]
It works! Thanks!

**Comment by lbrayner** [comment]
Hey, @ibhagwan, there's another spot we missed: https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/buffers.lua#L317.

populate_buffer_entries expects a tab handle, so just adding this simple patch in harmony with the previous commit is enough:

```lua
      local tabnr = vim.api.nvim_list_tabpages()[t]
      local buffers = populate_buffer_entries(opts, bufnrs_flat, tabnr)
```

I was getting errors such as 

```
E5108: Error executing lua: ...ack/bundle/opt/fzf-lua/lua/fzf-lua/providers/buffers.lua:327: ...onfig/nvim/pack/bundle/opt/fzf-lua/lua/fzf-lua/utils.lua:500: Invalid tabpage id: 3
stack traceback:
        [C]: in function 'fzf_exec'
        ...ack/bundle/opt/fzf-lua/lua/fzf-lua/providers/buffers.lua:327: in function <...ack/bundle/opt/fzf-lua/lua/fzf-lua/providers/buffers.lua:265>
```

**Comment by lbrayner** [comment]
@ibhagwan yet another patch! This time for the current tab page in `buffers.lua`:

```lua
local UPDATE_STATE = function()
  __STATE = {
    curtab = vim.api.nvim_win_get_tabpage(0),
    curbuf = vim.api.nvim_get_current_buf(),
    curtabidx = vim.fn.tabpagenr(),
...
```

And in `M.tabs`:

```lua
      cb(("%d)%s%s\t%s"):format(t, utils.nbsp,
        utils.ansi_codes.blue("%s%s#%d"):format(opts.tab_title, utils.nbsp, t),
          (t==__STATE.curtabidx) and
          utils.ansi_codes.blue(utils.ansi_codes.bold(opts.tab_marker)) or ''))
```

Without this patch, current tab marker points to current tab's tab handle.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/9b23c2c0ba83d57ab7936e7aaba812ca69c356e3

Ty again @lbrayner!

Btw, in the future it's better to utilize the "pull request" process for such fixes so you can get the credit for the commit and be registered as a contributor to this project :-)

**Comment by lbrayner** [comment]
Next time I will! Thanks!

**Comment by nyngwang** [comment]
@lbrayner Would be off-topic here but, may I ask you that could I think of "tab handle"(and I remember this word is frequently used in the (neo)vim's manual) as "reference/pointer" in other programming languages?

**Comment by lbrayner** [comment]
@nyngwang the tab number can change and the handle can't. You can move tabs around with `tabm` and use the number to jump to them with `gt`.

**Comment by nyngwang** [comment]
@lbrayner So indeed the handle is like tab id while tab number is just like the index of some structure where those tabs are stored?

**Comment by lbrayner** [comment]
@nyngwang exactly!
