### ISSUE TITLE
[Question] Is there a way to set default previewer position?

### ISSUE THREAD

**Issue by xiaochuanyu** [ibhagwan/fzf-lua#516]
Is there an option to set so that previewer starts at bottom position (like pic) so that I don't have to press F6?
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/1718745/189915842-59faecf7-b50a-4472-b027-af11087e7789.png">
I played around with `winopts.preview.layout` but it doesn't seem to do anything for me.

**Comment by ibhagwan** [comment]
Can also be configured via `setup` for a permanent effect:
```lua
:lua require'fzf-lua'.files({winopts={preview={layout='vertical'}}})
```

**Comment by xiaochuanyu** [comment]
Thank you so much!
Oh man I realized I had a typo and thats why my `layout` didn't do anything for me earlier.
