### ISSUE TITLE
Improve the readability of file-based option `path_shorten = true` by section-expansion? (continued #408)

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#518]
I would like to propose a feature request inspired by https://github.com/ibhagwan/fzf-lua/issues/408#issuecomment-1120093429

<details>
  <summary>Target Comment</summary>

> FYI, https://github.com/ibhagwan/fzf-lua/commit/b614a9d315512ec4ce9c1df41474e5ab8e12f7df - all file-based providers (files, grep, tags, lsp, etc) now support the `path_shorten` option, you can supply either `true` or a number that defines how many characters to use in each path part.
> 
>`:FzfLua lsp_workspace_symbols path_shorten=1`
![image](https://user-images.githubusercontent.com/59988195/167231120-b56a3bdc-a693-41a6-8d99-a3cf7b57d253.png)
> 
>`:FzfLua lsp_workspace_symbols path_shorten=2`
![image](https://user-images.githubusercontent.com/59988195/167231131-3cbccd22-7388-483d-ad62-a889afaf54bb.png)
> 
> _Originally posted by @ibhagwan in https://github.com/ibhagwan/fzf-lua/issues/408#issuecomment-1120093429_

</details>

For me, it will be convenient to expand some sections of the file path. In the current implementation only the last section, i.e. the filename itself is kept.

In my simple use case: I have two clones in both `~/GitHub/dotfiles/.config/nvim/...` and `~/.config/nvim/...`. While in this use case it's not a severe problem to more quickly identify where the files are from, it will be convenient to expand the first (or first two) section of the shortened file path(s), i.e. `GitHub/` and `.config/`. This is not a good example because `G` and `.` are easily for differentiating, but I think the problem will become more severe when the differences are in the middle sections of the paths.

My current alternative solution is to enable the title of the preview window, but it makes me feel like losing focus when a larger preview window is used and more items are in the result list. Picture of the current implementation for reference:

<img src="https://user-images.githubusercontent.com/24765272/190330231-57f592ba-df4d-4765-b52b-d3c4d55b306a.png" width="400">

**Comment by ibhagwan** [comment]
Unfortunately this wouldn’t be possible without a fundamental change how entries are stored, the way you’re describing, in order to expand back to full path additional metadata per entry would need to be stored within fzf’s memory which would increase the memory footprint per entry and slow down things significantly.

The way it’s currently implemented is using a builtin glob mechanism inside neovim (`vim.fn.glob`) to expand the path back to its full version, what you’re describing is more complex and IMHO not worth the effort.

**Comment by nyngwang** [comment]
@ibhagwan Then is it possible to have an option to move the title to the bottom of the preview window? (And probably need to rename it.)

**Comment by ibhagwan** [comment]
> @ibhagwan Then is it possible to have an option to move the title to the bottom of the preview window? (And we probably need to call it footer?)

Maybe as part of #462 I can also have different title locations.

**Comment by nyngwang** [comment]
Thanks for the link :) I like the idea of highlighted/colored title! Let me take a look at the thread. I think this thread can be closed as I will discuss there if anything could be added.

**Comment by ibhagwan** [comment]
> I think this thread can be safely closed
