### ISSUE TITLE
How to make result count align to the right?

### ISSUE THREAD

**Issue by TisnKu** [ibhagwan/fzf-lua#519]
Thank you for the most incredible plugin! It deserves 20x more stars! The documents are wonderful and features are inspring.

I have but one small question, how to move the result count in below picture? When typing, it is janking all the time.
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/10512841/190688199-065b6a3d-4cda-4aa5-aa24-93fe522a56e9.png">

**Comment by ibhagwan** [comment]
Ty for the kind words @TisnKu!

The location of the result count is controlled by fzf’s `--info` option, fzf-lua uses `inline` by default, other possible values are, `default` (left side) and `hidden` (right side):
![44219A73-5A16-414F-81A2-65EE936854DD](https://user-images.githubusercontent.com/59988195/190691017-919e969d-db69-4e11-89b5-e2ee0c59bd33.jpeg)

If you’re using [skim (`sk`)](https://github.com/lotabout/skim), the location for `inline` is slightly different though I can’t recommend using it as the project seems to be abandoned at this point:
![0CEB050B-3030-4FED-B529-3F1C68AB73A0](https://user-images.githubusercontent.com/59988195/190691217-8d86517e-1f95-4233-bb6e-4e545c490a41.jpeg)

**Comment by TisnKu** [comment]
Thanks, I'll go with `default` then.
