### ISSUE TITLE
FzfLua for tselect

### ISSUE THREAD

**Issue by sharklasers996** [ibhagwan/fzf-lua#526]
Running `:tselect` when there are several matches brings up vim selection, is it possible to use FzfLua instead somehow? I searched through docs and issues, but couldn't find anything

Example of what I mean - running `:tselect` on `Fetch` word:
![multiple_tags](https://user-images.githubusercontent.com/14793156/191517844-f081cf8e-17c0-4360-808d-0f34561aaa32.png)

**Comment by ibhagwan** [comment]
If this uses `vim.ui.select` you can use `:FzfLua register_ui_select` to register as the UI for these.

**Comment by ibhagwan** [comment]
Just realized `:tselect` uses the tag stack, you can view that with `:FzfLua tagstack`.

**Comment by vinted-stasys** [comment]
It doesn't seem to be the same as `tagstack`, I gave it a shot and got the result of `:tags` command (it shows previous tag jumps?)

![fzflua_tagstack](https://user-images.githubusercontent.com/72206928/191667367-96087166-62b3-4869-adfb-7aaf9183619f.png)

![tagstack](https://user-images.githubusercontent.com/72206928/191667378-0c26b991-f743-4014-a320-336965994133.png)

**Comment by sharklasers996** [comment]
`:FzfLua tagstack` seems to show tags that I've jumped to and `:tselect` shows a list of matching tags, found in docs that it doesn't change tagstack:/

![fzflua_tagstack](https://user-images.githubusercontent.com/14793156/191667815-c50c55fc-8af7-4c50-83a2-96ee73287173.png)

![tagstack](https://user-images.githubusercontent.com/14793156/191667840-62701a8f-ed90-48fe-9c72-d4acc24cb286.png)

**Comment by ibhagwan** [comment]
> `:FzfLua tagstack` seems to show tags that I've jumped to and `:tselect` shows a list of matching tags, found in docs that it doesn't change tagstack:/


What about `tags_grep_cword`?

**Comment by sharklasers996** [comment]
That still isn't exactly what I wanted, but you gave me a good idea for making my own command, thanks a lot, this is a great plugin:)

**Comment by ibhagwan** [comment]
Closing, lmk if you need more help.
