### ISSUE TITLE
[Question][LSP] Reverse FilePath and Symbol in Fuzzy Search Results

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#527]
### Description
![image](https://user-images.githubusercontent.com/5642902/191566930-730d581e-0bd2-41df-80fd-13bf010c57a1.png)

Is it possible to actually place the Symbol information first, then the filepath and line information next to it? I think it would be way more visibly cleaner if I could achieve this.

**Comment by ldelossa** [comment]
@ibhagwan where would I add that flag?

**Comment by ibhagwan** [comment]
> @ibhagwan where would I add that flag?


```lua
require'fzf-lua'.setup({
  lsp = {
    symbols = {
      symbol_style = 2
    }
  }
})
```

Can also be called directly:
```lua
:lua require'fzf-lua'.lsp_workspace_symbols({ symbol_style = 2 })
```

If you wish to hide filenames:
```lua
:lua require'fzf-lua'.lsp_workspace_symbols({symbol_style=2,fzf_opts={['--with-nth']='2..'}})
```

Or permenently:
```lua
require'fzf-lua'.setup({
  lsp = {
    symbols = {
      symbol_style = 2,
      fzf_opts={ ['--with-nth'] = '2..' }
    }
  }
})
```

**Comment by ibhagwan** [comment]
It's also worth noting that `path_shorten` is probably another viable option here:
```lua
:lua require'fzf-lua'.lsp_workspace_symbols({symbol_style=2,path_shorten=true})
```

**Comment by ldelossa** [comment]
```
require'fzf-lua'.setup({
  lsp = {
    symbols = {
      symbol_style = 2,
      fzf_opts={ ['--with-nth'] = '2..' }
    }
  }
})
```

Is working exactly how I'd want it:

![image](https://user-images.githubusercontent.com/5642902/191998058-69854662-4ea4-453c-9ada-c998e49ee502.png)


Thanks a ton!

**Comment by ldelossa** [comment]
Would it be possible to do the same thing for "Go to definition" and the other lsp calls?

**Comment by ibhagwan** [comment]
> Would it be possible to do the same thing for "Go to definition" and the other lsp calls?

This can be applied to any providers, `nth|with-nth` is a builtin fzf functionality to hide/exclude fields (based on `--delimiter`), the below applies it to all LSP providers, if you wish to selectively apply, send `fzf_opts` as part of your mapping:
```lua
require'fzf-lua'.setup({
  lsp = {
    fzf_opts={ ['--with-nth'] = '2..' }
    symbols = {
      …
    }
  }
})
```

**Comment by ldelossa** [comment]
thanks, that works!
