### ISSUE TITLE
Is it possible to make all `buffers`, `files`, `live_grep_glob` all like a toggle?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#530]
I map command `:FzfLua files` to shortcut `<C-G>`, and it works like a toggle. i.e. If I press it again at any time(whether or not I have something typed) it will be closed. I like this behavior since this saves me a movement to press `<Esc>`. But for other commands like `buffers`, `live_grep...`, pressing the same keycomb again doesn't work like that. Is it possible to make the toggle behavior as the default one?

**Comment by ibhagwan** [comment]
If you wish for the UI to close on a keypress you’d have to set that bind specifically to fzf’s `abort` or make sure no other bind exists by setting its `actions` keybind to false, I believe either should work, try these:
```lua
require'fzf-lua'.buffers({ actions = {['ctrl-g'] = `abort` } })
require'fzf-lua'.buffers({ actions = {['ctrl-g'] = false } })
```

**Comment by nyngwang** [comment]
@ibhagwan The 'abort' one works :) thank you!

**Comment by ibhagwan** [comment]
> @ibhagwan The 'abort' one works :) thank you!

Great, closing :-)
