### ISSUE TITLE
Suggestion: registers

### ISSUE THREAD

**Issue by timon-sue** [ibhagwan/fzf-lua#532]
Hi there, and thanks for this great plugin. I use it every day!

The only thing that t I find myself missing is the ability to use (paste from) registers. If I want to search for current word or selection I need to create complex binds for every different kind of search (tags, files, grep, ..). I have a small brain so I tend to forget those and find myself having to check my own config file.

Is there some way for me to implement that myself?

Kind regards and thanks again for your great work. :+1:

**Comment by ibhagwan** [comment]
Ty for the kind words @timon-sue.

> I tend to forget those and find myself having to check my own config file.

First, for that I would recommend using `which-key.nvim`, if you’re talking about fzf-lua binds try pressing `F1’ for the builtin help.

> The only thing that t I find myself missing is the ability to use (paste from) registers. If I want to search for current word or selection I need to create complex binds for every different kind of search (tags, files, grep, ..).

Not sure if I understand the connection here between the above and pasting from registers action. In any event creating a custom action is as easy as:
https://github.com/ibhagwan/fzf-lua/wiki/Advanced#keybind-handlers

Also, not sure if this is what you’re after but have you tried `:FzfLua registers`?

**Comment by timon-sue** [comment]
Hi and thanks for your message.

There are two variables: 

-  The type of fzf-lua search (tags, files, grep, commands ...etc)
-  The register I want to use as input for that search (+, ", 1,2,3,4....etc)

Yes, I could add a custom bind for "grep for contents of register 4", but then I'd end up adding a lot of custom binds/commands.

In my workflow I only use one bind, namely to run :FzfLua. It's much easier to grep for the right kind of search then to remember a bunch of binds.

Therefore I'd like to paste some register contents to search for contents of that register. 

So the workflow for me would look like this:

- yank `header.h` from my current file to register 'h'
- :FzfLua
- select 'files'
- paste register h

Does that make sense?

Thanks!

**Comment by ibhagwan** [comment]
Take a look at #534, it’s pretty much the same question, fzf-lua is just a terminal buffer, create a term bind to paste from register (I use `<A-r>`),  then to paste from say the yank register press `<A-r>0`.

Below  is the mapping I use globally for term buffers, if you wish to have this mapping just for Fzf-lua use the `on_create` event (configured on `setup`):

```lua
vim.keymap.set('t', '<M-r>', [['<C-\><C-N>"'.nr2char(getchar()).'pi']], { expr = true })
```

**Comment by timon-sue** [comment]
Ah, sorry! Totally missed that.

Thanks a lot, that solves my problem exactly :)
