### ISSUE TITLE
[Question] Pasting from clipboard into FZF

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#534]
### Description 
Something I cannot seem to figure out from searching issues or doc.txt. 

Often times I want to paste clipboard contents into live_grep command. 

I try "ctrl-r *" along with my terminal's paste shortcut of "ctrl-v". 

The former doesn't work and the latter closes the search modal all together.

Is there a way to paste contents into fzf modals such as "live_grep"

**Comment by ibhagwan** [comment]
That’s because Fzf is a terminal buffer, it behaves differently in neovim and has different rules and keymaps, I use this in my neovim config to replace `<C-r>` in all my term buffers:
```lua
vim.keymap.set('t', '<M-r>', [['<C-\><C-N>"'.nr2char(getchar()).'pi']], { expr = true })
```

Use `<A-r>` like you use `<C-r>` and paste from clipboard using `<A-r>+`.

**Comment by ldelossa** [comment]
thank you!
