### ISSUE TITLE
Feature Request: Show cwd for all `git_*()` commands

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#535]
As title. This originated from trying this command:

```lua
vim.keymap.set('n', '<Leader>gp', function () require('fzf-lua').git_files({ cwd = vim.fn.getcwd() }) end, ...)
```

Then, I realized that the `show_cwd_header` is not eabled by default. But I also prefer put the config option inside `setup(...)` and avoid duplication from all nested tables(e.g. `git.files`, `git.status`, etc) if possible. So, could the following option be added?

```lua
setup {
  git = {
    show_cwd_header = true,
  }
}
```

The current behavior of this option and two existing ones, i.e. `grep.show_cwd_header = true` and `files.show_cwd_header = true`, I got:

1. Only If the `cwd` is different from the project root(where the root `.git/` folder lives), the `cwd: ...` will be shown.
2. The `cwd: ...` of `require('fzf-lua').git_files({ cwd = vim.fn.getcwd() })` will never be shown.

The expected behavior is `cwd: ...` will always be shown.

---

> But I also prefer put the config option inside `setup(...)` [...]

Or maybe this is not a good idea? If so, feel free to reject this request!

**Comment by ibhagwan** [comment]
`show_cwd_header = true` should always display the header regardless of the current working directory, if it’s not showing up it’s a bug that needs to be fixed (I just tested it again and it works as expected).

As for adding yet another option/override to avoid extra text in `setup`, I honestly don’t think it’s worth it, as I wrote to you in the other issue, unless it’s a super common request I’d like to reduce the already existing overhead with the abundance of options.

**Comment by nyngwang** [comment]
> show_cwd_header = true should always display the header regardless of the current working directory [...]

I just realized that the two aforementioned options(`{grep|files}.show_cwd_header = true`) are not related to `git_*()`. Now I just added them to my config and it works as expected:

```lua
setup {
  git = {
    status = { show_cwd_header = true },
    files = { show_cwd_header = true },
  }
```

Since no bug, let me close this and thanks for your clarification :)
