### ISSUE TITLE
Excluding hidden directories in search

### ISSUE THREAD

**Issue by eliavo** [ibhagwan/fzf-lua#536]
I use fzf-lua on a BIG project, and searching files can be slow. what slows it down are some big hidden directories (for example .cache) which fzf-lua searches automatically. I can config the keymap for file searching to search specifically in one directory, but that means I can't use that feature on other projects.
I was wondering whether there is an option to exclude hidden directories in regular files/grep search.
fyi Maybe this should be a question on the fzf repo and not this one...

**Comment by ibhagwan** [comment]
It’s actually very easy, the underlying command sent to Fzf can be modified by the `cmd` argument, you can easily create two mappings one without hidden folders (or exclusions) and one that shows all files (create a mapping or command for convenience):

```lua
:lua require'fzf-lua'.files({ cmd = 'fd --no-ignore --hidden …' })
:lua require'fzf-lua'.files({ cmd = 'fd --exclude …' })
```

**Comment by unrealapex** [comment]
Sorry to necrobump but how would it be possible to append flags to the defaults defined by Fzf-lua?

```lua
require("fzf-lua").files({ cmd = default_opts .. "--hidden" })
```

**Comment by ibhagwan** [comment]
> Sorry to necrobump but how would it be possible to append flags to the defaults defined by Fzf-lua?
> 
> ```lua
> require("fzf-lua").files({ cmd = default_opts .. "--hidden" })
> ```

Overdoing the defaults is done by specifying `fd_opts = …` (if you have fd installed), otherwise just rewrite the entire command by setting `cmd = 'fd … --hidden'`

**Comment by unrealapex** [comment]
Thank you for the quick response! I guess I could just set it. So for clarification I would not be able to *append* to the defaults?

**Comment by ibhagwan** [comment]
If you really want to you can access the defaults with `fd_opts = require("fzf-lua").defaults.files.fd_opts .. ' --hidden'`.

Note this assumes you have fd installed, otherwise another command which isn’t fd will run.
