### ISSUE TITLE
[Feature request] expose currently open provider/command

### ISSUE THREAD

**Issue by gennaro-tedesco** [ibhagwan/fzf-lua#537]
Before anything else, this plugin is awesome, thank you for all your hard work!

### Description 

I would like to write a custom extension for [lualine](https://github.com/nvim-lualine/lualine.nvim) showing selected picker on the statusline (plus perhaps some other goodies); according to https://github.com/ibhagwan/fzf-lua/issues/30 the filetype of the prompts are set already to `fzf`, however, the default [fzf extension](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/extensions/fzf.lua) for lualine does not work (namely nothing is shown), whereas it does work in case of fzf.vim. Moreover I cannot see the filetype `fzf` listed in the list of all present filetypes, so I was wondering if it is really being set at all.

### Addendum

Is it possible to expose the current picker/provider being used? It would be great to use it as descriptive component of a statusline, say something along the lines of "fzf: files/commits/grep" (or whatever else is being invoked at the time). Do we have a method like `get_current_picker`or what could I use in its stead?

**Comment by ibhagwan** [comment]
Hi @gennaro-tedesco, and ty for the kind words.

The file type is definitely being set, you can test it by opening FzfLua and pressing `<C-\><C-n>:set ft?`, perhaps there are additional checks in the lualine code to make it work? That is something you’re better off asking in the lualine repo:
![AAB2E6E2-F375-4B51-825B-49F5D9CC07FD](https://user-images.githubusercontent.com/59988195/194591424-e721438a-8d4d-4726-bba3-8bebe648acb6.jpeg)

> Is it possible to expose the current picker/provider being used? It would be great to use it as descriptive component of a statusline, say something along the lines of "fzf: files/commits/grep" (or whatever else is being invoked at the time). Do we have a method like get_current_pickeror what could I use in its stead?

This shouldn’t be a problem, I’ll take a look if we can already extract this info or need a new function.

**Comment by gennaro-tedesco** [comment]
I do see with your example that the filetype is being set. I will ask in the lualine repositories to make sure my understanding of their extensions is correct - once so, I will try to create a statusline component too :)

**Comment by ibhagwan** [comment]
> I do see with your example that the filetype is being set. I will ask in the lualine repositories to make sure my understanding of their extensions is correct - once so, I will try to create a statusline component too :)

Let me know how it goes, once you know what you want to do we can make necessary adjustments if needed.

**Comment by gennaro-tedesco** [comment]
It seems (see cross-posted issue) that statuslines are not supported yet when floating windows open (which is the reason why it does not show despite being invoked). I am trying to see now if I can make winbars or inactive statuslines work nevertheless.

**Comment by ibhagwan** [comment]
> It seems (see cross-posted issue) that statuslines are not supported yet when floating windows open (which is the reason why it does not show despite being invoked). I am trying to see now if I can make winbars or inactive statuslines work nevertheless.

I see, ty for the update.

Btw, fzf-lua does support running in a split (instead of floating) if this is something you’d consider.

**Comment by gennaro-tedesco** [comment]
See below for example behaviour with split right:


https://user-images.githubusercontent.com/15387611/194715763-1f95ee90-52e3-4540-a6ae-c6a45dc3890e.mov

On the bottom right I have "hardcoded" the name of a method that ideally returns the selected picker: if implemented it would show whichever `fzf-lua` provider is currently active. If you find some time and if it isn't too hard, see if it makes sense to implement it - I could open a PR in lualine to merge the extension, it could be a cool integration for `fzf-lua` since lualine is among the most used statuslines out there.

**Comment by ibhagwan** [comment]
> If you find some time and if it isn't too hard, see if it makes sense to implement it

No problem at all, I’ll add it today and keep you posted.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5a05828f9fa9968726f2047cf58a78a05da7b2a1 - this commits adds a new API `get_info` that exposes the open window information:

```lua
-- while fzf-lua is open presss <C-\><C-n> to exit
-- terminal mode to normal mode and run:
:lua vim.pretty_print(require'fzf-lua'.get_info())
-- example output when using `:FzfLua help_tags`
-- returns `nil` when no fzf-lua window is open
{
  cmd = "help_tags",
  fnc = "helptags",
  mod = "fzf-lua.providers.helptags"
}
```

**Comment by gennaro-tedesco** [comment]
https://user-images.githubusercontent.com/15387611/194724167-2740b00a-08a0-4a4c-acbf-a73be891bb80.mov

What do you think? 😄 

I am opening a PR on lualine to include it as default extension :)

**Comment by ibhagwan** [comment]
> What do you think? 😄

Looks fantastic!

> I am opening a PR on lualine to include it as default extension :)

Would be even better if it works for floating wins as most users prefer that to the split layout :)

**Comment by gennaro-tedesco** [comment]
> Would be even better if it works for floating wins as most users prefer that to the split layout :)

According to https://github.com/neovim/neovim/issues/16753 this is being thought on and contributed, probably a patch will be coming soon.

Now that we are at it...is it possible to even expose the current selected item? I am having a look at the [actions](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/actions.lua) code, where one can `return selected[#selected]` from action functions, but it's unclear to me how to access selection outside the actions menu.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/c81874db259eef85ae21794b2f29e953519c692c

Latest commit also adds `selected` entry for the currently selected item, important to note:
- Only works on interfaces where there's a previewer present (even if set to `hidden`)
- Displays the entire line (including hidden fields, icons, etc, so you have to do your own parsing)

Sample output:
```lua
{
  cmd = "live_grep",
  fnc = "live_grep",
  mod = "fzf-lua.providers.grep",
  selected = '   scripts/minimal_init.lua:8:21:local res, packer = pcall(require, "packer")'
}
```

**Comment by ibhagwan** [comment]
Forgot to mention if you're just interested in file-type entries you can use fzf-lua's parser `path.entry_to_file` to get the data:
```lua
:lua vim.pretty_print(require'fzf-lua'.path.entry_to_file(require'fzf-lua'.get_info().selected))
-- output given the above entry:
{
  col = 21,
  line = 8,
  path = "scripts/minimal_init.lua",
  stripped = 'scripts/minimal_init.lua:8:21:local res, packer = pcall(require, "packer")'
}
```

**Comment by gennaro-tedesco** [comment]
I have added a section that makes use of the return value for the selected element: parsing the first bit of the string should show relevant information in most cases, see below:

https://user-images.githubusercontent.com/15387611/194774093-d86c74c5-5666-424d-81c4-4a33ba861e75.mov

**Comment by ibhagwan** [comment]
Looks great @gennaro-tedesco!

**Comment by gennaro-tedesco** [comment]
The [PR](https://github.com/nvim-lualine/lualine.nvim/pull/863#event-7617013628 has been merged). The extension is now available by simply configuring
```
require("lualine").setup({
	extensions = { "fzf" },
})
```
(feel free to mention it in the README since a lot of people are using lualine).

**Comment by ibhagwan** [comment]
> The [PR](https://github.com/nvim-lualine/lualine.nvim/pull/863) has been merged. The extension is now available by simply configuring
> 
> ```
> require("lualine").setup({
> 	extensions = { "fzf" },
> })
> ```
> 
> (feel free to mention it in the README since a lot of people are using lualine).

Ty @gennaro-tedesco! I’ll add it to the wiki when I get a chance (feel free to edit the Wiki yourself too).
