### ISSUE TITLE
lsp_definition in split (single result)

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#538]
I was wondering if its possible to open `lsp_definition` from `fzf.lsp_definitions({ sync = true, jump_to_single_result = true })` in a horizontal / vertical split. Wanted to add a new keymap to do this.

It is possible when `jump_to_single_result` is false, and I can use an action to open a split / tab. How can this be done for single result mode?

**Comment by ibhagwan** [comment]
Take a look at: https://github.com/ibhagwan/fzf-lua/wiki#lsp-jump-to-location-for-single-result

```lua
:lua require('fzf-lua').lsp_definitions({
  jump_to_single_result = true,
  jump_to_single_result_action = require('fzf-lua.actions').file_vsplit,
})
```

**Comment by ViRu-ThE-ViRuS** [comment]
perfect! Thank you so much!!
