### ISSUE TITLE
FzfLua man_pages with no resultst

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#539]
### Info

- Operating System: arch
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.8.0
- `fzf --version`: 0.340

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

Either I don't understand `FzfLua man_pages` or it is broken.
Simply running FzfLua man_pages results in ".: Nothing appropriate" when (I believe) it should come up with a menu of commands with man pages to choose from.

I think this was working in a previous commit but somehow got messed up.

**Comment by ibhagwan** [comment]
Nothing was changed in regards to how `man_pages` works in a long time, all it does is display the output of `man -k .` (configurable) - what is the output if you run it in the shell?

**Comment by barrett-ruth** [comment]
Running `sudo man-db` solved the problem. Arch linux should've do this with a timer service but I guess it wasn't/
