### ISSUE TITLE
fzf-lua/lua/fzf-lua/utils.lua:180: Vim(visual):E37: No write since last change (add ! to override)

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#54]
If I don't save a file and I try to run `:lua require'fzf-lua'.grep_visual()` I get the following error:

```
fzf-lua/lua/fzf-lua/utils.lua:180: Vim(visual):E37: No write since last change (add ! to override)
```

**Comment by ibhagwan** [comment]
This issue was a bit of a bigger annoyance than I anticipated but it's solved now :-)

It's still annoying me though as even when I exit visual selection with either `<Esc>` or `v` the last visual selection isn't saved and `gv` doesn't reselect the text.
