### ISSUE TITLE
How to execute a custom command when hitting select

### ISSUE THREAD

**Issue by superDross** [ibhagwan/fzf-lua#541]
### Info

- Operating System: Linux (Manjaro)
- Shell: bash
- Terminal: xfce4-terminal
- `nvim --version`: 0.8.0
- `fzf --version`: 0.34.0

### Description 
I have created the following command using fzf.vim to open a session when a session file is selected within the fzf popup:
```vim
function! FzfSessionSelection(selection) 
  let sessionfile = g:session_directory . '/' . a:selection[2]
  execute 'silent source ' . sessionfile
endfunction

let wrapped = fzf#wrap('sessions', {
\  'dir': g:session_directory,
\  'options': ['--query=' . a:args]
\}, 0)
let wrapped['sink*'] = function('FzfSessionSelection')
 fzf#run(wrapped)
```

I am now trying to recreate this using fzf-lua but am struggling to do so. I tried creating a wrap function using `fzf_wrap` but did not know how to use it along with `sink`. 

I am now trying to utilise actions with a default map to get this working:

```lua
local fzf = require('fzf-lua')

fzf.files({
  cwd = vim.g.session_directory,
  actions = {
    ['default'] = {
      function(selected)
        vim.cmd('source ' .. vim.g.session_directory .. '/' .. selected[0])
      end
    }
  }
})
```

After selecting a given file with enter, the terminal exits with `[process exited 0]`. I tried replacing `vim.cmd('source'....` with `print(selected)` and I get the same results.

I suspect I am misunderstanding the actions functionality is actually doing.

I was wondering if you could point me in the right direction to get this working?

Any help (even pointing to a place in the docs) would be appreciated.

**Comment by ibhagwan** [comment]
You're on the right track @superDross, `[process exited 0]` usually happens if the action raises an exception of some kind, one obvious error is the use of `selected[0]`, lua (weirdly enough) is not zero-based, that means that the first item is actually `selected[1]`.

If the above still doesn't work you'd need to debug this step by step and see what causes the failure, the first step would be to inspect the `selected` object contents by using `vim.pretty_print(selected)` as the only line inside your custom action and seeing if that works as expected and it gets printed without error into the `:messages` stream.

**Comment by ibhagwan** [comment]
You may have already seen that but it's also worth reading the advanced section of the Wiki

https://github.com/ibhagwan/fzf-lua/wiki/Advanced

**Comment by superDross** [comment]
This is what ultimately worked:

```lua
    require('fzf-lua').files({
      file_icons = false,
      git_icons = false,
      previewer = false,
      cmd = "find " .. vim.g.session_directory .. " -type f -name '*.vim' ",
      actions = {
        ['default'] = {
           function(selected)
               vim.cmd('quit')
               vim.cmd('source ' .. selected[1])
           end,
        }
      }
    })
```
I had to quit the fzf terminal before the source command would work, otherwise (presumably) it was trying to apply the source to the terminal buffer.

Thanks for the guidance :) 
I am fairly new to lua so appreciate the advice given regarding debugging. 

Also, I am loving this plugin. The interface is much easier to play with compared to the vimscript version.
