### ISSUE TITLE
Option to open live grep in Fuzzy Mode at Start

### ISSUE THREAD

**Issue by maran-e** [ibhagwan/fzf-lua#542]
Is there an option to open live_grep_native in fuzzy mode at start?

```lua
nmap('<leader>z', function() fzf.live_grep_native({ search = vim.fn.expand('<cword>') }) end)
```
I use this mapping to grep a word under cursor. I would then fuzzy search over the grep results. For this I have to switch to fuzzy mode everytime.

Is it possible to pass the grep_string as an option and open it in fuzzy mode at start?

**Comment by ibhagwan** [comment]
It already exists, have you tried pressing `c-g` from live_grep or grep_project? It switches back and forth between the kids while saving the grep/fuzzy strings

**Comment by ibhagwan** [comment]
> Is it possible to pass the grep_string as an option and open it in fuzzy mode at start?

Is it possible to pass the grep_string as an option and open it in fuzzy mode at start?

What about `:lua require'fzf-lua'.grep_cword` (or `grep_cWORD`)?

If you wanted to open a custom string directly at fuzzy mode you use `grep` instead of `live_grep`:
```lua
:lua require'fzf-lua'.grep({ search = "foo" })
```

**Comment by maran-e** [comment]
Thank you very much. That works!

**Comment by kapral18** [comment]
I think the question is still open, how to make it fuzzy by default without having to hit ctrl-g every single time.
Second question how to use live_grep_native with preselected text, not grep. Unless grep is as performant as live_grep_native?

**Comment by kapral18** [comment]
aliright found the answer to first one it's rg_glob = true in grep opts

**Comment by ibhagwan** [comment]
> @ibhagwan aliright found the answer to first one it's `rg_glob = true` in grep opts

That’s incorrect, for fuzzy marching use `grep_project` you’ll then be able to switch to live grep with `ctrl-g`.

**Comment by ibhagwan** [comment]
> Second question how to use live_grep_native with preselected text, not grep. Unless grep is as performant as live_grep_native?

First you have to differentiate between the `live` variants which run a new grep query for every new letter entered at the prompt to the grep variants which feed fzf with a certain result set and then run fuzzy matching on top (grep_project being an “empty” search query `rg`).

So there cannot be a comparison between live_grep_native and grep, only between live_grep and live_grep_narive - whether live_grep or grep_project is better/faster for your needs would depend on the situation at hand, how big is the project and what are you searching for? Is the project really big? Are you looking to match via regex? Use live_grep. If the project is small and you’re looking for a quick fuzzy match? Use grep_project.

Also read this:
https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep

**Comment by ibhagwan** [comment]
Btw, `grep_project` is merely an alias to an “empty search” grep (essentially feeding all project lines into fzf for fuzzy matching):
```lua
:lua require'fzf-lua'.grep({ search = "" })
```

**Comment by kapral18** [comment]
@ibhagwan no I want to be able to search something like 

recommended -- cognitive-complexity.js

Inside giant node_modules folder, so that it finds me all lines with `recommended: ` within files that end with cognitive-complexity.js for example.

To achieve that I assume I need glob, currently how I do it is I live_grep_native -> ctrl-g into fuzzy and add this and it works

But it's super annoying to ctrl-g every single time

**Comment by kapral18** [comment]
Docs say rg_glob affects both grep and live_grep, so docs are incorrect?

**Comment by kapral18** [comment]
![CleanShot 2023-12-12 at 01 30 28](https://github.com/ibhagwan/fzf-lua/assets/1625373/d76a2c4a-0c11-4230-a612-f1bfedfe6717)

**Comment by ibhagwan** [comment]
> I want to be able to search something like
> `recommended -- cognitive-complexity.js`

You can start directly in fuzzy mode with:
```lua
:lua require'fzf-lua'.grep({ search = "recommended -- cognitive-complexity.js", no_esc=true })
```

But that would grep “recommended” within the matched globs, if you wish to start fuzzy and search only inside certain globs do this:
```lua
:lua require'fzf-lua'.grep({ search = "-- cognitive-complexity.js", no_esc=true, rg_glob=true })
```

Use these with `debug = true` and you’ll see how the underlying `rg` command is constructed, hopefully this will help you understand what’s going on under the hood and you can craft the solution that meets your needs.

**Comment by ibhagwan** [comment]
> Docs say rg_glob affects both grep and live_grep, so docs are incorrect?

Docs are correct, but that has nothing to do with fuzzy matching (as you suggested), what `rg_glob` does is enable the parsing of the query and using anything found after `--` as glob arguments to `rg`.

**Comment by kapral18** [comment]
> > I want to be able to search something like
> > `recommended -- cognitive-complexity.js`
> 
> You can start directly in fuzzy mode with:
> 
> ```lua
> :lua require'fzf-lua'.grep({ search = "recommended -- cognitive-complexity.js", no_esc=true, rg_glob=true})
> ```
> 
> But that would grep “recommended” within the matched globs, if you wish to start fuzzy and search only inside certain globs do this:
> 
> ```lua
> :lua require'fzf-lua'.grep({ search = "-- cognitive-complexity.js", no_esc=true, rg_glob=true })
> ```
> 
> Use these with `debug = true` and you’ll see how the underlying `rg` command is constructed, hopefully this will help you understand what’s going on under the hood and you can craft the solution that meets your needs.

where does this `no_esc` come from? I cannot find it in docs. Does this mean that rg_glob only works with that flag on? 

Do rg_opts declared in grep opts affect grep and live_grep in the same way? I tried live_grep_glob it still shows that I am in regex  first.

**Comment by ibhagwan** [comment]
> where does this no_esc come from? I cannot find it in docs.

There are a few options that are yet to be undocumented, you can find these in random issues.

> Does this mean that rg_glob only works with that flag on?

no_esc makes it so special regex chars aren’t escaped, without it `-`, turns into `\-` which will mangle our glob separator.

> Do rg_opts declared in grep opts affect grep and live_grep in the same way? I tried live_grep_glob it still shows that I am in regex first.

rg_grep declared in setup effects both grep and live_grep, however it has nothing to do with which mode opens first.

**Comment by kapral18** [comment]
So let's say I have these bindings that use globs to filter out more or less artefacts to search through

```lua

      {
        "<leader>sg",
        function() require('fzf-lua').grep_project({
          rg_opts = "--column --line-number --no-heading --color=always --smart-case --max-columns=512 --hidden --no-ignore -g '!{.git,node_modules,.next,dist,build,reports,.idea,.vscode,.nyc_output,__generated__}/'",
          winopts = M.win_presets.large.vertical,
          rg_glob = true,
          no_esc = true
        }) end,
        desc = "Grep (excluding .git and node_modules)",
      }
      {
        "<leader>sG",
        function() require('fzf-lua').grep_project({
          rg_opts = "--column --line-number --no-heading --color=always --smart-case --max-columns=512 --hidden --no-ignore -g '!{.git}/'",
          winopts = M.win_presets.large.vertical,
          rg_glob = true,
          no_esc = true
        }) end,
        desc = "Grep (excluding .git)",
      },

```

and I use <leader>sG to go through node_modules

this is what I get

![CleanShot 2023-12-12 at 19 43 12](https://github.com/ibhagwan/fzf-lua/assets/1625373/f560913f-6e70-472d-809a-ea6cbc68c21e)

as you can see via fzflua it doesn't find what's searched with glob

and with vanilla rg it does

what do I do wrong?

**Comment by ibhagwan** [comment]
> what do I do wrong?

Your `leader<sG>` opens `grep` which does fuzzy matching at the prompt, it will only parse glob arguments if passes through the `search=‘ argument, if you wish to parse globs **at the prompt** you can only use live_grep, and then if you want to fuzzy match on top you can press `ctrl-g`.

As I explained before if you want to open the same query with fuzzy matching use grep with search:
```
:lua require'fzf-lua'.grep({ search = "recommended -- *elseif-without-else*, no_esc=true, rg_glob=true, debug=true})
```

Again, I added debug=true so you can explore how the command is formed, play around with it and press ctrl-g and you’ll see that with grep_xxx variants the command never changes, whatever you pass to search= (automatic with ctrl-g) won’t change while you’re fuzzy matching.

**Comment by ibhagwan** [comment]
> as you can see via fzflua it doesn't find what's searched with glob

Perhaps I wasn’t clear enough, grep does not parse globs at the prompt, it’s is fed a single `rg` command (which in your case returned 7392275 lines, the entire project) and then passes command to fzf to do its fuzzy matching, there is no way to restrict globs at that point.

The only way to restrict globs is to do so beforehand via live_grep or the passed via the `search=…` argument.

So if you wish for example to restrict certain globs and open directly in fuzzy mode you’d have to either use live_grep first or use `search`, as I posted before, this would open a glob restricted query directly in fuzzy mode:
```lua
:lua require'fzf-lua'.grep({ search = " -- *elseif-without-else*", no_esc=true, rg_glob=true})
```

**Comment by kapral18** [comment]
can you show an example of how to do it with `live_grep` ? Because everything I try with `live_grep` doesn't work

**Comment by kapral18** [comment]
> :lua require'fzf-lua'.grep({ search = " -- *elseif-without-else*", no_esc=true, rg_glob=true})

The problem with this is that I need to call this entire function for every single string which is way worse than hitting ctrl-g and my initial desire was to get rid of ctrl-g to get it even smoother.

So basically I need to call my own vim.ui.input to prepare a string to then pass into grep or live_grep ?

**Comment by ibhagwan** [comment]
> So basically I need to call my own vim.ui.input to prepare a string to then pass into grep or live_grep ?

Then why not call `:FzfLua grep no_esc=true`? FzfLua will then ask for the input, enter ` -- *elseif-without-else*` (note the space at the start of the search), and you'll be able to use fuzzy matching only on the matched globs.

**Comment by ibhagwan** [comment]
Here you go @kapral18, by calling `FzfLua grep no_esc=true` I use the `Grep For>` prompt to specify the glob (note the space at the start to indicate the glob separator) which then resricts the search to files that aren't `*.lua` (multiple globs are supported btw).

You can see the resulting command in the debug output and the original search term in the header line in red:
![Peek 2023-12-12 11-27](https://github.com/ibhagwan/fzf-lua/assets/59988195/b9e32f26-2783-4259-8d2e-a90568b61401)

**Comment by kapral18** [comment]
@ibhagwan ok now this worked, thank you. Can you show the live_grep one as well? Did you mean to use livegrep in the same manner?

**Comment by kapral18** [comment]
@ibhagwan how can I make this work with grep_cword or grep_visual? let's say I want to have the selection be passed through this subset glob ?

**Comment by ibhagwan** [comment]
> @ibhagwan ok now this worked, thank you. Can you show the live_grep one as well? Did you mean to use livegrep in the same manner?

As I explained before, with `live_grep` the fuzzy interface is disabled, each keypress generates a new `rg` command that is then fed to fzf, note how the globs are changed with each keypress, after I press `ctrl-g` the command is sent to fzf **and is never changed again** (unless you press ctrl-g back to live_grep):
![Peek 2023-12-12 11-34](https://github.com/ibhagwan/fzf-lua/assets/59988195/58cf4a95-e0df-4a4f-b296-098076bd3d3f)

> @ibhagwan how can I make this work with grep_cword or grep_visual? let's say I want to have the selection be passed through this subset glob ?

`grep_cword` and `grep_visual` are simply aliaes that take the word under the cursor or visual selection and then pass these to the `search=...` argument, the code is actually as simple as this:
https://github.com/ibhagwan/fzf-lua/blob/209e9405d2df949cbffe5b7b9329756b83bf2339/lua/fzf-lua/providers/grep.lua#L343-L359

So, in order to pass globs with a prompt to your visual select you'd need to create your own custom function that asks for the `Grep For>` input and then postfixes the search (cword or visual select) with your preferred glob, it's as simple as:
```lua
local fzf = require("fzf-lua")

_G.my_grep_cword = function(opts)
  if not opts then opts = {} end
  opts.search = vim.fn.expand("<cword>")
  local glob = fzf.utils.input("Glob> ")
  if glob then
    opts.search = string.format("%s -- %s", opts.search or "", glob)
  end
  return fzf.grep(opts)
end


-- Call you function with
_G.my_grep_cword()
```

**Comment by kapral18** [comment]
Thanks for clarifying visuals help.

Now I just tried with live_grep_glob and the query again and it works as expected without no_esc by default 

recommended -- *elseif*

properly shows the entry

but live_grep_native with rg_glob on/off doesn't work

if it because there is some fundamental diff there?

**Comment by kapral18** [comment]
is `utils.get_visual_selection()` private api and subject to change I assume?

**Comment by ibhagwan** [comment]
> is `utils.get_visual_selection()` private api and subject to change I assume?

Unless neovim changes something fundamental I don’t see it changing anytime soon.

**Comment by kapral18** [comment]
Thank you for your efforts to explain.  I appreciate it.

**Comment by ibhagwan** [comment]
> Thank you for your time. I appreciate it.

You’re welcome @kapral18.
