### ISSUE TITLE
No files results on VimR

### ISSUE THREAD

**Issue by FahimAnayet** [ibhagwan/fzf-lua#544]
### Info

- Operating System: MacOS
- GUI: VimR
- &#x2612; Shell:
- &#x2612; Terminal: 
- `nvim --version`: v0.9.0 dev
- `fzf --version`: v0.34.0 (brew)

- [x] The issue is reproducible with `mini.sh`

### Description 
Whenever I use neovide or nvim in terminal everything is good. But when I use VimR (a gui flavor of nvim) everything is perfect except `FzfLua files` command. I got no result at all and no errors too.

Thanks for your quick response.

**Comment by ibhagwan** [comment]
There seems to be an open issue for this:
https://github.com/qvacua/vimr/issues/972

I use neovim in the terminal on Linux so I'm not sure how much help I can be here.

**Comment by FahimAnayet** [comment]
Thanks for the quick response. I'll check the issue on VimR. In the meantime if anyone find any similarities and solution feel free to open the thread. Thanks a lot.

**Comment by wookayin** [comment]
Following https://github.com/qvacua/vimr/issues/972#issuecomment-1435115444, I'm also accepting this workaround:

```
  if vim.fn.has('gui_vimr') > 0 then
    vim.env.FZF_LUA_NVIM_BIN = "nvim"
  end
```
