### ISSUE TITLE
pass shell command to file previewer

### ISSUE THREAD

**Issue by gennaro-tedesco** [ibhagwan/fzf-lua#550]
### Description 

I am writing some extensions and I would like to pass a custom (shell) command to the previewer: from the documentation I see one can pass 
```
...
   preview = {
      -- default     = 'bat',           -- override the default previewer?
```
however trying to override it gave me no results (so probably I am doing it wrong). Practically speaking, my example can be reduced to a file picker where the preview is (some modified version of) `grep <something>` in the fzf selected entry: something along the lines of 
```
files = {
   preview = {
      default  = "rg <pattern> {1}"
     -- I also tried function() return os.execute("rg <pattern>") end or similar
```
(by mimicking the syntax in the git pickers).

What is the right way to pass a generic command to the previewer?

**Comment by ibhagwan** [comment]
`preview` expects an fzf-lua previewer you need to either use `previewer` or `fzf_opts['--preview']`, you can even use partial processing and generate your own command on the fly, there are some good examples in the wiki for that:

https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-native-preview

**Comment by gennaro-tedesco** [comment]
Oh yes, `fzf_opts['--preview']` accepts function arguments too, that will do, great!
