### ISSUE TITLE
Horizontal scrolling in a long line?

### ISSUE THREAD

**Issue by shmerl** [ibhagwan/fzf-lua#553]
I just started using fzf-lua so sorry if this sounds like a trivial question (haven't found project discussions section so posting it here).

When for example using `FzfLua files`, it opens two panes one for file list and one for contents preview. Sometimes the path in the file list is pretty long, so it adds `...` to indicate truncated line. Is there a way to horizontally scroll there to see the missing part? Using horizontal arrow keys didn't do it. I figured I can expand the panes with F2 to full width, but that still can potentially hit a very long line.

Thanks!

**Comment by ibhagwan** [comment]
Unfortuntely, this is controlled by the fzf binary and not fzf-lua, not currently supported and doesn't seem to be a plan to implement such feature: https://github.com/junegunn/fzf/issues/2236.

As mentioned in the above issue you can use `--keep-right` via `fzf_opts`:
> Can also be set via the `setup` function
```lua
:lua require'fzf-lua'.files({ fzf_opts = { ['--keep-right'] = '' } })
```
