### ISSUE TITLE
Remapping Escape/Close

### ISSUE THREAD

**Issue by knpwrs** [ibhagwan/fzf-lua#554]
I use `<C-d>` as my escape sequence rather than `<Esc>`. I was able to map this in Telescope, but wanted to switch to FzfLua for performance reasons. Is there a way to map `<C-d>` to close FzfLua?

**Comment by knpwrs** [comment]
It seems like neovim handles `ctrl-d` before it gets sent to fzf and places me in normal mode inside the FzfLua window.

**Comment by ibhagwan** [comment]
> It seems like neovim handles `ctrl-d` before it gets sent to fzf and places me in normal mode inside the FzfLua window.

Then you probably have a global terminal mapping in your neovim config (fzf-lua doesn’t set one), check it with `:verbose tmap <C-d>` to see where it’s coming from.

**Comment by knpwrs** [comment]
That was it, indeed. I had `<C-d>` mapped to `<C-\><C-n>`. I'll probably just get used to the standard mapping.

Thank you!
