### ISSUE TITLE
What highlight group is causing this red background?

### ISSUE THREAD

**Issue by knpwrs** [ibhagwan/fzf-lua#555]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: 0.8.0
- `fzf --version`: 0.30.0

- [ ] The issue is reproducible with `mini.sh`

### Description

When I use FzfLua the files list has a red background:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/174864/198676222-402ab853-3a26-49ba-af86-a6feddb0ef9a.png">

Which highlight group is causing this? I'm having trouble figuring it out from the README.

**Comment by ibhagwan** [comment]
If I were to guess, this is something inherited from your `FZF_DEFAULT_OPTS` in the shell, to override it use `fzf_colors` in the `setup` (`bg` is probably what you’re after), you can use your existing neovim hl groups:
```lua
require'fzf-lua'.setup {
  fzf_colors = {
      ["fg"]          = { "fg", "CursorLine" },
      ["bg"]          = { "bg", "Normal" },
      ["hl"]          = { "fg", "Comment" },
      ["fg+"]         = { "fg", "Normal" },
      ["bg+"]         = { "bg", "CursorLine" },
      ["hl+"]         = { "fg", "Statement" },
      ["info"]        = { "fg", "PreProc" },
      ["prompt"]      = { "fg", "Conditional" },
      ["pointer"]     = { "fg", "Exception" },
      ["marker"]      = { "fg", "Keyword" },
      ["spinner"]     = { "fg", "Label" },
      ["header"]      = { "fg", "Comment" },
      ["gutter"]      = { "bg", "Normal" },
  },
}
```

**Comment by knpwrs** [comment]
I just looked into this a little bit more: I don't have `FZF_DEFAULT_OPTS` set in my shell, and running `fzf` on its own both in my shell and in a floating terminal neovim doesn't result in a red background. I've also copied that snippet you provided verbatim and and I still have the red background.

Is there anything else it could be?

**Comment by knpwrs** [comment]
Err... scratch that. `fzf` running on its own in a floating terminal `does` have the red background, but `FZF_DEFAULT_OPTS` is still not defined in said floating terminal.

**Comment by knpwrs** [comment]
It looks like the red background happens in floating terminals on redraw, so it's not actually related to this plugin:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/174864/199781125-04f117fb-14ec-48fe-835b-d18d58c7ba0e.png">

Still looking into how to fix this though.

**Comment by ibhagwan** [comment]
> It looks like the red background happens in floating terminals on redraw, so it's not actually related to this plugin:
> 
> <img alt="image" width="198" src="https://user-images.githubusercontent.com/174864/199781125-04f117fb-14ec-48fe-835b-d18d58c7ba0e.png">
> 
> Still looking into how to fix this though.

Have you tried different terminals? What happens if you use neovim inside Kitty for example? Could it be another plug-in, try `nvim -u NONE` to test it out.

**Comment by knpwrs** [comment]
It happens in Kitty but not with `nvim -u NONE`. I'll have to start poking at my plugins.

**Comment by knpwrs** [comment]
Found it! It's this plugin: https://github.com/bronson/vim-trailing-whitespace

Now I just need to decide whether to uninstall, disable in certain buffer types, or only enable in markdown...

Thank you for your help!

**Comment by ibhagwan** [comment]
> Found it! It's this plugin: https://github.com/bronson/vim-trailing-whitespace
> 
> Now I just need to decide whether to uninstall, disable in certain buffer types, or only enable in markdown...
> 
> Thank you for your help!
> 
> **EDIT:** I think this change looks nice, the `listchars` don't show up in fzf and I can still highlight trailing whitespace: [knpwrs/dotfiles@b361ed2](https://github.com/knpwrs/dotfiles/commit/b361ed298a06e8570c383c1b6ce8b7ba52599fb4)

Ty for the update!

**Comment by louwers** [comment]
I had a similar issue. I am using [github-nvim-theme](https://github.com/projekt0n/github-nvim-theme).

Calling `require("github-theme").setup()` causes fzf-lua to not apply colors set with `fzf_colors`.
