### ISSUE TITLE
[Feature] Show loading UI for `lsp_references`

### ISSUE THREAD

**Issue by xiaochuanyu** [ibhagwan/fzf-lua#556]
Sometimes it's hard to tell whether there is LSP found 0 references or it's actually still running.
Is there some way of adding indicator UI for wether LSP call finished running/responded?
<img width="214" alt="image" src="https://user-images.githubusercontent.com/1718745/198718778-e1dabefe-f52d-4d52-82f7-72b28147de4d.png">
I have `lsp.async_or_timeout = true` in config.

**Comment by ibhagwan** [comment]
This is controlled by fzf, the indicator is the color of the `<` arrow, you can see the difference if you run `files` on your home directory and notice the color changes when it's done.

It does work nicer with `skim` which looks more like a spinning animation but I wouldn't recommend using it anymore since it's a dead project unfortunately.

**Comment by xiaochuanyu** [comment]
Ah ok I didn't realize that's how it showed in-progress.
I kinda just assumed it was supposed look similar to how fzf works if you just do `fzf` on command line.
![image](https://user-images.githubusercontent.com/1718745/198765726-99dca4f9-5c8c-4d32-b42a-5fe63b246c15.png)

**Comment by ibhagwan** [comment]
This is the indicator while the Fzf pipe is open, the way the LSP async call works Fzf-lua doesn’t see any results until it gets all of them in one go so it can never appear as an incremental feed unfortunately.

You can try changing the `--info=default` (Instead of `inline`), might look different.

**Comment by ibhagwan** [comment]
Just tested, if you change the `--info` setting you'll get the same loading indicator as you posted in your screenshot:
![image](https://user-images.githubusercontent.com/59988195/198898810-bb824121-f805-4b55-8234-cf1ededb2a5c.png)

Change it via `setup`:
```lua
require'fzf-lua'.setup {
  fzf_opts = { ['--info'] = 'default' },
  -- your other settings
  ...
}
```

Or send it in the call options (or in your key mapping), e.g.:
```lua
:lua require'fzf-lua'.lsp_workspace_symbols({ fzf_opts = { ['--info'] = 'default' } })
```

**Comment by ibhagwan** [comment]
Apparently this is intentional: https://github.com/junegunn/fzf/issues/619
