### ISSUE TITLE
I would like to buy you a coffee

### ISSUE THREAD

**Issue by Artem-Schander** [ibhagwan/fzf-lua#561]
Sorry I didn't fill out the issue template :)
I really like this implementation of FZF.
Is there a way to support this work financially?

**Comment by ibhagwan** [comment]
> Sorry I didn't fill out the issue template :)
> I really like this implementation of FZF.
> Is there a way to support this work financially?

Tysm for the kind words and generous offer @Artem-Schander  :)

I do this for fun and my own small contribution to the open source community, no donations are necessary.

**Comment by Artem-Schander** [comment]
I understand. Thank you for your efforts, I really appreciate it
