### ISSUE TITLE
not working on macOS (find: -printf: unknown primary or operator)

### ISSUE THREAD

**Issue by fegyi001** [ibhagwan/fzf-lua#564]
### Info

- Operating System: MacOS Ventura 13.0
- Shell:
- Terminal: iTerm2
- `nvim --version`: v0.8.0
- `fzf --version`: 0.34.0 (installed via homebrew)

- [] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
I'm on Mac, and the fuzzy finder does not work at all. It cannot find the `-printf` option for `find` (it does not exist for `find` on Mac). I see the following screen: 

```sh
find: -printf: unknown primary or operator
```

I use a basic setup of `fzf-lua`. I'm quite new to nvim.

<img width="1337" alt="Screenshot 2022-11-07 at 23 00 53" src="https://user-images.githubusercontent.com/4125222/200425496-9f5e436f-eabd-4640-8113-77a3bdc4f33b.png">

**Comment by ibhagwan** [comment]
It seems you don’t have `rg` or `fd` installed, in this case fzf-lua defaults to `find` and the default opts for fine use `printf` which requires GNU find.

Either install `rg` or `fd` or modify the default find options in setup:
> check the below command works in your shell first
```lua
require('fzf-lua').setup({
  files = { cmd = 'find -type f' }
})
```

**Comment by fegyi001** [comment]
Wow, it works now. It is blazingly fast also for big projects (compared to Telescope), thanks a lot!

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/4125222/200540468-0675c08c-458f-4250-bdf0-ae771d4a31a6.png">
