### ISSUE TITLE
Replace current buffer

### ISSUE THREAD

**Issue by jryom** [ibhagwan/fzf-lua#565]
With `fzf.vim` I always used the `enew` window layout, which would simply render fzf in current buffer instead of either a split or a floating window. 

Is there a way to achieve this with `fzf-lua`?

And thanks for your work on this plugin, it's sublime 🙏

**Comment by jryom** [comment]
Nevermind, just found out I can achieve this by passing `enew` to `winopts.split`.

**Comment by ibhagwan** [comment]
Ty @jryom!

TIL about `enew` :)

A similar alternative which would then also support preview rotation (with `f5/6`) is to use `fullscreen`, won’t be exactly the same as it will still be a floating window but you can disable it’s border and make it look very similar.
