### ISSUE TITLE
Changing vim.lsp.protocol.CompletionItemKind to display icons breaks other plug-ins

### ISSUE THREAD

**Issue by tssm** [ibhagwan/fzf-lua#568]
Hi! Thanks for this plugin, I'm really happy with it 🙂

The only issue I've found so far is that it relies on the user setting `vim.lsp.protocol.CompletionItemKind` to a custom value to display icons for `lsp_document_symbols`, `lsp_live_workspace_symbols` and `lsp_workspace_symbols`. According to [`:h vim.lsp.protocol`](https://neovim.io/doc/user/lsp.html#vim.lsp.protocol), that value should be treated as a constant:

> Module `vim.lsp.protocol` defines constants dictated by the LSP specification, and helper functions for creating protocol-related objects.

In fact, changing the value, or installing a plugin like lspkind.nvim (which does it for the user) breaks other plug-ins that relay on the default value (as stated [here](https://github.com/hrsh7th/nvim-cmp/issues/39#issuecomment-903093219)).

I know it's annoying to have to add yet another configuration variable, specially if we want the same icons all over the place, but I had to go back to the default `vim.lsp.protocol.CompletionItemKind` because changing it breaks the Noice's pop-up on my set-up.

I've looked at fzf-lua code, and it doesn't seem to be too hard to make the change. Would you be interested on a pull request with it? If not, I can patch it for myself, but I think more users will benefit from it (it took me a while to realise what was the problem)

**Comment by ibhagwan** [comment]
I would prefer to avoid yet another config option as there are already way too many, this does sound like a unique requirement, why don’t you use a combination of `symbol_style` and `symbol_fmt` to extract the icons from wherever you prefer? See https://github.com/ibhagwan/fzf-lua/issues/443 for more info.

**Comment by tssm** [comment]
It didn’t occur to me to use `symbol_fmt`, thanks for the help, I’ll go that route 🙂

I’ll close this, but I want to point out that `vim.lsp.protocol.CompletionItemKind` is there to be read, in case other users encounter the issue in the future. Changing it may break any other plug-in that relies on its value

**Comment by ibhagwan** [comment]
> It didn’t occur to me to use `symbol_fmt`, thanks for the help, I’ll go that route slightly_smiling_face
> 
> I’ll close this, but I want to point out that `vim.lsp.protocol.CompletionItemKind` is there to be read, in case other users encounter the issue in the future. Changing it may break any other plug-in that relies on its value

Thanks for letting me know, I wasn't aware of that, neverthless fzf-lua only reads it without any modifications.

**Comment by tssm** [comment]
Right, I was thinking about `symbol_style`, it kinda directed me in the direction of messing around with `vim.lsp.protocol.CompletionItemKind`, and now it feels redundant. Anyway, thanks for the help, and for the plug-in again :)
