### ISSUE TITLE
Question: How to make the current buffer in `FzfLua buffers` selectable but do nothing?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#569]
### Description 

As title. I'm trying to simulate the App switching functionality, i.e. cmd+tab, of macOS':

1. Each currently opened App is selectable.
2. Do nothing when the same App is selected.

But here in neovim, the targets I want to switch are buffers.

### Reasoning

The reason behind this is that: For me, these are the tedious steps (I'm not saying FzfLua is the cause) to switch between buffers on the current window:

1. Run `FzfLua buffers`.
3. Change selection.
4. Press the specified keymap to confirm the selection.

While I would be very happy if this process can be done in the macOS way:

1. Press cmd+tab to show the horizontal list of running Apps. (On neovim side, I want to use FzfLua for showing the list)
2. Holding cmd to keep the list shown, and change selection via tab or `.
3. release cmd to confirm the selection.

To be more clear, these are all the problems I need to solve:

1. The current buffer can be selected, and do nothing on confirmation.
2. There is a way to customize the window position/size just for the command `FzfLua buffers`. (**DONE**)
3. Trying to detect the "release key" event on neovim to achieve "release to confirm" action.
4. Make the keymap for `FzfLua buffers` the same as the "choose next" action when the fzf-lua floating terminal is open.

I hope I can solve the 1. step with your help. Thanks in advance.

**Comment by nyngwang** [comment]
**update**:

> 2. There is a way to customize the window position/size just for the command `FzfLua buffers`.

I just solved this with an old issue(I once read it but forgot).

<img src="https://user-images.githubusercontent.com/24765272/204272568-ab9918cc-c2dc-4387-aed9-889ecaf4d376.png" width="500">

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/cea72a81099c6a79fd3f561b168ccf7c2882965f, update and run:
```lua
:lua require'fzf-lua'.buffers({ fzf_opts = { ["--header-lines"] = false }})
```

**Comment by nyngwang** [comment]
@ibhagwan Could you elaborate more on the difference between adding this line for just `.buffers` and putting it in the `setup {...}`? I'm trying to understand this option. (The docs of fzf doesn't explain what will happen when the value is `false` too)

**Comment by ibhagwan** [comment]
It’s like any other option you can either add it to setup under `buffers` or send it in the mapping:
```lua
setup({
  buffers = { fzf_opts = { ["--header-lines"] = false },
  …
})
```

Setting it to `false` tells FzfLua to avoid sending this to the Fzf binary (which is what buffers does to to set the current buffer header).

**Comment by nyngwang** [comment]
@ibhagwan Thanks for your clear explanation, let me close this :)
