### ISSUE TITLE
Could we have a list of string passing into the `setup.keymap`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#571]
### Description 

As title. Is it possible to achieve something like this? Or there is some existing way to achieve the same result (entering fullscreen and open the preview). Thanks in advance!

```lua
keymap = {
  builtin = {
    ['<F1>']        = { 'toggle-fullscreen', 'toggle-preview' },
    -- ['<F2>']        = 'toggle-preview',
    -- ['<F3>']        = 'toggle-preview-cw',
    -- ['<F4>']        = 'toggle-preview-ccw',
    -- ["<S-down>"]    = "preview-page-down",
    -- ["<S-up>"]      = "preview-page-up",
    -- ["<S-left>"]    = "preview-page-reset",
  }
},
```

**Comment by ibhagwan** [comment]
Not possible, what’s the point of this if I may ask?

**Comment by nyngwang** [comment]
To @ibhagwan:

> [...], what’s the point of this if I may ask?

I recently like the idea of minimal UI before manually calling any functions. So I move fzf-lua to the center of my screen and disable the preview window. When I need to preview a hovered item, I will always call the two actions in sequence: `toggle-preview`, `toggle-fullscreen`. But this will cost two keypress. It will be good if I can just use one keymap to complete the task.

**Comment by ibhagwan** [comment]
I have a similar workflow in my neovim config to review git changes, I open git status, make it full screen and then make the tmux pane also fullscreen using `<tmux prefix>-Z`, IMHO, this is better achieved using your own customization, I don’t plan on adding this functionality into fzf-lua as it adds unnecessary complexity into the bind logic.

My code if you wish to take a look:

https://github.com/ibhagwan/nvim-lua/blob/6fc689c5f14fe9f0850f47622613ddb07ec51061/lua/plugins/fzf-lua/init.lua#L161-L186

**Comment by nyngwang** [comment]
@ibhagwan You're right, I complicated the problem. With your config, I came up with the following solution: (You might know how to improve it)

```lua
local NOREF_NOERR_TRUNC = { noremap = true, silent = true, nowait = true }
vim.keymap.set('t', '<F1>', function ()
  if vim.bo.filetype == 'fzf' then
    require('fzf-lua.win').toggle_preview()
    require('fzf-lua.win').toggle_fullscreen()
  end
end, NOREF_NOERR_TRUNC)
```

Thanks again for your beautiful plugin -- fzf-lua :) This issue can be safely closed now!

**Comment by ibhagwan** [comment]
Great! will close :-)
