### ISSUE TITLE
It seems that `FzfLua live_grep_glob` wouldn't jump to the word when working with neo-tree.nvim

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#572]
### Description 

As title. This is probably an edge case that would rarely happen and/or it would only happen on each new session once. The process I reproduced the bug:

1. I opened neovim (so a new session just started) and then directly change project root(I use the code you shared from an old issue to switch between projects).
2. Then I pressed a key-binding to trigger a lua function which calling `FzfLua live_grep_glob` to grep a word that is located in a Lua file(~700 lines). Notice that this file will be the first Lua file in the session.
3. ~~Now, it seems that because of "jump to the word" action is called before the LSP `sumneko/lua-language-server` got started, the cursor stops at the first line of that Lua file.~~

Since I'm not sure whether my assumption on step 3. is correct, I need some help. Thanks in advance!

**UPDATE**: It turns out this is a cross-plugin problem and not related to Lua LSP. During the testing, I uninstalled neo-tree.nvim and ran command `:LspStop` to stop the Lua LSP, the problem disappeared.

## DEMO

https://user-images.githubusercontent.com/24765272/204750634-fe3a4641-e1bc-430a-97e2-836a8c75dea9.mov

**Comment by ibhagwan** [comment]
The reason must be different, go to line shouldn’t be affected by the LSP functionality, maybe you have an autocmd that does something once the LSP on_attached is called?

**Comment by nyngwang** [comment]
OK, I will try to debug starting from some suspected `autocmd`s.

**Comment by nyngwang** [comment]
The problem disappeared after I uninstalled `neo-tree.nvim`, but since that project is large it will take some time to find those specific lines that cause this issue.

**Comment by nyngwang** [comment]
@ibhagwan I'm happy that I just found the culprit! But while I now know how to eliminate the problem I don't actually know *why* it can work.

I have to add the following check to move the cursor out of neo-tree buffer so as to make `live_grep_glob` work without this issue.

```lua
vim.keymap.set('n', '<C-f>', function ()
  if vim.bo.filetype == 'neo-tree' then vim.cmd('wincmd h') end -- This line to be specific.
  require('fzf-lua').live_grep_glob({ actions = { ['ctrl-f'] = 'abort' } })
end, NOREF_NOERR_TRUNC)
```

And I remember that I did add this check months ago and "refactor" it out recently because I forgot what it is for.

**Comment by ibhagwan** [comment]
> @ibhagwan I'm so happy that I just found the culprit! The problem is eliminated now **BUT** I don't actually know why it can work. I have to do the following check before calling the `live_grep_glob` API of fzf-lua:
> 
> ```lua
> vim.keymap.set('n', '<C-f>', function ()
>   if vim.bo.filetype == 'neo-tree' then
>     vim.cmd('wincmd h') -- This line to be specific. I use `h` because my filetree is on the right-hand side.
>   end
>   require('fzf-lua').live_grep_glob({ actions = { ['ctrl-f'] = 'abort' } })
> end, NOREF_NOERR_TRUNC)
> ```
> 
> And I remember that I did add this check months ago but I accidentally "refactored it out" because I forgot what it is for.

I honestly do not know, I would assume it has something to do with neotree autocmds, you’re probably better off asking there, all fzf-lua does is attempt to move the cursor to the correct line.

**Comment by nyngwang** [comment]
@ibhagwan Got it! Closing.
