### ISSUE TITLE
Cannot select single entries with blines or lines

### ISSUE THREAD

**Issue by bagohart** [ibhagwan/fzf-lua#573]
Hi, cool plugin! I'm currently trying to migrate from `fzf.vim` and have now stumbled over the following issue:

### Info

- Operating System: Manjaro
- Shell: Fish
- Terminal: Kitty
- `nvim --version`: 0.8.0
- `fzf --version`: 0.35.1 (b55f555)

- [x] The issue is reproducible with `mini.sh`

### Description 

If I use `FzfLua blines` or `FzfLua lines` on any buffer and select a single entry with `<CR>` then nothing happens, the floating window closes and the cursor didn't move. The quickfix list stays empty, too. If I select a single entry with `<Tab>` and then click `<CR>` on the same or another entry, the same happens.

If I select at least two entries with `<Tab>`, then those entries are selected and end up in the quickfix list. If I select two entries with `<Tab>` and close the menu with `<CR>` on an entry that was not previously selected with `<Tab>`, then that entry will not be part of the quickfix list - I'm not sure if this is the desired behaviour.

### Expected behaviour
Selecting a single entry with `<CR>` should definitely move the cursor to said entry, and maybe (not sure) add it to the quickfix list.\
When selecting two entries with `<Tab>` and then pressing `<CR>` on an unselected entry, the quickfix list should (not sure) be filled with all three entries.

**Comment by ibhagwan** [comment]
> If I select at least two entries with <Tab>, then those entries are selected and end up in the quickfix list. If I select two entries with <Tab> and close the menu with <CR> on an entry that was not previously selected with <Tab>, then that entry will not be part of the quickfix list - I'm not sure if this is the desired behaviour.

I’m not sure about “desired” but this is how fzf works, when using multi-select the fzf binary (which fzf-lua relies upon) will only output the selected entries.

> Selecting a single entry with <CR> should definitely move the cursor to said entry, and maybe (not sure) add it to the quickfix list.

This is unintended, the default behavior should take you to the selected line, does the cursor go to the correct line after using `grep_projecf` for example? How about `grep_curbuf`?

I’m trying to understand if this issue is related to not being able to move the cursor in general or is limited just to lines/blines.

**Comment by x86taha** [comment]
`grep_curbuf` works just fine. As far as I can tell there is definitely an issue is with `blines`: `actions.buf_edit` does nothing

**Comment by ibhagwan** [comment]
You're absolutely correct! seems I introduced this in https://github.com/ibhagwan/fzf-lua/commit/cea72a81099c6a79fd3f561b168ccf7c2882965f while accomodating #569, hang on will be fixed soon :-)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/0c8b3389ec433089ebbe9d138c2ec20a6a542ce0 - should work now, ty for the report!

**Comment by bagohart** [comment]
Wow, that was faster than I could answer the intermediate questions, thanks a ton!
It works now for me too, both lines and blines work now as I expected.

(Besides, I had also already tried it with `buf_split, buf_tabedit, buf_vsplit` and also some versions of grep, I had just forgotten to add it to my initial post, sorry about the omission...)
