### ISSUE TITLE
FR: is it possible to toggle preview to `FzfLua git_commits`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#574]
### Description 

As title. I really need to preview what I have done in a specific commit. Is it possible with current implementation?

**Comment by ibhagwan** [comment]
What do you mean? There already is a preview for all git commands, that includes `git_commits`, look at the default options under `git.commits.preview` and change it to whatever you want, I personally use it to preview my commits with [git delta](https://github.com/dandavison/delta).

**Comment by nyngwang** [comment]
@ibhagwan:

OK, I just reviewed my config and realized that I've been using the following config that seems to disable the default behavior of all fzf-lua git commands. I remember that I was solving a problem in my front-end project where there are some machine-generated compressed js files, which caused serious lagging due to lines with more than 200 characters. And at that time there was no other better solutions.

```lua
  previewers = {
    git_diff = {
      cmd_deleted = 'git diff --color HEAD %s | cut -c -200',
      cmd_modified = 'git diff --color HEAD %s | cut -c -200',
      cmd_untracked = 'git diff --color --no-index /dev/null %s | cut -c -200',
    }
  },
```

Are these the only related config? And how to achieve both "disable preview on files with some >200 chars lines" and "enable preview on normal files"?

**Comment by ibhagwan** [comment]
This all comes from the fact that these are different previews, the previewers that use the fzf binary have different functionality and are also lacking some features that the neovim previews have (due to technical limitation, for example, rotate preview), if you wish to toggle previews automatically you’d have to do so by sending the toggle preview keybind to the terminal.

**Comment by nyngwang** [comment]
@ibhagwan Let me close as this can be solved by reading `man fzf`. And thanks for reading all my issues!
