### ISSUE TITLE
Inconsistent `preview-page-up/down` between `FzfLua git_status` and `FzfLua files`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#576]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: `NVIM v0.9.0-dev-431+gaa4921273`
- `fzf --version`: `0.35.1 (brew)`

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  keymap = {
    builtin = {
      ['<S-up>'] = 'preview-page-up',
      ['<S-down>'] = 'preview-page-down',
    },
    fzf = false,
  },
})
```
</details>

### Description 

With keys comb. Shift + Up/Down, the preview of `git_*` commands will scroll one line up/down at a time. While the preview of `files` seems to scroll half-page at a time. I expect that both should have the same behavior (if possible). I prefer the half-page one, but I think providing new options like `preview-line-up/down` will be great.

**Comment by ibhagwan** [comment]
This is because you are using different previews, files uses neovim builtin previewer and git uses fzf’s previewer which behaves slightly differently, that said, fzf previewer should still scroll half pages up/down, I suspect this is something related to your setup (maybe $FZF_DEFAULT_OPTS in the shell?).

**Comment by nyngwang** [comment]
The `echo $FZF_DEFAULT_OPTS` output nothing both inside(terminal buffer) and outside(directly from zsh).

**Comment by ibhagwan** [comment]
> The `echo $FZF_DEFAULT_OPTS` output nothing both inside(terminal buffer) and outside(directly from zsh).

I can't say with certainlty what the issue is but it has to do with your specific setup, I just tested it again with `mini.sh` and it work as execpted, if your case is different I would start troubleshooting `fzf --preview` at the shell level.

**Comment by nyngwang** [comment]
@ibhagwan My apologies for answering in hurry. I will close the other thread as soon as possible. I forgot to mention that I indeed loaded these options during my testing:

```lua
require('fzf-lua').setup {
  fzf_cli_args = '-i', -- Case-Insensitive for: `Fzf files`, `buffers`.
  fzf_opts = {
    ['--cycle'] = '',
    ['--info'] = 'default', -- UI related: show item-list count, e.g. (42/42), on the next line.
    ['--header-lines'] = false, -- make current buffer selectable by `FzfLua buffers`.
  },
```

Would this impact the env. variable you just mentioned?

**Comment by ibhagwan** [comment]
Run this in the shell and see if scrolling works as expected (this is exactly what fzf-lua does):
```sh
fzf --preview="cat {}" --preview-window="nohidden:down:50%" --bind="shift-down:preview-page-down,shift-up:preview-page-up"
```

The options you describe above shouldn't change thre preview behavior but it wouldn't hurt to test with and without, does running fzf-lua with `mini.sh` work as expected or still has the same issue?

**Comment by nyngwang** [comment]
> Run this in the shell [...]

This scroll either half-page or full-page (I'm not pretty sure) and this is expected and I don't want to scroll one line at a time.

I will test it with mini.sh again.

**Comment by nyngwang** [comment]
@ibhagwan Yes, with mini.sh only (I changed the colorscheme since the default one so hard to read) the Shift+Up/Down will scroll 1-page at a time, and this is expected. As demo:

https://user-images.githubusercontent.com/24765272/205442981-55c54848-55b3-4991-abfa-ed6703d201f3.mov

But the problem is that this testing is in different start condition than the one I have reported. That is how do I add these lines to mini.sh? (I ran the terminal command `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"` to start neovim)

```lua
keymap = {
    builtin = {
      ['<S-up>'] = 'preview-page-up',
      ['<S-down>'] = 'preview-page-down',
    },
    fzf = false,
  },
```

**Comment by ibhagwan** [comment]
> @ibhagwan Yes, with mini.sh only (I changed the colorscheme since the default one so hard to read) the Shift+Up/Down will scroll 1-page at a time, and this is expected. As demo:

Not sure I understand, the demo appears to work as expected, the preview scroll does seem to scroll page up/down and not one line at a time.

> But the problem is that this testing is in different start condition than the one I have reported. That is how do I add these lines to mini.sh? (I ran the terminal command `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"` to start neovim)

```lua
keymap = {
    builtin = {
      ['<S-up>'] = 'preview-page-up',
      ['<S-down>'] = 'preview-page-down',
    },
    fzf = false,
  },
```
I'm not sure if the above works, as explained in the README, if you wish the disable all of the default options sent to fzf you need to have an empty table not `false`:
```lua 
keymap = {
    builtin = {
      ['<S-up>'] = 'preview-page-up',
      ['<S-down>'] = 'preview-page-down',
    },
    fzf = {},
  },
```

**Comment by nyngwang** [comment]
@ibhagwan Yes, I did test it with both `false` and `{}`. (when I was trying to solve this I read an issue saying that it can be set to `false`. I didn't know that it is outdated.) And now I just tested it again (I didn't use the `mini.sh` this time since I cannot set these configs) with `{}` but still get the same result. I will think about a way to delete my current config and use the mini.sh to test again.

**Comment by ibhagwan** [comment]
Maybe I can help you better if I understand the issue better which I'm not even sure I am...

Whether `false` or `{}` works might not be the cause here at all, I don't understand why do you expect  fzf preview scroll to work if you're disabling the fzf binds, without specifying a keybind under `keymap.fzf` you aren't telling fzf what keys to use to scroll the preview up/down, what happens if you add these?
```lua
keymap = {
    builtin = {
      ['<S-up>'] = 'preview-page-up',
      ['<S-down>'] = 'preview-page-down',
    },
    fzf = {
      -- These lines must exist to let fzf know you want to use preview scrolling
      ["shift-down"] = "preview-page-down",
      ["shift-up"]   = "preview-page-up",
    },
  },
```

**Comment by nyngwang** [comment]
@ibhagwan:
> [...] I don't understand why do you expect fzf preview scroll to work if you're disabling the fzf binds [...]

Lol, sorry for causing confusion. I was thinking about I was replying to #574. For #574 I expect it to not scroll when I pass either `false` or `{}` as the value. But the truth is that it still scrolls in a strange way: one line at a time.

And for this issue: you're right. I should test it with the config you just gave.

**Comment by ibhagwan** [comment]
From `man fzf` I see there's an `ignore` option, try this:
```lua
keymap = {
    builtin = {
      ['<S-up>'] = 'preview-page-up',
      ['<S-down>'] = 'preview-page-down',
    },
    fzf = {
      ["shift-down"] = "ignore",
      ["shift-up"]   = "ignore",
    },
  },

```

**Comment by nyngwang** [comment]
@ibhagwan This question can be closed as with the following config it does scroll 1-page at a time:

```lua
fzf = {
      -- These lines must exist to let fzf know you want to use preview scrolling
      ["shift-down"] = "preview-page-down",
      ["shift-up"]   = "preview-page-up",
    },
```

I did ask a bad question cus I use `fzf = false` when I tested it. I will copy and link your reply above this comment to #577 as this will make things clear.

**Comment by ibhagwan** [comment]
> I did ask a bad question cus I use fzf = false when I tested it. I will copy and link your above reply to https://github.com/ibhagwan/fzf-lua/issues/577 as this will make things clear.

I may be wrong indeed, I can't remember every single issue and it's intricacies :-)
