### ISSUE TITLE
Setting `keymap.fzf` to `false` doesn't disable all the default keymaps

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#577]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: `NVIM v0.9.0-dev-431+gaa4921273`
- `fzf --version`: `0.35.1 (brew)`

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  keymap = {
    builtin = false,
    fzf = false,
  },
})
```
</details>

### Description 

As title. In my config provided above, I have set both `keymap.bulitin`, `keymap.fzf` to `false`. Now if I press Shift + Up/Down in `FzfLua files` the previewer will not scroll (this is expected.), but this is not the case when in `FzfLua git_status`.

**Comment by ibhagwan** [comment]
As I wrote in the other issue, git uses fzf’s builtin previewer, it comes with its own set of binds (`man fzf`), you’d need to specifically disable these if you wish to achieve such behavior, you also want to check what you’re inheriting from shell via $FZF_DEFAULT_OPS.

**Comment by nyngwang** [comment]
@ibhagwan Sorry about creating many issues. I thought this would be a different problem and I would have to separate different problems. Let me close this and answer your question there.

**Comment by nyngwang** [comment]
> From man fzf I see there's an ignore option, try this:
> 
> keymap = {
>     builtin = {
>       ['<S-up>'] = 'preview-page-up',
>       ['<S-down>'] = 'preview-page-down',
>     },
>     fzf = {
>       ["shift-down"] = "ignore",
>       ["shift-up"]   = "ignore",
>     },
>   },

**Comment by nyngwang** [comment]
@ibhagwan: You're right! `ignore` does work as shift+up/down no longer scroll. Sorry for my carelessness (I was creating issues at the time when I was also trying to resolve some conflicts of a project...) So there is no wrong with fzf-lua, but my brain is wrong. I will help you improve the documentation on how to disable the scroll with `ignore`. Will send a PR asap.

**Comment by ibhagwan** [comment]
> @ibhagwan: You're right! `ignore` does work as shift+up/down no longer scrolls. Sorry for my carelessness and I should look up the manual myself (I was creating issues at the time when I was also trying to resolve some conflicts of a project...) So there is no wrong with fzf-lua, but my brain is wrong. I will help you improve the documentation on how to disable the scroll with `ignore`. Will send a PR asap.

No need for a PR for this, this is very specific and I don't believe many pepole will look for this, if you wish to help you can improve on the Wiki and explain in details what's the the difference between the previewers and how to set their bindings, what is the difference between `keymap.fzf` and `keymap.builtin`, how to test it with fzf in the shell and how to find the available options using `man fzf`, the Wiki is open edit to all :-)
