### ISSUE TITLE
[Question] How to extend the behavior of `<ctrl-x>` for `:FzfLua buffers` via `.setup`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#578]
### Description 

I have tried the following config but `ctrl-x` still triggers the old behavior: delete the selected buffer.:

```lua
.setup {
  actions = {
    buffers = {
      -- ...
      ['ctrl-x'] = function (selected, opts)
        print(selected[1])
      end
    }
  }
}
```

What I ultimately want to achieve is to extend the default behavior:

1. Use the default behavior of `ctrl-x` on normal buffers.
2. If the selected buffer is a terminal buffer, then run the force version `bd! term_buf_id`.

I want to do so because these terminal buffers are usually not deletable via the default action.

Thanks in advance.

**Comment by nyngwang** [comment]
After some trying I got the following code sometimes working sometimes not:

```lua
['ctrl-x'] = function (selected, opts)
  for _, sel in ipairs(selected) do
    local buf_id = sel:match('%[(%d+)')
    if vim.api.nvim_buf_get_option(tonumber(buf_id), 'buftype') == 'terminal' then
      M.vimcmd_buf('bd!', buf_id, opts)
    else
      actions.buf_del(selected, opts)
    end
  end
  actions.resume(selected, opts)
end
```

And, I also found that my calling of `actions.resume` caused the blinking problem: the fzf-lua menu is closed and opened. While I expect it to keep open.

**Comment by ibhagwan** [comment]
From the README:
```lua
buffers = {
    prompt            = 'Buffers❯ ',
    file_icons        = true,         -- show file icons?
    color_icons       = true,         -- colorize file|git icons
    sort_lastused     = true,         -- sort buffers() by last used
    actions = {
      -- actions inherit from 'actions.buffers' and merge
      -- by supplying a table of functions we're telling
      -- fzf-lua to not close the fzf window, this way we
      -- can resume the buffers picker on the same window
      -- eliminating an otherwise unaesthetic win "flash"
      ["ctrl-x"]      = { actions.buf_del, actions.resume },
    }
  },
```

As explained above, to prevent the flicker you need to set the handler to a table instead of a function with the first function being your custom handler:
```lua
buffers = {
      ["ctrl-x"] = {
        function (selected, opts)
          print(selected[1])
          actions.buf_del(selected, opts)
        end,
        actions.resume
      },
    }
  },
```

**Comment by nyngwang** [comment]
@ibhagwan Thank you! Let me close this too!
