### ISSUE TITLE
Error executing vim.schedule lua callback: Garbage after pattern: +//.+$+

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#58]
I'm getting the following error when scrolling through `fzf-files`

```
Error executing vim.schedule lua callback: ...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:177: Error executing lua:
...k/packer/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:178: Vim(syntax):E402: Garbage after pattern: +//.+$+
Press ENTER or type command to continue
```

**Comment by ibhagwan** [comment]
Just committed a fix, feel free to close the issue if it works.

**Comment by kdheepak** [comment]
My bad this was an issue with my configuration! Thanks for helping me figure it out!

**Comment by ibhagwan** [comment]
> My bad this was an issue with my configuration! Thanks for helping me figure it out!

Ty for helping me add code to avoid an error on faulty filetype configurations :)
