### ISSUE TITLE
Allow fzf to search horizontally deeper? (for compressed files)

### ISSUE THREAD

**Issue by crates51** [ibhagwan/fzf-lua#580]
### Info

- Operating System: Linux, Ubuntu 20.04
- Shell: zsh
- Terminal: st
- `nvim --version`: NVIM v0.8.1

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup{
  winopts = {
    --fullscreen = true,
  },
  fzf_opts = {
    ['--layout'] = "default",
    ['--keep-right'] = ''
  },
  files = {
    rg_opts = "--color=never --files --hidden --follow --no-ignore -g '!.git' -g '!vimlog' -g '!.mypy*' -g '!__pycache__' -g '!.pytest_cache'",
  },
  grep = {
    rg_opts = "--column --line-number --no-heading --color=always --hidden -g '!.git' -g '!vimlog'",
    },
  keymap = {
    fzf = {
      ["ctrl-q"]         = "select-all+accept",
    }
  }
}

```
</details>

### Description 

Hello, I have a compressed json file, 1501 chars long exactly (1 line with 1501 chars)
lua require('fzf-lua').grep() finds that file, no problemo, but i cannot find words deep inside that compressed json/line/file

To be clear, it finds words, in the beginning of the line, but it cannot find words after ~370 chars

So.. my problem is that the word at the 1300 char position cannot be find by grep :-/

I'm wondering, is there some kind of option to allow grep/fzf search deeper horizontally inside lines? Some kind of limit i can overwrite?

To closest issue i could find is [#392](https://github.com/ibhagwan/fzf-lua/issues/392) but that doesnt really help me.. 

Cheers !

**Comment by ibhagwan** [comment]
The happens is due to the the default rg options limiting the columns to 512 (for perf reasons), you can override the default command and remove the max columns flag:
```lua
require('fzf-lua').setup {
  grep = {
    -- the default command:
    -- cmd = 'rg --column --line-number --no-heading --color=always --smart-case --max-columns=512',
    cmd = 'rg --column --line-number --no-heading --color=always --smart-case'
  }
}
```
Can also run it directly (or in a mapping):
```lua
:lua require('fzf-lua').grep({ cmd = 'rg --column --line-number --no-heading --color=always --smart-case' })
```

**Comment by crates51** [comment]
Something is not right..

For example having 

<details>
<summary>this list of random names:</summary>


`Maisy Gillespie Tianna Grant Alexandra Greene Tomasz Myers Dale Conner Sebastian Mcintosh Jaydon Miranda Saira Miles Cain Dillon Polly Cortez Jude Dyer Ella-Louise Bernard Ellie-Mae Harrington Abdur Archer Charis Eaton Chantelle Kaufman Sarah Howard Umar Holden Kaan Li Isla Gibson Remi Barry Zain Neal Cindy Garcia Chelsey Rosales Elouise Lynch Gerard Irwin Louie Vincent Kade Kerr Garfield Benson Safaa Yates Maxim Morrow Teddy Lester Johnathan Melendez Charles Giles Ruben Orr Christian Brady Holly Booth Angus Haynes Victor Case Donald Harrell Jermaine Burch Howard Beltran Sonia Carlson Wade Anderson Rosanna Hebert Meredith Bolton Marc Burns Raihan Chambers Briony Cannon Orla Frye Zac Hanson Yash Haas Darren Cunningham Colin Aguirre Jeremiah Cooke Abbey Webb Sulaiman Chaney Darius Steele Dana Weiss Rupert Roth Saoirse Garner Blanche Hensley Riya Donaldson Andreas Oconnell Everett Brandt Regan Flores Caitlin Reeves Callum Allison Caleb Mcdonald Ciara Mckay Ria Matthams Karina Saunders Rhiannon Valdez Milly Moss Jean Powell Ismaeel Stephens Dan Matthews Markus Cohen Alexa Sanchez Jakob Ibarra Naima Christensen Audrey Hicks Tamzin Rosario Steven Houston Lacey Foster Keyaan Hall Owen Mccall Hasan Robertson Bradley Macdonald Bertha Dale Amie Fox Sanaa Martin Aiden Jordan Karol Freeman Walter Lowery Faith Baldwin Lukas Combs Susannah Walters Saba Donnelly Kabir Yoder
`
</details>

on one line;

_Ria_ - which is on position 969- appears (with or without `--max-columns` argument) in the search

But the next name, _Matthams_ - which is on position 973 - doesn't apear on search (with or without `--max-columns` argument)


From what is see on [rg documentation](https://www.mankier.com/1/rg#--max-columns), that setting is to not print the entire line,
and from my tweakings( setting --max-columns=700 for example) it print something like _[Omitted long line with 1382 matches]_


What i am trying to do is to print all names, indifferent of position

**Comment by ibhagwan** [comment]
> But the next name, Matthams - which is on position 973 - doesn't apear on search (with or without --max-columns argument)

What happens if you run the below in the shell, do you get any result at all?
```sh
rg --column --line-number --no-heading --color=always --smart-case "Matthams" "<TEST_FILE>"
```

If you manage to get it working in the shell, fzf-lua should have the exact same results, this is how mine works:
![image](https://user-images.githubusercontent.com/59988195/207181249-8a1c301a-9594-4c10-9257-89caece4ef03.png)

**Comment by crates51** [comment]
Thanks for the help!
Soo,
`rg --column --line-number --no-heading --color=always --smart-case "Yoder" names_one_line.txt` works from terminal
![image](https://user-images.githubusercontent.com/42578442/207263945-3cf5bfed-a98a-4111-856f-e494fee707bb.png)

And
`:lua require'fzf-lua'.grep({search="Yoder", cmd="rg --column --line-number --no-heading --color=always --smart-case"})`
from nvim works as well !
![image](https://user-images.githubusercontent.com/42578442/207264712-36fb9e66-8a3f-49e2-9607-fca247b293f8.png)

But there is one last piece of the puzzle, my day to day workflow with fzf-lua is using ctrl+f with this map

`nnoremap("<C-f>", "<cmd>lua require('fzf-lua').grep({ search = '' })<CR>")`

such that it open me an fzf-lua window and i can search lively anything i want (both filenames and file content,and even both same time))

As you can see below Maisy and Ria can be found, but Matthams and Yoder cannot

![Peek 2022-12-13 10-44](https://user-images.githubusercontent.com/42578442/207272308-e65263ad-4499-4360-8c70-8abb60dd20e3.gif)

if that doesnt work we can close it here and i will make a "special" remap  for special event (but i will lose that live interaction when typing)

nnoremap("<C-f>", "<cmd>lua require('fzf-lua').grep({ cmd = 'rg --column --line-number --no-heading --color=always --smart-case' })<CR>")

**Comment by ibhagwan** [comment]
> But there is one last piece of the puzzle, my day to day workflow with fzf-lua is using ctrl+f with this map

Your mapping is running an empty search `rg` (equivalent to `grep_project`), what you’re doing here is feeding all lines of your project into fzf and then fuzzy matching on top, it’s very possible that there is a limit within the fzf binary to line length (I’ll check later) which is the reason why it’s not matching anything past a certain column (with or without max columns).

As an alternative you can  use `live_grep`, the way it works is each keystroke generates a new `rg` command, on large projects it’s also much faster than using grep with an empty search, once you narrowed down your result set  (using exact match or regex) you can press `ctrl-g` to fuzzy match on top.

**Comment by ibhagwan** [comment]
Btw, another disadvatange of using `grep` with an empty search and then fuzzy matching is that it can only match a line (without a an exact column), when using `live_grep` you also get the execat column so when you press enter on the match the cursor should take you to the exact location.

I'm still trying to figure out though where the width limit is coming from.

**Comment by crates51** [comment]
Can live_grep also search for the file names(instead only the file contents)? cause that is one of the reasons i started with grep instead of live_grep

Like i open fzf_lua window with .grep() and start to write: 
module/file_x.py some_variable
file_y.yaml some_field

and it works cool, but live_grep doesn't get file_names :-/

**Comment by ibhagwan** [comment]
> an live_grep also search for the file names/file paths(instead only the file contents)? cause that is one of the reasons i started with grep instead of live_grep

You can use `live_grep_glob` (or enable `rg_glob` in setup) to limit the search to specific file globs but since each keystroke generates a new command you can't fuzzy match the filename the same way you can do when using `grep`.

As for your issue, update to https://github.com/ibhagwan/fzf-lua/commit/9a16c0e6870e354869ff3bafbd67aa6eafa5fea5 and try again, `grep` should now work as expected.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b1dea843c2f4c623ac974afc074ce832a29f8548 this one also increases the default `--max-columns` to 4k as I believe 1k to be too small.

**Comment by crates51** [comment]
Thanks :smile: !

**Comment by ibhagwan** [comment]
> Thanks 😄 !

Ty for submitting this report, I’m surprised it only came up now given the relative maturity of this project :)
