### ISSUE TITLE
`.help_tags()` is affected by `autocmd FileType help` 

### ISSUE THREAD

**Issue by cmpadden** [ibhagwan/fzf-lua#581]
### Info

- Operating System: MacOS
- Shell: `bash`
- Terminal: `Terminal.app`
- `nvim --version`: `v0.8.1`
- `fzf --version`: `0.33.0`

- [ ] The issue is reproducible with `mini.sh`

It was not re-producible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
vim.keymap.set("n", "<c-f>h", "<cmd>lua require('fzf-lua').help_tags()<CR>")

-- after opening `help` files, move them to the right
vim.cmd([[
  augroup helpFileType
    autocmd!
    autocmd FileType help wincmd L
  augroup END
]])

```
</details>

### Description 

Using `.help_tags()` results in the window contents to be displayed in a right split. This is due to `autocmd FileType help wincmd L`.

I was hesitant to report this, but I thought it might be useful only because this does *not* occur using `fzf.vim`. I wanted to bring it to your attention in case there is a way to prevent the `autocmd` from running for the pop-up window. Please close if you wish. Thanks!

![image](https://user-images.githubusercontent.com/5807118/207434426-c3194237-f4f2-40bb-8ac9-2a899ec343b6.png)

**Comment by ibhagwan** [comment]
> Using `.help_tags()` results in the window contents to be displayed in a right split. This is due to `autocmd FileType help wincmd L`.

I have something similar in my neovim config, my solution was to exclude floating windows from the autocmd, you can see it here: https://github.com/ibhagwan/nvim-lua/blob/68beb5d51f701a4140386192539f6245fe789052/lua/autocmd.lua#L144-L168

> I was hesitant to report this, but I thought it might be useful only because this does not occur using `fzf.vim`

Fzf-lua preview highlights work by setting the filetype of the previewer, naturally that generates a `FileType` event, I'm not sure how that can be avoided, I tried changing the `set ft=...` command to `:noautocmd set ft=...` but it ends up not setting the filetype and losing the syntax highlighting.

I would love to fix it I'm just not sure if it's possible, I don't know how fzf.vim's help works, does it have a preview? is the preview file filetype set to `help` (to be able to display proper help syntax highlights)?

If you have an idea how to avoid the autocmd (or setting the filetype, which happen for all previews btw, not just help), or maybe shed more light how this is avoided by `fzf.vim`, it would be great help.

**Comment by cmpadden** [comment]
Thanks so much for the example! 

After a cursory glance, I don't see any mention of setting file types in the `fzf.vim` source. I'd much rather have the highlighting, and apply the fix you suggested. 🙏
