### ISSUE TITLE
`oldfiles` shows only last ~30 files

### ISSUE THREAD

**Issue by JosefLitos** [ibhagwan/fzf-lua#584]
I edit a lot of different files, but only around 30 of the most recent ones show up. I looked through the wiki and the code, but don't see a reason, nor an option that could change that.
Am I missing something or is this a bug?

**Comment by ibhagwan** [comment]
- How many files do you see when you run `:oldfiles`?
- Do you see the missing files when running `:lua require'fzf-lua'.oldfiles({stat_file=false})`
> *by default, the code makes sure the file exists on the file system with `vim.loop.fs_stat`

**Comment by JosefLitos** [comment]
It actually does does seem to be broken in vim (both show the same last file). NVim gives me 100 files (but many of them terminal links).
This never occured to me with Telescope, so I thought this was a bug, sorry.
I only needed to change `vim.o.shada`.

**Comment by JosefLitos** [comment]
I found this [issue](https://github.com/neovim/neovim/issues/18433) over on neovim, but so far without any progress.
