### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by yashamon** [ibhagwan/fzf-lua#585]
Does it work on windows, I get no results with basic :fzflua files. The window opens but no results, no messages. fzf is installed and usual fzf.vim works fine.

**Comment by ibhagwan** [comment]
> Does it work on windows, I get no results with basic :fzflua files. The window opens but no results, no messages. fzf is installed and usual fzf.vim works fine.

Unfortunately this plug-in does not support windows.

**Comment by yashamon** [comment]
Oh, is there something blocking it, or you just don't want to deal windows?
I think what fzf.vim does is just send linux calls to wsl2. Although this is just for the previewer, without wsl everything works just fine except preview.

**Comment by ibhagwan** [comment]
> Oh, is there something blocking it, or you just don't want to deal windows? I think what fzf.vim does is just send linux calls to wsl2. Although this is just for the previewer, without wsl everything works just fine except preview.

Nothing blocking really, but given the windows file structure and RPC interface is quite different I can't do it blindly without access to a windows machine.

In addition, properly supporting windows at the level of maturity and stability this project is currently at  would require a lot of time (as you can tell by the amount of  outstanding issues, there are barely any bugs or unfulfilled requests), if I'm being absolutely honest about it, I don't really enjoy working on windows nor do I like the privacy abusive bloatware it has become so I won't invest any of my time supporting it.

That said, I would welcome a PR to support it.

As for WSL, I'm not closely familiar with it but I recall a few issues that came from WSL users and as far as I could tell this plugin worked seamlessly for them as if they were on Linux.

**Comment by ibhagwan** [comment]
Closing for now, if one day you decided to PR this and need my help feel free to reopen.

**Comment by ibhagwan** [comment]
FYI, windows is now supported follow #1038 and the [windows branch](https://github.com/ibhagwan/fzf-lua/tree/windows) for more info.

**Comment by yashamon** [comment]
Very cool
