### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by npearson72** [ibhagwan/fzf-lua#586]
Hi, I was wondering if you would be open to creating a discussion tab on this repo?

If not, perhaps you might be able to help me understand how to convert this vimscript function into lua?

```
function! s:fZFCtrlp(idx)
  let commands = ['Files', 'History']
  execute commands[a:idx]
  let next = (a:idx + 1) % len(commands)
  execute 'tnoremap <buffer><silent><c-f> <c-\><c-n>:close<cr>:sleep 10m<cr>:call <sid>fZFCtrlp('.next.')<cr>'
endfunction
command! FZFCtrlp call <sid>fZFCtrlp(0)

command! -bang -nargs=? -complete=dir Files
      \ call fzf#vim#files(<q-args>, fzf#vim#with_preview('right:50%:hidden', 'ctrl-p'), <bang>0)

command! -bang -nargs=? -complete=dir History
      \ call fzf#vim#history(fzf#vim#with_preview('right:50%:hidden', 'ctrl-p'))
```

The idea here is to be able to use ctrl-p to open fzf, but then cycle through Files and History with ctrl-f.

**Comment by ibhagwan** [comment]
> Hi, I was wondering if you would be open to creating a discussion tab on this repo?

I have no objection to this, I'm just not sure how much interaction that would get other than me having to answer all of the discussions as if it was an issue :-)

> If not, perhaps you might be able to help me understand how to convert this vimscript function into lua?

```lua
local fzf = require("fzf-lua")

_G.my_files = function()
  -- start with files
  local interface = fzf.files
  local fzf_opts = function()
    local int_name = interface == fzf.files and "History" or "Files"
    return {
      ["--header"] = vim.fn.shellescape(string.format(
        ":: %s to switch to %s",
        fzf.utils.ansi_codes.yellow("<C-f>"),
        fzf.utils.ansi_codes.yellow(int_name)))
    }
  end
  interface({
    -- comment this line if you don't want the header
    fzf_opts = fzf_opts(),
    actions = {
      ["ctrl-f"] = {
        function(_, o)
          interface = interface == fzf.files and fzf.oldfiles or fzf.files
          interface({ actions = o.actions, fzf_opts = fzf_opts() })
        end
      }
    }
  })
end

vim.keymap.set('n', '<C-p>', _G.my_files)
```

And the result:
![image](https://user-images.githubusercontent.com/59988195/209195460-58fe71cb-a593-45fa-9969-3b2de3d8baaa.png)

After pressing `<C-f>` once:
![image](https://user-images.githubusercontent.com/59988195/209195569-2abf2653-9d30-4f61-b22b-704d27c67069.png)

**Comment by npearson72** [comment]
>  I'm just not sure how much interaction that would get other than me having to answer all of the discussions as if it was an issue :-)

Ha! You're probably right. Thank you for the help with this. It's really instructive.

**Comment by rieje** [comment]
Also interested, I think the nature of something as extensible as fzf means there's naturally a ton of ideas people want to share or are seeking to implement. Not sure if there's a cost associated with inactive discussions or Gitter--the other outlets are opening an issue here or /r/neovim which don't seem as appropriate. Although I will say I'm a total noob to Neovim/Lua and the wiki seems quite thorough.

**Comment by ibhagwan** [comment]
> Also interested, I think the nature of something as extensible as fzf means there's naturally a ton of ideas people want to share or are seeking to implement. Not sure if there's a cost associated with inactive discussions or Gitter--the other outlets are opening an issue here or /r/neovim which don't seem as appropriate. Although I will say I'm a total noob to Neovim/Lua and the wiki seems quite thorough.

I wouldn’t mind opening the discussions page if there is more demand, haven’t looked into it yet but it doesn’t seem like it is associated with a cost, I think just requires to be enabled from my end.
