### ISSUE TITLE
[Question] Need helps to implement a feature so `FzfLua buffers` can show only shown buffers

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#588]
### Description 

I'm trying to extend the default `FzfLua buffers` by adding a new action for it so that only **shown** buffers, i.e. buffers that are opened in a window in some tab, will be listed. I expected that this can be achieved by extending the default one, so I have tried to read the source(as linked below) but it seems that copy-pasting it is not a good idea since some internal `local` functions are used and I'm not sure about whether they're related to my question or not. What I want to achieve is something like the default action `<C-g>` for `FzfLua live_grep_glob` but here I want to toggle between listed/shown buffers.

I really need this feature, thanks for your reading!

https://github.com/ibhagwan/fzf-lua/blob/5abf66f63bf08121dd4e917488b59ccb693eee12/lua/fzf-lua/providers/buffers.lua#L168-L196

**Comment by ibhagwan** [comment]
> What I want to achieve is something like the default action `<C-g>` for FzfLua `live_grep_glob` but here I want to toggle between listed/shown buffers.

Although I’m sure it’s possible with some hacks reusing the internal buffers code for an extension such as you’re describing isn’t the best idea and is alsp prone to break if I change something in the future.

For what you’re describing it’s best to use the API `fzf_exec` which is bound to stay the same, my honest suggestion is start from scratch and experiment first use the output from `nvim_list_bufs()` as is, see what you want to trim down and finds ways to determine which buffers you want displayed based on certain parameters (if they have visible window or not, maybe use `nvim_win_get_buf` or `winbufnr`?), once you have a provider that works to your liking you can use an action to open it using a `C-g` like action.

You can also copy the buffers source code and remove everything you don’t need there, either way you’ll end up in a similar result to “writing from scratch”.

Good luck!

**Comment by ibhagwan** [comment]
>new action for it so that only shown buffers, i.e. buffers that are opened in a window in some tab
 
@nyngwang, now that I think of it, isn't what you're asking **exactly** the `FzfLua tabs` command?

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if you need more help.

**Comment by nyngwang** [comment]
> @nyngwang, now that I think of it, isn't what you're asking exactly the FzfLua tabs command?

@ibhagwan Oh holy-moly golden era. That's exactly what I need!

**Comment by ibhagwan** [comment]
> > @nyngwang, now that I think of it, isn't what you're asking exactly the FzfLua tabs command?
> 
> @ibhagwan Oh holy-moly golden era. That's exactly what I need! I like the Tmux-like experience it provides: clearly points me out where am I.
> 
> (When did you add this?) (Sorry for my late reply I was frustratingly trying to solve some other problems)
>

This is a somewhat early feature requests, #143 :)

> What's the name of the highlight group for the `Tab #n` in the floating window?

That’s hard coded ansi blue (terminal color):
https://github.com/ibhagwan/fzf-lua/blob/292de730ebbd3834e87f864c8c4115dc1035db37/lua/fzf-lua/providers/buffers.lua#L303

**Comment by nyngwang** [comment]
@ibhagwan It's possible to change the color via highlight group? I know this might spend you some time thinking about how to expose it, but I really need it.

<img src="https://user-images.githubusercontent.com/24765272/215934124-8102d002-39df-46a3-9b81-b248d05c5033.png" width="500">

**Comment by ibhagwan** [comment]
You can control terminal colors via the colorscheme: this one should be `vim.g.terminal_color_4`, if this doesn’t work I can add a configuration key for the color tomorrow.

**Comment by nyngwang** [comment]
@ibhagwan Really appreciate that! Take your time I'm not in a hurry for this.

**Comment by ibhagwan** [comment]
Update to https://github.com/ibhagwan/fzf-lua/commit/dd0346cbe91e2fdf55dba043dfe218427b96ad5f and you can customize both the tab title and a custom neovim highlight, for example:
```lua
:lua require("fzf-lua").tabs({ tab_title="TAB NUMBER", tab_title_hl="Error" })
-- Another example:
:FzfLua tabs tab_title=TEST tab_title_hl=Special
```

Will result in:
![image](https://user-images.githubusercontent.com/59988195/216075969-6f4e8a5b-1bc1-465c-9ed1-1fa9c670b6b2.png)

**Comment by ibhagwan** [comment]
> @ibhagwan I just saw your update via the log message of lazy.nvim :) I didn't know that a red(?) title looks really nice, thanks for your swift help!


Try them all :-)

Any neovim highlight group should work now, including custom ones set by colorschemes/plugins/etc, you can explore avaiable highlight groups with `:FzfLua highlights`.
