### ISSUE TITLE
keymaps provider not listing all keymaps (missing callback functions)

### ISSUE THREAD

**Issue by gennaro-tedesco** [ibhagwan/fzf-lua#590]
I have noticed that `FzfLua keymaps` does not return all defined keymaps: in particular, looking at the [code](https://github.com/ibhagwan/fzf-lua/blob/5abf66f63bf08121dd4e917488b59ccb693eee12/lua/fzf-lua/providers/nvim.lua#L262), I see that the reference point for the list of all keymaps is `vim.api.nvim_get_keymap(mode)`. By exploring such a table it seems that [this condition](https://github.com/ibhagwan/fzf-lua/blob/5abf66f63bf08121dd4e917488b59ccb693eee12/lua/fzf-lua/providers/nvim.lua#L276) cuts off all the keymaps whose right hand side is a function callback: this is because the corresponding entry in `vim.api.nvim_get_keymap` does not contain a `rhs`, rather `callback = <function ... >` instead. Is this by design, namely is there a particular reason to exclude those ones (I understand they do not have an explicit definition in terms of strings, however when users search for them it may mistakenly appear they aren't defined whereas they are)?

If, for those keymaps, I instead use the old Vimscript API `verbose map XYZ?` I do get the location where the mapping is defined. Would it not still make sense to include them (even though we can leave the rhs undefined)?

**Comment by ibhagwan** [comment]
> Is this by design, namely is there a particular reason to exclude those ones

This was done long ago before lua function callbacks where enabled, it was meant to filter out plug-in related commands that weren’t meant to be displayed, for example ones created by which-key, we can revisit this logic now.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/f65acaeefd5a58d97868c7290402f74acb1c31c6 - should work better now, it only ignores mappings that do nothing, if the mapping has a lua callback but no description it would appear as `function <address>` instead.

**Comment by gennaro-tedesco** [comment]
Awesome as always! ❤️  🚀
