### ISSUE TITLE
allow fzf API filtering on search methods

### ISSUE THREAD

**Issue by RaulCote** [ibhagwan/fzf-lua#591]
Hi, 

Sorry to open an issue for this. First congrats, wonderful plugin. I like it, I simply have a question. 

fzf-lua.grep ask for some input, and then displays the fzf search that can be filtered with the regular fzf API (ie: use single quote for exact search, exclamation to remove, dollar for the string ending etc...), also as well it works on LSP go to references,  but I can't use those fzf API filters on the live_grep etc. 

I've been reading the advance wiki and the documentation but I can't realize how to built my own custom live RG that supports fzf API filtering.

**Comment by ibhagwan** [comment]
Have you read this?
https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep

This is impossible by design, each keystrokes in a new rg command, if you want fuzzy finding use `grep_project` instead.

**Comment by ibhagwan** [comment]
You’re probably missing the point and power of the live grep interface, it’s basically passing the arguments directly to rg, that enables you to do complex regex searches and also glob searches (with `live_grep_glob`), once you narrowed down what you are after press `ctrl-g` to switch to fuzzy mode with your current regex search.

For example live grep `foo.*bar -- *.lua` which will search for lines containing foo and bar only in lua files, then press ctrl-g and you can continue fuzzy searching, if you wanna modify the underlying regex just press ctrl-g again.

If you want to start with your entire project in fuzzy mode just use `grep_project` which is the equivalent of grep with an empty search.

**Comment by RaulCote** [comment]
Thanks, with your last response you made me realize that it was my bad. On fuzzy search mode it does accept the fzf way. Pretty cool. I just need to read and get used that some methods accept fuzzy search by invoking them and others start on regex mode.

I will close the issue.

**Comment by ibhagwan** [comment]
No worries feel free to open if it isn’t clear or you need more help.
