### ISSUE TITLE
oldfiles not sorting by time accessed after typing

### ISSUE THREAD

**Issue by floydj** [ibhagwan/fzf-lua#592]
When I bring up oldfiles with `FzfLua oldfiles`, it works as I expect. But once I start typing to narrow down the list of files, it loses that order (the latest-accessed file is no longer at the top of the list). How can I keep it ordered by accessed time/date?

My setup:

```lua
fzf.setup({
  grep = {
    rg_opts = "--sort=accessed --files --hidden --column --line-number --no-heading " ..
              "--color=always --smart-case -g '!{.git,node_modules}/*'",
  },
  oldfiles = {
    cwd_only = true,
  },
  actions = {
    files = {
      ["default"]       = fzf.actions.file_edit_or_qf,
      ["ctrl-i"]        = fzf.actions.file_split,
      ["ctrl-v"]        = fzf.actions.file_vsplit,
      ["ctrl-t"]        = fzf.actions.file_tabedit,
      ["alt-q"]         = fzf.actions.file_sel_to_qf,
    },
    buffers = {
      ["default"]       = fzf.actions.buf_edit,
      ["ctrl-i"]        = fzf.actions.buf_split,
      ["ctrl-v"]        = fzf.actions.buf_vsplit,
      ["ctrl-t"]        = fzf.actions.buf_tabedit,
      ["ctrl-r"]        = fzf.actions.buf_del,
    }
  },
})
```

Examples below: trying to get to test/system/gs_discharges_test.rb.

When first bringing up the History window:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/1292970/209977746-fcbe9eff-2ae6-4997-befa-5475c856e0dd.png">

After typing 'system', which should bring up test/system/gs_discharges_test.rb at the top of the list:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1292970/209977863-ac5cb678-9547-4b40-9e8c-30dd2bb448f1.png">

I'm sure I'm just missing a fzf option, but can't track it down.  Any ideas here? Thanks in advance for any help.

**Comment by ibhagwan** [comment]
Unfortunately there is no way to do that, once you start typing fzf binary will sort the matches according to the fuzzy matching algorithm.

**Comment by floydj** [comment]
Ach. So no way to tweak the algorithm with fzf options?

**Comment by floydj** [comment]
I looked through code at https://github.com/junegunn/fzf.vim since I didn't have the issue with it, but couldn't find a way to do it.

**Comment by ibhagwan** [comment]
> Ach. So no way to tweak the algorithm with fzf options?

Certainly you can do that, you can send extra cli options via  the`fzf_opts`, not sure how you’d get it sorted by access time though.

**Comment by ibhagwan** [comment]
> I looked through code at https://github.com/junegunn/fzf.vim since I didn't have the issue with it, but couldn't find a way to do it.

Perhaps it wasn’t sorting by access time but used a different `tiebreak`? Try
```lua
:lua require'fzf-lua'.oldfiles({ fzf_opts = { ['- -tiebreak'] = '<value>' } })
```
Try these options for  [--tiebreak](https://www.mankier.com/1/fzf#--tiebreak):
```
Comma-separated list of sort criteria to apply when the scores are tied.
length  Prefers line with shorter length
chunk   Prefers line with shorter matched chunk (delimited by whitespaces)
begin   Prefers line with matched substring closer to the beginning
end     Prefers line with matched substring closer to the end
index   Prefers line that appeared earlier in the input stream
- Each criterion should appear only once in the list
- index is only allowed at the end of the list
- index is implicitly appended to the list when not specified
- Default is length (or equivalently length,index)
- If end is found in the list, fzf will scan each line backwards
```

**Comment by floydj** [comment]
I'll look into that, though it doesn't appear that any one those will do what I'm after. Thank you!

**Comment by ibhagwan** [comment]
For what it’s worth, I’m pretty sure there is no special magic sort in fzf.vim oldfiles, if similar behavior exists in fzf.vim you’re pretty much guaranteed to match its behavior by using the same flags with the fzf binary.

**Comment by ibhagwan** [comment]
FYI https://github.com/ibhagwan/fzf-lua/commit/bcb5153f893829c78e59c1c788bb3f2b04dd46f2 sets the default tiebreak for both `buffers` and `oldfiles` to `index`.
