### ISSUE TITLE
Feature Question "extend Fzflua usefulness to the feature for vim command"

### ISSUE THREAD

**Issue by PorcoRosso85** [ibhagwan/fzf-lua#593]
### Info

- Operating System: ubuntu 2204
- Shell: zsh
- Terminal: wsl2 on windows10
- `nvim --version`: 0.8.1
- `fzf --version`: 0.35.1

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
Will you let me ask you the question like theme?
If not accepted, I'm ok for question to be closed immediately.

I'm in love fzf-lua.
Everyone here may be enjoying using fzf-lua for vim command.
I mean vim command is ":vimgrep...", ":Fzflua xxx..."
Especially I enjoy using " :Fzflua commands "  https://github.com/ibhagwan/fzf-lua#commands

Anyone can call command's argument in fzf-lua ui?
For example, 
1. vim command " : Fzflua commands "
2. select command in fzf-lua ui, like " Fzflua " again
But, we can call only command but not its argument, right?
If we can also add argument into ":Fzflua commands" ui,  it's so convenient for us, I think.

Thanks for this place.

update1
add image
![image](https://user-images.githubusercontent.com/40359643/210286846-9752c3ea-1ea1-491d-aa76-43fcfd41dcac.png)
![image](https://user-images.githubusercontent.com/40359643/210286851-322eecf7-99d1-4d90-b05d-38522ce1ce16.png)

**Comment by ibhagwan** [comment]
You can call arguments in two different ways:
```vim
:FzfLua grep search=foo
:FzfLua files cwd=~ previewer=false
```
Or lua
```lua
:lua require'fzf-lua'.grep( { search = 'foo' })
:lua require'fzf-lua'.files( { cwd = '~', previewer = 'false` })
```

**Comment by PorcoRosso85** [comment]
@ibhagwan 
Thanks.

Do you mean that we can add not command itself but argument into ":Fzflua commands" option?
like this images...

![":Fzflua commands"](https://user-images.githubusercontent.com/40359643/210286602-d604a2d0-dc06-4889-8f8c-7f03eacae996.png)
![":Fzflua keymaps"](https://user-images.githubusercontent.com/40359643/210286638-85a3f4f8-16ce-4939-b8e3-67529786205f.png)

**Comment by ibhagwan** [comment]
I’m not really sure what command you want to these?

Iyou’d like the query to be input into the interface use`FzfLua commands query=Plug`

**Comment by ibhagwan** [comment]
Reading again your original post I think `query` will be what you want, it works by pre-filling the fzf query field, this can also filter arguments as it works on the entire line, this works in every provider `commands`, `keymaps` etc:

```vim

:FzfLua commands query=FzfLua
:FzfLua keymaps query=space
 ```
Or Lua
```lua
:lua require'fzf-lua'.commands( { query='Fzf'})
:lua require'fzf-lua'.keymaps( { query='space'})
 ```

If you’re referring to filtering based on the arguments in the preview window of the command, there is no such option yet.

**Comment by PorcoRosso85** [comment]
""" If you’re referring to filtering based on the arguments in the preview window of the command, there is no such option yet.

Mayby this is what I wanted.

But ```query``` you told me is also good for me.
And I'm impressed that you reply soon.

Thanks for this issue, I'll ask again some day if you accept.

**Comment by ibhagwan** [comment]
> Thanks for this issue, I'll ask again some day if you accept.

If the solution was more straight forward it would be worth it, right now I’m not sure, the command detail table doesn’t necessarily correspond with arguments so I’m not sure what would be the benefit here and the keymaps can already be filtered using `query`.
