### ISSUE TITLE
How to map ["ctrl-x"] to delete item in FzfLua quickfix?

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#594]
### Info

- Operating System:
- Shell:
- Terminal:
- `nvim --version`:
- `fzf --version`:

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

As I check there is no actions like buf_del for deleting selected entries from quick fix list. Is it possible to to that using the API? or would need to change plugin code?

**Comment by ibhagwan** [comment]
You can achieve that with a custom action, the action would require to rebuild the list without the item you wish to delete.

Personally I have my default action set to `file_edit_or_qf` (default) which sends multiple entries to the qf so what I do is select the item(s) I wish to exclude, the press `alt-a` to toggle selection and `enter`, that rebuilds the qf for you without the items you wanted to delete.

It's just one extra keypress `tab`+`alt-a`+`enter` vs `tab`+`ctrl-x`, I don't know if it's worth the effort for a custom action :-)

**Comment by sandangel** [comment]
Is there a function that equivalent to `toggle-all`? So that I can call that in my custom action? The problem with extra keystroke is the inconsistency. we use `<ctrl-x>` for delete buffers, and `<alt-a>+<cr>` for deleting items in qf list.

**Comment by ibhagwan** [comment]
> Is there a function that equivalent to `toggle-all`? So that I can call that in my custom action? The problem with extra keystroke is the inconsistency. we use `<ctrl-x>` for delete buffers, and `<alt-a>+<cr>` for deleting items in qf list.

Yes, set up a (or modify the existing) `select-all` bind under `keymap.fzf`.

**Comment by sandangel** [comment]
Thanks a lot for sharing.

**Comment by sandangel** [comment]
>           ["alt-a"]       = "toggle-all",

I also searched for this, can I just replace `toggle-all` with a function and it return 'toggle-all'?

**Comment by sandangel** [comment]
What I'am trying todo: 
```lua
        fzf = {
          ['tab'] = 'toggle',
          ['alt-a'] = 'toggle-all',
          ['ctrl-x'] = function()
             -- Run toggle all function
             -- Run edit file or quickfix action 
          end
        },

**Comment by ibhagwan** [comment]
Btw, fzf supports multiple actions in one bind you can also do this:
```lua
:lua require("fzf-lua").quickfix({ keymap = { fzf = { ["ctrl-x"] = "select+toggle-all"}} })
```
or to delete and reopen the quickfix list:
```lua
:lua require("fzf-lua").quickfix({ keymap = { fzf = { ["ctrl-x"] = "select+toggle-all+accept"}} })
```

**Comment by sandangel** [comment]
oh thanks a lot. this is exactly what I want:

```lua
    local fzf_lua = require 'fzf-lua'

    local function fzf_quickfix(selected, opts)
      if #selected > 1 then
        local qf_list = {}
        for i = 1, #selected do
          local file = require 'fzf-lua'.path.entry_to_file(selected[i], opts)
          local text = selected[i]:match ':%d+:%d?%d?%d?%d?:?(.*)$'
          table.insert(qf_list, {
            filename = file.path,
            lnum = file.line,
            col = file.col,
            text = text,
          })
        end
        vim.fn.setqflist(qf_list)
        vim.cmd 'FzfLua quickfix'
      else
        fzf_lua.actions.file_edit(selected, opts)
      end
    end

    fzf_lua.setup {
      keymap = {
        fzf = {
          ['tab'] = 'toggle',
          ['ctrl-a'] = 'toggle-all',
          ['ctrl-x'] = 'toggle-all+accept',
          ['ctrl-f'] = 'half-page-down',
          ['ctrl-b'] = 'half-page-up',
        },
      },
      actions = {
        files = {
          ['default'] = fzf_quickfix,
          ['ctrl-s']  = fzf_lua.actions.file_vsplit,
        },
        buffers = {
          ['default'] = fzf_quickfix,
          ['ctrl-s']  = fzf_lua.actions.buf_vsplit,
        }
      },

```

**Comment by ibhagwan** [comment]
Looks great!
