### ISSUE TITLE
How to detect that my cursor is currently on `fzf` floating window in `BufEnter`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#596]
### Description 

I have the following animation related `autocmd`, i.e. a `BufEnter` event:

```lua
local function should_exclude()
  return (
    vim.bo.filetype == 'lazy'
    or vim.bo.filetype == 'mason'
    or vim.bo.filetype == 'neo-tree'
    or vim.bo.filetype == 'screensaver'
    or vim.bo.filetype == 'fzf'
    or vim.bo.buftype == 'terminal'
  )
end


vim.api.nvim_create_autocmd({ 'BufEnter' }, {
  pattern = '*',
  callback = function ()
    if not should_exclude() then
      -- ...
    end
  end
})
```

So as you can see I have added two conditions `vim.bo.filetype == 'fzf' or vim.bo.buftype == 'terminal'` in function `should_exclude()` to try to detect fzf-lua's floating window. But it doesn't work. Given that I must use the event `BufEnter`, how to detect the floating window/menu?

**Comment by ibhagwan** [comment]
Try `bufwinid` (or similar, not sure) and test for a floating window.

**Comment by nyngwang** [comment]
@ibhagwan It turns out `TermOpen` works. I still hope this can be detected by `vim.bo.filetype` and/or `vim.bo.buftype`. In fact, I have three plugins:

- williamboman/mason.nvim: can detect.
- folke/lazy.nvim: cannot detect. have to use `BufWinLeave`.
- ibhagwan/fzf-lua: cannot detect. have to use `TermOpen`.

So I believe there is a way to let `filetype` always be detectable even in `BufEnter`. While I can understand that technically one should detect the `filetype` by the `FileType` event, I need to run the animation script(the body of that `if` statement) every time I enter these three plugins' floating menu(? actually not sure what's the proper naming).

**Comment by ibhagwan** [comment]
I'm not sure what happens first `BufEnter` or setting the filetype, in any event this is unrelated to the behavior of the plugin, there's always a way to find the property that will identify the window/buffer you wish to exclude you just have to find it.

**Comment by nyngwang** [comment]
OK, maybe `TermOpen` is indeed the most convenient way to achieve the result. Many thanks for your instant replies :) Closing...
