### ISSUE TITLE
Issue #589 doesn't resolve the dirty buffer warning with confirm for unnamed buffers

### ISSUE THREAD

**Issue by andrewferrier** [ibhagwan/fzf-lua#597]
See #589 for previous issue and context.

The resolution to #589 appears to work as expected, but only for named buffers.

Recreation:
* Install `fzf-lua`.
* Turn on `confirm` and turn off `hidden` in `init.lua` or similar.
* Open NeoVim. Type into the scratch buffer. Do not save it anywhere.
* Use `:FzfLua files` to try to switch to another file.
* See the warning "[Fzf-lua] buffer 1 has unsaved changes". At this stage I would expect to see the Vim-generated `confirm` warning/question instead.

If instead you open a named file, then type into that, *then* switch to another file with `:FzfLua files`, the Vim-generated `confirm` warning appears as expected (this is the change made by #589).

Essentially - my recommendation would be just to remove this warning from `fzf-lua` entirely. `confirm` already has the behavior I think is desired here, and is built into NeoVim. Essentially `fzf-lua` is just providing another way to switch files here - in my personal opinion, I'm not sure what the `fzf-lua` warning adds. Just my 2c.

Thanks again for all your hard work on this great plugin!

**Comment by ibhagwan** [comment]
This is a by design, when I tested the solution for #597 I noriced the file can’t be saved with `confirm` so I deemed the warning appropriate, without the message the user is left with no action on the unnamed buffer and confirm can’t help here - why would you prefer this to be removed?

**Comment by andrewferrier** [comment]
Sorry, my mistake, you are correct! I had always assumed that NeoVim would offer me the ability to save the file there but even if I type Y for yes I don't get a prompt for a filename, which renders the prompt useless.

I might consider opening a bug on NeoVim itself as I think this behaviour is confusing and unhelpful, but I agree with you, the warning in fzf-lua given the current behaviour is probably actually more helpful, and certainly not less. 

I'm going to close this issue, sorry for not testing this more thoroughly first time.

**Comment by andrewferrier** [comment]
For the record, NeoVim bug opened for this issue: https://github.com/neovim/neovim/issues/21682.

**Comment by ibhagwan** [comment]
Ty for the update @andrewferrier
