### ISSUE TITLE
How can I add/modify header?

### ISSUE THREAD

**Issue by fjchen7** [ibhagwan/fzf-lua#599]
### Description 

I implement an action to switch oldfiles between `cwd_only=true` and `cwd_only=false`

```lua
{
  oldfiles = {
    actions = {
      ["tab"] = function(_, opts)
        opts.cwd_only = not opts.cwd_only
        fzf.oldfiles(opts)
      end
    }
  }
}
```

How can I add header about this keymap? Just like what live_grep does:
![image](https://user-images.githubusercontent.com/10106636/211144316-2107586c-d1a3-46db-99b5-50837c666475.png)

**Comment by ibhagwan** [comment]
Use Fzf’s `header` option:
```lua
  oldfiles = {
    fzf_opts = { ["--header"] = "custom header" ]  }
    …
  }
```

**Comment by fjchen7** [comment]
It doesn't work. Window dismissed immediately when calling `FzfLua oldfiles`.

**Comment by ibhagwan** [comment]
> ```lua
> fzf_opts = { ["--header"] = "custom header" ]  }
> ```

My bad I answered from my phone and there's an extra `]`, on top of it I didn't mention this requires escaping if the line has spaces/special chars:
```lua
oldfiles = {
    fzf_opts = { ["--header"] = [["custom header"]]  }
    …
  }
```

You can also try it as a one liner from the `:` prompt:
```lua
:lua require("fzf-lua").oldfiles({ fzf_opts = { ["--header"] = [["custom header"]]  } })
```

**Comment by fjchen7** [comment]
That work, thank! 

However I find that some commands still use default value even if I set `header`, like `files` or `git_files`. I thinks this problem may occurs for other fifth options. 

And if I set a value, I am not sure if the default one will be loaded. The override rule seems different for different config value.

Anyway this issue is solved. Thanks again.

**Comment by ibhagwan** [comment]
> That work, thank!
> 
> However I find that some commands still use default value even if I set `header`, like `files` or `git_files`. I thinks this problem may occur for other fzf options.
> 
> And if I set a table config value, I am not sure if the default one will be loaded. The override rule seems different for different config value.
> 
> Anyway this issue is solved. Thanks again.

Some commands back default header lines, for example for files, grep the header is reserved for the `cwd` and  search query, this can still be overridden option `no_header = true`.
