### ISSUE TITLE
Customise looks 

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#6]
Since `FZF_DEFAULT_OPTS` is emptied by `fzf-lua`, is there a way to customise colors of `fzf` UI elements and pass additional parameters to `fzf`, such as `--margin`?

**Comment by ibhagwan** [comment]
Added an option to specify additional args to fzf with the `fzf_args` option, can either be specified globally (see the updated README) or per call as below:

```lua
lua require('fzf-lua').files({fzf_args = '--margin 10%'})
```

**Comment by ibhagwan** [comment]
Btw, tysm for the extensive QA and suggestions :-)

**Comment by gegoune** [comment]
Haha, no problem at all! :)

**Comment by gegoune** [comment]
If you want to add something to FAQ. Came up with this little thing that I am very happy with!

A mapping executing

```lua
lua require('fzf-lua').oldfiles({cwd_only = function() return vim.api.nvim_command('pwd') ~= vim.env.HOME end})
```

Will show all old files when in ~, otherwise it will filter by current dir. :)

**Comment by ibhagwan** [comment]
> If you want to add something to FAQ. Came up with this little thing that I am very happy with!
> 
> A mapping executing
> 
> ```lua
> lua require('fzf-lua').oldfiles({cwd_only = function() return vim.api.nvim_command('pwd') ~= vim.env.HOME end})
> ```
> 
> Will show all old files when in ~, otherwise it will filter by current dir. :)

This is quite a cool addition, I was actually planing to work on the README later today, this will def be in it :)

**Comment by gegoune** [comment]
There might be better way to get pwd than `vim.api.nvim_command('pwd')` but did not look yet.

**Comment by gegoune** [comment]
`vim.loop.cwd()`
