### ISSUE TITLE
FzfLua git_branches errors with branches checked out at another worktree

### ISSUE THREAD

**Issue by phelipetls** [ibhagwan/fzf-lua#600]
### Info

- Operating System: Linux
- Shell: zsh
- Terminal: GNOME Terminal
- `nvim --version`: 8.0.2
- `fzf --version`: 0.30.0

- [x] The issue is reproducible with `mini.sh`

### Description

The command `:FzfLua git_branches` errors when  with branches checked out in another worktree. See video below:

[Kooha-2023-01-07-10-04-04.webm](https://user-images.githubusercontent.com/39670535/211152102-d6443ecb-498e-401b-adbf-cd881b413167.webm)

To reproduce, just create a worktree, run the mentioned command and navigate to the checked out branch.

```
mkdir tmp
cd tmp
git init
echo "# Hello World!" > README.md
git add README.md
git commit -m "Initial commit"
git worktree add ../tmp-worktree
curl https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh | sh
# inside neovim, run `:FzfLua git_branches`.
```

<details>
<summary>Stacktrace of the error</summary>

```
Error executing vim.schedule lua callback: .../pack/vendor/start/fzf-lua/lua/fzf-lua/providers/git.lua:160: attempt to index a nil value
stack traceback:
        .../pack/vendor/start/fzf-lua/lua/fzf-lua/providers/git.lua:160: in function 'fn'
        ...vim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/shell.lua:140: in function 'fn'
        ...vim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/shell.lua:53: in function <...vim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/shell.lua:52>
```
</details>

**Comment by ibhagwan** [comment]
Ty for the report @phelipetls, should be fixed now.
