### ISSUE TITLE
Documentation with examples for glob

### ISSUE THREAD

**Issue by SirJayEarn** [ibhagwan/fzf-lua#601]
Hi!

I'm enjoying to use this plugin a lot, thanks for your work!

One thing I just figured out mostly by trial and error was how to narrow down search results by just certain file types. A use case I have pretty commonly is for example searching in test-files or environment files. That would be files that have the pattern `*.spec.*` or `*.env`.

It turns out that this is already possible but I didn't really know how and the documentation did not provide a lot of information about that for me either.

Maybe I'm not the only one that got stuck there, so I would like to update the documentation with how to use the glob separator and provide a few examples.
I'll create a PR for it. I just wanted to have a related issue here, so the PR doesn't just come out of the blue :)

If there's something else to do, please let me know - I didn't contribute to a lot of open source projects yet

**Comment by ibhagwan** [comment]
Don’t need a special PR, [the wiki](https://github.com/ibhagwan/fzf-lua/wiki) is open for editing for exactly this reason.

**Comment by SirJayEarn** [comment]
Ok nice, I should have searched the wiki first as it seems :D
There already is something in there, but not particularly for my use case. I'll update the wiki, thanks!

**Comment by ibhagwan** [comment]
> Ok nice, I should have searched the wiki first as it seems :D
> There already is something in there, but not particularly for my use case. I'll update the wiki, thanks!

No pressure at all, whatever you contribute is appreciated :)
