### ISSUE TITLE
use  builds lsp functions

### ISSUE THREAD

**Issue by y1rn** [ibhagwan/fzf-lua#602]
### Info

- Operating System:  archlinux
- Shell:  zsh
- Terminal:  windows terminal
- `nvim --version`:  0.8.2
- `fzf --version`:  0.35

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
Is there any way to call buildin lsp function and view with fzf-lua like nvim-lspfuzzy

**Comment by ibhagwan** [comment]
Not sure I understand what are `builds` functions, if you want fzf-lua to open when you run `vim.lsp` commands either set a keymap for it or set fzf-lua to be the handler for LSP calls.

**Comment by y1rn** [comment]
> Not sure I understand what are `builds` functions, if you want fzf-lua to open when you run `vim.lsp` commands either set a keymap for it or set fzf-lua to be the handler for LSP calls, for example:
> 
> ```lua
> :lua vim.lsp.handlers = ['textDocument/references'] = { label = 'References', target = require('fzf-lua').lsp_ references }
> ```
> 
> Now if you open LSP references you get the fzf-lua interface.

yes, as your understanding, I want to view fzf references result by calling `vim.lsp.buf.references()` ,  but your suggestion doesn't work

**Comment by ibhagwan** [comment]
> > Not sure I understand what are `builds` functions, if you want fzf-lua to open when you run `vim.lsp` commands either set a keymap for it or set fzf-lua to be the handler for LSP calls, for example:
> > ```lua
> > :lua vim.lsp.handlers = ['textDocument/references'] = { label = 'References', target = require('fzf-lua').lsp_ references }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now if you open LSP references you get the fzf-lua interface.
> 
> yes, as your understanding, I want to view fzf references result by calling `vim.lsp.buf.references()` , but your suggestion doesn't work

I apologize I didn't test it and wrote it from the mobile :-)

This should work:
```lua
:lua vim.lsp.handlers['textDocument/references'] = require("fzf-lua").lsp_references
```

Here's the full list of handlers you can override (use the same format above and set the target to the fzf-lua function you wish to invoke):
```lua
{
  ["$/progress"] = <function 1>,
  ["callHierarchy/incomingCalls"] = <function 2>,
  ["callHierarchy/outgoingCalls"] = <function 3>,
  ["client/registerCapability"] = <function 4>,
  hover = <function 5>,
  signature_help = <function 6>,
  ["textDocument/codeLens"] = <function 7>,
  ["textDocument/completion"] = <function 8>,
  ["textDocument/declaration"] = <function 9>,
  ["textDocument/definition"] = <function 10>,
  ["textDocument/documentHighlight"] = <function 11>,
  ["textDocument/documentSymbol"] = <function 12>,
  ["textDocument/formatting"] = <function 13>,
  ["textDocument/hover"] = <function 14>,
  ["textDocument/implementation"] = <function 15>,
  ["textDocument/publishDiagnostics"] = <function 16>,
  ["textDocument/rangeFormatting"] = <function 17>,
  ["textDocument/references"] = <function 18>,
  ["textDocument/rename"] = <function 19>,
  ["textDocument/signatureHelp"] = <function 20>,
  ["textDocument/typeDefinition"] = <function 21>,
  ["window/logMessage"] = <function 22>,
  ["window/showMessage"] = <function 23>,
  ["window/showMessageRequest"] = <function 24>,
  ["window/workDoneProgress/create"] = <function 25>,
  ["workspace/applyEdit"] = <function 26>,
  ["workspace/configuration"] = <function 27>,
  ["workspace/executeCommand"] = <function 28>,
  ["workspace/symbol"] = <function 29>,
  ["workspace/workspaceFolders"] = <function 30>
}
```

**Comment by y1rn** [comment]
It works, thx. but options looks doesn't work with it. and Will lsp references called twice?

**Comment by ibhagwan** [comment]
> It works, thx. but options (`jump_to_single_result`) looks doesn't work with it. and Will lsp references called twice?
For options to work you need to create a custom function:
```lua
vim.lsp.handlers['textDocument/references'] = function()
  require("fzf-lua").lsp_references({ jump_to_single_result = true })
end
```

> I try to call `lua vim.lsp.buf.references({includeDeclaration = false})`, `includeDeclaration = false` doesn't work too.

I don’t think this can work, you’re replacing the handler, the option doesn’t so anything at this point.

**Comment by ibhagwan** [comment]
For a similar effect to `includeDeclaraton` I would use `ignore_current_line`:
```lua
:lua require("fzf-lua").lsp_references({ ignore_current_line = false, jump_to_single_result = true })
```

**Comment by y1rn** [comment]
> For a similar effect to `includeDeclaraton` I would use `ignore_current_line`:
> 
> ```lua
> :lua require("fzf-lua").lsp_references({ ignore_current_line = true, jump_to_single_result = true })
> ```
great, thx. I will update my keymaps to fzf-lua

**Comment by jellydn** [comment]
Hi @ibhagwan Do you have any solution/idea for below keymap?

``lua
      vim.lsp.handlers["textDocument/references"] = function()
        -- FIXME: This doesn't work on neovim nightly, NVIM v0.11.0-dev-1108+g5a86360400
        fzf_lua.lsp_references({ ignore_current_line = true, jump_to_single_result = true })
      end
```

It's working fine on stable (0.10.2) but not on nightly. Thank you in advance.

**Comment by phanen** [comment]
https://github.com/neovim/neovim/pull/30982
```lua
vim.keymap.set(
  'n',
  'grr',
  function()
    require('fzf-lua').lsp_refrence { jump_to_single_result = true, ignore_current_line = true }
  end
)
```

**Comment by jellydn** [comment]
Thanks @phanen but it doesn't work. The root cause from here https://github.com/neovim/neovim/pull/30722#discussion_r1792701875
