### ISSUE TITLE
How can I keep the window open when search file with '--query' gives empty result?

### ISSUE THREAD

**Issue by jackysee** [ibhagwan/fzf-lua#603]
I have the following mapping:
```
local files = function(txt)
    require('fzf-lua').files({ fzf_opts = { ['--query'] = vim.fn.shellescape(txt) } })
end
vim.keymap.set('n', '<leader>F', function() files("'"..vim.fn.expand('<cword>')) end, { silent = true });
````
So when pressing `<leader>F` it will search files with word under cursor prefixed with a single quote for exact match. Currently the behavior is that when there is no match, the search window appear and then disappear immediately. 

I used to have this mapping with `fzf.vim`:
```
    command! -bang -nargs=? -complete=dir FilesSearch
                \ call fzf#vim#files('', 
                \   fzf#vim#with_preview({'options':['--query='.<q-args>]}), <bang>0)
    nnoremap <leader>F :FilesSearch '<c-r><c-w><cr>
```

It would keep the window open and I can continue to delete the search string.

![Screenshot 2023-01-09 at 10 24 11 PM](https://user-images.githubusercontent.com/30516/211330545-f2609a0c-b3c3-4a76-bf22-7e19c6942e6e.png)

How can I keep the window open when search with `--query` using file search?

**Comment by ibhagwan** [comment]
The interface should never close due to `query` not sure why this happens in your case, I just used this:
```lua
:lua require"fzf-lua".files({ query = [['foo]] })
```

**Comment by jackysee** [comment]
It still close immediately if I use `{query = [['foo]]}` so it may be due to some other settings or plugins.

**Comment by ibhagwan** [comment]
- What is your `fzf --version`?
- Do you see any error in `:messages`?
- Do any of the below work?
```lua
:lua require"fzf-lua".files({ query = nil })
:lua require"fzf-lua".files({ query = [[a]] })
```

**Comment by ibhagwan** [comment]
Also what’s the output of `:lua print(vim.env.FZF_DEFAULT_OPTS)`?

Fzf has an option to exit immediately if there are no matches, it’s not enabled with Fzf-lua but might be somewhere in your shell vars, the option is either `-0` or `--exit-0`:
> from `man fzf`

```
-0,  --exit-0
  If there is no match for the initial query (--query),
  do not start interactive finder and exit immediately
```

**Comment by jackysee** [comment]
Yes. I have `-exit-0` in my `FZF_DEFAULT_OPTS`. So may be `fzf.vim` has different handling on this.

**Comment by ibhagwan** [comment]
> Yes. I have `-exit-0` in my `FZF_DEFAULT_OPTS`. So may be `fzf.vim` has different handling on this.

Fzf-lua doesn’t invalidate your default option, if you wish to ignore these you can add `vim.env. FZF_DEFAULT_OPTS = nil` to your config.

**Comment by jackysee** [comment]
That works. Thank you.
