### ISSUE TITLE
 Neovim builtin previewer disappears when browsing entries

### ISSUE THREAD

**Issue by gennaro-tedesco** [ibhagwan/fzf-lua#605]
### Description

Neovim builtin previewer disappears when browsing through fzf entries and must be manually invoked again.

This issue is a follow-up of https://github.com/ibhagwan/fzf-lua/issues/184 and https://github.com/ibhagwan/fzf-lua/issues/604.

The example I am running is, as per the wiki:
```lua

local builtin = require("fzf-lua.previewer.builtin")
local MyPreviewer = builtin.base:extend()

function MyPreviewer:new(o, opts, fzf_win)
	MyPreviewer.super.new(self, o, opts, fzf_win)
	setmetatable(self, MyPreviewer)
	return self
end

function MyPreviewer:populate_preview_buf(entry_str)
	local tmpbuf = self:get_tmp_buffer()
	vim.api.nvim_buf_set_lines(tmpbuf, 0, -1, false, {
		string.format("SELECTED FILE: %s", entry_str),
	})
	self:set_preview_buf(tmpbuf)
	self.win:update_scrollbar()
end

-- Disable line numbering and word wrap
function MyPreviewer:gen_winopts()
	local new_winopts = {
		wrap = false,
		number = false,
	}
	return vim.tbl_extend("force", self.winopts, new_winopts)
end

fzf_lua.fzf_exec("rg --files", {
  previewer = MyPreviewer,
  prompt = "Select file> ",
})
```
with a slight modification after [this comment](https://github.com/ibhagwan/fzf-lua/issues/184#issuecomment-1375939972).

### Steps to reproduce

1. fzf-lua default configuration (no custom setup)
2. copy and paste the code from above and invoke
```lua
fzf_lua.fzf_exec("rg --files", {
  previewer = MyPreviewer,
  prompt = "Select file> ",
})
```
### Info

- Terminal: iTerm2
- `nvim --version`: NVIM v0.9.0-dev-581+gcb9d68fe6-dirty
- `fzf --version`: 0.35.1 (brew)

May it be relevant that I am running neovim nightly, in case you tested it working on stable?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d96c82a2a0fd2f1740303fe8dfc4a57cc0c3e4ad - should work now.

**Comment by gennaro-tedesco** [comment]
It works! Thank you as always for your prompt help!! :)

**Comment by gennaro-tedesco** [comment]
To close the loop on this I would like to showcase what our discussions went into: I have just released a new plugin (intended as fzf-lua extension): [nvim-possession](https://github.com/gennaro-tedesco/nvim-possession). As you can see from the demo, the previewer is used to parse the list of individual buffers that belong to a session :)

I've seen some discussions in the past where other users proposed an ecosystem of fzf-lua "extensions" similar to what happens with Telescope.nvim: I hope the topic can be opened up again in the future, it is really incredible what your project allows and with users building extensions around it, it can give more and better credit to the amazing job you've done! 

P. S. obviously feel free to include this example in the relevant wiki sections of users' cases, should you like to do so :) 

P. P. S. quick reddit post [here](https://www.reddit.com/r/neovim/comments/109xz5w/nvimpossession_a_simple_and_minimal_session/)

**Comment by ibhagwan** [comment]
> To close the loop on this I would like to showcase what our discussions went into: I have just released a new plugin (intended as fzf-lua extension): [nvim-possession](https://github.com/gennaro-tedesco/nvim-possession). As you can see from the demo, the previewer is used to parse the list of individual buffers that belong to a session :)
> 
> I've seen some discussions in the past where other users proposed an ecosystem of fzf-lua "extensions" similar to what happens with Telescope.nvim: I hope the topic can be opened up again in the future, it is really incredible what your project allows and with users building extensions around it, it can give more and better credit to the amazing job you've done!
> 
> P. S. obviously feel free to include this example in the relevant wiki sections of users' cases, should you like to do so :)
> 
> P. P. S. quick reddit post [here](https://www.reddit.com/r/neovim/comments/109xz5w/nvimpossession_a_simple_and_minimal_session/)

Amazing work @gennaro-tedesco! And ty for the kind words :)

I do believe there is a need for this type of functionality, it’s amazing what lua did to the plug-in ecosystem.

**Comment by gennaro-tedesco** [comment]
Would you mind if I added this example to the Wiki? I believe it's a good use case of a more complex usage of the in-built previewer (where users can send to the preview more or less any manipulation of text obtained via lua functions).

**Comment by ibhagwan** [comment]
> Would you mind if I added this example to the Wiki? I believe it's a good use case of a more complex usage of the in-built previewer (where users can send to the preview more or less any manipulation of text obtained via lua functions).

There is an updated example here:
https://github.com/ibhagwan/fzf-lua/wiki/Advanced#preview-nvim-builtin

But feel free to update it / add your 2 cents, the Wiki is open edit for all for this reason :)
