### ISSUE TITLE
How to combine lsp definition, implementation, declaration, reference?

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#606]
### Info

- Operating System:
- Shell:
- Terminal:
- `nvim --version`:
- `fzf --version`:

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
Is it possible to combine lsp definition, implementation, declaration, reference in 1 view/command, they can be categorized by the leading symbols/icons, similar to how Lspsaga lsp_finder did?

**Comment by ibhagwan** [comment]
No builtin command for that, you can craft it yourself using the API if you wish.

**Comment by sandangel** [comment]
I think that is possible for combining the list, but how about adding heading icons before the item/entry. Is it also possible with the API?

**Comment by ibhagwan** [comment]
> I think that is possible for combining the list, but how about adding heading icons before the item/entry. Is it also possible with the API?

Anything is possible with the API as it’s just a way to send arbitrary data into fzf, granted, it won’t be 2 lines of code and you’ll have to add the icons and classifications yourself but you can probably reuse some of the code from the LSP providers to reduce the amount of code you need to write.

**Comment by sandangel** [comment]
hi @ibhagwan thanks for the comment. Could you help point me to the right place/API that I could use for adding icons?

**Comment by ibhagwan** [comment]
> hi @ibhagwan thanks for the comment. Could you help point me to the right place/API that I could use for adding icons?

Icons are just unicode text, find which icon you want to use (depending on your terminal font, but you’re probably using a version of nerd font / font awesome), for nerd fonts you can search for icons [here](https://www.nerdfonts.com/cheat-sheet), then replace the `<icon>` below with whatever icon you wish.

Build a provider that does all LSP queries and combines the results and feed into fzf using the API:
```lua
:lua require'fzf-lua'.fzf_exec({ "<icon> line1", "<icon> line2" })
```

For performance considerations, async and coroutines read the [advanced Wiki](https://github.com/ibhagwan/fzf-lua/wiki/Advanced).

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if you need more help.
