### ISSUE TITLE
Selected object contains git sign and dev icon

### ISSUE THREAD

**Issue by xvzc** [ibhagwan/fzf-lua#607]
### Info

- Operating System: MacOS
- Shell: ZSH
- Terminal: Alacritty
- `nvim --version`: 0.8.0
- `fzf --version`: 0.33.0(brew)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
local fzf_lua = require('fzf-lua')
local util = require('util')
local profile = require('profile')

fzf_lua.setup {
  winopts = {
    preview = { default = 'bat_native' },
    height = 0.6,
    width = 0.6,
  }
}

local buf_opt = { noremap = true, silent = true }
util.nmap(
  '<C-M-f>',
  "<cmd>lua require('fzf-lua').files()<CR>",
  buf_opt
)

local obj = {}
obj.foo = function()
  require 'fzf-lua'.files({
    fzf_opts = { ['--preview-window'] = 'nohidden,down,50%' },
    actions = {
      ['ctrl-y'] = {
        function(selected)
          print("selected:", selected[1])
          -- uncomment to enable deletion
          -- vim.fn.delete(selected[1])
        end,
        require 'fzf-lua'.actions.resume
      }
    }
  })
end


return obj
```
</details>

### Description 
I'm trying to write a custom defined functionality with fzf-lua. With the foo function in my configuration, If i hit `Ctrl-y` key, then the selected item will be printed in the excution line. However, as you can see in the picture below, the selected item is being printed with dev icons and git signs. Is there any way to get the absolute path just like how `fzf` works in terminal?
<img width="862" alt="image" src="https://user-images.githubusercontent.com/45588457/211740249-fb96f871-dc1b-40cf-824c-155b270df0fc.png">

**Comment by ibhagwan** [comment]
To setup the dev icon you can use the `path` module to parse the entry.
To get the full path join with the current working directory
```lua
local path = require("fzf-lua").path

local custom_action = function(selected, opts)
  local entry = path.entry_to_file(selected[1])
  local fullpath = entry.path
  if not path.starts_with_separator(fullpath) then
    fullpath = path.join({ opts.cwd or vim.loop.cwd(), fullpath })
  end
  print(fullpath)
end
```

**Comment by xvzc** [comment]
Great answer. thanks!
