### ISSUE TITLE
How do I remove this double border from my split?

### ISSUE THREAD

**Issue by luisvgs** [ibhagwan/fzf-lua#608]
### Info

- Operating System: Endeavouros
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: 0.8.1
- `fzf --version`: 0.35

```lua
require('fzf-lua').setup({
	winopts = {
		split = "belowright new | resize -10",
	},
	files = {
		previewer = false,
		cmd = "fd --type f --exclude '!{.git,node_modules,target}/'",
	},
	grep = {
		previewer = false,
		cmd = "rg --color=always --smart-case -g '!{.git,node_modules}/'",
	},
	oldfiles = {
		previewer = false,
	},
})
```
</details>

### Description 
Hello, first of all, I want to thank you for the effort you put into maintaining this awesome plugin. I recently switched back from Telescope and noticed the following when opening a split. As you can see in the image I'm attaching, there's another border above Fzf's split, causing some sort of double border thing. I wonder if one can get rid of it to make it look more accurate? I would appreciate any further suggestion. Thanks in advance.
![image](https://user-images.githubusercontent.com/10943988/211873155-039c27b4-cffe-4904-b949-5464af77a250.png)

**Comment by ibhagwan** [comment]
Ty for the kind words @luisvgs.

This is actually a new feature introduced with fzf 0.35, to disable:
```lua
require('fzf-lua').setup({
  fzf_opts = { ['--no-separator'] = '' },
  …
})
