### ISSUE TITLE
Feature request: ability to conditionally hide preview?

### ISSUE THREAD

**Issue by jonaz** [ibhagwan/fzf-lua#610]
Instead of `flip_columns` i would like to hide the preview if colums are below 120. 

Thanks for a great plugin! Just migrated from my custom legacy setup based on pure vimscript fzf.

**Comment by ibhagwan** [comment]
This doesn’t need a feature, you can easily achieve that with:
```lua
:lua require'fzf-lua'.files({ previewer = vim.o.columns > 120 and 'builtin' or false })
```
