### ISSUE TITLE
Windows OS Support

### ISSUE THREAD

**Issue by noheromen** [ibhagwan/fzf-lua#613]
Hi,

will there be support for Windows OS, or its not considered at all? Thank you :)

**Comment by ibhagwan** [comment]
> Hi,
> 
> will there be support for Windows OS, or its not considered at all? Thank you :)

I have no plans to do this myself, would welcome a PR though.

**Comment by ibhagwan** [comment]
Closing, if someone decides to pick this up please open a PR.

**Comment by ibhagwan** [comment]
FYI, windows is now supported follow #1038 and the [windows branch](https://github.com/ibhagwan/fzf-lua/tree/windows) for more info.
