### ISSUE TITLE
Advanced git grep with large repositories

### ISSUE THREAD

**Issue by freswa** [ibhagwan/fzf-lua#614]
### Info

- Operating System: Linux
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: 0.8.2
- `fzf --version`: 0.35.1

Sorry for asking here, feel free to close if inappropriate. I'm running the example from [here](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#example-2-live-git-grep) which backs my work tremendously, though I found an edge case where it, or rather `sh`, fails with `sh: line 1: /usr/bin/git: Argument list too long`.

To repro, clone gcc from `https://sourceware.org/git/gcc.git` and checkout `releases/gcc-12`.

As far as I investigated, the command fails due to the repo being to large returning to many refs and then sh fail with too many args. Unfortunately I also fail to find any workaround. I'd much appreciate any hint how to get git live grep working even for large repos.

**Comment by ibhagwan** [comment]
Ty for the report, I will look into it.

As a temp workaround, if all you’re interested is live grep (and not commit history), why aren’t you using `live_grep` directly or `live_grep({ cmd = "git grep --line-number --column --color=always <query>" })`?

**Comment by freswa** [comment]
I don't use `git grep` directly because I'm interested in the commit history here :)

**Comment by ibhagwan** [comment]
> I don't use `git grep` directly because I'm interested in the commit history here.
> Thanks for looking into it :)

I see :)

The solution will have to come from an alternative to the command as this is “out of the hands” of fzf-lua, `sh` seems to be unable to handle the amount of commits returned by `$(git rev-list --all)`.

**Comment by freswa** [comment]
It's a bit embarrassing I didn't found that stackoverflow question, but setting the cmd to `git rev-list --all | xargs git grep --line-number --column --color=always <query>` works perfectly here.
Maybe that's a good candidate for the docs as a more generic approach?
