### ISSUE TITLE
[Feature] Fzf find files inside project 

### ISSUE THREAD

**Issue by RayZ0rr** [ibhagwan/fzf-lua#616]
I wrote this little snippet with reference from [root dir function from lsp-config](https://github.com/neovim/nvim-lspconfig/blob/1e988250a0f52a68ddb72905d623405d634e9c5d/lua/lspconfig/server_configurations/clangd.lua#L46).

It's main objective is to jump between files in your project. Sometimes the project won't be a git repo. But it might have other files which indicates the root directory like **'setup.py',  'requirements.txt', 'cmake', 'build', ''compile_commands.json', '.clang-format'** etc. This file start file search from the directory which contains such files:

```lua
local util = require 'lspconfig.util'
local root_files = {
  '.clangd',
  '.clang-tidy',
  '.clang-format',
  'compile_commands.json',
  'compile_flags.txt',
  'configure.ac',
  'cmake',
  'setup.py',
  'requirements.txt',
  'build'
}

root_dir = function(fname)
  return util.root_pattern(unpack(root_files))(fname) or util.find_git_ancestor(fname)
end,
nnmap('<leader>fp', function() require('fzf-lua').files({cwd = root_dir(vim.api.nvim_buf_get_name(0))}) end, {desc="Fzf-Lua search project"})
```

It's not that pretty and also has a dependency on lsp-config. Someone with more knowledge might improve upon it. Maybe make it a function which accepts a list of root_files or use a default one like above.

**Comment by ibhagwan** [comment]
Looks great, ty @RayZ0rr!
