### ISSUE TITLE
Trying to port telescope-undo and cannot find a way to use a custom entry_maker

### ISSUE THREAD

**Issue by AndreaHasani** [ibhagwan/fzf-lua#617]
```lua
require('fzf-lua').setup({
})
```

### Description 
I'm trying to port the plugin over at github.com/debugloop/telescope-undo.nvim for use with fzf-lua. This is the first time messing around with lua on neovim so probably I'm missing something.

Looking over at the ```init.lua``` for that plugin, I noticed that the ```M.undo``` is the one creating the telescope window (it also handles actions and previews on some other folders but I have not started to look at them yet since I'm having issues at the start).

The problem I'm facing is over at:

```lua
M.undo = function(opts)
  if not vim.api.nvim_buf_get_option(0, "modifiable") then
    print("telescope-undo.nvim: Current buffer is not modifiable.")
    return
  end
  opts = opts or {}
  pickers
      .new(opts, {
        prompt_title = "Undo History",
        finder = finders.new_table({
          results = build_undolist(opts),
          entry_maker = function(undo)
            local order = require("telescope.config").values.sorting_strategy

            -- TODO: show a table instead of a list
            if #undo.additions + #undo.deletions == 0 then
              -- skip empty changes, vim has these sometimes...
              return nil
            end
            -- the following prefix should work out to this graph structure:
            -- state #1
            -- └─state #2
            -- state #3
            -- ├─state #4
            -- └─state #5
            -- state #6
            -- ├─state #7
            -- ┆ ├─state #8
            -- ┆ └─state #9
            -- └─state #10
            local prefix = ""
            if undo.alt > 0 then
              prefix = string.rep("┆ ", undo.alt - 1)
              if undo.first then
                local corner = order == "ascending" and "┌" or "└"
                prefix = prefix .. corner .. "╴"
              else
                prefix = prefix .. "├╴"
              end
            end
            local diffstat = ""
            if #undo.additions > 0 then
              diffstat = "+" .. #undo.additions
            end
            if #undo.deletions > 0 then
              if diffstat ~= "" then
                diffstat = diffstat .. " "
              end
              diffstat = "-" .. #undo.deletions
            end
            return {
              value = undo,
              display = prefix
                  .. opts.entry_format:gsub("$ID", undo.seq):gsub("$STAT", diffstat):gsub("$TIME", timeago(undo.time)),
              ordinal = undo.ordinal,
            }
          end,
        }),
        previewer = get_previewer(opts),
        sorter = conf.generic_sorter(opts),
        attach_mappings = function(prompt_bufnr, map)
          for _, mode in pairs({ "i", "n" }) do
            for key, get_action in pairs(opts.mappings[mode] or {}) do
              map(mode, key, get_action(prompt_bufnr))
            end
          end
          -- TODO: provide means to filter for time frames
          return true -- include defaults as well
        end,
      })
      :find()
end
```

I'm trying to rewrite this function using ```fzf_lua.fzf_exec```.

From what I can see above, on telescope the plugin gives ```build_undolist``` as content and uses ```entry_maker``` to parse the table.

I cannot find any argument on ```fzf_exec``` which allows this, the ```fn_transform``` is only available for strings.

Is there any way to do this?

**Comment by ibhagwan** [comment]
> I cannot find any argument on fzf_exec which allows this, the fn_transform is only available for strings.

At the end of the process everything that goes into fzf is a string, `fn_transform` is only required when you want to “transform” a shell command line output for each line.

What you need to do is build your list and then feed a table of the strings you wish to display to `fzf_exec`, you can save the undo list with metadata as a local object in your file.

**Comment by AndreaHasani** [comment]
I understand that I can do that, what I was worried about is how I get to identify on which line I am when I select so I can know which table to reference on the object.

**Comment by ibhagwan** [comment]
> I understand that I can do that, what I was worried about is how I get to identify on which line I am when I select so I can know which table to reference on the object.

There are different ways to do it, one such way would be to add an index to each line  e.g`[1]`, hide it using fzf’s `--nth`, parse the entry on select and access the index using the extracted number.

**Comment by ibhagwan** [comment]
Take a look at the `ui_select` provider for a more concrete example, you can either leave the index displayed or hide it with fzf’s `--with-nth`:

https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/ui_select.lua

**Comment by AndreaHasani** [comment]
Managed to get it working (together with the preview). Was not that hard (as a first time lua user).
The only thing I'm stuck at now is how to get the highlighter to work.

The plugin seems to use require("telescope.previewers.utils").highlighter (and I kinda don't want to have telescope installed just for one function).

From what I can see here: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/previewers/utils.lua, the plugin sets the buffer highlight via regex or treesitter I thnk

**Comment by ibhagwan** [comment]
> Managed to get it working (together with the preview). Was not that hard (as a first time lua user). The only thing I'm stuck at now is how to get the highlighter to work.

 
Nice job!

> The plugin seems to use require("telescope.previewers.utils").highlighter (and I kinda don't want to have telescope installed just for one function).
> 
> From what I can see here: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/previewers/utils.lua, the plugin sets the buffer highlight via regex or treesitter I thnk

I agree, minimal dependencies, I haven’t looked at the code but you can use the neovim API for highlights which is probably what this does, take a look at how fzf-lua highlights the cursor / match using `search`, `matchaddpos` etc:

https://github.com/ibhagwan/fzf-lua/blob/292de730ebbd3834e87f864c8c4115dc1035db37/lua/fzf-lua/previewer/builtin.lua#L691-L717

**Comment by ibhagwan** [comment]
Another example of using neovim highlights in the previewer from the `highlights` provider:
https://github.com/ibhagwan/fzf-lua/blob/292de730ebbd3834e87f864c8c4115dc1035db37/lua/fzf-lua/previewer/builtin.lua#L1075-L1116

**Comment by tssm** [comment]
Hey @AndreaHasani, have you made a plug-in out of this? I was going to port the same functionality, but I prefer to use yours

**Comment by AndreaHasani** [comment]
Yeah, Ill take a look if I can find it and if so ill make a github rebot

**Comment by vinoff** [comment]
Any news on this guys? @AndreaHasani , @tssm 

I am also interested in having telescope-undo ported to fzf-lua as I am moving my config from telescope to fzf-lua.

**Comment by sweetboss12512** [comment]
this is something i miss from telescope
