### ISSUE TITLE
It seems that `vim.fn.expand('%')` will return `{bufnr}/{file_path}` instead of `{file_path}` from the preview buffer

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#618]
#### Context

In `nvim-treesitter` there is an option(it's a key of a table) `is_supported` for a module, which is used to determine whether or not the module should be enabled on a given buffer.

#### Problem

In `is_supported`, I need to make use of `vim.fn.expand('%')` to get the name of the file to be opened. So I tried to `print()` it, and I realized that the output looks different after I run any fzf-lua command with a preview window(I guess treesitter was trying to parse the preview buffer), e.g.

```
22:34:44 msg_show 196/bfd.h
22:34:44 msg_show 199/cmp-codeium.md
22:34:44 msg_show 202/hello.go
22:34:45 msg_show 205/lazy-lock.json
```

So I assume the format is `{bufnr}/{file_path}`. This increases the complexity of getting the path of the file:

```lua
-- to get the `{file_path}` only
(vim.fn.expand('%'):gsub('^%d*/', ''))
```

Is this by design? If so, am I correct to say that the format is `{bufnr}/{file_path}`? I'm afraid that my assumption might be wrong, then my further usages of `{file_path}`, e.g. some APIs will return `nil` if the file path is invalid(apparently I don't have folders `{bufnr}` under the current path), will all be wrong.

Thanks for your reading.

**Comment by ibhagwan** [comment]
FzfLua does not modify the behavior of `expand` nor have I see this behavior anywhere else, I don’t think this is related to fzf-lua.

**Comment by ibhagwan** [comment]
If you need the selected entry why don’t you use `get_info`? See https://github.com/ibhagwan/fzf-lua/issues/537#issuecomment-1272418720

**Comment by nyngwang** [comment]
> [...] so it can be properly highlighted but not conflict with any other existing buffer, [...]

Clever idea! I didn't consider this part. Thanks for your explanation :)

> Btw, the issue here is not with `expand`, this is actually the (temporary) buffer name.

But during my testing, the only line I used to print is this: 

```lua
print(vim.fn.expand('%'))
```

> If you need the selected entry why don’t you use get_info?

No, it's not me who needs the selected entry. The problem is that `is_supported` will be called upon the preview buffers of fzf-lua, i.e. nvim-treesitter will be applied to these buffers too. If I use fzf-lua'a `get_info` to get the buffer name, then treesitter will only work with these preview buffers.

**Comment by ibhagwan** [comment]
> But during my testing, the only line I used to print is this: (maybe the underlying code would pick buffer name for expansion?)

When you call expand with `%`  you’re asking for the current buffer name, this is the same as calling `vim.api.nvim_get_current_buffer()`, since the buffer name is prepended with the buffer number the result is what you experience, this is the actual name of the temporary preview buffer.

**Comment by nyngwang** [comment]
Okay. I will keep using this `(vim.fn.expand('%'):gsub('^%d+/', ''))` until it might be changed in the future. Closing...
