### ISSUE TITLE
How to exclude hidden buffers from :FzfLua buffers ?

### ISSUE THREAD

**Issue by aerosol** [ibhagwan/fzf-lua#619]
### Info

- Operating System: linux
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: v0.8.2
- `fzf --version`: 0.37

### Description 

Opening a netrw window makes it visible in :FzfLua buffers even though it's hidden. I'm wondering how can I turn off that behavior and make them disappear from the picker.

![image](https://user-images.githubusercontent.com/173738/215824216-55f6317c-b73b-4afd-9872-dfac5db16205.png)

![image](https://user-images.githubusercontent.com/173738/215824282-194b49af-c548-498c-9ab9-fa9533afe021.png)

**Comment by ibhagwan** [comment]
Hidden buffers are automatically excluded, the above examples doesn’t seem like hidden buffers but rather `unnamed` buffers (similar to a buffer generated by `:new’), something is creating these buffers in your setup.

Run `:ls` and you’ll see all visible buffers, I suspect you’d see the `[No Name]` buffer there as well, you can see hidden buffers by running `:ls!`.

**Comment by aerosol** [comment]
Thanks for your quick reply (and for the plugin!). 
I think `unlisted` vs `hidden` is kind of confusing, I'm sorry for the noise.
