### ISSUE TITLE
How to check all LSP references restricted to the cwd?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#620]
### Description 

As title. So `:pwd` shows `/Users/ningwang/GitHub/NeoNoName.lua`, but I got results outside of it:

- The first four results should be removed. (Not sure why these results are shown.)
- Will be great if the `cwd` for `FzfLua references`can be shown too.

I have tried: `require('fzf-lua').lsp_reference({ cwd = vim.fn.getcwd(-1, -1) })` and the result is the same.

<img src="https://user-images.githubusercontent.com/24765272/216070326-7a631a75-c448-4d54-96b7-4fae77aebebe.png" width="500">

**Comment by ibhagwan** [comment]
Have you tried `:FzfLua lsp_references cwd_only=true`?

**Comment by nyngwang** [comment]
@ibhagwan That's it. Really sorry for the bad question.

**Comment by ibhagwan** [comment]
> The first four results should be removed. (Not sure why these results are shown.)

This is related to your LSP setup, fzf-lua simply relays what the LSP server replies with, if you run `:vim.lsp.buf.references()` you will see the same results.

**Comment by ibhagwan** [comment]
> Thanks for your hint. And I just realized that I also need to set the same for lsp_definition. I'm using the default setup for sumneko_lua from lspconfig, so not sure why this happened. :/

You have to configure `.luarc.json` at the project root, for exmaple here's the one from my neovim config:
```json
{
    "runtime.version": "LuaJIT",
    "diagnostics": {
        "enable": true,
        "globals": [
          "vim",
          "describe",
          "pending",
          "it",
          "before_each",
          "after_each",
        ],
        "neededFileStatus": {
          "codestyle-check": "Any"
        }
    },
    "workspace": {
        "library": [
            "runtime/lua",
        ],
        "checkThirdParty": false,
        "maxPreload": 2000,
        "preloadFileSize": 1000
    },
    "telemetry.enable": false
}
```
