### ISSUE TITLE
Setting custom keybind action to call lua function

### ISSUE THREAD

**Issue by momja** [ibhagwan/fzf-lua#621]
### Info

- Operating System: MacOS Montery 12.6
- Shell: ZSH
- Terminal: Kitty Terminal
- `nvim --version`: v0.8.1
- `fzf --version`: 0.36.0 (brew)

- [X] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
pasteFilename = function(selected, opts)
    print("selected:", selected[1])
end

local actions = require'fzf-lua.actions'
require 'fzf-lua'.setup({
  actions = {
    files = {
      ["default"]       = actions.file_edit,
      ["ctrl-s"]        = actions.file_split,
      ["ctrl-v"]        = actions.file_vsplit,
      ["ctrl-t"]        = actions.file_tabedit,
      ["alt-q"]         = actions.file_sel_to_qf,
      ["ctrl-space"]    = pasteFilename,
    },
  },
})

```
</details>

### Description
When I'm in the file finder, I would expect pressing "ctrl-space" to display the text "selected: <filename>" on the command line, but instead the window closes and nothing happens. Is there something I'm missing here? From the wiki, I think I need to declare all these keybindings, before providing custom actions. The other commands, "ctrl-v", "ctrl-t", etc do what I'd expect. Please excuse me if there's an issue with my lua code. I'm new to this.

**Comment by ibhagwan** [comment]
Looking at the [fzf man page](https://www.mankier.com/1/fzf#Key/Event_Bindings-Available_Keys:_(Synonyms)) it seems that `ctrl-space` is not a valid bind, you can perhaps work around it by creating a neovim bind using the FzfLua `on_create` event.

**Comment by momja** [comment]
> Looking at the [fzf man page](https://www.mankier.com/1/fzf#Key/Event_Bindings-Available_Keys:_(Synonyms)) it seems that `ctrl-space` is not a valid bind, you can perhaps work around it by creating a neovim bind using the FzfLua `on_create` event.

@ibhagwan `ctrl-space` is listed second from top

**Comment by ibhagwan** [comment]
> > Looking at the [fzf man page](https://www.mankier.com/1/fzf#Key/Event_Bindings-Available_Keys:_(Synonyms)) it seems that `ctrl-space` is not a valid bind, you can perhaps work around it by creating a neovim bind using the FzfLua `on_create` event.
> 
> @ibhagwan `ctrl-space` is listed second from top

Oops my bad, the interface does close with actions, can you check if the print appears in `:messages`, perhaps it’s just hidden due to cmd line settings.

**Comment by ibhagwan** [comment]
Also, can you see your bind setup as `function` in the help (default `F1`)?

**Comment by momja** [comment]
I do see the filename and icon when I type `:messages`! That's good, as for your second comment. I'm not sure I know what you mean. If you are asking whether there is a conflicting nvim keybinding on `CTRL-Space`, I don't believe so. No binding is listed in `:help index`

**Comment by momja** [comment]
What's strange is when I try to replace lua's `print` method with something like `vim.cmd("echo '" .. selected[1] .. "'")`, I get no output in messages at all.

**Comment by ibhagwan** [comment]
> What's strange is when I try to replace lua's `print` method with something like `vim.cmd("echo '" .. selected[1] .. "'")`, I get no output in messages at all.

I’m not sure why is that but your function seem to get called so you can do pretty much anything from here.

**Comment by ibhagwan** [comment]
> as for your second comment. I'm not sure I know what you mean

When any FzfLua interface is open you can press `F1` to see FzfLua binds, I wanted to see if your `ctrl-space` was registered and appears there.

**Comment by ibhagwan** [comment]
> It looks the keybind is registered and the function is getting called. I will close this issue. Thank you!

Btw, if you want to register an action help string for your function to appear in the `F1` screen:
```lua
require("fzf-lua").config.set_action_helpstr(pasteFilename, "my-custom-help")
```
