### ISSUE TITLE
Some enhancements about the `tab_title` option of `FzfLua tabs`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#622]
### Description

In my current workflow, I will open many Vim tabpages, and I will call `:tcd` on some of them to change tabpage-local directory. It will be great if `FzfLua tabs` could show this information. Since in #588 you already provided an option(I'm really grateful for your helps!) but it's not very useful if it's just a fixed value (I haven't tested passing a function to it but I guess it is not supported yet):

```lua
require("fzf-lua").tabs({
  tab_title=TEST
})
```

I'm thinking about maybe you could support passing a function for it:

- I haven't investigated your code but I think it will be cool if this `tab_title` option could be a function and you could call it on each tabpage. This way we can get the `tabid` as shown below.
- Maybe you could also pass another parameter `tabnr`, which is the number `#n` follows the title, since we cannot know it from barely `tabid`. E.g. a nonsense example: I can use a table to map each `tabnr` to a symbol so that I can decorate the title of each tabpage.

```lua
require("fzf-lua").tabs({
  tab_title = function(tabid) -- I'm still not sure about the param(s)
    -- then I can get the tabpage-local directory myself if the params are provided properly.
    local cwd_tab = vim.fn.getcwd(-1, tabid)
    -- do something the generate the `title_str`.
    return title_str
  end
})
```

This will be really useful for anyone who makes use of `:tcd`. It's really a good idea I promise! (Now the only way to get tabpage-local directory is either calling `pwd` or using some filetree plugin that is aware of tabpage-local directory.)

Thanks for your reading!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/9d00cb0e7a179af132bb663473e0759d18147165 - here you go.

Simple usage:
```lua
:lua require("fzf-lua").tabs({ tab_title = function(t) return "TABIDX" .. t end })
```

The full function signature also providers a `is_current_tab` variable so you can determine if this is the current tab, to extract the `tabnr` from the tab idx use `vim.api.nvim_list_tabpages`:
```lua
function(tab_idx, is_current)
  local tabnr = vim.api.nvim_list_tabpages()[tab_idx]
  ...
end
```

**Comment by nyngwang** [comment]
insane! I thought this will happen many hours later! Let me try it now and thank you so much!

**Comment by nyngwang** [comment]
The best way to reward a plugin author is to show off him/her using the plugin itself:

<img src="https://user-images.githubusercontent.com/24765272/216221018-37844f1d-886f-4794-ace7-d756aa2a76c9.png" width="500">

Closing...!

**Comment by ibhagwan** [comment]
> The best way to reward a plugin author is to show off him/her using the plugin itself:
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/24765272/216221270-5ef52539-fad7-4e1d-b106-3c48263559fc.png">
> 
> Closing...!

Looks wondeful @nyngwang! :rocket:

**Comment by nyngwang** [comment]
@ibhagwan Just completed the change. Thanks for these enhancements!

<img src="https://user-images.githubusercontent.com/24765272/217319546-7152d465-595c-4245-841e-4a0bf65be1ec.png" width="500">

**Comment by ibhagwan** [comment]
>  FYI: I just realized the importance of accessing tabnr first.(otherwise I got error when interacting with some other plugins/built-in APIs) Thanks a lot for your kindness in the old comment(s).

ty @nyngwang
