### ISSUE TITLE
Some of the names of buffers in `FzfLua tabs` are wrong with respect to the tabpage-local current directory.

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#623]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: `NVIM v0.9.0-dev-856+gecc1595c7`
- `fzf --version`: `0.37.0 (brew)`

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})

vim.keymap.set('n', '<C-b>', function () require('fzf-lua').tabs {
  actions = { ['ctrl-b'] = 'abort' },
  tab_title = function (tab_idx, is_current)
    local tab_path = vim.fn.getcwd(-1, tab_idx)
    return string.format('%s Tab #%d: %s', (is_current and '⛩️ ' or ' '), tab_idx, tab_path)
  end
} end)
```

</details>

### Description 

(Sorry that I haven't tested this with a minimal config. I will test it later today. So I instead provided the relevant config of `FzfLua tabs` above)

I expect that:

- If it's possible, then a buffer that is located under the same path as the tabpage-local directory `vim.fn.getcwd(-1, 0)` should only show: filename + extension. Otherwise, it should show the absolute path instead.
- If this is inconvenient regarding implementation, then I will expect a consistent result: all relative / all absolute. Some of the buffer names are incorrect with regard to the tab-local directory, as shown below.

<img src="https://user-images.githubusercontent.com/24765272/216223751-c29e428d-4983-433f-8ac9-1e01b36d5a3c.png" width="200"><img src="https://user-images.githubusercontent.com/24765272/216223616-5bb0bbb2-43f6-4562-8edf-ca7066c8158e.png" width="600">

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/ed0aa6cb562e5151ecd54d6faa9fa86933615543 - I also added a display of the cwd to the tab header (similar to what you did) **only if the tab `cwd` is different than global**.

**Comment by nyngwang** [comment]
I'm really happy to find out `FzfLua tabs` at the start of 2023 :) Closing...!
