### ISSUE TITLE
[Question] Indentation size in blines results

### ISSUE THREAD

**Issue by idr4n** [ibhagwan/fzf-lua#624]
Hi,
I was wondering if it is possible to control or reduce the indentation size in which the results of `Fzflua blines` are displayed (not the preview window)
![CleanShot 2023-02-02 at 09 42 35@2x](https://user-images.githubusercontent.com/20104703/216251780-2a851517-e115-4110-9a65-2a6565b4856d.png)

For example, this file only has 2 spaces indentation but Fzflua is showing something like 8 spaces I believe?

I just prefer those results to have minimal indentation, something similar to Telescope or even fzf.vim.

![CleanShot 2023-02-02 at 09 48 33@2x](https://user-images.githubusercontent.com/20104703/216252259-3bd53e60-556f-469c-ab3d-af0377ff833a.png)
![CleanShot 2023-02-02 at 09 49 45@2x](https://user-images.githubusercontent.com/20104703/216252496-6b46a66d-af24-49a4-8087-1ded2a613530.png)

**Many thanks for an awesome plugin!**

**Comment by ibhagwan** [comment]
Ty for the kind words @idr4n!

I didn’t know this was the case, we’ll definitely fix that, FzfLua just copies the lines exactly as they are found in the original buffer and feeds them into fzf which renders the lines.

I’m assuming this has to do with your neovim tab settings, few questions:
- What are your default tab settings in neovim (`expandtab`, `shiftwidth`, etc)?
- Do you have different different settings from the above for lua files specifically?
- In the example posted, the preview seems to show tab width of 4, is that correct?
- in the example posted, is the file indented with tabs or spaces?

**Comment by ibhagwan** [comment]
Turned out to be an easy fix, this only happens when using tabs for indentation, `fzf.vim` uses `--tabstop=1` and Telescope seems to exhibit the same behavior. I added `--tabstop=1` to the default options (configurable) of both `lines` and `blines` in https://github.com/ibhagwan/fzf-lua/commit/b51e6772339d55e54cccbd6f5cabaab14ba00648.

Update to the latest commit and it should behave as expected.

**Comment by idr4n** [comment]
Yes, it behaves as expected! Thanks a lot for the update and for the quick response as always 🙏🏻
