### ISSUE TITLE
[feat] window picker action for file / buf selection

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#625]
it would be nice to have a fzf-lua action which can be passed to commands like `lsp_definitions` and `buffers`, which trigger a window-selection after an entry is chosen. something like the window-picker in `nvim-tree` or using a lib like [nvim-window-picker](https://github.com/s1n7ax/nvim-window-picker).

**Comment by ibhagwan** [comment]
What would be the use case for this? Pick a window where the reference should be opened?

In any event, I don’t think I wish to maintain such a relatively open ended action with many config options especially when such options like `nvim-window-picker` exists, which brings me to the second question: why not create a simple custom action and call `nvim-window-picker`?

**Comment by athanase** [comment]
Hello @ViRu-ThE-ViRuS,

This is also a feature I am interested in. Could please the custom action you wrote to make this work ?

Thanks a lot.

**Comment by athanase** [comment]
@ibhagwan maybe you could help me understand why my custom action does not work.
```
local actions = require("fzf-lua.actions")
local function pick_window_and_edit(selected, opts)
    local fallback = vim.api.nvim_get_current_win()
    local window_id = require('window-picker').pick_window() or fallback
    vim.api.nvim_set_current_win(window_id)
    actions.file_edit(selected, opts)
end
```

When using this custom action for files fzf-lua picker, the pick_window() ui rapidly appears on screen then disappears, the picked file is open, and some characters are printed in the newly opened file.
