### ISSUE TITLE
[Question] How to pass a list of raw args to `fzf_exec` ?

### ISSUE THREAD

**Issue by RayZ0rr** [ibhagwan/fzf-lua#627]
I am trying to remove [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) 's dependence on `fzf#run` to `fzf_exec`. The following is the code I want to change:

[nvim-bqf code that uses fzf#run](https://github.com/kevinhwang91/nvim-bqf/blob/da1cd2557a16386829a213330e0fd46b61db7632/lua/bqf/filter/fzf.lua#L506)

At the very end, I want to pass the `opts.options` flags list to `fzf_exec` I tried going through various docs and methods but I don't think it's working.

Here is my current version:
```lua
function M.run()
    local qwinid = api.nvim_get_current_win()
    local qlist = qfs:get(qwinid):list()
    local prompt = qlist.type == 'loc' and ' Location> ' or ' Quickfix> '
    local size = qlist:getQfList({size = 0}).size
    if size < 2 then
        return
    end
    -- greater than 1000 items is worth using headless as stream to improve user experience
    local source = size > 1000 and sourceCmd or sourceList

    local baseOpt = {'--color', 'gutter:-1'}
    if compareVersion(version, '0.27.4') >= 0 then
        table.insert(baseOpt, '--scroll-off')
        table.insert(baseOpt, utils.scrolloff(qwinid))
    end
    if compareVersion(version, '0.35.0') >= 0 then
        table.insert(baseOpt, '--no-separator')
    end

    -- TODO
    -- ctx.fzf_extra_opts and ctx.fzf_action_for are used by myself, I'm not sure who wants them.
    local ctx = qlist:context().bqf or {}
    ctxActionFor = nil
    if type(ctx.fzf_action_for) == 'table' then
        ctxActionFor = vim.tbl_extend('keep', ctx.fzf_action_for, actionFor)
        filterActions(ctxActionFor)
    end
    local expectKeys = table.concat(vim.tbl_keys(ctxActionFor or actionFor), ',')
    vim.list_extend(baseOpt, {
        '--multi', '--ansi', '--delimiter', [[\|]], '--with-nth', '2..', '--nth', '3..,1,2',
        '--header-lines', 0, '--tiebreak', 'index', '--info', 'inline', '--prompt', prompt,
        '--no-border', '--layout', 'reverse-list', '--expect', expectKeys
    })
    local options = vim.list_extend(baseOpt, ctx.fzf_extra_opts or extraOpts)
    local delimiter = parseDelimiter(options)
    local bind = parseBind(options)
    local opts = {
        options = options,
        source = source(qwinid, qlist:sign():list(), delimiter),
        ['sink*'] = function(lines)
            return handler(qwinid, lines)
        end,
        window = {
            width = api.nvim_win_get_width(qwinid),
            height = api.nvim_win_get_height(qwinid) + 1,
            xoffset = 0,
            yoffset = 0,
            border = 'none'
        }
    }

    local tmpfile = fn.tempname()
    vim.list_extend(opts.options, {'--preview-window', 0, '--preview', 'echo {1} >> ' .. tmpfile})
    local releaseCallback = watchFile(qwinid, tmpfile)
    M.postHandle = function()
        releaseCallback()
        M.postHandle = nil
    end
    phandler.keepPreview()

    cmd(('au BqfFilterFzf FileType fzf ++once %s'):format(
        ([[lua require('bqf.filter.fzf').preHandle(%d, %d, %q)]]):format(qwinid, size, bind)))

    if ok_fzf_lua then
      fzf_lua.fzf_exec(opts.source,
      {
	-- fzf_args = opts.options,
	-- fzf_args = table.concat(opts.options,' '),
	fzf_raw_args = opts.options ,
	actions = {
	  ['default'] = function(lines)
	      return handler(qwinid, lines)
	  end
	}
      })
    else
      fn.BqfFzfWrapper(opts)
    end
end
```

**Comment by ibhagwan** [comment]
You can pass fzf flags in two different ways:
1. As a table with `fzf_opts`
2. As raw args with `fzf_cli_args`, I.e. `fzf_exec`{ … }, { 'fzf_cli_args’ = … })` (the entire argument will be encapsulated with `vim.fun.shellescape` automatically)

**Comment by ibhagwan** [comment]
Actually, I see you already used `fzf_raw_args` which is the same argument, the issue is you’re sensing it as a table which isn’t proxied directly to `termopen`, it wasn’t possible due to stream redirection limitations so I had to use a plain string for arguments with `sh -c`.

What you need to do is convert`opts.options` to a string with shell escaping for complex values so it will probably be a bit more nuanced than `table.concat`.

I can also try and revisit the issue of passing the arguments as a table directly to `termopen` but can’t make any promises as for the result.

**Comment by RayZ0rr** [comment]
> I can also try and revisit the issue of passing the arguments as a table directly to termopen but can’t make any promises as for the result.

It's okay if this isn't implemented. The main reason I'm trying to do this nvim-bqf PR myself is to take burden off you.

You guys can focus on other more important stuff. Let us(or just me :P) focus on the relatively simpler stuff.

**Comment by ibhagwan** [comment]
> > I can also try and revisit the issue of passing the arguments as a table directly to termopen but can’t make any promises as for the result.
> 
> It's okay if this isn't implemented. The main reason I'm trying to do this nvim-bqf PR myself is to take burden off you.
> 
Tysm!

I’ll give it a go again, if I can get rid of the output redirection at the shell level that would be a good first step for supporting windows, I even forgot what was the hurdle last time I tried.

> You guys can focus on other more important stuff. Let us(or just me :P) focus on the relatively simpler stuff.

There’s just me for now :) and it’s been relatively stable for a while now, only questions and feature requests and barely any bugs.

**Comment by ibhagwan** [comment]
I just revisited this and tried to convert the `termopen` (esssentially `jobstart`) to `no-shell` to be able to supply a table or raw arguments with no shell ecaping requirements, I'm again stuck at the lack of shell redirection.

To be able to "act" upon selection we need to redirect the fzf output into a file (maybe there's a better way?) and redirection ( `>`) requires the use of a shell, I tried removing the shell requirement by using jobstart's `on_stdout` parameter but it gets called for each line and each screen modification and I can't seem to find a way to discrern betweem the fzf draw output and the "post-selection" output.

TBH I would just convert `baseOpt` to the below and then pass it as `fzf_opts`:
```lua
local baseOpt = {
  ['--multi']        = "",
  ['--ansi']         = "",
  ['--delimiter']    = vim.fn.shellescape([[\|]]),
  ['--with-nth']     = '2..',
  ['--nth']          = '3..,1,2',
  ['--header-lines'] = "0",
  ['--tiebreak']     = 'index',
  ['--info']         = 'inline',
  ['--prompt']       = vim.fn.shellescape(prompt),
  ['--no-border']    = "",
  ['--layout']       = 'reverse-list',
  ['--expect']       = vim.fn.shellescape(expectKeys),
}
```

**Comment by ibhagwan** [comment]
Reading the code again I would also avoid the `--expect`, use the `actions` keybind table instead and let fzf-lua build the `--expect` argument by itself.
