### ISSUE TITLE
`FzfLua tabs` will cause an error on closing any existing tabs: `Vim:E5000: Cannot find tab number.`

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#628]
### Info

- Operating System: macOS 
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: `NVIM v0.9.0-dev-878+g6c39edaa7`
- `fzf --version`: `0.37.0 (brew)`

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})

vim.keymap.set('n', '<C-b>', function () require('fzf-lua').tabs() end)
```
</details>

You might try to reproduce it with these steps:

```
:tabnew
:tabnew
:tabnew
:tabp
:q
:FzfLua tabs
```

### Description 

I got the following error log when I called `FzfLua tabs` on closing any existing tabs after restoring from a Vim session: (It seems that this is related to those tabs that left got their tab-number updated, but I'm not sure.)

- It also changed to the normal mode instead of terminal mode on the fzf-lua floating window.
- The fzf-lua floating window shown a `[Process exited 130]` after I pressed `<Esc>` on the fzf-lua floating window in terminal mode.

```
E5108: Error executing lua ...k/vendor/start/fzf-lua/lua/fzf-lua/providers/buffers.lua:355: Vim:E5000: Cannot find tab number.
stack traceback:
        [C]: in function 'fzf_exec'
        ...k/vendor/start/fzf-lua/lua/fzf-lua/providers/buffers.lua:355: in function <...k/vendor/start/fzf-lua/lua/fzf-lua/providers/buffers.lua:280>
        .../nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/cmd.lua:78: in function 'run_command'
        .../nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/cmd.lua:100: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

**Comment by ibhagwan** [comment]
> It seems that this is related to those tabs that left got their tab-number updated, but I'm not sure.

I don’t use tabs/sessions, what do you mean by “the tab number got updated”? Aren’t tabs numbered the same way when restored from a session?

**Comment by nyngwang** [comment]
> It seems that this is related to those tabs that left got their tab-number updated, but I'm not sure.

I was just guessing, not sure... 

> [...] Aren’t tabs numbered the same way when restored from a session?

Yes, that's what I think. I meant these tab-number *might* got updated after I `:tabc` some of them.

**Comment by ibhagwan** [comment]
[Try now and let me know if that works?](https://github.com/ibhagwan/fzf-lua/commit/ebe4275a8f1be125bfbfb026207c7759d7d65dc4) - should work now, turns out `vim.fn.getcwd` requires the tab index and not tab handle.

**Comment by nyngwang** [comment]
Just confirmed it, and thank you!
