### ISSUE TITLE
empty uncloseable buffers-list after ctrl-x

### ISSUE THREAD

**Issue by afreakk** [ibhagwan/fzf-lua#629]
### Info

- Operating System: nixos
- Shell: fish (but bash inside vim)
- Terminal: alacritty
- `nvim --version`: NVIM v0.8.2
- `fzf --version`: 0.37.0 (0.37.0)

- [ ] The issue is reproducible with `mini.sh`
(its not, there the buffer-list does not loose content, and will close when pressing escape)

<details>
<summary>fzf-lua configuration</summary>

```lua
            local fzfLua = require('fzf-lua')
            fzfLua.setup {
                previewers = {
                    builtin = {
                        extensions = {
                            ["png"] = { "ueberzug" },
                            ["jpg"] = { "ueberzug" },
                        },
                        ueberzug_scaler = "fit_contain",
                    }
                },
                git = {
                    files = {
                        cmd = "git ls-files --exclude-standard --recurse-submodules"
                    }
                },
                grep = {
                    cmd = "git grep --ignore-case --recurse-submodules --line-number --color=auto --perl-regexp"
                }
            }
            fzfLua.register_ui_select()

```
</details>

### Description 
When i ctrl+x with the buffer view open, the content of buffer-list dissapear like so:
![image](https://user-images.githubusercontent.com/2227028/216949373-02d364ea-154d-4562-8f32-546345be87e4.png)
And escape to close the empty fzf-widget doesnt work.

As it didnt reproduce with mini.sh, im not sure, I will look more into this later, but just wanted to post this issue in case its a known missconfiguration.

**Comment by ibhagwan** [comment]
> there the buffer-list does not loose content, and will close when pressing escape

This is still not the expected behavior which should close the buffer and refresh the fzf-lua interface.

> As it didnt reproduce with mini.sh, im not sure, I will look more into this later, but just wanted to post this issue in case its a known missconfiguration.

Do you have custom autocmd’s for BufEnter, BufLeave, WinEnter or WinLeave?

**Comment by afreakk** [comment]
I found the culprit, it was `ethanholz/nvim-lastplace`.
Without that close-buffers works nicely

**Comment by afreakk** [comment]
A workaround is having nvim-lastplace ignore buftype = terminal like so:
```
require 'nvim-lastplace'.setup {
    lastplace_ignore_buftype = {"terminal" },
}
```

**Comment by ibhagwan** [comment]
Ty for the update and workaround @afreakk!

FYI, FzfLua also sets `filetype=fzf` which can also be ignored if you need a tighter ignore list.

**Comment by zetatez** [comment]
The workaround works for me, thanks!
