### ISSUE TITLE
Error after installation: 'Invalid preview window layout: :border:nowrap:nohidden:right:60%'

### ISSUE THREAD

**Issue by bluretrece** [ibhagwan/fzf-lua#63]
Hi! I recently discovered your plugin thanks to Reddit. I installed the dependencies that in the Wiki are mentioned but after I tried running `nnoremap <c-P> <cmd>lua require('fzf-lua').files()<CR>` the window instantly closes. I was able to see the error, it says `Invalid preview window layout: :border:nowrap:nohidden:right:60%`. I tried using the configuration that the readme provides as well as just `require('fzf-lua').setup{}`. Any idea of why this is happening? I was not able to find a related issue to my problem. Thanks in advance.

**Comment by ibhagwan** [comment]
Seems like the error is returned from fzf, not accepting the `—preview-window` flag, not sure why this would happen, can you try sending different flags separately to the files command and see which one is not accepted by `fzf`?

You can override all the defaults in one go by sending the `preview_window` directly like this:
```lua
: lua require('fzf-lua').files({ preview_window = “nohidden:right” })
```

Try with different options deleted from the string and see which one works? The full string should be `border:nowrap:nohidden:right:60%` (note there is no `:` prefix), you can even try with an empty string.

Let me know which fails the command and we’ll figure it out, also let can you run `fzf —version` in the shell and let me know the output as it could be a version compatibility issue.

**Comment by bluretrece** [comment]
Hello @ibhagwan! Thanks for the quick response. I tried the command you provided, but still got the same issue: the plugin makes an effort to appear but disappears in a blink. My current `fzf` version is 0.20.0. What's the required version to run this plugin? 

All the best.

**Comment by bluretrece** [comment]
Allow me to provide more details here: I'm running neovim 0.5 through WSL. I have installed `'junegunn/fzf`' as well as `junegunn/fzf.vim` (I didn't removed them) alongside `fzf-lua`. This perhaps is causing any conflict? I'm getting out of ideas.

**Comment by ibhagwan** [comment]
If you copy pasted the command it had the wrong type of quotation marks so it couldn't work, what I meant try with different combinations and tell me which one fails and which works if any?

```lua
lua require('fzf-lua').files({ preview_window = "" })
lua require('fzf-lua').files({ preview_window = "hidden" })
lua require('fzf-lua').files({ preview_window = "hidden:right" })
lua require('fzf-lua').files({ preview_window = "hidden:right:60%" })
lua require('fzf-lua').files({ preview_window = "hidden:right:60%:border" })
lua require('fzf-lua').files({ preview_window = "hidden:right:60%:noborder:nowrap" })
```

You can try different combinations of these till we figure out which is the option that fails your `fzf`.

As for the version I personally have `0.27 (devel)` and I'm not sure what options 0.20 may be missing but I guess we're about to find out.

**Comment by bluretrece** [comment]
@ibhagwan the plugin is working after upgrading `fzf` from 0.20 to 0.27!! Thanks for the help 😃

**Comment by ibhagwan** [comment]
> @ibhagwan the plugin is working after upgrading `fzf` from 0.20 to 0.27! Perhaps that detail should be mentioned in the documentation for newcomers? Anyway, thanks for the help, man! smiley

Fantastic! you just gave yet another issue to add to the dreaded Wiki lol
