### ISSUE TITLE
keep query when reopen

### ISSUE THREAD

**Issue by y1rn** [ibhagwan/fzf-lua#632]
### Info

- Operating System:
- Shell:
- Terminal:
- `nvim --version`:
- `fzf --version`:

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua

require 'fzf-lua'.fzf_live("rg --column --line-number --no-heading --color=always --smart-case", {
    prompt = "Search> ",
    actions = require 'fzf-lua'.defaults.actions.files,
  })


```
</details>

### Description 

When I want to search something again, I need to re-type again. I prefer press c-u when I want to search others.  Is there options?

**Comment by ibhagwan** [comment]
Have you tried `:FzfLua resume` or `:FzfLua live_grep resume=true`?

Another option is to enable fzf history with `--history`:
https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-setup-input-history-keybinds

**Comment by y1rn** [comment]
thx

**Comment by y1rn** [comment]
`require("fzf-lua").live_grep({continue_last_search = true})` and `FzfLua lgrep_curbuf resume=true` shard query history.

**Comment by ibhagwan** [comment]
> `require("fzf-lua").live_grep({continue_last_search = true})` and `FzfLua lgrep_curbuf resume=true` shard query history.

Then create two different bindings with two different history files.

**Comment by y1rn** [comment]
I try follow configs, but still share query string:
```
  require("fzf-lua").lgrep_curbuf({
      continue_last_search = true,
      fzf_opts = {
          ['--history'] = vim.fn.stdpath("data") .. '/buffer.history',
      },
  })
```
```
  require("fzf-lua").live_grep({
      continue_last_search = true,
      prompt = "Search> ",
      fzf_opts = {
          ['--history'] = vim.fn.stdpath("data") .. '/search.history',
      },
  })
```

**Comment by ibhagwan** [comment]
This functionality is controlled by the fzf binary (not by fzf-lua), I’m not sure why this happens in your case, according to your configuration above `lgrep_curbuf` should be saved inside `buffer.history` and `live_grep` should be saved inside `search.history`, you can check upstream but I really doubt there’s a bug in fzf mixing the the history files.

Most likely you also configured the history files within `setup` as well and have them mixed up.

**Comment by y1rn** [comment]
> I try follow configs, but still share query string:
> 
> ```
>   require("fzf-lua").lgrep_curbuf({
>       continue_last_search = true,
>       fzf_opts = {
>           ['--history'] = vim.fn.stdpath("data") .. '/buffer.history',
>       },
>   })
> ```
> 
> ```
>   require("fzf-lua").live_grep({
>       continue_last_search = true,
>       prompt = "Search> ",
>       fzf_opts = {
>           ['--history'] = vim.fn.stdpath("data") .. '/search.history',
>       },
>   })
> ```

sorry, I mean last search shared, not search history.

**Comment by ibhagwan** [comment]
> sorry, I mean last search shared, not search history. history work well.

That makes sense, all `grep` providers which includes `live_grep` and current buffer variants (`lgrep_curbuf`) all use the same "last search", the only separation is between `tags` and `grep`.
