### ISSUE TITLE
Feature request: locate and paste-buffer commands

### ISSUE THREAD

**Issue by randomizedthinking** [ibhagwan/fzf-lua#634]
### Description 

This is a feature request.

There are two items might be good to add in `fzf-lua`. The first item is a `locate` command: it is to search by the locate command, then display results in a fzf list. The original `fzf-vim` has this one. The second is a `paste-buffer` command: it is to display reg contents, then the user can select which item to paste into the current buffer.

Thanks.

**Comment by ibhagwan** [comment]
I’ll look into the `locate` command.

The second request is already possible with `:FzfLua registers`.

**Comment by randomizedthinking** [comment]
Thanks...

**Comment by ibhagwan** [comment]
The `locate` command seems to be a vim only thing, `:help locate` returns nothing, are you sure this exists with `fzf.vim` running on neovim?

**Comment by randomizedthinking** [comment]
> The `locate` command seems to be a vim only thing, `:help locate` returns nothing, are you sure this exists with `fzf.vim` running on neovim?

The command in fzf.vim is `Locate`. Please see: [fzf-vim.txt#L131](https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt#L131).

**Comment by ibhagwan** [comment]
> > The `locate` command seems to be a vim only thing, `:help locate` returns nothing, are you sure this exists with `fzf.vim` running on neovim?
> 
> The command in fzf.vim is `Locate`. Please see: [fzf-vim.txt#L131](https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt#L131).

As I wrote this seems to be a `vim` only command, not a `neovim` command.

**Comment by randomizedthinking** [comment]
It works for neovim, and I use this one quite often.

**Comment by ibhagwan** [comment]
> It works for neovim. Just note that `locate` is not a vim command, but a command-line utility just like `fzf`. You need to install it first before use. On Debian, there is a package called `locate` -- other distributions might have slightly different names.

I see, sorry for the confusion.

This doesn’t quire a separate command with fzf-lua, you can use the files provider with any command you want, for example: `lua require'fzf-lua'.files({ cmd = 'locate foo' })`, it should be very easy to create a user command that replicates `Locate` by combining files `cmd` with the q-args from the user command.

**Comment by ibhagwan** [comment]
I didn’t test this so you may want to inspect `t.args` (might need to use `t.args[1]`, I’m not sure) but it should be as simple as:
```lua
vim.api.nvim_create_user_command("Locate",
  function(t)
    require'fzf-lua'.files({ cmd = 'locate '  .. t.args })
  end,
  { nargs = "*" }
)

```

**Comment by ibhagwan** [comment]
Closing, lmk if this still doesn't meet your expectionations for a `:Locate` command and we can adjust it accordingly.
