### ISSUE TITLE
Feature request: quickfix title and quickfix_stack command

### ISSUE THREAD

**Issue by dembitskyi** [ibhagwan/fzf-lua#635]
Feature request:

Unfortunately, the plugin only allows resuming the last query.
it is quite problematic when you need to work on a project with a huge codebase (millions of files) where one `grep` takes several minutes to finish.
Quickfix comes to the rescue here, but it is not perfect because
1. the plugin does not set a quickfix title.
2. the plugin does not provide a command to show a stack of quickfix and their titles 

What if the plugin does next via optional flags or by default?
1. extend `file_sel_to_qf` to set the current query as a title for a new quickfix list
2. Add a new command `FzfLua quickfix_stack` that allows you to show all quickfix titles and preview selected quickfix

**Comment by ibhagwan** [comment]
This sounds very reasonable, which native neovim commands are you normally using to set titles for quick fix lists and browse the stack?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/579b115f11df4544a09703ef3cf7b44d19337a34 - update to this commit, it sets the quickfix `w:quickfi-title` title to the last typed query, looking into the APIs to browse the quiclfix lists.

**Comment by dembitskyi** [comment]
I'm using next commands:
1. `call setqflist([], 'a', {'title' : '<TITLE>'})`
2. `:chistory` -> https://neovim.io/doc/user/quickfix.html#%3Achistory

Unfortunately, `chistory` does not show the correct title if I use https://github.com/ibhagwan/fzf-lua/commit/579b115f11df4544a09703ef3cf7b44d19337a34

**Comment by ibhagwan** [comment]
> I'm using next commands:
> 
> 1. `call setqflist([], 'a', {'title' : '<TITLE>'})`
> 2. `:chistory` -> https://neovim.io/doc/user/quickfix.html#%3Achistory
> 
> Unfortunately, `chistory` does not show the correct title if I use [579b115](https://github.com/ibhagwan/fzf-lua/commit/579b115f11df4544a09703ef3cf7b44d19337a34)

You're correnct turns out `w:quickfix-title` wasn't the correct way to set the title for the purpose of `chistory`, I don't usually force push but since it wasn't this long ago and the code wasn't serving any purpose I force pushed so please `pull --rebase` to https://github.com/ibhagwan/fzf-lua/commit/86829672cfec3dbd4b66652ee1aaa122a74667c9 and the title should work as expected.

**Comment by ibhagwan** [comment]
It does appear though that I also need to suply the `nr` argument to `setqflist` options, otherwise the quickfix list is replaced (instead of creating a new list).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/6dcdb947dc63deb00d48bd24e0273c4a6af79a29 - adds 2 new providers `quickfix_stack` and `loclist_stack`, as the name suggests it opens the quickfix (or localtion list) stack with preview and sets the current list to the selected line as the default action:

> The default send to quickfix action was also modified to create a new quickfix list with every new selection
![image](https://user-images.githubusercontent.com/59988195/218167974-501e968e-265f-493e-a1c0-204ae06bf62c.png)

**Comment by dembitskyi** [comment]
Thank you for these changes :tada: 
It'll save a lot of time when you need to deal with a project where one grep request takes several minutes.

**Comment by ibhagwan** [comment]
> Thank you for these changes tada It'll save a lot of time when you need to deal with a project where one grep request takes several minutes.

Ty for bringing this to my attention, lmk if this works as expected and we can close this issue, I just pushed another commit to set `nocursorline` within the previewer.

**Comment by dembitskyi** [comment]
> lmk if this works as expected and we can close this issue

It works seamlessly. I do not see any unexpected/strange behaviors.

**Comment by ibhagwan** [comment]
Ty @dembitskyi, closing.
