### ISSUE TITLE
Blurring image preview

### ISSUE THREAD

**Issue by TroySigX** [ibhagwan/fzf-lua#636]
### Info

- Operating System: Endeavour OS, linux-6.1.11arch
- Terminal: Yakuake
- `nvim --version`: 0.8.3
- `fzf --version`: latest

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
    previewers = {
        builtin = {
            ueberzug_scaler = "cover",
            extensions = {
                ["gif"] = { "viu", "-b" },
                ["png"] = { "viu", "-b" },
                ["jpg"] = { "viu", "-b" },
                ["jpeg"] = { "viu", "-b" },
            },
        },
    },
})
```
</details>

### Description 
Image is very blurry when previewing in fzf-lua, like this:
![image](https://user-images.githubusercontent.com/88051085/218283195-94098e4b-3881-48b4-a3c5-13892f0d8ae7.png)

This is the original image previewed through viu in terminal:
![image](https://user-images.githubusercontent.com/88051085/218283420-3ff2ffef-375e-4a46-ad06-0bed63b14331.png)

**Comment by ibhagwan** [comment]
This happens due to the limitations of the neovim terminal, open a new terminal with `:new | term` and run `viu` inside and the result would be the same, not much I can do about it.

You can try [`chafa`](https://github.com/hpjansson/chafa), it works a bit better inside neovim.

**Comment by TroySigX** [comment]
Chafa doesn't work for me, it shows like this:
![image](https://user-images.githubusercontent.com/88051085/218283726-0ae3908d-148b-40af-bf86-fbc609493c53.png)

How do I solve it, here's my config:
local img_previewer = { "chafa" }

require("fzf-lua").setup({
    previewers = {
        builtin = {
            ueberzug_scaler = "cover",
            extensions = {
                ["gif"] = img_previewer,
                ["png"] = img_previewer,
                ["jpg"] = img_previewer,
                ["jpeg"] = img_previewer,
            },
        },
    },
})

**Comment by ibhagwan** [comment]
Does it work if you open a terminal **inside neovim** with `:new | term` and run `chafa <image_path.png>`?

**Comment by TroySigX** [comment]
It doesn't

**Comment by ibhagwan** [comment]
> It doesn't

Then you have your answer why it doesn’t work within fzf-lua, these media previews are mere suggestions I have no control over how or if they work within the neovim terminal.

**Comment by TroySigX** [comment]
Thank you!

**Comment by ibhagwan** [comment]
If you’re on Linux and use Xorg I recommend ueberzug, it works differently, it spawns an x-window on top of the preview pane, doesn’t use a terminal so it’s not bound by these limitations, will provide the most crisp previews.

**Comment by TroySigX** [comment]
It works perfectly, thank you so much!

**Comment by ibhagwan** [comment]
> It works perfectly, thank you so much!

That’s great! Play around with the scaler to get the result you like most, possible options (from the ueberzug project page) are: "crop", "distort", "fit_contain", "contain", "forced_cover" and "cover" (default)
