### ISSUE TITLE
Feature Request: Vim help search

### ISSUE THREAD

**Issue by mangelozzi** [ibhagwan/fzf-lua#637]
Great plugin, loving the speed of it.
Would be really great to use fzf-lua to find vim help entries, something like this: https://youtu.be/9gUatBHuXE0?t=180

TJDeVries refers to it as "Telescop Help Search".

**Comment by ibhagwan** [comment]
Have you tried `:FzfLua help_tags`?

**Comment by mangelozzi** [comment]
Sorry I hadn't, I kept checking buffers/files, completely missed the "Misc section" https://github.com/ibhagwan/fzf-lua#misc. Wow it just gets better and better, thank you!

**Comment by ibhagwan** [comment]
> Sorry I hadn't, I kept checking the `buffers/files` section, completely missed the "Misc section" https://github.com/ibhagwan/fzf-lua#misc. Wow it just gets better and better, thank you!

No worries, glad you like it :)
