### ISSUE TITLE
Ueberzug image preview won't disappear when switch to another tab of terminal

### ISSUE THREAD

**Issue by TroySigX** [ibhagwan/fzf-lua#638]
### Info

- Operating System: Endeavour OS 6.1.11arch
- Shell:
- Terminal: Yakuake
- `nvim --version`: 0.8.3
- `fzf --version`: latest

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
local img_previewer = { "ueberzug" }

require("fzf-lua").setup({
    previewers = {
        builtin = {
            ueberzug_scaler = "forced_cover",
            extensions = {
                ["gif"] = img_previewer,
                ["png"] = img_previewer,
                ["jpg"] = img_previewer,
                ["jpeg"] = img_previewer,
            },
        },
    },
})

```
</details>

### Description 
When I open image previewer, and then switch to another tab of the terminal, the image won't disappear. It behaves like this:
When I open image previewer:
![image](https://user-images.githubusercontent.com/88051085/218284515-29050e4b-d17c-400a-aa13-a6d1c732e63f.png)
When I switch to another tab of Yakuake (my terminal):
![image](https://user-images.githubusercontent.com/88051085/218284541-288ad2b2-c41a-4489-9d69-8bc31a7867b0.png)

**Comment by ibhagwan** [comment]
That’s a bug I’ll have to think how to solve, as I mentioned in the previous issue, ueberzug spawns another x-win on top of the terminal (independent of neovim) so as long as neovim is open with the preview it won’t disappear.

Another issue I just learned about is that the `ueberzug` seems to be no longer maintained and all the documentation is gone lol

https://github.com/seebye/ueberzug

**Comment by TroySigX** [comment]
Yes, that's why I avoided using ueberzug in the first place.

**Comment by ibhagwan** [comment]
I've looked into this, this would require setting up a specialized autocmd for `FocusLost` (that may not even fire in your case, I'm not sure about changing tabs in Yakuake) that would close the preview and then reopen it when focus is regained.

Given this is only for ueberzug and the project is abandoned I don't think it's worth the time investment and code maintenance and being such an edge case (leaving fzf-lua open while changing tabs), I've decided not to leave it as is.
