### ISSUE TITLE
Feature: Show a list of buffers for the current window

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#639]
**Description**

This is a feature request.

Hi, i was looking through the public api, and seeing as we have the tabs action, it would be a nice addition to also allow us to have a list of buffers for the current window. Sometimes when you have way too many splits, you want to quickly navigate between them. Would be quite helpful. 

Thanks !

**Comment by ibhagwan** [comment]
> 

Would you like to see a list of buffers **for the current tab only** (not “window”)?

If so I can easily add an option named `current_tab_only` and filter out all the other tabs.

**Comment by asmodeus812** [comment]
Seems to be nice replacement, technically there is no difference i would assume, one tab usually spans only one main window (which is then split into panes) ?

On a similar note, is there a way to totally disable all icon related configs for every picker at a more global level ? As it is right now a lot of pickers support them, but each is configured individually with pretty much the same property/names

**Comment by ibhagwan** [comment]
> Seems to be nice replacement, technically there is no difference i would assume, one tab usually spans only one main window (which is then split into panes) ?


Shouldn’t be any difference, I’ll make it so it also removes the `Tab #nr` title so it will basically be a list of buffers that exist in the current tab only (what you refer to as “main window”).

> On a similar note, is there a way to totally disable all icon related configs for every picker at a more global level ? As it is right now a lot of pickers support them, but each is configured individually with pretty much the same property/names

https://github.com/ibhagwan/fzf-lua/issues/188#issuecomment-1154172463

**Comment by asmodeus812** [comment]
I did edit a bit my initial comment, giving it a second thought, seems like showing all buffers is not that useful, i think if we have an option to not show hidden (i.e those not currently displayed in windows) that would make it even better.

**Comment by ibhagwan** [comment]
> I did edit a bit my initial comment, giving it a second thought, seems like showing all buffers is not that useful, i think if we have an option to not show hidden (i.e those not currently displayed in windows) that would make it even better.
> 

I’m not sure I’m getting what you want, tabs currently displays only visible buffers (buffers that have a neovim window associated with them), limiting to the current buffer will display only buffers that are visible in the current tab - is this what you’re after?


> Also i don't want to open new issue, would be great if ui.select wrapper extended from user opts, so we can add our own winopts etc. I was trying to resize a custom ui select only to realize it does not pick / extent from the user opts rather picks up only the prompt.

You can send any options to the register function: `register_ui_select({ winopts = … })`.

**Comment by asmodeus812** [comment]
Yes, did not consider that what the tabs do, makes total sense, in any case yes, both solutions do work as expected. As you noted above, the only small pet peeve is for current tab, the tab sub-label in the left pane is probably redundant

**Comment by ibhagwan** [comment]
> Yes, did not consider that what the tabs do, makes total sense, in any case yes, both solutions do work as expected. As you noted above, the only small pet peeve is for current tab, the tab sub-label in the left pane is probably redundant

I will hide the line with `Tab #<nr>`

> the tab sub-label in the left pane is probably redundant

If you mean the `[1]`, that's the buffer number (same display as in `buffers`) and not the tab number.

**Comment by ibhagwan** [comment]
Turns out I already had this implented and I forgot lol,

`:FzfLua tabs current_tab_only=true`

https://github.com/ibhagwan/fzf-lua/commit/f4fe61067e20c7fb7ffc83c849d638dbdc38a2af - latest commit modified the behavior slightly to hide the current `Tab #` line.

**Comment by ibhagwan** [comment]
Closing, lmk if you need more help or if this doesn't work to your expectations.
