### ISSUE TITLE
[bug] opts.actions is a nil value

### ISSUE THREAD

**Issue by LucasTavaresA** [ibhagwan/fzf-lua#641]
### Info

- Operating System: Void Linux
- Shell: fish
- Terminal: foot
- `nvim --version`: v0.8.3
- `fzf --version`: 0.37

- [X] The issue is reproducible with `mini.sh`

### Error 

Very easy to reproduce `:FzfLua keymaps` or `:FzfLua highlights`, does not seem to happen with other commands

```
E5108: Error executing lua ...pack/vendor/start/fzf-lua/lua/fzf-lua/providers/nvim.lua:307: ...nvim/site/pack/vendor/start/fzf-
lua/lua/fzf-lua/core.lua:143: attempt to index field 'actions' (a nil value)
stack traceback:
        [C]: in function 'fzf_exec'
        ...pack/vendor/start/fzf-lua/lua/fzf-lua/providers/nvim.lua:307: in function <...pack/vendor/start/fzf-lua/lua/fzf-lua/
providers/nvim.lua:262>
        .../nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/cmd.lua:78: in function 'run_command'
        .../nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/cmd.lua:100: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

the issue goes away when i comment the loop around 143 on `core.lua`, but idk what it does

**Comment by LucasTavaresA** [comment]
placing an empty/whatever table in the actions for the command also works

**Comment by ibhagwan** [comment]
Ty @LucasTavaresA, I accidentally missied this part in https://github.com/ibhagwan/fzf-lua/commit/15a57dcb19bca8bcad7af8e5b5c6b2cbf33d30d7, should work now.
