### ISSUE TITLE
Selecting a code action in lsp_code_actions does not execute the selected action

### ISSUE THREAD

**Issue by pure-bliss** [ibhagwan/fzf-lua#642]
### Info

- Operating System: Linux dell 5.15.77-1-lts # 1 SMP Thu, 03 Nov 2022 17:26:01 +0000 x86_64 GNU/Linux
- Shell: fish, version 3.5.1
- Terminal: kitty 0.26.5
- `nvim --version`: NVIM v0.8.2
- `fzf --version`: 0.35.1 (a38b63b)
- `fzf-lua` version: d3c6440

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
	winopts = {
		height = 0.97,
		width = 0.97,
		border = "single",
		preview = {
			scrollbar = false,
			layout = "vertical",
			vertical = "down:65%",
		},
	},
	grep = {
		rg_glob = false,
		glob_flag = "--iglob",
		glob_separator = "%s%-%-",
		actions = {
			["ctrl-f"] = { actions.grep_lgrep },
		},
	},
	keymap = {
		builtin = {
			["<down>"] = "preview-page-down",
			["<up>"] = "preview-page-up",
		},
		fzf = {
			["down"] = "preview-page-down",
			["up"] = "preview-page-up",
		},
	},
})

```
</details>

### Description 

Selecting a codeaction in fzf-lua-s codeactions window does not execute the action

Steps to reproduce:

 1. Create a code issue (ex.: forget a import in a javascript file)
 2. Move the cursor to the problematic keyword, and type `:FzfLua lsp_code_actions`
 3. Ideally the LSP server should suggest an action to add the import
 4. Select the `Add import from "..."` action

Expected: The action is executed

Actual: The action does not do anything

Additional information: `vim.lsp.buf.code_action()` works

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/859561a4bb447d8cb400daa52c7e3a29600bf0cf - Ty for the report @pure-bliss, should work now!
