### ISSUE TITLE
`redrawstatus` makes the preview text not show

### ISSUE THREAD

**Issue by mangelozzi** [ibhagwan/fzf-lua#643]
### Info

- Operating System:  Ubuntu 22.04
- Shell: Bash
- Terminal: Bash
- `nvim --version`: 0.82
- `fzf --version`: 0.36.0 (2023011)

- [x] The issue is reproducible with the following init.lua:
```lua
local ensure_packer = function()
    local fn = vim.fn
    local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
    if fn.empty(fn.glob(install_path)) > 0 then
        fn.system({"git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path})
        vim.cmd [[packadd packer.nvim]]
        return true
    end
    return false
end
local packer_bootstrap = ensure_packer()

local minimal_plugins = function(use)
    use {
        "ibhagwan/fzf-lua",
        -- optional for icon support
        requires = "nvim-tree/nvim-web-devicons"
    }
    if packer_bootstrap then
        require("packer").sync()
    end
end
require("packer").startup(minimal_plugins)

local StatusLineGroup = vim.api.nvim_create_augroup("StatusLineGroup", {clear = true})

vim.api.nvim_create_autocmd(
    {"BufWinEnter", "BufEnter", "WinEnter"},
    {
        desc = "StatusLine colouring dependant on active window",
        callback = function()
            vim.cmd("redrawstatus!")
        end,
        group = StatusLineGroup,
        pattern = "*",
    }
)


vim.defer_fn(function() require("fzf-lua").files() end , 500)
```

### Description 

Run the above `init.lua`, browse down to some files, you will see the preview text will be blank.

**Comment by ibhagwan** [comment]
Ty for the report @mangelozzi, I am able to reproduce this with a similar autocmd (even `BufEnter` alone is sufficient).

It seems that the text is there as I can see the scrollbar size change according to the file size and I am also able to scroll, the lines seem to be there but the text for some reason doesn't show, perhaps something to do with highlights?

I tried getting the lines from the buffer with `nvim_buf_get_lines` and they are definitely there, not sure what's messing with the display here.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/6be3ba4620ed44b29abc1562ecf67e4fdfb48d20 - I still don't know why this happens but I was able to disable autocmds for the preview buffer (which don't need to run these anyway) and it solves the issue.

Lmk if this works for you as well?

**Comment by mangelozzi** [comment]
Thanks for the fix. 
It is a bit of a weird one, maybe Neovim doesnt handle redraw correctly for floating windows (which I am guessing the preview is)? If you can't see why its happening, sounds like I should raise a Neovim issue, and maybe you revert this fix (small change someone wants to have autocmds on the preview window)?

**Comment by ibhagwan** [comment]
> Thanks for the fix.
> It is a bit of a weird one, maybe Neovim doesnt handle redraw correctly for floating windows (which I am guessing the preview is)? If you can't see why its happening, sounds like I should raise a Neovim issue, and maybe you revert this fix (small change someone wants to have autocmds on the preview window)?

I also believe this is a neovim issue, no need to revert tor fix, I don’t see why anyone would need aurocmds for the preview buffer (not the main terminal window).
