### ISSUE TITLE
Feature request: `fzf.vim` like ordering for buffers

### ISSUE THREAD

**Issue by mangelozzi** [ibhagwan/fzf-lua#645]
I recently changed from `fzf.vim` to `fzf-lua`, loving the plugin thank you.

One thing that trips me up often is the ordering of matches of buffers.

Say I opened up the following buffers in this order:
1. `foo/a.html`
2. `foo/b.html`
3. `foo/c.html`
4. `foo/d.html`

So the most recent buffer opened was `d`. If I FZF search for buffers and enter in the search term `html`, then the matches would be:
1. `foo/c.html`  - I.e. the best match
 2. `foo/b.html` - Second best match
 3. `foo/a.html` - third best match

It orders it according to the order of last accessed. I use it all the time when switching between files, it's like a reflex. Knowing the "best" match will be the most recent one, generally typing a phrase quickly and pressing enter before I even can read the results (the hand is quicker than the eye!). I am guessing `fzf.vim` uses the history (old_files) to sort the buffers matches.

I see there is :
```
      buffers = {
        prompt            = 'Buffers❯ ',
        file_icons        = true,         -- show file icons?
        color_icons       = true,         -- colorize file|git icons
        sort_lastused     = true,         -- sort buffers() by last used      <--------- This option
        actions = {
          -- actions inherit from 'actions.buffers' and merge
          -- by supplying a table of functions we're telling
          -- fzf-lua to not close the fzf window, this way we
          -- can resume the buffers picker on the same window
          -- eliminating an otherwise unaesthetic win "flash"
          ["ctrl-x"]      = { actions.buf_del, actions.resume },
        }
      },
```
I see the `sort_lastused` is set by default, but not working for me with my options set to:
```
    buffers = { prompt = 'Buffers❯ '},
```

Will investigate more

**Comment by ibhagwan** [comment]
> If I FZF search for buffers and enter in the search term `html`

Once you type something the initial ordering of the buffers doesn’t matter any longer, the ordering after typing is controlled by the fzf algorithm which you can tweak by adding `--tiebreak` to `fzf_opts`, have you tried that?

**Comment by mangelozzi** [comment]
Will give it a try thanks, I never used to use that option on my old  setup, maybe FZF has tweaked their algorithm since a year or 2 ago.

**Comment by ibhagwan** [comment]
Also, see a similar issue with `oldfiles`, setting tiebreak to `index` solved the issue: https://github.com/ibhagwan/fzf-lua/issues/592#issuecomment-1387609639

**Comment by ibhagwan** [comment]
FYI https://github.com/ibhagwan/fzf-lua/commit/bcb5153f893829c78e59c1c788bb3f2b04dd46f2 sets the default tiebreak for both `buffers` and `oldfiles` to `index`.
