### ISSUE TITLE
`buffers` current buffer should be at the top

### ISSUE THREAD

**Issue by icefed** [ibhagwan/fzf-lua#646]
### Info

- Operating System: MacOS
- Shell: zsh
- Terminal: iterm2
- `nvim --version`: 0.8.2
- `fzf --version`: 0.37.0 (brew)

```lua
require('fzf-lua').setup({
})
```

`sort_lastused     = true` by default.

### Description 

 I bound `ctrl+e` to `buffers` and split the neovim window. When I switch neovim windows and open `buffers` quickly, current buffer is not the first one, and I can't switch to the first one.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/3964419/218964704-0beb409b-addf-4357-bd78-8d111d2c1d25.png">

We should let current buffer at the top, and last buffer second.

solve: check flag first.
https://github.com/ibhagwan/fzf-lua/blob/9be7f26e486fe42ceeaeb4a6bb686e9554dd04b5/lua/fzf-lua/providers/buffers.lua#L103-L105

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a3be08c8821acda67e7efd3eb865cadb393e17b2 - couldn't reproduce but I guess there's no harm in this fix.

**Comment by icefed** [comment]
> [a3be08c](https://github.com/ibhagwan/fzf-lua/commit/a3be08c8821acda67e7efd3eb865cadb393e17b2) - couldn't reproduce but I guess there's no harm in this fix.

Thank you, current buffer on the top now, alse there's a little problem with the last buffer(flag is `#`),  may be that nvim cannot distinguish the last buffer under multiple windows, but It doesn't matter to me.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/3964419/219262759-a3fc254b-4ff1-496f-bac9-2a709fc667ff.png">

**Comment by ibhagwan** [comment]
That's very strange indeed, I couldn't reproduce this, the sort is merly a reflection of neovim's buffer info `lastused` - does this happen all the time or just if you open buffers really quickly?

**Comment by icefed** [comment]
Open buffers slowly and it will happen too, I think it's neovim/vim's problem.

To reproduce:
1. You can open multi files(>4) and split to two windows.
2. open buffers and select the bottom buffer -> switch window -> open buffers, try few times.

**Comment by ibhagwan** [comment]
Reopening until we figure out if this is a neovim bug or intended behavior.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/38e6c0ad7f1904db4745af3d3a77b32cb923a2d3 - this should solve it for both, arbitrarily setting the lastused date of `%` to 2100-01-01 and `#` to 1-second before, hopefully this bug gets solved before this hack expires at the year 2100 :smile:

**Comment by doronbehar** [comment]
Hey all, I am a bit confused about this issue. Today I noticed that apparently due to the two commits that closed this issue, I noticed that `:FzfLua buffers` acts differently when I press <kbd>Enter</kbd>. The previous behavior was better and simpler IMO: When I hot into `:FzfLua buffers`, I simply chose a buffer by pressing <kbd>Enter</kbd> and it just replaced the current buffer I was at. Now, I don't understand which buffer it is replacing - certainly it's not always the one I expect it to replace - sometimes it is, but most of the time it's not.

> We should let current buffer at the top, and last buffer second.

Why? I think `:FzfLua buffers` should only help me pick which buffer to switch to - a sort of `:ls` on steroids - nothing more.

I have currently reverted both https://github.com/ibhagwan/fzf-lua/commit/38e6c0ad7f1904db4745af3d3a77b32cb923a2d3 and https://github.com/ibhagwan/fzf-lua/commit/a3be08c8821acda67e7efd3eb865cadb393e17b2 on my checkout. It'd be nice to find a fix that will satisfy all of us.

**Comment by ibhagwan** [comment]
@doronbehar, not sure what you mean, this commits in this issue only made sure the sorting is accurate and the the last used buffer is always on top.

`buffers` should only list current buffers and when you press enter switch the current window to the selected buffer, any different behavior is a bug, the commits here are pretty old and you’re the only one having this issue  so please open a new detailed issue with the exact description and I’ll take care of it.

**Comment by ibhagwan** [comment]
Btw @doronbehar, by default, the current buffer should be the top buffer and set as a header (I.e. not selectable), the second buffer (which is the selected buffer by default) should be the alternate buffer, therefore, opening `buffers` and pressing enter should be equal to pressing `ctrl-^`.

**Comment by doronbehar** [comment]
By:

> opening `buffers` and pressing enter

I actually meant:

> opening `buffers` and choosing a buffer which is not necessarily the last one, by pressing enter.

**Comment by doronbehar** [comment]
I'll try to demonstrate the issue with a screencast perhaps.

**Comment by ibhagwan** [comment]
> I'll try to demonstrate the issue with a screencast perhaps.

Is it possible the buffer sort without these commits was bugged and you got used to the buggy behavior of an erroneous sort?

Is it properly sorted after the commits? I.e. the current buffer is set as header, alternate buffer as first selectable buffer and the rest are sorted by last used?

**Comment by doronbehar** [comment]
TBH, I don't care much about the sorting, so maybe indeed these commits are not related to the issue of '_where_ do a selected buffer is opened'. Unfortunately I also can't reproduce the issue with the minimal config, so this is a more specific issue then I anticipated. Hopefully I'll open a new issue with detailed steps to reproducing it, when I'll find time.

**Comment by doronbehar** [comment]
Thanks for the prompt replies anyway!

**Comment by ibhagwan** [comment]
> TBH, I don't care much about the sorting, so maybe indeed these commits are not related

You can always `sort_lastused=false` if you don't care about sorting.
