### ISSUE TITLE
[FR] Add custom commands to builtin

### ISSUE THREAD

**Issue by liangxianzhe** [ibhagwan/fzf-lua#648]
Proposal: allow users to add custom commands to the "builtin" view. In this sense, it is not "builtin" anymore, more like an extensible command palette. It seems doable, but not sure whether it makes to you.

Additionally, I would suggest having a dedicated place (a new repo) to host all kinds of new fzf commands (like the ones in your advanced wiki). It's like telescope extension, but I suggest putting them in a single place. This way, people can import that repo, pick the commands they like, then add them to the command palette.

**Comment by ibhagwan** [comment]
Ty @liangxianzhe!

I love the idea but if I'm honest I would hate to manage that, the last thing I want is to have responsibility for code that other people wrote which is bound to happen if the repo is under my github profile, this plugin is huge as it is and I do not wish to have to deal with issues fixing / having the responsibility for other people's code.

Imagine I'd have to review each PR and make sure it doesn't break anything, or worse, that it doesn't contain malicous code.

You're more than welcome to open a repo and I'll be happy to mention it in the README as well as have a function that you can call to "register" your new functions into the "command palette".

**Comment by liangxianzhe** [comment]
Totally understand. I'm not sure I have the time for that right now. 

But let's start with how I can register a few my functions into the "builtin" for my own convinence?

**Comment by ibhagwan** [comment]
It's very simple, you can just add it to the fzf-lua module, the `builtin` methods are automatically enumerated from it, for example:
```lua
:lua require("fzf-lua").test = function() print "test" end
```
And `test` is now included in the builtin.

**Comment by liangxianzhe** [comment]
Perfect. I'm closing the issue for now. Thanks!
