### ISSUE TITLE
Neovim gets stuck when opening fzf if mapping Escape to abort

### ISSUE THREAD

**Issue by krady21** [ibhagwan/fzf-lua#649]
### Info

- Operating System: Ubuntu 18.04
- Shell: bash
- Terminal: gnome terminal
- `nvim --version`: 0.9
- `fzf --version`: 0.38.0 

- [x] The issue is reproducible with `mini.sh`
<details>
<summary>fzf-lua configuration</summary>

```lua
fzf.setup {
  winopts = {
    hl_border = "VertSplit",
    preview = {
      layout = "vertical",
    },
  },
  keymap = {
    fzf = {
      ["escape"] = "abort",
      ["ctrl-q"] = "toggle-all",
      ["ctrl-a"] = "select-all",
      ["ctrl-f"] = "half-page-down",
      ["ctrl-b"] = "half-page-up",
    },
  },
  fzf_colors = {
    ["fg"] = { "fg", "Normal" },
    ["bg"] = { "bg", "Normal" },
    ["hl"] = { "fg", "Comment" },
    ["fg+"] = { "fg", "Normal" },
    ["bg+"] = { "bg", "CursorLine" },
    ["hl+"] = { "fg", "Statement" },
    ["info"] = { "fg", "PreProc" },
    ["prompt"] = { "fg", "Conditional" },
    ["pointer"] = { "fg", "Exception" },
    ["marker"] = { "fg", "Keyword" },
    ["spinner"] = { "fg", "Label" },
    ["header"] = { "fg", "Comment" },
    ["gutter"] = { "bg", "Normal" },
  },
}

```
</details>

### Description 
I've noticed that escape no longer works as it used to (closing the fzf window). At the moment pressing escape only exits insert mode in the fzf window. I'd like to map escape back to it's previous behavior, which was closing fzf completely, but configuring it like this (`['escape'] = 'abort'`) seems to block neovim and the terminal. Is there another proper way to do this remap? Thanks.

**Comment by ibhagwan** [comment]
You’re correct the, behavior changed, specifically this: https://github.com/ibhagwan/fzf-lua/commit/15a57dcb19bca8bcad7af8e5b5c6b2cbf33d30d7#commitcomment-100438891

It should still close, the difference is fzf-lua no longer hijacks the Esc bind, Is if possible you have a keybind mapping as described in the comment?

**Comment by krady21** [comment]
Yeah, it seems like I do. It works now if I remove the mapping. Thanks a lot.

**Comment by ibhagwan** [comment]
> Yeah, it seems like I do. It works now if I remove the mapping. Thanks a lot.

Ty for the update!
