### ISSUE TITLE
provide a rockspec

### ISSUE THREAD

**Issue by teto** [ibhagwan/fzf-lua#65]
I wonder if you could provide a rockspec in the repo similar to https://github.com/lewis6991/gitsigns.nvim/blob/main/gitsigns.nvim-scm-1.rockspec
so that packer can leverage luarocks dependency system. This would simplify the installation instructions from 
```
use { 'ibhagwan/fzf-lua',
  requires = {
    'vijaymarupudi/nvim-fzf',
    'kyazdani42/nvim-web-devicons' } -- optional for icons
}
```
to 
`use 'ibhagwan/fzf-lua' ` (and if you change dependencies, then users dont have to fiddle with their install, luarocks/packer.nvim will take care of it automatically.

**Comment by ibhagwan** [comment]
Ty, I didn’t even know that was a thing.

ATM, I would consider this at the “nice to have” category, `fzf-lua` has only one dependency which isn’t planned on being changed anytime soon, adding all this extra debugging, testing and maintenance of the rocks file just for a feature in packer which I’m not sure how many will use isn’t worth it right now.

**Comment by ibhagwan** [comment]
I'm going to close this for now, I'd rather invest my time in new functionality and improving the interfaces so it's easier to write extensions for fzf-lua.

I'm assuming it's not that complicated to add the rockspec and test it with packer, if you wish to do this yourself and create a PR I would welcome it :-)
