### ISSUE TITLE
please do tnoremap <C-c> <Esc>

### ISSUE THREAD

**Issue by uga-rosa** [ibhagwan/fzf-lua#653]
### Description 

Because I do `tnoremap <Esc> <C-\><C-n>`, the current forced mapping to <C-c> with noremap = false is inconvenient. If you are trying to match the previous behavior, then noremap = true should be fine, but why did you do it this way?

**Comment by ibhagwan** [comment]
Ty @uga-rosa, I’d like to get rid of it, I personally prefer <C-c> to close the UI faster but although it never came up as an issue I was having neovim process hangs which I concluded was a neoivm bug (https://github.com/neovim/neovim/issues/20726) so I added this mapping as proactive measure until this gets fixed upstream.

> the current forced mapping to with `noremap = false` is inconvenient

I will add `noremap=true`, just wondering what you mean by that? What’s process do you have which gets in the way?

**Comment by uga-rosa** [comment]
Because I did `tnoremap <Esc> <C-\><C-n>`, `noremap = false` maps `<C-c>` to `<C-\><C-n>`, and don't close UI.

**Comment by ibhagwan** [comment]
Ty @uga-rosa, makes absolute sense, fixed in https://github.com/ibhagwan/fzf-lua/commit/8778728c7afeefaca643162bcc17305ec1ace4a1.

**Comment by uga-rosa** [comment]
Ty!
