### ISSUE TITLE
mapping to send results to quickfix list broken

### ISSUE THREAD

**Issue by dimbleby** [ibhagwan/fzf-lua#654]
```lua
    config = function()
      require('fzf-lua').setup({
        keymap = {
          fzf = {
            ['CTRL-Q'] = 'select-all+accept',
          },
        },
      })
    end,
```
this has stopped working, bisecting points the finger at 15a57dcb19bca8bcad7af8e5b5c6b2cbf33d30d7

**Comment by dimbleby** [comment]
specifically the problem looks to be here https://github.com/ibhagwan/fzf-lua/blob/178709f0839359ffbd44fcaca64558212abe2493/lua/fzf-lua/core.lua#L152

**Comment by dimbleby** [comment]
if I spell my mapping as `ctrl-q` instead of `CTRL-Q` then it works again, but this seems fragile.  And anyway, per the docs, capitalised is the usual convention within vim / neovim.

**Comment by ibhagwan** [comment]
> if I spell my mapping as `ctrl-q` instead of `CTRL-Q` then it works again, but this seems fragile. And anyway, per the docs, capitalised is the usual convention within vim / neovim.

Ty for the report @dimbleby, I will adjust it for case insensitivity.

The reason for lowercase is because this is mapping for the `fzf` binary `--expect` which is listed in lowercase in the manual.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5c1c7f9267183772f57478404459fb49a94c31db - should work now, this handles any type of case mismatch in the `keymap` or `actions` tables.
