### ISSUE TITLE
User defined TermClose bufwipe autocmd prevents fzf help window from closing

### ISSUE THREAD

**Issue by craigmac** [ibhagwan/fzf-lua#658]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: 0.8.3
- `fzf --version`: 0.38.0

<details>
<summary>fzf-lua configuration</summary>

Start nvim using e.g., `nvim -u termclose.lua` where termclose.lua file contains:

```lua
vim.api.nvim_create_autocmd('TermClose', {
  command = 'if v:event.status==0 | exe "bwipe! " .. bufnr("%") | endif',
  desc = 'Completely remove terminal buffer if success on exit'
})

require('fzf-lua').setup({})
```
</details>

### Description 

Open any fzf command, we'll do: `:FzfLua files`, now press `<C-c>` or `<Esc>` or `<C-[>` to close it. Works fine. Now open the same file search and press `<F1>` to popup the help display. Press `<C-c>` or `<Esc>` or `<C-[>` now and fzf search window will shut like before, but the help window will remain, with no way to close it that's obvious.

I've got this TermClose autocmd to avoid the 'Hit Enter to close this window' prompt that you get when exiting from e.g., `:sp term://zsh` by default. If I could somehow determine whether that fzf help window is still open and close it, I could just take care of this in the autocmd, but I couldn't find anything. Is the help overlay a buffer, a window, or something else? how would I check for it's existence?

**Comment by ibhagwan** [comment]
> If I could somehow determine whether that fzf help window is still open and close it, I could just take care of this in the autocmd

I'd rather users don't need to hack their config for something that should never have been an issue :-)

https://github.com/ibhagwan/fzf-lua/commit/09f9d1ab530d945456364dd54e17c3a3d1fd59d4 - should work, tested with your supplied autocmd.

**Comment by craigmac** [comment]
Whoa that was quick, thanks! Will check it right away, I was in the middle of doing some hacky looping through windows and checking window types that probably would have worked in the end, but nicer if I didn't have to :)

**Comment by craigmac** [comment]
Works perfectly, thanks!

**Comment by ibhagwan** [comment]
> Works perfectly, thanks!

Fantastic, ty for the update!
