### ISSUE TITLE
live_grep matches are not highlighted in preview or when selected

### ISSUE THREAD

**Issue by benyn** [ibhagwan/fzf-lua#659]
### Info

- Operating System: macOS Ventura 13.2.1 (22D68)
- Shell: zsh
- Terminal: Apple Terminal / VimR
- `nvim --version`: v0.8.3 (Terminal) / v0.8.2 (VimR)
- `fzf --version`: 0.38.0
- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  winopts = {
    preview = {
      default = "bat_async",
    },
  },
  grep = {
    cmd = "rg",
    file_icons = false,
    color_icons = false,
    git_icons = false,
  },
})
```
</details>

### Description 
`live_grep` matches are not highlighted in preview. When selected, the file is opened but the cursor doesn't go to the matching line. This issue is NOT reproducible with `mini.sh`.

This might be related to the `bat` issue in #651

**Comment by ibhagwan** [comment]
Ty @benyn for opening a new issue for this, can you try the below, press `Enter` (on a failed file) and paste the output from `:messages`?
```lua
:lua require("fzf-lua").live_grep({actions={["default"]=function(sel) print("sel:", sel[1]) end}})
```

> This issue is NOT reproducible with `mini.sh`

Usually when things break outside of `mini.sh` it is related to autocmd's set by the user or another plugin, can you check the output `:autocmd BufEnter` and `:autocmd WinEnter` for something suspecious?

**Comment by benyn** [comment]
This is what I got:
```
sel: nvim/lazy-lock.json:  "fzf-lua": { "branch": "main", "commit": "368b9980f7ddd9ee622cf84d0e7f96185a95bfc0" },

--- Autocommands ---
FileExplorer  BufEnter
    *         sil call s:LocalBrowse(expand("<amatch>"))
MiniAnimate  BufEnter
    *         lua vim.schedule(MiniAnimate.track_scroll_state)
lualine  BufEnter
    *         lua require'lualine.components.branch.git_branch'.find_git_dir()
              lua require'lualine.components.diff.git_diff'.update_diff_args()
lualine_stl_refresh  BufEnter
    *         call v:lua.require'lualine'.refresh({'kind': 'tabpage', 'place': ['statusline'], 'trigger': 'autocmd'})

--- Autocommands ---
MiniAnimate  WinEnter
    *         lua vim.schedule(MiniAnimate.track_scroll_state)
lualine_stl_refresh  WinEnter
    *         call v:lua.require'lualine'.refresh({'kind': 'tabpage', 'place': ['statusline'], 'trigger': 'autocmd'})
```
I got suspicious of MiniAnimate, and disabled it, but it's still not working.

**Comment by ibhagwan** [comment]
> sel: nvim/lazy-lock.json:  "fzf-lua": { "branch": "main", "commit": "368b9980f7ddd9ee622cf84d0e7f96185a95bfc0" },

There are no line/column output to your matches, I'm suspecting this is again due to the default non-GNU `grep` on MacOS.

Now that I know what this is I can fix it easily but I highly recommend installing ripgrep `rg`, it's much faster and fzf-lua (and pretty much everything grep related) is better with it.

**Comment by ibhagwan** [comment]
Scrap what I said, the issue you defined your grep command as `rg` with no options, it doesn't ouput lines/columns and since it doesn't exist fzf-lua doesn't know where to go.

Your setup should look like:
```lua
require('fzf-lua').setup({
  winopts = { ... },
  grep = {
    -- modify these options to your liking but don't remove lines or columns
    -- color_icons is also not needed since you disabled the icons
    cmd = "rg --column --line-number --no-heading --color=always",
    file_icons = false,
    git_icons = false,
  },
})
```

**Comment by benyn** [comment]
Ah, that makes perfect sense. What you suggested works. I just got rid of `cmd` altogether since fzf-lua defaults to `rg` when available. I added it when I was trying out different configurations to fix #651 and didn't think to remove it. Ha, I just saw you edited your answer and suggested I remove `cmd` altogether as I was writing that sentence. ;)

This also explains whey `rg_opts` didn't work when I added `--trim` there in addition to `cmd`. Guess `rg_opts` is ignored when `cmd` is overridden? Anyway, thanks for responding to this quickly.

**Comment by ibhagwan** [comment]
> This also explains whey rg_opts didn't work when I added --trim there in addition to cmd. Guess rg_opts is ignored when cmd is overridden? Anyway, thanks for responding to this quickly.

Correct, `cmd` takes precedence over everything else, `rg_opts` is only used on”auto-detect” as defaults.

**Comment by benyn** [comment]
Makes sense. A minor observation: README.md says `--max-columns=512` instead of 4096.

**Comment by ibhagwan** [comment]
> Makes sense. A minor observation: README.md says `--max-columns=512` instead of 4096.

Thanks! I’ll update it next time, or if you want to be a contributor you can submit a PR :)

**Comment by benyn** [comment]
Haha, it's such a minor thing to contribute, but why not, I feel quite invested in fzf-lua now. Just submitted a PR.
