### ISSUE TITLE
Request: enable builtin reviewer for larger files

### ISSUE THREAD

**Issue by tzachar** [ibhagwan/fzf-lua#66]
Can we make the following configurable? like setting `1000` to something larger?
https://github.com/ibhagwan/fzf-lua/blob/e6c4f31c06c60627397351ac1b4263ff76e024d2/lua/fzf-lua/previewer/builtin.lua#L182

**Comment by ibhagwan** [comment]
Certainly, I was planning to do add a config key for it just forgot.

I have a syntax issue to fix today as well, I currently set the `filetype` from the file extension but sometimes the extension doesn’t match the filetype (I.e. `md` has `ft = markdown`) which can prevent the syntax from working on certain extensions.

I fix both these issues today.

**Comment by tzachar** [comment]
10x

Amazing plugin btw ):

**Comment by ibhagwan** [comment]
> 10x
> 
> Amazing plugin btw ):

Ty :)

**Comment by ibhagwan** [comment]
Done, take a look at the `syntax_limit_b` and `syntax_limit_l` under `previewers.builtin`, can limit based on bytes/lines respectively, default line limit is 0 (no limit), default bytes limit is 1MB (1024*1024).
