### ISSUE TITLE
Aborting with `<Esc>` no longer works with `tnoremap <Esc> <C-\><C-n>`

### ISSUE THREAD

**Issue by bR3iN** [ibhagwan/fzf-lua#663]
### Steps to reproduce with `mini.sh`:
- `tnoremap <Esc> <C-\><C-n>`
- Run e.g. `FzfLua files` and try to close the pop-up with `<Esc>` or `<C-[>`.

### Description
Closing the fzf pop-up with `<Esc>`/`<C-[>` no longer works if `<Esc>` is mapped to `<C-\><C-n>` in terminal mode (which I think is a pretty common keymap). By trial and error I found the commit introducing this regression to be `15a57dcb19`.

### Edit: Workaround
Adding `tnoremap <buffer> <Esc> <Esc>` to `ftplugin/fzf.vim` is a simple way to regain the original behaviour.

**Comment by ibhagwan** [comment]
You’re correct about the commit, FzfLua used to overwrite the Esc map which it no longer does (it was part of an improvement to support resume properly with `fzf-tmux`).

FzfLua works in terminal, as such terminal mappings dictate the behavior of Esc, why don’t you add your workaround within the `on_create` event?

```lua
require'fzf-lua'.setup {
  winopts = {
    on_create = function()
      vim.cmd('tnoremap <buffer> <Esc> <Esc>')
    end,
  }
}
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/9a98006e62bda1a38f6c09c3d3bc97e723eca52b - should do what you want while also taking into account customizations (for example, if someone decided to map esc to a different action).

**Comment by bR3iN** [comment]
Yes, works for me now as expected (and as it worked previously). Thanks for the quick fix!

> FzfLua works in terminal, as such terminal mappings dictate the behavior of Esc

I didn't find it completely obvious while debugging the problem that the user's terminal keybinding influence the plugin's interface at all. Maybe this should be documented more explicitly?

> why don’t you add your workaround within the on_create event?

I simply wasn't aware of the `on_create` callback since I didn't configure the plugin itself much; doing this in `ftplugin/fzf.vim` was just the first working solution I found. But yes, `on_create` looks like the more sensible place for this.

**Comment by ibhagwan** [comment]
> I didn't find it completely obvious while debugging the problem that the user's terminal keybinding influence the plugin's interface at all. Maybe this should be documented more explicitly?

You’re right, unless you understand the inner workings it might not be clear enough, perhaps it’s time to revise some elements of the Wiki.

**Comment by danielo515** [comment]
So just to be clear, in order to properly close the popup with esc, the suggested mapping is required? Maybe it can be stated in the How-Tos or something like that. I'm very used to closing a lot of popups with esc, and discovering this change was a bit frustrating

**Comment by ibhagwan** [comment]
> So just to be clear, in order to properly close the popup with esc, the suggested mapping is required? Maybe it can be stated in the How-Tos or something like that. I'm very used to closing a lot of popups with esc, and discovering this change was a bit frustrating

When you have in your neovim config `tnoremap <Esc> <C-\><C-n>` you’re asking neovim to use `Esc` to return to normal mode in terminal buffers (which is what fzf is)), having this mapping isn’t the default in neovim, the previous behavior of overriding the user setting was wrong, it’s very easy to make the exception for Fzf as explained in this thread.

**Comment by danielo515** [comment]
Ah, Ok, I don't have that setup. However, I had some fzf windows that refused to close with esc regardless. Maybe it's because I'm calling them from Lua?

```lua
function D.fzf_find()
  local fzf = require("fzf-lua")
  local context_completion = D.get_context_suggestions()
  D.vim.input(function(search_term)
    fzf.grep({ search = search_term, multiprocess = true })
  end, context_completion)
end
```

**Comment by ibhagwan** [comment]
> Ah, Ok, I don't have that setup

Then this should never be an issue foe you, the default behavior for `Esc` is `abort` which closes the window.

> I had some fzf windows that refused to close with esc regardless. Maybe it's because I'm calling them from Lua

Unrelated, you can check if you have an Esc mapping by opening fzf-lua, pressing `<C-\><C-n>` to switch to normal mode and running `:tmap <Esc>`.

**Comment by danielo515** [comment]
Oh, It seems I have one!
```
12:09:02 msg_show   tmap <Esc> t  <Esc>       *@<Esc>t  <Esc><Esc>  * <C-\><C-N>
                 Enter Normal Mode
```
Then I guess this mapping is mandatory. Thanks.
