### ISSUE TITLE
[FR] ability to modify existing query via keybind

### ISSUE THREAD

**Issue by jrnxf** [ibhagwan/fzf-lua#665]
This might already be possible and not require any modification to the source, but what I'd like is to set a binding that receives the text of the current prompt and replaces the prompt with whatever it returns. A simple example would be a keybind that postfixes the prompt with " --" so you can jump into file globbing quickly.

Is something like this already supported?

**Comment by ibhagwan** [comment]
I changed your title as I believe what you meant is change the typed query not the prompt (e.g. “live grep”).

```lua

require'fzf-lua'.live_grep({ actions = { ['ctrl-y'] = { function()
  print("last", require'fzf-lua'.config.__resume_data.last_query)
  require'fzf-lua'.live_grep({ no_esc=true, search = require'fzf-lua'.config.__resume_data.last_query .. ' -- '})
end }}})
```

**Comment by jrnxf** [comment]
oh yeah I meant to say query! This solution works for great. It would be nice if it didn't perform a full refresh of your results/preview, but not a big deal. Thanks for the speedy response!

**Comment by ibhagwan** [comment]
For that we can use fzf's `transform-query`:
```lua
require("fzf-lua").live_grep({ keymap = { fzf = {
  ["ctrl-y"] = "transform-query(echo '{q} -- ')",
}}})
```

**Comment by jrnxf** [comment]
Perfect! Exactly what I was looking for :)

**Comment by ibhagwan** [comment]
Great closing :)

**Comment by jrnxf** [comment]
I'll leave it up to you, but I think it might be a nice add to the README or wiki! I bet there are people who would use it if they thought about it / knew it existed

**Comment by ibhagwan** [comment]
> I'll leave it up to you, but I think it might be a nice add to the README or wiki! I bet there are people who would use it if they thought about it / knew it existed

The README is overloaded as is, and this is technically an fzf option (upstream), I wouldn’t wanna replicate the upstream manual and have to maintain that every time upstream changes something.

I agree some common practices are valuable to add to the wiki but this is the first time this has come up, if you believe this is way too common feel free to edit the wiki which is open to all.
