### ISSUE TITLE
Is it possible to always keep the `Tab #n:` tag after filtering so the same buffer on different tabpages can be more easily differentiated?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#666]
As title. Say I start from this:

<img src="https://user-images.githubusercontent.com/24765272/220003878-de8ef9bf-c7f6-4100-ab3b-832ef4e7f962.png" width="500">

after typing `ux.lua` I got:

<img src="https://user-images.githubusercontent.com/24765272/220003917-58a5dc45-bd60-4c30-8440-62a70d4315ec.png" width="500">

but I will be very happy if I can distinguish which one with the help of those `Tab #`:

```
Tab #4:
  [3]      lua/plugins.UX.lua:268
Tab #5:
  [3]      lua/plugins.UX.lua:271
```

**Comment by ibhagwan** [comment]
Filtering is  controlled by fzf the binary, I don’t think that that’s possible.

**Comment by ibhagwan** [comment]
What you can do is “unhide” the tab number which is contained but hidden on every line:
```lua
tabs({ fzf_opts = { ['--with-nth'] = false }})
```

**Comment by nyngwang** [comment]
>     tabs({ fzf_opts = { ['--with-nth'] = false }})

This one resolves it! And I also found typing `n)` very convenient to list only buffers from `Tab #n`. Closing...!
