### ISSUE TITLE
Is the normal mode mapping of `<C-C>` to `^V^[` really necessary?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#667]
As title. I just noticed some strange mappings are stored in my session files: (Since those are invisible characters so I can only represent them by typing visible ones)

```vimscript
tnoremap <buffer> ^V^C ^V^[
noremap <buffer> ^V^C ^V^[
tnoremap <buffer> <C-C> ^V^[
noremap <buffer> <C-C> ^V^[
```

and these mappings seem to be created by these lines:

https://github.com/ibhagwan/fzf-lua/blob/7d5795e2dcc9289151c83c32177be8ca615cd4eb/lua/fzf-lua/fzf.lua#L191-L192

But I have my own mapping on `<C-C>`, which unfortunately got overridden by those ones above. Based on the comments above line 191 of `fzf.lua`, it seems that there is no other solution currently, right?

**Comment by ibhagwan** [comment]
See #653, it’s a preventative measure while a neovim bug exists in relation to ctrl-c, perhaps the first line can be removed as only the terminal mapping is needed.

**Comment by nyngwang** [comment]
> perhaps the first line can be removed as only the terminal mapping is needed.

This should resolve my problem! But if you find that it is still necessary then feel free to let me know... (I did come across that issue, but I didn't really understand the problem the author was facing. He/she is also a good plugin author so I trust your conclusion there.)

**Comment by ibhagwan** [comment]
> Might be out-of-topic but I really want to know: What's the meaning of setting empty mode string

I believe it's all modes, normal, visual and visual-select.

**Comment by nyngwang** [comment]
Just confirmed that 1423f02 does work, thank you!

**Comment by ibhagwan** [comment]
> Just confirmed that [1423f02](https://github.com/ibhagwan/fzf-lua/commit/1423f02cbbc24e21835d3fb71e9a543d0c826207) does work and your answer is really helpful, thank you!

From `:help nvim_set_keymap`, empty string is the equivalent of the `map` vimscript command (which maps to `nvo` modes):
```help
    Parameters: ~
      • {mode}  Mode short-name (map command prefix: "n", "i", "v", "x", …) or
                "!" for |:map!|, or empty string for |:map|.
```
