### ISSUE TITLE
Can not get correct devicons

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#668]
### Info

- Operating System: linux
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.9.0-dev
- `fzf --version`: 0.38

I got this error after the latest update. I already reinstall the plugin but still same  error

```sh
"/nix-config/users/sand/nvim/lua/plugins/lspconfig.lua" 176L, 5553B
E5108: Error executing lua: ...hare/nvim/lazy/fzf-lua/lua/fzf-lua/providers/buffers.lua:253: attempt to call a nil value
stack traceback:
	...hare/nvim/lazy/fzf-lua/lua/fzf-lua/providers/buffers.lua:253: in function 'buffer_lines'
	...hare/nvim/lazy/fzf-lua/lua/fzf-lua/providers/buffers.lua:223: in function 'blines'
	/home/sand/.config/nvim/lua/plugins/fzf.lua:113: in function </home/sand/.config/nvim/lua/plugins/fzf.lua:113>
```

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
      keymap = {
        builtin = {
          ['<F1>'] = 'toggle-help',
          ['<F2>'] = 'toggle-fullscreen',
          ['<F3>'] = 'toggle-preview',
          ['<PageDown>'] = 'preview-page-down',
          ['<PageUp>'] = 'preview-page-up',
          ['<Home>'] = 'preview-page-reset',
        },
        fzf = {
          ['tab'] = 'toggle',
          ['ctrl-a'] = 'toggle-all',
          ['ctrl-f'] = 'half-page-down',
          ['ctrl-b'] = 'half-page-up',
        },
      },
      fzf_opts = {
        ['--layout'] = false,
        ['--history'] = fzf_history_dir .. '/fzf-lua',
        ['--history-size'] = '2000',
      },
      actions = {
        files = {
          ['ctrl-s'] = fzf_lua.actions.file_vsplit,
        },
        buffers = {
          ['ctrl-s'] = fzf_lua.actions.buf_vsplit,
        }
      },
      grep = {
        git_icons = false,
        file_icons = false,
        color_icons = false,
      },
      oldfiles = {
        cwd_only = true,
        include_current_session = true,
      },
})
```
</details>

**Comment by ibhagwan** [comment]
This seems to be coming from the devicons integration, does `files` or anything else works normally?

Does `:FzfLua blines color_icons=false` works?

**Comment by sandangel** [comment]
@ibhagwan `files` and `grep` work fine. `:FzfLua blines color_icons=false` also work

**Comment by ibhagwan** [comment]
A few more questions:

- Does `lines|blines` work with `mini.sh` (wasn't clear to me if you tested from the OP)?
- What file extension does this fail on?
- Does the output of `:lua _G.dump(require"fzf-lua".utils.ansi_codes)` look somewhat like:
```
{
  DevIconAi = <function 1>,
  DevIconAwk = <function 2>,
  DevIconBabelrc = <function 3>,
  DevIconBash = <function 4>,
  DevIconBashProfile = <function 5>,
  DevIconBashrc = <function 6>,
  DevIconBat = <function 7>,
  DevIconBinaryGLTF = <function 8>,
  DevIconBmp = <function 9>,
  ...
}
```
- What's the output of `:lua print(require"fzf-lua".utils.ansi_codes.DevIconLua)` (should print out `function: ...` into `:messages`)
- What's the output of `:lua print(require"fzf-lua".utils.ansi_codes.DevIcon<Your file extension>)`  (e.g. `DevIconCpp`)?

**Comment by sandangel** [comment]
* It failed on lua file
* Output of lua _G.dump(require"fzf-lua".utils.ansi_codes)
```lua
{
  black = <function 1>,
  blue = <function 2>,
  bold = <function 3>,
  clear = <function 4>,
  cyan = <function 5>,
  dark_grey = <function 6>,
  green = <function 7>,
  grey = <function 8>,
  italic = <function 9>,
  magenta = <function 10>,
  red = <function 11>,
  underline = <function 12>,
  white = <function 13>,
  yellow = <function 14>
}
```

* OUtput of lua print(require"fzf-lua".utils.ansi_codes.DevIconLua)

```lua
nil
```

**Comment by ibhagwan** [comment]
> Does lines|blines work with mini.sh (wasn't clear to me if you tested from the OP)?

You didn't answer this, can you try running `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"` and tell me if it works?

There's an issue setting up devicon highlights, I'm surprised `files` is working for you given there's no `file_icons=false` under your `setup.files`.

More questions:
- What's the output of `:lua _G.dump(require"nvim-web-devicons".get_icon("1.lua","lua",{default=true}))`
- What's the output of `:lua _G.dump(require"nvim-web-devicons".get_icons())`, should look something like:
```
{ {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Default"
  },
  [".DS_Store"] = {
    color = "#41535b",
    cterm_color = "59",
    icon = "",
    name = "DsStore"
  },
  ...
```

**Comment by sandangel** [comment]
I think I messed up my icons config

**Comment by sandangel** [comment]
thanks for helping

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/15e9b1f1494dc1facaffe9543281d015c43b9eba - this commits works around your issue by settings the defaults of `blines` to no icons/colors (as the file is a hidden field in `blines` anyways).

**Comment by sandangel** [comment]
@ibhagwan okay I think I found the issue, there is no `DevIconLua`, but there is `DevIconlua`. You might want to normalize the case of devicon.

**Comment by sandangel** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/22189661/221349246-91f47d58-11cb-4a86-93d7-3385bf5a9928.png">

the right hand side is fzf-lua `files`, the left hand side is `nvim-tree`. Nvim tree can pickup the icon correctly, but fzf-lua doesn't

**Comment by sandangel** [comment]
```lua
return {
  'nvim-tree/nvim-web-devicons',
  dependencies = { { 'NvChad/ui', branch = 'v2.0' }, { 'NvChad/base46', branch = 'v2.0' } },
  config = function()
    local colors = require('base46').get_theme_tb 'base_30'
    local override = vim.tbl_deep_extend('force', require('nvchad_ui.icons').devicons, {
      default_icon = { color = colors.red },
      c = { color = colors.blue, name = 'C' },
      css = { color = colors.blue },
      deb = { color = colors.cyan },
      Dockerfile = { color = colors.cyan },
      html = { color = colors.baby_pink },
      jpeg = { color = colors.dark_purple },
      jpg = { color = colors.dark_purple },
      js = { color = colors.sun },
      kt = { color = colors.orange },
      lock = { color = colors.red },
      lua = { color = colors.blue },
      mp3 = { color = colors.white },
      mp4 = { color = colors.white },
      out = { color = colors.white },
      png = { color = colors.dark_purple },
      py = { color = colors.cyan },
      toml = { color = colors.blue },
      ts = { color = colors.teal },
      ttf = { color = colors.white },
      rb = { color = colors.pink },
      rpm = { color = colors.orange },
      vue = { color = colors.vibrant_green },
      woff = { color = colors.white },
      woff2 = { color = colors.white },
      xz = { color = colors.sun },
      zip = { color = colors.sun },
      ['robots.txt'] = { color = colors.blue },
      ['docker-compose.yaml'] = {
        icon = '',
        name = 'DockerCompose',
        color = colors.cyan,
      },
      ['.dockerignore'] = {
        icon = '',
        name = 'DockerIgnore',
        color = colors.cyan,
      },
      yaml = {
        icon = '',
        name = 'yaml',
        color = colors.orange,
      },
      hcl = {
        icon = '',
        color = colors.green,
        name = 'hcl',
      },
      json = {
        icon = '',
        color = colors.green,
        name = 'Json',
      },
      md = {
        icon = '',
        color = colors.vibrant_green,
        name = 'md',
      },
      sh = {
        icon = '',
        color = colors.yellow,
        name = 'sh',
      },
      sql = {
        icon = '',
        color = colors.red,
        name = 'sql',
      },
    })
    require('nvim-web-devicons').setup {
      override = override
    }
  end
}
```
this is my `web-dev-icons` settings using Lazy if you would like to reproduce

**Comment by ibhagwan** [comment]
> @ibhagwan okay I think I found the issue, there is no `DevIconLua`, but there is `DevIconlua`. You might want to normalize the word case of devicon.

I thought about it before but this turned out to never be an issue, the issue is just with your setup since you’re overriding  the `name` property, whats the purpose of doing so?

What if you override the name completely not just change the capitalization? It shouldn’t matter as long as  devicons returns the same name from both `geticons` and `geticon`.

What’s the output of `:lua _G.dump(require"nvim-web-devicons".get_icon("1.lua","lua",{default=true}))`?  Is it `Lua` or `lua`?

**Comment by sandangel** [comment]
@ibhagwan I got this one: `"" "DevIconlua"`

**Comment by ibhagwan** [comment]
> @ibhagwan I got this one: "" "DevIconlua"

Everything is working as expected.

I just tried icon override with devicons and it also works as expected:
```lua
require("nvim-web-devicons").setup({
  override = {
    lua = {
      icon = "",
      color = "#89e051",
      cterm_color = "113",
      name = "luaicon",
    },
  },
})
```

My lua icons now look like terminal icons, and `:lua _G.dump(require"nvim-web-devicons".get_icon("1.lua","lua",{default=true}))` returns: `"" "DevIconluaicon"` - the case doesn't need to be normalized and both fzf-lua and devicons are adpating accordingly.

This issue is different than the original issue, you have no lua exceptions, the icons are picked up properly but the icon chosen for docker seems to have a font rendering issue within the neovim terminal (as I wrote above, fzf-lua runs fzf **inside a neovim terminal**).

Try to change docker to a different icon, for example change it to `a` and I expect it will work, figure out why your font doesn't render this icon within the neovim terminal and you'll have your solution.

**Comment by ibhagwan** [comment]
The issue is `devicons` defaults for `Dockerfile` contains an icon that's not part of nerd fonts, I suspect you have a custom definition for "special files" in nvim-tree that's why it works, you need to add an override to `Dockerfile` to get the result you want:
```lua
require("nvim-web-devicons").setup({
  override = {
    Dockerfile = {
      icon = "",
      color = "#458ee6",
      cterm_color = "33",
      name = "Dockerfile",
    },
  },
})
```

**Comment by sandangel** [comment]
@ibhagwan 

> The issue is devicons defaults for Dockerfile contains an icon that's not part of nerd fonts, I suspect you have a custom definition for "special files" in nvim-tree that's why it works

I think this is not correct. I have a code override like you mentioned already in web-devicons config. There is nothing specific.

```lua
    local override = vim.tbl_deep_extend('force', require('nvchad_ui.icons').devicons, {
      default_icon = { color = colors.red },
      c = { color = colors.blue, name = 'C' },
      css = { color = colors.blue },
      deb = { color = colors.cyan },
      Dockerfile = { color = colors.cyan }   -- <<----- this line
```

So I just reuse the table defined here and add colors to it using `tbl_deep_extend`

https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/icons.lua#L44

**Comment by sandangel** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/22189661/221407330-7741125a-a5ac-4c74-aead-6af33f2baf84.png">

I also changed the icon to `a` but it doesn't work either.

**Comment by sandangel** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/22189661/221407551-6675c6ac-d480-43c8-bf56-ee1c0414c228.png">

I also open nvim terminal and tried `ls`, it also showed dockerfile icon correctly

**Comment by ibhagwan** [comment]
- What does `:lua _G.dump(require"nvim-web-devicons".get_icon("Dockerfile","Dockerfile",{default=true}))` return?
- Can you add an override setting the icon to the letter `a` and see if it works?

**Comment by sandangel** [comment]
- "" "DevIconDockerfile"

- I set icon to letter `a` as above and it still doesn't work https://github.com/ibhagwan/fzf-lua/issues/668#issuecomment-1445334818

**Comment by ibhagwan** [comment]
> "" "DevIconDockerfile"

This seems accurate.

> I set icon to letter `a` as above and it still doesn't work

I understand your issue now, by default, overrides do not work with providers that use `multiprocess` (`files`, `grep`, etc), as these providers spawn in an external process, if you try `lines` (which doesn't run in an external process) you will see it works.

To apply your overrides in the external process read this:
https://github.com/ibhagwan/fzf-lua/wiki#how-can-i-use-custom-devicons-with-multiprocess

You'll need to move your devicons overrides to a separate file (with its limitations), see #657, #386, #311.

**Comment by ibhagwan** [comment]
@sandangel, https://github.com/ibhagwan/fzf-lua/commit/604eadfcf69b90cf9e508767ad217107520ce4d4 - this commits makes my previous post moot, everything should now work as expected including overrides without additional setup.

Let me know if this works as expected now?

**Comment by sandangel** [comment]
okay now it works as expected. thanks a lot for fixing.

**Comment by ibhagwan** [comment]
> okay now it works as expected. thanks a lot for fixing.

Great, ty for the update!
