### ISSUE TITLE
Question: Combining results from lsp_refs , lsp_defs

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#669]
### Info

Hi, I think I asked this question before, now I'm trying to implement it.

I'm trying to reuse the code to query lsp results from fzf-lua but [the function is not exposed](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/lsp.lua#L358)

I have this so far. 

```lua
      vim.keymap.set('n', 'gd', function()
        local lsp = require('fzf-lua.providers.lsp')
        lsp.definitions()
        -- lsp_typedefs = { "fzf-lua.providers.lsp", "typedefs" },
        -- lsp_references = { "fzf-lua.providers.lsp", "references" },
        -- lsp_definitions = { "fzf-lua.providers.lsp", "definitions" },
        -- lsp_declarations = { "fzf-lua.providers.lsp", "declarations" },
        -- lsp_implementations = { "fzf-lua.providers.lsp", "implementations" },
      end, opts)

```

Is it possible that we can expose those function or make it easier to reuse? Like exposing the functions those returning the results LSP only (not open fzf windows or something else), then I can combine them together and feed them to `fzf_exec`.

- Operating System:
- Shell:
- Terminal:
- `nvim --version`:
- `fzf --version`:

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

**Comment by ibhagwan** [comment]
`definitions` is exposed publicly:
https://github.com/ibhagwan/fzf-lua/blob/15e9b1f1494dc1facaffe9543281d015c43b9eba/lua/fzf-lua/providers/lsp.lua#L373

but it’s not returning a simple set of results as your code suggests, it’s a bit more complicated with callback handlers (for the async option), your best bet is copying parts of the code and modifying it to woke shnc only and combine the items in one big table, or alternatively (but more complex), use the async method and keep the pipe open until all LSP callbacks from all your calls are complete.

**Comment by sandangel** [comment]
> alternatively (but more complex), use the async method and keep the pipe open until all LSP callbacks from all your calls are complete.

I think  this one would be ideal. Could you share with me which code should I copy from?

**Comment by ibhagwan** [comment]
You'll have to follow this function, explore what it does and then copy the relevant parts:
https://github.com/ibhagwan/fzf-lua/blob/15e9b1f1494dc1facaffe9543281d015c43b9eba/lua/fzf-lua/providers/lsp.lua#L208

**Comment by sandangel** [comment]
may I ask where can I reference the opts structure?

**Comment by ibhagwan** [comment]
> may I ask where can I reference the opts structure?

Opts is the table sent in the original call, i.e `definitions({ <opts> })`, I'm afraid you're gonna have to dig deeper into the code and lua of you want to make this work, copy-paste without a deeper understanding of where things come from won't work for your mission.

**Comment by sandangel** [comment]
Is it possible that we consider this is a feature to add to fzf-lua? So instead of remembering 4 or 5 key mappings for lsp related actions like lsp_refs, lsp_defs, lsp_impls, lsp_typedefs, lsp_declarations, we only need to hit 1 key map to get all related information!

**Comment by sandangel** [comment]
and in this code, you call all functions the same way: https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/lsp.lua#L369-L387

How does it know which lsp query it needs to execute? The `opts` in those functions are the same with [this default opts](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/defaults.lua#L534-L543) right?

**Comment by sandangel** [comment]
okay I found 

```lua
  ["references"] = {
    label = "References",
    resolved_capability = "find_references",
    server_capability = "referencesProvider",
    method = "textDocument/references",
    handler = location_handler
  },
  ["definitions"] = {
    label = "Definitions",
    resolved_capability = "goto_definition",
    server_capability = "definitionProvider",
    method = "textDocument/definition",
    handler = location_handler
  },
  ["declarations"] = {
    label = "Declarations",
    resolved_capability = "goto_declaration",
    server_capability = "declarationProvider",
    method = "textDocument/declaration",
    handler = location_handler
  },
  ["typedefs"] = {
    label = "Type Definitions",
    resolved_capability = "type_definition",
    server_capability = "typeDefinitionProvider",
    method = "textDocument/typeDefinition",
    handler = location_handler
  },
  ["implementations"] = {
    label = "Implementations",
    resolved_capability = "implementation",
    server_capability = "implementationProvider",
    method = "textDocument/implementation",
    handler = location_handler
  },

```

**Comment by ibhagwan** [comment]
> Is it possible that we consider this is a feature to add to fzf-lua? So instead of remembering 4 or 5 key mappings for lsp related actions like lsp_refs, lsp_defs, lsp_impls, lsp_typedefs, lsp_declarations, we only need to hit 1 key map to get all related information!

Maybe one day if I get in the mood and I’m bored but currently no plans to add yet more providers combining existing info.

> and in this code, you call all functions the same way: https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/lsp.lua#L369-L387
> 
> How does it know which lsp query it needs to execute? The `opts` in those functions are the same with [this default opts](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/defaults.lua#L534-L543) right?

As I wrote above this is lua basics, fork the project, use it locally, change lines and you’ll figure it out, me feeding you question by question will get us nowhere.

**Comment by sandangel** [comment]
I opened a PR for this in #671 . Could you help me take a look?

**Comment by ibhagwan** [comment]
@sandangel, can you test the `lsp_finder` provider in the [`lsp_finder` branch](https://github.com/ibhagwan/fzf-lua/tree/lsp_finder)?

It's still WIP I have to add colors to the display and make async work but it's getting there, would love to have your feedback so I know this is on the right track.

**Comment by sandangel** [comment]
Absolutely, let me try that branch later today. 🙏🙏🙏

**Comment by ibhagwan** [comment]
@sandangel, this was completed in https://github.com/ibhagwan/fzf-lua/commit/5afd287adddeefed487e83b954212895b48f0783, you can customize it via setup under `lsp.finder`, see [README#Default-options](https://github.com/ibhagwan/fzf-lua#default-options) for all available settings, play around with it and lmk if this answers your need.

**Comment by sandangel** [comment]
oh my god, you are so fast, I just pull the change and will try as much as possible today. Thanks a lottttt for giving this features 🙏🙏. Are you considering adding a post in reddit channel for new features updates? I really love to see this on neovim weekly news. 😀😀😀

**Comment by ibhagwan** [comment]
> oh my god, you are so fast, I just pull the change and will try as much as possible today. Thanks a lottttt for giving this features 🙏🙏. Are you considering adding a post in reddit channel for new features updates? I really love to see this on neovim weekly news. 😀😀😀

I probably won’t do it but feel free to customization the icons (or even without) and get some karma from it :)

**Comment by sandangel** [comment]
Hi @ibhagwan , I think I ran into the first issue that I want to sort the order of result, for example the definition should go first, then reference. Can we change the order of providers config so the result from that provider will show first?

**Comment by ibhagwan** [comment]
Actually I already thought of that, reconfigure the `lsp.finder.providers` table (as shown in the readme) and sort the providers any way yo wish.

**Comment by sandangel** [comment]
Awesomeee. It works perfectly now. I will try it more for a few days and see. Thanks a lot.

**Comment by ibhagwan** [comment]
> @sandangel @ibhagwan Just want to say thank you for this feature!

Thanks @nyngwang

**Comment by nyngwang** [comment]
@ibhagwan Hi, firstly sorry for tagging you on a closed issue. I would like to know whether it is possible to do further customization. Currently, it's a common case that many different sources are pointing to the same destination, for example here the first four entries are all pointing to `segment.py:8:18`:

<img src="https://user-images.githubusercontent.com/24765272/232754743-a5ab31d1-52df-4c55-af5e-506e5b9d1143.png" width="700">

I would like to be able to merge all entries that lead to the same destination, so the information is more concise. About those tags `decl`,`def`,`tdef`,`ref`, etc, I would like to use one single char(and keep those distinguishable colors) for each of them after merge. (I know this part should better be put into a standalone issue if it's more complex than I think.) It will look like this:

D,d,t,r | segment.py:

**Comment by ibhagwan** [comment]
@nyngwang, unfortunately not possible, this was done by combining providers in a generic way, the only processing possible is formatting one line (adding prefix), it is run async, there is no way to process the results with the awareness of the final result.

**Comment by nyngwang** [comment]
@ibhagwan Is it possible to customize the previewer of lsp_finder? That is I want to apply my custom previewer from #677. Currently, I have this:


```lua
diagnostics = {
  previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
  fzf_opts = { ['--keep-right'] = '' },
},
lsp = {
  previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
  force_uri = true, -- https://github.com/ibhagwan/fzf-lua/issues/336.
},
git = {
  previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
  status = { show_cwd_header = true },
  files = { show_cwd_header = true },
},
```

**Comment by nyngwang** [comment]
I thought it was:

```
setup {
  -- ..
  finder = {
    previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
  },
}
```

but it turned out to be this nested one inspired by the original PR [line](https://github.com/ibhagwan/fzf-lua/blob/a81d18ee591635ce537bfa045ed1edf7dbe30cf3/lua/fzf-lua/defaults.lua#L593):

```lua
lsp = {
  previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
  force_uri = true, -- https://github.com/ibhagwan/fzf-lua/issues/336.
  finder = {
    previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
  },
},
```

**Comment by ibhagwan** [comment]
> but it turned out to be this nested one inspired by the original PR [line](https://github.com/ibhagwan/fzf-lua/blob/a81d18ee591635ce537bfa045ed1edf7dbe30cf3/lua/fzf-lua/defaults.lua#L593). This is a little counter-intuitive since I would expect that if `lsp.finder.previewer` is not defined then `lsp.previewer` should be used.
> 
> ```lua
> .setup {
>   lsp = {
>     previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
>     -- ...
>     -- nested inside `setup.lsp`.
>     finder = {
>       previewer = function () return require('ningwang.utils.fzf-previewer-M') end,
>     },
>   },
> }
> ```

You’re correct `lsp.finder` is the correct setting, you can also see the config path here:
https://github.com/ibhagwan/fzf-lua/blob/79c7c3480cc363b3d4ecdfcb8b56623d9decd570/lua/fzf-lua/providers/lsp.lua#L579
