### ISSUE TITLE
Question: Using custom `make_entry.tag`

### ISSUE THREAD

**Issue by ajitid** [ibhagwan/fzf-lua#670]
I was thinking to use [xref](https://docs.ctags.io/en/latest/output-format.html) format instead because its output is more clean and it doesn't abbreviates var's type (function, constant...). I thought I could be able to monkey patch [`make_entry.tag`](https://github.com/ibhagwan/fzf-lua/blob/15e9b1f1494dc1facaffe9543281d015c43b9eba/lua/fzf-lua/make_entry.lua#L387) to live grep my workspace tags but it doesn't seem possible to do.

Is there a safe and correct way to override this function? 

Edit: Turning [multiprocess](https://github.com/ibhagwan/fzf-lua/blob/15e9b1f1494dc1facaffe9543281d015c43b9eba/lua/fzf-lua/providers/tags.lua#L105) off here (assigning it to `false` a line above) does run my monkey-patched function but I don't want to lose any perf gains by touching that.

**Comment by ibhagwan** [comment]
> Turning [multiprocess](https://github.com/ibhagwan/fzf-lua/blob/15e9b1f1494dc1facaffe9543281d015c43b9eba/lua/fzf-lua/providers/tags.lua#L105) off here (but assigning it to false a line above) does run my monkey-patched function but I don't want to lose any perf gains by touching that.

You’re correct, unless you patch the actual file any in memory lua function overrides won’t work as `multiprocess` loads the file directly in the external process thus losing your “monkey patch”, if you run `:FzfLua tags debug=true` and explore `:messages` you’ll see the `require` for `make_entry.tag` function being passed as a string to the external process, you can perhaps override that by sending `dofile(<exact path of your tag process func>)` which will load your customized processor?

**Comment by ajitid** [comment]
Yeah, I think it's not worth this much hassle to get pretty lines. Thanks anyway!

**Comment by ibhagwan** [comment]
> Yeah, I think it's not worth this much hassle to get pretty lines. Thanks anyway!

Alright :)

Here is where it’s set if you change your mind:
https://github.com/ibhagwan/fzf-lua/blob/15e9b1f1494dc1facaffe9543281d015c43b9eba/lua/fzf-lua/providers/tags.lua#L105-L109

**Comment by ajitid** [comment]
Given that multiprocess means "run command in a separate process", what would I lose by marking it as `false`. Any perf gain, some sort of conflict, or something else?

**Comment by ibhagwan** [comment]
> Given that multiprocess means "run command in a separate process", what would I lose by marking it as `false`? Any perf gain, avoidance from any sort of conflict, or something else?

That means all processing of the command will be done on neovim’s main thread, similar to Telesceope, that means that on very large repos, you can experience UI lag and interface hangs, multiprocess runs the command externally in a totally independent process as if you ran another shell externally in a different term, freeing the neoivm process.
