### ISSUE TITLE
Jump to the bottom?

### ISSUE THREAD

**Issue by danielo515** [ibhagwan/fzf-lua#673]
Hello, and thank you for this wonderful extension. It solves my telescope performance issues.

Something I mis, however, is the ability to jump to the bottom of the list. Some times it is easier to me to start from the very bottom to reach some file or definition. Is it possible?
Ideally, I want the list to wrap the cursor movement, so when I hit up in the first element, it goes to the bottom of the list.

Thanks

**Comment by ibhagwan** [comment]
The available keybinds within the list are controlled by the fzf binary, I’m not sure if what you’re looking for exists, see [man fzf](https://www.mankier.com/1/fzf#Key/Event_Bindings-Available_Actions), I haven’t seen anything more than `page-down` but I could be missing something or the linked man page isn’t fully up to date.

**Comment by nyngwang** [comment]
@danielo515 

```lua
require('fzf-lua').setup {
  fzf_opts = {
    ['--cycle'] = '',
```

**Comment by ibhagwan** [comment]
> @danielo515
> 
> ```lua
> require('fzf-lua').setup {
>   fzf_opts = {
>     ['--cycle'] = '',
> ```

Ty @nyngwang! I didn’t know `--cycle` existed :)

Closing, @danielo515 feel free to reopen if you need more help.
