### ISSUE TITLE
Question: Is it still possible to achieve `toggle_fullscreen` when `fzf_bin = 'fzf-tmux'`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#675]
### Description 

As title. In short after migration to `fzf-tmux` my keymap on `<F1>` apparently cannot work anymore. There are cases where the line of entries(items?) is too long to read its content, e.g. `:FzfLua lsp_workspace_diagnostics`. (Sorry if this is a tmux-related question that should not appear here. Feel free to close)

---

After a second thought showing the preview at the ~~bottom~~ top of the floating window sounds like a great alternative. Keep this issue open as I'm still interested in the `toggle_fullscreen` part.

<img src="https://user-images.githubusercontent.com/24765272/223230399-435edbb1-6ea5-4f4a-8da2-3279450899da.png" width="500">

---

```lua
require('fzf-lua').setup {
  fzf_bin = 'fzf-tmux',
  fzf_tmux_opts = {
    ['-p'] = '80%,80%',
  },
  -- lines truncated.
}

vim.keymap.set('t', '<F1>', function () if vim.bo.filetype == 'fzf' then require('fzf-lua.win').toggle_fullscreen() end end)
```
<img src="https://user-images.githubusercontent.com/24765272/223229280-f40f1969-82de-4865-a4b6-79f507a04045.png" width="500">

**Comment by ibhagwan** [comment]
> my keymap on `<F1>` apparently cannot work anymore

Not possible anymore, help is currently programmed using a neovim window, I have no plans on recreating it using a tmux popup.

A toggle isn’t possible but you can have a keybind that opens the popup in full-screen:
```lua
require'fzf-lua'.files({ fzf_tmux_opts = { ["-p"] = "100%,100%" } })
```

**Comment by nyngwang** [comment]
> Not possible anymore, help is currently programmed using a neovim window [...]

👌 and Closing...
