### ISSUE TITLE
Opening a file (e.g. via git_files) always opens file with absolute path.

### ISSUE THREAD

**Issue by DanielSiepmann** [ibhagwan/fzf-lua#678]
### Info

- Operating System: ubuntu/nix
- Shell: zsh
- Terminal: st
- `nvim --version`: v0.8.3
- `fzf --version`: 0.38.0

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
    fzf_bin = "fzf-tmux",
    fzf_opts = {
        ["--border"] = "rounded",
    },
    fzf_tmux_opts = {
        ["-p"] = "",
        ["-y"] = "1",
        ["-w"] = "95%",
        ["-h"] = "75%",
    },
    winopts = {
        preview = {
            hidden = "hidden", -- I don't like a preview, keep space for selection
        },
    },
})

require("fzf-lua").register_ui_select()

```
</details>

### Description 

Opening a file (e.g. via git_files) always opens file with absolute path.
I would expect the file to open relativ to current working dir of neovim instance.

The issue with absolute paths is that other plugins will work on current buffer path and will not properly react to the working dir anymore.
I'll handle in an PR with a proposal.

This is probably releated to #341 and b273a358a7a33bebcf6e5c1ef1adc25439083023.

**Comment by ibhagwan** [comment]
> The issue with absolute paths is that other plugins will work on current buffer path and will not properly react to the working dir anymore.
I'll handle in an PR with a proposal.

I’m not sure what you mean by the above, never heard of anything breaking because something has full path, use `:e <file>` with both relative and full path and run `: lua print(vim.api.nvim_buf_get_name(0))`, the internal path is always full.

Please expand on what exactly is your issue and what’s breaking with “other plugins”?

**Comment by DanielSiepmann** [comment]
I did within the PR :) Will copy it here for completeness:

` expand('%:r')` will expand to the full path instead of relative path, causing trouble in my setup.

`set statusline+=\ %f` also shows the "full" path with ~ instead of relative path, consuming unnecessary space for information I don't care about.

**Comment by ibhagwan** [comment]
Update to https://github.com/ibhagwan/fzf-lua/commit/592ab9a26176a7f9ebd43faf91d1f5d066e0aa07 - should solve your issue.

**Comment by DanielSiepmann** [comment]
Cool, thanks for taking the time and fixing my issue. That works as well :+1:
