### ISSUE TITLE
Possible to restrict several directories to pass to FZF?

### ISSUE THREAD

**Issue by yangmillstheory** [ibhagwan/fzf-lua#683]
Hi,

I work on a codebase that's massive, millions of lines of code. In my Vim config, I have something like this to be able to manually set the directory I pass to `rg` (which is used by `fzf`).

```
" https://github.com/junegunn/fzf.vim#advanced-customization
"
" explicitly include/exclude directories from fzf + rg
" these aren't plugin options, but our own :)
let g:rg_in = []
let g:rg_ex = []
nnoremap <Leader>d q:ilet g:rg_in=['']<esc>hi
function! s:RgArgs(args) abort
  let rg_args = []
  if len(g:rg_ex)
    let rg_args += ["--glob=!{" . join(g:rg_ex, ",") . "}"]
  endif
  if len(a:args)
    let rg_args += [a:args]
  endif
  return join(rg_args + g:rg_in, " ")
endfunction
command! -bang -complete=dir -nargs=? FzfFiles
\ call fzf#run(fzf#wrap({
\     'source': $FZF_DEFAULT_COMMAND . " " . s:RgArgs(''),
\     'options': $FZF_DEFAULT_OPTS . " " . $FZF_CTRL_T_OPTS,
\   }),
\   <bang>0
\ )
command! -bang -nargs=* FzfRg
\ call fzf#vim#grep(
\   "rg --hidden --ignore-case --column --line-number --no-heading --color=always " . s:RgArgs(<q-args>), 1,
\   <bang>0 ? fzf#vim#with_preview('up:60%')
\           : fzf#vim#with_preview('right:50%'),
\   <bang>0)
" }}}
```

Would it be possible to do this via your plugin?

**Comment by ibhagwan** [comment]
It’s one of the most basic use cases, use the `cwd` option (works with all providers, not just grep):
```lua
require'fzf-lua'.live_grep({ cwd = <directory> })
```

**Comment by ibhagwan** [comment]
If you wish to use globs as your code snippet suggests, take a look at this:
https://github.com/ibhagwan/fzf-lua/wiki#live-grep-glob

**Comment by yangmillstheory** [comment]
Thanks - is there a config option that would work with the `files` command?

**Comment by ibhagwan** [comment]
> Thanks - is there a config option that would work with the `files` command?

`cwd` works with files too.

**Comment by yangmillstheory** [comment]
OK, thanks, I'll try this out!

**Comment by yangmillstheory** [comment]
Here's my `after/plugin/fzf-lua.lua` file:

```lua
local g = vim.g

-- https://github.com/junegunn/fzf.vim#advanced-customization
--
-- explicitly include/exclude directories from fzf + rg
g.rg_in = {}
g.rg_ex = {}

-- quickly edit g.rg_in
vim.api.nvim_set_keymap('n', '<leader>d', ":q:ilet g:rg_in=['']<esc>hi", {})

local fzf = require('fzf-lua')

fzf.setup({
  files = {
    cwd = table.concat(g.rg_in, " ")
  },
  grep = {
    cwd = table.concat(g.rg_in, " ")
  },
})

local keymap_opts = { silent = true, noremap = true }
vim.api.nvim_set_keymap('n', '<c-t>', ':FzfLua files<cr>',keymap_opts )
vim.api.nvim_set_keymap('n', '<c-f>', ':FzfLua live_grep<space>', keymap_opts) 
vim.api.nvim_set_keymap('n', '<c-b>', ':FzfLua buffers<cr>', keymap_opts) 
vim.api.nvim_set_keymap('n', '<c-_>', ':FzfLua blines<cr>', keymap_opts) 
vim.api.nvim_set_keymap('n', '<c-r>', ':FzfLua command_history<cr>', keymap_opts) 
vim.api.nvim_set_keymap('n', '<c-s>', ':FzfLua search_history<cr>', keymap_opts) 
vim.api.nvim_set_keymap('n', '<c-c>', ':FzfLua commands<cr>', keymap_opts) 
vim.api.nvim_set_keymap('n', '<c-q>', ':FzfLua quickfix<cr>', keymap_opts) 
```

I set `g:rg_in` to my home directory. When I try CTRL-T, I get 

![image](https://user-images.githubusercontent.com/2729079/224570029-ecdb93db-65b9-46e0-a124-2d4a267d9bdc.png)

which is empty, but I should be finding files. What am I doing wrong?

**Comment by yangmillstheory** [comment]
Also when I do `<leader>d` and set `g:rg_in` to any directory and press Enter, the `FzfLua marks` window pops up:

![image](https://user-images.githubusercontent.com/2729079/224570265-d40311b4-560d-450c-9821-fa81eb7badc9.png)

And when I try to quit out of the FZF panes (CTRL-C or Escape), the panes don't seem to go away.

**Comment by ibhagwan** [comment]
> which is empty, but I should be finding files. What am I doing wrong?

Why are you using `table.concat`?

It seems you’re sending an empty `cwd`, in lua there is no `g.`,  change it to `vim.g.rg_in` instead.

You can also check if the var is set with `:lua print(vim.g.rg_in)` which should print the variable into `:messages`, once you verified the global var is set use `:lua require'fzf-lua'.files({ cwd = vim.g.rg_in })` and see if it works.

**Comment by ibhagwan** [comment]
> Why are there two panes there?

The second pane is the preview which you can hide with `F4` (use `F1` to see all the binds).

**Comment by ibhagwan** [comment]
> And when I try to quit out of the FZF panes (CTRL-C or Escape), the panes don't seem to go away.

Perhaps you have something in your config taking over the binds?

First try with `mini.sh` and see that everything works, if it doesn’t work with `min.sh` it’s a bug (unlikely or there would be tons of issues about closing the panels):
```sh
sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"
```

**Comment by yangmillstheory** [comment]
It seems I can somewhat leverage `cwd` via:

```lua
vim.api.nvim_set_keymap('n', '<c-t>',
  ':lua require("fzf-lua").files({ cwd = table.concat(vim.g.rg_in, " ") })<cr>',
  keymap_opts)
```

>Why are you using table.concat?

I'd like to specify multiple paths, not a single root. This doesn't seem possible. Can it be supported?

![image](https://user-images.githubusercontent.com/2729079/224575375-c27d6807-3a61-4c68-824b-f717c1369cf8.png)

Again I work in a codebase with O(1M), possibly O(100M) files, with directories of interest rooted in various places, not all under the same root.

**Comment by ibhagwan** [comment]
> I'd like to specify multiple paths, not a single root. This doesn't seem possible. Can it be supported?

The underlying command runs `rg --files` inside a working directory, perhaps you can craft a shell command that combines multiple commands but it’s not supported natively.

**Comment by yangmillstheory** [comment]
Could you implement the feature request to allow passing multiple directories?

**Comment by ibhagwan** [comment]
You can easily do this with `fd` (install it first) and then craft your command as follows:
```lua
:lua require("fzf-lua").files({ cmd = 'fd . path1 path2 path3' })
-- in your case
:lua require("fzf-lua").files({ cmd = 'fd . ' .. table.concat(vim.g.rg_in, ' ') })
```
> make sure to add other `fd` arguments you need (ignore .git, etc)

**Comment by yangmillstheory** [comment]
Is there a way to get the other default options and UI when using the raw
command, or do I have to write it myself?

Also why use fd for files? Why not rg?

**Comment by ibhagwan** [comment]
> Is there a way to get the other default options and UI when using the raw command, or do I have to write it myself?
> […](#)

You do get the default options when using `cmd`, it just replaces the underlying command, you can still override any default option if you send it to the command as well, read the README and wiki.

> Also why use fd for files? Why not rg?

You can use whatever you wish, I just gave you an option for multiple folders, in general `rg` is better at grep’I got but `fd` is a specialized `find` replacement better at finding files within folders.

**Comment by yangmillstheory** [comment]
I think it would be best if the FR were implemented. It's a simple use case and it takes a lot of time and energy to figure hack around the API to make it work otherwise. Thanks for your help though.

**Comment by ibhagwan** [comment]
> I think it would be best if the FR were implemented. It's a simple use case and it takes a lot of time and energy to figure hack around the API to make it work otherwise. Thanks for your help though.

I respectfully disagree, if you read the docs and the wiki and understand how the plug-in works and it’s integration with fzf and the shell this request is quite basic, the plug-in already has way too many customization options and does way more than fzf.vim out of the box without having to understand anything.

Sending a custom `cmd` to fzf isn’t a “hack” but a feature and IMHO doesn’t take lots of time and energy.

**Comment by ibhagwan** [comment]
Closing, if you’re still struggling with this feel free to reopen.
