### ISSUE TITLE
[Enhancement] add a space after the chosen command for `:FzfLua command`

### ISSUE THREAD

**Issue by SichangHe** [ibhagwan/fzf-lua#684]
Please add a space after choosing a command using `:FzfLua`. I need to type it out every time anyway.

Thanks.

**Comment by ibhagwan** [comment]
Why don’t you `cnoreabbrev` it in your config?

**Comment by SichangHe** [comment]
Because I don't know how that works. Also, it would be a nice default as Fzf.vim has it.
