### ISSUE TITLE
Hide line number from buffers

### ISSUE THREAD

**Issue by adriafarres** [ibhagwan/fzf-lua#685]
Hello,

First, thanks for this plugin. It looks very complete, and has been very useful. I have been trying to remove the line number that appears with the `buffers()` command to no avail. Basically, instead of seeing

```
some/file:123
```

I would like to see

```
some/file
```

The `--delimiter` and `--with-nth` options of fzf can't be used, because they include the delimiter at the end. Basically, `--delimiter : --with-nth 1` displays

```
some/file:
```

Is there any way to solve this? What would be the best way? Would it be possible with `fn_transform`?

Thanks again

**Comment by ibhagwan** [comment]
Using `--with-nth` is the best option, but as you discovered it won't hide the `:`:
```lua
:lua require("fzf-lua").buffers({fzf_opts={["--with-nth"]="..-2"}})
```

> Is there any way to solve this? What would be the best way? Would it be possible with fn_transform?

`fn_transform` doesn't get called here, it's used when you wish to transform the output of a shell command, not with exisiting providers.

I can pretty quickly add a variable to not print the line number but that would have the unintended consequence of setting the cursor to line `1` when switching between buffers, that would mean that I also need to adjust the `buf_edit` action to discern between buffers with lines and without, TBH I don't think it's worth it for the minor inconvineince of having an extra `:` displayed.
