### ISSUE TITLE
Canceling the input of grep does works the same way as passing no input 

### ISSUE THREAD

**Issue by leiserfg** [ibhagwan/fzf-lua#686]
Here
https://github.com/ibhagwan/fzf-lua/blob/d666abc60fff12af9e91812666d42ff7f2555934/lua/fzf-lua/providers/grep.lua#L129

if the user closes the input the grep runs anyway,  which is a bit annoying. IMHO one should be allowed to abort the operation (by pressing escape or <C-c>), for an empty pattern it's still possible to hit enter.

**Comment by leiserfg** [comment]
@ibhagwan  Now that I check it works canceling with `<c-c>` but still does not work with `esc`, `utils.input` is returning `""` when using `esc` instead of returning `nil`. Is that intentional? If not I can make a pr to fix it.

**Comment by ibhagwan** [comment]
Sure, PR if you can fix it, not sure if possible as perhaps this was the reason I left it this way to begin with, the main reason I used it was to avoid the exception when using ctrl-c to interrupt.

**Comment by leiserfg** [comment]
It's doable, the issue is that in

https://github.com/ibhagwan/fzf-lua/blob/d666abc60fff12af9e91812666d42ff7f2555934/lua/fzf-lua/utils.lua#LL762C48-L762C57
When vim.ui.input ends (after pressing `esc`) the `nil` it returns is replaced by `""`, that's what I don't know if is intentional (like it's in another part that is required, I think it should not be, IMHO if a value is required then a value for `text` should be passed.

**Comment by leiserfg** [comment]
I see!, you are using `vim.fn.input`, instead of `vim.ui.input`, which is why canceling is not handled correctly (as `vim.fn.input` always returns something). Is there any reason not to use  `vim.ui.input` ?

**Comment by ibhagwan** [comment]
> I see!, you are using `vim.fn.input`, instead of `vim.ui.input`, which is why canceling is not handled correctly (as `vim.fn.input` always returns something). Is there any reason not to use `vim.ui.input` ?

That’s because this plug-in was created before 0.5 was officially released, there was no `vim.ui` back then and technically this plug-in still works with 0.5 (I still test it sometimes with it for fun) perhaps you can add a condition in `util.input` to check if vim.ui exists we can use the new function? I can do it too, lmk.

One day we can probably drop support for really old versions but I see no harm in continuing backward compatibility if it doesn’t over complicate the code.

**Comment by ibhagwan** [comment]
@leiserfg, I fixed it, `utils.input` now uses `vim.ui.input` and also handles the `Esc` use-case

https://github.com/ibhagwan/fzf-lua/commit/6ee73fdf2a79bbd74ec56d980262e29993b46f2b

**Comment by ibhagwan** [comment]
> I found a way to make `vim.fn.input` to handle `esc` in case you wanna make the util.input to work with old nvims you can do something as
> 
> ```lua
> local val = vim.fn.input({prompt=prompt, cancelreturn=3})
> ```
> 
> if `val == 3` ( a non string value) it means the input was cancelled.

Nice! I didn’t know that, feel free to PR it if you wish, I don’t think it’s that critical as nobody really uses anything under 0.7.2 anyways :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5d8dd500cc8c1cafbeffbdcc62dc87d8ec371e88

@leiserfg, FYI, had to revert the use of `vim.ui` for now due to a comment made by @kmac: https://github.com/ibhagwan/fzf-lua/commit/6ee73fdf2a79bbd74ec56d980262e29993b46f2b#commitcomment-105084946.

I added the above suggestion with `cancelreturn=3` but it doesn't cancel on `esc` on my end.

**Comment by leiserfg** [comment]
That's weird, I just updated and the change works for me (the `cancelreturn` thingy) btw, you don't have to use `3` there is nothing magic in the value :smile:.
I added a print locally to `utils.input`, like 

```lua
      ok, res = pcall(vim.fn.input, { prompt = prompt, cancelreturn = 3 })
    if res == 3 then
      print("cancelled")
      ok, res = false, nil
    end
```
and it printed as intended, I will check if it works for me because I'm using  `noice.nvim`.

**Comment by ibhagwan** [comment]
> you don't have to use 3 there is nothing magic in the value 😄

oh I know, I was I honoring your code :)

**Comment by leiserfg** [comment]
Feel free to use 420 or 69 instead :smile:

**Comment by leiserfg** [comment]
I think the problem with `vim.ui.input` is that you are using it as if it were blocking, which is the case in the default implementation, but is not mandatory. So in other implementations (like in [dressing.nvim](https://github.com/stevearc/dressing.nvim) ) it does not happen and the result is still `nil` when the call to `util.input` reaches the end.

**Comment by ibhagwan** [comment]
> I think the problem with `vim.ui.input` is that you are using it as if it were blocking, which is the case in the default implementation, but is not mandatory. So in other implementations (like in [dressing.nvim](https://github.com/stevearc/dressing.nvim) ) it does not happen and the result is still `nil` when the call to `util.input` reaches the end.

I guesses that too, I didn’t research enough how to try and figure out a non-blocking version.

**Comment by leiserfg** [comment]
It's easier to change until.input to be mimic the async API of the native ui.input

**Comment by ibhagwan** [comment]
> It's easier to change until.input to be mimic the async API of the native ui.input

Yes, but that will require more changes to the calling code as it assumes blocking input.

It really doesn’t bother me which API is used as long as it works.
