### ISSUE TITLE
How to append a line to the text using fzf-lua? & Other missing fzf.vim equivallents

### ISSUE THREAD

**Issue by doronbehar** [ibhagwan/fzf-lua#688]
Hello!

This plugin seems great! Seems to be designed much better then [junegunn/fzf.vim](https://github.com/junegunn/fzf.vim).. I am missing though a replacement to the following commands:

```vim
nmap <leader><tab> <plug>(fzf-maps-n)
```

`<plug>(fzf-maps-n)` allows you to choose with fzf all mappings and press them afterwards.

```vim
imap <expr> <c-x><c-f> fzf#vim#complete#path("find -maxdepth 1 -mindepth 1 -printf '%%P\n'")
```

Allows you to put in the edited file the output of the fzf selection of the command.

```vim
imap <c-x><c-l> <plug>(fzf-complete-line)
```

Allows you to choose with fzf a line from other files, to be copied to your currently edited file.

I'm sorry if this is trivial if one reads the documentation, but I searched it for a while and couldn't find an easy solution.

**Comment by ibhagwan** [comment]
> allows you to choose with fzf all mappings and press them afterwards.

`:FzfLua keymaps` - would that work?

> Allows you to put in the edited file the output of the fzf selection of the command.

There is no current provider that does exactly that but it can easily be recreated with `fzf_exec`:
```lua
:lua require'fzf-lua'.fzf_exec("find -maxdepth 1 -mindepth 1 -printf '%%P\n'")
```
Read [the advanced Wiki](https://github.com/ibhagwan/fzf-lua/wiki/Advanced) section about [keybind handlers](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#keybind-handlers) and add a default action inserting the text into the document, you can use `:help nvim_paste` for that.

> Allows you to choose with fzf a line from other files, to be copied to your currently edited file.

You can use `:FzfLua blines` with a custom action to paste into the document using `nvim_paste` above.

If you’ve just migrated from vim and new to lua and need some help with the code paste it below and I’ll do my best to help.

**Comment by doronbehar** [comment]
Wow thanks for the prompt reply! Much appreciated.

> > allows you to choose with fzf all mappings and press them afterwards.
> 
> `:FzfLua keymaps` - would that work?

Yes it does, thanks!

> There is no current provider that does exactly that but it can easily be recreated with `fzf_exec`:

I tried the following:

```nvim
lua << EOF
fzf = require'fzf-lua'
vim.keymap.set('i', '<c-x><c-f>', function()
  fzf.fzf_exec("ls", {
    actions = {
      ['default'] = {
        function(selected)
          vim.api.nvim_paste(selected[1])
        end
      }
    }
  })
end)
EOF
```

But it doesn't work - I press <kbd>Enter</kbd> and nothing happens...

**Comment by doronbehar** [comment]
OTH, if I write in that callback function `vim.fn.delete(selected[1])`, as in that example from the wiki it does indeed delete the file :/.

**Comment by ibhagwan** [comment]
Sorry about that, wiki is open edit for all, feel free to add a warning or modify the example to be safer.

**Comment by doronbehar** [comment]
> Sorry about that, wiki is open edit for all, feel free to add a warning or modify the example to be safer.

Oh it's OK! It was git tracked so no data was lost, I was aware of what might happen. The point is that `vim.fn.delete(selected[1])` works, and `vim.api.nvim_paste(selected[1])` doesn't.

**Comment by ibhagwan** [comment]
> > Sorry about that, wiki is open edit for all, feel free to add a warning or modify the example to be safer.
> 
> Oh it's OK! It was git tracked so no data was lost, I was aware of what might happen. The point is that `vim.fn.delete(selected[1])` works, and `vim.api.nvim_paste(selected[1])` doesn't.

`nvim_paste` accepts 3 arguments, use `vim.api.nvim_paste(selected[1], false, -1)`.

**Comment by ibhagwan** [comment]
@doronbehar, there's another issue in your code, you assigned a `table` (which contains a `function`) to the default action, that tells fzf-lua not to close the terminal after execution (usually used when `resume` is required).

I just tested this succesfully:
```lua
local fzf = require("fzf-lua")
fzf.fzf_exec("ls", {
  actions = {
    ['default'] = function(selected)
      vim.api.nvim_paste(selected[1], false, -1)
    end
  }
})
```

**Comment by doronbehar** [comment]
Thanks for your help, I ended up with something more sophisticated then that. It seems nontrivial to make `nvim_paste` put the text after the cursor, or to replace the line. Also `nvim_put` didn't work for me from some reason. I ended up using `vim.fn.setbufline`:

```lua
fzf = require('fzf-lua')
-- Useful if you debug these functions
--function shellinspect(var)
--  vim.fn.system("echo var is " .. vim.fn.shellescape(vim.inspect(var)) .. " >> dbg")
--end
FzfLuaCfileComplete = function(cfile)
  bufnr = vim.fn.bufnr('%')
  buflinenr = vim.fn.line('.')
  curpos = vim.fn.getcurpos()[3]
  cfile = cfile or ""
  cfile_expanded = vim.fn.expand(cfile)
  find_cmd = 'find ' .. vim.fn.shellescape(vim.fs.dirname(cfile_expanded)) .. ' -mindepth 1 -maxdepth 2'
  fzf.fzf_exec(find_cmd, {
    actions = {
      ['default'] = function(selected)
        line = vim.fn.getbufline(bufnr, buflinenr)[1]
        if cfile == "" then
          line_completed = line .. selected[1]
        else
          -- Special treatment to $HOME/ -> ~/ expansion likely done for cfile_expanded
          replacement = vim.fn.substitute(selected[1], os.getenv('HOME'), '~', '')
          line_completed = vim.fn.substitute(
            line,
            vim.fn.escape(cfile, '^$.*\\/~[]'),
            replacement,
            ''
          )
        end
        vim.fn.setbufline(bufnr, buflinenr, line_completed)
        vim.fn.cursor(buflinenr, curpos + string.len(selected[1]))
      end
    },
    fzf_opts = {
      ['--query'] = vim.fn.shellescape(cfile_expanded)
    },
    previewer = "builtin"
  })
end
vim.cmd([[inoremap <c-x><c-f> <esc>:lua FzfLuaCfileComplete('<C-R>=expand("<cfile>")<CR>')<CR>]])
vim.keymap.set('i', '<c-x><c-l>', function()
  bufnr = vim.fn.bufnr('%')
  buflinenr = vim.fn.line('.')
  curpos = vim.fn.getcurpos()[3]
  fzf.lines({
    actions = {
      ['default'] = function(selected)
        line_text = vim.fn.getqflist({
          efm = '%f:%l: %m',
          lines = selected
        }).items[1].text
        vim.fn.setbufline(bufnr, buflinenr, line_text)
        vim.fn.cursor(buflinenr, curpos + string.len(line_text))
      end
    },
    fzf_opts = {
      ['--query'] = vim.fn.shellescape(vim.fn.getbufline(bufnr, buflinenr)[1])
    }
  })
end)
```

I didn't imagine this little tweak will take me such a long time :sweat_smile:, but I'm satisfied. If you have any comments, I'd be happy to hear them. If not, I'll post this to the WiKi.

Your devotion to your users and to this plugin is observable both here and when reading the code as well. Thanks for creating it :green_heart:.

**Comment by ibhagwan** [comment]
> Your devotion to your users and to this plugin is observable both here and when reading the code as well. Thanks for creating it 💚.

Ty for your kind words @doronbehar!

> I didn't imagine this little tweak will take me such a long time 😅, but I'm satisfied. If you have any comments, I'd be happy to hear them. If not, I'll post this to the WiKi.

I also didn’t realize your need would end up with a bit more lines of code than I imagined, perhaps there is a real need here that I missed, users usually use `nvim-cmp` for completion (paths included) so I never really bothered looking into it but I’m almost sure there has to be a more elegant way of doing this, I’ll look into it and keep you posted :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/0bfae9b9552998f3be0e887bb4c154c8befd9809

@doronbehar, without discounting the solution you came up with, I added new completion functions that are a bit more tightly integrated and thus more robust, also added new [Completion functions section in the README](https://github.com/ibhagwan/fzf-lua#completion-functions-1).

To achieve what you wanted in the OP all you need to do is:
```lua
vim.cmd [[inoremap <c-x><c-f> <cmd>lua require("fzf-lua").complete_path({ cmd = "find -maxdepth 1 -mindepth 1 -printf '%P\n'" })<cr>]]
```

Or with the lua API:
```lua
vim.kepymap.set({ "n", "v", "i" }, "<C-x><C-f>",
  function()
    require("fzf-lua").complete_path({ cmd = "find -maxdepth 1 -mindepth 1 -printf '%P\n'" })
  end,
  { silent = true, desc = "Fuzzy complete path" })
```

Note that the completion works even when you're not in insert mode more akin to a replacement, the string is scanned backwards and forwards and the entire path is replaced with the result, I found it very convineint and it mimics (and enahnces a bit) the behavior of `fzf.vim`.

For buffer lines use `complete_line` and `complete_bline` respectively.

Try it out and lmk what what you think?

**Comment by sandangel** [comment]
Hi, I checked the docs. Maybe an example integration with nvim-cmp will help a lot of people. Let me give it a try

**Comment by ibhagwan** [comment]
> Hi, I checked the docs. Maybe an example integration with nvim-cmp will help a lot of people. Let me give it a try

This is not a replacement nvim-cmp nor is this an omni/complete function, this is the equivalent of fzf.vim’s functions: https://github.com/junegunn/fzf.vim#completion-functions

**Comment by ibhagwan** [comment]
> > Try it out and lmk what what you think?
> 
> This is certainly faster then my own solution! I think it'd be nice to add `previewer = "builtin"` by default for the `complete_path` function though. The `complete_line` function works great. Thanks a lot!

The builtin previewer is configured by default for `complete_file`  but starts hidden (made more sense for completion IMHO), press `F4` to unhindered it or use `winopts.preview.hidden` to start visible if you prefer.

 `complete_path` doesn’t have a previewer configured as it also displays folders and the previewer makes less sense this way, for all intents and purposes both functions are the same (albeit different default `cmd`), so just use `complete_file` if you need a previewer.

**Comment by ibhagwan** [comment]
> Great, thanks again!

Another difference is that `complete_file` displays icons (similar to `files`), look at all the default options in the README to configure it to your liking.
