### ISSUE TITLE
Using fn_transform with tags

### ISSUE THREAD

**Issue by leamingrad** [ibhagwan/fzf-lua#692]
### Description 

Would it be possible to allow the `fn_transform` option to fully integrate with the `tags` command?

### Detail

At the moment, there are a couple of issues as far as I can tell:
* The setting isn't respected at all if `multiprocessing = false`
* The output has already been formatted using `make_entry.tag` before it is passed to `fn_transform`

I've had a read through the code, and my understanding is that this is because the tags provider always sets `opts.__mt_transform` [here](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/tags.lua#L104-L109), which results in a transform that is applied before the result is passed to `fn_transform`.

Would it be possible to use `fn_transform` as `__mt_transform` (if it is provided), or to provide another setting that allows `__mt_transform` to be overridden?

I'm happy to put in a PR, but I am not sure what the intended behaviour is here.

### Context

The thing I would actually like to do is reformat the display of the elements in the tags command (from `<ICON> <FILE> <NAME> <TAG>` to `<ICON> <NAME> <FILE>`), but it seems like being able to do a general override would be more useful.

**Comment by ibhagwan** [comment]
> The thing I would actually like to do is reformat the display of the elements in the tags command (from <ICON> `<FILE> <NAME> <TAG>` to `<ICON> <NAME> <FILE>`), but it seems like being able to do a general override would be more useful.

I can pretty easily make the accomodation for you to overrride these but FYI, this will most likely create an issue with the previewer as well as the actions (goto tag, etc) as the code currently relies on certain order for parsing the entries, while fixable this may or may not require much more effort, for exmaple take a look at `btags` which uses `--with-nth` to hide the filename so the display shows just the tag name and pattern.

**Comment by leamingrad** [comment]
Thanks for the quick reply. That solution is definitely much easier - I didn't know about the `--with-nth` option.

I'm happy to close this issue unless you'd like to keep it open to track potentially making the larger change in the future.

**Comment by ibhagwan** [comment]
> Thanks for the quick reply. That solution is definitely much easier - I didn't know about the `--with-nth` option.
> 
> I'm happy to close this issue unless you'd like to keep it open to track potentially making the larger change in the future.

That’s great :)

No change to this functionality is planned ATM.
