### ISSUE TITLE
winopts_fn documentation isn't right

### ISSUE THREAD

**Issue by Diablo-D3** [ibhagwan/fzf-lua#693]
[The documentation](https://github.com/ibhagwan/fzf-lua/wiki#can-i-set-the-window-size-dynamically) indicates `winopts_fn` expects a [0.0, 1.0] range, however it seems to actually accept normal integers.

I do not consider this a bug in the implementation, as I'd rather actually use integer character cell counts instead of a range; given that, the documentation does not actually reflect whats going on.

**Comment by ibhagwan** [comment]
> [The documentation](https://github.com/ibhagwan/fzf-lua/wiki#can-i-set-the-window-size-dynamically) indicates `winopts_fn` expects a [0.0, 1.0] range, however it seems to actually accept normal integers.
> 
> I do not consider this a bug in the implementation, as I'd rather actually use integer character cell counts instead of a range; given that, the documentation does not actually reflect whats going on.

This is a “feature” not a bug, it accepts both, when normal integers are used it will use absolute positioning on the screen, when floats are used it automatically calculates the relative position on the screen, the Wiki is open edit, feel free to add a clarification if you feel like it :)

**Comment by Diablo-D3** [comment]
Done.

**Comment by ibhagwan** [comment]
> Done.

Ty @Diablo-D3 !
