### ISSUE TITLE
btags output should not be sorted alphabetically but in order to appearance

### ISSUE THREAD

**Issue by adriafarres** [ibhagwan/fzf-lua#694]
### Info

- Operating System: Linux
- Shell: zsh
- Terminal: kitty
- `nvim --version`: v0.8.3
- `fzf --version`: 0.38.0

- [X ] The issue is reproducible with `mini.sh`

### Description 
`btags()` should order the output by order of appearance instead of alphabetically. Would that be possible?

Thank you

**Comment by ibhagwan** [comment]
> `btags()` should order the output by order of appearance instead of alphabetically. Would that be possible?

btags order output is dependent on the order inside the tags file or **if no tags file is present** fzf-lua will generate one using the command `ctags -f - <file>`, can you try with `--sort=no` or `-u`:
```lua
:lua require'fzf-lua'.btags({ ctags_args = '-u -f -' })
:lua require'fzf-lua'.btags({ ctags_args = '--sort=no -f -' })
```
If you’re using a pre generated ctags file make sure to add sort flags before generating it.

**Comment by adriafarres** [comment]
Works, thanks! And thank you for being so responsive to everyone opening issues or questions.
