### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by travatomic** [ibhagwan/fzf-lua#697]
### Info

- Operating System: MacOS
- Shell: zsh
- Terminal: Kitty
- `nvim --version`: 
```
❯ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

- `fzf --version`:  zsh: command not found: fzf
I didn't install fzf globally, I'm loading fzf via:
```lua
  {
    'junegunn/fzf',
    run = './install --bin'
  },

```

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
return {
  {
    'junegunn/fzf',
    run = './install --bin'
  },

  {
    'ibhagwan/fzf-lua',
    dependencies = {
      'junegunn/fzf',
      'nvim-tree/nvim-web-devicons',
    },
    config = function()
      local fzflua = require('fzf-lua')
      local utils = require('fzf-lua').utils

      local function hl_validate(hl)
        return not utils.is_hl_cleared(hl) and hl or nil
      end

      local map = vim.keymap.set
      local opts = { noremap = true, silent = true }

      map('n', '<leader><space>', function() fzflua.buffers() end, opts)
      map('n', '<leader>ff', function() fzflua.files() end, opts)
      map('n', '<leader>fg', function() fzflua.live_grep() end, opts)
      map('n', '<leader>fd', function() fzflua.git_status() end, opts)

      fzflua.setup({
        winopts    = {
          border     = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
          fullscreen = true,
          hl         = {
            normal       = hl_validate 'TelescopeNormal',
            border       = hl_validate 'TelescopeBorder',
            help_normal  = hl_validate 'TelescopeNormal',
            help_border  = hl_validate 'TelescopeBorder',
            -- builtin preview only
            cursor       = hl_validate 'Cursor',
            cursorline   = hl_validate 'TelescopePreviewLine',
            cursorlinenr = hl_validate 'TelescopePreviewLine',
            search       = hl_validate 'IncSearch',
            title        = hl_validate 'TelescopeTitle',
          },
        },
        fzf_colors = {
              ['fg'] = { 'fg', 'TelescopeNormal' },
              ['bg'] = { 'bg', 'TelescopeNormal' },
              ['hl'] = { 'fg', 'TelescopeMatching' },
              ['fg+'] = { 'fg', 'TelescopeSelection' },
              ['bg+'] = { 'bg', 'TelescopeSelection' },
              ['hl+'] = { 'fg', 'TelescopeMatching' },
              ['info'] = { 'fg', 'TelescopeMultiSelection' },
              ['border'] = { 'fg', 'TelescopeBorder' },
              ['gutter'] = { 'bg', 'TelescopeNormal' },
              ['prompt'] = { 'fg', 'TelescopePromptPrefix' },
              ['pointer'] = { 'fg', 'TelescopeSelectionCaret' },
              ['marker'] = { 'fg', 'TelescopeSelectionCaret' },
              ['header'] = { 'fg', 'TelescopeTitle' },
        },
      })
    end
  }
}
```
</details>

### Description 

I'm trying out fzf-lua instead of telescope. So far, I'm loving it.

One thing I would really like to replicate is making files matching `*_spec.rb` have a different icon than `*.rb`. This helps me quickly visually distinguish tests from production code.

I have monkeypatched nvim-web-devicons to make this possible for anything that calls `require('nvim-web-devicons').get_icon` and `require('nvim-web-devicons').get_icon_colors`. This worked in telescope (and a few other plugins), but doesn't seem to work in fzf-lua. 

I found these two lines in the fzf-lua source, which may be relevant: https://github.com/ibhagwan/fzf-lua/blob/79a74aebab4cd5fca460c61dc47e5e1d7a54b01e/lua/fzf-lua/make_entry.lua#L178-L179

My assumption is that on my machine, this is resolving to false, and it's using the icon map on L180 instead.

Do you know a way I can get fzf-lua to use my monkeypatched `require('nvim-web-devicons').get_icon/get_icon_colors`? Open to any ideas.

**Comment by ibhagwan** [comment]
The reason this doesn’t work in some providers in fzf-lua (I bet it works in ‘lines` or `buffers` for example) is because all the processing heavy providers, such as `files` and `grep` variants are running in a totally independent external neovim process (for performance considerations).

Fzf-lua maintains its own icon set copy retrieved by the external process (over RPC):
https://github.com/ibhagwan/fzf-lua/blob/79a74aebab4cd5fca460c61dc47e5e1d7a54b01e/lua/fzf-lua/config.lua#L19

The map is then queried directly (`devicons.get_icon` isn’t used):
https://github.com/ibhagwan/fzf-lua/blob/79a74aebab4cd5fca460c61dc47e5e1d7a54b01e/lua/fzf-lua/make_entry.lua#L181

In order to achieve what you want you’d need to patch this part of the code **on the disk** as this gets called from an external neovim headless process.

**Comment by ibhagwan** [comment]
Closing, lmk if you need more help.
