### ISSUE TITLE
Manipulating the default sorting order of code actions

### ISSUE THREAD

**Issue by alextes** [ibhagwan/fzf-lua#699]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: kitty
- `nvim --version`: v0.9.0-dev-3891+g27b467bad-dirty
- `fzf --version`: 0.38.0 (brew)

### Description 

Loving the plugin ❤️ . Amazing defaults.

So the challenge I'm experiencing is that the default sorting of code actions is not great for me. Now, why would you care when you have fzf right there?
1. Because if the "top" action is the one I'm looking for, all I need to do is hit <kbd>return</kbd>.
2. I have a script that picks the "top" action and applies it without ever opening the code action selection window.  ... hmm, as I'm writing this I'm realizing I can just update that function. I'll do that. But 1. still stands. As editor suggestions get more powerful 1. seems more and more useful.

Screenshot showing an example where tsserver is giving a useful suggestion, and null-ls is drowning it out with completely useless suggestions. Disabling a lint rule for a whole file is _rare_, but it's the best eslint has. Either way, the LSP should almost always come before the "fake" LSP. Having a custom sorting function would be 🤩 . (or I'd prefer a better default but that seems intractable here).

<img width="1190" alt="Screenshot 2023-03-24 at 10 06 46" src="https://user-images.githubusercontent.com/2011351/227474718-25225102-6425-4f08-ba10-2400f4ce289a.png">

### Prior research
* `null-ls` can't help here: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/630
* others have posted about this on [reddit](https://www.reddit.com/r/neovim/comments/w1x13l/is_it_possible_to_change_the_order_of_items_in/)

**Comment by alextes** [comment]
Put together a neat fn to select the correct quickfix now if anyone is curious:

```lua
local function run_action(action, offse)
	if action.edit or type(action.command) == "table" then
		if action.edit then
			vim.lsp.util.apply_workspace_edit(action.edit, offse)
		end
		if type(action.command) == "table" then
			vim.lsp.buf.execute_command(action.command)
		end
	else
		vim.lsp.buf.execute_command(action)
	end
end

local function do_action(action, client)
	if
		not action.edit
		and client
		and type(client.server_capabilities) == "table"
		and client.server_capabilities.resolveProvider
	then
		client.request("codeAction/resolve", action, function(err, real)
			if err then
				return
			end
			if real then
				run_action(real, client.offset_encoding)
			else
				run_action(action, client.offset_encoding)
			end
		end)
	else
		run_action(action, client.offset_encoding)
	end
end

return function()
	local params = vim.lsp.util.make_range_params() -- get params for current position
	params.context = {
		diagnostics = vim.lsp.diagnostic.get_line_diagnostics(),
		only = { "quickfix" },
	}

	local actions_per_client, err = vim.lsp.buf_request_sync(
		0,                   -- current buffer
		"textDocument/codeAction", -- get code actions
		params,
		900
	)

	if err then
		return
	end

	if actions_per_client == nil or vim.tbl_isempty(actions_per_client) or #actions_per_client == 0 then
		vim.notify("no quickfixes available")
		return
	end

	-- Collect the available actions
	local actions = {}
	for cid, resp in pairs(actions_per_client) do
		for _, result in pairs(resp.result) do
			-- add the actions with a cid to the table
			local action = {}
			action["cid"] = cid
			for k, v in pairs(result) do
				action[k] = v
			end
			table.insert(actions, action)
		end
	end

	-- Find the top action
	local top_action = nil

	-- Using null-ls a lot of quickfixes are returned but all tend to be
	-- worse than what the real LSP is offering, we try to use other
	-- actions first, then only fall back to whatever null-ls is offering.
	for _, action in ipairs(actions) do
		print(vim.inspect(action))
		if action.command ~= "NULL_LS_CODE_ACTION" then
			top_action = action
			break
		end
	end

	if top_action == nil then
		top_action = actions[1]
	end

	do_action(top_action, vim.lsp.get_client_by_id(top_action.cid))
end
```

**Comment by ibhagwan** [comment]
Hi @alextes,

The LSP code actions and their order isn’t controlled by fzf-lua, we only use fzf-lua as the UI for `vim.ui.select` and call:
https://github.com/ibhagwan/fzf-lua/blob/79a74aebab4cd5fca460c61dc47e5e1d7a54b01e/lua/fzf-lua/providers/lsp.lua#L839

And the rest is controlled by neovim.

In fact, there used to be an older way of querying the LSP directly but it was recently deprecated in https://github.com/ibhagwan/fzf-lua/commit/a81d18ee591635ce537bfa045ed1edf7dbe30cf3, it’s redundant and not reliable.

While I appreciate your valiant effort here IMHO it’s not worth the effort :)

**Comment by alextes** [comment]
Clear, I'll make my way over to the nvim repo then 👍 .

**Comment by ibhagwan** [comment]
> Clear, I'll make my way over to the nvim repo then 👍 .

Not sure what your final goal is but if it’s just putting `null-ls` code actions last I would try to control the LSP client attachment order instead (I.e. make sure `null-ls` is attached after the actual LSP client).

**Comment by alextes** [comment]
@ibhagwan that works just fine 🙈 😂 .

Thanks so much!
