### ISSUE TITLE
Configuration idea

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#7]
How would you feel about making configuration not global as it is now, I mean something resembling snap's. Reason why I am asking is because I want to adjust size of floating window depending on size of nvim itself. I am not talking about percentages of window but different values depending on main window's size.

At the moment it seems like whatever gets set up during setup() call just stays.

Also, for some reason that takes up the whole screen (this is code without conditional values for different screen sizes):

```lua
win_width = math.floor(vim.o.columns - (vim.o.columns * 2 / 5)),
win_height = math.floor(vim.o.lines - (vim.o.lines * 1 / 3)),
```

**Comment by ibhagwan** [comment]
Currently the code is indeed percentage of columns and lines, however you can set `winopts` per provider, take a look at how I set the `colorscheme` provider to a much smaller window. As you can see below it has it's own winopts structure with different values (as well as s callback to reset my statusline colors).

Let me know if this is not sufficient and we will work something out.

```lua
colorschemes = {
    prompt            = 'Colorschemes❯ ',
    live_preview      = true,
    actions = {
      ["default"]     = actions.colorscheme,
      ["ctrl-y"]      = function(selected) print(selected[2]) end,
    },
    winopts = {
      win_height       = 0.55,
      win_width        = 0.30,
      window_on_create = function()
        vim.cmd("set winhl=Normal:Normal")
      end,
    },
    post_reset_cb    = function()
      require('feline').reset_highlights()
    end,
  },
```

**Comment by gegoune** [comment]
Thanks for doing back with that suggestion, unfortunately that will not work for my use case. Apologies if I wasn't clear enough earlier.

What I want is something like this:

```lua
  local width = math.floor(columns - (columns * 2 / 5))
  local height = math.floor(lines - (lines * 1 / 3))

  -- Increse size in smaller terminal windows.
  if columns < 120 then
    width = math.floor(columns - (columns * 1 / 5))
  end
```

That is currently not possible. And what I mean is that it will never change after initial `setup()` call, will it?

**Comment by gegoune** [comment]
`win_opts_raw` solves it! :) Thanks!

**Comment by ibhagwan** [comment]
You already saw it lol, I wanted to send you a completed function based on your numbers, I just tested this and it works :-)

```lua
  winopts_raw = function()
    local width = math.floor(vim.o.columns * 0.60)
    local height = math.floor(vim.o.lines * 0.65)
    local row = math.floor((vim.o.lines - height) * 0.50)
    local col = math.floor((vim.o.columns - width) * 0.50)

    print(width, height, row, col)

    -- Increse size in smaller terminal windows.
    if vim.o.columns < 120 then
      -- width = math.floor(vim.o.columns * 0.85)
    end

    return {
      height = height,
      width = width,
      row = row,
      col = col,
      border = true,
      window_on_create = function() end
    }
  end
```

**Comment by gegoune** [comment]
Haha, indeed, do you think there would be nice solution, or if you would want to do that at all, to still applying `window_on_create` separately to `winopts_raw`? I am reusing function that generates those parameter in there plugins and having `window_on_create` in there does not feel right as it is not one of expected parameters.

One solution I see is extracting passed parameters here

https://github.com/ibhagwan/fzf-lua/blob/1cb4ae1b0ed62e127ed206c55aed181a80bfe48f/lua/fzf-lua/config.lua#L260

so it could become

```lua
  local raw = {}
  if opts.winopts_raw and type(opts.winopts_raw) == "function" then
    raw =  opts.winopts_raw()
  end

  local height = raw.height or math.floor(vim.o.lines * opts.win_height)
  local width = raw.width or math.floor(vim.o.columns * opts.win_width)
  local row = raw.row or math.floor((vim.o.lines - height) * opts.win_row)
  local col = raw.col or math.floor((vim.o.columns - width) * opts.win_col)
  local border = raw.border or opts.win_border

  return {
    -- style = 'minimal', -- pass style along from raw as well
    height = height, width = width, row = row, col = col,
    border = border,
    window_on_create = opts.window_on_create
  }
end
```

Above code can most likely be improved, just a sketch to give you an idea what I am thinking about.

**Comment by ibhagwan** [comment]
It's a great idea, I added it as well as the options to use it's `border` and `window_on_create` vars.

**Comment by gegoune** [comment]
Ha, awesome, it works, I did not test that code, so you might want to be bit careful there. :)

Also, just have noticed that parameters passed set up function are bit disorganised. How about grouping them into tables to give some structures and remove uglyish `_` from their names?

And another point, global prompt's suffix setting? Would allow (together with above suggestion) something like:
```lua
require("fzf-lua").setup {
  ui = {
   suffix = '> ', 
  },
  commands = {. -- Snap calls them `providers` afair
    files = { prompt = "Files" },
    grep = { prompt = "Rg" },
  }
}
```

Names and structure are just suggestions to illustrate the idea.

**Comment by ibhagwan** [comment]
>Ha, awesome, it works, I did not test that code, so you might want to be bit careful there. :) 

It was a very simple addition but I tested it nonetheless :)

>Also, just have noticed that parameters passed set up function are bit disorganised. How about grouping them into tables to give some structures and remove uglyish _ from their names?

Probably not a bad idea, I’m gonna let it run like this for a while until I finish all the other providers and maybe collect more used input along the way, when the product is more complete it will probably be easier to decide on a proper convention, I’d hate to introduce breaking changes on day one.
