### ISSUE TITLE
E5108: Error executing lua ...nfig/nvim/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:248: ...nfig/nvim/pack/packer/start/fzflua/lua/fzf-lua/core.lua:98: table index is nil

### ISSUE THREAD

**Issue by ahmedelgabri** [ibhagwan/fzf-lua#70]
Following up on https://github.com/ibhagwan/fzf-lua/issues/59#issuecomment-907883990

I'm still getting 

```
E5108: Error executing lua ...nfig/nvim/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:248: ...nfig/nvim/pack/packer/start/fzflua/lua/fzf-lua/core.lua:98: table index is nil
Press ENTER or type command to continue
```

**Comment by ibhagwan** [comment]
I lost track of this because it was discussed in a totally different issue, so just to iterate, this happens only when running inside the encrypted repo correct?

Does it work when you disable `git_icons`? you can quickly test that with:

```lua
:lua require('fzf-lua').files({ git_icons = false })
```

**Comment by ibhagwan** [comment]
Also, can you please provide me with a sample output of the command `git diff --name-status --relative HEAD` run inside your encrypted repository with a few modified files?

The regex you provided on the other issue (`/^(M|U|D|A|R)\s(.*)/g`) might work but unfortunately lua does not support regex and instead has it's own version of regex like pattern matching, I'll have to convert to lua-regex and make sure it works before I commit this.

**Comment by ahmedelgabri** [comment]
> this happens only when running inside the encrypted repo correct?

yes, correct.



> Does it work when you disable `git_icons`? you can quickly test that with:
> 
> ```lua
> :lua require('fzf-lua').files({ git_icons = false })
> ```

This runs fine



> Also, can you please provide me with a sample output of the command `git diff --name-status --relative HEAD` run inside your encrypted repository with a few modified files?

```
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
M       config/.ssh/config
M       config/nvim/lua/_/config/telescope.lua
M       config/nvim/lua/_/packer.lua
M       config/weechat/sec.conf
M       nix/hosts/pandoras-box.nix
M       nix/modules/shared/shell.nix
```

**Comment by ibhagwan** [comment]
Just committed a fix, update your plugin and let me know if this works for you?

**Comment by ahmedelgabri** [comment]
It works fine now

**Comment by ibhagwan** [comment]
Great! I'll have a fix for your other issue very soon, just testing.
