### ISSUE TITLE
Support reading ctag file from tags option

### ISSUE THREAD

**Issue by hvarga** [ibhagwan/fzf-lua#700]
### Info

- Operating System: Manjaro Linux
- Shell: zsh
- Terminal: GNOME Terminal
- `nvim --version`: 0.8.1
- `fzf --version`: 0.38.0 (352ea07)

### Description 

fzf-lua has a configuration option called `ctags_file` under the `tags` section which holds a path to a file generated by the ctags. This is an input file to the `tags` command which is used to search project tags.

While this works without any issues, the path is hard coded into the configuration of the fzf-lua. It would be beneficial if this is read from the Neovim tags option similar to how the original junegunn/fzf.vim does. It will make fzf-lua play nice with other Neovim plugins, like vim-gutentags, that are used to automatically generate tags file.

Seems like fzf-lua is the best Neovim plugin to integrate fzf and I would really love to use the fzf-lua in my setup, but this is the only blocker for me to do so.

A bit of more context as to why this is a deal breaker for me. I am using already mentioned vim-gutentags which provides me with the following:

- I don't need to worry about ctags since vim-gutentags automatically generates tags file for me on every change that I do in the files.
- I have configure it to not "pollute" a directory for each project and instead generate tags file in my `$HOME`.

The first point is without a doubt indispensable, but the second point is what is blocking me to use fzf-lua. While I can configure vim-gutentags to generate tags in each project directory (this is actually the default behavior) so that fzf-lua and vim-gutentags play nice, I really much prefer to generate the tags file in my `$HOME` instead. The problem with such configuration is that the name of the tags file is not static anymore, but rather dynamic (the name of the tags file depends on the project folder name). This obviously means that I can't use `ctags_file` configuration option to specify a file name. Fortunately, the vim-gutentags (once tags is generated) updates the tags Neovim option with the path to this generated ctags file. So, fzf-lua could actually read the tags option value and use it to open tags file. 

I would really like your thoughts on this. I am aware that this is a feature request and probably would have a lower priority then the actual issues or maybe even with any other features you are doing or planning to do. It would be good to know that at least you are not against the feature. I am even open to implement this myself if this is OK for you.

**Comment by ibhagwan** [comment]
> I would really like your thoughts on this. I am aware that this is a feature request and probably would have a lower priority then the actual issues or maybe even with any other features you are doing or planning to do. It would be good to know that at least you are not against the feature. I am even open to implement this myself if this is OK for you.

Ty for the detailed request, I am not against this at all and I’m sure I can accommodate this pretty quick.

I’m not at the computer ATM, which option saves the tag file location?

**Comment by hvarga** [comment]
> I’m not at the computer ATM, which option saves the tag file location? Also would be helpful is an example of what the option contains (absolute path, relative? multiple paths?)

Just want to clarify that the `tags` option and tag functionality in general is part of the Neovim itself. It has nothing to do with the vim-gutentags. It allows user to easily jump all the places instead of a raw searching and hunting for the symbols. vim-gutentags just updates this option with the path to the tags file that it generated so that Neovim can use it to jump places. More about the tags is described in the `help tags`

Back to your question, Neovim calls this  `tags` option. It is described in the `tags-option` section in the Neovim documentation. See `help tags-option` for more details.

> The 'tags' option is a list of file names.  Each of these files is searched
for the tag.  This can be used to use a different tags file than the default
file "tags".  It can also be used to access a common tags file.

`tags` option contains a list of files separated by comma. An example of `tags` option value:

```
:set tags=./tags,tags,/home/user/commontags
```

See below to give you more info on how my setup works where I use vim-gutentags.

I have a `workspace` folder which contains all my projects.

```
$ pwd
/opt/workspace
```

For example:

```
$ ll
total 24K
drwxr-xr-x 11 developer developer 4.0K Mar 25 08:04 fzf
drwxr-xr-x 28 developer developer  20K Mar 25 08:05 git
```

So if I want to work on fzf, I position myself into `/opt/workspace/fzf` and fire up Neovim which will trigger vim-gutentags to automatically generate tags file for the whole fzf project. The tags, as described in the description of this issue, will be generated in the `$HOME` folder:

```
$ ll ~/.cache/vim/ctags/opt-workspace-fzf-tags
-rw-r--r-- 1 developer developer 326K Mar 25 08:13 /home/developer/.cache/vim/ctags/opt-workspace-fzf-tags
```

Note the name of the tags file `opt-workspace-fzf-tags` in above listing. The name is a concatenation of the absolute path to the project folder with a dash separator and the project directory itself.

Back to the Neovim, If I now run `set tags?` I will get the following value:

```
tags=~/.cache/vim/ctags/opt-workspace-fzf-tags,./tags;,tags
```

But if I now switch to git project and run `set tags?` from Neovim I will get:

```
tags=~/.cache/vim/ctags/opt-workspace-git-tags,./tags;,tags
```

With such setup, Neovim will always open the right tags file and tag jumping will work as expected.

**Comment by ibhagwan** [comment]
Tysm for the detailed explanation @hvarga.

One more question @hvargal, in your specific example let’s say for fzf, would it be enough to extract the tags from `~/.cache/vim/ctags/opt-workspace-fzf-tags` or do you need to search tags in all 3 files `~/.cache/vim/ctags/opt-workspace-git-tags,./tags;,tags`?

Does `fzf.vim` search the project specific generated file (the first file in `tags`), or all?

**Comment by ibhagwan** [comment]
@hvarga, I looked at how `fzf.vim` does it, it uses the vim function `getfiles()` to get a list of resolved tag files.

https://github.com/ibhagwan/fzf-lua/commit/ba5950e884f89b58de287ca77a76bc8a92a5de1e - this commit removes the hardcoded tags file and uses the first exisiting file from the `tagfiles()` command and `tags` file (hardcoded) as last resort.

I looked into combining the results from all tagfiles but that requires a bigger change as the tags file relies on grep'ing the tags file (one file).

Try it and lmk if this if this solves your issue?

**Comment by hvarga** [comment]
Wow, OK that was quick. I will try this during the day and let you know.

**Comment by ibhagwan** [comment]
> Wow, OK that was quick. I will try this during the day and let you know.

I'm usually faster, this took a day :-)

**Comment by hvarga** [comment]
I am happy to report that your commit is working as expected.

> commit removes the hardcoded tags file and uses the first exisiting file from the tagfiles() command and tags file (hardcoded) as last resort.

Good, this is what I as a user, would expect as well.

> I looked into combining the results from all tagfiles but that requires a bigger change as the tags file relies on grep'ing the tags file (currently just one file).

No worries about that, at least if you ask me. I don't have a use case that requires "multi-stage" tags files.

I can finally integrate fzf-lua into my hvarga/tuosde-docker. Thanks for this @ibhagwan.

**Comment by ibhagwan** [comment]
That’s great @hvarga, ty for the update!

**Comment by hvarga** [comment]
@ibhagwan, seems like there is still some hard coded path to a tags file. By using "Regex Search" in the `FzfLua tags` view, the following error will be shown:

```
[Fzf-lua] Tags file ('tags') does not exist. Create one with ctags -R
```

The reason I haven't caught this earlier during the testing of your commit is that I haven't used the regex search.

Can you check this out as well?

**Comment by ibhagwan** [comment]
Hi @hvarga,

I'm a bit confused where this is coming from, the `tags_live_grep` (and variants) code uses the exact same code path, there's only one line where hardcoded `tags` can come from (as fallback of last resort, line 59):
https://github.com/ibhagwan/fzf-lua/blob/11225b76a41ae59bd52307c64862e13b12de50ef/lua/fzf-lua/providers/tags.lua#L49-L60

I just ran mine with debug using `:FzfLua tags_live_grep debug=true`, you can see the underlying command does use the correct path:
![image](https://user-images.githubusercontent.com/59988195/227771678-ea7407b9-ac76-4e66-bdd6-fb718335ae8f.png)

Does this happen when you run `tags_live_grep` directly or when using `ctrl-g` to switch back and forth between fuzzy and regex (I tried both, mine seems to work)?

**Comment by hvarga** [comment]
> Does this happen when you run tags_live_grep directly or when using ctrl-g to switch back and forth between fuzzy and regex (I tried both, mine seems to work)?

No, not immediately when I run `tags_live_grep`. Only when I press `ctrl-g`. Unfortunately, adding `debug=true` to the command doesn't provide any additional observability. I still end up with only the:

```
[Fzf-lua] Tags file ('tags') does not exist. Create one with ctags -R
```

printed at the bottom of my Neovim.

**Comment by ibhagwan** [comment]
Nope you're not missing anything, and the  messages is very clear, somehow your `ctags_file` still remains set to `tags` and given that it works without the `ctrl-g` I'm a struggling to find the source of this issue...

Pretty sure this isn't the issue but can you confirm your fzf-lua commit hash so we can rule this one out?

**Comment by ibhagwan** [comment]
Also what happens when you start with `tags_live_grep` and then press `ctrl-g` does the same message still appears or can you switch to fuzzy mode?

**Comment by ibhagwan** [comment]
Actually I think I figured out this issue, with your setup (most probably) calling `tagfiles()` from the float window returns the wrong (or not a valid tag file in the tags-option), https://github.com/ibhagwan/fzf-lua/commit/02bde5fae96772729004743f0f309c35c5182b83 - this commit stores the resolved `ctags_file` in between mode changes.

Can you updated to the latest commit and lmk if this solves your issue?

**Comment by hvarga** [comment]
Yes, that did the trick - I can confirm that with your latest commit the switching between regex and fuzzy search now works as expected. Thanks again @ibhagwan for your support.

**Comment by fannheyward** [comment]
Hello all, my `echo tagfiles()` is `['.tags']`, a hidden file with `.` prefix, `vim.fn.expand(f)` is nil.

**Comment by ibhagwan** [comment]
> prefix, `vim.fn.expand(f)` is nil.

What do you mean by this? I just tried `:lua print(vim.fn.expand(".tags"))` and it returns `.tags` as expected.

**Comment by fannheyward** [comment]
In my tests, `print(vim.loop.fs_stat(vim.fn.expand('.tags')))` is `nil, ENOENT: no such file or directory:  ENOENT`

**Comment by ibhagwan** [comment]
> In my tests, `print(vim.loop.fs_stat(vim.fn.expand('.tags')))` is `nil, ENOENT: no such file or directory: ENOENT`

How have you generated the tags?
Does `.tags` exist in your current directory?
What does `:!ls .tags` output?

**Comment by fannheyward** [comment]
```
:!ls .tags
.tags
```

`.tags` exist in project root.

**Comment by ibhagwan** [comment]
Very confusing why does `fs_stat` fail…

Does `print(vim.loop.fs_stat('.tags'))` work (without `expand`)?
Does `print(vim.loop.fs_stat('/full/path/to/.tags'))` work (replace with your path)?

**Comment by fannheyward** [comment]
- `:lua print(vim.fn.expand('.tags'))`, nothing
- `:lua print(vim.loop.fs_stat('.tags'))`, `table 0x01025330a0`, `vim.inspect` prints the details
- `:lua print(vim.loop.fs_stat('/full/path/to/.tags'))`, works as expected 

The main issue is `vim.fn.expand('.tags')` is nil, can you reproduce this?

**Comment by fannheyward** [comment]
`:lua print(vim.fn.expand('/Users/fannheyward/.local/share/nvim/plugged/fzf-lua/.tags'))`, full path, still nothing

**Comment by ibhagwan** [comment]
> The main issue is vim.fn.expand('.tags') is nil, can you reproduce this?

Can’t reproduce, what neovim version are you using? Perhaps an upstream bug?

In any event, the workaround is easy, I’ll commit a it soon.

**Comment by ibhagwan** [comment]
@fannheyward, can you try this commit https://github.com/ibhagwan/fzf-lua/commit/d49f79fbdaf5247ce694637555e8cd503f6fc05f and lmk if this solves your issue?

It seems the result is already expanded anyways, from `:help tagfiles()`:
```help
tagfiles()	Returns a |List| with the file names used to search for tags
		for the current buffer.  This is the 'tags' option expanded.

```

**Comment by fannheyward** [comment]
@ibhagwan sorry for the delay, https://github.com/ibhagwan/fzf-lua/commit/d49f79fbdaf5247ce694637555e8cd503f6fc05f works! Thank you for your work on fzf-lua!

**Comment by fannheyward** [comment]
> Can’t reproduce, what neovim version are you using

I'm using NVIM v0.9.0-dev-3921+g84027f751
