### ISSUE TITLE
Bug: `FzfLua buffers` doesn't jump to the right column

### ISSUE THREAD

**Issue by ajitid** [ibhagwan/fzf-lua#701]
### Info

- Operating System: Fedora 37
- Shell: Fish
- Terminal: Kitty
- `nvim --version`: v0.9.0-dev-843+g860fea1a3
- `fzf --version`: 0.38.0 (Fedora)
- [x] The issue is reproducible with `mini.sh`

### Description 

I've found that doing `:FzfLua buffers` doesn't show right column in the preview and upon hitting enter, doesn't jump to the right column of a line either. It always shows and goes to the first column of the cursorline. On the other hand, doing `:b <buffer-number>` gives the expected behaviour.

**Comment by ibhagwan** [comment]
Does it work work `mini.sh`?

Can you post a screenshot of your buffers screen in fzf-lua? Does it show line number after the buffer?

**Comment by ajitid** [comment]
It does show the line number correctly, but column number is missing 

![image](https://user-images.githubusercontent.com/26769888/227724608-243e09f8-9ad3-4e62-92fa-2ea395d9eee4.png)

**Comment by ibhagwan** [comment]
Setting the column was never supported, unfortunately `getbufinfo` returns only line number.

**Comment by ajitid** [comment]
Okay. Any reason why upon hitting enter we don't do something like `:b getbufinfo[idx].bufnr` which would at least let us jump to right column even if the preview shows the incorrect column?

**Comment by ibhagwan** [comment]
> Okay. Any reason why upon hitting enter the plugin doesn't do something like `:b getbufinfo[idx].bufnr` which would at least let us jump to right column even if the preview shows the incorrect column?

Let me test this, if it works there is def no reason not to use it.

**Comment by ibhagwan** [comment]
> Okay. Any reason why upon hitting enter the plugin doesn't do something like `:b getbufinfo()[idx].bufnr` which would at least let us jump to right column even if the preview shows the incorrect column?

The code was already using `b <bufnr>` but it was using a unified function that switches buffers and files.

https://github.com/ibhagwan/fzf-lua/commit/11225b76a41ae59bd52307c64862e13b12de50ef - this commit disables setting the cursor when switching buffers which preserves both line and column.
