### ISSUE TITLE
Fzf lines and blines does not go to the correct lines anymore

### ISSUE THREAD

**Issue by sandangel** [ibhagwan/fzf-lua#702]
### Info

- Operating System:
- Shell:
- Terminal:
- `nvim --version`: nightly
- `fzf --version`: latest

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

It doesn't work even with mini.sh

</details>

### Description 

The issue started to happen from last week IIRC.

**Comment by ibhagwan** [comment]
Ty @sandangel, fixed now!

**Comment by sandangel** [comment]
That was quick, thank youuuu ❤️❤️❤️❤️❤️❤️

**Comment by ibhagwan** [comment]
> That was quick, thank youuuu heartheartheartheartheartheart

Ty for the report, I knew immeidietly I overlooked something in my fix for #701.
