### ISSUE TITLE
How to disable a special provider?

### ISSUE THREAD

**Issue by fannheyward** [ibhagwan/fzf-lua#704]
I'd like to disable some providers, for example, dap, because I don't use this by now. The main reason to disable provider is: ignore them in `:FzfLua` list that reduce fuzzy matching noise.

Thank you for the work of fzf-lua.

**Comment by ibhagwan** [comment]
Providers are lazy loaded, they are only loaded the first time you use them.

Unfortunately the auto complete returns all possible providers, no current way to be removed from auto complete.

**Comment by fannheyward** [comment]
Ok, got it. I didn't complain the loading speed or not, fzf-lua already does a very good job on performance, I just want to ignore them in commands list to reduce the fuzzy matching noise.

**Comment by ibhagwan** [comment]
> Ok, got it. I didn't complain the loading speed or not, fzf-lua already does a very good job on performance, I just want to ignore them in commands list to reduce the fuzzy matching noise.

Understood, unfortunately that’s not possible ATM.
