### ISSUE TITLE
Preview does not accept floating point percentages or absolute integer amounts

### ISSUE THREAD

**Issue by Diablo-D3** [ibhagwan/fzf-lua#705]
```lua
winopts = {
  preview = {
    layout = "horizontal",
    horizontal = "left:41.5%", -- doesn't work
    horizontal = "left:60",    -- doesn't work
    horizontal = "left:52%"    -- does work
  }
}
```

This example does not function as expected. Integer percentages lack the precision to accurately describe an exact intended width, and being able to just enter absolute integers would be preferable.

**Comment by Diablo-D3** [comment]
That leaves sort of a problem then. If I never intend on using the native previewer, I still should be able to concretely control integer widths.

So, I have this really weird function going on, and there's probably a better way of doing this:

```lua
    winopts_fn = function()
        local cols = vim.o.columns
        local rows = vim.o.lines

        return {
            on_create = function()
                local self = require('fzf-lua').utils.fzf_winobj()

                if not self._previewer then
                    self.winopts.col = cols > 80 and cols - 80 or cols / 2
                    self.winopts.row = 0
                    self.winopts.width = cols
                    self.winopts.height = rows
                    self.winopts.border = false
                    self.winopts.preview = {
                        hidden = true,
                        horizontal = "left:0%"
                    }
                    self.layout = self:generate_layout(self.winopts)
                    self:redraw_main()
                end
            end,
            col = 0,
            row = 0,
            width = cols,
            height = rows,
            border = false,
            preview = {
                horizontal = "left:" .. math.floor((100 * (cols > 80 and cols - 80 or cols / 2) / cols) + 0.5) .. "%",
                layout = "horizontal"
            }
        }
    end

```

Which, should, in theory, be: "if showing preview, the picker should be 80 characters exactly (or half of the screen if 80 or less wide) on the right; if not showing preview, the picker should still be 80 (or half) wide, but not obscure the normal window behind the float where the preview would be"

There should be a better and saner way of doing this. However, if I could set horizontal in integer cols, this solution would technically work (rounding and flooring both end up on the wrong column, otherwise).

**Comment by ibhagwan** [comment]
> That leaves sort of a problem then. If I never intend on using the native previewer, I still should be able to concretely control integer widths.

Unfortunately I don’t plan on making any changes to this code before a refactor of the window class, the code evolved from being developed while supporting only fzf native previewers and the builtin was added afterwards, accommodating what you’re asking as is would be hacks and messy and I have no plans on modifying it rn.

**Comment by Diablo-D3** [comment]
I guess that only leaves me being able to ask the obvious question: is the refactor coming soon, or is this a more off in the distance sort of thing because you have other things you want to get done first?

**Comment by ibhagwan** [comment]
> I guess that only leaves me being able to ask the obvious question: is the refactor coming soon, or is this a more off in the distance sort of thing because you have other things you want to get done first?

I don’t have this planned in the immediate timeframe, I will have to be inspired on a long flight or something similar :)
