### ISSUE TITLE
git_status does not display correct file path

### ISSUE THREAD

**Issue by jonassvedas** [ibhagwan/fzf-lua#706]
### Info

- Operating System: ubuntu 22
- Shell: bash 5.1.16
- Terminal: windows terminal
- `nvim --version`: v0.9.1
- `fzf --version`: 0.35.1

Setup
```
 nnoremap <leader>gs <cmd>lua require('fzf-lua').git_status()<CR>
```

### Description 

running get_status will display the files in git status however they have some strange prefix that breaks the path and hence opening the file fails.

eg:
![image](https://user-images.githubusercontent.com/7907366/228808107-645fd0c7-0216-4ea7-b4f4-78c16e840ce8.png)

when I click enter on the first file nvim opens a new file called `31mM .bashrc`

**Comment by ibhagwan** [comment]
Seems that the terminal / fzf isn’t interpreting the ansi color escape codes properly.

Do the icons/colors work properly with `files`?
Does `:FzfLua git_status color_icons=false` work?
Does `:FzfLua git_status file_icons=false` work?

**Comment by jonassvedas** [comment]
Do the icons/colors work properly with files?
yes icons and colors work fine with all other commands i tried, including files.
Does :FzfLua git_status color_icons=false work?
no
Does :FzfLua git_status file_icons=false work?
no

**Comment by jonassvedas** [comment]
Yes that was it.

if you do 
git config --global color.ui false

then the fzf-lua git_status() works fine.

i think git introduced colors in 2013. and by default the git ui will be colors so i think its worth fixing this on the fzf-lua side.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/60213f975d49027ece2720fa1a9e7e5b1f2d3a5b - this commit changes the default command (which you can also customize if you wish) to `git -c color.status=false status -s` (formerly `git status -s`) which should solve your problem.

I suspect this issue specifically arised in your config as `git` disables colored output when piped unless you specify `color.ui=always` in your config.

**Comment by jonassvedas** [comment]
my git config specified color.ui=auto

**Comment by ibhagwan** [comment]
> my git config specified color.ui=auto

No idea why then, perhaps Windows terminal behaves differently? otherwise I suspect I'd be seeing this issue earlier.

In any event changing the default command is the right solution here.

**Comment by jonassvedas** [comment]
I tested the fix, it solved the issue. Thanks. This is one of the best plugins!

**Comment by ibhagwan** [comment]
> I tested the fix, it solved the issue. Thanks. This is one of the best plugins!

Ty @jonassvedas!

**Comment by ibhagwan** [comment]
FYI, https://github.com/ibhagwan/fzf-lua/commit/1d65dbcbdc021627e2ff1bf96bbc0ba24f916187 - this also takes care of the user overriding the command regardless of `color.status`.

**Comment by jonassvedas** [comment]
I had another check actually my setup did use color.ui=always. So it was that. I just overrode it by accident when testing.

**Comment by wookayin** [comment]
I think `git status --porcelain` (with `-u`) should always be used. See also #889

**Comment by ibhagwan** [comment]
> I think `git status --porcelain` (with `-u`) should always be used. See also #889

Will look into it, didn’t know about `--porcelain`, have to make sure this works with older git versions too.

As of know there are no outstanding issues with git in relation to the used commands so this isn’t urgent.

**Comment by wookayin** [comment]
The porcelain option has existed since git v1, and is guaranteed to produce the same exact output even in future versions with more configuration point. In fact, if one sets `-c status.relativePaths` in their config, currently `git status --short` will break.
