### ISSUE TITLE
With `ruff_lsp` code_action fails

### ISSUE THREAD

**Issue by WhyNotHugo** [ibhagwan/fzf-lua#707]
### Info

- Operating System: Alpine Linux amd64
- Shell: zsh
- Terminal: foot
- `nvim --version`: NVIM v0.8.3 
- `fzf --version`: 0.38.0 (AlpineLinux)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
  winopts = {
    split = "belowright new",
    preview = {
      hidden = "hidden",
    },
  },
  fzf_opts = {
    ["--layout"] = "default",
  },
})
```
</details>

I can't reproduce with that minimal config because you need to configure a specific LSP too.

### Description 

This issue is tricky: it's only reproducible with a single LSP, [ruff-lsp](https://github.com/charliermarsh/ruff-lsp). When I run:

    require("fzf-lua").lsp_code_actions()

I get an error:

    LSP[ruff_lsp] Unexpected error in LSP server, see server's logs for details

However, the following does work:

    :lua vim.lsp.buf.code_action()

So it definitely doesn't sound like a bug with the LSP itself or neovim, but with now `fzf-lua` is querying for code actions.

**Comment by WhyNotHugo** [comment]
I don't think the LSP logs are relevant, but it's:

```
[ERROR][2023-01-17 16:08:01] .../vim/lsp/rpc.lua:733	"rpc"	"ruff-lsp"	"stderr"	"Unable to deserialize message\n  + Exception Group Traceback (most recent call last):\n  |   File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 401, in _deserialize_message\n  |     return self._converter.structure(data, request_type)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/usr/lib/python3.11/site-packages/cattrs/converters.py\", line 309, in structure\n  |     return self._structure_func.dispatch(cl)(obj, cl)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 26, in structure_TextDocumentCodeActionRequest\n  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)\n  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 10, in structure_TextDocumentCodeActionRequest\n    |     res['params'] = __c_structure_params(o['params'], __c_type_params)\n    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 31, in structure_CodeActionParams\n    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)\n    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (1 sub-exception)\n    | Structuring class TextDocumentCodeActionRequest @ attribute params\n    +-+---------------- 1 ----------------\n      | Exception Group Traceback (most recent call last):\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 15, in structure_CodeActionParams\n      |     res['context'] = __c_structure_context(o['context'], __c_type_context)\n      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 21, in structure_CodeActionContext\n      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)\n      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)\n      | Structuring class CodeActionParams @ attribute context\n      +-+---------------- 1 ----------------\n        | Traceback (most recent call last):\n        |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 5, in structure_CodeActionContext\n        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)\n        |                                                     ~^^^^^^^^^^^^^^^\n        | TypeError: list indices must be integers or slices, not str\n        | Structuring class CodeActionContext @ attribute diagnostics\n        +------------------------------------\n\n"
[ERROR][2023-01-17 16:08:01] .../vim/lsp/rpc.lua:733	"rpc"	"ruff-lsp"	"stderr"	"Error receiving data\n  + Exception Group Traceback (most recent call last):\n  |   File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 401, in _deserialize_message\n  |     return self._converter.structure(data, request_type)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/usr/lib/python3.11/site-packages/cattrs/converters.py\", line 309, in structure\n  |     return self._structure_func.dispatch(cl)(obj, cl)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 26, in structure_TextDocumentCodeActionRequest\n  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)\n  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 10, in structure_TextDocumentCodeActionRequest\n    |     res['params'] = __c_structure_params(o['params'], __c_type_params)\n    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 31, in structure_CodeActionParams\n    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)\n    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (1 sub-exception)\n    | Structuring class TextDocumentCodeActionRequest @ attribute params\n    +-+---------------- 1 ----------------\n      | Exception Group Traceback (most recent call last):\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 15, in structure_CodeActionParams\n      |     res['context'] = __c_structure_context(o['context'], __c_type_context)\n      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 21, in structure_CodeActionContext\n      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)\n      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)\n      | Structuring class CodeActionParams @ attribute context\n      +-+---------------- 1 ----------------\n        | Traceback (most recent call last):\n        |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 5, in structure_CodeActionContext\n        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)\n        |                                                     ~^^^^^^^^^^^^^^^\n        | TypeError: list indices must be integers or slices, not str\n        | Structuring class CodeActionContext @ attribute diagnostics\n        +------------------------------------\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 507, in data_received\n    self._data_received(data)\n  File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 539, in _data_received\n    json.loads(body.decode(self.CHARSET),\n  File \"/usr/lib/python3.11/json/__init__.py\", line 359, in loads\n    return cls(**kw).decode(s)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\n               ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 415, in _deserialize_message\n    raise JsonRpcInvalidParams() from exc\npygls.exceptions.JsonRpcInvalidParams: Invalid Params\n"
[ERROR][2023-01-17 16:08:06] .../vim/lsp/rpc.lua:733	"rpc"	"pylsp"	"stderr"	"2023-01-17 16:08:06,200 CET - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 2\n"
[ERROR][2023-01-17 16:08:06] .../vim/lsp/rpc.lua:733	"rpc"	"ruff-lsp"	"stderr"	'Cancel notification for unknown message id "2"\n'
```

Which untangled a bit translates to:

```
 "Unable to deserialize message
  + Exception Group Traceback (most recent call last):
  |   File "/usr/lib/python3.11/site-packages/pygls/protocol.py", line 401, in _deserialize_message
  |     return self._converter.structure(data, request_type)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/site-packages/cattrs/converters.py", line 309, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 26, in structure_TextDocumentCodeActionRequest
  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 10, in structure_TextDocumentCodeActionRequest
    |     res['params'] = __c_structure_params(o['params'], __c_type_params)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 31, in structure_CodeActionParams
    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (1 sub-exception)
    | Structuring class TextDocumentCodeActionRequest @ attribute params
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 15, in structure_CodeActionParams
      |     res['context'] = __c_structure_context(o['context'], __c_type_context)
      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 21, in structure_CodeActionContext
      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)
      | Structuring class CodeActionParams @ attribute context
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 5, in structure_CodeActionContext
        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)
        |                                                     ~^^^^^^^^^^^^^^^
        | TypeError: list indices must be integers or slices, not str
        | Structuring class CodeActionContext @ attribute diagnostics
        +------------------------------------
```

**Comment by ibhagwan** [comment]
> So it definitely doesn't sound like a bug with the LSP itself or neovim, but with now fzf-lua is querying for code actions.

FzfLua does in fact query for code actions, here is the call:
https://github.com/ibhagwan/fzf-lua/blob/d49f79fbdaf5247ce694637555e8cd503f6fc05f/lua/fzf-lua/providers/lsp.lua#L820

The reason for doing so is because code actions requires ui.select, when FzfLua isn’t registered globally for ui.select it to register itself and then deregister when the interface is closed. Since I couldn’t find a way to determine beforehand to determine if there are any code actions I had to call the LSP for that, otherwise the deregister callback will never be called which might not be what the user wants.

An easy workaround would be to call `:FzfLua register_ui_select` (once, at startup) and then call `vim.lsp.buf.code_action()` which is the better way to use FzfLua with code actions.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/30fb626355d4b65cb6922d7de8bdb2a276b7d97e - this is a semi-workaround for this issue, fzf-lua will now test if fzf-lua is the registered interface for `vim.ui.select` and will avoid calling the LSP code actions if it's already registered.

This doesn't solve the error coming back from the LSP server but it makes it so you can call `lsp_code_actions` after registering for `ui.select` (so you can keep calling `lsp_code_actions` instead of `vim.lsp.buf.code_action` if you prefer).

**Comment by WhyNotHugo** [comment]
Why does this use `async = false``? I noticed that when the LSP is starting, `require("fzf-lua").lsp_code_actions()` will freeze until the LSP is finally ready (or timeout, whichever comes first).

I'm also now seeing some scenarios with `rust_analyzer` where `:lua vim.lsp.buf.code_action()` shows 3 actions, but `require("fzf-lua").lsp_code_actions()` prints `[Fzf-lua] No code actions found`.

**Comment by ibhagwan** [comment]
> Why does this use `async = false`? I noticed that when the LSP is starting, `require("fzf-lua").lsp_code_actions()` will freeze until the LSP is finally ready (or timeout, whichever comes first).

That’s because of how the code actions work which is a shortcut to:
If fzf-lua is registered to ui.select the code calls `vim.lsp.but.code_action`
1. If fzf-lua isn’t registered it does this:
2. Call the LSP and get call actions, if there are code actions, register ui.select, call `vim.lsp.but.code_action` and deregister ui.select

When route (2) is taken the code must call the LSP to know beforehand if the interface will be opened as the deregister callback won’t be called otherwise (thus the sync call), it’s a hack, but it’s the only way I could find to facilitate code actions without forcing the users to register Fzf-lua for ui.select globally.

This is also the reason it was removed in Telescope, code actions are better served via `vim.lsp.but.code_action`.

> I'm also now (with [30fb626](https://github.com/ibhagwan/fzf-lua/commit/30fb626355d4b65cb6922d7de8bdb2a276b7d97e)) seeing some scenarios with `rust_analyzer` where `:lua vim.lsp.buf.code_action()` shows 3 actions, but `require("fzf-lua").lsp_code_actions()` prints `[Fzf-lua] No code actions found`.

The reason this hones is because of the check to see if code actions exist described in (2), if you can provide a code sample in rust that I can reproduce this I can look into solving this.

In any event the better way is to use `:FzfLua register_ui_select` and call `vim.lsp.but.code_action()` which will still use fzf-lua as the interface.

**Comment by ibhagwan** [comment]
I installed `ruff_lsp` in an attempt to improve when manually querying the LSP for code actions but I can't reproduce this, everything is working as expected:
![image](https://user-images.githubusercontent.com/59988195/230214769-c2b9301d-e89a-4a4a-8d18-86c2b749131a.png)

The code action itself also works:
> Before
![image](https://user-images.githubusercontent.com/59988195/230214941-27570c66-349a-40f8-b2ae-ccaf8e01355a.png)
> After selecting `Organize Imports`:
![image](https://user-images.githubusercontent.com/59988195/230215012-78263b62-7173-4429-aa37-caf3785c4715.png)

It would be helpful if you can provide a short code sample where code actions exist using `vim.lsp.buf.code_action()` but aren't working when calling fzf-lua's `lsp_code_action`.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/356e63d624a333acbcf4406b292eeb8036aa1b26 - @WhyNotHugo, it seems that some LSPs (ruff_lsp included) fail when line diagnostics are empty, this commit takes care of that.

Note that if you don't have fzf-lua registered for `ui.select` fzf-lua will still first query the LSP directly to determine if code actions exist (synchronously), if you wish to avoid that, call `:FzfLua register_ui_select` once at startup.

**Comment by WhyNotHugo** [comment]
Thanks for the thurough examplantion. So I guess the real cause of the issue is that `vim.lsp.buf.code_action` calls `ui.select` unconditionally, rather than allowing us to specify a callback with action items or something, right?

I wonder if such a change is worth proposing to neovim.

> The reason this happens is because of the check to see if code actions exist described in (2), if you can provide a code sample in rust that I can reproduce this I can look into solving this.

Sure, this repo:

```
git clone https://git.sr.ht/~whynothugo/shotman
git checkout 09fad8dd1b915bfe3063cf3503171656671874cb
nvim src/main.rs
```

On line 8 `:lua vim.lsp.buf.code_action()` shows 1 action, but `require("fzf-lua").lsp_code_actions()` says there are none.

> In any event the better way is to use :FzfLua register_ui_select and call vim.lsp.but.code_action() which will still use fzf-lua as the interface.

I'll try this out, although I'm not sure if an fzf picker is ideal in all scenarios. Only one way to find out I guess.

**Comment by WhyNotHugo** [comment]
On Mon, 10 Apr 2023, at 20:18, ibhagwan wrote:
> Have you tried after updating FzfLua to include this fix356e63d? This issue should have been solved by it.
> 

Sorry, my head was 30fb626355d4b65cb6922d7de8bdb2a276b7d97e. I've updated now and the issue is gone.
 



-- 
Hugo
