### ISSUE TITLE
search files within multiple cwd directories?

### ISSUE THREAD

**Issue by jonassvedas** [ibhagwan/fzf-lua#708]
I am aware that you can search for files within a custom directory like this:
`.files({cwd=/path/to/dir})`

is there a solution to provide a list of directories you want to search in?

something like the following or equivalent solution:
`.files({cwd=[/path/to/dir1, /path/to/dir2, /path/to/dir3]})`

apologies if this is already solved or trivial, I don't know lua very well and it seems this case was not in the documentation.

**Comment by ibhagwan** [comment]
> apologies if this is already solved or trivial, I don't know lua very well and it seems this case was not in the documentation.

Multiple working directories are not currently possible, behind the scenes fzf runs within the `cwd` therefore the grep/rg/fd cannot return results outside of it.

One thing you could do is use the `cmd` argument with a command that combines results from multiple directories (using `xargs`?).

**Comment by ibhagwan** [comment]
Btw, for `grep` you can [use ripgrep globs](https://github.com/ibhagwan/fzf-lua/wiki#live-grep-glob).

Perhaps you can use the same with files using `files({ cmd = 'rg --files --iglob=…' })`

**Comment by ibhagwan** [comment]
Was just able to achieve what you're after with `rg --iglob`:
> The below enumerates both `~/.config/nvim` and `~/.config/awesome`:
```lua
:lua require("fzf-lua").files({ cmd = [[rg --hidden --files --iglob=".config/{nvim,awesome}/*"]] })
```

If you wish for it to run on a narrower set (thus finishing faster) you can also set the `cwd`:
> `rg` will format the results relative to `cwd` so `.config` can be omitted from the glob
```lua
:lua require("fzf-lua").files({ cwd="~/.config", cmd=[[rg --hidden --files --iglob="{nvim,awesome}/*"]] })
```

**Comment by jonassvedas** [comment]
thanks this worked for me:

`nnoremap <leader>p <cmd>lua require('fzf-lua').files({cwd=/mydir/, cmd=[[rg --files subdir1 subdir2 subdir3]]})`

**Comment by ibhagwan** [comment]
> thanks this worked for me:
> 
> `nnoremap <leader>p <cmd>lua require('fzf-lua').files({cwd=/mydir/, cmd=[[rg --files subdir1 subdir2 subdir3]]})`

Even better :)

**Comment by ibhagwan** [comment]
If you wish to contribute I think this is would be a valuable contribution to the wiki, otherwise I’ll do it the next time I get a chance.
