### ISSUE TITLE
wish: document how to setup common fzf.vim commands

### ISSUE THREAD

**Issue by markstos** [ibhagwan/fzf-lua#710]
For people coming from fzf.vim, it would be helpful if there docs to show how to make these commands work as before:

 
  :Buffers to search buffers,
  :Files to search files.
  :GFiles for git status output
  :Lines for lines in open buffers
  :Commits for git commits

I started working on figuring this out myself and got this far:

```lau
vim.api.nvim_create_user_command('Files',
  function(opts)
    require('fzf-lua').files()
  end,
  {}
)
```

But this doesn't work quite the same. Before I could give an argument to some of these commands, like

`:Files ./lib` to search for files in the `./lib` directory, but I couldn't find docs or examples
for syntax that would allow me to set that up here. 

Since fzf.vim works as I wish, I think I'll stick with it for now, but once I can reproduce the features with this plugin, I'll consider switching.

Thanks!

**Comment by ibhagwan** [comment]
Although this plug-in is comparable it doesn’t have to work **exactly the same**, when you move from vimL to lua, things are going to end different and it makes sense to learn the lua way which is more empowering IMHO.

> Since fzf.vim works as I wish, I think I'll stick with it for now, but once I can reproduce the features with this plugin, I'll consider switching.

Absolutely, there is no immediate reason to switch, at one point when you’re more proficient with lua you’ll come back to this plug-in, read the docs which will then make more sense and realize how easy lua is and how to use this plug-in properly, until then keep using what works for you.

If somebody wishes to document an exact replica of the fzf.vim command they can do so and add it to the wiki (which is open edit) but it’s not currently on my plate.

**Comment by ibhagwan** [comment]
Forgot to show an example of your request: for example for `files`:
```lua
vim.api.nvim_create_user_command('Files',
  function(opts)
    require('fzf-lua').files({ cwd = opts.args })
  end,
  {}
)
```

**Comment by markstos** [comment]
Thanks for the reply and the example! I could figure out the rest of the commands I wanted to create based on that. 

So I far I like what I've learned about Lua.

**Comment by ibhagwan** [comment]
> Thanks for the reply and the example! I could figure out the rest of the commands I wanted to create based on that.
> 
> So I far I like what I've learned about Lua.

Ty @markstos!

I knew only the basics of lua before writing this plug-in and converting my config to pure lua, it’s a game changer, I still don’t know vimL and have zero need for it in [my config](https://github.com/ibhagwan/nvim-lua), the lua plug-in ecosystem is amazing and vast and IMHO already outshines the vim ecosystem, even though you can still use vimL plugins aside from vim-fugitive I only use lua plugins and they are all better than their counterparts.
