### ISSUE TITLE
feat: use `horizontal copen` instead of `copen` for actions.*_sel_to_qf

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#712]
Current implementation of [actions.*_sel_to_qf](https://github.com/ibhagwan/fzf-lua/blob/30fb626355d4b65cb6922d7de8bdb2a276b7d97e/lua/fzf-lua/actions.lua#L201) uses `copen`to toggle open the qflist after it has been set. this leads to the following behavior when you use this:

https://user-images.githubusercontent.com/16427330/229320035-5c4ae199-fb8d-482d-bdec-4175dba6a5df.mov

As you can see when there are multiple columns of buffers, you use this action for a selection of fzf-entries, the qflist/loclist will behave open always in the rightmost column (exactly like `belowright copen`).

It would be great if this could be configured, in which case I would prefer to use `horizontal copen` to always split below the current buffer. Not sure if this is relevant but I set `splitbelow` and `splitright` in my rc.

**Comment by ibhagwan** [comment]
I have no objection to this change as long as there is no side effect, it makes sense to open the quick fix under the current buffer, I’ll do some testing first.

**Comment by yujinyuz** [comment]
@ibhagwan This broke something on my config that I just noticed.

When I'm selecting files and then press `alt-q`, it opens the quickfix list on top. Previously, it opened at the bottom

https://user-images.githubusercontent.com/10972027/230859965-6d8c8aa0-8e14-4c7e-80eb-7e89f7977654.mp4

**Comment by fsouza** [comment]
Hey @ibhagwan, this change made is so `copen` respects `splitbelow`, while this kinda makes sense, in practice it becomes an annoyance for folks like me who are used to the old behavior. Would you be OK with making this optional? I can send a PR.

**Comment by ibhagwan** [comment]
@fsouza, @yujinyuz, I had a feeling but I didn’t anticipate this unintended consequence, I’ll make this optional.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/061a4df40f5238782fdd7b380fe55650fadd9384 - this restores the original functionality.

@ViRu-ThE-ViRuS , if you wish to use a different command send `copen` as part of your options, e.g.:
```lua
reqiure("fzf-lua").files({ copen = "horizontal copen" })
```

**Comment by ViRu-ThE-ViRuS** [comment]
> [061a4df](https://github.com/ibhagwan/fzf-lua/commit/061a4df40f5238782fdd7b380fe55650fadd9384) - this restores the original functionality.
> 
> @ViRu-ThE-ViRuS , if you wish to use a different command send `copen` as part of your options, e.g.:
> 
> ```lua
> reqiure("fzf-lua").files({ copen = "horizontal copen" })
> ```

would it not be better to be able to set `copen = ...` option in `require('fzf-lua').setup({ ... })` as the default `copen` to use. Currently I have had to set it for every single keymap individually, which is not clean. This should really be a config option that can be changed globally.

**Comment by ibhagwan** [comment]
> would it not be better to be able to set copen = ... option in require('fzf-lua').setup({ ... }) as the default copen to use. Currently I have had to set it for every single keymap individually, which is not clean. This should really be a config option that can be changed globally.

probably, only this has never come up until now and there are so many options already I’m trying to avoid adding yet one more.

**Comment by wookayin** [comment]
061a4df40f5238 --- Why not accepting "horizontal copen" as the sensible default?

**Comment by ibhagwan** [comment]
> [061a4df](https://github.com/ibhagwan/fzf-lua/commit/061a4df40f5238782fdd7b380fe55650fadd9384) --- Why not accepting "botright copen" as the sensible default?

Don’t think I have any objection to that

**Comment by ibhagwan** [comment]
@wookayin 

Following https://github.com/ibhagwan/fzf-lua/commit/a5858b312bb54ead3584a3cf099b6465be917920 the default was changed to `botright copen` (and `lopen` respectively).

It's also possible to change the setting globally, for example, opening at the top:
```lua
require("fzf-lua").setup({
  defaults = {
    copen = "topleft copen",
    lopen = "topleft copen",
  },
})
```
Or disabling opening the quickfix altogether:
```lua
require("fzf-lua").setup({
  defaults = {
    copen = false,
    lopen = false,
  },
})
```
