### ISSUE TITLE
Pass search string to an action

### ISSUE THREAD

**Issue by TheBlob42** [ibhagwan/fzf-lua#713]
This is a general question, as I could not find the answer in this repository.  
If I just missed it I would be grateful if you could point me towards it :slightly_smiling_face: 

Is it possible to pass the "search string" (whatever the user has typed after the prompt) to an action?

![image](https://user-images.githubusercontent.com/6849129/229622180-f57830d7-fac7-4e79-8ef5-5ae9c1219a2a.png)
(here the search string would be "git")

I am asking because I would like to catch the case when an action is invoked without any entry matching the search string. In my case I have written a small "save as"-utility which lets me quickly navigate through my file system to save a file at a certain location. In case nothing matches (aka I don't want to overwrite a certain file) I would like to create a new file based on the user input. But so far I haven't seen an easy way of doing this.

**Comment by ibhagwan** [comment]
`require("fzf-lua").get_last_query()`

**Comment by TheBlob42** [comment]
Exactly what I was looking for, thank you very much :+1:

**Comment by ibhagwan** [comment]
> Exactly what I was looking for, thank you very much 👍

You’re welcome :)
