### ISSUE TITLE
feat: use splits by default, but use floating window for ui_select

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#714]
**with the following configuration:**
```lua
    fzf.setup({ winopts = { split = 'horizontal new' })
    fzf.register_ui_select({ winopts = { split = nil, height = 0.5, width = 0.5 } }, true)
```
accordingly, all fzf-lua provided commands operate with the `horizontal new` split.
BUT when calling `vim.ui.select`, it will also use the same `horizontal new` split window, instead of a floating window with the specified height and width.

**NOTE that the reverse works:**
```lua
    fzf.setup({ winopts = { height = 0.5, width = 0.5 })
    fzf.register_ui_select({ winopts = { split = 'horizontal new' } }, true)
```

where all fzf-lua provided commands use floating windows, and all `vim.ui.select` calls use the `horizontal new` splits.

this might not be a feature request but rather a bug fix, looking at the code: https://github.com/ibhagwan/fzf-lua/blob/30fb626355d4b65cb6922d7de8bdb2a276b7d97e/lua/fzf-lua/providers/ui_select.lua#L43

it may be related to incorrect lua table extension/overloading.

**Comment by ibhagwan** [comment]
Due to the way lua works setting `split = nil` removes the argument so it doesn’t get merged, try setting `split = false`?

**Comment by ibhagwan** [comment]
Just tested, set `split = false` and everything will work as you wish.

The reason is that in lua `{ split = nil }` is equal to `{}` so the option never gets merged.

**Comment by ViRu-ThE-ViRuS** [comment]
neat! thanks :)
