### ISSUE TITLE
Barebones lazy setup fails to execute `serverstart`

### ISSUE THREAD

**Issue by mattiasbonte** [ibhagwan/fzf-lua#716]
### Info

- Operating System: MacOs
- Shell: Zsh
- Terminal: Wezterm
- `nvim --version`: nightly
- `fzf --version`:  0.38 (brew)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

`.config/lazytest/lua/plugins/fzf.lua`
```lua
return {
	{
		"ibhagwan/fzf-lua",
		dependencies = { "junegunn/fzf" },
		cmd = { "FzfLua" },
        }
}
```
</details>

### Description 

Hello! I'm trying to set up fzf-lua in a barebones lazy.nvim installation, but fail at something vital it seems.
I did use the method described in [this video](https://www.youtube.com/watch?v=LkHjJlSgKZY) where I use t[his newly implemented feature](https://github.com/neovim/neovim/pull/22128) in the nightly version. So it's not my main nvim installation but one at a different path.

This is the error I am seeing.

```lua
E5108: Error executing lua: Vim(lua):E5108: Error executing lua Vim:Failed to start server: no such file or directory
stack traceback:
	[C]: in function 'serverstart'
	.../nvim_distros/lazytest/lazy/fzf-lua/lua/fzf-lua/init.lua:28: in main chunk
	[C]: in function 'require'
	...e/nvim_distros/lazytest/lazy/fzf-lua/lua/fzf-lua/cmd.lua:2: in main chunk
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
	[C]: at 0x0102cb0220
stack traceback:
	[C]: at 0x0102cb0220
```
When I check out the file where this error is thrown, it's apparently trying to start a RTP server? I've looked into your personal dotfiles for a clue to what I might be doing wrong but can't really see anything special with your lazy setup that could help me.

Anyway, Im a bit lost in what all this means so I thought let's ask the professional :)! 

Any idea what might be going wrong?

Thanks in advance for your time.

**Comment by ibhagwan** [comment]
> It's apparently trying to start a RTP server? 

Correct, fzf-lua uses process sepration for most of the heavy lifiting, the named pipe is how the child process communicates with the main neovim instance for querying users's config and other options.

What is the exact version of your nightly?

I just tried `NVIM v0.9.0-dev-1326+g7c8c15507` with  [`LazyVim` starter repo](https://github.com/LazyVim/starter) and fzf-lua (same config file as you posted in the OP) and it worked as expected.

Can you start your neovim nightly, run `:lua print(vim.fn.serverstart())` and lmk the result (should succeed and print something like `/run/user/1000/LazyVim.1956.1`)?

**Comment by ibhagwan** [comment]
> When I run the command you provided I'm getting the same error.

Unfortunately this indicates a neovim bug, it is unable to start a server in the separate `NVIM_APP` environment, this will have to be solved upstream.

> I'm guessing the issue is related to using https://github.com/neovim/neovim/pull/22128 and will most likely work in my main `~/.config/nvim` installation without any issues.. Prehaps you've got some idea's on how to fix this?

Not sure how to fix this but you're correct in your assesment that this will work in your main neovim installation.

**Comment by ibhagwan** [comment]
We can leave this open until the upstream bug is fixed, we can also link the upstream issue if you open one, I would've done that but it doesn't reproduce for me (I can `:lua print(vim.fn.serverstart())` on my nightly), perhaps this issue is only on MacOS.

I would also look at https://github.com/neovim/neovim/issues/20865, as this seems related, perhaps you also have the same issue with `$XDG_RUNTIME_DIR`?

**Comment by mattiasbonte** [comment]
Yes you are probably right.. I am a bit confused though. When I run `:echo stdpath('run')` in my main installation, it shows a path `/var/folders/3q/.../T/nvim/jjVJ0I` which looks like a temp path. But when I run this command in the lazy installation it apprears to indeed be `unset`. When I then set `XDG_RUNTIME_DIR` manually in my `zshrc` it gets set in the lazy installation, but I don't really know to what I should set it to. So maybe that indeed holds the problem. 

Im gonna have to read up on what stdpath('run') is exactly to try to solve it and get back to this tomorrow. Thanks for the follow up!

**Comment by ibhagwan** [comment]
@mattiasbonte, any additional insight why server start fails when using `NVIM_APP` on your system? Is this an upstream issue or can this be closed?

**Comment by mattiasbonte** [comment]
Unfortunately not, I've tried but wasn't able to set it properly in the end. Also I used this method to migrate my installation from packer to lazy, so at some point I fully made the switch and used the installation with lazy as my main nvim setup. So then this issue was `resolved` for me. 

If I remember correctly some other plugins also had some weird behavior at some point and then I decided to fully switch it. So no valuable insights on my end no..

**Comment by shawnfelix** [comment]
@ibhagwan @mattiasbonte 
The same exact issue started occurring for me on nvim v0.10.3 and v0.10.4, eventually found the following discussion: [https://github.com/neovim/neovim/issues/30282](https://github.com/neovim/neovim/issues/30282)
I also use NVIM_APPNAME to switch between config profiles

The fix is to either create a dir with permissions 700 where the XDG_RUNTIME_DIR is pointing to. Or you can just unset XDG_RUNTIME_DIR.

Not exactly sure when the XDG_RUNTIME_DIR env was set on my system, but its a fairly fresh install of WSL Ubuntu with zsh + tmux. Probably when I started setting up session management plugins for tmux and nvim. But I cant exactly pinpoint when that variable was set.

Hopefully this helps anyone searching for the same error

**Comment by ibhagwan** [comment]
> [@ibhagwan](https://github.com/ibhagwan) [@mattiasbonte](https://github.com/mattiasbonte) The same exact issue started occurring for me on nvim v0.10.3 and v0.10.4, eventually found the following discussion: [neovim/neovim#30282](https://github.com/neovim/neovim/issues/30282) I also use NVIM_APPNAME to switch between config profiles
> 
> The fix is to either create a dir with permissions 700 where the XDG_RUNTIME_DIR is pointing to. Or you can just unset XDG_RUNTIME_DIR.
> 
> Not exactly sure when the XDG_RUNTIME_DIR env was set on my system, but its a fairly fresh install of WSL Ubuntu with zsh + tmux. Probably when I started setting up session management plugins for tmux and nvim. But I cant exactly pinpoint when that variable was set.
> 
> Hopefully this helps anyone searching for the same error

Can you let me know how to reproduce this and which directories to create to solve this? Maybe  I can create the dir from inside fzf-lua?

**Comment by shawnfelix** [comment]
> Can you let me know how to reproduce this and which directories to create to solve this? Maybe I can create the dir from inside fzf-lua?

Honestly I think its an issue for neovim. 

I installed neovim v0.10.4 with brew on WSL2 Ubuntu. My best guess is that I think that WSL2 and MacOS have some issues with xdg runtime dirs not setup correctly. Possibly in combination with tmux configs.

To reproduce:
1. set XDG_RUNTIME_DIR=/run/user/<some uid or dir that doesnt exist>
2. start neovim
3. :lua print(os.getenv('XDG_RUNTIME_DIR')) 
4. should print the same value set in step 1
5. now try to execute anything that requires serverstart, ex. FzfLua files
6. you should get an error that the the dir doesnt exist 

If you set XDG_RUNTIME_DIR to a path that luajit/nvim do not have perms to access, you will encounter the same issue but with error permission denied

**Comment by ibhagwan** [comment]
@shawnfelix, the XDG_RUNTIME_DIR is not an issue I’d try to hack around, it’s already reported in health check and the user should be well advised to fix that or other things will break outside of fzf-lua.

That said, in https://github.com/ibhagwan/fzf-lua/commit/ac6d8dc4270bab41cf8bc32db857d0d1ab7b74b8 I added a more verbose error directing the user to fix the issue, for example, starting nvim with `XDG_RUNTIME_DIR=/etc nvim`:

![Image](https://github.com/user-attachments/assets/627561e4-8b0e-428e-a7f0-35e41af4cccc)

**Comment by renantmagalhaes** [comment]
Interestingly enough, I'm also having this problem!

I have my LazyVim config across four different environments:

- WSL2 with Debian 12 (this error occurs)
- WSL2 with openSUSE TW (no error)
- Debian 12 on bare metal (no error)
- openSUSE TW with Slowroll (no error)

Unsetting XDG_RUNTIME_DIR fixes the issue on WSL2, but since it only happens on my Debian WSL and not on bare metal, I assume this is a WSL issue rather than a Neovim issue.

**Comment by mocte4** [comment]
also got this (practically out of the box Kickstarter following these instructions https://www.youtube.com/watch?v=cLWgjienc_s)

**Comment by ibhagwan** [comment]
> how does it work on windows (no WSL)

Should work on windows without issue.
