### ISSUE TITLE
feat: get previews when using fzf-lua for vim.ui.select

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#717]
it would be nice to have documentation on how to achieve working previews when using fzf-lua for `vim.ui.select`.
I believe this is related to the `opts.kind` parameter to `vim.ui.select` (perhaps also how fzf interprets the lines).

ideally, it would be nice to somehow pass function callback which can take the selected entry and return a file uri type object back to fzf-lua for preview. regardless, it would be nice to have a wiki section about it in this project.

**Comment by ViRu-ThE-ViRuS** [comment]
the best way to achieve this is via: https://github.com/ibhagwan/fzf-lua/wiki/Advanced#preview-overview 
creating a custom previewer

**Comment by ViRu-ThE-ViRuS** [comment]
reopening with the following question:
`vim.ui.select` can take in an opts dict with 
``` lua
{ 
  prompt = 'prompt> ',
  kind = 'custom_data_a',
  format_item = function(item) ... end
}
```

how would this `kind` parameter be accessed in `MyPreviewer` [here](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#preview-overview).

**Comment by ibhagwan** [comment]
1. Not possible ATM, if that’s your wish I can save the ui.select dict as `ui_select_opts` and you can then access it from the previewer using `self.opts.ui_select_opts.kind`.
2. Not possible, the previewer is attached before the interface is open, perhaps you can call `close` on the previewer based on certain entries but that is somewhat hacky.

**Comment by ViRu-ThE-ViRuS** [comment]
> * Not possible ATM, if that’s your wish I can save the ui.select dict as `ui_select_opts` and you can then access it from the previewer using `self.opts.ui_select_opts.kind`.


yes this would be very useful, will increase usability with `vim.ui.select`

> * Not possible, the previewer is attached before the interface is open, perhaps you can call `close` on the previewer based on certain entries but that is somewhat hacky.

I tried using `self:close()` in both `parse_entry` and in `populate_preview_buf` but I run into weird error messages but preview window still shows up.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/01af68c09b34d12345aea9f55d560e8e2a59f9a4 - you can now access the `ui.select` call options from preview/actions (anywhere where you can access fzf-lua's `opts`).

To access from the previewer overrides use `self.opts._ui_select.kind`.

**Comment by ibhagwan** [comment]
I was also able to achieve your other wish, cleaner and without hacks by overriding the previewer's `new` method, return `nil` for all the kinds you wish to have the previewer disabled for:
```lua
local builtin = require("fzf-lua.previewer.builtin")

local MyPreviewer = builtin.buffer_or_file:extend()

function MyPreviewer:new(o, opts, fzf_win)
  if opts._ui_select and opts._ui_select.kind == "codeaction" then
    print("disable preview for codeaction")
    return nil
  end
  MyPreviewer.super.new(self, o, opts, fzf_win)
  setmetatable(self, MyPreviewer)
  return self
end

require("fzf-lua").register_ui_select({
  previewer = MyPreviewer,
  winopts = {
    win_height = 0.30,
    win_width  = 0.70,
    win_row    = 0.40,
  }
})
```

**Comment by ViRu-ThE-ViRuS** [comment]
excellent solution! tysm.
