### ISSUE TITLE
bug: builtin preview layout specified with `up:*%`, shows up incorrectly in `vsplits`

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ibhagwan/fzf-lua#718]
using minimal config:
``` lua
fzf.setup({
      winopts = {
        split = 'horizontal new',
        fullscreen = false,
        preview = {
          layout = 'flex',
          horizontal = 'right:50%',
          vertical = 'up:50%',                                              -- example config shows use of down
        },
      }
})
```

https://user-images.githubusercontent.com/16427330/230258136-be553e97-9631-43c8-82be-cb497e2fe529.mov

explanation:
- with vsplits, any buffer with a split to its right will show this bug, where the preview window is drawn in the incorrect location (always offset to the right side, occupying the split on the right.
- this behavior IS NOT SHOWN when using `vertical='down:50%'` instead.

**Comment by ibhagwan** [comment]
I never tested with `horizontal new`, the splits are assumed to be one of the four listed in the README:
```lua

local actions = require "fzf-lua.actions"
require'fzf-lua'.setup {
  winopts = {
    -- split         = "belowright new",-- open in a split instead?
                                        -- "belowright new"  : split below
                                        -- "aboveleft new"   : split above
                                        -- "belowright vnew" : split right
                                        -- "aboveleft vnew   : split left
     }       
} 
```

What behavior are you trying to achieve? Am I understanding correctly that you’re trying to open fzf-lua in a **split below the current window with the same width**?

The layout code is already one of my most unpleasant ones that I aim to refactor one day I don’t know if I want to add yet more complexity to it, isn’t one of the 4 listed splits sufficient for your workflow?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/ed41a475527f07a6e887146779e0ee6f0a779efd - should work now:
![image](https://user-images.githubusercontent.com/59988195/230546072-7f3b9ab6-4bcd-4055-924e-dcd9758cdb75.png)
