### ISSUE TITLE
When toggling a preview the dimensions of the window are constrained to the original size

### ISSUE THREAD

**Issue by akinsho** [ibhagwan/fzf-lua#721]
### Info

- Operating System: macOS	
- Shell: zsh
- Terminal: kitty
- `nvim --version`: nightly
- `fzf --version`:  0.39.0

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  keymap = {
    builtin = {
      ['<c-e>'] = 'toggle-preview',
    },
  },
  winopts = {
    preview = { hidden = 'hidden' },
    height = 0.3,
    width = 0.4,
  },
})
```
</details>

### Description 
If you press `<c-e>` with the following config the preview window won't try to fill the remaining space nor can it be sized to be anything other than the remaining space that was initially allotted to the window.

Using the comparison of telescope's `dropdown` theme, if a user decided to toggle the preview when previously it was hidden, it would just extend to it's own size regardless of the dropdown size.

The current situation means that if as in my case I try to reproduce the behaviour of the dropdown theme by reducing the size of the window when/if I do toggle the preview it's essentially forced to be quite small with no way for me to increase this.

*Before:*
<img width="821" alt="image" src="https://user-images.githubusercontent.com/22454918/230433280-20c00d0a-0483-491b-81e6-5ebbe5ae0d30.png">

*After:*
<img width="883" alt="image" src="https://user-images.githubusercontent.com/22454918/230433142-ad74b337-6d9e-4606-89e1-2db1bc6f6bf3.png">

**Comment by ibhagwan** [comment]
I’m wasn’t aware of how Telescope’s drop-down works but your analysis is correct, fzf-lua generates a layout which includes the preview window in dimensions (albeit hidden), the total size of the fzf-window is **always the same**, when  a preview is toggled it will split the main window according to the preview size setting and fill it with the preview. This made more sense in terms of UI.

What you’re asking is not currently possible, however, for these situations you can always toggle fullscreen (default bind `F2`).

**Comment by ibhagwan** [comment]
Also important to note that the design choice was also due to the way fzf preview works, the total window size is always the same and toggling the preview “eats” the main window space.

What you’re asking would be much harder to implement when using a fzf native previewer (e.g. `:FzfLua files previewer=bat`)

**Comment by akinsho** [comment]
Thanks for the quick response, that makes sense in the context of fzf drawing the previews and that changing how this behaves. Thanks for pointing out the full screen mechanism that helps a bit but unfortunately not being able to see the underlying text at all is a shame. Re. the telescope behaviour (just for completeness, since I referenced it without showing it)

<img width="804" alt="image" src="https://user-images.githubusercontent.com/22454918/230440939-416a653d-a0c9-4602-a1a0-57226a84215d.png">

<img width="790" alt="image" src="https://user-images.githubusercontent.com/22454918/230440989-ccd951e3-9fe2-40c5-be00-36b3f8007f22.png">

The dropdown doesn't change size just adds a new window above. Probably it's not easy feat to do this but I wonder if for "native" previews they could be drawn without this constraint. Although saying this I can already imagine that implementation wise it's probably not straightforward at all to do.

**Comment by ibhagwan** [comment]
Ty for the explanation and screens, confirming this works as I understood from your OP.

As for implementing this for the fzf “native” previewer, I would imagine this is possible via a combination of changing the total window size and modifying the preview % but this wouldn’t be trivial at all and would require automatically calculating sizes which is prone to errors.

The layout generation code and window class/object is one part of the code I’d like to refactor one day as it has evolved into being more complex and less scaleable (feature wise) to what I wished, perhaps then it would be easier to separate the functionality and enable drop-down feature without complicating the code further.

**Comment by ibhagwan** [comment]
If you don’t mind a semi-hacky solution this might be possible to achieve with the “builtin” previewer only (not with `bat`) and a custom bind that changes the layout, it would just have to double the height for vertical previews (or double the width for horizontal).

**Comment by ibhagwan** [comment]
Actually when I think of it, if you don’t mind this being a feature of only the builtin preview I’m sure I can accommodate this pretty easily by generating the same layout even when the preview is hidden.

**Comment by akinsho** [comment]
@ibhagwan would be great I don't mind that limitation at all since I think it's fine to expect fzf to manage its own previews and the previewers for files and buffers cover a lot of use cases.

**Comment by ibhagwan** [comment]
@akinsho, update to https://github.com/ibhagwan/fzf-lua/commit/ae5e11f1cd7626a504410928b147f053738dcaf7 and add this to your `setup`:
```lua
require("fzf-lua").setup({
  previewers = { builtin = { toggle_behavior = "extend" } },
})
```

**Comment by ibhagwan** [comment]
Use this commit https://github.com/ibhagwan/fzf-lua/commit/a0b615c0b4279dea10cc3b6048e2f4b620286cff as I force pushed due to a comment typo :-)

**Comment by akinsho** [comment]
@ibhagwan that was quick ❤️ thank you. I just tested it out locally and I'm seeing the original menu open with the same size as if the preview was open

<img width="905" alt="image" src="https://user-images.githubusercontent.com/22454918/230469674-152e77ae-5b9a-42b7-a4ed-82dd954fd212.png">

In the image above the picker is the height it would be if I had the preview open prior to your commit. I find that it works if I don't specify a height and the preview is intended to be vertically placed but it behaves as above if a height is specified. This might be a limitation just thought it was worth mentioning

My "dropdown" options are
```lua
local function dropdown(...)
  return vim.tbl_deep_extend('force', {
    fzf_opts = { ['--layout'] = 'reverse' },
    winopts = {
      height = 0.33,
      width = 0.45,
      preview = { hidden = 'hidden', layout = 'vertical' },
    },
  }, ...)
end
```

Then I use it like
```lua
    oldfiles = dropdown({
      prompt = ' History: ',
      cwd_only = true,
    }),
    files = dropdown({
      prompt = ' Files: ',
    }),
    buffers = dropdown({
      prompt = '﬘ Buffers: ',
    }),
    keymaps = dropdown({
      prompt = ' Keymaps: ',
      winopts = { width = 0.7 },
    }),
    registers = cursor_dropdown({
      prompt = ' Registers: ',
      winopts = { width = 0.6, height = 0.4, preview = { layout = 'horizontal' } },
    }),
```

**Comment by ibhagwan** [comment]
> In the image above the picker is the height it would be if I had the preview open prior to your commit. I find that it works if I don't specify a height and the preview is intended to be vertically placed but it behaves as above if a height is specified. This might be a limitation just thought it was worth mentioning

This works as intended although a bit different than what you’re used to with Telescope’s drop down, what I would do is first enable the previewer to be visible and set the dimensions to my my liking, you probably need a bigger height than what you think as total height size **includes the preview**, then once you have the right layout set the preview to start `hidden`.

**Comment by ibhagwan** [comment]
Also, if you wish for the preview to open above set `winopts.preview.vertical  = "up:50%"`

**Comment by akinsho** [comment]
@ibhagwan that solves entirely thank you 🙏🏾 🚀

**Comment by ibhagwan** [comment]
Ty @akinsho, I apologize this is somewhat counter intuitive to what you’re used to, height is total height including preview and preview % is a derivative of total height, the only feature we added here is the ability to not modify the main window dimensions, I’m not sure if `toggle_behavior = “extend”` is the correct naming here, if you can think of something let me know :).

**Comment by akinsho** [comment]
Tbh I think probably the most valuable thing specifically is documenting the point above somewhere, since I think if someone comes from telescope and encounters the behaviour without this option it almost seems like a bug since it works so differently. Re. the name I guess `extend` now makes sense but I don't know if it would have made sense without having gone through this flow. I kind of want to suggest that it just be default. Although I'm not sure how that will affect other people. I'm not sure if it's ever desirable for it to eat into your picker dimensions but I can imagine someone out there might disagree

**Comment by ibhagwan** [comment]
> I kind of want to suggest that it just be default.

This would change the default behavior for users, that is a breaking change of which I’m not a fan of.

> I'm not sure if it's ever desirable for it to eat into your picker dimensions but I can imagine someone out there might disagree

This is arguable and has worked like this wince day one and matches the current behavior of fzf in the shell so I’d argue it makes more sense this way.

**Comment by akinsho** [comment]
@ibhagwan definitely don't think anything needs to be broken on account of this. I read through the wiki and help first before raising this issue and just a comment there is probably enough. It's probably not that many people trying to recreate the telescope dropdown theme 👍🏾

Anyway as the issue is resolved on my end I'll close this out
