### ISSUE TITLE
switching grep mode with ctrl-g leaks memory

### ISSUE THREAD

**Issue by tomtomjhj** [ibhagwan/fzf-lua#723]
### Info

- Operating System: Ubuntu 22.04
- Shell: bash
- Terminal: GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD
- `nvim --version`: 0.9
- `fzf --version`: 0.39
- [x] The issue is reproducible with `mini.sh`

### Description 

reproducing steps
1. Run nvim with mini.sh
2. `<C-g>` to start grep
3. Keep switching the grep mode with `<ctrl-g>`
4. Run tools like htop.
   Notice that the nvim process's memory usage grows by a few hundred kilobytes per `<ctrl-g>`.

Note that invoking the fzf-lua command (e.g. `FzfLua grep`) also leaks memory, but it's much less than the leak from switching the mode.
So I believe there's some anomaly with mode switching.

Interestingly, heaptrack, valgrind and address sanitizer don't detect leak related to this issue.
So I think some part of fzf-lua implementation might be preventing garbage collection.

**Comment by ibhagwan** [comment]
`ctrl-g` does nothing different, it’s just an action that reopens the interface, moreover most of the heavy lifting happens in a separate neovim headless process, there is just one location (the callback registry) which I know keeps a function ref in memory and doesn’t get cleared it shouldn’t be 100 k’s each call:
https://github.com/ibhagwan/fzf-lua/blob/04d5a528a4159901607c11d46a398f45db2ed43f/lua/fzf-lua/shell.lua#L12-L16

This is rather easily fixable but I’m not sure if this will solve this issue entirely, this leak might also have an upstream component.

**Comment by tomtomjhj** [comment]
I ran the [memory profiler included in plenary](https://github.com/nvim-lua/plenary.nvim/commit/3cf30ca41da07fba82567ed97833d13146d1ed69#diff-023b0364c95c7524f67332893aab774046dcd081908ed658bc650757372d4ca8).
result: https://gist.github.com/tomtomjhj/ad945999be7f34840ea23758a8a96215.

I'm not sure if I'm properly interpreting it, but it seems to me that very long chains of closure captures pile up in `__resume_data` for each invocation of `<ctrl-g>`, judging from the fact that there are a huge number of entries that start with `registry.1.[userdata:environment][_G].module.[function:environment].loaded.fzf-lua.config.__resume_data.opts._pid_cb.[ups:table:opts].fn_post_fzf.[ups:table:M].live_grep_st.[ups:table:core].setup_fzf_interactive_wrap.[ups:table:shell].get_func.[ups:table:_registry].THE_VALUE_OF_COUNTER` in after.txt.

**Comment by ibhagwan** [comment]
Interesting I didn’t think of `__resume_data`, I’ll investigate.

**Comment by ibhagwan** [comment]
@tomtomjhj while I wasn't able to reproduce it (the memory footprint appears to stay the same on my machine no matter what I do), I noticed the excessive amount of `_pid_cb` variables in the linked gist, I've made some changes to the callback that stores the PID (it not longer maintains a copy of `opts`) and also cleared the callback function registry when the fzf process exits.

Can you try [723_mem_leak branch](https://github.com/ibhagwan/fzf-lua/tree/723_mem_leak) and lmk if this solves the memroy leak for you?

**Comment by tomtomjhj** [comment]
The issue persists. `_pib_cb` is now gone from the capture chain, but the chain is still linked.

```diff
-__resume_data.opts._pid_cb.[ups:table:opts].fn_post_fzf.[ups:table:M].live_grep_st.[ups:table:core].setup_fzf_interactive_wrap.[ups:table:shell].get_func.[ups:table:_registry]
+__resume_data.opts.                         fn_post_fzf.[ups:table:M].live_grep_st.[ups:table:core].setup_fzf_interactive_wrap.[ups:table:shell].get_func.[ups:table:_registry]
```

**Comment by ibhagwan** [comment]
Can you try the latest branch commit https://github.com/ibhagwan/fzf-lua/commit/663edb707dc28ec2ba0d9998408f0ab77ae8d230?

Removed more references inside the `__resume_data`, also added one change that would need to be removed just as a test as it would prevent preview actions from working on resume:
https://github.com/ibhagwan/fzf-lua/blob/663edb707dc28ec2ba0d9998408f0ab77ae8d230/lua/fzf-lua/core.lua#L275-L276

I ran the profiler you linked, [yaukeywang/LuaMemorySnapshotDump](https://github.com/yaukeywang/LuaMemorySnapshotDump),  and compared the memory dumps with `mri.m_cMethods.DumpMemorySnapshotComparedFile` and I get only 142 objects references, 89 of them inside `__resume_data`, if the situation would be similar for you it should solve the issue.

I did some additional testing on MacOSX and noticed the memory increase even without `ctrl-g` simply by closing and reopening the interface, this seems to also happen with Telescope which makes me think perhaps this is a neovim issue with floating window memory regardless of the memory optimization within fzf-lua?

**Comment by nyngwang** [comment]
Not sure whether this might be related: recently I found that one feature broken, it's pressing `<C-g>` upon the floating window of `FzfLua live_grep_glob`:



```lua
vim.keymap.set('n', '<C-f>', function ()
  require('fzf-lua').live_grep_glob {
    cwd = vim.fn.getcwd(-1,0),
    actions = { ['ctrl-f'] = 'abort' }
  }
end)
```

**Comment by tomtomjhj** [comment]
Thanks a lot for taking time to investigate it.

> I get only 142 objects references, 89 of them inside __resume_data

With 663edb707dc28ec2ba0d9998408f0ab77ae8d230, I get a similar result.

But interestingly, the actual memory usage is similar to the current main.

For reference, here are the actual memory usage on main:
* at the start, 11.5MB
* after start, launch `grep`, and press `<ctrl-g>` 50 times: 27 MB
* after start, launch `grep` 50 times: 17 MB

(On 663edb707dc28ec2ba0d9998408f0ab77ae8d230, the memory usage is about 1MB smaller.)

So I think there is something special about grep mode switching (or resuming).


> Reasoning: maybe this is related to this issue since this mishap would lead to some resources not being released correctly.

If that's the case, I think it's likely to be reported by heaptrack/asan/valgrind. Example: https://github.com/neovim/neovim/issues/16257


> this seems to also happen with Telescope which makes me think perhaps this is a neovim issue with floating window memory regardless of the memory optimization within fzf-lua?

I believe so. I don't have a good idea for further direction of investigation. But please let me know if there's anything I can help you with.

**Comment by tomtomjhj** [comment]
> I get only 142 objects references, 89 of them inside __resume_data

With 663edb707dc28ec2ba0d9998408f0ab77ae8d230, I get a similar result.
But interestingly, the actual memory usage is similar to the current master. 

For reference, here are the actual memory usage on master:
* at the start, 11.5MB
* after start, start `grep` and `<ctrl-g>` 50 times: 27 MB
* after start, launch `grep` 50 times: 17 MB

On 663edb707dc28ec2ba0d9998408f0ab77ae8d230, the memory usage is about 1MB smaller.

**Comment by ibhagwan** [comment]
@nyngwang, this is a bug, there is probably a lua exception which prevents the code from loading the new interface - does this happen on main too or just this branch?

> So I think there is something special about grep mode switching (or resuming).

@tomtomjhj, I actually think this has nothing to do with `ctrl-g`, what you’re describing confirms my findings on Mac which aren’t related to `ctrl-g`, if you open and close the interface 50 times I suspect you’ll get to the same result in memory footprint.

> With https://github.com/ibhagwan/fzf-lua/commit/663edb707dc28ec2ba0d9998408f0ab77ae8d230, I get a similar result.
> I believe so. I don't have a good idea for further direction of investigation. But please let me know if there's anything I can help you with.

This also confirms my findings that this might not be an issue but rather neovim “intended behavior” untreated to fzf-lua, I’m not sure how to proceed with this issue further, doesn’t seem like there is something I can do on my end.

**Comment by ibhagwan** [comment]
This is the part I don’t know how to explain, but I also can’t reproduce it so it’s very hard to debug:

> - at the start, 11.5MB
> - after start, launch grep, and press <ctrl-g> 50 times: 27 MB
> - after start, launch grep 50 times: 17 MB

**Comment by tomtomjhj** [comment]
>  if you open and close the interface 50 times I suspect you’ll get to the same result in memory footprint.

If I understood this correctly, this is what I did for "after start, launch grep 50 times". Specifically, I pressed `<C-g>` to run `grep_protect()` and pressed `<C-q>` to close it, and repeat. 


> I also can’t reproduce

I can reproduce in two Ubuntu 22.04 machines. So this could be ubuntu or gnu/linux only issue.

> This also confirms my findings that this might not be an issue but rather neovim “intended behavior” untreated to fzf-lua, I’m not sure how to proceed with this issue further, doesn’t seem like there is something I can do on my end.

Since we both seem to have run out of idea, let's just ignore this issue. After all, it's just a few hundred KBs per invocation, and I only noticed this issue while deliberately trying to break things. Though I may take a stab when I get bored enough.

**Comment by ibhagwan** [comment]
> Since we both seem to have run out of idea, let's just ignore this issue. After all, it's just a few hundred KBs per invocation, and I only noticed this issue while deliberately trying to break things. Though I may take a stab when I get bored enough.

It’s not in my nature ignoring issues, we can keep this open and keep interesting ideas/code till we get to the bottom of this.

**Comment by ibhagwan** [comment]
>  this is what I did for "after start, launch grep 50 times". Specifically, I pressed <C-g> to run `grep_project()` and pressed <C-q> to close it, and repeat.

Can you also try opening `live_grep` or `live_grep_glob` 50 times instead?

`ctrl-g` alternates between `grep` and `live_grep`, perhaps the issue lies in the latter.

**Comment by tomtomjhj** [comment]
Sorry for late response.
 
The memory usage after opening `live_grep_glob` 50 times is about 14.5MB

**Comment by ibhagwan** [comment]
> The memory usage after opening `live_grep_glob` 50 times is about 14.5MB

In this case my I would suspect the issue might lie in the way the fzf-lua windows are "reused", reason: when running the action fzf-lua calls `vim.api.nvim_win_set_config` as opposed of `vim.api.nvim_open_win` when creating new windows.

There are 2 ways to test this theory, can you try one of the below and lmk if this makes a difference?

1. Test using branch [732_2](https://github.com/ibhagwan/fzf-lua/tree/723_2)
2. Setup your grep actions to avoid reusing the windows with:
```lua
require("fzf-lua").setup({
  grep =  { actions = { ["ctrl-g"] = actions.grep_lgrep } },
})
```

> Note the original action is wrapped in a table, i.e. `{ ["ctrl-g"] = { actions.grep_lgrep  } }` which instructs fzf-lua to **not close the original window** so we can reuse it and prevent the cosmentic "flash" when recreating the window, it would be very faint but with the above setup you'll be able to notice a tiny "flash" when pressing `ctrl-g`.

**Comment by tomtomjhj** [comment]
Indeed, window reusing seems to be the culprit. With 732_2 branch, `<ctrl-g>`-ing 50 times only uses about 16MB.

**Comment by ibhagwan** [comment]
> Indeed, window reusing seems to be the culprit. With 732_2 branch, `<ctrl-g>`-ing 50 times only uses about 16MB.

Now we need to find out if it’s fzf-lua leaving some resources behind on reuse or `vim.api.nvim_win_set_config` is the source of the leak.

**Comment by ibhagwan** [comment]
@tomtomjhj, can you try the latest commit on main, made some changes to buffer management on reuse, may have also helped with this issue, lmk if this makse any difference on your end?

https://github.com/ibhagwan/fzf-lua/commit/6b8654d35de6f985a33fda10829ca9e20d9bf87f

**Comment by tomtomjhj** [comment]
On 44f1ec92b57f15745f5f21cf224e521ce9ba0b66, the memory usage of ctrl-g is now on par with normal invocations. Thanks for your hard work!

**Comment by ibhagwan** [comment]
> On [44f1ec9](https://github.com/ibhagwan/fzf-lua/commit/44f1ec92b57f15745f5f21cf224e521ce9ba0b66), the memory usage of ctrl-g is now on par with normal invocations. Thanks for your hard work!

Ty @tomtomjhj for raising this issue, we keep improving this way :)
