### ISSUE TITLE
[Bug] Unable to pass `fzf_opts` to `ui_register` function

### ISSUE THREAD

**Issue by akinsho** [ibhagwan/fzf-lua#724]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: Kitty
- `nvim --version`: 0.9.0
- `fzf --version`:

### Description 

When passing options to `register_ui_select` the `fzf_opts` are not merged with those passed to the picker so a users preferences are ignored.

e.g.
```lua
require('fzf-lua').register_ui_select({
	fzf_opts = {
		['--layout'] = 'reverse',
	}
})
```

https://github.com/ibhagwan/fzf-lua/blob/f466e20196678f0c934dbf8c433adb8b6e9120e9/lua/fzf-lua/providers/ui_select.lua#L60-L66

This could be by design or a bug (not sure which). If the desire is to ensure that the above options are passed along no matter what then they could just be allowed greater priority in the merge but the user options could still be allowed in (IMO)

**Comment by ibhagwan** [comment]
> This could be by design or a bug

An oversight, I’ll change this to `vim.tbl_extend` instead.
