### ISSUE TITLE
[Feature] Allow setting a title on the fzf window (not the previewer)

### ISSUE THREAD

**Issue by akinsho** [ibhagwan/fzf-lua#725]
### Description 

Apologies for the multiple issues today 😅, hopefully this issue is relatively small. I'm trying to add the name of each picker as the window title to the fzf window i.e. using `nvim_open_win`'s `title` option which was added in `0.9.0`. The motivation being that I rather the prompt area be clear save for maybe an icon, and just have only my search query in there rather than prompt text

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/22454918/231512332-3e381170-6bd5-4f55-81bc-7b755ccd3bf7.png">

This is actually similar to how in the terminal you can set the border label for fzf 

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/22454918/231513662-7ff5b458-dd78-45bc-baa7-04b26a7def71.png">

In this case since the float is presumably controlled by this plugin (nvim) rather than fzf the request it to add in a title option separate to the prompt so I can achieve the neovim equivalent of the above result.

**Comment by ibhagwan** [comment]
> In this case since the float is presumably controlled by this plugin (nvim) rather than fzf the request it to add in a title option separate to the prompt so I can achieve the neovim equivalent of the above result.

You’re correct, the border is controlled by neovim’s window - that was the better design choice if we want we to control the border shape and highlights, the title option is currently only supported for the preview window, this was done by creating an artificial border using another window around the contents window, that isn’t possible yet for the main window.

 > using nvim_open_win's title option which was added in 0.9.0

I can easily merge the title option with the existing `nvim_open_win` options.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/ad035588ea8b516e1eb447a267ca009bbf2d7c9e - added both `title` and `title_pos` arguments passthrough directly to `nvim_open_win`.

**Comment by ibhagwan** [comment]
@monkoose, this might interest you as well in regards to your request in #462, if you're using `0.9` you can add title/position.

**Comment by akinsho** [comment]
Thanks @ibhagwan 🙏🏾
