### ISSUE TITLE
Feature: quick commands with search string in command

### ISSUE THREAD

**Issue by casonadams** [ibhagwan/fzf-lua#726]
### Description 

It would be nice to be able to write a user_command

```
vim.api.nvim_create_user_command("Rg", "FzfLua grep_project <q-args>", { nargs = 1, bang = true })
```

So that I can quickly run the same command(s) vs always having to type out the search string

`:Rg test`
`:Rg module`
`:Rg something really long and painful to type a lot`

etc...

**Comment by ibhagwan** [comment]
I’m not a fan of the idea of adding these by default, if that’s someone’s wish they can very easily add these using lua:
```lua
vim.api.nvim_create_user_command('Rg',
  function(opts)
    require('fzf-lua').grep({ search = opts.fargs[1] })
  end,
  { nargs = "*" }
)

```

**Comment by ibhagwan** [comment]
FYI, this is also possible out of the box `FzfLua grep_project search=foo`

**Comment by casonadams** [comment]
> FYI, this is also possible out of the box `FzfLua grep search=foo`

This is what I was looking for!  Thanks!
