### ISSUE TITLE
Mouse scroll down/up doesn't move the preview menu scroll bar

### ISSUE THREAD

**Issue by craigmac** [ibhagwan/fzf-lua#729]
### Info

- Operating System: macOS 12.6.3
- Shell: zsh
- Terminal: wezterm
- `nvim --version`: 0.10.0 commit gf4136c9d4
- `fzf --version`: 0.38.0

- [ x] The issue is reproducible with `mini.sh`

### Description 

Open `:Fzflua files` and find a file where you can scroll the preview window.  Use mouse scroll down and up and see the preview window viewport change as expected, but the scroll bar on the side remains in the same spot. When you scroll using keybinds this doesn't happen, the scroll bar moves with the viewport, as expected.

**Comment by ibhagwan** [comment]
I'm not sure if this is fixable without a siginificat overhead or hacks, from what I can see in `:help events` there is not approerpiate event for scrolling the window, `WinScrolled` only triggers when the terminal scroll event is sent to the main neovim tab and `CursorMoved` doesn't seem to trigger with the mouse (not sure why).

In any event for the `CursorMoved` event to work I'd have to reenable autocmds for the preview buffer which would cause bigger problems, for example #626 and #643.

Given the above I'm willing to live with this limitation.
