### ISSUE TITLE
builtin previewer: resize on toggle preview?

### ISSUE THREAD

**Issue by fsouza** [ibhagwan/fzf-lua#73]
Hey there, I love the builtin previewer, thank you very much for putting that together!

The only thing I miss from the native fzf preview experience is the ability to resize the main window when toggling preview. Is this something you're planning to support?

**Comment by ibhagwan** [comment]
It's on my "internal list" :-)

I'll keep this thread updated.

**Comment by ibhagwan** [comment]
Should work as expected now.
