### ISSUE TITLE
Better UX for git status

### ISSUE THREAD

**Issue by elamaranae** [ibhagwan/fzf-lua#730]
I would like to check if the following enhancements can possibly be added to the git status picker,

1. An additional binding to reset the file to latest commit (effectively removing the entry from `git status`). If it's an untracked file, then delete it (`git clean`).

2. All binding actions currently restarts the picker, so the file position I was at while performing the action is lost (now I am back to the first file). Instead, the binding can be performed using `reload()` so that, fzf is not restarted.

I am currently using a custom picker that solves this issue for me, but it doesn't support other niceties like multiple selections, icons, and other edge cases. But this feels like a better UX to me.

One problem I've run into is concurrency issue if the git binding action is invoked before the previous action is completed, this caused the `.git/index.lock` file to not be deleted properly effectively preventing further git actions. I've solved this by unbinding once the action started and rebinding after the load happens.

```lua
    local custom_git_status = function()
      local actions = require "fzf-lua.actions"

      local status = 'git -c color.status=always status --short --untracked-files=all'
      local unbind = 'unbind(ctrl-s)+unbind(ctrl-x)'
      local rebind = 'rebind(ctrl-s)+rebind(ctrl-x)'

      local preview = [=[
        if [[ {1} =~ \? ]]; then
          git diff /dev/null {2} | delta --file-style=omit | sed 1d
        else
          git diff HEAD -- {2} | delta --file-style=omit | sed 1d
        fi
      ]=]

      local stage_unstage = [=[
        git diff --cached --quiet -- {2}

        if [ $? -eq 0 ]; then
          git add -- {2}
        else
          git reset --quiet -- {2}
        fi
      ]=] .. status

      local remove = [=[
        git reset --quiet -- {2}

        if [ {1} == "M" ] || [ {1} == "D" ]; then
          git checkout -- {2}
        else
          git clean -fd {2}
        fi
      ]=] .. status

      require 'fzf-lua'.fzf_exec(status, {
        keymap = {
          fzf = {
            ['ctrl-s'] = string.format(unbind .. '+reload(%s)', stage_unstage),
            ['ctrl-x'] = string.format(unbind .. '+reload(%s)', remove),
            ['load'] = rebind
          }
        },
        actions = {
          ['default'] = function(selected, opts)
            for i = 1, #selected do
              selected[i] = selected[i]:match('[^ ]*$')
            end
            actions.file_edit_or_qf(selected, opts)
          end
        },
        preview = preview,
        winopts = { fullscreen = true }
      })
    end
```

**Comment by ibhagwan** [comment]
@maran-e, try the latest commit https://github.com/ibhagwan/fzf-lua/commit/fa7dd22660841d8b4f9ae66fc74f77bbab399e80.

- Added and improved the `reset` action (still doesn't handle refershing the buffer, TBD).
- All actions now use `reload` instead of exiting and reopneing fzf for a seamless UI

I'm still debating having a single bind for stage/unstage toggle vs the current left/right arrows which users have gotten used to and also makes sense with the output format of `git status -s`.

You can customize the keybinds (which will also change the header), note you'd have to set the current defined defaults to `false` first, for example modiyfing the "stage" bind:
```lua
require("fzf-lua").setup({
  git = {
    status = {
      actions = {
        ["left"] = false,
        ["ctrl-s"] = { fzf_lua.actions.git_stage, fzf_lua.actions.resume }
      },
    },
  }
})
```

To disable the header you can use `no_header = true` (disables the header completely) or `no_header_i = true` (will still display certain properties in the header such as `cwd`).

**Comment by ibhagwan** [comment]
How are you generating tags? Can you post a few sample lines from your tags file?

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/e8d61893eb5dc929d6e5c7afc6537bf5b17bf4a7

@maran-e, the latest commit adds a new action for a single toggle to stage/unstage, I personally prefer the `left|right` approach for multiselect and I also don't want to change users' defaults, to repliacet the behavior described in the OP you need to disabled the defaults:
```lua
local fzf_lua = require("fzf-lua")
fzf_lua.setup({
  git = {
    status = {
      actions = {
        ["left"] = false,
        ["right"] = false,
        ["ctrl-s"] = { fzf_lua.actions.git_stage_unstage, fzf_lua.actions.resume },
        ["ctrl-x"] = { fzf_lua.actions.git_reset, fzf_lua.actions.resume },
      },
    },
  }
})
```

This will also modify the header string (exmaple from my own config):
![image](https://user-images.githubusercontent.com/59988195/233454863-6ca7cd14-6d78-4768-b9eb-dc03dc805307.png)

**Comment by nyngwang** [comment]
(@maran-e This turns out to be an awesome suggestion that increases the UX a lot, really. Thanks for pointing it out! And thanks @ibhagwan passionately for making it come true! Hope this thank you message won't interrupt any existing discussion.)

**Comment by ibhagwan** [comment]
> (@maran-e This turns out to be an awesome suggestion that increases the UX a lot, really. Thanks for pointing it out! And thanks @ibhagwan passionately for making it come true! Hope this thank you message won't interrupt any existing discussion.)

Ty @nyngwang!

**Comment by maran-e** [comment]
Hi @ibhagwan, thank you for implementing the suggestion so quickly. I've tried it out and it works very well.

There is still some issues that needs to be addressed,

1. 

> One problem I've run into is concurrency issue if the git binding action is invoked before the previous action is completed, this caused the .git/index.lock file to not be deleted properly effectively preventing further git actions. I've solved this by unbinding once the action started and rebinding after the `load` event.

This concurrency issue is present in latest commit. Now that fzf doesn't reload, there is a high chance that user may just spam the binding before a git action is completed. This is not easily reproducible with smaller repos. 

Maybe you can try this with the linux kernel `git clone --depth 3 git@github.com:torvalds/linux.git`

I am on a large repo for work and this occurs more than enough times to be a major UX issue. Most users will not know that they need to [now manually delete](https://stackoverflow.com/questions/9282632/git-index-lock-file-exists-when-i-try-to-commit-but-i-cannot-delete-the-file) `.git/index.lock` to get `git` to work again.

2. 

> I'm still debating having a single bind for stage/unstage toggle vs the current left/right arrows which users have gotten used to and also makes sense with the output format of git status -s.

I agree that we don't want to change what users are already used to. Hence, this wasn't part of the suggestions. Although, can we retain the original colors of `git status`. The red and green clearly communicates which file is staged and which is unstaged. Now we have to indentify based on indentation alone and users who use the toggle action will not know if left is staged or unstaged.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/cf079db4f729f2eb6c4b4dbeb3e1d935293b40ed

@maran-e, latest commit modifies the staged icon colors to green (unstaged remain their config colors which I found useful), it does that for both `git_status` but also for other providers that display git icons (files, grep, etc).

I also limited the new interface with fzf version 0.36 and above, for some odd reason even though `reload` action exists in earlier versions the option is rejected and fzf-lua doesn't open as a result, see #735.

That leaves us with issue (1) which I was able to reproduce with the Linux kernel repo but only if I spam stage/unstage, it seems to be deleted automatically as soon as the stage/unstage succeeds and I never get to the phase of having to manually delete the file, perhaps I can add a safeguard and silently fail the stage/unstage if `.git/index.lock` exists? still testing different solutions.

Btw, what version of fzf/git are you using?

**Comment by maran-e** [comment]
[](url)@ibhagwan 

git - `git version 2.40.0`
fzf - `0.39.0`

For me, `index.lock` wasn't deleted automatically. I assumed it's because new actions kill the git process of old action pre-maturely thus they were not able to delete the `index.lock` file.

Attached a recording for reference,

Can you comment on the possibility of unbinding and rebinding the actions? This seems to solve the issue for me. 

https://user-images.githubusercontent.com/41508542/233826972-fa42798a-1677-4d88-bd18-fdcf7351dddb.mov

**Comment by ibhagwan** [comment]
> Can you comment on the possibility of unbinding and rebinding the actions? This seems to solve the issue for me.

If this works for you I don’t see why we shouldn’t do the same here, Is the solution in the OP with rebind on `load` sufficient?

What about `execute-silent(<cmd>)+reload(…)+rebind(…)`?

> I assumed it's because new actions kill the git process of old action pre-maturely thus they were not able to delete the index.lock file

If this is the cause of this issue unbind|rebind is probably the best course here, alternatively, I can probably temporarily `:tmap` the binds to null until the stage operation returns but it’s less clean than using fzf’s unbind.

**Comment by maran-e** [comment]
> What about execute-silent(<cmd>)+reload(…)+rebind(…)?

This doesn't seem to work for me. `index.lock` is still not deleted properly. Maybe rebinding happens before the command is completed.

> If this works for you I don’t see why we shouldn’t do the same here, Is the solution in the OP with rebind on load sufficient?

If there is no harm in adding this (from fzf 0.36), this solution is sufficient. Please note that all possible actions need to unbound and rebound (not just the action being performed).

It would be wise to keep in mind of possible concurrency issues for actions in other pickers also. If there are any, they can also be solved with similar solution. One can think of this as disabling a button after the button is pressed once in a web UI to prevent multiple network requests being fired.

**Comment by ibhagwan** [comment]
@elamaranae, https://github.com/ibhagwan/fzf-lua/commit/9deb70453cb9f1400b7c70a20d15d06ee15b6068 - should bring this issue to conclustion :-)

**Comment by elamaranae** [comment]
@ibhagwan - It feels robust now. Now I can use the builtin version. I will close this as resolved.

Thank you for taking up the suggestions so quickly 😁. Hoping this provides a better UX for all users.

**Comment by ibhagwan** [comment]
Ty @elamaranae for the great suggestions!

**Comment by ibhagwan** [comment]
@elamaranae, FYI, the latest commit https://github.com/ibhagwan/fzf-lua/commit/2b22ee5fb022a0444707a798a4ab032a34706431 adds new action properties which makes it easier to define "reloading" acitons, althought there is backward compatbility for actions that use `resume` the new way to define the actions uses a `reload` attribute, the new way to define the interface the way you requested in this issue is:
```lua
require("fzf-lua").setup {
  git = {
    status = {
      actions = {
         -- disable left|right (default) binds and replace with a single ctrl-s "reloading" bind
         ["right"]   = false,
         ["left"]    = false,
         ["ctrl-x"]  = { fn = actions.git_reset, reload = true },
         ["ctrl-s"]  = { fn = actions.git_stage_unstage, reload = true },
       },
    }
  }
}
```

**Comment by nyngwang** [comment]
@ibhagwan I tried to upgrade my API for `tabs` like the format you gave above then got an error:

```
E5108: Error executing lua: ...hare/nvim/lazy/fzf-lua/lua/fzf-lua/providers/buffers.lua:430: ...wang/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:779: assertion failed!
stack traceback:
	[C]: in function 'fzf_exec'
	...hare/nvim/lazy/fzf-lua/lua/fzf-lua/providers/buffers.lua:430: in function 'tabs'
	/Users/ningwang/.config/nvim/lua/plugins/nvim_ide.lua:398: in function </Users/ningwang/.config/nvim/lua/plugins/nvim_ide.lua:398>
```

```lua
tabs = {
  actions = {
    default = function(selected, opts) end,
    ['ctrl-x'] = { fn = function (selected, opts) end , reload = true } -- here
  }
}
```

**Comment by ibhagwan** [comment]
@nyngwang, the assertion is correct actions that are of type `string` are invalid and do nothing, if you wish to proxy an fzf action you need to put it under `keymap.fzf`.
