### ISSUE TITLE
Toggling Hidden Files

### ISSUE THREAD

**Issue by barrett-ruth** [ibhagwan/fzf-lua#731]
Hey, I've seen some attempts to figure this out here on fzf (like [here](https://github.com/junegunn/fzf/issues/2717)).

My question is, is it a realistic question to ask whether one can toggle showing hidden files interactively in fzf-lua? I understand if it simply out of the scope of fzf, and thus also out of the scope of this project, but I'm familiar enough with either project to answer that myself.

**Comment by ibhagwan** [comment]
It’s not out of scope, as mentioned in the issue you linked this is easily possible with a `reload` bind, with fzf-lua you can easily do that with an action that changes the `cmd` argument to toggle the hidden flag.

**Comment by barrett-ruth** [comment]
Ok, so this is my approach to the action so far (which is actually correctly altering the cmd):
```lua
                    ['ctrl-h'] = function(_, args)
                        if args.cmd:find '--hidden' then
                            args.cmd = args.cmd:gsub('--hidden', '', 1)
                        else
                            args.cmd = args.cmd .. ' --hidden'
                        end
                        actions.resume()
                    end,
```

How would I go about re-executing the query with this new cmd? actions.resume was my best guess as you can see, but it obviously is not the right thing to call.

**Comment by barrett-ruth** [comment]
Also, I tried to figure out a universal terminal solution that is passed to `FZF_DEFAULT_OPTS` like so:

`--bind=ctrl-h:reload(<stuff that toggles hidden files>)`

but I couldn't figure out how to toggle the hidden files back and forth. Obviously, just inputting `--hidden` will do the job, but won't allow me to change back. If I found a solution to this, there wouldn't even be a need for me to make the above action.

**Comment by ibhagwan** [comment]
> How would I go about re-executing the query with this new cmd? actions.resume was my best guess as you can see, but it obviously is not the right thing to call.

`resme` as the name suggests resume's the last interface so it won't rebuild the `cmd` argument, what you want to do is simply recall `files`, in addition, it's recommended to wrap the action in a table (other than just a function) in order to instruct fzf-lua to not close the interface and reuse the existing window, this will prevent the "flash" of the window closing and reopening:

> I also added `debug=true` so you can see the underlying command piped into fzf
```lua
require("fzf-lua").files({
  debug = true,
  actions = {
    ["ctrl-h"] = {
      function(_, args)
        if args.cmd:find "--hidden" then
          args.cmd = args.cmd:gsub("--hidden", "", 1)
        else
          args.cmd = args.cmd .. " --hidden"
        end
        require("fzf-lua").files(args)
      end
    },
  }
})
```

**Comment by barrett-ruth** [comment]
Thanks! So on the front of just the raw CLI and FZF_DEFAULT_OPTS, it isnt't possible?

**Comment by ibhagwan** [comment]
> Thanks! So on the front of just the raw CLI and FZF_DEFAULT_OPTS, it isnt't possible?

It's possible but a bit more complicated, the way I would go about it is via the `bind|rebind` mehcanism and hardcoded full commands within the bind.

**Comment by ibhagwan** [comment]
In my dotfiles I have a command that toggles between fuzzy mode and regex (similar to `ctrl-g` in fzf-lua), take a look at how it uses `bind|rebind`, might help you get ideas for the hidden toggle:
https://github.com/ibhagwan/dots/blob/f7ab09f21a2b8cfa485571c8a892d88446a7fb57/.config/zsh/fzf_git_functions.sh#L91-L102

**Comment by barrett-ruth** [comment]
Awesome. Thanks for the help as always 🙏
