### ISSUE TITLE
:FzfLua lsp_workspace_symbols doesnt show anything

### ISSUE THREAD

**Issue by I-Own-You** [ibhagwan/fzf-lua#732]
### Info

- Operating System: Kubuntu 22.04
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.9.0
- `fzf --version`: 0.29 (devel)

- [x] The issue is reproducible with `mini.sh`
maybe its reproducible and i just didnt figure it out how to, but i could not

<details>

fzf-lua setup file is too long, its the default configs,
the only thing i changed is that i added --no-ignore and --hidden for files and grep section to find files by .gitignore.
Also added 'telescope' before winopts in the setup func.
</details>

### Description 
So, the problem is that when i use :FzfLua lsp_workspace_symbols on .lua files, it works, but when i use it on python, it flickers the window but doesnt open, also :FzfLua lsp_document_symbols flickers if there are not symbols at all, only when i add one at least. So i have recorded a video so you could understand whats happening.

https://user-images.githubusercontent.com/91146968/232916961-ebc7dd4f-7153-468e-98bf-7bbd07d76ba9.mp4

<h3>Your plugin saves a lot of time btw, nice work.</h3>

**Comment by ibhagwan** [comment]
> > > > That by design, symbols are run in `async` mode as some LSP servers take time to respond, in `async` mode fzf-lua can't tell if there are exisiting symbols so it opens the interface and waits for the symbols, if none are returned it closes.
> > > > If you wish to avoid this behavior set `lsp.symbols.async = false` (in `setup`) or run `:FzfLua lsp_document_symbols async=false`.
> > > > > but when i use it on python, it flickers the window but doesnt open
> > > > 
> > > > 
> > > > The flicker reasoning is the same as I explained above, your python server probably doesn't support a global workspace symbols with no input for query (very commom), use `:FzfLua lsp_live_workspace_symbols` instead, as soon as you start typing something it should display a result (if there are any matches).
> > > 
> > > 
> > > for some reason it really acts sad on python lsps, so ill stick with live option, thank you
> > 
> > 
> > That's an LSP issue though, fzf-lua can't control that, fortunately there are manu different LSP servers for python so you can try different ones.
> 
> nah, all lsp on python are sad, every one of them, ill probably learn rust so i could have nice symbol outlines smile

When you use `rust_analyzer` you'll understand why `async` is important :-)
