### ISSUE TITLE
[Bug] Unable to access files in symlinked Dropbox directory

### ISSUE THREAD

**Issue by akinsho** [ibhagwan/fzf-lua#736]
### Info

- Operating System: macOS Ventura
- Shell: zsh
- Terminal: Kitty
- `nvim --version`: nightly/v0.9.0
- `fzf --version`: 0.39.0

### Description 

Since moving over to `fzf-lua` I've noticed (and ignored for a while) the fact that I'm unable to open any of my notes in my `Dropbox` directory. Each attempt result in `[Fzf-lua] Unable to access '/Users/username/Dropbox/neorg', removing 'cwd' option.`
I've tried running the `fd` and `rg` command in the terminal and that runs fine with fzf, note that this also worked with Telescope.

One thing to note is that `Dropbox` now uses a symlink from the Home directory to the `User/username/Library` directory since macOS now requires apps like dropbox and google drive to be based there but this symlink is presumably for people using it in the CLI.

The command being run is `fzf_lua.files({ cwd = '/Users/username/Dropbox/neorg' })` resolving the symlink doesn't help but also I'm not sure what command exactly is failing i.e. `rg` seems fine as does `fd`. It seems no other mac user has reported this issue though so not sure if there's some user error here but I've never had any issue accessing these directories before 🤔

**Comment by ibhagwan** [comment]
Hi @akinsho,

> It seems no other mac user has reported this issue though so not sure if there's some user error here but I've never had any issue accessing these directories before thinking

I guess it wasn't reported as it's not happening to everyone, I just tested on both Linux and Mac and was able to use `cwd` with links generated using `ln -s`.

The test to see if the directory exists is very simple using `vim.loop.fs_stat`, the code doesn't even check if the target is a directory or a file (therefore links should also be ok'd):
https://github.com/ibhagwan/fzf-lua/blob/9deb70453cb9f1400b7c70a20d15d06ee15b6068/lua/fzf-lua/config.lua#L258-L262

What is the output of `:lua print(vim.loop.fs_stat("/Users/username/Dropbox/neorg"))` on your machine?

**Comment by akinsho** [comment]
🤦🏾‍♂️🤦🏾‍♂️ sorry about this @ibhagwan was in fact user error, I copied over the directory path incorrectly from a previous telescope picker. There was section of the path missing so it didn't exist. Definitely on me, although I'd have expected the error to say "The path doesn't exist", because it says "Unable to access" my mind immediately went to a permissions issue with one of the other tools like `fd` or `rg` or something.

**Comment by ibhagwan** [comment]
> I'd have expected the error to say "The path doesn't exist", because it says "Unable to access" my mind immediately went to a permissions issue with one of the other tools like `fd` or `rg` or something.

That is true but then it wouldn’t cover “access denied” errors, although more vague this does cover both :)
