### ISSUE TITLE
How to start "grep_curbuf" with multiple searches

### ISSUE THREAD

**Issue by edi9999** [ibhagwan/fzf-lua#739]
### Info

- Operating System:
- Shell: bash 5.1.16
- Terminal: xfce4-terminal
- `nvim --version`: 0.9.0
- `fzf --version`: 0.39.0

```lua
:lua require('fzf-lua').grep_curbuf({ search="it(|describe(", grep_opts="-E" })
```

### Description 

I'm trying to search all files that either contain the string "it(" or the string "describe(" (to match all header lines of a test file.

However, this option of "it(|describe(" does'nt work.

The "it(" works alone, but not with the or opearator in regex .

For example, this works well with normal grep  in bash : 

```
printf "describe()\nit()\nfoobar\n" | grep -E 'describe\(|it\('
```

I'm not sure what I should do to match pattern1 or pattern2.

**Comment by ibhagwan** [comment]
You can’t use regex when you’re using `grep_curbuf`, fzf’s fuzzy matching algorithm is used instead, to search for multiple terms just space them out, if you wish to regex match use `lgrep_curbuf` instead.

**Comment by ibhagwan** [comment]
Similarly this is the difference between `grep` (and `grep_ project`) and `live_grep`, you can alternate between the two using `ctrl-g`.

**Comment by edi9999** [comment]
I've found out that I can use this : 

```
    command! FZFIt :lua require('fzf-lua').grep_curbuf({ search="it\\(|describe\\(", no_esc=true })
    " Quick-Nav
    nnoremap <leader>, :FZFIt<CR>
```

**Comment by ibhagwan** [comment]
Closing, lmk if you need more help.
