### ISSUE TITLE
Builtin previewer syntax doesn’t work for certain file types

### ISSUE THREAD

**Issue by ibhagwan** [ibhagwan/fzf-lua#74]

**Comment by ibhagwan** [comment]
Syntax fails to show for certain files, the main reason behind this is filetype detection when the extension of the file doesn’t match neovim’s filetype, for example `*.jl` files should be set to filetype `julia` (not `jl`) which messes up the file detect, at which point neovim would fail to show syntax.

I couldn’t find a way to get filetype from extension inside nvim as this happen with runtime autocmd’s when opening a buffer.

Will require more research.

**Comment by tzachar** [comment]
I also get no syntax highlighting with `*.py` files.

**Comment by tzachar** [comment]
what about something like this:

```diff
diff --git a/lua/fzf-lua/previewer/builtin.lua b/lua/fzf-lua/previewer/builtin.lua
index 94311f4..35e98c3 100644
--- a/lua/fzf-lua/previewer/builtin.lua
+++ b/lua/fzf-lua/previewer/builtin.lua
@@ -170,6 +170,29 @@ local function set_cursor_hl(self, entry)
     cmd(('noa call nvim_set_current_win(%d)'):format(self.win.preview_winid))
 end
 
+local function capture(cmd, raw)
+    local handle = assert(io.popen(cmd, 'r'))
+    local output = assert(handle:read('*a'))
+
+    handle:close()
+
+    if raw then
+        return output
+    end
+
+    output = string.gsub(
+        string.gsub(
+            string.gsub(output, '^%s+', ''),
+            '%s+$',
+            ''
+        ),
+        '[\n\r]+',
+        ' '
+    )
+
+   return output
+end
+
 function Previewer:do_syntax(entry)
   if not self.preview_bufnr then return end
   local bufnr = self.preview_bufnr
@@ -202,7 +225,11 @@ function Previewer:do_syntax(entry)
         -- nvim_buf_call is less side-effects than changing window
         -- make sure that buffer in preview window must not in normal window
         -- greedy match anything after last dot
-        local ext = entry.path:match("[^.]*$")
+
+        -- local ext = entry.path:match("[^.]*$")
+        local ext = capture('file -b --mime-type ' .. entry.path)
+        ext = ext:gsub('.*/', ''):gsub('.*-', '')
+

```

The string matching should be more robust, but is mostly works.

**Comment by ibhagwan** [comment]
The reason it doesn’t work for `.py` is the same, I set the filetype to py when it should be set to python.

About your code:
- Does `file -b —mime-type` equal nvim’s filetypes?
- If I go this route I will def add some caching, once you opened one file extension and understood py=python there is no need to open all other python files.

**Comment by ibhagwan** [comment]
`file -b —mime-type` is not going to work, just tested it on a `.vim` file:

```sh
❯ file -b --mime-type init.vim
text/plain
```

As I wrote in the OP, the only way to find the correct filetype (including the user's autocmds) is the open the file in neovim and get the filetype after the `BufEnter` event.

I'll have to think of a different solution here.

**Comment by jdrouhard** [comment]
You could use plenary's filetype plugin. It was designed for exactly this purpose and is used by telescope to figure out filetypes based on a few things, extension only being one of them. This would work well for people who already have overrides for plenary's filetype detection logic.

This would create a dependency on plenary, but probably isn't the worst idea since it's a pretty core library for a lot of lua plugins.

**Comment by ibhagwan** [comment]
> You could use plenary's filetype plugin. It was designed for exactly this purpose and is used by telescope to figure out filetypes based on a few things, extension only being one of them. This would work well for people who already have overrides for plenary's filetype detection logic.
> 
> This would create a dependency on plenary, but probably isn't the worst idea since it's a pretty core library for a lot of lua plugins.

I know but I’m trying to avoid exactly that, it’s a big library, I’d hate to add this dependency just for this function, I know I can find a better solution.

**Comment by jdrouhard** [comment]
It does solve exactly this issue in a way that people already have customized to their liking...

You can use plenary in such a way that only the filetype part is loaded if you're concerned about performance.

**Comment by ibhagwan** [comment]
> It does solve exactly this issue in a way that people already have customized to their liking...
> 
> You can use plenary in such a way that only the filetype part is loaded if you're concerned about performance.

I know this was the first thing I checked, I’d still like to avoid the dependency if I can.

**Comment by jdrouhard** [comment]
I have an idea that simplifies this and also seems to work a bit better. I'll submit a PR.

**Comment by ibhagwan** [comment]
> I have an idea that simplifies this and also seems to work a bit better. I'll submit a PR.

No need I have a very elegant solution I'm about to commit in the next couple of minutes :-)

**Comment by ibhagwan** [comment]
Should work perfectly now.

https://github.com/ibhagwan/fzf-lua/blob/96bbe334064da65e519249897c8995165861063a/lua/fzf-lua/utils.lua#L293-L309

**Comment by tzachar** [comment]
really nice, works amazingly well.
ty

**Comment by ibhagwan** [comment]
> Not quite :/
> 
> Not all filetype detection is done based on extension alone. A good example is `CMakeLists.txt` files. The solution I had going was even shorter than this, and all it did was simply set the preview buffer's name to the original path prepended with the buffer number, and that one did work perfectly:
> 
> ```lua
> api.nvim_buf_set_name(bufnr, bufnr .. entry.path)
> ```
> 
> Instead of the regex for extension and manual `filetype ext` call. As long as the preview buffer's name is unique (prepend with bufnr) and has the full path of the file, the `filetype detect` call will work correctly in all cases.

You're correct, it's not 100% perfect, I also noticed an issue with my `tags` file (ctags) which isn't recognized now as it has no extension, I'm trying to think of any downside to your approach, if not I can switch to this method (even more elegant).

**Comment by ibhagwan** [comment]
Ty @jdrouhard, absolutely amazing and even more elegant solution than mine :-)

Had to make a minor modification to make it work (prepended it as a "directory" instead) and changed the call method to `pcall` just in case it would fail (for the one in a million case such file would exist lol).

https://github.com/ibhagwan/fzf-lua/blob/1b1de47c573a75f9e628ca64ad84eb4b780b1628/lua/fzf-lua/previewer/builtin.lua#L221-L222
