### ISSUE TITLE
Error when using :FzfLua files

### ISSUE THREAD

**Issue by theniceboy** [ibhagwan/fzf-lua#740]
### Info

- Operating System: macOS 13.3.1 22E261 arm64
- Shell: /bin/zsh 5.9
- Terminal: tmux, iTerm2
- `nvim --version`: 
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```
- `fzf --version`: 0.39.0 (brew)

- [x] The issue is reproducible with `mini.sh`

### Description 
When using the `:FzfLua files` command, I got this error:
```
E5108: Error executing lua ...s/david/.config/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:78: ...s/david/.config/nvim/plugged/fzf-lua/lua/fzf-lua/win.lua:676: title must be string or array
stack traceback:
        [builtin#36]: at 0x0102c80624
        ...s/david/.config/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:78: in function 'run_command'
        ...s/david/.config/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:100: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

**Comment by theniceboy** [comment]
Seems like the issue was introduced here: ad035588ea8b516e1eb447a267ca009bbf2d7c9e

**Comment by ibhagwan** [comment]
> Seems like the issue was introduced here: [ad03558](https://github.com/ibhagwan/fzf-lua/commit/ad035588ea8b516e1eb447a267ca009bbf2d7c9e)

Are you certain this happens with mini.sh? Can you post your config, specifically `winopts` part.

**Comment by ibhagwan** [comment]
@theniceboy, it is as I suspected, remove this line from your config (under your `winopts’):
https://github.com/theniceboy/nvim/blob/1df7e95d3b5f8d0189dffa1a4d6807e6a5f276ae/init.vim#L1052

The reason this worked in the past for you is that the title variable wasn’t in use, it is now passed as is to `nvim_open_win` which expects a string or table.

**Comment by theniceboy** [comment]
Thanks! Sorry I misunderstood mini.sh.
