### ISSUE TITLE
[Question] How to implement live grep with support `--glob` in fzf.vim?

### ISSUE THREAD

**Issue by linrongbin16** [ibhagwan/fzf-lua#742]
Hi fzf-lua author, this question should be an off topic question, but actually I think you're the best one to ask:

I have no idea how to configure fzf.vim to support `--iglob` in live grep. (As an option to `rg`, here's my [fzf.vim config](https://github.com/linrongbin16/lin.nvim/tree/main/repo/junegunn/fzf.vim))

Do you have any idea that I could implement it?

**Comment by nyngwang** [comment]
That's included by default, if I understand your question correctly. This is my note on how to use those grep stuff:

```
usage `[keywords...] --includeKey* --!excludeKey*`, i.e. don't forget the `*`!
```

**Comment by ibhagwan** [comment]
@linrongbin16, as @nyngwang mentioned, it’s supported by default without the need for further customization.

Also see, https://github.com/ibhagwan/fzf-lua/wiki#live-grep-glob

**Comment by linrongbin16** [comment]
Thanks
