### ISSUE TITLE
Window crashes with `fzf error 2` on fresh install

### ISSUE THREAD

**Issue by lyndhurst** [ibhagwan/fzf-lua#744]
### Info

- Operating System: Ubuntu 18.04
- Shell: zsh
- Terminal: Kitty
- `nvim --version`: v0.10.0
- `fzf --version`: 0.24.2
---
### Configuration
- I have just installed the plugin, and not added any configuration.
- I use a very recent barely modified LunarVim configuration (version: `master-b1c72541`).
- I have 'nvim-tree/nvim-web-devicons'  installed and working.

```lua
require('fzf-lua').setup({
})
```
---

### Description 

When I issue a command like `:FzfLua files`, the fzf window flashes for an instant.
Checking the `:messages` shows: `[Fzf-lua] fzf error 2: invalid border style (expected: rounded|sharp|horizon`.

Looking at the `help` file, I tried:
 - `:lua require'fzf-lua'.files({ winopts={border='rounded'} })` 
  - `:lua require'fzf-lua'.files({ winopts={border='none'} })` 
  - `:lua require'fzf-lua'.files({ winopts={border='sharp'} })`
  - I also tried other `FzfLua` commands like `buffers` and so on just to make sure...

I might not have looked hard enough, but I did not find a `winopts` example for "border style" as described in the error message; I only found some `border` options for the preview window and the attempts described above. 

I really hope I am not missing something obvious and wasting your time, but I am not sure what to do next.
Thanks for your help.

**Comment by ibhagwan** [comment]
Upgrade your fzf, as mentioned in the README, minimum version is 0.27.

**Comment by lyndhurst** [comment]
Thanks for the swift reply.
So I did miss something obvious and waste your time. Upgrading `fzf` solved the issue.
I am terribly sorry for not checking the requirements, no more late posting on github for me !

**Comment by ibhagwan** [comment]
> Thanks for the swift reply.
> So I did miss something obvious and waste your time. Upgrading `fzf` solved the issue.
> I am terribly sorry for not checking the requirements, no more late posting on github for me !

Don’t be so harsh on yourself friend, it’s all good, replying didn’t cost me anything :)
