### ISSUE TITLE
[Discussion] Can I add a logger for debugging/develop?

### ISSUE THREAD

**Issue by linrongbin16** [ibhagwan/fzf-lua#745]
Hi,

First thanks for this great work, then, I want to ask if I could submit PR to add a logger (include file logger, and console logger, e.g. command line message) to this project? Because I want to try to use this plugin on windows, may need some debug/develop.

I have a small logger library for neovim: [logger.nvim](https://github.com/linrongbin16/logger.nvim).

Or would you please introduce some methods to easier debug?

**Comment by ibhagwan** [comment]
> Hi,
> 
> First thanks for this great work, then, I want to ask if I could submit PR to add a logger (include file logger, and console logger, e.g. command line message) to this project? Because I want to try to use this plugin on windows, may need some debug/develop.
> 
> I have a small logger library for neovim: [logger.nvim](https://github.com/linrongbin16/logger.nvim).
> 
> Or would you please introduce some methods to easier debug?

Ty for your interest @linrongbin16, would be amazing if you can add windows support.

You don’t need a PR for that, why don’t you fork the project, add your logging and develop using your own fork, when you’re done I’ll be more than happy to accept a PR.
