### ISSUE TITLE
Question: `nvim-dap` how do I passing argument to `:FzfLua dap_commands`?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#746]
### Description 

I'm playing around with nvim-dap recently and I found fzf-lua really useful for replacing my (tons of) keymaps. Now I see that I need to pass some argument to some command, for [example](https://github.com/jbyuki/one-small-step-for-vimkind#configuration):

```lua
vim.api.nvim_set_keymap('n', '<F5>', [[:lua require"osv".launch({port = 8086})<CR>]], { noremap = true })
```

Currently, it seems that we cannot do this in `:FzfLua dap_commands`. (please correct me since I only browse the source a little bit) If this is correct, then here are some different ways in my imagination to support it:

1. After a command got selected, prompt the user to type something, e.g. I could type `{ port=8086 }` and it will be read as a table and passed to the command.
2. After a command got selected, `:lua require"osv".launch` is prefilled in command mode and I will need to type `({ port=8086 })`.

These are just my random thoughts. What do you think?

**Comment by ibhagwan** [comment]
> Currently, it seems that we cannot do this in :FzfLua dap_commands.

Correct, port isn’t an argument yet but I can easily add one assuming the underlying dap call supports it you can call the command like so `FzfLua dap_commands port=xxx`.

I’m currently traveling but if this is what you meant I can look into it when I get a chance.

**Comment by nyngwang** [comment]
> I’m currently traveling

@ibhagwan Fine, enjoy your journey first :) I'm not hurrying with this.

**Comment by ibhagwan** [comment]
@nyngwang, what don’t you overload the default action and do whatever you want with the DAP command?

```lua
require'fzf-lua'.dap_commands({
  actions = {
    ["default"] = function(selected, _)
        require'dap'[selected[1]]({ port = 8086 })
     end,
  }
})
```

**Comment by nyngwang** [comment]
@ibhagwan Thanks, I believe this is the solution. I think I also need to extend it to prompt myself about the port too. (I'm not sure whether the 8086 port is a convention for Lua debug adapter, just copied that from their README)

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if you need more help with this @nyngwang
