### ISSUE TITLE
Fire commands immediately after selection

### ISSUE THREAD

**Issue by LintaoAmons** [ibhagwan/fzf-lua#747]
### Description 

Is it possible to fire the command immediately after I select the command from the `:FzfLua commands`, instead of putting the selected command into the command mode, which requires hitting the enter again?

**Comment by ibhagwan** [comment]
This behavior isn’t controlled by fzf-lua but rather nvim’s pum (popup menu), I’m pretty sure it’s possible via https://github.com/hrsh7th/cmp-cmdline if you’re using nvim-cmp

**Comment by nyngwang** [comment]
I encountered this hours ago. Originally, I was thinking about whether it's possible to prefill `:FzfLua commands` with `Dap` so I can press `<Tab>` to see the list of all commands provided by either nvim-dap or nvim-dap-ui. Out of curious, why extra dependency like hrsh7th/cmp-cmdline is needed in this case? Can't we just `vim.cmd(dap_command_str)` to execute the selected item from the list by `:FzfLua commands`?

**Comment by ibhagwan** [comment]
> Out of curiosity, why extra dependency like hrsh7th/cmp-cmdline is needed in this case? Can't we just vim.cmd(dap_command_str) to execute the selected item from the list by :FzfLua commands?

@nyngwang IMHO your issue is different to which I’ll respond in it’s dedicated issue, as for why nvim-cmd is needed I’m not 100% sure this might be solved using neovim pum behavior but in case it’s not I know you can control completion behavior with nvim-cmp so you can send enter immediately with the completion.

**Comment by nyngwang** [comment]
Can't we skip "pasting the selected command" into the command line/mode? Just like `:FzfLua dap_commands` now: after selection it's executed immediately.

**Comment by ibhagwan** [comment]
> Can't

As I wrote in my previous comments this behavior isn’t controlled by fzf-lua, if you wish to customize it look into neovim’s pum help or nvim-cmp-cmdline.

**Comment by ibhagwan** [comment]
Look at how I configured my own cmp custom completion for `<CR>`, pretty sure you can further customize it to auto fire (send addtl CR) if coming from the command line `:`, perhaps even do it only for FzfLua.

**Comment by nyngwang** [comment]
@ibhagwan In fact, you have implemented this before. Observations:

1. This is the default: https://github.com/ibhagwan/fzf-lua/blob/2dbedc91386a78ce08967135969d39392f7f36d7/lua/fzf-lua/defaults.lua#LL717C34-L717C34
2. Then I found this: https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/actions.lua#L405-L409

with 2., it resolves the title.

(and, hopefully, I wish this could save your vacation :) )

**Comment by LintaoAmons** [comment]
> I encountered this hours ago when trying to switch from manually defining all hard-to-remember keymaps to fzf-lua.

I'm trying to do the same thing. To define my personal commands and just invoke them by FzfLua commands

https://github.com/LintaoAmons/CoolStuffes/blob/main/lvim/.config/lvim/lua/lintao/commands.lua

So this is the reason why I want it just to be fired once I select the command I want.

**Comment by LintaoAmons** [comment]
@nyngwang I saw you already have commits related to this. So I can just update the plugin to have a try? Is this any configuration needed?

**Comment by nyngwang** [comment]
@LintaoAmons Hi, sorry for my late reply. To your first question, No, that PR has not been reviewed yet. To your second question, yes, you can try it before it might be merged: (add this key-table pair to the `setup` of fzf-lua)

```lua
commands = {
  actions = {
    -- see: https://github.com/ibhagwan/fzf-lua/issues/747.
    ["default"] = function (selected)
      vim.cmd(selected[1])
      vim.fn.histadd('cmd', selected[1])
    end
  },
},
```

**Comment by ibhagwan** [comment]
>  In fact, you have implemented this before

@nyngwang, @LintaoAmons, I read this issue from the mobile while traveling and totally misunderstood the issue lol

I read the request as auto-fire for the auto completion of the commands following `:FzfLua …`.

@LintaoAmons, ass the below to your setup:
```lua
require'fzf-lua'.setup({
  commands = {
    actions = { ["default"] =  require'fzf-lua'.actions.ex_run_cr },
  },
})
```

**Comment by LintaoAmons** [comment]
Wow, this is super cool~~ Thx for your help, this is exactly what I want~
