### ISSUE TITLE
A weight system to put the most selected items up front the list

### ISSUE THREAD

**Issue by LintaoAmons** [ibhagwan/fzf-lua#748]
### Description 
This would allow user to get what they want more quickly~

Or maybe just put their last selection as the first item in the list?

**Comment by ibhagwan** [comment]
Assuming you mean the cmd comparison items, similarly to #748, I consider this out of the project’s scope, perhaps it’s possible to control via nvim-cmp?

**Comment by ibhagwan** [comment]
@LintaoAmons, can you expand on what you mean exactly? Do you mean for a specific provider (buffers, files,  oldfiles, etc)? Or do you mean the auto-complete after `:FzfLua …`?

**Comment by LintaoAmons** [comment]
- Yes, For example, after I triggered the `GitListCurrentFileCommits`
    - <img width="1421" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/95092244/a71ca198-e4c9-4ee2-a6fa-4b626c095604">

- Next time, instead of show all the commands in alphabetical order.
    - <img width="1349" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/95092244/008ad6fe-cb23-4f73-9003-3ff7c4a041b2">

- It shows the most used commands(last used) at the top.
    - <img width="769" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/95092244/9674184a-616c-4880-9835-3abfc682971a">

**Comment by ibhagwan** [comment]
The  `commands` provider lists all existing commands wether executes or not, why don’t you use `command_history` instead?

**Comment by teto** [comment]
I had planned to submit a similar feature request, e.g., support frecency or anything similar in fzf-lua like telescope does https://github.com/nvim-telescope/telescope-frecency.nvim/ . 

My interrogation is whether that feature should live in fzf-lua or maybe even more general, in fzf itself

**Comment by sirfz** [comment]
I agree, ability to have the results ordered by some kind of weight that pushes more frequently accessed files/results to the top would be extremely useful. I believe LeaderF had something like this and it was really convenient.

**Comment by ibhagwan** [comment]
@teto, @sirfz, file sorting is a different issue, sorting is controlled by the binary producing the output (e.g. `rg`, `fd`), the best solution would be to find an external binary that would produce freecency-like output and use that as the `cmd`, any solution that requires running an algorithm within neovim would have a performance impact that would negate all the benefits of using external processing with fzf-lua. Perhaps there is something similar to [zoxide](https://github.com/ajeetdsouza/zoxide) but for files?

> It firstly show all the commands that used before, then if user start to type in some thing, it search from all the commands

@LintaoAmons, what you’re asking is a combination of `commands` and `command_history`, what if the commands use arguments? Does it also display the arguments? What if the same command is used twice with difference arguments, does it appear once or twice and with which arguments? This probably has a few more nuances than just a simple sort.

**Comment by LintaoAmons** [comment]
Unlike other editor(IDE), such as Vscode, IDEA, or the note taking app Obsidian which commands don't take any arguments, making search commands(actions) and just preform the action very intuitive, neovim's commands tend to have different arguments to perform different behaviour.

I don't think this is good since most of the case, in editor not terminal we don't have help to know want the arguments aims for. 

- For example, in Vscode, commands tend to have same prefix and search only one time can perform the specific behaviour. Instead of search a command and then search/type another time to do what user want.
     - ![image](https://github.com/ibhagwan/fzf-lua/assets/95092244/963987e4-10da-420d-809f-bbfd3f90f017)
- The same in the Obsidian
    - ![image](https://github.com/ibhagwan/fzf-lua/assets/95092244/c746e23a-0261-471f-9e2d-672362083dcf)
- In IDEA, if there's subcommand, it show's a popup to let user select the subcommands, I thought Fzf-Lua do the same thing in some scenarios? I remember I watched some video that show this kind of behaviour.
    - ![commands](https://github.com/ibhagwan/fzf-lua/assets/95092244/6252379a-21e7-47d8-bbae-aca7aa5e0a0b)

But since you told me how to configure to run the command after select it, I'm currently very satisfied with this solution.

Since I could write some customised commands which already mapping to commands with specific subcommands to achieve my goal~
> https://github.com/LintaoAmons/CoolStuffes/blob/main/lvim/.config/lvim/lua/lintao/commands.lua

**Comment by ibhagwan** [comment]
> I remember I watched some video that show this kind of behaviour.

Not sure which would fall into this category, maybe `:FzfLua builtin`?

> But since you told me how to configure to run the command after select it, I'm currently very satisfied with this solution.

Does that mean the if we only add a simple sort to the current `commands` based on last used commands **and no arguments** - would that be what you’re after? If so l this is something I can pretty easily add by prioritizing the used commands and listing them on top.

**Comment by LintaoAmons** [comment]
Yes，you are really kind ~

**Comment by ibhagwan** [comment]
> Yes，you are really kind ~

Ty! np, might take a while since I’m still traveling but perhaps next week.

**Comment by ibhagwan** [comment]
@LintaoAmons, updated to the latest commit and run:
```lua
:FzfLua commands sort_lastused=true
```

You can also set it permanently through `setup` if you prefer to not have to specify the option with each call:
```lua
require("fzf-lua").setup({
  commands = { sort_lastused = true },
})
```

I also changed the issue's title to reflect the change.
