### ISSUE TITLE
Support ctrl-e to edit for command_history and search_history

### ISSUE THREAD

**Issue by mcchrish** [ibhagwan/fzf-lua#75]
fzf.vim:
<img width="286" alt="Screen Shot 2021-08-31 at 5 27 05 PM" src="https://user-images.githubusercontent.com/7200153/131478494-24fab3e3-0903-4e8e-9f32-f1815dc69764.png">

**Comment by ibhagwan** [comment]
Shouldn’t be hard to add, since history has no actions why not set edit as the default action?

**Comment by ibhagwan** [comment]
I actually forgot what I did there, now that I look at the code I see that the default action puts the command in the `:` mode without pressing enter, isn't that the same as editing with `fzf.vim`, what is the exact behavior you're after?

I can add similar functionality to search history so it will input the search term for you but without "<CR>" so you can continue typing to modify the search term - is this what you're after?

**Comment by mcchrish** [comment]
`fzf.vim`'s default action is to execute the command immediately while c-e will just input the selected the commandline. I think this is the better default.

**Comment by ibhagwan** [comment]
> `fzf.vim`'s default action is to execute the command immediately while c-e will just input the selected the commandline. I think this is the better default.

I agree, it feels more consistent too, just committed the change, update your plugin and you'll have it the way you want.

**Comment by mcchrish** [comment]
Thanks! I'll try it out.

**Comment by ibhagwan** [comment]
> Thanks! I'll try it out.

Great lmk what you think of the new `blines` as well.
