### ISSUE TITLE
Set filetype fzf for all buffers

### ISSUE THREAD

**Issue by uga-rosa** [ibhagwan/fzf-lua#752]
I have it set to highlight trailing spaces only when the filetype is markdown, but when I run `:FzfLua` in a markdown file, it highlights them like this. 

- In README.md
![image](https://github.com/ibhagwan/fzf-lua/assets/82267684/349ecca1-a416-48d3-baa9-1180ae357b59)

This does not happen with other file types.

- In LICENSE
![image](https://github.com/ibhagwan/fzf-lua/assets/82267684/ed9ab341-b065-4fcf-bd6a-70f1159dbfb1)

**Comment by ibhagwan** [comment]
@uga-rosa, can you post the part of your config causing this? The main fzf window is set to `ft=fzf`, I’d like to see the autocmd responsible for this so I can test it and understand why this happens.

**Comment by uga-rosa** [comment]
minimal/init.lua
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

vim.opt.termguicolors = true

require("lazy").setup({
  {
    "uga-rosa/trailing-whitespace",
    config = function()
      require("trailing-whitespace").setup({
        enable = { "markdown" },
      })
    end,
  },
  { "ibhagwan/fzf-lua" },
})
```

**Comment by uga-rosa** [comment]
I was looking into this because I had a similar problem with another plugin, but it appears that the FileType is not yet updated at these events.
https://github.com/uga-rosa/trailing-whitespace/blob/8ad137cb55a819334b6887c697b574a4a4ba445c/lua/trailing-whitespace/init.lua#L6
I will fix it. Sorry for the inconvenience.

**Comment by ibhagwan** [comment]
Ty for the update @uga-rosa
