### ISSUE TITLE
Question: How to make `FzfLua live_grep` using `Fuzzy Search` as default

### ISSUE THREAD

**Issue by LintaoAmons** [ibhagwan/fzf-lua#753]
### Description 

How to make `FzfLua live_grep` using `Fuzzy Search` as default~

Current default is Regex Search

![image](https://github.com/ibhagwan/fzf-lua/assets/95092244/815ab4df-db50-4c3b-be6e-3ec8e0d10389)

**Comment by ibhagwan** [comment]
`live_grep` is regex and passes the query directly to `rg`, there is no way to make it fuzzy, what you’re looking for is to start from `grep` or `grep_project` (when you switch to fuzzy, fzf-lua runs `grep({ search = <query> })`:

 https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep

**Comment by LintaoAmons** [comment]
Thx~
