### ISSUE TITLE
[Feature] Allow using a function to `register_ui_select`

### ISSUE THREAD

**Issue by akinsho** [ibhagwan/fzf-lua#755]
### Description 
This relates somewhat to https://github.com/ibhagwan/fzf-lua/issues/717 where in that issue the OP was trying to get access to the options passed to the `ui.select` function so that they could change the behaviour of the previewer. In my case I'd like to do something similar but rather than change a previewer, I'd like instead to use the prompt that was passed in as the title of the window.

Rather than just solve that specific use case though I thought it would be quite helpful to allow a more flexible pattern for future variations of this request could also be solved e.g.

```lua
require('fzf-lua').register_ui_select(function(the_opts)
	local width = the_opts.kind == "codeaction" and small_width or medium_width
	local position = the_opts.kind == "codeaction" and "cursor" or "editor"
	return {
		previewer = CustomPreviewer(the_opts),
		winopts = {
 			title = the_opts.prompt,
			width = width height = 0.33,
			row = 0.5,
			relative = positions
		 },
	}
end)
```

I think this pattern would allow completing customising how the `ui_select` looks based on the current case.

**Comment by ibhagwan** [comment]
Hi @akinsho, this makes sense, I’m currently traveling so might take me a couple of days to get to it though.

**Comment by akinsho** [comment]
Awesome thanks 🙌🏿
