### ISSUE TITLE
Respect wildignore when finding files

### ISSUE THREAD

**Issue by DanielSiepmann** [ibhagwan/fzf-lua#757]
### Info

- Operating System: Ubuntu, NixOS
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.9.0
- `fzf --version`: 0.40.0

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
    fzf_bin = "fzf-tmux",
    fzf_opts = {
        ["--border"] = "rounded",
    },
    fzf_tmux_opts = {
        ["-p"] = "",
        ["-y"] = "1",
        ["-w"] = "95%",
        ["-h"] = "75%",
    },
    winopts = {
        preview = {
            hidden = "hidden", -- I don't like a preview, keep space for selection
        },
    },
    files = {
        -- TODO: Find a way to add wildignore support
        find_opts = [[-type f -not -path '*/\.git/*' -not -path '*/fileadmin/*' -not -path '*/typo3conf/l10n/*' -not -path '*/typo3temp/*' -not -name '*\.orig' -not -path '*/node_modules/*' -not -path '*/imgserver/*' -not -path '*/typo3export/*' -not -path '*/acceptance_tests/_output/*' -printf '%P\n']],
    },
})

require("fzf-lua").register_ui_select()
```
</details>

### Description 

I'm coming from https://github.com/ctrlpvim/ctrlp.vim/ which supports vims `wildignore` out of the box for finding files. It would be cool if this would also be supported by fzf-lua out of the box. Or if there would be a copy and paste example for users not familiar with lua within the wiki.

**Comment by ibhagwan** [comment]
Unforuntaely, using `wildignore` directly isn't an option. that said you can ignore files/globs in many different ways.

(1) when using `fd` and `rg`, `.gitignore` is respected.

(2) You can suppoy the ignore patterns yourself, for example when using `rg`:
```lua
:lua require("fzf-lua").files({ cmd = "rg --color=never --files --hidden --follow -g '!.git'" })
```
Or when using `fd`:
```lua
:lua require("fzf-lua").files({ cmd = "fd --color=never --type f --hidden --follow --exclude .git" })
```

(3) You can also supply `file_ignore_pattens`  and use [lua-style regex](https://fhug.org.uk/kb/kb-article/understanding-lua-patterns/), for example, ignoring all `.lua` files:
```lua
:lua require("fzf-lua").files({ file_ignore_patterns = { "%.lua$" } })
```
More info [on the wiki](https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-ignore-specific-file-patterns)

If I were in your position I'd create a smal lual function that converst `wildignore` to `file_ignore_patterns` compatible lua regexes and use that in fzf-lua `setup`:
```lua
local function wildignore2lua()
  local ret = {}
  for _, p in ipairs(vim.split(vim.o.wildignore, ",")) do
    -- convert wildignore glob to lua regex
    local regex = ...
    table.insert(ret, regex)
  end
  return ret
end

require("fzf-lua").setup({
  -- other setup options
  ...
  file_ignore_patterns = wildignore2lua(),
})
```

> It would be cool if this would also be supported by fzf-lua out of the box. Or if there would be a copy and paste example for users not familiar with lua within the wiki.

Lua is a very simple and efficient language, my recomendation would be to learn some lua, the investment will pay itself.

**Comment by DanielSiepmann** [comment]
Thanks for your comprehensive answer.

> (1) when using `fd` and `rg`, `.gitignore` is respected.

That won't solve my own needs. I use `git_files()` for that. I use `files()` when I need files not tracked by git, e.g. find files from dependencies.

> (2) You can supply the ignore patterns yourself, for example when using rg:

That's what I already did in my pasted configuration. But that would mean I duplicate my `wildignore` settings a 2nd time.

```lua
    files = {
        -- TODO: Find a way to add wildignore support
        find_opts = [[-type f -not -path '*/\.git/*' -not -path '*/fileadmin/*' -not -path '*/typo3conf/l10n/*' -not -path '*/typo3temp/*' -not -name '*\.orig' -not -path '*/node_modules/*' -not -path '*/imgserver/*' -not -path '*/typo3export/*' -not -path '*/acceptance_tests/_output/*' -printf '%P\n']],
    },
```

> (3) You can also supply file_ignore_pattens and use [lua-style regex](https://fhug.org.uk/kb/kb-article/understanding-lua-patterns/), for example, ignoring all .lua files:

Sounds better than 2, but still I would need to maintain the same set twice, once for wildignore and for fzf-lua.

> If I were in your position I'd create a small lual function that converts wildignore to file_ignore_patterns compatible lua regexes and use that in fzf-lua setup:

That's exactly what I would like to have. My request probably wasn't explained well. I'll give it a try.
The option `file_ignore_patterns` is not mentioned within "Default Options". Also the help file doesn't mention the option. How would I know this exists?

> Lua is a very simple and efficient language, my recomendation would be to learn some lua, the investment will pay itself.

Maybe too simple. I'm missing many features coming from other programming languages. They might be hidden behind other features which I don't understand by reading the manual. Or they are not part of the default library which looks pretty small. Also, not everyone using Neovim might be a programmer and willing to learn Lua as a language to get things done that could be configured globally within the editor already. So that snippet as copy and paste solution is cool.

**Comment by ibhagwan** [comment]
> That's exactly what I would like to have. My request probably wasn't explained well. I'll give it a try.
The option file_ignore_patterns is not mentioned within "Default Options". Also the help file doesn't mention the option. How would I know this exists?

 From the WiKi: https://github.com/ibhagwan/fzf-lua/wiki#how-do-i-ignore-specific-file-patterns

> Also, not everyone using Neovim might be a programmer and willing to learn Lua as a language to get things done that could be configured globally within the editor already. So that snippet as copy and paste solution is cool.

That’s why the basics along with sane defaults are provided out of the box, there will always be that one use case that requires some programming effort, especially when using an editor targeting programmers.

**Comment by ibhagwan** [comment]
I clicked close by mistake, lmk if you need more help with the snippet.
