### ISSUE TITLE
Octo.nvim integration questions

### ISSUE THREAD

**Issue by milogert** [ibhagwan/fzf-lua#759]
### Description

This is just a holding ticket for [Octo.nvim](https://github.com/pwntester/octo.nvim) integration questions. Tasks are listed below. They are based off of the stubs here: https://github.com/pwntester/octo.nvim/blob/1c9a79412a1d92dd3c5a601e2261c158ebb4d4bd/lua/octo/pickers/fzf-lua/provider.lua

### Tasks

- [x] Issues
- [x] PRs
- [x] Gists
- [x] Commits
- [x] Review Commits
- [x] Changed Files
- [x] Pending Threads
- [x] Project Cards
- [x] Project Columns
- [x] Labels
- [x] Assigned Labels
- [x] Users
- [x] Assignees
- [x] Repos
- [x] Search
- [x] Actions
- [x] Issue Templates

**Comment by milogert** [comment]
Ok question the first: How can I open the buffer that is in the preview section in the main neovim window?

Are there specific requirements for it? My entries do not look like file paths (they are formatted like `issue_number issue_title`) but I have tried setting file names, copying lines, etc but nothing seems to work quite right.

I might be completely missing something too. For clarity, I am extending the `builtin.buffer_or_file`

**Comment by ibhagwan** [comment]
> Ok question the first: How can I open the buffer that is in the preview section in the main neovim window?

I don’t understand what you’re asking… what do you mean the buffer that is in the preview section? The preview buffers are temp buffers and get wiped when the preview exits.

> My entries do not look like file paths

Your entries can be whatever you want them to be, format the string to be descriptive and parse-able so you can extract data from the entry if you need to preview/action.

> For clarity, I am extending the `builtin.buffer_or_file`

If I’m understanding correctly your entries aren’t files, in this case why are you extending ‘buffer_or_file`? Extend the base previewer instead and use `populate_preview_buffer` to fill the preview buffer with contents of your choosing.

Just to be on the same page, this integration should eventually be a PR for octo nvim, **not fzf-lua**.

**Comment by ibhagwan** [comment]
Perhaps you should also join forces with @mhanberg as they might also be working on this ATM? 
https://github.com/pwntester/octo.nvim/issues/206#issuecomment-1536706372

**Comment by mhanberg** [comment]
I have not started any work yet, but I am open to contributing to this effort!

**Comment by milogert** [comment]
> Just to be on the same page, this integration should eventually be a PR for octo nvim, not fzf-lua.

Yep, that's my understanding too. I was using this as a spot to ask you questions about fzf-lua but once I have some changes ready they'd go to Octo.nvim.

> The preview buffers are temp buffers and get wiped when the preview exits.

Ok, I didn't understand how fzf-lua and Octo.nvim were supposed to work. I think I figured it out now. The fzf-lua action I'm performing is just opening a regular buffer with the filename as `octo://some/data/here` which Octo.nvim figures out.

> Perhaps you should also join forces with @mhanberg as they might also be working on this ATM?

Yeah, I'll reach out to them, hopefully they see these messages though!

**Comment by milogert** [comment]
Ok I've got a number of functions working in my personal config. I'm going to convert them over to my Octo.nvim fork and submit a draft PR.

They are still rough-ish, but they _work_ which is a big step.

The main issue I can see with what I did is the entries are kind of ugly. Octo.nvim uses a key called `ordinal` to identify each item uniquely by string. Most often it's formatted like `<id> <friendly name>`. So for PRs it would look like `120 add: fzf-lua to Octo.nvim`, which is pretty friendly. But when you have things like project boards they get a lot uglier (i.e. their ids are not very human friendly, and you'd never filter by them in fzf). The reason I'm using these is that it makes it really convenient to look up the relevant data to give Octo.nvim.

Obviously switching the order could help (like `<name> (<id>)` and make the keys in the data lookup table same format, but I'm wondering if there's a way to eliminate the id in cases where we'd never want to see it. What I'm sort of getting at here is if it's possible to have an entry in fzf-lua to be a table of data structures and not just a table of strings (I don't think it's possible right now, but that would be a cool addition to fzf.lua).

🤷‍♂️ That's where I'm at, thanks for listening to my ramblings. I'll get a PR up hopefully this morning but otherwise this evening

**Comment by ibhagwan** [comment]
> The main issue I can see with what I did is the entries are kind of ugly. Octo.nvim uses a key called ordinal to identify each item uniquely by string. Most often it's formatted like <id> <friendly name>.

What I would suggest is to our all the “ugly” data (id/key/etc) at the start of the entry and then use  fzf’s `--with-nth` flag to hide the data, the entries will look pretty and you’d still be able to parse the ID from the entry when using previews/actions, you can see that in action in a few providers, for example the `blines` provider hides the filename as it only cares about the current file, the default options are:
https://github.com/ibhagwan/fzf-lua/blob/c56cd5c9e84e724ed6c707a4a7fc71ccfb0c6c1d/lua/fzf-lua/defaults.lua#L455-L459

Disable the default nth to see the full entry:
```lua
:lua require('fzf-lua').blines({ fzf_opts = { ["--with-nth"] = false } })
```

**Comment by milogert** [comment]
Thanks for the above, I didn't realize those were just display options. That's extremely helpful to understand.

Semi related: is it possible to colorize certain parts of the entry line? For instance, it would be cool to have a PR number be a different color than the PR title

**Comment by ibhagwan** [comment]
> Thanks for the above, I didn't realize those were just display options. That's extremely helpful to understand.
> 
> Semi related: is it possible to colorize certain parts of the entry line? For instance, it would be cool to have a PR number be a different color than the PR title

Yes, you can use terminal ansi escape sequences to use any color you want and even bold/italic/underline/etc.

Look into `utils.ansi_colors` for the basic colors and `utils.ansi_from_hl` to convert a neovim highlight to its terminal equivalent.

**Comment by ibhagwan** [comment]
@milogert, I took a quick look at what you've written so far in https://github.com/pwntester/octo.nvim/pull/396, looks great :-)


Allow me to make a few small suggetsions:

- Since most of your actions are only using a single item it would be advisable to disable multi-select (tab by default) by adding `["--no-multi"]  = ""` to `fzf_opts`.
- In actions that reopen the fzf-lua interface (e.g. `project_columns`), it's better to wrap the action within a table `{}`, that tells fzf-lua to reuse the neovim windows instead of recreating the windows, this is merly a cosmetic change (preventing a window "flash") but an important one IMHO.

So instead of:
```lua
['default'] = function (selected_project)
end
```
Use:
```lua
['default'] = {
  function (selected_project)
  end,
  -- can split into/add more functions which will be executed serially
}
```
If you're simply reopneing **the same interface** you can also utilize fzf-lua's `resume`, this is also mentioned  [in the wiki](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-act-resume).

**Comment by milogert** [comment]
> * Since most of your actions are only using a single item it would be advisable to disable multi-select (tab by default) by adding `["--no-multi"]  = ""` to `fzf_opts`.

Done. I added a TODO in a few of them where multi select might be useful in the future once I am more solid with work done (i.e. opening several pull requests in vertical splits at a time, etc).

> * In actions that reopen the fzf-lua interface (e.g. `project_columns`), it's better to wrap the action within a table `{}`, that tells fzf-lua to reuse the neovim windows instead of recreating the windows, this is merly a cosmetic change (preventing a window "flash") but an important one IMHO.

Nice! I added your suggestion. Why does that happen though? Or is just some fzf-lua thing that knows to keep the window around. No flickering is great.

> * Not sure if this applies with `octo.nvim` but for providers that take longer to load (perhaps executing external github queries?) it's worthwhie to supply a `function` as the `contents` argument and use a `coroutine` to populate the fzf interface for a better UI experience, fzf will open immeidietly and display the loading icon until all entries are loaded, see [the advanced wiki](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-cont-fnc) for more info and play around with the examples to see the difference it makes.

I added a `stream_cb` here https://github.com/pwntester/octo.nvim/pull/396/files#diff-ef4ee25827d4565dceaefe93a386ceee4ecdd267580bf0e0c96e6ab750b6ba96R102-R106 and I'm using it here. That helps a lot with slow loading, but I still don't see the spinner in fzf. Could this be a config/icon/version thing? I don't think I'm turning anything off in my PR and my global config in my editor isn't really anything.

**Comment by ibhagwan** [comment]
> Nice! I added your suggestion. Why does that happen though? Or is just some fzf-lua thing that knows to keep the window around. No flickering is great.

This is by design, actions are mostly triggered after fzf is exited, the assumption (by the code) when using a table is that more than one action will be used and one of them will reuse the interface, I found this approach the cleanest.

> but I still don't see the spinner in fzf. Could this be a config/icon/version thing?

The reason you aren’t seeing it is because fzf-lua defaults adds `--info=inline`, with inline info the loading indicator is simply a different color of the `<` sign post the query prompt, if you wish to see the full loading indicator add `["--info"]  = "default"` to your `fzf_opts`.

**Comment by ibhagwan** [comment]
Amazing work btw, @milogert :)

**Comment by milogert** [comment]
Thank you! I really appreciate it. It always helps to have someone answer my questions :)

I think that's all my questions now. Now to get a review on Phase One..

And if you have any feedback for how I'm using fzf-lua I'm definitely open to it

**Comment by milogert** [comment]
Phase 1 has been merged! Thanks for your help @ibhagwan.

I have another question/ramble: is there a way to readjust the contents after they have been loaded? For instance, the Telescope implementation acts more like a table than just a line of text, so you can set column widths on sections of data. In the screenshot below all of those columns (repo, public/private status, stargazers, forks, and description) are aligned in Telescope.

<img width="708" alt="Screenshot 2023-06-02 at 8 24 24 AM" src="https://github.com/ibhagwan/fzf-lua/assets/5378535/37b0d363-4a55-421b-b84d-eb22441fe342">

Part of the problem I'm running into is fetching some data ends up with different max column widths for each batch, so the columns of data aren't aligned (I'm using fzf_exec with a function to stream the results in).

There are a couple things I could do:

1. Try to rearrange the line to align _most_ of the data. This would end up having weird data at the start (the stuff I'm working with now is the repos, so putting the "fork" status at the start of the line helps with alignment but is also less important than the name.
2. Don't batch the data. This is less desirable since it reduces responsiveness.
3. Stop trying to align the columns. fzf will find them no matter what.
4. Use a previewer. This has the added advantage of being able to include way more data. 

Also something I ran into was searching on long lines could end up chopping off the start of the line, which is the most important piece of data. This is hard to explain, but in the screenshot below you can see I searched for something but I have no clue what the three lines actually indicate.

<img width="748" alt="Screenshot 2023-06-02 at 8 15 00 AM" src="https://github.com/ibhagwan/fzf-lua/assets/5378535/1e70c27b-bf56-46f9-bf6d-522c28b1ae1c">

Perhaps I should just stop including a description in there? But that could be helpful to search on 🤷‍♂️ 

My first goal with all this is to have feature parity with the Telescope implementation, but if there is just a completely different flow of data that makes this not possible that's totally fine with me! I just don't know it yet

**Comment by milogert** [comment]
Ok so related to ☝️ I think I found a happy medium. I am only keeping stuff that's worth searching on the line but adding a previewer with a title to the repo view so you can see all the data you want.

Now I am hitting another error.. I am getting a "Failed to set buffer N" when moving up and down between the items. I see this is a nvim-produced error but I am not sure why. Is there something I should do to clean the buffers out before switching to another entry in the results list?

**Comment by milogert** [comment]
This is the stacktrace I get

```
Error executing vim.schedule lua callback: ...ack/myNeovimPackages/start/fzf-lua/lua/fzf-lua/utils.lua:673: Failed to set buffer 12
stack traceback:
        [C]: in function 'nvim_win_set_buf'
        ...ack/myNeovimPackages/start/fzf-lua/lua/fzf-lua/utils.lua:673: in function 'win_set_buf_noautocmd'
        ...Packages/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:150: in function 'set_preview_buf'
        ...plugin-octo-nvim/lua/octo/pickers/fzf-lua/previewers.lua:298: in function 'populate_preview_buf'
        ...Packages/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:260: in function 'populate_preview_buf'
        ...Packages/start/fzf-lua/lua/fzf-lua/previewer/builtin.lua:286: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I'm guessing the line is https://github.com/ibhagwan/fzf-lua/blob/0f953fd7a35d22e1409d5ce77bbacef9cf07e2cb/lua/fzf-lua/utils.lua#L674

**Comment by ibhagwan** [comment]
> `...plugin-octo-nvim/lua/octo/pickers/fzf-lua/previewers.lua:298`

I’m assuming this new code you’re currently testing because I tried to find line `298` in https://github.com/pwntester/octo.nvim/blob/master/lua/octo/pickers/fzf-lua/previewers.lua and it’s not there yet.

I’m not sure why this happens I’d have to take a look at the entire code, the error message is also very opaque, neovim doesn’t tell us why this fails (window is no longer valid, etc).

**Comment by ibhagwan** [comment]
> Hey, sorry for the late response. I'm moving this week so things have been hectic. I finally got changes pushed up here [pwntester/octo.nvim#404](https://github.com/pwntester/octo.nvim/pull/404). That contains the code where I'm encountering the error I posted above.

No rush @milogert, the stack trace shows line 298 and it seems the code has changed a bit since then, a couple questions:
- Is it a single previewer where the switch isn't working or all of them?
- If a single previewer, is it the `gist` that's failing (L285) or `repo` (L321)?

**Comment by milogert** [comment]
Ah, of course it changed 🤦‍♂️ 

The previewer that's busted for me is the repo one, accessed via `:Octo repo list` and then scrolling from one entry to another

**Comment by ibhagwan** [comment]
Hi @milogert, I was able to solve this issue by commenting these lines:
https://github.com/milogert/octo.nvim/blob/f82f4dfcb9231d1ae319f389dfa659f53142834a/lua/octo/pickers/fzf-lua/previewers.lua#L306-L309.

I'm not sure why these are needed here as you don't seem to use this anywhere but with `repo` and `review_thread` (which I suspect has the same issue).

In addition due to the async nature of `gh.run` you need to add a test to make sure you're writing to the correct buffer and that it's still valid:
```lua
    gh.run {
      args = { "api", "graphql", "--paginate", "--jq", ".", "-f", string.format("query=%s", query) },
      cb = function(output, stderr)
        -- when the entry changes `preview_bufnr` will also change (due to `set_preview_buf`)
        -- and `tmpbuf` within this context is already cleared and invalidated
        if self.preview_bufnr == tmpbuf and vim.api.nvim_buf_is_valid(tmpbuf) then
          local resp = vim.fn.json_decode(output)
          writers.write_repo(tmpbuf, resp.data.repository)
        end
      end,
    }
```

Another issue I found (which isn't limited to fzf-lua) was that `write_repo` has an additional async function call within which adds the README to the preview once it was retrieved, you also need to make sure the buffer is still valid before calling `nvim_buf_set_lines`, https://github.com/milogert/octo.nvim/blob/f82f4dfcb9231d1ae319f389dfa659f53142834a/lua/octo/ui/writers.lua#L158-L161.


Without the below change switching to a new entry before the README is written into the preview will result in an exception, the modified code should look like:
```lua
  utils.get_file_contents(repo.nameWithOwner, repo.defaultBranchRef.name, "README.md", function(lines)
    if vim.api.nvim_buf_is_valid(bufnr) then
      vim.api.nvim_buf_set_lines(bufnr, -1, -1, false, lines)
    end
  end)
```

**Comment by milogert** [comment]
> Hi @milogert, I was able to solve this issue by commenting these lines:
> https://github.com/milogert/octo.nvim/blob/f82f4dfcb9231d1ae319f389dfa659f53142834a/lua/octo/pickers/fzf-lua/previewers.lua#L306-L309.

Alright after finally getting back to this I did some debugging. This is the line in question that's causing the error. I read the help docs and based `acwrite` and the error coming from fzf.lua, I'm assuming something else is trying to write to the buffer besides `BufWriteCmd`s.

> In addition due to the async nature of gh.run you need to add a test to make sure you're writing to the correct buffer and that it's still valid:

Thank you! This was a good catch. There were a few other spots in the same file that I needed to add this check.

> Another issue I found (which isn't limited to fzf-lua) was that write_repo has an additional async function call within which adds the README to the preview once it was retrieved, you also need to make sure the buffer is still valid before calling nvim_buf_set_lines, https://github.com/milogert/octo.nvim/blob/f82f4dfcb9231d1ae319f389dfa659f53142834a/lua/octo/ui/writers.lua#L158-L161.

I updated this locally and plan on including it in my PR. It seems pretty innocuous and a good safety change.

**Comment by ibhagwan** [comment]
> Alright after finally getting back to this I did some debugging. [This is the line in question](https://github.com/milogert/octo.nvim/blob/f82f4dfcb9231d1ae319f389dfa659f53142834a/lua/octo/model/octo-buffer.lua#L241-L241) that's causing the error. I read the help docs and based `acwrite` and the error coming from fzf-lua, I'm assuming something else is trying to write to the buffer besides BufWriteCmds.

I did notice you weren’t using the `configure` code in most other previewers, I’m unfamiliar with Octo’s code, is it required? If so what’s the purpose of using `acwrite`? Perhaps the call can be skipped?

**Comment by milogert** [comment]
I can ask in the new draft PR. I am not _really_ sure what it's for but it seems like it's just making the preview buffer more Octo-friendly (whatever that means, I just made up that term). The reason it's used in the `review_thread` previewer is because it's used in the Telescope version.

The `repo` previewer... Was added by me. After looking more closely the README doesn't get highlighting if I don't call `buffer:configure()`. 🤷‍♂️ More information will be useful here

**Comment by milogert** [comment]
For the sake of not getting off track [in the pr](https://github.com/pwntester/octo.nvim/pull/404#issuecomment-1598937301), I'll ask my question here:

Can you focus the preview buffer somehow? I just assumed it was a read-only buffer for some reason 😕 but I don't know why I thought that

**Comment by ibhagwan** [comment]
> Can you focus the preview buffer somehow? I just assumed it was a read-only buffer for some reason 😕 but I don't know why I thought that

Technically you can use `nvim_set_win` but I think I disabled focusing on the preview buffers, the question is why would you need to? For local window/buffer calls you can call `nvim_win_call` and `nvim_buf_call` respectively.

**Comment by milogert** [comment]
Ok that's clear. You can but it's designed so that you probably wouldn't. The reason I asked is because setting up that `OctoBuffer` make it so you can like edit things and save them to GitHub (by way of the `OctoBuffer`), but it's just in the preview window

**Comment by milogert** [comment]
I don't think there is anything for you to do here tbh. I agree with your assessment about how unintuitive it would be. I was sort of just asking questions

**Comment by milogert** [comment]
Well the second phase got merged in, so this is essentially complete.

One thing that can get addressed is the slowness in the search. I don't know where the issue actually lies, but the `gh` binary isn't the fastest so it very well could be an issue with that and we just suffer.

Beyond that there are minor tweaks I'll be doing, especially regarding fzf-lua docs in Octo.nvim.

@ibhagwan if you don't have any suggestions for search improvements then I think we can close this out. Thank you so much for the guidance here! It has been extremely helpful!

**Comment by ibhagwan** [comment]
> One thing that can get addressed is the slowness in the search. I don't know where the issue actually lies, but the `gh` binary isn't the fastest so it very well could be an issue with that and we just suffer.

That would be my guess too, once the information is passed into fzf it is generally very fast, if you’re running the search as “live queries” (meaning every keystroke generates a new query) that is somewhat to be expected given information is retrieved over an internet connection.

> @ibhagwan if you don't have any suggestions for search improvements then I think we can close this out. Thank you so much for the guidance here! It has been extremely helpful!

Np, will close, it’s been a pleasure working with you @milogert and don’t hesitate to open issues for any other questions or concerns.
