### ISSUE TITLE
Options for abbreviating paths in the Buffers command

### ISSUE THREAD

**Issue by egargan** [ibhagwan/fzf-lua#761]
### Description 

As far as I can see from the docs for the `Buffers` command, there isn't a way to make long paths in buffer list more readable. I should always be able to see the filenames of buffers here, even for small window widths.

![image](https://github.com/ibhagwan/fzf-lua/assets/27496517/9f45c9b9-a26d-4ae9-a92c-9f503fe16ea5)

Ideally, config would be available to let me declare how many parent directories should be shown. Alternatively, something like the `Files` command's `path_shorten` would help!

The [reach.nvim](https://github.com/toppair/reach.nvim) plugin uses a fancy "lowest unique parent directory" system, which would be quite neat.

![image](https://github.com/ibhagwan/fzf-lua/assets/27496517/a9f065a8-75d2-4317-831d-9e14ea363ce3)

I'd be happy to have a go at these changes myself with a bit of guidance: which solution you prefer, where I can find the relevant files, things to watch out for.

**Comment by ibhagwan** [comment]
> Alternatively, something like the Files command's `path_shorten` would help!

https://github.com/ibhagwan/fzf-lua/commit/180c4650cb215a21c489290b01726a158801299c

Ty for raising this issue @egargan, apparently I accidentally missed `path_shorten` support for buffer providers (buffers, tabs).
