### ISSUE TITLE
Feature: Hide buffer number in buffers command

### ISSUE THREAD

**Issue by adaitche** [ibhagwan/fzf-lua#762]
The `buffers` command shows a list of buffers. In the first column it lists the buffer number in square brackets. Would it be possible to add an option to hide this numbers? I personally never use them for anything and it would be cleaner without them.

**Comment by ibhagwan** [comment]
```lua
:lua require("fzf-lua").buffers({fzf_opts={["--delimiter"]="]",["--with-nth"]="2.."}})
```

You can also add to `setup` under `buffers` if you want it to be permanent.

**Comment by ibhagwan** [comment]
Another option using the invisible space used by fzf-lua:
```lua
:lua require("fzf-lua").buffers({fzf_opts={["--delimiter"]="' '",["--with-nth"]="-1.."}})
```

**Comment by asmodeus812** [comment]
@ibhagwan to avoid opening a new issue i would like to check if there was some change in the buffers API as well, i am occasionally getting the following problem - `Fzf-lua fzf error 1: ^[i `, this happens when i open the buffers list, not always and i am still not sure why, i am not deleting any buffers manually or even with fzf lua (C-x). Not sure what is causing that.

![image](https://github.com/ibhagwan/fzf-lua/assets/15955811/8e3ae0aa-5bf5-4e43-b389-cb31b1d051f3)

**Comment by ibhagwan** [comment]
@asmodeus812, no changes were introduced to the buffers code, I think we need a new issue for this, it also seems you’re using the `cwd` option for buffers?

**Comment by asmodeus812** [comment]
Yes indeed i am filtering the list based on cwd, i can not reliably repro this, not sure if its some input buffering but it breaks seemingly at random.

**Comment by ibhagwan** [comment]
@asmodeus812 - https://github.com/ibhagwan/fzf-lua/commit/5f1f4b2f129b732814b743f7fa7ad6dee605728e should solve your issue.

**Comment by tssm** [comment]
@ibhagwan would you accept a PR introducing a config option with this. Although using FZF itself to hide the numbers works, the paths get misaligned as the number of digits may vary.

I would also like to hide the buffer status symbols, which is not possible reliably using FZF

**Comment by ibhagwan** [comment]
> @ibhagwan would you accept a PR introducing a config option with this. Although using FZF itself to hide the numbers works, the paths get misaligned as the number of digits may vary.
> 
> I would also like to hide the buffer status symbols, which is not possible reliably using FZF

I’m pretty sure we can hide everything reliably (no misalignment) by setting delimiter to `utils.nbsp`, use `-2..` if you want to display the icons too:
```lua
lua local fzf=require("fzf-lua"); fzf.buffers({fzf_opts={["--delimiter"]=fzf.utils.nbsp,["--with-nth"]="-1.."}})
```

**Comment by tssm** [comment]
You are right, however for some reason it eats the `term:` prefix of terminal buffers when `-2` is used as `--with-nth` value. This is what I see when I set it to `-3` (as I want the icons, but not the buffer status):
![Screen Shot 2024-08-17 at 19 43 02](https://github.com/user-attachments/assets/c3a8cee7-b992-408e-b3ba-1cf7dae1f82f)

Any ideas?

**Comment by ibhagwan** [comment]
> You are right, however for some reason it eats the `term:` prefix of terminal buffers when `-2` is used as `--with-nth` value. This is what I see when I set it to `-3` (as I want the icons, but not the buffer status): ![Screen Shot 2024-08-17 at 19 43 02](https://private-user-images.githubusercontent.com/1188977/358860815-c3a8cee7-b992-408e-b3ba-1cf7dae1f82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTkxNTEsIm5iZiI6MTcyMzkxODg1MSwicGF0aCI6Ii8xMTg4OTc3LzM1ODg2MDgxNS1jM2E4Y2VlNy1iOTkyLTQwOGUtYjNiYS0xY2Y3ZGFlMWY4MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTgyMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk0ZWZkMjU4OTRkNTQyY2E4YWQ1OWVkODQyZTQwNjQyYTBkNGE2ZjFiMjU0NWY0OTliMWNhMWJiNGMwZTIxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-1a24LHeEOICDLYOy_YX9d65kHbSDgbwFshNRpoQw_c)
> 
> The terminal icon isn't shown. Any ideas?

Because the delimiter gets added `:` in the code, I can remove that.

**Comment by ibhagwan** [comment]
> Thanks! I hope it doesn't break anything else 😇

I’ll test before I make the change :)

It’ll have to be tomorrow though as I’m traveling.

**Comment by tssm** [comment]
No problem! Thanks a lot :)

**Comment by ibhagwan** [comment]
> Thanks! I hope it doesn't break anything else 😇

So the issue is this, first this only happens because you’re most likely using the `bat` previewer, this doesn’t matter with the builtin previewer and will work also for term buffers with `-2..`. When using `bat` previewer we need to use an offset field index expression in fzf to scroll the bat preview to the correct line, this is done by fzf with the combination of the `:` delimiter and `{2}`, therefore the bat previewer code makes sure `:` is also a delimiter and since `term://` contains a colon it will be split at that location hiding the `term` part.

**Comment by tssm** [comment]
I see. Thanks for looking into it, I can live with terminal buffers not having an icon when using bat :)
