### ISSUE TITLE
Cannot shorten path

### ISSUE THREAD

**Issue by TroySigX** [ibhagwan/fzf-lua#763]
### Info

- Operating System: Endeavour OS
- Shell: bash 5.1.16
- Terminal: Yakuake
- `nvim --version`: 0.9.0
- `fzf --version`: 0.40.0

### Config:
``` lua
require('fzf-lua').setup({
  files = {
    path_shorten = true,
  },
})
```

### Description

Cannot shorten path when using `require('fzf-lua').files`, here's the photo:
![image](https://github.com/ibhagwan/fzf-lua/assets/88051085/0e1acada-b436-444d-a8a4-d5dbf3ebc429)
I'd expect the path to be something like: `.../cs220/08/`

**Comment by ibhagwan** [comment]
This is a different issue, `path_shorten` only applies to the paths that are displayed within the picker, when using `cwd_prompt` (now the default) the full working directory is displayed within the prompt.

You can disable it with `cwd_prompt=false` btw.

Perhaps we can use the same path shortening code as the one for the paths, maybe a new variable that sets the length threshold for shortening the path?

**Comment by TroySigX** [comment]
Yeah, that can be useful.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/1ed899811d6535cd0feb6de8f064c5a78b7cda2a - new defaults shorten any path > 32 chars into 1 char parts (customizable), for example:
```lua
-- Defaults are:
-- cwd_prompt_shorten_len=32
-- cwd_prompt_shorten_val=1
-- shorten paths greater than 14 chars into 3 char parts
:FzfLua files cwd_header=true cwd_prompt_shorten_len=14 cwd_prompt_shorten_val=3
-- lua version
:lua require("fzf-lua").files({cwd_prompt_shorten_len=14, cwd_prompt_shorten_val=3})
-- `setup` version
require("fzf-lua").setup({
  files = {
    cwd_prompt_shorten_len=14,
    cwd_prompt_shorten_val=3
  },
})
```

**Comment by TroySigX** [comment]
Thank you so much @ibhagwan ! Really appreciate it.

**Comment by ibhagwan** [comment]
> Thank you so much @ibhagwan ! Really appreciate it.

Yw @TroySigX, ty for raising this important issue.

Changed the title to reflect the request so it's easier to find within issues.
