### ISSUE TITLE
Feature request, i guess ?

### ISSUE THREAD

**Issue by I-Own-You** [ibhagwan/fzf-lua#764]
### Info

- Operating System: arch linux
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.9.0
- `fzf --version`: 0.40.0

</details>

### Description 

Hi again! this plugin is insane as always, but i encountered a situation that i dont know its a *bug* or *the way it must work*.
I am using a session plugin that saves(not the content but just remaining opened) all opened buffers when i exit neovim, i enter it again and all buffers are still showing.
But i encountered a strange thing and i dont know if its a *bug* or *the way it works*
When using:
<li> :FzfLua buffers - it doesnt show buffers if i dont go to them, for example i left neovim with a bunch of buffers, entered it again and when i use the command, it shows only the buffer i am in(nothing, thats correct), but the other buffers are not shown, for them to be shown i need to switch to them all.
<li> :FzfLua lines - the same as above happens with :FzfLua buffers.

Can i request a feature and is it possible to have all the buffers and not the one i ended up entering on, and all the lines from buffers and not only from the buffer i entered on with session plugin ?

**Comment by ibhagwan** [comment]
> Can i request a feature and is it possible to have all the buffers and not the one i ended up entering on, and all the lines from buffers and not only from the buffer i entered on with session plugin

What you’re describing is how neovim works, I’m pretty sure your session manager saves the buffer list offline in some file or database but doesn’t actually open the buffers when you restore the session.

Both `buffers` and `lines` use the neovim API to list open buffers and use the output from neovim to populate the buffer list and lines respectively, you can view the list yourself if you run `:ls`, do it before and after you enter a buffer for the first time and you’ll see the difference.

If you wish for all buffers to be opened you need to ask for this feature in the session management plug-in, fzf-lua will then be able to display all buffers that are in the output of `:ls`.

**Comment by I-Own-You** [comment]
> Hi again! this plugin is insane as always, but i encountered a situation that i dont know its a _bug_ or _the way it must work_. I am using a session plugin that saves(not the content but just remaining opened) all opened buffers when i exit neovim, i enter it again and all buffers are still showing. But i encountered a strange thing and i dont know if its a _bug_ or _the way it works_ When using:
> 
> * :FzfLua buffers - it doesnt show buffers if i dont go to them, for example i left neovim with a bunch of buffers, entered it again and when i use the command, it shows only the buffer i am in(nothing, thats correct), but the other buffers are not shown, for them to be shown i need to switch to them all.
> * :FzfLua lines - the same as above happens with :FzfLua buffers.
>   Can i request a feature and is it possible to have all the buffers and not the one i ended up entering on, and all the lines from buffers and not only from the buffer i entered on with session plugin ?

thanks for the answer, i'll then ask about this feature the session plugin maintainer

**Comment by benewberg** [comment]
I have recently discovered that the behavior changed as well in commit `7160a20`. I actually don't use a session manager plugin.

As an example:
`touch a b c`
`nvim a b c`

```
:ls
  1 %a   "a"                            line 1
  2      "b"                            line 0
  3      "c"                            line 0
Press ENTER or type command to continue
```

Finally, running `:FzfLua buffers` only shows file "a".  `lines` would only search "a" as well.

**Comment by benewberg** [comment]
@ibhagwan wow, that was fast! Confirmed working again on my end. Thank you, and thanks for this plugin which is my most-used plugin by far.

**Comment by ibhagwan** [comment]
Ty @benewberg!

@I-Own-You, I apologize I didn't make the connection, I believe this will also solve your issue :-)

**Comment by I-Own-You** [comment]
> Ty @benewberg!
> 
> @I-Own-You, I apologize I didn't make the connection, I believe this will also solve your issue :-)

It fixed the :FzfLua buffers but the :FzfLua lines didnt't, either way thanks :)

**Comment by ibhagwan** [comment]
@I-Own-You, use the latest commit, https://github.com/ibhagwan/fzf-lua/commit/439415467731a9f3b6cf51291a29a4d4abe3133d, it adds `show_unloaded=true` to `lines` defaults as well, will solve your issue.

**Comment by I-Own-You** [comment]
> @I-Own-You, use the latest commit, [4394154](https://github.com/ibhagwan/fzf-lua/commit/439415467731a9f3b6cf51291a29a4d4abe3133d), it adds `show_unloaded=true` to `lines` defaults as well, will solve your issue.

yes, it fixed, nice 🍷
