### ISSUE TITLE
Is it possible to create new files with the `files` action?

### ISSUE THREAD

**Issue by joncol** [ibhagwan/fzf-lua#765]
Hi, is it possible to create a new file using the `:FzfLua files` command?

Otherwise, would it be easy to configure `fzf-lua` to support such an action?

**Comment by ibhagwan** [comment]
Yes, it’s very easy to add a custom action to so whatever you want see the [keybind handlers section in the wiki ](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-acts) and use `vim.cmd('e <filename>')` to open a new file.

If you need to access what you typed in the query prompt (to use as filename) the information exists in `require('fzf-lua').config.__resume_data.last_query `.

Take a look at #508 for a similar request and implementation.

**Comment by joncol** [comment]
Thanks! I'll look into this.

**Comment by joncol** [comment]
@ibhagwan I ended up using:
```lua
    vim.keymap.set("n", "<leader>fi", function()
      local plugins_dir = vim.fn.stdpath("config") .. "/lua/plugins"
      require("fzf-lua").files({
        cwd = plugins_dir,
        actions = {
          ["default"] = function(selected, opts)
            local selected_item = selected[1]
            local last_query =
              require("fzf-lua").config.__resume_data.last_query
            if selected_item then
              require("fzf-lua").actions.file_edit(selected, opts)
            else
              vim.cmd("e " .. plugins_dir .. "/" .. last_query)
            end
          end,
        },
      })
```

Seems to work well!

**Comment by ibhagwan** [comment]
Nice @joncol!

Perhaps it’s worthwhile checking if `selected_item` exists on the file system and if not then create it? You can do that with `vim.loop.fs_stat(selected_item)`.

**Comment by joncol** [comment]
Good idea, thanks.

**Comment by joncol** [comment]
@ibhagwan: Slight problem though, `selected_item` is (e.g.) `M  fzf.lua`, i.e. it contains icons and Git status... Would you know of any shortcut to just get the filename (preferably with full path)?

**Comment by ibhagwan** [comment]
> @ibhagwan: Slight problem though, `selected_item` is (e.g.) `M  fzf.lua`, i.e. it contains icons and Git status... Would you know of any shortcut to just get the filename (preferably with full path)? For reference, this is how my `fzf` looks:
> ![fzf](https://user-images.githubusercontent.com/194062/239760655-5bec2470-df3f-4ce4-ba04-8a3aa5b8b87a.png)

Use the same code as fzf-lua actions from the `path` module:
https://github.com/ibhagwan/fzf-lua/blob/29d71212486554314e4f357a86f6174fb893bcc7/lua/fzf-lua/actions.lua#L96-L97

**Comment by joncol** [comment]
OK, how about something like this then?

```lua
    local path = require("fzf-lua.path")
    vim.keymap.set("n", "<leader>fi", function()
      local plugins_dir = vim.fn.stdpath("config") .. "/lua/plugins"
      require("fzf-lua").files({
        cwd = plugins_dir,
        actions = {
          ["default"] = function(selected, opts)
            local selected_item = selected[1]
            local status, entry =
              pcall(path.entry_to_file, selected_item, opts, opts.force_uri)
            local last_query =
              require("fzf-lua").config.__resume_data.last_query
            if selected_item and status and vim.loop.fs_stat(entry.path) then
              require("fzf-lua").actions.file_edit(selected, opts)
            else
              vim.cmd("e " .. plugins_dir .. "/" .. last_query)
            end
          end,
        },
      })
    end, { noremap = true, desc = "Find init file" })
```

**Comment by ibhagwan** [comment]
Looks fine @joncol
