### ISSUE TITLE
`--no-info` option not taking effect

### ISSUE THREAD

**Issue by gennaro-tedesco** [ibhagwan/fzf-lua#766]
### Info

- Operating System:
- Shell: zsh
- Terminal: iTerm2
- `nvim --version`: NVIM v0.9.0 (or nightly)
- `fzf --version`:

### Description 
The fzf option `--no-info` seems to not take effect if `prompt=...` or `cwd=...` are specified. For example consider

```lua
fzf.setup({
...
  fzf_opts = {
    ["--no-info"] = "",
    ...
  },
  files = {
    prompt = "files:",
  },
...
```
the picker still shows the header info (number of total files) although the option is set to ` ["--no-info"] = "",`; interestingly enough if I remove the `prompt = "files:",` then all works fine. I have observed a similar behaviour when setting the picker to work with a specific `cwd=...` thus I presume that the way certain fzf options are parsed may interfere with how others are? 

For the picker `buffers` I noticed that some commits ago the header `::<ctrl-x> to close` was introduced: is it possible to hide that as well? I have tried forcing `--no-info` in one way or another (also explicitly passing the option when invoking the picker) without any luck.

**Comment by ibhagwan** [comment]
You need to prevent the `--info` flag from being sent so it won’t interfere with `--no-info`, use:
```lua
:lua require'fzf-lua'.files({ fzf_opts = { ['--info']=false, ['--no-info']=''} })
```

Use `no_header` or `no_header_I` to hide buffers header:
```lua
:lua require'fzf-lua'.buffers({ no_header = true })
```

**Comment by ibhagwan** [comment]
The prompt is a different option, I set the default for files to `cwd_prompt=true`, set it to `false` either via setup or direct call and it will restore the previous behavior, see the commit message in https://github.com/ibhagwan/fzf-lua/commit/8af3a5864b319883bb3c7f8da612890320b7f92f

**Comment by gennaro-tedesco** [comment]
Awesome, it works, thank you!

**Comment by ibhagwan** [comment]
FYI @gennaro-tedesco, I forgot to mention `show_cwd_header` was also renamed to `cwd_header` (for more consistency in naming along with `cwd_prompt`), just in case you're using this option you can now use `cwd_header` instead, not obligatory though, all changes are backward compatible as I hate breaking users configs.
