### ISSUE TITLE
Is there a way to filter live_grep results by path ?

### ISSUE THREAD

**Issue by davibe** [ibhagwan/fzf-lua#767]
Is there a way to filter live_grep results by path as I type ?
It would be very useful for me. Anything similar ?

**Comment by ibhagwan** [comment]
You can always use `cwd` argument to run in a specific path, you can also use `live_grep_glob` to filter for certain paths.

https://github.com/ibhagwan/fzf-lua/wiki#live-grep-glob

**Comment by davibe** [comment]
Understood.

The usecase is that you are in a multi-project workspace / monorepo and you want to search "TheThing", but then maybe you want to check in "frontend", or "backend", or "somethingelse" you're not sure yet. The entire point of grep-ing and fuzzy searching is that you're not sure where things are, so it's just another way to drill down live.

Ideally you'd do something like ctrl-[something] and filter the same results by path rather than content, or 2 fields

**Comment by ibhagwan** [comment]
> Ideally you'd do something like ctrl-[something] and filter the same results by path rather than content, or 2 fields

There are different ways to do that, as I mentioned, look into using ripgrep globs as they support paths.

Alternatively (which is what I do), is `ctrl-g` into fuzzy mode and fuzzy search certain paths **on top of the regex query** , you can then keep `ctrl-g`-ing with narrower sets each time till you get to the desired result.
