### ISSUE TITLE
Support `Lines`

### ISSUE THREAD

**Issue by mcchrish** [ibhagwan/fzf-lua#77]
https://github.com/junegunn/fzf.vim#commands

**Comment by mcchrish** [comment]
The only thing that keeping `fzf.vim` installed.

**Comment by mcchrish** [comment]
I assume `grep_curbuf` is the equivalent to `BLines` but doesn't seem to work.

**Comment by ibhagwan** [comment]
I was going to support this differently, add a bind that enables you to change back and forth from live grep to fuzzy matching, that way you can open the current file live grep and basically switch it to `Lines`.

**Comment by ibhagwan** [comment]
Btw, I just realized `grep_curbuf` wasn't working as intended with `fzf` (I missed it when testing with `sk`), it should work close to `Lines` now although not exactly the same as this requires an exact match and not using fuzzy finding.

I'm looking for an `fzf` bind option that would remove the `change:reload` event so you can decided if you want to fuzzy search a certain result set.

**Comment by ibhagwan** [comment]
Done.

```lua
:lua require('fzf-lua').blines()
```

**Comment by mcchrish** [comment]
I just tried out and it looks great. One thing I think it should display is the filename along side the buffer number.

<img width="413" alt="Screen Shot 2021-09-01 at 6 55 25 AM" src="https://user-images.githubusercontent.com/7200153/131586134-b149a7da-1c7e-4ca3-80c6-7216738263d8.png">

**Comment by ibhagwan** [comment]
> I just tried out and it looks great. One thing I think it should display is the filename along side the buffer number.
> `fzf.vim`:
> <img alt="Screen Shot 2021-09-01 at 6 55 25 AM" width="413" src="https://user-images.githubusercontent.com/7200153/131586134-b149a7da-1c7e-4ca3-80c6-7216738263d8.png">

Good idea, I’ll add it later.

**Comment by ibhagwan** [comment]
Added file names and icon support to `blines`, also added `lines` to search all open buffers at once.

**Comment by arsham** [comment]
May I ask what is the rationale behind disabling multi-select? I have a use case for selecting multiple lines and the only way I could do that was to use the `grep_curbuf`, but I like the `blines`'s interface more.

**Comment by ibhagwan** [comment]
> May I ask what is the rationale behind disabling multi-select? I have a use case for selecting multiple lines and the only way I could do that was to use the `grep_curbuf`, but I like the `blines`'s interface more.

The logic was that since `blines` uses buffer actions (not file actions, default action is `actions.buf_edit`) the multiple selection does nothing, it still jumps to the first selected line.

I agree that there should be an option to disable that (vs hard coded) so I just commited https://github.com/ibhagwan/fzf-lua/commit/0e775b075b45d9e2b31e6a08ae6f10ae55cd0745, if you wish to enable multi-select you just need to set `blines.fzf_opts["--no-multi"]` to false:
```lua
require'fzf-lua'.setup {
  blines = {
    fzf_opts = {
        -- disable multi-select, set to false to disable
        ["--no-multi"]    = false,
    },
}
```

**Comment by arsham** [comment]
Wow you are quick! Thank you very much for your prompt response.

**Comment by ibhagwan** [comment]
> Wow you are quick! Thank you very much for your prompt response.

Keep an eye on this, I'm changing the default to enable multi-select by default and adding new actions for buffer to send to quickfix so the buffer lists feature set matches the file actions.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/e5ce0700f8a12aee42d2e6068f0c9d3c6fe8b45b - try it out, default actions (configurable via `setup`, works similar to `files`, `grep`, etc) are:
```lua
  blines = {
    actions = {
      -- single selection jumps to location, multiple selection goes to quickfix
      ["default"]     = { actions.buf_edit_or_qf },
      -- explicit bind to send to quickfix
      ["alt-q"]       = { actions.buf_sel_to_qf }
    },
  }
```

**Comment by arsham** [comment]
This is exactly what I'm using it for [here](https://github.com/arsham/fzfmania.nvim/blob/18212d48934f47151403c02d556c414025f3cdb7/lua/fzfmania/fzf_lua.lua#L154).

Although parsing it proved to be a bit difficult. 

An Idea would be providing the `filename:line:col` in the results and increase the `--with-nths` and `--nth` numbers by `1`, but I imagine it will have a huge impact to the code base; So ignore the idea.

**Comment by ibhagwan** [comment]
FYI, just forced pushed because I forgot to update the README.
https://github.com/ibhagwan/fzf-lua/commit/fa69ad7b138dfb71ada504bf8fbc580216cde6b4

>An Idea would be providing the filename:line:col in the results and increase the --with-nths and --nth numbers by 1, but I imagine it will have a huge impact to the code base; So ignore the idea.

Yes, it's a bit problematic due to file/git icons messing up the order of separators, in addition some entries have hidden buffer and tab numbers which makes it even more difficult.

>Although parsing it proved to be a bit difficult.

I use `require'fzf-lua'.path.entry_to_file(selected[i])` to parse entries which should work for all `fzf-lua` use cases/formats, I recommend you call that instead.

**Comment by ibhagwan** [comment]
>An Idea would be providing the filename:line:col in the results and increase the --with-nths and --nth numbers by 1, but I imagine it will have a huge impact to the code base; So ignore the idea.

Also, this would increase the memory footprint of each item by a lot and will have a severe performance impact, I worked really hard on the performance of this plugin and it now works really well on huge code bases (even when adding file/git icons), try it out on the Linux kernel source code and see for yourself :-)

Although not very clear what I'm doing here, take a look [at the wiki](https://raw.githubusercontent.com/wiki/ibhagwan/fzf-lua/demo-ctrlg.gif).

**Comment by arsham** [comment]
> I use require'fzf-lua'.path.entry_to_file(selected[i]) to parse entries which should work for all fzf-lua use cases/formats, I recommend you call that instead.

Thanks for the recommendation!

> Also, this would increase the memory footprint of each item by a lot and will have a severe performance impact, I worked really hard on the performance of this plugin and it now works really well on huge code bases (even when adding file/git icons), try it out on the Linux kernel source code and see for yourself :-)
> 

I came to the same conclusion a while after I implemented that part. I've decided not to refactor my code, because your plugin is awesome and it does everything I need.

**Comment by ibhagwan** [comment]
>I came to the same conclusion a while after I implemented that part. I've decided not to refactor my code, because your plugin is awesome and it does everything I need.

Tysm @arsham!

Btw, Amazing project:
https://github.com/arsham/fzfmania.nvim

Gonna dig deeper into it later, maybe I'll get some ideas :-)
