### ISSUE TITLE
Config option prompt is ignored when cwd_prompt is set

### ISSUE THREAD

**Issue by tobiwild** [ibhagwan/fzf-lua#770]
Small thing, but I was confused after an update that my custom prompts for files didn't work anymore.
The example from the Readme also doesn't work anymore:
```
lua require'fzf-lua'.files({ prompt="LS> ", cmd = "ls", cwd="~/<folder>" })
```
Setting `cwd_prompt` to `false` helps, but this is a little counterintuitive IMO.
Tested on commit bc51107 on a Mac.

**Comment by ibhagwan** [comment]
This is by design, the question is which option should have priority over the other `cwd_prompt` or `prompt`, I’m not sure if there is a “correct” answer as someone else might feel `cwd_prompt` should take over.

**Comment by tobiwild** [comment]
Maybe prompt could also accept a Lua function or table to set the cwd and thus avoiding the conflicting cwd_prompt option?

**Comment by ibhagwan** [comment]
> Maybe prompt could also accept a Lua function or table to set the cwd and thus avoiding the conflicting cwd_prompt option?

That would mean yet another change in the default options and also an inconsistency with the `cwd_header` option, I think we can live with this as long as it’s documented properly.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/wiki#files-cwd-prompt
