### ISSUE TITLE
API questions

### ISSUE THREAD

**Issue by iovis** [ibhagwan/fzf-lua#773]
Hi! Long time user of your plugin. I'm not sure if this is the right place to ask these questions (or if they're welcomed), but I figured I'd give it a shot.

I've been developing a plugin of my own, [muxi.nvim](https://github.com/iovis/muxi.nvim/). It's still very early stages, very much not documented, and my first lua plugin, so I'm probably doing a lot of things wrong. It allows you to "mark" files with an arbitrary key and navigate and switch between them. Similar idea to [harpoon](https://github.com/ThePrimeagen/harpoon), but with a hash instead of a list.

I use your plugin a lot, so I wanted to build a nice integration with it and maybe serve as an entry point to my plugin. I referenced https://github.com/ibhagwan/fzf-lua/wiki/Advanced and it got me most of the way there, but I had some questions to make the integration even nicer.

### Context
My goal is to have something similar to your `buffers` popup:

![Screenshot 2023-05-31 at 15 33 15](https://github.com/ibhagwan/fzf-lua/assets/6660202/dacdb09f-c61b-4b40-93d4-c74a27ce19b5)

Particularly:
- [x] Show the marks for the current project, sorted
- [x] Show a previewer on the line of the mark
- [x] Allow to go to the mark as default action
- [x] Allow to open the mark as a (v)split/tab
- [x] Allow to remove a mark
- [x] Show nice colors, differentiating keys from files
- [x] Show file icons
- [x] Show a legend with some of the actions

Screenshot of my current progress:

![Screenshot 2023-05-31 at 15 33 22](https://github.com/ibhagwan/fzf-lua/assets/6660202/80c54878-0aa5-49bd-abcd-d8a2e1a000b1)

### Source

The table with the `marks` in question looks like [this](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/init.lua#L3-L9):

```lua
---@class Mark
---@field file string
---@field pos number[]

---@class Muxi
---@field marks table<string, Mark>
local muxi = {}
```

![Screenshot 2023-05-31 at 15 49 40](https://github.com/ibhagwan/fzf-lua/assets/6660202/86dc8790-7bde-4320-a3e2-87a8b097991d)

The entry point of my plugin's integration with fzf-lua would be [here](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/init.lua#L15). I also made a custom [previewer](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/previewer.lua) based on your docs, which works wonderfully, and a [row class](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/row.lua#L19-L21) that implements `__tostring` to show up in fzf.

### Questions

- I'm using the [function](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/init.lua#L17-L32) version of your API (with `fzf_cb`), I'm guessing this is the preferred method if I want to refresh the popup after a `delete` action. Is this correct?
- I made the `MuxiMarkRow` class hoping I could get the object back from the selected items —and decouple view from model—, but I'm getting strings back, meaning I have to deserialize them again to perform actions ([Example trying to match [key]](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/init.lua#L42-L47))
  - Is there a way to get the object back instead of a string? If not, do you plan to?
  - If I had to serialize strings and I was to use colors, how do you deserialize the output? Do you have a preferred way of both setting colors and escaping them after in your public API?
- I haven't been able to make `file_icons = true, color_icons = true` work, I'm not sure how to use them
- I'm also not sure how you make the "legend" with the `:: <ctrl-x> to close` (which looks really nice and is very helpful)
  - On a similar note, when using the `help` binding, I'm not sure how to give my custom actions proper labels. They show up as `function:` or `table:`

![Screenshot 2023-05-31 at 16 06 18](https://github.com/ibhagwan/fzf-lua/assets/6660202/e725506c-3ce0-4789-8e1f-530ad7f68bfa)

---

Sorry for the long wall of text and thank you for making an essential plugin for my workflow!

**Comment by ibhagwan** [comment]
Hi @iovis, sorry for the delay I apparently missed the email notification for this issue :)

Looks like you’ve done great work although from first glance at the code and also the type of entries you need to display (basically file entries with location, like grep results) you can reduce a lot of your boilerplate and reuse a lot of code that already exists in fzf-lua, all the action code already exist and if you use entries in a format fzf-lua understand you won’t even need a custom previewer.

> I'm using the [function](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/init.lua#L17-L32) version of your API (with fzf_cb), I'm guessing this is the preferred method if I want to refresh the popup after a delete action. Is this correct?

Inaccurate, `fzf_cb` is just for async feeding into the fzf, it has nothing to do with deletions.

> I made the MuxiMarkRow class hoping I could get the object back from the selected items —and decouple view from model—
> Is there a way to get the object back instead of a string? If not, do you plan to?

There is no way around this, we’re sending contents to an external process and getting a string of the selected item in return. 

> If I had to serialize strings and I was to use colors, how do you deserialize the output?

Fzf lua already strips the coloring when you make a selection, if I do find I need to transform a colored string I use `utils.strip_ansi_coloring`.

> I haven't been able to make file_icons = true, color_icons = true work, I'm not sure how to use them

For that need to use `make_enrry.file` which would take care of everything related to file entries (formatting, coloring, git, etc), these entries would also be “understood” by the builtin previewer.

> I'm also not sure how you make the "legend" with the :: <ctrl-x> to close (which looks really nice and is very helpful)

That is fzf’s headed flag which you can send via `fzf_opts`.

> On a similar note, when using the help binding, I'm not sure how to give my custom actions proper labels. They show up as function: or table:

You won’t need to do if you use the builtin actions (which I believe would be better), but just in case you do, you can set a string by calling `config.set_action_ helpstr`:
https://github.com/ibhagwan/fzf-lua/blob/0f953fd7a35d22e1409d5ce77bbacef9cf07e2cb/lua/fzf-lua/config.lua#L379-L382


Here’s my suggestion, take a look at how the `dap_breakpoints` code is written and duplicate it, it’s very close to what you need (almost identical, custom “marks” with preview and delete option), the only difference would be the table format of the input data (and perhaps not having `bufnr`, so just dump the buffer part):
https://github.com/ibhagwan/fzf-lua/blob/0f953fd7a35d22e1409d5ce77bbacef9cf07e2cb/lua/fzf-lua/providers/dap.lua#L85

**Comment by iovis** [comment]
> Hi @iovis, sorry for the delay I apparently missed the email notification for this issue :)
> 
> Looks like you’ve done great work although from first glance at the code and also the type of entries you need to display (basically file entries with location, like grep results) you can reduce a lot of your boilerplate and reuse a lot of code that already exists in fzf-lua, all the action code already exist and if you use entries in a format fzf-lua understand you won’t even need a custom previewer.

Thank you so much for your pointers, they really helped a lot! You're right that I was doing much more work that I needed, being able to leverage some of your plugin's logic felt much better (and I was indeed able to remove the custom previewer!).

> > I'm using the [function](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/init.lua#L17-L32) version of your API (with fzf_cb), I'm guessing this is the preferred method if I want to refresh the popup after a delete action. Is this correct?
>
> Inaccurate, fzf_cb is just for async feeding into the fzf, it has nothing to do with deletions.

This one I'm still having issues with. If I pass a lua table to `fzf_exec(my_table, opts)`, when I do the `actions.resume` it doesn't remove the entry, it keeps showing the original table. I was only able to make it update when using `fzf_cb`.

> >    I made the MuxiMarkRow class hoping I could get the object back from the selected items —and decouple view from model—
    Is there a way to get the object back instead of a string? If not, do you plan to?
>
> There is no way around this, we’re sending contents to an external process and getting a string of the selected item in return.

Ohhh, that makes sense, thank you for clarifying!

> > If I had to serialize strings and I was to use colors, how do you deserialize the output?
>
> Fzf lua already strips the coloring when you make a selection, if I do find I need to transform a colored string I use utils.strip_ansi_coloring.

Turns out that using the API as intended meant I didn't have to escape at all, but I'll keep it in mind if I ever need to.

> >    I haven't been able to make file_icons = true, color_icons = true work, I'm not sure how to use them
>
> For that need to use make_enrry.file which would take care of everything related to file entries (formatting, coloring, git, etc), these entries would also be “understood” by the builtin previewer.

You're right, `file_icons` and `color_icons` are working beautifully now! `git_icons` does not work though, I don't think I want it but I'm curious how I'd make it work.

> >    I'm also not sure how you make the "legend" with the :: to close (which looks really nice and is very helpful)
>
> That is fzf’s headed flag which you can send via fzf_opts.

Working perfectly now!

> >    On a similar note, when using the help binding, I'm not sure how to give my custom actions proper labels. They show up as function: or table:
>
> You won’t need to do if you use the builtin actions (which I believe would be better), but just in case you do, you can set a string by calling config.set_action_helpstr

I ended up needing to do my own `delete` (given that it needs to interact with my plugin), `config.set_action_helpstr` did the trick.

One extra question from looking at `dap_breakpoints`, I could not figure out what this line meant:

```lua
opts = fzf_lua.core.set_fzf_field_index(opts, 3, opts._is_skim and "{}" or "{..-2}")
```

It didn't seem like I needed it, but I figured I'd ask just in case.

Thank you so much again for taking the time to help me! I really appreciate it

**Comment by ibhagwan** [comment]
> This one I'm still having issues with. If I pass a lua table to fzf_exec(my_table, opts), when I do the actions.resume it doesn't remove the entry, it keeps showing the original table. I was only able to make it update when using fzf_cb.

That’s because resume continues exactly where you left of with the same local vars inside the `contents` function , this is the reason the code I linked uses `fn_pre_fzf`,  take a look at the below code, it updates the `_locations` member variable in the callback, `fzf_pre_fzf` gets called as part of the resume so you can use that to “refresh” your locations:
https://github.com/ibhagwan/fzf-lua/blob/0f953fd7a35d22e1409d5ce77bbacef9cf07e2cb/lua/fzf-lua/providers/dap.lua#L92-L98

> One extra question from looking at dap_breakpoints, I could not figure out what this line meant:

You’re correct, this line isn’t relevant unless you’re using a native previewer (e.g. `bat`) together with [skim](https://github.com/lotabout/skim) (rust version of fzf).

Let me know if you need any more help and I’ll be happy to take a look at your final code.

**Comment by ibhagwan** [comment]
Forgot to mention two things:

> Progress pic!

Looks great!!

Once you’re done take a look at the below lines from `git_status`:

https://github.com/ibhagwan/fzf-lua/blob/0f953fd7a35d22e1409d5ce77bbacef9cf07e2cb/lua/fzf-lua/providers/git.lua#L116-L119

It’s a “quality of life” improvement, if fzf version is > 0.36, it utilizes new features to reload the contents without restarting fzf, makes for a better UX and the cursor remains in place when you perform the action, you can experience that when you delete buffers or stage/unstage with `git_status`, take a look at #730 and https://github.com/ibhagwan/fzf-lua/commit/8cee7f542885cb78abef4e2cb6515470aea78564 if you’re interested in learning more how it was done.

**Comment by ibhagwan** [comment]
Another thing I missed:

> git_icons does not work though, I don't think I want it but I'm curious how I'd make it work.

If you want this to work you need to call `make_entry.preprocess` once before making any entries in order to populate the git diff tables although technically the only part of the function you need is this:

https://github.com/ibhagwan/fzf-lua/blob/0f953fd7a35d22e1409d5ce77bbacef9cf07e2cb/lua/fzf-lua/make_entry.lua#L250-L252

Once the above table is populated `make_entry.file` will utilize it:
https://github.com/ibhagwan/fzf-lua/blob/0f953fd7a35d22e1409d5ce77bbacef9cf07e2cb/lua/fzf-lua/make_entry.lua#L372-L373

**Comment by iovis** [comment]
Thank you again for helping me through this, I really appreciate the gesture!



> > This one I'm still having issues with. If I pass a lua table to fzf_exec(my_table, opts), when I do the actions.resume it doesn't remove the entry, it keeps showing the original table. I was only able to make it update when using fzf_cb.
>
> That’s because resume continues exactly where you left of with the same local vars inside the contents function , this is the reason the code I linked uses fn_pre_fzf, take a look at the below code, it updates the _locations member variable in the callback, fzf_pre_fzf gets called as part of the resume so you can use that to “refresh” your locations

(Spoiler, I solved it with your `reload` suggestion, _but_) I tried using something similar to what I saw in that command:

```lua
opts.fn_pre_fzf = function()
  opts._locations = muxi:to_fzf_list(opts) -- returns the formatted list
end

opts.fn_pre_fzf()

fzf_lua.fzf_exec(opts._locations, opts) -- I tried a bunch of stuff here
```

But I couldn't figure out what I was supposed to pass to `fzf_exec`. The `dap_breakpoints` function seems to rely on `fzf_cb` (even though it uses `opts._locations` to get the list). I was able to show the list I wanted, but using `actions.resume` would keep using the old list —even if I saw `fn_pre_fzf` firing with the right info—. I couldn't figure out this one, so I moved on to the next one.

> Once you’re done take a look at the below lines from git_status:
> 
> It’s a “quality of life” improvement, if fzf version is > 0.36, it utilizes new features to reload the contents without restarting fzf, makes for a better UX and the cursor remains in place when you perform the action, you can experience that when you delete buffers or stage/unstage with git_status, take a look at https://github.com/ibhagwan/fzf-lua/issues/730 and https://github.com/ibhagwan/fzf-lua/commit/8cee7f542885cb78abef4e2cb6515470aea78564 if you’re interested in learning more how it was done.

This one blew my mind. It's indeed a much better UX and I didn't know this was available. Somehow I managed to make it work by copying what you did verbatim:

```lua
opts = {  -- Somewhere above
  -- [...]
  -- actions listed below will be converted to fzf's 'reload'
  reload_actions = {
    [actions.delete_key] = true,
    [actions.toggle_go_to_cursor] = true,
  }
}

  ----Reload without flickering
  opts.__fn_reload = function(_)
    return muxi:to_fzf_list(opts)
  end

  -- build the "reload" cmd and remove '-- {+}' from the initial cmd
  local reload = fzf_lua.shell.reload_action_cmd(opts, "{+}")
  local contents = reload:gsub("%-%-%s+{%+}$", "")
  opts = fzf_lua.core.convert_reload_actions(reload, opts)
```

I can't say I understand much what's going on, but it worked. The commit you mentioned helped a lot to figure out the steps necessary. I inspected the `reload` and `contents` variables and they looked intense haha. When I'm less tired I'll see if I can figure out how it works.

> > `git_icons` does not work though, I don't think I want it but I'm curious how I'd make it work.
>
> If you want this to work you need to call make_entry.preprocess once before making any entries in order to populate the git diff tables although technically the only part of the function you need is this:

This one was very easy to implement and is now working, thanks for clarifying!

> Let me know if you need any more help and I’ll be happy to take a look at your final code.

Please don't feel obligated to do so! I'm already surprised you took the time to help me this much haha. If you're still curious, the current version is located [here](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/init.lua) and it looks like this:

![Screenshot 2023-06-03 at 01 26 26](https://github.com/ibhagwan/fzf-lua/assets/6660202/90157a08-05d0-4476-8389-8ea0a33495df)

Thank you again for helping me out!

**Comment by ibhagwan** [comment]
> But I couldn't figure out what I was supposed to pass to fzf_exec. The dap_breakpoints function seems to rely on fzf_cb (even though it uses opts._locations to get the list). I was able to show the list I wanted, but using actions.resume would keep using the old list —even if I saw fn_pre_fzf firing with the right info—. I couldn't figure out this one, so I moved on to the next one.

`dap_breakpoints` uses function as the contents argument, `fzf_cb` is the callback you need to call to add single line into fzf, the choice to iterate `_locations` within a function rather than supplying a simple table of strings is for the async "loading" effect, it looks much better when you have many entires or when entries are slow to load.

In any event, not relevant in your case since you chose the other (and better way) which I'll explain below.

> I can't say I understand much what's going on, but it worked. The commit you mentioned helped a lot to figure out the steps necessary. I inspected the reload and contents variables and they looked intense haha. When I'm less tired I'll see if I can figure out how it works.

Yes, it's definitely not for the faint of heart :smile:, it is somewhat simple if you understand what's happening, I'll try to explain:

```lua
 -- build the "reload" cmd and remove '-- {+}' from the initial cmd
  local reload = fzf_lua.shell.reload_action_cmd(opts, "{+}")
  local contents = reload:gsub("%-%-%s+{%+}$", "")
  opts = fzf_lua.core.convert_reload_actions(reload, opts)
```

First it's important to understand that both `reload` and `contents` are simple shell commands that print to `stdout`, the `contents` command is the shell command that is initially piped into fzf, the `reload` command is the command that will be called when a certain action is defined in `reload_actions`, both commands connect to the main neovim instance over RPC and then invokve the approperiate callback using `shell_helper.lua` and a function ID (which will end up calling `__fn_reload`).

> What is the purpose of `{+}`?

The reload action also supports passing the currently selected fzf items to `fn_reload`'s first parameter (which you aren't in need of) the way this is represented in the shell command is via fzf's `FIELD INDEX EXPRESSION`, in our case we are passing `{+}` which means **all currently selected items** but you can also pass the typed query prompt with `{q}`, you can read more about the different options in `man fzf`.

> Please don't feel obligated to do so! I'm already surprised you took the time to help me this much haha. If you're still curious, the current version is located [here](https://github.com/iovis/muxi.nvim/blob/main/lua/muxi/fzf/init.lua) and it looks like this

I looked at your code, at first glance I don't see how it can be improved further, it's the bare minimum code to make it work as you designed, `__fn_reload` is used correctly to both load the initial list and the reload actions and the rest is clean and well documented 10/10 :-)

**Comment by ibhagwan** [comment]
> Somehow I managed to make it work by copying what you did verbatim

As a true programmer, I will never stop being surprised with this stuff "ha, my stuff works I guess" :laughing:

**Comment by ibhagwan** [comment]
Last thing, in terms of look and feel I would experiment with the 2 fzf options below, personally I think it looks best as you currently have it but to each their own.
```lua
-- hides the separator that follows the fzf "info" string
-- in your screenshot the info is `> 3/3 (0)` after the query
fzf_opts = { ["--no-separator"] = "" }
-- changes the default "inline" info to the full version
-- I personally dislike full info when header strings exists
-- (what you call legend) but you might feel differently about it?
fzf_opts = { ["--info"] = "default" }
```

**Comment by iovis** [comment]
> Yes, it's definitely not for the faint of heart 😄, it is somewhat simple if you understand what's happening, I'll try to explain

Thank you for the explanation! I may use this knowledge to provide an fzf integration for the [tmux plugin](https://github.com/iovis/muxi) that made me start this one. That'll help me further solidify that knowledge.

> > Somehow I managed to make it work by copying what you did verbatim
> As a true programmer, I will never stop being surprised with this stuff "ha, my stuff works I guess" 😆

Haha, yeah. I couldn't tell right away how it worked, so my plan was to put it there and do some "error driven development" to guide me through your code and figure out how it worked. I was really shocked it just worked haha.  I think the only error I got (which was somewhat unrelated) was due to not using `opts = fzf_lua.config.normalize_opts(opts, M.default_opts)` originally, which helped me understand better how you handle opts overrides and helped me clean up a bit my default opts.

> Last thing, in terms of look and feel I would experiment with the 2 fzf options below, personally I think it looks best as you currently have it but to each their own.

I did play around a bit with `--info` when I saw it in some of your global opts. I do agree that your choice is the better looking one. Even if I disagreed, I do value consistency so I figured I'd be a good citizen and provide the same experience. Now that I'm using `normalize_opts` and allowing a user to pass `opts` I think people could override this to get the experience they prefer if they want to change it.

The one I was a bit on the fence of was maybe using `--nth` (with `--delimiter`) to limit the query search to the `mark.key` (the first column). But I think someone used to your plugin probably expects to be able to fuzzy find everything, so maybe I'll keep that behavior as default and add a custom `opts` to only search the key or something to that end.

Anyway, thank you so much for your help and your patience. This was really fun!

**Comment by ibhagwan** [comment]
Makes sense @iovis, happy I could help.

Will close the issue, feel free to reopen or create a new issue if you need anything else.

**Comment by ibhagwan** [comment]
Hi @iovis, FYI the last commit https://github.com/ibhagwan/fzf-lua/commit/2b22ee5fb022a0444707a798a4ab032a34706431 is a breaking change for your code, in order to support different types of actions I refactored the `convert_reload_actions` function and it's no longer required to be manually called, instead  you have to set `opts.__reload_cmd` and (optionally) change your action definitions:

So instead of:
```lua
  local reload, id = fzf_lua.shell.reload_action_cmd(opts, "{+}")
  local contents = reload:gsub("%-%-%s+{%+}$", "")
  opts = fzf_lua.core.convert_reload_actions(reload, opts)
```

Use:
```lua
  local reload, id = fzf_lua.shell.reload_action_cmd(opts, "{+}")
  local contents = reload:gsub("%-%-%s+{%+}$", "")
  opts.__reload_cmd = reload
```

**Due to backward compat code the next change is optional** but if you wish to convert your actions to the new format, for example, instead of:
```lua
actions = {
  ["ctrl-s"] = { actions.git_stage_unstage, actions.resume }
},
```

Use:
```lua
actions = {
  ["ctrl-s"] = { fn = actions.git_stage_unstage, reload = true }
},
```

**Comment by iovis** [comment]
Working beautifully, thank you for the heads up!
