### ISSUE TITLE
Put selected text as the search input automaticlly

### ISSUE THREAD

**Issue by LintaoAmons** [ibhagwan/fzf-lua#774]
If it's possible to have `FzfLua grep_project` binding to a shortcut, and when I trigger the shortcut in visual mode, it will put the selected text as the search input automaticlly?

**Comment by ibhagwan** [comment]
Have you tried `grep_visual`?

**Comment by LintaoAmons** [comment]
Thanks, I also copied some of your code to my plugin~~~

**Comment by ibhagwan** [comment]
> Thanks, I also copied some of your code to my plugin~~~

Looks like a [great plugin](https://github.com/LintaoAmons/easy-commands.nvim) @LintaoAmons :-)
