### ISSUE TITLE
win_border settings aren't applied to the builtin preview window

### ISSUE THREAD

**Issue by mottram** [ibhagwan/fzf-lua#78]
I have winopts set up like so:
```lua
winopts = {
  win_border = {'┌', '─', '┐', '│', '┘', '─', '└', '│'}
}
```
These characters are applied to the fzf search window border as expected, but not the builtin preview window, which still has rounded corners.

Is it possible to customise the preview's border in the same way?

**Comment by ibhagwan** [comment]
It should work, let me check if something got messed up perhaps.

**Comment by ibhagwan** [comment]
Silly bug, I forgot to add quotes around `string`, should work now.
