### ISSUE TITLE
Question about live_grep with rg's --fixed-strings option

### ISSUE THREAD

**Issue by deponian** [ibhagwan/fzf-lua#781]
Hi again!

I've read documentation and wiki after my yesterday's [PR](https://github.com/ibhagwan/fzf-lua/pull/777) but I still have a question.

I want to perform all my searches using `live_grep` with no regex processing, only literal strings. So I use `--fixed-strings` option for `rg` and disable escaping with `no_esc = true`. But I still can't search option-like strings (`-info`, `--help`, etc.). This fails because whole query is passed as argument for `nvim --headless ...` command for `mt` version of `live_grep`.

This can be fixed by using `--` (shell's options/arguments separator) here: https://github.com/ibhagwan/fzf-lua/blob/267098387dd7a3c53f8a4cfb17285ba05d841353/lua/fzf-lua/providers/grep.lua#L301-L302

Like this:
```lua
command = command:gsub(core.fzf_query_placeholder, "{argvz}")
        .. " -- " .. core.fzf_query_placeholder
```

Am I overcomplicating things again and there is some existing option for my kind of case?

**Comment by ibhagwan** [comment]
> Am I overcomplicating things again and there is some existing option for my kind of case?

You're not overcomplicating **your use case** but it does overcomplicate everything else :-)

The purposed solution solves your use case alone and only for `live_grep` **with glob support enabled**, this doesn't support using `--fixed-strings` with `grep`, for example try running `:FzfLua grep debug=true rg_glob=false no_esc=true search=--no`, this will result in:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/aa90920f-3966-49ba-928c-b09c71eec769)

A more generic solution would be to add the `--` separator to the grep command builder at:
https://github.com/ibhagwan/fzf-lua/blob/267098387dd7a3c53f8a4cfb17285ba05d841353/lua/fzf-lua/providers/grep.lua#L103

By changing the code to:
```lua
command = ("%s -- %s %s"):format(command, search_query, search_path) 
```

Which will no result in:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/36632b2f-5db0-48d4-bc5f-948b40108091)

But as you can guess from the above code, this would break the command when a specific file is specified which would break many more providers such as `grep_curbuf`, `lgrep_curbuf` and the `tags_xxx` variants (which reuses the grep code to perform searchs only within the `tags` file), will probably also break many other things I can't think of right now (needs to be tested with all other greppers, `fish` shell, `ctrl-g` switches and what not...) - needless to say this is not a rabbit hole I'd like to descened into :-)

Which brings me to a purposed solution, if you're using `rg_glob=true` you can solve your use case (and perhaps even enhance it) by using a custom `rg_glob_fn` function as discussed in https://github.com/ibhagwan/fzf-lua/issues/373#issuecomment-1079786343, you can modify the query, add `--` or even decided on parsing new types of flags, craft your own `rg` command and return it to fzf-lua for execution.

Let me know what you think?

**Comment by deponian** [comment]
> But as you can guess from the above code, this would break the command when a specific file ...

This is why I used `-e` for `rg`'s pattern instead of usual first positional argument in my previous PR :)
`rg` and `grep` support this flag (`ag` isn't) and with it `search_path` can be first positional argument and everything works like usual, but as you said before this will reduce the flexibility of the plugin, so probably this isn't the best deal.

I'll try to play with `rg_glob_fn`. Thanks for the link to #373!

**Comment by deponian** [comment]
Unfortunately `rg_glob_fn` can't help in my case. As far as I understand fzf runs `nvim --headless ... <query>` before `rg_glob_fn`, which will be called inside `nvim`, so if `<query>` is something like `-hello -- *.txt` then it breaks and print `Usage: ...` for `nvim`, which means `nvim` thinks that it was called with `-h` option.

I use this function as `rg_glob_fn`, but it doesn't matter what is inside this function actually:
```lua
function M.glob_parse(query, opts)
  local function strsplit(inputstr, sep)
    local t = {}
    for str in string.gmatch(inputstr, "([^" .. sep .. "]+)") do
      table.insert(t, str)
    end
    return t
  end

  if not query or not query:find(opts.glob_separator) then
    return query, nil
  end
  local glob_args = ""
  local search_query, glob_str = query:match("(.*)" .. opts.glob_separator .. "(.*)")
  for _, s in ipairs(strsplit(glob_str, "%s")) do
    glob_args = glob_args .. ("%s %s -- ")
        :format(opts.glob_flag, vim.fn.shellescape(s))
  end
  io.write(("q: %s -> flags: %s, query: %s\n"):format(
    query, glob_args, search_query))
  return search_query, glob_args
end
```

**Comment by ibhagwan** [comment]
@deponian, I’m not sure what’s the solution here then, unless we find a something that works for all use cases I can’t sacrifice other uses cases for the edge case of `--fixed-strings` (which isn’t that common).

Perhaps you create your own live grep’er using the [`fzf_live`](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-live-api) API?

**Comment by deponian** [comment]
Yeah, I don't see any easy ways to do it :(
Thanks for the idea with a shell command! I forgot about it.
I think we can close this issue :)

**Comment by ibhagwan** [comment]
Np will close, I’d be interested to see your final solution with `fzf_live` once you finalized it :)

**Comment by deponian** [comment]
I'll share it if it any good :upside_down_face:

**Comment by deponian** [comment]
Hi @ibhagwan!
I guess I can share my results now.
After my unsuccessful experiments with shell command mode for `fzf_live` I've decided to go the other way. What if I don't build one complicated command, but switch from one to the other instead? Like when you switch between `live_grep` and usual `grep` with `ctrl-g`. With that thought in mind I built this configuration:
```lua
function M.setup_grep()
  local rg_opts_tbl = {
    ["--color"]         = "always",
    ["--max-columns"]   = "4096",
    ["--glob"]          = "'!.git/'",
    ["--column"]        = "",
    ["--line-number"]   = "",
    ["--no-heading"]    = "",
    ["--no-ignore"]     = "",
    ["--smart-case"]    = "",
    ["--hidden"]        = "",
    ["--fixed-strings"] = "",
  }

  -- merge these options without resetting to defaults
  require("fzf-lua").setup({
    grep = {
      fzf_opts = {
        ["--delimiter"] = ":",
        ["--nth"] = "4..",
      },
      -- rg_opts will be constructed from this table
      -- if you run one of the wrapper functions above
      -- (e.g. live_grep_native)
      rg_opts_tbl = rg_opts_tbl,
      -- these are defaults that will be used if you run
      -- functions like live_grep directly from require("fzf-lua")
      rg_opts = "--color=always --max-columns=4096 --glob='!.git/' " ..
                "--column --line-number --no-heading --no-ignore " ..
                "--smart-case --hidden --fixed-strings",
      actions = {
        ["ctrl-g"] = { switch_to_grep_project },
        ["ctrl-n"] = { switch_to_live_grep_native },
        ["ctrl-o"] = { switch_to_live_grep_glob },
        ["ctrl-h"] = { rg_toggle_option("--hidden") },
        ["ctrl-r"] = { rg_toggle_option("--fixed-strings") }
      },
      exec_empty_query = true,
    },
  }, true)
end
```
I created `switch_to_*()` functions to switch between different grep modes and `rg_toggle_option()` to change `rg`'s options during the search. Now I can activate one of the commands and then change everything with my `ctrl-*` mappings.
To differentiate modes and see current active `rg` options I change prompt to `Literal search: `, when it's `live_grep_native` with `--fixed-strings`, `Regex search with globs` if it's `live_grep_glob` without `--fixed-strings` and so on. You can see full configuration here: https://github.com/deponian/vim.config/blob/9160c06ef3990f321bdb4ba9abcf1f88bff7d2ac/lua/deponian/fzf-lua/init.lua

**Comment by deponian** [comment]
Thanks again for your awesome plugin! The level of customization options is just enormous!

**Comment by ibhagwan** [comment]
> Thanks again for your awesome plugin! The level of customization options is just enormous!

Looks brilliant @deponian!

So am I getting this right that you’re using fixed strings only without globs or were you able to solve that as well and perhaps it wasn’t clear to me from the code?

**Comment by deponian** [comment]
No, I wasn't able to solve it :(

Now when I see error during `live_grep_glob` this means it's time to hit `ctrl-r` and disable `--fixed-strings` option. It's an ideal solution, but nothing is :upside_down_face: This is a good compromise for me, since I don't often use globes.

**Comment by ibhagwan** [comment]
> No, I wasn't able to solve it :(

I’ll take another stab at it and see if I can solve it without impacting other use cases.

**Comment by deponian** [comment]
> I’ll take another stab at it and see if I can solve it without impacting other use cases.

This would be great, thank you!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5b5e6359f9fbd0156b31e3046767c8dee3987cb7

@deponian, a bit of fine tuning to #777 and I was able to achieve the usage of  the literal separator `--` without adversly affecting anything else, namely `tags` and grep'ing current buffer, also tested on `fish` shell and seems to be working as expected, hopefully I didn't miss anything.

Try this commit with `--fixed-strings` and lmk if this solves your issue?

**Comment by deponian** [comment]
@ibhagwan, it works flawlessly! Now I can remove `-e` hack from my configuration for `live_grep_native` and get both `live_grep` and `live_grep_glob` working with `--fixed-strings`! Thank you so much!

**Comment by ibhagwan** [comment]
> @ibhagwan, it works flawlessly! Now I can remove `-e` hack from my configuration for `live_grep_native` and get both `live_grep` and `live_grep_glob` working with `--fixed-strings`! Thank you so much!

That’s great :)

**Comment by k33nice** [comment]
Hey! I was looking for a similar feature at one time, but unfortunately, I couldn't find a way to configure it by hotkey. 
Now I have the following config
`vim.keymap.set('n', '<leader>/', function () fzf_lua.grep({ no_esc = 2 }) end, {noremap = true, desc = 'FZF grep'})`
This allowed me to search for both fixed strings (`Grep For> -F 'only.fixed'`) and use other flags (`Grep For> -uu 'smth in git-ignored'`). But after these changes, it doesn't work anymore :(

**Comment by ibhagwan** [comment]
> Hey! I was looking for a similar feature at one time, but unfortunately, I couldn't find a way to configure it by hotkey. Now I have the following config `vim.keymap.set('n', '<leader>/', function () fzf_lua.grep({ no_esc = 2 }) end, {noremap = true, desc = 'FZF grep'})` This allowed me to search for both fixed strings (`Grep For> -F 'only.fixed'`) and use other flags (`Grep For> -uu 'smth in git-ignored'`). But after these changes, it doesn't work anymore :(

Unfortuntely, doing it the way you describe  is not possible anymore due to the separation by `--` literals, but allow me suggest a different solution using `rg_glob_fn`, by hijacking the glob parsing funciton we can simiarly pass raw arguments (or have more complex customizations):
```lua
require("fzf-lua").setup({
  grep = {
    debug = true, -- remove this line once you're done testing
    rg_glob = true,
    rg_glob_fn = function(q, o)
      local search_query, args = q:match("(.-)" .. o.glob_separator .. "(.*)")
      return search_query, args
    end
  },
})
```

With the above customiztaion anything after `o.glob_separator` (by default space followed by two hyphens ` --`, customizable) will be appended as raw arguments to the `rg` command , so to craft a query with `-uu` you'd need to first type the query, then the glob separator followed by the raw arguments:
> note the full command in the debug output:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/e6358c2b-8b24-4b6c-92aa-057f71ccf6f9)

The customization also affects `grep` and the `ctrl-g` switch to fuzzy, so you can also use it in the `Grep For>` prompt or directly using the `search` param:
```lua
:lua require("fzf-lua").grep({ search ="foo -- -uu" })
```
Will result in:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/0fd9fcbe-963d-4ee4-ba08-8075d2cec662)

Same for `-F|--fixed-strings` :
> added `no_esc` to avoid regex escape the hyphens
```lua
:lua require("fzf-lua").grep({ search ="--no -- -F", no_esc=true })
```
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/27c57952-4013-4de2-91be-680bddcf9bc3)

**Comment by k33nice** [comment]
Oh, thank you very much! I missed that `rg_glob_fn`. I use that flag-passing and narrowing with "--iglob" quite often, so unfortunately not a win-win for me. The "rg_glob_fn" function you suggest requires typing "ctrl-g > -- --iglob 'some/dir/**'" instead of just "ctrl-g > -- some/dir/**". However, I appreciate the advice and maybe tinker with regex to make it fit for me.

**Comment by ibhagwan** [comment]
> Oh, thank you very much! I missed that `rg_glob_fn`. I use that flag-passing and narrowing with "--iglob" quite often, so unfortunately not a win-win for me. The "rg_glob_fn" function you suggest requires typing `ctrl-g > -- --iglob 'some/dir/**'` instead of just `ctrl-g > -- some/dir/**`. However, I appreciate the advice and maybe tinker with regex to make it fit for me.

You’re correct, using this customization requires escaping the globs as they’re being passed as raw args directly to `rg`, maybe you can customize it further and get to a happy medium? You can split all the args (after the glob separator) and if the literal doesn’t start with `-` you can shell escape it, for reference here’s the original function:
https://github.com/ibhagwan/fzf-lua/blob/b58799714513083bd646f0b716e29f224ebba48e/lua/fzf-lua/make_entry.lua#L236-L242

Note that in the customization you cannot use references to other modules (e.g. `utils.strsplit`) as the function is passed as bytecode to the external neovim process (`multiprocess=true`) so if you wanted to copy the above you’d have to create a local copy of `strsplit`.

**Comment by ibhagwan** [comment]
@k33nice, I have another suggestion, first, **update to the latest commit** https://github.com/ibhagwan/fzf-lua/commit/cb0943a41df4bb59475a13c4dcc7256cc230a2e3 - the commit adds support for `rg_glob_fn` that is part of the `opts` (rather than a global setting), you can then keep using `live_grep_glob` normally and have a specialized `leader-/` mapping that's using a custom `rg_glob_fn`:
```lua
require("fzf-lua").grep({
  rg_glob = true,
  rg_glob_fn = function(q, o)
    local search_query, args = q:match("(.-)%s%-%-(.*)")
    return search_query, args
  end
})
```

If you wish to have the exact setup as before you can modify the `glob_separator` to be a single space, that way `rg_glob_fn` will get called as soon as a space is detected in the query/search string. The full setup should look as follows and should replicate your existing `no_esc=2` "hack":
```lua
vim.keymap.set('n', '<leader>/', function () require("fzf-lua").grep({
  debug = true,
  no_esc = true,
  glob_separator = "%s",
  rg_glob = true,
  rg_glob_fn = function(q, _)
    local args, search_query = q:match("(.*)%s(.*)")
    return search_query, args
  end
}) end, {noremap = true, desc = 'FZF grep'})
```

With the above customization, using the search query `-uu foo` results in:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/c9e72475-7746-4e44-87c9-3a57831c1679)

**Comment by k33nice** [comment]
Oh, that’s a nice one! Works like a charm. Thanks again man!

**Comment by ibhagwan** [comment]
> Oh, that’s a nice one! Works like a charm. Thanks again man!

Perfect :)

Ty for the update @k33nice!

**Comment by ibhagwan** [comment]
@deponian, due to #794 I mady a small change so we can support both `-e` and `--`.

After you update to https://github.com/ibhagwan/fzf-lua/commit/903dc4d3bc60bdb47dacbc13b8d70ac6713be30e, in order to use `--fixed-strings` you nee to add `--` to the end of your `rg_opts` or `cmd`.

```lua
require("fzf-lua").setup({
  grep = {
    rg_opts = "--color=always --max-columns=4096 --glob='!.git/' " ..
              "--column --line-number --no-heading --no-ignore " ..
              "--smart-case --hidden --fixed-strings --",
  },
})
```

**Comment by ibhagwan** [comment]
@deponian, please use the latest commit https://github.com/ibhagwan/fzf-lua/commit/672fe2781fcfd527cc82125c5267113f544075d2, refactored the glob args code and smoothed out potential issues.

**Comment by deponian** [comment]
@ibhagwan Hi! Checked latest commit 672fe27, added ` -e` to my `rg_opts` builder and it's work like a charm, thanks!

**Comment by ibhagwan** [comment]
> @ibhagwan Hi! Checked latest commit [672fe27](https://github.com/ibhagwan/fzf-lua/commit/672fe2781fcfd527cc82125c5267113f544075d2), added ` -e` to my `rg_opts` builder and it's work like a charm, thanks!

Out of curiosity, you prefer `-e` to `-F --`? I was under the impression you preferred fixed strings.

**Comment by deponian** [comment]
I use `-F -e pattern`. When `-F` is active pattern is literal, so `-e` is used for the same reason as `--`, which is searching for patterns that start with a dash.
`man rg` gives two examples with `-e` and `--`:

![Screenshot_20230625_031131](https://github.com/ibhagwan/fzf-lua/assets/31796184/60d7c0f4-76d7-42bc-bb4d-c552e2aea91f)

**Comment by ibhagwan** [comment]
Makes sense, ty @deponian!
