### ISSUE TITLE
Option to cache file lists

### ISSUE THREAD

**Issue by MaartenStaa** [ibhagwan/fzf-lua#782]
### Info

- Operating System: macOS 13.4
- Shell: Fish
- Terminal: Kitty
- `nvim --version`: NVIM v0.10.0-dev-3004+ga8ee4c7a8-Homebrew
- `fzf --version`: 0.41.1 (brew)

### Description 

In a large repo, `:FzfLua files` takes about 3.5 seconds to start showing the list of files (45518 results). Would it be possible to add an option to cache the list of files in between invocations? I imagine a scenario where the list of files is immediately populated on subsequent runs, and refreshed in the background while the user can already start filtering.

**Comment by MaartenStaa** [comment]
In case anyone else comes across this issue, dealing with slow file list population, I ended up [creating this project](https://github.com/MaartenStaa/file-web-devicons) to remedy this. It's a small binary that takes output from `fd`, and prepends the file icons like Lua does in `fzf-lua`. By using that instead of the built-in `files` provider, the delay for the file list is completely gone.

**Comment by ibhagwan** [comment]
> In case anyone else comes across this issue, dealing with slow file list population, I ended up [creating this project](https://github.com/MaartenStaa/file-web-devicons) to remedy this. It's a small binary that takes output from `fd`, and prepends the file icons like Lua does in `fzf-lua`. By using that instead of the built-in `files` provider, the delay for the file list is completely gone.

Nice job and interesting project @MaartenStaa!
