### ISSUE TITLE
The first word in a line is not searchable with `grep_project`

### ISSUE THREAD

**Issue by deponian** [ibhagwan/fzf-lua#785]
### Info

- Operating System: Arch Linux
- Shell: zsh
- Terminal: Alacritty
- `nvim --version`: v0.9.1
- `fzf --version`: 0.41.1 (4c70745c)

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

I believe I found a bug in `grep_project`. It doesn't search words that are located at the very beginning of the line. If the word starts at the first column of the string then it's not searchable, if the line starts with whitespace character then the first word after whitespace is searchable.

I think the problem lies in these lines: https://github.com/ibhagwan/fzf-lua/blob/267098387dd7a3c53f8a4cfb17285ba05d841353/lua/fzf-lua/providers/grep.lua#L433-L437

There is no `--delimiter` option for `fzf` so it uses default value, which is space character (` `). This is why words that start at the first column of the string are not searchable. They're just part of the first field from `fzf`'s point of view. I think we need something like this to fix it:
```lua
opts.fzf_opts["--delimiter"] = "':'"
opts.fzf_opts["--nth"] = "4.."
```
It's not an ideal solution, because `:` can be part of the filename (at least on Linux), but it's better than nothing and will work in most cases. Even if we stumble on highly unlikely filename with `:` we might get some extra search results, but we won't lose anything.

**Comment by ibhagwan** [comment]
Ty @deponian, I do see the issue I'm just not sure why this happens, when I run the command using `--with-nth` it does seem to identify the fields correctly and remove only the filename from the entry:
```lua
:lua require("fzf-lua").grep_project({ fzf_opts = {["--with-nth"]="2.."}})
```

I'll do some more testing why `--nth` behaves differently and doesn't what I would consider valid fields with `2..`.

**Comment by deponian** [comment]
```lua
:lua require("fzf-lua").grep_project({ fzf_opts = {["--with-nth"]="2.."}})
```
For me this command results in lines without first word, just line `--nth` :confused:

**Comment by deponian** [comment]
Maybe your `FZF_DEFAULT_OPTS` affects its behavior?

**Comment by ibhagwan** [comment]
You're correct my `FZF_DEFAULT_OPTS` adds `--delimiter='[ :]'`.

`grep_project` is just a convineince shortcut for running `grep({ search="" })`, we can add `--delimiter=":"` and set `--nth=3..` as `--nth=4..` would exclude too much.

**Comment by deponian** [comment]
Yes, to support both `grep` and `rg` we should use `--nth=3..`.
