### ISSUE TITLE
Prompt value not updated for vim.ui.select

### ISSUE THREAD

**Issue by TheBlob42** [ibhagwan/fzf-lua#786]
### Info

- Operating System: Ubuntu
- Shell: bash
- Terminal: Ubuntu terminal
- `nvim --version`: NVIM v0.9.1
- `fzf --version`: 0.36.0 (2023011)

- [x] The issue is reproducible with `mini.sh`

### Description 

1. run `FzfLua register_ui_select`
2. run `lua vim.ui.select({1,2,3}, { prompt = "Test" }, function() end)`
3. run `lua vim.ui.select({1,2,3}, { prompt = "A different prompt" }, function() end)`

After 3. I would expect to see the fzf-lua dialog to appear with the newly specified prompt ("A different prompt") but instead I see the same prompt as before ("Test"). This continues for all following calls to `vim.ui.select`: the prompt never changes from the first value being passed to it. I have not tested it for all available options, but did not found any other issue than this one with the prompt value.

If guess this has something to do with the ["option caching"](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/ui_select.lua#L8-L10), but I have to admit that I did not really get a hang of whats exactly going on there :sweat_smile:

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/3c260cce2499abe161e222fa1d69f3a7602a243e

Ty for raising this issue @TheBlob42, should be fixed now.

> If guess this has something to do with the ["option caching"](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/ui_select.lua#L8-L10), but I have to admit that I did not really get a hang of whats exactly going on there sweat_smile

And you were correct, it was being cached inside the `fzf_opts["--prompt"]` :smile:

**Comment by TheBlob42** [comment]
That was fast :slightly_smiling_face: 
Thanks for the quick fix, now it is working as expected.
Didn't know that fzf is caching this by itself :sweat_smile:

**Comment by ibhagwan** [comment]
> That was fast 🙂
> Thanks for the quick fix, now it is working as expected.
> Didn't know that fzf is caching this by itself 😅

That wasn’t Fzf caching but rather fzf-lua :)

**Comment by TheBlob42** [comment]
Ah thanks for the clarification :+1: I just had a look into your commit and now I understand what the issue was
