### ISSUE TITLE
Yank commit sha from `git_commits` or `git_bcommits` pickers.

### ISSUE THREAD

**Issue by gcanat** [ibhagwan/fzf-lua#787]
Is it possible to yank the commit sha from these pickers ? (in fzf.vim it's done with ctrl-y)
Would be usefull for example to diff the current buffer against a specific commit.
Sorry if it's been already asked or if it is explained somehwere, I couldn't find it.

**Comment by ibhagwan** [comment]
It’s possible with a very easy customization and a few lines of lua, the below copies anything before the first space into the yank reg `0`, if you wish to copy to the unnamed change to `”`, I’m writing this from mobile and didn’t text the lua regex hopefully I got it right :)
```lua
require'fzf-lua'.git_commits({
  actions = {
    ['ctrl-y'] = function(selected, opts)
      vim.fn.setreg([[0]], selected[1]:match('[^%s]+'))
    end
  }
})
```

**Comment by ibhagwan** [comment]
Scrap it, this makes sense to make a default, I will add it.

**Comment by ibhagwan** [comment]
@gcanat, update to https://github.com/ibhagwan/fzf-lua/commit/2b22ee5fb022a0444707a798a4ab032a34706431, it adds the action to both `commits` and `bcommits`.

The default just copies to the yank and unnamed registeres (both `0` and `"`) without exiting the interface, if you wish to exit the interface modify the action definition to `exec_silent=false`:
```lua
local actions = require("fzf-lua").actions
require("fzf-lua").setup({
  git = {
    commits = { actions = { ["ctrl-y"]  = { fn = actions.git_yank_commit, exec_silent = false } } },
    bcommits = { actions = { ["ctrl-y"]  = { fn = actions.git_yank_commit, exec_silent = false } } },
  }
})
```

**Comment by gcanat** [comment]
Works like a charm. Thanks a lot !
