### ISSUE TITLE
Previewer doesn't update in `git_status` for when multi selection is used

### ISSUE THREAD

**Issue by elamaranae** [ibhagwan/fzf-lua#789]
Hello again!

When selecting multiple files using tab key, the previewer is stuck with the first file selected. I was able to reproduce with the minimal  example script as well. Please check it out.

Thanks in advance!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b58799714513083bd646f0b716e29f224ebba48e - should work now.

Ty for the report @elamaranae!
