### ISSUE TITLE
Commit 5b5e6359 breaks searching in files with `rg`

### ISSUE THREAD

**Issue by micheleCTDE** [ibhagwan/fzf-lua#794]
Just reporting this for reference for the time being, I will see if I can find the time to investigate what is wrong during the weekend.

Up to commit `52f68fe`, I can use `rg` to grep text through files. From commit `5b5e635` this is no longer working and reports an error as `IO error for operation on searchText: No such file or directory (os error 2)`.
Perhaps it could be due to my fzf-lua/rg settings (need to investigate as I said), but it was indeed working till the mentioned commit.

**Comment by ibhagwan** [comment]
Hi @micheleCTDE, see #781, this I’d probably due to the addition of ` --` to separate the query string.

If you can you post your `grep` setup we’ll be able to fix it or find an alternative that would achieve the same as previous to the commit.

**Comment by micheleCTDE** [comment]
Hi @ibhagwan,
hope you are keep well.
Here is my current config for `grep`:
```
  grep =
  {
    debug=true,
    no_esc=true,  -- don't escape \
    cmd = [[ rg --with-filename --no-heading --line-number --column --smart-case \
                --no-ignore --hidden --trim --color "always" --sort-files \
                --glob "!{**/.git/**,**/obj-x86_64-linux-gnu/**,**/.cache/**,**/*.so,**/debian/**/*}" -e ]],
    fzf_opts =
    {
      ['--history'] = vim.fn.stdpath("data") .. '/fzf-lua-grep-history'
    },
  },
```

The attached pic shows the behavior with commit `52f68fe` (top - works fine) and current `master` (bottom - doesn't work well). Tomorrow I am going to look into the issue in more details, today I don't have the time for it.

**Comment by micheleCTDE** [comment]
The problem arises from the `-e` option passed to `rg` for regex patterns.
From `rg` documentation:
```
    -e, --regexp PATTERN ...
           A pattern to search for. This option can be provided multiple times, where all patterns given are searched. Lines matching at least one of the provided patterns are printed. This flag can also be used when
           searching for patterns that start with a dash.

           For example, to search for the literal -foo, you can use this flag:

               rg -e -foo

           You can also use the special -- delimiter to indicate that no more flags will be provided. Namely, the following is equivalent to the above:

               rg -- -foo
```
Note that `-e` can be used in place of `--` to search for stirngs that begin with `-`.
Adding ` -- ` by default as done in commit `5b5e635` removes flexibility. Instead a user could add `-e` prior to their pattern using `rg_glob_fn` if they want a flexible solution. Even better, adding `rg_toggle_option` mentioned [here](https://github.com/ibhagwan/fzf-lua/issues/781#issuecomment-1595831081) would be a more flexible solution and users could dynamically change the behavior of their search.

**Comment by ibhagwan** [comment]
@micheleCTDE, alright, let me think of a solution that can satisfy both use cases, yours and @deponian.

**Comment by micheleCTDE** [comment]
I think that `rg_toggle_option` from @deponian would be a nice addition ti fzf-lua. Could toggle hidden, fixed strings, regex pattern on the spot, may be even more options like smart case, line numbers and so on. @deponian already prepared some code, so worht looking into it :slightly_smiling_face:

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/903dc4d3bc60bdb47dacbc13b8d70ac6713be30e

@micheleCTDE, should work now as before.

**Comment by ibhagwan** [comment]
@micheleCTDE, please use the latest commit https://github.com/ibhagwan/fzf-lua/commit/672fe2781fcfd527cc82125c5267113f544075d2, refactored the glob args code and smoothed out potential issues.

**Comment by micheleCTDE** [comment]
Just back from a day trip and tested last commit, works like a charm. Thanks a lot for the quick fix!
As always, GREAT plugin, can't state this enough!

**Comment by ibhagwan** [comment]
Ty for the kind words @micheleCTDE ❤️
