### ISSUE TITLE
Extraneous preview window title highlights

### ISSUE THREAD

**Issue by 0xcharly** [ibhagwan/fzf-lua#796]
### Info

- Operating System: macOS Ventura 13.4
- Shell: Fish
- Terminal: Kitty
- `nvim --version`: `NVIM v0.10.0-dev-569+gfa0a25dcb`
- `fzf --version`: `0.42.0 (brew)`

```lua
require('fzf-lua').setup({
  winopts = {
    preview = {
      scrollbar = false,
    },
  },
})
```

### Description 

Title highlights are not cleared when `winopts.preview.scrollbar = false`, resulting in highlight artifacts that erroneously apply to the preview window border instead, as demonstrated in the following screenshot:

<img width="2179" alt="Screenshot 2023-06-25 at 12 32 34 PM" src="https://github.com/ibhagwan/fzf-lua/assets/5804569/78f9ccd9-79a3-4d42-a011-d220d3b3a30f">

**Comment by 0xcharly** [comment]
Tentative fix in https://github.com/ibhagwan/fzf-lua/pull/797.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7aff4a3a089c65c6e60646945d8a5c8116078061

@0xcharly  - should solve your problem, lmk if otherwise.

**Comment by ibhagwan** [comment]
@0xcharly if you don’t mind me asking, what settings you used to get the look and feel in your screenshot?

I believe @RayZ0rr was after something similar in #760 :)

**Comment by 0xcharly** [comment]
I've replied on #760 directly. Let me know if you want me to make it a profile.

**Comment by ibhagwan** [comment]
> I've replied on #760 directly. Let me know if you want me to make it a profile.

It does look great, would love to accept a PR with your profile, I’m just not sure how to craft this without the theme overrides, maybe with a custom `winopts.border` using “fat” characters?
