### ISSUE TITLE
Icons and highlight disappear when using "borderless" profile?

### ISSUE THREAD

**Issue by GreenSleeper** [ibhagwan/fzf-lua#798]
I've setup `fzf-lua` to use `borderless` profile, but i noticed that icons and highlight settings disappeared.
Is this by design?

**Comment by ibhagwan** [comment]
> but i noticed that icons and highlight settings disappeared

Hi @GreenSleeper, the profile is minimalistic by design take a look at the below lines from the profile which disable both file and git icons globally:
https://github.com/ibhagwan/fzf-lua/blob/bd5f54bc66cb63cdf6378c76eb3914ac677cd123/lua/fzf-lua/profiles/borderless.lua#L7-L8

> and highlight settings disappeared

Not sure which highlights do you mean?


The profile is just an example for what’s possible, it’s not possible to satisfy everyone’s desires, that’s why customization exists, if you wish to make modifications to it you can either copy paste the settings from [borderless.lua](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/profiles/borderless.lua), alternatively, you can start with this profile as base and override the settings you don’t like, for example re-enabling icons:
```lua
require"fzf-lua".setup({
  "borderless", -- start with borderless settings as base
  global_git_icons = true,
  global_file_icons = true,
})
```

**Comment by GreenSleeper** [comment]
highlight settings means settings in
hl = {
&nbsp; &nbsp; title = "something",
}


I'll look into the borderless.lua file.&nbsp;&nbsp;


btw, borderless looks beautiful, thanks for your great work.



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 26, 2023 11:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ibhagwan/fzf-lua] Icons and highlight disappear when using"borderless" profile? (Issue #798)




  
but i noticed that icons and highlight settings disappeared
  
Hi @GreenSleeper, the profile is minimalistic by design take a look at the below lines from the profile which disable both file and git icons globally:
 https://github.com/ibhagwan/fzf-lua/blob/bd5f54bc66cb63cdf6378c76eb3914ac677cd123/lua/fzf-lua/profiles/borderless.lua#L7-L8
  
and highlight settings disappeared
  
Not sure which highlights do you mean?
 
The profile is just an example for what’s possible, it’s not possible to satisfy everyone’s desires, that’s why customization exists, if you wish to make modifications to it you can either copy paste the settings from borderless.lua, alternatively, you can start with this profile as base and override the settings you don’t like, for example re-enabling icons:
 require"fzf-lua".setup({   "borderless", -- start with borderless settings as base   global_git_icons = true,   global_file_icons = true, })

**Comment by ibhagwan** [comment]
>highlight settings means settings in
>```lua
>hl = {
>  title = "something",
>}
>```

If I'm understanding correctly, you're asking what is `something`?

`something` is a neovim colorscheme highlight group (color settings, fg, bg, etc), you can explore all the existing highlights in your colorscheme with `:FzfLua highlights` type `Pmenu` and you'll see the settings from which the defaults in `borderless` are derived.

> btw, borderless looks beautiful, thanks for your great work.

Ty!

**Comment by GreenSleeper** [comment]
no, I mean I set something in hl before, for example, title = "IncSearch",&nbsp; but when I switch to borderless, it stops working that way.



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 26, 2023 12:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ibhagwan/fzf-lua] Icons and highlight disappear when using"borderless" profile? (Issue #798)




  
highlight settings means settings in
 hl = {  title = "something", }
  
If I'm understanding correctly, you're asking what is something?
 
something is a neovim colorscheme highlight group (color settings, fg, bg, etc), you can explore all the existing highlights in your colorscheme with :FzfLua highlights type Pmenu and you'll see the settings from which the defaults in borderless are derived.
  
btw, borderless looks beautiful, thanks for your great work.
  
Ty!

**Comment by ibhagwan** [comment]
> no, I mean I set something in hl before, for example, title = "IncSearch",&nbsp; but when I switch to borderless, it stops working that way.

`borderless` has highlights defined which override your previous ones:
https://github.com/ibhagwan/fzf-lua/blob/3115ed3d1be551e463f1639d6225d2fc2669ab70/lua/fzf-lua/profiles/borderless.lua#L19-L24

As I wrote above, copy the borderless.lua and make your own theme or override the highlights:
```lua
:lua require"fzf-lua".setup({"borderless",winopts={hl={title="IncSearch"}}})
```

Which would result in:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/071c0d98-5085-4554-96a5-5be5ee20fcb3)

**Comment by GreenSleeper** [comment]
I'll look into it when I get time, thanks for your patient reply.



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 26, 2023 12:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ibhagwan/fzf-lua] Icons and highlight disappear when using"borderless" profile? (Issue #798)




  
no, I mean I set something in hl before, for example, title = "IncSearch",&nbsp; but when I switch to borderless, it stops working that way.
  
borderless has highlights defined which override your previous ones:
 https://github.com/ibhagwan/fzf-lua/blob/3115ed3d1be551e463f1639d6225d2fc2669ab70/lua/fzf-lua/profiles/borderless.lua#L19-L24
 
As I wrote above, copy the borderless.lua and make your own theme or override the highlights:
 :lua require"fzf-lua".setup({"borderless",winopts={hl={title="IncSearch"}}})
 
Which would result in:

**Comment by ibhagwan** [comment]
> I'll look into it when I get time, thanks for your patient reply.

Yw @GreenSleeper, for further discussion I recommend reading #760.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/577f2a74c6914515d45a4c1f390978c18d9cd3cb

This commits adds a new profile `borderless_full`, has icons enabled and window titles.

**Comment by GreenSleeper** [comment]
> [577f2a7](https://github.com/ibhagwan/fzf-lua/commit/577f2a74c6914515d45a4c1f390978c18d9cd3cb)
> 
> This commits adds a new profile `borderless_full`, has icons enabled and window titles.

I just updated, looks beautiful.
