### ISSUE TITLE
Is it possible to search backwards with search_history?

### ISSUE THREAD

**Issue by jgonera** [ibhagwan/fzf-lua#799]
I mapped `<C-k>` when in `/` or `?` to open `search_history`. This works as expected for `/` which searches forward, but I'd like to make it search backwards for `?`. Is that possible? Ideally I'd pass an option to `search_history` so that `<cr>` there invokes search in the backwards direction.

Code illustrating what I'm doing:

```lua
vim.api.nvim_create_autocmd({ "CmdlineEnter" }, {
  callback = function(args)
    if args.file == ":" then
      vim.keymap.set("c", "<C-k>", function()
        fzf_lua.command_history({ fzf_opts = { ["--layout"] = "default" } })
      end)
    elseif args.file == "/" or args.file == "?" then
      vim.keymap.set("c", "<C-k>", function()
        -- Close command line mode first, otherwise it conflicts with
        -- fzf_lua.search_history
        vim.api.nvim_feedkeys("<Esc>", "t", true)
        fzf_lua.search_history({ fzf_opts = { ["--layout"] = "default" } })
      end)
    end
  end,
})

vim.api.nvim_create_autocmd({ "CmdlineLeave" }, {
  callback = function()
    vim.keymap.del("c", "<C-k>")
  end,
})
```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7fcb06ca95323c3a6524beefb345d3dc3c8cb32d


```lua
:FzfLua search_history reverse=true
-- or
:lua require("fzf-lua").search_history({ reverse = true })
```

Also works with `command_history`.

**Comment by jgonera** [comment]
Wow, that was quick :)
I'm not sure if it does what I had in mind though. I mean that if you have a file like this open in a vim buffer (numbers to denote lines):

```
1: phrase
2: phrase
3: phrase
```

Then if you're in line 2 and do `/phrase` in vim then it will go to line 3. If you write `?phrase` then it will go to line 1. Right now `search_history` will always replicate the `/phrase` behavior but never a `?phrase` behavior.

**Comment by ibhagwan** [comment]
Oops I jumped the gun @jgonera  :smile: 

https://github.com/ibhagwan/fzf-lua/commit/9f1192f036fafa0bcfb4b9dbfe97e7486670452d

Seaprated the funcionality to:

> Reversing the result list with:
```lua
:FzfLua search_history reverse_list=true
```

> Reversing the search action (`/` vs `?`)
```lua
:FzfLua search_history reverse_search=true
```

The latter is what you were after.

**Comment by ibhagwan** [comment]
@jgonera in regards to your other comment about duplicate history (which was fixed in https://github.com/ibhagwan/fzf-lua/commit/9c94851e30ded5a374b2de24d8847b6bdfcfe0b4) note that switching direction **causes duplicate entries in neovim**, if you search for `/foo` and then `?foo` you will see duplicate entries at the end of `:history search`.

**Comment by jgonera** [comment]
Everything works as expected now, thank you!
