### ISSUE TITLE
Issue triggering example code

### ISSUE THREAD

**Issue by Parkbro** [ibhagwan/fzf-lua#8]
Thank you for writing this plugin, I saw your post on reddit and rushed to give it a go (both in the newest nightly and stable neovim
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
```

When triggering
```
:lua require('fzf-lua').files()
# I receive
E5108: Error executing lua vim.lua:63: ...nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:11: invalid escape sequence near '"'
```
I think it's to do with the config, because pasting the config in the README into my init.lua causes the same error. I have tried looking at each config item and can't see anything that would need to be escaped.

**Comment by ibhagwan** [comment]
What OS are you on? Mac / Linux?
What happens if you run with an empty config (it’s just a repeat of the the defaults for people who want to change something)?

```lua
require'fzf-lua'.setup {}
```

**Comment by ibhagwan** [comment]
Actually I think I know what happened, I changed the invisible-char format to use a Unicode escape sequence `nbsp = "\u{00a0}"`, perhaps it’s not supported by your Lua version, I’ll change it back to what it was and you can test.

**Comment by Parkbro** [comment]
The same thing happens with the blank config. I'm sorry I can't be of more help short notice, I tried amending the pulled code but I couldn't get packer to re-compile the changed code.

**Comment by ibhagwan** [comment]
Update the plug-in and try now?

**Comment by ibhagwan** [comment]
> The same thing happens with the blank config. I'm sorry I can't be of more help short notice, I tried amending the pulled code but I couldn't get packer to re-compile the changed code. (I am on linux (Manjaro) Lua 5.4.3

You can either run `:PackerUpdate` followed by `:PackerCompile` or in one go `:PackerSync`

**Comment by Parkbro** [comment]
Yeah I did that, (I was just printing the line 64 going into the escape function but I couldn't get it to call, maybe needed to do something else to get it to be more useful. Thanks! That change works for me. I really appreciate the quick turnaround

**Comment by ibhagwan** [comment]
Happy to help :)

As a bonus this also forced me to push the `lsp_refs` on my WIP LSP functions so you get that as well.

**Comment by Parkbro** [comment]
That's good! Thanks again (Might be unrelated to your recent push but just thought to mention on the git_files() I am getting
```
Error executing luv callback:
...packer/start/nvim-web-devicons/lua/nvim-web-devicons.lua:972: E5560: nvim_command must not be called in a lua loop callback
Press ENTER or type command to continue
```
It still loads afterwards so I can still use the command but just thought to mention it in case you can reproduce. Only happens first time I call it, and subsequent calls I do not receive it.

**Comment by ibhagwan** [comment]
Very strange indeed, as it uses the same code as `files()` although with a difference command, `git ls-files` instead of `fd`… and the error is generated by the `nvim-dev-webicons`, can you try with `lua require('fzf-lua').git_files({ file_icons = false })`?

This should hide the file icons but will give me an indicator where the problematic code potentially lies.

**Comment by Parkbro** [comment]
Yes I was testing just the same. 
```
require'fzf-lua'.setup {
  bat_theme           = 'TwoDark', -- bat preview theme (bat --list-themes)
  bat_opts            = '--style=numbers,changes --color always',
  files = {
    prompt            = 'Files❯ ',
    cmd               = '',           -- "find . -type f -printf '%P\n'",
    git_icons         = false,         -- show git icons?
    file_icons        = false,         -- show file icons?
    color_icons       = true,         -- colorize file|git icons
  }
}
```
With this as my config it works fine.
With this it also works:
```
```
require'fzf-lua'.setup {
  bat_theme           = 'TwoDark', -- bat preview theme (bat --list-themes)
  bat_opts            = '--style=numbers,changes --color always',
  files = {
    prompt            = 'Files❯ ',
    cmd               = '',           -- "find . -type f -printf '%P\n'",
    git_icons         = true,         -- show git icons?
    file_icons        = true,         -- show file icons?
    color_icons       = false,         -- colorize file|git icons
  }
}
```
It appears to be pairing the `color_icons` with `git_icons` or `file_icons` as both `true`

**Comment by ibhagwan** [comment]
I just looked [nvim-web-devicons.lua:972](https://github.com/kyazdani42/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua#L972) which points to the `set_up_highlights` which apparently is called once on loading the devicons plug-in.

Are you by chance lazy loading it (by adding `opt = true`, or `cmd = …` in packer? Perhaps try and move the dev icons plug-in to its own line separate of any other requirements:
```lua
use { 'kyazdani42/nvim-web-devicons' }
```

**Comment by Parkbro** [comment]
It's my fault, it was lualine using the same with opt=True. Sorry for wasting your time

**Comment by ibhagwan** [comment]
Just in case I also changed the colors escape sequences to potentially support older versions of Lua, try the latest commit and let me know?

**Comment by Parkbro** [comment]
I'm afraid the changing of the nvim-web-devicons, disabling lualine entirely, and disabling the opts do not stop the error from occurring. I downloaded the nvim.appimage from github in case manjaro did something funky with its complication, but running on that version I got the same error I did with neovim nightly .6 on the git_files() command which was 

```
E5108: Error executing lua ...nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:215: ...l/share/nvim/site/pack/packer/start/nvim-fzf/lua/fzf.lua:130: ...nvim/site/pack/packer/start/nvim-fzf/lua/fzf/helpers.lua:29: bad argument #1 to 'new_pipe' (boolean expected, got no value)
```
Which is not the original error but was actually what prompted me to make the original ticket.

**Comment by Parkbro** [comment]
Yes I have just cleaned up nvim to just be the one plugin and the issue above persists in the nvim.image on neovim's github page, and the ```nvim-web-devicons.lua:972: E5560: nvim_command must not be called in a lua loop callback``` in the manjaro version of neovim. I get the loop callback error in the 0.6 nightly version as well. (Just trying to save as much time as possible)

Taking the webicons out of the plugin scope and ignoring it, fixes the issue in the manjaro verison of neovim as well as the nightly verison. The same newpipe issue in the github version of 0.5

**Comment by ibhagwan** [comment]
I’ll do some testing with 0.6 later today and keep you posted.

just to be clear aside from the 0.6 error and the git_files init issue everything else works?

**Comment by Parkbro** [comment]
I believe so from what I can tell! Thanks, there's no rush at all, I'll see
if I have the time to look more tomorrow myself. Have a good Sunday

**Comment by ibhagwan** [comment]
> I'm afraid the changing of the nvim-web-devicons, disabling lualine entirely, and disabling the opts do not stop the error from occurring. I downloaded the nvim.appimage from github in case manjaro did something funky with its complication, but running on that version I got the same error I did with neovim nightly .6 on the git_files() command which was
> 
> ```
> E5108: Error executing lua ...nvim/site/pack/packer/start/fzf-lua/lua/fzf-lua/core.lua:215: ...l/share/nvim/site/pack/packer/start/nvim-fzf/lua/fzf.lua:130: ...nvim/site/pack/packer/start/nvim-fzf/lua/fzf/helpers.lua:29: bad argument #1 to 'new_pipe' (boolean expected, got no value)
> ```
> 
> Which is not the original error but was actually what prompted me to make the original ticket.

I’m not sure why but libuv `vim.loop.new_pipe` and `vim.loop.spawn` behaves differently in the 0.5 release vs the 0.5 release installed by my distro (void) which breaks `nvim-fzf`.

I’ll have more time to check it later but perhaps @ vijaymarupudi can help, otherwise I’ll fork the repository make the fixes and create PR for him later today.

**Comment by ibhagwan** [comment]
Open [nvim-fzf issue #14](https://github.com/vijaymarupudi/nvim-fzf/issues/14)

**Comment by ibhagwan** [comment]
I forked `nvim-fzf` and fixed this issue, I also [created a PR for the fix](https://github.com/vijaymarupudi/nvim-fzf/pull/15), before it gets pulled you can use my fork as a workaround:

```lua
use { 'ibhagwan/fzf-lua',
  requires = { 'ibhagwan/nvim-fzf' }
}
```

**Comment by vijaymarupudi** [comment]
Just merged, apologies for the delay!

**Comment by ibhagwan** [comment]
Ty!

**Comment by ibhagwan** [comment]
> That's good! Thanks again (Might be unrelated to your recent push but just thought to mention on the git_files() I am getting
> 
> ```
> Error executing luv callback:
> ...packer/start/nvim-web-devicons/lua/nvim-web-devicons.lua:972: E5560: nvim_command must not be called in a lua loop callback
> Press ENTER or type command to continue
> ```
> 
> It still loads afterwards so I can still use the command but just thought to mention it in case you can reproduce. Only happens first time I call it, and subsequent calls I do not receive it.

FYI, I was able to fix this error as well, so you're now able to lazy load `nvim-web-devicons` if you wish.

**Comment by Parkbro** [comment]
Thanks! You're the best!
