### ISSUE TITLE
[ Request ] - lsp_document_symbols filter argument

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#80]
Hey there, 

I've never been a big fan out "outline" views in Vim as I can't get them to ever work well with split windows.

I've been experimentin with using `lsp_document_symbols` command to work similarily to a document outline, but obviously a bit flatter. 

What would be interesting is if I was able to do something similar to `FzfLua lsp_document_symbols METHODS` and output all the methods of the file. Repeat for any LSP kind.

**Comment by ibhagwan** [comment]
It’s already possible with `workspace_symbols` by supplying `query`argument:
```lua
:FzfLua lsp_workspace_symbols query=METHODS
```
I will add this functionality to document symbols too, is this what you’re after?

**Comment by ldelossa** [comment]
Would be great!

**Comment by ldelossa** [comment]
> It’s already possible with `workspace_symbols` by supplying `query`argument:
> 
> ```lua
> :FzfLua lsp_workspace_symbols query=METHODS
> ```
> 
> ~I will add this functionality to document symbols too, is this what you’re after?~ I actually cannot add query to `document_symbol` as this is not supported by the LSP implementation [only the workspace_symbol function supports `{query}`](https://neovim.io/doc/user/lsp.html).

Ahh I see.

**Comment by ibhagwan** [comment]
> > It’s already possible with `workspace_symbols` by supplying `query`argument:
> > ```lua
> > :FzfLua lsp_workspace_symbols query=METHODS
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ~I will add this functionality to document symbols too, is this what you’re after?~ I actually cannot add query to `document_symbol` as this is not supported by the LSP implementation [only the workspace_symbol function supports `{query}`](https://neovim.io/doc/user/lsp.html).
> 
> Ahh I see.

I can still easily do it, but the filtering would have to be done inside fzf-lua instead, try out the `lsp_live_workspace_symbols` provider which sends your queries to the LSP server as you type (similar to live grep).

If these results are what you’re after I can add a `current_buffer_only` flag to `lsp_workspace_symbols` you can use that instead of `lsp_document_symbols`.

**Comment by ldelossa** [comment]
To emulate a replacement to an "outline" plugin, all symbols in the
document should be present first (not have to be searched for).

**Comment by ibhagwan** [comment]
I'm not aware of the the outline plugin, I just added the option to filter all LSP functions by current buffer, try it out and let me know if that works for you?

```lua
:lua require('fzf-lua').lsp_workspace_symbols({ current_buffer_only = true, query = 'edit' })
:lua require('fzf-lua').lsp_references({ current_buffer_only = true })
```

Note that you now have to use `lsp_workspace_symbols` and not `lsp_document_symbols` as the latter does not support a `query` argument.

**Comment by ldelossa** [comment]
This works pretty good! thanks.

**Comment by ibhagwan** [comment]
Great :)

Closing.
