### ISSUE TITLE
bat previewer not found on linux

### ISSUE THREAD

**Issue by ramrom** [ibhagwan/fzf-lua#800]
### Info

- Operating System: Ubuntu
- Shell: zsh
- Terminal: xterm
- `nvim --version`: 0.9.0
- `fzf --version`: 0.29

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  winopts = { preview = { default = "bat" } }
})
```
</details>

### Description 
The mini test uses your default previewer. this is only an issue with the bat previewer. an on linux.

On osx it works. 
on ubuntu, i see the error `sh: 1: bat: not found`

My guess is that it's because the binary is called `batcat` and not `bat`. it's called `bat` on osx.

(on linux i have alias for bat -> batcat)

**Comment by ibhagwan** [comment]
The error message is self explanatory, the `sh` shell can’t find the executable `bat`, if `batcat` is your executable use setup to set `previewers.bat.cmd` to `batcat`.

**Comment by ramrom** [comment]
aah dangit, I was scouring the README and i missed that part of it. 

Maybe the cmd should be a default? I guess not many people run linux.

thanks!

**Comment by ibhagwan** [comment]
> I guess not many people run linux.

I'm on Linux :-)

![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/571eb578-1580-4330-a8a8-32a23ae36b4f)

**Comment by yao-weijie** [comment]
> The error message is self explanatory, the `sh` shell can’t find the executable `bat`, if `batcat` is your executable use setup to set `previewers.bat.cmd` to `batcat` on Linux:
> 
> ```lua
> require('fzf-lua').setup({
>   winopts = { preview = { default = "bat" } },
>   previewers = { bat = {
>     cmd = vim.loop.os_uname().sysname == "Darwin" and "bat" or "batcat"
>   } }
> })
> ```

Actually on Debian series distros, the bat cmd is `batcat`

```
❯ apt show bat
Package: bat
Version: 0.24.0-1
Built-Using: rust-ansi-colours (= 1.1.1-1), rust-onig-sys (= 69.8.1-1), rustc (= 1.70.0+dfsg1-1)
Priority: optional
Section: utils
Source: rust-bat
Maintainer: Debian Rust Maintainers <pkg-rust-maintainers@alioth-lists.debian.net>
Installed-Size: 5,299 kB
Depends: libc6 (>= 2.34), libgcc-s1 (>= 4.2), libgit2-1.7 (>= 1.7.0)
Homepage: https://github.com/sharkdp/bat
X-Cargo-Built-Using: rust-adler (= 1.0.2-2), rust-aho-corasick (= 1.1.2-1), rust-ansi-colours (= 1.1.1-1), rust-anstream (= 0.6.4-1), rust-anstyle (= 1.0.4-1), rust-anstyle-parse (= 0.2.1-1), rust-anstyle-query (= 1.0.0-1), rust-base64 (= 0.21.5-1), rust-bincode (= 1.3.3-1), rust-bitflags-1 (= 1.3.2-5), rust-bitflags (= 2.4.0-2), rust-bstr (= 1.7.0-2), rust-bytemuck (= 1.14.0-1), rust-bytesize (= 1.3.0-1), rust-cfg-if (= 1.0.0-1), rust-clap-builder (= 4.4.6-1), rust-clap (= 4.4.6-1), rust-clap-lex (= 0.5.0-1), rust-clircle (= 0.4.0-1), rust-colorchoice (= 1.0.0-1), rust-console (= 0.15.7-1), rust-content-inspector (= 0.2.4-1), rust-crc32fast (= 1.3.2-2), rust-encoding-rs (= 0.8.33-1), rust-etcetera (= 0.8.0-1), rust-flate2 (= 1.0.27-2), rust-fnv (= 1.0.7-1), rust-form-urlencoded (= 1.2.1-1), rust-git2 (= 0.18.1-1), rust-globset (= 0.4.14-1), rust-grep-cli (= 0.1.10-1), rust-hashbrown (= 0.12.3-1), rust-home (= 0.5.5-1), rust-idna (= 0.4.0-1), rust-indexmap (= 1.9.3-1), rust-itoa (= 1.0.9-1), rust-lazy-static (= 1.4.0-2), rust-libc (= 0.2.150-1), rust-libgit2-sys (= 0.16.1-1), rust-libz-sys (= 1.1.8-2), rust-line-wrap (= 0.1.1-1), rust-linked-hash-map (= 0.5.6-1), rust-linux-raw-sys (= 0.4.11-1), rust-log (= 0.4.20-2), rust-memchr (= 2.6.4-3), rust-miniz-oxide (= 0.7.1-1), rust-nu-ansi-term (= 0.48.0-2), rust-once-cell (= 1.18.0-1), rust-onig (= 6.3.2-1), rust-onig-sys (= 69.8.1-1), rust-onig-sys (= 69.8.1-1), rust-path-abs (= 0.5.1-1), rust-percent-encoding (= 2.3.0-1), rust-plist (= 1.6.0-1), rust-quick-xml (= 0.27.1-3), rust-regex-automata (= 0.4.3-1), rust-regex (= 1.10.2-1), rust-regex-syntax (= 0.8.2-1), rust-rgb (= 0.8.36-1), rust-rustix (= 0.38.25-1), rust-ryu (= 1.0.15-1), rust-safemem (= 0.3.3-1), rust-same-file (= 1.0.6-1), rust-semver (= 1.0.18-1), rust-serde (= 1.0.192-1), rust-serde-json (= 1.0.108-1), rust-serde-yaml (= 0.8.26-1), rust-shell-words (= 1.1.0-1), rust-smallvec (= 1.11.2-1), rust-std-prelude (= 0.2.12-1), rust-strsim (= 0.10.0-1), rust-syntect (= 5.1.0-2), rust-termcolor (= 1.3.0-1), rust-terminal-size (= 0.2.6-3), rust-thiserror (= 1.0.50-1), rust-time-core (= 0.1.1-1), rust-time (= 0.3.23-2), rust-unicode-bidi (= 0.3.13-1), rust-unicode-normalization (= 0.1.22-1), rust-unicode-width (= 0.1.11-1), rust-url (= 2.4.1-1), rust-utf8parse (= 0.2.1-1), rust-walkdir (= 2.4.0-1), rust-wild (= 2.1.0-1), rust-yaml-rust (= 0.4.5-1), rustc (= 1.70.0+dfsg1-1)
Download-Size: 2,193 kB
APT-Manual-Installed: yes
APT-Sources: https://mirrors.tuna.tsinghua.edu.cn/debian testing/main amd64 Packages
Description: cat(1) clone with syntax highlighting and git integration
 bat is a drop-in cat(1) replacement featuring:
 .
  * syntax highlighting for a large number of languages;
  * git integration;
  * automatic paging;
  * a user-friendly command-line interface.
 .
 In this package the executable and its manpage have been renamed from ‘bat’ to
 ‘batcat’ because of a file name clash with another Debian package.

```

I suggest to set the bat default cmd like this, and I don't have to write it in my config :)

```lua
require('fzf-lua').setup({
  previewers = {
    bat = {
      cmd = vim.fn.executable("batcat") == 1 and "batcat" or "bat",
    }
  }
```

**Comment by ibhagwan** [comment]
> I suggest to set the bat default cmd like this, and I don't have to write it in my config :)

Sure we cans do that, I’ll change it next time I get a chance or you’re welcome to submit a PR, here’s where it’s set:
https://github.com/ibhagwan/fzf-lua/blob/209e9405d2df949cbffe5b7b9329756b83bf2339/lua/fzf-lua/defaults.lua#L143-L157

**Comment by haunt98** [comment]
Hi, I use macOS but after update, I got hit with `sh: batcat: command not found`

<img width="1488" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/5424272/60477d3e-c820-46b7-9565-520235228bcf">

My dot is [here](https://github.com/haunt98/dotfiles/blob/a2287fdc486b08c13231923d9f54761bb1e3502c/data/nvim/init.lua#L126)

**Comment by ibhagwan** [comment]
@haunt98, this was an oversight of PR #958, fixed with latest commit https://github.com/ibhagwan/fzf-lua/commit/407323ade0ebca1bb4f26453c1aacbb246654139.

**Comment by haunt98** [comment]
Thank you @, it works again!
