### ISSUE TITLE
Can't get highlight of icons in "NvChad"

### ISSUE THREAD

**Issue by GreenSleeper** [ibhagwan/fzf-lua#801]
Any one using `NvChad` here?
It seems that `fzf-lua` can't get the highlight of icons in `NvChad`.

**Comment by ibhagwan** [comment]
It’s very rare that anyone would respond to issues here other than myself, let me try and help you.

Not sure I understand the question though.
- Does NvChad come with fzf-lua preconfigured?
- What do you mean by icon highlights not working?
- How does the fzf-lua `setup` function look like?

**Comment by GreenSleeper** [comment]
> It’s very rare that anyone would respond to issues here other than myself, let me try and help you.

I actually didn't want to add this issue, 'cause I thought it was just a user question. But I couldn't find a discussison anywhere, so sorry to bother you.
I've created serveral issues here, everytime you've patiently helped me, I cannot thank you enough man.

> Does NvChad come with fzf-lua preconfigured?

No.

> What do you mean by icon highlights not working?

File icons in `fzf-lua` are all grey, like:
![image](https://github.com/ibhagwan/fzf-lua/assets/95287687/f626457b-965a-4535-9140-15b7ea5aabc7)
They should look like:
![image](https://github.com/ibhagwan/fzf-lua/assets/95287687/c00872b1-ccc2-47ad-a204-313b653a2a77)


> How does the fzf-lua setup function look like?

```lua
{
    "ibhagwan/fzf-lua",
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    opts = {
      "borderless_full",
      global_git_icons = false,
      winopts = {
        hl = {
          title = "IncSearch",
        },
      },
    },
  }
```

I tried not to lazy load `nvim-web-devicons`, didn't work.

BTW, no icon highlight isn't a big deal, if it's too much trouble, just ingore this.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/26cc8e35ecdd02e03aeab39149187c3af3641add

@GreenSleeper, this was actually a bug (sort of...), I'm not sure why but the `get_icon` and `get_icons` method of devicons when called from NvChad returns an empty color field on some highlights, the commit above attempts to acquire the color from the highlight group setup by devicons as fallback which should solve your issue.

**Comment by GreenSleeper** [comment]
> [26cc8e3](https://github.com/ibhagwan/fzf-lua/commit/26cc8e35ecdd02e03aeab39149187c3af3641add)
> 
> @GreenSleeper, this was actually a bug (sort of...), I'm not sure why but the `get_icon` and `get_icons` method of devicons when called from NvChad returns an empty color field on some highlights, the commit above attempts to acquire the color from the highlight group setup by devicons as fallback which should solve your issue.

It works, thank you!
