### ISSUE TITLE
Documentation Suggestion: filter_buffers()

### ISSUE THREAD

**Issue by EmreDogann** [ibhagwan/fzf-lua#802]
I was playing around with Scope.nvim and was having trouble with `:FzfLua tabs` because Scope.nvim will set buffers in other tabs to unlisted. I searched through the docs and couldn't find anything but after looking 
through the source, I found this in `filter_buffers()`:
https://github.com/ibhagwan/fzf-lua/blob/577f2a74c6914515d45a4c1f390978c18d9cd3cb/lua/fzf-lua/providers/buffers.lua#L52-L70

All of these options are very useful but some of them aren't shown in the documentation such as `ignore_current_buffer`, and `current_tab_only`. Along with that, the filtering options that are shown are buried in the long `Default Options` section in the readme which can make then hard to find and don't have very clear documentation on what they do exactly. A lot of these options are self-explanatory but as mentioned the main issue is discoverability.

An entry in the wiki or readme going over the different filtering options would be very helpful! :)

**Comment by ibhagwan** [comment]
> An entry in the wiki or readme going over the different filtering options would be very helpful! :)

Tthere are many obscure options which you can find in the code or in the issues, unfrotuntately being the sole maintainer for this project, I didn't have time to document all of it and when I have time I'd rather priortize issues and enhancements.

That's why the wiki is open edit to all, you're welcome to add proper documentation to all of these :-)

**Comment by EmreDogann** [comment]
Oh I was unaware the docs were open. I shall give it shot them! :)

**Comment by ibhagwan** [comment]
> Oh I was unaware the docs were open. I shall give it shot then! :)

Ty @EmreDogann!

**Comment by EmreDogann** [comment]
I added a new section to the wiki home page called '**Filtering Results**'.

**Comment by ibhagwan** [comment]
Tysm @EmreDogann!

I moved your edit into it's own section:
https://github.com/ibhagwan/fzf-lua/wiki/Options

We can consider it WIP to document **all the hidden options** within fzf-lua, note that some options apply only to some providers, for example `current_tab_only` applies only to buffer type providers and does nothing for `files`, this can be furhter clarfied slowly.

**Comment by EmreDogann** [comment]
> note that some options apply only to some providers,

Ah yes, I see. Yeah, over time these can be worked on as a WIP.
In that case, I will close this issue, thanks for the help!
