### ISSUE TITLE
Syntax highlighting doesn't work in files preview for custom file types.

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [ibhagwan/fzf-lua#803]
### Info

- Operating System:
- Shell:
- Terminal:
- `nvim --version`: NVIM v0.9.1    
- `fzf --version`: 0.42.0 (brew)

- [x] The issue is reproducible with `mini.sh`

### Description 

I am using following auto command to want to enable SQL syntax highlighting for files with extension `*.ksql`
```
autocmd BufEnter *.ksql setlocal filetype=sql
```

When I open such files - syntax highlighting works, but when I execute `:FzfLua files` - the preview window doesn't highlight the syntax for `*.ksql` files.

Can you please help ?

**Comment by ibhagwan** [comment]
The preview buffer has autocmds disabled and the treesitter highlighting is performed manually, this has many reasons one of which to disable LSP analysis on the preview buffer as well as other potential collisions with other plug-in autocmds - this means your autocmd doesn’t do anything in the context of the preview buffer.

The filetype is determined by a call to `vim.filetype.match` which doesn’t know about your override:

https://github.com/ibhagwan/fzf-lua/blob/c3c71df6ffba3cc90335c538fad81aa7a0182e57/lua/fzf-lua/previewer/builtin.lua#L774-L775

The only solution I can offer is a manual config override within Fzf-lua, something like:
```lua
ext_override = { ['ksql'] = 'sql', … }
```

If this is something you can live with I can implement if pretty quickly.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d5e21216629f277377329374f7f0890714ce1220

@ievgenii-shepeliuk, update to the latest commit and add the below to your `setup`:
```lua
require("fzf-lua").setup({
  previewers = {
    builtin = {
      ext_ft_override = {
        ["ksql"] = "sql",
        -- other filetype overrides
      }
    }
  }
})
```

**Comment by ievgenii-shepeliuk** [comment]
Hello @ibhagwan 

It's working now, thank you.

**Comment by eshepelyuk** [comment]
@ibhagwan can you please add this option to README ?

**Comment by eshepelyuk** [comment]
Confirming that from my side it's working.

**Comment by ibhagwan** [comment]
@phanen, https://github.com/ibhagwan/fzf-lua/commit/ccda5841597787fc3522480aca7179193d8aac14
