### ISSUE TITLE
Is there a debounce mechanism for fzf-live?

### ISSUE THREAD

**Issue by milogert** [ibhagwan/fzf-lua#804]
### Info

- Operating System:
- Shell: zsh
- Terminal: Kitty
- `nvim --version`: v0.9.1
- `fzf --version`: 0.42.0 (0.42.0)

### Description 

Is it possible to have some sort of debounce timeout so `fzf_live` only runs the query after you stop typing for a number milliseconds or something?

Thinking about searching using `gh` (via Octo.nvim) it's very slow when it has to make requests on every keystroke especially when I know I'm not done typing, so forcing a delay could be helpful to speed things up (either perceived or actual speed).

**Comment by ibhagwan** [comment]
I can look into adding a denounce mechanism to the live variant.

[Fzf has a previewer debounce](https://github.com/junegunn/fzf/issues/2417#issuecomment-809886535) which I believe also applies to the live query but I might be wrong.

**Comment by ibhagwan** [comment]
Btw, the previewer has a debounce timer (customizable via `winopts.preview.delay`):

https://github.com/ibhagwan/fzf-lua/blob/b1ee200e50f11506be7dcb9c529ce091b375dc6a/lua/fzf-lua/previewer/builtin.lua#L291-L306

**Comment by ibhagwan** [comment]
https://github.com/junegunn/fzf/issues/2421 - the proposed solution by fzf's author is to add `sleep` to the command.

https://github.com/ibhagwan/fzf-lua/commit/c3c71df6ffba3cc90335c538fad81aa7a0182e57 - this commits adds a new option `query_delay` (miliseconds) which will add a deboucne before the command:
```lua
:lua require'fzf-lua'.fzf_live("rg --column --color=always -- <query> 2>/dev/null", {query_delay = 2000})
```
This works whether the `contents` is a shell command, table or funciton.

**Comment by milogert** [comment]
So to be clear this just delays the query? I was thinking something more along the lines that detects when you have stopped typing for a number of seconds then it runs the query. Or would that even be possible without `fzf` intervention?

**Comment by ibhagwan** [comment]
> So to be clear this just delays the query? I was thinking something more along the lines that detects when you have stopped typing for a number of seconds then it runs the query. Or would that even be possible without `fzf` intervention?

Read the linked fzf issue, this will have the same effect and the launched sleep processes will get killed as the typing continues.

IMHO, it’s a great solution that solves this issue for a very low cost.

**Comment by ibhagwan** [comment]
Try it out, it achieves exactly what you’re after.

**Comment by ibhagwan** [comment]
@milogert - did you get a chance to try this?

**Comment by jwoos** [comment]
Not OP, but I added the suggested sleep prior to my command and it works!

e.g. `sleep 0.1; <some command>`

Thanks for the pointer

**Comment by ibhagwan** [comment]
> Not OP, but I added the suggested sleep prior to my command and it works!
> 
> e.g. `sleep 0.1; <some command>`
> 
> Thanks for the pointer

Ty for the update @jwoos!

**Comment by milogert** [comment]
@ibhagwan I'm so sorry for the lateness of my reply, we've been in the middle of a move for a while and I had some big life changes. I finally buckled down this morning to test that out and it seems to work as you described it.

Thank you for working on this. Probably something will get added to Octo.nvim utilizing this (right now the `:Octo search` feature using fzf-lua is _slow_ without this feature)

**Comment by ibhagwan** [comment]
> @ibhagwan I'm so sorry for the lateness of my reply, we've been in the middle of a move for a while and I had some big life changes. I finally buckled down this morning to test that out and it seems to work as you described it.
> 
> Thank you for working on this. Probably something will get added to Octo.nvim utilizing this (right now the `:Octo search` feature using fzf-lua is _slow_ without this feature)
> 
> Edit: for those not aware: I wrote the integration with Octo.nvim and fzf-lua, so I am aware it was slow because I made it that way :) not blaming anybody here but myself!

No worries @milogert, sometime life gets priority over open source, I haven’t been able to get to some of the more complex issues myself :)

**Comment by ibhagwan** [comment]
@milogert, given this is working as expected I'm going to close this issue, feel free to reopen if this doesn't solve your issue or it requires further refinement.
