### ISSUE TITLE
Can not use keymaps defined in actions when fzf is empty, i.e. when there are zero entries

### ISSUE THREAD

**Issue by RaviRahar** [ibhagwan/fzf-lua#805]
### Description 

I was trying to make custom functions for me. It uses 3 modes: live_grep, files and dirs(custom). The following is a code snippet of dir mode, othes are similar:
```lua
M.mod_dir = function(opts)
    -- traverse to parent directory with "backspace", "ctrl-h"
    -- dir_mode: fuzzy find among directories, <CR> to go inside
    -- switch to "files" with ctrl-p (root_dir)
    -- switch to "live_grep" with ctrl-/ (root_dir)
    -- cycle between modes with ctrl-f (root_dir)(mode "files")
    opts = opts or {}
    opts.cwd = opts.cwd or vim.uv.cwd()
    opts.actions = nil
    opts.actions = {
        ['ctrl-h'] = { fn = function()
            local parent_dir_path = fzf_lua.path.parent(opts.cwd)
            opts.cwd = parent_dir_path
            M.mod_dir(opts)
        end, reload = true },
        ['return'] = { fn = function(selected)
            local cur_dir_path = selected[1]
            local next_dir_path = fzf_lua.path.join({ opts.cwd, cur_dir_path })
            opts.cwd = next_dir_path
            M.mod_dir(opts)
        end, reload = true },
        ['ctrl-p'] = { fn = M.mod_files, reload = true },
        ['ctrl-/'] = { fn = M.mod_live_grep, reload = true },
        ['ctrl-f'] = { fn = M.mod_files, reload = true },
    }
    fzf_lua.fzf_exec(M.get_dir_cmd(opts), opts)
end
```

The problem is that when there are zero results in fzf (for example: if cwd has 0 directories or when I haven't started typing in case of live_grep), then none of the keymaps defined in actions work. Can I do something to make them work?   
P.S. I am using default config other than this.

**Comment by ibhagwan** [comment]
@RaviRahar, that's because the `reload` and `execute-silent` fzf binds are specificed by default with the fzf field index `{+}`  which means "all selected items", when there are no items fzf won't fire the bind.

https://github.com/ibhagwan/fzf-lua/commit/546e3eb8012f46eb862bcd021598f5f1df8b82bb - this commit adds the option to specify the fzf field index expression which in the case of `ctrl-h` needs to be an empty string as the selected item doesn't matter in this case, the new code  should look like:
> Note that you aren't really reloading the fzf interface (that would be a different strategy), you're calling `fzf_exec` in recursion instead which restarts the fzf process, I find `exec_silent` a more approperiate option here, even though both would work:
```lua
local fzf_lua = require("fzf-lua")
local M = {}
M.mod_dir = function(opts)
    opts = opts or {}
    opts.cwd = opts.cwd or vim.loop.cwd()
    opts.actions = {
        ['ctrl-h'] = { fn = function()
            print("ctrl-h")
            local parent_dir_path = fzf_lua.path.parent(opts.cwd)
            opts.cwd = parent_dir_path
            M.mod_dir(opts)
        end, exec_silent = true, field_index = false },
        ['return'] = { fn = function(selected)
            print("ret")
            local cur_dir_path = selected[1]
            local next_dir_path = fzf_lua.path.join({ opts.cwd, cur_dir_path })
            opts.cwd = next_dir_path
            M.mod_dir(opts)
        end, exec_silent = true },
    }
    fzf_lua.fzf_exec("ls", opts)
end
M.mod_dir()
```

> when I haven't started typing in case of `live_grep`

FYI, you can make `live_grep` return results by running `rg` with an empty string for search using:
> https://github.com/ibhagwan/fzf-lua/wiki#live_grep-shows-no-results-before-i-start-typing
```lua
:lua require("fzf-lua").live_grep({ exec_empty_query = true })
```

**Comment by RaviRahar** [comment]
Okay
Two more questions (unrelated to this thread): 
1. Is there a function to strip file icons. Basically Undo this. I am using the "selection" and it contains the icon.
``` lua
    opts.fn_transform = function(file_name)
        return fzf_lua.make_entry.file(file_name, { file_icons = true, color_icons = true })
    end
```

2. How can I check if prompt is empty? I want to use backspace for something else if it is.

Also thanks for the plugin. Its super fast (Also your reply :) )

**Comment by ibhagwan** [comment]
1. Use `require’fzf-lua'.path.entry_to_file(selected[1])`
2. `require’fzf-lua'.get_last_query()`

**Comment by RaviRahar** [comment]
Thanks. Can you please look the following code, return does not work as intended ( shows blank fzf) when I use fn_transform. When I remove it it does.
```lua
M.mod_dir = function(opts)
    opts = opts or {}
    opts.cwd = opts.cwd or vim.uv.cwd()
    opts.fn_transform = function(file_name)
        return fzf_lua.make_entry.file(file_name, { file_icons = true, color_icons = true })
    end
    opts.actions = {
        ['ctrl-h'] = { fn = function()
            local parent_dir_path = fzf_lua.path.parent(opts.cwd)
            opts.cwd = parent_dir_path
            M.mod_dir(opts)
        end, exec_silent = true, field_index = false },
        ['return'] = { function(selected)
            local cur_dir_path = fzf_lua.path.entry_to_file(selected[1]).path
            local next_dir_path = fzf_lua.path.join({ opts.cwd, cur_dir_path })
            opts.cwd = next_dir_path
            M.mod_dir(opts)
        end, fzf_lua.actions.resume },
    }
    fzf_lua.fzf_exec(M.get_dir_cmd(opts), opts)
end

**Comment by RaviRahar** [comment]
Forgot to close the issue.

**Comment by ibhagwan** [comment]
> Thanks. Can you please look the following code, return does not work as intended ( shows blank fzf) when I use fn_transform. When I remove it, it does.

2 issues here

(1) `ctrl-h` - we don't need the `exec_silent`, this causes fzf to use a `execute-silent` bind spawning a background process which calls `M.mod_dir(opts)` which starts another process (which wil kill the execute-silent process), this is not needed. all we need to convert this to a simple action that terminates the fzf process and starts a new one (wrapped in a table so the neovim windows don't close elimiateing the "refresh").

(2) `return` - similarly we don't need to call `resume` as this will create yet another process which will terminate the previous call to `mod_dir`.

Convert both actions to simple table-wrapped functions and it will work as expected, my working sample:
```lua
local fzf_lua = require("fzf-lua")
local M = {}

M.mod_dir = function(opts)
  opts = opts or {}
  opts.cwd = opts.cwd or vim.loop.cwd()
  opts.fn_transform = function(file_name)
    return fzf_lua.make_entry.file(file_name, { file_icons = true, color_icons = true })
  end
  opts.actions = {
    ['ctrl-h'] = { function()
      local parent_dir_path = fzf_lua.path.parent(opts.cwd)
      opts.cwd = parent_dir_path
      M.mod_dir(opts)
    end },
    ['return'] = { function(selected)
      local cur_dir_path = fzf_lua.path.entry_to_file(selected[1]).path
      local next_dir_path = fzf_lua.path.join({ opts.cwd, cur_dir_path })
      opts.cwd = next_dir_path
      M.mod_dir(opts)
    end },
  }
  fzf_lua.fzf_exec("ls", opts)
end

M.mod_dir()
```

**Comment by ibhagwan** [comment]
FYI, regarding actions:

- `exec_silent` is used when you wish to perform a background action that doesn't refresh the interface, for example, copying the entry to a neovim register, like in `commits|bcommits`.

- A `reload` action uses fzf's `change:reload` event to reload the interface without restarting the process, this helps with UX when you wish to leave the cursor in the same place and have that "smoothness" effect, for example, changing the staging status with `git_status`, while this could be used here I'm not sure I see the benefit as each call is a different directory and there would be no point in reloading the interface when the entire list is changed. You might make the case for a reload action if you wish to delete/add folders/files and leave the cursor in place but for changing a folder I don't see the benfit.

**Comment by RaviRahar** [comment]
I looked at it. But I don't seem to be getting why it works when there is no fn_transform, but doesn't when there is one. The following is code, there is no other change, I just comment out fn_transform and it works.
```lua 
M.mode_dir = function(opts)
    opts = opts or {}
    opts.cwd = opts.cwd or vim.uv.cwd()
    -- opts.fn_transform = function(file_name)
    --     return fzf_lua.make_entry.file(file_name, { file_icons = true, color_icons = true })
    -- end
    opts.prompt = M.edit_prompt_dir_mode(opts.cwd)
    opts.dir_empty = false
    opts.last_mode = "mode_dir"
    fzf_lua.config.__resume_data = opts
    opts.actions = {
        [M.parent_dir_key] = { fn = function()
            local parent_dir_path = fzf_lua.path.parent(opts.cwd)
            opts.cwd = parent_dir_path
            M.mode_dir(opts)
        end, exec_silent = true, field_index = false },
        ['return'] = { fn = function(selected)
            local selected_query = selected[1]
            if opts.dir_empty then
                local parent_dir_path = fzf_lua.path.parent(opts.cwd)
                opts.cwd = parent_dir_path
            else
                local cur_dir_path = fzf_lua.path.entry_to_file(selected_query).path
                local next_dir_path = fzf_lua.path.join({ opts.cwd, cur_dir_path })
                opts.cwd = next_dir_path
            end
            M.mode_dir(opts)
        end, exec_silent = true },
        [M.cycle_key] = { fn = function()
            opts.prompt = nil
            M.mode_files(opts)
        end, exec_silent = true, field_index = false },
    }
    local cmd_num_files = string.format("find -L %s -maxdepth 1 -mindepth 1 -type d | wc -l", opts.cwd)
    local num_files = tonumber(vim.fn.system(cmd_num_files))
    if num_files and num_files > 0 then
        fzf_lua.fzf_exec(M.cmd_get_dir(opts), opts)
    else
        opts.dir_empty = true
        fzf_lua.fzf_exec({ "Empty Dir. Go Back?" }, opts)
    end
end
```
Also I use reload because its so much smoother (or exec_silent). But main question is why it works without fn_transform?

**Comment by RaviRahar** [comment]
One more question: I want backspace to do something if query is empty and work as normal if not. I have not managed to get second part working (i.e. work as normal backspace). Example code:
```lua
        ['bs'] = function()
            if #fzf_lua.get_last_query() == 0 then
                local parent_dir_path = fzf_lua.path.parent(opts.cwd)
                opts.cwd = parent_dir_path
            else
                local last_query = fzf_lua.get_last_query()
                local new_query = string.sub(last_query, 1, -2)
                fzf_lua.set_last_query(new_query)
                -- local backspace = vim.api.nvim_replace_termcodes('<BS>', false, false, true)
                -- vim.api.nvim_feedkeys(backspace, 'i', false)
            end
            M.mode_files(opts)
        end,
```

**Comment by RaviRahar** [comment]
btw here is the code for [combi mode](https://github.com/RaviRahar/dotfiles/blob/main/home/.config/nvim/lua/extras/fzf_combi_mode.lua), might help someone. It combines dir mode (to switch dirs), grep and files modes. Remembers your last location. Some details:
```lua 
-- opens in current directory, by default in "files"
--
-- traverse to parent directory with "backspace", parent_dir_key (in all modes)
--
-- switch to "mode_files" with files_key (current directory of fzf)
-- switch to "mode_grep" with dir_key (current directory of dir)
-- switch to "mode_dir" with grep_key, (current directory of fzf)
-- cycle between modes with cycle_key (current directory of fzf)
--
-- dir_mode: fuzzy find among directories, <CR> to go inside
--
-- resume from where you left off: same mode, same dir (resume=true)
-- or start a new session from current dir
```

**Comment by ibhagwan** [comment]
> One more question: I want backspace to do something if query is empty and work as normal if not. I have not managed to get second part working (i.e. work as normal backspace). Example code:

This is not the route I would choose, what you did there in the case of a "normal backspace" was: **exit the process, then determine the query and restart the process with a second (shorter) query**, not very efficient, why quit the process for a normal backspace?

If you want to do more complex customizations I highly recommend reading `man fzf` properly, you would then find out about the ability to bind `backward-eof`:
```
       backward-eof
              Triggered when the query string is already empty and you try to
              delete it backward.

              e.g.
                   fzf --bind backward-eof:abort
```

What I would do is bind that to `accept` (instead of the default `abort`) and then use the `default` action to determine when the query is empty thus removing the part where you have to feed the backspace back into fzf, this makes backspace behave like a normal backspace unless the query is empty:
> I used `opts.keymap.fzf` to supply the bind but you could also used `fzf_cli_args` to send raw args directly
```lua
local fzf_lua = require("fzf-lua")
local M = {}

M.mod_dir = function(opts)
  opts = opts or {}
  opts.cwd = opts.cwd or vim.loop.cwd()
  opts.fn_transform = function(file_name)
    return fzf_lua.make_entry.file(file_name, { file_icons = true, color_icons = true })
  end
  -- equivalent to sending `--bind backward-eof:accept`
  opts.keymap = { fzf = { ["backward-eof"] = "accept" },
  }
  opts.actions = {
    ['ctrl-h'] = { function()
      local parent_dir_path = fzf_lua.path.parent(opts.cwd)
      opts.cwd = parent_dir_path
      M.mod_dir(opts)
    end },
    ['return'] = { function(selected)
      local cur_dir_path = fzf_lua.path.entry_to_file(selected[1]).path
      local next_dir_path = fzf_lua.path.join({ opts.cwd, cur_dir_path })
      opts.cwd = next_dir_path
      M.mod_dir(opts)
    end },
    ['default'] = function()
      if #fzf_lua.get_last_query() == 0 then
        local parent_dir_path = fzf_lua.path.parent(opts.cwd)
        opts.cwd = parent_dir_path
        M.mod_dir(opts)
      end
    end,
  }
  fzf_lua.fzf_exec("ls", opts)
end

M.mod_dir()
```

**Comment by RaviRahar** [comment]
> ```lua
> opts.keymap = { fzf = { ["backward-eof"] = "accept" },
> ```

This didn't work for me. It is not going in default section.  
But I got your point, thank you for pointing in right direction. Fzf is a little new for me. I have given some time to reading when setting this one up. I will look into it once I finish some work I have at hand. I won't be able to read man of fzf right now due to that. But I will look few days later.
Again, thank you for being such a help.

**Comment by ibhagwan** [comment]
> This didn't work for me. It is not going in default section.

Did you try my sample?

**Comment by RaviRahar** [comment]
> Did you try my sample?

Yes
```lua
M.mode_files = function(opts)
    opts = opts or {}
    opts.cwd = opts.cwd or vim.uv.cwd()
    opts.fn_transform = nil
    opts.last_mode = "mode_files"
    fzf_lua.config.__resume_data = opts
    opts.keymap = { fzf = { ["backward-eof"] = "accept" }, }
    opts.actions = {
        ['default'] = function()
            if not fzf_lua.get_last_query() or #fzf_lua.get_last_query() == 0 then
                local parent_dir_path = fzf_lua.path.parent(opts.cwd)
                opts.cwd = parent_dir_path
                M.mod_dir(opts)
            end
        end,
        [M.parent_dir_key] = { fn = function()
            local parent_dir_path = fzf_lua.path.parent(opts.cwd)
            opts.cwd = parent_dir_path
            M.mode_files(opts)
        end, exec_silent = true, field_index = false },
    }
    fzf_lua.files(opts)
end
```

**Comment by ibhagwan** [comment]
Perhaps your `bs` is not bound to the default or is overwritten? Try my sample code I posted here **exactly as is**: https://github.com/ibhagwan/fzf-lua/issues/805#issuecomment-1618701571

I would also eliminate any issues coming from your `FZF_DEFAULT_OPTS` by running:
```lua
:lua vim.env.FZF_DEFAULT_OPTS=nil
```
And change reset the `bs` bind using:
```lua
opts.keymap = { fzf = {
  ["bs"] = "backward-delete-char/eof", 
  ["backward-eof"] = "accept"
} }
```

**Comment by RaviRahar** [comment]
> Try my sample code I posted here **exactly as is**: [#805 ](https://github.com/ibhagwan/fzf-lua/issues/805#issuecomment-1618701571)

Okay so I tried again. With minimal setup. Not binding 'bs' anywhere else. I set the vim.env.FZF_DEFAULT_OPTS variable to nil. After that I used this:
```lua
local mode_files = function(opts)
    opts = opts or {}
    opts.cwd = opts.cwd or vim.uv.cwd()
    -- opts.keymap = { fzf = { ["backward-eof"] = "accept" }, }
    opts.keymap = {
        fzf = {
            ["bs"] = "backward-delete-char/eof",
            ["backward-eof"] = "accept"
        }
    }
    opts.actions = {
        ['default'] = function()
            print("hi")
            if #fzf_lua.get_last_query() == 0 then
                local parent_dir_path = fzf_lua.path.parent(opts.cwd)
                opts.cwd = parent_dir_path
                M.mod_dir(opts)
            end
        end,
    }
    fzf_lua.files(opts)
end
```

**Comment by ibhagwan** [comment]
Binding `bs` seems to conflict I guess, this worked for me:
```lua
M.mod_files = function(opts)
  opts = opts or {}
  opts.cwd = opts.cwd or vim.loop.cwd()
  opts.keymap = {
    fzf = {
      ["backward-eof"] = "accept"
    }
  }
  opts.actions = {
    ['default'] = function(sel)
      print("selected", sel[1], "last_q", fzf_lua.get_last_query())
    end,
  }
  fzf_lua.files(opts)
end
```

**Comment by RaviRahar** [comment]
Okay, it is working. Thank you.
It was not working before, I don't know why. But this morning I opened it and it was working (same config) 
I made plugin out of if, just as you suggested. It seems quite small to be a plugin to me :) . It has some rough edges, but I do not have time right now. I will correct them later.
Here is the plugin: [fzf-combi-mode](https://github.com/RaviRahar/fzf-combi-mode)

**Comment by ibhagwan** [comment]
> Okay, it is working. Thank you.
> It was not working before, I don't know why. But this morning I opened it and it was working (same config)
> I made plugin out of if, just as you suggested. It seems quite small to be a plugin to me :) . It has some rough edges, but I do not have time right now. I will correct them later.
> Here is the plugin: [fzf-combi-mode](https://github.com/RaviRahar/fzf-combi-mode)

Nice work @RaviRahar :)
