### ISSUE TITLE
[Q]: Best way to get fzf-lua prompt input?

### ISSUE THREAD

**Issue by vicrdguez** [ibhagwan/fzf-lua#806]
Hi! 

I'm building a picker with _find or create_ functionality. It works as any file picker for `default`, but adds a binding that takes the prompt input as the title to create a new file (is a notes picker).

Looking at the plugin's code and some `vim.inspect`s I found how to do it with:

```lua
actions = {
    ["ctrl-o"] = function(_, fzf_opts)
        local prompt_input = fzf_opts.__resume_data.last_query
        -- do stuff with the prompt
    end
}
```

Is this the correct way? or is there a better source for this value?

Thanks for the plugin! I'm enjoying it a lot.

**Comment by ibhagwan** [comment]
> Is this the correct way? or is there a better source for this value?

That or `require'fzf-lua'.get_last_query()`, whichever you prefer.

> Thanks for the plugin! I'm enjoying it a lot.

Ty <3

**Comment by vicrdguez** [comment]
Awesome, thanks! closing the issue
