### ISSUE TITLE
Get all entries

### ISSUE THREAD

**Issue by tradiff** [ibhagwan/fzf-lua#807]
I am attempting to write an action for the `buffers` provider to delete all buffers except those selected. Kinda like the inverse of CTRL+X. My action is provided with the selected buffers, which I can get bufnrs from. Is there a way for me to also get all of the buffers displayed by fzf-lua? fzf-lua is doing a lot of filtering that I'd rather not repeat.

I've been digging through the source code, and i can't quite figure out how to get to this programatically.

Thanks for your incredible work, I love the plugin!

**Comment by ibhagwan** [comment]
Update to https://github.com/ibhagwan/fzf-lua/commit/6363b14efe02d2fbb42858132606b24e15b5a78e first.

**Requires fzf version 0.36 and above**

```lua
require("fzf-lua").setup({
  buffers = {
    actions = {
      ["ctrl-x"] = { fn = require("fzf-lua").actions.buf_del, reload = true, prefix = "toggle-all+" }
    },
  },
})
```
The prefix `toggle-all+` is taken from fzf available actions, to see the full list `man fzf` and search for `AVAILABLE ACTIONS`.

> Thanks for your incredible work, I love the plugin!

Ty <3

**Comment by tradiff** [comment]
🤯  Ooh, really nice solution!  Worked perfectly.

**Comment by ibhagwan** [comment]
> 🤯 Ooh, really nice solution! Invert the selection, and then call the built-in buf_del. Worked perfectly.

Ty @tradiff!

Edited the title so it's easier for other people to find, since this is yet another obscure undocumented option :-)

**Comment by tradiff** [comment]
My full config for this if anyone else wants to do something similar:
```lua
        buffers    = {
          no_header = true,
          fzf_opts = {
            ['--header'] = [['<ctrl-x> delete unselected']],
          },
          actions = {
            -- delete the unselected buffers
            ['ctrl-x'] = { fn = fzflua.actions.buf_del, reload = true, prefix = 'toggle-all+' }
          }
        }
```
Permalink
https://github.com/tradiff/dotfiles/commit/a6229ffc4da0c618f6a62ed109e5b3c575780ed4
