### ISSUE TITLE
How to paste yanked text to fzf-lua prompt?

### ISSUE THREAD

**Issue by GreenSleeper** [ibhagwan/fzf-lua#808]
How to paste yanked text to `fzf-lua` prompt?
I tried `C-r`+`register`, didn't work.

**Comment by ibhagwan** [comment]
Fzf-lua main window is a terminal window (fzf), in neovim, you can’t paste directly into a terminal buffer with `<C-r>`.

I have the following bind in my config to paste registers in the term with `<A-r>` (since I’m using `<C-r>` for command history):
```lua
vim.keymap.set("t", "<M-r>", [['<C-\><C-N>"'.nr2char(getchar()).'pi']], { expr = true })
```

**Comment by ibhagwan** [comment]
If you wish to have `<C-r>` to paste registers **only within fzf-lua** you can use the `on_create` event:
```lua
fzf_lua.setup({
  winopts = {
    on_create = function()
      vim.keymap.set("t", "<C-r>", [['<C-\><C-N>"'.nr2char(getchar()).'pi']], { expr = true, buffer = true})
    end
  }
})
```

**Comment by GreenSleeper** [comment]
I'll try it, thank you.
