### ISSUE TITLE
Is there a way to filter out some colorschemes?

### ISSUE THREAD

**Issue by Einenlum** [ibhagwan/fzf-lua#810]
### Info

- Operating System: Manjaro Linux, 23.0
- Shell: Zsh
- Terminal: Kitty
- `nvim --version`: 0.9.0
- `fzf --version`: 0.40.0

### Description 

First, thank you so much for your work. This plugin is amazing. I use it everyday and I love it :heart:!

I just have a simple question: is there a way to filter out some results when opening the list of colorschemes?

I never use some of the default ones that are ugly (like `blue`, `default` or `desert`) and I would rather filter them out than deleting them manually in my filesystem everytime I update neovim.

Thank you really much for your help.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/758d4ddb2a9447f21a8dc60799e57a9592edd170

@Einenlum, update to the latest commit and set `colorschemes.ignore_patterns`  in your `setup`, can also be called directly:
```lua
:= require("fzf-lua").colorschemes({ ignore_patterns = { "^delek$" , "^blue$" } })
```
Note that the matching is performed using lua's `string.match` so using the pattern `blue` will exclude all names that cotnain `blue`.

Lua patterns are very similar to regex, for more info [read this](https://fhug.org.uk/kb/kb-article/understanding-lua-patterns/).

**Comment by Einenlum** [comment]
Wow, I didn't expect such a quick answer and even an implementation!

It works amazingly. Exactly what I needed.
You rock, @ibhagwan. Thank you so much :heart: !

**Comment by ibhagwan** [comment]
Yw @Einenlum and ty for the kinds words :)
