### ISSUE TITLE
Need help on working with dap

### ISSUE THREAD

**Issue by bestdax** [ibhagwan/fzf-lua#811]
I setup neovim with dap after some search on website.

```lua
dap.configurations.cpp = {
    {
        name = "Launch",
        type = "codelldb",
        request = "launch",
        program = function()
            return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/",
                                "file")
        end,
        cwd = "${workspaceFolder}",
        stopOnEntry = false,
        args = {},
        runInTerminal = true
    }
}
```

When I start to debug, I need to input the executable path manually. Can I get it from a fzf-lua search?

**Comment by bestdax** [comment]
hi, many thanks for your response and very detailed instructions for my question.

I put the below code in my nvim configuration:
```lua
-- bind it to F1
keymap("n", "<F1>", function()
    local dap, dapui = require("dap"), require("dapui")
    require'fzf-lua'.files({
        -- I choose `find` command here, `fd` respects .gitignore by default and the build folder is included in it.
        -- I found I cannot use `find .  -executable -type f` here
        cmd = 'find .',
        actions = {
            ['default'] = function(selected)
                dap.configurations.cpp = {
                    {
                        name = "Launch",
                        type = "codelldb",
                        request = "launch",
                       -- change to square brackets
                        program = selected[1],
                        cwd = "${workspaceFolder}",
                        stopOnEntry = false,
                        args = {},
                        runInTerminal = true
                    }
                }
                -- run DAP
                dapui.open()
                dap.continue()
            end
        }
    })
end, silent_opts)
```

But I got this:
<img width="2240" alt="截屏2023-07-09 09 11 20" src="https://github.com/ibhagwan/fzf-lua/assets/22925996/88145996-952b-4101-99d3-ff4ec15c030c">

What the possible cause here?

**Comment by bestdax** [comment]
In the error info, I found there are some spaces in the path. I had tried to trim the selected[1], but the result is the same.

**Comment by ibhagwan** [comment]
> In the error info, I found there are some spaces in the path. I had tried to trim the selected[1], but the result is the same.

If you have icons enabled (default) the selected item contains the icon and padding, you can either disable icons with:
```lua
require'fzf-lua'.files({
       git_icons = false,    
       file_icons = false,
       cmd = 'find .',
```
Or extract the file using utilities using `require'fzf-lua'.path.entry_to_file(selected[1]).path`

**Comment by ibhagwan** [comment]
> I found I cannot use `find .  -executable -type f` here

Just tried and I see no issues with this command, what was the issue for you?

**Comment by bestdax** [comment]
Many thanks for your help, now it works.

I paste the solution here in case someone else needs it.

```lua
keymap("n", "<F1>", function()
    local dap, dapui = require("dap"), require("dapui")
    require'fzf-lua'.files({
        cmd = 'find .',
        actions = {
            ['default'] = function(selected)
                dap.configurations.cpp = {
                    {
                        name = "Launch",
                        type = "codelldb",
                        request = "launch",
                        program = require'fzf-lua'.path.entry_to_file(selected[1]).path,
                        cwd = "${workspaceFolder}",
                        stopOnEntry = false,
                        args = {},
                        runInTerminal = true
                    }
                }
                -- run DAP
                dapui.open()
                dap.continue()
            end
        }
    })
```

If I try `find . -executable -type f` I got this:
<img width="2240" alt="截屏2023-07-09 10 23 41" src="https://github.com/ibhagwan/fzf-lua/assets/22925996/705458a3-c81a-447e-b488-07d54168ee5c">

**Comment by ibhagwan** [comment]
> If I try `find . -executable -type f` I got this:

If you close the preview with `<F4>` you'd see the complete error message probably is `[unknown primary or operator]`, most likely because your local find version doesn't support it, that means you're probably using POSIX find, `-executable` is a feature of GNU find).

I highly recommend installing [`fd`](https://github.com/sharkdp/fd) for a better `find` utility, you can then use `fd -t x` to find all executable files.

This issue seems to be concluded, closing.

**Comment by nyngwang** [comment]
@bestdax I know this is unrelated but what's the colorscheme you used in the images?

**Comment by bestdax** [comment]
> @bestdax I know this is unrelated but what's the colorscheme you used in the images?

```lua
    use "NLKNguyen/papercolor-theme"
    use "vim-airline/vim-airline"
    use "vim-airline/vim-airline-themes"
```

It's papercolor with airline.

**Comment by nyngwang** [comment]
@bestdax Thank you good elephant <3

**Comment by miroshQa** [comment]
My solution:
```lua
dap.configurations.rust = {
  {
    name = 'Launch',
    type = 'lldb',
    request = 'launch',
    program = function()
      local co = coroutine.running()
      require("fzf-lua").files({
        cmd = "find .",
        git_icons = false,
        file_icons = false,
        actions = {
          default = function(selected)
            coroutine.resume(co, selected[1])
          end
        }
      })
      return coroutine.yield()
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},
  }
}

```

**Comment by ibhagwan** [comment]
From my config for picking exe / process/
https://github.com/ibhagwan/nvim-lua/blob/6bfeff4476e76919f9da1f00a20c05e246b34f23/lua/utils.lua#L428-L504

**Comment by miroshQa** [comment]
> From my config for picking exe / process/ https://github.com/ibhagwan/nvim-lua/blob/6bfeff4476e76919f9da1f00a20c05e246b34f23/lua/utils.lua#L428-L504

thanks for sharing :)

Also, I just found out that there are require("dap.utils").pick_file and pick_process, which use vim.ui.select. So, it’s enough to just use require("fzf-lua").register_ui_select() and then use the DAP utils.

**Comment by ibhagwan** [comment]
> Also, I just found out that there are require("dap.utils").pick_file and pick_process, which use vim.ui.select. So, it’s enough to just use require("fzf-lua").register_ui_select() and then use the DAP utils.

True,  although I wanted a bit more control so I made my own, just needed to figure out the coroutine and dap.ABORT.
