### ISSUE TITLE
fzf error 1: ^[i

### ISSUE THREAD

**Issue by 7c78** [ibhagwan/fzf-lua#812]
Hi, does anyone encounter this error

1. Open a dialog, e.g., `:Fzflua files`, etc.
2. Enter something to the search box so that there are no results.
3. Close the dialog, e.g., hit Enter, or Esc, or ctrl-c, etc

![image](https://github.com/ibhagwan/fzf-lua/assets/42330300/e6ab2dbb-e098-493a-b626-f2c912c1c54b)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/d04bbd91d2d96869071d965564aae34cae103ca1

Ty @7c78, there code was testing for the existence of an error message for an old obscure case using `sk` when the exit code was 1 which isn't an error with fzf, simply means "no match", the code was unnecessary and was removed.

**Comment by 7c78** [comment]
Thank you.
