### ISSUE TITLE
[Bug] Preview window loses current winopts after WinResized event

### ISSUE THREAD

**Issue by mikesmithgh** [ibhagwan/fzf-lua#813]
### Info

- Operating System: `MacOS 13.4.1`
- Shell: `Bash`
- Terminal: `Kitty`
- `nvim --version`: `NVIM v0.10.0-dev-613+gdb590e96d`
- `fzf --version`: `0.42.0 (brew)`

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
The preview window winopts appears to lose its settings during the WinResized event.

Steps to reproduce:
- Open `mini.sh`
- `<C-p>` (find files)
- Resize the terminal (in my case use the mouse to resize Kitty)

Expected: Fzf-lua handles resize and keeps current preview settings
Actual: Fzf-lua refreshes and preview loses some window settings (in my case, line numbers are removed)

Demo:

https://github.com/ibhagwan/fzf-lua/assets/10135646/c32b244d-a671-4041-ae9d-2dbdb006641e

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/46c83731c43ff863ada526220d54a6350a6369ba

Ty for the repot @mikesmithgh, I recently made refactoring of the window code and this was missed, should work with the latest commit.

**Comment by mikesmithgh** [comment]
> https://github.com/ibhagwan/fzf-lua/commit/46c83731c43ff863ada526220d54a6350a6369ba
> 
> 
> 
> Ty for the repot @mikesmithgh, I recently made refactoring of the window code and this was missed, should work with the latest commit.

🏃‍♂️that was fast! Thanks, I'll leave a comment later when I check 🙂

**Comment by mikesmithgh** [comment]
> > https://github.com/ibhagwan/fzf-lua/commit/46c83731c43ff863ada526220d54a6350a6369ba
> > 
> > 
> > 
> > Ty for the repot @mikesmithgh, I recently made refactoring of the window code and this was missed, should work with the latest commit.
> 
> 🏃‍♂️that was fast! Thanks, I'll leave a comment later when I check 🙂

Confirmed fixed 👍

**Comment by ibhagwan** [comment]
> > > [46c8373](https://github.com/ibhagwan/fzf-lua/commit/46c83731c43ff863ada526220d54a6350a6369ba)
> > > Ty for the repot @mikesmithgh, I recently made refactoring of the window code and this was missed, should work with the latest commit.
> > 
> > 
> > 🏃‍♂️that was fast! Thanks, I'll leave a comment later when I check 🙂
> 
> Confirmed fixed 👍

Ty @mikesmithgh!
