### ISSUE TITLE
extra spaces in buffers picker

### ISSUE THREAD

**Issue by gennaro-tedesco** [ibhagwan/fzf-lua#814]
### Info
- `nvim --version: NVIM v0.10.0-dev-653+gfbeef0d4e-Homebrew`
- `fzf --version: 0.42.0 (brew)`

- [x ] The issue is reproducible with `mini.sh`

### Description 

The buffers picker contains extra spaces between buffer ids (on the left) and name (on the right): see screenshot below reproduced with `mini.sh`. In particular notice the space between `[1] <-----> %`.

<img width="443" alt="Screenshot 2023-07-10 at 12 35 58" src="https://github.com/ibhagwan/fzf-lua/assets/15387611/07c6b0fd-43c2-4c8b-bb3c-f18f3c42f434">

I have noticed it after one of the latest commits, but I have not managed to figure out which one in particular (I do not remember this to ever be the case before, or am I wrong)? The files picker, on the other hand, looks fine (namely no extra spaces between the left and the right sides).

**Comment by ibhagwan** [comment]
Hi @gennaro-tedesco, this change was on purpose as I noticed buffer numbers weren’t aligning if you had a long session and buffer numbers cross the 99 and 999 boundaries.

I’ll think of a solution to make buffer numbers dynamically aligned based on the highest buffer number.

**Comment by gennaro-tedesco** [comment]
I wonder, are buffers numbers needed to show at all in a fuzzy picker? 🤔 

However I understand the purpose of the change, so do not worry too much if you cannot find any way around!

**Comment by ibhagwan** [comment]
You can always hide the buffer numbers with:
```lua
:lua require("fzf-lua").buffers({fzf_opts={["--delimiter"]="' '",["--with-nth"]="-1.."}})
```

> However I understand the purpose of the change, so do not worry too much if you cannot find any way around!

Virtually no chance of that happening, its just feeding the  right formatting alignment to `string.format` :)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/4dea46a7c61ff9f3ac3f77e2226312d50565b67d - should do what you want, @gennaro-tedesco.

**Comment by gennaro-tedesco** [comment]
Great, thank you as always!
