### ISSUE TITLE
Display Values

### ISSUE THREAD

**Issue by ibrokemypie** [ibhagwan/fzf-lua#815]
Question, not a bug, how would I go about having different display values in a picker from the actual value fed into actions? Context is I am moving over from Telescope as it got too slow, and am trying to rewrite a project picker for projections.nvim. What I want is entires looking like 
![image](https://github.com/ibhagwan/fzf-lua/assets/7827846/9f75c284-348c-4a2a-9efb-eb3831cd0fdd)
in the picker but instead I get 
![image](https://github.com/ibhagwan/fzf-lua/assets/7827846/e6aceba4-86c4-411e-b6be-29992cead1d0)

The action needs this full path to function, but I want the short path to be displayed.

I tried using `opts.fn_transform` for it as it seemed to do what I wanted (run a function on an entry before display) but it doesnt seem to get run, I have since read elsewhere its only for parsing shell commands?

I also tried passing in a table of tables to fzf_exec, assuming that the value being passed to actions being a table meant that I could do that, and display the first element but act on the second, but when I tried that I get this traceback
```
E5108: Error executing lua: ...odle/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:32: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...odle/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:32: in function 'contents_from_arr'
        ...odle/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/core.lua:82: in function 'fzf_exec'
        /home/noodle/.config/nvim/lua/utils.lua:183: in function </home/noodle/.config/nvim/lua/utils.lua:164>
```

I have scoured the wiki the readme and the github issues and at this point I am stumped. What is the correct way to do this?

**Comment by ibhagwan** [comment]
Can you share more details on what is providing you with the paths from projections? Is it a shell command? A simple table?

Unless you’re using an external shell command I don’t see why you’d need to use `fn_transform`? If you’re getting back a simple table from projections you can craft the entries yourself and pass it directly to `fzf_exec`, you can beautify the path (shortening is something else in Fzf-lua’s context) yourself or use `path.HOME_to_tilde`.

If you can paste your current WIP code I’ll be able to better help.

**Comment by rylee-randall** [comment]
Heres the WIP code at the moment, only the final two functions are specific to fzf-lua (the rest I use for my alpha startpage and elsewhere) but I have included them for the full context
```
M.get_projections_projects = function()
	local workspaces = require("projections.workspace").get_workspaces()
	local projects = {}

	for _, workspace in ipairs(workspaces) do
		for _, project in ipairs(workspace:projects()) do
			table.insert(projects, project)
		end
	end

	return projects
end

M.recent_projections_projects = function(number)
	if number == nil then
		number = 10
	end

	local get_session_filename = require("projections.session").session_filename
	local sessions_directory = require("projections.config").config.sessions_directory

	local projects = M.get_projections_projects()

	local function get_session_mod_time(project)
		-- gets the modified time of the project's session file

		local workspace_path = project["workspace"]["path"]
		local project_name = project["name"]

		local session_filename = get_session_filename(tostring(workspace_path), project_name)
		local session_file_path = tostring(sessions_directory .. session_filename)
		local session_mod_time = vim.fn.getftime(session_file_path)

		return session_mod_time
	end

	local function compare_projects(project1, project2)
		-- compares the modification time of two project sessions

		return get_session_mod_time(project1) > get_session_mod_time(project2)
	end

	table.sort(projects, compare_projects)

	local returned_projects = {}
	for _, project in ipairs(projects) do
		if number ~= -1 and #returned_projects >= number then
			break
		end

		table.insert(returned_projects, project)
	end

	return returned_projects
end

M.recent_projections_sessions = function(number)
	local projects = M.recent_projections_projects(number)

	local sessions = {}
	for _, project in ipairs(projects) do
		local session = tostring(project["workspace"]["path"]) .. "/" .. project["name"]
		table.insert(sessions, session)
	end

	return sessions
end

M.fzf_projects = function(opts)
	local fzf_lua = require("fzf-lua")
	opts = opts or {}
	opts.prompt = "Projects> "
	opts.fn_transform = function(x)
		local icon = ""
		local icon_text = icon .. "  "
		local short_session = vim.fn.fnamemodify(x, ":~")

		vim.pretty_print(short_session)
		return short_session
	end

	opts.actions = {
		["default"] = function(selected, opts)
			local session = selected[1]
			require("projections.session").restore(session)
		end,
	}
	fzf_lua.fzf_exec(M.recent_projections_sessions(-1), opts)
end

return M
```

The reason for trying `fn_transform` was because at first I didn't realise it was specifically for shell commands, it looked like it was just to transform entries at display time (as it was being used in examples to change colours and such).  I am building my own table of strings, I just need to be able to have fzf-lua display the beautified string (tilde shortened, path greyed out, icon before entry, not sure if these are separate steps in fzf-lua though) while giving the entire string to the action to load the project.


Thanks for the help! Did not expect such a quick response!

**Comment by ibhagwan** [comment]
This code should do it, the assumption is that your functions are returning a an array pf paths similar to `_sessions`, you can use any terminal highlight for the icon or an exisiting neovim colorscheme highlight with `utils.ansi_from_hl`:
```lua
local fzf_lua = require("fzf-lua")

local _sessions = {
  "/home/bhagwan/.config/nvim",
  "/home/bhagwan/Sources/nvim/fzf-lua",
  "/home/bhagwan/Sources/nvim/fzf-lua.wiki",
  "/home/bhagwan/A Dir with spaces",
}

local M = {}

M.recent_projections_sessions = function(_)
  return _sessions
end

M.restore = function(session)
  print(string.format([[restoring "%s"]], session))
  print(string.format([[expanded path "%s"]], vim.fn.expand(session)))
end

M.fzf_projects = function(opts)
  opts = opts or {}
  opts.prompt = "Projects> "
  opts.actions = {
    ["default"] = function(selected, _)
      -- extract the session without the icon using a lua pattern
      local session = selected[1]:match("%s+(.*)")
      M.restore(session)
    end,
  }
  local contents = function(cb)
    for _, s in ipairs(M.recent_projections_sessions(-1)) do
      cb(string.format("%s  %s",
        fzf_lua.utils.ansi_codes.green(""),
        fzf_lua.path.HOME_to_tilde(s)))
    end
  end
  fzf_lua.fzf_exec(contents, opts)
end
```

The result:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/8ed53751-548d-4047-b5da-ca661f5b6626)

**Comment by ibrokemypie** [comment]
Works perfectly! Thank you so much for the help!

**Comment by ibhagwan** [comment]
> Works perfectly! Thank you so much for the help!

Ty for the update @ibrokemypie!
