### ISSUE TITLE
Support visual selection with git_bcommits

### ISSUE THREAD

**Issue by SanchayanMaity** [ibhagwan/fzf-lua#816]
### Info

- Operating System: Arch Linux
- Shell: foot
- Terminal: fish
- `nvim --version`: NVIM v0.10.0-dev-657+g19fb573ad
- `fzf --version`: 0.42.0 (d471067e)

### Description 

First of all, thank you for this very useful plugin. I have a request for enhancement.

Right now, `git_bcommits` does not seem to support visual selection. Passing along the line range selected to `git log` via the `-L` option would be immensely useful IMO. `fzf.vim` use to support this.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/c971938df1da66613d1c0ade288de3b33dae3187

@SanchayanMaity - try it out and lmk?

**Comment by ibhagwan** [comment]
> Thank you very much. One question. What is the expected mapping?
> 
> ```lua
> local remap   = vim.api.nvim_set_keymap
> local opts    = { noremap=true, unique=true, silent=true }
> remap({ 'x', 'v'}, '<Leader>fc', ':<C-U>FzfLua git_bcommits<CR>', opts)
> ```
> 
> If I try to use without the `<C-U>`, I get `E481: No range allowed`. Adding `<C-U>` still gives me the old behavior without the line range being considered, as `mode.mode` in `mode_is_visual` returns `false` as the mode is detected as `n`.
> 
> Do I miss something?

Interesting, I’ll check why that happens, my mapping uses `{ n, v }` and it works:
https://github.com/ibhagwan/nvim-lua/blob/dc8f8c5dbef1fad8c5e8523d20426c1e3a586c11/lua/plugins/fzf-lua/mappings.lua#L158

**Comment by ibhagwan** [comment]
Apparently using `:` exists visual mode, you should change your mapping to `<cmd>` instead, or use `vim.keymap.set` with a lua function, both the below work:
```lua
vim.api.nvim_set_keymap("x", "<Leader>gg", "<cmd>FzfLua git_bcommits<CR>",
  { noremap = true, unique = true, silent = true })

vim.keymap.set({ "x" }, "<Leader>gg", function() require("fzf-lua").git_bcommits() end,
  { noremap = true, unique = true, silent = true })
```

**Comment by SanchayanMaity** [comment]
> Apparently using `:` exits visual mode

Ah, I see, did not know that. Thank you very much. Works now.

**Comment by porridgewithraisins** [comment]
@ibhagwan 
How do we do this without needing to have a keymap? I do these sorts of things rarely and in general prefer to type out `Fzf git_<tab tab tab>` and run them.

I think it would be nice if there was another command git_brcommits (or whatever) that takes the _previous_ visual selection (equivalent of `gv`) and then runs the range `git log` query for that.

**Comment by ibhagwan** [comment]
> @ibhagwan How do we do this without needing to have a keymap? I do these sorts of things rarely and in general prefer to type out `Fzf git_<tab tab tab>` and run them.
> 
> I think it would be nice if there was another command git_brcommits (or whatever) that takes the _previous_ visual selection (equivalent of `gv`) and then runs the range `git log` query for that.

That’s an easy customization you can do for yourself in a few lines of code, this doesn’t need its own bind, I believe this should also work `:'<,'>FzfLua git_bcommits`.

**Comment by porridgewithraisins** [comment]
Running the command in a vim range doesn't work. I think this is because the code in the plugin checks if it is _currently_ visual mode when deciding whether to get the commits for the selected region or not, and `:'<,'>Fzf...` get's detected as command mode.

Anyway, I have a very small, hacky patch for this I keep around which seems to do the job for me for now (Can run `:Fzflua git_bcommits v=1`).

```patch
From 0520c47a9b8e5887cd2bd4ae06f7423eac234d51 Mon Sep 17 00:00:00 2001
From: Santhanam <me@santhanam.dev>
Date: Wed, 16 Oct 2024 22:36:40 +0530
Subject: [PATCH 1/1] local patches

---
 lua/fzf-lua/providers/git.lua | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/lua/fzf-lua/providers/git.lua b/lua/fzf-lua/providers/git.lua
index 4943bf4..b1979e4 100644
--- a/lua/fzf-lua/providers/git.lua
+++ b/lua/fzf-lua/providers/git.lua
@@ -135,20 +135,23 @@ M.bcommits = function(opts)
   -- optimized to prevent the duplicate call to `git rev-parse`
   -- but overall it's not a big deal as it's a pretty cheap call
   -- first 'git_root' call won't print a warning to ':messages'
   if not opts.cwd and not opts.git_dir then
     opts.cwd = path.git_root({ cwd = vim.fn.expand("%:p:h") }, true)
   end
   local git_root = path.git_root(opts)
   if not git_root then return end
   local file = libuv.shellescape(path.relative_to(vim.fn.expand("%:p"), git_root))
   local range
+  if opts.v then
+    vim.cmd [[norm gv]]
+  end
   if utils.mode_is_visual() then
     local _, sel = utils.get_visual_selection()
     range = string.format("-L %d,%d:%s --no-patch", sel.start.line, sel["end"].line, file)
   end
   if opts.cmd:match("[<{]file") then
     opts.cmd = opts.cmd:gsub("[<{]file[}>]", range or file)
   else
     opts.cmd = opts.cmd .. " " .. (range or file)
   end
   if type(opts.preview) == "string" then
@@ -175,20 +178,23 @@ M.blame = function(opts)
     return
   end
   -- See "bcommits" for comment
   if not opts.cwd and not opts.git_dir then
     opts.cwd = path.git_root({ cwd = vim.fn.expand("%:p:h") }, true)
   end
   local git_root = path.git_root(opts)
   if not git_root then return end
   local file = libuv.shellescape(path.relative_to(vim.fn.expand("%:p"), git_root))
   local range
+  if opts.v then
+    vim.cmd [[norm gv]]
+  end
   if utils.mode_is_visual() then
     local _, sel = utils.get_visual_selection()
     range = string.format("-L %d,%d %s", sel.start.line, sel["end"].line, file)
   end
   if opts.cmd:match("[<{]file") then
     opts.cmd = opts.cmd:gsub("[<{]file[}>]", range or file)
   else
     opts.cmd = opts.cmd .. " " .. (range or file)
   end
   if type(opts.preview) == "string" then
-- 
2.47.0
```

**Comment by SanchayanMaity** [comment]
Just to note, this is what I have and what works here.

```lua
vim.keymap.set('x', '<Leader>fc', '<cmd>FzfLua git_bcommits<CR>', opts)
```

**Comment by ibhagwan** [comment]
> Anyway, I have a very small, hacky patch for this which seems to do the job for me for now (Can run `:Fzflua git_bcommits v=1`).

Instead of hacking fzf-lua why don’t you create a user command instead that runs the below in the callback?
```lua
vim.cmd [[norm gv]]
require'fzf-lua'.git_bcommits()
```

**Comment by ibhagwan** [comment]
> Just to note, this is what I have and what works here.
> 
> ```lua
> vim.keymap.set('x', '<Leader>fc', '<cmd>FzfLua git_bcommits<CR>', opts)
> ```

I believe @porridgewithraisins wanted to run a ranted commit without a keymap.

**Comment by porridgewithraisins** [comment]
> > Anyway, I have a very small, hacky patch for this which seems to do the job for me for now (Can run `:Fzflua git_bcommits v=1`).
> 
> Instead of hacking fzf-lua why don’t you create a user command instead that runs the below in the callback?
> ```lua
> vim.cmd [[norm gv]]
> require'fzf-lua'.git_bcommits()
> ```

I wanted to continue running it like `Fzf git_bcommits` :-)
