### ISSUE TITLE
Hello; I use the lua require('fzf-lua').files() command and there is an error? How can I fix it?

### ISSUE THREAD

**Issue by whxcode** [ibhagwan/fzf-lua#818]
### Info

- Operating System: mac os m1
- Shell:
- Terminal: xterm
- `nvim --version`: 0.9.1
- `fzf --version`: 0.42.0

<img width="1398" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/44012914/911c8be7-9ac1-40da-91f1-9c649c035b79">

Below is my config file

<img width="747" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/44012914/8b103ec2-dafa-41b5-8d7e-52ffb454cc5c">

**Comment by ibhagwan** [comment]
Is it possible you’re using a nightly version of neovim? `get_lang` was only introduced recently, another user with this issue was able to solve it by upgrading to `0.9.1` official release.

**Comment by whxcode** [comment]
> Is it possible you’re using an older nightly version of neovim? `get_lang` was only introduced recently, another user with this issue was able to solve it by upgrading to `0.9.1` official release.

I upgraded to v.10.0 and the problem went away;
Thanks
