### ISSUE TITLE
`git-files` always uses `cwd` 

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#82]
The output of 

```
:lua require("fzf-lua").git_files({cwd = "~/.config/nvim"})`
```

is on the left and the output of 

```
:lua require("fzf-lua").files({cwd = "~/.config/nvim"})`
```

is on the right

<img width="1680" alt="Screen Shot 2021-09-01 at 1 55 04 PM" src="https://user-images.githubusercontent.com/1813121/131735572-0d991cbf-293d-44e7-9d32-fa4fab782a13.png">

The fzf picker content on the left is the content from the current folder that I'm in.

It appears that `require"fzf-lua".git_files` uses always uses current `cwd`. If I go to a non git directory and run `:lua require("fzf-lua").git_files({cwd = "~/.config/nvim"})` I get:

```
[Fzf-lua] fatal: not a git repository (or any of the parent directories): .git
Press ENTER or type command to continue
```

Also, the name of the file in the preview is not right is I pass in `cwd = "~/.config/nvim"` to `git_files`, but possibly fixing the above issue will resolve this too.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7b9fe4495e5777ea4f506778fab39dd6b304a0d4 added support for 'cwd' in all git providers (files, status, commits, branches).
