### ISSUE TITLE
Lag in "a" and "g" key input 

### ISSUE THREAD

**Issue by RaviRahar** [ibhagwan/fzf-lua#820]
### Description 
For some reason there is lag when I type "a" or "g". I tried it using default config too (by running just setup( ) function). I was able to narrow down lag of "a" to this:
```lua
                keymap = {
                    builtin = {
                        ["alt-h"]    = "toggle-help",
                        ["alt-f"]    = "toggle-fullscreen",
                    }
                 }
```
When I comment "toggle-help" and "toggle-fullscreen" lines, then the lag of "a" goes away. I have to comment both of them, commenting only one doesn't work. I still do not know why there is a lag in "g".

**Comment by ibhagwan** [comment]
Does this also happen with `min.sh`?

At first glance this strikes me as something related to your config terminal mode mappings, if you have another `tmap` definition that starts with a or g neovim has to wait and see what is your second keypress before the first one is sent.

**Comment by ibhagwan** [comment]
Ok, I just realized the issue in regards to `a`, your kepmap definitions are wrong, these are neovim keybind style definitions (not fzf), they should be defined as `<A-f>` and not `alt-f`:
```lua
                keymap = {
                    builtin = {
                        ["<A-h>"]    = "toggle-help",
                        ["<A-f>"]    = "toggle-fullscreen",
                    }
                 }
```

This should explain the `a` lag, as for the `g` lag I suspect your config has other terminal mappings that starts with `g`, you can check all terminal mappings by running `:tmap` or `:verb tmap`.

**Comment by ibhagwan** [comment]
It's also posssible you have a "global" `gxx` mappings (which also affect terminal buffers), use `:map g` to find the culprit.

**Comment by RaviRahar** [comment]
> It's also posssible you have a "global" `gxx` mappings (which also affect terminal buffers), use `:map g` to find the culprit.

Thank you very much. This was it. I forgot that terminal mode mappings would conflict with fzf. Can I unmap terminal mode mappings for just fzf buffer? The following does not work:

```vim
    " unmaps globally
    autocmd FileType fzf tunmap  <leader>to

    " mapped globally so cannot unmap with <buffer>
    autocmd FileType fzf tunmap <buffer>  <leader>to

    " two letter mapping, so delay occurs waiting for b
     autocmd FileType fzf tnoremap <buffer> gb gb

    " Does not work for some reason
     autocmd FileType fzf tnoremap <buffer> gb <Nop>
```

**Comment by ibhagwan** [comment]
The autocmds you posted should work, I have something similar myself, try creating a lua function callback and debug it this way:

> https://github.com/ibhagwan/nvim-lua/blob/d2292418dc5ace0c11dde1f54f28f64ac748bc47/lua/autocmd.lua#L7

```lua
local aucmd = vim.api.nvim_create_autocmd

local function augroup(name, fnc)
  fnc(vim.api.nvim_create_augroup(name, { clear = true }))
end

augroup("FzfLuaUnmap", function(g)
  aucmd("FileType",
    {
      group = g,
      pattern = "fzf",
      callback = function(e)
        -- will raise an exception if called with wrong args or mapping doesn’t exist
        vim.keymap.del("t", "<leader>to", { buffer = e.buf })
      end,
    })
end)
```
