### ISSUE TITLE
Fzf-lua & lazy.vim delay and window closing problem

### ISSUE THREAD

**Issue by m-fonseca** [ibhagwan/fzf-lua#821]
### Info

- Operating System: linux 
- Shell: zsh
- Terminal: kitty with tmux
- `nvim --version`:

```
 NVIM v0.9.1 
Build type: MinSizeRel            
LuaJIT 2.1.0-beta3            
                                         
   system vimrc file: "$VIM/sysinit.vim"    
  fall-back for $VIM: "/usr/share/nvim"  
                   
Run :checkhealth for more info
```

- `fzf --version`:

```
c7e41f53d235:~/.config/nvim# fzf --version   
0.42.0 (AlpineLinux)
```

Using the latest fzf-lua (19732fd)

- [ ] The issue is reproducible with `mini.sh`

### Description 
Hello!

So I'm experiencing a bug, but I'm not 100% convinced its a fzf-lua bug as I can't reproduce this problem with a minimal neovim.  Figured I'd post it though. I've been having a problem where whenever I exit a fzf window (by pressing escape), it takes a second or two to disappear.  While that's not ideal, the real problem is if I hit escape twice before the window disappears on its own, the window does not go away at all, and I have to close the window with <kbd>ctrl-w c</kbd>.

I noticed this on my personal setup, and still occurred it if I use the [lazyvim docker container](https://www.lazyvim.org/installation) with the minimal config with only fzf as an added plugin (it still pulls its regular suite of plugins though).

`~/.config/nvim/lua/plugins/fzf-lua.lua`
```lua

return {
 "ibhagwan/fzf-lua", 

 keys = function() 
   return {
    { "\\ff", "<cmd>FzfLua files<cr>", desc = "fzf File search" }
  } 
  end, 
}
```

If you have any insight into this, it would great.  Also, thank you for the plugin, its awesome!

**Comment by ibhagwan** [comment]
Ty for the kind words @m-fonseca.

It sounds like you have a mapping for `<Esc><Esc>` or something similar in your config.

Few questions:
(1) what does `:tmap <Esc>` return?
(2) while fzf-lua is open press `<C-\-n>` to exit to normal mode and then execute `:tmap <Esc>` - is the output different than (1)?
(3) what happens when you try to exit with `ctrl-q`?
(4) what happens when you try to exit with `ctrl-c`?

**Comment by m-fonseca** [comment]
This is indeed the problem.  This helped a lot.  I should have known better with that escape delay.  Thank you!

FYI, the mapping giving me problem comes from lazyvim itself. 

```
LazyVim/lua/lazyvim/config/keymaps.lua:
135 map("t", "<esc><esc>", "<c-\\><c-n>", { desc = "Enter Normal Mode" })
```
Removing this mapping also makes the exiting of fzf with <kbd>esc</kbd> nice and snappy again.

**Comment by ibhagwan** [comment]
Thanks for the update @m-fonseca!
