### ISSUE TITLE
Add configurable sort option for grep_curbuf

### ISSUE THREAD

**Issue by damanis** [ibhagwan/fzf-lua#822]
Just an idea inspired by Emacs consult+orderless.
Sort output of grep_curbuf to show find entries from current line below, then continue from top of buffer.

**Comment by ibhagwan** [comment]
The order is determined by the output of `rg`, take a look at the available sorting options in `man rg` and you can add the flag to `rg_opts`.

> show find entries from current line below, then continue from top of buffer.

This is most likely not possible with `grep_curbuf` since it’s the output of a shell command, these customizations requests are a better fit for `blines`.

**Comment by damanis** [comment]
May be for `blines`, but now there is no option, correct?

**Comment by ibhagwan** [comment]
> May be for `blines`, but now there is no option, correct?

Correct, no such option currently.

**Comment by ibhagwan** [comment]
@damanis, update to https://github.com/ibhagwan/fzf-lua/commit/c8ac34d03692eff4aae7f20ebdfcd0449700665a and use:
```lua
:lua require("fzf-lua").blines({ start = "cursor" })
```

Or:
```vim
:FzfLua blines start=cursor
```

**Comment by damanis** [comment]
@ibhagwan 
Great, thank you.
