### ISSUE TITLE
[Bug] keymaps() doesn't show visual keymaps

### ISSUE THREAD

**Issue by TroySigX** [ibhagwan/fzf-lua#824]
### Info

- Operating System: 6.4.3-arch1-2
- Shell: bash 5.1.16
- Terminal: Yakuake
- `nvim --version`: 0.9.1
- `fzf --version`: 0.42.0

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
vim.keymap.set('v', '<space>sw', require('fzf-lua').grep_visual)
```
</details>

### Description 
Using the command `require('fzf-lua').keymaps()` doesn't show visual mode keymaps

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/1bba731df46feb1751dca1632268aae41ed5ac15 - an oversight, should work now.

Ty for the report @TroySigX!
