### ISSUE TITLE
How to make search with live_grep / live_grep_glob case sensitive?

### ISSUE THREAD

**Issue by shmerl** [ibhagwan/fzf-lua#825]
I noticed that by default, live_grep commands are searching things in somewhat inconsistent manner case wise.

For example, file containing:

```
foo
BAR
```

`FzfLua live_grep_native` finds `foo`, but doesn't find `FOO`. However it finds `BAR` and `bar`.

One can control case insensitivity with `(?i)` in the expression, but there is no way to force case sensitivity in the same manner, so that leaves some things not accessible to limit within just the expression.

Using something like this directly works with case being insensitive by default (so using `(?i)` allows to relax things):

```
lua require'fzf-lua'.live_grep_native({ cmd = "rg --color=always --column" })
```

Is the above intended behavior for out of the box live_greps?

**Comment by shmerl** [comment]
Actually correction, I could force case sensitivity!

Using: `(?-i)`

But still, out of the box behavior of live_grep somewhat inconsistent.

**Comment by ibhagwan** [comment]
> Is the above intended behavior for out of the box live_greps?

That’s correct, you can use either `cmd` or `rg_opts`, same thing (the latter used only with binary auto-detect).

> I guess that answers how to control it, but still, out of the box behavior of live_grep is somewhat inconsistent.

Our of the box uses these options (`--smart-case`) which made sense for most users, customize it any way you want:
https://github.com/ibhagwan/fzf-lua/blob/1bba731df46feb1751dca1632268aae41ed5ac15/lua/fzf-lua/defaults.lua#L316-L317

Also important noting that the default glob uses case insensitive matching:
https://github.com/ibhagwan/fzf-lua/blob/1bba731df46feb1751dca1632268aae41ed5ac15/lua/fzf-lua/defaults.lua#L321

For case sensitive, add this to your `setup`:
```lua
  grep = {
    glob_flag = "--glob"
  }
```

**Comment by shmerl** [comment]
Ah, got it, thanks. I wasn't familiar with rg's `--smart-case`. Good to know.
