### ISSUE TITLE
man_pages reports "can't chown/unlink (null) Bad address" error

### ISSUE THREAD

**Issue by hongxuchen** [ibhagwan/fzf-lua#826]
### Info

- Operating System: Kernel: 5.19.0-41-generic arch: x86_64 bits: 64 Console: pty pts/0 Distro: Ubuntu 2.10 (Kinetic Kudu)
- Shell: zsh (running as root)
- Terminal: windows wezterm remote login with tmux
- `nvim --version`: 
NVIM v0.10.0-dev-36941942d
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
- `fzf --version`: 0.30.0 (2093667)

- [x] The issue is reproducible with `mini.sh`

### Description 
- `man_pages` provider reports `can't chown (null): Bad address` and `man: can't unlink (null): Bad address`. 
- No previewer for any man page entries.
![image](https://github.com/ibhagwan/fzf-lua/assets/843267/156b53a0-0e90-416e-994c-28ed5c5cfe8b)

Other information:
* https://github.com/ibhagwan/fzf-lua/issues/368 may be relevant but different.  `-c` is `--catman` and `man man` says `This option is not for general use and should only be used by the catman program.`. `mandb` exists but seems nothing relevant when I run `mandb` or `mandb --test`.

* When running `man -c <entry>` in the terminal, all the `<entry>` reports similar errors on `chown` and `unlink`. e.g.,
```bash
$ man strcpy
man: can't chown (null): Bad address
man: can't unlink (null): Bad address
strcpy.
```
* `man` comes from `man-db` debian package; which is https://man-db.gitlab.io/man-db/.
```bash
$ dpkg -S $(which man)
man-db: /usr/bin/man
$ man --version
man 2.10.2
```

**Comment by ibhagwan** [comment]
@hongxuchen, this error is not specific to fzf-lua, if you can’t run the command in the same manner in the shell fzf-lua obviously can’t do it either.

Fix the underlying issue and once man works from the shell fzf-lua will be able to display the command output as well.

**Comment by ibhagwan** [comment]
> But my "man" is preinatalled by&nbsp; Ubuntu/debian package manager, which should affect many other users. In addition, telescope man_files works perfectly fine.
> […](#)

Idk what command Telescope man runs, fzf-lua just outputs the terminal command, having this error in the shell is not normal and should be fixed which is probably the reason why there are no other issues about it from other Debian users.

Something is obviously wrong with your man install, once you fix that fzf-lua will work as well.

**Comment by hongxuchen** [comment]
> > But my "man" is preinatalled by  Ubuntu/debian package manager, which should affect many other users. In addition, telescope man_files works perfectly fine.
> > […](#)
> 
> Idk what command Telescope man runs, fzf-lua just outputs the terminal command, having this error in the shell is not normal and should be fixed which is probably the reason why there are no other issues about it from other Debian users.
> 
> Something is obviously wrong with your man install, once you fix that fzf-lua will work as well.

I tried another machine Debian Sid (Host: debian Kernel: 6.1.0-9-amd64 arch: x86_64 bits: 64 Console: pty pts/7 Distro: Debian) and preinstalled `man` (still from man-db, with newer version `2.11.2`) and there are similar errors when running `man -c man` (for sure, without `-c` arg `man man` works perfectly fine). 

I suppose other Debian/Ubuntu users will also be affected since I haven't done anything customization on man command.

May I know what's the equivalent command of running vanilla fzf when invoking `man_pages` within fzf-lua? And is there any way to invoke without `-c`?

**Comment by ibhagwan** [comment]
> > > But my "man" is preinatalled by  Ubuntu/debian package manager, which should affect many other users. In addition, telescope man_files works perfectly fine.
> > > […](#)
> > 
> > 
> > Idk what command Telescope man runs, fzf-lua just outputs the terminal command, having this error in the shell is not normal and should be fixed which is probably the reason why there are no other issues about it from other Debian users.
> > Something is obviously wrong with your man install, once you fix that fzf-lua will work as well.
> 
> I tried another machine Debian Sid (Host: debian Kernel: 6.1.0-9-amd64 arch: x86_64 bits: 64 Console: pty pts/7 Distro: Debian) and preinstalled `man` (still from man-db, with newer version `2.11.2`) and there are similar errors when running `man -c man` (for sure, without `-c` arg `man man` works perfectly fine).
> 
> I suppose other Debian/Ubuntu users will also be affected since I haven't done anything customization on man command.
> 
> May I know what's the equivalent command of running vanilla fzf when invoking `man_pages` within fzf-lua? And is there any way to invoke without `-c`?

From your post it seemed that the error was appearing when running `man <cmd>` (without `-c`)  in the shell:
> ```sh
>$ man strcpy
>man: can't chown (null): Bad address
>man: can't unlink (null): Bad address
>strcpy.
>```

This is an easy fix, see https://github.com/ibhagwan/fzf-lua#default-options
```lua
require'fzf-lua'.setup {
  previewers = {,
    man = {
      -- NOTE: remove the `-c` flag when using man-db
      -- replace with `man -P cat %s | col -bx` on OSX
      cmd  = "man %s | col -bx",
    }
}
```

**Comment by hongxuchen** [comment]
@ibhagwan OK, it works now. It seems the issue of `--catman/-c` or `catman` mandb issue of debian packaged man-db.

**Comment by hongxuchen** [comment]
> > @ibhagwan OK, it works now. It seems the issue of `--catman/-c` or `catman` mandb issue of debian packaged man-db.
> 
> Yes, as I wrote in the default options comments the `-c` should be removed when using mandb, I was confused since you posted terminal output of the command without using `-c` (in the OP) which made me believe your man command is broken.

Sorry I pasted the wrong command which cause the misconstruction.
