### ISSUE TITLE
Question: how to implement toggle fuzzy/regex search mode in live grep?

### ISSUE THREAD

**Issue by linrongbin16** [ibhagwan/fzf-lua#828]
Hi,
Would you please help teach me, what exactly is the fzf command line options that make live grep toggle between fuzzy and regex search with 1 single key `ctrl-g`?

I found the doc [switching-between-ripgrep-mode-and-fzf-mode](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode) in fzf, but it's still using two keys `ctrl-f` and `ctrl-r` to implement it:

```bash
#!/usr/bin/env bash

# Switch between Ripgrep launcher mode (CTRL-R) and fzf filtering mode (CTRL-F)
rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload($RG_PREFIX {q})+unbind(ctrl-r)" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --bind "ctrl-f:unbind(change,ctrl-f)+change-prompt(2. fzf> )+enable-search+rebind(ctrl-r)+transform-query(echo {q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f)" \
    --bind "ctrl-r:unbind(ctrl-r)+change-prompt(1. ripgrep> )+disable-search+reload($RG_PREFIX {q} || true)+rebind(change,ctrl-f)+transform-query(echo {q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r)" \
    --color "hl:-1:underline,hl+:-1:underline:reverse" \
    --prompt '1. ripgrep> ' \
    --delimiter : \
    --header '╱ CTRL-R (ripgrep mode) ╱ CTRL-F (fzf mode) ╱' \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    --bind 'enter:become(vim {1} +{2})'
```

I don't understand is: `ctrl-f` will unbind `change` and enable search, while `ctrl-r` will disable search and rebind `change`.
But when I want to implement this with 1 single key `ctrl-g`, it seems I cannot rebind `change` again?

**Comment by ibhagwan** [comment]
> Would you please help teach me, what exactly is the fzf command line options that make live grep toggle between fuzzy and regex search with 1 single key `ctrl-g`?

This is not possible with just fzf, fzf-lua saves the context (search options, cwd, query, etc) and restarts the fzf process altogether with different options.

**Comment by linrongbin16** [comment]
Oh, that's quite a lot of work! thanks for your reply!
