### ISSUE TITLE
Question: Can we replace Tmux's default `list-buffer` UI with the fzf-lua version?

### ISSUE THREAD

**Issue by erwin** [ibhagwan/fzf-lua#829]
I really like the fzf-lua tmux-buffers UI as you present it at the bottom of the SmartYank page under "Tmux".

I just wish I could make it the default even when my current window is some kind of shell rather than nvim.

I found this: https://github.com/sainnhe/tmux-fzf/blob/master/scripts/clipboard.sh that suggests maybe some customization is possible...

BTW, this and SmartYank are so awesome!

**Comment by ibhagwan** [comment]
Hi @erwin, perhaps it’s possible the code you sent suggests the possibility exists but

> I just wish I could make it the default even when my current window is some kind of shell rather than nvim.

Fzf-lua is a **neovim plugin** it doesn’t work unless you’re inside neovim.

If I didn’t understand your question properly please further clarify what you mean?

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if I misunderstood or you need more help.

**Comment by ibhagwan** [comment]
> Since many tmux commands can launch shell scripts, my thinking was perhaps it could launch neovim with the -c command to directly execute your fzf tmux buffer script, and then depending on the selection, your plugin could write that to stdout and exit neovim.

That would be horribly inefficient, there really isn’t much to this provider, you can just pipe `tmux list-buffers` into fzf and you’ll have the same interface via the shell without the neovim proxy.
