### ISSUE TITLE
git_commits/git_bcommits ... {1} do not work

### ISSUE THREAD

**Issue by fonghou** [ibhagwan/fzf-lua#831]
### Info

- Operating System: Linux debian
- Shell: bash
- Terminal: tmux
- `nvim --version`: 0.9.1
- `fzf --version`: 0.42.0

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
git_commits and git_bcommits do not work with {1}, works with `echo {1} | awk '{print $1}`  

```
      git = {
        commits = {
          preview = "git show --pretty='%Cred%H%n%Cblue%an <%ae>%n%C(yellow)%cD%n%Cgreen%s' --color `echo {1} | awk '{print $1}'`",
        },
        bcommits = {
          preview= "git diff --color `echo {1} | awk '{print $1}'` -- <file>"
        },
      }
```

**Comment by ibhagwan** [comment]
I didn’t test this as I don’t have access to my computer ATM but you probably can’t use backtick for command outputs, can you try using `$(…)` instead?

```lua
      git = {
        commits = {
          preview = "git show --pretty='%Cred%H%n%Cblue%an <%ae>%n%C(yellow)%cD%n%Cgreen%s' --color $(echo {1} | awk '{print $1}')",
        },
        bcommits = {
          preview= "git diff --color $(echo {1} | awk '{print $1}') -- <file>"
        },
      }
```

**Comment by fonghou** [comment]
$(...) works also!

**Comment by ibhagwan** [comment]
Not sure I understood the issue correctly, are you saying the default preview commands didn’t work and you had to use the echo/awk workaround instead?

If so, what is your bash version? Can you try with zsh/fish if installed?

**Comment by fonghou** [comment]
> Not sure I understood the issue correctly, are you saying the default preview commands didn’t work and you had to use the echo/awk workaround instead?

correct
![image](https://github.com/ibhagwan/fzf-lua/assets/13973254/14542122-67ea-4ed6-8364-e121a6c93b1c)

> 
> If so, what is your bash version? Can you try with zsh/fish if installed?
3

GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
zsh 5.9 (x86_64-debian-linux-gnu)

Same issue with both. I don't have fish installed. 

I don't think the issue itself has anything to do with shell. fzf.lua git_commit  "cmd" uses --pretty-formt '%h...' plus other stuff, hence {1} output cannot be used in preview command as-is.

**Comment by ibhagwan** [comment]
> I don't think the issue itself has anything to do with shell. fzf.lua git_commit "cmd" uses --pretty-formt '%h...' plus other stuff, hence {1} output cannot be used in preview command as-is.

You’re probably right, then the question is what’s different in you setup which is making it fail and why does `$(echo {1} | awk '{print $1}')` work?

can you change the preview to just `echo {1}` and take a screenshot of what appears in the preview?

I’m thinking this has something to do with your `$FZF_DEFAULT_OPTS` containing a `--delimiter` flag, can you also post the output of `:lua print(vim.env.FZF_DEFAULT_OPTS)`?

**Comment by ibhagwan** [comment]
You can also try this:
```lua
      git = {
        commits = {
          fzf_opts = { ["delimiter"] = '[ ]' },
        },
        bcommits = {
          fzf_opts = { ["delimiter"] = '[ ]' }
        },
      }
```

**Comment by fonghou** [comment]
works with minor fixes.

```
      git = {
        commits = {
          fzf_opts = { ["--delimiter"] = "'[ ]'" },
        },
        bcommits = {
          fzf_opts = { ["--delimiter"] = "'[ ]'" }
        },
      }
```

**Comment by fonghou** [comment]
> > I don't think the issue itself has anything to do with shell. fzf.lua git_commit "cmd" uses --pretty-formt '%h...' plus other stuff, hence {1} output cannot be used in preview command as-is.
> 
> You’re probably right, then the question is what’s different in you setup which is making it fail and why does `$(echo {1} | awk '{print $1}')` work?
> 
> can you change the preview to just `echo {1}` and take a screenshot of what appears in the preview?
> 
> I’m thinking this has something to do with your `$FZF_DEFAULT_OPTS` containing a `--delimiter` flag, can you also post the output of `:lua print(vim.env.FZF_DEFAULT_OPTS)`?

You are absolutely correct. Thanks for your help!

**Comment by ibhagwan** [comment]
> works with minor fixes.

Oh yes, I forgot about the shell escape as I’m writing this from a mobile device :)

> You are absolutely correct. Thanks for your help!

You’re welcome and ty for the update!
