### ISSUE TITLE
skip unreadable files in oldfiles

### ISSUE THREAD

**Issue by p00f** [ibhagwan/fzf-lua#834]
### Info

- Operating System: Arch Linux
- Shell: fish
- Terminal: wezterm
- `nvim --version`:
    NVIM v0.10.0-dev
    Build type: Release
    LuaJIT 2.1.0-beta3
    Run "nvim -V1 -v" for more info
- `fzf --version`: 0.42.0 (d471067e)

- [x] The issue is reproducible with `mini.sh`

### Description 
When I edit files owned by root using `doas`, they appear in my oldfiles even though my user can't do anything with them
If I move the cursor to such a file, I get `[Fzf-lua] Unable to open file '/etc/doas.conf', error: EACCES: permission denied: /etc/doas.conf` and the preview window shows the previously selected file.

The fix is simple:
```diff
diff --git a/lua/fzf-lua/providers/oldfiles.lua b/lua/fzf-lua/providers/oldfiles.lua
index 8c9624f..7ab053d 100644
--- a/lua/fzf-lua/providers/oldfiles.lua
+++ b/lua/fzf-lua/providers/oldfiles.lua
@@ -53,7 +53,7 @@ M.oldfiles = function(opts)
       -- local start = os.time(); for _ = 1,10000,1 do
       for _, file in ipairs(vim.v.oldfiles) do
         local fs_stat = not opts.stat_file and true or vim.loop.fs_stat(file)
-        if fs_stat and file ~= current_file and not sess_map[file] then
+        if fs_stat and file ~= current_file and not sess_map[file] and vim.fn.filereadable(file) == 1 then
           add_entry(file, co)
         end
       end
```

**Comment by ibhagwan** [comment]
Ty for the report @p00f!

I think this can be further reduced to just testing for `vim.fn.filereadable(file) == 1` as this makes the call to `vim.loop.fs_stat` redundant, don’t you think?

**Comment by p00f** [comment]
Yeah sure
