### ISSUE TITLE
Perform live_grep on previous results

### ISSUE THREAD

**Issue by abenz1267** [ibhagwan/fzf-lua#836]
Hi,

this is not exactly an issue, more of a workflow "problem" i can't solve right now:

Is it somehow possible to do this:

1. first find files based on live_grep
2. perform 2nd live_grep search on the result of 1.

Is this possible somehow?

Regards

**Comment by ibhagwan** [comment]
Yes it’s possible, you’ll need to craft a new rg command using the last search query and use it as the new `cmd`.

Say I just searched for `foo`, you can now run live grep with this `cmd`:
```lua
live_grep({ cmd = 'rg …<opts>… “foo” | rg … <opts>' })
```

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if you need more help.
