### ISSUE TITLE
allow fzf_bin to be a function

### ISSUE THREAD

**Issue by p00f** [ibhagwan/fzf-lua#839]
I understand "just add an option lol" requests can be annoying, please just hear me out:

I use https://git.sr.ht/~whynothugo/darkman to toggle dark mode system-wide

The default fzf theme is dark which looks bad in light mode:
![image](https://github.com/ibhagwan/fzf-lua/assets/36493671/756db752-ca17-47c9-8360-62ca1f9533a1)

I use the following in fish:
```fish
function fzf --wraps fzf
    if test $DARK_MODE = true
        command fzf --color=dark $argv
    else
        command fzf --color=light $argv
    end
end
```

If fzf_bin is a function, I can check the `background` option to do something similar for fzf-lua

**Comment by ibhagwan** [comment]
Unfortuntaely that is not going to work as `fzf_bin` is just the binary, even if I make it accept a function, it cannot contain args like `--color`.

What if you wrap your fzf-lua binds in a lua function that can conditionally add `--color.=...` to `fzf_cli_args`?

**Comment by p00f** [comment]
That would be fine, thanks
