### ISSUE TITLE
[Question] Custom function fzf-lua cWORD

### ISSUE THREAD

**Issue by hattori-hanz0** [ibhagwan/fzf-lua#841]
Hi, I want to write my own function similar to live_grep

```lua
function fzf_lua_grep(opts)
    if not opts then opts = {} end
    local action = require("fzf-lua.shell").action(function(selected)
        for _, e in ipairs(selected) do
            local file = require'fzf-lua'.path.entry_to_file(e)
            vim.cmd("tabnew " .. file.path)
        end
    end, "{+}")
    opts.actions = { ["ctrl-y"] = false }
    opts.fzf_cli_args  = ("--bind=ctrl-y:execute-silent:%s"):format(action)
    require'fzf-lua'.live_grep(opts)
end
```

Regards

**Comment by ibhagwan** [comment]
Can you share more about your end goal?

why not use the `fzf_live` API directly?

https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-live-api

**Comment by ibhagwan** [comment]
Btw, whatever it is you want to do there are way easier ways to write this function, the `actions` table is there for a reason, you don’t need to use `shell.action` and `execute-silent` directly.

**Comment by hattori-hanz0** [comment]
I want the `GrepDocsDir` function to search for words under the cursor in the 'docs' directory

```lua
GrepDocsDir = function(opts) 
    local cwd_dir = "$HOME/.config/nvim/docs"
    local prompt = "Docs> "
    local rg_cmd = "rg -g '*.md'"
    fzf_lua_grep_cWORD({ prompt = prompt, cmd = rg_cmd, cwd = cwd_dir })
end
```

The keyboard shortcut works well, but I would prefer to use a function for this purpose

```lua
vim.keymap.set({ "n" }, "gm", [[<cmd>lua require("fzf-lua").grep_cWORD({ cwd = "$HOME/.config/nvim/docs" })<cr>]])
```

**Comment by ibhagwan** [comment]
> I want the GrepDocsDir function to search for words under the cursor in the 'docs' directory

I don’t understand, is the code for `GrepDocsDir` not working for you?

**Comment by hattori-hanz0** [comment]
This is an example of how I see it, but I don't know how to write a function to make it happen.  `fzf_lua_grep_cWORD`

**Comment by ibhagwan** [comment]
> This is an example of how I see it, but I don't know how to write a function to make it happen. `fzf_lua_grep_cWORD`

You were close:
```lua
_G.GrepDocsDir = function(opts) 
    local cwd_dir = "$HOME/.config/nvim/docs"
    local prompt = "Docs> "
    local rg_cmd = "rg -g '*.md'"
    require('fzf_lua').grep_cWORD({ prompt = prompt, cmd = rg_cmd, cwd = cwd_dir })
end
```
You can call it with `:lua _G. GrepDocsDir()`

**Comment by hattori-hanz0** [comment]
sorry, doesn't work

after opening the window, the searched word is displayed, but the line with the searched word doesn't appear in the preview window

when I press Enter, the file opens at the first line

**Comment by ibhagwan** [comment]
Can you add `debug = true` to the function arg table, close the preview with `F4` and post a screenshot?
I’d like to see the search term and the debug command

**Comment by hattori-hanz0** [comment]
https://i.imgur.com/H2tJ7LW.png

**Comment by hattori-hanz0** [comment]
Without `cmd = rg_cmd` it works ok

**Comment by hattori-hanz0** [comment]
I added the parameter --line-number, and now it's working.

```lua
local rg_cmd = "rg --line-number -g "*.md"
```

**Comment by ibhagwan** [comment]
> I added the parameter `--line-number`, and now it's working.

You can also add `- -column` and you’ll get a better indicator when the matched string starts, the complete default parameters are:
https://github.com/ibhagwan/fzf-lua/blob/77c24ecce152bc32c0e99620cab5d03309ed3438/lua/fzf-lua/defaults.lua#L316-L317

> BTW: Why you add _G to the begining of the function name?

I prefer to define the function as a member of the global `_G` variable rather than a global variable.
