### ISSUE TITLE
hoe to keep my input in prompt when switch search mode?

### ISSUE THREAD

**Issue by GreenSleeper** [ibhagwan/fzf-lua#842]
Currently when I enter `live_grep`, I'm in regex search mode and I can type in what I want to search for.
Then I'm not satisfied with the results I'm getting and I switch to fuzzy search but I can only continue to search for other stuff based on my input before.
Like below, if I search for `fzf-lua` in regex mode and I switch to fuzzy mode, I can only search within the results I got before.
![image](https://github.com/ibhagwan/fzf-lua/assets/95287687/d56f2e8f-5b65-4dcd-8381-cbcd54a3723e)

How can I start a new fuzzy search from the regex search mode without closing and opening the search window again?

**Comment by ibhagwan** [comment]
> How can I start a new fuzzy search from the regex search mode without closing and opening the search window again?

That’s the entire point of the `ctrl-g`, keep refining result sets, if you wish to start a new search add a new bind to `actions` table that calls `live_grep` with no parameters.

**Comment by GreenSleeper** [comment]
OK, ty
