### ISSUE TITLE
Enable full width split layout

### ISSUE THREAD

**Issue by mikehaertl** [ibhagwan/fzf-lua#843]
When using split layout e.g. with `winopts.split = 'belowright new'` the created window should use full width.

### Current behavior

```
require('fzf-lua').setup({
  'fzf-native',
  winopts = {
    split = "belowright new",
    preview = {
      horizontal = 'right:50%',
    },
  }
})
```

1. Start `nvim`
2. `:vsplit`
3. `:FzfLua files`

![image](https://github.com/ibhagwan/fzf-lua/assets/675062/71070bde-6e1e-4a5d-ab93-0d095c6e6109)

### Expected

Here's an example from fzf.vim how I would expect the layout:

![image](https://github.com/ibhagwan/fzf-lua/assets/675062/707d45ee-0e79-429f-a137-b24675fa5591)

**Comment by mikehaertl** [comment]
Ok, found it out:

```
winopts = {
    split = "botright new"
}
```

(See `:h :botright` or `:h :topleft`)

**Comment by ibhagwan** [comment]
Ty for the diligent wiki updates @mikehaertl!
