### ISSUE TITLE
live_grep_native() seems to ignore file_ignore_patterns?

### ISSUE THREAD

**Issue by vinoff** [ibhagwan/fzf-lua#844]
### Info

- Operating System: Arch
- Shell: Zsh
- Terminal: Wezterm 
- `nvim --version`: NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
- `fzf --version`: 0.42.0 (d471067e)

------

This is my config, using lazy.nvim

```
return {
    'ibhagwan/fzf-lua',
    -- optional for icon support
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
        -- calling `setup` is optional for customization
        require('fzf-lua').setup({
            winopts = {
                preview = { default = 'bat_native' },
            },
            file_ignore_patterns = { 'node_modules/.*', '.*%.jpg', '.*%.png', '.*%.gif', '.*%.jpeg' },
        })
    end,
}
```

This is my keymap:

`vim.keymap.set('n', '<c-f>', "<cmd>lua require('fzf-lua').live_grep_native()<CR>", { silent = true })`

I am searching (C-p) on a folder with node-modules and it is finding content in that folder.. Shouldn´t file_ignore_patterns also apply to live_grep_native? It seems to apply to live_grep though..

**Comment by ibhagwan** [comment]
That is by design, the native version does zero processing and sends the command output  directly into fzf, processing the command output via the lua filters would nullify the performance gains of the native version.

Closest thing you can do is use the non native version disable file and git icons.

**Comment by vinoff** [comment]
Oh, I see..

Which do you thing is more performant?

native version (as is) or non-native version with file_ignore_patterns and file and git icons disabled?

**Comment by ibhagwan** [comment]
native will **always be more performant** as it doesn’t need to do any processing the command output is piped directly into fzf via the shell (more accurately `$FZF_DEFAULT_COMMAND`) with (2) having to pass the output through another neovim headless process with lua code, even if not by much the extra step does in fact have a cost.

That said, fzf-lua is very finely optimized and most likely you won’t notice the difference either way, just try it.

Keep in mind the most optimized way to filter is via `rg_opts`, that way you can use globs using `-g` and filter out certain patterns at the `rg` level.

**Comment by vinoff** [comment]
Alright, I will keep using the native then, though it does annoy me seeing all the node_modules being searched.

I will close this. Thank you for the great plugin and for the very prompt replies! You are awesome @ibhagwan!

**Comment by vinoff** [comment]
> > Alright, I will keep using the native then, though it does annoy me seeing all the node_modules being searched.
> > I will close this. Thank you for the great plugin and for the very prompt replies! You are awesome @ibhagwan!
> 
> Why don’t you use native and add node module filters to rg_opts?

Oh sorry, I missread. I thought that wouldn´t work for native. I just did  that, thank you! For posterity sake, here is my config, if anyone ever comes searching:

```
return {
    'ibhagwan/fzf-lua',
    -- optional for icon support
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
        -- calling `setup` is optional for customization
        require('fzf-lua').setup({
            winopts = {
                preview = { default = 'bat_native' },
            },
            file_ignore_patterns = { 'node_modules/.*', '.*%.jpg', '.*%.png', '.*%.gif', '.*%.jpeg' },
            grep = {
                rg_opts = "--smart-case -g '!{.git,node_modules}/*'",
            },
        })
    end,
}

```

With this config though, when doing live_grep_native, I get` [bat error] invalid digit found in string`. This happens for ALL files, so it has nothing to do with the content of the file themselves. I read another issue that suggested adding `vim.env.FZF_LUA_NVIM_BIN = 'nvim'` to my config, which I did, but it didn´t fix the issue..

**Comment by vinoff** [comment]
Adding the whole thing seems to fix the issue.. What do you think is the error:
```

grep = {
    rg_opts = "--sort-files --hidden --column --line-number --no-heading " ..
              "--color=always --smart-case -g '!{.git,node_modules}/*'",
  }
```

**Comment by ibhagwan** [comment]
> What do you think is the error:

The error is due to your rg options missing line numbers and columns (`--column --line-number`) which then confuses the bat options which section of the file to display/highlight.

If you try again without these you’d see the results are just filenames without lines and columns of the matched string.
