### ISSUE TITLE
Default to noremap for config.actions

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#845]
Hello, there is a small problem with the way the actions are created at the moment, i think, looking at the impl, that these actions do not fallback to noremap, maybe there is a reason. But having tried to bind to <C-w> a new action, i would like to still keep the original <C-w> and not recursively remap it, which i have bound to <M-bs>. Example below with c-w bound in actions, the M-bs actually triggers the c-w action from the config.

```lua
        actions = {
            files = {
                ["ctrl-t"] = actions.file_tabedit,
                ["ctrl-w"] = actions.file_winedit,
            },
            buffers = {
                ["ctrl-t"] = actions.file_tabedit,
                ["ctrl-w"] = actions.file_winedit,
            },
        },

    vim.api.nvim_create_autocmd({ "FileType" }, {
        pattern = "fzf",
        callback = function(args)
            local opts = { noremap = true, silent = true, buffer = args.buf }
            vim.keymap.set("t", "<M-d>", "<S-Right><C-w>", opts)
            vim.keymap.set("t", "<M-BS>", "<C-w>", opts)
        end,
        desc = "Picker readline keys and keybind mappings",
    })
```

**Comment by ibhagwan** [comment]
Actions aren’t mapped via neovim, using an action means fzf is expecting that keybind and will close the interface when pressing that bind, fzf will then print the bind to terminal and fzf-lua will parse the bind and decide what to do.

**Comment by ibhagwan** [comment]
Btw, there are still open items in #779, if it isn’t an issue any longer let me know and I’ll close it.

**Comment by asmodeus812** [comment]
> Actions aren’t mapped via neovim, using an action means fzf is expecting that keybind and will close the interface when pressing that bind, fzf will then print the bind to terminal and fzf-lua will parse the bind and decide what to do.
> 
> If you wish to disable an action “bind” (not a really a neovim bind) - set it’s action table value to `false`.

So actions.files or buffers, are not mapped from neovim, how is the lua callback we set to those getting called then ?

**Comment by ibhagwan** [comment]
> > Actions aren’t mapped via neovim, using an action means fzf is expecting that keybind and will close the interface when pressing that bind, fzf will then print the bind to terminal and fzf-lua will parse the bind and decide what to do.
> > If you wish to disable an action “bind” (not a really a neovim bind) - set it’s action table value to `false`.
> 
> So actions.files or buffers, are not mapped from neovim, how is the lua callback we set to those getting called then ?

Fzf will return the pressed keybind in the terminal (as text), it will then be parsed by:
https://github.com/ibhagwan/fzf-lua/blob/fe649a0d042e68d5810c9da8045560e885a705d7/lua/fzf-lua/actions.lua#L56-L79

**Comment by ibhagwan** [comment]
FYI, fzf-lua uses `--expect` to differentiate the keybind that was pressed, from `man fzf`:
```man
       --expect=KEY[,..]
              Comma-separated list of keys that can be used to complete fzf in
              addition to the default enter key. When this option is set, fzf
              will print the name of the key pressed as the first line of its
              output (or as the second line if --print-query is also used).
              The line will be empty if fzf is completed with the default
              enter key. If --expect option is specified multiple times, fzf
              will expect the union of the keys. --no-expect will clear the
              list.
```

The important part:
>When this option is set, fzf will print the name of the key pressed as the first line of its output (or as the second line if `--print-query` is also used).

**Comment by asmodeus812** [comment]
Okay well the action is still being executed by fzf-lua anyhow, is there a way to achieve what i was going for then ? Having C-w work as it does, as a readline binding which deletes word backward, retain that action and bind it to Alt-Bs, but still have the C-w execute the action with the current fzf lua selection.

**Comment by asmodeus812** [comment]
I want to map C-w to execute an action, and Alt-Backspace to delete a word backward.

**Comment by ibhagwan** [comment]
You don't need the neovim mappings, keep the `ctrl-w` action mappings as they are and add this to your setup:
```lua
require("fzf-lua").setup({
  keymap = {
    fzf = {
      ["alt-bs"] = "backward-kill-word",
    }
  }
})
```

If this still doen't work check for conclicts in your `$FZF_DEFAULT_OPTS` because technically this mapping it's not required as it's the default, from `man fzf`:
```
   AVAILABLE ACTIONS:
       A key or an event can be bound to one or more of the following actions.

         ACTION:                      DEFAULT BINDINGS (NOTES):
           abort                        ctrl-c  ctrl-g  ctrl-q  esc
           accept                       enter   double-click
           accept-non-empty             (same as accept except that it
       prevents fzf from exiting without selection)
           backward-char                ctrl-b  left
           backward-delete-char         ctrl-h  bspace
           backward-delete-char/eof     (same as backward-delete-char except
       aborts fzf if query is empty)
           backward-kill-word           alt-bs
           backward-word                alt-b   shift-left
```

**Comment by asmodeus812** [comment]
Yes it is already provided by default, i was not aware, and went to a binding straight away. Can be closed.
