### ISSUE TITLE
ctrl-y doesnt yank the commit hash 

### ISSUE THREAD

**Issue by I-Own-You** [ibhagwan/fzf-lua#846]
### Info

- Operating System: arch linux
- Shell: zsh
- Terminal: kitty
- `nvim --version`: 0.9.1
- `fzf --version`:0.42

<h4> The lua config is the default one, with some changes for rg and fd to find hidden and ignored files.

### Description 
Hello best plugin in the world, i still use it 🍾 
But i did encounter a small issue 🤔 
ctrl-y keybind doesnt yank the commit hash in :FzfLua git_bcommits | git_commits

**Comment by ibhagwan** [comment]
Have you tried with `mini.sh`?
How are you pasting the register?
Can you press `ctrl-y` and then post a screenshot of `:FzfLua registers`?

**Comment by I-Own-You** [comment]
<h3>I have in my options:</h3>

```lua
vim.o.clipboard = "unnamedplus"
```
<p>and <i><b>wl-clipboard</b></i> package installed on my system, also i am using gnome on wayland.</p>

<h3>Output of the :FzfLua registers: </h3>

![Screenshot from 2023-08-13 15-29-16](https://github.com/ibhagwan/fzf-lua/assets/91146968/87ff3fa9-0d67-4dfe-ba5f-c55ae4b2b2b1)
)

<h3>Its 3 separate windws from kitty terminal, for convenience to see:</h3>

1. the commit hash yanked(on the left).
2. the :FzfLua registers from the upper right
3. the pasting result (the line pasted is the line i yanked from my options, and after that i yanked the commit hash)

**Comment by ibhagwan** [comment]
As you can see in the images you posted yourself it did work, both the unnamed register `”` and the yank register `0` contain the commit hash `9ef7a1c`.

At this point if I you press `p` in normal mode it should paste the commit hash at the cursor location.

Not sure what you mean by “pasting the result doesn’t work” - are you trying to paste outside of neovim using `cmd-v` or something?

**Comment by I-Own-You** [comment]
after i yank the commit hash, then i press 'p', it doesnt paste the commit hash, it pastes whatever i yanked before the commit hash, i can make a video, maybe you will better understand ?

**Comment by ibhagwan** [comment]
If you wish for the commit hash to enter the clipboard instead (`+` register), create your own custom action and yank into whatever register you want, the code is pretty simple:
https://github.com/ibhagwan/fzf-lua/blob/77c24ecce152bc32c0e99620cab5d03309ed3438/lua/fzf-lua/actions.lua#L571-L575

```lua
require'fzf-lua'.setup({
  commits = {
    actions = {
      ['ctrl-y'] = function(selected, _) 
        local commit_hash = selected[1]:match("[^ ]+") 
        vim.fn.setreg([[+]], commit_hash) 
      end 
    }
  }
})
```

**Comment by ibhagwan** [comment]
> after i yank the commit hash, then i press 'p', it doesnt paste the commit hash, it pastes whatever i yanked before the commit hash, i can make a video, maybe you will better understand ?

that’s because of your clipboard config, you’re attempting to pate from `+`, if you pressed `”0p` it would work.

**Comment by I-Own-You** [comment]
ok, i will try with your function to do something

> If you wish for the commit hash to enter the clipboard instead (`+` register), create your own custom action and yank into whatever register you want, the code is pretty simple:
> 
> https://github.com/ibhagwan/fzf-lua/blob/77c24ecce152bc32c0e99620cab5d03309ed3438/lua/fzf-lua/actions.lua#L571-L575
> 
> ```lua
> require'fzf-lua'.setup({
>   commits = {
>     actions = {
>       ['ctrl-y'] = function(selected, _) 
>         local commit_hash = selected[1]:match("[^ ]+") 
>         vim.fn.setreg([[+]], commit_hash) 
>       end 
>     }
>   }
> })
> ```

ok, i will try

**Comment by I-Own-You** [comment]
> > after i yank the commit hash, then i press 'p', it doesnt paste the commit hash, it pastes whatever i yanked before the commit hash, i can make a video, maybe you will better understand ?
> 
> that’s because of your clipboard config, you’re attempting to paste from `+`, if you pressed `”0p` it would work.

"0p doesnt work

**Comment by I-Own-You** [comment]
actually i can just get it from registers then, thanks!

**Comment by ibhagwan** [comment]
How about `""p`?

In any event, the yank is clearly in the register, so the `ctrl-y` worked, being unable to paste it from the register with direct register shouldn’t happen and could be an issue with your installation / config but **not an issue with fzf-lua**.

There is nothing more I can do with this issue unfortunately, closing.

**Comment by ibhagwan** [comment]
> actually i can just get it from registers then, thanks!

I also gave you an option to copy it to the clipboard [in this comment](https://github.com/ibhagwan/fzf-lua/issues/846#issuecomment-1676359497).
