### ISSUE TITLE
empty garbage buffer when opening an entry in a new window from lsp provider

### ISSUE THREAD

**Issue by tomtomjhj** [ibhagwan/fzf-lua#847]
### Info

- Operating System: Ubuntu 22.04
- Shell: bash
- Terminal: gnome-terminal
- `nvim --version`: 0.10, 6d93bdd45
- `fzf --version`: 0.42.0

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>Some modifications to `mini.sh`</summary>

```diff
diff --git a/scripts/init.lua b/scripts/init.lua
index 5a685c6..f58f4c3 100644
--- a/scripts/init.lua
+++ b/scripts/init.lua
@@ -7,6 +7,12 @@ vim.o.termguicolors = true

 require "fzf-lua".setup { global_git_icons = false }

+require'mason'.setup()
+vim.cmd[[MasonInstall lua-language-server]]
+
+require'mason-lspconfig'.setup()
+require'lspconfig'.lua_ls.setup{}
+
 vim.api.nvim_set_keymap("n", "<C-\\>", [[<Cmd>lua require"fzf-lua".buffers()<CR>]], {})
 vim.api.nvim_set_keymap("n", "<C-k>", [[<Cmd>lua require"fzf-lua".builtin()<CR>]], {})
 vim.api.nvim_set_keymap("n", "<C-p>", [[<Cmd>lua require"fzf-lua".files()<CR>]], {})
diff --git a/scripts/mini.sh b/scripts/mini.sh
index 69d86fb..1b61eed 100755
--- a/scripts/mini.sh
+++ b/scripts/mini.sh
@@ -36,6 +36,9 @@ if [ "${1:-}" = "reset" ]; then
 fi

 download_plugin "nvim-tree" "nvim-web-devicons"
+download_plugin "neovim" "nvim-lspconfig"
+download_plugin 'williamboman' 'mason.nvim'
+download_plugin 'williamboman' 'mason-lspconfig.nvim'

 # if exists, link to local folder so we can test local changes
 if [ -d "${plug_dir}" ]; then
```
</details>

### Description 
With lsp providers, opening the entry in a new window leaves an empty garbage buffer.

1. Run nvim with the above modified `mini.sh`. This sets up lua_ls.
2. Edit any lua file in this repository, e.g. lua/fzf-lua/init.lua
3. Use `:FzfLua lsp_references` e.g. on `require`
4. Select an item with `<C-s>` or `<C-t>`.
5. Run `:ls`. There is an empty `[No Name]` buffer.

**Comment by tomtomjhj** [comment]
https://github.com/ibhagwan/fzf-lua/blob/257aafb3c3a3475821db74d1a48ea5b097ac53a9/lua/fzf-lua/actions.lua#L127-L139

Here, `:new` (for `<C-s>`) is unconditionally run if the entry is a URI entry, even if it has `file://` scheme. I think it's more appropriate to use `:split`, `:vsplit`, and `:tab split` for `file_split`, `file_vsplit`, and `file_tabedit`. In fact, the git actions use them.

**Comment by ibhagwan** [comment]
Ty @tomtomjhj, I’ve been busy traveling in recent weeks, I’ll look into this and solve it as soon I can.

**Comment by ibhagwan** [comment]
>  think it's more appropriate to use `:split`, `:vsplit`, and `:tab split`

Correct, these were one of the first actions ever written and this slipping through as URI jump to location was added at a later stage.

Ty @tomtomjhj!
