### ISSUE TITLE
Better support for `git log --graph`

### ISSUE THREAD

**Issue by pmphan** [ibhagwan/fzf-lua#848]
### Info

- Operating System: Arch Linux
- Shell: bash
- Terminal: kitty
- `nvim --version`: 0.9.1
- `fzf --version`: 0.42.0

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
  git = {
    commits = {
      cmd = "git log --graph --all --color --format='%C(auto)%h%d %s %C(black)%C(bold)%cr'",
    }
  }
})
```
</details>

### Description 
This will cause yanking, checkout, edit and split actions to fail because the plugin fails to find the commit hash. `git log --graph` output starts with special characters at the beginning of the line, which is what the plugin was matching. Is it possible to change this line in `actions.lua` from

```lua
local commit_hash = selected[1]:match("[^ ]+")
```
to something like this instead
```lua
local commit_hash = selected[1]:match("[a-z0-9]+")
```
I am aware this doesn't cover all cases but it's the quick and easiest to implement while still allow for some level of flexibility.

**Comment by ibhagwan** [comment]
I’ll do some testing and see if I can find a better regex that captures more use cases.

**Comment by pmphan** [comment]
Thank you! Lua's "regex" is relatively limiting so that's the best I can come up with. I suppose another solution is to let the users define the pattern themselves via config?

**Comment by ibhagwan** [comment]
> Thank you! Lua's "regex" is relatively limiting so that's the best I can come up with. I suppose another solution is to let the users define the pattern themselves via config?

Good idea, try this (can also be defined via `setup`):
```lua
require("fzf-lua").git_commits({
  fn_match_commit_hash = function(line, _)
    return line:match("[a-z0-9]+")
  end
})
```
