### ISSUE TITLE
FzfLua code_actions does not work with nvim-jdtls

### ISSUE THREAD

**Issue by mikehaertl** [ibhagwan/fzf-lua#849]
When I use `:FzfLua code_actions`  with nvim-jdtls it gives me this error:

```
[Fzf-lua] LSP: server does not support codeActionProvider
```

The LSP server does support code actions:

```
:lua vim.lsp.buf.code_action()
Code actions:
1: Organize imports
2: Generate Getters and Setters
...
Type number and <Enter> or click with the mouse (q or empty cancels):
```

I can even make it work with fzf-lua, when registering UI select:
```
:FzfLua register_ui_select
:lua vim.lsp.buf.code_action()
```
![image](https://github.com/ibhagwan/fzf-lua/assets/675062/d1ca2bfa-b243-41f6-a86e-213011c244c6)

But `:FzfLua code_actions` still fails.

**Comment by ibhagwan** [comment]
> But :FzfLua code_actions still fails.

Code actions is a bit tricky to support and is also redundant since the introduction of `ui.select`, Telescope also dropped support for direct code actions (without ui.select), I just left it as “bonus” since it was already there, I will also remove support one day, use `ui.select` instead.
