### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by vijaymarupudi** [ibhagwan/fzf-lua#85]
Hello!

I've noticed that `fzf-lua` doesn't have a LICENSE file yet, so I wanted to bring that to your attention.

`nvim-fzf` has an AGPL license, so if you'd like to use the same LICENSE, that would be the easiest way to resolve this.

Otherwise, I can look into providing an exception if you have any problems with this. I'll have to reach out to contributors in that case, and it'll be a bit messy.

**Comment by ibhagwan** [comment]
Good catch, I’m not well versed in the difference between licenses, any specific reason to use AGPL over MIT for example?

**Comment by vijaymarupudi** [comment]
I view MIT as a free for all, basically you can do whatever with the code.

AGPL requires distributing the source code to users, which you're already doing. It probably has implications for commercializing the code (i.e. making it closed course), but I doubt that'll happen for neovim plugins.

**Comment by ibhagwan** [comment]
> I view MIT as a free for all, basically you can do whatever with the code.
> 
> AGPL requires distributing the source code to users, which you're already doing. It probably has implications for commercializing the code (i.e. making it closed sourse), but I doubt that'll happen for neovim plugins.

I see, doesn't much difference in this case then, I don't see much commercial use for neovim plugins or how to monetize them, with that said, I like the "free for all" approach for open-source.

**Comment by dccsillag** [comment]
Another notable thing from AGPL (if I'm not mistaken) is copyleft -- so anything that "redistributes" (which effectively means, uses) your code would also need to be licensed under a compatible license (which basically means that it should also be licensed under AGPL).

**Comment by ibhagwan** [comment]
> Another notable thing from AGPL (if I'm not mistaken) is copyleft -- so anything that "redistributes" (which effectively means, uses) your code would also need to be licensed under a compatible license (which basically means that it should also be licensed under AGPL).

Maybe then the better approach is just to use AGPL since @vijaymarupudi licensed his plug-in which is the cornerstone of this plug-in the same? Does that make sense?

**Comment by dccsillag** [comment]
Yeah, I think that's the way to go. I'm also a big fan of MIT license, but once you use some GPL/AGPL code your hands are kind of tied.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/68a398bc7c383a6421e28d8ca9664e3ffcf06952

**Comment by vijaymarupudi** [comment]
Great! Sorry about the hassle, GPL vs MIT is kind of an ideological thing, I use GPL when I think something should remain open source forever.

**Comment by ibhagwan** [comment]
> Hey @ibhagwan , would you consider re-licensing as MIT?
> 
> Would allow other nVim plugins released under MIT to borrow code from `fzf-lua`.

I personally don’t have any objection but given I initially based the plugin on code from nvim-fzf I would have to respect @vijaymarupudi’s decision. That said if @vijaymarupudi agrees we can go ahead with the change.

**Comment by vijaymarupudi** [comment]
Personally, I like the AGPL and its virality, and I don't really see any disadvantage to the AGPL for an open source ecosystem like neovim and its plugins.

That said, if there is a strong need to change the license, I will consider it. I will say that it's probably difficult to change the LICENSE at this point. If someone volunteers to put in the time to contact all contributors to nvim-fzf and get them to approve the license change, it could happen.

**Comment by wookayin** [comment]
AGPL is restrictive license: https://opensource.google/documentation/reference/using/agpl-policy not much different from GPL.

I believe it's a grey area whether having a AGPL/GPL licensed plugin as a "*dependency*" to one's project, or people "copying" example codes would lead to potential violation, but having a Apache or MIT compatible license would be much better and less restrictive in general.

**Comment by vijaymarupudi** [comment]
I understand that's it is restrictive, but it's restrictive in a way that makes more software open-source and protects the contributions of the contributors. Makes sense why a company like Google which depends on proprietary software would be against it. They don't want to share their source code. The safe choice for a project that wishes to use an AGPL dependency is to use the AGPL.

Practically speaking, I don't think the license restricts anyone from building / using the project. All neovim plugins of interest are open-source, and issues only arise if someone wants to build proprietary software on top. That's not something I think is likely, but I will hear arguments otherwise.

**Comment by Roniyahe54** [comment]
@vijaymarupudi, AGPL is sometimes disallowed even for internal, non-deployed development in companies. That means that developers working in those companies cannot use this plugin at all. 

What would effort would it take to change the license? Or has changing the license become a non-starter in the meantime?

**Comment by vijaymarupudi** [comment]
Sure, sounds like enough people want this.

`nvim-fzf` has 7 external contributors. Organize an effort to get them to approve the LICENSE change in an issue over there, and then I can change it, thereby also allowing fzf-lua's license to change.

**Comment by Roniyahe54** [comment]
Started https://github.com/vijaymarupudi/nvim-fzf/issues/58. Please check and confirm that MIT as a target is acceptable to you. I chose MIT as most other plugins I use are using the MIT license.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/ace9968be267b034e450be4feaf6e9107bc34fbd

Ty @Roniyahe54 for taking the lead on this.
