### ISSUE TITLE
[Question] How can I sort the lsp_document_diagnostics by the severity?

### ISSUE THREAD

**Issue by wustho** [ibhagwan/fzf-lua#851]
Hi, first of all, thanks for bringing fzf into neovi! I, personally, prefer this instead of telescope.

I want to ask, currently it seems that lsp_document_diagnostics sort the list by lines, how can I get it to sort by severity? (ie. Error at the first lines.

But also sorted by files after severity for lsp_workspace_diagnostics?

**Comment by ibhagwan** [comment]
No such functionality ATM, the interface of querying the diag is async and sorting would make it sync which I’m not super excited about as it could downgrade the UX.

You can filter by severity though, for example warnings and up, or just errors.

**Comment by wustho** [comment]
Is there no way to at least give the user option to make it synchronous with severity sort?

**Comment by ibhagwan** [comment]
Use `:FzfLua lsp_workspace_diagnostics sort=true` to sort descending from error -> hint and `:FzfLua lsp_workspace_diagnostics sort=2` for the reverse.

**Comment by wustho** [comment]
Thanks so much for your work!
