### ISSUE TITLE
oldfiles does not find all previously opened files

### ISSUE THREAD

**Issue by shyun3** [ibhagwan/fzf-lua#852]
### Info

- Operating System: Ubuntu 20.04.6 LTS
- Shell: zsh 5.8
- Terminal: Windows Terminal 1.17.11461.0
- `nvim --version`:
  ```
  NVIM v0.8.0-1210-gd367ed9b2
  Build type: Release
  LuaJIT 2.1.0-beta3
  Compiled by runner@fv-az505-656
  
  Features: +acl +iconv +tui
  See ":help feature-compile"
  
     system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/share/nvim"
  
  Run :checkhealth for more info
  ```
- `fzf --version`: 0.42.0 (d471067)

- [x] The issue is reproducible with `mini.sh`

### Description 
After I start Neovim (using my personal setup), I can see hundreds of files after running `:oldfiles` but `:FzfLua oldfiles` only shows one or a few. The command does not seem to be picking up previously opened files.

**Steps to reproduce**
* Create some test files:
  ```sh
  echo hello > first.txt
  echo world > second.txt
  ```
* Launch Neovim using `mini.sh` and open the first file: `:e first.txt`
* Close Neovim then launch it again to open the other file: `:e second.txt`
* Run `:FzfLua oldfiles` and confirm that `first.txt` is present:
  ![image](https://github.com/ibhagwan/fzf-lua/assets/37260523/efe727a9-b045-41e5-8c72-01211979b3ff)
* Close Neovim and open it again
* Run `:FzLua oldfiles` and confirm that only `second.txt` is present:
  ![image](https://github.com/ibhagwan/fzf-lua/assets/37260523/9f11313a-6b4a-446c-8ead-0a2324078a14)
* Run `:oldfiles` and confirm that both files are present:
  ```
  1: /home/shyun3/tmp/second.txt
  2: /home/shyun3/tmp/first.txt
  ```

**Comment by ibhagwan** [comment]
Strange, this doesn’t reproduce for me, I’ll try with `mini.sh` on a different computer.

![IMG_1462](https://github.com/ibhagwan/fzf-lua/assets/59988195/702442f6-480b-4db6-8063-8bb2ee73e8dc)

**Comment by ibhagwan** [comment]
Btw, is this a new issue? Could this be related to https://github.com/ibhagwan/fzf-lua/commit/257aafb3c3a3475821db74d1a48ea5b097ac53a9 (due to #834)?


What happens if you run `:FzfLua oldfiles stat_file=false`?
Can you post the result of:
```lua
:lua print(vim.fn.filereadable('/home/shyun3/tmp/first.txt'))
:lua print(vim.fn.filereadable('/home/shyun3/tmp/second.txt'))
```

**Comment by shyun3** [comment]
> Btw, is this a new issue? Could this be related to [257aafb](https://github.com/ibhagwan/fzf-lua/commit/257aafb3c3a3475821db74d1a48ea5b097ac53a9) (due to #834)?

Interesting. If I checkout the previous commit, it seems to work fine.
 
> What happens if you run `:FzfLua oldfiles stat_file=false`?

Hmm, I see all files with this option.

> Can you post the result of:
> ```lua
> :lua print(vim.fn.filereadable('/home/shyun3/tmp/first.txt'))
> :lua print(vim.fn.filereadable('/home/shyun3/tmp/second.txt'))
> ```

Both of these return `1`.

**Comment by ibhagwan** [comment]
> Hmm, I see all files with this option.

That’s because it skips the condition of checking if the file is readable:
https://github.com/ibhagwan/fzf-lua/blob/257aafb3c3a3475821db74d1a48ea5b097ac53a9/lua/fzf-lua/providers/oldfiles.lua#L55

> Both of these return 1.

This is where I get confused, why would this condition fail if this returns 1, I suspect this might be related to running `vim.fn` inside a lua coroutine but in this case it should fail equally on my system as well.

I will look for a libuv alternative for testing file readability.

**Comment by shyun3** [comment]
> This is where I get confused, why would this condition fail if this returns 1, I suspect this might be related to running `vim.fn` inside a lua coroutine but in this case it should fail equally on my system as well.
> 
> I will look for a libuv alternative for testing file readability.

Seems like the `vim.fn` does have something to do with it. I tried reverting that line and adding a `print` to see what's going on:
```lua
local fs_stat = not opts.stat_file and true or vim.loop.fs_stat(file)
print(file, vim.fn.filereadable(file) == 1)
```
But then I see the same issue as before of having only entry in the oldfiles window and `:mess` only contains one line (for example):
```
/home/shyun3/.config/nvim/bundle/fzf-lua/lua/fzf-lua/providers/oldfiles.lua true
```
despite `:oldfiles` containing much more entries.

It looks like `fs_stat()` returns mode, could that be used to determine if a file is readable?

**Comment by ibhagwan** [comment]
@shyun3, can you test with https://github.com/ibhagwan/fzf-lua/commit/949e9f82ccc5431b3fc4e94834dfdbc2c3a1ac3e?

It uses libuv instead if `vim.fn` so it can safely be used inside a coroutine.

**Comment by ibhagwan** [comment]
> It looks like fs_stat() returns mode, could that be used to determine if a file is readable?

I created a libuv version of `filereadable`:
https://github.com/ibhagwan/fzf-lua/blob/949e9f82ccc5431b3fc4e94834dfdbc2c3a1ac3e/lua/fzf-lua/utils.lua#L210-L217

**Comment by shyun3** [comment]
> @shyun3, can you test with [949e9f8](https://github.com/ibhagwan/fzf-lua/commit/949e9f82ccc5431b3fc4e94834dfdbc2c3a1ac3e)?
> 
> It uses libuv instead if `vim.fn` so it can safely be used inside a coroutine.

Yes, it's working!

**Comment by ibhagwan** [comment]
> > @shyun3, can you test with [949e9f8](https://github.com/ibhagwan/fzf-lua/commit/949e9f82ccc5431b3fc4e94834dfdbc2c3a1ac3e)?
> > It uses libuv instead if `vim.fn` so it can safely be used inside a coroutine.
> 
> Yes, it's working!

Great, my hunch was right, I'm still confued why lua coroutine behaves differently on my system but this was definitely the issue.
