### ISSUE TITLE
[Feat] Allow using a placeholder e.g. `{}` for `previewers.builtin.extensions`

### ISSUE THREAD

**Issue by Bekaboo** [ibhagwan/fzf-lua#853]
Firstly, thanks for this plugin!

Recently I'm considering switch from telescope to fzf-lua because the previewer is easier to configure, however I encountered some problems when trying to replicate my fzf setup in the terminal, which uses a custom previewer for pdf files.

I would like to use `pdftotext` to preview contents in pdf files, to achieve this in a terminal, I simply run

```sh
fzf --ansi --preview='pdftotext -l 10 -nopgbrk -nodiag -q {} -'
```

The last `-` in the preview command is important because it tells `pdftotext` to send the text to stdout instead of saving it to a file.

From the documentation, if I want to achieve similar behavior in fzf-lua, I will have to configure `previewers.builtin.extensions`, I tried with

```lua
fzf.setup({
  previewers = {
    builtin = {
      extensions = {
        ['pdf'] = { 'pdftotext -l 10 -nopgbrk -nodiag -q {} -' },
      },
    },
  },
})
```

But the output is not shown in the preview window. It seems that the filename can only be the last argument passes to the preview command. Could we use a placeholder in case that the filename should be somewhere in the middle of a command?

EDIT: it will be even better if we could use a callback function for each key in `previewers.builtin.extensions`, that will be useful for giving fallback command if some previewer if not executable, for example:

```lua
fzf.setup({
  previewers = {
    builtin = {
      extensions = {
        ['html'] = function(fpath, preview_winid)
            if vim.fn.executable('glow') == 1then
                return string.format([[glow -w="%d" -- "%s"]],
                vim.api.nvim_win_get_width(preview_winid),
                fpath),
            else if vim.fn.executable('highlight') == 1 then
                return string.format([[highlight -O ansi --force -- "%s"]], fpath)
            else
                -- ...
            end
        end,
      },
    },
  },
})
```

**Comment by Bekaboo** [comment]
@ibhagwan Thanks!

> you can use a fzf’s native previewer with the preview option (same as fzf_opts['--preview']

Do you mean I can use fzf's native preview window? How can I achieve that? I have `--preview='fzf-file-previewer {}'` in my env variable`$FZF_DEFAULT_OPTS` where `fzf-file-previewer` is a bash script in my `$PATH`, however setting `fzf_opts['--preview'] = 'fzf-file-previewer {}'` gives error

```
[Fzf-lua] fzf error 2: unknown option: {}
```

I've also tried `winopts.preivew.default = 'native'`, but get error

```
[Fzf-lua] invalid previewer 'native'
```

then I printed the available previewer options and found out they are:


```
{ "cat", "builtin", "bat", "bat_native", "git_diff", "bat_async", "highlight", "man
_native", "head", "help_tags", "help_native", "man" }
```

so I guess I need to first define the "native" file previewer in `previewers` table? Finally I tried:

```lua

fzf.setup({
  winopts = {
    preview = {
      default = 'fzf_file_previewer',
    },
  },
  fzf_opts = {
    ['--ansi'] = '',
    ['--info'] = 'hidden',
    ['--height'] = '100%',
    ['--layout'] = 'reverse',
    ['--border'] = 'none',
    ['--padding'] = '0',
    ['--margin'] = '0',
  },
  previewers = {
    fzf_file_previewer = {
      cmd = 'fzf-file-previewer',
    },
  },
})
```

but the preview window completely disappeared, I'm so confused:

![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/30314374-f5dd-40fd-875d-da541051b872)

---

I also noticed a bug (is it?) that the info (match count) is shown despite that I've set `['--info'] = 'hidden'` in fzf_opts.

**Comment by ibhagwan** [comment]
@Bekaboo, take a look at that:

https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-native-preview

**Comment by Bekaboo** [comment]
Thanks, that's much clearer. By the way do you have any idea about why the match count info is shown even when `['info'] = 'hidden'` or `['--no-info'] = ''` is set? Here's my config:

```lua
local fzf = require('fzf-lua')
local esc = vim.fn.shellescape

fzf.setup({
  fzf_opts = {
    -- ['--no-info'] = '',          -- setting this and commenting out `--info` setting gives same result
    ['--info'] = esc('hidden'),
    ['--layout'] = esc('reverse'),
    ['--border'] = esc('none'),
    ['--padding'] = esc('0'),
    ['--margin'] = esc('0'),
    ['--preview'] = esc('fzf-file-previewer {}'),
    ['--preview-window'] = esc('border-sharp'),
  },
})
```

result:

![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/2fabd370-8b03-420a-8d83-008a01054866)

Thanks again.

**Comment by ibhagwan** [comment]
> Thanks, that's much clearer. By the way do you have any idea about why the match count info is shown even when `['info'] = 'hidden'` or `['--no-info'] = ''` is set? Here's my config:

The global `fzf_opts` default is set to `inline` which gets overwritten by your config **but** there is a specific override for `files`, `grep` and `lsp_...` which sets the info to `default`:
https://github.com/ibhagwan/fzf-lua/blob/fe649a0d042e68d5810c9da8045560e885a705d7/lua/fzf-lua/defaults.lua#L198

You can negate that by setting it to `false` or overriding the setting:
```lua
fzf.setup({
  files = {
    fzf_opts = { ['--info'] = false }
  },
}
```

**Comment by ibhagwan** [comment]
> @ibhagwan Thanks that fixes the issue! I could be wrong but it will make more sense to me if `files`, `grep`, ... etc. respect the global default option values unless explicitly set up under their own config option field.

What you say makes sense but it’s also nice to have full info where the interface shows a proper loading interface and count where `inline` fits almost everything else so this was the best compromise, given this has been the default for a while I wouldn’t want to change it for the users.

**Comment by Bekaboo** [comment]
That's fine too, it's just my personal preferences, thanks for explanation!

**Comment by ibhagwan** [comment]
@Bekaboo, update to https://github.com/ibhagwan/fzf-lua/commit/edc1a4b8df73dea017bc46f321b73520b18255c6 and you can use `<file>` as a positional argument, note that the command is a table which is then sent directly to `termopen`, no shell is used so string commands cannot be used (ATM).

Let me know if this is sufficient and if not I will look into implementing the lua callback suggestion (although it would have to return a table, not a string due to `termopen`).

```lua
fzf.setup({
  previewers = {
    builtin = {
      extensions = {
        ['pdf'] = {
            "pdftotext",
            "-l",
            "10",
            "-nopgbrk",
            "-nodiag",
            "-q",
            "<file>",
            "-"
        },
      },
    },
  },
})
```
```

**Comment by Bekaboo** [comment]
@ibhagwan Thanks! It works like a charm.

> Let me know if this is sufficient

Yes this is sufficient, for simplicity a lua callback is not necessary, it is just a nice-to-have feature -- after all I mainly use neovim from my own PC where I can always ensure that some previewers (`w3m`, `htmltotext`, `pdftotext`, etc) are installed, so not really need a fallback mechanism, which is one of the main reasons why we may want lua callbacks in some cases.
