### ISSUE TITLE
Color of icons from nvim-web-devicons not refreshed after changing `&bg`

### ISSUE THREAD

**Issue by Bekaboo** [ibhagwan/fzf-lua#855]
### Info

- Operating System: 6.1.45-1-lts
- Shell: Fish
- Terminal: alacritty
- `nvim --version`: NVIM v0.10.0-dev-915+g898ef1835d
- `fzf --version`: 0.42.0 (d471067e)

- [ ] The issue is reproducible with `mini.sh`
Issue is not reproducable because nvim-web-devicons is not available in minimal config provided, I believe the bug is not config-related, though, after searching and reading #551

To provide some context, here are related issues and PR:
- nvim-tree/nvim-web-devicons#193
- nvim-tree/nvim-web-devicons#226
- nvim-tree/nvim-web-devicons#270

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({ --[[ empty here ]] })
```
</details>

### Description 

1. Open nvim with default config of fzf-lua
2. Launch fzf-lua with `:FzfLua files` or other commands that may require nvim-web-devicons -> icon color is correst (dark variant for light bg, light variant for dark bg)
3. Press `<C-\><C-n>` to enter normal mode, then `:if &bg ==# 'dark' | exe 'set bg=' . 'light' | else | exe 'set bg=' . 'dark' | endif`
4. Icon colors keep the same (should change)

### Additional info

Here are some screenshots of fzf-lua (left) and the comparison with the behavior of telescope.nvim (right):

- Step 2: ![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/4de0690d-8594-4b6c-8f78-c8df622e4535)

- Step 4: ![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/2fff8ebd-719e-4fe6-87a8-263ed734d63a)

**Comment by ibhagwan** [comment]
@Bekaboo, you're correct in  your analysis, since fzf-lua does the heavy lifting in a separate process (AKA multiprocess) it maintains a copy of the devicons map which is generated on init (and never refreshed). Due to various nuances (or bugs) the code iterates the map and fixes potential issues that could arise from misconfiguring devicons.

This process could be costly if called every run so I'd prefer to avoid that route, perhaps I can add a paramter to the function (`force=true`)  which you can run after changing the background to refersh fzf-lua's copy of devicons?

https://github.com/ibhagwan/fzf-lua/blob/6c8e95677f7a93de4a7ff30dff70a35728375e7f/lua/fzf-lua/config.lua#L19-L67

**Comment by Bekaboo** [comment]
@ibhagwan Hi thanks for your reply. I can imagin the hassles that may occur in fixing this, ~~I think an acceptable solution that might be simpler to implement is to reload the icons on opening fzf windows (i.e. icon colors will be corrected after closing the reponing fzf-lua),~~ or register an autocmd that fires on ColoScheme to refresh the icons so that we don't need to do that every time the user opens fzf-lua, Idk if it is doable, what's your opinion?

**Comment by ibhagwan** [comment]
> register an autocmd that fires on ColoScheme to refresh the icons so that we don't need to do that every time the user opens fzf-lua, Idk if it is doable, what's your opinion?

Very doable, I’ll look into it.

**Comment by ibhagwan** [comment]
@Bekaboo, https://github.com/ibhagwan/fzf-lua/commit/2632033492cadfbda3a8678d3c3e65d9397e521d - I found a cleaner solution, test the saved `bg` against `vim.o.bg` and refresh if needed, better than an autocmd IMHO.

**Comment by Bekaboo** [comment]
> test the saved bg against vim.o.bg and refresh if needed

Yeah that is cleaner, thanks for your work!

**Comment by ibhagwan** [comment]
> > test the saved bg against vim.o.bg and refresh if needed
> 
> Yeah that is cleaner, thanks for your work!

Ty @Bekaboo!
