### ISSUE TITLE
Can't open window with Lsp document_symbols 

### ISSUE THREAD

**Issue by hqkhan** [ibhagwan/fzf-lua#858]
### Info

- Operating System: AL2
- Shell: Bash
- Terminal: Alacritty
- `nvim --version`: `NVIM v0.9.1`
- `fzf --version`: `0.42.0 (brew)`

- [ ] The issue is reproducible with `mini.sh`

I couldn't test this with `mini.sh` as it requires an LSP client to be attached. I wasn't sure how to attach it in this sand-box nvim environment. 

<details>
<summary>fzf-lua configuration</summary>

This is similar to your setup. I'm not changing anything besides the `winopts`. This used to work but I'm not sure why it's not working now.

```lua
map_fzf('n', "<leader>ls", "lsp_document_symbols",    { desc = "Document symbols", winopts = small_top_big_bottom})
```
</details>

### Description 

The document symbols are there but when I open a symbol, it opens a new empty buffer and I see the path being incorrect.

Here's what I'm seeing:

https://github.com/ibhagwan/fzf-lua/assets/22674069/3ac0ff91-3de7-43ed-b126-393c324dd5a7

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b7bda51ba7d0c07aaa30e8428a6531e939f6c3a3 - Should work now @hqkhan.
