### ISSUE TITLE
Toggle between respecting/ignoring .gitignore in files picker

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#860]
### Description 

Not an issue, just a question/request for help.
I'm trying to write a custom action for respecting/ignoring `.gitignore` when using the files picker, but I'm not too sure of how to do it since it requires changing the command's arguments. I tried looking at the `grep<->live_grep` action but it uses `opts.__MODULE__` to reload the picker and I'm not sure if a similar hack is needed here?

**Comment by ibhagwan** [comment]
No need to use `opts.__MODULE__`, below is rudimentary and can be improved but you get the idea:
```lua
local fzf = require("fzf-lua")

_G.myfiles = function(opts)
  opts = opts or {}
  opts.debug = true -- use this to debug print the underlying command in the first line
  opts.cmd = opts.cmd or "fd --color=never --type f --hidden --follow"
  opts.actions = {
    ["ctrl-g"] = function(_, o)
      _G.myfiles(o)
    end
  }
  if opts.cmd:match("%s+%-%-no%-ignore$") then
    opts.cmd = opts.cmd:gsub("%s+%-%-no%-ignore$", "")
  else
    opts.cmd = opts.cmd .. " --no-ignore"
  end
  fzf.files(opts)
end

_G.myfiles()
```
The output from `debug=true`:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/61905cde-3046-40d3-8bf8-0013d0c385d0)

**Comment by MariaSolOs** [comment]
Works great, thanks a lot @ibhagwan! <3

I did notice that now I get an "unsupported action" message when hitting `esc`. I'm a bit surprised that the `ctrl-g` action isn't being merged with the defaults...?

**Comment by ibhagwan** [comment]
> Works great, thanks a lot @ibhagwan! <3
> 
> I did notice that now I get an "unsupported action" message when hitting `esc`. I'm a bit surprised that the `ctrl-g` action isn't being merged with the defaults...?

Are you defining the actions globally under `actions.files`? If so, this is by design so users can define their own global actions without having to set the defaults to `false` (for example, some users feel very strongly about `ctrl-x` for split vs `ctrl-s`).

See this comment from the [default options](https://github.com/ibhagwan/fzf-lua#default-options) section:
```lua
actions = {
    -- These override the default tables completely
    -- no need to set to `false` to disable an action
    -- delete or modify is sufficient
    files = {
    ...
```

When I use the sample I posted I see all actions in the `F1` help:

![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/6d9dbbe5-5a4a-4c42-9e22-5e14d8365588)

**Comment by ibhagwan** [comment]
FYI, `actions.files` is used everywhere files-type pickers are used: files, git_files, git_status, grep, lsp, oldfiles, quickfix, loclist, tags, btags, args, etc.

If you define the new action under `files.actions` it will get merged with the `actions.files` table.

**Comment by MariaSolOs** [comment]
@ibhagwan I did not add the action globally. It's interesting because I see the help entry for `esc`, but I still get the error message:

https://github.com/ibhagwan/fzf-lua/assets/62502207/91ed2de6-0e32-40b7-b2d2-6f84ac6ca7a0

**Comment by ibhagwan** [comment]
> @ibhagwan I did not add the action globally. It's interesting because I see the help entry for `esc`, but I still get the error message:

Which version of fzf are you using?

**Comment by MariaSolOs** [comment]
The relevant part of my configuration is:
```lua
-- Custom files picker with toggling for respecting/ignoring .gitignore.
local FilesPicker = {}
FilesPicker.toggle = function(_, opts)
    FilesPicker.pick(opts)
end
FilesPicker.pick = function(opts)
    opts = opts or {}
    opts.debug = true
    opts.cmd = opts.cmd or 'fd --color=never --type f --hidden --follow --no-ignore'
    opts.actions = {
        ['ctrl-g'] = FilesPicker.toggle,
    }
    if opts.cmd:match '%s+%-%-no%-ignore$' then
        opts.cmd = opts.cmd:gsub('%s+%-%-no%-ignore$', '')
    else
        opts.cmd = opts.cmd .. ' --no-ignore'
    end

    require('fzf-lua').files(opts)
end

-- Picker, finder, etc.
return {
    {
        'ibhagwan/fzf-lua',
        keys = {
            { '<leader>ff', FilesPicker.pick, desc = 'Find files' },
        },
        config = function()
            local fzf = require 'fzf-lua'

            -- Add the .gitignore toggle description for the files picker.
            require('fzf-lua.config').set_action_helpstr(FilesPicker.toggle, 'no-ignore<->ignore')

            fzf.setup {
                keymap = {
                    builtin = {
                        ['<C-/>'] = 'toggle-help',
                        ['<C-a>'] = 'toggle-fullscreen',
                        ['<C-i>'] = 'toggle-preview',
                        ['<C-f>'] = 'preview-page-down',
                        ['<C-b>'] = 'preview-page-up',
                    },
                    fzf = {
                        ['alt-s'] = 'toggle',
                        ['alt-a'] = 'toggle-all',
                    },
                },
                -- Configuration for specific commands.
                files = { git_icons = false },
                oldfiles = { include_current_session = true },
                grep = {
                    git_icons = false,
                    header_prefix = ' ',
                },
            }
        end,
    },
}
```

**Comment by MariaSolOs** [comment]
> Which version of fzf are you using?

0.42.0 (brew)

**Comment by ibhagwan** [comment]
Can you comment out the `keymap.fzf` section and try? the keymap tables work similar to the `actions.files` table where no default actions are merged, I suspect that due to your settings (unsure what ATM) the `esc` action isn't getting defined in:
https://github.com/ibhagwan/fzf-lua/blob/b7bda51ba7d0c07aaa30e8428a6531e939f6c3a3/lua/fzf-lua/core.lua#L216-L226

**Comment by ibhagwan** [comment]
If  commenting `keymap.fzf` turns out to be the issue, can you try adding from the default actions and see which action solves the issue?

https://github.com/ibhagwan/fzf-lua/blob/b7bda51ba7d0c07aaa30e8428a6531e939f6c3a3/lua/fzf-lua/defaults.lua#L87-L100

You can see the issue if you run `:FzfLua files debug=true` and then inspect `:messages`, the fzf command should contain the following `--expect=esc,alt-q,ctrl-q,ctrl-t,ctrl-s,ctrl-c,ctrl-v,ctrl-l`, without `esc` in the `--expect` you'd be seeing this error message.

**Comment by ibhagwan** [comment]
Just tried with your config and I can't seem to reproduce the issue, the `--expect` flag seems to correctly have both `esc` and `ctrl-c`, also using fzf `0.42.0`.

Does this happen only in the custom files picker or in all of them?

**Comment by MariaSolOs** [comment]
> Just tried with your config and I can't seem to reproduce the issue, the `--expect` flag seems to correctly have both `esc` and `ctrl-c`, also using fzf `0.42.0`.
> 
> Does this happen only in the custom files picker or in all of them?

Very interesting. This happens only when using the custom files picker and when I'm ignoring `.gitignore` (so after the toggle).

**Comment by ibhagwan** [comment]
> > Just tried with your config and I can't seem to reproduce the issue, the `--expect` flag seems to correctly have both `esc` and `ctrl-c`, also using fzf `0.42.0`.
> > Does this happen only in the custom files picker or in all of them?
> 
> Very interesting. This happens only when using the custom files picker and when I'm ignoring `.gitignore` (so after the toggle).

Checking.

**Comment by ibhagwan** [comment]
My bad, didn't need to use the actions sent by the function (2nd arg), needed to use the original `opts` instead, change this:
```lua
    opts.actions = {
        ['ctrl-g'] = FilesPicker.toggle,
    }
```

To this:
```lua
    opts.actions = {
        ['ctrl-g'] = function() FilesPicker.pick(opts) end,
    }
```

**Comment by MariaSolOs** [comment]
@ibhagwan genius! Thank you soooo much!
I feel awful to continue bothering you hehe but using the closure means I cannot add the `helpstr` anymore right?

**Comment by ibhagwan** [comment]
> @ibhagwan genius! Thank you soooo much! I feel awful to continue bothering you hehe but using the closure means I cannot add the `helpstr` anymore right?
> 
> EDIT: nvm, I guess I can do it by keeping the current opts in the `FilesPicker` class. Sometimes `lua` confuses me hehe.

Np at all @MariaSolOs!

To set a function help string, save a local copy of the function ptr and then use (I should probably move this to the main API one day):
```lua
require'fzf-lua'.config.set_action_helpstr(fn_ptr, “help string”)
```

**Comment by ibhagwan** [comment]
> EDIT: nvm, I guess I can do it by keeping the current opts in the FilesPicker class. Sometimes lua confuses me hehe.

Oops, I just saw you wrote this and that you already know about `set_acrion_helpstr` :)

**Comment by MariaSolOs** [comment]
> Oops, I just saw you wrote this and that you already know about set_acrion_helpstr :)

No worries! I just got confused with how to create the function pointer for a sec, but I think I got it.

I'm ready to close this issue, but before I do that I want to deeply thank you for debugging this with me and your quick and complete responses! The only thing better than an amazing plugin is an amazing maintainer, and `fzf-lua` is lucky enough to have both <3

**Comment by ibhagwan** [comment]
> > Oops, I just saw you wrote this and that you already know about set_acrion_helpstr :)
> 
> No worries! I just got confused with how to create the function pointer for a sec, but I think I got it.
> 
> I'm ready to close this issue, but before I do that I want to deeply thank you for debugging this with me and your quick and complete responses! The only thing better than an amazing plugin is an amazing maintainer, and `fzf-lua` is lucky enough to have both <3

Tysm for the kind words @MariaSolOs!

**Comment by lsaint** [comment]
I'm interested in this feature.
Is there anyone who can tell me how to achieve it from scratch?


> Toggle between respecting/ignoring .gitignore in files picker

**Comment by MariaSolOs** [comment]
> [@lsaint](https://github.com/lsaint), I can’t find the original comment from the email for some reason, I will leave this comment as an FYI just in case someone else needs to see this.
> 
> This issue isn’t relevant anymore, this functionality now comes out of the box with 3 binds`alt-{i|h|f}` that toggle ignore|hidden|follow respectively, if the defaults don’t work for you the binds are customizable via `actions.files`, there are also “title flags” (next to the picker title) that display `h i f` depending on which flag is activated, to start in any state you can either customize `cmd|rg_opts|fd_opts` or simpler:
> 
> :FzfLua files hidden=true no_ignore=true follow=true
> ![Image](https://github.com/user-attachments/assets/66f27dbd-d6eb-405e-b7db-64772b2bea62)

Same here! I also got the email notification but I echo everything that @ibhagwan said and [I'm now longer using my custom picker anymore](https://github.com/MariaSolOs/dotfiles/blob/3002d5af400d96be944040d818aca033bce4464e/.config/nvim/lua/plugins/fzf-lua.lua) as the behavior is now built-in :)

**Comment by ibhagwan** [comment]
@MariaSolOs, while we’re revisiting useful features I noticed you aren’t using any profile, I highly recommend adding the “hide” profile to your config, this will make fzf-lua hide the fzf process instead if killing it and you get to keep selection, cursor position or a long running enumeration (if the project is large enough).

Personally I use both `hide` and `border-fused` which closes the gap between the previewer and main window thus giving me one extra line:

https://github.com/ibhagwan/nvim-lua/blob/e5c424518a52c02fcd58327a19d02f2d377f4c11/lua/plugins/fzf-lua/setup.lua#L77

To use both all you need to do is add `{ "border-fused", "hide" }` in line 45 (your opts [1] position).

**Comment by ibhagwan** [comment]
> omg and THIS IS WHY I LOVE FZF-LUA <3
> 
> Thank you for the suggestions, adding them to my config ASAP

Ty @MariaSolOs :heart: I’ve been running this for a while now, thinking of making this the default so lmk if you find any issues.

**Comment by lsaint** [comment]
> [@lsaint](https://github.com/lsaint), I can’t find the original comment from the email for some reason, I will leave this comment as an FYI just in case someone else needs to see this.
> 
> This issue isn’t relevant anymore, this functionality now comes out of the box with 3 binds`alt-{i|h|f}` that toggle ignore|hidden|follow respectively, if the defaults don’t work for you the binds are customizable via `actions.files`, there are also “title flags” (next to the picker title) that display `h i f` depending on which flag is activated, to start in any state you can either customize `cmd|rg_opts|fd_opts` or simpler:
> 
> :FzfLua files hidden=true no_ignore=true follow=true
> ![Image](https://github.com/user-attachments/assets/66f27dbd-d6eb-405e-b7db-64772b2bea62)

@ibhagwan Yep, I delete the comment cause i figure out the functionality in current version. But still thank you very much for your reply.
