### ISSUE TITLE
Wrapping up/down navigation

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#861]
### Info

- Operating System: macOS Ventura 13.5
- Shell: zsh
- Terminal: kitty
- `nvim --version`: v0.10.0-dev-953+g1635c9e75
- `fzf --version`: 0.42 brew

### Description 

Not sure if this is a feature request for this plugin or `fzf` itself, but I'm wondering how I could make up/down motions (e.g. `<C-n>/<C-p>`) "wrap around" when reaching the last/first entry. For example, I would like to be able to press `<C-n>` when the last entry is currently selected and wrapping back to the first result.

**Comment by ibhagwan** [comment]
This would be a feature for fzf the binary, fortunately it already exists, 
From `man fzf`:
```man
       --cycle
              Enable cyclic scroll
```
> Within the fzf-lua context:
```lua
require'fzf-lua'.setup {
  fzf_opts = { ['--cycle'] = '' }
}
```

**Comment by MariaSolOs** [comment]
Oh I'm so sorry, I should have read the documentation more thoroughly. I apologize for wasting your time!

**Comment by ibhagwan** [comment]
> Oh I'm so sorry, I should have read the documentation more thoroughly. I apologize for wasting your time!

My pleasure @MariaSolOs, feel free to ask anything :)
