### ISSUE TITLE
Feature request: "Multiline diagnostics" setting

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#863]
### Info

- Operating System:
- Shell: zsh
- Terminal: kitty
- `nvim --version`: v0.10.0-dev-1002+gee56daebb
- `fzf --version`: 0.42 (brew)

### Description 

I would like to have a setting that allowed me to configure multiline diagnostic messages. My idea is that if `multiline = true`, then multiline diagnostics are concatenated into a single string (as done below but maybe using a space for readability). If `multiline = false`, then only the first line of the diagnostic is listed.

https://github.com/ibhagwan/fzf-lua/blob/a6d524cc1107caf7655ff6dc0aa9a51792d27965/lua/fzf-lua/providers/diagnostic.lua#L157

**Comment by ibhagwan** [comment]
@MariaSolOs - https://github.com/ibhagwan/fzf-lua/commit/ddf535b631db07b0d6c1f692c535a210e7e5e284, should do what you want if I understood the requirements correctly.

**Comment by MariaSolOs** [comment]
Works like a charm, thank you so much @ibhagwan! <3
