### ISSUE TITLE
Inconsistent display location when using fzf-tmux

### ISSUE THREAD

**Issue by aud** [ibhagwan/fzf-lua#865]
### Info

- Operating System: MacOS Ventura 13.5
- Shell: Bash v5.2.15
- Terminal: iTerm2
- `nvim --version`:
```sh
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```
- `fzf --version`:
```sh
~ $ fzf --version
0.42.0 (brew)
```

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require("fzf-lua").setup({
  "fzf-tmux",
  fzf_tmux_opts = {
    -- Docs: `fzf-tmux --help`
    ["-d"] = "20%"
  },
})
```
</details>

### Description 

Hi, love the plugin so far. I'm trying to migrate from `fzf.vim` where I'm a user of the fzf-tmux profile. In that config I use the `down` option which basically pins FZF on the bottom of the screen: (docs: https://github.com/junegunn/fzf/blob/c5e4b83de3a201e496f356e826529a45165138ea/doc/fzf.txt#L500-L504).

```
let g:fzf_layout = { 'down': '20%' }
```

In `fzf-tmux`, I noticed the `-d` option appears to be equivalent. However, it's working very inconsistently when passed through the fzf-lua using `fzf_tmux_opts`:

For example, this is what it looks like when it works: 
<img width="1512" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/13060190/d8273f6b-af4d-454c-94c5-4641e68dc863">

Here's a video of the behaviour. It doesn't work for the first few times, then it works fine. Seems like there might be a race somewhere.

https://github.com/ibhagwan/fzf-lua/assets/13060190/72f5db55-47c6-40f2-bb93-eed941d168bb

Thanks for looking. Any ideas?

**Comment by ibhagwan** [comment]
> Thanks for looking. Any ideas?

Ty for the report @aud ! Interesting, I’ll do some digging and keep you posted.

In the meantime can you post the output of `:lua print(vim.env.FZF_TMUX_OPTS)` (essentially the shell’s `$FZF_TMUX_OPTS`)?

If it’s not empty can you run `:lua vim.env.FZF_TMUX_OPTS = nil` and then try?

**Comment by aud** [comment]
In both UI cases (pinned to the bottom and not) the output of `:lua print(vim.env.FZF_TMUX_OPTS)` is `nil`.

**Comment by ibhagwan** [comment]
Thanks @aud, I’ll investigate further when I get a chance in the next days.

**Comment by ibhagwan** [comment]
I had another idea to test your race condition assumption, when the bug is reproduced try running the below and let me know if that works fine?
```lua
 :lua require'fzf-lua'.files({ fzf_tmux_opts = { ["-d"] = "20%" } })
```

**Comment by aud** [comment]
Unfortunately had no effect:

https://github.com/ibhagwan/fzf-lua/assets/13060190/8d296a8f-9400-4637-bf66-fed2180f0a4c

**Comment by ibhagwan** [comment]
Sorry for the spam, I think I have another idea, the default `-p` is never removed (in the options table merge), if that’s the case, this should work:
```lua
require("fzf-lua").setup({
  "fzf-tmux",
  fzf_tmux_opts = {
    ["-p"] = false, 
    ["-d"] = "20%",
  },
})
```

If this works you can also experiment with removing the default margin setting by setting it also to `false`:
https://github.com/ibhagwan/fzf-lua/blob/2632033492cadfbda3a8678d3c3e65d9397e521d/lua/fzf-lua/defaults.lua#L126

**Comment by aud** [comment]
That worked great! Fixes the inconsistency. Thanks for taking a look.

**Comment by ibhagwan** [comment]
> That worked great! Fixes the inconsistency. Thanks for taking a look.

Now we know what the issue was, specifying both `-d` and `-p` creates the conflict, I’ll leave this issue open and when I get a chance I’ll add code that removes conflicting options or doesn’t copy from defaults (I’ll think about which would work best).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/13d9974c17c526412648395a062db936fecbe10b - this commit deletes the popup flag when split pane flags are found (`-udlr`), you can omit `["-p"] = false` if you wish.
