### ISSUE TITLE
Custom icons from nvim-web-devicons are not loaded

### ISSUE THREAD

**Issue by ArtAndreev** [ibhagwan/fzf-lua#866]
### Info

- Operating System: macOS Ventura 13.5 (22G74)
- Shell: zsh 5.9 (x86_64-apple-darwin22.0)
- Terminal: WezTerm nightly
- `nvim --version`:
    ```
    NVIM v0.9.1
    Build type: Release
    LuaJIT 2.1.0-beta3

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

    Run :checkhealth for more info
    ```
- `fzf --version`: `0.42.0 (brew)`

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
-- default.
require('fzf-lua').setup({})
```
</details>

### Description 

Fzf-lua doesn't load setup of `nvim-web-devicons` and custom icons, suppose, I have this configuration in `lazy.nvim`:
```lua
return {
  "nvim-tree/nvim-web-devicons",

  opts = {
    strict = true,
    override_by_filename = {
      ["go.mod"] = {
        icon = "",
        color = "#519aba",
        cterm_color = "74",
        name = "GoMod",
      },
    },
  },
}
```

and this project:
```
.
├── go.mod
└── main.go
```

I open it and run `:FzfLua files`, that's what I got:

<img width="756" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/26388769/b571f08c-9b11-45fb-9f0d-354bc258d01f">

The result is another in `Telescope`:

<img width="756" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/26388769/09adde62-a3ce-45c0-a9f0-7a64d411fd2d">

and another in `nvim-tree`:

<img width="756" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/26388769/8938d984-e6e5-4868-9011-d189a8e1acb3">

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/877ea6a3887877dfe47cdda501ec964c1e25b119

Ty for the report @ArtAndreev, for performance reasons fzf-lua runs in an external process and executes its own copy of the devicons lookup function which wasn't taking into account filename overrides, the above commit fixes this.

**Comment by ArtAndreev** [comment]
It works now, thank you!

**Comment by ibhagwan** [comment]
> It works now, thank you!

Ty for the confirmation @ArtAndreev!
