### ISSUE TITLE
`git_status` preview shows error for new directories with untracked files

### ISSUE THREAD

**Issue by heygarrett** [ibhagwan/fzf-lua#867]
### Info

- Operating System: macOS 13.5.1
- Shell: fish
- Terminal: wezterm
- `nvim --version`:
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
```
- `fzf --version`: 0.42.0 (brew)

- [x] The issue is reproducible with `mini.sh`

### Description 

After adding a new directory with an untracked file to a git repo, selecting that new directory from `git_status` shows an error in the preview:
![CleanShot 2023-09-05 at 22 26 22@2x](https://github.com/ibhagwan/fzf-lua/assets/1154912/3132d1b4-b5f8-4a94-ae1e-e93cb83814e5)

Selecting an untracked file in an existing directory does not show an error:
![CleanShot 2023-09-05 at 22 25 58@2x](https://github.com/ibhagwan/fzf-lua/assets/1154912/48acd607-2fb7-43df-a8e9-a6590bbf7102)

**Comment by ibhagwan** [comment]
I’ll fix it by testing if the untracked is a folder and if so I can display the output of `ls -la`.

personally, I modified my git status command to include individual untracked files (with `-su`) so I can both preview and control their staging better:
https://github.com/ibhagwan/nvim-lua/blob/d2292418dc5ace0c11dde1f54f28f64ac748bc47/lua/plugins/fzf-lua/setup.lua#L156

Try the below:
```lua
require'fzf-lua'.setup {
  git = {
    status = { cmd = "git status -su" }
  }
}

**Comment by heygarrett** [comment]
> Personally, I modified my git status command to include individual untracked files (with -su) so I can both preview and control their staging better

Oh, this is great! Any reason this isn't the default behavior for the picker?

**Comment by ibhagwan** [comment]
> > Personally, I modified my git status command to include individual untracked files (with -su) so I can both preview and control their staging better
> 
> Oh, this is great! Any reason this isn't the default behavior for the picker?

Good question, legacy default and slight hesitation on my end that repos with lots of untracked files take a bit longer to load.

Now that you mentioned it, I might set this as default next commit 😄

**Comment by heygarrett** [comment]
Whatever you think is best. 😁 I'm just glad to have the option!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7794b616acdca5ba0cf78781f8adc0752bac2d51

@heygarrett, the above commit both fixes displaying preview for directories and also changes the default command to `git status -su` which is superior in most cases.
