### ISSUE TITLE
`require('fzf-lua').buffers {}` call from actions.files does not work

### ISSUE THREAD

**Issue by TheBlob42** [ibhagwan/fzf-lua#868]
### Info

- Operating System: Ubuntu 20.04.6 LTS
- Shell: bash
- Terminal: GNOME Terminal 3.36.2
- `nvim --version`: NVIM v0.10.0-dev-1031+gc431d820e
- `fzf --version`: 0.36.0 (2023011)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
local fzf = require('fzf-lua')
fzf.setup({
    actions = {
        files = {
            ['alt-s'] = {
                function(_, opts)
                    fzf.live_grep { cwd = opts.cwd }
                end,
                fzf.actions.resume
            },
            ['alt-b'] = {
                function(_, opts)
                    fzf.buffers { cwd = opts.cwd }
                end,
                fzf.actions.resume
            }
        }
    }
})
```
</details>

### Description 

I have create some simple actions to quickly start a live_grep or switch to an existing buffer from an fzf-lua files dialog. Starting the search this way works perfectly fine, but for some reason the buffer mapping (check the fzf-lua configuration) always throws an error:

```
Error executing vim.schedule lua callback: ...zel/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:297: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [builtin#36]: at 0x55a5779c74c0
        ...zel/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:297: in function 'fn'
        ...zel/.local/share/nvim/lazy/fzf-lua/lua/fzf-lua/shell.lua:71: in function <...zel/.local/share/nvim/lazy/fzf-lua/lua/fzflua/shell.lua:70>
````

I have verified with your `mini.sh` configuration that this is not caused by another plugin or other parts of my configuration. Am I doing something wrong here or is the mapping created correctly? A regular call to `require('fzf-lua').buffers { cwd = "<path>" }` works as expected, so it seems to me that something in the actions handling has to do with this error.

> It also does not work if I remove the `cwd = opts.cwd` part of the call

**Comment by ibhagwan** [comment]
Why are you calling `resume` after calling buffers (or live grep)? Once you called buffers the interface opens and there is no need to open the interface again with resume.

**Comment by TheBlob42** [comment]
I thought that I needed this to avoid the fzf window to "flicker", but it seems like I have misunderstood its purpose :sweat_smile: 
Unfortunately the issue persists for me when I remove the `resume` call

**Comment by ibhagwan** [comment]
Also, read this comment in the README under the `actions` table:
```lua
    -- These override the default tables completely
    -- no need to set to `false` to disable an action
    -- delete or modify is sufficient
```

https://github.com/ibhagwan/fzf-lua/blob/877ea6a3887877dfe47cdda501ec964c1e25b119/README.md?plain=1#L560-L564


The reasons for this is to ease modifying the global actions without setting the default actions to `false` but what you’ve done is also delete the `default` action which is probably causing this issue.

**Comment by TheBlob42** [comment]
Sorry that is something which I missed in my minimal example configuration (not my actual configuration). I know about the "replacement logic" of the actions table and my actual configuration takes account for this. But even with the "default" action set this issue still persists (I left out the custom `live_grep` action for this example):

```lua
local fzf = require('fzf-lua')
fzf.setup {
    actions = {
        files = {
            ['default'] = fzf.actions.file_edit_or_qf,
            ['alt-b'] = {
                function(_, opts)
                    fzf.buffers { cwd = opts.cwd }
                end
            }
        }
    }
}

```

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/ff6839852cef39ca0b617be341747948638142a2

@TheBlob42, should work now, ty for the report!

**Comment by TheBlob42** [comment]
I just gave it another try and it works, thanks for the fast response and fix :slightly_smiling_face:
