### ISSUE TITLE
Does not work with NextJS file structure

### ISSUE THREAD

**Issue by brenoprata10** [ibhagwan/fzf-lua#870]
If using a dynamic routing with NextJS. The file preview and file navigation will not work.

File Structure example:
```
-app
---[playerId]
-----route.tsx
```

This structure will return this error when using the plugin:
<img width="1241" alt="Screenshot 2023-09-13 at 14 22 16" src="https://github.com/ibhagwan/fzf-lua/assets/26099427/5a06dd29-6b9b-4d26-9e54-5e1ed4dece5d">

This happens due to the `[` `]` characters, a similar error shows up if I try using git normally in the terminal
<img width="558" alt="Screenshot 2023-09-13 at 14 23 20" src="https://github.com/ibhagwan/fzf-lua/assets/26099427/1d45b4aa-c393-48fc-9f27-3f779398717c">

Escaping the chars with `\` makes it work on my shell, so I think the same solution would fit here.

`git add src/app/\[playerId\]/page.tsx`

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/7ee9b5378a32b517f4bdccb8948def5c58fa2ac5

@brenoprata10, the issue was caused by using `path_shorten`, the glob expand function required escaping the square brackets , should work with the above commit.

**Comment by brenoprata10** [comment]
Thanks a lot and keep up the great work!

**Comment by brenoprata10** [comment]
Tested right now and I confirm it's fixed 🍪
