### ISSUE TITLE
fzf-lua does not work if set `ambiwidth="double"`

### ISSUE THREAD

**Issue by mimikun** [ibhagwan/fzf-lua#874]
### Info

- Operating System: Ubuntu 22.04(WSL2)
- Shell: fish
- Terminal: wezterm 20230713-081419-f73f7180
- `nvim --version`:
	- NVIM v0.10.0-dev-1f551e0
	- NVIM v0.9.2
- `fzf --version`: 0.42.0 (d471067)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({})
```
</details>

### Description 

`mini.sh` can't work to my env.
using [neovim's minimal reproduction template](https://github.com/neovim/neovim/wiki/Minimal-reproduction-template).

#### issue.lua

```lua
for name, url in pairs{
  -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
  -- some_plugin = 'https://github.com/author/plugin.nvim'
  fzf_lua = 'https://github.com/ibhagwan/fzf-lua'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
require("fzf-lua").setup({})

vim.opt.ambiwidth = "double"
```

#### run

```shell
nvim --clean -u issue.lua
```

#### error message

```txt
E5108: Error executing lua ...hoge/nvim_issue/fzf_lua/lua/fzf-lua/providers/module.lua:38: /tmp/hoge/nvim_issue/fzf_lua/
lua/fzf-lua/utils.lua:751: border chars must be one cell
stack traceback:
        [C]: in function 'fzf_exec'
        ...hoge/nvim_issue/fzf_lua/lua/fzf-lua/providers/module.lua:38: in function <...hoge/nvim_issue/fzf_lua/lua/fzf-
lua/providers/module.lua:9>
        /tmp/hoge/nvim_issue/fzf_lua/lua/fzf-lua/cmd.lua:78: in function 'run_command'
        /tmp/hoge/nvim_issue/fzf_lua/lua/fzf-lua/cmd.lua:87: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

**Comment by ibhagwan** [comment]
Ty for this report @mimikun, TIL about `ambiwidth`.

The latest commit should make it work but the preview doesn't look normal since the border is manually drawn and the double width characters make it look spaced, working on a fix by using the native border instead. will update this post when done.

**Comment by ibhagwan** [comment]
@mimikun, use the latest commit https://github.com/ibhagwan/fzf-lua/commit/ba449c6112a6bf694e740c1de79c054ad6d11be4, it should also fix the spaced preview border characters and title when `ambiwidth="double"`.

Note that the default preview scrollbar is drawn by the border which is now not possible, I highly recommend switching to the `float` scrollbar which will still work with the new commit:
```lua
require("fzf-lua").setup({
  winopts = {
    preview = { scrollbar = "float" }
  }
})
```

Which should look like this:
> note the floating scrollbar at the right side of the preview window
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/8c9dbcd4-194f-4db9-8aff-0d91382d04b9)

**Comment by mimikun** [comment]
@ibhagwan 
Thank you fix.
Is there a way to customize the part of the scrollbar indicated by the red circle?
It's thin and hard to see.
![スクリーンショット 2023-09-15 204912](https://github.com/ibhagwan/fzf-lua/assets/13450321/aa077a34-d542-4661-a33e-6a562289d62b)

**Comment by ibhagwan** [comment]
> @ibhagwan
> Thank you fix.
> Is there a way to customize the part of the scrollbar indicated by the red circle?


Yes, this is the scroll bar controlled by fzf the binary, it has a few different customization options, see [fzf’s man  page](https://www.mankier.com/1/fzf) and use `fzf_opts` to pass the options to fzf, you’re most likely interested in:
```man
--scrollbar=CHAR1[CHAR2]
  Use the given character to render scrollbar.
  (default: '│' or ':' depending on --no-unicode).
  The optional CHAR2 is used to render scrollbar of the preview window.
```

**Comment by mimikun** [comment]
Thank you!
