### ISSUE TITLE
Feature request: Telescope's path_display = "truncate"

### ISSUE THREAD

**Issue by smjonas** [ibhagwan/fzf-lua#881]
Is there currently an option that works like Telescope's `path_display = "truncate"`? I could not find an option for that.
Here's how it looks in telescope (file names that are too long are truncated on the left which I find really useful):
![image](https://github.com/ibhagwan/fzf-lua/assets/40792180/96815dbb-3d77-4f96-affb-bc275cac67e4)

**Comment by ibhagwan** [comment]
From `man fzf`:
```
--keep-right
Keep the right end of the line visible when it's too long.
Effective only when the query string is empty.
```

Use with:
```lua
require'fzf-lua'.files({ fzf_opts = { ['--keep-right'] = '' } }
```

**Comment by ibhagwan** [comment]
You should also try `path_shorten = true`, it’s different but also effective.

**Comment by smjonas** [comment]
Thank you, `--keep-right` works great!

**Comment by littenglt** [comment]
what about the result display for grep strings? Is there currently an option that works like Telescope's path_display = "truncate"? 
if use "path_shorten = 1", the result is not very elegant....

**Comment by ibhagwan** [comment]
> what about the result display for grep strings? Is there currently an option that works like Telescope's path_display = "truncate"? if use "path_shorten = 1", the result is not very elegant....

You can try different length but unfortunately no other option ATM, we need the full paths inside fzf to be able to use them in actions later.

Play around with fzf_opts `--nth` with a separator for delimiter, maybe you’ll get what you want.

**Comment by littenglt** [comment]
With other lengths, it's not very good when it comes to presenting results of grep string. So is it possible to use the form -1, 1 like telescope to make the file name in some locations not be reduced in length?
for example:
drivers/s/lpfc/lpfc_hw.h:227:4: * Directory Service Subtypes

**Comment by ibhagwan** [comment]
> With other lengths, it's not very good when it comes to presenting results of grep string. So is it possible to use the form -1, 1 like telescope to make the file name in some locations not be reduced in length? for example: drivers/s/lpfc/lpfc_hw.h:227:4: * Directory Service Subtypes

Unfortunately that’s not possible ATM.

**Comment by MariaSolOs** [comment]
@ibhagwan sorry to revive this old thread but maybe I'm missing something.

I have this in my `fzf-lua` configuration:
```lua
files = {
    fzf_opts = { ['--keep-right'] = '' },
    winopts = {
        preview = { hidden = true },
    },
}
```

But then truncation still seems to happen based on the location of the match:

<img width="946" height="668" alt="Image" src="https://github.com/user-attachments/assets/95d03a31-cef2-4322-9ffb-4d00035a07fb" />

**Comment by ibhagwan** [comment]
> [@ibhagwan](https://github.com/ibhagwan) sorry to revive this old thread but maybe I'm missing something.
> 
> I have this in my `fzf-lua` configuration:
> 
> files = {
>     fzf_opts = { ['--keep-right'] = '' },
>     winopts = {
>         preview = { hidden = true },
>     },
> }
> But then truncation still seems to happen based on the location of the match:


That’s how fzf works, from `man fzf`:
```
       --keep-right
              Keep the right end of the line visible when it's too long.
              Effective only when the query string is empty.
```

When I miss something in the display I toggle line wrap (default fzf bind is `alt-/`).

**Comment by MariaSolOs** [comment]
@ibhagwan omg how did I miss the 2nd sentence 🤦🏻‍♀️ 

Thank you for the clarification (and patience 😅)
