### ISSUE TITLE
FzfLua doesn't work properly with 'set autochdir = true'. Is this option necessary?

### ISSUE THREAD

**Issue by RayZ0rr** [ibhagwan/fzf-lua#882]
### Description 
Whenever I have `opt.autochdir = true` in my config, fzf behaves incorrectly when opening **multiple** files.

Example :
Say I have the following directory and files structure 
```
$ tree one1
one1
├── one1_file.txt
└── one2
    ├── one2_file.txt
    └── one3
        └── one3_file.txt
```
I open `one1_file.txt` : `nv one1_file.txt` 
Use `:Fzflua files`
Open `one2_file.txt` and `one3_file.txt`. I believe their corresponding paths will be `one2/one2_file.txt` and `one2/one3/one3_file.txt`
But with `opt.autochdir = true`, opening `one2/one2_file.txt` will change the dir to `one2` such that `one2/one3/on3_file.txt` becomes a new file and not the original one.

I have created the following script to check: 
```bash
#! /usr/bin/env bash

mkdir -p ./{one1/one2/one3,two1/two2,three1}

touch one1/one1_file.txt
touch one1/one2/one2_file.txt
touch one1/one2/one3/one3_file.txt

touch two1/two1_file.txt
touch two1/two2/two2_file.txt

touch three1/three1_file.txt

echo "one1" > one1/one1_file.txt
echo "one2" > one1/one2/one2_file.txt
echo "one3" > one1/one2/one3/one3_file.txt

echo "two1" > two1/two1_file.txt
echo "two2" > two1/two2/two2_file.txt

echo "three1" > three1/three1_file.txt
``` 

**My question is whether `autochdir` is a useful option or is it safe to turn off**

**Comment by ibhagwan** [comment]
> My question is whether `autochdir` is a useful option or is it safe to turn off

This is a matter of personal preference, IMHO this option is not useful, it changes neovim’s working directory whenever you switch files/buffers, to me that would be confusing and counter productive.

Nevertheless, this is an easy fix and I’ll make sure this is solved.

**Comment by ibhagwan** [comment]
Btw, the default for the option is `false`, what was the reason you decided to turn it on? What’s the use case for this option?

**Comment by RayZ0rr** [comment]
> Btw, the default for the option is false, what was the reason you decided to turn it on? What’s the use case for this option?

The reason is that I cannot use `:FzfLua files` properly without `autochdir = true`.

Take the above tree structure for example: 
```
$ tree one1
one1
├── one1_file.txt
└── one2
    ├── one2_file.txt
    └── one3
        └── one3_file.txt
```
If open `one2_file.txt` above when I am currently in `one1` dir like,
```
$ pwd
one1
$ nv one1/one2/one2_file.txt
```
then neovim is currently viewing a file in `one2` and the user called it from `one1`
then `:FzfLua files` will show: 
1. with `vim.opt.autochdir = false` :- Shows all the files in `one1` and below (`one2` and `one3`)
2. with `vim.opt.autochdir = true` :- Only the files in `one2` and below (`one3`)

**Comment by ibhagwan** [comment]
I understood the issue from the OP, I’m just not clear why would you enable this option? Why do you need to change the `cwd` with every file?

**Comment by ibhagwan** [comment]
> 1. with vim.opt.autochdir = false :- Shows all the files in one1 and below (one2 and one3)
> 2. with vim.opt.autochdir = true :- Only the files in one2 and below (one3)

`:help aurochdir` and read what this options does, it changes the current working directory, in (2) neovim changes the working directory to `one2` so obviously you’ll be able to see only the files under `one2`, fzf-lua does what it’s supposed to, show the files under **the current working directory**.

Do the same test (with and without `autochdir` and then run `:pwd` and you’ll see the difference.

**Comment by RayZ0rr** [comment]
Yes, I understand what `autochdir` does and what `FzfLua` does.

> Why do you need to change the cwd with every file?

Sometimes I open my code files with `fzf` from my home dir right after I open the terminal (Ctrl-T).

After I open my main code file, I only want to see the files forward.

I have keymaps for `FzfLua  cwd=~`  and another `fzflua project` option. What I am missing is the option, like `ctrl+t` to open files from the directory of the current file onwards.

**Comment by ibhagwan** [comment]
> But with opt.autochdir = true, opening one2/one2_file.txt will change the dir to one2 such that one2/one3/on3_file.txt becomes a new file and not the original one.

As I wrote above, this is an bug and I'll fix it.

> What I am missing is the option, like ctrl+t to open files from the directory of the current file onwards.

Not sure I understand this one, `FzfLua files` opens from the current directory onwards (i.e. using the current `pwd`).

**Comment by RayZ0rr** [comment]
> Not sure I understand this one, FzfLua files opens from the current directory onwards (i.e. using the current pwd).

I didn't say `FzfLua` is working incorrectly. 

 > I understood the issue from the OP, I’m just not clear why would you enable this option? Why do you need to change the cwd with every file?

I was answering to your question on usecase for `autochdir`.

When I open a file( say my main code source file) from my home dir, I want working directory to be that file's directory and  not my home dir.

**Comment by ibhagwan** [comment]
> > Not sure I understand this one, FzfLua files opens from the current directory onwards (i.e. using the current pwd).
> 
> I didn't say `FzfLua` is working incorrectly.
> 
> > I understood the issue from the OP, I’m just not clear why would you enable this option? Why do you need to change the cwd with every file?
> 
> I was answering to your question on usecase for `autochdir`.
> 
> When I open a file( say my main code source file) from my home dir, I want working directory to be that file's directory and not my home dir.

I apologize I misunderstood, having `is this option necessary` in the title confused me.

I’ll fix this issue by forcing the use of full paths when `autochdir = true`

**Comment by asmodeus812** [comment]
I might be wrong, but to me reading the issue, it seems the OP might be using fzf incorrectly. Imo, the appropriate / desired cwd should be always properly specified by the user before picking or as it is atm assumed from the pwd. Maybe there can be a warn for autochdir, forcing full path might be obscuring user/config related issues outside fzflua.

**Comment by RayZ0rr** [comment]
> I might be wrong, but to me reading the issue, it seems the OP might be using fzf incorrectly. Imo, the appropriate / desired cwd should be always properly specified by the user before picking or as it is atm assumed from the pwd. Maybe there can be a warn for autochdir, forcing full path might be obscuring user/config related issues outside fzflua.

It seems you are confused. I repeat again:

**I know how `FzfLua` and `autochdir` works**. With `FzfLua`, some people extend it to have more functions other than the default ones. I have, example:
`FzfLua files cwd=~/.config/nvim` and another I showed [here](https://github.com/ibhagwan/fzf-lua/issues/616)

I also want another one that opens shows files from the current directory of the currently viewing/opened file and its subdirectories. `autochdir` is a convenient option for that but it makes `FzfLua` behave differently when opening multiple files

**Comment by RayZ0rr** [comment]
> I’ll fix this issue by forcing the use of full paths when `autochdir = true`

No worries. If it's a troublesome fix, then leave it. I think a note in README would work.

This is one of my favorite plugins and I would prefer not to burden the dev as much as possible.

**Comment by ibhagwan** [comment]
> No worries. If it's a troublesome fix, then leave it. I think a note in README would work.
> This is one of my favorite plugins and I would prefer not to burden the dev as much as possible.

Not a troublesome fix, nor does this burden me, I’ve been traveling and I’ll fix it when I get a chance.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/ed3c8dea946017eca9835a7150ec85acfc22bb7a

@RayZ0rr, should work now, lmk if otherwise?

**Comment by Akhil-CM** [comment]
@ibhagwan 

Sorry got busy with some work so didn't want to update the plugins.

And yes now its working perfectly.

**Comment by RayZ0rr** [comment]
@ibhagwan 

Sorry got busy with some work so didn't want to update the plugins.

And yes now its working perfectly.

**Comment by ibhagwan** [comment]
> @ibhagwan
> 
> Sorry got busy with some work so didn't want to update the plugins.
> 
> And yes now its working perfectly.

Ty for the updste @RayZ0rr!
