### ISSUE TITLE
Icon color in `git_status` not updated after switching `&bg`

### ISSUE THREAD

**Issue by Bekaboo** [ibhagwan/fzf-lua#893]
### Info

- Operating System: Linux 6.1.54.15.realtime1-2-rt-lts
- Shell: fish
- Terminal: alacritty
- `nvim --version`: NVIM v0.10.0-dev-1224+gdfa8b582a6
- `fzf --version`: 0.42.0 (d471067e)

- [x] The issue is reproducible with `mini.sh`

### Description 

After changing `&bg`, icon color for `git_status` is not updated. Icons colors in other pickers, e.g. `files` works correctly, though.

Related to #855 

Screenshots:

`git_status` picker shows light icon in dark background (correct):

![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/ae8ced96-0e65-4c0e-8150-9e447eb2f9cc)

`git_status` picker shows light icon in light background (incorrect):\
![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/beccf3ec-261e-4ff6-bab9-8952a4c49c37)

`files` picker shows light icon in dark background (correct):

![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/d4b807fc-e4ca-437f-90d1-787eabba4839)

`files` picker shows dark icon in light background (correct):

![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/9ed49aa9-12f8-4caf-a931-a1fdab94d52c)

**Comment by ibhagwan** [comment]
Ty @Bekaboo, wondering why #855 didn’t apply here as well, will take a look.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/0c9ce4b59e05a22d9d6978e102830ca808e8974d

@Bekaboo, should work after an update.

**Comment by Bekaboo** [comment]
@ibhagwan Thanks! Don't know why I missed your message 2 weeks ago.
