### ISSUE TITLE
[Feature] Global configuration for copen and lopen and better lua binding

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#898]
It would be great if we had, similar to the register_ui, the ability to register a function globally which opens the qf or local list, or have it provided in the fzf configuration table, whichever you consider a better approach, as it is right now, it is quite hard to get to the property which is read into **sel_to_qf** action, we have to wrap around the action to update the opts to set the copen or lopen, before calling the original sel_to_qf action. Then instead of using vim.cmd it would be great to have the property be a more friendly lua interface, i.e a function. Not sure where else applicable, maybe in the **set_qflist** action too. 

This is what i am doing right now, seems more cumbersome than necessary, compared to if the configuration was available within fzf's config table instead.
```lua
                ["default"] = function(s, o)
                    o.copen = qf_open
                    o.lopen = lc_open
                    actions.file_edit_or_qf(s, o)
                end,
```

**Comment by ibhagwan** [comment]
Good point, this applies to other options, I'd rather think about making this more robust and future proof as opposed to fixing just the `copen` and `lopen` variants.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/a5858b312bb54ead3584a3cf099b6465be917920

@asmodeus812, for example, modifying both quickfix and location lists to open at the top (globally):
```lua
require("fzf-lua").setup({
  defaults = {
    copen = "topleft copen",
    lopen = "topleft copen",
  },
})
```

**Comment by asmodeus812** [comment]
@ibhagwan great, thanks looks good, two notes, there is a global_resume, not sure if that should also be present in the new defaults table, second,  i was thinking the lopen and copen could also take in a function callback too, since it is more lua friendly than simply putting it in a vim.cmd as it does right now.

**Comment by ibhagwan** [comment]
`global_resume` can be ignored, I’m going to remove it one day, there is no reason to even disable the resume functionality.

> second, i was thinking the lopen and copen could also take in a function 

That’s why I made it so `defaults` can be defined as a function:
```lua
defaults = function()
  return { lopen = … }
end
```

**Comment by asmodeus812** [comment]
Wouldn't it make sense for copen and lopen to be callbacks to avoid raw dogging vim cmd directly. Having the entire table of configs be a function, maybe is overkill. But for copen, it might be useful if we want to run some setup code beforehand and constructing a cmd to do that is kinf of messy or have to be a vim.cmd(lua require(.....)) which is anipattern imo for nvim

**Comment by ibhagwan** [comment]
> Having the entire table of configs be a function, maybe is overkill

Not an overkill, it’s a simple if statement and callback, the only to satisfy everyone as evident by your request to make copen to a function.

> Wouldn't it make sense for copen and lopen to be callbacks to avoid raw dogging vim cmd directly

IMHO it’s not a big deal, this runs once after item selection, I can make the action accept a function if that’s your wish.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/365b55113534ef82f10ca4296fd8ee626fcd1ec1, the callback avoids the `vim.cmd`, do whatever you want with the callback (contains items and options):
```lua
require("fzf-lua").setup({
  defaults = {
    copen = function(sel, o) print(sel[1]) end
  },
})
````
