### ISSUE TITLE
Drawing issue

### ISSUE THREAD

**Issue by gegoune** [ibhagwan/fzf-lua#9]
After upgrading plugins couple of hours ago I have noticed that fzf will only take half of available window. I have removed all my custom settings but it did not help. Here is with empty `setup{}`

<img width="1621" alt="Screenshot 2021-07-20 at 11 14 14" src="https://user-images.githubusercontent.com/69750637/126295327-684f0ec0-ac63-4062-ad5f-a3c14c8b47cc.png">

**Comment by ibhagwan** [comment]
That is strange indeed, I just tried with 3 different nvim versions (my distro, nightly and 0.5 appimage) and I can't reproduce this behavior, does this happen for all other providers too?

Going on a limb here perhaps it's just an empty preview window? what happens if you press `F2`? if that's the case (an empty hidden preview window), I have an idea how to fix it right away.

**Comment by gegoune** [comment]
Yes, all provides, at least all those that I have set up. Unfortunately it is not preview window. for help tags preview does not show up at all, but for olfdiles or files it does show to the size of the list.

**Comment by ibhagwan** [comment]
> Yes, all provides, at least all those that I have set up. Unfortunately it is not preview window. for help tags preview does not show up at all, but for olfdiles or files it does show to the size of the list.

Just to make sure I understand, when a preview window exists, is it able to utilize the bottom half of the fzf window or is the preview now also limited to half the list?

What is the output of `fzf —version` and `nvim —version`? I’ll try to download the exact same versions and see if I can reproduce this.

Also, when you run fzf in the shell, is it able to utilize all the space given to it?

**Comment by gegoune** [comment]
Thanks for all those questions. Especially the last one, which made me remember that I do have `--height=50%` in `FZF_DEFAULT_OPTS` in my shell. This is the culprit, I think you were resetting this var last time I checked, that must have change. Thanks!

**Comment by ibhagwan** [comment]
> Thanks for all those questions. Especially the last one, which made me remember that I do have `--height=50%` in `FZF_DEFAULT_OPTS` in my shell. This is the culprit, I think you were resetting this var last time I checked, that must have change. Thanks!

But the strange thing is, nothing changed... the resetting of `FZF_DEFAULT_OPTS` is there there at [config.lua:5](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/config.lua#L5)

I'm going to try and find out why it's not resetting it properly, will keep you posted.

**Comment by ibhagwan** [comment]
I also have `--height 50%` in my shell's `FZF_DEFAULT_OPTS`, doesn't seem to reproduce the issue, I also tried printing `FZF_DEFAULT_OPTS` before and after the reset and right before any provider call and it works as intended, this issue has me confused, I need to get to the bottom of this.

**Comment by gegoune** [comment]
Ah, that's interesting then. Another possible reason why I am seeing it now is because I was testing out `shell=/bin/sh` for a while and have removed it earlier today as well, so perhaps fzf started reading var from environment (zsh) again? (Just tested it and it is the case, `sh` being `shell` obviously does not see `FZF_DEFAULT_OPTS` from `zshenv`.)

**Comment by ibhagwan** [comment]
Can you run `:lua print(vim.env.FZF_DEFAULT_OPTS)` in nvim and let me know what is the output?
If you're lazy loading the plugin you can run the command before and after calling any provider and seeing the variable is indeed reset and should print `nil`.

**Comment by gegoune** [comment]
Interestingly it returns `nil` in both nvim instances, one that still has shell set to `/bin/zsh` and another with with `/bin/sh`.

**Comment by ibhagwan** [comment]
> Interestingly it returns `nil` in both nvim instances, one that still has shell set to `/bin/zsh` and another with with `/bin/sh`.

Yet on `zsh` it somehow respects `FZF_DEFAULT_OPTS`? Are you certain that’s the issue? If you change height to say 80 it will respect that?

If so the issue might be in the way `nvim-fzf` spawns `fzf` which I’ll look at right away.

**Comment by gegoune** [comment]
It does! Setting it to 80% with zsh as shell makes it only take up 80% of the window!

**Comment by ibhagwan** [comment]
> It does! Setting it to 80% with zsh as shell makes it only take up 80% of the window!

Alright, progress :)

Perhaps the nvim terminal doesn’t respect the `vim.env` options, can you try running `:term` and then `echo $FZF_DEFAULT_OPTS` in it?

Maybe I’ll just add `—height 100%` to the cli args? All other options should be overwritten by `fzf-lua` anyways so this will also fix the issue.

**Comment by gegoune** [comment]
echo in term prints what I have set up in zshenv. I guess overriding it makes sense. Unless there is another problem at play here that would affect more things.

**Comment by ibhagwan** [comment]
> echo in term prints what I have set up in zshenv. I guess overriding it makes sense. Unless there is another problem at play here that would affect more things.

Not sure why your term doesn't respect `vim.env.FZF...`, anyways, in hindsight resetting `FZF_DEFAULT_OPTS` isn't wise and can conflict with fzf in a neovim term or `fzf.vim` plugin.

I just committed the change, `fzf-lua` should basically override any fzf option anyway so it should be fine now, lmk if that works for you?

**Comment by gegoune** [comment]
Yes, it does work with shell set to zsh and 50% set in my shell files. So all good, thanks a log for yet another super quick tunraround!

**Comment by ibhagwan** [comment]
> Yes, it does work with shell set to zsh and 50% set in my shell files. So all good, thanks a log for yet another super quick tunraround!

Ty for the best QA one could wish for :-)

When you get a chance I added loads of LSP functionality, would be interested to hear your opinion.

**Comment by gegoune** [comment]
Didn't have a chance but will report as soon as I have. :)
