### ISSUE TITLE
Error when switching branches with no file present.

### ISSUE THREAD

**Issue by kaihowl** [ibhagwan/fzf-lua#901]
### Info

- Operating System: macOS Ventura 13.5
- Shell: zsh
- Terminal: alacritty
- `nvim --version`: NVIM v0.9.2
- `fzf --version`: 0.42.0 (d471067)

- [x] The issue is reproducible with `mini.sh`

### Description 

Expected behavior: No error when switching git branches directly after starting nvim.

Observed behavior: Error occurred as unconditional `edit!` is called as part of `git_switch` action. (See [here](https://github.com/ibhagwan/fzf-lua/blob/d1ebd68f16d889ef7bea8ecdc89e3b23c1d9bda5/lua/fzf-lua/actions.lua#L572).)

```
[Fzf-lua] fn_selected threw an error: vim/_editor.lua:0: nvim_exec2(): Vim(edit):E32: No file name
stack traceback:
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:179: in function <...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:178>
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I...m/site/pack/vendor/start/fzf-lua/lua/fzf-lua/actions.lua:572: in function 'action'
^I...m/site/pack/vendor/start/fzf-lua/lua/fzf-lua/actions.lua:72: in function 'act'
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:93: in function 'fn_selected'
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:177: in function <...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:176>
^I[C]: in function 'xpcall'
^I...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:176: in function <...nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/core.lua:170>
```

Repro:
- `cd $(mktemp -d)`
- Have a git repo with two branches ready:
  - `git init && touch a && git add a && git commit -m 'init' && git checkout -b otherbranch`
- Launch minimal config
  - `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"`
- Call `:FzfLua git_branches`
- Choose "master" / "main"
- Observe error

Possible fix: Add `silent!` in front of `edit!` [here](https://github.com/ibhagwan/fzf-lua/blob/d1ebd68f16d889ef7bea8ecdc89e3b23c1d9bda5/lua/fzf-lua/actions.lua#L572).

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/dada713c18b117ca7032979d32b9bf325440369d

Ty for the report @kaihowl - should work with the latest commit.
