### ISSUE TITLE
[Question] Can we switch between the commands while the previewer is open?

### ISSUE THREAD

**Issue by SandeepTuniki** [ibhagwan/fzf-lua#903]
### Background
In VSCode, pressing `Cmd+P` opens the search window, which fuzzy searches files. However, starting the search with `@` key switches from searching files to searching symbols within the files.

### Issue
I'm trying to re-create the same flow with fzf-lua. Can we switch between `require('fzf-lua').files()` and `require('fzf-lua').lsp_document_symbols()` after the previewer is open?

I'm presently using two different keymaps for this (and several more for other `fzf-lua` commands). While it works, sometimes I trigger a wrong command, start typing several characters, realize I'm on the wrong command, and hit `<esc>` and redo the whole sequence. Instead, I want to quickly switch between the commands using the same input I already typed. Is there a way to achieve this?

**Comment by SandeepTuniki** [comment]
> You can always open a different fzf-lua interface, unrelated to the previewer.

This can actually solve my problem very easily, if I can access the text within the search field. Is there a way I can trigger a lua function and access the text (typed so far) by pressing a key sequence (say, `Ctrl + S`)?

I imagine the flow as something like this:

1. I open the file search command: `require('fzf-lua').files()` (I use keymap for this).
2. I type some text `foobar`. This triggers a file search within the project.
3. I realise I actually want to trigger a symbol search, so I press `Ctrl + S`, which triggers a custom function.
4. The custom function copies the text `foobar` from the command interface, closes the file previewer, and triggers a new command `require('fzf-lua').lsp_document_symbols()` with the text `foobar`.

Based on the above flow, I need to know how to access text from the command interface. Can you point me on how to do that?

**Comment by ibhagwan** [comment]
> This can actually solve my problem very easily, if I can access the text within the search field

You can always call `require('fzf-lua').get_info()`which also contains the last query text (inspect the output with `vim.print`), also see #765, #508.

**Comment by SandeepTuniki** [comment]
Thanks, @ibhagwan. I'll close this for now. I'll attempt your solution when I get time, and re-open the issue if I have further questions.
