### ISSUE TITLE
Performance regarding closing the fzf-lua window compared to fzf.vim

### ISSUE THREAD

**Issue by araaha** [ibhagwan/fzf-lua#904]
### Info

- Operating System: Arch
- Shell: Zsh 5.9
- Terminal: Alacritty 0.12.3
- `nvim --version`: 0.9.4
- `fzf --version`: 0.42.0

- [x] The issue is reproducible with `mini.sh`

### Description 

Compared to fzf.vim, closing the fzf-lua window takes significantly longer. It is not that clear in the video but there is a significant key press delay. 

https://github.com/ibhagwan/fzf-lua/assets/76860315/0a629169-8bd4-4310-abd6-8e8e3226f22a

**Comment by ibhagwan** [comment]
Are you using `<C-c>` to close the interface?

If so, this might be the reason, due to an upstrea issue https://github.com/neovim/neovim/issues/20726 `<C-c>` is internally mapped to `<Esc>` which waits for the external process to terminate.

If you don't mind a rare hang map you can restore the mapping with:
```lua
local aucmd = vim.api.nvim_create_autocmd

local function augroup(name, fnc)
  fnc(vim.api.nvim_create_augroup(name, { clear = true }))
end

augroup("FzfLuaCtrlC", function(g)
  aucmd("FileType",
    {
      group = g,
      pattern = "fzf",
      callback = function(e)
        vim.keymap.set("t", "<C-c>", "<C-c>", { buffer = e.buf, silent = true })
      end,
    })
end)
```

**Comment by ibhagwan** [comment]
@araaha, take a look at #1091, I'm attempting to solve this with a workaround, if you're still interested in using `<C-c>` and experience the occasional hang, can you try the [trace branch](https://github.com/ibhagwan/fzf-lua/tree/trace) , add the below to your setup:
```lua
require("fzf-lua").setup({
  -- 0: silent mode, no messages will be displayed
  -- 1: display the message only if process kill workaround is applied
  -- 2|true, display all `ctrl-c` keypresses (on normal fzf-lua UI close)
  -- I'm using `1` for testing so I can see the message only if proccess was required to be killed
  nvim_freeze_workaround = 1,
})
```

And monitor `:messages` for something like this:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/1e905299-dd3f-44af-8fca-031bc826d465)

**Comment by araaha** [comment]
Just switched and C-c works without freezing.

**Comment by ibhagwan** [comment]
> Just switched and C-c works without freezing.

I applied some more workarounds lately (namely `foldmethod`, found in the upstream discussion) so this happens a lot less but still happens, I was just able to get it stuck on again by spamming `<C-c>` and unfortunately it seems that killing the job/process doesn't exit the infinite loop.

That said I'm very close to finding a proper "solution" (read: workaround) to the upstream issue.

**Comment by ibhagwan** [comment]
@araaha, I just force pushed another update adding extra safety that tries to end the infinite loop by rasing an lua `error`, I think this will also help so make sure to `pull --rebase` upto commit https://github.com/ibhagwan/fzf-lua/commit/8b90c8fb1467b3727f3f688485ab5ae939baca92.

**Comment by ibhagwan** [comment]
With the latest update, supposedly where it would crash you'd get an error message:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/90408270-1f82-4174-a026-d691fd05893c)
