### ISSUE TITLE
Is there a reference for options??

### ISSUE THREAD

**Issue by stevenroose** [ibhagwan/fzf-lua#905]
On [this page](https://github.com/ibhagwan/fzf-lua/wiki), it says

> To control location of the preview of the preview window (up|down|left|right) look into winopts.preview.horizontal and winopts.preview.vertical respectively.

How do I "look into" these exactly?  I can't find any real reference for variables, I'm just grepping through all pages I can find and it's a real mess.

Currently the split is vertical and the left side, the one that's actually interesting, is super narrow.
So I want to either
- remove the preview
- make the preview appear above or under the actual search
- increase the left column

But I can't seem to find any indication for how to do that..

**Comment by ibhagwan** [comment]
> How do I "look into" these exactly?

That’s a naming convention to look for the variable within the `opts` map structure (look at the defaults section under the README).

To remove the previewer altogether call:
```lua
require("fzf-lua").files({ previewer = false })
```

To start with hidden previewer (press F4 to toggle):
```lua
require("fzf-lua").setup({ winopts = { previewer = { hidden = 'hidden' }} })
```

Vertical, 70% down:
```lua
require("fzf-lua").setup({ 
  winopts = {
    preview   = {
      layout   = "vertical",
      vertical = "down:70%",
    },
  },
})
```

many of the options are derivatives of the binary fzf flags, man fzf where appropriate.

**Comment by Dotrar** [comment]
> To start with hidden previewer (press F4 to toggle)

Can I rebind this? for the old fzf.vim i used `?` which was handier.

is there also a way to collapse the filepath, like what you can do in telescope? ie: maybe just show only 2 letters of each path until the last file name, or just show last file name + directory, etc..

**Comment by ibhagwan** [comment]
The answer is yes to all, please read the README, wiki and issues.

**Comment by stevenroose** [comment]
My issued stemmed from using `skin` and skin documents to have the same CLI flags mentioned, but they don't seem to work. Solved by moving back to fzf.

**Comment by stevenroose** [comment]
I checked the skim CLI help and I used fields that supposedly existed, but they didn't work. So they seem like skim bugs, maybe skim just documents those fields but doesn't support them (yet) or so.

**Comment by ibhagwan** [comment]
> I checked the skim CLI help and I used fields that supposedly existed, but they didn't work. So they seem like skim bugs, maybe skim just documents those fields but doesn't support them (yet) or so.
> 
> EDIT: that debug stuff is helpful though!

Can you paste what’s working for you right now with fzf? I’ll convert it to something that works with skim.

**Comment by ibhagwan** [comment]
Btw, I ditched skim because it’s pretty much a dead project, last year’s development in fzf added a lot of features that made the UX much better, for example, being able to remove/modify entries without restarting the process, compare `git_status` stating changes between skim and fzf and you’ll see what I mean, you can use the skim profile with `:FzfLua profiles`.

**Comment by stevenroose** [comment]
Thanks for the effort. I don't mind too much using fzf instead of skim if it saves me trouble. I just think it's nice to use Rust tools since occasionally I can contribute to them. Thanks for the effort here.

I commented on the skim issue (you actually created) here: https://github.com/lotabout/skim/issues/418 in the hope that the skim devs can look into having it work better with this plugin.

Thanks for the awesome work!

**Comment by ibhagwan** [comment]
Ty @stevenroose, hopefully the project is revived one day.

**Comment by ibhagwan** [comment]
Closing, lmk if ever need more help on this @stevenroose.
