### ISSUE TITLE
Extra dot-slash when using complete_path to complete a file name

### ISSUE THREAD

**Issue by randomizedthinking** [ibhagwan/fzf-lua#906]
### Info

- Operating System: Debian 12
- Shell: zsh
- Terminal: urxvt
- `nvim --version`: v0.9.1
- `fzf --version`: 0.42.0

- [X] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```

No other configuration is needed. Just run the following command under the minimal setup.

```vimrc
:inoremap <c-x><c-f> <cmd>lua require("fzf-lua").complete_path()<cr>
```
</details>

### Description 
When using `complete_path` command to complete a filename, an extra pair of `./` is inserted in the completed filename.

Suppose I would like to complete a filename from `/tmp` directory: `<c-x><c-f>` is pressed after `/tmp`, then select any file as prompted. An extra pair of `./` would be inserted in the completed filename. See the screenshot below for an example. 

![image](https://github.com/ibhagwan/fzf-lua/assets/5283430/8d51c159-19ac-4168-bb06-35aceb7fee66)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/aeab02f60cab6c6caf8060eb183796a0dc030576

@randomizedthinking  - should work now, lmk if otherwise.

**Comment by typhooncamel** [comment]
I too have this problem - an extra `./` added to the path completion. This is with fzf v0.46.0, and neovim v0.11.0. Is there anything I'm missing to avoid this from happening?

**Comment by ibhagwan** [comment]
> I too have this problem - an extra `./` added to the path completion. This is with fzf v0.46.0, and neovim v0.11.0. Is there anything I'm missing to avoid this from happening?

Unless your path starts with `~` or `/` (I.e. full path) or if the already written path cannot be found fzf-lua will attempt enumeration from the current path `./` - this is by design and is not a bug.

**Comment by typhooncamel** [comment]
The thing is this happens also when a path starts with `~` or `/`, so that for example completing a path starting with `/` will then have `/./`.

**Comment by ibhagwan** [comment]
> The thing is this happens also when a path starts with `~` or `/`, so that for example completing a path starting with `/` will then have `/./`.

That shouldn’t happen and is most likely a bug, you can either open a bug or if it’s easily reproducible let me know the exact circumstances when this happens (all the time?), what directory you’re trying to complete? Does it exist? Does the same happen with `~/`?

**Comment by ibhagwan** [comment]
This is what happens when I input `/` and use completion with `C-x C-f`:
![IMG_2394](https://github.com/user-attachments/assets/a2777dd1-92da-4ab7-a275-365b91ea66b9)

In the exact same usecase, does yours return a `./`?

**Comment by typhooncamel** [comment]
This happens all the time, when completing paths that do exist (independently if it's a folder or a file), across different files. The same happens with `~/`, that then becomes `~/./`. I configure the plugin following the README:

```
{
  "ibhagwan/fzf-lua",
  -- optional for icon support
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    -- calling `setup` is optional for customization
    require("fzf-lua").setup({
      vim.keymap.set({ "i" }, "<C-x><C-f>",
      function()
        require("fzf-lua").complete_path() end,
        { silent = true, desc = "Fuzzy complete path" })
    })
  end
}
```
And this is what I get when I input `/`:
![Screenshot from 2024-08-06 13-11-08](https://github.com/user-attachments/assets/06713dbc-b6ac-4bad-8a31-b7681798e6f4)

**Comment by ibhagwan** [comment]
> And this is what I get when I input `/`

This is most likely output from your `fd` command used to enumerate the paths, can you try changing your mapping to `require("fzf-lua").complete_path({ cmd = 'fd --strip-cwd-prefix' })`?

If this the issue I’ll add this argument to the auto-detected command.

**Comment by typhooncamel** [comment]
Now it doesn't complete at all (as in no options are given).

**Comment by ibhagwan** [comment]
> Now it doesn't complete at all (as in no options are given).

Maybe you don't have `rg` or `fd` installed, what's the auto-detected command at the `[DEBUG]` line at the top if you change it to `require("fzf-lua").complete_path({ debug = true })`?

> Should show something like  this:
![image](https://github.com/user-attachments/assets/2eb1952b-3930-4c4f-9f01-c8f42d4eeb1c)

**Comment by ibhagwan** [comment]
I think you may have `fd` installed as `fdfind`, so also try `require("fzf-lua").complete_path({ cmd = 'fdfind --strip-cwd-prefix' })`

**Comment by ibhagwan** [comment]
I'm prerty sure `--strip-cwd-prefix`  is the issue, I pushed https://github.com/ibhagwan/fzf-lua/commit/e9413dc2b6e8ab7f62385c972df1dceba483492d, update and it will be solved without the custom command.

**Comment by typhooncamel** [comment]
Yes, that fixed it, it was `fdfind`, thank you!

**Comment by ibhagwan** [comment]
> Yes, that fixed it, it was `fdfind`, thank you!

Great, ty for the confirmation and debugging :-)
