### ISSUE TITLE
Invalid window ID when using the LSP document symbols finder

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#907]
### Info

- Operating System: Mac OS
- Shell: zsh
- Terminal: kitty
- `nvim --version`: v0.10.0-dev-1351+g28ef4a449
- `fzf --version`: 0.42.0 (brew)

- [ ] The issue is reproducible with `mini.sh`

```lua
require('fzf-lua').setup({
  global_git_icons = false,
  winopts = {
    height = 0.7,
    width = 0.55,
    preview = {
      scrollbar = false,
      layout = 'vertical',
      vertical = 'up:40%',
    },
  },
})
```
</details>

### Description 

When using `FzfLua lsp_document_symbols`, `fzf-lua` sometimes fails and the following error is displayed:
<img width="1276" alt="Screenshot 2023-10-15 at 10 31 33 AM" src="https://github.com/ibhagwan/fzf-lua/assets/62502207/fa00e9b9-d783-489c-9a4a-fc16f5497fcf">
Unfortunately I haven't been able to pinpoint exactly when this happens. Restarting the LSP fixes it, but this started happening recently.

**Comment by ibhagwan** [comment]
This smells related to the recent refactor moving the context table to the core module (amongst other changes), I’ll investigate when I get home (currently traveling).

**Comment by ArtAndreev** [comment]
Also sometimes causes wrong jumps to definition (noticed in window with two splits). The jumps are done like the cursor is in the another split.

**Comment by MariaSolOs** [comment]
> Also sometimes causes wrong jumps to definition (noticed in window with two splits). The jumps are done like the cursor is in the another split.

Yeah... I thought the issue was specific to the symbols finder but it is also happening with LSP go to definition :/

> This smells related to the recent refactor moving the context table to the core module (amongst other changes)

@ibhagwan I tried debugging this a bit yesterday and I guess that we could simply add a check to [`core.CTX`](https://github.com/ibhagwan/fzf-lua/blob/aeab02f60cab6c6caf8060eb183796a0dc030576/lua/fzf-lua/core.lua#L187) to reinitialize the context if the window/buffer are invalid. I was wary of contributing the change though since I'm unsure of what the assumptions of this code are.

> I’ll investigate when I get home (currently traveling).

No worries, as always: Thank you for your amazing work on this plugin <3

**Comment by ibhagwan** [comment]
> I guess that we could simply add a check to [core.CTX](https://github.com/ibhagwan/fzf-lua/blob/aeab02f60cab6c6caf8060eb183796a0dc030576/lua/fzf-lua/core.lua#L187) to reinitialize the context if the window/buffer are invalid

Although this would solve it (more of a workaround) I'd prefer to get to the bottom of this issue, why is the context not refelecting the current window when run from the LSP.

 I have a feeling it's related to the wrapper function and being called from `check_capabilities`, I'll dig into this tomorrow.

**Comment by ibhagwan** [comment]
I gave it some thought, the issue lies in the reset condition of `CTX`:
https://github.com/ibhagwan/fzf-lua/blob/aeab02f60cab6c6caf8060eb183796a0dc030576/lua/fzf-lua/core.lua#L383

When calling it from the LSP code we don't always open the UI and thus the CTX is never cleared, for exmaple when you attempt references on an object that doesn't have any refs you'll see the message `[Fzf-lua] No references found` and the context will never get cleared, if you then switch a window you'll get this error.

I have an idea how to fix this properly which I'll implement tomorrow.

**Comment by MariaSolOs** [comment]
Ohh that makes sense! Let me know if there's any testing/verification I can do to help from my side.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/81a9e6b738095ad8b1aaa27d2a19c2b339caf661

@MariaSolOs - should work now.

**Comment by MariaSolOs** [comment]
@ibhagwan thank you! <3

**Comment by tomtomjhj** [comment]
I'm experiencing similar issue even after https://github.com/ibhagwan/fzf-lua/commit/81a9e6b738095ad8b1aaa27d2a19c2b339caf661

```
E5108: Error executing lua /home/user/apps/neovim/runtime/lua/vim/lsp/util.lua:1987: Invalid window id: 1066
stack traceback:
        [C]: in function 'nvim_win_get_buf'
        /home/user/apps/neovim/runtime/lua/vim/lsp/util.lua:1987: in function 'make_position_params'
        ...e/user/.vim/plugged/fzf-lua/lua/fzf-lua/providers/lsp.lua:367: in function 'fn_contents'
        ...e/user/.vim/plugged/fzf-lua/lua/fzf-lua/providers/lsp.lua:538: in function 'fn'
        ...e/user/.vim/plugged/fzf-lua/lua/fzf-lua/providers/lsp.lua:868: in function 'lsp_references'
        [string ":lua"]:1: in main chunk
```

Specifically this seems to happen when a lsp method times out, then I make new windows (with the same buffer), close old windows, and then run another lsp method.

**Comment by ibhagwan** [comment]
Ty for the report @tomtomjhj, should be taken care of with https://github.com/ibhagwan/fzf-lua/commit/14d34705906e979d94d8033953d40c64d2d96d02.
