### ISSUE TITLE
FzfLua freezes if oldfiles contains a named pipe

### ISSUE THREAD

**Issue by mikesmithgh** [ibhagwan/fzf-lua#908]
### Info

- Operating System: macos
- Shell: bash
- Terminal: Kitty 
- `nvim --version`:
```
NVIM v0.10.0-dev-1364+ga4c4b39d5-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.1696795921
Run "nvim -V1 -v" for more info
```
- `fzf --version`: `0.43.0 (brew)`

- [x] The issue is reproducible with `mini.sh`

Download [testshada.txt](https://github.com/ibhagwan/fzf-lua/files/12920947/testshada.txt) (this contains a file marker on /tmp/named_pipe causing it to be added to `oldfiles`)

```
git checkout 949e9f8
mkfifo /tmp/named_pipe
NVIM='nvim -i testshada.txt' scripts/mini.sh
:FzfLua oldfiles
```
![FzfLua oldfiles](https://github.com/ibhagwan/fzf-lua/assets/10135646/010bba8d-64d4-4d95-913e-dc4c11a6be94)

### Description 

Ok I have a weird one for you 😅

The change on https://github.com/ibhagwan/fzf-lua/commit/949e9f82ccc5431b3fc4e94834dfdbc2c3a1ac3e to check if a file is readable causes oldfiles to freeze if there exists a named pipe in `vim.v.oldfiles`.

I also tested older versions before the commit, and it doesn't freeze initially. But, it does freeze when Neovim attempts to close.

This is a really rare issue that is not likely to occur, I just found it while I was experimenting with named pipes.

### Workaround
Delete the old named pipe or remove the shada file.

**Comment by mikesmithgh** [comment]
@ibhagwan so I think what happened is I opened a file with Neovim `/tmp/named_pipe` for example. Then, I removed it and created it as a named pipe with `mkfifo /tmp/named_pipe`. 

I was playing around trying to see if I could write to a named pipe and read from it inside Neovim. But, gave up and had the left over files hanging out 😂 Users will find a way to break things

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/416b4745dbcfbba92fd9d29cad3f30ece6a6a4f3

@mikesmithgh - should work now.

**Comment by mikesmithgh** [comment]
> [416b474](https://github.com/ibhagwan/fzf-lua/commit/416b4745dbcfbba92fd9d29cad3f30ece6a6a4f3)
> 
> @mikesmithgh - should work now.

Thanks! I confirmed it is working
