### ISSUE TITLE
lsp_definitions selection does now change to buffer

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#91]
Hey there,

I'm experiencing an issue which seems to occur after working on a few buffers.

Once I have a split open, if I do "lsp_definitions" and then select the item in the FZF term that pops up, the buffer does not open. 

If I choose to open in a split with ctrl-v or ctrl-s it all works fine. Maybe its an issue with stealing the full screen buffer?

**Comment by ibhagwan** [comment]
Is there any pattern to this issue that is easily reproducible does this happen randomly?

The LSP actions are exactly the same actions as any other file providers (files, git, grep) which runs `:e <file>` maybe there is something about formatting of the LSP result preventing proper parsing? If you can take a screenshot of the fzf window before you press Enter it would be helpful.

**Comment by ldelossa** [comment]
Let me try to find some pattern at which I can reproduce. Right not it feels somewhat random but I doubt that's the case.

**Comment by ldelossa** [comment]
Hmm, sorry. I cant actually reproduce this (which is a good thing lol). Must have gotten my vim in a weird state.

**Comment by ibhagwan** [comment]
Ty for the update!
