### ISSUE TITLE
Replace hardcoded colors with highlight links (FzfLuaBufNr, etc.)

### ISSUE THREAD

**Issue by TheBlob42** [ibhagwan/fzf-lua#910]
### Description 

Less of an issue and more of a proposal for an enhancement

Against to what seems to be the default for most Neovim users I usually work with a light theme :sweat_smile: 
Unfortunately there are some FzfLua specific highlights that make this hard to work with for certain functionalities especially `FzfLua buffers`

![image](https://github.com/ibhagwan/fzf-lua/assets/6849129/ce35dcf9-722c-4ba5-ba4f-6387ed866dd0)

As you can see the marked elements are basically invisible. The reason is that the respective [highlights](https://github.com/ibhagwan/fzf-lua/blob/85bfacfebe9b10980bd7f0ed4f292fe344877231/lua/fzf-lua/init.lua#L56-L67) are created with certain colors instead of being linked to other highlight groups. My question would if there is a specific reason for this or if you would be open to instead link those highlights as it has been done for all the others? 

I know this can be easily fixed in the user config (which is what I did as a workaround) but I thought this might also be of interest for other light theme users.

**Comment by ibhagwan** [comment]
> The reason is that the respective [highlights](https://github.com/ibhagwan/fzf-lua/blob/85bfacfebe9b10980bd7f0ed4f292fe344877231/lua/fzf-lua/init.lua#L56-L67) are created with certain colors instead of being linked to other highlight groups

This is due to legacy code of how the original highlights were defined (in the config), later to be created as highlight (linkable) groups, for example the top element in your image is actually `FzfLuaHeaderBind`, you can test it with (should appear in red color after the below):
```vim
: hi! link FzfLuaHeaderBind ErrorMsg
```

**Comment by TheBlob42** [comment]
> ```:hi! link FzfLuaHeaderBind ErrorMsg```

I have exactly such "link statements" in my config in order to get better visibility for my theme. Since you mentioned that this is legacy code I would like to ask if this is changeable? To link them to certain Neovim builtin highlight groups by default or would this clash with other parts of the code? Would you be open for a PR with those changes and to discuss which would be the best "default" highlights to link to?

For reference this is what I do to make everything more readable:

```lua
vim.api.nvim_set_hl(0, "FzfLuaBufNr", { link = "Constant" })
vim.api.nvim_set_hl(0, "FzfLuaBufFlagAlt", { link = "Operator" })
vim.api.nvim_set_hl(0, "FzfLuaHeaderBind", { link = "Operator" })
```

**Comment by ibhagwan** [comment]
> To link them to certain Neovim builtin highlight groups by default or would this clash with other parts of the code?

Not sure I understand what you mean, each hl group is already linked by default to a neovim highlight group, for example `FzfLuaNormal` is lined to `Normal`, etc.

https://github.com/ibhagwan/fzf-lua#highlights

**Comment by TheBlob42** [comment]
What about the groups from my previous comment? They are not linked but their own highlights which are hardcoded to a terminal color (and therefore do not change with different colorschemes)

```
:hi FzfLuaBufNr
FzfLuaBufNr    xxx guifg=BlanchedAlmond
```
These are the highlights I am talking about:
- FzfLuaHeaderBind
- FzfLuaHeaderText
- FzfLuaBufName
- FzfLuaBufNr
- FzfLuaBufLineNr
- FzfLuaBufFlagCur
- FzfLuaBufFlagAlt
- FzfLuaTabTitle
- FzfLuaTabMarker

**Comment by ibhagwan** [comment]
> What about the groups from my previous comment? They are not linked but their own highlights which are hardcoded to a terminal color (and therefore do not change with different colorschemes)

I see, IMHO it is even harder  to find groups that will are consistent between colorscheme and satisfy most users and then I’m faced yet even more “how do I customize highlights?” issues, so I went with that seemed most reasonable for a dark theme (which as you pointed out, most users use).

You can never satisfy everyone’s needs that’s why there are customizations.

**Comment by TheBlob42** [comment]
Totally understandable :+1: 

I was about to open an issue with the colorscheme I am using, but I thought it make more sense to tackle this here, so that more colorschemes profit of it. But I absolutely get the point that it is not easy to find the best highlight groups to link to. My suggestion would be to use something very basic like `Normal`, `Operator`, `Keyword` etc. but again I understand if you don't want to tackle as it might make more dark users "angry" :joy:

**Comment by TheBlob42** [comment]
As I said fine with me, thank you for the time and discussion :+1:
