### ISSUE TITLE
wrongly claims `[Fzf-lua] LSP: no client attached`

### ISSUE THREAD

**Issue by dimbleby** [ibhagwan/fzf-lua#913]
### Info

- Operating System: ubuntu
- Shell: bash
- Terminal: tmux
- `nvim --version`: NVIM v0.10.0-dev-1400+gbc850ba2a
- `fzf --version`: 0.43.0 (f5e4ee90)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
        keymap = {
          fzf = {
            ['CTRL-Q'] = 'select-all+accept',
          },
        },
      })
```
</details>

### Description 

I have a keybinding mapped to `require('fzf-lua').lsp_definitions({ jump_to_single_result = true })`.

If I sit on some piece of code and hit that such that it takes me to a definition in some other file, that works fine.  But hitting it again to find a definition in that second file fails:
```
[Fzf-lua] LSP: no client attached
```
but this is not true, as `LspInfo` confirms: `1 client(s) attached to this buffer`

I did some printf-style debugging and I suspect that fzf-lua is losing track of which buffer we are in: `core.CTX().bufnr` [here](https://github.com/ibhagwan/fzf-lua/blob/293e9086f9c546ba50f48a5966b95d450bffa94f/lua/fzf-lua/providers/lsp.lua#L17) is returning 1, though the current bufnr is 2.

this worked prior to 434cacd, but was broken at that commit

**Comment by ibhagwan** [comment]
Ty for the report @dimbleby, an oversight on my end, fixed in https://github.com/ibhagwan/fzf-lua/commit/ac2f7cbe961900ccfbb87858ca8fdb5154f0fab5.

**Comment by dimbleby** [comment]
that was fast!  thank you
