### ISSUE TITLE
Icons rendered small on Kitty due to following nbsp

### ISSUE THREAD

**Issue by Bekaboo** [ibhagwan/fzf-lua#916]
### Info

- Operating System: `Linux 6.1.58-1-lts`
- Shell: `fish`
- Terminal: `kitty 0.29.2` + `tmux 3.3a`
- `nvim --version`: `NVIM v0.10.0-dev-1334+gd2d38858d1`
- `fzf --version`: `0.42.0 (d471067e)`

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

Icon rendered small on kitty terminal due to following nbsp.

See https://github.com/kovidgoyal/kitty/issues/1463, kitty will only render icons as full-width when it is followed by at least on space.

Screenshots:

- On kitty:
    
    ![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/5171d7b1-5192-4c79-b172-bdfd98605334)

- Same tmux pane on alacritty:

    ![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/9428de73-5de6-43b4-9d20-7fbd074afbc9)

Setting `opts.nbsp` to plain space seems to fix this issue, but it will break the `live_grep` finder (e.g. cannot jump to the correct file and location), not sure if that breaks other functionalities.

Tried with `opts.nbsp = ' \xe2\x80\x82'` (space followed by nbsp), but that makes the gap between the icon and the text too large.

Could you help me figure out how can I have full-width nerd font icons on kitty without breaking existing functionalities? Thanks in advance!

**Comment by ibhagwan** [comment]
Take a look at the [default options](https://github.com/ibhagwan/fzf-lua#default-options) section:

```lua
require('fzf-lua').setup {
  -- padding can help kitty term users with
  -- double-width icon rendering
  file_icon_padding = ' ',
}
```

**Comment by Bekaboo** [comment]
Thank you for your assistance! I attempted to adjust the `opts.file_icon_padding`, but encountered a similar issue when setting `opts.nbsp` to `' \xe2\x80\x82'` – the space between the icon and the text appeared slightly too large.

I'm very grateful to @kovidgoyal for addressing this specific case in Kitty! With the recent patch he added, using kitty nightly now allows for a seamless full-width icon display, whether followed by a space or a nbsp. Now setting `opts.nbsp` to `'\xc2\xa0'` solves the issue. 
Setting it other invisible values, e.g. `'\xe2\x80\x82'` (the default nbsp value) does not work, however, but it should be easy to solve.
