### ISSUE TITLE
[Question] Current line vs selected item

### ISSUE THREAD

**Issue by dmy-gh** [ibhagwan/fzf-lua#917]
Hello,
First and foremost, thank you for this amazing tool and all the answers that can be found in the wiki or the existing issues you take time to answer :pray: 

I would like to keep a state of selected items (marked ones due to a `fzf` toggle action) across distinct searches or providers but I can't figure how to differentiate them from the current line depending on the context.

When I select multiple items I can get the selected ones as the first argument of the action and get the current line with `require("fzf-lua").get_info()["selected"]` (which may or not be part of the selection).
The same logic works when only one item is selected and the cursor is on another line, so far so good.
But when there is only one item involved and the cursor is on the same line I can't figure out how to know if the item is selected or not as `fzf` puts the current line into selected if no selection is made.

`fzf` has a `focus` event but no `selected` one on which I could rely to maintain a selected items list.
Is it possible at all or should I implement a custom selection independent from `fzf` one?

Thank you.

**Comment by ibhagwan** [comment]
As you correctly identified, actions use the default fzf mechanism which prints only the selected items **and not the selected item** (unless `--no-multi` is used), run `fzf` in the shell and select multiple items and you'll see what I mean, only the selected items are printed regardless of the selected line.

> `fzf` has a `focus` event but no `selected` one on which I could rely to maintain a selected items list.
Is it possible at all or should I implement a custom selection independent from fzf one?

You can use `focus` with a custom action but the default fzf "field index expression" is set as `{+}` which prints the selected items and **not the selected line**, to achieve what you want you need to set it to `{}` which translates to  the **selected item only**, you can do so in two different ways:

> (1) Using the actions table:
```lua
require("fzf-lua").files({
  actions = {
    ["focus"] = {
      fn = function(sel) print("selected line:", sel[1]) end,
      exec_silent = true,
      field_index = "{}" -- change this to "{+}" to see the difference
    }
  }
})
```

> (2) Using raw args and a custom action
```lua
local shell = require "fzf-lua.shell"
local act = shell.raw_action(function(items)
  print("selected", items[1])
end, "{}") -- changes this to "{+}" to see the difference
require("fzf-lua").files({
  fzf_cli_args = "--bind=" .. vim.fn.shellescape(string.format("focus:execute-silent(%s)", act))
})
```

**Comment by ibhagwan** [comment]
> I may end up pursuing this way if you don't think there is a simpler solution.

Are the purposed solutions I posted not working for your need?

> Also, is it possible to trigger fzf native actions as part of the actions options?

Unfortunately the actions are triggered by the output of fzf **after the process was already terminated**,  however if you use `exec_silent` or `reload` (which don’t wait for termination) you might be able to hack you way with `prefix`, see #807.

Another possible way is via the `keymap.fzf` table which translates into `--bind=`.

**Comment by ibhagwan** [comment]
> I don't see how the focus event is enough to know that a single item is selected or not when applying the default action.
Did I miss something?


If you store the currently selected line (perhaps in the `opts`) and then compare the sited item to the `selected` array of the default action, if both are the same you can conclude a single item was selected no?

> The prefix option perfectly does the job 👍
The previous binding was a suffix but the logic is the same

If a postfix makes more sense I can add an argument for it, lmk.

**Comment by ibhagwan** [comment]
Thanks @dmy-gh, just in case you (or anybody) needs this in the future https://github.com/ibhagwan/fzf-lua/commit/6589bdd872385d120a1eb3cb85e5d15d37621c1d adds a `postfix` option to `exec_silent` or `reload` type actions.
