### ISSUE TITLE
Custom `action` that modifies command parameters

### ISSUE THREAD

**Issue by xiaochuanyu** [ibhagwan/fzf-lua#918]
I'm trying to create a custom `action` for grep (or other commands) that lets you toggle pre-determined parameters but can't figure out how to modify `rg_opts`.
For example, lets say I search something via `grep` and but at some point wants to filter down the results to "non-test Ruby and Typescript files". This translates to adding `-t ruby -t ts -g !**/test/**` in the code base I work on to `rg_opts`.
However, I can't figure out how to modify `rg_opts` inside an `action` as seen here:
```lua
          actions = {
            ["ctrl-g"] = { actions.grep_lgrep },
            ["ctrl-f"] = {
              function(selected, opts)
                -- this below doesn't work
                opts.rg_opts = opts.rg_opts .. " -t ruby -t ts -g !**/test/**"
              end,
              require("fzf-lua").actions.resume,
            }
          },
```

**Comment by ibhagwan** [comment]
When you call `resume` you’re resuming the last used command, it won’t use your new `opts.cmd`, instead call `live_grep` (or grep) with the new command, see #860 for a similar case toggling `.gitignore` for files.

**Comment by xiaochuanyu** [comment]
@ibhagwan thanks for pointing me to the right place.
Based on what I read, I've been able to piece together the following that does what I wanted above (but quite ugly).
It seems to mostly handle switching around between ctrl-g / ctrl-f. Haven't tested this very thoroughly and not sure if I'm using `search` right.
```lua
        local toggle_params_callback = function(_, opts)
          local toggle_opts = " " .. "-t ruby -t ts -g '!**/test/**'"
          local toggle_opts_pattern = vim.pesc(toggle_opts)
          local new_rg_opts
          if opts.rg_opts:find(toggle_opts_pattern) == nil then
            new_rg_opts = opts.rg_opts .. toggle_opts
          else
            new_rg_opts = opts.rg_opts:gsub(toggle_opts_pattern, "")
          end
          local last_query = require("fzf-lua").get_last_query()
          -- not sure how to detect grep vs lgrep
          if opts.prompt:sub(1, 1) == "*" then
            -- "*Rg"
            print("This is live grep .. " .. new_rg_opts)
            require("fzf-lua").live_grep({
              search = last_query,
              rg_opts = new_rg_opts,
              actions = opts.actions,
              debug = true,
            })
          else
            -- "Rg"
            print("This is grep .. " .. new_rg_opts)
            require("fzf-lua").grep({
              search = last_query,
              rg_opts = new_rg_opts,
              actions = opts.actions,
              debug = true,
            })
          end
        end
```
and in `actions`:
```lua
            ["ctrl-f"] = { toggle_params_callback },
```

**Comment by ibhagwan** [comment]
> but quite ugly

Many ways to skin a can, if it works it works :-)

>  not sure if I'm using `search` right

Technically `live_grep` should be using `query` (the propmp test) but both work equally for your use case, you can see the difference if you try both with `grep`, for example: `:FzfLua grep search=pcall query=foo`,  you'd notice `search` is the regex sent to `rg` and `query` is the `--query` argument sent to fzf (and pasted after the prompt).
