### ISSUE TITLE
`shell` registered functions circular buffer (`_MAX_LEN`) size limit

### ISSUE THREAD

**Issue by dmy-gh** [ibhagwan/fzf-lua#919]
- [x] The issue is reproducible with `mini.sh`

### Description 

Trying to circumvent `fzf` initial multi selection behavior I find myself having too much `fzf_cli_args` custom bindings with `shell.raw_action`s.
At some point, starting with the first declared binding, they started not to work as expected anymore.
It seems due to `shell` `_MAX_LEN` being limited to 10 which makes any additional `raw_action` having a `fnc_id` starting back from `1`.

Each of my custom binding declares two `raw_action` in order to also update the `header` after the action is done.
Maybe there is another way to update it that will spare me one `raw_action` per binding?
```lua
local fzf = require("fzf-lua")

opts.fzf_cli_args = "--bind="
    .. vim.fn.shellescape(
        string.format(
            "tab:execute-silent(%s)+toggle+down+transform-header:%s",
            fzf.shell.raw_action(function(focused) update_selected_entries(focused, opts.cwd) end, "{}"),
            fzf.shell.raw_action(function() return get_header() end)
        )
    )
```

If not, is it possible to make the `shell` `_MAX_LEN` configurable?
Or should I look at the problem from a different angle?

Thank you.

**Comment by ibhagwan** [comment]
> If not, is it possible to make the shell _MAX_LEN configurable?

Sue, we can have a global variable for this, I’ll add this next time I make changes.

**Comment by ibhagwan** [comment]
@dmy-gh, update to https://github.com/ibhagwan/fzf-lua/commit/cd3a9cb9ef55933be6152a77e8aeb36f12a0467b and use `vim.g.fzf_lua_shell_maxlen`.
