### ISSUE TITLE
Adding `--sort-files` to `rg_opts` makes `live_grep` fail to filter

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#92]
Adding `--sort-files` to `rg_opts` makes `live_grep` fail to filter. Here's a screencast:

https://user-images.githubusercontent.com/1813121/131958631-428d7df6-585e-4615-85e6-0111ecd0c421.mov

This seems to happen most of the times but not always. It never happens if I don't add `--sort-files` to `rg_opts` though.

**Comment by ibhagwan** [comment]
The reason there are no icons or additional processing of lines with `live_grep()` is due to the fact that after I launch it I relinquish all control to `fzf`, this is due to the way `change:reload` event works in fzf.

Although `fzf-lua` might have something to do with it in (in a roundabout way) I suspect this is a different issue.

Can you run the below script (`chmod a+x` it) and see if you can reproduce, this is almost exactly what `live_grep` does but in the shell (very useful btw if you make this a `zsh` function and call it with a bind...):

```bash
#!/bin/sh
QUERY="$1"
RG_CMD="rg --hidden --column --line-number --no-heading --color=always --smart-case --sort-files -- "
FZF_BINDS="f2:toggle-preview,f3:toggle-preview-wrap,f4:execute($EDITOR {1}),shift-down:preview-page-down,shift-up:preview-page-up,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-f:page-down,ctrl-b:page-up,ctrl-a:toggle-all,ctrl-l:clear-query"
CMD="false "
if [ "$#" -gt 0 ]; then
    QUERY=$(echo $QUERY | sed 's/[\\~$?*|\\[()]/\\&/g')
    CMD="$RG_CMD '$QUERY'"
fi
eval ${CMD} | fzf --border --ansi --layout=reverse --info=inline --multi --height='80%' --delimiter='[: ]' --phony --query="$QUERY" --bind="$FZF_BINDS,change:reload:$RG_CMD {q} || true" --prompt='Rg❯ ' --preview-window='border:nohidden:nowrap:down:45%:+{2}-/2' --preview='bat --style=numbers,changes --color always --highlight-line={2} -- {1}' 
```

Play around with `$RG_CMD` (with and without `--sort-files`) and lmk if this can be reproduced in the shell?

**Comment by ibhagwan** [comment]
I tried reproducing it on my end, `--sort-files` has no effect, let's hope not another one of these voodoo issues on your machine like #89

**Comment by ibhagwan** [comment]
I just had a theory how this might be related to #89… using an action from `nvim-fzf` requires writing to a pipe, perhaps fzf fails to run the preview and then the `change:reload` event croaks and stops working?

We can test this in two different ways which will also help us with #89:

- test with `default_previewer = “bat_native”` (still uses nvim-fzf action but in a different place in the preview command)
- install  [skim](https://github.com/lotabout/skim) (rust fzf), and set `fzf_bin = “sk”` - `skim` doesn’t have `change:reload` but rather uses something called “interactive mode” to achieve the same functionality as `live_grep`


Should be interesting how using `sk` should affect your problems at #89

**Comment by kdheepak** [comment]
I was able to install `skim` but for some reason setting `fzf_bin = "sk"` in my `fzf-lua` setup isn't actually propagating the settings? 

I manually editing `config.lua` to change `fzf_bin =  nil` to `fzf_bin = "sk"` but `files` still using `fzf`. `live_grep` doesn't even load. It just flickers and dies silently without any errors.

When using `default_previewer = "bat"` and changing the config to point to my `~/.config/bat/config` however, `live_grep` always seems to work!

I also tried the `test.sh` script you shared and it always works as expected, with or without `--sort-files`.

**Comment by ibhagwan** [comment]
> I was able to install `skim` but for some reason setting `fzf_bin = "sk"` in my `fzf-lua` setup isn't actually propagating the settings?

It should work, I’m constantly switching back and forth with no problem.


> I manually editing `config.lua` to change `fzf_bin = nil` to `fzf_bin = "sk"` but `files` still using `fzf`. `live_grep` doesn't even load. It just flickers and dies silently without any errors.

That tells me the code doesn’t even recognize you’re on `sk`, if you look at the live grep code you’ll see it should branch to the sk live grep (different command line args) which seem to not happen in your case.


> When using `default_previewer = "bat"` and changing the config to point to my `~/.config/bat/config` however, `live_grep` always seems to work!

My guess is that the previewer somehow breaks the RPC channel and fzf stops reloading the command on query change, this may or may not be related to your other issue.


> I also tried the `test.sh` script you shared and it always works as expected, with or without `--sort-files`.

Ok that confirms my above theory regarding the previewer breaking fzf somehow.

**Comment by ibhagwan** [comment]
This is the function that should run the live grep for `sk` not sure why it doesn’t happen in your case, maybe it couldn’t recognize `sk` in the shell for some odd reason, it has to be verified with `fn.excute`

**Comment by kdheepak** [comment]
I reinstalled `sk` using a different method and it is working now. And `live_grep` works with `sk` with and without `--sort-files` in `rg_opts`. I guess that confirms that `fzf` is the problem here.

**Comment by ibhagwan** [comment]
> I reinstalled `sk` using a different method and it is working now. And `live_grep` works with `sk` with and without `--sort-files` in `rg_opts`. I guess that confirms that `fzf` is the problem here.

Does this also fix issue #89 for you?

What is your `fzf --version`?

**Comment by ibhagwan** [comment]
Now why in the world `--sort-files` make a difference? Is it possible when you `live_grep` the list changes triggering a preview callback which somehow causes this issue, if you can find out which files are the cause I can get to the solution faster.

**Comment by kdheepak** [comment]
I remember seeing it happen when the first result was a license file. I’ll try to reproduce it in the morning.

**Comment by ibhagwan** [comment]
Ok, progress, I was able to reproduce this with relative consistency, I'm still not sure how `--sort-files` plays a factor here but it seems to happen if you open `live_grep()` and start typing really quick before the results show up, I don't know why I even ran an empty string query for the initial `live_grep()` - it doesn't make much sense to display all lines under the project.

Will have a commit soon where if the initial query is empty it will not run anything before you start typing.

**Comment by kdheepak** [comment]
Great!

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/5fcbace5ba7f8af98cbf5a56709de2b7a53e84ec should solve it.

Let me know if that works well for you now?

**Comment by kdheepak** [comment]
Yeah, that seems to work now! Thanks!
