### ISSUE TITLE
octo.nvim error when running "add label"

### ISSUE THREAD

**Issue by mhanberg** [ibhagwan/fzf-lua#920]
### Info

- Operating System: Ubuntu MATE 23.10
- Shell: zsh
- Terminal: Ghostty
- `nvim --version`: v0.10.0-dev-9dc4404
- `fzf --version`: 0.43.0 (0.43.0)

- [ ] The issue is reproducible with `mini.sh` Uses octo.nvim, not sure if applicable

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 

I ran into this error when attempting to add a label to an issue using `octo.nvim`

```
Error executing vim.schedule lua callback: ...azy/octo.nvim/lua/octo/pickers/fzf-lua/pickers/utils.lua:129: attempt to index field 'ansi_colors' (a nil value)
stack traceback:
	...azy/octo.nvim/lua/octo/pickers/fzf-lua/pickers/utils.lua:129: in function 'color_string_with_hex'
	...zy/octo.nvim/lua/octo/pickers/fzf-lua/pickers/labels.lua:28: in function 'cb'
	...ll/.local/share/nvim/lazy/octo.nvim/lua/octo/gh/init.lua:119: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

I'll attempt to get a minimal repro soon

**Comment by ibhagwan** [comment]
This bug stems from the octo.nvim code, not fzf-lua, you need to open this issue in octo.nvim’s repo.

**Comment by ibhagwan** [comment]
@milogert, can you help?

**Comment by milogert** [comment]
Yeah, I can but I won't be at a computer for a couple of days

Once I get to my machine I'd be happy to look at this

**Comment by milogert** [comment]
I have a fix here: https://github.com/pwntester/octo.nvim/pull/450

Sorry for the slight delay!

**Comment by mhanberg** [comment]
Awesome, thanks! You're awesome!
