### ISSUE TITLE
How to enable picker wrap and precision highlight in previewer?

### ISSUE THREAD

**Issue by kapral18** [ibhagwan/fzf-lua#921]
When going through lsp_references into node_modules I see this

![CleanShot 2023-11-06 at 08 31 14@2x](https://github.com/ibhagwan/fzf-lua/assets/1625373/ee40e6c3-943b-4ae7-848b-c31100671ca7)

Usually references that belong to the same filename are grouped below the entry with visible filename which is ok, but sometimes as outlined in the screenshot a new entry is not fully visible, hence  I cannot see the filename because the string is too long.

I would love to tweak it to make it always show the filename and also have an option to wrap the long lines so I can see the full entry in all picker sizes.

Also since most of the times especially in long typescript oneline definitions the grepped word is somewhere within the text noise having the line visually selected is not enough I'd love to have specific word under grep highlighted in the preview window on top of that.

Are these possible in the settings somehow or via some plugin?

Any helpful advice or a direction is welcome. Thank you

**Comment by ibhagwan** [comment]
> I would love to tweak it to make it always show the filename and also have an option to wrap the long lines so I can see the full entry in all picker sizes.

Unfortunately that would be quoite complicated as we're dependent on the options of `fzf` the binary, technically you can "hide" all the entry data either at the start or end of the entry using the `--nth` option that would require code complexity I'd rather avoid ATM.

As for why your filenames aren't showing it's because you added `--keep-right` to your default options:
https://github.com/kapral18/config.nvim/blob/3957c92efd9ad5b86cd8b94463f45c07097eadb4/lua/plugins/fzf.lua#L301

If you remove this option all entries will be aligned by default to the left.

>  wrap the long lines

That's not possible using `fzf`, you're always welcome to attempt to convince the upstream maintainer: https://github.com/junegunn/fzf/issues/2236

**Comment by kapral18** [comment]
@ibhagwan and what about highlighting the specific grep word match? Is it available in some way on your or fzf level?

**Comment by ibhagwan** [comment]
> what about highlighting the specific grep word match? 

The previewer already has the line/column highlighted, do you mean adding a special highlight for word under cursor in the main fzf window?

> Also do you know if it's possible to dynamically toggle keep-right?

Not AFAIK, from the [man page for fzf’s `--keep-right`](https://www.mankier.com/1/fzf#--keep-right):
```
Keep the right end of the line visible when it's too long.
Effective only when the query string is empty.
```

**Comment by kapral18** [comment]
@ibhagwan no I mean for example if you call lsp_references instead of highlighting the occurence of reference in the line it visually highlights the entire lines, and sometimes lines are too long it's very hard to find the exact place of the reference for example in a long nested type on a long line in typescript

**Comment by ibhagwan** [comment]
> @ibhagwan no I mean for example if you call lsp_references instead of highlighting the occurence of reference in the line it visually highlights the entire lines, and sometimes lines are too long it's very hard to find the exact place of the reference for example in a long nested type on a long line in typescript

The cursor will usually be placed at the start of the marched item but I agree this can be improved by highlighting the entire match, I can look into it.

**Comment by ibhagwan** [comment]
@kapral18, this is already happening, the cursor is placed at the match column:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/d93d445b-4efe-42b4-91be-ae233e2b3e79)

You can also press `<F3>` to toggle line wrap:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/6560c744-d7d0-4191-b785-20496eee452c)

**Comment by ibhagwan** [comment]
Btw, to set the previewer to wrap by default (see [default-options](https://github.com/ibhagwan/fzf-lua#default-options) for the full default options list):
```lua
require("fzf-lua").setup({
  winopts = {
    preview = {
      wrap = "wrap",
    }
  }
})
```

**Comment by kapral18** [comment]
@ibhagwan it's not happening for lsp_references. For example here I hit lsp_references on HttpResponse reference and am trying to visually spot it which is hard

![CleanShot 2023-11-13 at 21 37 12@2x](https://github.com/ibhagwan/fzf-lua/assets/1625373/add5a95f-d756-4240-a5b6-f1567cdf65a3)

**Comment by kapral18** [comment]
Same with grep cword or any other action that looks up something under cursor

**Comment by ibhagwan** [comment]
> Same with grep cword or any other action that looks up something under cursor

Probably an issue with your colorscheme highlights, can you try with a different cursor highlight?
```lua
:lua require("fzf-lua").lsp_references({hls={cursor="CurSearch"}})
```

Once you've found the highlight that works best you can add it to your `setup` or link it:
```lua
hi! link FzfLuaCursor CurSearch
```

**Comment by ibhagwan** [comment]
> Same with grep cword or any other action that looks up something under cursor

The cursor hilight location is irrespective to the type of search, looking at your example you can see the `HttpResponse` ref is found at line 172 **column 316** which tells fzf-lua which column to highlight.

**Comment by ibhagwan** [comment]
Looking at your screenshot again it seems you're using `bat` previewer which doesn't support highlighting the correct column, you need to use the `builtin` previewer for that.

**Comment by ibhagwan** [comment]
Comment the below line in your config if you wish to use the builtin previewer:
https://github.com/kapral18/config.nvim/blob/8f1b7cb81f223a986626d82a71cbe42ed4667be6/lua/plugins/fzf.lua#L247

**Comment by kapral18** [comment]
thanks for cues
