### ISSUE TITLE
[query] Is there any way to resume file search?

### ISSUE THREAD

**Issue by Palanikannan1437** [ibhagwan/fzf-lua#923]
### Description 

First of all, thanks for this wonderful plugin, it's absolutely `blazingly fast` and so freaking customisable 🤌🤌

Just wanted to know if there's any way to resume file search,

I tried this, but this doesn't seem to work like it does in live_grep.
`:FzfLua files continue_last_search=true`

Is there any way we could do this?

**Comment by ibhagwan** [comment]
Ty for the kinds words @Palanikannan1437!

You can resume any interface with `:FzfLua resume` but if you last opened interface wasn't `files` that's probably not what you're after.

What you can do instead is enable history for files and then use `ctrl-p` and `ctrl-n` to go back and forth in your search history:
> You can also place `fzf_opts` at the root for "global history"
```lua
require("fzf-lua").setup({
  files = {
    fzf_opts = {
      ["--history"] = vim.fn.shellescape(vim.fn.stdpath("data") .. "/fzf_files_hist"),
    },
  }
})
```

**Comment by Palanikannan1437** [comment]
Ohhh wow, this definitely works for now, thanks so much for the super quick reply!!  

But would it be possible to get a dedicated `resume` for this like for live_grep so that I could map it to a key? Or is it not possible due to some limitation 🤔.

**Comment by ibhagwan** [comment]
> Or is it not possible due to some limitation

No limitation just some code and the fact nobody requested it until now in regards to `files`.

**Comment by Palanikannan1437** [comment]
Ohhh I see, I'm not sure but what's your workflow during this scenario,

1. Say for lsp references,

I want to refactor all the references of a particular variable/function, I currently have to click 

2. While finding files in a monorepo (especially a Next.js monorepo), a lot of file names are similar (page.tsx convention with the new App router), so though the preview window is amazing to differentiate stuff, it's difficult to get it right the first time especially when you're new to the codebase, hence I have to get into the file, debug if this is the correct file, etc and then I'd like the option to explore other files by resuming my previous search.

Now though the `resume` command in fzf-lua is amazing for this, but if I do (1) during exploring the file, then I lose the ability to `resume` my file search and hence I kind of have to remember the file name again and try to find that file by fuzzyfinding, hopefully you get the loop...

Hence I thought having it as an option for all the commands (not just files) like `live_grep` would be an awesome addition...

**Comment by ibhagwan** [comment]
> having it as an option for all the commands (not just files)

That's a good idea but doing it right would require a refactor (to make the store/retrieve code generic) so I'm going to leave this issue open until I get around to it.

In the meantime you can update to https://github.com/ibhagwan/fzf-lua/commit/b1b734a0acc33cd54cdb2b94eab3afa40d7ee894 and use `:FzfLua files resume=true` (`continue_last_search` was previously renamed to the more generic `resume` name).

**Comment by Palanikannan1437** [comment]
Another feature I'd absolutely love is the fact how resume works (for live_grep and the command itself), it'd be amazing if the resume worked in such a way that it could resume at my previous "selection" from the list and not reset the whole thing.

What I mean my this is, if say I left my selection on `src/03....`
<img width="1150" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/73993394/f74c84cf-0fad-4499-aa44-9c81cd825bf6">

On resuming, it resets to the first option...
<img width="1150" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/73993394/fd0fe4cd-c375-429a-96a5-59bc778e4d8e">

Would be amazing if it could resume at the exact same selection...is that a possibility?

**Comment by Palanikannan1437** [comment]
> > having it as an option for all the commands (not just files)
> 
> That's a good idea but doing it right would require a refactor (to make the store/retrieve code generic) so I'm going to leave this issue open until I get around to it.
> 
> In the meantime you can update to [b1b734a](https://github.com/ibhagwan/fzf-lua/commit/b1b734a0acc33cd54cdb2b94eab3afa40d7ee894) and use `:FzfLua files resume=true` (`continue_last_search` was previously renamed to the more generic `resume` name).

That was super quick ⚡, thanks so much for this @ibhagwan 🙌, you're amazing!

**Comment by ibhagwan** [comment]
> it could resume at my previous "selection" from the list and not reset the whole thing

Unfortuntaely that's almost impossible, each time fzf-lua is launched it executes a new `fzf` process which doesn't have options to enable your request and using terminal screen scan would be clunky and not practical so this one will have to wait :-)

**Comment by Palanikannan1437** [comment]
> > it could resume at my previous "selection" from the list and not reset the whole thing
> 
> Unfortuntaely that's almost impossible, each time fzf-lua is launched it executes a new `fzf` process which doesn't have options to enable your request and using terminal screen scan would be clunky and not practical so this one will have to wait :-)

Ohh got it, thanks so much 🙌

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/f32b5c736439d8431b5e16c893a1169ff8a1b3a2

We can close this issue now, resume code was refactored and all providers now support resume with `resume=true`:
https://github.com/ibhagwan/fzf-lua#resume
