### ISSUE TITLE
[feat]: Resume at current selection 

### ISSUE THREAD

**Issue by Palanikannan1437** [ibhagwan/fzf-lua#924]
### Description 

A feature I'd absolutely love is the fact how resume works (for live_grep and the command itself), it'd be amazing if the resume worked in such a way that it could resume at my previous "selection" from the list and not reset the whole thing.

What I mean my this is, if say I left my selection on `src/03....`
<img width="1150" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/73993394/f74c84cf-0fad-4499-aa44-9c81cd825bf6">

On resuming, it resets to the first option...
<img width="1150" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/73993394/fd0fe4cd-c375-429a-96a5-59bc778e4d8e">

Would be amazing if it could resume at the exact same selection...is that a possibility?

**Comment by ibhagwan** [comment]
As I explained in #923, this won't be easily possible in the near future unless fzf (upstream) provides much more information and also enables the user to use said information as input.

Given the (precieved, by me) complexity of doing so in fzf (it can't predict the result set in advance) I don't see it happening anytime soon so I'm going to close this issue (to avoid the clutter).

Feel free to reopen if you learn of new advancements in fzf that enable such behavior.

**Comment by Palanikannan1437** [comment]
That makes a lot of sense, thanks a ton @ibhagwan 😄
