### ISSUE TITLE
Square brackets in folder name do not work

### ISSUE THREAD

**Issue by WolfeCub** [ibhagwan/fzf-lua#925]
### Info

- Operating System: Arch
- Shell: zsh
- Terminal: kitty
- `nvim --version`:  v0.9.0
- `fzf --version`:  0.27.2

- [X] The issue is reproducible with `mini.sh`

### Steps to reproduce

1. Create a folder named `[something]`
2. Create a file inside it with any name
3. Run `:lua require('fzf-lua').files({ cwd = '/path/to/[something]' })`
4. You won't see any files inside of the directory

![image](https://github.com/ibhagwan/fzf-lua/assets/1369773/2444e7b6-47b1-450a-af00-8fcbcb041bbf)
![image](https://github.com/ibhagwan/fzf-lua/assets/1369773/0f9fa52d-63eb-44c4-947f-b8dc1a4baaae)
![image](https://github.com/ibhagwan/fzf-lua/assets/1369773/0d88f10c-2b97-4179-bf3e-aa21bff34282)

### Investigation

After a bit of debugging it seems like the issue is caused by this function: https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/core.lua#L572-L574

Running `str_to_str("/path/to/[something]")` outputs `[[/path/to/[something\]]]` which seems incorrect to me. In addition in looks like `fd` isn't expecting escaped square brackets because deleting the `gsub` entirely seems to solve this specific problem.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/e1046726cf0cedf15ae0ff40537a421b79968c3e

@WolfeCub - should work now

**Comment by ibhagwan** [comment]
Oh, and ty @WolfeCub for the investigation, saved me a bit of time :smile:

**Comment by WolfeCub** [comment]
Amazing! Thanks for the quick turnaround :)
