### ISSUE TITLE
Combining internal nvim lua actions with fzf ones

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#926]
There is something that i have been wanting to do for a while but not sure how it could be achieved. At the moment there are two ways to define bindings, one directly to the fzf binary, and one to intercept by nvim, there is a use case, for example for enable / toggle the preview in fzf, where i would like to first resize the fzf window, before toggling the preview, since by default my non-preview enabled pickers are not as tall, enabling the preview makes it rather useless, the height is not enough to either see the results well or the preview at the same time. Would it be possible to have an fzf nvim action send keys/term keycodes to the fzf binary ? Say we enable the preview for fzf to be c-/ which translates to c-underscore. Then define an fzf  action i.e lua callback to resize the fzf term window and then send term code to fzf to show the preview. 

```lua
        keymap = {
            fzf = {
                ["ctrl-_"] = "toggle-preview",
            },
        },

        actions = {
            files = {
                ["ctrl-_"] = actions.toggle_preview,
            },
            buffers = {
                -- toggle preview callback would first have to resize fzf window, before sending term codes to fzf
                ["ctrl-_"] = actions.toggle_preview,
            },
        },

```
There is something similar being done here `lua/fzf-lua/win.lua:1193` or here `lua/fzf-lua/win.lua:666` which might be a good entry point for resizing, but i was wondering if there is a general way to solve the issue above, to allow the lua bindings to send the term keycodes, for example to manually trigger page/up/down in fzf or scroll down/up entries etc.

**Comment by ibhagwan** [comment]
>  At the moment there are two ways to define bindings

That's because "actions" aren't real bindings, the actions table is only inspected **after the process terminated** , the code then inspects the executed keybind (output by fzf when using the `--expect` flag) only then the selection action function is executed.

The exception is when using `exec_silent` actions which are trnaslated to binds that don't terminate the process:
```lua
local fzf = require("fzf-lua")
fzf.files({
  actions = {
    ["ctrl-_"] = {
      fn = function(items, opts)
        fzf.win.toggle_fullscreen()
        fzf.win.toggle_preview()
      end,
      exec_silent = true,
    }
  }
})
```

**Comment by ibhagwan** [comment]
The `bat` variant will be slightly different as it needs to combine both lua code and an fzf bind action:
```lua
local fzf = require("fzf-lua")
fzf.files({
  previewer = "bat",
  actions = {
    ["ctrl-_"] = {
      fn = function(items, opts)
        fzf.win.toggle_fullscreen()
      end,
      postfix = "+toggle-preview",
      exec_silent = true,
    }
  }
})
```

**Comment by ibhagwan** [comment]
Closing, if this doesn’t solve your issue lmk.

**Comment by asmodeus812** [comment]
@ibhagwan forgot about this issue, but in case somebody is wondering here is how i solved it

```lua
--- define a basic toggle function
local function toggle_preview_win()
    local preview = fzf_lua.win.__SELF()

    local winid = preview.fzf_winid
    local hidden = preview.preview_hidden
    local height = vim.api.nvim_win_get_height(winid)

    -- do whatever you like with the height here
    height = hidden and height * 2 or height / 2
    vim.api.nvim_win_set_height(winid, height)

    preview.toggle_fullscreen()
    preview.toggle_preview()
end

--- add the action to the fzf's actions table
["ctrl-{key}"] = {
  postfix = "+toggle-preview",
  fn = toggle_preview_win,
  exec_silent = true,
}
```
