### ISSUE TITLE
Unexpected behavior when using `ignore_current_line` and `jump_to_single_result`

### ISSUE THREAD

**Issue by starpact** [ibhagwan/fzf-lua#928]
### Info

- Operating System: macos
- Shell: bash
- Terminal: alacritty
- `nvim --version`: v0.9.4
- `fzf --version`: 0.43.0

### Description
Related to https://github.com/ibhagwan/fzf-lua/issues/529, I've been using this feature since then and recently I noticed some weird behaviors.

My setup:
1. `lsp.jump_to_single_result = true` inside setup function
2. Use `fzf.lsp_references({ ignore_current_line = true })`

The unexpected behaviors:
1. When first invoking `lsp_references` at function definition, somtimes the current line is not excluded. But when invoked again, the current line is excluded. This does not always happen, but quite frequently. When `jump_to_single_result` is disabled, this doesn't seem to happen anymore.
2. I used to be able to jump back and forth using `fzf.lsp_references({ ignore_current_line = true })` between function definition and the *only* function call, but now it can not jump back. Only the first jump A->B will succeed, the following B->A seems to become B->B.

**Comment by starpact** [comment]
Just released there is `includeDeclaration`, tried using `includeDeclaration = false` instead of `ignore_current_line = true` and the first issue never happens, great!
The second behavior does not change, but from its name `includeDeclaration = false`, I guess this should be the expected behavior.

All good for me now, just 2 small questions:
1. Is `ignore_current_line` deprecated?
2. Seems that `jump_to_single_result` is not documented, is it recommended to keep using it?
3. May I know why `ignoreDeclaration` is using camel case?

**Comment by ibhagwan** [comment]
> Is ignore_current_line deprecated?

Nope, I’ll investigate the issue and fix it.

> Seems that jump_to_single_result is not documented, is it recommended to keep using it?

Many options are not documented and are found just issues, might be in the Wiki I’m not sure, it’s open edit if you want to add it yourself.

> May I know why ignoreDeclaration is using camel case?

To match the original LSP argument and I think Telesxope also has it defined like that so it’s easier for users coming from Teleadope.
