### ISSUE TITLE
How process only selection right before use?

### ISSUE THREAD

**Issue by akemrir** [ibhagwan/fzf-lua#929]
### Info

- Operating System: EndeavourOS (Archlinux)
- Shell: fish 3.6.1
- Terminal: kitty 0.31.0
- `nvim --version`: NVIM v0.9.4 LuaJIT 2.1.1699392533
- `fzf --version`: 0.43.0 (d3311d9f)

```lua
function Split(s, delimiter)
  local result = {};
  for match in (s .. delimiter):gmatch("(.-)" .. delimiter) do
    table.insert(result, match);
  end
  return result;
end

_G.fif_grep = function(opts)
  local fzf_lua = require 'fzf-lua'
  opts = opts or {}
  if opts.buffer ~= "" and opts.buffer ~= nil then
    opts.prompt = "fif  :'" .. opts.buffer .. "'❯ "
  elseif opts.search ~= "" and opts.search ~= nil then
    opts.prompt = "fif  :'" .. opts.search .. "'❯ "
  elseif opts.buffer ~= "" and opts.buffer ~= nil and opts.search ~= "" and opts.search ~= nil then
    opts.prompt = "fif  :'" .. opts.buffer .. "'  :'" .. opts.buffer .. "'❯ "
  else
    opts.prompt = "fif❯ "
  end
  opts.git_icons = true
  opts.file_icons = true
  opts.color_icons = true
  opts.actions = fzf_lua.defaults.actions.files
  opts.previewer = "builtin"

  -- opts.fzf_cli_args = '-q ' .. vim.fn.shellescape('none l')

  opts.actions = {
    -- ["<bind1>"] = { fn = function(selected) end, reload = true }
    -- ["<o>"] = { fn = require'fzf-lua'.actions.file_edit, reload = true }
    ["default"] = { fn = require 'fzf-lua'.actions.file_edit_or_qf },
    ["ctrl-s"]  = { fn = require 'fzf-lua'.actions.file_split },
    ["ctrl-v"]  = { fn = require 'fzf-lua'.actions.file_vsplit },
    ["ctrl-t"]  = { fn = require 'fzf-lua'.actions.file_tabedit },
    ["alt-q"]   = { fn = require 'fzf-lua'.actions.file_sel_to_qf },
    ["alt-l"]   = { fn = require 'fzf-lua'.actions.file_sel_to_ll }
  }

  local tags = table.concat(vim.opt.tags:get(), ' ')
  local cmd = { "cat", "tags",  "|", "rg", "-v", "'^!'" }
  cmd = table.concat(cmd, " ")
  print(cmd)

  return fzf_lua.fzf_exec(cmd, opts)
end

-- example keymaps
vim.keymap.set("n", ";t", function() _G.fif_grep({ search = "" }) end)
vim.keymap.set("n", "<leader>t", function() _G.fif_grep({ search = "" }) end)
vim.keymap.set("n", ";T", function() _G.fif_grep({ search = vim.fn.expand('<cword>') }) end)
vim.keymap.set("n", "<leader>T", function() _G.fif_grep({ search = vim.fn.expand('<cword>') }) end)
```
</details>

### Description 

How to process lines but only these choosen? To pass only choosen to execution.
When I have > 300.000 tags this transform slows down fzf input very much:

```
  opts.fn_transform = function(x)
    -- 1 tag
    -- 2 filename
    -- 5 line number
    local el = Split(x, "\t")
    local no = Split(el[5], ":")[2]
    return string.format("%s:%s:%s", el[2], no, el[1])
  end
```

**Comment by akemrir** [comment]
I was thinking rather about function which could  convert selection for action.
I would even go without decoration, for speed.
We expect compatible line to be passed down to action, right? It should be in some specific format to execute actions.

**Comment by ibhagwan** [comment]
> I was thinking rather about function which could convert selection for action.

Not sure what you mean, do you mean a custom action? That’s easily achieved via `actions`.

**Comment by ibhagwan** [comment]
Let me know if I understand your issue correctly first:
- You’re using your own `tags` variant (why not use builtin tags btw?)
- You need a custom action to execute a function on the selected output
- Selected entries require processing inside your custom action function 
- You have a performance issue when selecting large amount of items so you’re trying to optimize performance of the custom action?

Does that sound about right?

**Comment by akemrir** [comment]
Ok, for starters. I found that with built in Tags/BTags uses only first tag file, hence the reason of this approach.

Want to have multiple tag files. Some of them are not in current working directory.
I want to jump to source, open in tabs, for current project and to related libraries, when it's not supported by LSP.

Yes I have somewhat custom variant of tag files, because I am using very custom configuration.
But still, this is ctags.

```
Universal Ctags 6.0.0(p6.0.20221218.0), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb 24 2023, 18:05:01
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript, +pcre2
```

I was checking few command combinations for best performance, and on my machine this is the one:

```
cat tags ~/lib/tags | rg -v '^!'
```

When I feed output from it into fzf-lua it gets rendered, but enter to execute action fails because it's not compatible.

When I do transform for fzf-lua, I have performance issues.

**Comment by ibhagwan** [comment]
> When I do transform for fzf-lua, I have performance issues.

That’s why I suggested you do that transform in the external process. However, IMHO that is over complicating things and you’ll also need to optimize your transform function for speed.

> When I feed output from it into fzf-lua it gets rendered, but enter to execute action fails because it's not compatible.

Why don’t you run your transform only **after selection** and then call fzf-lua’s handlers?
Something like:
```lua
local fn_transform_tbl = function(tbl)
  -- format all entires as “fzf-lua compatible”
  return vim.tbl_map(selected, function(x)
    -- your “fn_transform” code goes here
    return string.format(…, x)
  end)
end

opts.actions = {
    ["default"] = function(selected, opts)
      require 'fzf-lua'.actions.file_edit_or_qf(fn_transform_tbl(selected), opts)
    end,
}
```

**Comment by akemrir** [comment]
Ok, here's the status.

I needed to make extra script which is decorating tags on the fly with absolute path to tags file.

![obraz](https://github.com/ibhagwan/fzf-lua/assets/240986/fc87b7d2-da39-4cd1-b1a3-0b58051a6f6f)

When I want to get tags for buffer outside of project, I need to remove path to directory with tags file.

![obraz](https://github.com/ibhagwan/fzf-lua/assets/240986/a19c8736-1427-4557-8fd4-86b0675241d9)

Relevant helper functions:

![obraz](https://github.com/ibhagwan/fzf-lua/assets/240986/b8b99f63-51fd-4486-b200-e03ace6a6285)

Gist with code: https://gist.github.com/akemrir/b1c791e46dccd119e855ed8e0938dfc9

Thanks for your help, your hint worked very well.

**Comment by ibhagwan** [comment]
Looks great @akemrir!

Closing, feel free to reopen if you need more help in this regard.
