### ISSUE TITLE
frecency-like for all commands

### ISSUE THREAD

**Issue by teto** [ibhagwan/fzf-lua#931]
There has been tickets about frecency (https://github.com/nvim-telescope/telescope-frecency.nvim/) - like feature to sort entries by access usage in fzf-lua  but the  outcome was https://github.com/ibhagwan/fzf-lua/issues/748  that doesn't cover all commands (commits/files/buffers).
Now I've seen https://www.reddit.com/r/neovim/comments/17dn1be/implementing_mru_sorting_with_minipick_and_fzflua/ and I believe this approach could be used in fzf-lua for all commands without it being too complex ?

**Comment by ibhagwan** [comment]
This relies on an external utility,`fre`, and is in fact quite simple to add but it does require a decent effort to add globally to all commands and has its own nuances and config and having to support issues with said external utility. Also, why fre, why not zoxide (just an example), or any other utility? You see where this going.

Given how easy this is to achieve with `fzf_exec` I don’t feel this needs be an official part of fzf-lua.

**Comment by ibhagwan** [comment]
FYI: https://github.com/elanmed/fzf-lua-frecency.nvim, wait for https://github.com/elanmed/fzf-lua-frecency.nvim/pull/1 to be merged or use my fork in the meantime.
