### ISSUE TITLE
Make keybinding to change only the preview mode? 

### ISSUE THREAD

**Issue by MadKuntilanak** [ibhagwan/fzf-lua#932]
Hello, can you give me a hint about how I can toggle only the preview window, not the left side?
I want to show my keybindings in preview mode (and yes I know  I can use `--header`, I am not using that)

Right now, I use `fzf_exec` and it works, but I want to change that.
This my binding:
![screenshot_18-Nov-2023_1442](https://github.com/ibhagwan/fzf-lua/assets/151346058/fc23715d-45a3-4d9c-b0b3-48f1981f3912)

Result:
https://github.com/ibhagwan/fzf-lua/assets/151346058/b83ea0c1-7ab9-4de7-be2e-eea2ee8398e2

Any helpful advice is welcome. Thank you 😄

**Comment by ibhagwan** [comment]
May work by adding:
```lua
  fzf_opts = {
    ['--preview-window']='right:99%',
    …
  }
```

Or:
```lua
  winopts = { preview = { layout='horizontal', hoizontal='right:99%' } },
```

Take a look at [man fzf](https://www.mankier.com/1/fzf#--preview-window) for more info on the preview window layout.

**Comment by ibhagwan** [comment]
Another tip I can give you, since your actions aren’t mean to close the interface you can wrap them in `{}` which tells fzf-lua to avoid recreating the window and eliminating the “flash” when you press the action:
```lua
  actions = {
    ['ctrl-y'] = { function() … end }
  }
```

**Comment by ibhagwan** [comment]
Btw, it’s probably easier to add help strings to your custom actions to the `F1` help - have you tried pressing that when fzf-lua is open?

https://github.com/ibhagwan/fzf-lua/blob/03d8c35bf7b0541a877348cefc486dcd02142ec7/lua/fzf-lua/config.lua#L436

**Comment by MadKuntilanak** [comment]
> Another tip I can give you, since your actions aren’t meant to close the interface you can wrap them in `{}` which tells fzf-lua to avoid recreating the window and eliminating the “flash” when you press the action:

I think I missed guiding you or something.
I use `<c-y>` to show key bindings in preview mode.

It was supposed to change the preview mode, not the left side.
I use `fzf_exec` (it works atm), but I think it's wrong to use that.

I want to make it like this. Is that possible?

https://github.com/ibhagwan/fzf-lua/assets/151346058/270a6ff6-6331-494b-8271-6c28b76cb0f8



> Btw, it’s probably easier to add help strings to your custom actions to the `F1` help - have you tried pressing that when fzf-lua is open?


yes, i did

**Comment by MadKuntilanak** [comment]
nvm, I just tried the custom help string; it was so nice! 😆 

btw, how can I change the result in the help string to show me only four?

**Comment by ibhagwan** [comment]
> I think I missed guiding you or something.
> I use <c-y> to show key bindings in preview mode.

I understood that :)

> It was supposed to change the preview mode, not the left side.
> I use fzf_exec (it works atm), but I think it's wrong to use that.

Using another `fzf_exec` call you’re restarting the process, it won’t be doing grep anymore, so you’re correct it’s probably not the right tool for the job.

> I want to make it like this. Is that possible?

 I’ll have to think how to do it, it’s also dependent on the previewer you’re using as the solution would be different for the builtin or an fzf prefiewer (like bat).

> nvm, I just tried the custom help string; it was so nice! 😆
> btw, how can I change the result in the help string to show me only four?

Not possible ATM unless you override the help function completley.

**Comment by MadKuntilanak** [comment]
> Using another `fzf_exec` call you’re restarting the process, it won’t be doing grep anymore, so you’re correct it’s probably not the right tool for the job.
> I’ll have to think how to do it, it’s also dependent on the previewer you’re using as the solution would be different for the builtin or an fzf prefiewer (like bat).

Yup you right, 
My goal is not to lose my left side; I just want to change only the previewer. so I can continue typing when doing grep.

> Not possible ATM unless you override the help function completley.

Yes, next time I figure that out

Thank you for your help and your response @ibhagwan 
Awesome plugin; I'm out now. :)

**Comment by ibhagwan** [comment]
> Awesome plugin; I'm out now. :)

Cheers, closing.
