### ISSUE TITLE
fzf-lua doesn't work appropriately for tags after changing directory

### ISSUE THREAD

**Issue by daedroza** [ibhagwan/fzf-lua#933]
### Info

- Operating System: Ubuntu 22.04
- Shell: bash
- Terminal: gnome-terminal
- `nvim --version`: 0.9.4
- `fzf --version`: 0.38.0

- [YES] The issue is reproducible with `mini.sh`

```lua
require('fzf-lua').setup({
telescope
})
```

### Description 

The tags file is remember relatively the nvim binary. Let's assume the tag is at root directory called ~/Test.

Navigating to various func/method is works.

Change the directory (cwd) using :cd ~/Test/NewDirectory or use vim-rooter.

The tags file is still set and hence we can search for function. However, in the preview it says "Unable to state the file". Attempting to open the file opens empty buffer because I believe it statically check's the path.

This same behavior is not reproduced with original fzf.vim.

**Comment by ibhagwan** [comment]
@daedroza, should work after https://github.com/ibhagwan/fzf-lua/commit/dad2ca35141d9039bb881c3dafbc85a97803e3a9.

**Comment by daedroza** [comment]
Hi @ibhagwan , thanks for quick response.

I updated the plugin with your recent patch however it seems to me that it is not fixed completely.

Test case:

1. Open nvim. Use `:FzfLua tags` to navigate to a file. vim-rooter will automatically change the cwd. Again use `:FzfLua tags_grep_cword`, file preview and navigation works. [PASS]
2. Open nvim. Before using tag functionality, use file picker (`FzfLua files`) to navigate to a file. vim-rooter will automatically change the cwd. Now use `:FzfLua tags` or ':FzfLua tags_grep_cword`, file preview and navigation fails due to wrong path appending/management. [FAIL]

**Comment by ibhagwan** [comment]
On the case which fails can you let me know before and after:
- What’s the path of the file you’re on
- output of `:pwd`
- output of `:lua _G.dump(vim.fn.tagfiles())`
- output of `:lua _G.dump(require'fzf-lua.providers.tags'._ TAGS2CWD)`

**Comment by ibhagwan** [comment]
@daedroza, should work better after https://github.com/ibhagwan/fzf-lua/commit/99684a6c07da13ba49f62cfaf309dbce285247a7 assuming your tags file header contains a `!_TAG_PROC_CWD` directive.

**Comment by daedroza** [comment]
Hmm, I don't have a `!_TAG_PROC_CWD` directive. However, I wonder if we can use `:ts` in combination with this plugin which seems to be more sturdy in usage.

**Comment by ibhagwan** [comment]
> Hmm, I don't have a `!_TAG_PROC_CWD` directive. However, I wonder if we can use commnad `:ts` (from nvim doc) in combination with this plugin which seems to be more sturdy in usage.

I’m not sure how using tag stacks helps in this case?

The issue with solving your specific scenario is the unexpected change of working directory which doesn’t match where the directory where the tags file was created and while I can simply use the parent directory of the `tags` file location this would break other use cases where the tags file is located outside the project, for example, when using vim-gutentags the tags file are generated in a cache outside the project and the current working directory is used as the tags location.

What I’m failing to understand in your use case is why vim-rooter changes the working directory to something other than the project root (coincidentally, where the tags file cwd would match) - shouldn’t vim-rooter detect the project root?

I have a simple solution for you that doesn’t require additional fixes on my end, why don’t you change the mapping for your tags to this:
```lua
:lua require'fzf-lua'.tags({ cwd = vim.fn.fnamemodify(vim.fn.tagfiles()[1], ':h') })
```

**Comment by daedroza** [comment]
> I’m not sure how using tag stacks helps in this case?

`:ts` is not tag stack but tag select (http://neovim.io/doc/user/tagsrch.html).
`:ts` does the binary search on the tag and returns a list of tag to select.

> What I’m failing to understand in your use case is why vim-rooter changes the working directory to something other than the project root (coincidentally, where the tags file cwd would match) - shouldn’t vim-rooter detect the project root?

I work on large code bases (for eg. chromium/android open source project) where each code base is composed of smaller .git code bases. vim-rooter allows me to change to different smaller projects and then use `:FzfLua files` from there.

If you can help me setup :ts <cword> and pipe it out to fzf, that would be super cool. Something similar is done with quickfixlist here https://github.com/AndrewRadev/tagfinder.vim (and maybe but unsure https://github.com/Yggdroot/LeaderF)

**Comment by ibhagwan** [comment]
> :ts does the binary search on the tag and returns a list of tag to select.
> If you can help me setup :ts and pipe it out to fzf, that would be super cool.

This is more of a feature request if we want it done right, it still doesn’t solve the issue of having the correct `cwd` which I provided a simple solution for, have you tried running tags as I suggested below?
```lua
:lua require'fzf-lua'.tags({ cwd = vim.fn.fnamemodify(vim.fn.tagfiles()[1], ':p:h') })
```

**Comment by daedroza** [comment]
> :lua require'fzf-lua'.tags({ cwd = vim.fn.fnamemodify(vim.fn.tagfiles()[1], ':p:h') })

That works appropriately, thanks! The only question was how `:ts` would display and jump appropriately to tags irrespective of the cwd problem.

> This is more of a feature request if we want it done right

The primary ask for this is because grep returns far less results than `:ts` does. `:ts` results which are far more appropriate and accurate to what someone would like to jump. Even the fzf.vim version accurately shows the results closer in the search picker than this.

The primary reason behind this is that the fzf.vim `:Tags` would include the function name in the fuzzy search along with the path. While yours just fuzzy searches the path. The whole point of jumping to the tag is that we are not aware of the path and hence my question for piping `:ts` result into fzf.

Thanks for quick responses!

**Comment by ibhagwan** [comment]
> Even the fzf.vim version accurately shows the results closer in the search picker than this.

Grep as its name suggests does a regex search within the tags file and lets you fuzzy match on top, unless I’m missing something  fzf.vim’s version is equal to `:FzfLua tags`, if you don’t use the grep function you should get the same results per query aa basically all tags are fed into the interface and then fuzzy matched by fzf the binary. The grep version lets you refine the results so you’re matching on a smaller subset (with `ctrl-g` enabling you to go back and forth to further refine the regex).

> The primary reason behind this is that the fzf.vim :Tags would include the function name in the fuzzy search along with the path. While yours just fuzzy searches the path.

FzfLua should also match the tag/function, let me do some testing and make sure it works similarly to fzf.vim’s version.

**Comment by ibhagwan** [comment]
I just did some testing, the results of fzf.vim's are the same, the matching is a bit different due to the formatting of the entries  (fzf-lua has the filename first), for example from tags of my own neovim config:
> `fzf.vim`, matches for `fzf`
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/548c688c-166f-4925-a9cf-c094cb02f520)

> `fzf-lua`, matches for `fzf`
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/67fa3737-fa4d-4979-9df8-6116d96a6c50)

I can see why the results would make more sense matching the tag name before the filename - is that what you mean?

**Comment by ibhagwan** [comment]
@daedroza, I updated the formatting to be better suited for tags, the tag name will now appear first, together with `--tiebreak="begin"` will provide better matching more akin to the fzf.vim version, new format below:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/e6da29ae-f6ae-4f4b-aa71-f8822056b439)

**Comment by ibhagwan** [comment]
> The whole point of jumping to the tag is that we are not aware of the path

Regarding this, if you wish to use `:FzfLua tags` on the names only, without having to search the path, you can do either of the below:
> Excluding path from the search, **still displays the path, but will exclude it from matching**
```lua
:lua require("fzf-lua").tags({fzf_opts={["--nth"]="1,-1"}})
```

> Hide the path from display altogether
```lua
:lua require("fzf-lua").tags({fzf_opts={["--with-nth"]="1,-1"}})
```

**Comment by daedroza** [comment]
> > The whole point of jumping to the tag is that we are not aware of the path
> 
> Regarding this, if you wish to use `:FzfLua tags` on the tag names and code only, without searching the path, you can do either of the below:
> 
> > Excluding path from the search, **still displays the path, but will exclude it from matching**
> 
> ```lua
> :lua require("fzf-lua").tags({fzf_opts={["--nth"]="1,-1"}})
> ```
> 
> > Hide the path from display altogether
> 
> ```lua
> :lua require("fzf-lua").tags({fzf_opts={["--with-nth"]="1,-1"}})
> ```
> 
> > If you wish to **display tag names only** (hide the line of code where it was found)
> 
> ```lua
> :lua require("fzf-lua").tags({fzf_opts={["--with-nth"]="1"}})
> ```

Thanks these all work great. Just few more questions now that we're close to what we want.

- There are few differences in how search results are shown between fzf.vim and fzf-lua. fzf.vim makes sure the results are the top. Is there some setting I'm missing to make this work?

### fzf.vim
![Screenshot from 2023-11-22 16-59-26](https://github.com/ibhagwan/fzf-lua/assets/19841386/390be9cf-e086-4592-9977-cad69b1fa5b1)

### fzf-lua
![Screenshot from 2023-11-22 16-59-03](https://github.com/ibhagwan/fzf-lua/assets/19841386/084bf575-ee1e-4073-830d-d16ed2fe44fe)

**Comment by ibhagwan** [comment]
> There are few differences in how search results are shown between fzf.vim and fzf-lua. fzf.vim makes sure the results are the top. Is there some setting I'm missing to make this work?

You’re comparing **two different approaches**, in your example using fzf.vim you’re just opening tags and then using fuzzy matching for `ConnectivityManager`, if you note the info line says `3089/1244224`, that means roughly 3k matches out of 1.2m tags.

You will have similar results with fzf-lua if you use `:FzfLua tags` and input `ConnectivityManager`, or you can pre-input the query with `:FzfLua tags query=ConnectivityManager`.

In your example with fzf-lua you’re using the grep version which uses only a subset of the tags, you’re using only tags that already meet the regex `ConnectivityManager`, that’s why the info line says `1087/1087`, you’re now only fuzzy matching on 1k results **which is significantly faster in large projects**, if you press `ctrl-g` you can further refine the regex (for example change it to `Connectivity.*` and see what happens, then press `ctrl- g` to fuzzy match on top (and so forth until you get to the result you want).

If you wish to prefil queries (and not grep regexes) **do not use tags_grep**, you can easily create a mapping for the word under cursor with:
```lua
:lua require("fzf-lua").tags({ query = vim.fn.expand("<cword>") })
```

Compare the above with `tags_grep_cword` and you’ll understand the difference, try them both on projects with huge tags file (e.g. Linux kernel) and you’ll see the performance difference of fuzzy matching millions of results vs reducing the result set first with `grep`.

All of this also applies to grep vs live grep, and grep_project, once it all clicks you’ll be golden.

**Comment by ibhagwan** [comment]
Highly recommend reading https://github.com/ibhagwan/fzf-lua/wiki#grep-vs-live-grep and also playing with the `debug=true` option to understand what's going on under the hood, all `tags_grep_xxx` variants don't exist in fzf.vim, they aren't meant to replace the classic approach of **opening all tags and then fuzzy matching**, these are additional (very powerful) tools that need to be used when approperiate.

**Comment by ibhagwan** [comment]
> Can I use nth and with-nth together?
> For example, I would like to display first, second and fourth column however would like to search only in first column.

Both these options are controlled by fzf the binary, my hunch says what you’re asking is possible, just try it, if not we’ll need to make a feature request upstream.

> I also found that moving away from fuzzy to regex and coming back reset's --nth parameter sadly.

I’ve been working on a refactoring on how resuming options work, this should also solve this issue, code is still WIP but close to being finalized (just missing intensive testing by me) - can you try it out and lmk if it solves  the nth persistence?
https://github.com/ibhagwan/fzf-lua/tree/resume_refactor


> Additionally, the second 2nd column which is the path column has ":" appended to it, but in my tag file it isn't.
> This is what I'm using, fzf_opts={["--with-nth"]="1,2", ["--nth"] = "4,1,2"}, am I doing something wrong? > Additionally it formats it badly (just adds to the search list for one search result even though in tag file it's not present, weird...)

Not sure what you mean, can you post a screenshot of what you’re describing?
At the end of the day it’s just string split by certain delimiters and printing the spec fields.

**Comment by ibhagwan** [comment]
> Hmm, with :FzfLua tags, ctrl+g resets the results order

Pressing `ctrl-g` runs a new `rg` command, it’s not going to be the same result order, you can see the command with `debug=true`.

> then after that doing ctrl+g to go back to fuzzing resets the searching query.

This is by design, first time moving from tags (or grep) to the live version (by pressing ctrl-g) uses the fuzzy matching query as the regex, it used to have a first empty search term but users found it confusing so made the exception for the first switch.

> However, comparing that with :FzfLua grep, this issue is not seen.

The behavior should be the same, you’re probably starting from `live_grep`, try this:
- Start from `tags` or `grep` input `foo` in the prompt
- press ctrl-g to switch to live, prompt should transfer to live and display `foo`
- press ctrl-g to switch to fuzzy, **prompt should be empty**, search header should display `foo`
- input `bar` and press ctrl-g to switch to live, prompt should display `foo`
- press ctrl-g to switch to fuzzy, prompt should display `bar`, search header should display `foo`


> I understand fzf's "nth/with-nth" uses delimiter, however when I use 4th column to show it still shows 1st and 2nd column only (which is method and file path)

Assuming tags output that looks like this:
```
fzf_fn        lua/plugins/fzf-lua/cmds.lua:        /^  local fzf_fn = function(cb)$/
```

There is no field that denominates that object type, while we can add space to the delimiter and maybe use the last field with `-1`, it probably won’t be consistent, you can try playing around with it, use `--with-nth` first to see which fields match which part of the line.
