### ISSUE TITLE
Default keybindings and selecting multiple files in picker

### ISSUE THREAD

**Issue by daedroza** [ibhagwan/fzf-lua#936]
Hello,

I want to understand how to do the following:

1. Select/unselect new files using <tab> and <shift-tab> and quickly open them instead of opening them in quickfixlist.
2. Remove all keybindings and set <tab>, <shift-tab> (for selecting/unselecting) and <ctrl-t> (toggle-preview).

			keymap = {
				builtin = {
					["<c-t>"] = "toggle-preview",
				},
				fzf = {
					["ctrl-t"] = "toggle-preview",
		      -- ["shift-tab"] = "toggle+up",
		      -- tab = "toggle+down",
				}

This is what I tried to do, but <ctrl-t> opens new tab.

**Comment by ibhagwan** [comment]
First take a look at all default actions/binds:
https://github.com/ibhagwan/fzf-lua#default-options

>1.  Select/unselect new files using and and quickly open them instead of opening them in quickfixlist.

Copy `actions.files` to your setup call and change `file_edit_or_qf` to `file_edit`.

>2. Remove all keybindings and set , (for selecting/unselecting) and (toggle-preview).

Copy the keymap table (entirely) into your setup and modify the binds to whatever you want, the reason why to copy entirely is in the comments:
```
    -- These override the default tables completely
    -- no need to set to `false` to disable a bind
    -- delete or modify is sufficient
```

**Comment by daedroza** [comment]
Thanks! @ibhagwan , it works!

**Comment by ibhagwan** [comment]
Ty for the update @daedroza
