### ISSUE TITLE
[feature request] Search in Directory with a nice intermediate UI

### ISSUE THREAD

**Issue by Palanikannan1437** [ibhagwan/fzf-lua#938]
## Description 

This one thing would really help a lot, currently I know that to search files in a directory we can do `lua require('fzf-lua').files({cwd="/mydir/"})` and for live grepping `lua require('fzf-lua').live_grep({cwd="/mydir/"})`

But with this I'd have to either hardcode mydir or type it again and again,

Would be awesome if it was possible to launch a fzf-lua command such that it first let's me choose a directory via directory search and then search files inside it/live grep inside it in the next step.

**Comment by ibhagwan** [comment]
How about your own customization?

> Uses `fd` but can be adjusted for `find`
```lua
_G.live_grep_cwd = function()
  require('fzf-lua').fzf_exec('fd -type d', {
    actions = {
      ['default'] = function(sel, opts)
        require('fzf-lua').live_grep({ cwd = sel[1] })
      end
    }
  })
end

-- you can then call it with
_G.live_grep_cwd()
```

**Comment by ibhagwan** [comment]
> Also, I wanted to understand your workflow with fzf-lua and quickfix list, I recently came across how well fzf-lua can play with the quickfix list, how do you generally use the quick fix list in your day to day work in vim?

I mostly use the quick fix list for refactors and global search and replace.

**Comment by ibhagwan** [comment]
> How does this refactor workflow look like exactly?

I would first find which places need the refactor either with live_grep/ctrl-g or with lsp_refs, etc and then traverse the locations with `]q` and `]q` which I mapped to :cnext/:cprev, bonus points if it’s a simple refactor I would create a vim macro and apply it to all lines with `:cdo normal @q`
