### ISSUE TITLE
`live_grep` prompt is just `*` if `*` is first char passed to `prompt`

### ISSUE THREAD

**Issue by xiaochuanyu** [ibhagwan/fzf-lua#940]
### Info

- Operating System: OSX
- Shell: zsh
- Terminal: iTerm
- `nvim --version`:  v0.9.4
- `fzf --version`: 0.32.1

- [x] The issue is reproducible with `mini.sh`

### Description 
Very minor issue where if you do this:
```
:lua require("fzf-lua").live_grep({prompt="*hah"})
```
Results in just `*` as prompt:
<img width="302" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/1718745/5088ee5f-b6ea-407b-87fe-59c6b123f254">
But expected `*hah` to be the prompt.
Not reproducible with `grep`.
Not reproducible after reverting to commit before f32b5c736439d8431b5e16c893a1169ff8a1b3a2.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/f32b5c736439d8431b5e16c893a1169ff8a1b3a2 - @xiaochuanyu , should work as previously now.
