### ISSUE TITLE
Easy way to set `--color=16`

### ISSUE THREAD

**Issue by cbarrete** [ibhagwan/fzf-lua#943]
### Info

- Operating System: NixOS 23.11
- Shell: bash
- Terminal: alacritty
- `nvim --version`: v0.9.4
- `fzf --version`: 0.44.1

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
   winopts = { fullscreen = true }
})
```
</details>

### Description 

As far as I can tell, there is no way to pass `--color=16` to FZF. That would be very convenient to have a "good enough" colorscheme without setting the `fzf_colors` configuration option.

One possible solution would be to make `fzf_colors` accept a string, which would be used as a `BASE_SCHEME` in fzf parlance. I suppose that just making `M.create_fzf_colors` return `fzf_colors` if it is a string would work.

**Comment by cbarrete** [comment]
I missed that somehow, thanks!
Somehow I get different colors than when running fzf in bash with the same `--color`, but that's probably unrelated.

**Comment by ibhagwan** [comment]
> I missed that somehow, thanks! Somehow I get different colors than when running fzf in bash with the same `--color`, but that's probably unrelated.

Check if terminal gui colors is enabled with `:lua print(vim.o.termguicolors)` and explore your neovim colorscheme terminal colors (0-15) with `:lua print(vim.g.terminal_color_0)`.
