### ISSUE TITLE
[Feature Request] lsp actions preview

### ISSUE THREAD

**Issue by jqhr** [ibhagwan/fzf-lua#944]
Like [actions-preview.nvim](https://github.com/aznhe21/actions-preview.nvim),
But this plugin only support telescope.
FzfLua has its own lsp code action provider.
Why not provide preview for code action?

**Comment by ibhagwan** [comment]
> FzfLua has its own lsp code action provider.

It’s a legacy provider that currently only calls the `lsp.buf.code_actions` while making sure fzf-lua is registered for `vim.ui.select` as its interface.

> Why not provide preview for code action?

IMHO the beneift here is pretty minimal and based on my previous work with code actions the maintenance overhead is bigger than just implementing this, every LSP has its own quirks (jdtls, etc) which can complicate things so I posted against implementing this myself.

If you wish to implement this yourself and submit a PR I’ll gladly accept it.

**Comment by jqhr** [comment]
I could submit a pr, but obviously it may bring many break changes. You know, I just want a simple point. So I submit an issue rather than pr

**Comment by ibhagwan** [comment]
> I could submit a pr, but obviously it may bring many break changes. You know, I just want a simple point. So I submit an issue rather than pr

It won’t bring breaking changes, a previewer is an addition which can always be disabled/hidden by default, I you wish to PR this we can work on it together.

**Comment by ibhagwan** [comment]
@jqhr, don’t worry about if if you don’t feel Ike submitting a PR, I’ll do it myself when I get some free time.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/b3b05f9d438736bb1f88aa373476753ddf83f481

@jqhr, this commits adds 2 new previewers, the default is `codeaction`:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/e53d603c-5fab-406e-8f66-1c50efcebc38)

If you have `git-delta` installed I recommend changing the default to `codeaction_native` for a highly pleasing diff display:
> `:FzfLua lsp_code_actions previewer=codeaction_native`
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/be77b524-8983-4507-a157-2c486d191da1)

**Comment by jqhr** [comment]
Great!
Ty

**Comment by MariaSolOs** [comment]
This is very nice indeed! I just tweaked my config and I'm quite happy with the result :)
<img width="1512" alt="Screenshot 2023-12-10 at 2 15 56 PM" src="https://github.com/ibhagwan/fzf-lua/assets/62502207/bee1bb8f-54f0-4733-ae84-8f8a61c13833">

In case anyone wants to use it as inspiration, [here](https://github.com/MariaSolOs/dotfiles/commit/209c4a689f593ee871eb8fd14e02470368ccebd5) is the commit where I added this to my dotfiles!

**Comment by ibhagwan** [comment]
> This is very nice indeed! I just tweaked my config and I'm quite happy with the result :) <img alt="Screenshot 2023-12-10 at 2 15 56 PM" width="1512" src="https://private-user-images.githubusercontent.com/62502207/289390200-bee1bb8f-54f0-4733-ae84-8f8a61c13833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDc2MjcsIm5iZiI6MTcwMjI0NzMyNywicGF0aCI6Ii82MjUwMjIwNy8yODkzOTAyMDAtYmVlMWJiOGYtNTRmMC00NzMzLWFlODQtOGY4YTYxYzEzODMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDIyMjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MmI1MmFiOWI0YWFiMGVmNTUxMmRmZWZiYTJkMTU5ZGIyYzI3ZDNkYTZhYmZhMGM1NjU5N2MwYmI5ZjUyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ot_aT3bSoZVIe9RSUH4Q21w8svo_SWcKbTjtfkXpik">
> 
> In case anyone wants to use it as inspiration, [here](https://github.com/MariaSolOs/dotfiles/commit/209c4a689f593ee871eb8fd14e02470368ccebd5) is the commit where I added this to my dotfiles!

Looks great @MariaSolOs!

**Comment by mikesmithgh** [comment]
Awesome work @ibhagwan ! and thanks for the inpsiration @MariaSolOs :) 

![fzf-lua-code-action](https://github.com/ibhagwan/fzf-lua/assets/10135646/0ab1135b-d7d9-409c-9db4-76f365f6617c)

**Comment by ibhagwan** [comment]
Very cool color scheme / setup @mikesmithgh :)

**Comment by xaviduds** [comment]
hey, @ibhagwan , so probably a noob issue, involving document/workspace, but as i tried to implement it i got this error message below. I didn't find any source that illuminated my doubt of 'document/workspace edit error' online. I have fzf and delta correctly installed. Do you know what might be the problem?

![screenshot](https://github.com/user-attachments/assets/43be2897-1386-493b-8658-5fe7ef1cb13c)

**Comment by ibhagwan** [comment]
> Do you know what might be the problem?

The messages is pretty self explantory, the LSP has to response with a "documentEdit" and then fzf-lua can query "what are the edits" and display the diff, if for this specific action there's no document edit response than there's no diff.
