### ISSUE TITLE
Allow registering custom actions

### ISSUE THREAD

**Issue by ArtAndreev** [ibhagwan/fzf-lua#946]
### Description 

I set `files` picker not to show hidden files (`files.fd_opts = "--color=never --type f --follow"`). Now I want to define a custom action that toggles hidden files like `actions.toggle_ignore` does. I tried hacking config, but actions definitions are local (`fzf-lua.core`). It would be useful to register new actions in a non-hacky way via some public function.

**Comment by ibhagwan** [comment]
What do you mean registering? You want it to be part of the `actions` module?

If you want to set the help string for F1 that’s already possible via `config.set_action_helpstr`.

In any event, I’m planning a revamp of the actions/keybinds that will make it more flexible, not sure when I’ll get to it though.

**Comment by ArtAndreev** [comment]
Yeah, I just want a flexible way to define my own actions that modify opts of called fzf.

**Comment by ibhagwan** [comment]
Have you tried the below? Why does it have to be `registered`?
https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-acts

**Comment by ArtAndreev** [comment]
I haven't seen this, it works, but there are some drawbacks of this method:

1. A missing tooltip about a keybinding, `actions.toggle_ignore` has one. Because of this tooltip I searched for code that "registers" this action and wanted the same behavior for mine.
2. Fzf-lua popup is redrawed entirely, not only content, so it flickers.
3. Tooltip for `toggle_ignore` is changed, I might use `_hdr_to` in a wrong way.
4. It seems like I use some private API with underscores, not much stable.

The code:

```lua
{
  files = {
    fd_opts = "--color=never --type f --follow",
    actions = {
      ["ctrl-g"] = { actions.toggle_ignore },
      ["ctrl-b"] = function(_, opts)
        local utils = require("fzf-lua.utils")

        local o = { resume = true }
        local flag = opts.toggle_hidden_flag or "--hidden"
        if not flag:match("^%s") then
          -- flag must be preceded by whitespace
          flag = " " .. flag
        end
        if opts.cmd:match(utils.lua_regex_escape(flag)) then
          o._hdr_to = false
          o.cmd = opts.cmd:gsub(utils.lua_regex_escape(flag), "")
        else
          -- signals "core.set_header" to set the correct "to" header
          o._hdr_to = true
          o.cmd = opts.cmd .. flag
        end
        opts.__ACT_TO(o)
      end,
    }
  }
}
```

**Comment by ibhagwan** [comment]
> A missing tooltip about a keybinding, actions.toggle_ignore has one. Because of this tooltip I searched for code that "registers" this action and wanted the same behavior for mine.

Registering headers is not exposed ATM, more so, registering a “toggle” action is a bit more involved and before said refactor won’t be dealt with automatically, use `fzf_opts` with `--header` to set it to whatever you want.

> Fzf-lua popup is redrawed entirely, not only content, so it flickers.

Wrap the action in a table and it won’t close the interface and flicker:
```lua
  ["ctrl-b"] = { function(_, opts) … end },
```

> Tooltip for toggle_ignore is changed, I might use _hdr_to in a wrong way.

Use `fzf_opts = { ['--header'] = 'foo' }` to manually set the header instead.

> It seems like I use some private API with underscores, not much stable.

Because it’s not meant to be used :)

**Comment by ArtAndreev** [comment]
Well, using fzf `--header` makes things more hard to configure.

Anyway, thanks for advices and help! I've almost got what I wanted, looking forward for new API of configuring actions :)

**Comment by ibhagwan** [comment]
> Well, using fzf `--header` makes things more hard to configure.
>
> Anyway, thanks for advices and help! I've almost got what I wanted, looking forward for new API of configuring actions :)


Planning on a consolidated binds table combining both fzf and neovim binds, will keep you posted when that happens :)

**Comment by ArtAndreev** [comment]
Thanks)
