### ISSUE TITLE
Failed assertion when using `FzfLua lsp_code_actions`

### ISSUE THREAD

**Issue by MariaSolOs** [ibhagwan/fzf-lua#947]
### Info

- Operating System: Arch Linux
- Shell: Fish
- Terminal: Wezterm
- `nvim --version`: v0.10.0-dev-1793+g808fbe67a
- `fzf --version`: 0.44.1

- [ ] The issue is reproducible with `mini.sh`

_This issue requires an LSP setup with `lua_ls`, `nvim_lspconfig` etc, and hence isn't exactly minimal. I'm still deleting the setup section, since I'm using the `fzf-lua` defaults in this bug report._

That being said, if this isn't reproducible in other people's environments I'll provide a proper minimal configuration and/or close this issue and debug my own setup.

### Description 
1. Assumming an LSP setup including `lua_ls`, create a `lua` file with the following content:
```lua
local x
```
2. Place the cursor over the unused variable and run `:FzfLua lsp_code_actions`.

Expected result: For `fzf-lua` to list available code actions (with a preview if the code action provider supports it).

Actual result:
<img width="1512" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/62502207/fa56c1f8-28a3-4cba-ad67-819e6a16480b">

**Comment by ibhagwan** [comment]
Strange, this is the first line of code in the equivalent runtime code:
https://github.com/ibhagwan/fzf-lua/blob/4fae64e4305fbc062455833a5d4cd32435f09e31/lua/fzf-lua/previewer/codeaction.lua#L138

Does this happen only with `: FzfLua lsp_code_actions`? What happens if you run `:FzfLua register_ui_select` and then call `:lua vim.lsp.buf.code_action()`?

**Comment by ibhagwan** [comment]
One thing I forgot to ask is what version of `lua_ls` are you using and are you on the latest commit of fzf-lua?

Btw, in the meantime, you can always disable the previewer with `:FzfLua lsp_code_actions previewer=false`.

**Comment by MariaSolOs** [comment]
@ibhagwan same results :/
I debugged this a bit and I think I understand what's happening: [`get_client_by_id`](https://neovim.io/doc/user/lsp.html#vim.lsp.get_client_by_id()) expects an integer parameter, but while debugging this I see that the entire context parameter is being passed:
<img width="1512" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/62502207/f810c021-328c-477e-92c7-33ed13212afe">

**Comment by ibhagwan** [comment]
> but while debugging this I see that the entire context parameter is being passed:

I’m confused, why would this happen? This parameter is relayed directly from `vim.ui.select`.

Just tested it with lua_ls 3.7.3 and it works as expected with the same set of code actions:
![IMG_1717](https://github.com/ibhagwan/fzf-lua/assets/59988195/ae9aa676-f3de-4508-9df1-c65ce4c2912e)
![IMG_1718](https://github.com/ibhagwan/fzf-lua/assets/59988195/95716e32-32d5-4494-b9fd-4f3454c6479d)

**Comment by MariaSolOs** [comment]
> One thing I forgot to ask is what version of `lua_ls` are you using and are you on the latest commit of fzf-lua?

Using version 3.7.3 of `lua_ls` and I'm on the tippy top (commit 4fae64e) of `fzf-lua` :)

> Btw, in the meantime, you can always disable the previewer with `:FzfLua lsp_code_actions previewer=false`.

No worries! This isn't disturbing my setup, I'm more than happy to debug this.

**Comment by ibhagwan** [comment]
Ok, found the issue, happens only with the nightly build 0.10.0-dev, let look at the runtime and see what changed.

**Comment by ibhagwan** [comment]
@MariaSolOs, try https://github.com/ibhagwan/fzf-lua/commit/0fde123a55a1e6cc617654e7a228bb2f284b0cf3, should be good, works on my end with nightly.

**Comment by ibhagwan** [comment]
Also take a look at #944 for some recomendations with `git-delta` :-)

**Comment by MariaSolOs** [comment]
@ibhagwan YOU'RE AMAZING! The fix works like a charm 🚀

> Also take a look at #944 for some recomendations with `git-delta` :-)

Oh nice, will definitely take a look at that.

As always, thank you <3

**Comment by ibhagwan** [comment]
Ty for the kind words @MariaSolOs ❤️ 😄
