### ISSUE TITLE
`command_history` should append the executed command to the history

### ISSUE THREAD

**Issue by mcchrish** [ibhagwan/fzf-lua#95]
Useful when running the previously execute command using `@:`.

**Comment by ibhagwan** [comment]
This is so strange, all the code does is feed the keys `:<cmd><CR>`, yet the command won't go into history, I tried swapping it with `vim.cmd(<command>)` instead but it still won't go into history.

Do you have a clue how to get it to feed into history? might save me some research time.

**Comment by mcchrish** [comment]
Strange, I'm remembering that fzf.vim was able to do it but now that I tried it again, it seems it's not able to do so as well.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/1837038f8e05980bd3ac810f78e53b01fb0134ca should work now.

**Comment by jgonera** [comment]
@ibhagwan was this also supposed to be added to `search_history`? I seem to be getting duplicate items there (i.e. when I choose an item in `search_history` then re-open `search_history` the last search term will now appear twice).

**Comment by ibhagwan** [comment]
> @ibhagwan was this also supposed to be added to `search_history`? I seem to be getting duplicate items there (i.e. when I choose an item in `search_history` then re-open `search_history` the last search term will now appear twice).

You're correct @jgonera!

Fixed in https://github.com/ibhagwan/fzf-lua/commit/9c94851e30ded5a374b2de24d8847b6bdfcfe0b4
