### ISSUE TITLE
live grep > E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim

### ISSUE THREAD

**Issue by mikesmithgh** [ibhagwan/fzf-lua#950]
### Info

- Operating System: macos
- Shell: bash GNU bash, version 5.2.21(1)-release (aarch64-apple-darwin23.0.0)
- Terminal: kitty 0.31.0 created by Kovid Goyal
- `nvim --version`:
```
NVIM v0.10.0-dev-1819+gb40170f7a-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
```
- `fzf --version`: 0.44.1 (brew)

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
When I use live-grep I am getting errors about opening `syntax.nvim`.

It appears to be looking for:
```
ADDITIONAL DATA DIRECTORY (DEFAULT)  
                  *$XDG_DATA_DIRS*              Nvim: stdpath("data_dirs")
    Unix:         /usr/local/share            /usr/local/share/nvim
                  /usr/share                  /usr/share/nvim
    Windows:      Not applicable              Not applicable
```

I build neovim nightly and have the environment variable set `VIMRUNTIME=/Users/mike/gitrepos/neovim/runtime`

`/usr/local/share/nvim` and `usr/share/nvim` do not exist on my machine

### Demo

https://github.com/ibhagwan/fzf-lua/assets/10135646/6f25bf3d-e818-4c95-a446-2a597ae76978

**Comment by ibhagwan** [comment]
Can you run `:FzfLua live_grep debug=true` and post the command that will appear under `[DEBUG]` as the first outpt line?

Then run `:new | term` to open a new neovim terminal and run the same command inside?

**Comment by mikesmithgh** [comment]
sure, I ran it but the error doesn't seem to be coming from rg. Let me know if you need me to try anything else 👍

:FzfLua live_grep debug=true
```
*Rg> a                                                                                                        
  3/3 (0)                                                                                                     
  :: <ctrl-g> to Fuzzy Search                                                                                 
󰅂  [DEBUG]: rg --column --line-number --no-heading --color=always --smart-case --max-columns=4096 -e 'a'      
   󰈙 a.txt:1:1:a                                                                                              
   E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim                                              
                                          
```
:new | term
```bash
bash-5.2$ rg --column --line-number --no-heading --color=always --smart-case --max-columns=4096 -e 'a'
a.txt:1:1:a                                                                                           
bash-5.2$ pwd                                                                                         
/Users/mike/tmp/test                                                                                  
bash-5.2$ ls -la                                                                                      
total 24                                                                                              
drwxr-xr-x    5 mike  staff   160 Dec 12 09:27 .                                                      
drwxr-xr-x@ 183 mike  staff  5856 Dec 12 09:46 ..                                                     
-rw-r--r--    1 mike  staff     2 Dec 12 11:44 a.txt                                                  
-rw-r--r--    1 mike  staff     2 Dec 12 11:44 b.txt                                                  
-rw-r--r--    1 mike  staff     2 Dec 12 11:44 c.txt                                                  
bash-5.2$                                                                                                                                                                                         
```

**Comment by ibhagwan** [comment]
> sure, I ran it but the error doesn't seem to be coming from rg. Let me know if you need me to try anything else 

In your post I see results are coming back as well as the error line, is everything else working as it should and this line is always appended as the last line? Does the same result set and error appear when you press `ctrl-g` as well?

What happens if you run grep with the same search term, for example `:FzfLua grep search=a`?

**Comment by ibhagwan** [comment]
I think I have a suspect for this issue @mikesmithgh, can you try `live_grep_native`?
If my suspicions are correct it will work without the extra error message.

**Comment by mikesmithgh** [comment]
`:FzfLua grep search=a` results in the same. I tested using grep instead of rg.

![grep](https://github.com/ibhagwan/fzf-lua/assets/10135646/eed5db04-2453-488f-a3ca-67ccfc98f7e6)

^^ I was typing the above before I saw you most recent message.

I just tests with `live_grep_native` and it worked without the error 👍

**Comment by mikesmithgh** [comment]
`live_grep_native` without the error 🥳 

![fzf-lua-no-error](https://github.com/ibhagwan/fzf-lua/assets/10135646/62e50030-3ab3-4856-b0ed-da27df4f4c77)

**Comment by ibhagwan** [comment]
> `live_grep_native` without the error

Confirming my suspicion, now I have to fix it :)

**Comment by mikesmithgh** [comment]
I should also mention I am seeing the issue on `lsp_code_actions` when I have `previewer` set to `codeaction_native` as well.

**Comment by ibhagwan** [comment]
> I should also mention I am seeing the issue on `lsp_code_actions` when I have `previewer` set to `codeaction_native` as well.

You'll bee seeing it everywhere where an external `neovim --headless` command is used as proxy to run external commands / communicate with the main neovim instance, I'm going to commit a branch soon in an attempt to fix it and would be grateful if you can try it.

**Comment by mikesmithgh** [comment]
> > I should also mention I am seeing the issue on `lsp_code_actions` when I have `previewer` set to `codeaction_native` as well.
> 
> You'll bee seeing it everywhere where an external `neovim --headless` command is used as proxy to run external commands / communicate with the main neovim instance, I'm going to commit a branch soon in an attempt to fix it and would be grateful if you can try it.

sure just let me know 👍

**Comment by ibhagwan** [comment]
@mikesmithgh, can you try branch `950`?
https://github.com/ibhagwan/fzf-lua/tree/950

Can you also post the output of any command with debug so we can see the runtime
> `:FzfLua files debug=true` with a custom runtime from AppImage:
![image](https://github.com/ibhagwan/fzf-lua/assets/59988195/c88476dc-4847-4d3c-b0b3-1d3e5b0502b5)

**Comment by mikesmithgh** [comment]
@ibhagwan That worked for me! the runtime looks good too 👍 
```
[DEBUG]: VIMRUNTIME: /Users/mike/gitrepos/neovim/runtime                                                                                                           
[DEBUG]: rg --sort-files --column --line-number --no-heading --color=never --smart-case --hidden --max-columns=512 -g '!{.git,.worktrees,node_modules,.Trash}/' '' 
```
![fzf-lua-live-grep](https://github.com/ibhagwan/fzf-lua/assets/10135646/32ea321a-7e18-4f15-84a5-c1060f3759a0)

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/209e9405d2df949cbffe5b7b9329756b83bf2339

Great @mikesmithgh! Merged with main (minus the extra debug line).
