### ISSUE TITLE
question: can i disrespect .gitignore?

### ISSUE THREAD

**Issue by tmnvanderberg** [ibhagwan/fzf-lua#951]
I'm using `files` search a lot, but the maintainer of the project i'm working on has placed the build config files in .gitignore.

Is is possible to ignore .gitignore?

**Comment by ibhagwan** [comment]
You can modify files command to whatever you want and add  `--no-ignore` to it, for example:
```lua
require('fzf-lua').files({ cmd = 'fd …' })
```

You can also add a toggle action (conveniently already exits but is not the default):
```lua
require('fzf-lua').files({ actions = { ['ctrl-g'] = require('fzf-lua').actions.toggle_gitignore }})
```

**Comment by tmnvanderberg** [comment]
Awesome, thanks!
