### ISSUE TITLE
Question: adding a new "builtin"

### ISSUE THREAD

**Issue by tmnvanderberg** [ibhagwan/fzf-lua#953]
I have a somewhat atypical scenario in that I don't use any keybinds for fzf-lua. Instead I like to just run :FzfLua (bind to C-P) and use the power of fzf to help me find what I need.

Is it possible to add custom entries to this list of "builtins"?

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if you need more help with this.

**Comment by tmnvanderberg** [comment]
Hi, sorry to re-open this late, I completely forgot to get back to you.

From what I understand, `require('fzf-lua').my_function = …`  would add my function to the fzf-lua module. But what I would like (additionally) is to call it from the main BuiltIn menu, i.e. this one:

![image](https://github.com/user-attachments/assets/36188c9c-673c-4f22-a9a6-127e4e42ce89)

Is this possible as well?

**Comment by ibhagwan** [comment]
> Is this possible as well?

Add your function as I mentioned and try, the list is automatically built from the module functions so it should work.

**Comment by tmnvanderberg** [comment]
Hmm, I must have been blind, that works perfectly! Thank you.
