### ISSUE TITLE
Passing path to grep { ... } : feat

### ISSUE THREAD

**Issue by daedroza** [ibhagwan/fzf-lua#955]
Would it be possible pass a path to search directory?

There are two ways to achieve this:
1. One way is to just append path to the calling process. However, with appending PATH, rg will ignore it's some of it's ignore rules.
2. Starting a new process in search directory and search from there without appending path so the ignore rules still apply.

Any ideas how to approach this?

**Comment by ibhagwan** [comment]
Why aren’t you passing the path `cwd` option?

**Comment by daedroza** [comment]
Thanks, I am unsure why it wasn't working before hence the question. The doc for the default config is also very long and becomes cumbersome to identify the position.

Can you please tell if input_prompt is working for you? I am unable to modify the default "Grep for>" text.

**Comment by daedroza** [comment]
I'm doing something like this
```
        require("fzf-lua").grep({
          prompt = prompt,
          cwd = cwd,
          winopts = {
            preview = {
              hidden = "nohidden",
            },
          },
          grep = {
            input_prompt = input_prompt,
          },
        })
```

**Comment by daedroza** [comment]
So it looks like input_prompt changes when I pass it to the setup() however fails when I pass it to grep().

**Comment by ibhagwan** [comment]
> The doc for the default config is also very long and becomes cumbersome to identify the position.

You’re welcome to contribute to the wiki, it’s open edit for all and there is always work to be done to make docs more clear as you’ve noticed. There was an initiative to document all the options but unfortunately it’s not where I would like it to be yet:
https://github.com/ibhagwan/fzf-lua/wiki/Options

> So it looks like input_prompt changes when I pass it to the setup() however fails when I pass it to grep().

Works perfectly for me:
```lua
:FzfLua grep input_prompt=test
```

**Comment by daedroza** [comment]
> > The doc for the default config is also very long and becomes cumbersome to identify the position.
> 
> You’re welcome to contribute to the wiki, it’s open edit for all and there is always work to be done to make docs more clear as you’ve noticed. There was an initiative to document all the options but unfortunately it’s not where I would like it to be yet: https://github.com/ibhagwan/fzf-lua/wiki/Options
> 
> > So it looks like input_prompt changes when I pass it to the setup() however fails when I pass it to grep().
> 
> Works perfectly for me:
> 
> ```lua
> :FzfLua grep input_prompt=test
> ```

For me also it works using `:FzfLua grep input_prompt=test` but not using the Lua function.

**Comment by daedroza** [comment]
Here is my setup config
```
      require("fzf-lua").setup({
        "max-perf",
        winopts = {
          height = 0.90,
          width = 0.99,
          preview = {
            hidden     = "hidden",
            horizontal = "right:50%",
            scrollbar  = false,
          },
        },
        grep = {
          rg_glob = true,
          multi_process = true,
          glob_flag = "--iglob",
          glob_separator = "%s%-%-",
          rg_opts = "--column --line-number --no-heading --color=always " ..
              "--smart-case --max-columns=512 -e",
        },
        tags = {
          multi_process = true,
        },
        actions = {
          files = {
            ["default"] = actions.file_edit,
          },
          buffers = {
            ["default"] = actions.buf_edit,
          },
        },
        keymap = {
          builtin = {
            ["<C-t>"] = "toggle-preview",
          },
          fzf = {
            ["ctrl-t"] = "toggle-preview",
          },
        },
        files = {
          cwd_prompt = false,
          cwd_prompt_shorten_len = 0,
          cwd_prompt_shorten_val = 1,
        },
      })
```

And the calling grep function
```
      require("fzf-lua").setup({
        "max-perf",
        winopts = {
          height = 0.90,
          width = 0.99,
          preview = {
            hidden     = "hidden",
            horizontal = "right:50%",
            scrollbar  = false,
          },
        },
        grep = {
          rg_glob = true,
          multi_process = true,
          glob_flag = "--iglob",
          glob_separator = "%s%-%-",
          rg_opts = "--column --line-number --no-heading --color=always " ..
              "--smart-case --max-columns=512 -e",
        },
        tags = {
          multi_process = true,
        },
        actions = {
          files = {
            ["default"] = actions.file_edit,
          },
          buffers = {
            ["default"] = actions.buf_edit,
          },
        },
        keymap = {
          builtin = {
            ["<C-t>"] = "toggle-preview",
          },
          fzf = {
            ["ctrl-t"] = "toggle-preview",
          },
        },
        files = {
          cwd_prompt = false,
          cwd_prompt_shorten_len = 0,
          cwd_prompt_shorten_val = 1,
        },
      })
```

**Comment by ibhagwan** [comment]
Your config, makes no difference, it doesn't specify `input_prompt`, the below doesn't work (would be very strange if it didn't):
```lua
:lua require("fzf-lua").grep({ input_prompt = "test>" })
```

> And here is the calling grep function.

When calling `grep` you don't need to specify these are grep options, just set it at the top level:
```lua
  require("fzf-lua").grep({
          prompt = prompt,
          cwd = cwd,
          winopts = {
            preview = {
              hidden = "nohidden",
            },
          },
          input_prompt = input_prompt,
        })
```
