### ISSUE TITLE
Question: How to handle problem with current lua pattern? (Windows support PR)

### ISSUE THREAD

**Issue by TheLeoP** [ibhagwan/fzf-lua#956]
### Description 
 
Currently, the following code is used to support defining fzf key bindings using an old fzf-lua syntax:

```lua
      -- backward compatibility to when binds
      -- where defined as one string '<key>:<command>'
      local key, action = v:match("(.*):(.*)")
```

This does not gives problems on Linux/Mac because file paths do not contain `:` (which does happen on Windows because of the disk syntax `C:/Users/...`). This means that key bindings that include a path (I encountered this for the `zero` binding that calls `fzf-lua` through a headless neovim instance that uses the full path to the executable) are wrongly divided into a key and an action. My question is:

Would it be ok to simply check if the user is running on windows and, if yes, don't support the old syntax (on windows)? Or would it be preffered to define a more complicated lua pattern to account for windows paths (I'm not even sure if this option is possible :p)?

**Comment by ibhagwan** [comment]
You can remove that part altogether, this is most likely very old backward compat code which is used by nobody anymore.
