### ISSUE TITLE
Question: Using `:` as fzf delimiter is a problem on Windows, what would be the prefered curse of action? (Windows support PR)

### ISSUE THREAD

**Issue by TheLeoP** [ibhagwan/fzf-lua#957]
### Description 

For similar reasons to the ones described in #956, using `:` as the fzf delimiter (or part of the fzf delimiter) it's a problem on Windows.

For example, the `FzfLua autocmds` uses `:` as a delimiter by default.

What would be the preffered curse of action? Would it be ok to simply change the delimiter?

**Comment by TheLeoP** [comment]
As a reference, using `:` as a delimiter (the defautl at the moment), `FzfLua autocmds` looks like this:

![image](https://github.com/ibhagwan/fzf-lua/assets/53507599/b2b0c241-71f7-4bc8-9fc7-49242d651822)

and without any delimiters it looks like this:

![image](https://github.com/ibhagwan/fzf-lua/assets/53507599/f6c17c3b-f83c-4d71-a75d-4372ce8aadbc)

**Comment by ibhagwan** [comment]
That’s a good question, not just `autocmds`, all line/column delimiters use `:` as delimiter (so basically all file type entries, buffers, grep, etc), I think there could be an easy solution for that which it to increase the fzf field index expression by 1 on windows (configurable), so for example on Linux/Mac line is always `{2}` on windows it will be `{3}`.

The alternative would be a full refactor and new approach to delimiters and also having to transform rg/grep output which IMHO would also incur a heavy performance cost.

**Comment by TheLeoP** [comment]
> The alternative would be a full refactor and new approach to delimiters and also having to transform rg/grep output which IMHO would also incur a heavy performance cost.

I think this option is out of the picture.

> I think there could be an easy solution for that which it to increase the fzf field index expression by 1 on windows (configurable), so for example on Linux/Mac line is always {2} on windows it will be {3}.

Should this be changed in the appropiate default configs? Or inside the `set_fzf_field_index` function? I can see that the function isn't called in every provider that uses `:` as delimiter, should every provider that uses it call this function?

**Comment by ibhagwan** [comment]
> Should this be changed in the appropiate default configs? Or inside the set_fzf_field_index function? I can see that the function isn't called in every provider that uses : as delimiter, should every provider that uses it call it?

I think perhaps we can use this opportunity to normalize the usage of the `:` delimiter and the field index separators and have a single source function that sets it including adjusting for windows, we can then call this function while setting config.defaults.

We can then make a list of everything affected and see if we can dedup the code even more to a single source that sets the delimiter while taking windows into account.

**Comment by ibhagwan** [comment]
Mind me asking how far are you in this? Have you managed to support all 3 types of `fzf_exec` contents, table, async function with callback and string (simple shell command)?

I’m asking because if I were to support windows I’d start there, if you can make `fzf_exec` work with all 3 use cases, you’re way ahead of the game and can probably make this work.

**Comment by TheLeoP** [comment]
> Mind me asking how far are you in this? Have you managed to support all 3 types of fzf_exec contents, table, async function with callback and string (simple shell command)?

I hadn't even realized that there were 3 types of contets. I was trying random things and slowly fixing them as a way to gradually understand the codebase, so let me check.

- `FzfLua files` uses a string and it's currently working.
- `FzfLua colorschemes` seems to use a table and it's currently working.
- `FzfLua autocmds` seems to use a an async function and it's currently working (besides the delimiter thing).


I'll try to fix the delimiter problem tomorrow. I've been programming for a while now and it's already really late here, so my brain isn't really working anymore (I tried to read your previous response and my brain just couldn't proccess it, lol)

**Comment by ibhagwan** [comment]
> > Mind me asking how far are you in this? Have you managed to support all 3 types of fzf_exec contents, table, async function with callback and string (simple shell command)?
> 
> I hadn't even realized that there were 3 types of contets. I was trying random things and slowly fixing them as a way to gradually understand the codebase, so let me check.
> 
> * `FzfLua files` uses a string and it's currently working.
> * `FzfLua colorschemes` seems to use a table and it's currently working.
> * `FzfLua autocmds` seems to use a an async function and it's currently working (besides the delimiter thing).
> 
> I'll try to fix the delimiter problem tomorrow. I've been programming for a while now and it's already really late here, so my brain isn't really working anymore (I tried to read your previous response and my brain just couldn't proccess it, lol)

That’s great progress so I’m assuming you managed to solve the named pipes and shell redirection on windows which is ahead of previous attempts already :)

Go to sleep and good luck to tomorrow, IMHO config/delimter issues should be simple to solve and we’ll refactor if need be.

Pain points would probably be previews that require shell commands, live grep `exec_empty_query` conditioning and other random `sh -c`’s spread in random locations.

**Comment by TheLeoP** [comment]
It's worth mentioning that a lot of the code is based in how [nvim-fzf](https://github.com/vijaymarupudi/nvim-fzf) handles things for windows (mainly how to replace `mkfifo`). There were also some escaping problems with `cmd` (which I'm still not sure why weren't working as expected by using `vim.fn.shellescape`, but I managed to solve them). Fortunately, `cmd` does support redirection, so that was one less problem to deal with.

**Comment by ibhagwan** [comment]
> > That’s great progress so I’m assuming you managed to solve the named pipes and shell redirection on windows which is ahead of previous attempts already :)
> 
> Yeah. It's worth mentioning that a lot of the code is based in how [nvim-fzf](https://github.com/vijaymarupudi/nvim-fzf) handles things for windows (mainly how to replace `mkfifo`). There were also some escaping problems with `cmd` (which I'm still not sure why weren't working as expected by using `vim.fn.shellescape`, but I managed to solve them). Fortunately, `cmd` does support redirection, so that was one less problem to deal with.

`nvim-fzf` is how this project started and the fzf execution code in [`fzf.lua`](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/fzf.lua) is still a copy of what it once was (+improvements) before it added windows support.
