### ISSUE TITLE
Search highlight text in neovim preview buffer

### ISSUE THREAD

**Issue by kdheepak** [ibhagwan/fzf-lua#96]
I'm not sure how practical this is but it would be nice if the word that we are currently searching for is highlighted in the neovim preview buffer.

**Comment by ibhagwan** [comment]
It’s possible, I also added a highlight for this to be used one day under `previewers.builtin.range`, one day I’ll get to it.

**Comment by ibhagwan** [comment]
I'm going to close this for now, I don't want to invest the time in this at the moment, `hl_cursor` already highlights the exact location where the match is found, the combination of the cursor line and cursor highlight you know exactly where the match is, see how the word `buffers` is highlighted in the preview below.

Adding new code with new complexity (LSP, live grep, grep, etc) just to be able to match entire words adds too much complexity for no major benefit IMO.

![screenshot-1631173517](https://user-images.githubusercontent.com/59988195/132644592-8f382654-5cbf-403e-b369-0f7299a49bc4.png)
).

**Comment by kdheepak** [comment]
For me, this is definitely easier to see:

<img width="1680" alt="Screen Shot 2021-09-09 at 9 08 42 AM" src="https://user-images.githubusercontent.com/1813121/132712525-7c340380-c108-4ea6-8f30-85c20fd0bd27.png">

than this:

<img width="1680" alt="Screen Shot 2021-09-09 at 9 08 53 AM" src="https://user-images.githubusercontent.com/1813121/132712491-461ab226-91ab-4c77-9ce5-543897f134e9.png">

Especially when pair programming, and pointing out a change a line in the file is much more easier to do when it is highlighted by default. 

I think just adding the "search" to the search register and resetting it when fzf exits will be more than sufficient. Is that going to make things complicated?

**Comment by kdheepak** [comment]
Also, I have the following in my `init.lua`.

```lua
  grep = {
    rg_opts = "--hidden --column --line-number --sort-files --no-heading --color=always --smart-case -g '!{.git,node_modules}/*'",
  }
```

I'm not sure why the other of the files in `live_grep` is different. Strange.

**Comment by ibhagwan** [comment]
> For me, this is definitely easier to see:

You highlights aren't very visible, why don't you set both `hl_cursor` and `hl_cursorline` to something more visible?

For example:
```lua
  previewers = {
      builtin = {
        hl_cursor       = 'Error',     -- cursor highlight
        hl_cursorline   = 'IncSearch', -- cursor line highlight
      },
  }
```

> I think just adding the "search" to the search register and resetting it when fzf exits will be more than sufficient. Is that going to make things complicated?

Probably not that complicated just a bit more conditioning between LSP ranges and live_grep search terms.

**Comment by kdheepak** [comment]
Nice idea! Using

```
    builtin = {
      hl_cursorline = "Search", -- cursor line highlight
    }
```

gives me:

<img width="1680" alt="Screen Shot 2021-09-09 at 9 25 38 AM" src="https://user-images.githubusercontent.com/1813121/132715250-df7d0e4e-1251-4fae-817e-3dd7bf780f41.png">

Which is better.

**Comment by ibhagwan** [comment]
Why don't you also use `hl_cursorline` with a more visible highlight so you can see the column where the match starts?

> I'm not sure why the order of the files in live_grep is different. Strange.

Just tested `rg_opts` is well respected in all `grep` commands, including both `live_grep` versions, not sure what happens in your case, interesting.

**Comment by alopatindev** [comment]
> hl_cursor already highlights the exact location where the match is found

Sounds reasonable, but I'd be really great to highlight *all* matches in the preview.
