### ISSUE TITLE
How to grep word including word boundaries

### ISSUE THREAD

**Issue by KortanZ** [ibhagwan/fzf-lua#962]
### Info

- Operating System: Arch linux
- Shell: zsh
- Terminal: Windows Terminal
- `nvim --version`: NVIM v0.9.4
- `fzf --version`: 0.44.1 (29e67d30)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description
Hi, I want to grep word with regex `\b` boundary symbol, so that i can find function references. 
For example, there are serval functions named `module_init`, `module_init_stage1`, etc, and i want to only grep `module_init` without showing `module_init_xxxx`.
I used to use `map('n', 'gr', ':Rg \\b<C-R><C-W>\\b<cr>', default_opt)` in fzf.vim and it works well.
In in fzf-lua's builtin `fzf-vim` profile, when type `\bmodule_init\b` in `:FzfLua live_grep_native` prompt manually, it shows correct result. But when write it in lua config, it can't work. I've tried `Rg` and `live_grep_native`:
 -  `map('n', 'gr', ':Rg \\b<C-R><C-W>\\b<cr>', default_opt)`, press `gr` on `module_init`, it shows `module_init` in search line and press ctrl-g to regex search mode, it shows `\\bmodule_init\\b` in search line and show no result
 - `map('n', 'gr', ":lua require('fzf-lua').live_grep_native({ search = '\\b<C-R><C-W>\\b' })<cr>", default_opt)`, press `gr` on `module_init`, it shows `module_init` in search line, but show no result.

So how to pass `\b` to fzf-lua correctly, or is there any other way to do "full match" search in fzf-lua?

**Comment by ibhagwan** [comment]
Special characters are automatically escaped, if you wish to prevent that add `no_esc=true`, for that you’d need to use the original command and not the `Rg` variant:
```lua
:FzfLua live_grep search=foo\b no_esc=true
-- or
:lua require('fzf-lua').live_grep({ search = '\bmodule_init\b', no_esc=true })
```

Anther option, if you’re after the current cursor word use the builtins:
```lua
:FzfLua grep_cword
:FzfLua grep_cWORD
:FzfLua grep_visual
```

**Comment by ibhagwan** [comment]
@KortanZ, due to #968, if you update to the latest commit `grep_cword` will automatically add word boundries with `\b<word>\b`.

**Comment by KortanZ** [comment]
Sorry for the late reply, got really busy these days. And really thank you for your fast and kindly reply. 
Now `grep_cword` works like a charm. The solution you give lastweek actually can not work properly, i need to config keymaps like `:lua require('fzf-lua').live_grep({ search = '\\\\b<C-R><C-W>\\\\b', no_esc=true })` to make it work, which looks a little bit awkward since there are too many `\`s. With #968, my config file finally become clean again : ).
Btw, I've also have tried to pass `-w` to rg, but i cant find how to "add" a flag. If i need to add a flag, i have to rewrite all flags, which looks a little bit awkward too because the default flags works great and what i want is just pass one more simple `-w` flag. Am i missing some options that can "add" flags to rg?

**Comment by ibhagwan** [comment]
> which looks a little bit awkward since there are too many \s.

If you use a lua’s square bracket string wrap instead `[[\b…]]` you don’t need the double slash.

> but i cant find how to "add" a flag. If i need to add a flag, i have to rewrite all flags, which looks a little bit awkward too because the default flags works great and what i want is just pass one more simple -w flag. Am i missing some options that can "add" flags to rg?

There is no “add flag” you need to write the entire flag set you wish to use.
