### ISSUE TITLE
live_grep prompt is not resumed

### ISSUE THREAD

**Issue by mortezadadgar** [ibhagwan/fzf-lua#963]
### Info

- Operating System: Archlinux
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.9.4
- `fzf --version`: 0.44.1 (29e67d30)

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
there's a `resume` command which as expected resume the last fzf window, it's mentioned in wiki https://github.com/ibhagwan/fzf-lua/wiki#can-i-continue-from-the-last-search that alternatively `resume` can be used but it's not the case and only `live_grep` window is returned not the last inserted prompt; `resume` works ok in other commands.

**Comment by ibhagwan** [comment]
Not sure I what you mean by prompt, do you mean query or prompt prefix?

In any event, can you post reproduction steps, I just tested the below and it works as expected:
```lua
:FzfLua live_grep prompt=test>
-- enter a query and resume, works as expected, both query and prompt are resumed
:FzfLua live_grep resume=true
```

**Comment by mortezadadgar** [comment]
sorry for not being so clear, here are steps to reproduce:
`:FzfLua live_grep` and query some texts close with C-c
`:FzfLua live_grep resume` and see the inserted text is not resumed

**Comment by ibhagwan** [comment]
> :FzfLua live_grep resume

You need to specify `resume=true`:
```lua
:FzfLua live_grep resume=true
```

**Comment by mortezadadgar** [comment]
but that's another command to bind, i used to have same keymap for resuming every last window is there a way to manage it?

**Comment by ibhagwan** [comment]
> but that's another command to bind, i used to have same keymap for resuming every last window is there a way to manage it?
> 
> Edit:
> 
> > :FzfLua live_grep resume and see the inserted text is not
> 
> sorry I meant `:FzfLua resume`

I see what you mean now, that's a bug, I'll fix it.

**Comment by ibhagwan** [comment]
@mortezadadgar, should work as expected with https://github.com/ibhagwan/fzf-lua/commit/de33c83fdb7b231ef2ef4295b2011600f77fddb1.

**Comment by mortezadadgar** [comment]
wow that was quick three issues closed and solved in a row ⚡

**Comment by ibhagwan** [comment]
> wow that was quick three issues closed and solved in a row ⚡

Well the others didn’t need any solving :)

Ty for the reports!

**Comment by barrett-ruth** [comment]
@ibhagwan adding `resume=true` to the vim command worked, but I remember an issue a while ago led to me having these options in my config which seem to be of no effect now:

```lua
{
    global_resume = true,
    resume = true,
}
```

In summary, `FzfLua resume` used to work and does not, but `FzfLua <cmd> resume=true` does work.

**Comment by ibhagwan** [comment]
> @ibhagwan adding `resume=true` to the vim command worked, but I remember an issue a while ago led to me having these options in my config which seem to be of no effect now:
> 
> ```lua
> {
>     global_resume = true,
>     global_resume_query = true,
> }
> ```

These are no longer required.

> In summary, `FzfLua resume` used to work and does not, but `FzfLua <cmd> resume=true` does work.

Doesn’t work at all or for specific commands? I use `:FzfLua resume` all the time and it works.

**Comment by ibhagwan** [comment]
> Hmm, it doesn't seem to work now (at least for `live_grep.*` commands). Should I create another issue?

When you say doesn’t work what exactly doesn’t work? Feel free to create a new issue if you feel this issue isn’t exactly related.

**Comment by loyd** [comment]
> When you say doesn’t work what exactly doesn’t work?

```
FzfLua live_grep
<write a query>
<C-c or Esc>
FzfLua resume
```

The last command opens an empty window =(

**Comment by loyd** [comment]
It seems that `resume_set()` isn't call for `live_grep` on exit (I've checked it by logging in that function).

**Comment by loyd** [comment]
Ohh, that's the reason:
```
      -- reminder: this doesn't get called with 'live_grep' when using skim
      -- due to a bug where '--print-query --interactive' combo is broken:
      -- skim always prints an empty line where the typed query should be.
      -- see additional note above 'opts.fn_post_fzf' inside 'live_grep_mt'
```

**Comment by ibhagwan** [comment]
> Ohh, that's the reason:
> 
> ```
>       -- reminder: this doesn't get called with 'live_grep' when using skim
>       -- due to a bug where '--print-query --interactive' combo is broken:
>       -- skim always prints an empty line where the typed query should be.
>       -- see additional note above 'opts.fn_post_fzf' inside 'live_grep_mt'
> ```

Oh, you’re using skim, I would recommend to use fzf, not only skim is a dead project fzf introduced many changes and events that make the UX much better, e.g. reloading without restarting the process - try staging/unstaging with git_status and see the difference.
