### ISSUE TITLE
git commands window is not properly resized

### ISSUE THREAD

**Issue by mortezadadgar** [ibhagwan/fzf-lua#965]
### Info

- Operating System: Archlinux
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.9.4
- `fzf --version`: 0.44.1 (29e67d30)

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
require('fzf-lua').setup({
})
```
</details>

### Description 
every git command except the `git_files` doesn't rearrange the window after being resized by rearranging I'm mean when the window size if small preview is at bottom and files at top maximizing it should arrange the preview at right (sorry if it's not clear)
so stays like this after maximized
![image](https://github.com/ibhagwan/fzf-lua/assets/27911493/c5710ba9-3d89-4af8-a9e8-17eac7297c52)

**Comment by ibhagwan** [comment]
Unfortunately rearranging preview layouts isn’t possible with fzf native previewers (such used by git commands), the layout adjustments only work when using the neovim built in previewed which can be identified by having actual 2 windows (note that the preview in git commands is internal to the terminal).
