### ISSUE TITLE
git_commits copy commit hash not working

### ISSUE THREAD

**Issue by mortezadadgar** [ibhagwan/fzf-lua#966]
### Info

- Operating System: Archlinux
- Shell: zsh
- Terminal: st
- `nvim --version`: 0.9.4
- `fzf --version`: 0.44.1 (29e67d30)

- [x] The issue is reproducible with `mini.sh`

### Description 
it's mapped to `C-y` in header shown to users to copy current commit hash but it's doesn't seem to doing anything.

**Comment by ibhagwan** [comment]
How are you trying to paste? By default the hash gets copied to neovim’s yank register which you can paste by pressing `p` in normal mode.

If you wish to copy to clipboards, use a custom function that sets the `+` register:
> use the default action as base
https://github.com/ibhagwan/fzf-lua/blob/de33c83fdb7b231ef2ef4295b2011600f77fddb1/lua/fzf-lua/actions.lua#L594-L598

**Comment by mortezadadgar** [comment]
yes that's right but as I have `clipboard` set to "unnamedplus"` I expect everything to be in yanked to clipboard register not in neovim's like before setting this option.

**Comment by ibhagwan** [comment]
> yes that's right but as I have `clipboard` set to `unnamedplus` I expect everything to be in yanked to clipboard register not in neovim's like before setting this option.

As you can see in the action it gets copied directly to `0` and `”`, if you want it to clipboard set it to `+`.

**Comment by mortezadadgar** [comment]
@ibhagwan which fzf window this key will be applied? this seems to be a hacky solution to me and might break in future codebase changes, why not having a `use_system_clipboard` option for `commits` and `bcommits`

**Comment by ibhagwan** [comment]
> @ibhagwan which fzf window this key will be applied? this seems to be a hacky solution to me and might break in future codebase changes, why not having a `use_system_clipboard` option for `commits` and `bcommits`?

It’s not badly it’s a simple custom action, it will be applied to the provider you will set its action to, this needs to be set to `ctrl-y` in the actions table of `commits` or `bcommits` or both.

https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-acts

**Comment by mortezadadgar** [comment]
ok if that's the case this issue can be closed.

**Comment by ibhagwan** [comment]
> ok if that's the case this issue can be closed.

In case you haven’t different it out:
```lua
local copy_hash = function(selected, opts) 
   local commit_hash = match_commit_hash(selected[1], opts) 
   vim.fn.setreg([[+]], commit_hash)
 end

require'fzf-lua'setup({
  git = {
    commits = { actions = {  ['ctrl-y'] = copy_hash } },
    bcommits = { actions = {  ['ctrl-y'] = copy_hash } }
  }
})
```

**Comment by ibhagwan** [comment]
@mortezadadgar, this doesn't need another config issue, update to https://github.com/ibhagwan/fzf-lua/commit/3d71803d1ed25420c0c719d97fe8e1f7a1285f1f, the action will now consider the `clipboard` setting and copy to `*` or `+` for `unnamed` and `unnamedplus` respectively:
https://github.com/ibhagwan/fzf-lua/blob/3d71803d1ed25420c0c719d97fe8e1f7a1285f1f/lua/fzf-lua/actions.lua#L594-L604

**Comment by mortezadadgar** [comment]
thanks that's better now, wondering why you changed your mind

**Comment by ibhagwan** [comment]
> thanks that's better now, wondering why you changed your mind?

I gave it some thought and as long as it didn't "cost" yet another configuration option nobody will ever remember it made sense to match the `clipboard` setting.
