### ISSUE TITLE
Unify configing git pagers under previewers.git_diff.pager

### ISSUE THREAD

**Issue by mortezadadgar** [ibhagwan/fzf-lua#967]
just a small suggestions currently for changing bcommits and commits git pagers you have make changes to git command individually (except git_status) like this:
```
{
		local delta = "delta --diff-so-fancy --width=$FZF_PREVIEW_COLUMNS"
			git = {
				bcommits = {
					preview_pager = delta,
				},
				commits = {
					preview_pager = delta,
				},
			},
			previewers = {
				git_diff = {
					pager = delta,
				},
			},
}
```
can be all done under previewers.git_diff.pager? bcommits and commits seems to be related to git_diff previewers as well.

**Comment by ibhagwan** [comment]
It’s a good suggestion, there is also `preview_pager` for `lsp.code_actions`, I’ll think about the best way to do this.

**Comment by ibhagwan** [comment]
Apparently I already created the generic solution with the `defaults` table:
https://github.com/ibhagwan/fzf-lua/blob/6991c1f86eb9fa449a186ab047e88063d3a14484/README.md?plain=1#L749-L755

Can you try this and let me know if this solves your issue?
```lua
require('fzf-lua').setup({
  defaults = { preview_pager = 'delta' },
  -- your other settings
  …
})

**Comment by mortezadadgar** [comment]
Yes that changes `git_status`, `git_commits` and `git_bcommits` unfortunately `lsp.code_actions` stays the same.

**Comment by ibhagwan** [comment]
@mortezadadgar, https://github.com/ibhagwan/fzf-lua/commit/f2083c5cc157f17c416c1459cd667a1f8fda606f used this opportunity to refactor how default opts overrides work (which I wanted to do for a while) , `lsp_code_actions` override from `defaults` should work now.

**Comment by mortezadadgar** [comment]
@ibhagwan doesn't seem to work for me `lsp_code_actions` stays the same despite this config:
```
defaults = {
		preview_pager = "delta --diff-so-fancy --width=$FZF_PREVIEW_COLUMNS",
},
```

**Comment by ibhagwan** [comment]
> @ibhagwan hmm doesn't seem to work for me `lsp_code_actions` stays the same despite this config:
> 
> ```
> defaults = {
> 		preview_pager = "delta --diff-so-fancy --width=$FZF_PREVIEW_COLUMNS",
> },
> ```

Just tested again and the override priority works as expected, can you make sure your plugin got updated properly to the lastest commit and then run `:= _G.dump(require("fzf-lua").config.globals["lsp.code_actions"])`, the output should display the unified code action options, e.g:
```lua
{
  async_or_timeout = 5000,
  preview_pager = "delta --width=$FZF_PREVIEW_COLUMNS --hunk-header-style='omit' --file-style='omit'",
  previewer = "codeaction_native",
  prompt = "Code Actions> ",
  winopts = {
    col = 0,
    height = 0.4,
    preview = {
      vertical = "down:70%"
    },
    relative = "cursor",
    row = 1
  }
}
```

**Comment by mortezadadgar** [comment]
this is what i get:
```
{
  async_or_timeout = 5000,
  preview_pager = "delta --diff-so-fancy --width=$FZF_PREVIEW_COLUMNS",
  previewer = "codeaction",
  prompt = "Code Actions> "
}
```
and code action diff:
![image](https://github.com/ibhagwan/fzf-lua/assets/27911493/486c50e4-7be6-473f-855e-49ee17b13edb)

**Comment by ibhagwan** [comment]
@mortezadadgar, it worked (I can see a modified `preview_pager` setting) but you’re using the default builtin previewer (neovim window) which does not support a pager, you need to change your previewer to `codeaction_native` which uses shell commands instead, add this to your setup:
```lua
  lsp = { code_actions = { previewer = 'codeaction_native' } },
```

**Comment by mortezadadgar** [comment]
yeah that make it works, thanks!

**Comment by ibhagwan** [comment]
Mind me asking what LSP server generated this formatting code action? Is it `lua_ls`?

**Comment by mortezadadgar** [comment]
yes it's `lua_ls`.
