### ISSUE TITLE
Should `grep_cword` imply the `-w` ripgrep flag?

### ISSUE THREAD

**Issue by cbarrete** [ibhagwan/fzf-lua#968]
### Info

- Operating System: NixOS
- Shell: bash
- Terminal: Alacritty
- `nvim --version`: NVIM v0.9.4
- `fzf --version`: 0.44.1

- [x] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
local fzf_lua = require('fzf-lua')
fzf_lua.setup({ winopts = { fullscreen = true }})
vim.keymap.set('n', '<Space>w', fzf_lua.grep_cword)
```
</details>

### Description 

As `grep_cword` (and `grep_cWORD`) match full words, it makes sense to me that the output would contain exact matches: the intuitive behavior would be "search for the word under the cursor". This can be achieved by using the `-w` flag in ripgrep.

This is not the case currently: using `grep_cword` over the word `set` will match e.g. the word `reset`.

Of course, one can use `grep_cword` with a custom `rg_opt` that appends `-w` to the default grep args but:
1. This should (IMO) be the default
2. It takes a bit of time to figure out how to get the default grep flags, which is not very accessible to non-power users
3. It messes with other grep functions (e.g. `live_grep_resume`) which share the same grep options: unless I set the rg_opts for each of those functions, them using `-w` will depend on whether I've already used my `grep_cword` binding in this session or not

Non of this is critical or a show stopper, but having this work out of the box would probably be a better user experience.

**Comment by ibhagwan** [comment]
> This is not the case currently: using grep_cword over the word set will match e.g. the word reset.

I agree there is some sense in this statement but adding `-w` has a few issues:
- Limits the usage to `rg` (it currently auto-detects and works with `grep` seamlessly, can also easily be setup to use with `ag`
- Will be confusing if you wish to then change the search term with `ctrl-g` change the regex and now there are no matches.

> This should (IMO) be the default

This would be confusing and create other issues as explained above

> It takes a bit of time to figure out how to get the default grep flags, which is not very accessible to non-power users

Only power users understand the underhood of this plugin and doesn't seem to be an issue for even the average user until now (and it's been a while...)

Btw, use `debug=true` and you'll see the flags and underlying command as the first output line.

> It messes with other grep functions

Proving my point, over engineering the rg_opts for automatic adaptation is counter intuitive and shouldn't be the solution here.


What I'm willing to offer instead is generating a regex from the neovim word that makes sure the match is a full word (space or EOL/SOL around the word), if you're willing to help research the exact regex used when using `-w` that would save me some time and I can add that to the `grep_cword` variants.

**Comment by cbarrete** [comment]
Thanks for the quick reply and the context that I was missing.
At a quick glance, here is what I could find in `RegexMatcherBuilder::build_many` (`crates/pcre2/src/matcher.rs`):

```rust
        let mut singlepat = pats.join("|");
        if self.case_smart && !has_uppercase_literal(&singlepat) {
            builder.caseless(true);
        }
        if self.whole_line {
            singlepat = format!(r"(?m:^)(?:{})(?m:$)", singlepat);
        } else if self.word {
            // We make this option exclusive with whole_line because when
            // whole_line is enabled, all matches necessary fall on word
            // boundaries. So this extra goop is strictly redundant.
            singlepat = format!(r"(?<!\w)(?:{})(?!\w)", singlepat);
        }
```

This is one of the two usages of `BoundaryMode::Word`, which is set by the `-w` flag.
Note that this is used by the `pcre2` implementation, the other one (native, found in `crates/regex/src/matcher.rs`) doesn't have an explicit regex string, so it would take a bit more effort and understanding of ripgrep's native regexes to figure out what it does, but I expect them to have the same behavior.

**Comment by ibhagwan** [comment]
> Note that this is used by the pcre2 implementation

This requires the options to contain `--pcre2` which will create an issue with custom `rg_opts` and `grep` (when `rg` isn't installed).

https://github.com/ibhagwan/fzf-lua/commit/a2271a239646ecffa2fbaa6004614b9ac82f6bb4 

For `grep_cword`, `\b<word>\b` seems to be an adequate solution, it matches the exact word and is also pretty clear what it does when it appears in the header string.

However it doesn't work as expected for `grep_cWORD` so I opted to match neovim's WORD behavior which only stops the match at spaces, start of line and end of line with the regex `(^|\s)<WORD>($|\s)`.

Both of these implementation work with both `rg` and `grep` (and I would assume `ag` as well).

**Comment by cbarrete** [comment]
Thank you very much, it works great!
My only nitpick is that this is case insensitive and messes up the history used by `live_grep_resume`, but that's something I can live with :)

**Comment by ibhagwan** [comment]
> Thank you very much, it works great! My only nitpick is that this is case insensitive and messes up the history used by `live_grep_resume`, but that's something I can live with :)

Why don't you remove `--smart-case` from the default `rg_opts` then?

**Comment by ibhagwan** [comment]
> messes up the history used by live_grep_resume, but that's something I can live with :)

If what you mean is preventing `grep_cword` from overriding the query used by the other `grep` and `live_grep` commands, it can be easily solved.

**Comment by cbarrete** [comment]
> Why don't you remove --smart-case from the default rg_opts then?

That's what I'm going to do, so it's fine, having it be the default would just be the cherry on top :)

> If what you mean is preventing grep_cword from overriding the query used by the other grep and live_grep commands, it can be easily solved.

Yes, that's what I mean

**Comment by ibhagwan** [comment]
> Yes, that's what I mean

Resume call data is stored in based on a key set by the calling function (grep, files, etc), you can override that with `__resume_key` thus storing the resume data for grep_cword (or cWORD) elsewhere:
```lua
:FzfLua grep_cword __resume_key=whatever
-- same as
:lua require("fzf-lua").grep_cword({ __resume_key="whatever" })
-- if are inquisitive, this is where it will be stored:
:= _G.dump(require("fzf-lua").config.__resume_map["whatever"])
```

If you change your mapping as per the above you can `live_grep resume=true` without cword/cWORD pollution.

As a side note if you're intersted in history add `--history` to your `fzf_opts` and you can use `ctrl-p|n` for previous/next search:
```lua
require("fzf-lua").setup({
  grep = {
    fzf_opts = {
      ["--history"] = vim.fn.shellescape(vim.fn.stdpath("data") .. "/fzf_grep_hist"),
    },
  }
})
```

**Comment by cbarrete** [comment]
That works, but it seems a little unnecessary, since I don't see how it makes sense to have a history/resume for cword: every time the function is called, we need to get and expand the cword.
Should the options be merged with e.g. `{ __resume_key = "grep_cword" }` by default for cword/cWORD?

I've also tried using `fzf_lua.grep_cword({ resume = false})`, but it seems to write into the resume data anyway (which I is reasonable if the idea is to be able to resume a call that itself wasn't a resume).

**Comment by cbarrete** [comment]
Meaning:
```
diff --git a/lua/fzf-lua/providers/grep.lua b/lua/fzf-lua/providers/grep.lua
index 628c3aa..e5da647 100644
--- a/lua/fzf-lua/providers/grep.lua
+++ b/lua/fzf-lua/providers/grep.lua
@@ -344,6 +344,7 @@ end

 M.grep_cword = function(opts)
   if not opts then opts = {} end
+  opts = vim.tbl_extend("keep", opts, { __resume_key = "grep_cword" })
   opts.no_esc = true
   -- match whole words only (#968)
   opts.search = [[\b]] .. utils.rg_escape(vim.fn.expand("<cword>")) .. [[\b]]
```

(there's also a ` M.grep_cword` in `tags.lua`, but it seems unused?)

**Comment by ibhagwan** [comment]
> That works, but it seems a little unnecessary, since I don't see how it makes sense to have a history/resume for cword: every time the function is called, we need to get and expand the cword.
Should the options be merged with e.g. { __resume_key = "grep_cword" } by default for cword/cWORD?

I don’t necessarily agree, `grep_cword` is just an alias to grep while expanding the word under cursor, IMHO that still falls under `grep` so why shouldn’t it be resumed? I personally would find it more confusing to disable that in grep_cword.

There are many users and many use cases, I personally feel the default makes sense (or many users would have made the same  request), and as demonstrated can be disabled.

> I've also tried using fzf_lua.grep_cword({ resume = false}), but it seems to write into the resume data anyway (which I is reasonable if the idea is to be able to resume a call that itself wasn't a resume).

The above does nothing `resume=false` (or `nil`) is the default which means to not resume the last typed query/search, **it does not prevent storing resume data**, if you wish to throw away the resume data for a provider use `__resume_key` as we discussed.

> there's also a M.grep_cword in tags.lua, but it seems unused?

It is used, this is what gets called when you execute `tags_grep_cword` - I will give these the same treatment for consistency.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/15734a586e03aa93465770f6396d661cb1e37137 - this commit gives a similar treatment to `tags_grep_{cword|cWORD}`.

**Comment by cbarrete** [comment]
Fair enough, at this point I just have subjective preferences, so I won't bother you any more than that.
I appreciate you taking the time to explain all of this to me though!
