### ISSUE TITLE
Disable preview for code action

### ISSUE THREAD

**Issue by haunt98** [ibhagwan/fzf-lua#969]
### Info

- Operating System: macOS
- Shell: zsh
- Terminal: wezterm/kitty
- `nvim --version`: NVIM v0.9.4
- `fzf --version`: 0.44.1 (d7d2ac3)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
			require("fzf-lua").setup({ "fzf-native" })

			vim.keymap.set("n", "<Leader>f", ":FzfLua files<CR>")
			vim.keymap.set("n", "<Leader>l", ":FzfLua blines<CR>")
			vim.keymap.set("n", "<Leader>rg", ":FzfLua live_grep_resume<CR>")
			vim.keymap.set("n", "<Space>s", ":FzfLua lsp_document_symbols<CR>")
			vim.keymap.set("n", "<Space>d", ":FzfLua lsp_definitions<CR>")
			vim.keymap.set("n", "gd", ":FzfLua lsp_definitions<CR>")
			vim.keymap.set("n", "<Space>r", ":FzfLua lsp_references<CR>")
			vim.keymap.set("n", "gr", ":FzfLua lsp_references<CR>")
			vim.keymap.set("n", "<Space>i", ":FzfLua lsp_implementations<CR>")
			vim.keymap.set("n", "gi", ":FzfLua lsp_implementations<CR>")
			vim.keymap.set("n", "<Space>ca", ":FzfLua lsp_code_actions<CR>")
```
</details>

### Description 

Disable preview for lsp code action if can not show

<img width="1382" alt="image" src="https://github.com/ibhagwan/fzf-lua/assets/5424272/47acb37e-cd25-42cb-a036-0b0b6aa65480">

**Comment by ibhagwan** [comment]
This can be per-item, once code action can have a preview while others (for the same code location) won’t, disabling code action just for these items would be confusing.

if you wish to disable the previewed altogether set it to false either in setup or `:FzfLua lsp_code_actions prefiewer=false`.

**Comment by haunt98** [comment]
Thanks @ibhagwan , I think the correct one is `previewer=false`. And it works!

**Comment by ibhagwan** [comment]
> Thanks @ibhagwan , I think the correct one is `previewer=false`. And it works!

Correct, sorry for the typo :)
