### ISSUE TITLE
Feature request: `:Lines` equivalent

### ISSUE THREAD

**Issue by Grazfather** [ibhagwan/fzf-lua#97]
This is similar to `:BLines`, but instead of filtering over the lines of the current buffer it searches over lines of _all_ open buffers.

**Comment by ibhagwan** [comment]
I know it’s not exactly the same but wouldn’t  a combination of `grep/live_ grep` basically already a solution for this?

I’m trying to understand the use case where this would be needed and have an advantage over a other already existing options, I can understand that when it comes to `blines` not so much for all open buffers, seems a bit messy and unintuitive to understand when searching all lines of all buffers.

**Comment by Grazfather** [comment]
Say you're in a flat repo with 1000 files with 10 open.

`blines` only searches the current buffer. `live_grep` searches 1000. I know what I am looking for is in ONE of the buffers I've opened.

**Comment by ibhagwan** [comment]
```vim
:FzfLua lines
```

**Comment by Grazfather** [comment]
Awesome! Thank you :)

**Comment by ibhagwan** [comment]
You're welcome :-)

**Comment by ibhagwan** [comment]
FYI, quick update, `lines|blines` now show file icons by default, to disable use (can also be configured in setup):

```vim
: FzfLua lines file_icons=false
```
