### ISSUE TITLE
【Question or Suggestion】 Regarding Whitespace Stripping

### ISSUE THREAD

**Issue by RsrnlWysxr** [ibhagwan/fzf-lua#971]
### Description 

This is a question or suggestion (in case the feature isn't available yet), rather than a troubleshooting issue.

fzf-lua is an amazing plugin, but I have a minor functionality question. Since I work with indentation-based programming languages like Python, there are many whitespace characters at the beginning of each line. How can I strip off these space characters? I couldn't find any configuration options for this.

![image](https://github.com/ibhagwan/fzf-lua/assets/41769433/8369a81a-1e13-42b4-9294-70be14ef7d71)

**Comment by ibhagwan** [comment]
Do you have `rg` installed?

If so you can remove these by adding `--trim` to the command (or `rg_opts`), from `man rg`:
```
   --trim
       When set, all ASCII whitespace at the beginning of each line
       printed will be trimmed.
```

Try it out with:
```lua
:lua require("fzf-lua").live_grep({ cmd = "rg --line-number --column --color=always --trim" })
```

If you wish to set this up permanently with the default options, call `setup` with:
```lua
require("fzf-lua").setup({
  grep = {
    rg_opts = "--column --line-number --no-heading --color=always --smart-case --max-columns=4096 --trim -e",
  },
  -- your other options
})
```

**Comment by RsrnlWysxr** [comment]
This is fantastic, it works perfectly, thank you so much! @ibhagwan

**Comment by ibhagwan** [comment]
> This is fantastic, it works perfectly, thank you so much! @ibhagwan

You’re welcome @RsrnlWysxr!

**Comment by tssm** [comment]
Hey @ibhagwan, is it possible to make this work for live grep? It seems to ignore the `rg_opts`

**Comment by ibhagwan** [comment]
> Hey @ibhagwan, is it possible to make this work for live grep? It seems to ignore the `rg_opts`

Both grep and live grep use the same `rg_opts`, if it’s not working for you the issue is somewhere else.
