### ISSUE TITLE
[question] How to keep the cursor position of search target when scrolling previewer?

### ISSUE THREAD

**Issue by hexh250786313** [ibhagwan/fzf-lua#972]
This issue isn't related to any bug. I am quite interested in how the fzf-lua previewer maintains the cursor position while the window is scrolling, even if the search target has scrolled out of view.

Could you please point out the specific code that implements this feature?

https://github.com/ibhagwan/fzf-lua/assets/26080416/5953f1ca-011e-4d33-90b0-140a4fdd6c42

**Comment by ibhagwan** [comment]
First,I apologize @hexh250786313 for not replying to your old issue question earlier, the email notification became read I had a feeling I missed something and as soon as I saw this I remembered what it was :)

https://github.com/ibhagwan/fzf-lua/issues/224#issuecomment-1871206252


> how the fzf-lua previewer maintains the cursor position while the window is scrolling, even if the search target has scrolled out of view.

Now as for this, the scrolling code is quite simple, it sends ctrl-d/u to scroll and then checks if the cursor line (the line of interest usually) is “out of bounds” and toggles `cursorline` on/off:
https://github.com/ibhagwan/fzf-lua/blob/9a4ee4a3a0a302a4925b5348863d94d866efb65e/lua/fzf-lua/previewer/builtin.lua#L329-L384

**Comment by hexh250786313** [comment]
Thanks a lot for your super fast response!

Maybe addressing a specific issue can help others who are interested in it.

**Comment by ibhagwan** [comment]
> Thanks a lot for your super fast response!
> 
> Maybe addressing a specific issue can help others who are interested in it.

Does that answer you question or do you need more to respond to something else more specific in #224?

**Comment by hexh250786313** [comment]
> 
> https://github.com/ibhagwan/fzf-lua/blob/9a4ee4a3a0a302a4925b5348863d94d866efb65e/lua/fzf-lua/previewer/builtin.lua#L329-L384

That's exactly what I need. I'm not very proficient in Lua, so reading the source code is somewhat challenging for me. I've tried seeking help from GPT, but it can't offer any help :<

Anyway, thanks a lot.

**Comment by ibhagwan** [comment]
Lua is very simple you’ll get used to it, if you have any specific questions about why something is done a certain way in the code feel free to ask here and I’ll do my best to explain.
