### ISSUE TITLE
simple way to remap split action to ctrl-x

### ISSUE THREAD

**Issue by asknet** [ibhagwan/fzf-lua#978]
### Info

- Operating System: Macos
- Shell: zsh
- Terminal: iTerm2
- `nvim --version`: v0.9.1
- `fzf --version`: 0.42.0

### Description

Thank you for the awesome plugin!

for some reason, neovim doesn't receive ctrl-s from iTerm2. I tried solutions from the internet and nothing worked so far. I like to remap split action from ctrl-s to ctrl-x. Based on my understanding, I need to duplicate the complete default options and edit the mapping for split action. 

I'm wondering if there is a better way to not duplicate the default option and keep all defaults except this mapping.

**Comment by ibhagwan** [comment]
> I'm wondering if there is a better way to not duplicate the default option and keep all defaults except this mapping.

Unfortunately you need to duplicate the defaults in `actions.files|buffers` (although you can copy from defaults directly and merge) - this was done on purpose, the other side of the coin was “how do I change the bindings without having to set the default action I wish to override to `false`”.

Given bindings are very personal and many users change the defaults it made more sense to do it this way.

**Comment by ibhagwan** [comment]
You can always copy the defaults if you wish but you’ll have to disable the current bind by setting it to `false`:
```lua
require('fzf-lua').setup({
  actions = vim.tbl_deep_extend({'force', require('fzf-lua.defaults').actions, {
    files = { ['ctrl-x'] = false, ['ctrl-s'] = … },
    buffers = { ['ctrl-x'] = false, ['ctrl-s'] = … },
  },
})
```

**Comment by ibhagwan** [comment]
Closing, feel free to reopen if this doesn’t answer you question or if you have a creative idea how to satisfy both use cases without sacrificing anything.

**Comment by asknet** [comment]
Thank you!
