### ISSUE TITLE
Add an option to add spaces for double width file icons

### ISSUE THREAD

**Issue by EdwarKenedy** [ibhagwan/fzf-lua#98]
Hi, I would like to see this option implemented, I use kitty terminal which can render double width icons when they have extra space.

Current behavior
![image](https://user-images.githubusercontent.com/36998912/132097409-d369f5c2-f838-401f-b810-b5e56c1c6a19.png)

Expected behavior 
![image](https://user-images.githubusercontent.com/36998912/132097427-8f1650d5-ba31-41b6-a533-2c06134d5fe6.png)

**Comment by ibhagwan** [comment]
Does this happen automatically with kitty or is there an option you have to enable in the config?

Can you open a new neovim term (`:term`) and the run the below and let me know the result?

```lua
:lua print(vim.env.TERM)
```

**Comment by EdwarKenedy** [comment]
yes, Kitty does this automatically [(see docs)](https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty)
```lua
:lua print(vim.env.TERM)
-- reuslt: xterm-kitty
```

**Comment by ibhagwan** [comment]
I want to solve this the right way but I can't seem to reproduce it, I created the same file extension as you have in your example and I'm not getting this error, do you have overrides for the default icons of `nvim-web-devicons`?

![screenshot-1630793416](https://user-images.githubusercontent.com/59988195/132109199-ae39f601-9d35-49a2-bcd2-a3ec1623be65.png)

**Comment by EdwarKenedy** [comment]
I modified the source code of fzf-lua to get the expected behavioral image, it seems that the actual behavioral image only occurs because I have the font set to bold when the fzf cursor appends to the filename

**Comment by ibhagwan** [comment]
> I modified the source code of fzf-lua to get the expected behavioral image, it seems that the actual behavioral image only occurs because I have the font set to bold when the fzf cursor appends to the filename

Can you let me know what code changes did you make to achieve that?

Also, if this required a code change to break, what is the user case we're trying to solve here?

**Comment by EdwarKenedy** [comment]
I have only concatenated an extra space to [core.lua](https://github.com/ibhagwan/fzf-lua/blob/cc7828d4d22924de329577232cae2d3d9f857ec2/lua/fzf-lua/core.lua#L164)
```lua
icon = M.get_devicon(x, ext)..' '
```
the user case could be to support double-width icons in the kitty terminal, to make the icons more readable

**Comment by ibhagwan** [comment]
> I have only concatenated an extra space to [core.lua](https://github.com/ibhagwan/fzf-lua/blob/cc7828d4d22924de329577232cae2d3d9f857ec2/lua/fzf-lua/core.lua#L164)
> 
> ```lua
> icon = M.get_devicon(x, ext)..' '
> ```
> 
> the user case could be to support double-width icons in the kitty terminal, to make the icons more readable

But when will this actually happen? The code can only get icons from `nvim-web-devicons` so I don't see how this will happen without code intervention?

**Comment by EdwarKenedy** [comment]
sorry, that was a quick fix, I will create a pull request in which I will implement my solution.
