### ISSUE TITLE
lsp_definitions with jump_to_single_result doesn't work

### ISSUE THREAD

**Issue by kapral18** [ibhagwan/fzf-lua#980]
### Info

- Operating System: MacOS Sonoma 14.2.1
- Shell: fish
- Terminal: iterm2
- `nvim --version`: v0.10.0-dev-2016+g5dc0bdfe9
- `fzf --version`: 0.45.0

### Description 

For example if I try to jump to definiton of `running_procs_by_buf` from this line https://github.com/mfussenegger/nvim-lint/blob/4dbc7ec60b33b656f7c54bb945671a55b18699f2/lua/lint.lua#L198C5-L198C5

Without `jump_to_single_result` it properly jumps to the definition after selecting the item in picker, but with `jump_to_single_result` it just stays in place

my config: https://github.com/kapral18/config.nvim/blob/dee5f388194a315bfbf7d8587b7d3ce8de9dbe60/lua/plugins/fzf.lua

**Comment by ibhagwan** [comment]
@kapral18, https://github.com/ibhagwan/fzf-lua/commit/69a51aeffa4aee602b7825fd36421b2e33678ced - should work as expected now.

**Comment by kapral18** [comment]
you are the best, thank you!

**Comment by ibhagwan** [comment]
> @ibhagwan you are the best, thank you!

Ty for pointing out the exact location where this happens @kapral18, saved me some time figuring out what happened there :)

**Comment by kapral18** [comment]
@ibhagwan of course my pleasure

but unfortunatley I have another one connected to this now I keep getting this notification that no definitions were found

![CleanShot 2024-01-02 at 23 23 14](https://github.com/ibhagwan/fzf-lua/assets/1625373/0dba738d-c2e0-4cba-bf57-e36d4502e4b5)

**Comment by ibhagwan** [comment]
> I keep getting this notification that no definitions were found

I just tried at the exact same code location your cursor is placed in the screenshot, can you let me know better how to reproduce this? Does this happen all the time or after a while? At what exact location?

**Comment by ibhagwan** [comment]
Also can you try running `:FzfLua lsp_definitions cwd_only=false` and lmk if that works?

**Comment by ibhagwan** [comment]
@kapral18, try https://github.com/ibhagwan/fzf-lua/commit/f4f3671ebc89dd25a583a871db07529a3eff8b64 - should work this time around, the message was errornous, it was still performing the jump.

**Comment by kapral18** [comment]
@ibhagwan yes that's the fix. Thank you again!

**Comment by kapral18** [comment]
@ibhagwan I got another one for you

this time calling vim.lsp.buf.definition() works but calling fzflua lsp_definitions doesn't regardless jump_to_single_result or not.

To reproduce you can just have a index.js file with:

```js
const restrictedGlobals = require("confusing-browser-globals");
```

And try lsp_definitions on `confusing-browser-globals` it says no definitions found but native lsp definition works and navigates me correctly to the source

**Comment by kapral18** [comment]
also within node_modules folder most symbols are not being resolved at all by `lsp_definitions` for whatever reason

**Comment by ibhagwan** [comment]
@kapral18, the node modules issue is probably due to `cwd_only=true`, the definition is. OST likely outside the project working directory and by setting this limit you’re excluding the node modules defs.

**Comment by kapral18** [comment]
@ibhagwan yes I removed once I realized but thanks nevertheless

**Comment by ibhagwan** [comment]
> @ibhagwan yes I removed once I realized but thanks nevertheless

Sorry I responded from mobile as I saw the notification I didn’t realize it was removed :)
