### ISSUE TITLE
Is it possible to make .registers support in command line edit mode?

### ISSUE THREAD

**Issue by towry** [ibhagwan/fzf-lua#984]

**Comment by ibhagwan** [comment]
Unfortunately there are issues with windows management that prevent this from being supported, I'm not sure why but certain commands err with `E11` (see `:help E11`) therefore the interface is disabled from command line mode, btw, Telescope does the same.

**Comment by towry** [comment]
Yes, registers.nvim doesn't support it too. maybe cmp-registers is good choice in command line mode.
