### ISSUE TITLE
[Feature] Non-blocking processing of language server results

### ISSUE THREAD

**Issue by asmodeus812** [ibhagwan/fzf-lua#985]
This is more of a discussion issue but it affects fzf-lua too, since the bulk of the work here is not relying on the built in client to call a handler, rather the call to the server, and handing of the response is entirely done in fzf-lua, here is a suggestion, which we might want to consider - https://github.com/neovim/neovim/issues/26924

**Comment by ibhagwan** [comment]
Ty for linking @asmodeus812, I will look into it.

At first glance we already work around this by using `async=true` for the LSP calls (for example, it's the default for symbols), the LSP call is async and is non-blocking using `vim.lsp.buf_request` with a callback.

**Comment by asmodeus812** [comment]
@ibhagwan It is indeed the processing of the data that this is related to.

**Comment by ibhagwan** [comment]
> @ibhagwan It is indeed the processing of the data that this is related to, not the calls
> 
> One thing to note, while with the default nvim config without fzf when i call references, while the response comes in i am not being blocked and can still move around, when it comes in to populate the qf list then it blocks. However with fzf-lua, once i trigger lsp_references, everything locks up until the fzf window with the results is shown. So there is that difference.

The default for references/definitions is synchronous, in this case it will indeed block until the response from the LSP arrives and is processed, if your LSP is slow use `async=true` for non-blocking.

**Comment by asmodeus812** [comment]
What is async=true ? All async properties i can see in fzf-lua are by default true already.

**Comment by ibhagwan** [comment]
As I mentioned it’s false for all LSP commands aside symbols (this is the query timeout):
https://github.com/ibhagwan/fzf-lua/blob/d4eb38625d22c48512ce8590a6248736ffc067a1/lua/fzf-lua/defaults.lua#L599

LSP symbols:
https://github.com/ibhagwan/fzf-lua/blob/d4eb38625d22c48512ce8590a6248736ffc067a1/lua/fzf-lua/defaults.lua#L641


You can either change `lsp.async_or_timeout = true` or add ‘async = true`, you can also run directly:
```
:FzfLua lsp_references async=true
```

**Comment by ibhagwan** [comment]
> but the picker is immediately opened, without any results, and while for them we can't do anything even though the editor is NOT blocked. Maybe open the picker after we get some results / response at the very least.

That’s not a bad idea but it would require some additional logic for cancellation, status indicator, etc - I’ll have to think about how to do it, this would require a refactor of the LSP code probably.
