### ISSUE TITLE
Unable to open preview for custom map

### ISSUE THREAD

**Issue by asknet** [ibhagwan/fzf-lua#989]
### Info

- Operating System: macos
- Shell: zsh
- Terminal: iterm2
- `nvim --version`: 0.9.1
- `fzf --version`:

### Description 

In my init.lua i disable previewer by default, by setting like below
```lua
fzf.setup({
    preview_opts = 'hidden',
    fzf_opts = { ["--layout"] = "default" },
})

```

Now for some custom maps, I want to enable preview and I tried below both options, but it's not working. Appreciate your time and help on this. 

```lua
lua require('fzf-lua').grep_cword({ preview_opts = true, winopts = { preview = { vertical = 'right', hidden = 'nohidden' }}} )
```

```lua
lua require('fzf-lua').grep_cword({ previewer = true, winopts = { preview = { vertical = 'right', hidden = 'nohidden' }}} )
```

**Comment by ibhagwan** [comment]
I haven’t tested, but it’s probably because you’re using an old backward compatible option that takes precedence over your overrides, change your setup to:
```lua
fzf.setup({
    winopts = { preview = { hidden = 'hidden' }},
    fzf_opts = { ["--layout"] = "default" },
})
```

Do this and your overrides will work as expected.

**Comment by ibhagwan** [comment]
Btw I also created a shortened version for vimscript where you can set the key with one string, for example to enable preview (with the setup I provided above):
```vim
:FzfLua grep_cword winopts.preview=nohidden
```

**Comment by asknet** [comment]
Thank you for quick response @ibhagwan 
After fixing `preview_opts` it's working. You are awesome!

**Comment by ibhagwan** [comment]
> Thank you for quick response @ibhagwan After fixing `preview_opts` it's working. You are awesome!

Ty for the kind words @asknet!
