### ISSUE TITLE
preview not working since last commit

### ISSUE THREAD

**Issue by mosheavni** [ibhagwan/fzf-lua#992]
### Info

- Operating System: macOS 14.2.1 (23C71)
- Shell: zsh
- Terminal: iterm2
- `nvim --version`: 
  ```
NVIM v0.10.0-dev-2051+gee3d4f6b9
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
- `fzf --version`: 0.44.1 (brew)

<!--
Check if your problem is reproducible with minimal init, by running:

sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"

For more minimal init testing options see:
https://github.com/ibhagwan/fzf-lua/wiki#minimal-init

Change '[ ]' to '[x]' below if the issue is reproducible.
-->
- [X] The issue is reproducible with `mini.sh`

### Description 

Preview is not working since commit ada262b4235c86a4365eb49d51e4f7616c8f7da5
Both on my setup and on `mini.sh`

![2024-01-09_10-37-32 (1)](https://github.com/ibhagwan/fzf-lua/assets/17252601/99098871-1f28-4936-8208-ff54a277e9a9)

**Comment by ibhagwan** [comment]
I apologize @mosheavni, should’ve tested PR #991 better before approving the merge.

@wookayin, turns out it did break something :)

**Comment by mosheavni** [comment]
> I apologize @mosheavni, should’ve tested PR #991 better before approving the merge.
> 
> @wookayin, turns out it did break something :)

I can confirm it's fixed now. thanks!!!

**Comment by ibhagwan** [comment]
> > I apologize @mosheavni, should’ve tested PR #991 better before approving the merge.
> > @wookayin, turns out it did break something :)
> 
> I can confirm it's fixed now. thanks!!!

Ty @mosheavni, just force pushed a slightly safer fix with a more pronounced condition, so make sure to update again (pull rebase if needed).

**Comment by wookayin** [comment]
Sorry about the inconvenience, I wasn't aware of `M.shell_error()`... You merged it too fast without testing it together :P 

Hmm but looking at the fix done here, it looks like that some part of the code (preview) relies on the global state `vim.v.shell_error` or `M.shell_error()` which is not ideal and should be refactored?

**Comment by ibhagwan** [comment]
> Sorry about the inconvenience, I missed `M.shell_error()`... You merged it too fast without testing it together :P but it's my bad.

All good, I’m usually very keen on the testing but it was the middle of the night and it seems inconspicuous :)



> Hmm but looking at the fix done here, it looks like that some part of the code (preview) relies on the global state `vim.v.shell_error` or `M.shell_error()` which is not ideal and should be refactored?

Yes, definitely, I thought about that as well but I just wanted to make a quick fix for the issue at that moment.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/cc47997ebeb87e0caa9ab6fd8039427c1f6930ee

@wookayin - this removes `utils.shell_error` altogether, no more calling `vim.fn.system` directly and only check the `rc` from the call to utils to determine success/failure.
