### ISSUE TITLE
Control number of preview window scrolling steps

### ISSUE THREAD

**Issue by mortezadadgar** [ibhagwan/fzf-lua#994]
Hey,
currently fzf preview scrolls around 30 steps which is too much sometimes I briefly looked at the source code and documentations and didn't find a way.

**Comment by ibhagwan** [comment]
The preview scroll sends ctrl-d/u to the preview, it’s not configurable by fzf-lua. Maybe there is a way to change that but  it would be global.

**Comment by mortezadadgar** [comment]
Yeah but there seems to be no way to even change the scrolling behavior globally.
