### ISSUE TITLE
How could I enhance query/search with keybinding action?

### ISSUE THREAD

**Issue by daliusd** [ibhagwan/fzf-lua#995]
I came up with this way where I can click ctrl-g to narrow results to JS/TS files. This is working and is better than nothing, but it has bunch of side effects:

* it is flashing

* it somehow remembers what was entered before, even if I delete manually something

```lua
      require("fzf-lua").setup({
        grep = {
          actions = {
            ["ctrl-g"] = function (_, opts)
              local text = opts.search .. " -- *.js *.jsx *.ts *.tsx"
              require("fzf-lua").live_grep_glob({ search = text, no_esc = true })
            end,
          },
        }
      })

```

**Comment by ibhagwan** [comment]
Wrap the action with {} to prevent flashing and use get last query for the typed query:
```lua
          actions = {
            ["ctrl-g"] = { function (_, opts)
              local text = require("fzf-lua").get_last_query() .. " -- *.js *.jsx *.ts *.tsx"
              require("fzf-lua").live_grep_glob({ search = text, no_esc = true })
            end } ,
          },
```

**Comment by daliusd** [comment]
Thanks, this did the magic. I would document it somewhere, but I am not sure what would be the best place.

```
            ["ctrl-g"] = { function()
              local text = require("fzf-lua").get_last_query() .. " -- *.js *.jsx *.ts *.tsx"
              require("fzf-lua").live_grep_glob({ search = text, no_esc = true })
            end },
```

**Comment by ibhagwan** [comment]
Pretty sure the wiki has this mentioned somewhere.

**Comment by daliusd** [comment]
Feel free to add text below to Home wiki (I don't have rights and no idea how to create PR for Wiki). I read the whole wiki and README before posting this issue. I am closing this issue as it is solved for me.

BTW, thanks for amazing plugin. 

```md
[How do I write custom action?](#custom-keybind-actions)



### <a id="custom-keybind-actions">How do I write custom action?</a>

You can write your own action as well. You need to pass function to keybind.
That function receives `selected` items and options `opts` that were used. E.g.:

```lua
["ctrl-s"] = function(selected, opts)
  local idx = get_idx(selected[1])
  print("ctrl-s", contents[idx].data, opts.query)
end
```

Let's say you need keybind that limits your results to Javascript/Typescript files:

```lua
require("fzf-lua").setup({
  grep = {
    actions = {
      ["ctrl-g"] = { function()
        local text = require("fzf-lua").get_last_query() .. " -- *.js *.jsx *.ts *.tsx"
        require("fzf-lua").live_grep_glob({ search = text, no_esc = true })
      end },
    },
  }
})
```

**Comment by ibhagwan** [comment]
Ty @daliusd, there is always improvement to be had with the Wiki, there are no rights needed to edit the Wiki it’s open for everyone :)

Ty for writing, I’ll think where it fits best whether live grep section or advanced actions:
https://github.com/ibhagwan/fzf-lua/wiki/Advanced#keybind-handlers
