### ISSUE TITLE
Cannot override actions.files["ctrl-g"] (actions.toggle_ignore)

### ISSUE THREAD

**Issue by lbrayner** [ibhagwan/fzf-lua#996]
### Info

- Operating System: Ubuntu 22.04
- Shell: zsh
- Terminal: foot
- `nvim --version`: NVIM v0.10.0-dev
- `fzf --version`: 0.45.0 (202401011)

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
local actions = require("fzf-lua.actions")

require("fzf-lua").setup({
  -- These override the default tables completely
  -- no need to set to `false` to disable an action
  -- delete or modify is sufficient
  actions = {
    files = {
      ["default"]     = actions.file_edit_or_qf,
      ["ctrl-s"]      = actions.file_split,
      ["alt-s"]       = actions.file_vsplit,
      ["ctrl-t"]      = actions.file_tabedit,
      ["alt-q"]       = actions.file_sel_to_qf,
      ["alt-l"]       = actions.file_sel_to_ll,
    },
  },
})
```
</details>

### Description 

By setting `actions.files`, I expect to "... override the default tables completely", but `ctrl-g` is still mapped to `actions.toggle_ignore`.

**Comment by ibhagwan** [comment]
> By setting actions.files, I expect to "... override the default tables completely", but ctrl-g is still mapped to actions.toggle_ignore.

`actions.files` refers to all pickers that deal with files which also includes grep, etc.

Toggle ignore action is defined specifically for files, so you’d need to override it there, which also makes it easier as you don’t need to define the other actions:
```lua
require("fzf-lua").setup({
  files = { actions = { ["ctrl-g"] = false } },
})
```

**Comment by ibhagwan** [comment]
Here’s the definition in the defaults and the reason it wasn’t being overridden in your setup, as you can see below it’s configured directly for `files`:
https://github.com/ibhagwan/fzf-lua/blob/2cd8e0c32fcdad48d8d56120c559d15a10affb3f/lua/fzf-lua/defaults.lua#L212-L230

**Comment by lbrayner** [comment]
Thanks, @ibhagwan,  that clears it up!
