### ISSUE TITLE
[BUG] option passed to `ui_select()` ignored when source is code actions

### ISSUE THREAD

**Issue by Bekaboo** [ibhagwan/fzf-lua#999]
### Info

- Operating System: `Linux xps-13-7390 6.6.10-arch1-1`
- Shell: `fish`
- Terminal: `alacritty 0.13.1 (fe2a3c56)` + `tmux 3.3a`
- `nvim --version`: `NVIM v0.10.0-dev-2074+g786089013d`
- `fzf --version`: `0.44.1 (29e67d30)`

- [ ] The issue is reproducible with `mini.sh`

<details>
<summary>fzf-lua configuration</summary>

```lua
local fzf = require('fzf-lua')
fzf.setup({
  winopts = {
    split = 'botright 12new',
  },
})

local fzf_ui = require('fzf-lua.providers.ui_select')
fzf_ui.register(function(_, items)
  return {
    winopts = {
      split = string.format('botright %dnew', math.min(10, #items + 1)),
    },
  }
end)
```
</details>

### Description 

According to #755, the ui_select provider's `register()` function can accept a callback function to change options dynamically according to the context, I use it to change the fzf window heihgt when different number of candicates are given to `vim.ui.select()` and it works pretty well:

- when using other "normal" providers, e.g. files, use 12 rows as configured in the `setup()` function:

    ![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/86f5eb06-ee87-4f4b-81f8-e7e6797c8123)

- ui select, 6 candidates provided, only use 7 rows as configured in the ui_select `register()` function callback:

    ![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/cedb18a8-7638-4543-997b-ccbce24f9056)

- however, when it comes to code actions, my configure for ui select is ignored, here we only have 4 candidates but still fzf uses 12 rows:

    ![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/ad636154-c83f-4b01-9e94-50a74b861ef6)

**Comment by ibhagwan** [comment]
This isn’t a bug, with code actions the options are inherited from `lsp.code_actions`:
https://github.com/ibhagwan/fzf-lua/blob/faf850e03555512960b5ed1cb1fa50de6f586644/lua/fzf-lua/providers/ui_select.lua#L132-L134

If you wish to override these you need to setup `lsp.code_actions`:
https://github.com/ibhagwan/fzf-lua/blob/faf850e03555512960b5ed1cb1fa50de6f586644/lua/fzf-lua/defaults.lua#L704-L709

**Comment by Bekaboo** [comment]
Hi thanks for your quick response, it there a way I can make the behavior more consistent i.e. make code actions respect the ui select options?

> This isn’t a bug, with code actions the options are inherited from lsp.code_actions

Does it mean that when it comes to code actions fzf does not respect the general options for ui select? I am a bit confused. Why should ui select be different from other cases? Thanks!

**Comment by ibhagwan** [comment]
> Does it mean that when it comes to code actions fzf does not respect the general options for ui select? I am a bit confused. Why should code actions be different from other cases? Thanks!

This goes both ways, most people don’t get as deep as customizing to this level and expect code actions to respect their setup settings.

**Comment by Bekaboo** [comment]
Here's what I thought: I registered fzf ui_select provider as `vim.ui.select()`, so any other modules calling this function can use fzf lua as an interface... it works great in all cases except for code actions. I assume nvim's LSP client will call `vim.ui.select()` in the code actions handler? So the code path should be the same, but why the height configuration is ignored? I am so confused 🤔

**Comment by Bekaboo** [comment]
I see, thanks. Do you think this can be made more consistent or we should just keep what it is right now?

**Comment by ibhagwan** [comment]
> I see, thanks. Do you think this can be made more consistent or we should just keep what it is right now?

I'll add an option so both use cases can be satisfied

**Comment by Bekaboo** [comment]
Thanks, this can be closed now.

**Comment by ibhagwan** [comment]
We can close it once we sort this out properly, note that by doing so you'd lose the code action previewer (which was one of the main reasons I decided on inheriting from defaults).

**Comment by Bekaboo** [comment]
https://github.com/ibhagwan/fzf-lua/blob/faf850e03555512960b5ed1cb1fa50de6f586644/lua/fzf-lua/providers/ui_select.lua#L142

Will it work if we simply change "keep" to "force" in this line?

If no `opts` for ui select is passed in -- then good we are using the opts from the setup function, it there is `opts` for ui select then it takes precedence to opts in the setup function, in this case the user opt-in to apply the config for ui select so it should not be breaking.

**Comment by ibhagwan** [comment]
> https://github.com/ibhagwan/fzf-lua/blob/faf850e03555512960b5ed1cb1fa50de6f586644/lua/fzf-lua/providers/ui_select.lua#L142
> 
> Will it work if we simply change "keep" to "force" in this line?
> 
> If no `opts` for ui select is passed in -- then good we are using the opts from the setup function, if there is `opts` for ui select then it takes precedence, in this case the user opt-in to apply the config for ui select so the change should not be breaking.

I’ll do some testing when I’m not AFK and I think this could be a good solution without introducing yet another config option.

**Comment by ibhagwan** [comment]
@Bekaboo, try https://github.com/ibhagwan/fzf-lua/commit/3d526d24436312cf4e05fbd27452ab2d0ef383cc - it keeps the behavior as is when running `:FzfLua lsp_code_actions` but overrides the options with `force` as you suggested **only when using `vim.lsp.buf.code_action()` directly.

I believe this is a good compromise as users running `lsp_code_actions` expect their options to be fully respected.

**Comment by Bekaboo** [comment]
It works pretty well!

![image](https://github.com/ibhagwan/fzf-lua/assets/76579810/5b981020-edcc-4d9c-b69c-2474110a5b89)

**Comment by ibhagwan** [comment]
> It works pretty well!

Very nice @Bekaboo! Closing.
